### ISSUE TITLE
[bug] Baldur's gate 1 (GOG version) battle weapon effect won't play

### ISSUE THREAD

**Issue by tomudo** [gemrb/gemrb#100]
**Describe the bug**
Baldur's gate 1 (GOG version) battle weapon effect won't play. I tried serveral weapon such as staff, dagger, sword, bow but no clash, bang, wiff,etc. sound effect

GemRB version: 0.85

**To Reproduce**
Battle with enemies.

**Expected behavior**
Have weapon sound effect like original.

**Comment by lynxlynxlynx** [comment]
Thanks for the report!

This is related to #92 , but there's no need to wait for that — we can play it each hit. Do you know if there's any sound on a miss?

**Comment by lynxlynxlynx** [comment]
I'm also curious how you found this bug tracker? I opened it just a few hours ago. :)

**Comment by tomudo** [comment]
> 
> 
> I'm also curious how you found this bug tracker? I opened it just a few hours ago to start moving stuff from the wiki one. :)

Just a pure coincident. I'm compiling gemrb from git and found some bugs.

**Comment by lynxlynxlynx** [comment]
Ok, closing this in favour of the other bug, where the missing swooshes are tracked.
