### ISSUE TITLE
[subviews] PST PCs moonwalking

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1000]
#### Bug description
When you try to run in PST, it looks kind of funny, unfortunately that's not the correct speed. Not sure if related to #129 since I see most of the changes in subviews, so maybe something merge related?

#### Steps to reproduce
1. Run in PST.

#### Screenshots
![pst_walk](https://user-images.githubusercontent.com/238558/96369618-69d20600-115b-11eb-9b92-377323609bb4.gif)

**Comment by lynxlynxlynx** [comment]
PST ships with unhardcoded speed, so that's not it. Looks like walking speed there, so perhaps the little speed setting refactoring got mismerged. I'll take a look.
