### ISSUE TITLE
[IWD1] kresselak slow animation 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1002]
#### Bug description
In chapter 1 of IWD1 (ar3503 [350.626]) Kresselak animation is slow compared to original as if frame rate was too low but no : 30 fps

For original : https://www.youtube.com/watch?v=XOGbnz32ldE
I can provide a video or save if needed

GemRB version: master

#### Expected behavior
Same speed as original and more important no low frame rate impression

#### Screenshots
![image](https://user-images.githubusercontent.com/55502325/96371287-3befc000-1161-11eb-82a3-82e22f2e7e05.png)

**Comment by lynxlynxlynx** [comment]
He's using this animation:
0x2300     MDKN

I hope it wasn't hardcoded.
