### ISSUE TITLE
[subviews] save games won't list if there are too few

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1005]
I can no longer see my save games. assuming something wrong with the last merge from master
Oddly, if I put my BG2 save path it will list my BG2 saves. Both directories are identical in name so I really don't understand what is the cause.

**Comment by chilvence** [comment]
Do you have less than 5 saves by any chance?

**Comment by bradallred** [comment]
yes... I have 4

**Comment by chilvence** [comment]
For some odd reason, I have exactly the same issue in any game where I don't have at least 5 saves, the list does not get populated at all

**Comment by bradallred** [comment]
must have something to do with the fact that there are only 4 slots... somehow

**Comment by chilvence** [comment]
It actually doesn't happen in PST I just noticed, I will try and compare

**Comment by chilvence** [comment]
If this line comes up with a result of TopIndex=0, then there are no games displayed

https://github.com/gemrb/gemrb/blob/7c99068211e78f5a4e321f919c6df199c9e5775f/gemrb/GUIScripts/GUILOAD.py#L79

**Comment by chilvence** [comment]
Does this seem ok? https://github.com/chilvence/gemrb/commit/a7b02bb055a2f14fa6ef27ec2fb22fb551d47b43

**Comment by lynxlynxlynx** [comment]
Yes, does it fix it?

**Comment by chilvence** [comment]
Well, it correctly starts with the first Autosave now, also when there are more than 4 saves 
![save 1](https://user-images.githubusercontent.com/1923867/96598964-518ef200-12e7-11eb-9b7d-0784aab7900d.png)

**Comment by lynxlynxlynx** [comment]
Is that a yes?

**Comment by chilvence** [comment]
Yes :) 

Sorry, it just seemed a bit too easy, that never happens usually

**Comment by lynxlynxlynx** [comment]
Cool, you know what to do. 👍🏾
