### ISSUE TITLE
PST Day/Night tint does not work 

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#1007]
I didn't actually notice this until I looked at of @MarcelHB 's saves from another issue - I can't remember which one so I will attach it again:

[000000001-Marcel-Jump2.zip](https://github.com/gemrb/gemrb/files/5410139/000000001-Marcel-Jump2.zip)

If you look at the game screenshot, it appears it is supposed to be dark, but when you actually load the game, the appearance is mid-day

iesdp says that PST has different area type flags, https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm , so I thought I would try starting with that, but I can't seem to get any tint to apply at all, even when forcing one in Game::GetGlobalTint here: https://github.com/gemrb/gemrb/blob/d8dc825717fa0b370863c719c4bac4feeef804ee/gemrb/core/Game.cpp#L2078

I thought this would be something easy to fix because it already works in the other games, but I guess I am missing something.

**Comment by bradallred** [comment]
is there weather in PST? I know it is possible to save a game in BG2 with rain (so tinted) and the reload it and have no rain or vice versa.

**Comment by chilvence** [comment]
No there's no weather in the original, only the day/night cycle - the only real clue it isn't working is looking at the time reported on the clock

**Comment by lynxlynxlynx** [comment]
So which areas are we talking about?

**Comment by chilvence** [comment]
Any area that could be considered outdoors

**Comment by lynxlynxlynx** [comment]
I doubt it has night WEDs, so you're right that it's probably a tint. I'm pretty sure we don't have any time-based tint yet at all though — these global ones are either from weather, dream, timestop and maybe more.

**Comment by chilvence** [comment]
Hmm... I guess I was fooled because the BG1 games load up with tinting and weather, but you're right they don't seem to change

**Comment by MarcelHB** [comment]
> 
> 
> I doubt it has night WEDs, so you're right that it's probably a tint. I'm pretty sure we don't have any time-based tint yet at all though — these global ones are either from weather, dream, timestop and maybe more.

Isn't that how IWD2 works?

**Comment by lynxlynxlynx** [comment]
Oh, you're right, we do do something. :)

**Comment by chilvence** [comment]
Yay!
