### ISSUE TITLE
IWD2: Oswald not disappearing in AR6000

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1008]
#### Bug description
In IWD2, when chapter ~~6~~5/AR6000 starts, there is a cutscene that make Oswald and Maralie flee back into the ship. Maralie disappears, Oswald runs towards the stairs but remains in existance on this map.

I'm sure this is a regression and it worked until some point in time. Script is:

```
                ...
                Wait(2)
		MoveToPoint([444.1479])
		DestroySelf()
```

GemRB version: current master

#### Steps to reproduce
1. Start IWD2, AR6000

#### Expected behavior
Oswald to disappear.

**Comment by lynxlynxlynx** [comment]
I doubt anyone tried this before, since you can't play that far. Sounds like something overrides his action queue.

**Comment by lynxlynxlynx** [comment]
Also, this requires a save to reproduce, since just teleporting there shows it in the initial state (chapter 3-5?).

**Comment by MarcelHB** [comment]
My bad, chapter 5 it is. Savegame to reproduce, _do not_ engage the thief in the fight while there is #817 open.

[000000000-automatic_chapter5.zip](https://github.com/gemrb/gemrb/files/5411329/000000000-automatic_chapter5.zip)

**Comment by lynxlynxlynx** [comment]
I'll first start by fixing the parsing, I think we only support this crap in script right now:
```
[GameScript/ERROR]: Malformed scripting action: StartCutscene(#53cKulda#)                                                                           
[DLGImporter/WARNING]: Can't compile action: StartCutscene(#53cKulda#)  
```

**Comment by lynxlynxlynx** [comment]
He looses his action and it's not anything related to pathfinding. After he arrives close enough, GameScript::Update calls Stop and that includes clearing the whole action queue (not just the current one), so the DestroySelf never gets to run.

The Stop thing is not really something we should change, so a bit more research is needed on how things come to pass.

**Comment by lynxlynxlynx** [comment]
Avatarremoval-ed actors shouldn't block the searchmap - should fix the girl abandoning the path ... but it actually fixes the bug as well. :)
