### ISSUE TITLE
Some PST Buttons contain double spaces

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1010]
This was brought up in #293 

![](https://user-images.githubusercontent.com/238558/66959506-cee7ad00-f06a-11e9-8eeb-4ee170d70e2f.jpg)

as you can see the button looks odd because it contains a double space. The original seems to collapse contiguous whitespace (or at least spaces). We don't know if this applies to only buttons

There are lots of options to address this and I'm not sure which is best.

1. Add a new flag to GetString
2. handle this in Button::SetText
3. handle it on the Python side

**Comment by lynxlynxlynx** [comment]
I would wipe them already in GetString, without any flags (we can add one if we find a counterexample). Spaces are not used for layouting — both buttons and labels have alignment flags and I don't recall seeing double space in any text.

**Comment by lynxlynxlynx** [comment]
There are plenty of double spaces in the original; `weidu --strfind "  " | wc -l` finds over 37k lines in iwd2 alone. Too much to check if any are labels, but iwd2 definitely doesn't coalesce them in general (visible in the script customization window). So I changed the text and the original didn't coalesce them on buttons or labels either. PST might be different, but I doubt it.

And the string matches, just the first l is cut off, not more, when comparing to a screenshot.

Maybe it's only present when the TLK language is non-English, but that seems arbitrary. @MarcelHB are there more cases where this is broken? Does it still look the same?

**Comment by MarcelHB** [comment]
I still see what's in the screenshot above. Can't say for sure whether there is more since I only noticed it in the PST menu so far.

**Comment by lynxlynxlynx** [comment]
Then let's do it on a needs basis on the python side until a greater need is proven.

**Comment by lynxlynxlynx** [comment]
That should do it, but I'm curious if we still cut of the first L.
