### ISSUE TITLE
[subviews] default event bubbling up too much

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1011]
Start tob chargen and just press enter a few times. You'll get to the gender window and the log will be filled with `[GUIScript]: Loading Script GUICG1.`.

This is because a gender isn't chosen yet, so the done button is disabled. It's marked as the default though and the keypress ends up triggering the default of the main chargen window, which is NextPress, currently attached to the gender entry. So it's not visible in game, but we keep reloading the step in this case.

The expected behaviour is that the enter is eaten up and discarded. I don't know if this hold in general though, but it's easy to fix if not as well — all these cg windows can be marked as modal.

**Comment by bradallred** [comment]
I think the real issue is have a button enabled that shouldn't be.

I'm not so sure you can use modal windows in charge. IIRC charges is actually 2 or 3 windows carefully arranged like a puzzle.

**Comment by lynxlynxlynx** [comment]
It works for gender, you don't need to use the dithered mode.
That button has every right to be enabled; it would lead to all sorts of weird work if we had to reset default buttons per window.

**Comment by bradallred** [comment]
if you used a modal window the candle and import buttons wouldn't work

**Comment by lynxlynxlynx** [comment]
True, but it's the same in the original, those button work only on the overview.

**Comment by bradallred** [comment]
I didn't realize the original did that... still the keys shouldn't leave the focus window and that should be fixed

**Comment by lynxlynxlynx** [comment]
Yep, it works.
