### ISSUE TITLE
Pathfinding not considering diagonals - problem in AR9106 (HoW) / ar1008

### ISSUE THREAD

**Issue by fizzet** [gemrb/gemrb#1015]
#### Bug description
There's a cupboard container at the north end of the house which appears to be unreachable at the moment. It looks like the actors need too much space.

**Comment by lynxlynxlynx** [comment]
For reference:
![image](https://user-images.githubusercontent.com/121515/97088007-58db3600-162e-11eb-8048-cfe460a200b3.png)

The problem then becomes pretty obvious. If you teleport into the island of walkability, you can get close enough, so it's that diagonal corner transition that is blocking things. I even tried with just blocking one searchmap square and it doesn't help — you could walk right up to the border before as well.

@kmfrick do I see correctly that this is because the pathfinder considers only the four cardinal directions when considering adjacency?

**Comment by kmfrick** [comment]
> For reference:
> ![image](https://user-images.githubusercontent.com/121515/97088007-58db3600-162e-11eb-8048-cfe460a200b3.png)
> 
> The problem then becomes pretty obvious. If you teleport into the island of walkability, you can get close enough, so it's that diagonal corner transition that is blocking things. I even tried with just blocking one searchmap square and it doesn't help — you could walk right up to the border before as well.
> 
> @kmfrick do I see correctly that this is because the pathfinder considers only the four cardinal directions when considering adjacency?

You're right. I'll have a look in chat, notes and old issues to see if there's a specific reason for this. If there isn't one, I'll adjust it to consider diagonal directions too and test for performance before submitting a PR.

**Comment by lynxlynxlynx** [comment]
Thanks. From memory it just seemed to be enough and since it saves a few cycles, we left it like so.

**Comment by kmfrick** [comment]
It's more complicated than that. It's fixed only if we check diagonal directions AND we use `GetBlockedNavmap` instead of `GetBlockedInRadius` to check if the adjacent node is blocked when expanding. I'm afraid this might cause some quantum tunneling, I'll go back to the thieves' maze and test there. Also it does seem weird to me that a single diagonal corner is enough to warrant walkability, but hey, there _is_ a container there.

**Comment by lynxlynxlynx** [comment]
Just noting another test case is recorded in #1100.

**Comment by MarcelHB** [comment]
I tried the obvious thing:
```diff
--- a/gemrb/core/PathFinder.cpp
+++ b/gemrb/core/PathFinder.cpp
@@ -46,11 +46,11 @@

 namespace GemRB {

-constexpr size_t DEGREES_OF_FREEDOM = 4;
+constexpr size_t DEGREES_OF_FREEDOM = 8;
 constexpr size_t RAND_DEGREES_OF_FREEDOM = 16;
 constexpr unsigned int SEARCHMAP_SQUARE_DIAGONAL = 20; // sqrt(16 * 16 + 12 * 12)
-constexpr std::array<char, DEGREES_OF_FREEDOM> dxAdjacent{{1, 0, -1, 0}};
-constexpr std::array<char, DEGREES_OF_FREEDOM> dyAdjacent{{0, 1, 0, -1}};
+constexpr std::array<char, DEGREES_OF_FREEDOM> dxAdjacent{{1, 1, 0, -1, -1, -1,  0,  1}};
+constexpr std::array<char, DEGREES_OF_FREEDOM> dyAdjacent{{0, 1, 1,  1,  0, -1, -1, -1}};
```
then something interesting happens: It works _most_ of the times, just not all the time, it's mostly that one PC is completely unable to find a path whereas all others have moved already, but sometimes it's more people standing around. And it's not blocking while moving: click as much as you want, the PC won't move until ... I don't know, moving around the map will eventually make that one reach the destination but lock others.

![paths](https://github.com/gemrb/gemrb/assets/238558/ea436283-cbf0-44a2-b61e-5dae1dd1a766)

bailing out until giving up is at
https://github.com/gemrb/gemrb/blob/c75315b1933f33747ebce8e01ea2ec7cf89e6dca/gemrb/core/PathFinder.cpp#L364
or https://github.com/gemrb/gemrb/blob/c75315b1933f33747ebce8e01ea2ec7cf89e6dca/gemrb/core/PathFinder.cpp#L371-L372

**Comment by lynxlynxlynx** [comment]
I don't know ... considering how few cases require this, we could just patch the data instead and save many cycles that way.

**Comment by bradallred** [comment]
the circle size adjustment in #1826 is _probably_ fine, so we should resolve that first.

**Comment by bradallred** [comment]
but what about it the PCs (circle size 2?) only occupied one tile?

**Comment by lynxlynxlynx** [comment]
That's already the current behaviour for movement:
![image](https://github.com/gemrb/gemrb/assets/121515/7672b8d4-8d42-4563-af2f-e2580e046b42)

So far only problems in iwd have been encountered, so it'd be easy to check. We would need some extra logic in the importer, a 2da with coordinates and value, to fix the areas on load — since we shouldn't ship the modified maps.

**Comment by MarcelHB** [comment]
Sounds like a good compromise.

**Comment by lynxlynxlynx** [comment]
@bradallred am I doing anything obviously wrong? Trying to change the read 1-bit bmp, but nothing happens, the searchmap is preserved.

```c++
diff --git a/gemrb/plugins/AREImporter/AREImporter.cpp b/gemrb/plugins/AREImporter/AREImporter.cpp
index 1e56064c5..d6461f2c6 100644
--- a/gemrb/plugins/AREImporter/AREImporter.cpp
+++ b/gemrb/plugins/AREImporter/AREImporter.cpp
@@ -202,6 +202,30 @@ static TileProps MakeTileProps(const TileMap* tm, const ResRef& wedref, bool day
        if (!searchmap) {
                throw std::runtime_error("No searchmap available.");
        }
+       // override some diagonal-only transitions to save on pathfinding time
+       AutoTable smOverride = gamedata->LoadTable("smoverri");
+       if (smOverride) {
+               TableMgr::index_t areaCount = smOverride->GetRowCount();
+               for (TableMgr::index_t row = 0; row < areaCount; row++) {
+                       if (wedref != smOverride->GetRowName(row)) continue;
+
+                       int x = smOverride->QueryFieldSigned<int>(row, 0);
+                       int y = smOverride->QueryFieldSigned<int>(row, 1);
+                       Point badPoint(x, y);
+                       auto it = searchmap->GetIterator();
+                       auto end = PixelFormatIterator::end(it);
+                       while (it != end) {
+                               //if (it.Position() == badPoint) {
+                                       // paint it as passable wood, idx 9 in the palette (255, 0, 0, 255)
+                                       Color c = it.ReadRGBA();
+                                       (void)c;
+                                       constexpr uint8_t goodPx = 9;
+                                       *static_cast<uint8_t*>(it.pixel) = goodPx;
+                               //}
+                               ++it;
+                       }
+               }
+       }
 
        TmpResRef.Format("{:.6}HT", wedref);
 
```

**Comment by bradallred** [comment]
It's unfortunately non-obvious, but I believe the `it.pixel` for `PixelFormatIterator` is always pointing to the first pixel. I think you need to use the `PixelFormatIterator::operator*`. Something like: `*it.pixel = goodPx` should work. Shouldn't need to cast anything.

**Comment by bradallred** [comment]
oh, I now realize that the `searchmap` there is the combo of material and SM. Might be better to adjust it down below:
https://github.com/gemrb/gemrb/blob/c40242294773e97f4d6d02d33fade88b11417ad9/gemrb/plugins/AREImporter/AREImporter.cpp#L230-L233

**Comment by lynxlynxlynx** [comment]
Thanks, it's more efficient to do it above, so we don't have to check the area match all the time. 

And it works, but it's also quite interesting — the debug overlay shows a proper map, but these new accessible areas are not accessible until you get close enough and then they are forevermore. But it's just a silly trap — with the overlay enabled, one forgets the area is not explored yet and that's the reason you can't order movement everywhere. :)
