### ISSUE TITLE
[IWD1] Pathing failed in ar3601

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1017]
#### Bug description
At ar3601 [1319.593], Verbeeg fail to find path to attack you.

console :
 
FindPath/DEBUG]: Pathing failed for Verbeeg
[ResourceManager/ERROR]: Couldn't find 'mgve.2da'.
[FindPath/DEBUG]: s = (1224, 630), d = (1429, 507), caller = Verbeeg, dist = 103, size = 4
[FindPath/DEBUG]: Pathing failed for Verbeeg
[ResourceManager/ERROR]: Couldn't find 'mgve.2da'.
[FindPath/DEBUG]: s = (1003, 537), d = (1429, 507), caller = Verbeeg, dist = 107, size = 4
[FindPath/DEBUG]: Pathing failed for Verbeeg
[ResourceManager/ERROR]: Couldn't find 'mgve.2da'.
[FindPath/DEBUG]: s = (1224, 630), d = (1429, 507), caller = Verbeeg, dist = 103, size = 4

GemRB version: master (tested with 0.8.6 and not really better...)

#### Steps to reproduce
1. stay upstairs and get detected by Verbeeg
2. they can't attack you as if stair doesn't exist

#### Expected behavior
When they detect you, they go upstairs to fight you

#### Screenshots
![pathing_failed](https://user-images.githubusercontent.com/55502325/97102422-afd02200-16a5-11eb-8d97-bb63bb6ad42a.png)

**Comment by lynxlynxlynx** [comment]
Are you sure the one on the left is attacking you? Try ctrl-y on him — the other should move (if there's nothing else blocking in the fog), or on the other one — if he's the only attacker, the messages should stop.

**Comment by FrElvire** [comment]
You can ctrl-click the one on the left, but the one on the right doesn't move.

If you get close enough for the left Verbeeg to attack you too, it won't move either.

**Comment by lynxlynxlynx** [comment]
You can press ctrl-8 to get the debug searchmap overlay:
![image](https://user-images.githubusercontent.com/121515/97113759-c0f05180-16ec-11eb-9d09-31d5f90a76ce.png)

Can you check if these giants had the same circle size in the original? They look too big and lowering should fix it.

**Comment by chilvence** [comment]
Here's GemRB on the left, IDMain.exe on the right

![verbeeg](https://user-images.githubusercontent.com/1923867/97114151-ae731980-16e6-11eb-85b3-3fbc3c7db776.png)

**Comment by FrElvire** [comment]
For the debug searchmap overlay : 
![pathing_failed_2](https://user-images.githubusercontent.com/55502325/97114552-71f8eb00-16f1-11eb-85f5-285d5f162525.png)

**Comment by FrElvire** [comment]
:+1:
