### ISSUE TITLE
[IWD1 with HOW] Can't buy multiple time the same item

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1019]
#### Bug description
With HOW you should have the possibility to buy or select multiple time the same item by double clicking, but it doesn't work. (In BG2 it worked).

Tested on original (same files) and it works.

GemRB version: master

#### Steps to reproduce
1. Go to a merchant
2. try to buy more than a (pack of) arrow by example

**Comment by lynxlynxlynx** [comment]
Without looking, I suspect the relevant code in GUISTORE.py is explicitly limited to only bg2.
