### ISSUE TITLE
pst infopoint bit not implemented

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#1020]
I noticed that while testing on Subviews branch, I can no longer talk to the ghost of Deionarra in the Mortuary - I am able to see the dialog cursor if I hover over her actor circle, but nothing actually happens when I click on it.

Here is a save game at the exact location:

[000001008-Deionerra.zip](https://github.com/gemrb/gemrb/files/5435513/000001008-Deionerra.zip)

**Comment by bradallred** [comment]
is that info point cursor supposed to appear in the area around her?

**Comment by lynxlynxlynx** [comment]
Which area is this?

**Comment by bradallred** [comment]
ar0201

**Comment by chilvence** [comment]
That's AR0201, first region (Bier), attached script 0201BIER.BCS - clicking on it is just supposed to show some floating text description I believe

**Comment by bradallred** [comment]
so is that broken on master too or just here?

**Comment by chilvence** [comment]
Sorry, a correction: there are actually Tomb1 and Tomb2 regions that are hard to see, they are the ones with the info text

You are able to click her actor circle on master though

**Comment by bradallred** [comment]
im not asking about clicking her, im asking about what is supposed to happen when I click the info point, because nothing is happening so what is the point of it? if its broken, then is it this way on master too?

**Comment by lynxlynxlynx** [comment]
This bier infopoint does have flag bit set that's not used in other games. Can you retry in the original, but with just the "trap resets" bit set? Should reproduce the behaviour in master, otherwise it's a deeper mistery.

Brad: yes, it's the same on master. This trap is there to trigger her appearance when you get close enough.

**Comment by chilvence** [comment]
Ah I see.. to clarify, even in the original exe, the 'Bier' infopoint does enable the '?' cursor, but clicking on it is a non-event. So that particular part isn't a GemRB problem. I will try changing that bit and see what happens though, if it might uncover something interesting, hold on...

**Comment by chilvence** [comment]
Ok, removing the 'trigger silent' bit (so named in NearInfinity, not sure if it is the same internally) just seems to disable the floating text display when you click on the region - which makes sense, because it is not defined so you get the "I shall wait for you in deaths halls" string that appears everywhere there is a '0' strref. 

No idea why it still presents as clickable when nothing happens though, I'd imagine like every other unanswered question, the short development window had something to do with it.

**Comment by lynxlynxlynx** [comment]
More like new studio, this same scenario could be done by just hiding her instead, several infopoints, an invisible observer ...

But thanks, that clears things up. When the bit is set, it doesn't eat up the click, but lets the bottom one do it. Annoying, I guess we better not set overInfoPoint to the top one when there are several.

**Comment by bradallred** [comment]
is there still something more that needs to be done for this?

**Comment by lynxlynxlynx** [comment]
Yes, implementing that bit, so we can trigger the underlying regions.
