### ISSUE TITLE
 Subviews PST: Some scrollbars are missing

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#1024]
On some PST GUI screens with text areas, scrollbars don't seem to appear at all, eg in GUIREC:

![no scrollbar](https://user-images.githubusercontent.com/1923867/97592996-2730e900-19f9-11eb-9da8-14f9743e9e4f.png)

Some of them work though, eg the top box in the GUIJRNL bestiary, but not the actor description. 

![bestiary](https://user-images.githubusercontent.com/1923867/97593442-9c9cb980-19f9-11eb-9146-614812d178fe.png)

I can't find any insightful pattern or clue why some text areas work and others don't, and there's no error in the log. 
BG2 doesn't seem to have the same issue either, the record window is scroll-able just fine.

**Comment by bradallred** [comment]
oh subviews you wont get scrollbars if there is nothing to scroll

**Comment by chilvence** [comment]
Those are both text boxes that are overflowing though, in the first I can't scroll down to see proficiencies etc

Is it supposed to update automatically when you use X.SetText("___"), or is there an override needed?

**Comment by bradallred** [comment]
the scrollbars are all handled in the core (cpp) side and are completely automatic.

Can you scroll them with a scroll wheel?

**Comment by chilvence** [comment]
No, neither can I click and drag them

**Comment by lynxlynxlynx** [comment]
I can confirm the problem, there's definitely more text to be had.

**Comment by bradallred** [comment]
I dont know what the problem is per se, but it appears that `SetText` is called repeatedly and occasionally has something weird and unexpected in it:

<img width="252" alt="image" src="https://user-images.githubusercontent.com/1126744/97597149-21bcaa00-19cb-11eb-8158-ee67bca5f082.png">

**Comment by lynxlynxlynx** [comment]
GUIREC is full of mouse-over handlers, so I'd suspect that. I don't see how that could avoid a scrollbar though.

**Comment by bradallred** [comment]
noted. I didn't realize. you are correct.

**Comment by chilvence** [comment]
Thanks :)
