### ISSUE TITLE
PST Record Sheet: Character species label broken due to original save bug

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#1025]
I've known about this one for a while, but not sure the best way to solve it.  It isn't really super important, but an issue on the tracker means it won't be forgotten

The original game seems to not save the player characters species stat properly, they all get set to ```0``` so when you load a game with GemRB, which uses that stat to decide which text label to display on the record sheet, they all show ```*``` instead.

https://github.com/gemrb/gemrb/blob/d43ce277445eddf2a6a7a5f3ce5026264fdd7543/gemrb/GUIScripts/pst/GUIREC.py#L256

Changing this stat has no effect on the character species label when you load in the original, so I can only guess that it was hardcoded.

GemRB version:  Any

#### Screenshots
![unknown species](https://user-images.githubusercontent.com/1923867/97600673-361b9980-1a01-11eb-8ba6-5cc8f2ddb314.png)

I can probably solve this one easily, but I don't know what the preferred method is.

Perhaps it can be solved by adding or extending an unhardcoded 2da file and using that instead of this stat?

**Comment by lynxlynxlynx** [comment]
What's the mapping supposed to be?

**Comment by chilvence** [comment]
Something like:

```
Character - Species - String ID - RACE.IDS name - number
NAMELESS - Human , 19746 , HUMAN , 1
MORTE - Morte , 274 , MORTE , 45
DAKKON - Githzerai , 1741  , GITHZERAI , 30
ANNAH - Tiefling , 1737 , TIEFLING  , 64
GRACE - Succubus , 3135 , SUCCUBUS , 61
NORDOM - Rogue Modron , 2798 , ROGUE_MODRON , 52
IGNUS - Human , 19746 , HUMAN , 1
VHAILOR - Restless Spirit , 3240, RESTLESS_SPIRIT , 51
```

Those are the strings I found by prodding around with NI and looking at unhardcoded races.2da 

Really it just needs a table to map each character to their species, looking it up in races.2da is already enough for the rest.

**Comment by lynxlynxlynx** [comment]
Are you saying the original then does display the species string, just disregarding the stat?

**Comment by chilvence** [comment]
Yes, but it's probably in the UI code somewhere. There are no useful references to these strings elsewhere, and of course it doesn't have races.2da

**Comment by lynxlynxlynx** [comment]
So I propose we keep the current lookup, but if it results in * (original saves), we use the race to look up the string in races.2da (already loaded through CommonTables).

**Comment by chilvence** [comment]
That nearly works, but you end up with "Human" instead of "Morte" (sort of meh), but still * for Vhailor, because he's registered as GHOST(26)

**Comment by lynxlynxlynx** [comment]
The g-only experience is what matters most. :)

**Comment by chilvence** [comment]
It finally got under my skin too much though :)

How does this look?

https://github.com/gemrb/gemrb/commit/3343cc2ee0ca893c0b305da25b961b7b1c22d260

**Comment by lynxlynxlynx** [comment]
I'd rather see a specifics check for Vhailor as well, but other than that it looks fine.
