### ISSUE TITLE
XDG path compliance

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#103]
Standardise user paths on linux (icon location should already be fine). Instead of using ~/.gemrb, we should be putting it to $XDG_CONFIG_HOME.

spec: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by lhanson** [comment]
Please don't invade my `$HOME` with arbitrary directories. There is no downside to respecting users' preferences.

**Comment by lynxlynxlynx** [comment]
We're not saving anything, but we do look up if the user has our config there. When this was written, XDG didn't exist yet. It's a pretty simple issue to fix, but one must also think of the migration path.

**Comment by lhanson** [comment]
The best approach to making the transition seamless for existing users would likely be to look for the config in the specified XDG path and fall back to `~/.gemrb` if not found.

**Comment by lynxlynxlynx** [comment]
Yes, it's simplest without any migration, just adding the extra search path with precedence. Which I guess would be fine. It should be done here, with the rest of the lookups:
https://github.com/gemrb/gemrb/blob/6f1b497a5a0bda41319a7baaa88a92d881393742/gemrb/core/InterfaceConfig.cpp#L114-L176
