### ISSUE TITLE
[IWD1] Giant insect priest spell  sould last only 8 hours 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1032]
#### Bug description
If you summon giant insect, you can sleep multiple time 8 hours and they don't disappear.

GemRB version: master

#### Steps to reproduce
1. summon giant insect
2. sleep 
3. They are always here

#### Expected behavior
they should last only 8 hours

#### Screenshots
![giant_insect](https://user-images.githubusercontent.com/55502325/97803048-ee3a8380-1c47-11eb-9bdf-5fff89bb44ad.png)

**Comment by lynxlynxlynx** [comment]
The effect has a duration of 11.2 hours, so at minimum the description is misleading.

All the code starts from fx_iwd_monster_summoning, the only effect the spell uses. Maybe something is wrong with the unsummoning effect creation?

Alsp perhaps iwd_monster_2da needs to be changed — NI has CDOOM and GINSECT in the reverse order.
