### ISSUE TITLE
[subviews] Poor performance in battles

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1035]
#### Bug description
I have tested two battles, one in IWD2 (exit of monastry in the basement), and the finale of BG. Both suffer from performance penatlies of about 50%.

It's not purely related to actors. When I summon hordes of monsters, it stays Ok, but degrades as soon as there is action.

I've tested both cases on master, and there it's good. Platform was Windows with OpenGL enabled. Can maybe test it later on Linux as well.

#### Screenshots
![bg_battle](https://user-images.githubusercontent.com/238558/98393534-b40f1e80-2059-11eb-9126-922a6713ccc8.jpg)
![iwd2_battle](https://user-images.githubusercontent.com/238558/98393537-b5404b80-2059-11eb-894f-64a5af448c36.jpg)

**Comment by bradallred** [comment]
does the problem go away if you hide the message window? I suspect this is just #233

**Comment by MarcelHB** [comment]
_A bit_ ... When I hide the UI, it's notably better (~20fps) but far from optimal.

**Comment by bradallred** [comment]
probably need to do some profiling with the UI hidden to find the main cause. its been awhile since ive merged master, so maybe something to do with the pathfinder. seems unlikely to be drawing related if things are fine while the game is paused

**Comment by lynxlynxlynx** [comment]
For it to be a pathfinder thing, it would have to be from an older merge problem. Since the last merge, there has been only a tiny change; something that could affect iwd2, but not bg1.

**Comment by chilvence** [comment]
I haven't built with MinGW for a while so I don't know if it is much different, but one thing I have noticed on windows is that the command window output can sometimes have a silly effect on performance. I can actually tell there is a drop if I add too many debug prints of my own. I also have a branch that silences most of the loudest ones, which always seems to be 'lighter'.  Hell, my pi4 seems to be able to load games faster than my win 10 xeon sometimes

I also can't help but notice #1036

It's just a stab in the dark, but does removing the log messages from the pathfinder make any difference?

**Comment by bradallred** [comment]
im sure logging doesn't help, but it should be the same on both branches so ultimately not the difference. Some things might be inadvertently happening more on subviews due to the `Actor` and `Map` drawing refactor. its possible the pathfinding stuff didn't make it into the right "update" cycle.

**Comment by chilvence** [comment]
Sorry, didn't mean to imply the logging was the main culprit, but it has been something I have wondered about for a while. Sometimes I feel like even the version I build on WSL Ubuntu somehow feels snappier, just that it's hard to tell whether or not I am imagining it or if there is really a big difference, or even why that would be. Even if there are other factors, I can't help but think this is one of them, but I also can't think how to test the theory. I don't have any savegames from BG/IWD series any more. As you said, it's just a gut feeling that it probably isn't helping.

**Comment by MarcelHB** [comment]
Can confirm. My Linux also feels way smoother while showing the same fps. But it's on master as well, and I did not found the metric to look at so far, too. So I suggest to look at _that_ when subviews is done.

**Comment by bradallred** [comment]
I've merged master if you want to see if the unmarked pathfinder fixes help at all. otherwise somebody is going to have to find some time to do profiling.

**Comment by MarcelHB** [comment]
No improvement. I also checked again: The problem remains while being paused, but only while the viewport is focused on the battleground.

Does that mean that you cannot reproduce that?

**Comment by bradallred** [comment]
I dont have a quick way to check and I dont really have time at all right now to work on this.

**Comment by lynxlynxlynx** [comment]
Sounds like an upstream sdl issue to me, since you only hit it on one platform.

**Comment by MarcelHB** [comment]
I haven't particularly tested that on Linux yet, but I assume you cannot reproduce as well. Well, I try to find something anytime soon.

**Comment by bradallred** [comment]
no rush, at some point ill have time. what would be helpful is if you had some quick repro instructions. can this be seen by just loading any arbitrary save and spamming summons for example. 

Resolution settings also play a huge factor in performance so it would be nice to know details like that.

**Comment by MarcelHB** [comment]
It's just 1024x768.

AMD's profiler is not as helpful as Intel, but from what I see is that plenty of time gets lost in `Palette::Copy`. Will continue to find the call stack on this hot path.

**Comment by bradallred** [comment]
thanks. I'm sure a lot of copies come from the font color changing which is expected until #233 is addressed. I wouldn't expect a whole lot of others unless there is some gfx stuff happening.

**Comment by lynxlynxlynx** [comment]
I tried a battle with about 20 actors in bg2, same resolution. No slowdown even when not paused.

**Comment by bradallred** [comment]
can you try this patch

```diff
diff --git a/gemrb/core/Scriptable/Actor.cpp b/gemrb/core/Scriptable/Actor.cpp
index 26fbd9885..47f649fe9 100644
--- a/gemrb/core/Scriptable/Actor.cpp
+++ b/gemrb/core/Scriptable/Actor.cpp
@@ -8375,21 +8375,15 @@ void Actor::DrawActorSprite(int cx, int cy, uint32_t flags,
 
 		Holder<Sprite2D> currentFrame = anim->CurrentFrame();
 		if (currentFrame) {
-			if (palette->HasAlpha() && TranslucentShadows) {
-				ieByte tmpa = palette->col[1].a;
-				palette->col[1].a /= 2;
-				video->BlitGameSpriteWithPalette(currentFrame, palette, cx, cy, flags, tint);
-				palette->col[1].a = tmpa;
-			} else if (TranslucentShadows) {
-				PaletteHolder cpy = palette->Copy();
-				cpy->col[1].a = tint.a / 2;
+			if (TranslucentShadows && !palette->HasAlpha()) {
+				// we exclusively own this palette and can do as we please with it
+				palette->col[1].a = tint.a / 2;
 				for (int i = 2; i < 256; ++i) {
-					cpy->col[i].a = tint.a;
+					palette->col[i].a = tint.a;
 				}
-				video->BlitGameSpriteWithPalette(currentFrame, cpy, cx, cy, flags, tint);
-			} else {
-				video->BlitGameSpriteWithPalette(currentFrame, palette, cx, cy, flags, tint);
 			}
+			
+			video->BlitGameSpriteWithPalette(currentFrame, palette, cx, cy, flags, tint);
 		}
 	}
 }
@@ -8446,19 +8440,32 @@ bool Actor::AdvanceAnimations()
 	const auto count = anims->GetTotalPartCount();
 	const auto zOrder = anims->GetZOrder(face);
 	
+	auto CopyTransShadowPal = [](PaletteHolder pal) -> PaletteHolder {
+		if (pal->HasAlpha() && TranslucentShadows) {
+			PaletteHolder cpy = pal->Copy();
+			cpy->col[1].a /= 2;
+			return cpy;
+		} else if (TranslucentShadows) {
+			return pal->Copy();
+		}
+		return pal;
+	};
+	
 	// display current frames in the right order
 	for (int part = 0; part < count; ++part) {
 		int partnum = part;
 		if (zOrder) partnum = zOrder[part];
 		Animation* anim = stanceAnim[partnum];
 		if (anim) {
-			currentStance.anim.emplace_back(anim, anims->GetPartPalette(partnum));
+			auto pal = anims->GetPartPalette(partnum);
+			currentStance.anim.emplace_back(anim, CopyTransShadowPal(pal));
 		}
 		
 		if (shadows) {
 			Animation* anim = shadows[partnum];
 			if (anim) {
-				currentStance.shadow.emplace_back(anim, anims->GetShadowPalette());
+				auto pal = anims->GetShadowPalette();
+				currentStance.shadow.emplace_back(anim, CopyTransShadowPal(pal));
 			}
 		}
 	}
```

**Comment by MarcelHB** [comment]
It's notably better (~20fps with UI, ~23fps without UI) but there's probably still something else.

**Comment by bradallred** [comment]
does the profiler still highlight `Palette::Copy`? if so, where from?

**Comment by MarcelHB** [comment]
So, here is what my profiler shows in the biggest root sub-element:

<details>
  <summary>Expand to see patch</summary>

![flame](https://user-images.githubusercontent.com/238558/98864147-bb736500-2469-11eb-8b48-456ca6d3331b.png)

</details>
Summary: Deleting and updating texture is really slow for AMD's driver. Maybe it's such an anti-pattern nobody every consider to be handeled there? Don't know.

Anyway, then I remebered this observation from another ticket (#899), and then I tried [this patch](https://github.com/gemrb/gemrb/issues/899#issuecomment-671109228) from there again: Problem gone, don't destory and create all the time when you can just do an update.

**Comment by bradallred** [comment]
thanks, this is helpful. I'm pretty sure I have an idea that will resolve this

**Comment by bradallred** [comment]
ok, I distilled that patch down to the part that we need. there is still some work that could be done with `CharAnimations` and the unnecessary palette copy/manipulations happening.

**Comment by MarcelHB** [comment]
That's much better already.

**Comment by bradallred** [comment]
at least 30fps better?

**Comment by MarcelHB** [comment]
Basically yes, going at 30fps (not steadily, dropping by 10% from time to time) with framecap, 130-160fps without it.

**Comment by bradallred** [comment]
sweet :)
