### ISSUE TITLE
 Make all loggers optional

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1036]
Talking with the MorphOS porter it became obvious that the current extra logging and the additional disk writing is bogging things down. Let's make the loggers opt-out, so platforms like these can disable them completely.

**Comment by bradallred** [comment]
yeah we should. if we want a quick fix in the interim just make a logger that discards everything.

**Comment by lynxlynxlynx** [comment]
From what I see, they're currently hardcoded, so all the compiled ones are used. Meaning a NullLogger wouldn't help without further changes.

**Comment by bradallred** [comment]
hmmm, I'm not sure its that dire. We have `AddLogger` and I thought you needed to call that to have logging at all. We already have platform specific loggers (`AppleLogger` for example).

**Comment by lynxlynxlynx** [comment]
We do, I'm just saying we call AddLogger by default. Eg. the file logger does it in its addLogger function, which is the plugin initializer.

**Comment by bradallred** [comment]
another thing we ought to do is defer the actual I/O to a background thread.
