### ISSUE TITLE
[subviews] iwd2 chargen default/focus problem

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1037]
If you import a character and then press enter, cg resets.
UpdateOverview in CharOverview.py does make the step buttons default (eg. appearance in this case) and just sets up the buttons in the other window where that restart button is (YesButton in that function), not making it default.

So the wrong button ends up with the key press even if something else after UpdateOverview focuses the wrong window.

**Comment by bradallred** [comment]
I'll speculate and say we probably don't even need to call `MakeDefault` for any of these buttons and that would fix the issue.

**Comment by lynxlynxlynx** [comment]
Sounds weird, but also has no effect. There's an even quicker reproducer: just choose the gender and enter away.

**Comment by bradallred** [comment]
the problem is the `CharGenWindow.SetFlags (IE_GUI_VIEW_IGNORE_EVENTS, OP_OR)`. I'm not sure why I added that. I'm also not sure why we are loading the `StartOverWindow` where we do instead of as needed.

**Comment by lynxlynxlynx** [comment]
The defaults still don't work, but the narrow issue is fixed.
