### ISSUE TITLE
[feature] Character creation - stats reroll randomization balancing

### ISSUE THREAD

**Issue by tomudo** [gemrb/gemrb#104]
**Description**
Adjust stats reroll randomization to similar to original game for balancing overpower character creation. 

**Detail**
The stats reroll is higher randomization than origin in BG1. For example, sum of stats in original game rerolls maybe around 70 to 80, higher and lower stats is harder to get (bell curve distribution) but gemrb look like randomization is greater than original. This lead to easier to create overpower character.

**Comment by lynxlynxlynx** [comment]
It's random ... so I can't even believe you without significant numbers, maybe a chi-squares to back it up.  I don't think it's worth the effort though.

The minimum is of course adjusted by the race and chosen class, so eg. paladins will always get higher chances of better stats.

**Comment by tomudo** [comment]
I didn't try before I request. I reroll with the same class but it took less time in gemrb to create sum of stats + 85 than the original game. You may try it by yourself.
