### ISSUE TITLE
 [IWD1] Character go back and forth

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1040]
#### Bug description
Often a character go back and forth between 2 positions, here is an easy reproducible case. 

Position : Position: ar4005 [353.349]

Console output : 

[FindPath/DEBUG]: s = (411, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[FindPath/DEBUG]: s = (427, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[FindPath/DEBUG]: s = (411, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[FindPath/DEBUG]: s = (427, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[FindPath/DEBUG]: s = (411, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[FindPath/DEBUG]: s = (427, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[FindPath/DEBUG]: s = (411, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[FindPath/DEBUG]: s = (427, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[FindPath/DEBUG]: s = (411, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[FindPath/DEBUG]: s = (427, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[FindPath/DEBUG]: s = (411, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[KeyMap]: Looking up key: �(�) 
[FindPath/DEBUG]: s = (427, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[FindPath/DEBUG]: s = (411, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[FindPath/DEBUG]: s = (427, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[FindPath/DEBUG]: s = (411, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[FindPath/DEBUG]: s = (427, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[FindPath/DEBUG]: s = (411, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[FindPath/DEBUG]: s = (427, 351), d = (465, 407), caller = Alua, dist = 60, size = 2
[FindPath/DEBUG]: s = (411, 351), d = (465, 407), caller = Alua, dist = 60, size = 2

GemRB version: Master

#### Steps to reproduce
1. See video

#### Video
here a screenshot doesn't help so....

[path-2020-11-08_15.53.25.mkv.zip](https://github.com/gemrb/gemrb/files/5506543/path-2020-11-08_15.53.25.mkv.zip)

**Comment by lynxlynxlynx** [comment]
Something to check after the other fixes land.

CC @kmfrick

**Comment by lynxlynxlynx** [comment]
Can't reproduce this any more. :)
