### ISSUE TITLE
Demo: fixing the clown colors 

### ISSUE THREAD

**Issue by m7600** [gemrb/gemrb#1045]
#### Description
Fixing the clown colors of the protagonist in the Demo, so that they match a more realistic palette. 

#### Additional context
I can make the palette, but I don't know how to match it to the clown colors of the protagonist. I'm opening this issue to get suggestions.

**Comment by lynxlynxlynx** [comment]
The code is already there to apply different colors to different parts, but last time I looked, I didn't manage to figure out why it's ignored.

**Comment by m7600** [comment]
Looking at the other folders in GUIScripts (bg1, b2, iwd, etc.), it might be better to not have a SetupGame.py file at all. Maybe I can start to work on some CharGen stuff, and see if the clown colors can be fixed there.

**Comment by lynxlynxlynx** [comment]
That's not how things work. The colors that are used to recolor clowns get set correctly. But perhaps the values are bad. avatars.2da definitely needs a 0 in the palette column for this animation, but that's not enough.

**Comment by m7600** [comment]
I fixed it (sort of). Take a look at the last line of avatars.2da, it says "0x**c**800" instead of 0x8000. Given that the "c" key is right next to the "x", it's an understandable mistake.

**Comment by m7600** [comment]
The animation now looks almost completely yellow. Is this normal? Here's a [screenshot](https://raw.githubusercontent.com/m7600/GemRB-demo-extension/main/Screenshot%20from%202020-11-11%2019-17-05.png).

**Comment by lynxlynxlynx** [comment]
Changing 0xc800 to 0x8000 has no effect in this case, beside being incorrect — this is the animation id set in the cre file.

**Comment by m7600** [comment]
Are you sure? it did change the avatar to completely yellow for me, so it has to be doing something... right? Take a look at the screenshot that I posted.

**Comment by lynxlynxlynx** [comment]
That's from changing the palette column. If you still want to play with it, try changing the color numbers in SetupGame. If you change all, does the color change? If so, then try changing just one, until you find the one color stat responsible.

**Comment by lynxlynxlynx** [comment]
I suspect we should be shipping more palette files and that's why it doesn't quite work. But yellow is indeed an unexpected result.

**Comment by m7600** [comment]
Apologies lynx, you were right, the yellow is from changing the palette column. Let me see if I can do something with SetupGame.py like you suggested.

**Comment by m7600** [comment]
lynx, I tried several different combinations in SetupGame, and only two things can happen, depending on the value:
1) Nothing
2) A crash

I don't think I can solve this, sadly.

**Comment by lynxlynxlynx** [comment]
Ok, cool, so it's indeed not about the values.

**Comment by lynxlynxlynx** [comment]
Just noting for future reference that setting Palette16, Palette32, Palette256 in gemrb.ini to full palettes doesn't fix it.

**Comment by lynxlynxlynx** [comment]
Actually it does fix it for editing in NI, but it also requires an avatars.2da fix (palette to 0). It looks like we only need to replace Palette16 for all of this to work. :)
