### ISSUE TITLE
[subviews] spell icons get corrupted when memorizing

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1052]
![image](https://user-images.githubusercontent.com/121515/99144045-e248bb80-2662-11eb-8466-ae0fe1d83a94.png)
It happens at the end of the animation, before that it's fine. Moving the mouse over makes it flicker.
But at most one slot has the problem, interesting. Also visible in the priest spellbook.

**Comment by MarcelHB** [comment]
Probably what I gave up debugging in #778
