### ISSUE TITLE
[subviews] pst journal misplaces text

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1055]
This is the textarea in the CHU:
![image](https://user-images.githubusercontent.com/121515/99145441-28a41780-266f-11eb-9e62-645cbc6769ce.png)

We somehow print:
![image](https://user-images.githubusercontent.com/121515/99145445-36f23380-266f-11eb-9e82-5f6552defa54.png)

We don't touch the control, it's populated by SetOptions.

**Comment by bradallred** [comment]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/1126744/100828527-8c269700-341c-11eb-8fff-5b25396e32b4.png">

Either we are changing it (somehow), or that isn't accurate

**Comment by bradallred** [comment]
Ah, the cause is `MergeTextAreaAndScrollbar`. It's because the scrollbar assigned to the TA extends beyond the top/bottom. The fix then, is to compensate for this scenario by increasing the top/bottom margins respectively.

**Comment by bradallred** [comment]
looking at the code, we _do_ set the margins appropriately, as seen here:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/1126744/100829414-8a5dd300-341e-11eb-9fd2-214d43208bde.png">

the problem, then, must be that the selection options don't obey the margins.

This brings another issue to light too, the CHU has the scrollbar on the left. We only handle them on the right.

**Comment by lynxlynxlynx** [comment]
We still have a problem at the bottom:
![image](https://user-images.githubusercontent.com/121515/101240694-3fc7a980-36f1-11eb-9ba6-119c042cf155.png)

**Comment by lynxlynxlynx** [comment]
And on the right (line 5-6):
![image](https://user-images.githubusercontent.com/121515/101240774-aea50280-36f1-11eb-865f-1859e6bade4e.png)

Similar, but different, the scrollbar is hiding creature description:
![image](https://user-images.githubusercontent.com/121515/101240805-d5fbcf80-36f1-11eb-8dba-ade153a1de39.png)

**Comment by bradallred** [comment]
I think that is everything

**Comment by lynxlynxlynx** [comment]
Yep, looks fine.
