### ISSUE TITLE
[subviews] pst worlmap issues

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1058]
- [x] place name text is white
 - [x] place names are not always drawn over icons
 - [x] done button is missing text and action
 - [x] can't scroll with the mouse - tries to drag
 - [x] hovering icons causes bad highlight with color inversion, while it should just shade
 - [x] traveltime tooltip is there, while it shouldn't be

```
[WorldMap]: CalculateDistances for Area: ar0100
[GUIScript/ERROR]: Runtime Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "../gemrb/GUIScripts/pst/GUIMA.py", line 90, in OpenTravelWindow
[Python/ERROR]:     WMap = Window.CreateWorldMapControl (4, 0, 62, 640, 418, Travel, "FONTDLG")
[Python/ERROR]:   File "../gemrb/GUIScripts/GUIClasses.py", line 173, in CreateWorldMapControl
[Python/ERROR]:     return self.CreateControl(control, IE_GUI_WORLDMAP, args[0], args[1], args[2], args[3], args[4:])
[Python/ERROR]:   File "../gemrb/GUIScripts/GUIClasses.py", line 152, in CreateControl
[Python/ERROR]:     return self.CreateSubview(id, type, frame, *args)
[Python/ERROR]:   File "../gemrb/GUIScripts/GUIClasses.py", line 165, in CreateSubview
[Python/ERROR]:     created = self.AddSubview(view) # this will move the reference into the our window's group
[Python/ERROR]:   File "../gemrb/GUIScripts/MetaClasses.py", line 44, in handler
[Python/ERROR]:     raise type(e)(str(e) + "\nMethod Docs:\n" + str(f.__doc__))
[Python/ERROR]: RuntimeError: Cannot construct object with null ref.
```

**Comment by chilvence** [comment]
This commit fixes the python error b1a8707d0bb619eadd4aa8d4e234d7d3ffad21e3

It looks like this was changed for the other games but PST was using the old method. There are no other usages of CreateWorldMapControl so I removed it.

There's some behaviour that needs refining though, the map highlight is inverted and you can currently travel just by opening the map from interface (which I really want to make into a nice debug feature....)
