### ISSUE TITLE
[subviews] rightclick not reseting the action window

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1061]
Now you have to use the keyboard, issue an actual command or do some other GUI action to get out of the action subwindows (like innates). They don't have any back buttons, so it's annoying. Even more so for forcing attacks, the talk icon, defend and anything else that causes a cursor change.

**Comment by bradallred** [comment]
seemingly broken in #962

**Comment by lynxlynxlynx** [comment]
Works fine now, closing.
