### ISSUE TITLE
demo: fix fog of war hugging too much

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1064]
More of the cliff side should get explored than this:
![image](https://user-images.githubusercontent.com/121515/99155669-4cd91600-26ba-11eb-8895-7e0a02c4773b.png)

Perhaps a searchmap thing, I don't know.

**Comment by m7600** [comment]
Good catch, I hadn't noticed that. I'll look into it.

**Comment by lynxlynxlynx** [comment]
Wait a bit, I'm refreshing the searchmap anyway and I suspect I see the reason why you can walk through the pillars as well (you can pass through).

**Comment by lynxlynxlynx** [comment]
Yeah, that was it. :)

**Comment by m7600** [comment]
Cool. Just out of curiosity, do you use IE Tileset Map Editor, or do you do all of the area editing with DLTCEP? I use IETME for this.

**Comment by lynxlynxlynx** [comment]
This was done in DLTCEP (searchmap) and gimp (lightmap). Never used IETME.

**Comment by m7600** [comment]
When you have the time, you should give IETME a chance, it will simplify your life. Or at least area making : P

**Comment by lynxlynxlynx** [comment]
I doubt it. Maybe it's better at the basics, but while I've never done it, I'm pretty sure DLTCEP is the best way to tackle complex substructures like wallgroups and doors. I can't even find a website describing IETME. :P

**Comment by m7600** [comment]
That's true, DLTCEP is way more powerful
