### ISSUE TITLE
Demo: connect ar0100 and ar0110

### ISSUE THREAD

**Issue by m7600** [gemrb/gemrb#1070]
![Screenshot from 2020-11-15 18-18-38](https://user-images.githubusercontent.com/56371872/99199395-8757b700-277d-11eb-939c-e03caaae9b41.png)

I've got both areas working, and I can travel between them using the console command MoveToArea("").
But when I try to move the protagonist from one area to another using point-and-click, I get the following error:

```
[Map/ERROR]: Invalid entrance 'Trav0110' for area ar0110
[Map/WARNING]: WARNING!!! EntryPoint 'Trav0110' does not exist and direction 0 is invalid
[GameScript/ERROR]: Invalid scripting action: LeaveArea("ar0110",[2560.1920],-1)
[Scriptable/WARNING]: AA: NULL action encountered for protagon!
```

**Comment by lynxlynxlynx** [comment]
First, there's a shortcut you can use: mta("ar0110")

You need to add this to gemact.ids:
93 LeaveAreaName(O:Target*)

As far as the entrance goes, it looks like you didn't set it up properly.

**Comment by lynxlynxlynx** [comment]
If you send me the files over, I can take a look.
I also mentioned the wrong action, since I apparently can't read:
91 LeaveArea(S:Area*,P:Point*,I:Face*Dir)

**Comment by m7600** [comment]
That fixed it! Thanks! I get a few warnings but it works, the character moves to the interior of the cave (though not to a correct location, but to a black area, because I didn't configure it properly). [Here are the files](https://github.com/m7600/GemRB-demo-extension/tree/main/areas), but I haven't made the search map (or the light map) for the new area yet.

**Comment by m7600** [comment]
You probably don't need the .slh files, but I uploaded everything just in case.

**Comment by lynxlynxlynx** [comment]
Thanks, though in that case I'll look at it later, once we're done with the exterior.
