### ISSUE TITLE
PST Worldmap travel regression: worldmap does not activate 

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#1071]
I was scoping out the best way to implement the proper area entrance usage for PST worldmap travel when I stumbled across a new problem. There is something going wrong in GameControl::ShouldTriggerWorldMap

https://github.com/gemrb/gemrb/blob/db3900283e5df6930a37136aa65f3f44c0b99feb/gemrb/core/GUI/GameControl.cpp#L2103-L2104

I can only get the worldmap to appear if I remove the check for the actor flag IF_USEEXIT

It's fine on the master branch

I don't really know how this is supposed to go, so I will do a bisect on my linux install to try and find out what broke it.

**Comment by bradallred** [comment]
it wouldn't have changed on purpose, so I'd just look at the master merge commits to start

**Comment by chilvence** [comment]
This is turning out to be really awkward for me to bisect. I have trouble building and running subviews on my VM's for some reason, my pi4 wont let me use their gl driver, and I can't really do the job on windows because I need the commits that fix the msvc build issues :/

I really don't have a setup that is conducive to bisecting stuff...

**Comment by lynxlynxlynx** [comment]
This gets checked before UseExit gets called to set the bit. For some reason GameControl::OnMouseUp gets called twice and the first time it behaves like movement and in the second one it does the UseExit stuff.

**Comment by chilvence** [comment]
This branch I am working on is not finished, but this commit seems to fix it: 266552600d5c99b4ae166ef804b001b2fe716430. Can anyone for see any problems with switching the command order?

Note there is also some GUI breakage with the worldmap here, and I would also like to implement the 'frommap' entrances so that this can finally be 1:1 with the original.

**Comment by lynxlynxlynx** [comment]
Looks fine to me at a glance, but it requires a deeper look, since IIRC UseExit results in ProcessActions.

frommap is a separate issue, so let's not tangle everything together.

**Comment by lynxlynxlynx** [comment]
This fix is still fine, even if it doesn't merge. It brings up the travel map, however you can't travel anywhere, so perhaps it's in GUIMA this time.
