### ISSUE TITLE
BG1: No rest button on the portrait panel

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#1074]
I was testing BG1 and noticed there is no longer a rest button on the right portrait panel

It should usually appear when you look at one of the information panels eg the inventory, record sheet, etc - it replaces the ai/select all buttons in the corner

I believe this got lost because the window logic was cleaned up and BG2/IWD don't have this control (they have it on the left panel instead)

Should be easy to fix, but as an alternative, I threw this tweak together to add one on the left panel, if that is of any interest 

(I prefer it on the main screen, in any case, just like the other games):

![rest](https://user-images.githubusercontent.com/1923867/99435196-b69a2f80-2907-11eb-8ee6-fecb64eef79c.png)

https://github.com/chilvence/gemrb/commit/b4225ac528e11209ba0a6631a36639663f7c7d5f

Is that worth including, or does it look awkward and out of place?

**Comment by bradallred** [comment]
no, this is "missing" because we dont ever load the alternate portrait window anymore. we did this on purpose for resolution independence etc. Is there a reason why the one on the left panel is insufficient?

**Comment by chilvence** [comment]
I fixed the alignment on it a bit.

 I got so used to having it there in BG2 that it feels odd without it. It's probably not worth swapping it out on the portrait pane like the original did if that goes in, since then there would be two rest buttons (or the rest button would move, which would be really weird)

**Comment by m7600** [comment]
I think it looks good on the left.

**Comment by bradallred** [comment]
I agree the left seems more natural and is convenient to have always. its more complex and awkward to show/hide it on the right.
