### ISSUE TITLE
[subviews] trademeet map border artifacts

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1075]
ar2000, lower right corner of the map:
![image](https://user-images.githubusercontent.com/121515/99442917-582a7c80-291a-11eb-81a4-049b0d3f35ca.png)

Something wrong with the fog of war extension we do? Whatever it is it's encroaching on valid map territory.

Ah, bg1 has the same, but filled:
![image](https://user-images.githubusercontent.com/121515/99443318-f1f22980-291a-11eb-994a-1714cefe796f.png)

**Comment by bradallred** [comment]
this isn't what I see. what is your resolution?

**Comment by lynxlynxlynx** [comment]
Maybe it's a sdl1 thing then. I see it at any resolution.

**Comment by bradallred** [comment]
I don't see this on SDL 1 either.

**Comment by lynxlynxlynx** [comment]
@MarcelHB @chilvence can any of you two reproduce?

I can also see it in pst (ar0500) and iwd2:
![image](https://user-images.githubusercontent.com/121515/100131070-d7243580-2e83-11eb-8995-9b1efd71de4d.png)
![image](https://user-images.githubusercontent.com/121515/100131169-f9b64e80-2e83-11eb-8439-71e5eddd0660.png)

I don't get the empty variant in Trademeet any more though.

**Comment by bradallred** [comment]
sorry, let me be clear. I cannot reproduce the boundary as seen in this picture:

![](https://user-images.githubusercontent.com/121515/99442917-582a7c80-291a-11eb-81a4-049b0d3f35ca.png)

**Comment by MarcelHB** [comment]
I have _something_ (unrelated?) when hiding the UI and without FoW:

![bg2_border_viewport](https://user-images.githubusercontent.com/238558/100136797-c8418100-2e8b-11eb-88dd-aa16208e5595.jpg)

With FoW and hidden UI, it looks Ok:

![bg2_border_viewport_fow](https://user-images.githubusercontent.com/238558/100136845-d68f9d00-2e8b-11eb-8b94-870d89e61fda.jpg)

**Comment by bradallred** [comment]
this should work as expected now

**Comment by lynxlynxlynx** [comment]
Pretty much, yes.
