### ISSUE TITLE
 iwd2 worldmap icon highlight is misplaced

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1077]
![image](https://user-images.githubusercontent.com/121515/99444010-e3584200-291b-11eb-8f4e-7c90730eb503.png)

iwd2 uses shared code for the gui, so this should be in core worldmap control code.

**Comment by lynxlynxlynx** [comment]
It has a center set that way, so it looks like we need to ignore it.
![image](https://user-images.githubusercontent.com/121515/99909908-73ff9b00-2ceb-11eb-8c3d-200db6882ad0.png)

**Comment by bradallred** [comment]
strangely, I can't see a difference between the 2 branches as far as the coordinates we draw the sprites at. its as if the sprites x/y position was changed, but I cant see where that happens either.

**Comment by lynxlynxlynx** [comment]
It's not a subviews bug ...

**Comment by bradallred** [comment]
heh, indeed. my mistake :)
