### ISSUE TITLE
[subviews] Ground stuff disappears when there is a map animation

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1079]
In IWD2, there is this infamous fireside light animation right at the beginning (AR1005), see #224. When you kill the goblins close to there, both the dead goblin and its container disappear. SDL2 + OpenGL.

See screenshot with a correct cursor over where it is supposed to be drawn.
![iwd2_anim](https://user-images.githubusercontent.com/238558/99854300-db4f0b00-2b84-11eb-824b-57e9523d5bf2.jpg)

**Comment by bradallred** [comment]
the disappearing actor is a completely separate issue that happens because the stance animations are cleared and we fail to find one for the current stance for dead actors

**Comment by bradallred** [comment]
hmmm actually, it is due to `IE_AVATARREMOVAL` I dont know what this is or why it gets set on dead actors

**Comment by lynxlynxlynx** [comment]
It's most likely scripted, since this is a special state. A bit odd though. Can't affect the container though.

**Comment by bradallred** [comment]
right, as I said, they are separate issues. the piles are covered because the animation is not `A_ANI_BACKGROUND` as it should be.

**Comment by bradallred** [comment]
the only thing to figure out now is what is up with `IE_AVATARREMOVAL` being set on dead actors.

it is suspiciously set in `Actor::CheckOnDeath`... are we sure this affects subviews only? Looking at the code in master shows that `Actor::Draw` bails out if `IE_AVATARREMOVAL` is set too.

**Comment by lynxlynxlynx** [comment]
For me the goblins remain there just fine, both on master and subviews. Where is this avatar removal talk from?

The only way to legitimately remove anyone immediately in combat is through excessive damage. Since we haven't implemented the fountain of flesh (chunking #128 ) yet, the user gets to visual feedback.

**Comment by bradallred** [comment]
oh, that must be it then. I was using ctrl-y to replicate.
