### ISSUE TITLE
[feature] [bg2] Missing buying sound in merchant interface 

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#108]
**Description**
Applies to Baldur's Gate 2, Baldur's Gate Trilogy. When buying a item the game will play its specific sound. Helmets, potions, weapons, misc items all have specific sounds by the category they belong to. The file name with those sounds starts with GAM_Number.WAV. We already play the sound when you play with the item in your inventory just not yet when you buy a item. When buying multiple items the sound will play for the item selected which is on the top of the list.

**Comment by lynxlynxlynx** [comment]
This is now fixed in master.
