### ISSUE TITLE
[subviews] can't close store window

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1080]
Store windows come in pairs and while we try to make them work together, only the bottom closes on exit. It makes sense, the close button is on that window, but even when I try reassigning the focus in CloseStoreWindow, nothing happens. 

CloseTopWindow requires the window to be focused, otherwise it does nothing. The StoreWindow is manually closed, but it's set to the button row. Which makes sense if we expect CloseTopWindow to do it for the main one.

It's been a few days since I looked, but I think part of the problem was that calling Focus on GetView with a window alias calls the view version, while we need the window version (`GemRB.GetView("WIN_TOP").Focus ()`). So it looks like we need to change the binding to be able to choose between the two, add a forcing param to CloseTopWindow or add some cast-like capability to get back to the window object from the view. Or something else altogether — what do you think @bradallred ?

For the same reason switching between store modes doesn't work (but in CreateTopWinLoader/ret).

**Comment by lynxlynxlynx** [comment]
Any preference @bradallred ?

**Comment by bradallred** [comment]
>  calling Focus on GetView with a window alias calls the view version, while we need the window version 

this doesn't sound right. If `GetView` only returned a `GView` then things would be broken lots of other places. `GWindow` and `GView` both have a separate method binding for `Focus()` too.

Just from the top of my mind, seems like the cleanest, most straight forward thing to do is set an `ACTION_WINDOW_CLOSED` handler to just close the second window. Haven't looked at any code to see why that might not work, but it seems like it ought to.

**Comment by lynxlynxlynx** [comment]
Thanks!

**Comment by lynxlynxlynx** [comment]
Now closing the steal window fails (if you steal and fail, we call CloseStoreWindow at line 1606):
```
[GUIScript/ERROR]: Attribute Error:                                                                               
[Python/ERROR]: Traceback (most recent call last):                                                                
[Python/ERROR]:   File "../gemrb/GUIScripts/GUISTORE.py", line 216, in <lambda>                                   
[Python/ERROR]:     Window.SetAction(lambda: topwin.Close(), ACTION_WINDOW_CLOSED)                                
[Python/ERROR]:   File "../gemrb/GUIScripts/GUIClasses.py", line 240, in Close                                    
[Python/ERROR]:     RemoveView(self, False)                                                                       
[Python/ERROR]: AttributeError: Invalid view 
```
I don't see anything special about it.

**Comment by bradallred** [comment]
we can revert bd7bc8d now that we don't have `IE_GUI_VIEW_IGNORE_EVENTS` set. I believe that would resolve the error.
