### ISSUE TITLE
Changing framerate in GemRB ?

### ISSUE THREAD

**Issue by Toulonnais72** [gemrb/gemrb#1083]
#### Description
Add a clear and concise description of what you would like to see. Eg. the original supported
weapon sets only in iwd2, but I'd like to have them in all games.

#### Additional context
Add any other details, ideas or plans about the request here.

**Comment by Toulonnais72** [comment]
Hello,
Would it be possible to change the framerate in GemRB ?
I tried it with IWD and it is slow. I have the original game which I run at 45 fps (through config) and it is much smoother.
Thanks !

**Comment by lynxlynxlynx** [comment]
Not yet, but it is tracked in #144, so closing.
