### ISSUE TITLE
[subviews] another GUISTORE event issue - donations

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1086]
Since we ignore events, one cannot enter donation amounts in the textedit.

**Comment by bradallred** [comment]
IIRC `IE_GUI_VIEW_IGNORE_EVENTS` is set to prevent closing the window with `esc` so the sensible fix might be to remove that flag and bind the esc key to a dummy button

**Comment by lynxlynxlynx** [comment]
Nice workaround.

**Comment by bradallred** [comment]
Well, I'm not sure that alone will suffice. If that secondary window becomes focused then pressing esc will no longer close the main store window, no?

**Comment by lynxlynxlynx** [comment]
Now nothing happens. We can bind CloseStoreWindow to the button if we want to have escape close it. Hard to say if that's all that's needed, since the error from #1080 crops up.
