### ISSUE TITLE
IE_GUI_EDIT_NUMBER is broken

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1087]
The store textedit from #1086 has IE_GUI_EDIT_NUMBER set to only receive numbers. But it actually accepts also characters, so then things break on the python side.

**Comment by bradallred** [comment]
`IE_GUI_EDIT_NUMBER ` isn't a thing anymore. `TextEditFlags` need to be used instead

**Comment by lynxlynxlynx** [comment]
I guess this is fixed, so closing. Can't verify due to the other bug.
