### ISSUE TITLE
cmake is checking for "malloc.h" when it should be checking "stdlib.h"

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1088]
I noticed the `config.h` generated by cmake on my system is lacking several features that my system actually provides

the lack of these features all seem to boil down to this segment of cmake code
```
CHECK_INCLUDE_FILES("malloc.h" HAVE_MALLOC_H)
IF(HAVE_MALLOC_H)
	CHECK_FUNCTION_EXISTS("_aligned_malloc" HAVE_ALIGNED_MALLOC)
	CHECK_FUNCTION_EXISTS("memalign" HAVE_MEMALIGN)
	CHECK_FUNCTION_EXISTS("posix_memalign" HAVE_POSIX_MEMALIGN)
ENDIF()
```

the problem of course being that malloc.h doesn't exist because all of the functions we are checking for are declared in stdlib.h as per the standard.

I _want_ to fix it by just changing malloc.h -> stdlib.h, but I've no idea what esoteric reason we might have for checking malloc.h in the first place.

I'm also unsure about `_aligned_malloc`. my system has `aligned_malloc` with no leading underscore. typo? I imagine this most likely never gets used because every system that I know of outside of windows has `posix_memalign` which supersedes the use of `_aligned_malloc` in every place we check for it. Maybe this is a Windows thing?

**Comment by lynxlynxlynx** [comment]
We can check for those functions directly and just make sure we also include cstdlib wherever HAVE_MALLOC_H is checked and do nothing if none of them are available.

The _ version was added for Windows, yes.

**Comment by bradallred** [comment]
but do we need `HAVE_MALLOC_H` at all? it is not documented what platforms it is applicable to if we do. Seems likely to me anything that supports c++11 will also provide a conforming `cstdlib`

**Comment by lynxlynxlynx** [comment]
I don't think we need it, no. A shorthand for all three will be useful, but that needs to be a new define.

**Comment by lynxlynxlynx** [comment]
We have it for mallopt, which is not standard. Fixing so the other mem functions are available everywhere.
