### ISSUE TITLE
GameControl::CreateMovement implementation doesnt allow for appending movements when running

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1089]
```
//try running (in PST) only if not encumbered
if (CanRun && ShouldRun(actor)) {
	sprintf( Tmp, "RunToPoint([%d.%d])", p.x, p.y );
	action = GenerateAction( Tmp );
	//if it didn't work don't insist
	if (!action)
		CanRun = false;
}
if (!action) {
	if (append) {
		sprintf(Tmp, "AddWayPoint([%d.%d])", p.x, p.y);
	} else {
		sprintf(Tmp, "MoveToPoint([%d.%d])", p.x, p.y);
	}
	action = GenerateAction( Tmp );
}
```

as you can see `append` is only checked in the non-running case

**Comment by bradallred** [comment]
Also, I don't think `GameScript::RunToPoint` and `GameScript::MoveToPoint` should be different other than the `IF_RUNNING` flag.

**Comment by lynxlynxlynx** [comment]
The only difference is that one has an iwd2-only block and the other a probably useless SetOrientation call. Not much to do as only pst has running speeds. 

However, the whole family of functions can be generalized into a GSUtils function to remove the code repetition (like eg. SpellPointCore).

**Comment by bradallred** [comment]
sure, I just mean that ideally the run actions all just call the move actions then just call `Actor::SetRunFlags`. AFIK there is no other necessary difference.

**Comment by bradallred** [comment]
I also noticed that (at least on subviews) you could never run to a container/door/IP so I've addressed that as well

**Comment by bradallred** [comment]
however, I hadn't noticed that `WalkTo` is implemented in both `Moveable` and `Actor` as an overload so this is not quite right yet

**Comment by lynxlynxlynx** [comment]
I don't know if it's from these changes yet, but I can't run at all any more.
