### ISSUE TITLE
[subviews] demo issues

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1091]
Copying from the other bug, since it's nicely grouped:
- [x] worldmap doesn't work; because we try to reuse the same window from the same pack
- [x] esc to close works, but prints `TypeError: TopWindowClosed() takes exactly 1 argument (0 given)`
- [x] toggling with m doesn't work

Luckily DLTCEP can copy windows, so I've tried with that and a unique window id for the CreateTopWindow call. It fixes the problem, but it's a bit lame. I guess we shouldn't even bother with a separate window when everything stays the same and just recreate the appropriate map control on toggle.

**Comment by bradallred** [comment]
sounds like it would be less code anyway. we have `Window.ReplaceSubview` already

**Comment by lynxlynxlynx** [comment]
After some pains, it now works fine, but has two workarounds:
- one mentioned in the commit message, not very important
- had to add another button to make esc properly close the window, since we need to ensure some state gets reset (so I doubt fixing the TopWindowClosed complaint will change it)
