### ISSUE TITLE
[subviews] subspell selection silently doesn't work

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1092]
Tracked it down to 3d0a3cfe4 — we shouldn't be resetting ActionLevel, since the opcode (and some others) rely on it. We could only do it when it's not set to one of the problematic values, but that's ugly. Why isn't it done in the click handler instead?

**Comment by bradallred** [comment]
thats from 2018 so I'm not sure. I don't even know what "subspell selection" is. I doubt I'm opposed to doing things in Python tho if you know what needs to be done.

**Comment by lynxlynxlynx** [comment]
It's when spells cause the spell choice action bar to appear. Eg. for spell immunity, wild surging, that cleric spell that can create different weapons. Will play a bit and see.

**Comment by lynxlynxlynx** [comment]
I didn't have any luck attaching to the GC, but a fix in core works nicely:
http://sprunge.us/l6EbjY?diff

ESC doesn't, but it also doesn't bother me. Trying to bind "Return to game" to ESC and enhancing CloseTopWindow didn't do anything; I guess it's eaten up by the GC and would also need a change in core.

**Comment by bradallred** [comment]
the GC callback doesnt work because GC doesnt have `View::OnMouseUp(...)` anywhere. just add that and it should work.
