### ISSUE TITLE
[subviews] figured out when lambdas break

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1093]
I hit the same wtf-is-this-param problem in #1063 and investigated. The params indeed get changed when evaluated, but I couldn't figure out the true reason. To avoid problems, don't pass parameters to lambda callbacks.

Eg. the first is what broke and the second works fine:
```python
Button.SetEvent (IE_GUI_BUTTON_ON_PRESS, lambda mc = ms['MemoCount']: OnSpellBookUnmemorizeSpell (mc))
Button.SetEvent (IE_GUI_BUTTON_ON_PRESS, lambda: OnSpellBookUnmemorizeSpell (ms['MemoCount']))
```

Just noting it for later, since I don't want to need to retest all the GUIs again — using SetAction directly works: 
```python
Button.SetAction(lambda mc = ms['MemoCount']: OnSpellBookUnmemorizeSpell (mc), IE_ACT_MOUSE_PRESS, GEM_MB_ACTION, 0, 1)
```

It's a two part problem:
- we inject two more parameters (button, value)
- lambda parameters all have declared if any are used, so in the above case `lambda a, b, mc = ms['MemoCount']: ...` is ok

Handy decorators: https://stackoverflow.com/questions/6200270/decorator-that-prints-function-call-details-parameters-names-and-effective-valu

**Comment by bradallred** [comment]
After merging it would probably be worthwhile to go though the pain of removing the `EventMap`, it was only put in to provide backwards compatibility with exiting code. we can do it in stages (one map entry at a time) to ease the pain.

**Comment by bradallred** [comment]
for that matter, there are several other functions in GUIClasses.py that are commented with `# backwards compatibility` we may want to remove them or remove the comment on the ones we decide to keep.

**Comment by lynxlynxlynx** [comment]
I like the old/SetEvent stuff, since it's more concise and thus prettier and less error-prone. Default arguments could get us a clean button press, but nothig more. 

Things like CreateTextEdit and co can go, since they're there only to reduce merge noise and that won't be a problem any more soon.

**Comment by bradallred** [comment]
We can get rid of the `EventMap` and still have concise mappings:

instead of 
```
Button.SetEvent (IE_GUI_BUTTON_ON_PRESS, function)
```

being implemented in a map just write a method for it:
```
class GButton(GControl):
...
  def OnLeftMousePress(self, function)
    self.SetAction(function, IE_ACT_MOUSE_PRESS, GEM_MB_ACTION, 0, 1)
...
```

which becomes even more concise:
```
Button. OnLeftMousePress(function)
```

**Comment by lynxlynxlynx** [comment]
#1506  will also affect this.
