### ISSUE TITLE
[subviews] potential area animation regression

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1097]
In ar0201, just above Deionnara, there's a weird area animation looping. On master it stays still:
![image](https://user-images.githubusercontent.com/121515/101828394-c76a4980-3b31-11eb-94a7-611d418520a6.png)

@chilvence can you check what happened in the original?

**Comment by bradallred** [comment]
I imagine the behavior changed with #1049, but perhaps not

**Comment by chilvence** [comment]
Bizzare, that's actually the left arm from Coaxmetal by the look of it. There is nothing in the original: 
![nothing to see here](https://user-images.githubusercontent.com/1923867/101841927-dd323b80-3b3e-11eb-9c9c-78c68786ca71.png)

I can't even see anything in the area file in this location in NearInfinity

**Comment by lynxlynxlynx** [comment]
Thanks, this looks like something fun to investigate. I started from an original save, but then saved in gemrb to get there faster in both branches. I doubt it matters.

**Comment by lynxlynxlynx** [comment]
Nothing in its bcs or ini either, plus it doesn't appear to be an actor. 😆

**Comment by lynxlynxlynx** [comment]
Exciting, it's indeed the 0x3000 igarm char animation. At runtime, there are no new actors and none have that ID. There are no new area animations and all are just these flames. Same for other runtime structures.

Nice puzzle! The only idea I have left is to start selectively disabling drawing calls, since it's still not clear what the actual source is.

**Comment by lynxlynxlynx** [comment]
Ok, it *is* an actor, just the animation id is for the head =  0x4d00 for "Mortuary ghost". Luckily it has a few scripts set. One is missing, the other (for Dabuses) has a single hit: MRTGHOST.cre. Doh, I thought that was Deionnara in NI, but she's spawned through the ini. 

The CRE has STATE_DEAD set, all the appearance/schedule bits on and no expiry. However, it has both MC_REMOVE_CORPSE and MC_KEEP_CORPSE set, so I suspect we do the wrong thing in this silly combo case.

**Comment by chilvence** [comment]
Would that make this Shrödinger's Corpse?

**Comment by bradallred** [comment]
looks like we no longer handle `MC_REMOVE_CORPSE` at all

**Comment by bradallred** [comment]
the code handling `MC_REMOVE_CORPSE` seems to purposely ignore PST

```
//TODO: verify removal times
ieDword time = core->GetGame()->GameTime;
if (!pstflags && Modified[IE_MC_FLAGS]&MC_REMOVE_CORPSE) {
	RemovalTime = time;
	return true;
}
```

**Comment by lynxlynxlynx** [comment]
Yes, that was a bugfix. This doesn't matter here, since this code is never reached, since the actor is already properly dead. I'll fix it in AREImporter.
