### ISSUE TITLE
Brightness setting not restored when restarting game

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1098]
#### Bug description
When setting Brightness in game all is right but when you restart the game, brightness is not restored even if brightness slider is at the right place.

Tried to reproduce with contrast setting, but the slider does nothing....

Tested with IWD1 and BG2

For information : game files (read only) and save/cache/gem-icewind.ini (read/write) are not at the same place. gem-icewind.ini is modified by setting brightness in game.

GemRB version: master

**Comment by lynxlynxlynx** [comment]
Yeah, I don't think contrast is even implemented. Comparing the same run in the original and in gemrb makes it obvious we / SDL doesn't treat the values the same.

**Comment by bradallred** [comment]
it probably behaves differently for SDL 2

**Comment by lynxlynxlynx** [comment]
It's even more complicated. The SDL_SetWindowBrightness function adjusts gamma of the whole screen. On Windows it also resets the system's active color profile (ICC) and undoes some other display options like those available on the NVIDIA Control Panel. So it's not user friendly in that regard.

Plus it might not even work properly. The docs:
> Many platforms will refuse to set the display brightness in modern times. You are better off using a shader to adjust gamma during rendering, or something similar.

**Comment by bradallred** [comment]
we do have a shader so we could incorporate it there

**Comment by burner1024** [comment]
Yes, contrast setting does nothing, and brightness currently goes something like from 0 to 150%, while in original it's maybe 75% to 125%.
See [here](https://github.com/gemrb/gemrb/pull/1761#issuecomment-1354060397) for comparison screenshots. Unfortunately, GemRB looks noticeably darker, and raising brightness does not result in the same look as the original.

**Comment by burner1024** [comment]
Right... I re-checked, and with original set to minimal contrast colors look the same, so it's indeed contrast that makes the difference.

**Comment by burner1024** [comment]
Reading issue description again, the problem described there looks similar to #1762, the setting gets reset.

That's separate from other issues:
- Brightness has different limits in gemrb compated to original game.
- Brightness control only works in full screen mode.
- Contrast is not implemented at all.
