### ISSUE TITLE
[IWD1] Visual problem on some torch rendering

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1101]
#### Bug description
In severed hand (Position: ar5004 [1786.1903]), on the 2 left blue torch (see screenshot), top is partially missing.
And another yellow (Position: ar5004 [689.1671]), the left of the torch is missing.

perhaps others.

GemRB version: master / SDL2

#### Screenshots
![blue_torch](https://user-images.githubusercontent.com/55502325/101987546-f3521000-3c94-11eb-864a-94f99266ea16.png)
![yellow_torch](https://user-images.githubusercontent.com/55502325/101987581-3ad89c00-3c95-11eb-96c0-b0ab49ca4af9.png)

**Comment by lynxlynxlynx** [comment]
Please check if the same problem is also present on the subviews branch.

**Comment by FrElvire** [comment]
It seems OK with subviews branch but not used latest commit as branch seem broken for now. Will create a report for this

gemrb: /var/tmp/portage/games-engines/gemrb-6666/work/gemrb-6666/gemrb/plugins/SDLVideo/SDLVideo.cpp:628: void GemRB::SDLVideoDriver::RenderSpriteVersion(const GemRB::SDLSurfaceSprite2D*, uint32_t&, const GemRB::Color*): Assertion `tint' failed.
Aborted

Torch rendering is ok with git commit : 7e97f5e (old commit chosen randomly / 19 days ago)

So can be closed ?

**Comment by bradallred** [comment]
we keep these open and just tag them for a recheck after merge
