### ISSUE TITLE
[IWD1] potential hiding issue of shadowed elves

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1103]
#### Bug description
Not sure if this is a bug or if this spell can't do anything against shadowed Elven in Corellon Tower (severed hand) but when entering room, elves become invisible and after casting the spell they don't appear.

Position: ar5301 [799.701]

GemRB version: master

**Comment by lynxlynxlynx** [comment]
No, they are scripted to disappear or appear depending on some variables. GNTRPM1.BCS has the only code that can hide them.

So the real question is, should they disappear or not in the first place?

**Comment by FrElvire** [comment]
If I trust this video (EE) : https://www.youtube.com/watch?v=SThv2o8dlfE

Shadowed elves are already invisible when you enter, in gemrb they are visible when you enter and disappear one or two second later.

**Comment by lynxlynxlynx** [comment]
Something similar is visible in iwd2. I suspect we don't run their scripts soon enough. Worth checking if they have anything that should set IE_ENABLEOFFSCREENAI or similar to activate them sooner.
