### ISSUE TITLE
[IWD/HOW/Trials] Party shortly displayed after teleportation

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1106]
#### Bug description
When beginning Trials of the luremaster after talking to Hobart (ar9101 [1017.470]), he teleport us but after teleport animation, party shortly reappear (master/subviews).

Before re-appear we can always see something like shadow of party (see screenshot) -> subviews at least

GemRB version: master/subviews

#### Steps to reproduce
1. Go to Whistling Gallows tavern in Lonelywood
2. Talk to Hobart to be begin trials of the luremaster

#### Expected behavior
party doesn't re-appear in tavern after teleportation.
when party vanish, don't show shadow (??) of party member

#### Screenshots
![toftl](https://user-images.githubusercontent.com/55502325/102052043-d8db7c00-3de5-11eb-9afd-54071bbebfa1.png)

**Comment by FrElvire** [comment]
Tested with subviews branch with opengl enabled (this time) and no differences, same issues.

**Comment by lynxlynxlynx** [comment]
This looks fixed now. If you're forcing selection circle visibility, those remain, but that's it.

**Comment by FrElvire** [comment]
Maybe not perfect but perfectly on par with original, same ""issue"" (selection circle visibility). :+1:
