### ISSUE TITLE
Early logging erroneusly disabled 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1109]
My bad, surely a regression from b8a31ea9c4. Stdio gets fed, but doesn't print, so perhaps this will require splitting init.

**Comment by bradallred** [comment]
hmmmm, I didn't mean to step on your toes here, but I needed to fix the segfaulting. I dint even notice this issue until I came to find #231

**Comment by lynxlynxlynx** [comment]
No worries, one thing less on my plate. Didn't realize it's a crasher on mac. I see now we don't even run the minimal test on them:
https://github.com/gemrb/gemrb/actions/runs/429103457/workflow
What's the way to invoke gemrb on these platforms?

For this bug, also AddLogger needs exclusion, but I'll tackle it.
