### ISSUE TITLE
[subviews] Couldn't create animationfactory

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1110]
#### Bug description
During walk party's member are not always shown, here are the errors : 

[CharAnimations/ERROR]: Couldn't create animationfactory: chmb1 (6100)
[ResourceManager/ERROR]: Couldn't find 'cemt1.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: cemt1 (6301)
[ResourceManager/ERROR]: Couldn't find 'chmb1.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: chmb1 (6100)
[ResourceManager/ERROR]: Couldn't find 'cemt1.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: cemt1 (6301)
[ResourceManager/ERROR]: Couldn't find 'chmb1.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: chmb1 (6100)
[ResourceManager/ERROR]: Couldn't find 'cemt1.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: cemt1 (6301)
[ResourceManager/ERROR]: Couldn't find 'chmb1.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: chmb1 (6100)
[ResourceManager/ERROR]: Couldn't find 'cemt1.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: cemt1 (6301)
[ResourceManager/ERROR]: Couldn't find 'chmb1.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: chmb1 (6100)
[ResourceManager/ERROR]: Couldn't find 'cemt1.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: cemt1 (6301)
[ResourceManager/ERROR]: Couldn't find 'chmb1.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: chmb1 (6100)

Tested with IWD1 and BG2, ok with master (with no errors in console)

In both case same game files and same config file

#### Screenshots
![iwd1_missing_anim](https://user-images.githubusercontent.com/55502325/102456501-87c7c400-4041-11eb-9452-80c2ef0a52de.png)

**Comment by lynxlynxlynx** [comment]
Are you sure you tested with movement in the exact same path and direction?

**Comment by FrElvire** [comment]
This is not needed, it's visible on nearly every move.
For me it's a regression as with commit "7e97f5e" I don't see any problem.

**Comment by lynxlynxlynx** [comment]
Please attach a save then or even better, do a `git bisect` run to see which commit broke this. Nothing really comes to mind.

It goes basically like this:
```
git bisect start
git bisect bad # saying current version is bad
git bisect good 7e97f5e # saying this version is fine
# git then checkouts the version in between the two
# you build it, run it and test it, then run either
# git bisect good
# or
# git bisect bad
# and repeat the loop, until git tells you which commit caused the problem
```

**Comment by bradallred** [comment]
I don't know how you fingered 7e97f5e as the culprit. that is a change that could only affect the Console.

**Comment by FrElvire** [comment]
There's no need of save, you can reproduce by starting a new game (tried with iwd1), the problem is seen when a character need to avoid another (member of party or not), so a little harder to see with one character party. But with a full party it's all the time during move.

I won't have time to do a git bisect until next week

**Comment by FrElvire** [comment]
Finally I have found time :), the first "bad" commit is : 

384d5dac58305d2e5085fc4c1f6cda1d8e28da64 is the first bad commit
commit 384d5dac58305d2e5085fc4c1f6cda1d8e28da64
Author: Brad Allred <bradallred@me.com>
Date:   Sun Nov 29 14:35:20 2020 -0700

    Actor: rewrite SetRunFlags as SetIsRunning

 gemrb/core/Scriptable/Actor.cpp         | 14 ++++++++------
 gemrb/core/Scriptable/Actor.h           |  4 ++--
 gemrb/plugins/PSTOpcodes/PSTOpcodes.cpp |  2 +-
 3 files changed, 11 insertions(+), 9 deletions(-)

**Comment by FrElvire** [comment]
Removing the test on "run" in "void Actor::SetIsRunning(bool run)" (gemrb/core/Scriptable/Actor.cpp) seems to remove effect of this bug

```
void Actor::SetIsRunning(bool run)
{
//	if (run) {
		InternalFlags |= IF_RUNFLAGS;
//	} else {
		InternalFlags &= ~IF_RUNFLAGS;
//	}
}
```

It would be a miracle if this is the required fix but maybe it can save you some time..

**Comment by lynxlynxlynx** [comment]
Thanks, that commit looks quite bad — ignores other flags and they can now enable running ... then of course there's no data for running animations except in pst, so nothing gets drawn.
