### ISSUE TITLE
[subviews] UI problems at some resolutions

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1111]
#### Bug description
There are some missing buttons (select group, IA, ...), duplicate element ("clock") or misplaced (change text window format) at some resolutions, here are some examples

#### Screenshots
1280x720
![1280_720](https://user-images.githubusercontent.com/55502325/102457822-a3cc6500-4043-11eb-9395-f90fdcbf307e.png)
1920x1080
![1920_1080](https://user-images.githubusercontent.com/55502325/102457917-c78fab00-4043-11eb-8302-0702676cd1d0.png)

**Comment by lynxlynxlynx** [comment]
- Clock: only missing in guiw8's menuwindow; guiw10 has it on all MSGWINs, the other half being on the action win; guiw8 doesn't have it anywhere (let's add it to the menuwindow)!?
- Odd button under portraits: only in guiw (not really a button, that's part of the background) ... but missing the whole window 28 (AI, select all, rest)
- MTA min/max buttons: these are properly placxed in the CHU, we just don't move them as we expand the MTA

Yuck.

**Comment by bradallred** [comment]
the other games all have MTAs that only increase in size vertically so horizontal repositioning wasn't accounted for. Should be an easy tweak in `SetMWSize`

**Comment by lynxlynxlynx** [comment]
Closing. There's only one remaining problem, but it is a data one and cosmetic — the biggest resolutions will continue to have two clocks, since the unwanted one is baked into the background.
