### ISSUE TITLE
 NPCs won't approach player/start dialog after getting interrupted on their way to him

### ISSUE THREAD

**Issue by Northfear** [gemrb/gemrb#1112]
#### Bug description
NPCs that were supposed to approach the player and talk won't do so if they'll get interrupted somehow. The guard that confuses your party with bandits on the way to Nashkel sometimes can stop mid way before reaching the player and won't talk or walk towards him no matter what. The only way to start this conversation afterwards is to talk to him yourself.

GemRB version: 
Master after commit [4427650657256f603406db3c2fec6c01be9e5e8c](https://github.com/gemrb/gemrb/commit/4427650657256f603406db3c2fec6c01be9e5e8c)

#### Steps to reproduce
1. Go to area south of Beregost (ar3800)
2. The guard at the bottom of the map approaches the party to talk
3. Sometimes if you click to move to the new location just after he starts moving towards you, he would stop in place and won't move again (or move to his initial position). It usually takes a few tries to reproduce this for me.
4. He won't initiate the dialog himself even with party near him

#### Expected behavior
Previously NPCs were resuming their path to the party or would start a dialog in close proximity to the player.

**Comment by lynxlynxlynx** [comment]
This is flam5.cre. The random walk is a fallback in his default script, while the dialog starting one is the class one, so it should run first. So the main question is only why the payload is not called again if the first initdlg run is interrupted. The action itself is blocking, but perhaps it should also not be interruptible.

**Comment by lynxlynxlynx** [comment]
Ok, this will be as good as it gets, the original can also lose focus the same way.
