### ISSUE TITLE
[IWD1] Protection from evil or bless causes the character to disappear

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1114]
#### Bug description
After casting Protection from evil, affected character disappear, only one frame of many is displayed

In log :
[Unknown]: Cast spell: spin121
[Unknown]: Slot: 6
[Unknown]: Type: 2 (4 vs 4)
[Unknown]: Spellname: Protection From Evil
[Unknown]: Target: 5
[Unknown]: Range: 1
[ResourceManager/ERROR]: Couldn't find 'wqMS2ca.bam'.

Bless spell does the same : 

[Unknown]: Cast spell: sppr101
[Unknown]: Slot: 0
[Unknown]: Type: 0 (1 vs 1)
[Unknown]: Spellname: Bless
[Unknown]: Target: 4
[Unknown]: Range: 40
[ResourceManager]: Found 'spell.ids' in 'Override'.
[KeyMap]: Looking up key:  ( ) 
[ResourceManager]: Searching for 'A_PLATE4'...
[ResourceManager]: Found 'A_PLATE4.wav' in 'chitin.key'.
[ResourceManager]: Searching for 'A_PLATE7'...
[ResourceManager]: Found 'A_PLATE7.wav' in 'chitin.key'.
[ResourceManager]: Searching for 'CHA_fp05'...
[ResourceManager]: Found 'CHA_fp05.wav' in 'chitin.key'.
[ResourceManager]: Found 'cgtable.2da' in 'shared GemRB Unhardcoded data'.
[ResourceManager]: Found 'conjucg.bam' in 'chitin.key'.
[ResourceManager]: Found 'chff4ca.bam' in 'chitin.key'.
[ResourceManager/ERROR]: Couldn't find 'wqMMSca.bam'.
[ResourceManager/ERROR]: Couldn't find 'wqMD4ca.bam'.

BG2 does not appear to be affected

subviews/SDL2/OpenGL

**Comment by lynxlynxlynx** [comment]
Both spells use two opcodes related to drawing. Is this problem really subviews-only?

**Comment by FrElvire** [comment]
In master, no problem : 

![master_bless](https://user-images.githubusercontent.com/55502325/103173758-752d6600-485d-11eb-8c98-0ee1ca80b957.png)

**Comment by lynxlynxlynx** [comment]
Works fine for me on SDL1.
