### ISSUE TITLE
Conjure Fire Elemental, bad effect positioning

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1117]
#### Bug description
In iwd1 at least, When casting fire elemental some effect are not well placed. Fire elemental appear at selected position, it's just the effect

log : 

Unknown]: Cast spell: sppr605
[Unknown]: Slot: 0
[Unknown]: Type: 0 (1 vs 1)
[Unknown]: Spellname: Conjure Fire Elemental
[Unknown]: Target: 4
[Unknown]: Range: 30
[ResourceManager/ERROR]: Couldn't find 'wqMSLca.bam'.
[ResourceManager]: Searching for 'am9100l1'...
[ResourceManager]: Found 'am9100l1.wav' in 'chitin.key'.
[ResourceManager]: Found 'CFELEMP.2da' in 'chitin.key'.
[ResourceManager]: Found 'ES12FIRE.cre' in 'Override'.
[ResourceManager]: Found 'gnsummm.bcs' in 'chitin.key'.
[Actor]: No moverate.2da found, using animation (0xE228) for speed fallback!
[Actor]: No moverate.2da found, using animation (0xE228) for speed fallback!
[ResourceManager/ERROR]: Couldn't find 'wqMSLca.bam'.

Identical in master & subviews

Screenshot : 

![fireelemental](https://user-images.githubusercontent.com/55502325/103168305-2a4a2900-4832-11eb-98ce-b97f25be18d9.png)

**Comment by lynxlynxlynx** [comment]
How does it look on master? I doubt it's a subviews issue.

**Comment by FrElvire** [comment]
Yes it's not limited to subviews, present in master too.

**Comment by bradallred** [comment]
this is most definitely _not_ a subviews issue. This crashes for me in master too.
