### ISSUE TITLE
Some spell effects are hidden by decors

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1119]
#### Bug description
Here at beginning of trials of luremaster (Position: ar9700 [1332.1063]) when casting horror (you can cast something else but very visible with this spell effect), part of the effect is hidden by wall of house.

master & subviews

![spell_effect_hidden](https://user-images.githubusercontent.com/55502325/103168731-0a1c6900-4836-11eb-904b-edaeaa462abd.png)

**Comment by lynxlynxlynx** [comment]
How does it look on master?

**Comment by FrElvire** [comment]
Yes it's not limited to subviews, present in master too.

**Comment by bradallred** [comment]
the actor effects use the same stencil as the actors so it seems like the actor is considered behind the wall.

FYI, your screenshots for issues like this would be more helpful if you hit ctrl+5 enough times to show the polygons+bounding box+baseline

**Comment by bradallred** [comment]
the only thing that jumps out at me as possibly wrong is `Actor::GetElevation`

**Comment by bradallred** [comment]
the problem is this `ScriptedAnimation` is not actually attached to the actor. I don't know how that is decided tho.

**Comment by lynxlynxlynx** [comment]
What do you mean by attached?

**Comment by bradallred** [comment]
I mean it is not part of `Actor::vvcShields` or `Actor::vvcOverlays`

it also doesn't have the `IE_VVC_NOCOVER` bit set so that is why it gets occluded

**Comment by lynxlynxlynx** [comment]
Well yeah, from the looks of it it's just the casting animation, so any necromantic spell (if that's the correct school) should net the same results. We construct it in fx_casting_glow, so we can add any flags we want.

**Comment by bradallred** [comment]
I just assumed casting animations were attached to the actor so that they could inherit the actors stencil and flags.

The problem is just unilaterally setting `IE_VVC_NOCOVER` will just invert the problem and then the casting animation will always be in front of the walls. So why aren't casting gfx attached to the actor?

**Comment by lynxlynxlynx** [comment]
vvcShields and vvcOverlays are there just to work around hardcoded logic in the originals with something a bit less hairy. Also unlike the shields/overlays, the casting animations don't come in upper and lower halves, to be treated differently (in this case it's necrocg.bam). It's like blur or mirror image, except that we treat those specially when drawing.

**Comment by bradallred** [comment]
my point is that casting glows seem like they ought to be occluded with the actor and the best way to do that AFIK is insert it into `vvcOverlays`.

**Comment by lynxlynxlynx** [comment]
You can give it a shot to see if it works. There's a lot of code to check, so it's easier to be pragmatic.

**Comment by bradallred** [comment]
ok, lets try it out

**Comment by bradallred** [comment]
One side effect of this change is that the casting animation stays with the actor on move... I don't know how the originals works. If the actor moves when casting a spell what is supposed to happen?

**Comment by lynxlynxlynx** [comment]
The spell fizzles, since you lose concentration. So the animation should stop - switch to the fade phase. Related #1121

**Comment by bradallred** [comment]
I understand that it fizzles and stops. I'm interested in knowing if the fizzling animation is supposed to follow the actor or not.

**Comment by lynxlynxlynx** [comment]
No, it stays where it was. And I've checked with iwd2: the animation duration isn't actually affected.

**Comment by bradallred** [comment]
so it seems like we need to attach it to the `Actor` for occlusion purposes, but stop updating the animation position to the actors position. Problem is, I don't know if there is a way to distinguish vex that should follow the actor vs not. we may need a new flag.

**Comment by bradallred** [comment]
Could somebody test something like fire shield at this exact location in the original and let me know if it gets occluded or not?

**Comment by lynxlynxlynx** [comment]
I have it in my list. First need to resolve the regression and pull that in, then check a suspicious bit in a0eeecc322, then this.

**Comment by lynxlynxlynx** [comment]
No fireshield in iwd. Somewhat mixed results, but it clearly has the same problems sometimes:
![image](https://user-images.githubusercontent.com/121515/104056966-98f39300-51f1-11eb-9c5a-425f07af84ea.png)
![image](https://user-images.githubusercontent.com/121515/104056985-9f820a80-51f1-11eb-84bc-744400b6caca.png)
![image](https://user-images.githubusercontent.com/121515/104057024-b0cb1700-51f1-11eb-8bc7-4017280bc8fa.png)
![image](https://user-images.githubusercontent.com/121515/104057059-c6d8d780-51f1-11eb-931b-58c0650ef659.png)
![image](https://user-images.githubusercontent.com/121515/104057104-d821e400-51f1-11eb-8093-8f1841e7ead4.png)
![image](https://user-images.githubusercontent.com/121515/104057179-fc7dc080-51f1-11eb-87f5-4b5c479f90dc.png)
![image](https://user-images.githubusercontent.com/121515/104057262-23d48d80-51f2-11eb-9e91-96f44985dbc9.png)

**Comment by bradallred** [comment]
interesting results. glad we can do better than the originals here, but we will need some new flag then to prevent them from following the actor

**Comment by lynxlynxlynx** [comment]
Just use another bit below IE_VVC_FREEZE — we construct these manually, so we can mark them however we want.

**Comment by bradallred** [comment]
I dont know where the code is that cancels the spell on move. Seems like we could avoid a new custom bit if we could distinguish the fizzle... I dont know if the fizzle is a separate VVC or a phase of the regular casting animation

**Comment by lynxlynxlynx** [comment]
There is no fizzle animation, it just plays out all the same. The casting cancellation is simply a result of the action being cancelled by whatever else was ordered clearing the queue and adding its own action. In this case it would be the Scriptable::Stop call from GameControl::ExecuteMovement.
