### ISSUE TITLE
[IWD1] Berserk warrior invocation if not created under cursor 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1120]
#### Bug description
When invoking Berserk warrior with Bardic Horn of Valhalla, Berserk warrior is not created under cursor but next to summoner.

if needed, log : 

[ResourceManager]: Searching for 'valhala'...Unknown]: Use item: bardic
[Unknown]: Extended header: 0
[Unknown]: Attacktype: 3
[Unknown]: Range: 20
[Unknown]: Target: 4
[Unknown]: Projectile: 0
[Control/WARNING]: Nested event handlers are not supported!
[ResourceManager]: Searching for 'A_LTHR4'...
[ResourceManager]: Found 'A_LTHR4.wav' in 'chitin.key'.
[ResourceManager]: Searching for 'valhala'...
[ResourceManager]: Found 'valhala.wav' in 'chitin.key'.
[ResourceManager]: Found 'berserk.cre' in 'chitin.key'.
[ResourceManager]: Found 'gnbzkwar.bcs' in 'chitin.key'.
[Actor]: No moverate.2da found, using animation (0x6100) for speed fallback!
[Actor]: No moverate.2da found, using animation (0x6100) for speed fallback!
[ResourceManager]: Found 'wqLH0g1.bam' in 'chitin.key'.
[ResourceManager]: Found 'wqLS1g1.bam' in 'chitin.key'.
[GameScript]: Displaying string on: berserk
[ResourceManager]: Found 'valhala.wav' in 'chitin.key'.
[ResourceManager]: Found 'berserk.cre' in 'chitin.key'.
[ResourceManager]: Found 'gnbzkwar.bcs' in 'chitin.key'.
[Actor]: No moverate.2da found, using animation (0x6100) for speed fallback!
[Actor]: No moverate.2da found, using animation (0x6100) for speed fallback!
[ResourceManager]: Found 'wqLH0g1.bam' in 'chitin.key'.
[ResourceManager]: Found 'wqLS1g1.bam' in 'chitin.key'.
[GameScript]: Displaying string on: berserk

**Comment by lynxlynxlynx** [comment]
Are you sure this is not the expected behaviour?

**Comment by FrElvire** [comment]
No I'm not sure but from what I see when you have to select a place for a spell, the spell is targeted at this place even with objects that allows to make invocations. But indeed it's not sure at all...

**Comment by lynxlynxlynx** [comment]
Tried in the original and you're right. But the summoning effect has target:self set so grrr.
