### ISSUE TITLE
[HoW] missing projectile RETRIB2 

### ISSUE THREAD

**Issue by fizzet** [gemrb/gemrb#1122]
When Wylfdene/Icasaracht strikes down the seer in AR9201 (cutscene `bcscut2a.bcs`) he/she does so using `SPIN140`. The effect in this spell uses projectile 345 (-1) which `gemprjtl.ids` has as `RETRIB2`. We currently don't have that projectile, however, thus missing out on a few graphical effects (visible in this video https://youtu.be/hfzGyM1jkz0?t=936, at about 15:35).

**Comment by lynxlynxlynx** [comment]
Is it just that white circular flash (reminds of the one for fx_transparency)? IIRC we display the piercing and dragon animations already.

**Comment by fizzet** [comment]
Yes, the piercing and dragon aren't from the projectile. Those work fine.

**Comment by lynxlynxlynx** [comment]
It's so close it's barely perceptible, since we apply the payload anyway — just a quick orby travel projectile is missing.

**Comment by lynxlynxlynx** [comment]
Maybe there are some artifacts in the video (what's with the light spot?), but when casting in the original, it's basically magic missile with these glowing orbs. Same as Mordenkainen's Force Missiles (spwi430) ... :)
