### ISSUE TITLE
[IWD1/TOLM at least] Resist fear doesn't seem to protect against fear

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1123]
#### Bug description
It's maybe not a bug and just something I don't understand correctly. Now it's done, when encountering with harpies "resist fear" spell doesn't protect you from fear but "Remove fear" spell does the job. It doesn't fell coherent.

Position: ar9710 [725.806]

spell : 

[Unknown]: Cast spell: spwi210
[Unknown]: Slot: 0
[Unknown]: Type: 1 (2 vs 2)
[Unknown]: Spellname: Resist Fear
[Unknown]: Target: 4
[Unknown]: Range: 30

[Unknown]: Cast spell: sppr108
[Unknown]: Slot: 2
[Unknown]: Type: 0 (1 vs 1)
[Unknown]: Spellname: Remove Fear
[Unknown]: Target: 4
[Unknown]: Range: 30

GemRB version: master

with resist fear 
![fear](https://user-images.githubusercontent.com/55502325/103464069-6cdb9c00-4d31-11eb-86cb-009afbddf69c.png)

after casting remove fear
![remove_fear](https://user-images.githubusercontent.com/55502325/103464072-71a05000-4d31-11eb-9667-4072d41bdb42.png)

**Comment by lynxlynxlynx** [comment]
I guess it's spin166 (harpy wail), which does use panic (fx_set_panic_state). However, resist fear adds immunity to the same opcode, so it looks like something does go wrong.

As an aside, the wail panic opcode doesn't set param2 to 1, as one would perhaps expect from the docs (either by name or by function).

**Comment by fizzet** [comment]
This is probably just a cosmetic issue. If you hit Ctrl+m on the party member in question, does the list of effects actually include `State: Panic`? It doesn't in my tests. But "Resists Fear" does not protect against the Icon Display opcode so the "Panic" icon is shown even though the actual panic effect is correctly resisted.

**Comment by FrElvire** [comment]
No it's not only a cosmetic issue, here is the result of Ctrl-M

EFFECT QUEUE:
  0: 0x00: ACVsDamageTypeModifier (2, 16) S:elfchan
  1: 0x17: MoraleModifier (10, 1) S:sppr108
  2: 0x07: Color:SetPalette (98, 5) S:elfchan
  3: 0x07: Color:SetPalette (93, 4) S:elfchan
  4: 0x07: Color:SetPalette (27, 0) S:elfchan
  5: 0x00: ACVsDamageTypeModifier (2, 8) S:elfchan
  6: 0x00: ACVsDamageTypeModifier (-2, 1) S:elfchan
  7: 0x3b: StealthModifier (-10, 0) S:elfchan
  8: 0x5a: OpenLocksModifier (-5, 0) S:elfchan
  9: 0x5b: FindTrapsModifier (-5, 0) S:elfchan
 10: 0x5c: PickPocketsModifier (-20, 0) S:elfchan
 11: 0x1c: ColdResistanceModifier (20, 0) S:elfchan
 12: 0x8e: Icon:Display (0, 25) S:elfchan
 13: 0x07: Color:SetPalette (30, 53) S:helmsun
 14: 0x07: Color:SetPalette (25, 48) S:helmsun
 15: 0x00: ACVsDamageTypeModifier (1, 0) S:helmsun
 16: 0x06: CharismaModifier (1, 0) S:helmsun
 17: 0x07: Color:SetPalette (63, 21) S:ulxbw3b
 18: 0x07: Color:SetPalette (15, 20) S:ulxbw3b
 19: 0x07: Color:SetPalette (27, 16) S:ulxbw3b
 20: 0x01: AttacksPerRoundModifier (2, 1) S:ulxbw3b
 21: 0x105: Protection:Opcode2 (0, 24) S:spwi210
 22: 0x17: MoraleModifier (10, 1) S:spwi210
 23: 0x8e: Icon:Display (0, 37) S:spwi210
 24: 0xae: PlaySound (0, 0) S:spwi210
 **25: 0x2d: State:Stun (0, 0) S:spin166**
 26: 0x8e: Icon:Display (0, 36) S:spin166
 **27: 0x2d: State:Stun (0, 0) S:spin166**
 28: 0x8e: Icon:Display (0, 36) S:spin166

**Comment by fizzet** [comment]
Stun is different from Panic, though. Resist Fear does not protect against Stun.

**Comment by lynxlynxlynx** [comment]
Yeah, they should've used a protection-from-spell opcode to make sure everything is skipped - if that was the desired outcome.

**Comment by FrElvire** [comment]
I just check original and it's a little bit different, nobody get stun, only panicked.

Resist fear spell protect and/or cure from this state.

**Comment by fizzet** [comment]
Hm, no idea how that's supposed to happen -- unless stun in IWD works differently than what we have implemented...

**Comment by lynxlynxlynx** [comment]
The priest Remove fear (sppr108) specifically removes Harpy wail (spin166) on first application. Resist fear (spwi210) does nothing like that. Both just protect against panic. The wail does both stun and panic. I haven't retested yet, but I suspect we shouldn't just kill the effect, but the whole spell in iwd. Currently check_resistance doesn't facilitate that, so it's handled like any other blocker.
