### ISSUE TITLE
Strange placement of crosshair when going downstair

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1124]
#### Bug description
I think screenshot says all, on second screenshot crosshairs are not on stair as expected.

Position: ar9710 [725.806]

GemRB version: master

#### Screenshots
![stair1](https://user-images.githubusercontent.com/55502325/103464289-cf816780-4d32-11eb-99d9-6798e56cdd89.png)
![stair2](https://user-images.githubusercontent.com/55502325/103464296-d90acf80-4d32-11eb-98a4-a17c072e6ab7.png)

**Comment by lynxlynxlynx** [comment]
I wouldn't consider this a bug. The stairs have an activation radius and the party tries to go the shortest distance to satisfy it. Are you saying they don't trigger from there?

**Comment by FrElvire** [comment]
No problem with trigger. I suspected it was expected but in case it was a bug... so can be closed ?

**Comment by lynxlynxlynx** [comment]
We could decrease the range, but with this layout, there will always be a "failure" point. So yeah, let's just close.
