### ISSUE TITLE
[TOLM] Missing animation at start 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1125]
#### Bug description
If I trust video mentioned in #1107, at 26:18 there are some animation missing when party appear (same animation when leaving HOW (works ok), 26:13 in video )

GemRB version: master

#### Steps to reproduce
1. Talk to Hobart (ar9101 [1017.470]),
2. See animation
3. appear at start of TOLM but no animation

![appear_anim](https://user-images.githubusercontent.com/55502325/103464471-305d6f80-4d34-11eb-93f3-ecf7be09e8db.png)

**Comment by lynxlynxlynx** [comment]
Wait, are you saying you get this blue animation when exiting the tavern, but not when arriving?

Anyway, took another look at the spell, area and scripts involved, but haven't found the source. The projectile used is also 1 - none, so huh.

Thanks for all the reports btw!

**Comment by FrElvire** [comment]
Yes that's it, blue animation when exiting but not when arriving .

Same, thanks for your help to make better reports.

**Comment by lynxlynxlynx** [comment]
Ah, it's actually portalh.bam from our portalh.pro. Now to find out what creates it ...

**Comment by lynxlynxlynx** [comment]
The animation effects actually get added and run normally, but at the party locations from the area before, so they're off-screen once in the new area. We need to re-set it safely somehow.
