### ISSUE TITLE
[subviews] almost stuck in ar2001 due to viewport

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1127]
It's a small area and at 1280x1024 it pretty much fits into the screen. You have to minimize the msgwin to be able to see pcs on entry and can barely escape — see the blue sliver on the left bottom:
![image](https://user-images.githubusercontent.com/121515/103479865-e5456a00-4dd0-11eb-8fc4-c6029c690cb9.png)

Does the size makes us skip the ability to scroll to the border? On master the window was always below the area limit.

**Comment by bradallred** [comment]
we are supposed to add extra from the message window in `GameControl::MoveViewportTo`

**Comment by lynxlynxlynx** [comment]
It only happens at this resolution of the standard few and not in bigger areas, so I suspect it's related to the viewport size relative to the area size.
