### ISSUE TITLE
[subviews] journal chapter locked

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1131]
The buttons aren't clickable because the TA resizes to match the scrollbar and covers them:
![image](https://user-images.githubusercontent.com/121515/103680400-6bef7800-4f86-11eb-9202-33d499a4b06d.png)

We can't just disable that part of MergeTextAreaAndScrollbar, since the scrollbar graphic is baked into the bg and the recreated scrollbar then appears to have two ends:
![image](https://user-images.githubusercontent.com/121515/103680418-71e55900-4f86-11eb-9078-b6509f5de892.png)

We can't make the recreated scrollbar have no/transparent starting frame, since users would then not know where to click and the baked one is not reactive. As an aside, even on master you can't use the whole height of the scrollbar.

What to do? Is it really necessary to force the two heights to match? Can we somehow keep pushing the TA to the bg, so the chapter buttons get a chance to receive the events?

**Comment by bradallred** [comment]
just move the buttons to be subviews of the TA

```
button = Window.RemoveSubview(leftButton)
TextArea.AddSubview(button)
button = Window.RemoveSubview(rightButton)
TextArea.AddSubview(button)
```

**Comment by bradallred** [comment]
Actually, it looks like we have `ReparentSubview` for this exact purpose already

**Comment by lynxlynxlynx** [comment]
This has no effect:
```diff
index 38f7d0b62..2827834a7 100644
--- a/gemrb/GUIScripts/iwd/GUIJRNL.py
+++ b/gemrb/GUIScripts/iwd/GUIJRNL.py
@@ -44,10 +44,14 @@ def InitJournalWindow (JournalWindow):
        #StartYear is the year of the lowest ingame date to be printed
        StartYear = Table.GetValue("STARTYEAR", "VALUE")
 
+       TextArea = JournalWindow.GetControl (1)
+
        Button = JournalWindow.GetControl (3)
+       Button = JournalWindow.ReparentSubview (Button, TextArea)
        Button.SetEvent (IE_GUI_BUTTON_ON_PRESS, JournalPrevSectionPress)
 
        Button = JournalWindow.GetControl (4)
+       Button = JournalWindow.ReparentSubview (Button, TextArea)
        Button.SetEvent (IE_GUI_BUTTON_ON_PRESS, JournalNextSectionPress)
 
        Chapter = GemRB.GetGameVar("chapter")
```

**Comment by bradallred** [comment]
it works now since 13622c0
