### ISSUE TITLE
[subviews] yapi crash

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1132]
Again in Channel, this time by Mythos casting in ar3501. Just move up and end the dialog. He will retreat and cast a spell (let him), boom.
![image](https://user-images.githubusercontent.com/121515/103685588-cb04bb00-4f8d-11eb-9e6d-8b61921e4e68.png)

[000000001-Quick-Save.zip](https://github.com/gemrb/gemrb/files/5771953/000000001-Quick-Save.zip)

**Comment by bradallred** [comment]
ugg. the problem appears to be that `ScriptedAnimation::Draw` performs some state changes... gonna have to separate that like had to be done with `Actor`

**Comment by bradallred** [comment]
That should fix it. Hopefully we are running out of unaccounted for tidbits 😄

**Comment by lynxlynxlynx** [comment]
Already got a decent way into iwd, so yeah, looking good.

**Comment by lynxlynxlynx** [comment]
Already got a decent way into iwd, so yeah, looking good.
