### ISSUE TITLE
[subviews] PNGImporter eating pixels

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1135]
Demo inventory subviews vs master:
![image](https://user-images.githubusercontent.com/121515/103948139-946ba380-5139-11eb-8bde-b0864ffb9169.png)

The portrait png is 210x330, the same as the button control size. And it's full of color, like you see on master. What baffled me when investigating is, that the size is actually correct on subviews — on master it somehow visually shrinks about 45px. If you just look at the art, you can see both are of the same size.

But, it shouldn't have any black. Not that it should be transparent like on master, but the image should be rendered fully, taking all that space. So I guess something goes wrong in PNGImporter that we end up with a shorter sprite and the rest is just a difference in how we handle lack of data.

**Comment by bradallred** [comment]
is this a paletted PNG?

**Comment by lynxlynxlynx** [comment]
Eh. Had to open it to check. It is, but I also see I left transparency in to maintain the original aspect ratio.

So it is simpler — only about the transparency. Do we also expect only <=255 colors in indexed pngs too?

**Comment by bradallred** [comment]
I think the problem is the `// TODO: colorkey` this probably works on master by luck
