### ISSUE TITLE
[subviews] demo transparency issue on modals

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1136]
In the demo, we have a cursor set that is partially transparent. It works fine almost everywhere except in some subwindow of the inventory window. It works in the color picker, but not in the item info window or item amount window. They all appear to be modal.

![image](https://user-images.githubusercontent.com/121515/103947375-41ddb780-5138-11eb-9c80-a8344cfdeafe.png)
![image](https://user-images.githubusercontent.com/121515/103947403-499d5c00-5138-11eb-9aa1-f3bc5b61fa36.png)

There are two aspects — why is creating holes in the upmost window? It also breaks in the modal shadow area.

The color picker wiindow manually disables the inventory window, which is a bit lame — should just be a modal instead — but the disabling doesn't affect this bug, since even without it, it has no problems. However marking it modal does cause the same issues as for the other windows, so at least it makes sense.

**Comment by bradallred** [comment]
SDL2 doesn't appear to be affected

**Comment by bradallred** [comment]
in part this is a data problem. The alpha value of those pixels is 1 instead of 0 so we miss our special case:

```
if (SRCALPHA && src.a == 0) {
    return;
}
```

tho we should handle blending alpha == 1 so something else is wrong

**Comment by lynxlynxlynx** [comment]
Thanks, it's fine within the window now. Still not in the modal shadow area:
![image](https://user-images.githubusercontent.com/121515/103988213-fc4bd980-518d-11eb-8b2a-3fa9b1abfe5c.png)

**Comment by bradallred** [comment]
I don't know how this hasn't been a problem for other things... regardless, fixed now

**Comment by lynxlynxlynx** [comment]
Beautiful. :)
