### ISSUE TITLE
[subviews] text container shrinking?

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1139]
In bg2 (but not in how), the number of attacks is not displayed any more in GUIREC. The text is generated just fine and while the view/TA matches the background size, the text container is narrower and I guess it hits a corner case, since the number (1) doesn't wrap:
![image](https://user-images.githubusercontent.com/121515/104246470-58e91600-5466-11eb-99e1-97806a230ef7.png)

Without looking, the description is delineated by paragraphs — do subsequent ones inherit the width of the first one?

Setting IE_GUI_VIEW_RESIZE_WIDTH on the TA didn't help.

**Comment by bradallred** [comment]
I believe `[p]` blocks always take up the entire width minus margins. Is the green area there just an erroneously set margin? we should probably change the coloring so margins stand out too...

if it were just a margin thing you would be able to scroll horizontally tho (shift+mousewheel)

**Comment by lynxlynxlynx** [comment]
It's now yellow, so I guess the margin from merging the scrollbar is to blame.

**Comment by bradallred** [comment]
scrollbars just by themselves only add margin when there was space between the TA and SB in the CHU. I don't know where the margin here is from.

**Comment by lynxlynxlynx** [comment]
It looks about one scrollbar width too much, but I can take a look at this as well — you have so many reports already assigned to yourself.

**Comment by bradallred** [comment]
thanks. sounds like a minor change in `MergeTextAreaAndScrollbar` then.
