### ISSUE TITLE
[bug] When hiding in shadow your NPCs will not give proper comment

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#114]
**Describe the bug**
BG2, BGT. When hiding in shadow your NPCs will not give proper comment "Now you see me, now you don't."﻿ ~ _Imoen_

**Comment by lynxlynxlynx** [comment]
We call VB_HIDE, but it finds an invalid strref in the actor, so there's no text or sound displayed.

Eg. the Imoen from the shipped TOTSC save has -1 there ... but looking at the shipped files, bg1 just didn't have these soundsets. Need to try bg2 though.

**Comment by lynxlynxlynx** [comment]
Works for me in bg2, just tested with Minsc. I guess you have the Imoen from bg1, so she's missing the soundset entries.
