### ISSUE TITLE
[subviews] actor overlay & mirror image drawing bugs

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1141]
I've fixed fireshield, but noticed that some of the overlays aren't drawn if others are used. 

~To retest:
spell turning + fireshield: ok
spell turning +  globe of invulnerability: ok, but globe too transparent
globe of invulnerability makes the actor not be rendered or partly with mirror images: ok
globe of invulnerability + fireshield again draws only half: ok
globe of invulnerability / fireshield + spell turning doesn't draw the disc: ok
AddressSanitizer: alloc-dealloc-mismatch (INVALID vs operator delete) if you ctrl-r on the combos (pcf_bounce calls RemoveVVC): fine now
7 eyes: ok, but too transparent
perhaps unrelated regression: the actor is invisible for a few moments after casting spell turning, spell deflection or some others.~

TODO:
- [x] not all mirror images are always rendered, even when there's no interference - even just moving the viewport changes the count drawn
- [x] as noted on the commit reverting the change c9a1d22: making overlays globally tinted is bad; also needs BLIT_COLOR_MOD removed to restore fireshield, but haven't tested any others.
- [x] globe of invulnerability and 7 eyes are too transparent

![image](https://user-images.githubusercontent.com/121515/109549322-1e970f00-7ace-11eb-9377-6c1bd9a63833.png)
![image](https://user-images.githubusercontent.com/121515/109549369-2e165800-7ace-11eb-93ce-6cd0365ce50f.png)

**Comment by bradallred** [comment]
this is a good collection of test cases. I imagine more "tint"/flag conflicts

**Comment by lynxlynxlynx** [comment]
Part of this is already better, but I noticed transparency issues — we draw the globes more translucent, that's why they're barely noticeable in combination with fireshields:
![image](https://user-images.githubusercontent.com/121515/109434339-1cbd4500-7a15-11eb-8ee1-354b756a7102.png)
![image](https://user-images.githubusercontent.com/121515/109434347-23e45300-7a15-11eb-87d1-b74487f6a2f9.png)

**Comment by bradallred** [comment]
I cant repro the globe. I've tried both backends. gotta be an alpha modded tint presumably from the environment. a night only thing?

**Comment by lynxlynxlynx** [comment]
Ok, fixing the tint and removing BLIT_COLOR_MOD doesn't fix the translucency, but the other overlays look fine. The problem can be seen during daytime without any weather, but it's still subtle, so a side by side comparison is easiest. For the globe, the vvc only has the blended bit on.

Is it ok to remove the BLIT_COLOR_MOD bit for overlay drawing — why was it added?

**Comment by bradallred** [comment]
it wasn't "added" passing a tint requires use of `BLIT_COLOR_MOD` or `BLIT_ALPHA_MOD` to do anything with the tint. since we are passing a tint we clearly intend to use one or both of those. master doesn't distinguish between these 2 things and `BLIT_TINTED` implies both. We just don't want the "global" tint (terrible name choice obviously) to apply to `ScriptedAnimation`s

**Comment by lynxlynxlynx** [comment]
Just using the untouched tint wasn't enough, that's why I started playing with the flags. Didn't try removing BLIT_ALPHA_MOD though:
http://sprunge.us/nwaX9W?diff

**Comment by lynxlynxlynx** [comment]
Hmm, upon further testing 7 eyes don't look so bad and I found out there are other problems in play for the globe — when intersecting other drawing boxes. See this demo:
![globe](https://user-images.githubusercontent.com/121515/111025363-e653d280-83e3-11eb-9742-42da4945b293.gif)
If if it's not obvious, it's almost perfectly drawn only when the pc's box is white or pink.

**Comment by lynxlynxlynx** [comment]
Testing in SDL1 shows a similar problem. Night, day, original (below and above the base line):
![sdl1](https://user-images.githubusercontent.com/121515/113823845-653bf100-977f-11eb-961f-425337c45946.jpg)
Weather doesn't affect it in either case, which is good.
It looks like the drawing has different problems between the two backends, only while within the box:
- on SDL1: not transparent / blended enough
- on SDL2: too transparent / blenede

**Comment by lynxlynxlynx** [comment]
This fixes the actor being treated as behind a wall too often, but the drawing issue remains while still behind a wall. Have to double check how that looked in the original.

**Comment by lynxlynxlynx** [comment]
Disabling the stencil flag bits when drawing the vvc helps, but of course then there's no dithering. Appears like the problem is we don't use the stencil, treating the whole animation as being the same.

**Comment by lynxlynxlynx** [comment]
Looks fine now for both backends. :)
