### ISSUE TITLE
[subviews/BG2 only ? ] leaving a zone SDL2+OGL

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1145]
#### Bug description
When leaving a zone in BG2, there's an error, and you can't select another zone after that.

In HOW all seems OK

With SDL2 only, I don't see this problem

WorldMap/DEBUG]: Updated Area visibility: ar0020 (accessible and visible)
[WorldMap/DEBUG]: Updated Area visibility: ar0900 (accessible and visible)
[WorldMap]: CalculateDistances for Area: ar0500
[GUIScript/ERROR]: Runtime Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "../gemrb/GUIScripts/GUIMA.py", line 192, in OpenTravelWindow
[Python/ERROR]:     WorldMapWindowCommon (Window, GemRB.GetVar ("Travel"))
[Python/ERROR]:   File "../gemrb/GUIScripts/GUIMA.py", line 214, in WorldMapWindowCommon
[Python/ERROR]:     WorldMapControl = Window.ReplaceSubview (4, IE_GUI_WORLDMAP, Travel, "floattxt")
[Python/ERROR]:   File "../gemrb/GUIScripts/GUIClasses.py", line 161, in ReplaceSubview
[Python/ERROR]:     return self.CreateSubview(id, ctype, frame, args)
[Python/ERROR]:   File "../gemrb/GUIScripts/GUIClasses.py", line 165, in CreateSubview
[Python/ERROR]:     created = self.AddSubview(view) # this will move the reference into the our window's group
[Python/ERROR]:   File "../gemrb/GUIScripts/MetaClasses.py", line 44, in handler
[Python/ERROR]:     raise type(e)(str(e) + "\nMethod Docs:\n" + str(f.__doc__))
[Python/ERROR]: RuntimeError: Cannot construct object with null ref.
Method Docs:
AddSubview(superview, subview [,siblingView=None, id=-1])

Adds a view to a new superview in front of siblingView (or the back if None), removing it from its previous superview (if any).
You can pass id to assign a new id to the view. Do this if current id would conflict with an existing id in the new window.

If it wasn't a general issue in BG2, you can use this save :
[000000013-bridge disctrict - fin.zip](https://github.com/gemrb/gemrb/files/5861858/000000013-bridge.disctrict.-.fin.zip)

**Comment by bradallred** [comment]
seems we have 2 map windows active at once for some reason.
