### ISSUE TITLE
Can't select a new zone after switching map view. 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1147]
#### Bug description
When on world map, switching to local map and switch again to world map, you can't select a zone anymore

Subviews : click on the map icon or type 'M'
![map_icon](https://user-images.githubusercontent.com/55502325/105627732-df273400-5e38-11eb-830a-fc7a967d6f5f.png)
and again to return to world map.

Master : type 'M' (clicking on the map icon quit map window so no problem), on the local map click on the map icon to return to world map.

From this point you can't select a zone, you have to quit map

GemRB version: master or subviews

#### Expected behavior
When changing zone you shouldn't be able to switch between world map and local map.

**Comment by bradallred** [comment]
this is easy to fix. If we want to be able to switch between map windows then the `ACTION_WINDOW_CLOSED` that resets the `Travel` variable just needs to be moved to the "main" map window. If we don't want map toggling then just disable/delete the button when `Travel` is set.

**Comment by lynxlynxlynx** [comment]
Yeah, easiest to just disable it. In bg1, it quit the window if it was in travel mode.
