### ISSUE TITLE
[subviews] trying to manually move it (while the viewport is moving) prevents all later movement

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1148]
Scripted moves of the viewpoint work pretty fine. There's some jitter if you try to force a move, but that's minor. MoveViewPoint works as expected, however MoveViewObject can break the game.

If you try to move the viewport away while the action is scrolling it, you won't be able to move it again once it's done. Not with the mouse, not with the kb. It immediately jumps back when trying, so I guess the goal point gets messed up and persists too long.

To reproduce, just scroll away in an area, run `ExecuteString("MoveViewObject(Player1,2)")`, try to scroll away, wait for the move to finish and then try to scroll anywhere.

**Comment by bradallred** [comment]
Cutscene/Dialog mode both disable user inputs so the jitter shouldn't be an issue IRL.

**Comment by lynxlynxlynx** [comment]
The cutscene may end before the move finishes, as is the case in the demo one. I don't know if it crops up in the games.

**Comment by bradallred** [comment]
I'm not seeing this. I thought maybe 7fd4cbf inadvertently fixed it, but I can't see it from the commit prior either.

**Comment by lynxlynxlynx** [comment]
Can still easily reproduce with that console command in the demo. When I tried in bg2, it didn't even move the viewport, regardless of the speed.

**Comment by bradallred** [comment]
> The cutscene may end before the move finishes, as is the case in the demo one. I don't know if it crops up in the games.

I would argue that if the cutscene ends then the viewport should be unlocked and manually moving the viewport should just cancel the scripted move

**Comment by lynxlynxlynx** [comment]
I don't see how that could be implemented safely — if it's the case at all. But this problem is visible without cutscenes anyway, so that's besides the point.

**Comment by bradallred** [comment]
im speaking to the point about jitter. There are multiple points floating around :)
