### ISSUE TITLE
[bug] [minor] Improve Wander Around AI for NPCs

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#115]
**Describe the bug**
BG2, BGT. Mostly nameless NPCs such as; Commoners, Guards, Peasants, and Beggers who have move around AI stick to the north of the map too often.

GemRB version: 

**To Reproduce**
Go to Beregost leave your party standing in one place for a long time. No easy way to reproduce the bug fast. Loading same area multiple times may also reproduce the broken wander around AI.

**Expected behavior**
NPCs should not wander off so far from their original location. Take a look at the Begger in Nashkel. He should be circling around Belching Dragon Inn and not north of the Helm's Temple.

![nashkel beggar north](https://user-images.githubusercontent.com/17316115/52993088-e342af80-33e0-11e9-855d-28e93835464d.jpg)
![npcs like to wander off to the most northern part of the area](https://user-images.githubusercontent.com/17316115/52993094-e76ecd00-33e0-11e9-8a22-b44ef384f61c.jpg)

**Comment by lynxlynxlynx** [comment]
Part of this is that RandomWalk needs improvement:
- it should be a blocking action if it isn't already
- maybe the default 25x25 candidate square is too big

Please check the beggar's scripts to see what action he uses for his wandering.

**Comment by cygarniczka** [comment]
One instance of RandomWalk from WDRUNSGT.BSC
```
IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		RunAwayFrom(NearestEnemyOf(Myself),150)
END

IF
	AttackedBy([ANYONE],DEFAULT)
THEN
	RESPONSE #100
		RunAwayFrom(LastAttackerOf(Myself),150)
END

IF
	True()
THEN
	RESPONSE #100
		RandomWalk()
END

```

RUNENEMY.BSC is full of RandomWalk
``` 
IF
	!StateCheck(Myself,STATE_CHARMED)
	See([0.0.DEMONIC.0.0.SUMMONED_DEMON])
	Gender(Myself,MALE)
	General(Myself,HUMANOID)
THEN
	RESPONSE #100
		PlaySound("PEASM209")
		RandomWalkContinuous()
END

IF
	!StateCheck(Myself,STATE_CHARMED)
	See([0.0.DEMONIC.0.0.SUMMONED_DEMON])
	Gender(Myself,FEMALE)
	General(Myself,HUMANOID)
THEN
	RESPONSE #100
		PlaySound("PEASF209")
		RandomWalkContinuous()
END

IF
	PickPocketFailed([PC])
	Allegiance(Myself,NEUTRAL)
	General(Myself,HUMANOID)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See(LastTrigger)
	!Allegiance(LastTrigger,FAMILIAR)
THEN
	RESPONSE #100
		StartDialogOverride("RR#PICKP",LastTrigger)
END

IF
	PickPocketFailed([FAMILIAR])
	Allegiance(Myself,NEUTRAL)
	General(Myself,HUMANOID)
	!StateCheck(Myself,CD_STATE_NOTVALID)
	See(LastTrigger)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		FaceObject(LastTrigger)
		DisplayStringHead(Myself,369877)  // Get away from me you filthy creature!
		SetSequence(SEQ_ATTACK)
		ApplySpellRES("RR#FEAR",LastTrigger)  // No such index
		SetInterrupt(TRUE)
END

IF
	GlobalLT("ENDOFBG1","GLOBAL",2)
	See([ENEMY])
	Gender(Myself,MALE)
	General(Myself,HUMANOID)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #10
		PlaySound("BEDWIN43")
		RandomWalkContinuous()
	RESPONSE #90
		RandomWalkContinuous()
END

IF
	GlobalLT("ENDOFBG1","GLOBAL",2)
	See([ENEMY])
	Gender(Myself,FEMALE)
	General(Myself,HUMANOID)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #10
		PlaySound("FCHIL05")
		RandomWalkContinuous()
	RESPONSE #90
		RandomWalkContinuous()
END

IF
	Detect([PC])
	Global("ENDOFBG1","GLOBAL",2)
	See([ENEMY])
	Gender(Myself,MALE)
	General(Myself,HUMANOID)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #50
		PlaySound("BDHIGG03")
		RandomWalkContinuous()
	RESPONSE #50
		RandomWalkContinuous()
END

IF
	Detect([PC])
	Global("ENDOFBG1","GLOBAL",2)
	See([ENEMY])
	Gender(Myself,FEMALE)
	General(Myself,HUMANOID)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #50
		PlaySound("PEASF209")
		RandomWalkContinuous()
	RESPONSE #50
		RandomWalkContinuous()
END

IF
	!Detect([PC])
	Global("ENDOFBG1","GLOBAL",2)
	See([ENEMY])
	Gender(Myself,MALE)
	General(Myself,HUMANOID)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	!Detect([PC])
	Global("ENDOFBG1","GLOBAL",2)
	See([ENEMY])
	Gender(Myself,FEMALE)
	General(Myself,HUMANOID)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		RandomWalkContinuous()
END
```

**Comment by lynxlynxlynx** [comment]
Also, there's a bunch of bits in the CRE header related to RandomWalk depending on object selectors. It's not well understood (so perhaps unused): https://gibberlings3.github.io/iesdp/file_formats/ie_formats/cre_v1.htm

**Comment by kmfrick** [comment]
I guess this has to be rechecked after #126 since I also modified the wander around code. Besides rewriting `RandomWalk` to not use the pathfinder, it now has a counter and after some walks calls `WalkTo(HomeLocation)`.

**Comment by lynxlynxlynx** [comment]
Yeah that nicely fixes things, so only the PurgeArea stuff remains to be more consistent.
