### ISSUE TITLE
[subviews/SDL2] the cursor remains gray after hovering over a gray button

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1151]
#### Bug description
With SDL2 (perfect on SDL1) , the cursor remains gray after hovering over a gray button.

#### Steps to reproduce
1. Start IWD1
2. fly over 'join game'
3. cursor stay greyed

#### Screenshots
![cursor](https://user-images.githubusercontent.com/55502325/107122545-92ac1180-6898-11eb-8899-42bcae3959d8.png)

**Comment by lynxlynxlynx** [comment]
Hmm, could be the same underlying reason for one of the items in #1152.

**Comment by bradallred** [comment]
It's an SDL 2 regression so probably not
