### ISSUE TITLE
[subviews] worldmap problems

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1152]
- [x] travel times are displayed as -1 when you exit waukeen's promenade (should be 0); I think from a8de141f50e910
- [x] no label color differences (visited, not visited, hover, inaccessible) #1149 
- [x] after hovering over an icon, the cursor doesn't change back to the scrolling one
- [ ] the dragging cursor is forced to the portrait dragging one
- [x] non-subviews: icon pulsing on hover, always to red

**Comment by bradallred** [comment]
you can ignore the drag cursor thing. it wont be an issue once I finish up my drag stash

**Comment by lynxlynxlynx** [comment]
Interesting, bg2 has all the color info in the mapicons.bam, including the fade in-out of the red overlay at the end. The previous frames are for individual states (normal, visited and so on).

**Comment by bradallred** [comment]
closing since the only remaining thing is already #992
