### ISSUE TITLE
[subviews] scrollbar in load window

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1154]
#### Bug description
when loading a game, on loading window (displayed very short time), on the right there is a scrollbar displayed

#### Screenshots
![lifter](https://user-images.githubusercontent.com/55502325/107883215-e9939580-6eed-11eb-913c-d5001505f434.png)

**Comment by lynxlynxlynx** [comment]
It's called a scrollbar. :)

**Comment by lynxlynxlynx** [comment]
Interesting that you get it that way, spanning the whole window height. There is an offscreen control by default, but I don't think we add scrollbars to windows without textareas at all.

**Comment by bradallred** [comment]
`ScrollView` is actually what what automatically adds scroll bars. Both `TextArea`s and `Windows employ them (`Window` is actually a subclass). So what is this control and why does it extend beyond the window bounds? can we just delete the control?

**Comment by lynxlynxlynx** [comment]
It's the button that's supposed to represent the highlighted end state of the full progressbar (see EndLoadScreen). It's offscreen in the data, not bigger than the window. Probably a mistake.

**Comment by lynxlynxlynx** [comment]
Fixed, just needs to be merged back.
