### ISSUE TITLE
Enable SSL on the website & migrate

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#116]
It's 2019. A free certificate can be got from Let's Encrypt. DNS or file verification. 3 month validity, so a script needs to be used to refresh the cert a few days before expiry.

EDIT: So the idea is to move to the Jekyll static site generator, since github supports it natively and have the actual site in a separate repo. We then get SSL for free for no hassle. We need to find and/or design a template (theme) and then move the actual content over.

**Comment by countbuggula** [comment]
Let's Encrypt + certbot makes it seamless and you never have to worry about certificate renewals.  Highly recommend using this for your website.

**Comment by lynxlynxlynx** [comment]
I don't think we can run services like that over on Source Forge.

**Comment by countbuggula** [comment]
Oh, is it hosted directly by sourceforge?  Interesting, let me investigate to see what options sourceforge has.

**Comment by lynxlynxlynx** [comment]
Thanks, there's indeed a section "HTTPS and PHP version" under Admin now. It does the upgrade to php 7.1 in the same run, so just another reason to bump dokuwiki first. However, that only works for the SF provided domain, so indeed they'd have to add a special entry just for us (unlikely). 

However, I'm thinking it's easier to invest some work to remove the maintenance overhead and move the few personal pages to the gh wiki and use gh pages for the actual site. It also supports LE for custom domains: https://github.blog/2018-05-01-github-pages-custom-domains-https/

**Comment by lynxlynxlynx** [comment]
The extra call for volunteers is now out: https://www.freecodecamp.org/forum/t/looking-for-a-student-who-wants-to-learn-about-github-pages-and-jekyll/327876

**Comment by lynxlynxlynx** [comment]
Here's the outline of what we need to do:
https://github.com/gemrb/gemrb.github.io/issues

The site is up and wired, but of course it's empty:
https://gemrb.github.io/

**Comment by lynxlynxlynx** [comment]
Progress is quite good. I've managed to trim, migrate and rewrite about half of the content and things seem to be falling into place quite nicely, even though that's not visible on the live site yet. 

We managed to migrate all the tracker items to the tracker (except #587 to gh wiki), so thanks to everyone that helped with that. :)

The other benefit of resolving this is that we'll be able to get 100% on the CLI best practice checklist (now at 97%).

**Comment by lynxlynxlynx** [comment]
All right, I'm excited! Check out the mature beta of the new page:
https://gemrb.github.io/

Please let me know if you'd change anything, if any content is missing or unclear, if you think anything should be additionally styled or any other thing that comes to your mind. Searching doesn't work yet.

As far as content goes, we need to improve the installation part and fix any issues with the generated binaries (eg. #696 ) and of course get the windows process closer to perfection #611 (eventually #612 ). @bradallred please specifically look at the [innovations](https://gemrb.github.io/Innovations.html) page, since I'm hitting a mental wall. It kinda sucked even in the original on the wiki.

It's using a pre-existing jekyll (remote) theme that I haven't modified in the slightest, besides adding the deluge of favicons (which can be done cleanly). It's mobile friendly and we could style it more harshly if desired. So far I only don't like the link-visited outline, as it looks quite janky.

BTW, here's my final todo:
https://github.com/gemrb/gemrb.github.io/issues/11

So close! :grinning:

**Comment by MarcelHB** [comment]
Great improvement! Should make a little 20y anniversary post easy to be placed well in this layout. Not sure, maybe by a sub-banner or a slider page.

**Comment by lynxlynxlynx** [comment]
Ok, everything is done, just dealing with the final launch details https://github.com/gemrb/gemrb.github.io/issues/1. :)
