### ISSUE TITLE
stdio logging now buffered 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1160]
One of the most recent changes gimped it. Now you see the console text only after exiting.

**Comment by MarcelHB** [comment]
Strange, I did not observe this on my platforms. MSYS2 has always been lagging behind a bit without explicit flushing, but definitely not until exiting.

**Comment by bradallred** [comment]
it has nothing to do with exiting and everything to do with when the buffer is filled or otherwise flushed. I've added an explicit flush after logging a message.

**Comment by lynxlynxlynx** [comment]
No change here.

**Comment by lynxlynxlynx** [comment]
The last commit fixed the buffering, however it doesn't end properly — I have to ctrl-c. Starting and quitting the game immediately is enough to reproduce.

**Comment by bradallred** [comment]
obviously im not having that problem, but if it want that way before I would suspect we can just add both conditions to the predicate. Try that?`return !messageQueue.empty() || !running;`

**Comment by lynxlynxlynx** [comment]
That was enough, thanks.
