### ISSUE TITLE
[subviews] Part of exit background screen is half transparent  in IWD1 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1166]
#### Bug description
See the screenshot, better than any explication.

subviews with SDL2/OGL

#### Steps to reproduce
1. On IWD1 load a game with bright "map" (not too visible with dark one) 
2. Exit the game to return to main game windows
3. Click on quit game
4. And border of main windows get half transparent (instead of being greyed ?)

#### Screenshots
![quit_game](https://user-images.githubusercontent.com/55502325/108809226-abab0700-75a8-11eb-9901-9c660d98bf83.png)

**Comment by bradallred** [comment]
I'm not sure I follow what you are saying, but it doesn't sound like something to fix. it sounds like a side effect from bec0766 which is going to stick around for as long as we support SDL1

the game window shouldn't be sticking around there anyway. thats the real bug.

**Comment by lynxlynxlynx** [comment]
Wouldn't clearing the buffer before destroying the game window fix it? The border/window frame region should be black, just like on startup.

**Comment by bradallred** [comment]
thats what I meant by "the game window shouldn't be sticking around there anyway. thats the real bug."

the issue with the transparency is moot, but still there
