### ISSUE TITLE
[subviews] gears missing the tooltip

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1168]
Noticed in bg2 @ 1024x768; there's no date and time tooltip.

**Comment by bradallred** [comment]
aren't there 2 clocks? we are probably setting the wrong one

**Comment by lynxlynxlynx** [comment]
For bg2 it actually depends on the version of the game, if you're talking about the animations. If it's about the copy sometimes on the actionwin, perhaps. It's clear something is bad though, since even clicking doesn't work properly.

**Comment by bradallred** [comment]
im talking about how there is a clock on the action window and the option window
