### ISSUE TITLE
 Improve the special item outline coloring in the inventory

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1173]
This blue frame around items in GemRB inventories (except PST) always made me wonder whether this is some key color error but it's probably a very simple way to indicate items with special attributes:

IE: 
![blue_item_ie](https://user-images.githubusercontent.com/238558/110240272-7066eb80-7f4b-11eb-9a91-79c0fc48b491.jpg)

GemRB:
![blue_item_gemrb](https://user-images.githubusercontent.com/238558/110240300-8ecce700-7f4b-11eb-86e9-5c61c944b351.jpg)

Anyway, I find it quite ugly in later save games, when everything is special:
![inv_iwd2_strong](https://user-images.githubusercontent.com/238558/110240303-91c7d780-7f4b-11eb-84f8-a903534a1901.jpg)

We should maybe find a more decent way as in the in original, like some unopaque watercolor blue layer.

**Comment by bradallred** [comment]
you can actually do that now by changing the parameters passed to `SetBorder` just tweak the color and include an alpha value and set the 'filled' parameter to `True`

**Comment by lynxlynxlynx** [comment]
This is how it looked in the original (armor, bullet):
http://oceanofgames.com/wp-content/uploads/2014/11/Icewind-Dale-Free-Setup-Download.jpg

So wider border, blended (same color as the unidentifed overlay - clever!) and probably set only on items with a non-zero enchantment level.

**Comment by MarcelHB** [comment]
> 
> 
> you can actually do that now by changing the parameters passed to `SetBorder` just tweak the color and include an alpha value and set the 'filled' parameter to `True`

So with:
```diff
--- a/gemrb/GUIScripts/InventoryCommon.py
+++ b/gemrb/GUIScripts/InventoryCommon.py
@@ -977,7 +977,7 @@ def AbilitiesItemWindow ():
 def UpdateInventorySlot (pc, Button, Slot, Type, Equipped=False):
        Button.SetFont ("NUMBER")
        Button.SetBorder (0, 0,0,0,0, 128,128,255,64, 0,1)
-       Button.SetBorder (1, 2,2,2,2, 32,32,255,0, 0,0)
+       Button.SetBorder (1, 5,5,4,4, 64,128,192,128, 0,1)
        Button.SetBorder (2, 0,0,0,0, 255,128,128,64, 0,1)
        Button.SetText ("")
        Button.SetFlags (IE_GUI_BUTTON_ALIGN_RIGHT | IE_GUI_BUTTON_ALIGN_BOTTOM | IE_GUI_BUTTON_PICTURE, OP_OR)
```

This isn't too bad anymore, colorwise, but ...
![new_inv](https://user-images.githubusercontent.com/238558/110377448-ba87c400-8054-11eb-8b81-edb98e75092b.jpg)

**Comment by lynxlynxlynx** [comment]
Yeah, we either need a border width param for the normal mode or an inversion param for the filled mode.

I also checked if stonslot.bam has this as an extra cycle, but nope.

**Comment by MarcelHB** [comment]
_Inverse filling_ sounds like a hack, but then again _border width_ make my mind whirl around CSS width rules, so no quick win either. Anyway, worth looking at in parallel to subviews?

**Comment by bradallred** [comment]
cant we just use multiple borders? we already have 3, but im not even sure why. seems like we should just have 2 that we change the colors for.

its hard to tell from the original screenshot if the blue is even an overlay or a background

**Comment by lynxlynxlynx** [comment]
Like I said, the slot bam doesn't have this.

We have borders for the different button states, so we can't just set a few to fake width.

**Comment by bradallred** [comment]
I dont see how the borders are related to states at all. The c++ side would happily let you specify 1 border for each side and then one for the middle. on the subviews branch at least.

**Comment by lynxlynxlynx** [comment]
Not the enabled/disabled/... states, the normal/identified/unusable ones in this script. Sure, the colors could be done with only one border even on master, but it would just make the code less readable.

Are you saying on subviews we could have a second border cut out another?

**Comment by bradallred** [comment]
yes, on subviews we _could_ have a separate buffer for the borders and as long as they are ordered correctly one could fill the entire button and the subsequent one can cut away from the middle by filling the middle with transparency. if thats the way we want to do it.

**Comment by lynxlynxlynx** [comment]
Sounds cleaner to use a param for width. Only 4/56 calls to SetBorder have the `enabled` param set to 1, but we have EnableBorder anyway, so we could repurpose it for width.

**Comment by lynxlynxlynx** [comment]
It turns out there *are* extra resources for this — if you look closely at the screenshot from the original, it's clear the border is rounded. IWD2 did all the overlays here with extra bams: stortint, stortin2 (magic item = this bug) - stortin4. Looks like we just need some tweaks for better stacking support. :)

**Comment by lynxlynxlynx** [comment]
Eh, it's the only image that needs to be blended:
![image](https://user-images.githubusercontent.com/121515/156039356-a84e32a3-2615-45bc-bf37-9b33c2baf9d8.png)
Perhaps just overriding its opaqueness would do, but I don't see any simple way to modify a Sprite2d. Is the cleanest option to add another Button flag bit, so we can then directly set blit flags in its DrawSelf?

**Comment by bradallred** [comment]
yeah, we wouldn't want to be modifying sprites to achieve this. It looks like it would fall under the same umbrella as the "blood" overlay, which we currently hack into `IE_GUI_BUTTON_HORIZONTAL`, which seems like a poor name anyway.

**Comment by lynxlynxlynx** [comment]
Adding BlitFlags::COLOR_MOD like with IE_GUI_BUTTON_HORIZONTAL doesn't help in this case, the bam is rendered black:
![image](https://user-images.githubusercontent.com/121515/156065294-355f4945-7f75-48a1-8a3a-35a4f8a8eeb7.png)
And BLENDED has no effect. Is all this expected?

**Comment by bradallred** [comment]
`COLOR_MOD` and `ALPHA_MOD` both require a color to do anything, if you dont pass one then the default color is black. But you dont want to tint things, you want to blend two images, so `MULTIPLY` is probably what you want since `BLENDED` is just a standard alpha blending.

**Comment by lynxlynxlynx** [comment]
Ah, my code completion failed me, I didn't see the whole list. MULTIPLY turns everything green, but HALFTRANS is good enough. 👍🏾 
I'll just reuse this IE_GUI_BUTTON_HORIZONTAL bit for now.
