### ISSUE TITLE
RPi build broken

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1174]
Hi there

compiling rom git latest code fails at around 35% ...

Only code from releases 0.8.7 compiles ok with above but gemrb still cant launch a game neither as SDL nor on Pi4 Desktop with GLES driver

RetroPie compile scriptmodule compiles 0.8.6 code with SDL backend and runs OK..

I notice in cmake options if RPI found to apply SDL + GLES

Here is what I tried and my pastebin error. Much appreciated any comments

Built from Git with
`git clone https://github.com/gemrb/gemrb.git`
 
And build folder with
`cmake .. -DCMAKE_BUILD_TYPE=Release -DFREETYPE_INCLUDE_DIRS=/usr/include/freetype2/  -DUSE_SDLMIXER=OFF -DOPENGL_BACKEND=GLES -DSDL_BACKEND=SDL2`
 
```
--
-- Options:
--   LAYOUT: fhs
--   NOCOLOR: disabled
--   STATIC_LINK: disabled
--   INSOURCEBUILD: disabled
--   DISABLE_WERROR: disabled
--   WIN32_USE_STDIO: disabled
--   SDL_BACKEND: SDL2
--   OPENGL_BACKEND: GLES
```

PASTEBIN: https://pastebin.com/kfWdutmJ

_Originally posted by @2play in https://github.com/gemrb/gemrb/issues/988#issuecomment-792680120_

**Comment by lynxlynxlynx** [comment]
This appears to be the only error in the log @2play:
```
/home/pi/code/v0.8.7/gemrb/core/SaveGameIterator.cpp: In member function ‘void GemRB::SaveGameIterator::PruneQuickSave(const char*)’:
/home/pi/code/v0.8.7/gemrb/core/SaveGameIterator.cpp:202:44: error: ‘-’ directive output may be truncated writing 1 byte into a region of size between 0 and 4107 [-Werror=format-truncation=]
   snprintf(destination,sizeof(destination),"%s%s%s%09d-%s", \
                                            ^~~~~~~~~~~~~~~
/home/pi/code/v0.8.7/gemrb/core/SaveGameIterator.cpp:414:3: note: in expansion of macro ‘FormatQuickSavePath’
   FormatQuickSavePath(to, myslots[i]+1);
   ^~~~~~~~~~~~~~~~~~~
/home/pi/code/v0.8.7/gemrb/core/SaveGameIterator.cpp:202:11: note: ‘snprintf’ output 11 or more bytes (assuming 4118) into a destination of size 4116
   snprintf(destination,sizeof(destination),"%s%s%s%09d-%s", \
   ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   core->SavePath,SaveDir(), SPathDelimiter,i,folder);
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/code/v0.8.7/gemrb/core/SaveGameIterator.cpp:414:3: note: in expansion of macro ‘FormatQuickSavePath’
   FormatQuickSavePath(to, myslots[i]+1);
   ^~~~~~~~~~~~~~~~~~~
```
Relatively easy to fix by limiting the snprintf input lenghts. What version of gcc are you using?

**Comment by 2play** [comment]
@lynxlynxlynx 
Thank you for such a swift reply!

-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0

**Comment by lynxlynxlynx** [comment]
In the meanwhile, it's easiest if you just build without having warnings be errors: pass -DDISABLE_WERROR=1

**Comment by 2play** [comment]
it crossed my mind, testing and reverting

**Comment by 2play** [comment]
it compiles ok from git with the parameter as you proposed.
I have tested by replacing with compiled binary the precompiled one from RPie Setup v0.8.6
Unfo I cant run any of the games afterwards. 
I also did `sudo make install` and retested but I regret to say no luck with same GemRB.cfg

Do you think its due the GLES?

I just want to say thank you for all your help.  I ll try some environment variables as I also have custom MESA drivers compiled on the side to test things. Maybe new binary needs newer GLES driver. Cant say

**Comment by lynxlynxlynx** [comment]
You can't just replace the binary, no way that would work. Open a new issue if you have some specific problem — "cant run" isn't one.

I think we may require GLESv2 compatible hw now, but not sure, since we're working on two branches at once.

**Comment by 2play** [comment]
I totally understand. it makes sense as each binary uses specific libraries
at least i have the 0.8.7 compiled from latest git and libs etc installed.
I can do more config testing. Further i got was  it was trying to set video in desktop and crash out after a 640*480 windows popped for a sec.
Ill post more findings down the road.
Thank you again @lynxlynxlynx

**Comment by lynxlynxlynx** [comment]
Check the log, it should be helpful. GemRB.log in the game dir if you're not running from the console.

**Comment by 2play** [comment]
im testing both on x11 and console. 0.8.6 works great on both apart some video intro hick ups

**Comment by lynxlynxlynx** [comment]
Any updates here?

**Comment by 2play** [comment]
@lynxlynxlynx  I ended up using the RPIe setup 0.8.6 in the meantime. 
but i believe since i can compile latest ok now then I can set as needed.
Thank you for all you help!
If preferred you can close this ticket.

**Comment by lynxlynxlynx** [comment]
Thanks, closing then.
