### ISSUE TITLE
[subviews] chapter screen takes too long to appear

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1178]
The bg2 cutscene when you exit the underground in the intro starts on area exit. For some reason we now just draw a black screen for too many a second. On master the scripted textscreen appears with little delay.

**Comment by bradallred** [comment]
is this not resolved by fixing the bug from #233?

**Comment by lynxlynxlynx** [comment]
I doubt it, but I'll recheck.

**Comment by lynxlynxlynx** [comment]
Takes 2-3x longer to appear. The cursor is visible sooner, but it's just a black background.
The only thing that comes to mind are the GlobalTimer changes, but I'll just go run a bisect, since it could be a faster way to find a lead.

**Comment by lynxlynxlynx** [comment]
Did a few. When I treated dde366b - 69cea5 as bad (fast, but one can see the area for a while), it led me to a dead end. When treating them as good, it led me to 8d6c4f64. It's not directly timing related, but it is to drawing, so perhaps it's not a fluke. Reverting it right after it was added fixes the problem, but of course it's not possible to test on HEAD.

**Comment by bradallred** [comment]
does it require then to be on a resolution small enough to have window frames?

**Comment by lynxlynxlynx** [comment]
Was testing at 1024x768, but now also tried 1280x1024, no change.
