### ISSUE TITLE
[subviews] IWD2: Python error when right-clicking items in inventory

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1180]
#### Bug description
When I try to inspect an item in IWD2 – after I have changed a map at least once – by clicking right in the inventory, nothing happens. Instead, I get a Python error.

#### Screenshots
```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "D:\Sources\gemrb_subviews\gemrb\GUIScripts/InventoryCommon.py", line 440, in OpenItemInfoWindow
[Python/ERROR]:     DisplayItem (slotItem, value)
[Python/ERROR]:   File "D:\Sources\gemrb_subviews\gemrb\GUIScripts/InventoryCommon.py", line 246, in DisplayItem
[Python/ERROR]:     Label.SetText (text)
[Python/ERROR]: AttributeError: 'NoneType' object has no attribute 'SetText'
```

**Comment by lynxlynxlynx** [comment]
Do you have a reproducer? I've seen it a few times myself, but it was always ephemeral.

**Comment by MarcelHB** [comment]
Just as you mention it: Damn, no. This launch it looks good again.

**Comment by MarcelHB** [comment]
Well, I got something: When starting a game freshly, it's good. But after changing the map, it's there for me reliably.

**Comment by lynxlynxlynx** [comment]
Bizarre, as expected.

**Comment by lynxlynxlynx** [comment]
Hmm, still can't reproduce. Went to subareas, went to different master areas and nothing. Does the slot matter for you? Between which areas are you travelling?

**Comment by MarcelHB** [comment]
Maybe try it as simple as ESCing the window, not closing it by button. That also causes the error for me.

**Comment by lynxlynxlynx** [comment]
Yep, that does it, no area move needed at all. So it must be another close handler issue.
