### ISSUE TITLE
[subviews] No button to end dialogues

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1181]
#### Bug description
When in dialogues, and there is nothing more to talk about, some games (BG, IWD) I've tested lack the "End Dialogue" button, so you are stuck with a Python error:

#### Steps to reproduce
1. Get in to some dialog that is terminated by some NPC lines.

#### Expected behavior
Have an "End Dialogue" button to go on.

#### Screenshots
```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "D:\Sources\gemrb_subviews\gemrb\GUIScripts/GUIWORLD.py", line 100, in OpenEndMessageWindow
[Python/ERROR]:     Button = ContinueWindow.GetControl (0)
[Python/ERROR]: AttributeError: 'NoneType' object has no attribute 'GetControl'
```

**Comment by lynxlynxlynx** [comment]
I think it's fine if we just check for ContinueWindow being None beforehand.

**Comment by MarcelHB** [comment]
Looks good. I did not find any dialogues in PST/IWD2 that are finished by the NPC in my savegames, but the other games work.
