### ISSUE TITLE
[subviews] Hotkeys for dialogue options not working

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1182]
#### Bug description
Lazy me wants to go through dialogue options fast when debugging, by num keys. What happens: PCs get their focus and also the viewport leaves the NPC during the dialogue. Maybe related to changes by #963.

#### Steps to reproduce
1. In a dialogue, press 1..9 to trigger dialogue options.

#### Expected behavior
Dialogue option to trigger, not PC focus to change.

**Comment by MarcelHB** [comment]
This does not work in PST/IWD2 since `indialog` evaluates to 0 there, but the other games look good again.

**Comment by bradallred** [comment]
There certainly shouldn't be a difference between any games. are you getting any python errors?

**Comment by MarcelHB** [comment]
None around.
