### ISSUE TITLE
[subviews] Wrong report of group death in IWD

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1183]
#### Bug description
I found something interesting – and only in subviews and IWD so far: If your PC#1 dies, i. e. the first one I added to the group, _not_ the one I moved to position 1, the whole group is reported dead. That may abruptly kick you out of some fight, terminating the game.

#### Steps to reproduce
1. In IWD, kill the PC that is group member one.

#### Expected behavior
The game to go on until everyone ist down.

#### Screenshots
![grafik](https://user-images.githubusercontent.com/238558/111042991-51cb8d80-8440-11eb-8ff1-17c67e9e47a7.png)

**Comment by lynxlynxlynx** [comment]
For some reason it's not in team mode, will take a look.
