### ISSUE TITLE
[subviews] IWD2 CharGen preview with clown colors

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1189]
#### Bug description
An identical character in IWD2's preview looks good on master, on subviews it's colorful:

![iwd2_cg_preview](https://user-images.githubusercontent.com/238558/111386480-9a877e80-86ac-11eb-9e32-840e21a54f07.jpg)

**Comment by lynxlynxlynx** [comment]
A quick look shows that RefreshPDoll does get called and with the same globals, so it looks like something goes wrong in Button itself, since the guiscript function is pretty much identical between the branches.

**Comment by lynxlynxlynx** [comment]
Not sure what changed, but this was clean and localized enough for me not to care.
