### ISSUE TITLE
[enhancement]  Disable hostile reaction after charm

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#119]
**Description**
BGT TWEAK mod has a nice component to disable hostile reaction after charm wears off. Unfortunately component does not work on GemRB. Maybe add it as toggleable feature in the ini file?

**Comment by lynxlynxlynx** [comment]
Please link to the mod/component, so I can check what it does.

**Comment by cygarniczka** [comment]
http://www.shsforums.net/files/file/67-baldurs-gate-trilogy-tweak-pack-11/

It says the download is broken but the file downloads and I compared to mine BGT .rar package and they look the same.

**Comment by lynxlynxlynx** [comment]
Which component would that be (if you're sure it's in this mod), since none of their names suggest anything like this?
