### ISSUE TITLE
BG2: No paperdoll for half-orcs 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1192]
#### Bug description
Both in CharGen and the game, there is no paperdoll for half-orcs. The only warnings of missing BAMs ask for something like `COMT1INV` but I'm not sure if this is related.

#### Screenshots
![bg2_halforcs](https://user-images.githubusercontent.com/238558/111390404-f3f2ac00-86b2-11eb-9add-3af65c3498c4.jpg)

**Comment by MarcelHB** [comment]
The BAM string is correct but there aren't any BAM files for `CO*`. Anyway, it's there somewhere we need to find it, there are even some related hardcodings in the executable.

**Comment by lynxlynxlynx** [comment]
Looks like my choice:
b42a2992e5cdcb3dddad4fb0a1010784611106df

They're either added by 1pp or infinity animations:
http://readme.spellholdstudios.net/infinityanimations.html
https://spellholdstudios.github.io/readmes/1pp/documentation/1pp-readme-english.html#101

Definitely now in 1pp:
https://github.com/SpellholdStudios/1pp/tree/master/1pp/core/1ppfixed

So I guess the bug should be: use a default fallback if the animation isn't found. I think we actually already check that somewhere  ... but don't do anything impactful about it: see GetActorPaperDoll.

**Comment by MarcelHB** [comment]
When running vanilla BG2: ToB, there is a paperdoll for the half-orc. My assumption was: it's some irregular, just find it?

**Comment by lynxlynxlynx** [comment]
Ok, I'll ask around.

**Comment by MarcelHB** [comment]
Mugshot

![bg2_halforc](https://user-images.githubusercontent.com/238558/111524269-800cde00-875c-11eb-82d3-e536b9524965.jpg)

**Comment by MarcelHB** [comment]
Got it: I was looking for BAMs, and the error message complains about BAMs in the first line, so I went looking the wrong way:
```
[ResourceManager/ERROR]: Couldn't find 'COMF1INV.bam'.
[GUISCript/WARNING]: PLT/BAM not found for ref: COMF1INV
```

**Comment by lynxlynxlynx** [comment]
A bg1 remnant? No idea what the benefit is.

**Comment by MarcelHB** [comment]
Then let's handle this as a topic on its own.
