### ISSUE TITLE
[subviews] PST action bar problems

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1194]
#### Bug description
Following #1184, there is something else that prevents me from using PST's action bar elements. It does not happen all the time, for example when loading save games with TNO alone, it seems to work. I find this Python error:

Update for reliable reproduction:

1. Load a game.
2. Right-click to open the floating menu.
3. Go to options and load again, the menu should not have disappeared before.
4. Now, I see the action bar broken.

```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "D:\Sources\gemrb_subviews\gemrb\GUIScripts/GUICommonWindows.py", line 1917, in SelectionChanged
[Python/ERROR]:     SelectionChangeMultiHandler ()
[Python/ERROR]:   File "D:\Sources\gemrb_subviews\gemrb\GUIScripts\pst/FloatMenuWindow.py", line 498, in FloatMenuSelectAnotherPC
[Python/ERROR]:     UpdateFloatMenuWindow ()
[Python/ERROR]:   File "D:\Sources\gemrb_subviews\gemrb\GUIScripts\pst/FloatMenuWindow.py", line 252, in UpdateFloatMenuWindow
[Python/ERROR]:     Button.SetSprites (GUICommonWindows.GetActorPortrait (pc, 'FMENU'), 0, 0, 1, 2, 3)
[Python/ERROR]: AttributeError: 'NoneType' object has no attribute 'SetSprites'
```

**Comment by lynxlynxlynx** [comment]
It's odd that it's calling that handler for a 1 pc party, but should be easy to hunt down.

**Comment by lynxlynxlynx** [comment]
Do you have a more detailed reproducer? I tried saves with just TNO, two or full parties, with just one pc selected or all, and it worked just fine.

**Comment by MarcelHB** [comment]
You're right. The savegame I had used for reproducing looks good to me now, too. Until I encounter this again, let's consider this invalid.

**Comment by MarcelHB** [comment]
Ha, just as I closed the I game I found the exact thing to do:

1. Load a game.
2. Right-click to open the floating menu.
3. Go to options and load again, the menu should not have disappeared before.
4. Now, I see the action bar broken.

**Comment by bradallred** [comment]
it might make more sense to close upon opening a new top window rather than on close sense both make use of the selection change handler

**Comment by lynxlynxlynx** [comment]
That's what I did, unless I don't understand you.

**Comment by bradallred** [comment]
👍 the commit lacked enough context and I misunderstood the commit message to mean something about running in `OnClose`
