### ISSUE TITLE
[subviews] IWD: alignments are not restricted in CharGen

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1195]
#### Bug description
You can have a shining druid or an evil Paladin. The list of assignments does not seem to impose any restrictions. Good on master.

**Comment by MarcelHB** [comment]
I suspect it's somehow the same root as #1180 i. e. there is no obvious problem in the Python code but somehow `IE_GUI_BUTTON_DISABLED` does not work or gets overthrown on said radio buttons.

**Comment by lynxlynxlynx** [comment]
Perhaps another inconsistency between the now two ways we can disable buttons (disabled view, disabled state). 4ca4fd1

**Comment by lynxlynxlynx** [comment]
This got fixed by the first part of the fixes for #1190, so it was indeed the same problem.
