### ISSUE TITLE
[subviews] IWD has the wrong scrollbar in many places

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1196]
#### Bug description
In many UI elements, IWD shows the scrollbar of the journal instead of the native ones. This bloats smaller UI textboxes and looks ugly quite often. See two examples below.

#### Screenshots
![iwd_scrlbar1](https://user-images.githubusercontent.com/238558/111394593-56e84100-86bb-11eb-96e5-0640c61bd4cc.jpg)
![iwd_scrlbar2](https://user-images.githubusercontent.com/238558/111394594-58196e00-86bb-11eb-995b-c774a7a9bbf6.jpg)

**Comment by lynxlynxlynx** [comment]
Are these all attached to text areas? Those we rip out and add our own.

**Comment by MarcelHB** [comment]
Guess so: text areas, message window, PC overview sheet.

**Comment by lynxlynxlynx** [comment]
Too bad, then it does break our assumption that we can get away with just one global scrollbar in CreateScrollbarARGs / ScrollView / MergeTextAreaAndScrollbar.

**Comment by MarcelHB** [comment]
What was the idea/need to do so?

**Comment by lynxlynxlynx** [comment]
Brad can explain it better, but I think it was a simplification that also allows not to display them if they're not required.

**Comment by bradallred** [comment]
more important than hiding them when not require is displaying them when the text is more than can be displayed even if a scrollbar is missing in the CHU. We allow changing fonts/sizes/localizations/mods and there were several cases of missing scrollbars in various scenarios. It's just easier to have `ScrollView` manage the need for scrollbars like every modern GUI toolkit does.

The implementation is incomplete and assumes scrollbars are on the right which sometimes isn't true (PST), but scrollbars on the right should draw over the original location. We already handle cases where the scrollbars are detached from the TextArea so i'm not sure what that is evidently failing here. It should be well handled.

The only issue here that I can explain is the default scrollbar we create from `CreateScrollbarARGs` is not always what we want for IWD apparently. We would have to add a second `ScrollView` constructor to take a scrollbar template which is easily done.

**Comment by lynxlynxlynx** [comment]
Will take a stab at this.

**Comment by bradallred** [comment]
my plan was to just pass the `ScrollBar` from the CHU along to the `TextArea` constructor. what were you thinking?

**Comment by lynxlynxlynx** [comment]
Just started looking at the code, so no overall plan yet, except that loading several SBGLOBs wouldn't make sense.

**Comment by lynxlynxlynx** [comment]
It's a bit tricky, since scrollbars don't always come before or after textareas, so we have chicken and egg problems.

An uncleaned draft for comment:
http://sprunge.us/UbDujv?diff

GUIREC is where one of the replacements needs to be made.
