### ISSUE TITLE
 BG2: Use PLT files for paperdolls

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1197]
#### Description

Until now, BG2 uses BAM files for paperdolls. 

1. It's not what the original BG2 displays.
2. We don't have half-orcs there, so the player faces an empty char gen & inventory.

Looking at the assets, the PLT files seem to follow the same kind of name pattern.

**Comment by lynxlynxlynx** [comment]
As the error suggests, we at one point looked for both. I remember some problems in that guiscript function, again with 1pp. I think it installs dummy plt files to make the original engine not use them. So perhaps I just disabled plts, but we should look at both, just in the opposite order.

**Comment by lynxlynxlynx** [comment]
Yeah, it's all documented in GemRB_Button_SetPLT.
