### ISSUE TITLE
BG: No default voice available 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1198]
#### Bug description
My favourite protagonist voice in BG was the _default_ voice. It's not available in the CharGen list of BG in GemRB, there are just the named ones.

#### Screenshots

![bg_voices](https://user-images.githubusercontent.com/238558/111550741-0b976680-877f-11eb-9709-8a49af8a1830.jpg)

**Comment by MarcelHB** [comment]
WAV resources are prefixed by `MAINF` and `MAINM`, but I don't see any convenient way in GUIScripts to prepend or append an item to the resources list that is also selectable in the same way. So maybe post-subviews to enhance this.

**Comment by lynxlynxlynx** [comment]
I'd add another optional string or list param to GemRB_TextArea_ListResources for things to be appended after the internal generation.

**Comment by lynxlynxlynx** [comment]
I remembered we already jump through hoops for the player script list in GUIREC (on subviews), so it's probably be possible to fix this in python.
