### ISSUE TITLE
[bug] As soon as save game loads NPCs react to reputation

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#120]
**Describe the bug**
As soon as save game loads NPCs react to reputation

![Rep_reaction_triggers](https://user-images.githubusercontent.com/17316115/54134016-8d649480-43ed-11e9-9be1-03ff57fd2735.jpg)

TODO: check if UpdateHappiness or anything related is called too early for the timers etc to be defined.

**Comment by lynxlynxlynx** [comment]
how does your happy.2da look?

**Comment by lynxlynxlynx** [comment]
I don't see it on random saves. What is your reputation?

**Comment by cygarniczka** [comment]
14 for the Friendly Arm Inn screenshot.
For new game Xzar and Monty screenshot - 3.

**Comment by cygarniczka** [comment]
I had Minsc react to (low) reputation after I resurrected him via scroll Raise Dead SCRL63.

**Comment by lynxlynxlynx** [comment]
The problem was that the value was stored unsigned, so all those -300 and similar values usually hit by evil npcs got mangled.
