### ISSUE TITLE
[subviews] IWD2 trading window has minor issues

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1201]
#### Bug description
When entering the trade window in IWD2, I observe two problems:

1. Initially, you cannot click any items, nothing happens. You need to click the coin button to the left.
2. After that, we can move around items, but the _Done_ button to the lower right does not work anymore.
3. You can somehow work around by entering the inventory by hotkey (or something else), and then close it. Then there is an artifact of leftovers of panels on screen, with the _Done_ button now ready to be clicked.

#### Screenshots

![iwd2_trading](https://user-images.githubusercontent.com/238558/111712202-6eefca00-884d-11eb-9783-13bde5633474.jpg)

**Comment by MarcelHB** [comment]
When there is another option (such as identification), I also cannot switch back to trading.

**Comment by lynxlynxlynx** [comment]
"minor" is an understatement. There are no python errors, but there are clearly several focusing problems:
- the need for the initial click
- no switching / done

The done button and store subwindows buttons are on the same separate window.

**Comment by lynxlynxlynx** [comment]
Actually this doesn't appear to be focus related. It got broken in b837c5b0c9d, so just after the complete gui tests (#1054). :(

**Comment by bradallred** [comment]
I dont see how that can possibly be relevant. Are these not BAM's? the code in that commit wouldn't affect BAMs at all.

**Comment by bradallred** [comment]
I guess SDL 2 wouldn't use BAMs, but I still dont understand how fixing clearly buggy behavior with getting pixels from mirrored sprites would result in the described behavior.

**Comment by lynxlynxlynx** [comment]
I'm on SDL2. It's indeed bizarre, but compiling that and the previous commit did confirm the problem started there. Maybe through IsPixelTransparent and the hit box testing?

The frame region testing regression that got fixed later is not the culprit.

**Comment by lynxlynxlynx** [comment]
Same problem on SDL1, introduced at the same time. 🤷🏾‍♂️

**Comment by lynxlynxlynx** [comment]
Other stores work, so I checked the iwd2 ifdefs in GUISTORE, but only setting WF_ALPHA_CHANNEL on the window stood out, the rest is subcontrol minutiae. Commenting the flag setting out didn't achieve anything though.

**Comment by bradallred** [comment]
if it affects SDL1 too and it truly did break with that commit then I have to suspect these BAMs are getting converted somewhere along the way, but even then I dont see how it could be broken by this. we use `GetPixel`, `BLIT_MIRRORX`/`BLIT_MIRRORY`, and `SDLPixelIterator` all the time and surely should be seeing additional fallout from a broken implementation.

do these sprites somehow have `BLIT_MIRRORX` or `BLIT_MIRRORY` set?

**Comment by lynxlynxlynx** [comment]
Doesn't appear so. I've hacked away the actor and fog drawing and nothing hits the two cases that set these bits.
Can you reproduce btw?

**Comment by bradallred** [comment]
I'll attempt to repro when I get a min

**Comment by bradallred** [comment]
can I get an area number to repro? I dont know IWD2 at all.

**Comment by lynxlynxlynx** [comment]
ar1003 should work all the time, but has only drinks — still showing the problem. The main store in ar1102 is not operational until the docks are cleared iirc.

**Comment by bradallred** [comment]
eh, both seem to require the docks to be cleared. is there a console command to do this or a save somebody can throw up?

**Comment by lynxlynxlynx** [comment]
[000000008-store test.zip](https://github.com/gemrb/gemrb/files/6260358/000000008-store.test.zip)

**Comment by lynxlynxlynx** [comment]
Oh and the simplest test cases are: left/right click. Can you select an item, can you open its description.

**Comment by bradallred** [comment]
I realized what @MarcelHB described as "artifacts" are in fact no such thing, but actually the window background. IWD2 uses this trick a lot where it composites multiple windows together. It makes a lot more sense to realize that the buttons (and therefore BAMs) have nothing to do with this at all.

**Comment by lynxlynxlynx** [comment]
So we were drawing those parts as transparent, but not registering them as such, so one was clicking on an empty window part, even though it looked otherwise.

**Comment by bradallred** [comment]
yes, thats correct. the mouse events were blocked from the window below because the pixels were considered as opaque by our event code. obviously the rendering side handled the color key appropriately. There probably aren't many instances of a color key on non paletted images.
