### ISSUE TITLE
[subviews] IWD2 incomplete lighthouse light animation

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1202]
#### Bug description
In IWD2 AR1000, there is the lighthouse. It has an animation to mime some kind of light rotation.

On master, we see the whole cycle. On subviews, there is only a bit to see shortly to the east and west.

#### Screenshots
Here is what we are _not_ seeing:

![iwd2_lighthouse](https://user-images.githubusercontent.com/238558/111713070-276a3d80-884f-11eb-9507-c0e32ce7b20d.jpg)

**Comment by lynxlynxlynx** [comment]
Peek had some lagging issues, but the lighthouse appears to be drawn fine for me (sdl2):
![Peek 2021-03-20 11-57](https://user-images.githubusercontent.com/121515/111867345-9ccf2e80-8973-11eb-843b-54ac413cb848.gif)

**Comment by MarcelHB** [comment]
I will double-check.

**Comment by MarcelHB** [comment]
With SDL2 + OpenGL on two setups, I miss the light shining southwards. I'll try some investigation later.

**Comment by MarcelHB** [comment]
To me and for me, it looks as if the polygons overlap with the animation:

This is what I see:
![Screenshot_2021-03-22_16-36-13](https://user-images.githubusercontent.com/238558/112016407-f890e780-8b2c-11eb-8732-6088e0328710.png)

This is what NI tells us:
![Screenshot_2021-03-22_16-34-16](https://user-images.githubusercontent.com/238558/112016382-f4fd6080-8b2c-11eb-9590-f585040a6f16.png)
![Screenshot_2021-03-22_16-34-32](https://user-images.githubusercontent.com/238558/112016394-f6c72400-8b2c-11eb-9123-51f5552b25f6.png)

**Comment by lynxlynxlynx** [comment]
Ingame for me you can see the partial central draw, as it passes through:
![image](https://user-images.githubusercontent.com/121515/112019473-c2a13280-8b2f-11eb-9c14-f2134d3e8cf9.png)
I can confirm that it looks slightly cut as in your first picture, which is a regression compared to the original.

**Comment by bradallred** [comment]
is the `WF_COVERANIMS` bit set?

**Comment by lynxlynxlynx** [comment]
Yep, bit 0 (shade wall in NI) and bit 3. While the animation doesn't have bit 6 (not covered by wall), just 0 and 1.

Perhaps some of these have a different meaning in iwd2, though I find that unlikely. Would be good to see if we have similar problems in other (non-pst) games.

**Comment by bradallred** [comment]
is this really only happening on subviews then? Not sure what the difference would be.

**Comment by bradallred** [comment]
wait, `WF_COVERANIMS ` is bit 8, not bit 0. typo? we consider bit 0 to be disabled/enabled.

**Comment by lynxlynxlynx** [comment]
No, it's value of 8, everything matches.

It's fine on master:
![image](https://user-images.githubusercontent.com/121515/112027392-6a6e2e80-8b37-11eb-837b-398ee1e4e978.png)
vs
![image](https://user-images.githubusercontent.com/121515/112027425-70fca600-8b37-11eb-8825-3abd27f2ae39.png)

**Comment by bradallred** [comment]
looks like https://github.com/gemrb/gemrb/blob/2515887fcdbd6929ff3ef8903f5e209fdbcfb33d/gemrb/core/Map.cpp#L3473-L3481

**Comment by MarcelHB** [comment]
Looks good. If there's any regression by this, I'll report in a new ticket.

**Comment by bradallred** [comment]
I just don't understand why they would take an engine that clearly had the functionality to specify this behavior in the game data on a per-animation/wall basis and then just gut it. makes no sense to make the engine _less_ capable. Plus the obviously have the bits in the game data anyway. Feels like we are missing something.

**Comment by lynxlynxlynx** [comment]
Besides there being multiple other occurrences of similar silly behaviour, the fact that different studios were involved and that they didn't always start with the latest engine, iwd2 was developed on a very short cycle. I think initially they had less than a year, so I can imagine people cutting corners, not realizing all the features are there already.
