### ISSUE TITLE
[new game] Making a new game

### ISSUE THREAD

**Issue by m7600** [gemrb/gemrb#1209]
I hope I'm not bothering anyone by opening this issue, and I'm sure that the subject has been discussed many times before. Still, I think we could use this thread for discussing the possibility of making a new game. I know that we already have the demo and that we haven't finished it yet, but if you don't mind, I'd like to start to work also on a new game. Basically it would be an excuse to just go crazy and add a ton of stuff, some of it might end up being useful for the demo.

**Comment by bradallred** [comment]
certainly nobody is going to discourage you from spending your time an such an endeavor.

My 2 bits of advice is to do any such work against the subviews branch, or you will find yourself redoing _a lot_ of GUI scripting. Looks like thats where we've decided to move the continued demo development for presumably the same reason.

I dont know if the main engine repo is the best place to do such work tho. If you create your own repo for the game data it will be easier for you to develop on your own. You can always transfer ownership of the repo to GemRB later on.

**Comment by m7600** [comment]
Thanks brad. Yeah, I agree about working on a different repo, I'll keep you guys updated on what I'm doing, in case any of it turns out to be useful (I'll still make commits to the official GemRB branches though). But basically I just want a space to tests different things without having to worry about introducing new bugs to the game's official branches.

**Comment by lynxlynxlynx** [comment]
Knock yourself out. :) For your own benefit I suggest you first do some planning. Like what art direction are you going for, does the world or the setting impose any limits (eg. no magic, guns, cheese, dinosaurs) and in general what you want to end up in the game.

**Comment by m7600** [comment]
Thanks for the advice guys. It will be a very simple game for now, it will only have:
- A town (the base for the character, with a shop, 1 or 2 NPCs, one of them can join the party)
- A small dungeon (maybe 3 or 4 levels)
- A fight against some monsters in the dungeon
- Boss fight

I'll close this issue then.

**Comment by m7600** [comment]
Here's a legal question that I have. According to this [official FAQ](http://www.wizards.com/default.asp?x=d20/oglfaq/20040123i) from Wizards of the Coast, we cannot technically make a video game that uses D&D rules, such as rolling for ability scores, combat, leveling up, etc. The FAQ is old, but I think that the legal things that it says are still valid today. Actually, since I'm not a lawyer, I don't really understand what the Open Game License and the d20 License allows us to do in terms of software. So if we want to make a free/libre open source game using GemRB, what exactly are we allowed to do, in terms of game mechanics?

**Comment by lynxlynxlynx** [comment]
Well don't use the d20 system then. I wouldn't worry too much about the mechanics, since the original games are but a pale approximation to the ruleset and then there's some tweakability available on top already.

**Comment by MarcelHB** [comment]
You may implement any system you like, even it is virtually copy of what some D&D ruleset does. You may indeed _not_ use any official logo, trademark, copy paragraphs from the rulebook to explain what's happening, and advertise it as an implementation of such a branded spec, unless you adhere to their license requirements.

Of course, you can acquire a license as mentioned in the FAQ and be allowed and disallowed to do things in exchange for some kind official branding -- for making everyone is _Oh great, a d20 game, no need to spend time explaining rules then_.

It is similar to USB: There is absolutely no need to license anything to build an electronically compliant USB device, but without such a license you may not use any well-known assets (logos) for your products, making it look like something from a backyard workshop.

**Comment by m7600** [comment]
Right, thanks for the replies.
