### ISSUE TITLE
 [bug] Spells using Angle for Area of Effect don't hit targets

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#121]
BG2. Such spells e.g. **Cone of Cold or Burning Hands don't hit the target in their cone, if you target them directly**. When working correctly both spells get larger angle/range as levels of the caster increases.  

<details><summary>Spell aim and fire</summary>

![Ready to fire](https://user-images.githubusercontent.com/17316115/54498438-b7cabc00-48dd-11e9-963e-4858f31d76d4.jpg)

![Fired](https://user-images.githubusercontent.com/17316115/54498422-818d3c80-48dd-11e9-9d3e-7ee544f512fb.jpg)
</details>

<details><summary>Cold Cone Spell Description</summary>

![Cold Cone Description](https://user-images.githubusercontent.com/17316115/54498423-8520c380-48dd-11e9-99eb-f1ac4b6030a9.jpg)
</details>

Imoen's targets should have taken damage from the spell. Imoen is level 9 mage. Level 10 mage casts cold cone 10 feet in diameter and 50 feet long. 5 feet long and 1 feet in diameter per level of the caster.

**Comment by lynxlynxlynx** [comment]
50 feet is a lot — please make sure this isn't just a silly description (that it works as it says in the original).

**Comment by cygarniczka** [comment]
You're on point it's silly inaccurate description but the spell at least should hit the targets in the screenshot. The spell has range of 12 feet which is 3.65 meter.

![Cold of Cone NI](https://user-images.githubusercontent.com/17316115/54499019-daf86a00-48e3-11e9-8a89-a219f4d23984.jpg)

**Comment by cygarniczka** [comment]
New finding - if you aim spell (Cold Cone, should work also for Burning Hands) to the side of the target it will hit the target. Spell don't hit the target if you aim it straight at the target.
![Cold Cone SideAim](https://user-images.githubusercontent.com/17316115/54499172-3d059f00-48e5-11e9-8f52-d8322a3bb48b.jpg)
![Cold Cone Side](https://user-images.githubusercontent.com/17316115/54499176-42fb8000-48e5-11e9-8282-5dcc6ba0b8ea.jpg)

**Comment by lynxlynxlynx** [comment]
This is only a problem for certain angles, since we don't normalize the calculation. Phew.

**Comment by cygarniczka** [comment]
This is going to be easy fix?

**Comment by lynxlynxlynx** [comment]
Kinda, I fixed it for this angle pretty fast, but then making sure the math is good in all cases took the better part of yesterday's evening. Just testing remains for today. :)

**Comment by lynxlynxlynx** [comment]
It's fixed properly now.

For future reference, I've attached my table for testing the maths.
[gemrb-cone-angles.zip](https://github.com/gemrb/gemrb/files/3587547/gemrb-cone-angles.zip)
