### ISSUE TITLE
[subviews] Touchscreen input broken and break mouse input

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1211]
#### Bug description
First I don't know if it's supposed to work ?

If  touchscreen is used at least one time to move cursor or click when in main game screen you can't select (by hovering) or click on any button (touchscreen or mouse) on left, right or bottom bar, just on map as if there was only map displayed.

On screenshot you can see cursor totally ignore right bar when hovering it  as if there is none.

On console there are no error.

device : x86 laptop with touchscreen under linux (specifically onemix 2)

#### Steps to reproduce
1. use at least one time touchscreen
2. go to main screen game
3. you can't use or interact with other things than map

#### Screenshots
![touchscreen](https://user-images.githubusercontent.com/55502325/112748426-c9122d00-8fbb-11eb-8aac-e04d134609da.png)

**Comment by lynxlynxlynx** [comment]
Can you always reproduce this, with a fresh load?

**Comment by bradallred** [comment]
One thing to note is that we dont expect dual use of both touchscreen and mouse simultaneously so I can imagine a number of ways for that to not work right.

**Comment by FrElvire** [comment]
Yes it's always reproducible with a fresh load and from memory it doesn't work even if you don't use mouse at all but I will confirm that

**Comment by bradallred** [comment]
you should add the device to the report.

**Comment by FrElvire** [comment]
Yes, even when using only touchscreen, it's not OK (same result -at least visually- when using both). 
If wanted I can add a little video to show the bug

Device added to first pot

**Comment by bradallred** [comment]
can you check if that fixed it? Sadly, I cannot test GemRB on iOS very well anymore because the Python 2.7 distribution that I have doesnt provide the 'collections' module which we depend on so you can load a save, but lots of breakage

however, that change was enough to allow me to actually load the game. before that no buttons did anything useful.

**Comment by FrElvire** [comment]
It's not resolved, but another thing that can help you : 

After menu, in game if the firs touch is 

- on the map (not map button) : you can select/move/ party member and and it is as if the buttons (of the three bars) did not exist
- on the left bar : only this bar and contained button doe anything
- on the bottom bar : will add in some minutes
- on the right bar : will add in some minutes

**Comment by bradallred** [comment]
This is going to sit unresolved until somebody that has a touchscreen device that has a problem comes along. The device I have works fine (or I can't understand your reproduction steps).

I'm assuming you have the latest SDL2 (you can also try building from source). I have no idea how touch devices work on Linux, but I wouldn't be surprised if Linux is not well supported by SDL2 in this way yet.

**Comment by FrElvire** [comment]
Full screen or not give the same result and you can't miss it, it's not playable. I don't have latest version of SDL2, just 2.0.12, i will try with 2.0.14.

**Comment by FrElvire** [comment]
Tried libsdl2 2.0.14, no change

If I use the SDL1 backend everything looks OK ! (outside limitations of SLD1)

Of all this, for you, is it a gemrb bug or an sdl2 bug?

**Comment by bradallred** [comment]
SDL 1 doesn't support touchscreens at all so this tells me the "bug" is at least that you are using your device as both a mouse and a touchscreen at the same time. I'm not sure what to do about that.

**Comment by bradallred** [comment]
https://github.com/gemrb/gemrb/blob/921cc7b15bc82b296d88fa6fe4649235b10d950f/gemrb/plugins/SDLVideo/SDL20Video.cpp#L732-L742

we already handle mouse emulation performed by SDL so your issue is coming from a higher level. You should be able to disable mouse emulation at the device/system level. You should also be able to disable touch input by adding `TouchInput=0` to your gemrb.cfg

**Comment by bradallred** [comment]
I don't see that there is anything for us to do here.
