### ISSUE TITLE
Need for alternative to existing GetTickCount

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1215]
#### Bug description
For as long as I've been compiling GemRB on Windows, there was always one mystery for me: The game does not _feel_ running smoothly, regardless of the SDL backend settings. And despite seeing 30FPS, it never was the case on Linux -- regardless how cheap the CPU/GPU. There it's how it is supposed to feel.

Over the time, I ocassionally debugged into SDL, did profiling but nothing could reveal what's wrong. Unless the whole thing runs in some different time-continuum (like showing 30FPS where seconds are not what we know to be seconds), on Windows at least.

Then [I got a suspicion](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-gettickcount):

> The resolution of the GetTickCount function is limited to the resolution of the system timer, which is typically in the range of 10 milliseconds to 16 milliseconds. 

From what I see, this can end up in all kind of aliasing problems when sampling the time on Windows, including wobbly FPS capping and not-so-smooth animations.

So in contrast to the non-Windows implementation of `GetTickCount` in GemRB that gives 1ms precision, Windows needs something [else](https://github.com/libsdl-org/SDL/blob/bd06538778102f72bad8393ef07da5a1ec444217/src/timer/windows/SDL_systimer.c#L129-L136). 

I did at quick implementation and that's it -- a whole new experience of playing GemRB on Windows (it's like getting a new, higher Hz display). But there are some things to address first:

- [SDL_GetTicks](https://wiki.libsdl.org/SDL_GetTicks) picks what's best and available on a per-platform basis, including fallbacks but it also requires changes to the linking since it would require SDL to be linked against the core.
- We can copy something like this on our own but this requires some refactoring, since BIK/MVE player also need a counter with the surrounding tick variables (currently inlinable code from `globals.h`).

What's your preference? Better addressing this in subviews, or after that?

**Comment by bradallred** [comment]
this is easy now that we require C++11. just use `std::chrono::high_resolution_clock `

**Comment by MarcelHB** [comment]
Yeah, good idea.

**Comment by bradallred** [comment]
it's possibly important to provide a fallback to `std::chrono::steady_clock` if `std::chrono::high_resolution_clock::is_steady` is for some reason `false`. I can't imagine that they are different clocks under the hood tho, but esoteric platforms exist. we could always `assert(std::chrono::high_resolution_clock::is_steady )` and address it if anybody complains.

**Comment by bradallred** [comment]
The C++ committee actually addressed this
> I would not be opposed to deprecating high_resolution_clock, with the intent to remove it after a suitable period of deprecation. The reality is that it is always a typedef to either steady_clock or system_clock, and the programmer is better off choosing one of those two and know what he’s getting, than choose high_resolution_clock and get some other clock by a roll of the dice.

So I guess we should just use `std::chrono::steady_clock`
