### ISSUE TITLE
[BG2] Skald Bard Song not applying effects

### ISSUE THREAD

**Issue by psilyntdev** [gemrb/gemrb#1216]
#### Bug description
The skald's bard song does not apply any effect to themselves or others in the party.

An unkitted bard's 'Bard Song' does function as intended, giving the icon and effects (icon and morale bonus)

GemRB version: v0.8.7-2-g2bf5f904b2
BG2 version: GOG, unmodded

#### Steps to reproduce
1. Create a skald.
2. Active 'Bard Song'. Wait 10 seconds to give the ability time to activate.
3. No expected effect icon appears on bard or other party members (Imoen).
4. Make a save file.
5. Use ShadowKeeper to read the affects on the characters and see that no additional bonuses have been added.

#### Optional steps to reproduce unkitted bard behaving normally for comparison
1. Create a bard.
2. Activate 'Bard Song'. Wait 10 seconds to give the ability time to activate.
3. Music score effect icon appears on bard and party members.
4. Make a save file.
5. Use ShadowKeeper to read the affects on the characters. The icon and two +1 morale bonuses are listed.

#### Expected behavior
It is expected to have the music score icon appear on the character portraits and the effects skald song's attack and damage bonuses applied.

**Comment by psilyntdev** [comment]
With my unmodified GOG install, I've tested this with BG2Main.exe file and through GemRB. When running the same installation through BG2Main.exe, the skald bonuses are working as intended.

**Comment by lynxlynxlynx** [comment]
Thanks. I'll continue this tomorrow, but the different song setting (via clab) works, the delivery works (aoe projectile), the invtrav secondary projectile also works. So EffectQueue::AddAllEffects is the last normal thing ... showing the problem in the data.

In `spcl542a.spl` timing mode is set to 10 (FX_DURATION_JUST_EXPIRED). NI has it as instant/limited, like mode 0, but in ticks, so now I wonder if we should bump the two constants by 1 and add this extra timing mode. Need to check the data for other users first.

**Comment by lynxlynxlynx** [comment]
iesh made this trivial and while I only looked at all the spell headers (not standalone EFFs), no other game has effects with this timing mode and even in bg2 there's only this one user. So congratulations on finding a real corner case. :)
