### ISSUE TITLE
[subviews] PST has wrong scrollbar in the identification service panel

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1219]
#### Bug description
When you go identification-as-a-service at some mercheant, then to the right a description of the identified item appears. Naturally, this often has a lot of text. As you see below to the right, there are two sockets that are supposed to be mount points for a scrollbar, but it appears to the right. To the left, for the inventory scrollbar, this looks as exepected. master is good.

#### Screenshots
![pst_identify](https://user-images.githubusercontent.com/238558/113512860-f71ce180-9566-11eb-8d83-8b6f12f9178d.jpg)

**Comment by lynxlynxlynx** [comment]
So this two things: a dupe of the wrong image issue and the mentioned pst exception of having some scrollbars on the left.

**Comment by lynxlynxlynx** [comment]
Actually it's the correct scrollbar, but it is too high as well as being on the right

**Comment by bradallred** [comment]
the solution is still the same for all these issues. We have to add a `SetScrollbar` method and move `MergeTextAreaAndScrollbar` to `ScrollView`. then it should be a simple matter of reparenting the scrollbar from the window to the `ScrollView`

**Comment by bradallred** [comment]
there, now all that should remain to be done is to handle left handed scrollbars appropriately

**Comment by bradallred** [comment]
I'm closing this. open a new issue if there are regressions. I didn't see any myself in PST.
