### ISSUE TITLE
[bug] Animation ID shifts when tiefling NPC joins or NPC with different ID than it's race

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#122]
**Describe the bug**
As soon as a tiefling NPC joins party it's Animation ID shifts to human. Same goes for any NPC with different animation ID from it's race. The animation ID will shift to its race overriding custom animation ID.

Examples:

### 0)
Death Knight from Durlag Tower has human race in default BGT/ BG1:EE and his animation gets swamped to human

### 1)
Haer'Dalis tifeling male bard animation ID **0x6001** changes to human male bard **0x6300**

Fade mod NPC - tiefling female bard animation ID **0x6311** changes to human female bard **0x6310**
<summary>
<details>
<summary>Haer'Dalis and Fade before joing</summary>

![Haer'Dalis and Fade before joing](https://user-images.githubusercontent.com/17316115/55674730-b0685400-5886-11e9-9681-a8771122537a.jpg)
</details>
<details>
<summary>Tieflings Fade HaerDalis after joining</summary>

![Tieflings Fade HaerDalis after joining](https://user-images.githubusercontent.com/17316115/55674766-0d640a00-5887-11e9-9fe3-d9560e3d00b6.jpg)
</details>

### 2)
Tenya is a female human cleric NPC but has non human animation ID **0x6011** but after joining the party her animation ID changes to female human cleric **0x6010**

<details><summary>Tenya before joining</summary>

![Tenya before joining](https://user-images.githubusercontent.com/17316115/55674801-4ef4b500-5887-11e9-9680-7cacb221563d.jpg)
</details>
<details>
<summary>Tenya after joining</summary>

![Tenya after joinig](https://user-images.githubusercontent.com/17316115/55674812-751a5500-5887-11e9-8079-51970ac2ed37.jpg)
</details>

**To Reproduce**
Have Haer'Dalis join the party and see his animation ID to change to human bard.

**Comment by cygarniczka** [comment]
I recruits into party CTRL+Q Half-Ogre (animation same like TAZOK from BG2) just for hack and changed its animation ID on fly by pressing CTRL+A & CTRL+Z. The animation ID did not bounce back to Half-Ogre. GemRB lets (I think) non playable monster races to change to any animation ID.

**Comment by lynxlynxlynx** [comment]
Really, really?? WTF of a naming convention is that. :angry: 
We don't support non ASCII UTF-8 for files yet, but neither did the original. Might just fit into some 8-bit encoding. 

Anyway, if we can't read them, that's a separate issue.
Btw, I think that's just the omicron, not actual Cyrillic (unless the glyph is the same).

**Comment by cygarniczka** [comment]
I tried to rename bams, 2da, and changing file name in anisnd.2da but GemRB still couldn't load frost giant custom anim it turned frost giant anim into halfling. The naming conversion does not seem to be problem for original engine even if it can't read it. I don't think it would be the problem as I hypothesized before.

**Comment by lynxlynxlynx** [comment]
Ok, this is easily reproducible in the original: bamf to ar0705 and force join Haer'Dalis. But why bother, I just fixed the bug. :)
