### ISSUE TITLE
[subviews] Scrollbar position reset when looting (at least)

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1221]
#### Bug description
When clicking on pile of objects on the floor if there are enough to need a scrollbar there are two difference with master : 

A. Scrollbar is at the bottom (on master on top)
B. Every time an object is selected, scrollbar position is initialized at the bottom (on master stay at a the same position)

#### Steps to reproduce
1. select pile of object on the floor
2. go to the top and select one object

#### Expected behavior
As in master for point B, for the A ???

#### Screenshots
![object_scroll](https://user-images.githubusercontent.com/55502325/114234902-af8bc080-997f-11eb-918d-a2960ceb3843.png)

**Comment by lynxlynxlynx** [comment]
For A the original bg1 behaved like on master, but that should be an easy tweak to reinstate that behaviour.

**Comment by FrElvire** [comment]
Same thing in inventory for objects on floor 

![scrollbar_floor](https://user-images.githubusercontent.com/55502325/114265676-86f0de80-99f2-11eb-879d-5a056e113619.png)

**Comment by lynxlynxlynx** [comment]
Fixed, yuck, but also found another related issue — for a separate report though.
