### ISSUE TITLE
[subviews] Characters are hidden behind dead NPC 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1222]
#### Bug description
Character in master appear on top of dead NPC, and here it's hidden by dead NPC.

#### Screenshots
![hidden_character](https://user-images.githubusercontent.com/55502325/114237092-df889300-9982-11eb-8f16-301315a9b9cb.png)

**Comment by lynxlynxlynx** [comment]
Hmm, looks like you have to make a fresh kill to reproduce — corpses already there on load work fine.

**Comment by lynxlynxlynx** [comment]
This is still a problem even with the wall revert.

**Comment by bradallred** [comment]
stencils only include walls tho, so its not that. draw order for actors is entirely determined by `GenerateQueues` which hasn't changed between the 2 branches (tho the code updating the actor states it uses did). Are we positive this problem doesn't exist on master?

**Comment by bradallred** [comment]
oh sneaky, `GetNextActor` can modify the queue index. this merits investigation.

**Comment by bradallred** [comment]
my guess is that we never hit this `else` condition so the corpse always ends up with the `PR_DISPLAY` priority

```
//dead actors are always visible on the map, but run no scripts
if ((stance == IE_ANI_TWITCH) || (stance == IE_ANI_DIE) ) {
	priority = PR_DISPLAY;
} else {
	//isvisible flag is false (visibilitymap) here,
	//coz we want to reactivate creatures that
	//just became visible
	if (IsVisible(actor->Pos) && actor->Schedule(gametime, false) ) {
		priority = PR_SCRIPT; //run scripts and display, activated now
		//more like activate!
		actor->Activate();
		ActorSpottedByPlayer(actor);
		hostiles_new |= HandleAutopauseForVisible(actor, !hostiles_visible);
	} else {
		priority = PR_IGNORE;
	}
}
```

**Comment by bradallred** [comment]
seems to me that if `IE_ANI_TWITCH` is the actors body on the ground then we should treat it like a corpse

```diff
//dead actors are always visible on the map, but run no scripts
-if ((stance == IE_ANI_TWITCH) || (stance == IE_ANI_DIE) ) {
+if (stance == IE_ANI_DIE) {
	priority = PR_DISPLAY;
} else {
```

however, I assume that `IE_ANI_TWITCH` shouldn't linger forever, so im not sure this will completely fix the problem.

**Comment by lynxlynxlynx** [comment]
I very much doubt that's a good idea, as PR_DISPLAY is the right state for corpses, just like the comment says.

**Comment by bradallred** [comment]
I'm backwards, yes I meant we should be in `PR_DISPLAY`, but are still in `PR_SCRIPT`. thats the only explanation that makes any sense.

**Comment by lynxlynxlynx** [comment]
It's relatively easy to test with what priority it ends up — I can check tomorrow.
