### ISSUE TITLE
[Pathfinder] Summoned fire elemental blocked on it's summon point (a "narrow" bridge)

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1223]
#### Bug description
In IWD1 (Position: ar6002 [3263.2082]) a summoned fire elemental blocked on it's summon point.

Fire elemental : 
Unknown]: Cast spell: sppr605
[Unknown]: Slot: 0
[Unknown]: Type: 0 (1 vs 1)
[Unknown]: Spellname: Conjure Fire Elemental
[Unknown]: Target: 4
[Unknown]: Range: 30

console : 
[FindPath/DEBUG]: Pathing failed for Fire Elemental
[ResourceManager/ERROR]: Couldn't find 'melf.2da'.
[FindPath/DEBUG]: s = (2084, 1848), d = (1900, 1598), caller = Fire Elemental, dist = 86, size = 4
[FindPath/DEBUG]: Pathing failed for Fire Elemental
[ResourceManager/ERROR]: Couldn't find 'melf.2da'.
[FindPath/DEBUG]: s = (2084, 1848), d = (1900, 1598), caller = Fire Elemental, dist = 86, size = 4
[FindPath/DEBUG]: Pathing failed for Fire Elemental
...

GemRB version: subviews

#### Screenshots
![path_fail](https://user-images.githubusercontent.com/55502325/114238484-f7611680-9984-11eb-96c8-5cc6996b2a4d.png)

Same thing, summoned too close of a wall (Position: ar6002 [1024.1798])
![path_fail2](https://user-images.githubusercontent.com/55502325/114240114-4d36be00-9987-11eb-8540-10ce3230c450.png)

**Comment by lynxlynxlynx** [comment]
That looks like it's supposed to. Just needs checking in the original, in case the elemental should have a smaller circle size (looks more appropriate for the bg2 version here).

**Comment by FrElvire** [comment]
I don't know how it's in original, but it doesn't feel logical to be able to summon something which can't stand (and move) on this place.

**Comment by lynxlynxlynx** [comment]
That's a bad argument, since there are many much more narrower spots available as well. A bg2 speedrun technique uses a similar mechanism to skip the first level almost immediately.
