### ISSUE TITLE
[subviews] option window after save or not ?

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1224]
#### Bug description
In subviews after saving you return to option menu, in master you return to game.

Not returning directly to game doesn't help to see that save is not done if you can't (monster nearby by example)

#### Steps to reproduce
1. open option window and do a save
2. you return to option window and not to game

**Comment by lynxlynxlynx** [comment]
Yeah, best to close it either way.

**Comment by bradallred** [comment]
should just be a simple window close handler
