### ISSUE TITLE
Dead NPC die at  game load

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1225]
#### Bug description
I don't know if it's specific to this place and this NPC but at Position: ar6003 [1049.1790] in IWD1 you encounter a dead NPC with some object. After saving you load game and you see the NPC die and you can loot him one more time.

GemRB version: master & subviews

#### Steps to reproduce
1. At ar6003 [1049.1790] in IWD1 loot dead NPC
2. save game
3. load game
4. lyou can loot him one more time

#### Expected behavior
You shouldn't see him dying and you shouldn't be able to take object you have already take

#### Save
[000000001-Quick-Save.zip](https://github.com/gemrb/gemrb/files/6289543/000000001-Quick-Save.zip)

**Comment by lynxlynxlynx** [comment]
Works fine for me. Do you have Heart of Winter installed?

**Comment by FrElvire** [comment]
Yes HOW is installed, even with save ?

I have to redo this zone, I will recheck

**Comment by FrElvire** [comment]
I fail to reproduce on a new run (I tried with and without Ctrl+W as I use it very often), only the included save to reproduce.

Maybe better to close if nothing can be explained by the save as we fail to reproduce it, and maybe someone will reopen it one day ?

**Comment by lynxlynxlynx** [comment]
Yes, let's leave it be then. Thanks
