### ISSUE TITLE
[subviews] only one character on right bar and crash

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1227]
#### Bug description
One time at game load from in game, only first character was displayed on right bar and shortly after (in inventory ?) game crashed.

console :
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/usr/share/gemrb/GUIScripts/GUICommonWindows.py", line 1938, in SelectionChanged
[Python/ERROR]:     SelectionChangeHandler ()
[Python/ERROR]:   File "/usr/share/gemrb/GUIScripts/GUICommonWindows.py", line 1439, in <lambda>
[Python/ERROR]:     selectionHandler = lambda win=window, fn=selectionHandler: fn(win)
[Python/ERROR]:   File "/usr/share/gemrb/GUIScripts/iwd/GUIINV.py", line 120, in UpdateInventoryWindow
[Python/ERROR]:     ScrollBar.SetVarAssoc ("TopIndex", Count)
[Python/ERROR]: AttributeError: 'NoneType' object has no attribute 'SetVarAssoc'

........

[GameData/FATAL]: Saving a store that wasn't cached.

#### Steps to reproduce
I don't know how to reproduce this and haven't think to take a screenshot, reloading same game save after was correct.

I submit this bug in case console log say something to you.

Feel free to close it...

**Comment by lynxlynxlynx** [comment]
No, not enough info, but thanks.
