### ISSUE TITLE
Thief level up issue

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1229]
#### Bug description
I can't take a level of thief, validating does nothing than close level up window.

Other things : 

- life points doesn't get updated correctly : 
     before level up : 59 points
         displayed in level up window : 64/59 or 59/59 (alternately, if you do more than one time)
- skill point stay to 0

#### Steps to reproduce
1. Load save and try to level up 'Alua'

#### Screenshots
subviews : 
![levelup_sub](https://user-images.githubusercontent.com/55502325/114312680-cbb06e80-9af3-11eb-91c2-96c9b9a2c3e9.png)

master : 
![levelup_master](https://user-images.githubusercontent.com/55502325/114312686-d3701300-9af3-11eb-9860-ab80722d6ff5.png)

**Comment by lynxlynxlynx** [comment]
Where's the save? Anyway, it looks like different classes are being leveled up between the two cases.

**Comment by FrElvire** [comment]
oh, forgot the save :( 
[000000064-bug_levelup_thief.zip](https://github.com/gemrb/gemrb/files/6292287/000000064-bug_levelup_thief.zip)

screenshot come from the same save, same character, branch is the only difference

**Comment by lynxlynxlynx** [comment]
Something is broken on master already — comparing GUIREC and the levelup overview (which matches the final state), the levels are wrong and next level mage xp changes.

**Comment by lynxlynxlynx** [comment]
Did you use any cheats? For the xp you have, the mage level is too high.

**Comment by FrElvire** [comment]
No, no cheats, just some "tweak" : 

```
// Log of Currently Installed WeiDU Mods
// The top of the file is the 'oldest' mod
// ~TP2_File~ #language_number #component_number // [Subcomponent Name -> ] Component Name [ : Version]
~IWDFIXPACK/SETUP-IWDFIXPACK.TP2~ #0 #0 // Assorted Fixes: v6
~IWDFIXPACK/SETUP-IWDFIXPACK.TP2~ #0 #100 // Game Text Update: v6
~UB_IWD/SETUP-UB_IWD.TP2~ #0 #0 // The Voice of Durdel Anatha: v8
~UB_IWD/SETUP-UB_IWD.TP2~ #0 #100 // Malavon's Golems: v8
~UB_IWD/SETUP-UB_IWD.TP2~ #0 #200 // Expanded Guello/Beorn Quest: v8
~UB_IWD/SETUP-UB_IWD.TP2~ #0 #300 // Marketh's Ring: v8
~UB_IWD/SETUP-UB_IWD.TP2~ #0 #400 // Presio's Duel: v8
~UB_IWD/SETUP-UB_IWD.TP2~ #0 #500 // Orrick's Rhino Beetle Shield: v8
~UB_IWD/SETUP-UB_IWD.TP2~ #0 #600 // The High Baptist's Flock: v8
~UB_IWD/SETUP-UB_IWD.TP2~ #0 #1500 // Minor Item Restorations: v8
~UB_IWD/SETUP-UB_IWD.TP2~ #0 #2000 // Restored Random Drops: v8
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #130 // Force All Dialogue to Pause Game: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #160 // Make Magic Shields Glow (plainab/grogerson): v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #170 // Unique Icons: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #182 // Unique Containers -> Unique icons and names: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #2010 // Separate Resist Fire/Cold Icon into Separate Icons (Angel): v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #1080 // Add Bags of Holding: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #1120 // Stores Sell Higher Stacks of Items: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #3083 // Increase Ammo Stack Size -> Stacks of 120: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #3093 // Increase Gem and Jewelry Stacking -> Stacks of 120: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #3103 // Increase Potion Stacking -> Stacks of 120: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #3113 // Increase Scroll Stacking -> Stacks of 120: v9
```

**Comment by lynxlynxlynx** [comment]
Well, the level thing is still an anomaly, so you'll have to cheat in some xp or set it back direcly. But I did find a subviews bug, for which I'll open a new report for clarity.
