### ISSUE TITLE
[bug] Sarevok BG1 animation has red shadow

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#123]
**Describe the bug**
The problem is known and noticeable in Gorion's death cutscene and even in mods that use Sarevok BG1 animation **0x6404** e.g. Sarevok ([Wiederherstellung](http://www.baldursgate-refugium.de/mods/sarevok-wiederherstellung/)) Restore mod.

<details>

![Sarevok](https://user-images.githubusercontent.com/17316115/55674978-aeec5b00-5889-11e9-9075-e742ef1b2907.jpg)
![Sarevok RED](https://user-images.githubusercontent.com/17316115/55674979-aeec5b00-5889-11e9-8857-f34cc3550825.jpg)

</details>

**Comment by lynxlynxlynx** [comment]
Since bg2 used the same animation, it should also be visible in the Candlekeep dream sequence.

I think we didn't always have this problem, so a bisect would be good.

**Comment by MarcelHB** [comment]
I guess there never was a shadow animation for BG1 assets ever before, since I introduced them in #75, and animation 0x6404 is something exceptional, from what I see in the list.

**Comment by lynxlynxlynx** [comment]
I got stumped the last time I looked at this. The shadow is actually red, so I don't think any of that pink corruption stuff is in effect. So I guess we do something wrong with the palette, but why just this one?

There's reallly no need for the modded Sarevok, you can just get him in tob or change someone's IE_ANIMATION_ID to that value to reproduce.

**Comment by MarcelHB** [comment]
I think I found the reason: I did not give the shadow animation their own palette, which is coincidentally Ok for most of the actors, as the shadow animation palette and ragdoll animation palette look the same from my quick sampling. With one exception: Sarevok, who has a red color code for 0x01 whereas the default is black.

Maybe I can come up with a solution that loads one (?) distinct palette for shadows and fumble this into or around of `DrawActorSprite`.

**Comment by lynxlynxlynx** [comment]
Why not first try to just use the individual shadow bam's palette? There's just two separate shadow bams and not much overhead, since we have a palette cache.

Plan b would be to add a FLAGS column to avatar_shadows.2da and use that to distinguish this corner case, but that's uglier.

**Comment by MarcelHB** [comment]
Yes, the first suggestion is what I think of.

**Comment by lynxlynxlynx** [comment]
Ok, good. The previous post made it seem like you think it'd be a hack.
