### ISSUE TITLE
[subviews] detected trap not displayed

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1230]
#### Bug description
When finding trap it should be displayed in red (in master at least), here you hear that trap is found but nothing is displayed but you can disarm it.

By example in IWD1 : Position: ar6011 [-198.608]

#### Screenshots
not showed : 
![trap_no_detect](https://user-images.githubusercontent.com/55502325/114313486-049e1280-9af7-11eb-9770-bfde103d0b20.png)

but can be disarmed : 
![trap](https://user-images.githubusercontent.com/55502325/114313579-55ae0680-9af7-11eb-9efa-f6230fcb5f56.png)

**Comment by lynxlynxlynx** [comment]
So detected traps aren't drawn, before and after that everything is fine.
