### ISSUE TITLE
[subviews] Dialog box can hide game screen

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1231]
#### Bug description
In this small area (IWD / ar6011 [-198.608]) (resolution : 1280x720, map smaller than one screen) when dialog box is in it's medium size, you can't see bottom of the screen.

with small size all is displayed (screenshot 1)
With medium size, bottom is cropped (screenshot 2)
With big size, you can scroll viewport to see all (screenshot 3)

#### Screenshots
![map_hidden1](https://user-images.githubusercontent.com/55502325/114314061-77a88880-9af9-11eb-81e2-6c7c79015c81.png)
![map_hidden2](https://user-images.githubusercontent.com/55502325/114314064-7b3c0f80-9af9-11eb-866d-581e82c76c13.png)
![map_hidden3](https://user-images.githubusercontent.com/55502325/114314067-7ecf9680-9af9-11eb-87f3-6810da8f6f86.png)

#### Save, if needed
[000000066-crop_map.zip](https://github.com/gemrb/gemrb/files/6292323/000000066-crop_map.zip)

**Comment by lynxlynxlynx** [comment]
This is resolution dependent, but yeah, should be fixed. Reminds me of #1127
