### ISSUE TITLE
[subviews] IWD1 : Dorn's Deep: Upper Level / secret room / stairs to forge appear without all requirements

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1234]
#### Bug description
In secret room (Position: ar6010 [547.777]) after walking to the correct floor tiles,  when walking to the center of the disk stairs appear. If you quit room an re-enter it stairs are not there anymore (go to the center of the disk and they appear).

In theorie you have to return to the Room with the room with the round table and click on the hammer of the statue who's hammer is down instead of up.

It's OK in master.

**Comment by lynxlynxlynx** [comment]
So you're saying the puzzle works fine the first time, but when you return, you should repeat it / move that horn?

**Comment by FrElvire** [comment]
No it's not exactly that, the puzzle works fine but when completed stairs should not appear, you should first click on the hammer of the statue in the previous room.

**Comment by lynxlynxlynx** [comment]
I tried just bisecting it and oh boy, what an adventure. Git jumps to 2018, even though both good and bad commits are in 2020+. Doesn't like something about our history structure. With --topo-order or --simplify-merges fd8af5f can be identified as the first bad commit, but that's a merge and nothing immediately stands out in its long diff.

Still, more interesting than delving into the actual scripts. Will try some git surgery next. One thing I noticed in the bad commits is that the actor is automatically ordered to move to the center after the third click.

**Comment by fizzet** [comment]
One of the original problems was that the (inoperable) secret door and the stairs below them were intercepting the mouse click instead of the ground tile you were supposed to step on. It sounds like that's again the problem here, so it's likely that the merge in `GameControl::OnMouseOver` (what now seems to be in `UpdateCursor` mostly) went bad. Don't really have the time to investigate myself, though.

**Comment by lynxlynxlynx** [comment]
Thanks, that made it much easier. This fixes it all nicely for me, in case you have any comments:

```diff
diff --git a/gemrb/core/GUI/GameControl.cpp b/gemrb/core/GUI/GameControl.cpp
index e0d97b508..413bd2e37 100644
--- a/gemrb/core/GUI/GameControl.cpp
+++ b/gemrb/core/GUI/GameControl.cpp
@@ -1366,7 +1366,11 @@ void GameControl::UpdateCursor()
        overDoor = area->TMap->GetDoor(gameMousePos);
        // ignore infopoints and containers beneath doors
        if (overDoor) {
-               nextCursor = GetCursorOverDoor(overDoor);
+               if (overDoor->Visible()) {
+                       nextCursor = GetCursorOverDoor(overDoor);
+               } else {
+                       overDoor = nullptr;
+               }
        } else {
                overInfoPoint = area->TMap->GetInfoPoint(gameMousePos, true);
                if (overInfoPoint) {
```
