### ISSUE TITLE
[subviews] When saving a new game, caret disappear when moving it with keyboard

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1237]
#### Bug description
When saving a new game, cursor disappear when moving it first with direction key or backspace. When moved first with mouse no problem after.

reproduced with BG2 and IWD1, OK with master branch

#### Steps to reproduce
1. make a new save
2. add some characters to save name
3. use backspace key or left key
4. cursor disappear

#### Expected behavior
cursor still there

#### Screenshots
![save_name](https://user-images.githubusercontent.com/55502325/115155257-5ad2fe80-a07f-11eb-9c37-580828289506.png)

**Comment by lynxlynxlynx** [comment]
Indeed, the "caret" disappears. Also happens when overwriting old saves.

**Comment by lynxlynxlynx** [comment]
It's initially badly placed. If you click anywhere else in the string or reset it to the end, then everything works as expected. Other movement doesn't have this "healing" property.

**Comment by lynxlynxlynx** [comment]
cursorPoint doesn't get updated in the keyboard case, so it looks it's that end iterator check in TextContainer::DrawContents that needs a rethink / else branch.

**Comment by lynxlynxlynx** [comment]
It's worse, in the kb case DrawContents doesn't even get called, so it's like MarkDirty fails.
