### ISSUE TITLE
 [IWD1] Can't select target of static charge spell

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1239]
#### Bug description
When casting static charge spell, you can't select the target, it's automatically casted on yourself.

Unknown]: Cast spell: sppr412
[Unknown]: Slot: 3
[Unknown]: Type: 0 (1 vs 1)
[Unknown]: Spellname: Static Charge
[Unknown]: Target: 5
[Unknown]: Range: 80

GemRB version: master

**Comment by lynxlynxlynx** [comment]
Even the description says it has a range of Caster and the data follows that. It doesn't have any special projectile set, so I guess we have to fix it in fx_static_charge.

**Comment by lynxlynxlynx** [comment]
Closing, since a duplicate was opened and I didn't notice. #1959
