### ISSUE TITLE
[iwd1/how] place to rest, difference with original 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1240]
#### Bug description
At Position: ar9100 [3686.1560] in gemrb you can rest, in original "you may not rest here".

It's likely just an example

GemRB version: master

**Comment by lynxlynxlynx** [comment]
Are there monsters nearby? Is your party together? Is anyone under any funny effect?

Either way, I doubt there's any real bug.

**Comment by FrElvire** [comment]
no monster ( from memory there are none in this map), party together, no problem to sleep in tavern, exactly same place 

I don't see any common reason to forbid the rest ?

**Comment by lynxlynxlynx** [comment]
Hmm, you can't rest anywhere in that area, but that at least makes more sense.

Looks like we should distinguish between the "indoor" bit and the rest.
gemrb/core/Game.cpp:1760
