### ISSUE TITLE
 [iwd/how] sleep in tavern difference with original

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1241]
#### Bug description
In the tavern (Position: ar9101 [471.788]) when asking to rest, after confirmation (screen1), rest button is greyed and you have to click on done (screen2)

In original after  confirmation, you return to main screen game after a fade from black to normal.

GemRB version: master

#### Screenshots
![rest1](https://user-images.githubusercontent.com/55502325/115997413-5197e380-a5e3-11eb-8469-3ec941a0f614.png)
![rest2](https://user-images.githubusercontent.com/55502325/115997417-55c40100-a5e3-11eb-9f76-100213e875e5.png)

**Comment by lynxlynxlynx** [comment]
I think we're smarter than the original here and only close the window if any resting scripts need to run (dreams, cutscenes). The renting button is greyed out as no room is chosen.

**Comment by FrElvire** [comment]
Here the renting button is greyed as we already agreed to rest but yes it's just different. 

so it's not a bug
