### ISSUE TITLE
[subviews] PST wont load due to missing font

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1249]
PST games wont load because they are missing the "normal" font

the console CHU we added for #842 has "normal" set for the font, but PST doesn't have a font by that name

**Comment by lynxlynxlynx** [comment]
Yeah, in the code we have this abstracted away, but the data can't handle it. Wouldn't just adding another line to fonts.2da, with NORMAL as FONT_NAME fix it though? Basically adding an alias.

**Comment by bradallred** [comment]
I assume so, yes.
