### ISSUE TITLE
[bug] Some Feedback and Sound options don't save and don't work

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#125]
Setting them on won't enable those options. Also when you load a savegame or quit and start the game again those options will be marked off.

Feedback options:
-Actions
-Selection Text
-Combat Information
-State Changes
-Misc

Feedback To Hit Rolls works correctly.

Sound option:
-Battle Cries

This is probably related to NPCs constantly repeating battle cries I mentioned before.

![feedback options](https://user-images.githubusercontent.com/17316115/55898106-e875dc80-5b8f-11e9-86e0-f36a43647cf8.png)
![Sound option](https://user-images.githubusercontent.com/17316115/55898107-e875dc80-5b8f-11e9-8a4e-8f7bf90205ef.jpg)

At first I thought it was 1PP GUI mod messing with those options but I checked on BG2 with TobEX and BG2Fixpack and replicated the same results.

**Comment by lynxlynxlynx** [comment]
Can you dig out which baldur.ini entries these change?

**Comment by cygarniczka** [comment]
It could be GemRB can't set those options because they are nowhere to find in baldur.ini
I only found **Extra Feedback=0** which could relate to marked options in the second screenshot.
Problem is I set those options on and off and 0 stays the same inside the ini. 

GUI Feedback Level=5
Locator Feedback Level=3
Extra Feedback=0 [this setting in ini has no effect on the setting in-game]

Subtitles=0
[No ENTRY FOR BATTLE CRIES]
Footsteps=0
Command Sounds Frequency=1
Selection Sounds Frequency=1

**Comment by lynxlynxlynx** [comment]
It could all be stored in that one variable. Try this:
- copy baldur.ini here: https://www.diffchecker.com/
- rerun and change all these options
- copy baldur.ini in the other box and Find Difference

This will then show you just the lines — settings changed.

**Comment by cygarniczka** [comment]
This website is nifty I like it. :)

All six from the first screenshot:
-To Hit Rolls (this button works)
-Actions
-Selection Text
-Combat Information
-State Changes
-Miscellaneous
Are controlled  by **Effect Text Level.**

When all six are on the value is Effect Text Level=63. When all are off the value is 0.

Second screenshot 

Subtitles  ==> 	Subtitles=1 (button works)
Battle Cries ==> 	**Attack Sounds=1**
Character Movement Sounds ==> 	Footsteps=1 (button works)
Command Sounds ==>           Command Sounds Frequency=2 (button works)
Selection Sounds ==>            Selection Sounds Frequency=2 (button works)

**Comment by lynxlynxlynx** [comment]
Ok, please try individual settings for Effect Text Level (disable all but one). It's a bitfield, so the values will be 2, 4, 8, 16 and 32, besides the one you already mentioned.

**Comment by cygarniczka** [comment]
Effect Text Level=1  ==> To Hit Rolls
Effect Text Level=2 ==> Combat Information
Effect Text Level=4  ==> Actions
Effect Text Level=8 ==> State Changes
Effect Text Level=16 ==> Miscellaneous
Effect Text Level=32 ==> Selection Text

**Comment by lynxlynxlynx** [comment]
If you set it to 63, do you get saving throw feedback? What if you set it to? Please type a typical line — I found the following strings, but they don't include the rolls, so they can't be the whole thing, if they're used at all.

20246:@14797 = ~Made Saving Throw versus Poison~
20247:@14798 = ~Made Saving Throw versus breath weapon~
20248:@14799 = ~Made Saving Throw versus Spells~
20249:@14800 = ~Made Saving Throw versus Petrification~
20250:@14801 = ~Made Saving Throw versus rods, staffs and wands~

**Comment by cygarniczka** [comment]
I tried setting it 63 in gem-baldur.ini and game does not display saving throw feedback. Strings in dialog.tlk 14797 through 14801 have proper saving throw info.

**Comment by lynxlynxlynx** [comment]
No, you have to test this in the original, which means modifying baldur.ini.

**Comment by cygarniczka** [comment]
Yes 63 displays info about saving throws. 
![wqwqe43qwer](https://user-images.githubusercontent.com/17316115/56853877-ba1c2f00-68fb-11e9-9338-4cae57fe9acc.jpg)

**Comment by lynxlynxlynx** [comment]
This has now been fixed. The war cry will toggle party war cries, while the feedback levels are mostly educated guesses (pst has more useful help text).
