### ISSUE TITLE
Shops: add red overlay for unsellable items 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1250]
Merchants can be picky and we should be more obvious about it. #426 The original uses a red tint:
https://imgur.com/Bkzar4H

All the code is in GUISTORE.py and the buttons should just get an overlay like for unusable items.

**Comment by rsantellan** [comment]
After some tinkering I have:
![image](https://user-images.githubusercontent.com/1820598/131235629-b230067d-d175-4cb7-80c7-528f415b1602.png)
That is better than use to be:
![image](https://user-images.githubusercontent.com/1820598/131235645-f678d0ae-ff98-4a33-8df6-f66035fa6b88.png)
But not really like should be:
![image](https://user-images.githubusercontent.com/1820598/131235650-8cb09d7e-f9c5-4a9b-8ba1-b3811e46112d.png)
The problem is that the item do not have colors, so is more than a layout to it.
I was looking and is a function to change colors:
https://github.com/gemrb/gemrb/blob/adeda7953862c6258889a9e961d09ca004b43e76/gemrb/core/Video/Video.cpp#L338
It this a correct way to aproach the change of color of the item to a more sepia one ?
Going down the rabbit hole.....

**Comment by lynxlynxlynx** [comment]
That would clearly require different blending, so yeah, by not going the red overlay route, you've made the problem harder.

**Comment by rsantellan** [comment]
@bradallred  one question about this:
https://github.com/gemrb/gemrb/blob/adeda7953862c6258889a9e961d09ca004b43e76/gemrb/core/Video/Video.cpp#L348
It was supposed to pass an extra flag to show the sepia and gray scale ? Why the todo is there ?

**Comment by bradallred** [comment]
the TODO is there because we don't handle `BlitFlags::GREY` or `BlitFlags::SEPIA` for drawing primitives, Shouldn't be relevant tho, I cant see why you would need to.

**Comment by bradallred** [comment]
`Button.SetOverlay` is terribly named and isn't what you want. You want `Button.EnableBorder` (which is also terribly named). Honestly, the 2 should be combined somehow. Really all we need is a set of rectangles with colors which would be much simpler and a lot more flexible.

**Comment by rsantellan** [comment]
@bradallred the problem is that the item maintain the color, so I was thinking on taking out the color of the item and that with the EnableBorder should accomplish it. But perhaps I'm over-complicating a simple issue.

**Comment by bradallred** [comment]
the OP shows a screenshot that just has a red overlay. Your screenshot shows disabled buttons. those 2 things are accomplished in different ways.

**Comment by rsantellan** [comment]
@bradallred I will try that, I took the screenshots from the original game, don't know where the OP screenshot where taken.

**Comment by rsantellan** [comment]
@bradallred GButton do not have a SetDisabled is only for the buttons on the bottom, searching how to do it. Sorry for the bothering!!

**Comment by bradallred** [comment]
sure they do, it is inherited from `GView`

**Comment by rsantellan** [comment]
> sure they do, it is inherited from `GView`
I made a typo and have the wrong name. **Button.SetState (IE_GUI_BUTTON_DISABLED)** The state is disabled that accomplish the same. And it look the same as the first screenshot that I uploaded....

**Comment by lynxlynxlynx** [comment]
That's why I suggested to fix it halfway first with just the "overlay" (=border). It might even be correct for some games.

**Comment by bradallred** [comment]
sounds like the item images dont come from a BAM that has the disabled state (or we dont properly set it up)

**Comment by rsantellan** [comment]
@bradallred where I can read more about the BAM files and how are used ?

**Comment by bradallred** [comment]
just use NearInfinity to view them

**Comment by rsantellan** [comment]
Searching with the NearInfinity I find that the items has two states:

![image](https://user-images.githubusercontent.com/1820598/131765352-ba26ffe6-711e-4bb7-85f0-4a3e56c5061a.png)

Where I can look for the disabled state ? Could not exists and be made removing the image colors on the fly ?

**Comment by bradallred** [comment]
two possibilities:
1. there is another BAM with more frames
2. yes, draw the icon with `BlitFlags::Sepia` or `BlitFlags::Grey`

**Comment by rsantellan** [comment]
@bradallred searchin with NearInfinity I can't find a BAM with the disabled state. I can't find where to draw the item button with the **SEPIA** or **GRAY** flags. I'm looking at: https://github.com/gemrb/gemrb/blob/adeda7953862c6258889a9e961d09ca004b43e76/gemrb/core/GUI/Button.cpp#L206
Perhaps I will  just put the overlay with the item color below just as @lynxlynxlynx said and leave it when I learn more.
