### ISSUE TITLE
[subviews] Non-initials first char color regression

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1253]
Non-initials initial character color is white:
![image](https://user-images.githubusercontent.com/121515/119219987-684d2f80-bae8-11eb-9b69-478151cb3f82.png)

**Comment by lynxlynxlynx** [comment]
This was caused by the fix for #1149 9bd8596e, but doesn't affect #1252.

**Comment by bradallred** [comment]
for BG2 when using the `INITIALS` font, specifically the item info window

**Comment by lynxlynxlynx** [comment]
Hmm, now some initals are not drawn ok:
![image](https://user-images.githubusercontent.com/121515/119334443-6cfe1900-bc8b-11eb-952d-a51149c3e26f.png)
![image](https://user-images.githubusercontent.com/121515/119334474-738c9080-bc8b-11eb-84a4-52ae45050ccc.png)
I double checked that it's not a consequence of #1251.

**Comment by bradallred** [comment]
of course not, nobody has gone and changed their color to white yet

**Comment by lynxlynxlynx** [comment]
Can't we do this internally? If the initials font is different from the main one, color it white, otherwise use the initials color by default. If someone ever wants differently colored ttf initials, the python binding remains.

**Comment by bradallred** [comment]
according to the code (and comments) that would result in the problem in OP returning.

https://github.com/gemrb/gemrb/blob/a845a54967d0662daf4b02653e19ea07dbb473db/gemrb/core/GUI/TextArea.cpp#L467-L490

We can add/change something in fonts.2da to suppress tinting

**Comment by lynxlynxlynx** [comment]
Ah, too bad.
