### ISSUE TITLE
can't unmemorize spells any more

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1259]
Tried only bg1 and bg2 so far, but the error is generic:
```
[GUIScript/ERROR]: Runtime Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "../gemrb/GUIScripts/GUIPR.py", line 320, in OnPriestUnmemorizeSpell
[Python/ERROR]:     if GemRB.UnmemorizeSpell (pc, type, level, index):
[Python/ERROR]: RuntimeError: Spell not found!

[GUIScript/ERROR]: Runtime Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "../gemrb/GUIScripts/GUIMG.py", line 383, in OnMageUnmemorizeSpell
[Python/ERROR]:     if GemRB.UnmemorizeSpell (pc, type, level, index):
[Python/ERROR]: RuntimeError: Spell not found!
```

As unlikely as it looks, it is a regression since the merge.

**Comment by bradallred** [comment]
AFIK, `GemRB.UnmemorizeSpell` didn't change, so the suspect is `index = GemRB.GetVar ("SpellButton")`.

**Comment by bradallred** [comment]
hmmm, looks like the problem is actually that `VarName` is the empty string...

**Comment by bradallred** [comment]
it looks like `UpdateMageWindow` is getting called when we push the button which calls `SetVarAssoc` which then erases the value of "SpellButton"

**Comment by lynxlynxlynx** [comment]
With my last push it looks fine with mages and sorcerers, so only priests remain.

**Comment by bradallred** [comment]
then we just need to apply the same change as 62f76ad to GUIPR

**Comment by lynxlynxlynx** [comment]
And give OpenMageSpellUnmemorizeWindow some parameters, as now we pass them and discard them.

**Comment by lynxlynxlynx** [comment]
Yeah, looks fine now, though I did notice two other problems: sorcerers can erase known spells, erasing known spells erases the wrong one (last). Looking into it.
