### ISSUE TITLE
[iwd1] can not load save 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1261]
#### Bug description

I can't load my iwd1 saves (tried several saves and it's ok with bg2) anymore, you see the loading screen but after you return to save list instead of game.

didn't try with 0.8.8 or master... didn't have time to check...., I will try tomorrow

GemRB version: subviews at least

**Comment by lynxlynxlynx** [comment]
Closing dupe of #1258. Please check the list before reporting. ;)

**Comment by FrElvire** [comment]
ouch...sorry...

**Comment by lynxlynxlynx** [comment]
Don't worry, testing is very much appreciated, especially right now after such a big merge.
