### ISSUE TITLE
Compiler error in Actor.cpp with GCC/Ubuntu

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1265]
I wanted to try out the latest state, but obviously there is something a gcc v10.3 does not like:

```
/mnt/shared/Sources/gemrb/gemrb/core/Scriptable/Actor.cpp: In function ‘void GemRB::InitActorTables()’:
/mnt/shared/Sources/gemrb/gemrb/core/Scriptable/Actor.cpp:2453:33: error: argument 1 range [18446744071562067968, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Werror=alloc-size-larger-than=]
 2453 |    wspattack[i] = (int *) calloc(wspattack_cols, sizeof(int));
      |                           ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/10/cstdlib:75,
                 from /mnt/shared/Sources/gemrb/gemrb/includes/Platform.h:54,
                 from /mnt/shared/Sources/gemrb/gemrb/includes/ie_types.h:31,
                 from /mnt/shared/Sources/gemrb/gemrb/includes/globals.h:31,
                 from /mnt/shared/Sources/gemrb/gemrb/core/Animation.h:26,
                 from /mnt/shared/Sources/gemrb/gemrb/core/CharAnimations.h:27,
                 from /mnt/shared/Sources/gemrb/gemrb/core/Scriptable/Scriptable.h:26,
                 from /mnt/shared/Sources/gemrb/gemrb/core/Scriptable/Actor.h:24,
                 from /mnt/shared/Sources/gemrb/gemrb/core/Scriptable/Actor.cpp:25:
/usr/include/stdlib.h:542:14: note: in a call to allocation function ‘void* calloc(size_t, size_t)’ declared here
  542 | extern void *calloc (size_t __nmemb, size_t __size)
      |              ^~~~~~
```
Looks like there better be some sign-related cast around `wspattack_cols` but I cannot dig deeper right now.

**Comment by lynxlynxlynx** [comment]
Hmm, that's odd — I've been on gcc 10 the whole time (on the main machine) and this line has been unchanged since 2009.

**Comment by lynxlynxlynx** [comment]
Does changing wspattack_cols type to unsigned fix it for you?

**Comment by bradallred** [comment]
changing the type _shouldn't_ change anything since there is a conversion to unsigned upon passing it. Seems like a weird compiler optimization bug. I suspect Marcel is compiling with -O3 and you are not.

**Comment by MarcelHB** [comment]
You're right, this is what my last CMake run obviously generated as flags:

`-Werror -Wno-error=inline -Wno-error=cast-align -Wmissing-declarations -Wcast-align -Winline -Wno-error=stringop-truncation -Wall -W -Wpointer-arith  -pedantic -Wno-format-y2k -Wno-long-long -fsigned-char -fvisibility=hidden -fno-stack-protector -Wimplicit-fallthrough=2 -O3 -DNDEBUG -fPIC   -UNDEBUG -std=gnu++11`

**Comment by MarcelHB** [comment]
Also not sure if it's some weird deduction for optimization battling some security mechanism to prevent potentially abnormous allocations, anyway that _can_ silence the error:

```cpp
wspattack[i] = (int *) calloc(static_cast<uint32_t>(wspattack_cols), sizeof(int));
```

**Comment by bradallred** [comment]
if you're gonna cast, just cast to the type `calloc` asks for, else you get 2 conversions

**Comment by MarcelHB** [comment]
In theory, I'd agree. But compiler says not to `size_t`.

**Comment by lynxlynxlynx** [comment]
I'll just take the opportunity and rewrite it out completely by using containers and moving it to GameData.
