### ISSUE TITLE
BG2 Sansuki don't doing nothing 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1266]
#### Bug description
On the bridge district Sansuki aproach and ask for help. When the vampires arrive nothing happens.

I press CTRL + M on the three of them.

[Actor/DEBUG]: Debugdump of Actor Sansuki (Sansuki, Sansuki):
Scripts: vvshaesc <none> <none> <none> vvsansuk initdlg <none> wtasight
Area:       ar0500 ([2863.2178])
Dialog:     vvsansuk    TalkCount:  1
Global ID:  11138   PartySlot: 0
Script name:vvsansuk    Current action: -1    Total: 0
Int. Flags: 0x50a00    MC Flags: 0x0    Allegiance: 128   current allegiance:128
Class:      2   current class:2    Kit: 0 (base: 0)
Race:       1   current race:1
Gender:     1   current gender:1
Specifics:  0   current specifics:0
Alignment:  23   current alignment:23
Morale:     10   current morale:10
Moralebreak:5   Morale recovery:60
Visualrange:28 (Explorer: 0)
Fatigue: 0 (current: 0)   Luck: 0
Movement rate: 10 (current: 10)

Levels (average: 14):
FIGHTER: 14    
current HP:105
Mod[IE_ANIMATION_ID]: 0x6300 ResRef:chmb1 Stance: 1
TURNUNDEADLEVEL: 0 current: 0
Colors:       505288990   707406378   1061109567   202116108   387389719   471598364   33686018
WaitCounter: 0
LastTarget: 0 <NULL>    LastSpellTarget: 0 <NULL>
LastTalked: 10002 none
INVENTORY:
10:     FIST - (1 0 0) Fl:0x2029 Wt: 0 x 0Lb
35:   sw1h43 - (1 0 0) Fl:0x2c61 Wt: 0 x 6Lb
Equipped: 0       EquippedHeader: 0
Total weight: 6
SPELLBOOK:
EFFECT QUEUE:
  0: 0x07: Color:SetPalette (5, 21) S:sw1h43
  1: 0x07: Color:SetPalette (25, 20) S:sw1h43
  2: 0x07: Color:SetPalette (25, 16) S:sw1h43

) eyMap]: Looking up key: 
[Actor/DEBUG]: Debugdump of Actor Vampire (Vampire, Vampire):
Scripts: vvvamesc <none> <none> <none> vvmale2 <none> vampir01 wtasight
Area:       ar0500 ([2820.2154])
Dialog:     vvmale2    TalkCount:  0
Global ID:  11141   PartySlot: 0
Script name:vvmale2    Current action: -1    Total: 0
Int. Flags: 0x50a00    MC Flags: 0x0    Allegiance: 128   current allegiance:128
Class:      163   current class:163    Kit: 0 (base: 0)
Race:       125   current race:125
Gender:     1   current gender:1
Specifics:  0   current specifics:0
Alignment:  33   current alignment:33
Morale:     10   current morale:10
Moralebreak:0   Morale recovery:1
Visualrange:28 (Explorer: 0)
Fatigue: 0 (current: 0)   Luck: 0
Movement rate: 11 (current: 11)

Levels (average: 9):

current HP:75
Mod[IE_ANIMATION_ID]: 0x7F12 ResRef:mvam Stance: 1
TURNUNDEADLEVEL: 0 current: 0
Colors:       421075225   976894522   976894522   1397969747   370546198   505290270   454761243
WaitCounter: 0
LastTarget: 0 <NULL>    LastSpellTarget: 0 <NULL>
LastTalked: 0 <NULL>
INVENTORY:
 7:  vampreg - (0 0 0) Fl:0x6828 Wt: 0 x 0Lb
 8:  immune1 - (0 0 0) Fl:0x2029 Wt: 0 x 0Lb
10:     FIST - (1 0 0) Fl:0x2029 Wt: 0 x 0Lb
35:     vamp - (1 0 0) Fl:0x6069 Wt: 0 x 0Lb
Equipped: 0       EquippedHeader: 0
Total weight: 0
SPELLBOOK:
EFFECT QUEUE:
  0: 0x10b: Protection:String (54337, 78) S:vampreg
  1: 0x10b: Protection:String (39752, 78) S:vampreg
  2: 0x65: Protection:Opcode (0, 78) S:vampreg
  3: 0x62: State:Regenerating (2, 3) S:vampreg
  4: 0x65: Protection:Opcode (0, 24) S:vampreg
  5: 0xce: Protection:Spell (-1, 25) S:vampreg
  6: 0xce: Protection:Spell (-1, 25) S:vampreg
  7: 0xce: Protection:Spell (-1, 25) S:vampreg
  8: 0x10b: Protection:String (14017, 25) S:vampreg
  9: 0x10b: Protection:String (14662, 25) S:vampreg
 10: 0x65: Protection:Opcode (0, 25) S:vampreg
 11: 0x10b: Protection:String (14001, 39) S:vampreg
 12: 0x65: Protection:Opcode (0, 217) S:vampreg
 13: 0x65: Protection:Opcode (0, 39) S:vampreg
 14: 0x65: Protection:Opcode (0, 93) S:vampreg
 15: 0x65: Protection:Opcode (0, 3) S:vampreg
 16: 0x128: Protection:Animation (0, 5) S:vampreg
 17: 0x10b: Protection:String (14780, 5) S:vampreg
 18: 0x10b: Protection:String (14672, 5) S:vampreg
 19: 0x10b: Protection:String (8364, 5) S:vampreg
 20: 0x65: Protection:Opcode (0, 5) S:vampreg
 21: 0x128: Protection:Animation (0, 109) S:vampreg
 22: 0x128: Protection:Animation (0, 109) S:vampreg
 23: 0x10b: Protection:String (14102, 109) S:vampreg
 24: 0x65: Protection:Opcode (0, 175) S:vampreg
 25: 0x65: Protection:Opcode (0, 109) S:vampreg
 26: 0xad: PoisonResistanceModifier (100, 0) S:vampreg
 27: 0x65: Protection:Opcode (0, 216) S:vampreg
 28: 0x128: Protection:Animation (0, 106) S:vampreg
 29: 0x10b: Protection:String (17427, 106) S:vampreg
 30: 0x10b: Protection:String (14007, 106) S:vampreg
 31: 0xce: Protection:Spell (0, 0) S:vampreg
 32: 0x65: Protection:Opcode (0, 106) S:vampreg
 33: 0x10b: Protection:String (41495, 0) S:vampreg
 34: 0x10b: Protection:String (40968, 0) S:vampreg
 35: 0x10b: Protection:String (40969, 0) S:vampreg
 36: 0x10b: Protection:String (40979, 0) S:vampreg
 37: 0x10b: Protection:String (41616, 0) S:vampreg
 38: 0x65: Protection:Opcode (0, 23) S:vampreg
 39: 0x78: Protection:Weapons (-1, 2) S:immune1
 40: 0xce: Protection:Spell (0, 0) S:vamp

[OpenAL]: Playing Next Music
[ResourceManager]: Searching for 'SPC1'...
[ResourceManager]: Found 'SPC1.acm' in 'Music'.
[MUSImporter]: Playing SPC1...
[OpenAL]: Queuing New Music
) eyMap]: Looking up key: 
[Actor/DEBUG]: Debugdump of Actor Vampire (Vampire, Vampire):
Scripts: vvvamesc <none> <none> <none> vvmale1 <none> vampir01 wtasight
Area:       ar0500 ([2890.2148])
Dialog:     vvmale1    TalkCount:  0
Global ID:  11140   PartySlot: 0
Script name:vvmale1    Current action: -1    Total: 0
Int. Flags: 0x50a00    MC Flags: 0x0    Allegiance: 128   current allegiance:128
Class:      163   current class:163    Kit: 0 (base: 0)
Race:       125   current race:125
Gender:     1   current gender:1
Specifics:  0   current specifics:0
Alignment:  33   current alignment:33
Morale:     10   current morale:10
Moralebreak:0   Morale recovery:1
Visualrange:28 (Explorer: 0)
Fatigue: 0 (current: 0)   Luck: 0
Movement rate: 11 (current: 11)

Levels (average: 9):

current HP:75
Mod[IE_ANIMATION_ID]: 0x7F12 ResRef:mvam Stance: 1
TURNUNDEADLEVEL: 0 current: 0
Colors:       421075225   976894522   976894522   1397969747   370546198   505290270   454761243
WaitCounter: 0
LastTarget: 0 <NULL>    LastSpellTarget: 0 <NULL>
LastTalked: 0 <NULL>
INVENTORY:
 7:  vampreg - (0 0 0) Fl:0x6828 Wt: 0 x 0Lb
 8:  immune1 - (0 0 0) Fl:0x2029 Wt: 0 x 0Lb
10:     FIST - (1 0 0) Fl:0x2029 Wt: 0 x 0Lb
35:     vamp - (1 0 0) Fl:0x6069 Wt: 0 x 0Lb
Equipped: 0       EquippedHeader: 0
Total weight: 0
SPELLBOOK:
EFFECT QUEUE:
  0: 0x10b: Protection:String (54337, 78) S:vampreg
  1: 0x10b: Protection:String (39752, 78) S:vampreg
  2: 0x65: Protection:Opcode (0, 78) S:vampreg
  3: 0x62: State:Regenerating (2, 3) S:vampreg
  4: 0x65: Protection:Opcode (0, 24) S:vampreg
  5: 0xce: Protection:Spell (-1, 25) S:vampreg
  6: 0xce: Protection:Spell (-1, 25) S:vampreg
  7: 0xce: Protection:Spell (-1, 25) S:vampreg
  8: 0x10b: Protection:String (14017, 25) S:vampreg
  9: 0x10b: Protection:String (14662, 25) S:vampreg
 10: 0x65: Protection:Opcode (0, 25) S:vampreg
 11: 0x10b: Protection:String (14001, 39) S:vampreg
 12: 0x65: Protection:Opcode (0, 217) S:vampreg
 13: 0x65: Protection:Opcode (0, 39) S:vampreg
 14: 0x65: Protection:Opcode (0, 93) S:vampreg
 15: 0x65: Protection:Opcode (0, 3) S:vampreg
 16: 0x128: Protection:Animation (0, 5) S:vampreg
 17: 0x10b: Protection:String (14780, 5) S:vampreg
 18: 0x10b: Protection:String (14672, 5) S:vampreg
 19: 0x10b: Protection:String (8364, 5) S:vampreg
 20: 0x65: Protection:Opcode (0, 5) S:vampreg
 21: 0x128: Protection:Animation (0, 109) S:vampreg
 22: 0x128: Protection:Animation (0, 109) S:vampreg
 23: 0x10b: Protection:String (14102, 109) S:vampreg
 24: 0x65: Protection:Opcode (0, 175) S:vampreg
 25: 0x65: Protection:Opcode (0, 109) S:vampreg
 26: 0xad: PoisonResistanceModifier (100, 0) S:vampreg
 27: 0x65: Protection:Opcode (0, 216) S:vampreg
 28: 0x128: Protection:Animation (0, 106) S:vampreg
 29: 0x10b: Protection:String (17427, 106) S:vampreg
 30: 0x10b: Protection:String (14007, 106) S:vampreg
 31: 0xce: Protection:Spell (0, 0) S:vampreg
 32: 0x65: Protection:Opcode (0, 106) S:vampreg
 33: 0x10b: Protection:String (41495, 0) S:vampreg
 34: 0x10b: Protection:String (40968, 0) S:vampreg
 35: 0x10b: Protection:String (40969, 0) S:vampreg
 36: 0x10b: Protection:String (40979, 0) S:vampreg
 37: 0x10b: Protection:String (41616, 0) S:vampreg
 38: 0x65: Protection:Opcode (0, 23) S:vampreg
 39: 0x78: Protection:Weapons (-1, 2) S:immune1
 40: 0xce: Protection:Spell (0, 0) S:vamp

I attach the save file.

[000000035-Sansuki.tar.gz](https://github.com/gemrb/gemrb/files/6601899/000000035-Sansuki.tar.gz)

GemRB version:  v0.8.8

#### Steps to reproduce
1. Go to 'Bridge district'
2. Go to bottom of the map
3. See Sansuki

#### Expected behavior
Del appear and have a conversation of vampires. Another weird thing is that this happen during daytime 

#### Screenshots
![image](https://user-images.githubusercontent.com/1820598/120877008-8015c080-c58a-11eb-8490-162707c65567.png)

**Comment by rsantellan** [comment]
Found her at the bottom of the map and that trigger the rest of the scene.

![image](https://user-images.githubusercontent.com/1820598/120877711-6eceb300-c58e-11eb-8847-a3182862762d.png)

I read that was a bug with her path finding, but she was standing there doing nothing

**Comment by lynxlynxlynx** [comment]
Do you have any mods installed? A save? This is the script block from vampsttp.bcs that triggers the encounter:

```
IF
  Detect([PC])
  Range([PC],20)
  OR(3)
    Global("AmaWaukeen","GLOBAL",0)
    Dead("shthass1")  // ~Ama~
    !AreaCheck("AR0700")
  CombatCounter(0)
  GlobalLT("Chapter","GLOBAL",4)
  Global("VampShadWar","GLOBAL",3)
  Global("WorkingForBodhi","GLOBAL",0)
  GlobalTimerExpired("VampShadTimer","GLOBAL")
  OR(2)
    TimeGT(24)
    TimeLT(DAWN_START)
THEN
  RESPONSE #100
    SetGlobal("VampShadWar","GLOBAL",4)
    SetGlobalTimer("VampShadTimer","GLOBAL",3600)
    CreateCreatureObject("VVPARIS",Myself,0,0,0)  // ~Parisa~
    CreateCreatureObject("VVSHAD6",Myself,0,0,0)  // ~Shadow Thief~
    ActionOverride("VVPARIS",FaceObject("VVSHAD6"))
    ActionOverride("VVSHAD6",FaceObject("VVPARIS"))
END
```
Which is fine, but it does have a night time check!

**Comment by rsantellan** [comment]
Hi @lynxlynxlynx I added the save in the first comment. 

This is my weidu.log

// Log of Currently Installed WeiDU Mods
// The top of the file is the 'oldest' mod
// ~TP2_File~ #language_number #component_number // [Subcomponent Name -> ] Component Name [ : Version]
~DDRAWFIX/DDRAWFIX.TP2~ #0 #0 // DDrawFix -> Force DirectDraw Emulation: v1.0
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #0 // BG2 Fixpack - Core Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #1001 // BG2 Fixpack - Game Text Update -> GTU Classic (from Baldurdash, by Kevin Dorner): v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #3 // BETA Core Fixes (please check the readme!): v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #100 // Party Gets XP for Sending Keldorn to Reconcile With Maria: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #101 // Improved Spell Animations: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #103 // Mixed-Use Dagger Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #104 // Ghreyfain's Holy Symbol Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #106 // Giants Receive Penalties When Attacking Halflings, Dwarves, and Gnomes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #107 // Remove Dual-Classing Restriction from Archers and Stalkers: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #108 // Remove Second Attribute Bonus for Evil Path in Wrath Hell Trial: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #109 // Corrected Summoned Demon Behavior: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #110 // Additional Script Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #111 // Bard Song Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #112 // Wizard Slayers Cause Miscast Magic on Ranged Attacks: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #113 // Additional Alignment Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #114 // Change Free Action to Protect Against Stun: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #116 // Remove Thieving Start Bonuses from Bard and Ranger Skills: v13
~WIDESCREEN/WIDESCREEN.TP2~ #0 #1 // Widescreen Mod -> for GemRB: Widescreen Mod v3.07

Regards

**Comment by lynxlynxlynx** [comment]
Ok, so it is actually dawn already, that's why it triggered.

**Comment by lynxlynxlynx** [comment]
Cool, was a generic bug. I've fixed it (not yet pushed), but it won't matter for this particular save. Luckily the encounter is irrelevant and you can simply continue it by talking to Del.

**Comment by lynxlynxlynx** [comment]
The positioning is now fixed, but the whole concept of this dialog's scripting is a bit whack. I'll open a clean issue for it.
