### ISSUE TITLE
BG2: Really slow to start merchant sequence 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1269]
#### Bug description
On the slums when talking with Bernard after you ask to see the things he sells he keep walking and then open up the screen.

GemRB version: v0.8.8

#### Steps to reproduce
1. Go to the  Copper Coronet
2. Click on Bernard
3. Ask to see what he has on tap

#### Expected behavior
Start merchant dialog inmediatly

#### Screenshots

https://user-images.githubusercontent.com/1820598/120899334-9b71e180-c605-11eb-9a97-a6aff033a25c.mp4

**Comment by lynxlynxlynx** [comment]
Yeah, I noticed that too, thanks for the permanent reminder. 👍🏾

**Comment by lynxlynxlynx** [comment]
I'm not sure the original behaves differently, but it's worth trying to fix. It's his own script that's causing the move and the fact that we need one tick more to start the store.

**Comment by rsantellan** [comment]
I don't have the original installed in this machine :( but I found this guy on youtube playing the original https://youtu.be/VHtpw69Sz2Y?t=423 it should open after conversation.

**Comment by lynxlynxlynx** [comment]
Like I said, it depends on the timing, sometimes it works fine. 

It looks like we should clear the target's queue once the dialog has been established. So probably best done in DialogHandler::InitDialog. Too invasive to do right now though.
