### ISSUE TITLE
port GemRB_Window_SetupControls to python

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#127]
`GemRB_Window_SetupControls` is currently a GUIScript.cpp function, but we need it to be more flexible in the similar way SetupSpellIcons was ripped out and moved into what is now Spellbook.py.

Approach: Create a SetupControls function in GUICommonWindows.py and start migrating logic from the c++ version. Perhaps new private GUIScript functions will be needed to make it possible. Change the user(s) to use the new SetupControls.

A bit of a blocker for #96 and #135 , but kinda blocked by #95 .

**Comment by rsantellan** [comment]
@lynxlynxlynx any tip of how to start this ? I'm having troubles with getting the actor by id on the python side (where I can find a example) and understanding PARSE_ARGS method in https://github.com/gemrb/gemrb/blob/ef5288538b6b82cbd1a89207517e1529173a1992/gemrb/plugins/GUIScript/GUIScript.cpp#L10818
Where I can look up some documentation ?

**Comment by bradallred** [comment]
`PARSE_ARGS` is just a wrapper around `PyArg_ParseTuple` which is documented [here](https://docs.python.org/3/c-api/arg.html)

**Comment by lynxlynxlynx** [comment]
If you look at who's calling the function, you can see everyone is using `GemRB.GameGetFirstSelectedActor ()
` to get the pc. It can replace the whole `actor` block in the function and can be looked up from within, doesn't need to be a parameter.

You've chosen a pretty difficult issue to work on considering your experience. I suggest you pick something else instead and can help you choose if you want.

**Comment by rsantellan** [comment]
> If you look at who's calling the function, you can see everyone is using `GemRB.GameGetFirstSelectedActor () ` to get the pc. It can replace the whole `actor` block in the function and can be looked up from within, doesn't need to be a parameter.
> 
> You've chosen a pretty difficult issue to work on considering your experience. I suggest you pick something else instead and can help you choose if you want.

What will be a good first issue for me instead ?
Regards

**Comment by bradallred** [comment]
they are usually tagged as [good first issue](https://github.com/gemrb/gemrb/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)

**Comment by lynxlynxlynx** [comment]
#1420 looks nicely contained and well explained.

**Comment by rsantellan** [comment]
> #1420 looks nicely contained and well explained.

I will look to that one! Thanks!
