### ISSUE TITLE
BG2 Tanar'ri is casting when speaking 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1272]
#### Bug description
On the Planar Sphere when meeting Tanar'ri he start attacking when speaking to him.

GemRB version: v0.8.8

#### Steps to reproduce
See video

#### Expected behavior
He should have the courtesy of finish speaking before attacking.

#### Screenshots

https://user-images.githubusercontent.com/1820598/120946326-728b4280-c712-11eb-98bf-30b5a1e11e76.mp4

### Save file

[000000039-He is cheating.tar.gz](https://github.com/gemrb/gemrb/files/6605252/000000039-He.is.cheating.tar.gz)

### This is the log

[OpenAL]: Music in INITIAL State. AutoStarting
[ResourceManager]: Searching for 'mghl_re'...
[ResourceManager]: Found 'mghl_re.bmp' in 'chitin.key'.
[ResourceManager]: Found 'bag02.sto' in 'Cache'.
[ResourceManager]: Found 'bag05.sto' in 'Cache'.
[GameScript]: Displaying string on: valygar
[ResourceManager]: Searching for 'valyga31'...
[ResourceManager]: Found 'valyga31.wav' in 'chitin.key'.
[FindPath/DEBUG]: s = (2400, 935), d = (2239, 1090), caller = Valygar, dist = 0, size = 2
[FindPath/DEBUG]: s = (2379, 944), d = (2239, 1090), caller = Valygar, dist = 0, size = 2
[FindPath/DEBUG]: s = (2272, 1018), d = (2175, 1218), caller = Valygar, dist = 0, size = 2
[FindPath/DEBUG]: s = (2163, 1207), d = (2168, 1317), caller = Valygar, dist = 0, size = 2
[ResourceManager]: Searching for 'ARM_03d'...
[ResourceManager]: Found 'ARM_03d.wav' in 'chitin.key'.
[FindPath/DEBUG]: s = (2163, 1315), d = (2185, 1392), caller = Valygar, dist = 0, size = 2
[FindPath/DEBUG]: s = (2179, 1399), d = (2185, 1520), caller = Valygar, dist = 0, size = 2
[ResourceManager]: Found 'abydem01.dlg' in 'Override'.
[ResourceManager]: Found 'CGUI1070.chu' in 'Override'.
[ResourceManager]: Searching for 'guwbtp38'...
[ResourceManager]: Found 'guwbtp38.mos' in 'Override'.
[ResourceManager]: Found 'CGUI1070.chu' in 'Override'.
[ResourceManager]: Searching for 'guwbtp18'...
[ResourceManager]: Found 'guwbtp18.mos' in 'Override'.
[ResourceManager]: Found 'CGUI1070.chu' in 'Override'.
[ResourceManager]: Searching for 'CHA_sm00'...
[ResourceManager/WARNING]: Couldn't find 'CHA_sm00'... Tried CHA_sm00.wav CHA_sm00.acm CHA_sm00.wav CHA_sm00.ogg 
[ResourceManager]: Searching for 'CHA_sm00'...
[ResourceManager/WARNING]: Couldn't find 'CHA_sm00'... Tried CHA_sm00.wav CHA_sm00.acm CHA_sm00.wav CHA_sm00.ogg 
[ResourceManager]: Found 'mtan.2da' in 'chitin.key'.
[2DAImporter/WARNING]: Bad signature (mtan.2da)! Complaining, but not ignoring...
[Actor]: Getting sound 2da mtan entry: Battle_Cry
[FindPath/DEBUG]: s = (2155, 1763), d = (2179, 1519), caller = Tanar'ri, dist = 74, size = 3
[ResourceManager]: Found 'CGUI1070.chu' in 'Override'.
[ResourceManager]: Searching for 'guwbtp28'...
[ResourceManager]: Found 'guwbtp28.mos' in 'Override'.
[ResourceManager]: Found 'mtan.2da' in 'chitin.key'.
[2DAImporter/WARNING]: Bad signature (mtan.2da)! Complaining, but not ignoring...
[Actor]: Getting sound 2da mtan entry: Battle_Cry
[ResourceManager]: Searching for 'sttravl1'...
[ResourceManager]: Found 'sttravl1.bmp' in 'chitin.key'.
[EffectQueue]: effect resisted: State:Hold
[EffectQueue]: effect resisted: Color:BriefRGB
[EffectQueue]: effect resisted: VisualSpellHit
[EffectQueue]: effect resisted: PlaySound
[EffectQueue]: effect resisted: PlaySound
[ResourceManager]: Searching for 'sharea1'...
[ResourceManager]: Found 'sharea1.bmp' in 'chitin.key'.
[ResourceManager]: Searching for 'shair1'...
[ResourceManager]: Found 'shair1.bmp' in 'chitin.key'.
[InitRound]: Name: Tanar'ri | Attacks: 4 | Start: 3377944
[Actor/DEBUG]: Performattack for Tanar'ri, target is: Valygar
[MUSImporter]: Loading /home/rodrigo/games/BaldurGate2/bg2new/music/mx0013.mus...
[ResourceManager]: Searching for 'Mx0013/Mx0013A'...
[ResourceManager]: Found 'Mx0013/Mx0013A.acm' in 'Music'.
[MUSImporter]: Playing Mx0013/Mx0013A...
[OpenAL]: Music in INITIAL State. AutoStarting
[Actor/DEBUG]: Performattack for Tanar'ri, target is: Valygar
[Attack/COMBAT]: (Main) Left: 3 | Next: 3377968 [Hit]
[ModifyDamage/COMBAT]: Resisted 0 of 15 at 0% resistance to 256
[Actor/COMBAT]: 15 unknown damage taken.

**Comment by lynxlynxlynx** [comment]
Sounds like it's a non-pausing dialog. Maybe just the fact that the text is displayed is suboptimal, but that would also conflict with other needs (#405). Needs more investigating.

**Comment by rsantellan** [comment]
@lynxlynxlynx the problem is that he has an edge because doesn't have the spelling time. Is like when you close the window the spells are cast without casting time.

**Comment by lynxlynxlynx** [comment]
Those are most likely not normal spells, but abilities cast from scripts, quite possibly deliberately without casting time (eg. with ForceSpell or ReallyForceSpell). 

Either way, first order of business is to use ctrl-m to find his script name and dialog file name. Then checking if the dialog is pausing or not.

**Comment by rsantellan** [comment]
This is ctrl+m on him.

) eyMap]: Looking up key: 
[Actor/DEBUG]: Debugdump of Actor Tanar'ri (Tanar'ri, Tanar'ri):
Scripts: shoutdlg <none> <none> <none> tanari <none> wtasight <none>
Area:       ar0414 ([2155.1763])
Dialog:     abydem01    TalkCount:  0
Global ID:  10044   PartySlot: 0
Script name:abydem01    Current action: -1    Total: 0
Int. Flags: 0x150a00    MC Flags: 0x0    Allegiance: 128   current allegiance:128
Class:      160   current class:160    Kit: 0 (base: 0)
Race:       121   current race:121
Gender:     4   current gender:4
Specifics:  0   current specifics:0
Alignment:  33   current alignment:33
Morale:     10   current morale:10
Moralebreak:0   Morale recovery:60
Visualrange:28 (Explorer: 0)
Fatigue: 0 (current: 0)   Luck: 0
Movement rate: 10 (current: 10)

Levels (average: 10):

current HP:94
Mod[IE_ANIMATION_ID]: 0x1100 ResRef:mtan Stance: 1
TURNUNDEADLEVEL: 0 current: 0
Colors:       505290270   623191333   960051513   202116108   387389207   471604252   0
WaitCounter: 0
LastTarget: 0 <NULL>    LastSpellTarget: 0 <NULL>
LastTalked: 0 <NULL>
INVENTORY:
 7: ringdemn - (0 0 0) Fl:0x2829 Wt: 0 x 0Lb
10:     FIST - (1 0 0) Fl:0x2029 Wt: 0 x 0Lb
15:   misc6m - (0 0 0) Fl:0x2d01 Wt: 0 x 25Lb
18:   scrl73 - (1 0 0) Fl:0x6ca1 Wt: 5 x 0Lb
35:  s1-12m2 - (1 0 0) Fl:0x6069 Wt: 0 x 0Lb
Equipped: 0       EquippedHeader: 0
Total weight: 25
SPELLBOOK:
EFFECT QUEUE:
  0: 0xc1: InvisibleDetection (0, 1) S:
  1: 0x78: Protection:Weapons (-1, 2) S:ringdemn
  2: 0xce: Protection:Spell (-1, 25) S:ringdemn
  3: 0xce: Protection:Spell (-1, 25) S:ringdemn
  4: 0xce: Protection:Spell (-1, 25) S:ringdemn
  5: 0x10b: Protection:String (14017, 25) S:ringdemn
  6: 0x10b: Protection:String (14662, 25) S:ringdemn
  7: 0x65: Protection:Opcode (0, 25) S:ringdemn
  8: 0xad: PoisonResistanceModifier (100, 0) S:ringdemn
  9: 0x128: Protection:Animation (0, 5) S:ringdemn
 10: 0x10b: Protection:String (14780, 5) S:ringdemn
 11: 0x10b: Protection:String (14672, 5) S:ringdemn
 12: 0x10b: Protection:String (8364, 5) S:ringdemn
 13: 0x65: Protection:Opcode (0, 5) S:ringdemn
 14: 0x65: Protection:Opcode (0, 76) S:ringdemn
 15: 0x10b: Protection:String (14791, 128) S:ringdemn
 16: 0x10b: Protection:String (14782, 128) S:ringdemn
 17: 0x128: Protection:Animation (0, 128) S:ringdemn
 18: 0x65: Protection:Opcode (0, 128) S:ringdemn
 19: 0x128: Protection:Animation (0, 24) S:ringdemn
 20: 0x10b: Protection:String (17427, 24) S:ringdemn
 21: 0x10b: Protection:String (14007, 24) S:ringdemn
 22: 0xce: Protection:Spell (-1, 135) S:ringdemn
 23: 0xce: Protection:Spell (-1, 135) S:ringdemn
 24: 0xce: Protection:Spell (-1, 135) S:ringdemn
 25: 0x65: Protection:Opcode (0, 135) S:ringdemn
 26: 0x65: Protection:Opcode (0, 24) S:ringdemn
 27: 0x65: Protection:Opcode (0, 23) S:ringdemn
 28: 0x65: Protection:Opcode (0, 106) S:ringdemn

**Comment by lynxlynxlynx** [comment]
Yeah, it's not a pausing dialog (pause specifically disabled).

**Comment by lynxlynxlynx** [comment]
Definitely practically a problem — if you wait long enough to end the dialog, it'll queue so many spell attacks that you're doomed.

**Comment by lynxlynxlynx** [comment]
huh, in the original something else paused the game — time to look at the scripts:
https://youtu.be/eFgIZfav-hA?t=736

**Comment by lynxlynxlynx** [comment]
his dialog payload doesn't fire (pillar, summon imps, turn hostile) and his regular combat ai takes over.

**Comment by lynxlynxlynx** [comment]
It worked fine in 0.8.7, regression from e14fe1ac.
