### ISSUE TITLE
pst: can break dialog window by pressing Show more when you should chose an option

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1275]
It just closes the window and one is stuck:
![image](https://user-images.githubusercontent.com/121515/121078298-0e7f8180-c7d9-11eb-9041-9fb9492d8a6b.png)

Is there a way to detect when an option list is presenting?

**Comment by bradallred** [comment]
shouldn't we just disable that button in dialog? even if you could detect that aren't there dialog nodes that have no options that would have the same result?

**Comment by lynxlynxlynx** [comment]
It's basically the pst continue button, so it's possible it's just a bug on the python side.

**Comment by lynxlynxlynx** [comment]
Commenting out the close in NextDialogState avoids the main problem, but pressing the button still has bad effects — it just picks the first option, potentially looping.
