### ISSUE TITLE
pst worldmap hovering glitches 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1276]
![image](https://user-images.githubusercontent.com/121515/121213780-d6cb1500-c87e-11eb-9b8d-67fcea016b72.png)

I also noticed we take a recolor parameter when constructing it, that's currently unused. But that might be for the bg1 icons.

**Comment by bradallred** [comment]
its obvious that the alpha is set to 0 since its cutting a hole

**Comment by bradallred** [comment]
https://github.com/gemrb/gemrb/blob/bde0b2e7d9532ba69aae9f89cae29a010ff814d1/gemrb/core/GUI/WorldMapControl.cpp#L97-L104

don't know which of those blit cases we fall in, but either way the icon must have a completely transparent alpha. I have no idea what kind of resource these are in PST. it could also be we are setting the palette to a palette with no alpha.

https://github.com/gemrb/gemrb/blob/bde0b2e7d9532ba69aae9f89cae29a010ff814d1/gemrb/core/WorldMap.cpp#L85-L123

**Comment by bradallred** [comment]
are we sure this "recoloring" is actually a palette swap and not just a blending operation? IIRC we have icons that are colored slightly different than the originals and that might be why.

**Comment by lynxlynxlynx** [comment]
I'm sure this worked on subviews at some point, since we had regressions with the worldmap a few times. The icons look fine (or as fine as before) in the rest of the games. I don't know if that unused recolor parameter is of any significance, but can check its evolution later.

**Comment by bradallred** [comment]
regardless, its pretty clear from examining the originals that we never had this right. Annoyingly, I cant seem to screenshot from wine, the wine window is always black for some reason. Can you screenshot the BG1 normal/hover and the PST normal/hover and I can match them.

the multiply blend mode looks right, but as you can see it affects the color key and causes the transparency there to be lost in SDL2
<img width="136" alt="image" src="https://user-images.githubusercontent.com/1126744/121411826-4691dc00-c921-11eb-85b4-318e6c7503a4.png">

SDL1
<img width="122" alt="image" src="https://user-images.githubusercontent.com/1126744/121412085-8bb60e00-c921-11eb-9b72-1020cca6b6be.png">

its also clear from playing with the text fg/bg colors that the text is just black on the tooltip bg color
<img width="131" alt="image" src="https://user-images.githubusercontent.com/1126744/121416708-58c24900-c926-11eb-826d-292312a0aea5.png">

which may indicate that these map icons are composited similar to how text is done

**Comment by lynxlynxlynx** [comment]
Ah, it could I was on sdl1 at those two points when the pst wmap was broken. I checked `recolor`: it was indeed added for bg1 and its palette override a long time ago in 826bab7a.

bg1 visited, potential yet unvisited (bluish tint) and unvisited (sepia?):
![image](https://user-images.githubusercontent.com/121515/121421109-1de40380-c96e-11eb-923c-125e2876bc7b.png)

On hover it's flashing red in all cases, which is tracked in #1244 

pst had no hovering change (also doesn't run in wine any more):
https://youtu.be/7D02maTw3_8?t=104

**Comment by lynxlynxlynx** [comment]
The colors are a bit too strong in bg1 and unvisited areas are miscolored (this looks to behave differently than bg2 — only known, border accessible areas unvisited areas are blue), but overall it works:
![image](https://user-images.githubusercontent.com/121515/121537154-f8a1d480-ca03-11eb-8149-f77956f8f552.png)
