### ISSUE TITLE
it appears that GF_DIALOGUE_SCROLLS and GF_ANIMATED_DIALOG are the same

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1279]
as the title says we have 2 game flags that are apparently the same. what is the best way to remove one?

should we redo the flags as an enum while we are at it?

**Comment by lynxlynxlynx** [comment]
The values aren't hardcoded anywhere, so we're free to change them and just remove something from the middle. An enum sounds fine; the only thing I remember is that we do some manipulation after reading to be able to store all of them and that there's an unspecified upper limit because of it.
