### ISSUE TITLE
pst journal: entries randomly in a horrid black color

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1283]
Maybe it's related to the color tags we're using? Setting the TA color manually doesn't change anything. Sometimes I get a properly drawn entry and the second one's text is bad (title ok), sometimes all content is black ... can't quite put a finger on it.

**Comment by lynxlynxlynx** [comment]
Buying drinks in stores prints in black too and it also uses an initial. The first SetText with it draws fine, everything else Appended is black.

**Comment by bradallred** [comment]
I wonder if its the changes to `GemMarkupParser::ParseColor` since the format asks for 4 bytes. My understanding was that `swscanf` would still parse fewer and just leave the alpha unset which in this case is already `0xff`.

**Comment by lynxlynxlynx** [comment]
It's nothing in ParseColor, even forcing alpha doesn't change things.  The CHU has good color info:
![image](https://user-images.githubusercontent.com/121515/148674579-bb3f847c-215e-434d-bb3d-c3c850bec4eb.png)
But we use all-black:
![image](https://user-images.githubusercontent.com/121515/148674610-7cb440b7-9def-4a3c-8db0-20db5970cb9b.png)

**Comment by lynxlynxlynx** [comment]
Interesting, found that I can reproduce it reliably now and it's always just the last journal entry that is bad:
![image](https://user-images.githubusercontent.com/121515/155857375-f407c7fb-90df-4008-bf2b-7e916b3e88bc.png)
It doesn't matter which it is or how many there are, it's immediately visible. 

As if the color after a color tag is closed is ill-defined. In fact, just appending an empty tag pair at the end hides the bug, so it seems like a bug somewhere in the parser.

**Comment by bradallred** [comment]
seems likely that it's just bad defaults on the `TextContainer` we pass into `ParseMarkupStringIntoContainer`. We are going to be hitting the `if (token.length()) {` check which is going to append text without overriding attributes. Using `SetText` works because that calls `ClearText`, which sets the defaults on the `TextContainer`.  Calling `TextArea::SetColor` doesnt change those defaults for some reason.

**Comment by lynxlynxlynx** [comment]
ParseMarkupStringIntoContainer is only ran for tagged text, so bad defauls could be an explanation, as they would affect the other code path as well. Looks like nothing is calling `TextContainer::SetColors` by default, but `ClearText` does.

**Comment by lynxlynxlynx** [comment]
Yeah, that does it:
```
--- a/gemrb/core/GUI/TextArea.cpp
+++ b/gemrb/core/GUI/TextArea.cpp
@@ -407,6 +407,7 @@ void TextArea::SetColor(const Color& color, COLOR_TYPE idx)
        assert(idx < COLOR_TYPE_COUNT);
        colors[idx] = color;
        parser.ResetAttributes(ftext, {colors[COLOR_NORMAL], colors[COLOR_BACKGROUND]}, finit, {colors[COLOR_INITI
ALS], colors[COLOR_BACKGROUND]});
+       textContainer->SetColors(colors[COLOR_NORMAL], colors[COLOR_BACKGROUND]);
 }
 
 void TextArea::SetColor(const Color* color, COLOR_TYPE idx)
```

**Comment by bradallred** [comment]
> Looks like nothing is calling TextContainer::SetColors by default, but ClearText does.

I think CHUImporter does, but seems you figured it out. Looks like the appropriate fix to me.
