### ISSUE TITLE
[demo] Green background of the protagonist animation in build bot for Linux

### ISSUE THREAD

**Issue by m7600** [gemrb/gemrb#1286]
In the latest build bot for linux, the protagonist animation is surrounded by a green background, instead of transparent.
![Screenshot from 2021-06-13 15-11-08](https://user-images.githubusercontent.com/56371872/121818198-19fcfd80-cc5c-11eb-9613-c589b78a8f17.png)

**Comment by lynxlynxlynx** [comment]
Can now confirm also on my main machine. From the image, from my build dir the transparency is still fine.

**Comment by Laulajatar** [comment]
I have the same issue with Baldur's Gate 1. I just downloaded the new 0.9 AppImage, dropped it in there and made a new save, didn't change any config or add any mods yet. 

![Green](https://user-images.githubusercontent.com/68446748/122608185-12828d80-d07c-11eb-946b-dd33ba7d0a25.png)

I'm not sure which info is useful, I'm using the GOG version, Manjaro on Kernel 5.10 and a Nvidia GPU.

**Comment by lynxlynxlynx** [comment]
Thanks, it could be sdl (2.0.8) on the build bot and/or an interaction with #1290.

**Comment by bradallred** [comment]
it has nothing to do with #1290. color keys are handled in software. This is almost certainly a bug in an old version of SDL2.

**Comment by STyx2909** [comment]
Whatever I have the same problem on Xubuntu 20.04.x with Ubuntu's Nvidia drivers (340.108).
GemRB 0.9.0

**Comment by burner1024** [comment]
Same for me in PST and ubuntu/intel.

**Comment by bradallred** [comment]
has anybody actually tried updating SDL2 and rebuilding?

**Comment by m7600** [comment]
brad: I think my SDL2 is up to date. I've built GemRB from source using the tarball, and I've also done it by cloning the github repo first. Everything went well, the game runs fine, without that green thing. The problem for me only happens when I use the build bot images.

**Comment by bradallred** [comment]
thanks for confirming. We will have to update the build bot, ideally to the latest.

**Comment by lynxlynxlynx** [comment]
No, we just need to update sdl, at worst building it ourselves. The point of appimages is to have maximum compatibility, so we need them built on the oldest host available to not accidentally drag in too new glibc and stdc++ requirements.

**Comment by lynxlynxlynx** [comment]
Here's a ppa with sdl2 backports:
https://launchpad.net/~cybermax-dexter/+archive/ubuntu/sdl2-backport

**Comment by lynxlynxlynx** [comment]
Looks fine to me now; someone please verify with the latest build (and reopen if you still have problems):
https://sourceforge.net/projects/gemrb/files/Buildbot%20Binaries/Linux/

**Comment by STyx2909** [comment]
All clear! good job.
