### ISSUE TITLE
[demo] replace .chu and .bam files with open source formats 

### ISSUE THREAD

**Issue by m7600** [gemrb/gemrb#1288]
Support for .chu and .bam files, among others, are necessary for running the original games, but I was wondering if they could be replaced with open source formats for the demo. 

If you agree, I'll start to look into it.

**Comment by bradallred** [comment]
nobody is going to stop you from pursuing whatever interests you. What is the benefit tho? seems like a lot of work and I suspect not much is going to map cleanly to the GUI classes which would then require necessary additional complexity added to support both.

It would be helpful if you had an actual idea in mind for what you want to do and why. Most shortcomings of the CHU can be corrected via Python scripts. Also, if we were to spend time supporting a new GUI dataset I would think we would gain more from whatever BGEE uses for eventual compatibility there.

**Comment by m7600** [comment]
True, thanks for the feedback. The EE games use .chu files, I think.

I think that the idea that I had for this suggestions was that it would be good if we could stop depending on DLTCEP, NearInfinity, etc. These are great programs and I'm very grateful to their creators. It's just that I think that modding the GemRB demo or eventually a new game could be easier if we didn't have to rely on specialized programs for creating and editing .chu files, or other files that require those programs.

**Comment by m7600** [comment]
Ok I'll close this issue then, it's true that it would be a lot of work for very little benefit.

**Comment by bradallred** [comment]
the EE games use [something else](https://forums.beamdog.com/discussion/48994/the-new-ui-system-how-to-use-it) in addition to CHU

I see you point about the pain of DLTCEP and NI tho, but again, without an actual proposal I dont know how the situation would be improved by anything. You never even said what you were thinking about using.

**Comment by m7600** [comment]
Oh, you mean the .menu format? Or Lua scripting?

Regarding what to use instead of .chu and .bam... I don't know. Yeah, I should have given this more thought before posting it.

**Comment by m7600** [comment]
Ok, I've given this some thought. For .bam files, maybe they could be replaced by sprite sheets in .png format. I know that .png might never get support, though. Still, if that format was supported, then there would be no need to use cycles and frames. Actually, each sprite would behave like a frame, and each row or column in the sprite sheet would behave like a cycle. The advantage of this would be that the number of files would be reduced greatly, you wouldn't need a file for the walking animation and another one for standing and another one for attacking, etc. Everything would be in the same file.

**Comment by bradallred** [comment]
we already support PNG. We have sprite sheets too, but only the fonts use them sadly. It's on a list somewhere to utilize them for animations too. You would still need some auxiliary information with the PNG to specify the rectangles and cycles etc. At least I don't understand how you would specify an animation without that extra info. Keep in mind animations can play forward and backwards and many frames will be used in many animations. To me this looks like an _increase_ in the number of files since BAM encompasses all that.

**Comment by bradallred** [comment]
have you ever tried BAM Workshop? It looks pretty easy to use, but also looks windows only.

**Comment by m7600** [comment]
You're right, the demo has several .png files, for example for the backgrounds of some windows, the player's portrait, etc. I don't know what I was thinking when I wrote that comment.

I have Bam Workshop, I run it with Wine. It's a good program but it has some weird bugs, I think that NearInfinity and DLTCEP are enough for bam editing. The good thing about Bam Workshop that the other programs don't have is that you can paint and edit the pixels themselves. I sometimes use it only for that reason.

**Comment by lynxlynxlynx** [comment]
Once we get BAM2 support quite a lot of the tedium of BAM files will go away, since there won't be any palette related issues, a limited colorspace, to worry about.
