### ISSUE TITLE
Python3: status icons displayed wrong everywhere

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1289]
- [ ] misaligned on the portraitwindow
- [ ] in the records window, wrong characters get used (usually looks like four dashes)

**Comment by bradallred** [comment]
the second issue sounds like we are treating them as unicode strings. we should be building them as byte strings in python and extracting their raw bytes on the C++ side.

**Comment by lynxlynxlynx** [comment]
Yeah, something like that. The type changed to an int, so it can't be concatenated as before anymore, so now it's just wrapped in str() to avoid erroring out.

**Comment by bradallred** [comment]
well then it sounds like mostly we just need to do `bytes()` instead of `str()`

**Comment by bradallred** [comment]
Ok, I've looked at the code more and done some digging. we cant combine the text and states together because doing so will cause python to decode the bytes as unicode.

instead, we have to use `GemRB_TextArea_Append` to append each segment so that the text segments are unicode and the states segments are raw byte strings

**Comment by lynxlynxlynx** [comment]
Since everything works mostly fine and this will require refactoring how the description is set up, let's postpone it. I don't see problems with the portrait window any more either — a happy surprise.

**Comment by MarcelHB** [comment]
It's actually as bad as breaking (German version; but it was today that I switched from Py 2.7 to 3.9): Load screen does not finish itself and UI gets messed up. Errors are like:

```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "D:/Sources\gemrb\gemrb\GUIScripts\iwd2/LoadScreen.py", line 63, in EndLoadScreen
[Python/ERROR]:     TMessageTA.Append("[p][color=f1f28d]" + GemRB.GetString (HintStr) + "[/color][/p]\n")
[Python/ERROR]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 28: invalid continuation byte
```

**Comment by bradallred** [comment]
that sounds like a separate issue to me

**Comment by MarcelHB** [comment]
No idea :man_shrugging: 

I looked into the sources and discovered that there is obviously some things to take care around `GUIScript` and `PythonConversions`, both in terms in backward- and forward-compat. (even when just considering v3.x). And then I noticed this issue that sounds like going this direction.

**Comment by bradallred** [comment]
a new issue detailing the "obvious things to take care of" other than state "strings" would be useful. We clearly aren't aware of them.

**Comment by MarcelHB** [comment]
One obvious thing, or at least an hypothesis: Non-ASCII bytes, as for ISO-8859-1 aren't fully supported for now. The error above complains an `ä` in one of the strings.

I will open another more-or-less related issue.

**Comment by bradallred** [comment]
also, shouldn't your problem be fixed by setting your encoding to `ISO-8859-1` instead of `uff-8`?

**Comment by bradallred** [comment]
the portrait icons I have fixed, but the fix completely prevents GUIREC from executing. Its going to take a bit of time to rewrite all of necessary code there.

**Comment by bradallred** [comment]
I decided against a rewrite and extended `GemMarkup` to allow us to reinterpret integer strings as character literals

**Comment by lynxlynxlynx** [comment]
The pluses for the count are from a different font or what? I didn't expect proficiencies to be a problem.

**Comment by bradallred** [comment]
its not a font or '+' problem, its the fractions for attacks per round

**Comment by lynxlynxlynx** [comment]
Ah, I think that's been broken for a while then.

**Comment by lynxlynxlynx** [comment]
Opening a separate issue, since it's neither python3-only or from the states font.
