### ISSUE TITLE
Actors sometimes turn translucent

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1290]
I thought it might be a dithering regression, since this is on SDL2, but the topmost goblin and pile don't intersect with any walls. I've seen it with pcs as well and any movement fixes it for a while.

![image](https://user-images.githubusercontent.com/121515/122000192-b6cfb000-cdae-11eb-91eb-22e6304d5329.png)

Sadly no reproducer yet.

**Comment by bradallred** [comment]
yeah, that looks more like `BLIT_HALFTRANS` (unless you mean SDL2 without GL)

I only see we add `BLIT_HALFTRANS` when `APP_HALFTRANS` is set

**Comment by lynxlynxlynx** [comment]
Appearance flags are mostly if not completely a pst thing. We also don't modify them at runtime, so that's definitely not it.

**Comment by lynxlynxlynx** [comment]
bg2 ar0311 is a good test case. It does appear to be some sort of dithering stencil problem, since a simple chair can turn you wholly translucent:
![image](https://user-images.githubusercontent.com/121515/122279510-66f50400-cee8-11eb-8be8-9810dfd96f04.png)
![image](https://user-images.githubusercontent.com/121515/122279608-85f39600-cee8-11eb-8b56-b27e5d638028.png)
![image](https://user-images.githubusercontent.com/121515/122279665-9a379300-cee8-11eb-8f50-5a2357c4e736.png)
One clear pattern is when the actor is intersecting the polygon base, but that's definitely not the whole story.
![image](https://user-images.githubusercontent.com/121515/122279782-baffe880-cee8-11eb-9459-112aa01e86ae.png)

**Comment by lynxlynxlynx** [comment]
Any quick fixes, fast wins available here?

**Comment by bradallred** [comment]
is this with GL or no? if its GL try turning off render batching with `SDL_HINT_RENDER_BATCHING`

**Comment by bradallred** [comment]
if that has no effect we probably just need to tickle SDL into realizing the render state has changed by doing something like `SDL_DrawPoint(renderer, -1, -1)`... probably right after we unbind the texture.

**Comment by lynxlynxlynx** [comment]
[SDL20Video/DEBUG]: Renderer: opengl 

Disabling SDL_HINT_RENDER_BATCHING seems to work fine, no problem in that room and the "real" room walls still behave properly.

**Comment by lynxlynxlynx** [comment]
Should we just remove it or is there some case where it's indeed needed? Now it's only ifdefed to newer sdl2.

**Comment by bradallred** [comment]
batching is a big performance enhancement. We _want_ it, but disabling it wont break anything. we should see if ticking the renderer with my other suggestions fixes it instead.

**Comment by lynxlynxlynx** [comment]
Ok, please give it a shot. Do you not get the same problem?

Also, if you have anything else small lying around like maybe the map icon improvements, now is the time. I want to release tomorrow, as then I'm off for three weeks with just my phone.

**Comment by bradallred** [comment]
I haven't tried yet. I'll see if I can find time this weekend, but I too am leaving for a week.

**Comment by lynxlynxlynx** [comment]
I thought the SDL_RenderDrawPoint fixed it, but it now just works without any changes after a thorough rebuild. Maybe some cache somewhere.

I tried the latest appimage, just to see if it'd be any different for a build from a different host: there it hits #1286.

I'll try disabling the batching just to see if it has any effect on this. Otherwise I'll just revert.

**Comment by bradallred** [comment]
likely what happened is you panned the viewport slightly or some other actor/object was on screen. there is no cache, just "luck" (based on what we call after drawing a stenciled object) on if sdl updates its render state.

**Comment by bradallred** [comment]
because of what I just explained, I haven't been able to reproduce this. If you can, make a save that can be loaded to witness the issue. I'll push my changes to see if that fix it tho.

**Comment by bradallred** [comment]
forgot to reference this issue, but see if 64f5435 resolves it for you

**Comment by lynxlynxlynx** [comment]
Still works fine, while before it was 100 % reproducible. I'm attaching a save, but it might not be relevant any more:
[000000109-translucency bug.zip](https://github.com/gemrb/gemrb/files/6675168/000000109-translucency.bug.zip)

**Comment by lynxlynxlynx** [comment]
Ah, started happening again.

**Comment by bradallred** [comment]
did you try adding the `SDL_SetRenderDrawColor` reset? I also removed the blend mode reset thinking it was irrelevant, but perhaps not.

diff
```
// WARNING: these are necissary hacks to combine SDL_Renderer with OpenGL (or other) native calls
void SDL20VideoDriver::BeginCustomRendering()
{
	// To start we need to make sure SDL thinks it is using its texture shader
	// so that we can change the program without it knowing
	static const SDL_Rect r = {0, 0, 1, 1};
	SDL_RenderCopy(renderer, ScratchBuffer(), &r, &r);
+	SDL_SetRenderDrawColor(renderer, 1, 1, 1, 1);
	// if we ever call more than glUseProgram (and associates) then we will need to do more here
	// we may want to add a 'flags' parameter to conditionally clear the other states
#if SDL_VERSION_ATLEAST(2, 0, 10)
	SDL_RenderFlush(renderer);
#endif
}

void SDL20VideoDriver::EndCustomRendering()
{
	// to end we need SDL to "reset" the render state to restore the textrue shader
	// we do this by changing the state to the primitive "solid" shader
	SDL_RenderDrawPoint(renderer, -1, -1);
+	SDL_SetRenderDrawColor(renderer, 1, 1, 1, 1);
	// if we ever call more than glUseProgram (and associates) then we will need to do more here
	// we may want to add a 'flags' parameter to conditionally clear the other states
#if SDL_VERSION_ATLEAST(2, 0, 10)
	SDL_RenderFlush(renderer);
#endif
}
```

**Comment by bradallred** [comment]
I still can't reproduce this.

can you try removing this block so we can at least rule out something to do with `BlitFlags::HALFTRANS`

https://github.com/gemrb/gemrb/blob/ef002864b1218b1e116f6bb0a3b22c9aae3dcf4c/gemrb/plugins/SDLVideo/SDL20Video.cpp#L369-L379

**Comment by FrElvire** [comment]
At location specified in #1347 (ar7004 [140.1894]) it's 100% reproducible (for me at least....)

**Comment by bradallred** [comment]
looking at that block of code makes me wonder if this isnt fixed by:

diff```
if (flags & (BlitFlags::ALPHA_MOD | BlitFlags::HALFTRANS)) {
	Uint8 alpha = SDL_ALPHA_OPAQUE;
	if (flags & BlitFlags::ALPHA_MOD) {
		alpha = tint->a;
	}
			
	if (flags & BlitFlags::HALFTRANS) {
				alpha /= 2;		}
	SDL_SetTextureAlphaMod(ScratchBuffer(), alpha);
+} else {
+	SDL_SetTextureAlphaMod(ScratchBuffer(), SDL_ALPHA_OPAQUE);
}
```

**Comment by lynxlynxlynx** [comment]
@FrElvire can you still reproduce? I again can't any more.

**Comment by FrElvire** [comment]
looks ok, I can't reproduce anymore.

**Comment by lynxlynxlynx** [comment]
Closing then ... 🤷🏾
