### ISSUE TITLE
bg2 chapter text silently skipped

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1293]
Once you leave for Brynnlaw, something goes wrong closing the window:
```
[GUIScript/ERROR]: Attribute Error:
[Python/ERROR]: SystemError: ../Objects/longobject.c:998: bad argument to internal function
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "../gemrb/GUIScripts/TextScreen.py", line 74, in StartTextScreen
[Python/ERROR]:     EndTextScreen ()
[Python/ERROR]:   File "../gemrb/GUIScripts/TextScreen.py", line 181, in EndTextScreen
[Python/ERROR]:     TextScreen.Unload ()
[Python/ERROR]:   File "../gemrb/GUIScripts/GUIClasses.py", line 237, in Unload
[Python/ERROR]:     self.Close()
[Python/ERROR]:   File "../gemrb/GUIScripts/GUIClasses.py", line 240, in Close
[Python/ERROR]:     RemoveView(self, False)
[Python/ERROR]: AttributeError: Invalid view
```

Maybe we should just warn? Though it's a SystemError and the problem could be elsewhere.

Perhaps it has to do with the script, since these two are both calls to TextScreen:
```
TextScreen("SCRTXT02")
IncrementChapter("")
```
I'll go check where it breaks more closely.

**Comment by bradallred** [comment]
just looks like we are trying to close a window that has already been closed

**Comment by lynxlynxlynx** [comment]
Hmpf, worked fine on a reload.

**Comment by lynxlynxlynx** [comment]
Tried a couple more times, same nothing ... but neither a textscreen. So there's definitely something wrong.

**Comment by lynxlynxlynx** [comment]
StartTextScreen does run, but only once, since both actions run in the same tick (they're instants). The second one wipes the 2da parameter and so we exit prematurely.

Looking at the data, some uses are ok, but at least two will hit this bug. `IncrementChapter("")` is only used in bg2 and the iwds, which we handle on the py side. So it looks like we can just skip overwriting the table for bg2.
