### ISSUE TITLE
The console sometimes stops taking input 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1295]
Enter just doesn't do anything, so you can't run commands.

Haven't found a reproducer yet, but it can usually be fixed by closing, toggling a top win and then retrying.

**Comment by bradallred** [comment]
it sounds like something else is getting focused. I would think clicking the field would refocus it. IIRC, we focus things in a lot of the `UpdateXXX` functions that get called automatically and that sounds like a likely culprit. We also probably don't need to be doing that. Previously, we had to do this to keep the event manager focused on the correct control, but that need is gone now.

**Comment by lynxlynxlynx** [comment]
I've thought of focus, but clicking on the textarea doesn't achieve anything notable. The history one remains interactable, but there's just no way to execute the selection. Will keep it in mind for the next time I hit it though.

**Comment by bradallred** [comment]
so typing works just not return? not a focus issue then. likely something is binding to the return key using `SetDefault`

**Comment by lynxlynxlynx** [comment]
I think it's the continue/end dialog buttons. I can reproduce in bg1:
- load game, console works fine
- talk to someone
- no more enter

**Comment by bradallred** [comment]
yeah, those definitely bind to the enter key. we can make console bind to something like shift+enter so that you can still enter commands when something has hijacked the enter key

**Comment by lynxlynxlynx** [comment]
Why doesn't it rebind when we show it again? That seems like the simplest solution.

**Comment by bradallred** [comment]
it never binds that key in the first place. besides if you did that then when you close the console enter wouldn't proceed with the dialog

**Comment by lynxlynxlynx** [comment]
I could live with that, since most uses happen outside of dialog. Hmm, how about making the console modal?

**Comment by bradallred** [comment]
I believe we use a global key bind instead of a window key bind so modality wouldn't affect it. If it were just a window hot key then the console window being focused would already bypass it. unless of course the continue/end window is modal... in which case there is probably a better solution

**Comment by bradallred** [comment]
I (re)discovered why the dialog end/continue window cant just be modal/focused. its because it extends over the option/portrait window and should be behind them always. So we cant just fix this with clever modal stacking since forcing the window to the background is precisely the reason it requires a global key bind.

**Comment by lynxlynxlynx** [comment]
Deceptively simple in the end.
