### ISSUE TITLE
Wrong configuration missing files with either GemRB 0.85 Ubunutu or Linux v0.9 appimage

### ISSUE THREAD

**Issue by STyx2909** [gemrb/gemrb#1298]
#### Bug description
Failed to launch.

GemRB version: 0.85 ubuntu official repository .deb

#### Steps to reproduce
note: gemrb.cfg, casesensitive=1 / or 0 is the same...

#### Expected behavior
Failed to launch.

#### log included

GemRB version: 0.9.0 AppImage from GemRB official website

Same problem. Some parts of the log maybe different though.

Checked for required files, not present on the system (Xubuntu 20.04)

Note: owner of digital version of BG, BG2, etc. from GOG, BG E version runs fine.

[GemRB AppImage log](https://github.com/gemrb/gemrb/files/6678725/GemRB.AppImage.log)
[GemRB 0.85 ubunutu log](https://github.com/gemrb/gemrb/files/6678726/GemRB.0.85.ubunutu.log)

**Comment by lynxlynxlynx** [comment]
0.8.5 is four years old, forget about it.
Do you have an old gemrb.cfg in that folder, in ~/.gemrb or /etc?

Try this:
```
echo GameType=bg2  > new.cfg 
# then run it like
./gemrb-linux* -c new.cfg
```

**Comment by STyx2909** [comment]
Works fine. Probably something left after my first attempt of 0.85 1 month ago also...

**Comment by lynxlynxlynx** [comment]
Great, closing then. You can change bg2 to auto or bg1 and it should also work for bg1.
