### ISSUE TITLE
IWD2: Black Screen when returning to the main menu

### ISSUE THREAD

**Issue by GraionDilach** [gemrb/gemrb#1299]
GemRB version: 0.9.0

#### Steps to reproduce
Start IWD2.
Select New Game.
Click on Cancel.

Interestingly this doesn't happen if I try returning from the "create party" screen, only from the "begin game" screen.

IWD2 is from GoG default install, if it's relevant.

**Comment by bradallred** [comment]
that should fix it

**Comment by bradallred** [comment]
I didnt find any others
