### ISSUE TITLE
Bad pick up stuff window positioning 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1303]
#### Bug description
When you pick up stuff from the floor the window positioning is really bad

GemRB version: v0.9.0

#### Steps to reproduce
1. Kill some one
2. Pick up the loot 
3. See error

#### Expected behavior
Window is fix to the bottom and only one time clock is on display

#### Screenshots
![image](https://user-images.githubusercontent.com/1820598/122700469-b9545e80-d221-11eb-943f-c4ac321b3c1c.png)

**Comment by lynxlynxlynx** [comment]
What resolution is this?

**Comment by rsantellan** [comment]
This is my cfg

```
GameType=bg2
GameName=Baldur's Gate 2
Width=1028
Height=700
Bpp=32
Fullscreen=0
TooltipDelay=500
GUIEnhancements = 15
GamePath=./games/BaldurGate2/bg2new/
CD1=./games/BaldurGate2/bg2new/data/
CachePath=./Cache2/
GemRBPath=../../gemrb
PluginsPath=./plugins/
GamepadPointerSpeed=10
VitaKeepAspectRatio=1
```
I have installed the widescreen mod, but after seeing this https://youtu.be/nn1v-yG4-lo I'm confused if I should use it or not.

**Comment by lynxlynxlynx** [comment]
Your choice, you can easily try without. I think your custom resolution avoided our fix for the data bug in guiw10. Try 1024 width first.

**Comment by rsantellan** [comment]
Hi @lynxlynxlynx ,
This is 1024 X 700
![1024x700](https://user-images.githubusercontent.com/1820598/123092898-5b7e6d00-d401-11eb-9d04-a8952f1b5424.png)
This is 1024 X 768
![1024x768](https://user-images.githubusercontent.com/1820598/123092909-5de0c700-d401-11eb-8e15-dbac339115d5.png)

I will try removing the widescreen mod, after doing a massive backup! :)

**Comment by lynxlynxlynx** [comment]
Are you sure? You had 1028 in the config.

**Comment by rsantellan** [comment]
I try with this:


# Encoding=default

#####################################################
#  Video Parameters                                 #
#####################################################

#Screen width
#Width=800
#Width=1028
Width=1024

#Screen height
#Height=600
#Height=700
Height=768

**Comment by lynxlynxlynx** [comment]
The check here should be against the window pack, not width, to become robust.
https://github.com/gemrb/gemrb/blob/ffff847d98aa5e7795b84a2d9f7537ada61073e6/gemrb/GUIScripts/CommonWindow.py#L162-166

**Comment by rsantellan** [comment]
After removing the widescreen mod at 1028X700 is shown like this

![image](https://user-images.githubusercontent.com/1820598/123186357-560b3c00-d46e-11eb-9082-0962ba2d7525.png)

And at 1024X768 is shown correctly.

![image](https://user-images.githubusercontent.com/1820598/123186423-7935eb80-d46e-11eb-87b3-06bc52399282.png)

So I believe is a little incompatibility between the widescreen mode and gemrb.

**Comment by bradallred** [comment]
I cant reproduce. this is what it looks like when set to 1028x700 for me
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/1126744/123187047-9f4f9180-d456-11eb-82cf-091829c27787.png">

**Comment by rsantellan** [comment]
@bradallred how can I clean the cache ? Should make a clean build ?

**Comment by bradallred** [comment]
you just said that you uninstalled the widescreen mod. the widescreen mod is what is causing this. the windows are resized to the size you want, but the backgrounds are not.

**Comment by lynxlynxlynx** [comment]
If you used the gemrb mode of widescreen then you need to manually remove a chu file from the override for a full uninstall, sth like cg*.chu from memory. Maybe also mos.

**Comment by rsantellan** [comment]
I used: [https://www.gibberlings3.net/mods/tools/widescreen/](Widescreen) and I uninstalled using **weinstall widescreen** and remove.
Searching for the chu file I have this.
```
find . -iname cg*.chu
./override/cgui1070.chu
```
Should I delete it ? I will search the mod files if it from the mod.

**Comment by lynxlynxlynx** [comment]
Yes, that's what I said.

**Comment by rsantellan** [comment]
@lynxlynxlynx removing the chu file work like a charm in all resolutions. Should I close this ?
