### ISSUE TITLE
BG2: Errors on console selecting Jan inventory 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1305]
#### Bug description
On selecting Jan inventory this is display on console

```
[Actor/DEBUG]: GetIWD2KitIndex: didn't find kit 1024 at expected class 13, recalculating!
[Actor/DEBUG]: GetIWD2KitIndex: didn't find kit 1024 at expected class 13, recalculating!
[Actor/DEBUG]: GetIWD2KitIndex: didn't find kit 1024 at expected class 13, recalculating!
[Actor/DEBUG]: GetIWD2KitIndex: didn't find kit 1024 at expected class 13, recalculating!
[Actor/DEBUG]: GetIWD2KitIndex: didn't find kit 1024 at expected class 13, recalculating!
[Actor/DEBUG]: GetIWD2KitIndex: didn't find kit 1024 at expected class 13, recalculating!
[Actor/DEBUG]: GetIWD2KitIndex: didn't find kit 1024 at expected class 13, recalculating!
[Actor/DEBUG]: GetIWD2KitIndex: didn't find kit 1024 at expected class 13, recalculating!
[Actor/DEBUG]: GetIWD2KitIndex: didn't find kit 1024 at expected class 13, recalculating!
[Actor/DEBUG]: GetIWD2KitIndex: didn't find kit 1024 at expected class 13, recalculating!

```

GemRB version: v0.9.0

#### Steps to reproduce
1.Have Jan on the Party
2. Click on 'inventory'
3. Watch console

#### Expected behavior
No errors

**Comment by bradallred** [comment]
what error? looks like debug output. is something actually broken by this?

**Comment by rsantellan** [comment]
@bradallred nothing is broken, but didn't happen on previous version

**Comment by bradallred** [comment]
that message comes from IWD2 code. Is this IWD2? you didn't put it in your report, not everybody knows your good friend Jan 😉

**Comment by chilvence** [comment]
@rsantellan the output from the console can seem unnecessarily loud sometimes, it isn't always anything to worry about, , it's more likely to be "tracer fire" GemRB is conceived as "one engine to rule them all" so IWD2 debug messages can leak into your normal BG2 game when you least expect them to.

That said, superfluous messages can often be distracting when trying to investigate actual bugs. I have a personal hacky branch that silences a lot of stuff because it's needlessly distracting, so I get that.

if you are compiling from source, this message is in scriptable/Actor.cpp line 857 in the function GetIWD2KitIndex and can be safely commented out and ignored, if it is distracting

Otherwise, you can just ignore it if it isn't causing any gameplay problems.

**Comment by bradallred** [comment]
Ideally we would move a lot of the game specifics to data tables and/or Python scripts so it wouldn't be a problem. I dont know that anybody is currently motivated enough to begin that tho.

**Comment by rsantellan** [comment]
Hi @chilvence,

For the little that I understand this should be on false

![image](https://user-images.githubusercontent.com/1820598/122918112-2ad10180-d335-11eb-8b6d-c78c00f6399e.png)

And because of that it will never have to go to that function because I'm on Baldur Gate 2. 

I track GF_LEVELSLOT_PER_CLASS to includes/globals.h but I don't see where is populate with the value, I see that is called here

![image](https://user-images.githubusercontent.com/1820598/122919003-1f320a80-d336-11eb-9539-29a6098257e7.png)

Is this loaded from an ini file ? Or where I can look where is loaded ?

Regards

**Comment by bradallred** [comment]
the flags are set by gemrb.ini for the respective game. "game" being what you have `GameType` set to in your cfg. I recommend "auto"

**Comment by rsantellan** [comment]
I have bg2 on my cfg

GameType=bg2

But is using the other one.... I try to get more info.

**Comment by rsantellan** [comment]
@bradallred if I put auto is the same behavior. Still trying to figuring out the code...

**Comment by rsantellan** [comment]
I found out that here is the problem
![image](https://user-images.githubusercontent.com/1820598/123033108-91016700-d3bd-11eb-89c5-c930045c12c2.png)

When is call this function on Jan baseclass equals 0.

Trying to find out where this is call....

**Comment by lynxlynxlynx** [comment]
Perhaps his specialist school kit is causing problems. The function name became a bit of a misnomer, this is already mostly table data driven and it's probably easiest if you just wait for me to come back to a computer in July.
