### ISSUE TITLE
BG2: All party moves opening containers 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1311]
#### Bug description
When you click a container with all the party selected all move to the place instead of only the leader.

GemRB version: v0.9.0

#### Steps to reproduce
1. Go to a place with a container
2. Select all party
3. Click on the container

#### Expected behavior
Only the leader moves

#### Screenshots

https://user-images.githubusercontent.com/1820598/123025231-b0de5e00-d3b0-11eb-9643-a8ab5c2f79dc.mp4

**Comment by lynxlynxlynx** [comment]
This is easy to fix. All the code is the mouse handler functions in GameControl.cpp and in one place we should clearly work with just the active actor, not the whole selection.

**Comment by rsantellan** [comment]
For what I see the function HandleContainer is the one that invokes the opening the container.

![image](https://user-images.githubusercontent.com/1820598/123185166-a8972900-d46b-11eb-885d-6ba3d2ea88cc.png)

If I follow **UseContainer** to the file **core/GameScript/Actions.cpp** I found out that in that function I have the sender but can't figure out how to get the rest of the party to make them stop. Also I found out that the same applies to doors, is a race to see which one open it first!.

@lynxlynxlynx any clue on where I can look to stop the rest of the party ?

**Comment by bradallred** [comment]
`HandleContainer` is not the problem, that clearly generates an action for a single actor. The problem is going to be here

https://github.com/gemrb/gemrb/blob/07a8a780f0bfb180e31a978f9afc8b3e4b531eda/gemrb/core/GUI/GameControl.cpp#L2215-L2218

**Comment by bradallred** [comment]
also looks like the `ST_TRAVEL` part of things should be handled separately since then you do want everybody to move

**Comment by rsantellan** [comment]
@bradallred that works like a charm now I'm trying to understand why :)

**Comment by bradallred** [comment]
I added some more context to the diff for you so you can see how it relates :)

**Comment by rsantellan** [comment]
So, you only set one actor to do the action instead of the CommandSelectedMovement that moves the hole party, then the next action is the UseContainer that if you are really far start moving the character to open the container. 
Now, when all where moving, it will open the character that was faster to open it ? Or still is the first selected ?

**Comment by bradallred** [comment]
I think your confusion is that you think that `HandleContainer` moves the party/pc then opens the container. It does not. the 2 actions are independent and `HandleContainer` only queues the latter. `HandleContainer` commands the actor passed to it, which in this case is `GetFirstSelectedPC`. The movement comes from the code above in my diff as an action that is queued _before_ the open container action and that action must complete before the open container action begins.

what was happening before was that we were commanding the entire party to move, but we were still only commanding the first PC to open the container. The diff changes that to only command the first PC.

I'm having second thoughts tho about the doors. Shouldn't doors still move the whole party? isn't the intent to move though the door? does the original really only use the first PC?

**Comment by rsantellan** [comment]
I think that I understand, the thing that confuse me was this line :

https://github.com/gemrb/gemrb/blob/f99e0159b6fa458b67dfdabfda33d36c1247926a/gemrb/core/GameScript/Actions.cpp#L5640

That line move the actor near the container (Or so it says it does).

About the doors this video shows that they all move together to the door: https://youtu.be/DE6ikAxepvs?list=PL0B2047B09486313C&t=460

**Comment by lynxlynxlynx** [comment]
Re doors: I don't remember, but if it didn't move everyone, I'd consider it a usability improvement if we did the opposite.

**Comment by bradallred** [comment]
@rsantellan Indeed it appears the `UseContainer` action will handle moving closer to the container. I was assuming it did not because of the code in `GameControl` but that code is probably redundant in any case where you are commanding a single PC.

@lynxlynxlynx im unsure if you are saying we should or should not move everybody to doors. We could always add a modifier key to allow either style.

**Comment by lynxlynxlynx** [comment]
That we should. :)

**Comment by lynxlynxlynx** [comment]
@rsantellan do you need help finishing this up?

**Comment by rsantellan** [comment]
@lynxlynxlynx using @bradallred solution works, but I don't understand yet the **MoveNearerTo** function. I don't want to take his credit to steal the solution that I don't even comprehend fully yet. :(
