### ISSUE TITLE
 UI elements disappear when resizing the window

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1317]
Since nothing prevents me from resizing or maximizing the window, I do so -- convinced it once worked without flaws on SDL2 w.r.t. scaling -- but then UI elements disappear until they are dirty and get redrawn, obviously.

This results in black, missing or partially redrawn UI/HUD parts in virtually every screen where performed. Here is an example in BG2 when resizing the window and hitting Pause.

![screen_size](https://user-images.githubusercontent.com/238558/123476214-b16b3480-d5fc-11eb-886c-26df390d4827.jpg)

I guess something is now aware of the physical screen size, instead of the logical one (or not scaled in time?), or we better prevent window modification, since this is easy to run into.

**Comment by lynxlynxlynx** [comment]
What's your sdl2 version? I had no problems with resizing when making a video, but the symptom is similar to #1296.

**Comment by MarcelHB** [comment]
It's 2.0.14.

**Comment by lynxlynxlynx** [comment]
Maybe a windows backend thing then.

**Comment by MarcelHB** [comment]
Well, yes. Just tested Linux: cannot reproduce there. :unamused:

**Comment by MarcelHB** [comment]
Latest git-SDL doesn't contain any out-of-the-box fixes either.

**Comment by MarcelHB** [comment]
It's inside of `direct3d`. OGL is fine.

**Comment by bradallred** [comment]
D3D invalidates the textures. you have to handle `SDL_RENDER_DEVICE_RESET` and `SDL_RENDER_TARGETS_RESET` to have the window recreate it's texture. Easy to do if you feel inclined.
