### ISSUE TITLE
[iwd1]  Snow Troll death animation drawn twice

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1319]
#### Bug description
In IWD1 (Position: ar7005 [3382.1620] for example), the animation of snow troll death is played twice (like in #468 ?)

if needed :

Debugdump of Actor Snow Troll (Snow Troll, Snow Troll):
Scripts: <none> <none> <none> <none> <none> eftrolg gnmmgsg <none>
Area:       ar7005 ([3240.1625])
Dialog:         TalkCount:  0
Global ID:  10040   PartySlot: 0
Script name:snowtroll11    Current action: 134    Total: 0
Int. Flags: 0x850a00    MC Flags: 0x0    Allegiance: 255   current allegiance:255

GemRB version: master

**Comment by lynxlynxlynx** [comment]
Does it always happen? I noticed it for some creatures in bg2 too, but nothing reliable and usually from ctrl-y.

**Comment by FrElvire** [comment]
no it's not always

**Comment by lynxlynxlynx** [comment]
Can you try to figure out in what cases it does happen then?

**Comment by FrElvire** [comment]
I will try

**Comment by FrElvire** [comment]
with this save go to the bottom, on  the left there is a snow troll. finish him by example with panoramide's
 poison dagger (already selected) and there is nearly always at least some part of death animation repeated. 

[save_troll.zip](https://github.com/gemrb/gemrb/files/6720372/save_troll.zip)

**Comment by FrElvire** [comment]
It seem restricted to (ice)troll and you have one death animation when '''killed'' with standard weapon (near death) and one another when really killed with fire damage by example. So you can have twice he animation in a row.

Don't know if I'm clear... :(

**Comment by lynxlynxlynx** [comment]
Yes, but the way you describe it shouldn't happen as often and should also in the original. But I haven't taken a proper look yet, so this is still just speculation.

**Comment by lynxlynxlynx** [comment]
Ok, I see what you mean. It has nothing to do with the troll's two stages. Once you kill him for good, his animation plays twice in a row. Like you said, it's similar to #468. Summoning @fizzet if he has any time.

**Comment by fizzet** [comment]
Hm. I can't look into it myself, but I can try to recall what the problem was. IIRC it was related to the DIE state change. The animation takes longer to finish than the one cycle the engine waits before changing to TWITCH, and that restarts the animation. Or something like that.  Hope that helps with porting the fix from master.

**Comment by lynxlynxlynx** [comment]
The IE_ANI_DIE -> IE_ANI_TWITCH transition looks fine, the animation is already done by then. So the problem happens before. And it's simple in essence — the IE_ANI_DAMAGE animation is very similar to IE_ANI_TWITCH, so the player is confused. Looks like we should not play it when dealing a killing blow.
