### ISSUE TITLE
Better scaling algo?

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1324]
#### Description
The following screenshots are showing PST in GemRB. Both are run with the same GemRB resolution (1280x720), but display resolution is changed from 1280x720 (first) to 1920x1080 (second, native display resolution). The second one is all edgy (probably seen better if you click for original size).
So, basically the only difference between screenshots is where scaling happens - in the engine or in videodriver, but quality difference is obvious.

![Captura de pantalla de 2021-06-26 23-57-10](https://user-images.githubusercontent.com/1279852/123520919-92909f00-d6dd-11eb-96d5-3e4dd5418828.png)
![Captura de pantalla de 2021-06-26 23-57-33](https://user-images.githubusercontent.com/1279852/123520921-93c1cc00-d6dd-11eb-9c13-c2aae1954c24.png)

**Comment by lynxlynxlynx** [comment]
Sdl provides a tuning variable one can set for its scaling. Can't easily check right now, but we likely just default to NN scaling, while it also supports bilinear.

**Comment by lynxlynxlynx** [comment]
How about now with the "best" strategy chosen?

**Comment by burner1024** [comment]
It's definitely better:
![Captura de pantalla de 2021-07-05 12-37-01](https://user-images.githubusercontent.com/1279852/124422828-28879200-dd8e-11eb-8259-935fb7fb9ed8.png)

For the reference, here's a screenshot from original at the same resolution:
![Captura de pantalla de 2021-07-05 12-38-15](https://user-images.githubusercontent.com/1279852/124422897-49e87e00-dd8e-11eb-8d88-215c298e4c3d.png)

**Comment by lynxlynxlynx** [comment]
So, is there something more to be done here?

Also, now that I can look at this on a proper screen, why are all the pairs of images of different sizes?

**Comment by burner1024** [comment]
I think it's ok for now. Maybe a more trained eye could spot something else, but for me it's close enough at least.
Different because Gemrb scales keeping screen resolution while vanilla changes it.

**Comment by lynxlynxlynx** [comment]
Ah, ok, thanks. Closing then.
