### ISSUE TITLE
PST: floats are wrong color and fade slowly

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1325]
#### Bug description
Dustmen's floats are green, then they turn white and start fading.

GemRB version: 0.9.0

#### Steps to reproduce
1. Go to Hive near Dustmen, wait for the floats.

#### Expected behavior
Original behaviour: floats are blue and disappear instantly.

#### Screenshots
Original
![Captura de pantalla de 2021-06-27 00-43-34](https://user-images.githubusercontent.com/1279852/123521417-bf928100-d6e0-11eb-94a5-58ea32b84481.png)

Gemrb 1
![Captura de pantalla de 2021-06-27 00-44-58](https://user-images.githubusercontent.com/1279852/123521445-eea8f280-d6e0-11eb-8ed1-dbe21aae30b1.png)

Gemrb 2
![Captura de pantalla de 2021-06-27 00-35-00](https://user-images.githubusercontent.com/1279852/123521422-cc16d980-d6e0-11eb-8a2e-4249b1b0413b.png)

**Comment by lynxlynxlynx** [comment]
Thanks! By instant youmean as soon as the sound clip is done or something else?

**Comment by burner1024** [comment]
The ones on screenshots are silent, so not sure how it behaves when there's sound.

**Comment by lynxlynxlynx** [comment]
I've fixed the recoloring, but the base color is still different. This requires another colors.2da entry and I didn't want to do it while we have another PR open that changes it.
