### ISSUE TITLE
PST: marker circles are off 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1326]
#### Bug description

Markers are way to the south compared to original. (Or animations are to the north?)

GemRB version: 0.9.0

#### Steps to reproduce
See a marker on pretty much any creature.

#### Expected behavior
Centered markers

#### Screenshots
Original
![Captura de pantalla de 2021-06-27 00-54-07](https://user-images.githubusercontent.com/1279852/123521656-3a0fd080-d6e2-11eb-99a2-1a76b33264f8.png)

GemRB
![Captura de pantalla de 2021-06-27 00-48-11](https://user-images.githubusercontent.com/1279852/123521629-12b90380-d6e2-11eb-947c-1abd8a66fe57.png)

**Comment by lynxlynxlynx** [comment]
Pst uses bitmap circles, so I wonder if the bam has the center coordinates properly set. And then if we care at all (seems not).

**Comment by burner1024** [comment]
Actually, the circle seems to be in the same position, it's the animation that's moved.

**Comment by lynxlynxlynx** [comment]
Hmm, the first that comes to mind is that the pst height map needs different handling. Can you try both engines, but with a completely flat map?

**Comment by burner1024** [comment]
I'm not familiar at all with height maps, and NI [doesn't work](https://github.com/NearInfinityBrowser/NearInfinity/issues/140) for me now... Do you have an area in mind that I can try?

**Comment by lynxlynxlynx** [comment]
Not really. Perhaps just deleting it would work ... but biffing is in the way. Perhaps an empty file in the override would work. From memory they're called arxxxxht.

I've downgraded ni as well, to the release before May's

**Comment by MarcelHB** [comment]
I guess it's the height map theory. Follows exactly when lining up the PCs along the gradient:

![heights](https://user-images.githubusercontent.com/238558/123526179-602f7380-d6d6-11eb-9069-64ee31afac4a.jpg)
