### ISSUE TITLE
Missing a lot of animations on IWD and Linux 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1328]
When I start a game in IWD and Linux, lots of BAMs are reported missing, mostly of the PCs -- and not all of them (lying on the ground is visible). I can see monsters and some NPCs though.

Log says:
```
[CharAnimations/ERROR]: Couldn't create animationfactory: chfb1g16 (5010)
[ResourceManager/ERROR]: Couldn't find 'chmf4g17.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: chmf4g17 (6100)
[ResourceManager/ERROR]: Couldn't find 'chfb1g17.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: chfb1g17 (5010)
[ResourceManager/ERROR]: Couldn't find 'cemb3g14.bam'.
```

Paths look good, so maybe something related to case-sensitivity of the res refs? Also, it's Ok in the HoW folder, but not for the one of the pure base game.

**Comment by bradallred** [comment]
do you have the correct `GameType` set?

**Comment by MarcelHB** [comment]
Obvioulsly not, I had left it `how`. Thanks, that fixes it.
