### ISSUE TITLE
PST wrong actor tooltips 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1330]
#### Bug description

On screenshots, the exact same save is loaded. Several bugs, not sure if I should open separate issues for each:
1. Name tooltips on hover are displayed over head in original, but in near cursor in GemRB.
2. Tooltip content is different: "Hive thug" vs "Hive townsperson"
~3. Extra two thugs appear when loading the save in GemRB. They aren't there in original. (Full story: there was a group of 3 thugs on the left, they were killed, and the save was made right after that.)~

GemRB version: 0.9.0

#### Steps to reproduce
It's a little modded PST, not sure is save will be helpful, let me know.

#### Expected behavior
Behaviour consistent with original... unless it's intentional?

#### Screenshots
Original
![Captura de pantalla de 2021-06-29 02-10-56](https://user-images.githubusercontent.com/1279852/123691822-45006780-d880-11eb-8f6b-0d583b9d8fd5.png)

GemRB
![Captura de pantalla de 2021-06-29 02-11-24](https://user-images.githubusercontent.com/1279852/123691871-521d5680-d880-11eb-8e76-7215070aacf5.png)

In dialog, he's correctly referred as Thug. Probably related to https://github.com/gemrb/gemrb/issues/467 ?
![Captura de pantalla de 2021-06-29 02-19-15](https://user-images.githubusercontent.com/1279852/123692012-82fd8b80-d880-11eb-949b-e559d5cf994d.png)

**Comment by bradallred** [comment]
it would be with checking the tooltip position in other games before attempting to adjust it

**Comment by lynxlynxlynx** [comment]
Which area is this in? Your guess about TalkCount is probably correct.

**Comment by burner1024** [comment]
Hive, top right corner.

**Comment by lynxlynxlynx** [comment]
There are several hives, don't you have the area code?

**Comment by burner1024** [comment]
Sorry, I didn't play PST for so long, I forgot there are multiple ones. And for some reason hotkey (L?) doesn't work for me.
It's the first area, where the entrance to the Mortuary is.

Also, on point 1), tooltips in BG2:
Original
![Captura de pantalla de 2021-07-12 22-07-08](https://user-images.githubusercontent.com/1279852/125312775-ca931580-e35e-11eb-875f-1e0179415597.png)
GemRB
![Captura de pantalla de 2021-07-12 22-07-16](https://user-images.githubusercontent.com/1279852/125312800-d088f680-e35e-11eb-889c-864765925572.png)
As you can see, original removes "talk" cursor when tooltip is shown, while GemRB doesn't.

**Comment by lynxlynxlynx** [comment]
You were thinking of ctrl-x. But you can ctrl-m and get even more info.
