### ISSUE TITLE
PST: when pursuing a moving enemy, walking markers are displayed at enemy's location

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1332]
#### Bug description
See the screenshots. Destination marker disappears and reappears as path is recalculated, mostly it's off the enemy's circle, and it doesn't look great.

GemRB version: 0.9.0

#### Steps to reproduce
1. Attack an enemy, get them to flee.

#### Expected behavior
Matching the original is one option, I guess.

But if an enhancement is possible, I'd suggest to indicate which enemy is being attacked by altering it's foot circle. Pulsate color/size slightly. Or maybe make the move marker center perfectly on the enemy's foot circle (like second screenshot), and turn it red to match color.

#### Screenshots
Original
![Captura de pantalla de 2021-06-29 02-48-38](https://user-images.githubusercontent.com/1279852/123695986-6dd72b80-d885-11eb-94fe-0e91d5a58540.png)
GemRB
![Captura de pantalla de 2021-06-29 02-46-01](https://user-images.githubusercontent.com/1279852/123696021-7af41a80-d885-11eb-8e0f-2b8d21bfdc97.png)
GemRB 2
![Captura de pantalla de 2021-06-29 02-52-01](https://user-images.githubusercontent.com/1279852/123696038-821b2880-d885-11eb-9af2-b2d4fd9c43ca.png)

**Comment by bradallred** [comment]
you cant just alter the foot circle since that is actually a sprite in PST. Tho looking at them, I'm not sure why we couldn't easily draw them.

**Comment by bradallred** [comment]
we have `BlitFlags::ADD` now, so we could pulse between the color of the sprite and white

does the original do anything? for any game?

**Comment by burner1024** [comment]
BG2 pulsates the foot circle on mouseover, but GemRB already does the same.
One difference is foot circle when ordered to interact (talk, attack, I guess other actions too):

GemRB looks as above:
![Captura de pantalla de 2021-07-21 09-21-17](https://user-images.githubusercontent.com/1279852/126420484-73c2d00c-e025-4937-b8ee-14e3744b31b1.png)

BG2:
(send PC to talk or attack a neutral)
![Captura de pantalla de 2021-07-21 09-23-11](https://user-images.githubusercontent.com/1279852/126420559-2f8f5ef9-fa19-4e36-951f-f81e317ba1e2.png)
After attacking: 
![Captura de pantalla de 2021-07-21 09-24-06](https://user-images.githubusercontent.com/1279852/126420656-5f47b6ae-1755-4157-9a64-7bf0bafad198.png)
![Captura de pantalla de 2021-07-21 09-25-02](https://user-images.githubusercontent.com/1279852/126420883-77aa7182-07ec-404b-80ec-05661e4188e1.png)

Red crosshair indicates the target of currently selected player controlled creature.

**Comment by lynxlynxlynx** [comment]
I'll open a new issue: please let's try to limit things to one per report.
