### ISSUE TITLE
PST: Ghostdog's bigger fonts cause assertion due to missing font

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1333]
#### Bug description
Crash with
```
gemrb/gemrb/core/GUI/TextArea.cpp:236: GemRB::TextArea::TextArea(const GemRB::Region&, GemRB::Font*, GemRB::Font*): Assertion `ftext && finit' failed.
```
when using bigger font from [Ghostdog's UI](https://www.moddb.com/games/planescape-torment/downloads/ghostdogs-pst-ui-mod-v22) (option 3: 80% bigger fonts for English, French, German, Spanish and Italian languages)

GemRB version: 0.9.0

#### Steps to reproduce
1. Open journal
2. Click on Beasts, or Quests

#### Expected behavior
No crash.

**Comment by bradallred** [comment]
you need to include your language at least

**Comment by burner1024** [comment]
English

**Comment by burner1024** [comment]
This is all I can see about font, if needed can attach full log:
```
$ grep -i font 1.log 
[PluginLoader]: Loaded plugin "TTF Font Importer" (/home/user/gemrb/lib/gemrb/plugins/TTFImporter.so).
[ResourceManager/WARNING]: Invalid path given: /usr/share/fonts/TTF (CustomFonts)
[Core]: Loading Fonts...
[ResourceManager]: Found 'fonts.2da' in 'Override'.
[ResourceManager]: Searching for 'FONTDLG'...
[ResourceManager]: Found 'FONTDLG.bam' in 'Override'.
[Core]: Loaded Font: FONTDLG for ResRef fontdlg
[ResourceManager]: Searching for 'TRMTFONT'...
[ResourceManager]: Found 'TRMTFONT.bam' in 'Override'.
[Core]: Loaded Font: TRMTFONT for ResRef trmtfont
[ResourceManager]: Searching for 'EXOFONT'...
[ResourceManager]: Found 'EXOFONT.bam' in 'chitin.key'.
[Core]: Loaded Font: EXOFONT for ResRef exofont
[Core]: Loaded Font: POSTANT for ResRef postant
[Core]: Loaded Font: NUMBER for ResRef number
[Core]: Loaded Font: NUMBER2 for ResRef number2
[Core]: Loaded Font: NUMBER3 for ResRef number3
[ResourceManager]: Searching for 'SYSFONT'...
[ResourceManager]: Found 'SYSFONT.bam' in 'chitin.key'.
[Core]: Loaded Font: SYSFONT for ResRef sysfont
[ResourceManager]: Searching for 'FONTDLG'...
[ResourceManager]: Found 'FONTDLG.bam' in 'Override'.
[Core]: Loaded Font: FONTDLG for ResRef fontdlg
[ResourceManager]: Searching for 'FONTDLG'...
[ResourceManager]: Found 'FONTDLG.bam' in 'Override'.
[Core]: Loaded Font: FONTDLG for ResRef normal
[Core]: Fonts Loaded...
[ResourceManager]: Fogemrb: /home/user/gemrb/gemrb/core/GUI/TextArea.cpp:236: GemRB::TextArea::TextArea(const GemRB::Region&, GemRB::Font*, GemRB::Font*): Assertion `ftext && finit' failed.

```

**Comment by bradallred** [comment]
if you are running a mod that adds additional fonts it is on you to edit the fonts.2da for the relevant game and add it there.

**Comment by bradallred** [comment]
you may want to reach out to the mod author and ask if they will add support for GemRB by providing a compatible fonts.2da file themselves.

**Comment by burner1024** [comment]
Ah GemRB has its own font thingie, I didn't know that. That probably obsoletes the corresponding mods.

But anyway, is core dump expected behaviour?

**Comment by bradallred** [comment]
of course it's expected for an assertion to do that. We don't want to have to add a bunch of normally useless `nullptr` checks all over the place. `TextArea` has a precondition that it has a font to work with and failure to meet that precondition wouldn't make sense. In a desktop app we might opt to throw an exception in the constructor in this case, but for performance reasons we prefer to carefully choose where we allow exceptions so instead we `assert` on most preconditions.

**Comment by lynxlynxlynx** [comment]
It would be easy for the mod to change our file, but I'm not sure it's maintained any more. 

Besides that, we can still improve our logging for this case, so it becomes obvious to everyone.
