### ISSUE TITLE
[PST] Crash during character creation

### ISSUE THREAD

**Issue by ctiedt** [gemrb/gemrb#1334]
#### Bug description
The game starts and the main menu seems to work. However, as soon as I try to end character creation and actually start playing, the game crashes. Using gdb, I found out that the crash happens in `/gemrb/plugins/GUIScript/GUIScript.cpp` in the function `GemRB_Window_SetAction`.

The specific error is:

```
Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.
PyCallable_Check (x=0x7fff00000000) at Objects/object.c:1667
1667	Objects/object.c: File or Directory not found.
```

I am using GemRB version 0.9.0 on Arch Linux.

#### Steps to reproduce
1. Start Planescape Torment
2. Enter character creation
3. Press 'OK'
4. The game crashes

#### Expected behavior
The game should properly start after finishing character creation.

**Comment by lynxlynxlynx** [comment]
Thanks for the report, it matches another from a guix user. Can you `p func`? We're setting a bad callback somewhere, but python for some reason doesn't handle it gracefully.

**Comment by ctiedt** [comment]
Here's my `p func` output with a breakpoint in `GemRB_Window_SetAction`: 

```
Thread 1 "gemrb" hit Breakpoint 1, GemRB_Window_SetAction (self=0x0, args=0x7fffccb34b90) at /home/clemens/Programming/gemrb-0.9.0/gemrb/plugins/GUIScript/GUIScript.cpp:1859
1859		uint32_t key = -1;
(gdb) n
1860		PyObject *func = nullptr;
(gdb) n
1861		PARSE_ARGS(args, "OOk", &self, &func, &key);
(gdb) n
1863		Window *win = GetView<Window>(self);
(gdb) n
1864		ABORT_IF_NULL(win);
(gdb) n
[OpenAL]: WARNING: Buffer Underrun. AutoRestarting Stream Playback
1866		Window::WindowEventHandler handler = nullptr;
(gdb) n
1867		if (PyCallable_Check(func))
(gdb) p func
$1 = (PyObject *) 0x7fff00000000
(gdb) n

Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.
PyCallable_Check (x=0x7fff00000000) at Objects/object.c:1667
1667	Objects/object.c: File or Directory not found.
```

Removing the lines

```cpp
if (PyCallable_Check(func))
{
	handler = PythonWindowCallback(func);
}
```
in `GemRB_Window_SetAction` stops the game from crashing, but everything except the UI is black.

**Comment by lynxlynxlynx** [comment]
Clearly there's some memory corruption going on, so the function may be a red herring. If you can, it would be helpful if you built using address sanitizer to catch the culprit red-handed.

**Comment by ctiedt** [comment]
I'm pretty new to this project (and build systems using cmake in general) - how do I build with address sanitizer?

**Comment by lynxlynxlynx** [comment]
Rerun cmake, but prefix the line with CXXFLAGS="-fsanitize=address"

If that doesn't work you can edit the top CMakeLists.txt file and add it there- you'll see where we manipulate flags.

**Comment by ctiedt** [comment]
I did a clean rebuild with address sanitation enabled and still get the same result:

```
(gdb) p func
$1 = (PyObject *) 0x7fff00000000
```

Also the same error about `Objects/object.c` not being found.

**Comment by lynxlynxlynx** [comment]
Hmm, I guess it's in python  itself then. I'm stuck with just a phone for another week, but if you want to investigate further, start at NewLife.py and check which setaction call triggers it.

**Comment by ctiedt** [comment]
Thank you for your help, I'll look into it and update this issue if I find anything new.

**Comment by MarcelHB** [comment]
Unfortunately I cannot reproduce this on 0.9.0 and current master, neither do I spot any Python errors.

**Comment by bradallred** [comment]
I cant repro either nor do I get ASAN/UBSAN reports

what version of Python? You should probably use the latest 2.7 or even try 3 with master to see if that fixes it

**Comment by ctiedt** [comment]
I have no idea if I changed anything and if so what I changed (I might also just be going crazy), but I don't get the crash anymore now. I have no idea if I can reproduce this issue, but until then I'm going to close this issue. Thank you everyone who answered!

**Comment by bradallred** [comment]
judging by the Objects/object.c: File or Directory not found error I would guess that your `PYTHON_PATH` or other python env var was messed up.

**Comment by lynxlynxlynx** [comment]
For one user, after trying a bunch of stuff (including both python branches), it was resolved by building in debug mode instead of RelWithDebInfo. Not much of a difference, but just noting in case anyone else hits it.
