### ISSUE TITLE
since 6cdc73d  (more ResRef transition work) many crash

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1345]
#### Bug description
since 6cdc73d (more ResRef transition work) there is a crash in iwd1 at the end of chapter 4. At Position: ar6006 [481.401], go through the door to end chapter 4 : 

Thread 1 "gemrb" received signal SIGSEGV, Segmentation fault.
0x00007ffff7afeb96 in ?? () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff7afeb96 in ?? () from /lib64/libc.so.6
#1  0x00007ffff7a21f1b in _IO_file_xsputn () from /lib64/libc.so.6
#2  0x00007ffff7a16cad in fwrite () from /lib64/libc.so.6
#3  0x00007ffff7f3384b in GemRB::FileStream::Write(void const*, unsigned int)
    () from /usr/lib64/gemrb/libgemrb_core.so.0.9.0-git
#4  0x00007ffff68b58a9 in ?? () from /usr/lib64/gemrb/plugins/AREImporter.so
#5  0x00007ffff68b6256 in ?? () from /usr/lib64/gemrb/plugins/AREImporter.so
#6  0x00007ffff7ec2946 in GemRB::Interface::SwapoutArea(GemRB::Map*) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.9.0-git
#7  0x00007ffff7ef6457 in ?? ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.9.0-git
#8  0x00007ffff7ef6b6a in GemRB::SaveGameIterator::CreateSaveGame(int, bool) ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.9.0-git
#9  0x00007ffff7ecffe9 in GemRB::Map::MoveToNewArea(char const*, char const*, unsigned int, int, GemRB::Actor*) const ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.9.0-git
#10 0x00007ffff7ed8e4e in GemRB::Map::UpdateScripts() ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.9.0-git
#11 0x00007ffff7e7c60c in GemRB::Game::UpdateScripts() ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.9.0-git
#12 0x00007ffff7ec2653 in GemRB::Interface::Main() ()
   from /usr/lib64/gemrb/libgemrb_core.so.0.9.0-git
#13 0x00005555555552a7 in ?? ()
--Type <RET> for more, q to quit, c to continue without paging--
#14 0x00007ffff79c97fd in __libc_start_main () from /lib64/libc.so.6
#15 0x000055555555546a in _start ()

as always can give a save if needed.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment]
unfortunately your second trace has no line number.

I couldn't reproduce either one but I made an attempt at fixing the first.

**Comment by bradallred** [comment]
ah, you meant a door to another area! not just open a closed door.

**Comment by FrElvire** [comment]
sorry but for the fisrt trace, this crah append before this commit, so I removed it from this bug. I will open a new for it tomorrow unless you correct it before ;)

**Comment by FrElvire** [comment]
yes a door to another area and chapter

**Comment by FrElvire** [comment]
Yes the two were corrected :+1:
