### ISSUE TITLE
smeared text when autoscrolling

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1346]
Demo message text area gets all smeared with the history scrolling changes.

Hitting pause:
![image](https://user-images.githubusercontent.com/121515/125081724-9d2c3a80-e0c6-11eb-8a05-d88e3ee99877.png)
SDL2, no GL.

**Comment by lynxlynxlynx** [comment]
I don't get it on the buildbot build though, so it could be another sdl issue.

**Comment by lynxlynxlynx** [comment]
Actually I have OPENGL_BACKEND set to None, but `[SDL20Video/DEBUG]: Renderer: opengl`, but I guess that's irrelevant,

**Comment by bradallred** [comment]
im sure it has nothing to do with which backend. I've seen this before for a long time, but it only ever seems to happen for text appended during a load screen. I never found a way to reliably repro (plus it was rare) it so it never got investigated.

**Comment by lynxlynxlynx** [comment]
For me it also always happens in iwd2, while other games are fine.
