### ISSUE TITLE
[iwd1] character become translucent near wall

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1347]
#### Bug description
In IWD1 (Position: ar7004 [140.1894]) when character is near the wall it become translucent

#### Screenshots
![image](https://user-images.githubusercontent.com/55502325/125096398-6578bf00-e0d5-11eb-8a86-b66e114e6e62.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Different than #1290?

**Comment by bradallred** [comment]
reports like this can be made more useful by hitting ctrl+5 before you screenshot

**Comment by FrElvire** [comment]
Yes it can be a duplicate, you will a better judge than me... :)

here is a "better" screenshot

![image](https://user-images.githubusercontent.com/55502325/125098265-2a778b00-e0d7-11eb-8a8d-631585e9a040.png)

**Comment by bradallred** [comment]
This seems to be the same as #1290 to me
