### ISSUE TITLE
EditorConfig 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1349]
Since depending on the platform and project I'm on, also GemRB sometimes requires some post-processing for indentation, line endings and side stuff against some editor defaults.

I'd like to suggest introducing a [.editorconfig](https://editorconfig.org/) so my vim should handle the flavor by project, and by file type.

**Comment by lynxlynxlynx** [comment]
Sure, it's also much easier to do this than handle the whole style guidelines.

**Comment by lynxlynxlynx** [comment]
... and we have a few files with vim header lines that can be removed afterwards.
