### ISSUE TITLE
BG1: Ambient sounds stop after a moment

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1350]
#### Bug description
When starting a new game, just standing around in Candlekeep, after a few moments (sometimes just a few seconds, sometimes a minute or more) suddenly the background sounds of birds and voices stop. Other sounds still play, like NPCs opening doors. 

I've left the game running with 0.8.8 for a couple of minutes and the ambient sounds didn't stop, so I believe this behaviour is a bug.

I have not tried other locations (don't have any savegames).

I'm using the AppImages on Linux, Manjaro, the game is the GOG "Linux" version.

#### Steps to reproduce
1. Start a new game
2. Just wait, I guess

#### Expected behavior
The ambient sounds should loop endlessly

GemRB version (check as many as you know apply)
- On 0.9.0 and later build bot AppImages
- Still present in the 52b9133c70 build bot AppImage

**Comment by bradallred** [comment]
this is almost certainly the same as #1300

**Comment by bradallred** [comment]
looks like they simply stop getting enqueued so I'd look at `AmbientMgrAL::AmbientSource::tick`
