### ISSUE TITLE
animated portraits rocketing through time

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1351]
It's probably from some of the timer changes, but the button animations are way too fast now.

**Comment by bradallred** [comment]
they dont even use a timer anymore so I dont know why they would behave differently than the others (clock, spell book).

**Comment by lynxlynxlynx** [comment]
Perhaps the others have more frames to artificially slow themselves down through data.

**Comment by bradallred** [comment]
yeah, Id wager those others are 30fps and so they sync with our fps lock. Looks like we are missing a check against `nextFrameTime` in `SpriteAnimation::GenerateNext` is all.

**Comment by lynxlynxlynx** [comment]
I'm not sure all match, but it's definitely 95 % there if not more. More of a @chilvence level difference, if any.
