### ISSUE TITLE
Does pst use the SOUND_EFFECT column of its speldesc.2da?

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1352]
It's the only game that has the column, so we don't support it yet. Since the column contains references to files, the obvious might be true and it's just extra sounds to be played, probably when buying.

**Comment by MarcelHB** [comment]
Seems so, when buying the respective stuff at Hargrimm, its exactly those sounds.

**Comment by lynxlynxlynx** [comment]
Ah, we actually already use it, just from the python side — oops.
