### ISSUE TITLE
BG1: Gold ends up in inventory as object

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1355]
#### Bug description
When picking up gold coins, they are added to the inventory instead of being added to the count. 

I tested this in an unmodded BG1 install, but it also happened in my BGT install, so I guess it might apply to BG2 as well. 

#### Steps to reproduce
1. Find a chest with coins
2. Loot
3. Admire the useless coins in your bag

#### Expected behavior
Gold should be added to the amount of gold coins, not as item. 

#### Screenshots
![unknown-1](https://user-images.githubusercontent.com/68446748/125596610-887e3afb-6de6-4cf0-8881-150caed10bff.png)

GemRB version (check as many as you know apply)
- master as of this issue (a335fc6255 AppImage from Build Bot)
- first appeared in AppImage cadefe59ab from Build Bot
- older Build Bot AppImages seem fine

**Comment by lynxlynxlynx** [comment]
The comparison in `Interface::CanMoveItem` fails ... more ResRef refactoring to be done.
