### ISSUE TITLE
BG1: Quicksave not blocked during scripted scene 

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1357]
#### Bug description
At the start of the game, when Gorion walks with the PC to the gate and talks, and afterwards on the field, pressing Q to create a quicksave is not blocked. 

This will result in a quicksave that is rather buggy, loading into the game with no visible menus and having Gorion walk off screen with bad timing when talked to and being told "ready to go". 

#### Steps to reproduce
1. Start the game until they walk to the gate
2. Press Q

#### Expected behavior
Not create a quicksave, as in 0.8.8

#### Screenshots
![Screenshot_2021-07-15_11-48-34](https://user-images.githubusercontent.com/68446748/125772242-ab6143d5-7ae2-4878-95c1-dd97f1a16d15.png)
Being able to walk around and click on things after loading the buggy quicksave. 

GemRB version (check as many as you know apply)
- [x] master as of this issue (tested on AppImage bf7148b4ac)
- [x] 0.9.0
- [ ] 0.8.8

**Comment by lynxlynxlynx** [comment]
sounds like a bug in CanSave from SaveGameIterator.cpp.

**Comment by bradallred** [comment]
I'm not sure where the regression would have come from, but yeah adding a check in `SaveGameIterator::CanSave()` should do the trick
