### ISSUE TITLE
BG2 / BGT: Dark screen on new game

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1358]
#### Bug description
On starting a new game with Baldur's Gate Trilogy (both 1.20 and 1.21), after closing the introduction text, the screen turns very dark and takes a while to gradually get lighter again. 
This affects menus as well, except for the "quit" menu, which temporarily removes the darkness behind it. If the menu is closed again, it turns dark again. 

#### Steps to reproduce
1. Start a new game with BGT

#### Expected behavior
As in 0.8.8 the screen should not turn dark.

#### Screenshots
![Screenshot_2021-07-16_00-00-03](https://user-images.githubusercontent.com/68446748/125863815-ef7c67c6-b6f0-4da3-862d-7567f84d5a2e.png)
![Screenshot_2021-07-16_00-00-05](https://user-images.githubusercontent.com/68446748/125863823-31a2c501-bfa2-480a-a0b0-c358132ea3bc.png)
![Screenshot_2021-07-16_00-00-18](https://user-images.githubusercontent.com/68446748/125863833-21aae74d-cd9e-4ff0-9e47-a8353ee9dadb.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [x] 0.9.0
- [ ] 0.8.8

**Comment by bradallred** [comment]
This is due to using BGT. BG2 does have a fade in the intro which we code in the GUIScript somewhere. You have to comment that out since I don’t think we have a way of detecting bgt.

**Comment by bradallred** [comment]
Another option would be to reach out to the BGT folks and ask them to support GemRB by adding a script that does a 0 tick fade from black which would cancel our fade (this is what actually happens in vanilla BG2)

**Comment by bradallred** [comment]
for reference this is the code causing the fade
https://github.com/gemrb/gemrb/blob/27d0485688fa0d4b0169ccab151c0feb574bb78b/gemrb/GUIScripts/bg2/CharGenEnd.py#L120-L124

**Comment by lynxlynxlynx** [comment]
We can detect BGT easily though — `GameCheck.HasBGT()`.

**Comment by bradallred** [comment]
I didnt realize we had a check for BGT. sounds like that is the answer then.
