### ISSUE TITLE
Pile highlight is always on 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1360]
Without hovering or ALT, even in fog:
![image](https://user-images.githubusercontent.com/121515/125983471-175885c3-90e9-4c3b-9cc7-9b9453112c73.png)

Must be a recent regression; it means the wrong frame is looked up. The original did something clever here, so perhaps we broke that.

**Comment by bradallred** [comment]
IIRC there is no separate frame; it is `palette->col[1]`.

**Comment by lynxlynxlynx** [comment]
Could be, I just remember something clever from adding it to the demo.

**Comment by bradallred** [comment]
meh first thoughts are that palette versioning got broken or is being bypassed somewhere. I believe this theory fits with #1356 as well

**Comment by bradallred** [comment]
a quick test would be to see if the3se 2 issues affect SDL1 at all.

**Comment by bradallred** [comment]
I suspect a351603 tho I havent confirmed
