### ISSUE TITLE
Message when trying to copy a spell already in your mage book

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1362]
With a mage when trying to copy a spell already in book, it fail with "You fail to copy the spell to your mage book". IF my memory is good (?), you should have something like " you have already this spell in your book".

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Which game are you testing this in?

**Comment by FrElvire** [comment]
it's iwd1 (with how)

**Comment by lynxlynxlynx** [comment]
Then no, only bg2 has that string.
@72873 = ~That spell is already in your spellbook.~
