### ISSUE TITLE
Formation rotation ignored after confirmation

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1363]
When selecting a destination with right click you can change orientation of the formation but when you release the mouse button, it's always the same orientation which is selected .

Maybe it's me not doing the right thing to do that ?

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [X] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
That was confusing, but I can see what you mean — formation rotation doesn't seem to work (besides drawing).

**Comment by FrElvire** [comment]
that's it :)

**Comment by bradallred** [comment]
interesting regression assuming it works in 0.9.0

**Comment by lynxlynxlynx** [comment]
This is working again, so it looks like we accidentally fixed it just like we accidentally broke it. :)
