### ISSUE TITLE
Helmets not being rendered on game load

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1365]
If you equip a helmet to a character and save the game then reload the save the helmet visuals will not be applied.
you can open inventory to unequip and reequip to fix it.

I haven't noticed issues with other types of equipment, but I haven't really done a rigorous check.

This is a newish issue. I personally suspect some kind of `ResRef` issue, but that is only a guess.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
The string refactors are a good guess — I now noticed it's the same with shields. And they all use that ugly two-char animation suffixing.

**Comment by lynxlynxlynx** [comment]
I'll check it out, kind of on a roll today. :)

**Comment by lynxlynxlynx** [comment]
It's actually the string cleanup in d29d5643, with the now more obvious truncation:
```
[CharAnimations/DEBUG]: Truncating animation ref (wqMH1SPg1) to size.                                             
[ResourceManager/ERROR]: Couldn't find 'wqMH1SPg.bam'.
```
The last part of the root is bad, the final is probably wqMH1g1.
