### ISSUE TITLE
 BG2: Allow custom journal entries 

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1366]
#### Description
In Baldur's Gate 2, you can add custom journal entries in the "USER" section of the journal. 

#### Additional context

The middle button turns into "ADD" when "USER" is selected, but click in the empty area (when "USER" is selected) also works. 

Clicking on an existing custom entry allows editing that entry, or deleting it. If the entry is a new one that has not yet been saved, the delete button is greyed out. 

Deleting entries has a confirmation. 

Those entries take the current game time. While the journal can't be sorted while on this page, it will react to how the other pages of the journal are sorted. 

After a new entry has been added, the order is weird. I believe the new entry is put on top if sorted by date was last active, and on bottom if sorted by name was last active. 

Unlike on other pages, there is no text showing what it's sorted by. 

I have no idea what the revert button does, it was always greyed out for me. 

#### Pics

A custom entry
![unknown](https://user-images.githubusercontent.com/68446748/126397833-9da84c42-1fe3-497a-9d7e-6227c90b3419.png)

Editing a custom entry
![unknown-2](https://user-images.githubusercontent.com/68446748/126397838-dbe3914c-f430-412d-9c5f-7f1a6245d732.png)

Deleting a custom entry
![unknown-1](https://user-images.githubusercontent.com/68446748/126397846-c069a10d-40f2-410a-9042-b5a0ee0250f1.png)

Weird sorting after the entry uuuuu was added. 
![unknown-5](https://user-images.githubusercontent.com/68446748/126398727-6888936d-9bb1-48e9-8b89-681cf8ae6c60.png)

**Comment by lynxlynxlynx** [comment]
@rsantellan this can be your next project, since you've already looked at the journal. There's some GUI work to do and then we have a SetJournalEntry GUIScript action that can actually store the user note.

(interestingly SetJournalEntry was added already in 2010, but never used)

**Comment by rsantellan** [comment]
> 

I'll look at this. I will create a flow in the original to see the changes.

**Comment by rsantellan** [comment]
> @rsantellan this can be your next project, since you've already looked at the journal. There's some GUI work to do and then we have a SetJournalEntry GUIScript action that can actually store the user note. Ignore the bad sorting behaviour in the original.
> 
> (interestingly SetJournalEntry was added already in 2010, but never used)

Looking at this I have a question about the Windows, I was able to change the text list for a TextArea. Now I have an error that Window is not closed correctly. Looking at **GUIRECCommon.py** I see that it does `SubCustomizeWindow = GemRB.LoadWindow (23)` Where is the 23 defined ? Where I can look that ?

**Comment by lynxlynxlynx** [comment]
In the CHU file, guijrnl for the journal, so explore it with NearInfinity. I'm a bit skeptical that it loads a new window though. I would also be amazed if the existing control where quests are displayed is not a text area already.

**Comment by rsantellan** [comment]
![image](https://user-images.githubusercontent.com/1820598/158922697-107972bf-c54f-4106-a99a-f23c6405b3db.png)
For what I see id 2 is the one that shows but id 9 is the one to create new ones, this means is a new window ?

**Comment by lynxlynxlynx** [comment]
It is, but we can just make the textarea in the existing window editable — see how IE_GUI_TEXTAREA_EDITABLE is used.

**Comment by rsantellan** [comment]
> @rsantellan this can be your next project, since you've already looked at the journal. There's some GUI work to do and then we have a SetJournalEntry GUIScript action that can actually store the user note. Ignore the bad sorting behaviour in the original.
> 
> (interestingly SetJournalEntry was added already in 2010, but never used)

@lynxlynxlynx  Could I change SetJournalEntry to accept a String ? Because now it expect a pyref that I suppose is an integer:

```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "~/gemrb-myfork-git/gemrb/GUIScripts/bg2/GUIJRNL.py", line 162, in SaveAndCloseAddEditJournalEntry
[Python/ERROR]:     GemRB.SetJournalEntry (Chapter, Text.QueryText (), Section)
[Python/ERROR]: TypeError: an integer is required (got type str)
```

**Comment by lynxlynxlynx** [comment]
Good question! Since it's unused, it can be modified as we wish without repercussions. Clearly some of its functionality is not needed.

However, it probably should still work with a strref, since also the GAM journal entries expect that and all our code in the background as well. So yeah, make it take a string, but then we'll have to add it to the CTLK, so we get a strref to use in the journal code. Or perhaps there is a range of reserved strrefs already and we just need to update their text.

So please make a test. Backup dialog.tlk, open the original game (without gemrb), add a few journal notes, save, exit. Then compare the two dialog.tlk files — are they still the same? If not, we should be able to find the strref where these entries start.

**Comment by lynxlynxlynx** [comment]
Is there another tlk file in the save game's dir?

**Comment by rsantellan** [comment]
> Is there another tlk file in the save game's dir?

Only this:

```
ls save/000000052-Journal\ test/
BALDUR.BMP  baldur.gam  BALDUR.SAV  PORTRT0.BMP  PORTRT1.BMP  PORTRT2.BMP  PORTRT3.BMP  PORTRT4.BMP  worldmap.wmp
```

**Comment by lynxlynxlynx** [comment]
Ah, it's put in the tot/toh file, which are embedded into savs. The journal entry then has a bit (which we don't save yet — see GAMJournalEntry) to tell the engine whether to look there or in the tlk:
https://gibberlings3.github.io/iesdp/file_formats/ie_formats/gam_v2.0.htm#GAMEV2_0_Journal

Our TlkOverride class deals with the tot/toh files. So we need to find at which strrefs the journal entries start, if that's compatible with our current system and then UpdateString can be used to actually assign text to the strref. So look at the SAV file with NI and inspect the tot/toh file inside.

**Comment by lynxlynxlynx** [comment]
Ok, so it really starts at 3 million like IESDP suggests. :O Perhaps we should bump ieStrRef::OVERRIDE_START even further.

Anyway, looks like you should make CTlkOverride::GetNewStrRef public, use it to get a new strref and then update it with the user text.

**Comment by rsantellan** [comment]
> Ok, so it really starts at 3 million like IESDP suggests. :O Perhaps we should bump ieStrRef::OVERRIDE_START even further.
> 
> Anyway, looks like you should make CTlkOverride::GetNewStrRef public, use it to get a new strref and then update it with the user text.

So I should get the new string of the text area, call ** CTlkOverride::GetNewStrRef ** and with the result strref call **GemRB_SetJournalEntry** ? Is that correct ?

**Comment by lynxlynxlynx** [comment]
No, the CTlkOverride functions are not exposed to python, so all of that needs to happen in GemRB_SetJournalEntry.

**Comment by rsantellan** [comment]
> No, the CTlkOverride functions are not exposed to python, so all of that needs to happen in GemRB_SetJournalEntry.
Hi! I'm returning to this! How I can create the override to 3 million ? I suppose I have to change the **GemRB_SetJournalEntry** so I can pass a custom chapter and section to trigger the retrieve of the next entry number ? Should I loop all the existing and add one more ?

**Comment by lynxlynxlynx** [comment]
I don't think we support sparse TLK files, so let's ignore compatibility with the original for now. Just let the engine create a new strref for you.

Change GemRB_SetJournalEntry however  you find needed. I don't know why you'd need a chapter and section (unless you mean the title) though.

**Comment by lynxlynxlynx** [comment]
@rsantellan did you mean to finish this or should someone take over?
