### ISSUE TITLE
BG2: Allow sorting of journal entries

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1367]
#### Description
Allow sorting journal entries by name or by date. 

#### Additional context
Clicking on the "BY NAME"/"BY DATE" button in the journal should toggle between both modes. 

The current mode is shown at the top: "Sorted by name/date". 

This works, and the button is shown, for quests, done quests, journal. While the user quests panel has no button to sort, it will react to being sorted and behave accordingly. 

### Pics

Sorted by name
![unknown-4](https://user-images.githubusercontent.com/68446748/126399370-897a7720-55d3-4de3-a83b-43249aa5a0bc.png)

Sorted by date
![unknown-3](https://user-images.githubusercontent.com/68446748/126399397-9c7a5489-4fb7-49ae-9d19-925600e9b87a.png)

**Comment by lynxlynxlynx** [comment]
This is all in `gemrb/GUIScripts/GUIJRNL.py` and we already change a variable when pressing the button. The loop filling the textarea with journal entry disregards it and does not sorting whatsoever.

**Comment by rsantellan** [comment]
@lynxlynxlynx I figure it out the sorting (was the easy part) my problem is that I should change the text. From where this text come from: https://github.com/gemrb/gemrb/blob/6d70e2207159a1587678421f36d38651f0b9db26/gemrb/GUIScripts/bg2/GUIJRNL.py#L91

**Comment by lynxlynxlynx** [comment]
That's the string index into dialog.tlk. You can find the correct number for the other text through NearInfinity or DLTCEP, as they both have search available.

**Comment by rsantellan** [comment]
@lynxlynxlynx I found it and found the one for: Sorted by name and Sorted by date.
How can I add a new label in the journal window? Where the window is defined ?

**Comment by lynxlynxlynx** [comment]
What's the problem?

**Comment by rsantellan** [comment]
I want to change this:
![image](https://user-images.githubusercontent.com/1820598/134189086-fe39b14d-a6ee-4bb3-b4ca-5c113fe046c6.png)
Don't know how...

**Comment by lynxlynxlynx** [comment]
It's the label with control ID 10 (you have to add 0x100000 or something like that to access it instead of the button — check other labels).

**Comment by rsantellan** [comment]
> It's the label with control ID 10 (you have to add 0x100000 or something like that to access it instead of the button — check other labels).

Found it! Was already on the file!
