### ISSUE TITLE
Targetted actors should have a different reticle

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1368]
One difference is foot circle when ordered to interact (talk, attack, I guess other actions too):

GemRB looks as above:
![Captura de pantalla de 2021-07-21 09-21-17](https://user-images.githubusercontent.com/1279852/126420484-73c2d00c-e025-4937-b8ee-14e3744b31b1.png)

BG2:
(send PC to talk or attack a neutral)
![Captura de pantalla de 2021-07-21 09-23-11](https://user-images.githubusercontent.com/1279852/126420559-2f8f5ef9-fa19-4e36-951f-f81e317ba1e2.png)
After attacking: 
![Captura de pantalla de 2021-07-21 09-24-06](https://user-images.githubusercontent.com/1279852/126420656-5f47b6ae-1755-4157-9a64-7bf0bafad198.png)
![Captura de pantalla de 2021-07-21 09-25-02](https://user-images.githubusercontent.com/1279852/126420883-77aa7182-07ec-404b-80ec-05661e4188e1.png)

Red crosshair indicates the target of currently selected player controlled creatures.

_Originally posted by @burner1024 in https://github.com/gemrb/gemrb/issues/1332#issuecomment-883837556_

**Comment by lynxlynxlynx** [comment]
This is relatively easy. We have `GameControl::DrawTargetReticle` abstracting away the drawing, which perhaps just needs a way to override the color. Then we just need to loop over the whole selection (`game->selected`) and see if anyone has a target set (`LastTarget`). Look at where DrawTargetReticle is used to draw the reticles for the party.

That would fix it for combat. For dialog and other things that may require movement, it's more annoying. We already draw the reticle, so the color needs adapting (if there's an actor at the target pos, draw with their color instead). But then also their own circle needs to be disabled. Or vice versa and the circle drawing code should use the reticle.

**Comment by burner1024** [comment]
>  But then also their own circle needs to be disabled. Or vice versa and the circle drawing code should use the reticle.

I think the second option is better, otherwise discrepancies will keep appearing. (For example, the target could be moving, which would result in de-sync as in linked PST issue).
