### ISSUE TITLE
Externalize message colors

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#137]
iwd2 for example uses gold for xp. So we need new entries in the colors.2da table of each game's unhardcoded/ folder and then use them in core (DisplayMessage). ~See `GameData::GetColor` on how to fetch the new colors from the table. The colors would replace the old DMC_BG2XPGREEN (...) defines. (done)~

PST:
>     Dialog text color #8CA27B (currently #70FF70)
>     Response option color #FF2C21 (currently #FF0000)
>     Response number color #84C7D6 (currently #FF0000, and wrong format)
>     Dialog creature name color #B59E73 (currently #B9B63F)
>     Dialog PC name color #84C7D6 (currently #A2A0A4)
>     Dialog chosen response text #9CC7D6 (currently #8080FF)
>     gained item/xp color #C6FFC6 (currently #BCEFBC)
Journal messages. Load/Save hints. Save messages ... look at where all the ~DMC_~ GUIColors enum constants are used.

**Comment by bradallred** [comment]
this will be related to #233 
would be nice to just do them both at the same time.

**Comment by lynxlynxlynx** [comment]
For #233 there is one tricky aspect to this — the color for the actor name is computed, so it's different for the various interlocutors. We'll have to pregenerate a palette with many options and then limit the choice to those.

**Comment by bradallred** [comment]
I'm not sure what you mean. I was thinking a single grey-scale palette that is then combined with a tint color. There is no reason the tint color cant be dynamically computed.

**Comment by lynxlynxlynx** [comment]
That avoids the speed problem? Ok then. :)

**Comment by bradallred** [comment]
These colors have been externalized in BG:EE and can be found in BGEE.lua. I think our colors are a bit off for most, but I'm not sure and I've already updated a few.

**Comment by rsantellan** [comment]
Searching for the DMC_ string I found

```
grep 'DMC_' * -nr | awk -F 'DMC_' '{print "DMC_"$2}' | awk -F',' '{print $1}' | awk -F')' '{print $1}' | awk -F' ' '{print $1}' | sed 's/^[ \t]*//' | sort | uniq -c
     33 DMC_ //IGNORE THIS ONE
    102 DMC_BG2XPGREEN
      4 DMC_DIALOG
      4 DMC_DIALOGPARTY
     12 DMC_GOLD
     84 DMC_LIGHTGREY
     30 DMC_RED
    210 DMC_WHITE

```
There are more colors or only this ones ?

**Comment by lynxlynxlynx** [comment]
For now only these — you can see all are defined in DisplayMessage.h. I suggest you first tackle DMC_DIALOG*, so we can evaluate the approach.

Btw, you could've searched much more cleanly with: `git grep -Eoh "DMC_\w+" | sort | uniq -c` and your count is doubled.

**Comment by rsantellan** [comment]
@lynxlynxlynx I have started working on this: https://github.com/rsantellan/gemrb/commit/ce6641ee691ba48b052d4494a3a5f759e71d0c75
I have the doubt if I should put only the new colors on the shared one or in all of them ?
Regards

**Comment by lynxlynxlynx** [comment]
My comments:
- use sensible names, there's no need to preserve the DMC_ prefix
- DisplayMessage members like DisplayStringName should take the color key and look up the color themselves. This will save a bunch of code
- color definitions need to be in all existing files. Then they can be changed and split further as needed in the second step, after externalization

**Comment by rsantellan** [comment]
> My comments:
> 
>     * use sensible names, there's no need to preserve the DMC_ prefix
> 
>     * DisplayMessage members like DisplayStringName should take the color key and look up the color themselves. This will save a bunch of code
> 
>     * color definitions need to be in all existing files. Then they can be changed and split further as needed in the second step, after externalization

- I keep the same names for been easier to search for them
- I will look the DisplayStringName function to see what I can.
- I will copy to all files.

**Comment by lynxlynxlynx** [comment]
Just add new wrapper functions as needed. They would take the color constants, resolve them and then call the existing functions. It will kill off most of your diff as well.

**Comment by rsantellan** [comment]
So the best way will be to keep the code like this:
```
displaymsg->DisplayStringName( tr->textStrRef, DMC_DIALOGPARTY, speaker, IE_STR_SOUND|IE_STR_SPEECH|IE_STR_ALLOW_ZERO);
```
Instead of this:
```
displaymsg->DisplayStringName( tr->textStrRef, gamedata->GetColor("DMC_DIALOGPARTY"), speaker, IE_STR_SOUND|IE_STR_SPEECH|IE_STR_ALLOW_ZERO);
```
Or this:
```
displaymsg->DisplayStringName( tr->textStrRef, "DMC_DIALOGPARTY", speaker, IE_STR_SOUND|IE_STR_SPEECH|IE_STR_ALLOW_ZERO);
```
And do the **GetColor** on that function ?

**Comment by bradallred** [comment]
we use C++11 now, you can just forward the argument list:

```cpp
template<class... Args>
void DisplayRollStringName(int stridx, int colorID, const Scriptable *speaker, Args&&... args) 
{
  const Color& color = gamedata->GetColor(colorID);
  return DisplayRollStringName(stridx, color, speaker, std::forward<Args>(args)...);
}
```

**Comment by rsantellan** [comment]
Hi @bradallred @lynxlynxlynx I'm a newbie with C++ what you talking is this https://en.cppreference.com/w/cpp/language/parameter_pack right ? I just have to figure it out the .h and .cpp implementation.

**Comment by lynxlynxlynx** [comment]
Yes, Brad gave you a working example.

**Comment by rsantellan** [comment]
One thing I seeing is that I should change:

- DisplayString
- DisplayStringName
- DisplayRollStringName

And all the calls, but if I change obtaining the color I change that part. Trying to see the benefit of this, I'm only seeing the tree not the forest right now.

**Comment by lynxlynxlynx** [comment]
Sorry, it's not clear to me which part you are struggling with. The main point of the extra wrapper functions is to remove the need for callers (users) to call `gamedata->GetColor()` themselves.

Looking at DisplayRollStringName, it never takes a variable color, so there you don't even need another wrapper — just change the function itself. DisplayStringName (and maybe DisplayString) is the one that will need two: one that takes a Color and one that takes, let's say, a string (so the color name from the table). You'll have to change the DMC_* constants to strings either way.

**Comment by rsantellan** [comment]
@lynxlynxlynx it will be something more like this ? https://github.com/rsantellan/gemrb/commit/2e4bb8ec9ce2de87c40cbea998b7efed710041f1

**Comment by rsantellan** [comment]
I have made the changes on https://github.com/rsantellan/gemrb/tree/137-constant-change I will wait until the UTF-16 is finish to merge it.

**Comment by lynxlynxlynx** [comment]
Now only the data part remains. Perhaps that will show some other colors need to be unhardcoded, but that is trivially done now.

**Comment by lynxlynxlynx** [comment]
Looks like there's a regression somewhere: all pc text is red (probably from the default) and pause/unpause are not.

**Comment by rsantellan** [comment]
> Looks like there's a regression somewhere: all pc text is red (probably from the default) and pause/unpause are not.

#1630 I fix the starting number of the enum. I counted 7 but is the 6 position.
