### ISSUE TITLE
BG2: Error after dialog. 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1372]
#### Bug description
After starting a dialog cut scene the character options bar is removed.

In the terminal it shows:
```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/rodrigo/games/BaldurGate2/gemrb-myfork-git/gemrb/GUIScripts/GUIWORLD.py", line 87, in DialogEnded
[Python/ERROR]:     ContinueWindow.GetControl(0).SetHotkey (None, 0, True)
[Python/ERROR]: AttributeError: 'GButton' object has no attribute 'SetHotkey'
```
#### Steps to reproduce
1. Go to Umar hill with shadows
2. Aproach Anath
3. See error

#### Expected behavior
Character action bar still there

#### Screenshots
![image](https://user-images.githubusercontent.com/1820598/126728265-484968bc-0e3f-4bc6-b9cd-485ebdf02a19.png)

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [X] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by rsantellan** [comment]
I think this commit is the one that introduce the problem: a2bc2c854db4296f03c15cda3e8bc7a25b602b52

**Comment by bradallred** [comment]
im sure you're right, but it doesnt makes sense `GButton` _definately_ has `SetHotkey`

are you sure you haven't been switching between 0.8.8 and master? if you do that you need to be careful to replace the GUIScripts

**Comment by rsantellan** [comment]
I forked from master the 8 of July and today I press the button fetch upstream from the github gui, I delete all build and recreated. 
I have the class here https://github.com/rsantellan/gemrb/blob/660c81ecd7be502b6a700a62ad05ce5cb6a8b257/gemrb/GUIScripts/GUIClasses.py#L326 with the method but still fails

**Comment by bradallred** [comment]
maybe we could get a more useful error with python 3.

if you remove that line do you get a different error?

**Comment by lynxlynxlynx** [comment]
GameControl::ChangeMap calls EndDialog (huh), triggering the function. So it just needs a guard that the button exists.

**Comment by bradallred** [comment]
if the button didnt exist I would have expected a different error (eg "none type has no attribute 'SetHotkey')

**Comment by lynxlynxlynx** [comment]
Me too, but it could be the first error wasn't shown or there was one of those frame stack corrupting internal python errors earlier.

**Comment by rsantellan** [comment]
> maybe we could get a more useful error with python 3.
> 
> if you remove that line do you get a different error?
@bradallred  How do I do this ? Do you work with python virtual enviroments ?

**Comment by lynxlynxlynx** [comment]
It's fixed, don't bother.
