### ISSUE TITLE
Simplify Map::SortQueues

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1378]
`cstdlib` provides `qsort`, so surely we don't need to reimplement it.

https://www.cplusplus.com/reference/cstdlib/qsort/

**Comment by bradallred** [comment]
we can probably just use `std::sort` too. AFIK there is no reason to prefer `qsort` specifically

**Comment by rsantellan** [comment]
Looking at the code:
 https://github.com/gemrb/gemrb/blob/4e0fcacb97b7f39156cc91aa1145ad0400227c39/gemrb/core/Map.cpp#L2848
The ordering condition is always the **Y** position ?

**Comment by rsantellan** [comment]
> Looking at the code:
> 
> https://github.com/gemrb/gemrb/blob/4e0fcacb97b7f39156cc91aa1145ad0400227c39/gemrb/core/Map.cpp#L2848
> 
> The ordering condition is always the **Y** position ?

And what will be a good test to do to the function ?

**Comment by lynxlynxlynx** [comment]
You can print the global IDs of the Scriptables in the final queue and abort immediately, then compare the order before the actual refactoring and afterwards.
