### ISSUE TITLE
[bug] Dispelling Polymorph Other Does Not Work And Spell Itself Is Extremely Ineffective.

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#138]
**Describe the bug**
There are two issues with Polymorph Other SPWI415 spell. The spell uses EFF file PLYSQUIR.EFF to turn target into squirrel.
1) The spell is nearly impossible to be successfully cast even on caster level 30. 
Test:
Game: Unmodded (BG2Fixpack + ToBEx)
CASTER LVL: 16 CHARNAME Necromancer
TEST SUBJECT: LVL 1 Enge (SHOP04.CRE)
TEST SUBJECT Polymorph saving throw: 18 
Lowered TEST SUBJECT Magic Resistance: -52%
Lowered TEST SUBJECT Polymorph saving throw: 24
               -Doom (-2)
               -Greater Malision (-4)
Result: Cast Polymorph Other spell on (hostile) Enge 8 times while the NPC had it's polymorph saving throw lowered to 24. None of the attempts were successful.

Modded Game:
Performed similar test on Hubelpot lvl 1 NPC with Irenicus caster level 30. Hubelpot polymorph saving throwed lowered from 15 to 21. None of the 9 attempt to cast Polymorph Other on Hubelpot were successful. Magically created weapon that changes forces squirrel animation is DVSQUIR.ITM

2) If target gets successfully polymorphed into squirrel the actor can be returned to original form by casting Dispel Magic spell as per spell description. Dispel Magic spell does not remove polymorphed state. I tried using Dispel Spell from a cleric and a wizard spellbook. I also tried to cure polymorphed state by visiting temples of Illmatar in Baldur's Gate, Morning Sun east of Beregost and temple of Helm in Nashkel. 

Tiax NPC from my party managed to get himself polymorphed into squirrel during battle with Brother Hasdar (NTotSC mod) and his lackeys. The caster who turned Tiax into squirrel ~~is unknown because I checked Hasdar and he does not have memorized Polymorph Other spell.~~ is SHADOW01.CRE who has memorized Polymorph Other Spell with exactly matching ID of SPWI415 - the same one I tested. SHADOW01.CRE both on modded and unmodded game has the same spell.

**Comment by lynxlynxlynx** [comment]
Fixed, thanks for the details. Dispel was generally done completely wrong, while polymorph didn't get a chance due to using exotic targetting.
