### ISSUE TITLE
[BG2] No sleep button at resolution 1280x960 

### ISSUE THREAD

**Issue by goduck777** [gemrb/gemrb#1380]
#### Bug description
The sleep button is not shown up on the left bar for BG2 using 1280x960, which should be supported according to the configuration file.

#### Expected behavior
Sleep button should appear on the left bar.

GemRB version (check as many as you know apply)
- [ ] master as of this issue
- [x] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
This is a data problem with the files from the game. GUIW12.chu (and higher) just don't have the button for some reason, so we'll have to construct it on the python side. It's control id 11 in the other files. We already have do almost the exact same thing in bg1:

https://github.com/gemrb/gemrb/blob/ab01a35a4c39d4f9a1ce87c842eaaa943fa4d888/gemrb/GUIScripts/GUICommonWindows.py#L252-L267

We can do the same here or actually append a button.

**Comment by rsantellan** [comment]
On latest master the button is visible.
![image](https://user-images.githubusercontent.com/1820598/133710035-84164b8e-1057-425d-8c1b-3be413667930.png)
