### ISSUE TITLE
ieVariable: review uses

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1381]
First, is sizeof ieVariable guaranteed to return the array size? The docs say it could also include padding.

Looking at where we use it also shows a bunch of mem* and str* function uses, some of which actually target an ieVariable:
```c
gemrb/core/GameScript/Triggers.cpp:1711:                        len = snprintf(Variable,sizeof(ieVariable),"%s_DEAD",parameters->string0Parameter);
gemrb/core/GameScript/Triggers.cpp:1714:                        len = snprintf(Variable, sizeof(ieVariable), core->GetDeathVarFormat(), parameters->string0Parameter);
gemrb/core/GameScript/Triggers.cpp:1717:                if (len > sizeof(ieVariable)) {
gemrb/core/IniSpawn.h:138:              strnlwrcpy(Name, name, sizeof(ieVariable) - 1);
gemrb/core/Interface.cpp:1622:          memcpy(DeathVarFormat, IWD2DeathVarFormat, sizeof(ieVariable));
gemrb/core/Map.cpp:3870:        memcpy(Name, src->Name, sizeof(ieVariable));
gemrb/core/Scriptable/Actor.cpp:5414:           const size_t len = snprintf(DeathVar, sizeof(ieVariable), "%s_DEAD", scriptName.CString());
gemrb/core/Scriptable/Actor.cpp:5415:           if (len > sizeof(ieVariable)) {
gemrb/core/Scriptable/Actor.cpp:10455:          memset(UsedExit, 0, sizeof(ieVariable));
gemrb/core/Scriptable/Actor.cpp:10461:                          snprintf(UsedExit, sizeof(ieVariable), "%s", ipName);
gemrb/plugins/GAMImporter/GAMImporter.cpp:778:                          memset(tmpname, 0, sizeof(ieVariable));
gemrb/plugins/GAMImporter/GAMImporter.cpp:779:                          strncpy(tmpname, "DICTIONARY_GITHZERAI_ HJACKNIR", sizeof(ieVariable));
gemrb/plugins/GUIScript/GUIScript.cpp:10023:                    strnuprcpy(ip->EntranceName, NewEntrance, sizeof(ieVariable)-1 );
gemrb/plugins/TLKImporter/TLKImporter.cpp:58:           strnuprcpy(key, tm->GetRowName(i), sizeof(ieVariable)-1 );
```
I guess the functions are fine, since it has a char*() operator?

**Comment by bradallred** [comment]
as per the standard, a compiler would be allowed to pad at the end.

IRL, this is no concern. it is a byte array which already has no alignment requirement and therefore no reason to add padding anywhere for any architecture. 

To avoid undefined behavior we can trivially replace any `memcpy` operations with an assignment. I suspect all the `members` can be removed since we already have 0 initialized data.

everything else should work fine without undefined behavior

**Comment by lynxlynxlynx** [comment]
So I take it there's also no need for overriding operator[] above?

**Comment by bradallred** [comment]
we actually _should_ use `operator[]` it would be more idiomatic and less error prone (cant pass it as a `void*` or or oth3r implicit conversions). I only opted for the implicit conversion operator because I didnt want to go around dealing with all the `memcpy`/`memset` issues at the time.

**Comment by lynxlynxlynx** [comment]
Good idea to take another look, clang-tidy and sonar were of course complaining that the constructors and operators are not explicit.

I was talking about this new line specifically:
https://github.com/gemrb/gemrb/commit/6e43510432243f181493582d8ae4e58aac1827e3#diff-3a77b6a6e62202ce2848a7e9653052496ba60decb2e7d5f52ff9b0169f7c6942R10460

**Comment by lynxlynxlynx** [comment]
Done, except for the char* operator, which I don't think is possible.
