### ISSUE TITLE
[BG1] No ambient sound when changing area 

### ISSUE THREAD

**Issue by goduck777** [gemrb/gemrb#1382]
#### Bug description
When playing BG1 using GemRB with OpenAL, the amibient sound plays normally when loading the game. However, when changing to a new area including entering room, the ambient sound of the new area never plays, and does not recover when going back to original area. The other sounds are normal.

There is no error in the log.

#### Steps to reproduce
1. Start a new game in BG1
2. Enter an inn

#### Expected behavior
The ambient music of inn should be played.

GemRB version (check as many as you know apply)
- [ ] master as of this issue
- [x] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Can you try with the latest build, since there were some relevant fixes in between?

**Comment by goduck777** [comment]
Thank you for reply. Unfortunately the latest build from the master branch does not work for me. It gives a lot of core dumps when loading a save file and when creating a new character.

**Comment by lynxlynxlynx** [comment]
Really? Which platform are you on? 

I've just tried creating a new character in bg1 and succeeded to enter the game normally. Do you have any mods installed? Please provide one of the problematic saves.

**Comment by goduck777** [comment]
Sorry my mistake. I remove my configuration file and make a new one, and it works now.

I can confirm that in the latest build, the inn music is on when entering it.

However, the background noise of Candlekeep still has some issues. If I load a game in the town, the ambient sound is normal. However, if I enter the inn and then exit, there is no ambient sound.

**Comment by goduck777** [comment]
For the core dump, see #1383

**Comment by lynxlynxlynx** [comment]
~Map resets the ambients and  that happens after SetupAmbients was already called for the new area. It's not a problem when going into the inn as the previous area is its master area and is not unloaded, but when exiting we of course do it to the inn area.
