### ISSUE TITLE
[BG1] Core dump when enabling DebugMode=1 

### ISSUE THREAD

**Issue by goduck777** [gemrb/gemrb#1383]
#### Bug description
In the latest build using master branch, when setting DebugMode=1, the game can crash and give core dump when loading a game or creating a character.

#### Steps to reproduce
1. Set DebugMode=1 in GemRB.cfg
2. Start a game
3. Single Player - New Game

#### Expected behavior
The New Character screen should show up

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
It's odd that you have that on and on that value, but good to know — can reproduce.
