### ISSUE TITLE
BG2: Companions stays speachless when removed from the party 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1384]
#### Bug description
When removing Valygar from the party or any companion it stays speachless

#### Steps to reproduce
1. Go to Reform Party
2. Remove some one from the party
3. See error

#### Expected behavior
The companion should say **are you sure ? And I'll be on someplace**

#### Screenshots
https://user-images.githubusercontent.com/1820598/126922082-97ae1893-3f27-4d3f-b07f-31e3780af14c.mp4

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [X] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Can you try with 0.9.0 just to see if it's a recent regression? If it doesn't work there, please attach a save.

**Comment by rsantellan** [comment]
On the 0.9.0 tag is working ok.

![image](https://user-images.githubusercontent.com/1820598/126990912-d1f80d69-0abd-4b04-8748-baad7cc227d2.png)

**Comment by lynxlynxlynx** [comment]
Please retest this, it works for me.

**Comment by rsantellan** [comment]
Now it is working alright
