### ISSUE TITLE
correctly implement height maps

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1385]
If you look at `Actor::GetElevation` you will see that we clamp elevation at 15. This is because we only correctly handle 4bpp height maps. BG2 AR1300 (and presumably others) have 8bpp height maps, which lead me to question even our handling of 4bpp maps.

Annoyingly, NI wont seem to open either the 8bpp nor the 4bpp height maps, but I have interjected a `BMPWriter` to export a couple of height maps from both an 8bpp area and a 4bpp area.

Currently we assume 4bpp height maps to represent a height from 0-15, but it is clear from looking at the both of the exports this is incorrect.

AR1300 (8bpp):
![BG2-AR1300](https://user-images.githubusercontent.com/1126744/127049802-3c4d008d-bac5-4bea-bec9-6a4057a576af.png)

AR2000 (4bpp):
![BG2-AR2000](https://user-images.githubusercontent.com/1126744/127049844-3fcd5a2b-cfb0-4ce9-bd88-9dc3b7e88c10.png)

it's pretty straight forward: black is the bottom of the world, white is the top. RGB(128,128,128) is "sea level". This means that values below RGB(128,128,128) are _negative_ height. We shouldn't be looking at the "bitmap" at all, we need the palette to see the actual height.

Now, I have no idea what the top and bottom of the world values are. Even if we did know it seems that all we do with elevation is offset drawing from the foot circle, which certainly cant be right. I'm actually struggling to think what the original engine used height maps for. Is it just for "advantage" calculations in combat?

This would probably be a better fix for #1326 as well. I'll bet their "uniform" values are all RGB(128,128,128)

**Comment by lynxlynxlynx** [comment]
We have a fixme somewhere for this, yes, since they're not well understood. But they were indeed only used for drawing offset, to make the maps feel less flat.

**Comment by bradallred** [comment]
one good test would be to recode walking up the stairs in AR1300 from the original. I doubt it affects the drawing per se, but it does seem reasonable that transitioning from elevations would actually shift the actor position (not just the drawing). Imagine stairs on a 2d background, a character should shift their position, otherwise it doesn't really feel like stairs. Maybe a better example is imagining falling from the walls, the actor position would need to shift, otherwise it would look like you just walked off the wall and teleported some ways to the north.

we could also use a debug flag to draw the height map like the search map

**Comment by lynxlynxlynx** [comment]
Changing the position could easily break so many things I have almost no faith in this hypothesis. But yeah, specially crafted heightmaps would be the best way to easily test original behaviour. I think ctrl-m printed the actor position there as well.

**Comment by bradallred** [comment]
i'm not sure how it could break anything as long as it was clamped to passible tiles. Right now things are broken because we draw the actor above their position so you can easily look like you are trying to scale a wall.

regardless, yes, the experiment to replace some original height map and run with it in the original will certainly answer things. Use extreme values like all white and all black.

**Comment by bradallred** [comment]
the proposed experiment should also be able to answer the question of "world height" by using the extremes of black and white compared to RGB(128,128,128)

**Comment by lynxlynxlynx** [comment]
If it affected the actual position, imagine the grief of the pathfinder or range calculations.

Here's some old research that doesn't bother with 8-bit entries:
https://gibberlings3.github.io/iesdp/appendices/height.htm
http://www.simpilot.net/~sc/dltcep/areamaking/main.htm#height

My bet is they just forgot to change the color space for these few areas before shipping.

**Comment by bradallred** [comment]
that research backs up my claims about BPP not mattering. Palette is key, not the "bitmap".

also appears that the "world height" I was referring to is +/-7 instead of our current +15. We are probably getting lucky with the 4bpp images that the palette colors happen to align with the bitmap values, but we are still interpreting it wrong since we go too positive and don't handle negative.

That makes the fix rather easy: use a `Sprite2D` instead of `Bitmap` and read the color and pick any of the R/G/B channels to use to map the 0 - 255 value to -7 - +7

this would also probably work in PST

**Comment by lynxlynxlynx** [comment]
pst foot circles are still fine.
