### ISSUE TITLE
[BG1] Scroll view window not showing up after pressing "Esc"

### ISSUE THREAD

**Issue by goduck777** [gemrb/gemrb#1388]
#### Bug description
The scroll view window shows up normally when first starting the game after right click the scroll in the priest/mage scroll window. However, after pressing "Esc" to close this window, right click does not call the window any more.

The error message is like

```
[GUIScript/ERROR]: Attribute Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/usr/share/gemrb/GUIScripts/GUIPR.py", line 202, in OpenPriestSpellInfoWindow
[Python/ERROR]:     PriestSpellInfoWindow.Unload ()
[Python/ERROR]:   File "/usr/share/gemrb/GUIScripts/GUIClasses.py", line 237, in Unload
[Python/ERROR]:     self.Close()
[Python/ERROR]:   File "/usr/share/gemrb/GUIScripts/GUIClasses.py", line 240, in Close
[Python/ERROR]:     RemoveView(self, False)
[Python/ERROR]: AttributeError: Invalid view
```

#### Steps to reproduce
1. Start a new game
2. Press 'P‘ to go to priest scrolls
3. Right click on a scroll
4. Press 'Esc'
5. Right click on a scroll

#### Expected behavior
The scroll info window should show up

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment]
GUIMG for BG2 behaves as expected now. We can copy that to the other scripts as needed.

**Comment by lynxlynxlynx** [comment]
There's no other except for pst. :)

**Comment by bradallred** [comment]
well I think GUIPR needs more work

does PST not have this feature then?

**Comment by lynxlynxlynx** [comment]
Ah, I thought you just meant copies for other game types. You can definitely inspect spells in the spellbook in pst.

**Comment by goduck777** [comment]
I can confirm the problem in BG1 is fixed. Thanks!
