### ISSUE TITLE
[bug] Wizard and priest spellbook constant sparkle.

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#139]
When using the spellbook you can notice constant sparkle. The sparkle usually starts when removing a spell from current memorized spells. 

![Priest spellbook sparkle](https://user-images.githubusercontent.com/17316115/56845530-c8813100-6890-11e9-8978-0c8999824479.jpg)
![Wizard   Priest Spellbook sparkle glitch](https://user-images.githubusercontent.com/17316115/56845531-c8813100-6890-11e9-96c7-5546d02fba5c.jpg)

**Comment by lynxlynxlynx** [comment]
This is fixed, we got a duplicate reports: #194 #205
