### ISSUE TITLE
BG2: Black parts of portraits can turn transparent on bmps with indexed colors

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1394]
#### Bug description
When my dear Gavin died in BGT, his hair and other parts of the portrait that are black `#000000` turned transparent, showing the background of the game.

Creating a new game in BG2 with Gavin's picture as my player avatar has those parts transparent, even when alive.

Looking at the gavin bmp, it has indexed colors. Creating a new avatar with indexed colors and a black part has the same effect. 

This doesn't happen in 0.8.8.
Tested with both, latest AppImage and own build.

#### Steps to reproduce
1. Create a new character with a portrait that has indexed colors and black parts

#### Expected behavior
Those parts should just stay black.

#### Screenshots
Alive (BGT)
![unknown-1](https://user-images.githubusercontent.com/68446748/127696792-6841363c-2fb6-461c-b79a-f5608f9f3ced.png)

Dead (BGT)
![unknown](https://user-images.githubusercontent.com/68446748/127696808-7276f307-fcfe-4bc1-b1da-1c4ebf3889cf.png)

Custom portrait with black dot (BG2)
![unknown-4](https://user-images.githubusercontent.com/68446748/127705710-f6739bbd-06a6-47a9-a330-30b9aa18a0d1.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [x] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment]
use the OPENGL backend

**Comment by bradallred** [comment]
The code in question is doing `BlitFlags::COLOR_MOD`, but that shouldn't affect the alpha channel. Still the `TODO` indicates dead actors should be `BlitFlags::GREY`

If you are dealing with indexed colors you need to pay attention to the alpha value. we used to ignore it, but cannot any longer.

https://github.com/gemrb/gemrb/blob/03d2cbcc00a1957ad514e04beed229dbbe0dc699/gemrb/core/GUI/Button.cpp#L196-L200

**Comment by Laulajatar** [comment]
> try using the OPENGL backend and see if it is an issue there.

--   SDL_BACKEND: SDL2
--   OPENGL_BACKEND: OpenGL

Still happens with OpenGL. 

![unknown-5](https://user-images.githubusercontent.com/68446748/127708839-ab279d5a-966a-4e3f-8c17-f24b82d98fe4.png)


[portraits.zip](https://github.com/gemrb/gemrb/files/6909892/portraits.zip)

**Comment by bradallred** [comment]
good to know thanks. 

The problem is that black is our BMP importer expects there to be a color key. I dont know why or which BMPs we expect to have a color key, but the code is here. Just change `PixelFormat fmt = PixelFormat::Paletted8Bit(pal, true, 0);` to `PixelFormat fmt = PixelFormat::Paletted8Bit(pal, false, 0);`

https://github.com/gemrb/gemrb/blob/03d2cbcc00a1957ad514e04beed229dbbe0dc699/gemrb/plugins/BMPImporter/BMPImporter.cpp#L233-L240

**Comment by lynxlynxlynx** [comment]
I don't remember any transparent bmps and looking at zelazko's gigainstall, it's just portraits and area maps (light, height, search). What's the 32-bit reason?

**Comment by bradallred** [comment]
I haven't a clue its just obvious it is was "purposely" written since it is explicit code written to make a color key as opposed to 8bit where the default `CreateSprite` value was index 0 and could easily be attributed to an accident or oversight.

we can change it and see what breaks 🤷

**Comment by lynxlynxlynx** [comment]
You could always look at the commit message. `git log -Ssth` is great at finding specific changes and if you get to the end, you can always pass the sha^ as well, to start looking from the parent commit onwards. Might be faster than travelling back with git blame though github UI makes that very simple now.

**Comment by bradallred** [comment]
32bpp color keys were added in fbc49c3

**Comment by bradallred** [comment]
8bpp was added in c4170df and it doesn't say anything useful about why

**Comment by lynxlynxlynx** [comment]
Ah, so ancient and old stuff. c4170d doesn't look useful; our guils use mos and bam like everyone else. But pst indeed has several users in the journal and map notes:
![image](https://user-images.githubusercontent.com/121515/127731924-59e8244c-cdf1-488a-956b-db235900883a.png)
![image](https://user-images.githubusercontent.com/121515/127731915-678b1335-ea82-49ed-8199-708280582afd.png)
STPVHA.bmp and usernote.bmp

So we should be treating them like bams.

**Comment by bradallred** [comment]
well, we unfortunately have no way of calling `SetColorKey` on the specific BMPs we want to have a color key, but maybe we can compromise and only set the color key if index 0 is pure green.

**Comment by lynxlynxlynx** [comment]
Yep, sounds good.
