### ISSUE TITLE
BG1/BG2: Portraits with indexed colors are distorted 

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1397]
#### Bug description
Using bitmaps with indexed colors as portrait distorts the graphic.
I tested this with custom portraits, indexed and not indexed. The not indexed ones show up normally.

Some of the game's portraits are also affected. 

#### Steps to reproduce
1. Create a new character
2. Pick a custom portrait with indexed colors
or
1. In BG1, just load the [888888888-Mission-Pack-Save.zip](https://github.com/gemrb/gemrb/files/6911947/888888888-Mission-Pack-Save.zip)

#### Expected behavior
Not do that.

#### Screenshots
BG2
![unknown](https://user-images.githubusercontent.com/68446748/127754615-44cbd4a4-db0a-4bd8-81c4-0c24b278ac5d.png)

BG1
![Screenshot_2021-08-01_01-30-49](https://user-images.githubusercontent.com/68446748/127754631-29e7a70f-0d11-47ed-8798-45407a0dde0e.png)

BG1 mission pack save
![Screenshot_2021-08-01_01-34-59](https://user-images.githubusercontent.com/68446748/127754699-0d52e24a-1c07-486f-be0f-ebb9168f4e6d.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Interestingly, in bg2 the big portraits in GUIREC are fine (in this save only one of the default portraits has the problem): of Skie:
https://baldursgate.fandom.com/wiki/Portraits?file=Skie_Silvershield_SKIE_Portrait_BG1.png

So that means files skie[sml].bmp.

**Comment by Laulajatar** [comment]
Do you mean the character stats page? 
I assumed that for some reason not all portraits of BG2 are saved with indexed colors, as it also happens on that page if I make sure to use a custom portrait with indexed colors: 

![Screenshot_2021-08-01_14-40-06](https://user-images.githubusercontent.com/68446748/127771223-11fc56a0-112d-4bdd-b66c-225ea3573b87.png)

**Comment by bradallred** [comment]
this has nothing to do with index vs not. I can tell just by looking at the screenshot its a classic pitch issue. We allow SDL to create the pixel buffer now and SDL wants the buffer rows to be aligned on 4 byte boundaries so it can efficiently blit them with SIMD instructions. We then mindlessly copy into this buffer assuming the designation and source have the same pitch.

the fix is trivial tho. Drop `memcpy` and use `std::copy` with a pitch aware `PixelIterator`
