### ISSUE TITLE
IWD: fails to start over clashing opcodes 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1399]
#### Bug description
I cannot start IWD (without HoW; HoW directory looks good). Maybe related to d74b336aa3fcffc43f537fc3d2c463105af4b3a8?

#### Steps to reproduce
1. Try to start IWD.

#### Screenshots
While starting:
```
[EffectQueue/FATAL]: Clashing Opcodes FN: 324 vs. 290, protection:spell3
```

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Yeah, that line in gemrb/unhardcoded/iwd/effects.ids was a mistake.
