### ISSUE TITLE
TextEdit: implement XEditCaretOffset

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1409]
It's a currently unused field that should help with proper caret positioning. Can maybe obviate the need for OverrideCursorPos / GF_OVERRIDE_CURSORPOS in pst and iwd2 (not obvious from data).

Also CHUImporter: what we read into `cursor` might be the caret to use (NI suggestion), not or not only the mouse cursor. In pst at least one control sets it to a different font (postant.bam instead of caret.bam).

**Comment by bradallred** [comment]
I suspect the `cursor` is for the mouse. IIRC, each font has its own caret we should be using for the printed cursor.

**Comment by lynxlynxlynx** [comment]
I tested various fields in pst and bg2 only to realize that the originals always take the file from the bif, ignoring the override. 🤦
