### ISSUE TITLE
BG1/BG2: Save menu slightly broken

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1412]
#### Bug description
Not sure how to describe this better. The load/save menu doesn't show all entries properly and does weird things on scrolling. It displays less entries than there are savegames and sometimes displays one savegame multiple times. 
Loading works if you can find the right save, didn't (dare to) try saving. 

The commit that broke it seems to be b541714fba3811bf85ff6bc1df4e3fcb69e84df1

#### Steps to reproduce
1. Try to load or save a game.

#### Screenshots
I'm scrolling through the list in both gifs:

![Peek 2021-08-07 19-07](https://user-images.githubusercontent.com/68446748/128609048-748db418-379b-41cf-ac3b-4f10b30bc7c5.gif)
![Peek 2021-08-07 19-32](https://user-images.githubusercontent.com/68446748/128609051-7fdf45b7-da4f-4135-a366-798585237f80.gif)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

**Comment by bradallred** [comment]
are you sure about b541714 being at fault. I don't see how it could be myself.

**Comment by Laulajatar** [comment]
That's what a bisect told me. If I build ff1dd0df8758d4c6730ce35125f58a73d0dbdb52 it works and on b541714fba3811bf85ff6bc1df4e3fcb69e84df1 it's broken.

**Comment by bradallred** [comment]
you didnt mention the python error in the log. that clarifies things.

**Comment by Laulajatar** [comment]
I'm sorry, I didn't even see that. 
Thank you for the quick fix.

**Comment by bradallred** [comment]
oh its fine! I want trying to chastise you! I was just struggling to understand how the 2 could possible be related, they weren't really, premature script termination has funny side effects.
