### ISSUE TITLE
BG1/BG2: You must gather your party before venturing forth

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1413]
#### Description
When attempting to travel while some party members are not close enough, the text "You must gather your party before venturing forth" should appear (and though my VM has no sound, I'm pretty sure there was a voice, too :D)

Instead the character just stands there, doing nothing. 

#### Additional context
The text should appear when some of the characters are waiting / not moving towards the character who initiated map travel. It should not appear as long as the other characters are currently walking towards the character who initiated map travel. 

Unlike on the overworld, it seems inside dungeons frantic clicking on a door triggers the message as soon as the first character has arrived there, even if the others are still moving. 

#### Screenshots
Original BG1
![unknown-1](https://user-images.githubusercontent.com/68446748/128609644-ce8f0642-c70a-42e6-8c17-b1f05a816f07.png)

**Comment by lynxlynxlynx** [comment]
We already support this iconic line; it's handled in Map::UseExit. So the question is why the wholeparty stuff isn't being triggered by these area exits.
