### ISSUE TITLE
BG1/BG2: Inconsistent behaviour of the settings for Marker Feedback

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1414]
#### Description
I'm honestly not sure if this is really worth an issue, just a small difference, do with it what you want. 
In BG2, friendly/non-hostile NPCs do not show the cirlce around their feet unless hovered over with the cursor. 

In GemRB, they do. 

#### Additional context
Original BG2
![unknown-2](https://user-images.githubusercontent.com/68446748/128610256-252b8bce-d1eb-4a11-b301-766c85faefbc.png)

GemRB
![Screenshot_2021-08-07_20-16-49](https://user-images.githubusercontent.com/68446748/128610260-14bd8d2b-2b03-49b5-bf91-36d0783872dc.png)

**Comment by bradallred** [comment]
I thought this was one of the "feedback" settings

**Comment by Laulajatar** [comment]
Yes, you are right, my bad, didn't think of that. 
I'm using the same settings though and it behaves differently. On both screenshots the sliders is one step to the left from max. 

It seems GemRB is off by one. If I move it 2 ticks to the left, the friendly NPCs marker vanish. The description says hostile creatures should have no marker, but they are still there. Moving it 3 to the left makes them vanish.

**Comment by lynxlynxlynx** [comment]
So is the problem the GUI displays it wrong or we store the wrong number? Compare the key value in gem-baldur.ini and baldur.ini.

**Comment by Laulajatar** [comment]
baldur.ini `GUI Feedback Level=5` 
gem-baldur.ini `GUI Feedback Level = 5`

**Comment by Laulajatar** [comment]
Ok, I hope I got this all right, it was a lot of alt tabbing back and forth. 

### Baldur's Gate 1

#### All levels: 
**Classic**: Hovering over a party member or portrait flashes the frame of the portrait black, green, white.
**GemRB**: Hovering over a selected party member portrait flashes the frame of the portrait, but hovering over a unselected one does nothing.

**Classic & GemRB:** Pausing shows all circles, behaving as on level 5.

**Classic**: If a party member is talking, the circle flashes white while the audio plays. If no circles usually show due to the setting, it appears while flashing white.
**GemRB**: The white circle only shows if green circles are showing. If the party member is unselected, the white circle is dimmed. 

#### Feedback level 1:
**Desc**: Minimum - picked creature 
**Classic**: No circles are shown, except when hovering with mouse over the character or portrait. The circle flashes between black, color of the circle* and white (* cyan for npcs, green for party members, red for enemies). 
**GemRB**: No circles are shown, not even when hovering

#### Feedback level 2: 
**Desc**: Low - picked creature or selected character
**Classic**: The currently selected party member shows a circle, and the character or party member/ the mouse hovers over (or portrait in case of party member) shows a flashing circle as in 1
**GemRB**: The currently selected party member shows a circle, nothing on hover

#### Feedback level 3: 
**Desc**: Medium - picked creature or selectable character
**Classic**: The selected party member has a bright green circle, the others have a dull green circle. Hovering (figure or portrait) flashes the circle as in 1. Enemies show no circle, but flash when hovered over. 
**GemRB**: The selected party member has a bright green circle, the others have a dull green circle. Hovering (figure or portrait) flashes between dark green and bright green, no black or white. Hovering over neutral npcs still does nothing. Enemies show no circle unless paused.

#### Feedback level 4:
**Desc**: High - picked creature or selectable character or targeted creature
**Classic**: As in 3. A hostile creature that is currently being attacked by a party member shows a red circle (well, more a red pizza as described in issue https://github.com/gemrb/gemrb/issues/1368 )
**GemRB**: As in 3. Enemies show a red circle always (not only when targeted), and pulse when hovered over. 

#### Feedback level 5: 
**Desc**: all creatures and characters (default) 
**Classic**: All circles are shown. Unselected party members still a dull green, selected ones a bright green, hovered characters and creatures flash as in 1.
**GemRB**: NPCs now show their cyan circle and hovering for the first time flashes the circle, but not as much as in Classic (not as dark/white)

**Comment by Laulajatar** [comment]
### Baldur's Gate 2

#### All levels: 
Same as in BG1

#### Feedback level 1:
**Desc**: Minimum - picked creature 
Same as in BG1

#### Feedback level 2: 
**Desc**: Low - picked creature or selected character
Same as in BG1

#### Feedback level 3: 
**Desc**: Medium - picked creature or selectable character
Same as in BG1

#### Feedback level 4:
**Desc**: High - picked creature or selectable character or targeted creature
Same as in BG1

#### Feedback level 5:
**Desc**: Higher - picked creature or selectable character or hostile creature or targeted creature (default, I think)
**Classic**: As 3, but enemies always show a red circle, not only while targeted, while friendly npcs don't show a circle.
**GemRB**: All friendly and enemy creatures show their circle always.

#### Feedback level 6: 
**Desc**: all creatures and characters 
**Classic**: All circles are shown, like BG1 level 5.
**GemRB**: Can't see a difference to 5. gem-baldur.ini does show `GUI Feedback Level = 6`




Seems to me the three main problems are

- GemRB not implementing BG2's Feedback level 5 
- GemRB not implementing the "targeted creature" setting, instead showing enemies always
- GemRB not flashing the circle on hover npc/creature if they are not already visible due to the setting

**Comment by lynxlynxlynx** [comment]
The first universal hovering issue is now tracked in #2064 and the rest have been fixed already or just now. :)
