### ISSUE TITLE
what is the purpose of GameData::ResetTables?

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1418]
This raised my eyebrows when I was working on 9d1ef2e and was previously `GameData::DelTable` with a `-1` parameter.

the issue is that we seem to want to dispose of all tables loaded by `GameData` but there are several "singleton" instances of tables that linger (see `InitActorTables` for several examples) after this call. So what is the point of this existing? To me it seems useless at best and at worst a source of unexpected behavior.

If it's not clear, the singleton instances will remain while any new references will be generated freshly from the 2da and handed out to whomever. I dont _think_ this actually causes bad behavior (unless somebody edited a 2da in the middle of the game) because I dont think there is any way to mutate a table.

if we truly need this then we probably should destroy these "singleton" references and report an error if a table has an unexpected reference count.

**Comment by lynxlynxlynx** [comment]
I think it can just be removed — it looks like the other windows workarounds with centralized memory management.
