### ISSUE TITLE
[bug] Bonus spells (42) & (62) stay in the spellbook after unequipping the item

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#142]
Bonus Wizard Spells (42) & Bonus Priest Spells (62) will stay in the spellbook after unequipping item that gives bonus. As long as bonus spells are in section of memorized spells (even if spent) creature will continue to receive the bonus. Only way of removing bonus spells is by changing the spell. If you change the spell and the bonus item is unequipp the bonus slot will disappear.

**Comment by bradallred** [comment]
I think I would prefer to behave as if the item is cursed and disallow unequipping until you erase/use a spell. Print the appropriate message too.

I always found it annoying when i would accidentally forget a spell.

**Comment by lynxlynxlynx** [comment]
It's not like level drain, where it's clear the effect will be temporary and quality of life trumps the cheese.

I think at best we can run a  confirmation popup when trying to unequip. Just as a way to prevent accidents. We could add the handful of items to itemspec.2da, a new bit and detect them that way.
