### ISSUE TITLE
 BG1/BG2: Subtitles appear even with the setting turned off

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1420]
#### Bug description
Even with the subtitle option checked off, the texts from party members saying their idle or selection dialogue gets dumped into the chat log.

#### Steps to reproduce
1. Disable subtitles
2. Stand around make a coffee
3. Check chat log

#### Expected behavior
When subtitles are turned off, they shouldn't appear in the log.

#### Screenshots
![Screenshot_2021-08-08_14-16-11](https://user-images.githubusercontent.com/68446748/128631677-d4714e3a-a3c3-4983-bf32-8487c488434a.png)
![Screenshot_2021-08-08_14-16-19](https://user-images.githubusercontent.com/68446748/128631680-fbe738cb-c2ba-42a0-8015-979067951b49.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [x] 0.8.8
(Just didn't test 0.9.0)

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Ok, so this is the "Subtitles" key (out of three possible), which we do check in DisplayStringCore. I guess it should effectively toggle DS_CONSOLE.
