### ISSUE TITLE
Write instructions for debugging in a VM 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1429]
Let's make it easier for keen windows users to help debug problems. The point is to avoid troubling them with installing a compiler and debugger, which we then have little experience with.

I've wrote the GemRB part here:
https://www.gibberlings3.net/forums/topic/33034-crash-when-spell-casting-duplicated-on-two-installs-and-crash-on-npc-leaving-area/?do=findComment&comment=297387 (and a few replies lower for debugging), but the VM choice and setup is missing. We need a short document to put on our page and later point anyone in the same situation towards it.

And the debugging part can be split off onto a separate page, since that's useful even more frequently.

**Comment by MarcelHB** [comment]
We can consider something like a Vagrant box.

**Comment by Darpaek** [comment]
Attached.

[Linux is Lame.zip](https://github.com/gemrb/gemrb/files/6985783/Linux.is.Lame.zip)

**Comment by Laulajatar** [comment]
Tried my luck with some markdown and a Kubuntu and a Xubuntu machine. 

https://pastebin.com/VxpqVUDu

**Comment by bradallred** [comment]
would it be easier to use WSL2 or no? I have no experience myself, but thats why the windows team an my work uses.

**Comment by lynxlynxlynx** [comment]
Thanks everyone, I've started editing everything together. Vagrant also sounds like a fine idea, but this is primarily a doc issue, so that's out of scope.

Brad: I don't trust it, since it's not native. I expect similar potential complications as with cygwin/mingw, while the intention is to have as few as possible differences.

**Comment by Laulajatar** [comment]
I tried to install Ubuntu in WSL2 in my W10 virtual machine (probably not the best idea, but I don't have a windows pc to use right now) but I can't get graphical applications to work. Not a huge fan of WSL2 having access to C:\ either (one rm -rf / away from disaster).

I noticed my K/Xubutnu machines were still building python2 and I had a bit of trouble getting python3 to work. `libpython3.8-dev` didn't exist, only `libpython3-dev` did (I got those requirements from the gibberlings3 forum thread a few days ago), which installs python 3.9.5.

**Comment by lynxlynxlynx** [comment]
Oh, @Darpaek actually already included also instructions for VMWare and WSL2, so that's covered. :) I've added it to the end as an "advanced user" section, so the main body can remain focused on Virtualbox.

It'll be here: https://gemrb.org/Debugging-with-a-VM.html

**Comment by Laulajatar** [comment]
A small note, `python-is-python2` and `python-is-python3` conflict, so I dropped the former, but I guess I edited that too late.. :D

**Comment by lynxlynxlynx** [comment]
I'm still making it leaner, so all suggestions are welcome. Btw, where do mountpoints end up in the vm, /media or ye olde /mnt?

**Comment by Laulajatar** [comment]
It's in `/media/sf_*/` where * is the folder name, but spaces are replaced by _.
Btw I'm not using a Ubuntu-based system myself, so especially the part about the dependencies was just copy and pray it works.

**Comment by lynxlynxlynx** [comment]
Again, thanks everyone, it's as nice and simple as I could make it. The bisection stuff is now on the dev docs page.

**Comment by rsantellan** [comment]
Hi @lynxlynxlynx I never used before git bisect (The project that I work usually have a small release cycle) and one thing that really help me was this page with the images: https://www.git-tower.com/learn/git/faq/git-bisect/ can we include an image like this https://www.git-tower.com/learn/git/faq/git-bisect/bisect-checkout-middle.png ?

**Comment by lynxlynxlynx** [comment]
I've added a link to that: https://gemrb.org/Dev-docs.html#git-bisect

We can't use the image directly, since it's not ours.
