### ISSUE TITLE
BG2: Aborting character creation with cancel causes small graphical issue 

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1431]
#### Bug description
When creating a new character, clicking on `Cancel` when it shouldn't be available causes a small graphical issue.

#### Steps to reproduce
1. Start creating a character
2. Click on Gender
3. Click on `Cancel` instead of `Back`

#### Expected behavior
`Cancel` should be greyed out and impossible to click as in 0.8.8.

#### Screenshots
![unknown](https://user-images.githubusercontent.com/68446748/129424813-332a424e-cea5-46d4-9fa8-7489f5d5a355.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [x] 0.9.0
- [ ] 0.8.8

**Comment by bradallred** [comment]
thats not a graphical issue, chargen uses more than one window

**Comment by Laulajatar** [comment]
I just built it new, but it still happens: 

![Peek 2021-08-14 02-36](https://user-images.githubusercontent.com/68446748/129429341-a6dc724d-2f30-466b-b133-61cd9e7f54a9.gif)

It's only a problem in the gender selection, afterwards that button is "Start Over"
