### ISSUE TITLE
BG2: Slightly strange behaviour regarding map markers on right click

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1434]
#### Bug description
- After right clicking on a map marker the next time you right click on the map, be it on an empty spot or another map marker, the old marker will still be selected and you'd be editing the first marker, not creating a new one/editing another.
- Even if you delete a marker, then right click again, the old text will show and selecting `done` will bring the marker right back. 
- I think this is caused by the game not "losing focus" of the last selected marker after closing the edit window. Left clicking on the map fixes this. 
- Also not related to right click, but when creating a new map marker, the text field isn't empty but says "Note" which has to be manually deleted. 

#### Steps to reproduce
1. Right click on a map marker
2. Close the menu
3. Right click on another spot

#### Expected behavior
As in 0.8.8, closing the map marker edit menu should not freeze the selected marker. 

#### Screenshots
[Made a vid](https://www.youtube.com/watch?v=5AuNgreKIZU)
At the very end I left click to unfreeze it.

#### GemRB version (check as many as you know apply)
- [x] master as of this issue
- [x] 0.9.0
- [ ] 0.8.8

**Comment by bradallred** [comment]
its not a focus problem. the `MapControl` state is manually managed by setting variables sadly

**Comment by bradallred** [comment]
what game are you trying this in? BG2 worked as I expected (tho maybe I dont understand your explanation)
