### ISSUE TITLE
BG2: Game freeze when trying to enter the temple of the bridge district 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1437]
#### Bug description
The game freeze when trying to enter the temple in the bridge district.
Pausing the execution it stops on the loop of WEDImporter.cpp +382 never reaching the line 385

![image](https://user-images.githubusercontent.com/1820598/129766930-33ab5892-431e-4a63-8e8d-04d0e36d3c5a.png)

Some data extracted with a LOT of help.
The **PLTSize** is 2147482818 
The **VerticesOffset** is 2464
The **PLTOffset** is 4136

#### Steps to reproduce
1. Go to Bridge District
2. Enter the temple
3. See error

#### Expected behavior
You enter the temple.

#### Screenshots

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [X] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by rsantellan** [comment]
The area I want to enter is ar0152

![image](https://user-images.githubusercontent.com/1820598/129769096-6b061fe2-e087-4239-9d2e-fbe3fe400ae1.png)

**Comment by bradallred** [comment]
obviously PLTSize is being calculated incorrectly leading to a negative value

**Comment by bradallred** [comment]
I actually cant reproduce this. I wonder if somehow cheating to teleport there isn't enough. I don't see how it wouldn't be tho.

**Comment by rsantellan** [comment]
> I actually cant reproduce this. I wonder if somehow cheating to teleport there isn't enough. I don't see how it wouldn't be tho.

Do you want a save game ?

**Comment by bradallred** [comment]
wont hurt, but that might just mean you have a corrupted save

**Comment by lynxlynxlynx** [comment]
WED files are not saved, so that is unlikely. It could be the area is wrong though, since some do share the same WED file. But  looking up the only temple in that district shows the area code matches the WED name.

**Comment by bradallred** [comment]
if you have mods installed, it could be the same as #1436

**Comment by bradallred** [comment]
I dont think the WED is actually the problem. none of the variables listed in OP are even close to having those values so its clear something else is happening like not clearing old data. And indeed if you teleport to that area then leave and reenter you can see the problem.

**Comment by bradallred** [comment]
actually, if you wait long enough you get inside...

**Comment by bradallred** [comment]
the hang up im seeing isnt even in WEDImporter. It's the pathfinder going crazy.

**Comment by rsantellan** [comment]
> the hang up im seeing isnt even in WEDImporter. It's the pathfinder going crazy.

I never finish the WEDImporter class, my CPU give up after a while.. Should I wait more or there is something extra I can try?

**Comment by bradallred** [comment]
Your problem seems more like not having a clean build or loading plugins from a previous build.

**Comment by rsantellan** [comment]
@bradallred I did a lot of clean builds today... I remove my build countless times and did it again... Some problems with python 2 and then I change to python 3. 
When I build the 0.9.0 tag I don't have the same problem.

**Comment by bradallred** [comment]
I understand that, but clean build means nothing about where the plugins you are loading are located or what code they were built from.

**Comment by rsantellan** [comment]
I'm here:

commit 5c9a0c78fbe199a9301c180dd0f280dc090f4d16
Author: Jaka Kranjc <lynxlupodian@users.sourceforge.net>
Date:   Tue Aug 17 16:02:09 2021 +0200

    PyString_AsString: removed unused line breaking the build

in a clean project. My plugin are there: PluginsPath=./gemrb/plugins/ so when I do rm build -rf I clean all of it

**Comment by bradallred** [comment]
well I guess upload a save then, because I've tried to repro (tho I'm on the latest master and you are not, but I doubt that matters) and I cannot, nor do the sanitizers complain to me.

**Comment by bradallred** [comment]
> > the hang up im seeing isnt even in WEDImporter. It's the pathfinder going crazy.
> 
> I never finish the WEDImporter class, my CPU give up after a while.. Should I wait more or there is something extra I can try?

The pathfinder hang up happens well before the WEDImporter. I dont know what "my CPU give up after a while" means tho.

**Comment by bradallred** [comment]
can you paste the value of `SIZEOF_INT` and `SIZE_LONG_INT` from your generated config.h? or even just your whole config.h, maybe something else in there will jump out.

**Comment by rsantellan** [comment]
I'm on Linux Mint 20 64bits
[000000035-Sansuki.tar.gz](https://github.com/gemrb/gemrb/files/7007002/000000035-Sansuki.tar.gz)
I upload the save file (It work perfect on the original.)
This is the config.h
[config.h.tar.gz](https://github.com/gemrb/gemrb/files/7007006/config.h.tar.gz)
**My CPU give up after a while** is that the system freeze and could quit the program making me to restart the machine :(
I will start from the last known good point and going forward in the history.

**Comment by bradallred** [comment]
> I'm on Linux Mint 20 64bits

this isn't an architecture. what kind of CPU?

**Comment by bradallred** [comment]
you have `#define PLUGIN_DIR "/usr/local/lib/gemrb/plugins"` in your config.h. is there anything in that directory?

the size of types is the same as me, so that cant be a cause. So unless your CPU is BE I'm out of ideas.

**Comment by rsantellan** [comment]
> > I'm on Linux Mint 20 64bits
> 
> this isn't an architecture. what kind of CPU?

Sorry... More details.
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           24
Model name:                      AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx
Stepping:                        1
Frequency boost:                 enabled
CPU MHz:                         1253.958
CPU max MHz:                     2100,0000
CPU min MHz:                     1400,0000
BogoMIPS:                        4192.31
Virtualization:                  AMD-V
L1d cache:                       128 KiB
L1i cache:                       256 KiB
L2 cache:                        2 MiB
L3 cache:                        4 MiB
```

**Comment by rsantellan** [comment]
> you have `#define PLUGIN_DIR "/usr/local/lib/gemrb/plugins"` in your config.h. is there anything in that directory?
> 
> the size of types is the same as me, so that cant be a cause. So unless your CPU is BE I'm out of ideas.

No nothing in /usr/local/lib/gemrb/plugins

**Comment by bradallred** [comment]
its not an arch problem, i'm also x86_64

grasping at stars at this point, but you could try changing `VERSION_GEMRB` in globals.h

**Comment by lynxlynxlynx** [comment]
I can reproduce this easily. Will go check the data.

**Comment by rsantellan** [comment]
I just found out that when running on Visual Code all the cmake config are overriden making it use only the defaults so it is using SDL1.2 and python 2, don't know if that helps. 
I'm trying to figure out how to change it

**Comment by lynxlynxlynx** [comment]
The data looks fine, we're just assuming ordering of the offsets. WED unfortunately doesn't have a count field to make this clean, but this files offset values actually follows the format — it's a bit odd that most don't.

**Comment by bradallred** [comment]
I still dont understand how my WED is different 🤷

**Comment by lynxlynxlynx** [comment]
You didn't reply in that other bug, but I suspect yours is vanilla. The fixpack patches it to fix green water.
