### ISSUE TITLE
BG2: Can enter a house without party, but can't leave without party

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1438]
#### Bug description
There is a certain house in the slums district of Baldur's Gate that is possible to enter without having the party present, but trying to leave presents me with "You must gather your party before venturing forth". 

#### Steps to reproduce
1. Enter the house alone
2. Try to leave

#### Expected behavior
As much as I like that line, I shouldn't be able to enter the house without my party (as in the original). 

#### Screenshots
![Screenshot_2021-08-17_23-05-37](https://user-images.githubusercontent.com/68446748/129802307-2e9ba31b-c622-43d5-9e15-aa3f048dee6a.png)
![Screenshot_2021-08-17_23-21-25](https://user-images.githubusercontent.com/68446748/129802329-ac155064-5fbb-4142-9f24-48a2bd8c4c39.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [x] 0.8.8

**Comment by lynxlynxlynx** [comment]
I can't reproduce (can't enter or exit without the whole party), so it looks like a BGT bug. I don't think anything relevant changed in these few days, but please retry, preferably with a fresh Slums (eg. teleport there from CI for example).

**Comment by Laulajatar** [comment]
I wasn't testing this in BGT, it was vanilla BG2, no mods (not even any fixes, if that is relevant - the original game version I tested against also had no fixes installed). 
How would I teleport there?

**Comment by lynxlynxlynx** [comment]
with mta("arXXXX")
https://gemrb.org/Cheats.html#pop-up-console

a game without the fixpack is not supported, though it doesn't sound like something for the fixpack.

**Comment by Laulajatar** [comment]
Is just the core fixes enough, or should I install all of it? 
`~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #0 // BG2 Fixpack - Core Fixes: v13`

I started a new game with the fixpack and it worked as intended. 
It's a bit weird because I was using the same save on the same, unmodded game on Windows (where it also worked), but doesn't seem to be a problem if it works with the fixpack.

**Comment by lynxlynxlynx** [comment]
Core is enough, though some beta fixes are also cool and will become part of core with the next release.

From the docs:
> Several areas in the game can only be accessed with the full party in tow. However, in many of these cases the flags only worked one way, or multiple entrances to areas were flagged differently from one another. (An example: a single party member could enter Coran's cabin in the woods, but only the full party could leave.) The flags were reviewed and adjusted to be consistent. (ar0300.are, ar0400.are, ar0415.are, ar0500.are, ar0504.are, ar0505.are, ar2000.are, ar2207.are, ar2600.are, ar2603.are, ar2902.are)
