### ISSUE TITLE
Inventory scrollbar at bottom in store

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1439]
#### Bug description
In store, inventory scrollbar is at the bottom, shouldn't it be at the top by default?

#### Screenshots
![image](https://user-images.githubusercontent.com/55502325/129840559-3104964d-f5ba-4e65-8644-8ad632023a9a.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by FrElvire** [comment]
An every action reset scrollbar to bottom : 
- change character and sellers scrollbar reset
- display properties of an object, scrollbar reset

**Comment by lynxlynxlynx** [comment]
Needs testing in the originals for the starting position, while the annoying resetting should be fixed nonetheless.

**Comment by bradallred** [comment]
9d7b703?

**Comment by lynxlynxlynx** [comment]
@FrElvire is it fixed now?

**Comment by bradallred** [comment]
I was asking if that is what broke it

**Comment by FrElvire** [comment]
yes it's this commit. With ab16b86 it's ok : scrollbar is by default at top and is not reset all the time

**Comment by FrElvire** [comment]
The fix seem to cover only scrollbar position and not it's resetting (by example the sellers scrollbar when selecting another character).

**Comment by bradallred** [comment]
open a new issue please
