### ISSUE TITLE
Pathfinder(?) seems to keep trying find a way and just slow down the game

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1441]
#### Bug description
In some circumstances the pathfinder seems to keep trying find a way and just slow down the game. When loading the included save this line keep reappearing : 

```
[FindPath/DEBUG]: Pathing failed for Monk
[FindPath/DEBUG]: s = (1800, 978), d = (1299, 663), caller = Monk, dist = 0, size = 2
```

the FPS stay around 20 and the game is sluggish (even with a relative powerful processor).

Another thing : even if the game is sluggish, no processor core is at 100% (~55% on one of the core), nor gpu (25% on Render/3d engine). So there is some bottleneck somewhere other than the cpu in this case, is this expected ?

[000000043-path cpu.zip](https://github.com/gemrb/gemrb/files/7011838/000000043-path.cpu.zip)

#### Steps to reproduce
1. Load save in TOB

#### Expected behavior
If no path can be found, maybe stop trying to find one ?

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment]
to would be worth knowing if this happens on 0.9.0 or if it's a recent regression.

**Comment by FrElvire** [comment]
On 0.9.0

```
[FindPath/DEBUG]: Pathing failed for Monk
[FindPath/DEBUG]: s = (1800, 978), d = (1299, 663), caller = Monk, dist = 0, size = 2
```
keep reappearing so no change


But yes there is a regression on performance as FPS stay to ~28, the game feel not sluggish and cpu usage is lower.

just a note : this test was made on another computer with lower spec, so on this computer : 
- 0.9.0 : ~28fps, not sluggish, 15-30% cpu usage
- master : ~16fps, sluggish, 50-80% cpu usage

**Comment by bradallred** [comment]
do you think you can do a bisect between 0.9.0 and master to find where the performance regression was introduced?

**Comment by bradallred** [comment]
its definitely not drawing related. if you pause the game the hitching stops. does seem like a likely pathfinder issue then.

**Comment by bradallred** [comment]
I think I see what is happening

**Comment by FrElvire** [comment]
If bisect is always needed I can do it (certainly this weekend)

**Comment by bradallred** [comment]
not necessary I think. the profiler exposes it pretty clearly.

**Comment by FrElvire** [comment]
what is the cause ?

**Comment by bradallred** [comment]
the gist is that we are iterating the search map (and other maps) from the beginning rather than just jumping to the desired position.

**Comment by bradallred** [comment]
I'll reopen this since the monk pathfinding issue still persists, but the performance regression appears to be gone for me.

**Comment by lynxlynxlynx** [comment]
The remainder is basically #1040.
