### ISSUE TITLE
 [BG2] Saves can be overwritten

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1448]
#### Bug description
Since SOA and TOB saves are in the same directory, if you make a save with the same name and same number between the 2 games, this save will overwrite the save of the other game.

I know there is very little risk but it' possible....

#### Steps to reproduce
1. take the game with the least saves number
2. find next save number (N+1) on the other game (with the most saves)
3. in this game (with the most saves) make a new save with the same name of the other game (with the least saves number) of number N+1
4. save get overwritten

I know t's not very clear :( ....

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0 
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
I guess what happens is that when we are determining the new filename, we're ignoring other expansion version saves (you can see this in the log when opening the window) and thus don't take them into account, possibly coliding.
