### ISSUE TITLE
Inventory scrollbar reset in store 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1449]
#### Bug description
In store every action reset scrollbar position, by example :

- change character and sellers scrollbar reset
- display properties of an object, scrollbar reset

Problem introduced in 9d7b703 (see #1439 for more detail).

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
I suspect the constant re-associations are to blame. Visible in 99831bd7 already.

**Comment by lynxlynxlynx** [comment]
Probably the same reason that dumping items to the ground also looks like it doesn't work, since they get scrolled out of view.

**Comment by lynxlynxlynx** [comment]
Ok, so there is no reset for looking at the item description any more, but there is for changing characters. Which I just have to push the fix for.
