### ISSUE TITLE
BG2: Settings not displayed right in the options menu

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1451]
#### Bug description
The setting for "Dither Always" does not show correctly in the menu. 

Every time the menu is opened, the dot will be lit, no matter what the real setting is. If it's turned off, you need to click twice - disable, then enable - for it to really enable it. 

**Edit**: I am an idiot, I was so busy testing the Dither settings I didn't think to check for other settings. It seems to affect all settings. 
I believe it shows the default settings when the menu is opened, no matter what the settings are actually set to.

#### Steps to reproduce
1. Open menu, disable Dither Always
2. Open menu again

#### Expected behavior
The glowing dot should show the real setting status.

#### Screenshots
![Peek 2021-08-22 22-31](https://user-images.githubusercontent.com/68446748/130369570-b69835c0-442f-4d7c-b63c-0d2919fb4a57.gif)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [x] first appeared in commit 9d7b70341196ed02600dc98d7de40fe236ea3648
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
That commit's been causing a lot of trouble. :(
