### ISSUE TITLE
BG2: Levelup icon broken in Python3 build

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1454]
#### Bug description
The little + on the portraits of characters who are ready to level up is not displayed right when built with python3. 
~~Not sure if it only affects BG2, don't have a save for BG1 with a character ready to level up.~~ Would BG1 even have this icon, I can't remember.

#### Screenshots
Python 3
![Screenshot_2021-08-22_23-57-26](https://user-images.githubusercontent.com/68446748/130371477-acb77457-2a63-422f-9fba-21e86aad4875.png)

Python 2
![Screenshot_2021-08-23_00-03-08](https://user-images.githubusercontent.com/68446748/130371481-ea843118-a218-45bc-b32b-30541ec84e8f.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Looks like the padding is broken; two spaces into 4 chars and then the icon itself is off the screen.
