### ISSUE TITLE
 BG2: Script assignment doesn't work right

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1458]
#### Bug description
Trying to assign some scripts to party members, the game doesn't pick the one I selected, but a different one. 

#### Steps to reproduce
1. Assign a script
2. Close menu
3. Open menu again

#### Expected behavior
Use the script I selected. 

#### Screenshots
[Video.](https://www.youtube.com/watch?v=tGuMCXT5Kg8)
Video is BGT, but unmodded BG2 (except for fixpack) behaves the same. 

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0 - not here
- [ ] 0.8.8 - not here

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Should be the same SetVarAssoc regression as everything else.

**Comment by bradallred** [comment]
no doubt, but its good to keep opening issues as the fix (not constantly rebinding on refresh) needs to be applied to each broken script.

**Comment by bradallred** [comment]
we we were wrong it seems :)

the problem is that the 2da order doesnt match the order of the `OrderedDict` we create in `OpenScriptWindow`. I'm assuming the regression occurred as part of the Python 3 update.

**Comment by lynxlynxlynx** [comment]
Seems to work fine here, but there are problems with display, as per the video. If you look at the assigned script, that's actually fine. Investigating ...
