### ISSUE TITLE
 Malavon doing weird things in IWD

### ISSUE THREAD

**Issue by dagdha2002** [gemrb/gemrb#1459]
#### Bug description
The problem is in Icewind Dale, with Heart of Winter and Trails of Luremaster. 

I have arrived to the final chapter and I have to confront Malavon in its dome, in the artisan district in lower dorn area.
The correct sequence of things are: I enter to the dome and confront Malavon with a pair of Iron golems. Is a tough fight, but when you finish with him, you discover that he was a simulacrum and then the real one attacks you with a lot of teleports along all the dome, but at last you catch him.
But my sequence is: I enter the dome and the first that confront me is the real Malavon and talks to me as if I already defeated the simulacrum. Then I can defeat the simulacrum, but I can catch the real Malavon because he is invisible or somehow.
He is still in the area, because he is launching spells, but I´m completely unable to catch him. Invisibility purge doesn´t work and no matter the time I wait, he remains invisible.

I have attached two save files: In Auto save one, you can enter for first time to the dome. Once inside, you have two kill two umber hulks and the turn to the right. In that moment, the real Malavon will confront you, always invisible. I t one I have already killed the simulacrum just in case it will trigger some response that will let the real Malavon to turn visible, but with no result: If you mole along the area, you can see the spell effects, but no Malavon.

The problem was detected playing in my PS Vita, that uses version 0.88, but the problem persists in my PC using version 0.9.
I expect that this will be useful. Thanks for all your work.
[000000009-t.zip](https://github.com/gemrb/gemrb/files/7039811/000000009-t.zip)
[000000000-Auto-Save.zip](https://github.com/gemrb/gemrb/files/7039812/000000000-Auto-Save.zip)

Also, I have installed some mods. This is the WeiDU log:

```
// Log of Currently Installed WeiDU Mods
// The top of the file is the 'oldest' mod
// ~TP2_File~ #language_number #component_number // [Subcomponent Name -> ] Component Name [ : Version]
~DDRAWFIX/DDRAWFIX.TP2~ #0 #2 // DDrawFix -> Use WineD3D's DDraw Library: v1.0
~1PP/1PP.TP2~ #0 #101 // 1ppv4: Core paperdolls (main component): v4.2.0
~1PP/1PP.TP2~ #0 #103 // 1ppv4: Extended palette entries -> Full install (recommended): v4.2.0
~1PP/1PP.TP2~ #0 #105 // 1ppv4: Avatar fixes: v4.2.0
~1PP/1PP.TP2~ #0 #113 // 1ppv4: Smart Avatar & Armour Switching: v4.2.0
~1PP/1PP.TP2~ #0 #200 // 1ppv4: Core content patches: v4.2.0
~1PP/1PP.TP2~ #0 #203 // 1ppv4: Restored flame sword animations: v4.2.0
~1PP/1PP.TP2~ #0 #206 // 1ppv4: Additional Shield Animations (core): v4.2.0
~1PP/1PP.TP2~ #0 #207 // 1ppv4: Wizards' Staves (core): v4.2.0
~1PP/1PP.TP2~ #0 #208 // 1ppv4: Additional Helmet Animations (core): v4.2.0
~1PP/1PP.TP2~ #0 #210 // 1ppv4: Increased paperdoll object variety (core): v4.2.0
~1PP/1PP.TP2~ #0 #400 // 1ppv4: Core updates and item patches: v4.2.0
~1PP/1PP.TP2~ #0 #301 // 1ppv4: Miscellaneous content fixes: v4.2.0
~AB.TP2~ #0 #0 // Auril's Bane Core Files
~AB.TP2~ #0 #5 // Level 40 Rules Pack
~AB.TP2~ #0 #7 // Harder Yxunomei
~IWDFIXPACK/SETUP-IWDFIXPACK.TP2~ #0 #0 // Assorted Fixes: v6
~IWDFIXPACK/SETUP-IWDFIXPACK.TP2~ #0 #100 // Game Text Update: v6
~UB_IWD/SETUP-UB_IWD.TP2~ #0 #100 // Malavon's Golems: v8
~UB_IWD/SETUP-UB_IWD.TP2~ #0 #200 // Expanded Guello/Beorn Quest: v8
~UB_IWD/SETUP-UB_IWD.TP2~ #0 #300 // Marketh's Ring: v8
~UB_IWD/SETUP-UB_IWD.TP2~ #0 #400 // Presio's Duel: v8
~UB_IWD/SETUP-UB_IWD.TP2~ #0 #500 // Orrick's Rhino Beetle Shield: v8
~UB_IWD/SETUP-UB_IWD.TP2~ #0 #600 // The High Baptist's Flock: v8
~UB_IWD/SETUP-UB_IWD.TP2~ #0 #1500 // Minor Item Restorations: v8
~UB_IWD/SETUP-UB_IWD.TP2~ #0 #2000 // Restored Random Drops: v8
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #110 // Icon Improvements: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #170 // Unique Icons: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #180 // Unique Containers -> Fixes only: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #200 // Remove Blur Effect from Items, e.g. Cloack of Displacement: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #2010 // Separate Resist Fire/Cold Icon into Separate Icons (Angel): v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #1080 // Add Bags of Holding: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #1140 // Gems and Potions Require Identification -> Gems and potions: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #1300 // Make Heart of Winter accessible at any level: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #2100 // Allow Thieving and Stealth in Heavy Armor: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #2120 // Allow Arcane Spellcasting in Heavy Armor: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #2152 // Wear Multiple Protection Items -> Allow Armor Plus One Protection Item (Angel): v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #2192 // Limit Ability of Storekeepers to Identify Items -> Hybrid of Both Methods: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #2200 // Multi-Class Grandmastery (Weimer): v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #2210 // Change Grandmastery Bonuses -> True Grandmastery (Baldurdash): v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #2312 // Add Save Penalties for Spells Cast by High-Level Casters (BETA) -> Arcane & Divine Magic: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #3250 // Never lose access to Orrick the Gray's trade goods: v9
```

**Comment by lynxlynxlynx** [comment]
The battle went fine for me, so here's a save you can use to continue afterwards:
[after-save.zip](https://github.com/gemrb/gemrb/files/7040154/after-save.zip)

**Comment by dagdha2002** [comment]
Thank you very much! So the problem was in the mods?

**Comment by lynxlynxlynx** [comment]
I doubt it, more likely it has been fixed since the release.
