### ISSUE TITLE
 BG2: Tooltip info when hovering over 2 particular game settings is swapped

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1463]
#### Bug description
Hovering over the icons/selection dots for Auto Pause: Spell Cast and Auto Pause: Trap Found is swapped. The text when hovering over the written text is correct. 

#### Steps to reproduce
1. Move mouse over the glowy or non glowy dot

#### Expected behavior
Both icons should show the right tooltip info when hovering.

#### Screenshots
![Screenshot_2021-08-26_00-58-11](https://user-images.githubusercontent.com/68446748/130875813-10e02d4c-ed32-46fd-abf8-a6ad0e4032ab.png)
![Screenshot_2021-08-26_00-58-08](https://user-images.githubusercontent.com/68446748/130875821-af1838a8-c0e7-4eb9-95a9-ddfe0065b4c5.png)

#### Ge1mRB version (check as many as you know apply)
- [x] master as of this issue
- [x] 0.9.0
- [x] 0.8.8 (well, you have to click, but)

**Comment by lynxlynxlynx** [comment]
Fixed the GUI, but didn't synchronise the internal bit values. Too much hassle for something only few could notice (if migrating existing games) and can easily fix themselves.
