### ISSUE TITLE
IWD: Hidden thiefs remain invisible trying to attack 

### ISSUE THREAD

**Issue by dagdha2002** [gemrb/gemrb#1464]
#### Bug description

The problem is in Icewind Dale, with Heart of Winter and Trails of Luremaster.

At entering in AR8006 some shadowed thieves must attacks the party. The bug is that you can´t see the thieves even if they attack you. The game log tell that the thieves are attacking one of the party members, but they remain invisible and doing no damage. 

I attach a save file in AR8006, you can note the thieves attacking in the game log.
Probably all of this is mod related, is not the first problem that I have with invisible enemies.

The problem was detected playing in my PS Vita, that uses version 0.88, but the problem persists in my PC using version 0.9.

I have installed some mods. #1459
[000000076-Bug2.zip](https://github.com/gemrb/gemrb/files/7060525/000000076-Bug2.zip)

**Comment by dagdha2002** [comment]
Sorry for the delay in answering. Thanks, I´ve used ctrl-shift-y and it seems to work. At least if I change the area and then return to AR8006 there are no more thieves attacks registered in the game log. But we still have no corpses...

**Comment by lynxlynxlynx** [comment]
That's because they're hidden by script. And they may have gotten chunked by the cheat damage anyway.
