### ISSUE TITLE
BG2: A body of green water in small teeth pass  

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1466]
#### Bug description
One body of water in ar1700 is green. 

#### Steps to reproduce
1. mta("ar1700")

#### Expected behavior
Don't be green. 

#### Screenshots
![Screenshot_2021-08-26_23-43-42](https://user-images.githubusercontent.com/68446748/131045591-a211ec43-29af-4ed1-bf63-75a141620547.png)
![Screenshot_2021-08-26_23-50-40](https://user-images.githubusercontent.com/68446748/131045599-1d356e40-507b-4e82-94de-244f63262932.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [x] 0.9.0
- [ ] 0.8.8 not here

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment]
this is definitely a data bug. I can see clearly the there are 2 green values in the sprite. we have the color at index 0 (the color key) has the expected value of 0,255,0. the color at index 1 is 4,226,4. I do not know how the original must have handled this. Its impossible to set 2 color keys so we would have to do some pixel editing on load.

I think more likely, in the original engine, color index 1 was also ignored for these tiles. Similar to the "shadow color" issue in #402

**Comment by bradallred** [comment]
nope, that cant be right. that only mostly fixes it. there is at least one more color and it is at index 105, so it's not a heuristic based on index. must be some kind of color matching, but I'm not sure what the algorithm should look like.
