### ISSUE TITLE
[bug] investigate non-deterministic false positives on Dead() checks

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#147]
It's all here: https://github.com/gemrb/gemrb/commit/d55919bffe052983e3a6df31f42d5d6cc77a41bb#commitcomment-28380692

Basically:
- the second param to Schedule doesn't make sense as a bool / how it's used; no matter the game
- Branston's plot should still work
- Gallaway TD (AR1102) patrons shouldn't turn hostile for no reason

**Comment by cygarniczka** [comment]
In BG2 `SetGlobal("SPRITE_IS_DEADFoo","GLOBAL",0)` can rest living actor state to not dead. Where `Foo` stands for the script name of the given creature. 
<summary>BG2 Dead state as far as I remember it's fixed</summary>
<details>
That way I managed to fix Xzar and Monty dialogue that was not triggering. Niemen (Zhent in Sorcerous Sundries) considered Xzar and Monty dead state to be 1 after resetting it back to 0 Xzar and Monty replies kicked in.
Mod Jarl's Adventure Pack and BG1 NPC Project edited Nieman dialogue where Xzar and Monty dialogue intejection come from. As far as I remember dead state is fixed for BG2.
</details>

**Comment by lynxlynxlynx** [comment]
Yeah, death vars are only a part of it and their number varies between the games.

**Comment by lynxlynxlynx** [comment]
It fixed it for me in a save from the shop that in recent testing had everyone turn hostile. Nice side result from investigating something else.
