### ISSUE TITLE
 BG2: Huge FPS drops when fighting Ankhegs

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1470]
#### Bug description
When fighting Ankhegs, the game sometimes drops to very low fps numbers. My guess is that it is because of pathfinding. The Ankhegs seem to burrow too close to a party member, then get stuck on them when trying to move. 
Selecting my close party members and Ctrl-J them away instantly returns to 30 fps.

I noticed that on the original, they don't seem to come so close so often, instead using mostly ranged attacks. 

#### Steps to reproduce
1. Fight some Ankhegs

#### Expected behavior
Add a clear and concise description of what you expected to happen.

#### Screenshots
[Video](https://www.youtube.com/watch?v=DbIwj-NSQfQ).
The video is BGT, but I also had it happen on BG2. 
Edit: Great, the console output is useless because I was scrolled up. 

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Yeah, I can usually see it when they get up close and personal, eg. in the center of ar1200. Not clear yet what gives, but it doesn't look like they're trying to repath like mad.

And we have several animation problems — some coloring, looks like the emerge/unemerge stances don't work and even attacking seemed still.

**Comment by lynxlynxlynx** [comment]
It appears to be GameScript::RunAwayFrom from ANKHEG.bcs causing a lot of searchmap lookups:
```
IF
	See(NearestEnemyOf(Myself))
	Range(NearestEnemyOf(Myself),5)
	Delay(12)
THEN
	RESPONSE #40
		SelectWeaponAbility(SLOT_WEAPON0,0)
		RunAwayFrom(NearestEnemyOf(Myself),45)
		AttackReevaluate(NearestEnemyOf(Myself),15)
	RESPONSE #60
		SelectWeaponAbility(SLOT_WEAPON1,0)
		AttackReevaluate(NearestEnemyOf(Myself),15)
END
```
Shows a bug in the function, as we keep calling the internal run-awayer with increasingly small distances. 

And something wipes their weapons (ankheg1/2).

**Comment by lynxlynxlynx** [comment]
It's practically gone now, but I also noticed sometimes pathing fails needlessly. Will open fresh bugs.
