### ISSUE TITLE
BG1/BG2: Game should not attempt to autosave when leaving a waylaid by enemies area 

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1472]
#### Bug description
You can't save in those areas, so every time you leave one, the chat will show the message that you can't save. 

Also the message shown, both when trying to save in a waylaid area and when leaving it and the autosave failed is `You cannot save at this time...Monsters are about.` but it should be `You cannot save at this time.` (I realize that this is probably the least important issue of all time :D)

#### Steps to reproduce
1. Get ambushed
2. Kill ambush
3. Leave map

#### Expected behavior
Don't attempt to autosave when leaving a waylaid by enemies map.

#### Screenshots
![GemRB_2021-08-28_11-56-17](https://user-images.githubusercontent.com/68446748/131214238-095ae284-e9c8-4aba-bbab-7bdea1ee08a1.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
It's all in the CanSave function. So:
- it shouldn't print anything when triggered by autosaving in ambush areas (or we should skip autosaving earlier)
- perhaps the message is wrong, but this is also on a timer, so until the combat times out after its end, the monster one is correct

**Comment by Laulajatar** [comment]
Directly after combat, the message is different:
`You cannot save during combat.`

I was waiting for that message to time out.
