### ISSUE TITLE
BG1/BG2: Certain resolution draws the waylaid by enemies area under interface to the sides

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1473]
#### Bug description

My window is 1280 wide, and on waylaid by enemies area, I cannot leave the map to the sides without hiding the interface parts. When an area is larger, and you scroll to the side, the map will end before the portrait/menu bars like this, so you can touch the edge of map to travel:
![unknown-1](https://user-images.githubusercontent.com/68446748/131215179-9e93770a-30a3-4bdd-8bec-96a8f9e82f7f.png)

One example area is `ar0046` in BG2, but I've had it in every single waylaid by enemies area so far (BG1, BG2, BG2 with BGT). 
More area numbers: 
- ar5900 (BG1)
- ar5400 (BGT)
- ar4800 (BGT)
- ar4801 (BGT)
- ar5100 (BGT)

This seems to only happen if the window width matches the width of the area map or is slightly larger. Even setting my width to 1279 "fixes" it because I need to scroll side to side for that pixel. 

I assume it's the same for height of the map, but my screen doesn't have a high enough vertical resolution to test this :D

![unknown-2](https://user-images.githubusercontent.com/68446748/131215589-e5898b7a-8dca-434d-8185-cd7bf4682727.png)

My settings: 

```
#Screen width
Width=1280

#Screen height
Height=900
```

#### Steps to reproduce
1. Set resolution to 1280x900
2. Get waylaid by enemies

#### Expected behavior
I believe the area should be able to be scrolled side to side/around not only if the window width is smaller than the map width, but if the (window width - interface width) is smaller than the map width. 

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment]
this should be easily addressed in `GameControl::MoveViewportTo`
