### ISSUE TITLE
"Camera" bugging out

### ISSUE THREAD

**Issue by Laulajatar** [gemrb/gemrb#1474]
#### Bug description
I'm not really sure how to best describe this, so I attached a video. 
Basically when opening the area map and double clicking on the top/right border to move the camera view there, panning with holding the middle mouse button or using keyboard keys bugs out until the map is moved at least once by moving the mouse cursor to the edge of the window (or opening the map and selecting a spot that doesn't touch the edge).

In this video, I center the camera by double clicking, then I attempt to pan around the map, both with middle mouse button and arrow keys. 
This seems to only happen on the top and left border of the map. 

[Video in question](https://www.youtube.com/watch?v=TIVlFU_itwk).

I believe it affects all games, can confirm in BG1, BG2 and IWD.
This also does not seem to be map specific.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [x] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment]
ah, the problem is that we allow setting a negative goal point, but of course can never reach it
