### ISSUE TITLE
Icewind Dale: Boneguard skeleton duplicated and unable to move AR8012 

### ISSUE THREAD

**Issue by dagdha2002** [gemrb/gemrb#1475]
Bug description

The problem is in Icewind Dale, with Heart of Winter and Trails of Luremaster.

Another weird bug, probably mod related. In AR8012, the Black Temple, there are lots of boneguard skeleton. In my game most of them are unable to move from their start points, they remain still but can attack if I approach to their range. Some of them are duplicated, there are two of them occupying the same point, unable to move. In a normal game, boneguard skeleton are free to move and attack on sight.
I have attached one save game, before to enter AR8012. Once you enter to the area, there many boneguard skeleton.
The problem was detected playing in my PS Vita, that uses version 0.88, but the problem persists in my PC using version 0.9.
I expect that this will be useful. Thanks for all your work.
I have installed some mods. #1459
[000000077-Bug3.zip](https://github.com/gemrb/gemrb/files/7077674/000000077-Bug3.zip)

**Comment by lynxlynxlynx** [comment]
Hmm, sounds like a spawning issue. We'll need to check how the area ini file is used there and how the ARE file actors are placed, if any, and if any interfere by default. The same if they're spawned by area spawn groups or scripts.

**Comment by dagdha2002** [comment]
Are you going to need any files from my installation? If so, please tell me and I´ll attach them as soon as possible.

**Comment by lynxlynxlynx** [comment]
Probably not, first we need to check if the same thing happens in vanilla. We had a similar bug already, but I think that one was fixed for 0.8.8 already.

**Comment by dagdha2002** [comment]
More info about this issue: If I load a save game in AR8012, all Boneguard skeletons respawn. Most of them have now normal movement and attack as normal, only a few remain still, still duplicated.
I have checked the area with nearinfinity and it seems to me that they are duplicated, but as far as I know, they wouldn´t respawn.

**Comment by lynxlynxlynx** [comment]
When I teleport there, everyone moves as expected. So I think this is another thing that's already fixed.

Perhaps try the latest linux build in a virtual machine? You can find instructions here:
https://gemrb.org/Debugging-with-a-VM.html
Only the first part is important, as you can download the prebuild binaries to test gemrb.

**Comment by dagdha2002** [comment]
Thanks for check and for your suggestion. It´s not very difficult to sort out the bug, so I prefer to stay at the moment in 0.88 in my PS Vita, just to help Northfear with its work in the port.
