### ISSUE TITLE
Icewind Dale: Crashing while entering at AR8009 

### ISSUE THREAD

**Issue by dagdha2002** [gemrb/gemrb#1479]
#### Bug description

The game crash while trying to enter at AR8009, no matter the way I try (It has two different access in game). Command MoveToArea does not work either with this AR. Strange enough, it does not work with any area, but previously the command worked right. Using MoveToAre does not crash the game, a loading screen appears, but my party still remain is same area.
I have attached one save game, before to enter AR8009 using one of the two access that you can use in the game-
The problem was detected playing in my PC, that uses version 0.9, but the problem persists in my PS Vita using version 0.88.
I expect that this will be useful. Thanks for all your work.
I have installed some mods. #1459
[000000078-Bug4.zip](https://github.com/gemrb/gemrb/files/7111538/000000078-Bug4.zip)

GemRB version (check as many as you know apply)
- [ ] master as of this issue
- [ ] 0.9.0
- [x] 0.8.8

**Comment by bradallred** [comment]
I definitely cant reproduce this.

as for the console command, sounds like you are trying areas that don't exist. maybe a case sensitivity issue.

**Comment by dagdha2002** [comment]
Sorry, but I don´t know how to post a backtrace, but I´ll gladly do if you can explain me an easy way to do it. As for the areas, I have been trying code areas listed in IWD, or at least they appear in nearinfinity. I´ll try again later, maybe I´m doing something wrong...

**Comment by lynxlynxlynx** [comment]
I tried mta-ing several times from Lonelywood and it worked fine. This area has umber hulks though, so you're hitting the same fixed bug as with Malavon, if you were there before.

**Comment by dagdha2002** [comment]
Thanks for check the problem. Maybe all this bugs appear because I´m playing in my PS Vita with version 0.88...

**Comment by lynxlynxlynx** [comment]
I doubt it's vita-specific, but there were some fixes after the release, so who knows.
