### ISSUE TITLE
Black background on map 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1483]
#### Bug description
After pulling the latest master I see all black in the background of the characters.
Doing some bisect I found that the problem begins at 2f0c3ee

#### Steps to reproduce
1. Open any save file
2. See error

#### Expected behavior
The background has colors.

#### Screenshots
Bad one:
![image](https://user-images.githubusercontent.com/1820598/133713716-c8b8a627-b956-4c45-9533-e786e39ef601.png)
Correct one:
![image](https://user-images.githubusercontent.com/1820598/133713728-e915f65c-490d-4fb5-9610-4fe6ffbbcc5e.png)

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment]
which area is this?

**Comment by rsantellan** [comment]
Hi @bradallred is Umar Hill.
![image](https://user-images.githubusercontent.com/1820598/133714213-bfe09d60-5fea-4d05-9def-f13f7baf3f5e.png)
Pressing the x don't show me nothing but according to here: [Fandom](https://baldursgate.fandom.com/wiki/Umar_Hills) is AR1100
I will do the linking to the commit next time 2f0c3ee (Didn't know you can do that so easy.)

**Comment by bradallred** [comment]
I cant see a problem. what happens if you do ctrl+7?

**Comment by bradallred** [comment]
if you're sure it was 2f0c3ee you can try:

diff```
for (Color& c : pal->col) {
 	std::swap(c.b, c.r); // argb format
+     c.a = c.a ? c.a : 255; // alpha is unused by the originals but SDL will happily use it
 }
```

**Comment by rsantellan** [comment]
> I cant see a problem. what happens if you do ctrl+7? To me it looks like the fog is inverted, tho that draws above everything else so IDK how that happens.

This don't show anything

https://user-images.githubusercontent.com/1820598/133715582-e95ee962-3e94-4184-af1e-c41550aba25e.mp4

Will try the line you say..

**Comment by rsantellan** [comment]
> if you're sure it was [2f0c3ee](https://github.com/gemrb/gemrb/commit/2f0c3ee6a600e99c86bb731adf4a924babdd859b) you can try:
> 
> ```diff
> for (Color& c : pal->col) {
>  	std::swap(c.b, c.r); // argb format
> + 	c.a = c.a ? c.a : 255; // alpha is unused by the originals but SDL will happily use it
>  }
> ```

This do the trick!
![image](https://user-images.githubusercontent.com/1820598/133715863-f2a7632e-80b3-40f2-9780-972f4f7a7bca.png)
Now is back to normal.
