### ISSUE TITLE
 Icewind Dale Trials of Luremaster: Quest enemies don´t spawn

### ISSUE THREAD

**Issue by dagdha2002** [gemrb/gemrb#1489]
Bug description

The quest enemies don´t spawn in AR9707 after speaking with the spectral figure (Luremaster). The quest consists in figth with some monsters, and after that, the spectral figure must appear again to give me a scroll and the XP points (120000). There is the same problem in AR9703, enemies don´t spawn and I´m unable to earn the XP points and the scroll.
I have attached one save game, before to enter AR9707.
The problem was detected playing in my PS Vita, that uses version 0.8.8, but the problem persists in my PC using version 0.9.0.
I expect that this will be useful. Thanks for all your work.
I have installed some mods. #1459

[000000081-Bug6.zip](https://github.com/gemrb/gemrb/files/7270282/000000081-Bug6.zip)
GemRB version (check as many as you know apply)

 master as of this issue
 0.9.0
 0.8.8

**Comment by lynxlynxlynx** [comment]
Hmm, he uses a wand on himself, but the main baddies are spawned directly via cutscene seSpwnH. Perhaps a ClearActions regression, a UseItem bug or something else. Can't test right now.

**Comment by lynxlynxlynx** [comment]
Now the problem is different, the spawn is successful, but he immediately finishes the task, before you really get a chance to fight.

**Comment by dagdha2002** [comment]
Sorry I know that this is closed, but I´ve been a bit disconnected. Thanks to take a look on this. If it´s of any help, in the last fight the Luremaster has to attack with the help of some falling heroes. For me, all these people didn´t spawn at all, only the Luremaster. If you consider that this is worth of open a new issue I´ll do asap.

**Comment by lynxlynxlynx** [comment]
If it still happens with the latest code, then yeah, of course I want to know about it. If it's a thing from the past, then no, not really. Sadly the windows build hasn't been fixed yet, so it's much harder for you to test.
