### ISSUE TITLE
opengles2 GLSL fatal launch error on arm64 - Undeclared variable 'gl_ModelViewProjectionMatrix'

### ISSUE THREAD

**Issue by romadu** [gemrb/gemrb#1496]
#### Bug description
Gemrb fails to launch on arm64 ubuntu system, and I'm not sure why. This is the error message.

```[SDL 2 Driver]: Creating display
[SDL20Video/DEBUG]: Renderer: opengles2
[SDL 2 GL Driver]: OpenGL version: OpenGL ES 3.2 v1.r13p0-01rel0.8747d14aec16ec21ac2b2da252c4ec5f, renderer: Mali-G31, vendor: ARM
[SDL 2 GL Driver]:   GLSL version: OpenGL ES GLSL ES 3.20
[SDL 2 GL Driver/FATAL]: Can't build shader program: 0:8: L0002: Undeclared variable 'gl_ModelViewProjectionMatrix'
0:9: L0002: Undeclared variable 'gl_Color'
0:10: L0002: Undeclared variable 'gl_MultiTexCoord0'
[Core/FATAL]: Cannot initialize shaders.
[Main]: Aborting due to fatal error...
```

gemrb was compiled using `cmake .. -DOPENGL_BACKEND=GLES -DSDL_BACKEND=SDL2 -DDISABLE_VIDEOCORE=ON`

gemrb fails to compile on the same device when using `cmake .. -DCMAKE_TOOLCHAIN_FILE=/home/cmake_toolchain_arm64.cmake -DCMAKE_INSTALL_PREFIX=/roms/ports/gemrb -DSDL_BACKEND=SDL2 -DUSE_ICONV=OFF -DUSE_LIBVLC=OFF -DOPENGL_BACKEND=GL -DDISABLE_WERROR=1 -DDISABLE_VIDEOCORE=ON`

The error message for compile failure is:
```/repositories/gemrb/gemrb/plugins/SDLVideo/SDL20Video.cpp: In member function 'virtual int GemRB::SDL20VideoDriver::CreateSDLDisplay(const char*)':
/repositories/gemrb/gemrb/plugins/SDLVideo/SDL20Video.cpp:116:38: error: 'driverName' was not declared in this scope
  SDL_SetHint(SDL_HINT_RENDER_DRIVER, driverName);
```

#### Expected behavior
Add a clear and concise description of what you expected to happen.

#### Screenshots

GemRB version (check as many as you know apply)
- [x ] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x ] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Closing for now, please reopen if you get in trouble again. The cmake issue itself has been fixed.
