### ISSUE TITLE
 GCC 11 errors with stringop-overflow

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1497]
New GCC (on MSYS2), new heuristics annoyances w. r. t. warnings/errors:
```
In member function 'FixedSizeString<LEN, CMP>& FixedSizeString<LEN, CMP>::operator=(const char*) [with long long unsigned int LEN = 8; int (* CMP)(const char*, const char*, size_t) = strnicmp]',
    inlined from 'bool GemRB::Interface::LoadGemRBINI()' at D:/Sources/gemrb/gemrb/core/Interface.cpp:1984:2:
D:/Sources/gemrb/gemrb/core/System/String.h:144:32: error: 'char* strncpy(char*, const char*, size_t)' writing 8 bytes into a region of size 0 overflows the destination [-Werror=stringop-overflow=]
  144 |                         strncpy(str, c, sizeof(str) - 1);
      |                         ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
```

From what I've found, GCC/strncpy magic assumes a blank string because of
https://github.com/gemrb/gemrb/blob/6b1092476a3c4776dfb4a7930aa944987d3ee2b7/gemrb/core/System/String.h#L131
instead of recognizing the fixed-string string with a null at the end.

When you do something like this, GCC suddenly won't even complain about size 8 into 1 and just happily continues.
```diff
diff --git a/gemrb/core/System/String.h b/gemrb/core/System/String.h
index 3d89d2b23..fba847223 100644
--- a/gemrb/core/System/String.h
+++ b/gemrb/core/System/String.h
@@ -141,6 +141,7 @@ public:

        FixedSizeString& operator=(const char* c) noexcept {
                if (c) {
+                       str[0] = 1;
                        strncpy(str, c, sizeof(str) - 1);
                } else {
                        std::fill(begin(), end(), '\0');
```
Or instead, we set `-Wno-error=stringop-overflow`.

**Comment by bradallred** [comment]
wouldn't this work instead?

```diff
if (c) {
-	strncpy(str, c, sizeof(str) - 1);
+	strncpy(str, c, LEN);
} else {
```

**Comment by MarcelHB** [comment]
No difference. Would have been surprising, since it complains about the destination string termination size, not the copy length.

**Comment by bradallred** [comment]
well it shouldn't be complaining about anything :)

**Comment by MarcelHB** [comment]
See #1498

**Comment by MarcelHB** [comment]
Some of the assertion complaints that as seen in the other report can be killed by:
```diff
diff --git a/gemrb/core/GUI/Control.cpp b/gemrb/core/GUI/Control.cpp
index 2c97e2446..940d42d46 100644
--- a/gemrb/core/GUI/Control.cpp
+++ b/gemrb/core/GUI/Control.cpp
@@ -192,7 +192,7 @@ void Control::UpdateDictValue() noexcept
 void Control::BindDictVariable(const varname_t& var, value_t val, ValueRange range) noexcept
 {
 	// blank out any old varname so we can set the control value without setting the old variable
-	VarName[0] = '\0';
+	VarName[0u] = '\0';
 	if (range.first != Control::INVALID_VALUE) {
 		SetValueRange(range);
 	}
diff --git a/gemrb/core/Resource.h b/gemrb/core/Resource.h
index a5af0a916..0fb47ead0 100644
--- a/gemrb/core/Resource.h
+++ b/gemrb/core/Resource.h
@@ -57,7 +57,7 @@ inline ResRef MakeUpperCaseResRef(const char* str) {
 }
 
 inline bool IsStar(const ResRef& resref) {
-	return resref[0] == '*';
+	return resref[0u] == '*';
 }
 
 template <typename T>
 ```

Yet, even after fixing this, I still receive stringop-overflow warnings-as-errors. 😒 On the other hand, I'd be impressed if `assert` really made a difference to the compile time.

**Comment by lynxlynxlynx** [comment]
Does perhaps changing the assignment to direct shut gcc up? I can't get 11 yet to test myself.
`char str[LEN + 1] = {'\0'}; `

**Comment by MarcelHB** [comment]
What still baffles me is how Ubuntu GCC (v11.2) is much more silent than its same-version MSYS2 counterpart: I'll need to recheck this later on my different setup as even the most pedantic flags don't cause any trouble on Ubuntu here.

Not sure if there are any build flags, or header files stirring this up on different platforms.

**Comment by MarcelHB** [comment]
Not of help, unfortunately.

Let's ignore this, I just use `-DDISABLE_WERROR` for now and keep an eye on the warnings on the Ubuntu host. The GCC codebase is too much of a jungle to RE what's actually the problem between.

**Comment by TheCycoONE** [comment]
For what it's worth I am seeing this on an archlinuxarm host with gcc 11.2.0

**Comment by MarcelHB** [comment]
Yeah, it's still around. I believe it's the difference between compiling with `-O2` (`RelWithDebInfo` build type) and `-O3` (`Release` build type) with some newer GCC versions, but this needs some more investigation that I skipped so far.

**Comment by lynxlynxlynx** [comment]
Considering how many subreports the bug has, let's just disable the warning for now:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88443
I propose skipping the warning as well to avoid getting false reports.
