### ISSUE TITLE
GUIScript Control callbacks should take 0 or 1 parameters

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1506]
Currently, the callbacks can be 0, 1, or 2 parameters where the first parameter is the GControl and the second is the control value.

The control value is now available as a field on GControl (GControl.Value) so that second parameter is redundant.

This also causes warnings in static analysis tools since we often don't use the first parameter in the function, but still need to define it so the GUIScript plugin can pass the value.

Finding all of the uses will be a tad tricky. Probably a carefully crafted regex to find SetAction and SetEvent definitions that have 2 parameters will find them. We also need to be mindful of all the callers, which is more complicated. Luckily, there are not many times we call them from within the Python scripts.

**Comment by lynxlynxlynx** [comment]
Nothing interesting for SetAction. Whittled down SetEvent calls, checking exclusions at each step to 25 entries with
`git grep -n SetEvent.*lambda | grep -v '()' | grep -v GemRB | grep -v SetText  | grep -v '(Window)' | grep -vF .back`

Manually filtering that list gives only these to inspect and change:
```
gemrb/GUIScripts/GUIMG.py:352:  Button.SetEvent (IE_GUI_BUTTON_ON_PRESS, lambda: Unmemorize(btn, val))
gemrb/GUIScripts/GUIPR.py:287:  Button.SetEvent (IE_GUI_BUTTON_ON_PRESS, lambda: Unmemorize(btn, val))
gemrb/GUIScripts/GUIWORLD.py:244:               Button.SetEvent (IE_GUI_BUTTON_ON_PRESS, lambda btn, val: UpdateReformWindow(Window, val))
gemrb/GUIScripts/LUProfsSelection.py:323:               ProfsScrollBar.SetEvent(IE_GUI_SCROLLBAR_ON_CHANGE, lambda sb, val: ProfsRedraw (val))
gemrb/GUIScripts/iwd2/GUISPL.py:191:                            Button.SetEvent (IE_GUI_BUTTON_ON_PRESS, lambda btn, val, mc = ms['MemoCount']: OnSpellBookUnmemorizeSpell(btn, val, mc))
```

**Comment by lynxlynxlynx** [comment]
OpenItemInfoWindow was missed somehow, so now bags don't open.
