### ISSUE TITLE
Remove python2 support

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1517]
Continuing from #1515, so it's easier to track. There's no plan yet, but there's also nothing stopping us.  🐍

**Comment by lynxlynxlynx** [comment]
I don't know if ios is still being maintained, but it hardcodes python2 paths:
platforms/apple/CocoaWrapper/ios/GEM_AppDelegate.mm:108

@Northfear is there a py3 port for vita? I'm a bit surprised I wasn't able to quickly find it.

**Comment by bradallred** [comment]
The iOS issue is really that we were providing binaries for iOS at one point and I was unsure if we could distribute the Python runtime with it. It would be easy to just integrate Python directly into the app bundle if we could instead of relying on the user to load their own Python runtime.

**Comment by bradallred** [comment]
looks like there is an unofficial Vita distribution of [Python 3.8.7](https://github.com/SonicMastr/cpython-vita/tree/3.8.7-vita)

there is no official Vita distribution of any version of Python AFICT.

**Comment by lynxlynxlynx** [comment]
Oh cool, I'll go ahead with disabling it in the build system stuff then.

**Comment by Northfear** [comment]
@lynxlynxlynx no working Python3 here. Current VitaSDK isn't working properly with gemrb/py2 either, so I wouldn't hold anything because of Vita at this point.

**Comment by bradallred** [comment]
even if we want to have Python 2.7 compatibility we are probably better served by removing it now, transiting to Unicode text, then implementing Python 2.7 compatibility. The current Python module strings are not how to do Unicode in either version of Python.

**Comment by lynxlynxlynx** [comment]
I've ripped it out, but left the `PyStringWrapper` deprecation for someone else that can actually test with non-ascii range data.
