### ISSUE TITLE
use std::u16string instead of std::wstring

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1518]
Prior to C++11 `wchar_t` and `std::wstring` were the only viable method of using strings with 16 bit characters. However, `wchar_t` is often 32bits so our strings can be 2x as large as they need to be.

the main problem to overcome is that we use `swprintf` and there is no alternative for `char16_t` so we would need to roll our own formatting function. ~~Alternatively, C++11 introduced `std::to_string` so we may be able to use that instead of formatting, tho I suspect there are a few places that won't work well.~~ apparently `std::to_string` isn't a template and only works with `std:string`.

here are some open source formatting implementations that support 16 bit chars:
https://chromium.googlesource.com/chromium/src/+/refs/heads/main/base/strings/safe_sprintf.cc
https://chromium.googlesource.com/chromium/src/+/refs/heads/main/base/strings/stringprintf.cc

there is also [fmtlib](https://github.com/fmtlib/fmt), it does support C++11, but we would have to rewrite the way we format.

related to #1516

**Comment by bradallred** [comment]
I highly suspect that using UTF-16 on the Python side won't be viable without this. We would have to write our own function to do the conversion every time we wanted to pass a string to python and do the inverse when taking a string from Python.

**Comment by fizzet** [comment]
What would be the advantage of using UTF-16 for Python?

**Comment by MarcelHB** [comment]
Sounds good: Dropping Py2, sticking to a single encoding as far as data is ingested into GemRB, and relying on fmtlib.

Should put a lot of things back into maintainability.

**Comment by bradallred** [comment]
> relying on fmtlib

I'm not sure this is our preferred solution. It's another dependency and the need to change all of our format strings which is another tedious undertaking. I haven't really analyzed it. I don't know how @lynxlynxlynx feels about it either.

**Comment by MarcelHB** [comment]
Yeah, I just think that implementing [this](https://www.cplusplus.com/reference/cstdio/printf/) with a sufficiently large feature subset, in a safe and performant way saves us from rewriting every formatted line but is that less work itself? I'm just scanning the fmtlib repo for what it seems to take.

**Comment by lynxlynxlynx** [comment]
I'm not familiar with it; in another project we used "string theory", which also has it's own formatting capabilities, but that seems like overkill. Ideally the solution would be something stable we would just include directly like we did with the old fairer RNG or the Fibonacci trees.

**Comment by bradallred** [comment]
string theory sounds great, but unfortunately uses uff-8 internally and indeed seems like overkill.

one reason to perhaps prefer libfmt is that it is the basis for the string formatting used by C++20 so it will be familiar to most C++ devs. Its also very similar to Pythons formatting which is nice since we use both languages. It also has a header only mode (using `FMT_HEADER_ONLY`) so it should work on any C++11 compliant platform easily.

We _probably_ could use regex (or something else) to update the vast majority of our format strings so maybe it won't be as painful as I imagine.

**Comment by lynxlynxlynx** [comment]
We have only 24 users of (v)swprintf and 95 of regular flavour, so not much either way. Some are there just to deal with conversions that should be obsoleted by this work, some are just concatenations, but for sure many can be mass ninjad. VitaLogger will probably need some work, but that's the only special thing I saw.

Header-only sounds perfect. :)

**Comment by fizzet** [comment]
I don't think it's worth the hassle on the Python side. Python's internal representation of Unicode objects is not going be UTF-16 in most cases, anyway, so there's nothing to gain there, and working with UTF-8 is the straightforward option.

**Comment by bradallred** [comment]
> Python's internal representation of Unicode objects is not going be UTF-16 in most cases

My cursory research indicated this is controlled by the encoding of the source file. Not certain about it, however. It doesn't matter if we keep Python UTF-8 or not ultimately, but that is beside the actual point. 

The real issue is that, currently, we use our own bastardized encoding scheme (TLK expanded to 4 bytes). If we want to easily transfer stings between Python and C++, and expect to be able to manipulate those strings in our scripts, we _need_ to use an actual ISO encoding. Otherwise Python will throw a fit when it tries to decode our wide strings.

**Comment by fizzet** [comment]
No arguments on the C side. Python's internal representation depends on the string's contents, and for our use cases, will typically be ISO-8859-1. The source file encoding doesn't matter.

**Comment by bradallred** [comment]
> Python's internal representation depends on the string's contents, and for our use cases, will typically be  ISO-8859-1. The source file encoding doesn't matter.

The internal representation of Python strings is covered by [PEP393](https://www.python.org/dev/peps/pep-0393/). Assuming we use the "new" API to create the strings (`PyUnicode_New`) then we can assume `UTF-16` since we would pass 65535 for `maxchar`.

As for string literals, they are supposed to match the source encoding according to [PEP263](https://www.python.org/dev/peps/pep-0263/), but that same document also apparently forbids Python source to be encoded as UTF-16 so it is moot (and I don't thing we really care anyway).

**Comment by lynxlynxlynx** [comment]
Source encoding has always been weak in python, but I guess it was more obvious to us with non-us keyboard layouts. A stray em dash instead of a hyphen in a comment and it would refuse to run. So all our code is ASCII-range only already.
