### ISSUE TITLE
 Icewind Dale: Heart of Winter. Bugged ending.

### ISSUE THREAD

**Issue by dagdha2002** [gemrb/gemrb#1519]
#### Bug description
I have experimented some bugs in the last battle of Heart of Winter. When you killed Icasaracht, you must fight with its soul gem to end Heart of Winter and return to Kuldahar. In my game, when I killed the dragon, the soul gem remains liveless, so I can not attack it. I´ve tried to solve this using Near Infinity editor, editing the CHAR file for the Soul Stone, changing the value from no visible to visible. Making this solve the problem, when the dragon dies, I can fight now the Soul Gem (It appears red circled, but it does not attack my party members). But the problems don´t end here. At finishing the Soul Gem, a cinematic sequence must appear, and then, the party have to be moved to Kuldahar. In my game it doesn´t occur, the cinematic sequence doesn´t display at all and my party remain at the same area. If I tried to exit the area, the game displays the credits and it ends exiting to the main menu. To solve this, I tried to use MoveToArea command, moving the party to Hjolder cabinet in Kuldahar. Making this fire the cinematic sequence, but if I tried to move normally to exit Kuldahar, the game crashes. I only can move between areas using MoveToArea command.
I have attached one save game, before to enter Icasaracht lair.
The problem was detected playing in my PC, that uses version 0.9.0, 
I expect that this will be useful. Thanks for all your work.
I have installed some mods. #1459
[000000083-Bug7.zip](https://github.com/gemrb/gemrb/files/7873618/000000083-Bug7.zip)

**Comment by lynxlynxlynx** [comment]
Looks like it was temporary — the gem works fine now. But The ending needs further investigation of the scripting involved. The current behaviour is correct for standalong HoW games.

**Comment by dagdha2002** [comment]
Ok, thanks to have a look on this.
