### ISSUE TITLE
error: conflicting decleration when trying to build GemRB

### ISSUE THREAD

**Issue by MesmericOrb** [gemrb/gemrb#152]
I am following the guide for the installation from:
http://www.gemrb.org/wiki/doku.php?id=install:windows

I am currently trying the GemRB-buildnv.cmd and I am encountering a problem with an "error: conflicting decleration". 

Similar to an error someone else had: 
https://github.com/gemrb/gemrb/issues/149

I tried to use the solution that was provided, however my problem isn't solved. 

Perhaps someone can help me with this? Here is my feedback:
C:\Users\Ryan\gemrb_source\gemrb_build>mingw32-make
Scanning dependencies of target gemrb_core
[  0%] Building C object gemrb/core/CMakeFiles/gemrb_core.dir/System/swab.c.obj
[  1%] Linking CXX shared library libgemrb_core.dll
[ 57%] Built target gemrb_core
[ 57%] Linking CXX executable gemrb.exe
[ 57%] Built target gemrb
[ 57%] Linking CXX shared module ..\2DAImporter.dll
[ 57%] Built target 2DAImporter
[ 57%] Linking CXX shared module ..\ACMReader.dll
[ 59%] Built target ACMReader
[ 60%] Linking CXX shared module ..\AREImporter.dll
[ 60%] Built target AREImporter
Scanning dependencies of target BAMImporter
[ 60%] Building CXX object gemrb/plugins/BAMImporter/CMakeFiles/BAMImporter.dir/BAMImporter.cpp.obj
In file included from C:\Users\Ryan\gemrb_source\gemrb\gemrb\plugins\BAMImporter\BAMImporter.cpp:39:0:
C:/Users/Ryan/gemrb_source/gemrb/gemrb/core/System/swab.h:29:19: error: conflicting declaration 'typedef long int ssize_t'
  typedef long int ssize_t;
                   ^~~~~~~
In file included from c:\mingw\include\wchar.h:66:0,
                 from c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\cwchar:44,
                 from c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\bits\postypes.h:40,
                 from c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\bits\char_traits.h:40,
                 from c:\mingw\lib\gcc\mingw32\6.3.0\include\c++\string:40,
                 from C:/Users/Ryan/gemrb_source/gemrb/gemrb/core/System/String.h:26,
                 from C:/Users/Ryan/gemrb_source/gemrb/gemrb/includes/win32def.h:33,
                 from C:/Users/Ryan/gemrb_source/gemrb/gemrb/includes/globals.h:53,
                 from C:/Users/Ryan/gemrb_source/gemrb/gemrb/core/AnimationMgr.h:24,
                 from C:\Users\Ryan\gemrb_source\gemrb\gemrb\plugins\BAMImporter\BAMImporter.h:24,
                 from C:\Users\Ryan\gemrb_source\gemrb\gemrb\plugins\BAMImporter\BAMImporter.cpp:22:
c:\mingw\include\sys\types.h:123:21: note: previous declaration as 'typedef _ssize_t ssize_t'
   typedef _ssize_t  ssize_t;
                     ^~~~~~~
gemrb\plugins\BAMImporter\CMakeFiles\BAMImporter.dir\build.make:62: recipe for target 'gemrb/plugins/BAMImporter/CMakeFiles/BAMImporter.dir/BAMImporter.cpp.obj' failed
mingw32-make[2]: *** [gemrb/plugins/BAMImporter/CMakeFiles/BAMImporter.dir/BAMImporter.cpp.obj] Error 1
CMakeFiles\Makefile2:588: recipe for target 'gemrb/plugins/BAMImporter/CMakeFiles/BAMImporter.dir/all' failed
mingw32-make[1]: *** [gemrb/plugins/BAMImporter/CMakeFiles/BAMImporter.dir/all] Error 2
Makefile:128: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
ERROR: 2

C:\Users\Ryan\gemrb_source\gemrb_build>POPD

C:\Users\Ryan\gemrb_source>

**Comment by MesmericOrb** [comment]
my swab.h file currently:
#ifndef IE_SWAB_H
#define IE_SWAB_H

#include "exports.h"

#if defined(__cplusplus)
extern "C" {
#endif

#if !defined(_SSIZE_T_DEFINED_) && !defined(__ssize_t_defined)
# define _SSIZE_T_DEFINED_
 typedef long int ssize_t;
#endif

GEM_EXPORT void swabs(void *buf, ssize_t n);

#if defined(__cplusplus)
}  /* extern "C" */
#endif
#endif

**Comment by lynxlynxlynx** [comment]
First, if you're in a hurry, you can just use the automatically built binaries. This is from the last commit:
https://ci.appveyor.com/project/lynxlynxlynx/gemrb/builds/25140952/artifacts

Can you show me your c:\mingw\include\sys\types.h instead?

**Comment by MesmericOrb** [comment]
[typeh.txt](https://github.com/gemrb/gemrb/files/3273634/typeh.txt)

Thanks for the fast response. 👍 
I'm checking out the automatically built binaries right now as well.

**Comment by MesmericOrb** [comment]
I have the automatically built binaries file, but how do I use it. Do I place it somewhere?
Sorry I am a complete novice.

**Comment by lynxlynxlynx** [comment]
You unzip it and edit the config file like with any other installation method.

**Comment by lynxlynxlynx** [comment]
Btw, the build problem should be fixed for you as well.
