### ISSUE TITLE
Actors' orientation is flipped while moving 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1520]
Across the games, I noticed that some actors are now often facing the opposite direction while moving.

Can be observed at the dragon at the end of HoW while it is moving towards the group:

![orientation](https://user-images.githubusercontent.com/238558/149632567-185bcd20-17d7-4d45-bf3d-b1a9b55c4a3d.jpg)

**Comment by lynxlynxlynx** [comment]
Definitely a pathfinder thing, it executes a regular `MoveToPoint([1804.915])`.

**Comment by lynxlynxlynx** [comment]
His path gets 12 as the orientation set, which is correct and doesn't change. So did we start drawing them badly at some point?  East animations are often separate ...

**Comment by lynxlynxlynx** [comment]
It's a regression from d2f2daf08.

**Comment by lynxlynxlynx** [comment]
I can't see anything special there, besides not replacing the sprite any more, but it's clear x mirroring isn't working any more. @bradallred can you take a look? It's easiest to test by just loading an iwd save with some space, `cc("icasa")` and talking to her from the east — she will reorient the opposite way.

**Comment by MarcelHB** [comment]
I don't think it's limited to facing the east. In the example cutscene above, I can also see at least two PCs walking backwards (heading north-west) for some distance until they correctly end up where they wait for the dragon.

**Comment by bradallred** [comment]
mirroring obviously works or the fog would be broken. ignoring the fog related changes from that commit leaves pretty much this:

```diff
for (size_t i = 0; i < indicesCount; i++) {
 	frame_t& sprite = frames[I];
 	-sprite = video->MirrorSprite(sprite, flags & (BlitFlags::MIRRORX | BlitFlags::MIRRORY));
 	+sprite->renderFlags ^= flags & (BlitFlags::MIRRORX | BlitFlags::MIRRORY);

 	if (flags & BlitFlags::MIRRORX) {
 		sprite->Frame.x = sprite->Frame.w - sprite->Frame.x;
```

You already pointed out the difference is that we aren't copying the sprite anymore. The problems must be then, that the same sprite is getting mirrored multiple times effectively undoing the original mirroring. The simple fix would be to just dupe the sprite and apply the flag to the copy. The best fix would involve knowing when to pass the appropriate mirror flags when the frame is drawn.

there is also a bug here, but I don't know if its causing issues:
`anim->MirrorAnimation(BlitFlags(Transparency) & (BlitFlags::MIRRORX | BlitFlags::MIRRORY));`

`MirrorAnimation` should only accept `MIRRORX` and `MIRRORY` and I have no idea why `Transparency` is getting anded here but it could obviously affect the result if it has certain bits set.

**Comment by lynxlynxlynx** [comment]
What's also suspect is the xoring, since I'd expect the flags to switch back and forth with each call, since they're now working on the same object. But there's no visible flickering. Clearing the two bits before potentially setting them again introduces other problems, so I guess it needs some watchpoints.

**Comment by lynxlynxlynx** [comment]
Stepping through was useful, as somehow the frames share the exact same renderFlags field, having pairwise (0 and 1, 2 and 3 ...) the same address. WTF

**Comment by bradallred** [comment]
right, as I said we must be dealing with the same `Sprite2D` used for multiple frames. I know nothing about the underlying data unfortunately.

**Comment by lynxlynxlynx** [comment]
Good point, it could be in the data itself ... And you're right, the source data has duplicated frames (eg. chmb3g1 cycle 63), I guess to double the duration. Time to reinstate the sprite copying, no way around it.
