### ISSUE TITLE
[bug] False-positive compilation error on Debian 10/g++ 8.3.0

### ISSUE THREAD

**Issue by sten13** [gemrb/gemrb#153]
**Description**

When building gemrb, one gets an error:

```
In file included from .../gemrb/gemrb/core/ImageMgr.h:28,
                 from .../gemrb/gemrb/plugins/CHUImporter/CHUImporter.cpp:28:
In member function ‘void GemRB::ResRef::operator=(const char*)’,
    inlined from ‘GemRB::ResRef::ResRef(const char*)’ at .../gemrb/gemrb/core/Resource.h:54:12,
    inlined from ‘virtual GemRB::Window* GemRB::CHUImporter::GetWindow(unsigned int)’ at .../gemrb/gemrb/plugins/CHUImporter/CHUImporter.cpp:395:30:
.../gemrb/gemrb/core/Resource.h:71:11: error: ‘char* strncpy(char*, const char*, size_t)’ output may be truncated copying 8 bytes from a string of length 8 [-Werror=stringop-truncation]
    strncpy(ref, str, sizeof(ref)-1 );
```

GemRB version: git (435b73d5a)

**To Reproduce**

1. mkdir build
2. cd build
3. cmake ..
4. make

**Expected behavior**

A finished build.

**Workaround**

The code in Resource.h that the C++ compiler flags is perfectly fine. The issue is with g++, in this case apparently some interaction between the optimiser and the warning engine. As a temporary workaround, this specific warning can be disabled:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a80ca8d61..448122076 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -156,7 +156,7 @@ IF(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
                endif ()
        endif ()
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -W -Wpointer-arith ")
-       set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pedantic -Wno-format-y2k -Wno-long-long")
+       set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pedantic -Wno-stringop-truncation -Wno-format-y2k -Wno-long-long")
        # only later c++ standards conditionally allow function/object pointer casts
        # gcc pragmas for disabling are broken: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=53431
        if (CMAKE_CXX_COMPILER_ID MATCHES "GNU" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 7)
```

In case you can't see it right away, the new version adds the flag `-Wno-stringop-truncation` to `CMAKE_CXX_FLAGS`.

**Comment by lynxlynxlynx** [comment]
Hmm, I don't get this on gcc 9. Does using `strlcpy` work for you instead? The warning is quite useful, so as a second option it's better to add `-Wno-error=stringop-truncation`.

**Comment by sten13** [comment]
Yep, can confirm it builds with `strlcpy()`. Thanks!

**Comment by sten13** [comment]
Diff attached.

```
diff --git a/gemrb/core/Resource.h b/gemrb/core/Resource.h
index 61fb5c2f0..975f89a17 100644
--- a/gemrb/core/Resource.h
+++ b/gemrb/core/Resource.h
@@ -66,7 +66,7 @@ public:
                if (str == NULL) {
                        Clear();
                } else {
-                       strncpy(ref, str, sizeof(ref)-1 );
+                       strlcpy(ref, str, sizeof(ref));
                        ref[sizeof(ref)-1] = '\0';
                }
        }
```

**Comment by lynxlynxlynx** [comment]
It's even better, the next line isn't needed then. Thanks for the confirmation, the fix will land in the tree today.

**Comment by sten13** [comment]
Excellent, thanks! Do I close issues or do you? From my POV, this solves my problem.

**Comment by lynxlynxlynx** [comment]
It should happen automatically once the commit arrives. :)

**Comment by sten13** [comment]
Dammit, I ought to have known that, but it seems that I don't use the github issue tracker enough!

**Comment by lynxlynxlynx** [comment]
The commit message has to mention it, the rest is magic:
https://help.github.com/en/articles/closing-issues-using-keywords
