### ISSUE TITLE
In a modded BGT install, helmets are not appearing on halfling fighter paperdoll, and banters are reset

### ISSUE THREAD

**Issue by Rhastor** [gemrb/gemrb#1531]
See this post on gibberlings3: 

https://www.gibberlings3.net/forums/topic/34236-some-errors-when-loading-a-modded-bgt-game-in-gemrb/

**Comment by lynxlynxlynx** [comment]
Can you provide more details, a save? The reporting instructions aren't there just to be deleted ...

**Comment by Rhastor** [comment]
[000000000-Auto-Save.zip](https://github.com/gemrb/gemrb/files/7964294/000000000-Auto-Save.zip)

Sure, here is a save. Details about the issue are in the post I linked.

**Comment by lynxlynxlynx** [comment]
Not really, what is the next expected banter? For which character?

**Comment by Rhastor** [comment]
As soon as you load, Branwen banters about the protagonist being gender-changed as though she is wearing the transsexual ogre's cursed girdle. In fact she just has this in inventory, and wore it, and removed it many chapters ago.

**Comment by Rhastor** [comment]
Oh, and another thing while I'm at it: a neutral courtesan and a hostile kobold commando appear to the left of the party in that save, but neither is supposed to be there nor do they appear when the save is loaded without GemRB.

**Comment by Rhastor** [comment]
Oh, and another thing while I'm at it: a neutral courtesan and a hostile kobold commando appear to the left of the party in that save, but neither is supposed to be there nor do they appear when the save is loaded without GemRB.

**Comment by lynxlynxlynx** [comment]
One thing per bug please ... Getting back to the banter: that appears to be mod-added, I guess BG1 NPC. Can you transcribe at least part of it, so it's easier to find? I suspect it's not really a banter, but a scripted line and that it's a trigger problem in the end.

**Comment by Rhastor** [comment]
"Branwen: I have nothing to say to any of you.

Branwen: That's quite a predicament ... sister."

This is probably from BG1 NPC Project. The main character is naturally female and not wearing the belt.

Should I submit another report about the incorrectly spawned creatures that appear in the same save?

**Comment by lynxlynxlynx** [comment]
bg1re apparently. And annoying enough it's stored as @6, so two chars, which means github search is useless. The code is here:
https://github.com/Gibberlings3/BG1_Romantic_Encounters/blob/75cb5bb9d0e20c91b36774b49cfd02e2fc5541c2/bg1re/girdlegender/baf/PCreactions/re1ggbrb.baf
Which then confirms my suspicion — one of our older hacks, known fixmes is to blame. Practically we check the whole inventory, not just equipped items, that's why it happens.

spawn: yes and please also ctrl-m on the two npcs, so their death vars / scripting names will be obvious.

**Comment by Rhastor** [comment]
Oy, I somewhat regret installing RE. Kind of boring as a female character anyway, as I am just turning everyone down!

I'll get on the other bug report in a moment.

**Comment by Rhastor** [comment]
I am actually having trouble doing this as CTRL+M is not working for some reason. I do have debug mode on, and cheat keys enabled through CLUAConsole:EnableCheatKeys(), and Wild Surge Keys=1 under Game Options in baldur.ini, but CTRL+M followed by enter does nothing. (Other cheats like CTRL+J and CTRL+Q do work.)

There's an even worse problem I just noticed, which is a crash to desktop when loading the world map, whether through the map screen, or by walking off the edge of the map.

Three/four bug reports? Or should I not bother?

**Comment by lynxlynxlynx** [comment]
ctrl+m prints to the console and log, not the ingame message window (unless specifically told to).

the worldmap crash would deserve its own report, yeah, BUT I think it has already been fixed after the release of 0.9.0. What OS are you using?

**Comment by Rhastor** [comment]
It's not printing to the console or log.

I am using 0.9.0 on Windows 10.

**Comment by lynxlynxlynx** [comment]
Oh, if it wasn't clear, you have to point to the actor with your mouse to get their dump.

Sadly the windows build has been broken for a while, so I can't give you the latest code to try (I've fixed the "banter" bug). You can still try the development build to see if it avoids the worldmap crash though.

**Comment by Rhastor** [comment]
Yep, no matter where I point - the kobold, the courtesan, Xzar, the PC, a tree, the dirt - the result is the same nothing.

Now that you mention it, I can try this on an Ubuntu machine later on, and see if the result is the same.
