### ISSUE TITLE
removing pl_uppercase/pl_lowercase

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1532]
in order to achieve #1516 we will need to resolve the reason for these arrays existing.

My analysis so far has indicated that we are inverting uppercase and lowercase characters. I imagine the motivation was simply font display issues (fonts were swapped for these locales?), which we can resolve another way. 

However, there are 3 functions which are "aware" of these arrays: `strnlwrcpy`, `strnuprcpy`, and `strnspccpy`. These are used for dealing with `ResRef`s and `ieVariable`s, but [the plan](https://github.com/gemrb/gemrb/wiki/Text-Encoding-Documentation) assumes both of these types are limited to ASCII. If they are ASCII, then the chars above 127 don't matter and the use of these arrays here is useless. It's probably also worth pointing out that since we have inverted upper and lowercase then using those arrays to uppercase or lowercase a string is inherently incorrect anyway.

**Comment by lynxlynxlynx** [comment]
I think these are needed for text, not data, since tlk encoding can differ. The functions exist to take into account the remapped lower/upper case pairs — see czech.ini for example.

**Comment by bradallred** [comment]
yeah, I've looked at some of the INIs and AFICT we are just swapping some lowercase and uppercase letters. The code reads the same way:

```
const char *s2 = strchr(s,',');
if (s2) {
	unsigned char upper = atoi(s);
	unsigned char lower = atoi(s2+1);
	pl_uppercase[lower] = upper;
	pl_lowercase[upper] = lower;
}
```

**Comment by lynxlynxlynx** [comment]
Remapping, but yeah. German might be the simplest to test, since it has only 4 substitutions.

I forgot we have the data differences better documented here:
https://gemrb.org/Text-encodings.html

**Comment by bradallred** [comment]
I understand the point of swapping uppercase and lowercase now.

All ini files I've examined, including German, are simply using UTF code points. We just need a `tolower` and `toupper` that works with UTF, which we need anyway.

**Comment by bradallred** [comment]
great, it looks like `std::towupper` and `std::towlower` do [exactly this](http://www.open-std.org/JTC1/SC35/WG5/docs/30112d10.pdf).
