### ISSUE TITLE
Volume setting is busted

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1540]
On reopening, different values are shown with the sliders, as if the saving failed and don't match initial ini settings either. Variables do get updated when twiddling with the slider live though.

**Comment by lynxlynxlynx** [comment]
It's visible already on the first open: all the knobs are the minimal position.

The bug starts happening with 9d7b7034. Sliders use `SetVarAssoc` in a special way, treating the value as a multiplier, not something part of the value range. This still works fine if you interact with the slider, but the way `SetVarAssoc` was changed nukes the associated actual-var value.
That can be restored by saving it first in the script, but then we don't have a way to force the slider to update / redraw. Calling `SetValue` two times to force it doesn't result in redraw, because it first changes the value and then as a result `Slider::UpdateState` always results in position 1. In a sense `Pos` is closer to a value field for Slider than the shared value.

**Comment by lynxlynxlynx** [comment]
@bradallred  do you have any design preferences for addressing this?

**Comment by bradallred** [comment]
Speaking short term, it's probably easiest to just not bind the variables to the slider, and setup a callback to multiply and set the volume vars there.

Something like:
```
Slider.SetAction(lambda ctl: GemRB.SetVar("VolumeVar", ctl.Value * whatever), IE_ACT_VALUE_CHANGE)
```

long term, it might make sense to refactor `Control::UpdateDictValue` with more options (currently uses `SetBits` to achieve toggle or set) if we have greater need.
