### ISSUE TITLE
Tall actors are trampled on visually by other actors

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1546]
With actors of normal height, this is visible in some cases only, but when having tall actors like this cyclops, this is something that should be improved. We had similar tickets in the past but I did not spot any open one.

#### Screenshots

![actor_cover](https://user-images.githubusercontent.com/238558/152877670-8d630666-a594-47b9-9dd9-5a842d89b06e.jpg)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment]
it's not just tall actors, I can trivially repro it with normal actors. Something fairly recent too as it effects one of my primary test saves. I remember 4e4a2c7 changing the sorting so thats probably what did it.

**Comment by bradallred** [comment]
hmmm, looks like maybe we aren't iterating the entire queue

**Comment by bradallred** [comment]
no, obviously counting iterations though the sorting function are a bad test :)

I think that leaves the problem being that some actors are ending up in the wrong queue.

**Comment by bradallred** [comment]
my quick test tells me it is in fact 4e4a2c7 (or it is somehow transient)

The previous sorting code is definitely confusing. I cant tell what else it is sorting on.

**Comment by MarcelHB** [comment]
I'll have a look.

**Comment by MarcelHB** [comment]
I don't see any problem either, or at least the most obvious one is gone then.

**Comment by lynxlynxlynx** [comment]
Also matches std::sort docs and it doesn’t matter which way we sort when ys are the same.
