### ISSUE TITLE
IWD2: Acid storm leads to some severe performance drop 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1547]
When casting _Acid storm_ in IWD2 (SPWI708), right before emission, the whole game freezes for about a second. I did not find any other spell to have a similar anomaly.

#### Screenshots
![iwd2_acid_storm](https://user-images.githubusercontent.com/238558/152879054-5e147c9c-5f14-4501-9ec3-ecfcc0596757.gif)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment]
this _probably_ isn't something we can fix without finishing the [gfx roadmap](https://github.com/gemrb/gemrb/wiki/Graphic-Rendering-Roadmap) combining software and hardware rendering is just never going to be good performance. My instinct tells me we are creating textures for several "particles" or something. 

unless you profile it and find something eating CPU outside of SDL.

**Comment by lynxlynxlynx** [comment]
I didn't notice any slowdowns when the chult dragon cutscene does it, so this could be new. But I also probably was on software rendering. It's a single bam btw.

**Comment by MarcelHB** [comment]
@bradallred What about this? It spends 50 projectiles x 16 orientation anims doing 23 frame copies (the latter takes 1ms, so in total almost a second). But since that spell animation obviously does not need mirroring, this looks like a naive solution:

```diff
diff --git a/gemrb/core/Projectile.cpp b/gemrb/core/Projectile.cpp
index a853bf57e..dfa83c0b9 100644
--- a/gemrb/core/Projectile.cpp
+++ b/gemrb/core/Projectile.cpp
@@ -151,7 +151,9 @@ Projectile::AnimArray Projectile::CreateOrientedAnimations(const AnimationFactor
                        a->SetFrame(0);
                }

-               a->MirrorAnimation(mirrorFlags);
+               if (mirrorFlags != BlitFlags::NONE) {
+                       a->MirrorAnimation(mirrorFlags);
+               }
                a->gameAnimation = true;

                anims[Cycle] = std::move(*a);
```

**Comment by bradallred** [comment]
it would probably be better to make `MirrorAnimation` return early if there are no applicable flags so that the fix will more broadly apply. Go ahead and make a PR!

**Comment by bradallred** [comment]
I'm assuming that fully fixed the issue? or is just an improvement?

reopen if the latter

**Comment by MarcelHB** [comment]
Yeah, hope so.
