### ISSUE TITLE
 IWD2: Cannot open action bar menu for special abilities (rogue)

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1548]
I have a thief/rogue PC that has a special (?) ability _Rapid Shot_. In the original, you can toggle its state in this menu for on/off. Here, we get a Python error (see below).

#### Steps to reproduce
1. Load this save [000000009-gemrb.zip](https://github.com/gemrb/gemrb/files/8020092/000000009-gemrb.zip)
2. Select PC no. 5
3. Hit the star icon on the action bar to the right.

#### Screenshots
```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "D:/Sources\gemrb\gemrb\GUIScripts/GUICommonWindows.py", line 1008, in ActionInnatePressed
[Python/ERROR]:     UpdateActionsWindow ()
[Python/ERROR]:   File "D:/Sources\gemrb\gemrb\GUIScripts/GUICommonWindows.py", line 664, in UpdateActionsWindow
[Python/ERROR]:     Spellbook.SetupSpellIcons(CurrentWindow, spelltype, TopIndex, ActionBarControlOffset)
[Python/ERROR]:   File "D:/Sources\gemrb\gemrb\GUIScripts/Spellbook.py", line 217, in SetupSpellIcons
[Python/ERROR]:     raise AttributeError ("Error, unknown BookType passed to SetupSpellIcons: %d! Bailing out!" %(BookType))
[Python/ERROR]: AttributeError: Error, unknown BookType passed to SetupSpellIcons: 1280! Bailing out!
```

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

**Comment by lynxlynxlynx** [comment]
Interesting value, book types are usually single bits. 1280 =1024 + 32 + 16 + 8

Was this save made in gemrb or the original?

**Comment by MarcelHB** [comment]
gemrb. I can check again for some native same game later.

**Comment by lynxlynxlynx** [comment]
Yes, please, it would make a good comparison.

**Comment by MarcelHB** [comment]
I did tests with fresh IWD2 runs, with more than one PC, resaved them in GemRB and everything is good. Then again, opening the spellbooks also does not working on these savegames: nothing shows up.

Not sure what I did when exactly with the existing savegames but maybe some of them are saved in GemRB pre #667 so corrupted in these terms, at least the timestamps may indicate that.
