### ISSUE TITLE
[enhancement] Set the window manager icons

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#155]
FLOSS platforms support WM icon(s), stuff visible in the window titlebar, program lists, window switcher lists ... now the default X11 logo is used instead.

SDL1 has [SDL_WM_SetIcon](https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlwmseticon.html), but that has a somewhat limited format.
SDl2 only has [SDL_SetWindowIcon](https://wiki.libsdl.org/SDL_SetWindowIcon), which can do arbitrary sizes also on Windows. So we can ignore SDL1 ... Both cover only part of the use cases, while the rest is handled by the .desktop file for anyone that uses it.

https://github.com/gemrb/gemrb/blob/master/artwork/ has the logos, the "rb" square one being most appropriate. Nowadays it should be enough to install the SVG into /usr/share/icons/hicolor/scalable/apps ([as suggested by XDG icon theme spec](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html)). ~We currently install only the PNG to ICON_DIR. The gemrb.desktop file tells the WM the name to look for, so remember to rename it to gemrb.svg on install.~

For SDL, a fixed size surface is needed, so I suggest loading a 128x128px version.

EDIT: as of #166 windows gets an icon through cmake. Not sure if any other cases needs to be handled for that platform.

EDIT: GIMP can generate the C code, yay. :) https://blog.gibson.sh/2015/04/13/how-to-integrate-your-sdl2-window-icon-or-any-image-into-your-executable/

> I managed to get icons to work in sdl2 and linux by calling SDL_SetWindowIcon right after SDL_CreateWindow, before SDL_CreateRenderer.

**Comment by lynxlynxlynx** [comment]
Actually we already install the svg and it works fine for the prebuilt binaries ... I think, I noticed now that the icon got cached for me and I can't wipe it clean. @fenuks can you please try downloading one of the linux builds and running it, just to see if you get the proper taskbar icon?

https://sourceforge.net/projects/gemrb/files/Buildbot%20Binaries/Linux/

**Comment by fenuks** [comment]
So, icon does render correctly for me using the latest build at the moment (gemrb-2020-06-305b0cf79.tar.bz2).

![obraz](https://user-images.githubusercontent.com/1249829/86147451-f0010880-bae8-11ea-82b3-760eb1078520.png)

**Comment by lynxlynxlynx** [comment]
Excellent, thanks. So basically it's not there only for cases when running from the build dir. A simple copy inside doesn't do it, but this all is now low priority. :)

**Comment by fenuks** [comment]
Oops, sorry. I had GemRB installed on my system via package manager, and after uninstalling it, I'm sorry to say that GemRB icon is not correctly set (x icon is displayed instead in my case).

**Comment by lynxlynxlynx** [comment]
Hmm, how about if you edit gemrb.desktop and set the Icon line to ./gemrb? Or maybe with a .svg at the end?

**Comment by fenuks** [comment]
Desktop file icon was updated (Thunar can use both png and svg, but Dolphin accepts only png), but that doesn't seem to affect icon on taskbar when I run GemRB with this updated desktop file.

**Comment by lynxlynxlynx** [comment]
Reread the specs and it appears there's not much we can do. We could use a script just for resetting XDG_DATA_DIRS before invocation, but that's lame. I guess the sdl functions are unavoidable.
