### ISSUE TITLE
Speed up Appveyor build

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1551]
It's now spending ~15 minutes building openssl, so look for better vcpkg options, caching etc. Also, can we avoid some of the multilib stuff?

There are probably other slow downs, since it used to take less than 10 minutes altogether.

> Elapsed time for package bzip2:x64-windows: 18.37 s
> Elapsed time for package expat:x64-windows: 16.17 s
> Elapsed time for package libffi:x64-windows: 5.512 s
> Elapsed time for package libffi:x86-windows: 4.796 s
> Elapsed time for package liblzma:x64-windows: 35.57 s
> Elapsed time for package liblzma:x86-windows: 35.11 s
> **Elapsed time for package openssl:x64-windows: 8.14 min**
> **Elapsed time for package openssl:x86-windows: 7.699 min**
> Elapsed time for package sqlite3:x64-windows: 32.68 s
> Elapsed time for package zlib:x64-windows: 8.84 s
> **Elapsed time for package python3:x64-windows: 5.389 min**
> Elapsed time for package sqlite3:x86-windows: 26.64 s
> **Elapsed time for package python3:x86-windows: 4.812 min**

The rest are measured in milliseconds, some due to being preinstalled.

**Comment by bradallred** [comment]
what on earth are we using thats bringing in openssl?

**Comment by lynxlynxlynx** [comment]
My money is on python, though there should be no need to build from scratch.

**Comment by lynxlynxlynx** [comment]
Yeah. The python3 package has no useful features we could disable, but building statically would kill its deps (there just for extra modules). The forced caching now avoids the dependency problem though and it takes less than a second to set them all up.
