### ISSUE TITLE
Refactor Effect struct

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1553]
I don't have a deep grasp of how Effects work, so some of this is speculative.

The `Effect` struct is a whopping ~224 bytes, yet it is something we need to move around and copy a _lot_. Nothing in the struct is even moveable, so moves and copies are the same.

Now the speculation. I believe that many of the fields of `Effect` are actually static and could be abstracted out into a _shared_ structure (`shared_ptr` or `Holder`). Ideally, we could end up without custom copy/move operations for a small structure with one or a few shared reference fields that are trivially copied/moved.

**Comment by lynxlynxlynx** [comment]
What do you mean by static there? Effects don't share fields except by chance, so I don't understand what could be done.

**Comment by bradallred** [comment]
at a minimum there appear to at least be "V1" and "V2" effects, but it looks like there is a lot more that never changes between the original effect we are cloning from and the one that gets applied to an `Actor`. seems like mainly position, timing mode, and parameters.

**Comment by lynxlynxlynx** [comment]
Ah, things that are currently only read from. Maybe a few fields, though nothing obvious comes to mind, maybe saving throw type.

**Comment by lynxlynxlynx** [comment]
I still don't think anything worthwhile can be done here, so closing. For each effect there will be just a subset of fields set, but we can't know in advance which those might be.
