### ISSUE TITLE
Effects/Spells are in slow-motion 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1570]
Take some spell, like a fireball, and cast it. The game does not matter.

What happens: 

- The projectile flies about 18s towards its destination, but not steadily. More like lingering in the air for a few seconds at one place, and then advancing a few meters forwards to the next point, and so on.
- The local eruption visual hangs around for another few seconds.
- The fire burst rings also take their time.
- And finally, some more seconds later, the actors indicate a hit.

So something makes this spell a matter of 25s, instead of ~1s.

**Comment by lynxlynxlynx** [comment]
Hmm, could be my fault with the Game::Ticks cleanup, will take a look.
