### ISSUE TITLE
Switch to a more recent c++ standard

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#158]
Due to portability concerns, we've been slow in the uptake of new language standards. It's time to move to c++11, which had enough time to solidify and get widely supported:
https://en.cppreference.com/w/cpp/compiler_support

It's trivially achieved by adding `set (CMAKE_CXX_STANDARD 11)` to the main CMakeLists.txt and requiring at least cmake 3.1.

Postponed until https://github.com/gemrb/gemrb/milestone/2 is released.

**Comment by MarcelHB** [comment]
I suggest two things in addition with this step:

1. Choose a `clang-format` style in a way that I can configure my editor to auto-format changes into a consistent format, as can be seen [here](https://github.com/rhysd/vim-clang-format). For me, it's just easier than looking around what looks like fitting to its neighbours.
2. With a modern CMake, you can also [integrate](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_CLANG_TIDY.html) `clang-tidy` with some given check profiles, especially `modernize-*`.

The C++ codebase shows the usual symptoms of 15y+ of age and plenty of contributors, so this could align things a bit for future work, with enforcement by CI steps.

**Comment by lynxlynxlynx** [comment]
Definitely something for a separate report. 

We had a comprehensive style ruleset written ... on Titanpad, which since expired and the pad isn't in the internet archive. Grrr.

I am against enforcing a style everywhere, since we'd get a bunch of unrelated changes with each modified file. IDEs are dumb like that. As for new/modified chunks, definitely. The style needs to be codified first, of course.

**Comment by MarcelHB** [comment]
I only hat diff formatting in mind, so that I can do something like this for my changes without doing anything manually: http://clang.llvm.org/docs/ClangFormat.html#script-for-patch-reformatting

**Comment by lynxlynxlynx** [comment]
Sonar also highlighted above 50 places where we could use the new "explicit" keyword to avoid a certain class of problems.

**Comment by lynxlynxlynx** [comment]
Ok, it's in and none of the build bots complained when I added an auto. So feel free to use c++11 features going forward.
