### ISSUE TITLE
Request: List of exact files required by GemRB for each game

### ISSUE THREAD

**Issue by shinra-electric** [gemrb/gemrb#1583]
#### Description
After unpacking the games from GOG, there are a load of useless files (such as gog installers, autorun, windows dlls etc) that could be deleted. 

Is it possible to create a list of all the files that are required for each game in order for it to run, so irrelevant files can be deleted? 

For example, ScummVM list all their required files [like this](https://wiki.scummvm.org/index.php?title=Blade_Runner#Required_data_files).

**Comment by MarcelHB** [comment]
Since depending on the platform bundle, game and language this ends up in a very large list. It's probably easier to have a look at [this list](https://gibberlings3.github.io/iesdp/file_formats/index.htm) instead and go by file extension.

**Comment by shinra-electric** [comment]
Is that a list of supported file formats for the game engine? 

So if I kept all the files with those extensions, I could delete the rest and it should still work? 

(I know some other source ports require keeping the main.exe file because it contained the mouse cursor images..)

**Comment by MarcelHB** [comment]
Give it a try, feel to report if anything breaks this assumption.

**Comment by shinra-electric** [comment]
So I just tried with BG2... 

I kept the following folders intact: 

- characters
- data
- music
- override
- script compiler
- scripts
- sounds

And I also kept these files in the main directory: 
- Chitin.key
- dialog.tlk
- keycap.ini
- Language.txt

I was able to go in game with just these files, and I didn't notice any difference. Can some of these be removed also? 

Regarding the script compiler and scripts folder, the list you sent did not have support for these .bs files. I assume these were used for scripting in the original game. Are these used in GemRB?

**Comment by lynxlynxlynx** [comment]
BS are BCS files, so don't delete them if you want to use party AI. None of this will save you any noticeable space though.

**Comment by shinra-electric** [comment]
Thank, I restored from backup. 

It's not really about saving space, it's more about being OCD.

**Comment by lynxlynxlynx** [comment]
Basically you can remove any GOG-specific stuff (usually obviously named), exes and dlls (if you never plan to run them), and documentation (licenses, readmes etc.). All candidates are in the top dir, you can kill `mplayer/` if present and `temp/`, `tempsave/`, `cache`.

**Comment by lynxlynxlynx** [comment]
Feel free to create a wiki page with your final lists. In the meanwhile I'm closing this issue.
