### ISSUE TITLE
 [IWD1] wrong life point, continuation of #1339

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1589]
Bug #1339 doesn't seem to be resolved, but there something new (?) : 

By example with nominee (see included save) when sleeping :
- You get 80 max life point as in record
- You get 53 life point and even if you have more before sleeping

#### Save
[000000001-Quick-Save.zip](https://github.com/gemrb/gemrb/files/8224304/000000001-Quick-Save.zip)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Looks like we're mishandling the constitution bonus in this case.

**Comment by lynxlynxlynx** [comment]
Stepping through it looks like something went wrong with the stats refactoring, as the old stats are bad, but I'm still bisecting to verify.

**Comment by lynxlynxlynx** [comment]
Yeah, it was 715baba19 and the stuff pointed out in the commit mails. But you've also found a corner cased missed in #1339 — regeneration items allowed one hp more than the max. All fixed now.
