### ISSUE TITLE
[feature] NPCs should have white circles when vocalizing

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#159]
**Description**
I don't know all the circumstances under which this is supposed to happen, but generally speaking, when an NPC talks into the wild without a prior interaction, its circle should turn white and oscillating for the time of the sound file playing. 

**Additional context**
Here, you see what I mean (BG, candlekeep, singing priests) in the original game:
![people_talking](https://user-images.githubusercontent.com/238558/62584061-4783fd80-b8b3-11e9-8d33-5b1b01ee417a.jpg)

**Comment by lynxlynxlynx** [comment]
We already do this for proper dialog, but at least Actor::VerbalConstant should trigger it too. 

The color is eventually set in Actor::SetCircleSize.
