### ISSUE TITLE
Fail to touch Remorhaz with melee weapon

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#1590]
In HOW (IWD1), nearly all attack with melee weapon doesn't occur as if character can't go enough close of monster and if there is already a character in front of monster other can't go close at all

All I can see in log is : [WalkTo/DEBUG]: brutas: Path was just abandoned

or is it something else ?

Position: ar9501 [1883.840]

#### Steps to reproduce
1. load save and enter cave or go to ar9501 [1883.840]
2. attack Remorhaz with melee weapon

#### Save
[000000001-Quick-Save.zip](https://github.com/gemrb/gemrb/files/8224609/000000001-Quick-Save.zip)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
I can see it happening some times, yes. Apparently the pathfinding and weapon range code disagree about what's close enough.
