### ISSUE TITLE
Assertion crash in bg, when escaping character colour picker

### ISSUE THREAD

**Issue by TheCycoONE** [gemrb/gemrb#1595]
#### Bug description
Crash during character colour selection in an unmodified baldur's gate. (GOG) The system is a Samsung Chromebook Plus (aarch64) running archlinuxarm.

```
emrb: /usr/src/debug/gemrb-0.9.0/gemrb/core/GUI/Window.cpp:501: bool GemRB::Window::DispatchEvent(const GemRB::Event&): Assertion `target == nullptr || target->IsVisible()' failed.
zsh: IOT instruction (core dumped)  gemrb -c .gemrb/gemrb.cfg
```

#### Steps to reproduce
1. Launch game, start a new game
2. Fill in race, alignment, skills, etc.
3. Open the colour select (e.g. click on major color)
4. Press [Esc] key

#### Expected behavior
Should not have crashed, maybe the color selection closes leaving the last colour.

GemRB version (check as many as you know apply)
- [ ] master as of this issue
- [x] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Thanks, this is still reproducible on master.
