### ISSUE TITLE
[bg] No response targetting NPCs

### ISSUE THREAD

**Issue by TheCycoONE** [gemrb/gemrb#1596]
#### Bug description
Start Baldur's gate, enter the inn, and attempt to talk to the various NPCs. Sometimes the first few respond but eventually I cannot talk to anyone. The amount of tie until this happens seems variable. I believe attacking and spell casting is also affected though I haven't spent as much time trying to reproduce.

I am running GemRB from the build directory on aarch64 (Samsung Chromebook Plus). I have tested BG with and without the fixpack, and gemrb with and without OpenGL.

```
Levels (average: 1):
FIGHTER: 1    
current HP:25
Mod[IE_ANIMATION_ID]: 0x6102 ResRef:CDMF1 Stance: 1
TURNUNDEADLEVEL: 0 current: 0
Colors:       454761243   656877351   825307441   1431655765   370546198   387389207   67372036
WaitCounter: 0
LastTarget: 0 <NULL>    LastSpellTarget: 0 <NULL>
LastTalked: 0 <NULL>
INVENTORY:
10: FIST - (1 0 0) Fl:0x2029 Wt: 0 x 0Lb
35: STAF01 - (1 0 0) Fl:0x2e61 Wt: 0 x 4Lb
Equipped: 0       EquippedHeader: 0
Total weight: 4
SPELLBOOK:
EFFECT QUEUE:
  0: 0x07: Color:SetPalette (22, 20) S:STAF01
  1: 0x07: Color:SetPalette (27, 16) S:STAF01

[GameScript/ERROR]: Target object: Object: =DP�U\f�"4�
```

#### Steps to reproduce
1. Launch gemrb with Baldur's Gate
2. Create or import a character and start the game
3. Enter the Inn (though it happens outside as well)
4. Talk to characters until the problem happens. In my experience this is pretty quick, e.g. I've never been able to talk to Elvenbeard.

#### Expected behavior
Expect character dialog to come up

GemRB version (check as many as you know apply)
- [x] master as of this issue (42e6211b7a5435b32ec0af34c94391c394be03f8)
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Huh. What do you mean by "I cannot talk to anyone", what happens?

**Comment by lynxlynxlynx** [comment]
Oh crap, I can reproduce this. There's some garbage in the object fields.

**Comment by TheCycoONE** [comment]
Yeah, I pasted what appeared to be the relevant log line. From there I was thinking ASAN or something might be needed if it's a memory issue. If you need anything else from me I can try to help.

**Comment by lynxlynxlynx** [comment]
It's uninitialized memory, so I've made a mistake in c5eb26223 — going on from "All members that are not initialized explicitly are zero-initialized" and a warning from a static analyzer. Not sure what gives, but I've just reverted it.

**Comment by TheCycoONE** [comment]
Thanks. Fixes for me too.
