### ISSUE TITLE
[bg] Delete save doesn't dialog doesn't update

### ISSUE THREAD

**Issue by TheCycoONE** [gemrb/gemrb#1597]
#### Bug description
In Baldur's Gate on the latest master when you click delete on a save you get a confirm dialog. Clicking to confirm does not appear to do anything in the UI, the save is still there. After opening the game again you will see the save is gone.

Traceback:
```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/stephen/gemrb/gemrb/GUIScripts/GUILOAD.py", line 196, in DeleteGameConfirm
[Python/ERROR]:     ScrollBarUpdated (ScrollBar)
[Python/ERROR]:   File "/home/stephen/gemrb/gemrb/GUIScripts/GUILOAD.py", line 86, in ScrollBarUpdated
[Python/ERROR]:     ActPos = sb.Value + i
[Python/ERROR]: TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

Traceback 2:
```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/stephen/gemrb/gemrb/GUIScripts/GUILOAD.py", line 190, in DeleteGameConfirm
[Python/ERROR]:     GemRB.DeleteSaveGame(Games[Pos])
[Python/ERROR]: IndexError: list index out of range
```

#### Steps to reproduce
1. Start a new game, import or create character
2. Save in a new slot (or 2 or 3)
3. Quit the game
4. Start the game again, click single player, load game
5. Click the delete button on your save and click confirm
6. Observe traceback in log, and save is not removed from the UI
7. Cancel and quit the game
8. Start the game again and load a save, note the save is gone.

#### Expected behavior
Save should be removed from the list after confirming delete.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by TheCycoONE** [comment]
Note: The same issue can be observed on the load game dialog in game, but the save game dialog delete button works as expected.

**Comment by lynxlynxlynx** [comment]
I didn't get the python errors, but the GUI was kinda stuck. Deleting seems to work fine now (tried at the end, the middle).
