### ISSUE TITLE
[bg] Map doesn't change when Obe teleports me 

### ISSUE THREAD

**Issue by TheCycoONE** [gemrb/gemrb#1601]
#### Bug description
In candlekeep at the south east corner Obe offers to train you by fighting magical monsters. When he teleports you away, the actors disappear (including the player) but the map doesn't change back to the outside, effectively blocking any further game play.

#### Steps to reproduce
1. Go to south east corner of candlekeep and agree to train
2. Select one or more of the other party members, so that the player character is not selected.
3. When prompted ask to be teleported out

#### Expected behavior
Should be teleported back to the surface map

#### Screenshots
![2022-04-07_22-04-1649385608](https://user-images.githubusercontent.com/823433/162352739-2a80f231-596d-4cfb-843e-9d46b10df44f.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
If you click on the player portrait, does the map properly change back to outside?

**Comment by TheCycoONE** [comment]
Yes it does - thanks!

**Comment by TheCycoONE** [comment]
Tested the original and I'm automatically selected and teleported after the dialog there.

**Comment by lynxlynxlynx** [comment]
Of course. :) So there appears to be some action competition now; we've had problems like this before in some cutscenes, so we already ship some workarounds.

**Comment by lynxlynxlynx** [comment]
Is this reproducible for you? If I save inside, it works as expected. If I don't, the viewport ends up near the inn, but on the correct map.

**Comment by TheCycoONE** [comment]
Yes I can reproduce every time, but I skipped a step. I select one of the magically created party members (not myself) before the dialog comes up.

**Comment by lynxlynxlynx** [comment]
Ah, so nobody is selected at that point. Easier to differentiate then.

**Comment by TheCycoONE** [comment]
Yes, I was wondering if that was even a valid state but I hadn't gotten to testing

**Comment by lynxlynxlynx** [comment]
It is, I wondered the same before and tried it even in normal circumstances.
