### ISSUE TITLE
[bg] Fuller does not detect the bolts in my inventory 

### ISSUE THREAD

**Issue by TheCycoONE** [gemrb/gemrb#1602]
#### Bug description
Fuller's dialog tells me that I have no bolts even though I bought them and they are in my inventory.
There seems to be a problem handling the script.

I am playing Baldur's Gate with the bgfixpack.

```
[ResourceManager]: Found 'fuller.dlg' in 'Override'.
[GameScript/ERROR]: Invalid scripting trigger: !partyhasitem("sw1h12")
[DLGImporter/WARNING]: Can't compile trigger: !PartyHasItem("SW1H12")
[GameScript/ERROR]: Invalid scripting trigger: !hasitem("bolt01",lasttalkedtoby)
[DLGImporter/WARNING]: Can't compile trigger: !HasItem("BOLT01",LastTalkedToBy)
[GameScript/ERROR]: Invalid scripting trigger: !hasitem("bolt01",lasttalkedtoby)
[DLGImporter/WARNING]: Can't compile trigger: !HasItem("BOLT01",LastTalkedToBy)
[GameScript/ERROR]: Invalid scripting trigger: !hasitem("bolt01",lasttalkedtoby)
[DLGImporter/WARNING]: Can't compile trigger: !HasItem("BOLT01",LastTalkedToBy)
[GameScript/ERROR]: Invalid scripting trigger: !hasitem("bolt01",lasttalkedtoby)
[DLGImporter/WARNING]: Can't compile trigger: !HasItem("BOLT01",LastTalkedToBy)
```

#### Steps to reproduce
1. Go to barracks in Candlekeep, and tell Fuller that you will do a quest for him
2. Buy bolts from Inn and return to Fuller
3. Talk to Fuller

#### Expected behavior
Should give him bolts and collect reward

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

Save: 
[888888891-bolts.tar.gz](https://github.com/gemrb/gemrb/files/8456179/888888891-bolts.tar.gz)

**Comment by TheCycoONE** [comment]
This is a regression, it worked in d1105d85bccc406d1a81b9a14c2c4c72f6e415d2

I'll do a bisect on the weekend if you don't find it before me.

**Comment by lynxlynxlynx** [comment]
Looks like a regression in the dialog parsing code; the actions and triggers there are plain text, not compiled like in scripts. And curiously all the errors are with negated triggers.
