### ISSUE TITLE
 [bg] "Unable to create cache directory" error

### ISSUE THREAD

**Issue by jheronimus** [gemrb/gemrb#1605]
I'm trying to run BG1 and BG2 using GemRB on my Mac.

My system is an M1 MacBook Air running Mac OS 12.3.1

My game files are from GOG Mac versions. I've installed the games using GOG Galaxy, opened the app bundles and extracted the Wine folders from them to a new separate folder (~/Games/).

Whenever I've tried running the game using 0.9, I get a "Fatal Error in Core/Unable to create cache directory './Cache2'" error. Attached a screenshot for that.

<img width="859" alt="Screenshot 2022-04-10 at 21 20 26" src="https://user-images.githubusercontent.com/108759/162634024-ae25601a-d663-4e9d-986c-4832de67ef12.png">

I've also tried running the latest dev build (gemrb-2022-04-09337911a). Under that version just pressing "Launch" doesn't do anything, but if I enable logging, I get "Fatal Error in Core, Missing GUI Script Engine." 
message.

Also note that there's a typo in "Prefrences" window title (should be "Preferences")

**Comment by lynxlynxlynx** [comment]
CocoaWrapper has code for setting CachePath, but perhaps that's obsolete since `launchGame` uses InterfaceConfig without files.

What's wrong with the current build will require delving deeper.
