### ISSUE TITLE
[bg] Color picker not properly applied to character view

### ISSUE THREAD

**Issue by TheCycoONE** [gemrb/gemrb#1606]
#### Bug description
The effect of the four colour options in the original game closely resemble their labels on the character view in the colour picker. In GemRB the same options update other aspects of the character or have no effect. In game the colours appear to be correct.

#### Steps to reproduce
1. Launch the game and create a new character
2. Pick distinctive recognizable major and minor colours in the colour picker
3. Observe the character view in the screenshot does not reflect those colours, e.g. the male halfling thief always has green gloves.

#### Expected behavior
Expect GemRB screenshots to match the original game below

#### Screenshots
Original Game - Female Elf Cleric
![Tales of the Sword Coast 2022-04-10 6_28_02 PM](https://user-images.githubusercontent.com/823433/162642928-46eb793f-79e2-4e6a-8153-b61a09080747.png)
![Tales of the Sword Coast 2022-04-10 6_28_44 PM](https://user-images.githubusercontent.com/823433/162642931-bb7b594b-8d2a-4f66-b733-c7ed0717d3e7.png)

Original Game - Male Halfling Thief
![Tales of the Sword Coast 2022-04-10 6_24_40 PM](https://user-images.githubusercontent.com/823433/162642952-6cb2820b-0163-4e38-acc0-6b072ef0b77e.png)
![Tales of the Sword Coast 2022-04-10 6_30_41 PM](https://user-images.githubusercontent.com/823433/162642957-dfa415ef-3961-46d0-aaee-2d705fd5f9ee.png)

GemRB - Female Elf Cleric
![2022-04-10_19-04-1649632557](https://user-images.githubusercontent.com/823433/162644122-7a5fb392-9016-4ec7-9bed-78939c5986d8.png)
![2022-04-10_19-04-1649632589](https://user-images.githubusercontent.com/823433/162644125-1597e231-ca2e-4d16-aac3-8aaaa1ee61bd.png)

GemRB - Male Halfling Thief
![2022-04-10_19-04-1649632746](https://user-images.githubusercontent.com/823433/162644208-2bff707c-1570-4f23-ab0e-bc602c5619e3.png)
![2022-04-10_19-04-1649632767](https://user-images.githubusercontent.com/823433/162644215-574c6680-1b3f-47d6-8df0-1872178c0c7b.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by TheCycoONE** [comment]
This is a regression over v0.90

**Comment by TheCycoONE** [comment]
git bisect blames e91dee1d8691e33575bb08bae20c570504776206

@bradallred - could you explain what's going on in that commit.

**Comment by lynxlynxlynx** [comment]
Yeah, I noticed this while fixing that assertion bug. The code path is almost identical for bg2, where it works fine, so this is quite curious.
