### ISSUE TITLE
[bg1][bg2][p:t] Some ingame strings have a bad encoding when using Polish dialog.tlk

### ISSUE THREAD

**Issue by Emwues** [gemrb/gemrb#1611]
#### Bug description
While a lot of strings display fine, both with "Encoding=polish" cfg option set as well as without, some do not(again, regardless of encoding setting), mostly in GUI.

#### Steps to reproduce
1. Download [Polish tlks](https://github.com/gemrb/gemrb/files/8721217/dialogs.zip)
2. unzip
3. replace original dialog.tlk and dialogf.tlk(where applicable) with the Polish ones in GamePath
4. run GemRB

#### Expected behavior
GemRB should display strings correctly

#### Screenshots
P:T is an interesting one, game menu has both correctly("Zapisz grę" = save game) and incorrectly(should be "Wczytaj grę" = load game) encoded strings:
![busted-pt](https://user-images.githubusercontent.com/105691089/169165128-90cb909f-3024-4f78-9095-049b0817ea94.png)
classic for comparison:
![correct-pt](https://user-images.githubusercontent.com/105691089/169165419-2b3908f2-0fb4-4e84-a9bc-5b19bb77261d.png)
Record screen is almost unreadable:
![busted-pt2](https://user-images.githubusercontent.com/105691089/169165688-82933124-6bb8-4f02-b36b-98a7fe9b3c55.png)
classic:
![correct-pt2](https://user-images.githubusercontent.com/105691089/169165833-c2fe0693-f27e-48c2-aeb4-9b35d0f4527b.png)
Same in BG1:
![busted-bg](https://user-images.githubusercontent.com/105691089/169165981-15e74744-a640-4a10-8184-bbbaa3d7a9f1.png)
classic:
![correct-bg](https://user-images.githubusercontent.com/105691089/169166068-41519b29-6288-4947-98b7-a4464cd9f859.png)
and ToB:
![busted-tob2](https://user-images.githubusercontent.com/105691089/169166174-f95fb7b7-048a-4e65-9053-b4cecaaaefe4.png)

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many
 as you know apply)
- [ ] SDL1.2
- [X] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Maybe some manual mappings have to be added to polish.ini (sounds like it's not cp1250 encoded), but also, we know we still have some problems with non-ascii text. That's tracked elsewhere.

We used to support manual overrides until recently, when that got removed in #1532.

**Comment by Emwues** [comment]
As far as I know, with the exception of BG1 which was very wild as far as non-English versions go, all non-Asian IE games use some win encoding - English, German, French, Spanish and so on all use WIN-1252(which AFAIK, for alphabetic signs is functionally the same as ISO-8859-1, but differs in some upper regions), all Central European are on WIN-1250 (I'm 100% sure about Polish, but it is true for Czech too, IIRC), and from what I heard, all Cyrillic versions are on WIN-1251.

This is not really surprising too, since the Windowses used to develop those only supported WIN encodings(that's certainly true for  DOS based 95, 98, 98SE and Me as well as then-current NT 4.x and Windows 2000), as Microsoft was back then in the "fight-all-standards-that-didn't-came-from-Microsoft" mode(any one remembers the IE 4.x and HTML standard one? That was "fun") and that included the ISO-8859 standard too.

This specific problem through, looks to me like a problem of treating a UTF-8 string as WIN-1250 encoded, if I take the string `@2592  = ~Wczytaj grę~`, convert it to UTF-8 and then load it into text editor as if encoded with WIN-1250, I get: `@2592  = ~Wczytaj grÄ™~` which matches the P:T screenshot, so it seems that somewhere in GemRB WIN-1250 is enforced on those strings affected even though they were already converted to UTF-8 earlier, I think. Then again, I might talk out of whack here, since not a programmer and all that. ;)

**Comment by bradallred** [comment]
Right, we are aware of these issues and they will eventually be resolved with #1516 

It is useful to know what encodings we need to convert from when we finally reach that bridge.

**Comment by burner1024** [comment]
Any workaround or quick hack meanwile?

**Comment by burner1024** [comment]
I tried launching with `LC_ALL=en_US.iso88591`. It fixes some issues, while others remain.

No LC mod (`en_US.UTF-8`):
![Captura desde 2023-05-20 17-15-46](https://github.com/gemrb/gemrb/assets/1279852/386d0e79-2c49-4eab-8122-5ae26b96c5c9)

`en_US.iso88591`:
![Captura desde 2023-05-20 17-16-15](https://github.com/gemrb/gemrb/assets/1279852/2c5656f9-0fb4-4a99-a98f-e134bdacb996)
