### ISSUE TITLE
 Static assertion error in strtounsigned

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1616]
I tried to compile the latest revision with MSYS2/GCC v12.1. It fails because of the following static assertion:

```
[  1%] Building CXX object gemrb/core/CMakeFiles/gemrb_core.dir/Interface.cpp.obj
In file included from D:/Sources/gemrb/gemrb/core/Audio.h:26,
                 from D:/Sources/gemrb/gemrb/core/Interface.h:32,
                 from D:/Sources/gemrb/gemrb/core/Interface.cpp:21:
D:/Sources/gemrb/gemrb/includes/globals.h: In instantiation of 'T GemRB::strtounsigned(const char*, char**, int) [with T = long long unsigned int]':
D:/Sources/gemrb/gemrb/core/TableMgr.h:72:30:   required from 'RET_T GemRB::TableMgr::QueryFieldUnsigned(const ROW_T&, const COL_T&) const [with RET_T = long long unsigned int; ROW_T = long long unsigned int; COL_T = int]'
D:/Sources/gemrb/gemrb/core/Interface.cpp:553:80:   required from here
D:/Sources/gemrb/gemrb/includes/globals.h:220:33: error: static assertion failed: Type is too big for conversion.
  220 |         static_assert(sizeof(T) <= sizeof(long), "Type is too big for conversion.");
      |                       ~~~~~~~~~~^~~~~~~~~~~~~~~
D:/Sources/gemrb/gemrb/includes/globals.h:220:33: note: the comparison reduces to '(8 <= 4)'

```

**Comment by MarcelHB** [comment]
https://github.com/gemrb/gemrb/blob/b344079ac5979962a9b6b02fc6207a73549cdce2/gemrb/core/Interface.cpp#L553
Do we see a good reason for `size_t`? The table values should be something fixed like `uint32_t` (or 64), I presume?

https://github.com/gemrb/gemrb/blob/b344079ac5979962a9b6b02fc6207a73549cdce2/gemrb/includes/globals.h#L220
Similarly, maybe replace `long` by something static as well to avoid platform confusion?

**Comment by bradallred** [comment]
`uint16_t` is good enough for this particular call. There are probably others of different sizes.

> Similarly, maybe replace long by something static as well to avoid platform confusion?

I dont care if we nix that assert at this point. It was there so I could detect all the callers that were using inappropriate types at the time it was written. However, you shouldn't just change the `long` to something else since `strtol` explicitly returns a `long`.
