### ISSUE TITLE
[bug] Blending issues in PST, AR1202

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#163]
**Describe the bug**
Enter AR1202 to notice a blending issue of that altar-thing, and some red-ish whatever artifcat that I cannot identify (Ignus' remainings after defeat?).

GemRB version: `HEAD` of right now.

**To Reproduce**
1. Enter AR1202 of PST.
2. Look around

**Expected behavior**
See here:

![pst_blending_good](https://user-images.githubusercontent.com/238558/62827507-5975e100-bbd0-11e9-814f-b79958777661.jpg)

**Screenshots**
See here:
![pst_blending_bad](https://user-images.githubusercontent.com/238558/62827518-6bf01a80-bbd0-11e9-92c8-ddc65c50e153.jpg)

**Comment by MarcelHB** [comment]
Yep, InfExp tells met it's Ignus, so we can primarily fix that animation.

**Comment by MarcelHB** [comment]
I think I got something: PST interprets the map's area animation flags differently.

In this example, there are A1202GB{1-4}, and their area animation bits are set to 0x2519. According to this [description](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Anim), there are already two obvious misinterpretations:

1. Bit 1 is set to 0, so do not blend over blackness. Actually, we want exactly that to fix this bug. The result is then visually Ok.
2. Bit 4 is set to 1, so stop after some frame (that 0x0032 is non-zero). Erroneously, the animation stops shortly after starting, but it should run indefinitely.

Maybe I can try to bit-flip things tomorrow to observe obvious effects in the original PST.

**Comment by lynxlynxlynx** [comment]
Yeah, this must be the "the gem in his [Ignus'] room does not animate and it is opaque." report from the area-by-area investigation by chiv.

These are the set bits: 1 4 5 9 11 14
14 is out of our range, so please definitely try toggling that in the original.

It seems unlikely that 1 and 9 would be completely different in pst. I'll go write an iesh script to see if any other outliers are set anywhere.

**Comment by lynxlynxlynx** [comment]
Looks like that bit is the only one out of range ever set and not that often:
> A: AR1201 Anim name: A1201G1R
>    Anim flags: 9625 Only high bits: 8192
> A: AR1201 Anim name: A1201G3R
>    Anim flags: 9625 Only high bits: 8192
> A: AR1201 Anim name: A1201G1L
>    Anim flags: 9625 Only high bits: 8192
> A: AR1201 Anim name: A1201G1R
>    Anim flags: 9625 Only high bits: 8192
> A: AR1202 Anim name: A1202GB2
>    Anim flags: 9497 Only high bits: 8192
> A: AR1202 Anim name: A1202GB3
> Anim flags: 9497 Only high bits: 8192
>    Anim flags: 9497 Only high bits: 8192
> A: AR1202 Anim name: A1202GB4
>    Anim flags: 9497 Only high bits: 8192

**Comment by MarcelHB** [comment]
Ok, I sampled some of the animations I found to maybe find any kind of pattern:

```
|Where/What                                        |Flags |13 |12 |11 |10 |9  |8  |7  |6  |5  |4  |3  |2  |1  |0  |Notes                                            |
|--------------------------------------------------|------|---|---|---|---|---|---|---|---|---|---|---|---|---|---|-------------------------------------------------|
|AR0201 (Mortuary) / AR0202F1 (fire)               |0x101 |   |   |   |   |1  |   |   |   |   |   |   |   |   |1  |                                                 |
|AR0207 (Tomb) / DEADMLC7 (corpse)                 |0x1   |   |   |   |   |   |   |   |   |   |   |   |   |   |1  |                                                 |
|AR0403 (Tenement) / A0403_F1 (torch)              |0x191 |   |   |   |   |   |1  |1  |   |   |1  |1  |   |   |1  |                                                 |
|AR0405 (Alley) / ALLEY_S (stone face)             |0x0   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |no frames, programmatic reset?                   |
|AR0502 (Foundry) / A0502Bx (liquid metal)         |0x29  |   |   |   |   |   |   |   |   |1  |   |1  |   |   |1  |                                                 |
|AR0508 (Sub city cave) / A0508Txx (glow)          |0x101 |   |   |   |   |1  |   |   |   |   |   |   |   |   |1  |                                                 |
|AR0509 (Print shop) / A0509_Gx (machine parts)    |0x19  |   |   |   |   |   |   |   |   |   |1  |1  |   |   |1  |                                                 |
|AR0606 (Sensorium) / A0606G1x (stones)            |0x39  |   |   |   |   |   |   |   |   |1  |1  |1  |   |   |1  |                                                 |
|AR0608 (Museum) / AR0608x (Objects)               |0x19  |   |   |   |   |   |   |   |   |   |1  |1  |   |   |1  |                                                 |
|AR0702 (Trias prison) / sword                     |0x99  |   |   |   |   |   |   |1  |   |   |1  |1  |   |   |1  |                                                 |
|AR1201 (Fortress, entry) / AR1201Gx (pits)        |0x1599|   |1  |   |1  |   |1  |1  |   |   |1  |1  |   |   |1  |semi-transparent glowing/darkening by brightness?|
|AR1202 (Fortress, Crystal) / AR1202GBx (Crystal)  |0x2519|1  |   |   |1  |   |1  |   |   |   |1  |1  |   |   |1  |black as transparency                            |
|AR13xx (Modrom Maze) / A130101x (door gears)      |0x99  |   |   |   |   |   |   |1  |   |   |1  |1  |   |   |1  |                                                 |
|AR1501 (Throne room) / AR1501K (throne dude)      |0x1   |   |   |   |   |   |   |   |   |   |   |   |   |   |1  |                                                 |
|AR1501 (Throne room) / AR1501N (throne dude dead?)|0x0   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |                                                 |
|AR1601 (Rats' throne) / CRATEYEx (glowing eyes)   |0x1   |   |   |   |   |   |   |   |   |   |   |   |   |   |1  |                                                 |
|AR1906 (Maze) / effect_x (Portals)                |0x1   |   |   |   |   |   |   |   |   |   |   |   |   |   |1  |                                                 |
```
For the AR1201 pits, GemRB already knows the required blending mechanism, yet it's somehow not the PST flag style to switch on:

![pit_gemrb](https://user-images.githubusercontent.com/238558/62833362-dee3aa80-bc3d-11e9-86d7-28a12b2a1f8f.jpg)

original:

![pit_original](https://user-images.githubusercontent.com/238558/62833365-e4d98b80-bc3d-11e9-955f-5beeb37d7a41.jpg)

I will later try to manipulate bits and check the other things, also with the doc.

**Comment by MarcelHB** [comment]
So, that's what I found by comparing animations side by side, as far as possible (I don't know any way to move around areas in native PST):
```
|Where/What                                        |Flags |GemRB                                            |Game                    |
|--------------------------------------------------|------|-------------------------------------------------|------------------------|
|AR0201 (Mortuary) / AR0202F1 (fire)               |0x101 |moving, also when under fow                      |looks better blended    |
|AR0207 (Tomb) / DEADMLC7 (corpse)                 |0x1   |ok                                               |(not tested)            |
|AR0403 (Tenement) / A0403_F1 (torch)              |0x191 |gone under fow                                   |under fow               |
|AR0405 (Alley) / ALLEY_S (stone face)             |0x0   |fades in brokenly twice, but the gone again      |                        |
|AR0502 (Foundry) / A0502Bx (liquid metal)         |0x29  |not moving                                       |moving under fow        |
|AR0508 (Sub city cave) / A0508Txx (glow)          |0x101 |probably okay                                    |looks better blended    |
|AR0509 (Print shop) / A0509_Gx (machine parts)    |0x19  |not moving                                       |moving                  |
|AR0606 (Sensorium) / A0606G1x (stones)            |0x39  |not moving                                       |moving under fow        |
|AR0608 (Museum) / AR0608x (Objects)               |0x19  |not moving                                       |moving under fow        |
|AR0702 (Trias prison) / sword                     |0x99  |not moving                                       |(not tested)            |
|AR1201 (Fortress, entry) / AR1201Gx (pits)        |0x1599|not blending correctly, not under fow, not moving|looks good              |
|AR1202 (Fortress, Crystal) / AR1202GBx (Crystal)  |0x2519|not blending correctly, not moving               |looks good              |
|AR13xx (Modrom Maze) / A130101x (door gears)      |0x99  |not moving                                       |(not tested)            |
|AR1501 (Throne room) / AR1501K (throne dude)      |0x1   |ok, not moving anyway                            |(not tested)            |
|AR1501 (Throne room) / AR1501N (throne dude dead?)|0x0   |(not tested)                                     |(not tested)            |
|AR1601 (Rats' throne) / CRATEYEx (glowing eyes)   |0x1   |looks good, but not randomized! works under fow  |rotating more randomized|
|AR1900 (Maze) / effect_x (Portals)                |0x1   |(did not know how to trigger)                    |(not tested)            |
```

And then also what I found out by playing around with bits on that crystal glow animation:
```
|What                                              |13          |12                                               |11          |10                      |9           |8                                 |7           |6           |5           |4           |3                        |2           |1                  |0       |
|--------------------------------------------------|------------|-------------------------------------------------|------------|------------------------|------------|----------------------------------|------------|------------|------------|------------|-------------------------|------------|-------------------|--------|
|GemRB/Doc                                         |?           |combat switch                                    |mirroring   |palette                 |frame subset|cover                             |slow PCs    |covered     |random start|sync.       |stopping                 |illumination|black handling     |enabled |
|PST                                               |?           |mirroring                                        |unused?     |?                       |?           |?                                 |?           |unused?     |?           |?           |height related           |unused?     |enabled but unused?|to show |
|AR1202GB3                                         |bad blending|mirror effect                                    |bad blending|bad blending            |bad blending|Crash! No crash if 0x0032 set to 0|bad blending|bad blending|bad blending|bad blending|Z fighting + bad blending|bad blending|supoptimal blending|rendered|
```

Well, some suggestion: We make sure that the known area animation flags don't apply in case of PST (as it breaks more things), and instead focus on the bits that seem to add the visible effects (display, blending, mirroring)

**Comment by lynxlynxlynx** [comment]
Yeah, please continue. Once you find a bit that doesn't do any good at all, I can easily pull up all the animations using it and recheck.

There's definitely something extra needed wrt blending — I remember fixing something about the portal animation, but it was still not ideal (44021da44). One is already on the upper level of the Mortuary, but you have to have the correct stats to learn about it.

PS: here's a bunch of saves from the original: http://eowyn.cz/gemrb/pst/saves/

**Comment by lynxlynxlynx** [comment]
Also, here's how NI labels the bits (with the 13/14 in EE style): https://github.com/NearInfinityBrowser/NearInfinity/blob/fabd7da51fe4be0e23c33a781f984a47d4d66542/src/org/infinity/resource/are/Animation.java#L39

**Comment by MarcelHB** [comment]
Interesting, thanks. I'll look into the other games and NI, too, to check that.

**Comment by lynxlynxlynx** [comment]
Here's the actual drawing code and it nicely ignores some bits (just check the rest of the isTorment mentions):
https://github.com/NearInfinityBrowser/NearInfinity/blob/fabd7da51fe4be0e23c33a781f984a47d4d66542/src/org/infinity/resource/are/viewer/LayerObjectAnimation.java#L199

**Comment by MarcelHB** [comment]
Ok yes, in addition:
- don't treat 0x80 as A_ANI_NOT_IN_FOG, otherwise the torches in AR0403 and pits in AR1201 go away under FoW, just never set
- don't treat 0x100 as A_ANI_BACKGROUND, as PST seems to use some different, black-based blending algorithm then, as you can see here:

![ar0508_set](https://user-images.githubusercontent.com/238558/63217397-4ae67700-c146-11e9-9b9a-c82904feead9.jpg)

Bits 1, 2, 6, 11 don't seem to be used at all, ans for the rest of bits, I do not find anything too conclusive yet. Maybe somebody starts to notice if the low hanging fruits are fixed.

**Comment by lynxlynxlynx** [comment]
Nice! What area is the comparison from? Makes me wonder about the actual background and the bounds of the animations.

**Comment by MarcelHB** [comment]
It's in [AR0508](https://torment.fandom.com/wiki/Bones_of_the_Night_(Area)).

**Comment by lynxlynxlynx** [comment]
OK, so the river part is completely black, the waterfall rocky and the animation just slightly fading in&out.  Judging by the upper third (a0508tr1.bam), we don't blend it at all, so that's where the black splotch on the rock comes from. Its palette has the default color for transparency (green), so nothing useful there.

Did you try enabling our bit 2? Seems like treating black as transparent would help somewhat.

**Comment by MarcelHB** [comment]
Indeed, it looks better but I also noticed a little glitch (regardless of the flag, as you can see above already):

![ar0508_103_set](https://user-images.githubusercontent.com/238558/63229656-28666380-c203-11e9-8949-d9cb5b7eeb62.jpg)

**Comment by lynxlynxlynx** [comment]
Nice, it looks almost identical. 

I also noticed the clipping issue, but I can't explain it. There's nothing else there (z index doesn't matter), the searchmap has the same values, the bg pixels are of various colors, same for the fg (so not transparent), all the animation frames have the same geometry ... so where's the mask?

**Comment by MarcelHB** [comment]
From my understanding, for the other games, there is a distinct flag for that occlusion? IESDP says bit 6, NI does not know that one.

**Comment by lynxlynxlynx** [comment]
The wall polygons have an analogous flag bit (see comments around):
https://github.com/gemrb/gemrb/blob/f38b307fcd392415a1140d93441b97d5cab71551/gemrb/core/Polygon.h#L65

**Comment by MarcelHB** [comment]
Ok, then let's consider this a different issue for now.

**Comment by lynxlynxlynx** [comment]
Maybe, yeah. I guess toggling the wall bit in the animation doesn't help?

**Comment by MarcelHB** [comment]
No, I did not spot any visual impact by that bit.

**Comment by bradallred** [comment]
@MarcelHB was it considered that PST has perhaps a different bit layout for these flags in the ARE? the wall cover bit is still suspiciously missing, but it clearly isn't supposed to be always set either.

**Comment by MarcelHB** [comment]
The definetely have different flags, that's what we've been wiring into the code here. Yet, we have only identified very few of them - and were fine so far.

If you refer to some area/animation in particular, feel free to choose a bit from the table above.

**Comment by bradallred** [comment]
From the PR it doesn't look like any bits were identified; we just always set `(A_ANI_BLEND | A_ANI_SYNC)` and always clear `(A_ANI_PLAYONCE | A_ANI_NOT_IN_FOG | A_ANI_BACKGROUND)`. We don't seem to just be reading them from other bits like I would have thought. Am I missing something?

An example of an animation with an incorrect flag is above; the green chasm with the bridge has a wall polygon that should clearly be covering the animation. Leads me to think we are misinterpreting bits in PST.

**Comment by MarcelHB** [comment]
That's the essence, yes. Without these edge case pixels, the setup works.

So your example is bit pattern 0x101, the same as the torches in the mortuary. So maybe bit 9 is your animation cover, which conflicts to the description of IESDP for PST.

**Comment by bradallred** [comment]
Actually, if that has bits `0x101` then that means bit 6 is 0, which means walls should cover it according to iesdp. I wonder then, is that particular issue now fixed on subviews? maybe that was a blending issue rather than a bit issue.
