### ISSUE TITLE
[bg1] loading mission pack save doesnt transport entire party to AR1000

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1633]
Loading the mission pack save that comes with BG1 the party is supposed to get transported to AR1000 following a text screen. Currently, only PC1 is moved and the rest of the party get left behind.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

**Comment by lynxlynxlynx** [comment]
e4b0eb6 fixed the only-1 problem, but now the cutscene doesn't fire, sigh.
