### ISSUE TITLE
Multiple unresolved externals in GUIScript.dll using MSVC

### ISSUE THREAD

**Issue by jabaldwin** [gemrb/gemrb#1636]
I'm attempting to build GemRB from source following [the guide on the website](https://gemrb.org/MSVC-build.html#get-gemrb-sources-and-build-them). I encounter several "unresolved external" linking errors within GUIScript.cpp, which is odd since that file doesn't seem to have been updated since the v0.9.0 release. Any help is appreciated! 

Build output attached:
[gemrb_build_log.txt](https://github.com/gemrb/gemrb/files/9075071/gemrb_build_log.txt)

**Comment by MarcelHB** [comment]
> I encounter several "unresolved external" linking errors within GUIScript.cpp, which is odd since that file doesn't seem to have been updated since the v0.9.0 release. Any help is appreciated!

`GUIScript.cpp` has undergone [a lot of changes](https://github.com/gemrb/gemrb/compare/v0.9.0...master#diff-96ea9d8971dee67edce84478072a33a6730e52ef01fb174cfa0b7dda99cfacfe) since v0.9.0.

You can maybe execute a `git status` to check what revision you are really compiling on.

**Comment by jabaldwin** [comment]
Sorry, I must have read the history of GUIScript.cpp wrong, my mistake. I have tried compiling on the most recent commit to master and several slightly older commits, all with the same issues. Is there a particular commit that should be more "stable" re: being compile-able?

**Comment by MarcelHB** [comment]
The most recent commit rev [looks good](https://ci.appveyor.com/project/lynxlynxlynx/gemrb/builds/44121819) from what we see in MSVC 2019, and I wasn't seeing any linker problem locally either.

But I have found something suspicious, could you maybe give this modification a try (`ScriptEngine.h` line 57)?
```diff
diff --git a/gemrb/core/ScriptEngine.h b/gemrb/core/ScriptEngine.h
index 86e85c6c7..69f0daab4 100644
--- a/gemrb/core/ScriptEngine.h
+++ b/gemrb/core/ScriptEngine.h
@@ -54,7 +54,7 @@ public:
 };

 template <class T>
-class GEM_EXPORT ScriptingRef : public ScriptingRefBase {
+class ScriptingRef : public ScriptingRefBase {
 private:
        T* ref;
 public:
```

**Comment by jabaldwin** [comment]
That change got the build to succeed, thank you!

Now I'm having a problem immediately on running the app:
`The code execution cannot proceed because iconv-2.dll was not found.`

I checked, I installed libiconv through vcpkg before building, so I'm not sure why this is having trouble.

**Comment by MarcelHB** [comment]
From what I see, the program should use `libiconv.dll`, not `iconv-2.dll`.

No sure how it end ups there, but you could maybe look for the the first one and create a copy with the other name into the same directory of the executable.

**Comment by DudeMcDude** [comment]
> 

Ran into the same issue here

**Comment by DudeMcDude** [comment]
> From what I see, the program should use `libiconv.dll`, not `iconv-2.dll`.
> 
> No sure how it end ups there, but you could maybe look for the the first one and create a copy with the other name into the same directory of the executable.

Ran into the same issue here. Where is this specified?

**Comment by lynxlynxlynx** [comment]
We specify the first, from vcpkg here: platforms/windows/vcpkg_deps.cmake

Perhaps a system copy is present and gets picked up instead.

**Comment by DudeMcDude** [comment]
> We specify the first, from vcpkg here: platforms/windows/vcpkg_deps.cmake
> 
> Perhaps a system copy is present and gets picked up instead.

Looks like the vcpkg binary is named iconv-2.dll. No idea what determines this...
Not sure if relevant, but I'm using VS 2022.

**Comment by lynxlynxlynx** [comment]
Ah, I guess they changed it upstream then. In this mess one can see they redid the package build and it's also not called unofficial anymore: https://github.com/microsoft/vcpkg/commit/3a26eb3dc4d684ca6c1748dccc7a15684b9e8d0a
Looking at spatialite changes shows at minimum the .lib got renamed. And this build log confirms the dll rename:
https://github.com/microsoft/vcpkg/issues/25269

Does this fix it for you? http://sprunge.us/P14J04?diff

**Comment by DudeMcDude** [comment]
Just noticed that appveyor uses a cached older version (1.15-6), which must be why it works there.

Perhaps you should pin dependency versions?
https://github.com/microsoft/vcpkg/blob/master/docs/examples/versioning.getting-started.md

**Comment by lynxlynxlynx** [comment]
Not a bad idea, but because we cache the builds, it doesn't add much. We'll have to refresh the cache for changes either way. It does help developers like you though, so let's do it. 

Assuming my patch fixed the build for you, can you prepare this extra manifest (just use current latest versions)?

**Comment by DudeMcDude** [comment]
The following manifest worked for me (pinning libiconv to 1.15-6)

{
    "name": "gemrb",
    "version-string": "0.9.0",
    "dependencies": [
      "zlib",
      "sdl2",
      "sdl2-mixer",
      "python3",
      "openal-soft",
      "libpng",
      "libogg",
      "libvorbis",
      "freetype",
      {"name": "libiconv", "version>=": "1.15-6"}
    ],
    "builtin-baseline": "f93ba152d55e1d243160e690bc302ffe8638358e",
    "overrides": [
      {"name": "libiconv", "version": "1.15-6"}
    ]
  }

**Comment by lynxlynxlynx** [comment]
But why pin the old version, why skip 5 years of improvements?

**Comment by DudeMcDude** [comment]
Didn't realize it was that old 😆 anyway just wanted to confirm it works when set up that way, and to stick closer to the official build in case I ran into issues. I'll give it another go with the latest.

**Comment by lynxlynxlynx** [comment]
The idea is to bump the official builds once it's confirmed they're likely to work. ;)

**Comment by DudeMcDude** [comment]
Alright, verified the following manifest:
```
{
    "name": "gemrb",
    "version-string": "0.9.0",
    "dependencies": [
      "zlib",
      "sdl2",
      "sdl2-mixer",
      "python3",
      "openal-soft",
      "libpng",
      "libogg",
      "libvorbis",
      "freetype",
      "libiconv"
    ],
    "builtin-baseline": "f93ba152d55e1d243160e690bc302ffe8638358e",
    "overrides": [
      {"name": "sdl2", "version": "2.0.22#1"},
      {"name": "sdl2-mixer", "version": "2.6.1"},
      {"name": "openal-soft", "version": "1.22.2#1"},
      {"name": "libogg", "version": "1.3.5"},
      {"name": "libvorbis", "version": "1.3.7#2"},
      {"name": "freetype", "version": "2.12.1"},
      {"name": "libiconv", "version": "1.17"}
    ]
  }
```

**Comment by lynxlynxlynx** [comment]
Thanks! Too bad it has to be at the root of the source tree. Care to submit a PR, so we can credit you properly? You can bundle my dll update in the same commit.

**Comment by DudeMcDude** [comment]
Ok PR submitted, except now appveyor is using a cached vcpkg which doesn't recognize the builtin-baseline commit... can you update it?
