### ISSUE TITLE
Main character dead keep on loop. 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1639]
#### Bug description
When the main character is dead the game is on loop and not contuine to the death video.
On the log is this:
```
[Movable/WARNING]: Stance overridden by death
[Movable/WARNING]: Stance overridden by death
[Movable/WARNING]: Stance overridden by death
[Movable/WARNING]: Stance overridden by death
[Movable/WARNING]: Stance overridden by death
[String/WARNING]: Invalid UTF-8 character: 0x92
[Movable/WARNING]: Stance overridden by death
[Movable/WARNING]: Stance overridden by death
[Movable/WARNING]: Stance overridden by death
[Movable/WARNING]: Stance overridden by death
[Movable/WARNING]: Stance overridden by death
[Movable/WARNING]: Stance overridden by death
```
Not always happens, sometimes is correct and sometimes is not.

#### Steps to reproduce
1. Make the main character die.
2. See error

#### Expected behavior
Show the dead video.

#### Screenshots

https://user-images.githubusercontent.com/1820598/179116551-9b95885c-82d1-48dc-8e4b-6364af430acc.mp4

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Works for me when I ctrl-y the protagonist. Is this reproducible for you?

**Comment by bradallred** [comment]
I couldn't repro either, but I wonder if maybe reducing hp to exactly 0 would do it.

**Comment by lynxlynxlynx** [comment]
No, the IF_STOPATTACK check would catch it the same way. It has both the dying/dead bits in it, so there's not even a one tick window. These aren't saved though, so it could be a race in the importer.

**Comment by rsantellan** [comment]
Only happens when talking with the statue and getting killed by it, I upload my save game here: #1641

**Comment by lynxlynxlynx** [comment]
That works for me as well, though it looks like I botched up #1644 ... even with that fixed, suicide-by-statue works. Can you try with latest code again?

**Comment by rsantellan** [comment]
https://user-images.githubusercontent.com/1820598/180625482-3c46d7f4-2530-4d1d-b82f-840f7d3b3b98.mp4

@lynxlynxlynx  Using latest commit from master is the same.

**Comment by lynxlynxlynx** [comment]
Which mods do you have installed?

**Comment by rsantellan** [comment]
None, only the recommended https://gemrb.org/Common-problems.html#game-bugs fixpacks
```
// Log of Currently Installed WeiDU Mods
// The top of the file is the 'oldest' mod
// ~TP2_File~ #language_number #component_number // [Subcomponent Name -> ] Component Name [ : Version]
~DDRAWFIX/DDRAWFIX.TP2~ #0 #0 // DDrawFix -> Force DirectDraw Emulation: v1.0
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #0 // BG2 Fixpack - Core Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #1001 // BG2 Fixpack - Game Text Update -> GTU Classic (from Baldurdash, by Kevin Dorner): v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #3 // BETA Core Fixes (please check the readme!): v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #100 // Party Gets XP for Sending Keldorn to Reconcile With Maria: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #101 // Improved Spell Animations: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #103 // Mixed-Use Dagger Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #104 // Ghreyfain's Holy Symbol Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #106 // Giants Receive Penalties When Attacking Halflings, Dwarves, and Gnomes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #107 // Remove Dual-Classing Restriction from Archers and Stalkers: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #108 // Remove Second Attribute Bonus for Evil Path in Wrath Hell Trial: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #109 // Corrected Summoned Demon Behavior: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #110 // Additional Script Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #111 // Bard Song Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #112 // Wizard Slayers Cause Miscast Magic on Ranged Attacks: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #113 // Additional Alignment Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #114 // Change Free Action to Protect Against Stun: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #116 // Remove Thieving Start Bonuses from Bard and Ranger Skills: v13
// Recently Uninstalled: ~WIDESCREEN/WIDESCREEN.TP2~ #0 #1 // Widescreen Mod -> for GemRB: Widescreen Mod v3.07
```

**Comment by lynxlynxlynx** [comment]
I tried also with a ring of regeneration, but no dice. However I can reproduce with your save. :s

**Comment by rsantellan** [comment]
@lynxlynxlynx still happening..

https://user-images.githubusercontent.com/1820598/181386861-4c32f510-ab66-4857-9ea3-78dcf4bcd70a.mp4

**Comment by lynxlynxlynx** [comment]
I resaved your game for testing and it works there, but it's true that your original save still suffers. Interesting!
