### ISSUE TITLE
Music not starting on main menu. 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1640]
#### Bug description
Music is not starting on main menu. All the sound in the game are correct.

#### Steps to reproduce
1. Go to Main menu
2. See error

#### Expected behavior
Music should start playing.

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Looks like another string regression: 
`[MUSImporter]: Loading /media/games/bg2-gog/prefix/drive_c/GOG Games/Baldur's Gate 2/music...`
