### ISSUE TITLE
Umar hill no correct answer on ritual 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1641]
#### Bug description
On selecting the correct question it doesn't trigger the correct response.
The log is this:
```
[ResourceManager]: Found 'shaava01.dlg' in 'Override'.
[ResourceManager]: Found 'spell.ids' in 'Override'.
[ResourceManager]: Found 'boolean.ids' in 'chitin.key'.
[String/WARNING]: Invalid UTF-8 character: 0x9a
[String/WARNING]: Invalid UTF-8 character: 0x92
[ResourceManager]: Found 'GUIW10.chu' in 'chitin.key'.
[ResourceManager]: Searching for 'GUWBTP10'...
[ResourceManager]: Found 'GUWBTP10.mos' in 'Cache'.
[ResourceManager]: Found 'CLIK2CON.bam' in 'chitin.key'.
[ResourceManager]: Searching for 'guwbtp30'...
[ResourceManager]: Found 'guwbtp30.mos' in 'chitin.key'.
[KeyMap]: Looking up key: 49(1) 
[KeyMap]: RunFunction(GUICommon::ResolveKey)
[KeyMap]: Looking up key: 50(2) 
[KeyMap]: RunFunction(GUICommon::ResolveKey)
[String/WARNING]: Invalid UTF-8 character: 0x92
[ResourceManager]: Searching for 'guwbtp20'...
[ResourceManager]: Found 'guwbtp20.mos' in 'Cache'.
[ResourceManager]: Found 'SPPR503.spl' in 'chitin.key'.
[ModifyDamage/COMBAT]: Resisted 0 of 18 at 0% resistance to 8
[Actor/COMBAT]: 18 unknown damage taken.

[GameScript]: Displaying string on: none
[Actor/COMBAT]: Damage animation type: 5
[ModifyDamage/COMBAT]: Resisted 0 of 9 at 0% resistance to 8
[Actor/COMBAT]: 9 unknown damage taken.

[GameScript]: Displaying string on: none
[Actor/COMBAT]: Damage animation type: 4
[ResourceManager]: Found 'spflast2.vvc' in 'chitin.key'.
[ResourceManager]: Found 'SPFLAST2.bam' in 'chitin.key'.
[ResourceManager]: Found 'spflsrin.vvc' in 'chitin.key'.
[ResourceManager]: Found 'SPFLSRIN.bam' in 'chitin.key'.
[String/WARNING]: Invalid UTF-8 character: 0x92
[ResourceManager]: Searching for 'EFF_M21'...
[ResourceManager]: Found 'EFF_M21.wav' in 'chitin.key'.
[ResourceManager]: Searching for 'EFF_P16'...
[ResourceManager]: Found 'EFF_P16.wav' in 'chitin.key'.
[KeyMap]: Looking up key: 224(�) 
[KeyMap]: Looking up key: 225(�) 
[ResourceManager]: Found 'GUIOPT.chu' in 'chitin.key'.
[ResourceManager]: Searching for 'GUIERR2'...
[ResourceManager]: Found 'GUIERR2.mos' in 'Override'.
[ResourceManager]: Found 'GUIERRB.bam' in 'chitin.key'.
[ResourceManager]: Searching for 'GAM_03'...
[ResourceManager]: Found 'GAM_03.wav' in 'chitin.key'.
[Info]: Press ctrl-c (or close the window) again to quit GemRB.
```

#### Steps to reproduce
1. Go to Statue Bust
2. Take the test
3. Select option: **I shall say a prayer to the light**

#### Expected behavior
Answer is correct

#### Screenshots

https://user-images.githubusercontent.com/1820598/179119090-f49020fb-dcbe-4291-a386-f97b08e9abf2.mp4

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Can reproduce and this is in ar1401.

**Comment by lynxlynxlynx** [comment]
Some change in event handling broke this. `SetValue` in `TextArea::UpdateState` eventually runs `DialogChoose` and then PerformAction on the next line does the same. So we move two dialog states with the same line choice, which in this case makes it look like the first choice was bad.

**Comment by bradallred** [comment]
maybe the `PerformAction(Action::Select)` in `TextArea::UpdateState` was supposed to be `PerformAction(Action::Change)`

**Comment by bradallred** [comment]
hmmm, no, probably not because thats what `Control::SetValue` does, so we'd be doing it twice there. Also, there is seemingly misplaced commentary a few lines up:
```
// always run the TextAreaOnSelect handler even if the value hasnt changed
// the *context* of the value can change (dialog) and the handler will want to know 
```

unfortunately that doesnt jog my memory.

**Comment by bradallred** [comment]
bleh, that got further, but there is another issue

**Comment by rsantellan** [comment]
For me is still not working. Now I can choose the right answer but not the incorrect one.
![image](https://user-images.githubusercontent.com/1820598/179403964-e75d86fc-7854-4884-b781-6c4a51c6c4d1.png)
This is the only thing that shows in the log.
```
[ResourceManager]: Found 'GUWBTP10.mos' in 'Cache'.
[ResourceManager]: Searching for 'guwbtp30'...
[ResourceManager]: Found 'guwbtp30.mos' in 'Cache'.
[KeyMap]: Looking up key: 49(1) 
[KeyMap]: RunFunction(GUICommon::ResolveKey)
```
If you choose one then you can choose another one, ignoring the first one. Only happens when selecting the first option of the list.

**Comment by lynxlynxlynx** [comment]
Did you really try with the latest code? It works for me ...

**Comment by rsantellan** [comment]
https://user-images.githubusercontent.com/1820598/180625482-3c46d7f4-2530-4d1d-b82f-840f7d3b3b98.mp4

@lynxlynxlynx  Using latest commit from master is the same.

**Comment by lynxlynxlynx** [comment]
I can reproduce some bad behaviour now: clicking on some answers just highlights them, doesn't advance the dialog state. I guess the new check is not sensitive enough and the action isn't performed.
