### ISSUE TITLE
Loading a game with a dead enemy autopauses due to enemy seen

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1644]
#### Bug description

If you kill an enemy and save the game, the enemy is briefly "resurrected" when you load the game. Unwanted sideefects of this include: the enemy appears alive and then its death is re animated, the event appears in the message window feedback, the game auto pauses due to "enemy seen"

#### Steps to reproduce
1. find a lone enemy in an area you can save in
2. kill the enemy and save as soon as combat ends
3. load the quick save

#### Expected behavior
Dead enemies should stay dead and not be undead on game load.

**Comment by lynxlynxlynx** [comment]
Saving is disabled during combat, how did you manage to "kill" somebody without it?

**Comment by bradallred** [comment]
This has nothing to do with combat; once combat is over, save the game.

**Comment by lynxlynxlynx** [comment]
Then there is no immediacy. I tried now with some elementals and sahuagin and don't get this behaviour. How did you test?

**Comment by bradallred** [comment]
the save I just uploaded in the other issue exhibits this problem.

**Comment by lynxlynxlynx** [comment]
That does trigger, but it's unclear how you managed to get there. Anyway, an hp check in Map::HandleAutopauseForVisible is all it would take.

**Comment by bradallred** [comment]
that might fix auto pause, what about the other issues?

**Comment by lynxlynxlynx** [comment]
Looks like I commented in the wrong bug, but yeah, it's as easy to patch it all.
