### ISSUE TITLE
 BGT crashes trying to play credits music

### ISSUE THREAD

**Issue by Tomsod** [gemrb/gemrb#1645]
So, after the recent commits fixing #1640, the game (BGT with some mods incl. music from BG1 I think, gemrb hand-compiled on Arch Linux) stopped working for me.  It always crashes after intro videos, trying to play the title screen music:
```
[MUSImporter]: Loading /home/tomsod/.wine/drive_c/Program Files (x86)/Baldur's Gate 2/music/Cred.mus...
/usr/include/c++/12.1.0/bits/basic_string.h:1221: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; reference = char&; size_type = long unsigned int]: Assertion '__pos <= size()' failed.
```
Apparently, `MUSImporter::OpenPlaylist()` uses the return value of `DataStream::ReadLine()` as resulting string length, even though I think it's supposed to be the count of bytes read, and the string is usually shorter because it lacks "\r\n".  And then the game crashes as above when trying to read beyond `line`'s size.

I've fixed it, which stopped the crashes, but then most of the music scores just wouldn't play.  The relevant logs were like this:
```
[MUSImporter]: Loading /home/tomsod/.wine/drive_c/Program Files (x86)/Baldur's Gate 2/music/BGTheme.mus...
[MUSImporter]: Playing BGTHEME/BGTHEMEA��]!V...
[OpenAL/ERROR]: Unable to query music source state: 0xa001 - Invalid Name
```
And the problem here turned out to be the `fmt::format_to()` used to concatenate the music file's name in `MUSImporter::PlayMusic()`, which almost always adds trailing garbage for some reason.  I've replaced it with a simple `strcat()` and the music works fine now.

Here's also the diff of my fixes.  I could also open a pull request, if the code is satisfactory (although it was intended to be a hack).
```diff
diff --git a/gemrb/plugins/MUSImporter/MUSImporter.cpp b/gemrb/plugins/MUSImporter/MUSImporter.cpp
index 9ad6c2b01..6935626e6 100644
--- a/gemrb/plugins/MUSImporter/MUSImporter.cpp
+++ b/gemrb/plugins/MUSImporter/MUSImporter.cpp
@@ -86,8 +86,9 @@ bool MUSImporter::OpenPlaylist(const ieVariable& name)
 		return false;
 	}
 	std::string line;
-	strret_t c = str->ReadLine(line);
+	str->ReadLine(line);
 	PLName = line;
+	int c = line.length();
 	while (c > 0) {
 		if (isblank(PLName[c - 1]))
 			PLName[c - 1] = 0;
@@ -99,7 +100,8 @@ bool MUSImporter::OpenPlaylist(const ieVariable& name)
 	str->ReadLine(line, 5);
 	int count = atoi(line.c_str());
 	while (count != 0) {
-		strret_t len = str->ReadLine(line);
+		str->ReadLine(line);
+		int len = line.length();
 		int i = 0;
 		int p = 0;
 		PLString pls;
@@ -272,7 +274,8 @@ void MUSImporter::PlayMusic(const ieVariable& name)
 		PathJoin(FName, "mx0000", name, nullptr);
 	} else if (!name.BeginsWith("SPC")) { //bg2
 		char File[_MAX_PATH];
-		fmt::format_to(File, "{}{}", PLName, name);
+		int len = strlcpy(File, PLName.c_str(), _MAX_PATH);
+		strncat(File, name.c_str(), _MAX_PATH - len - 1);
 		PathJoin(FName, PLName.c_str(), File, nullptr);
 	} else {
 		strlcpy(FName, name.c_str(), _MAX_PATH);
```

**Comment by lynxlynxlynx** [comment]
Interesting, I guess I was lucky. The first chunks look ok, but the last makes me wonder if `name` was missing a terminating null. 

`ieVariable` is a `FixedSizeString`, which uses strncpy in constructors and operators, but it does use its own max length when doing it in most cases. This means if it gets reconstructed from a shorter buffer than before, it could easily have extra garbage. But looking at the code paths leading here, I only see construction from std::string and no object reuse, hmm. 

Still, it would be better to find and fix the underlying problem. Does this work instead of the last chunk?
```
fmt::format_to(File, "{}{}", PLName.c_str(), name.c_str());
```
If so, it could indicate something being wrong with the `FixedSizeString` formatter.

**Comment by Tomsod** [comment]
I think I've tried it, and it didn't work.  *rechecks*  Nope, still trailing junk in the logs.  The problem is with your formatting function, I suspect.

**Comment by bradallred** [comment]
> Still, it would be better to find and fix the underlying problem

Agreed, something here smells fishy. And if `FixedSizeString` formatting were broken in general we would be seeing it elsewhere. The formatter is _really simple_ and just delegates to libfmt's `const char*` formatter:

```
auto format(const STR& str, FormatContext &ctx) -> decltype(ctx.out()) {
	return formatter<const char*, char>::format(str.begin(), ctx);
}
```

I cant see how this could be broken.

I _think_ the problem is rather that libfmt doesnt null terminate in `format_to`, so we must do that ourselves, or just 0 init the buffer.

**Comment by Tomsod** [comment]
Yeah, `*fmt::format_to(File, "{}{}", PLName, name) = 0;` seems to work.

**Comment by lynxlynxlynx** [comment]
That's true, but annoying:
https://github.com/fmtlib/fmt/blob/0db43cf7feb89f221f642c11b66bcc27043b2b5b/include/fmt/core.h#L3181
We use it in 3 other places currently, which need to be reviewed.

**Comment by lynxlynxlynx** [comment]
Is there a reason we do it that way in `FixedSizeString::Format`? I understand it's a sanity truncation, but even when not truncating reuse of variables can cause problems. For example here, if the initial count is double digit, won't single digit strings be malformed?
https://github.com/gemrb/gemrb/blob/366a210b880e6e1aed1d3504aa251eb0410944c7/gemrb/plugins/AREImporter/AREImporter.cpp#L1404-L1414

**Comment by bradallred** [comment]
right, we need to null terminate in both cases. this was originally `snprintf` which does append a null terminator, so that would be consistent with our expectations.
