### ISSUE TITLE
 No bonus for 17+ constitution for warrior multiclasses (BG2)

### ISSUE THREAD

**Issue by Tomsod** [gemrb/gemrb#1646]
As of master, fighter/mages, fighter/druids etc. with constitution above 16 don't seem to get the bonus HP they should.  Single-classed fighters (also rangers etc.) are OK, constitution below 17 is OK.  Test case: Jaheira.

The problem seems to be in `InitActorTables()` in Scriptable/Actor.cpp.  The `Explode()` function used to separate class names is not performing like the code expects it to: instead of splitting e.g. FIGHTER_MAGE_THIEF to FIGHTER, MAGE, and THIEF, it returns FIGHTER_MAGE_THIEF, MAGE_THIEF, and THIEF.  This leads to fighter multiclasses not being recognized as fighters by `GetClassLevel()` because `levelslots` aren't filled properly.  Probably, HP is not the only symptom of this, but it's what I noticed.

**Comment by lynxlynxlynx** [comment]
Grrr, that one has been a source of a lot of pain recently. Thanks for the detailed diagnosis!
