### ISSUE TITLE
 No bonus to thief skills from dexterity or race (BG2)

### ISSUE THREAD

**Issue by Tomsod** [gemrb/gemrb#1647]
As of master, thieves don't get skill bonuses from skilldex.2da or skillrace.2da.  Apparently 97ee08a33c broke their parsing: in the old code, it looped over columns starting from -1, with that index being special-cased to read row name.  The commit changed the index variable to unsigned, and the loop now starts from `(unsigned) -1`, or rather, it doesn't!

I've fixed this by removing the "-1 code" from the loop altogether, diff below.  Also for some reason the skilldex code tried to read the first column as the row name, I've also fixed that.  Again, I can open a PR if you ask me to, I think my code is OK here.
```diff
diff --git a/gemrb/core/Scriptable/Actor.cpp b/gemrb/core/Scriptable/Actor.cpp
index f92daa024..9cbff0c46 100644
--- a/gemrb/core/Scriptable/Actor.cpp
+++ b/gemrb/core/Scriptable/Actor.cpp
@@ -56,6 +56,7 @@
 #include "StringMgr.h"
 
 #include <cmath>
+#include <string>
 
 namespace GemRB {
 
@@ -2214,12 +2215,9 @@ static void InitActorTables()
 		for (TableMgr::index_t i = 0; i < skilldexNRows; i++) {
 			skilldex.emplace_back();
 			skilldex[i].reserve(skilldexNCols+1);
-			for (TableMgr::index_t j = -1; j < skilldexNCols; j++) {
-				if (j == TableMgr::npos) {
-					skilldex[i].push_back(tm->QueryFieldSigned<int>(i, 0));
-				} else {
-					skilldex[i].push_back(tm->QueryFieldSigned<int>(i, j));
-				}
+			skilldex[i].push_back(std::stoi(tm->GetRowName(i)));
+			for (TableMgr::index_t j = 0; j < skilldexNCols; j++) {
+				skilldex[i].push_back(tm->QueryFieldSigned<int>(i, j));
 			}
 		}
 	}
@@ -2245,23 +2243,20 @@ static void InitActorTables()
 		for (TableMgr::index_t i = 0; i < rows; i++) {
 			skillrac.emplace_back();
 			skillrac[i].reserve(cols+1);
-			for (TableMgr::index_t j = -1; j < cols; j++) {
-				if (j == TableMgr::npos) {
-					// figure out the value from the race name
-					if (racetable == -1) {
-						value = 0;
-					} else {
-						if (subracetable == -1) {
-							value = race->GetValue(tm->GetRowName(i));
-						} else {
-							value = subrace->GetValue(tm->GetRowName(i));
-						}
-					}
-					skillrac[i].push_back (value);
-				} else {
-					skillrac[i].push_back(tm->QueryFieldSigned<int>(i, j));
-				}
-			}
+			// figure out the value from the race name
+			if (racetable == -1) {
+				value = 0;
+			} else {
+				if (subracetable == -1) {
+					value = race->GetValue(tm->GetRowName(i));
+				} else {
+					value = subrace->GetValue(tm->GetRowName(i));
+				}
+			}
+			skillrac[i].push_back(value);
+			for (TableMgr::index_t j = 0; j < cols; j++) {
+				skillrac[i].push_back(tm->QueryFieldSigned<int>(i, j));
+			}
 		}
 	}
 
```
Side note: do original BG/BG2 check for class when displaying thief skills in the character record?  Currently GemRB shows these race/dex bonuses for all classes (with the fix, of course), but I'm not sure it should.

**Comment by lynxlynxlynx** [comment]
Looks good, thanks — please submit a PR.
As far as the stats, so far we left them in the record by choice, but it's easy to hardcode them out if anyone feels strongly enough about it.

**Comment by Tomsod** [comment]
It was kinda bothering me, yeah.  If I can't pick locks, the game shouldn't say I can.

**Comment by lynxlynxlynx** [comment]
We could maintain generality by crosschecking with our skills.2da ... but we'd still need to handle bards and rangers specially (or add them to the table in a special way).
