### ISSUE TITLE
 Cannot level up some mage/cleric multiclasses (BG2)

### ISSUE THREAD

**Issue by Tomsod** [gemrb/gemrb#1648]
Broken in master: leveling up Jaheira crashes GUIScript, leaving the window unfinished and uncloseable.  Probably other F/C, F/M, M/T, C/M, C/T, F/D, and C/R are also affected, judging from the code (not tested, though!)

The problem is that `GemRB_Table_FindValue()` now returns None instead of -1 if it fails to find anything.  This broke the GUI code as follows.  `OpenLevelUpWindow()` in LevelUp.py always constructs `Classes` as a three-item list for multiclasses, possibly padded with zeroes, e.g. for F/D Jaheira it's [2, 11, 0].  This is then passed to `GetNewSpells()`, where for each element, `GUICommon.GetClassRowName()` is called.  In 0.9.0, it silently returned an incorrect value for an argument of 0, which was then ignored.  Now it tries to call `CommonTables.Classes.GetRowName(None)`, which raises an error and breaks the GUI window.

My quick fix: cut off zeroes from `Classes`.
```diff
diff --git a/gemrb/GUIScripts/LevelUp.py b/gemrb/GUIScripts/LevelUp.py
index a4f689152..c64cddeee 100644
--- a/gemrb/GUIScripts/LevelUp.py
+++ b/gemrb/GUIScripts/LevelUp.py
@@ -187,7 +187,7 @@ def OpenLevelUpWindow():
 	NewWSpells = [0]*9
 
 	# calculate the new spells (results are stored in global variables)
-	GetNewSpells(pc, Classes, Level, LevelDiff, Kit)
+	GetNewSpells(pc, Classes[:NumClasses], Level, LevelDiff, Kit)
 
 # this is handled by core
 #		# setup class bonuses for this class
```
There's probably a better way to do this, e.g. avoid inserting those zeroes at all.  Note that everywhere else except for that function call, `NumClasses` is used instead of `len(Classes)`.

**Comment by lynxlynxlynx** [comment]
Looks good enough to me, though it might be cleaner if the skipping was done in the loop in GetNewSpells. Either is also safe for pst.
