### ISSUE TITLE
 Crash when launching game in debug mode

### ISSUE THREAD

**Issue by DudeMcDude** [gemrb/gemrb#1650]
#### Steps to reproduce
Compile on windows with MSVC 2022, debug config.
Launch the game, happens on startup.

Explode() triggers an exception while parsing "GameType=auto". Looks like some issue with reverse iterators. 

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Hmm, it works for me. I also tried with DOS line endings, but we trim anyway. Please post the full error.

**Comment by DudeMcDude** [comment]
Unhandled exception at 0x00007FFD5884AFEC (ucrtbased.dll) in gemrb.exe: An invalid parameter was passed to a function that considers invalid parameters fatal.

[gemrb_debug_dump.zip](https://github.com/gemrb/gemrb/files/9176407/gemrb_debug_dump.zip)

![image](https://user-images.githubusercontent.com/11220053/180660538-30047b90-458d-4275-a5c4-0a8a5fbc2703.png)

![image](https://user-images.githubusercontent.com/11220053/180660580-8d97f975-db3d-4112-9a09-8d70ecd0ac50.png)

![image](https://user-images.githubusercontent.com/11220053/180660639-22a7a3c0-d4af-4a10-8a11-fa64e14f9c1f.png)

![image](https://user-images.githubusercontent.com/11220053/180660660-b74eb83e-ce62-4117-a4a7-60631566f834.png)

![image](https://user-images.githubusercontent.com/11220053/180660609-6bd733ba-c990-4293-bd2b-dd77996f4e8e.png)

**Comment by lynxlynxlynx** [comment]
It looks like msvc is using a negated `pos` in that offset check. I could understand it somehow being from the reverse iteration, but why the broken check then? It's not clear to me if this /is/ a bug in the msvc library though.

A workaround would be defining _ITERATOR_DEBUG_LEVEL to 0, but that sounds lame. A release build would also avoid it.

**Comment by MarcelHB** [comment]
Shouldn't that subtract `pos` from `rend()`, or `pos` be negative which is probably not the case since it's a size type? If you add something to `rend()`, it goes into invalid memory.

**Comment by DudeMcDude** [comment]
> Shouldn't that subtract `pos` from `rend()`, or `pos` be negative which is probably not the case since it's a size type? If you add something positive to `rend()`, it goes into invalid memory.

Yeah I think that's the issue, rend() points to the string start, adding pos = 3 converts it internally to negative offset -3, and it tries to access s[-3].

**Comment by lynxlynxlynx** [comment]
Ah, thanks. I guess gcc just silently does what I expected.
