### ISSUE TITLE
 Debug assertion

### ISSUE THREAD

**Issue by DudeMcDude** [gemrb/gemrb#1654]
#### Bug description
Debug build crashes here:

https://github.com/gemrb/gemrb/blame/master/gemrb/core/GUI/View.cpp#L421

Looks like the cause is that the iterator is end-of-list when back is NULL:
https://github.com/gemrb/gemrb/blame/master/gemrb/core/GUI/View.cpp#L408

#### Steps to reproduce
Build in debug mode, MSVC 2022, launch game

#### Expected behavior
Handle it gracefully :)

I guess when it == subViews.end() then don't increment it...

#### Screenshots
![image](https://user-images.githubusercontent.com/11220053/180865627-1a14a1b8-1583-4f7e-a13c-bd9e53b352b5.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment]
that increment looks like leftovers from an older version. just remove it.

**Comment by bradallred** [comment]
can you tell me if `back == nullptr`? Obviously if its not null there is a bigger problem.

**Comment by DudeMcDude** [comment]
By the way, it looks like I'm going to run into a whole bunch of such issues. Might make this a meta...

**Comment by DudeMcDude** [comment]
> can you tell me if `back == nullptr`? Obviously if its not null there is a bigger problem.

It was nullptr, so `it` was correctly at the end of the list.

**Comment by bradallred** [comment]
> By the way, it looks like I'm going to run into a whole bunch of such issues. Might make this a meta...

a PR might be better.

**Comment by bradallred** [comment]
It looks like we do have bigger issues, since `back` is not always found even when not null.
