### ISSUE TITLE
IWD2 switching characters while in spellbook

### ISSUE THREAD

**Issue by DudeMcDude** [gemrb/gemrb#1660]
#### Bug description
If you switch between Sorc and Cleric, you get errors.

#### Steps to reproduce
IWD2 - use the first pregen party. Go into spellbook UI, and switch between the sorc & cleric.

#### Expected behavior
Spellbook tabs should refresh.

#### Screenshots
![image](https://user-images.githubusercontent.com/11220053/181117834-5292f981-0814-426a-96cc-e32a06a4af4a.png)
![image](https://user-images.githubusercontent.com/11220053/181117861-73fb1dfc-2bb8-43b3-bac2-d9597b5e7a92.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Hmm, that's an odd one. I can reproduce it with a random save, though sometimes it works fine. I guess it's from 9b6e63f0b.
