### ISSUE TITLE
 Loot UI exit button sometimes not responsive

### ISSUE THREAD

**Issue by DudeMcDude** [gemrb/gemrb#1662]
#### Bug description
Sometimes I have to wiggle the mouse a bit for it to register the click on the exit UI button. Otherwise I can click the button multiple times with no reaction. It's as if it doesn't recognize the mouse having entered the widget area.

Pressing ESC works fine though.

I also notice the UI tooltip doesn't come up (again until I wiggle the mouse for a bit).

#### Steps to reproduce
Playing IWD2 in windowed mode, debug build. 
Starting area, click on some loot pile or container.

#### Screenshots
![image](https://user-images.githubusercontent.com/11220053/181359337-22cb785f-acbf-41bb-881e-edc480e6fec2.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
There's potentially something newly bugged here, yeah. I noticed something similar today elsewhere, but was too focused on another problem to look into it. How easily reproducible is this particular scenario?

Perhaps worth a bisect, but considering the recent build fixes, you'd have trouble with that, so it's best if someone else does it.

**Comment by bradallred** [comment]
I was questioning the iterator passed to splice here:
https://github.com/gemrb/gemrb/blob/cc4c31db9a8a133cada8e0dda64bbd03f20e6547/gemrb/core/GUI/View.cpp#L408-L420

perhaps I was wrong to do so and we shouldn't have incremented in this case.

**Comment by DudeMcDude** [comment]
Should be quite easy to reproduce.

**Comment by lynxlynxlynx** [comment]
Looking at it, there is no problem. The actual button is just that smaller inner circle in a box, the rest of the rect is part of the background image. So for example it's expected that where the screenshot is pointing will not result in anything.

**Comment by DudeMcDude** [comment]
Oh! Figures. But is it really supposed to be like that? It's very counter intuitive. I'd enlarge the active area if it's not too much trouble...

**Comment by lynxlynxlynx** [comment]
That's how they set up the GUI. We could enlarge it, but that would require artistic interpretation — buttons need several states etc. Btw, it's inefficient to close them that way. Moving, selecting another character, right clicking, escape main window hotkeys and probably more all close it.
