### ISSUE TITLE
Keys in bags are not visible to scripts

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1663]
#### Bug description
I'm on Umar hills and just have all the pieces of the Symbol of Amaunator, but the door to going down is not opening.
It says **Locked door**

```
[ResourceManager]: Found 'CHMB3g1.bam' in 'chitin.key'.
[ResourceManager]: Searching for 'ARM_04c'...
[ResourceManager]: Found 'ARM_04c.wav' in 'chitin.key'.
[ResourceManager]: Found 'CEFF4g18.bam' in 'chitin.key'.
[ResourceManager]: Found 'formatio.2da' in 'GemRB Unhardcoded data'.
[ResourceManager]: Searching for 'error02'...
[ResourceManager/WARNING]: Couldn't find 'error02'... Tried error02.wav error02.acm error02.wav error02.ogg 
[ResourceManager]: Searching for 'AMB_D20'...
[ResourceManager]: Found 'AMB_D20.wav' in 'chitin.key'.
[ResourceManager]: Searching for 'ARM_03e'...
[ResourceManager]: Found 'ARM_03e.wav' in 'chitin.key'.
[ResourceManager]: Found 'CIFB3g12.bam' in 'chitin.key'.
^C[ResourceManager]: Found 'GUIOPT.chu' in 'chitin.key'.
[ResourceManager]: Searching for 'GUIERR2'...
[ResourceManager]: Found 'GUIERR2.mos' in 'Override'.
[ResourceManager]: Found 'GUIERRB.bam' in 'chitin.key'.
[ResourceManager]: Searching for 'GAM_03'...
[ResourceManager]: Found 'GAM_03.wav' in 'chitin.key'.
```

#### Steps to reproduce
1. On umar hills
2. Get Symbol of Amauntur
3. Try to open de door

#### Expected behavior
Door open

#### Savegame
[000000061-Cant open door.tar.gz](https://github.com/gemrb/gemrb/files/9215281/000000061-Cant.open.door.tar.gz)

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
It's the forcefield, right? You need the sun gem for that. It doesn't find it, since you put it into a bag.

**Comment by rsantellan** [comment]
Just giving a quick glance over there is the method **FindItem** on Inventory could I use that instead ?

**Comment by lynxlynxlynx** [comment]
That's what's currently used, so no. :)

**Comment by rsantellan** [comment]
Checking for the type 58 it returns false.

![image](https://user-images.githubusercontent.com/1820598/182008105-55c1c7a8-48e2-4a4b-9755-82ab2b736e8a.png)

Should I try each inventory slot ?

**Comment by lynxlynxlynx** [comment]
Yes, it looks like that only checks the equpped slots.

**Comment by rsantellan** [comment]
@lynxlynxlynx using this https://github.com/gemrb/gemrb/blob/8e92679b198d8e1ccb447574220d406b32435687/gemrb/core/GameScript/GSUtils.cpp#L379 wouldn't be better in certain occasions ? Or will slow everything down ?

**Comment by rsantellan** [comment]
@lynxlynxlynx I open the door with this:
```
diff --git a/gemrb/core/Scriptable/Scriptable.cpp b/gemrb/core/Scriptable/Scriptable.cpp
index 256cd0897..0be529c7c 100644
--- a/gemrb/core/Scriptable/Scriptable.cpp
+++ b/gemrb/core/Scriptable/Scriptable.cpp
@@ -1817,8 +1817,7 @@ bool Highlightable::TryUnlock(Actor *actor, bool removekey) const {
                for (int idx = 0; idx < game->GetPartySize(false); idx++) {
                        Actor *pc = game->FindPC(idx + 1);
                        if (!pc) continue;
-
-                       if (pc->inventory.HasItem(KeyResRef,0)) {
+                       if (HasItemCore(&pc->inventory, KeyResRef, 0)) {
                                haskey = pc;
                                break;
                        }
```
But I don't know performance wise is it good, it loop all the items if you don't have it. And the next problem is that it doesn't remove it from inventory. It do not look in the bag, is my next step.

**Comment by lynxlynxlynx** [comment]
Great find. :) Maybe salvaging StoreGetItemCore is an option, but it does require a lot of parameters. Maybe some of the functionality should be moved to Inventory, to be more easily shared. Play around.
