### ISSUE TITLE
BG2: Strange effect on adding spell to spellbook. 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1670]
#### Bug description
Leveling up and choosing a new spell to fill the slot, makes the slot to set the spell, banish and if you hover comes again.

#### Steps to reproduce
1. Level up a mage.
2. Click on the spellbook
3. Choose a new spell.

#### Expected behavior
It stays visible.

#### Screenshots

https://user-images.githubusercontent.com/1820598/182979815-aa185971-0d02-4c69-ab50-bda849310de7.mp4

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by fizzet** [comment]
This is the same as #1340
