### ISSUE TITLE
enable opengl for windows builds

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1671]
Looking at AppVeyor logs confirms we're not building with any GL. Luckily there's a handy package in VCPKG:
https://github.com/microsoft/vcpkg/tree/master/ports/opengl

So for most users it should just be about installing that and passing the OPENGL_BACKEND flag to cmake. I'm not sure if we can use the same approach for AppVeyor, because on closer inspection it so far only supports Windows 8+, while the bots run on Windows Server:
https://github.com/microsoft/vcpkg/blob/master/ports/opengl/portfile.cmake#L4
https://www.appveyor.com/docs/windows-images-software/#operating-system

Since we use the 2019 image, we should be fine:
https://docs.microsoft.com/en-us/windows/win32/sysinfo/operating-system-version

But would we be cutting off users on 7 or older?

**Comment by MarcelHB** [comment]
The check above is testing for the SDK, not Windows, that just follows the same version style. But even newer Windows SDKs can be used for applications on [older Windows, such as 7](https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/). Of course this may fail on using stuff that is exclusive to new versions.
