### ISSUE TITLE
Intermittent invisible actors

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1674]
If you start SoA, the pc will soon vanish (empty cage) and a similar thing is visible for the golem after arrival and in the middle of departure; iirc also Jon. It starts with the refactor in c044814fb56 and only affects the opengl backend.

Looking at that, are we handling gl_FragColor.a setting when mod returns 0 properly? Before we hardcoded a value, but on the other hand, why would gl_FragCoord change. Or could stencilFactor suddenly be 0?

**Comment by bradallred** [comment]
the first thing that comes to my mind is #1612. if there is another path that leads to `SDL_RenderCopy[Ex]`, or if we simply don't always set the uniforms for each sprite, then a previously set value will be erroneously set.

**Comment by bradallred** [comment]
the fact that you can `ctrl+5` and get them to appear does make it seem like we simply have a stale uniform or other render state that gets reset when switching shaders to draw the polys.
