### ISSUE TITLE
[bug] Grace's animation palettes look bad

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#168]
**Describe the bug**
The palette(s), or the color application, of Grace (tested when in the party) is odd when she is standing still (almost inverted), and not fully correct when moving (lacks saturation).

GemRB version: HEAD of right now.

**To Reproduce**
1. Meet Grace or obtain her as a party member.
2. Make her move and stand.

**Expected behavior**

![grace_correct](https://user-images.githubusercontent.com/238558/63300414-71d4b280-c2d8-11e9-80db-483f9585e52e.jpg)

**Screenshots**

![grace](https://user-images.githubusercontent.com/238558/63300199-f410a700-c2d7-11e9-8fe9-a9f78a08049b.jpg)

**Comment by lynxlynxlynx** [comment]
Here is more, [chiv's research](http://www.gemrb.org/wiki/doku.php?id=pst_bugs) from the wiki:
> Ebb Creakness, curst guards, Fall from Grace and many others seem to have a corrupt palette while standing idle
>   * here is a list of sprites with a broken palette in their idle stance in case it helps find a pattern (possibly incomplete, some are hard to tell): http://pastebin.com/zMuXLkWH
>   * From all I can tell, this seems to be because PST can have a different palette for every stance, while bg/iwd was neater and had only one for each creature?

As for the latter guess, not sure why he thought that. If you look at resdata.ini, where the animation info for actors is stored, ther's no field for palettes. Different animations had different bams in other engines too, potentially with different palettes, so nothing unexpected there.

**Comment by MarcelHB** [comment]
_potentially_ is likely the point here. :wink:  Indeed, CSTDFFGB.BAM and CRUNFFGB have very different palettes, looking at them byte-wise, so I have a rough idea what to check. Sarevok-has-a-red-shadow kind of stuff.

**Comment by MarcelHB** [comment]
So, yes, see this block of code: 
https://github.com/gemrb/gemrb/blob/115b255309662b9c547a1bbe21aa6d0550ac227b/gemrb/core/CharAnimations.cpp#L1011-L1015

When you make the Actor switch between animations, and you end and up returning here, there is no update of the palette. A one-liner to confirm this (and fix that single issue mentioned here, not sure yet what would have been left to do this correctly and for other cases):

```cpp
if (anims) {
	palette[PAL_MAIN] = anims[0]->GetFrame(0)->GetPalette()->Copy();
	return anims;
}
````

**Comment by lynxlynxlynx** [comment]
Hmm, interesting — always better when it's a simpler problem than you thought.

Ebb Creakness has an animation ID just 1 less than Grace - 0xe015, while the guards 0xe009. Can you try them too? You can summon via the console: cc("ebb") and cc("crstgrd").

Doesn't that leak any previous palette there though? SetupColors is called afterwards in other setters, but it's too late for me to go down that rabbit hole.

**Comment by MarcelHB** [comment]
Yes, it is the same for those two samples as well.

You probably should not code it like above, yes. I will dig around there in the next days, the method has multiple returns and a ton of cases to consider.

**Comment by MarcelHB** [comment]
I'm trying to understand a bit: `CharAnimations::GetAnimation` is called all the time for returning the animation set depending on stance and orientation.

In theory, this is a good place to update the palette to use on drawing, depending on the current animation. Generally, palettes are `Palette::Copy()`d from the animation sprite/frame into the `CharAnimations` object on the first occasion [0] on whatever animation is requested, internally calling `Palette::release()`d, refcount decreases, possibly freeing itself [1]. The palette size often seems 1KB of size.

Anyway, updating an animation is not happening all the time, and for probably 99%, there is no need to update, i.e. copy, the palette at all as they are factually the same.

I'm trying to figure out what to do best without wasting tons of cycles, under the following assumptions:

- For what we know, different palettes over different stances only occur on PST actors.
- PST is not using composed animations, e.g. TNO has distinct full body BAMs for different weapon types (that are not switching as well, yet).
- So we can live with updating `PAL_MAIN` alone.

Correct me if we must widen assumptions for other cases that I don't have in mind atm.

1. We test if the stance has changed, and restrict updating `PAL_MAIN` to that case.
2. We load every palette lazily or upfront, and then switch to that palette (per actor caching, so to say).
3. Knowing that 2. essentially covers a rare case, we implement something even smarter, e.g. checksumming the palettes on loading and testing if a palette change is actually necessary, so no need to copy palettes into the CA and redoing the colors.

[0] https://github.com/gemrb/gemrb/blob/479c590b7fb05d97953fc33f12335b3e47eacc93/gemrb/core/CharAnimations.cpp#L1120
[1] https://github.com/gemrb/gemrb/blob/479c590b7fb05d97953fc33f12335b3e47eacc93/gemrb/core/Palette.cpp#L86-L91

**Comment by lynxlynxlynx** [comment]
It's pretty obvious by now, but pst changed the bg1 system quite a lot and yes, many stances are missing. It's a longstanding TODO now tracked in #175.

You assumptions seem fine. I'm sure there are still a few animation types in other games with palette issues, but I'll list them below, since it could distract.

If you load the palette through GameData, it's stored in a cache (PaletteCache) while in use. I doubt this path is used here though. But, wouldn't a memcmp of both pal->col be enough to compare? I don't know if it memory contiguousness is guaranteed though, but if it isn't true just occasionally, that's still probably a good enough optimisation.

In the subviews branch we have a private version field in Palette, but it's just a counter, so it's not unique among palettes.

Other games; most common issue was/is pixelation due to wrong palette and these remain documented:
> bg2
>   * fire giants  (0x7F3E ResRef:mfig ) eg. in tob ar5200 can get all pixelated (verified today)
>   *  umber hulks change color sometimes for a few frames
>   *  some elemental animation frames are all pixelatedly ugly. For example **fire elementals have 2 bmp palette files each**, but not like we're used to.
>
> iwd1
>   * arundel (maru) has a clowncolored base avatar (the cloak is fine), visible in ar2112.

**Comment by MarcelHB** [comment]
I'm not sure how much this would end up memcmp'ing over and over in situations where this is irrelevant, let's say a battle with many actors in BG2.

I'm looking at the mentioned examples though.

**Comment by lynxlynxlynx** [comment]
A gameflag can limit it to pst, but there are big crowds there too. memcmp is fast, plus I don't think we'd really need to check the whole array. If you have a better idea, go ahead, of course.

**Comment by MarcelHB** [comment]
A Game flag is not an option: The fire giants and umber hulks of BG2 have the same condition, indeed.
