### ISSUE TITLE
BG2: Inventory weight is computing bad 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1686]
#### Bug description
On Jan I notice that the **Flasher Master Bruiser Mate** don't weight nothing and adding a **Chain Mail Dark Mail +3** without identifing with weight 40 only add 9 to the total weight.

#### Steps to reproduce
1. Go to Jan
2. Add a Chain Mail Dark Mail +3 without identified
3. Look inventory total

#### Expected behavior
If it unidentified it has to weight 40 but when identified should weight 9.
If you see the descriptions they are ok, unidentified is 40 and identified is 9. 

#### Screenshots
![image](https://user-images.githubusercontent.com/1820598/185509358-82826e1e-62e0-458c-9098-07ce92d70930.png)

https://user-images.githubusercontent.com/1820598/185509469-071b8d2e-bfe3-48ee-8b36-c1fc4c779595.mp4

https://user-images.githubusercontent.com/1820598/185509471-84c51a61-6ecd-4caf-a140-95fa64c755d5.mp4

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
So two things:
- those bolts have 0 weight set. Making weight minimum at 1 would be wrong though, even if limited to equippables, so I'm inclined not to fix this
- unidentified items show the weight of the base item, so plain chain mail in this case. Doesn't make any sense, would require annoying extra lookups, so definitely not "fixing" this

**Comment by rsantellan** [comment]
@lynxlynxlynx for the first one no question but the second one could be the check here https://github.com/gemrb/gemrb/blob/29515d846681c6ddd90280fd69d08bce13a1d90b/gemrb/plugins/GUIScript/GUIScript.cpp#L9583 is not identified set the other item weight ? Because later I don't find that go load again the item, just a thought.

**Comment by lynxlynxlynx** [comment]
identified or not is an item flag, there are no separate unidentified copies of items.
