### ISSUE TITLE
BG2: Can't drop more than 5 items to the ground 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1687]
#### Bug description
Trying to leave only one item on the inventory I found that the scroll on the ground is not working.
You can only drop 5 items per time, and then you have to move.

#### Steps to reproduce
1. Go to the inventory
2. Move 5 items to the ground
3. Try to scroll the ground

#### Expected behavior
Should be able to scroll in the ground part to put more there.

#### Screenshots

https://user-images.githubusercontent.com/1820598/185657403-f5254e8b-8133-4e44-8067-182c696b4648.mp4

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
There's nothing to scroll to there and you can still drop items just fine. Like with the first five, the placement doesn't matter.

**Comment by rsantellan** [comment]
On the original you can scroll down.

https://user-images.githubusercontent.com/1820598/185662850-0c4476ce-3fed-465a-8df4-359513273303.mp4

I confirm that I can drop all items putting them on over other one and the scroll only moves to the one you have.

Don't know now if this is really a bug now.
