### ISSUE TITLE
Refactor Point to hide navmap<->tilemap coordinate conversions

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1693]
Copy Point to let's say BasePoint and make Point a subclass. Then add a TileMapPoint subclass that works in tilemap coordinates instead. Then make use of it in Map and Pathfinder, reducing the number of uses of ConvertCoordToTile and ConvertCoordFromTile.

_Originally posted by @lynxlynxlynx in https://github.com/gemrb/gemrb/issues/1692#issuecomment-1242115673_

Same can be done for the fog and ConvertPointToFog, if it turns out to be sensible.

**Comment by bradallred** [comment]
a subclass would still allow you to pass the derived to functions asking for the "base". I think we need two distinct types.

**Comment by bradallred** [comment]
I wasn't aware we needed any functionality out of the "tile point" other than comparisons. But yes, that would work fine.

**Comment by Mingun** [comment]
Just to remind: private inheritance solves problem with inheritance. You cannot use private subclass instead of base class: https://godbolt.org/z/szxbbxac8

**Comment by bradallred** [comment]
Wouldn't that just take us back to not having any of the functionality exposed?

e.g. will I be able to call `isWithinRadius()` externally on an object that is privately inherited? I think not. I know calling it internally would work tho.

**Comment by Mingun** [comment]
> Wouldn't that just take us back to not having any of the functionality exposed?

Ah, yes. That will be a problem

**Comment by lynxlynxlynx** [comment]
Going standalone is not that bad, but the base class route would avoid some of the reimplementations, the ugly template embedding and AREIMporter workarounds:
https://github.com/gemrb/gemrb/commit/22edcebc5c39ac8a484f0ce9be0c9f71469012d4

Thoughts?

**Comment by MarcelHB** [comment]
```cpp
class Point {
  protected:
    int x;
    int y;

  public:
    Point(int x, int y) : x(x), y(y) {}
    // ... point math members
};

class NormalizedPoint : public Point {
  public:
    SearchMapPoint(int x, int y) : Point(x, y) {}
};

class SearchMapPoint : public Point {
  public:
    SearchMapPoint(const NormalizedPoint& p) : Point(p.x / 16, p.y /12) {}

    operator NormalizedPoint() const {
      return NormalizedPoint(x * 16, y *12);
    }
};

class SomeOtherPoint : public Point {
  // ... similar to `SearchMapPoint`
};
```
Ok, maybe I didn't get _the point_ of the discussion yet, but just some untested idea how to design the types and keeping the need for multiple conversion math definitions low?

**Comment by lynxlynxlynx** [comment]
Well yeah, something like that was my suggestion, a base point class. I humored the other approach to see how it would fare in practice. It turns out there is more functionality needed than just comparisons. I'll try with the subclassing approach next.

**Comment by lynxlynxlynx** [comment]
It spills into a few more places to avoid the big templated PlotCircle and co, but I think it comes out cleaner overall:
https://github.com/gemrb/gemrb/compare/master...smpt-1693-2

I kept Point the same as the current one / NavmapPoint, since there are so many users.
