### ISSUE TITLE
Add ARM arch to Mac builds for releases

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1694]
I develop on an M1. Yes, we run just fine on it. I'll open an issue to add ARM arch to the buildbot so our releases dont require rosetta.

_Originally posted by @bradallred in https://github.com/gemrb/gemrb/issues/164#issuecomment-1245451925_

**Comment by lynxlynxlynx** [comment]
It looks like Github Actions supports only x86 natively for macs, so we'd have to crosscompile or use something else:
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by bradallred** [comment]
The macOS tool chain will cross compile just fine. The more difficult issue is that homebrew only supports the native arch of the machine it’s on. We need something that will build “fat” dependencies.

**Comment by lynxlynxlynx** [comment]
[Cirrus CI](https://cirrus-ci.org/guide/macOS/) apparently has the right hw, but we'd need a separate pipeline for it and of course it doesn't solve the fat problem. If there's no good solution for this out there, I propose we just start shipping separate binaries for both targets.

**Comment by lynxlynxlynx** [comment]
Now it finally works, you can try the build here:
https://sourceforge.net/projects/gemrb/files/Buildbot%20Binaries/Apple/ARM64/

**Comment by lynxlynxlynx** [comment]
Ok, someone tested and it works. We don't package any default config though, cmake just isn't instructed to install them (not something new with this arch).
