### ISSUE TITLE
BG2: Petrification of the main character don't end game 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1696]
#### Bug description
Opening the south door in the Bridge District triggers a trap that cast petrification, if the main character is hit with it, it should show the game over sequence.

#### Steps to reproduce
1. Go to Bridge District
2. Click on the southest door
3. Trigger the trap with the main character

#### Expected behavior
Death sequence

#### Screenshots

![image](https://user-images.githubusercontent.com/1820598/191647985-cc10d652-c569-40c4-a91d-2a96bc73e5e3.png)

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Sounds like an antifeature to me.

**Comment by rsantellan** [comment]
> Sounds like an antifeature to me.

I thought It was nice not to finish the game in that way but if you don't revive the character what happen to the story line?, you could mess all the story. I understand why it happens.

**Comment by lynxlynxlynx** [comment]
Of course things would break. But who would want to play without their main character?
