### ISSUE TITLE
BG2: Spells are missing to select 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1698]
#### Bug description
Spells of clerics, druids and mages are missing to select from the options

#### Steps to reproduce
1. Go to a party that has Anomen for example
2. Click on the spell selection
3. Click on the learned spells
4. You see only a subset on the selections.

#### Expected behavior
All spells are shown

#### Screenshots

https://user-images.githubusercontent.com/1820598/192682301-5c8cab8d-1ae9-4eed-bd34-c48167c8afd3.mp4

![spells-wierd](https://user-images.githubusercontent.com/1820598/192682352-205effa1-f991-4f02-a353-6c120d925ab7.png)

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Still works fine for me, including in saves with Anomen and Jaheira. Please provide a save.

**Comment by bradallred** [comment]
just a wild guess, but I suspect this happens when there are multiple pages of spells. we are supposed to have arrow buttons to scroll them.

**Comment by lynxlynxlynx** [comment]
Well yeah, I do get them. Perhaps it's a new off-by-1 somewhere, only visible with a particular spell count. From what I can see he has 17 unique spells memorized and 6 are displayed. We display 10 per "page", so that doesn't add up.

**Comment by rsantellan** [comment]
It's really weird, if you load from a save game it works all the time. If I play a bit sometimes it happens, I notice only when I try to use a spell, an all spell caster have the same problem. I will send all the log to a file to try to see if an error has occur in the game and I didn't notice. 
Don't know if it is related but on the druid groove all the chat history was deleted upon finishing the quest. I will try to reproduce them both.

**Comment by rsantellan** [comment]
I found that after this error it happen:

```
[AREImporter/DEBUG]: Loading wallgroups
[Core/WARNING]: 35 ms (compressing SAV file)
[OpenAL/ERROR]: Unable to get listener pos: 0xa003 - Invalid Value
[GameScript]: MoveBetweenAreas: Jaheira to ar0700 [832.807] face: 12
[MUSImporter]: Loading ~/bg2new/music/mx0300.mus...
[MUSImporter]: Playing SPC1...
[GameScript]: MoveBetweenAreas: Anomen to ar0700 [832.807] face: 12
[MUSImporter]: Loading ~/bg2new/music/mx0300.mus...
[MUSImporter]: Playing SPC1...
[GameScript]: MoveBetweenAreas: Yoshimo to ar0700 [832.807] face: 12
[MUSImporter]: Loading ~/bg2new/music/mx0300.mus...
[MUSImporter]: Playing SPC1...
[GameScript]: MoveBetweenAreas: Aerie to ar0700 [832.807] face: 12
[MUSImporter]: Loading ~/bg2new/music/mx0300.mus...
[MUSImporter]: Playing SPC1...
[GameScript]: MoveBetweenAreas: Minsc to ar0700 [832.807] face: 12
[MUSImporter]: Loading ~/bg2new/music/mx0300.mus...
[MUSImporter]: Playing SPC1...
[GameScript]: MoveBetweenAreas: Arkon to ar0700 [832.807] face: 12
[MUSImporter]: Loading ~/bg2new/music/mx0300.mus...
[MUSImporter]: Playing SPC1...
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "~/gemrb-myfork-git/gemrb/GUIScripts/GUIWORLD.py", line 86, in DialogEnded
[Python/ERROR]:     ContinueWindow.GetControl(0).SetHotKey (None, 0, True)
[Python/ERROR]: AttributeError: 'NoneType' object has no attribute 'GetControl'
[ResourceManager]: Searching for 'am0700'...
[MUSImporter]: Loading ~/bg2new/music/mx0700.mus...
[MUSImporter]: Playing SPC1...
[ResourceManager]: Searching for 'AMGRDX01'...
```
