### ISSUE TITLE
BG2: Bad formation display 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1699]
#### Bug description
When selecting all the party and pressing ESC it will select the rightmost formation, but keep using the selected one.

#### Steps to reproduce
1. Go to a place that you can walk and have all the party, select all the party
2. Click on a formation that is not the rightmost formation
3. Press ESC and see the formation change
4. Move the party and see that the old formation is respected.

#### Expected behavior
The formation should not change pressing ESC

#### Screenshots

https://user-images.githubusercontent.com/1820598/193032951-2109667d-24d0-4a6f-b59a-cb008bdfc9ed.mp4

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
It's just the usual radio button snafu.
