### ISSUE TITLE
BG2: Harper Hold Doorman is missing. 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1700]
#### Bug description
After given the quest of Jahiera Harper Hold and sleeping one night go to the docks to the entrance of the Harper Hold and you will not be able to enter because the Doorman is missing. 

[000000110-Next quest.zip](https://github.com/gemrb/gemrb/files/9679247/000000110-Next.quest.zip)

#### Steps to reproduce
1. Go to Docks with Jahiera after having the Harper Hold
2. Try to enter the Harper Hold and the Doorman is missing.
3. See error

#### Expected behavior
The doorman is there and let you enter

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by rsantellan** [comment]
I catch him entering inside in the second 51

https://user-images.githubusercontent.com/1820598/193172189-8f0c2c9b-54fb-4a92-8e98-ddc809ea8087.mp4

This is the log of the console.
[screenlog.0.gz](https://github.com/gemrb/gemrb/files/9680013/screenlog.0.gz)

How can I make him come out again ? What trigger is missing ?

**Comment by lynxlynxlynx** [comment]
He's not out there during the night, the quest timer might have not expired etc. I played through this quest line when realease testing without a hitch.

**Comment by rsantellan** [comment]
@lynxlynxlynx I done some testing and make it work, I still don't know why but Jaheira appears to be dead on the checks. What I try was:

1. Kill her and revive her with CTRL + R
2. Kill her and revive her with a scroll
3. Kill her and revive her on a temple.

With the three options the quest is now playable, so I don't know how it was corrupt on the first place.

**Comment by lynxlynxlynx** [comment]
There are very few ways STATE_DEAD gets set and I now reviewed them, so my bet is on some memory corruption (cosmic rays, system, whatever).
