### ISSUE TITLE
BG2: Segfault on watcherkeep level 3

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1703]
#### Bug description

I was playing and have a segfault entering a portal.

[ResourceManager]: Found 'cut202e.bcs' in 'Override'.
[GameScript/DEBUG]: CutSceneID was called by none!
[GameScript]: MoveBetweenAreas: Arkon to ar3005 [471.434] face: 14

![image](https://user-images.githubusercontent.com/1820598/195742786-7d1c47ca-0b46-43d7-9926-3b397936e41b.png)

I been a little lost so a lot of portals I have cross, really hard to replicate.

#### Steps to reproduce
1. Go to Watcherkeep
2. Click on portal
3. See error

#### Expected behavior
Don't crash

#### Screenshots
![image](https://user-images.githubusercontent.com/1820598/195742661-e92bb937-4db0-4936-affe-b9800c2ea721.png)

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Explore the values involved the next time. Is somehow the map without a valid script name?

**Comment by rsantellan** [comment]
> Explore the values involved the next time. Is somehow the map without a valid script name?

I'm trying to reproduce again. I have a segfault fighting the chromatic demon on the level 2 but I was without the ide and couldn't see anything.

**Comment by lynxlynxlynx** [comment]
Any luck with testing either crash?

**Comment by rsantellan** [comment]
@lynxlynxlynx I couldn't replicate anymore, I didn't have much time but I couldn't crash it again. You could close it and if I can replicated I reopen it.

**Comment by lynxlynxlynx** [comment]
Ok, thanks.
