### ISSUE TITLE
BG2: Some spells occasionally not shown in the spellcast bar 

### ISSUE THREAD

**Issue by Tomsod** [gemrb/gemrb#1709]
I occasionally (as recently as last month with git) had a problem with some prepared spells not being shown in the spellcasting menu.  After some digging, it turned out something would change the case of prepared spells' resrefs (usually to lowercase), while known spells remained as usual (usually all caps), which caused Spellbook.py, which compared these resrefs case-sensitively, to react poorly.  Now, I never figured out the cause or even how to reliably reproduce it (and I don't even have a save right now, sorry), but I at least was able to fix the consequences by rewriting the spellbook code so it would ignore case.  I can provide a pull request if you want, but really, finding out what mangles spells' case would also be prudent.

Here's the code just in case:
```diff
diff --git a/gemrb/GUIScripts/Spellbook.py b/gemrb/GUIScripts/Spellbook.py
index e834f9674..b51ac3e77 100644
--- a/gemrb/GUIScripts/Spellbook.py
+++ b/gemrb/GUIScripts/Spellbook.py
@@ -51,16 +51,17 @@ def GetUsableMemorizedSpells(actor, BookType):
 			if not Spell0["Flags"]:
 				# depleted, so skip
 				continue
-			if Spell0["SpellResRef"] in spellResRefs:
+			resref = Spell0["SpellResRef"].lower()
+			if resref in spellResRefs:
 				# add another one, so we can get the count more cheaply later
-				spellResRefs.append (Spell0["SpellResRef"])
+				spellResRefs.append (resref)
 				continue
-			spellResRefs.append (Spell0["SpellResRef"])
-			Spell = GemRB.GetSpell(Spell0["SpellResRef"])
+			spellResRefs.append (resref)
+			Spell = GemRB.GetSpell(resref)
 			Spell['BookType'] = BookType # just another sorting key
 			Spell['SpellIndex'] = GemRB.GetSpelldataIndex (actor, Spell["SpellResRef"], 1<<BookType) # crucial!
 			if Spell['SpellIndex'] == -1:
-				GemRB.Log (LOG_ERROR, "GetUsableMemorizedSpells", "Memorized spell not found! " + Spell["SpellResRef"] + " of type " + 1<<BookType)
+				GemRB.Log (LOG_ERROR, "GetUsableMemorizedSpells", "Memorized spell not found! " + Spell["SpellResRef"] + " of type " + str(1<<BookType))
 			Spell['SpellIndex'] += 1000 * 1<<BookType
 			memorizedSpells.append (Spell)
 
@@ -70,10 +71,11 @@ def GetUsableMemorizedSpells(actor, BookType):
 	# count and remove the duplicates
 	memorizedSpells2 = []
 	for spell in memorizedSpells:
-		if spell["SpellResRef"] in spellResRefs:
-			spell['MemoCount'] = spellResRefs.count(spell["SpellResRef"])
-			while spell["SpellResRef"] in spellResRefs:
-				spellResRefs.remove(spell["SpellResRef"])
+		resref = spell["SpellResRef"].lower()
+		if resref in spellResRefs:
+			spell['MemoCount'] = spellResRefs.count(resref)
+			while resref in spellResRefs:
+				spellResRefs.remove(resref)
 			memorizedSpells2.append(spell)
 
 	return memorizedSpells2
```

**Comment by lynxlynxlynx** [comment]
Hmm, grepping for tolower doesn't show anything problematic. CREMemorizedSpell's SpellResRef also looks untouched once set.  On the python side the list gets recreated every time. So I'm out of (sane) ideas.

A PR would be welcome either way, as it doesn't hurt to remove assumptions from the code.

**Comment by Tomsod** [comment]
If you're okay with the code, then of course.

The bug's cause could also be something on my system, maybe?  I'm running [ciopfs](https://www.brain-dump.org/projects/ciopfs/) to use BG2 files on Linux, could be its fault.  There _are_ lowercase spell files involved (in the mount base's override).

**Comment by lynxlynxlynx** [comment]
That would be convenient to blame, but once we read off the disk, the names stay in memory.
The diff looks fine.
