### ISSUE TITLE
Time Stop visually bad on OpenGL

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1712]
#### Bug description
I just noticed that when casting _Time Stop_ on BG2, there are two things bad or broken: The non-fog area is completely black, the fog areas is very dark in contrast to the original -- I think there is a darkening color-to-gray algorithm in play.

The black area is probably related to some mask problem or draw order on SDL2 + OpenGL.

#### Steps to reproduce
1. Start BG2
2. Cast Time Stop

#### Screenshots
![bg2_ts](https://user-images.githubusercontent.com/238558/201521847-1f4e5a24-61d8-45be-9d9a-b0478db2e2cb.jpg)

![bg2_rt](https://user-images.githubusercontent.com/238558/201521845-eedb36ba-2d2b-4808-abe0-76c01d42eb3b.jpg)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Hmm, sounds new, considering #1377.
