### ISSUE TITLE
BG2: familiar disappears after releasing it twice 

### ISSUE THREAD

**Issue by Tomsod** [gemrb/gemrb#1714]
After summoning a mage familiar, telling it to go into the backpack, releasing and storing it again, releasing it the second time won't work: familiar is gone forever.  Apparently the script that summons the familiar ultimately invokes this faulty code:
https://github.com/gemrb/gemrb/blob/7d347269fa6d1f8ea51881eb5637f40170f60766/gemrb/core/GameScript/GSUtils.cpp#L3102-L3104
Compare it to the code used almost everywhere in Actions.cpp (example):
https://github.com/gemrb/gemrb/blob/7d347269fa6d1f8ea51881eb5637f40170f60766/gemrb/core/GameScript/Actions.cpp#L2999-L3001
And this exception:
https://github.com/gemrb/gemrb/blob/7d347269fa6d1f8ea51881eb5637f40170f60766/gemrb/core/GameScript/Actions.cpp#L672-L676
As noted in the comment, `CreateMovementEffect()` causes actors to stop being persistent!  So what happens is that the familiar is summoned the first time, is removed from global actor list, and the second time there's nothing to summon.

I've used a quick fix in my own install by also checking for familiar EA, but it's really just a band-aid.  Instead, I think, someone needs to figure out why these two instances of moving actors don't check for `Persistent()` and if that can be safely changed.

**Comment by lynxlynxlynx** [comment]
Nice find, I'm sure that it's just a historical artefact and we need to review all these CreateMovementEffect calls.
