### ISSUE TITLE
No alteration casting sounds because of octal numbers in 2DA

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1716]
#### Bug description
So if you cast some alteration spell like Time Stop in BG2, you hear nothing – but the caster is supposed to mumble something. Looking around a bit, I spotted the culprit:

https://github.com/gemrb/gemrb/blob/2072737a31847bcfaa8100309be0dfdec17110e4/gemrb/unhardcoded/bg2/cgtable.2da#L14

Changing `08` to `8` confirms my suspicion: something interprets that as octal number, so this ends up badly.

Under unspecified circumstances `base` defaults to 0 here, i. e. asking the library to interpret the value by convention:

https://github.com/gemrb/gemrb/blob/2072737a31847bcfaa8100309be0dfdec17110e4/gemrb/includes/globals.h#L193

But since fixing something usually breaks something else for us, I'd like to ask what appears to be the best solution here:

1. Going through all of our `unhardcoded`/`override` 2DAs and replace what appears to be octal for nothing but visual alignment reasons.
2. Make 2DA code set the base to `10` explicitly. That will probably make these 2DAs work as expected, but I have no idea if anything really appears to be octal in the original data and will break.

Suggestions?

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
I thought they might need to be treated as strings, but it's clearly just a mistake in a refactoring — the initial implementation used `atoi`. No idea then why the data was entered that way.
We definitely also store hex in the 2das, so option 2 is a no go.

I doubt there's many octal-like values in our 2das. In fact, grepping for '\<0[0-7]\+\>' shows it's only cgtable.2da files that have the problem.
