### ISSUE TITLE
BG2: arrows of biting deal no damage to low-HP targets 

### ISSUE THREAD

**Issue by Tomsod** [gemrb/gemrb#1727]
Arrows of Biting deal percentage poison damage: 30% of the target's max HP over 20 seconds, or 1.5% per second.  But due to rounding, this results in 0 damage per second for targets with less than 67 max HP.  Here's the code:
https://github.com/gemrb/gemrb/blob/b6ce8a6996807d4a0a1d0be38dcbc4aed617d2ad/gemrb/plugins/FXOpcodes/FXOpcodes.cpp#L1004-L1011
One way to fix it would be to carry over the remainder after rounding, something like
`damage = (total damage until now) - (total damage until last update)`.
I don't understand how to access the effect's original duration, though, which would be necessary.

**Comment by lynxlynxlynx** [comment]
Parameter3-6 can be used for any other state if they are unused. 5 and 6 are a safe bet.
Did the original round up? Do some alternation?

**Comment by Tomsod** [comment]
Honestly, I haven't researched the original in detail and it wouldn't be convenient for me to do it.  As I understand, EE gave up entirely and just does 1 damage per second.

If you don't need to precisely copy the original BG2's algorithm, I could try to implement something later by storing total seconds in parameter 5, I guess.  Otherwise, research needed.

**Comment by lynxlynxlynx** [comment]
How about just adding a minimum of 1, so it's always at least 1 point of damage?

**Comment by Tomsod** [comment]
That's what I did for my install, but isn't it incredibly half-assed?

**Comment by lynxlynxlynx** [comment]
Not if nobody notices. And to prevent doing too much damage, the effect can keep a tally and shut itself down when reached.

I think it's more user friendly if in these cases the damage is dealt uniformly, but in a shorter time, than not applying something every few seconds.

**Comment by Tomsod** [comment]
I'll leave it to you then.
