### ISSUE TITLE
BG2: sleep effects broken on hit 

### ISSUE THREAD

**Issue by Tomsod** [gemrb/gemrb#1728]
In EE, sleep effects (`fx_set_unconscious_state`) use parameter 2 to indicate whether the effect should persist after the target is hit.  But at least my installation of (classical) BG2 doesn't seem to be aware of this, and parameter 2 is zero for all sleep-type spells (Sleep, Emotion, (Greater) Command...), which in EE terms should mean they only last until the first hit.  But that doesn't seem to be the spells' intended behavior.  Do we have a way to check if we're playing EE?
Here's the code snippet for reference:
https://github.com/gemrb/gemrb/blob/b6ce8a6996807d4a0a1d0be38dcbc4aed617d2ad/gemrb/plugins/FXOpcodes/FXOpcodes.cpp#L2176-L2190

**Comment by lynxlynxlynx** [comment]
Why would we need to check for EE here? Its data should already work — we check via these extra states in Actor::GetHit.

**Comment by Tomsod** [comment]
Oh, you're right.  But they still woke up for me!  Let me recheck just in case.

**Comment by Tomsod** [comment]
Yep, enemies still wake up.  Are you sure that extra state is set properly for non-EE installs?

**Comment by Tomsod** [comment]
Okay, I'm pretty sure the extra state is only ever set here:
https://github.com/gemrb/gemrb/blob/b6ce8a6996807d4a0a1d0be38dcbc4aed617d2ad/gemrb/core/Scriptable/Actor.cpp#L4248-L4253
And that damage flag depends on effect, I think.  Where's the EE check?

**Comment by Tomsod** [comment]
We're talking past each other, I think.  My problem is:

In EE, parameter 2 is used to determine if the target wakes up on hit.  Zero means wake up.

In classical BG2, parameter 2 is unused and targets never wake up.

In my classical BG2 install, all sleep effects I see have zero parameter 2.

In the original, classical game, this would result in no wake up on hit.

In GemRB, these effects do result in waking up on hit.

This is not the original game behavior.

If GemRB haven't treated these effects as EE effects, it wouldn't be a problem.

Can we check for that?

**Comment by lynxlynxlynx** [comment]
Ahh, I thought the originals had wake on damage by default. I tried bg1 now and you're right, at least bg1 doesn't. So yeah, a new game flag for ee effects will be needed. I haven't added one yet, since it wasn't clear how many we'll need (eg. there's a specific bullshit opcode that works in reverse on SoD).

**Comment by burner1024** [comment]
Do you really even want to match both? Maybe just expose that as a setting?

**Comment by lynxlynxlynx** [comment]
That's what game flags are for. We're sometimes lazy and have the same one do multiple things, but most toggle a single setting.
