### ISSUE TITLE
BG2: wrong level for newly joined PCs 

### ISSUE THREAD

**Issue by Tomsod** [gemrb/gemrb#1729]
I've noticed that the companions joining me in BG2 consistently have one level lower than they're supposed to, according to the npclevel table.  Apparently my table starts with level 2, and the relevant code expects it to be level 3:
https://github.com/gemrb/gemrb/blob/b6ce8a6996807d4a0a1d0be38dcbc4aed617d2ad/gemrb/core/Game.cpp#L894-L904
So that a hypothetical level 3 PC would end up on the first column, which is level 2 for me (the 0th is script names).  And by the way, if the table _would_ start with 3, then `safeLevel` would be off by one, I think.

So it could be just a typo, but maybe the minimum level differs by game, in which case it would need to be parsed.  Research needed.

**Comment by lynxlynxlynx** [comment]
I think it's just an off-by-one error and should also check for equality. But come to think of it, why repeat this static check all the time? Just move it to where the level is determined and return false there.
