### ISSUE TITLE
weidu log parse error

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1735]
#### Bug description
weidu.log is being parsed as utf-8.
In fact, it's mostly ascii, often cp1252, but in general can contain a mix of different encodings.
I'm not sure if there's a good solution.

```
[GUIScript]: Loading Script Game.
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/opt/gemrb/share/gemrb/GUIScripts/bg2/Game.py", line 38, in EnterGame
[Python/ERROR]:     MessageWindow.OnLoad()
[Python/ERROR]:   File "/opt/gemrb/share/gemrb/GUIScripts/MessageWindow.py", line 34, in OnLoad
[Python/ERROR]:     MessageWindow = GemRB.LoadWindow(12, GUICommon.GetWindowPack(), WINDOW_BOTTOM|WINDOW_HCENTER)
[Python/ERROR]:   File "/opt/gemrb/share/gemrb/GUIScripts/GUICommon.py", line 51, in GetWindowPack
[Python/ERROR]:     if default == "GUIW" and GameCheck.HasWideScreenMod ():
[Python/ERROR]:   File "/opt/gemrb/share/gemrb/GUIScripts/GameCheck.py", line 87, in HasWideScreenMod
[Python/ERROR]:     for line in weiduLog:
[Python/ERROR]:   File "/usr/lib/python3.10/codecs.py", line 322, in decode
[Python/ERROR]:     (result, consumed) = self._buffer_decode(data, self.errors, final)
[Python/ERROR]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 3756: invalid continuation byte
```

#### Steps to reproduce
1. Install some mods with non-english translations
2. Load game
3. check console
4. see error

#### Expected behavior
No error

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by MarcelHB** [comment]
Does this work for you?
```diff
--- a/gemrb/GUIScripts/GameCheck.py
+++ b/gemrb/GUIScripts/GameCheck.py
@@ -79,7 +79,7 @@ def HasWideScreenMod ():
        gamePath = GemRB.GetSystemVariable (SV_GAMEPATH)
        weiduLogPath = os.path.join (gamePath, "weidu.log")
        try:
-               weiduLog = open (weiduLogPath)
+               weiduLog = open (weiduLogPath, encoding='latin-1')
        except OSError:
                return False
```

Since we are only interested in comparing against ASCII byte sequences, this should be safe. Otherwise, Python picks some platform-dependent default (`utf-8` Linux, something else on Windows) that may collide with that logfile.

**Comment by burner1024** [comment]
That removes the error from the log.
