### ISSUE TITLE
Map polygons are partially broken 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1747]
#### Bug description
I noticed that on some maps dithering actors was missing when crossing a polygon. That rules out SDL trouble, and bisect says it started with 92778c519cb111b1321c083e2d0c8e2a58a87940

#### Screenshots
Both cases to see:
![dithering_bad](https://user-images.githubusercontent.com/238558/204668632-8a6fa0c1-b6fd-4c6d-b3aa-5e7111381ef8.jpg)
![dithering_ok](https://user-images.githubusercontent.com/238558/204668635-39d16578-14c1-4761-8830-cd9e7b75de4f.jpg)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment]
ah, yeah, that'd do it. wanna submit a PR to refer that then? I'm not around to do it.

**Comment by MarcelHB** [comment]
I'd revert that part accordingly? I guess we don't need `ReadRegionTransposed` or something for that case.

**Comment by bradallred** [comment]
Well the first question is: are the other uses of `ReadRegion` doing the correct thing? if I just mixed up the order then we fix that, but if the data files really have 3 different was of specifying rectangles thats a bit annoying, but I don't see the need for a flavor of `ReadRegion` for a single use.

**Comment by MarcelHB** [comment]
As far as I have checked your other commits, the other use cases of this function are valid.
