### ISSUE TITLE
Death at BG2 start 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1751]
#### Bug description
Start new game, immediately die (before cutscene). ToB too.
BG2 classic with fixpack.
This is on current master. Doesn't happen with 0.9.1.

Not much in logs, some ActionOverride errors.
```
GameScript/ERROR]: ActionOverride failed for object and action: 
[GameScript/DEBUG]: IDS Targeting: 0 0 0 0 0 0 0 0 0 0 
Filters: 26 0 0 0 0 

[GameScript/DEBUG]: Int0: 0, Int1: 0, Int2: 0
String0: , String1: 
Point: (0, 0)
1. IDS Targeting: 0 0 0 0 0 0 0 0 0 0 
Filters: 26 0 0 0 0 
2. Object - NULL
3. Object - NULL
RefCount: 2     actionID: 223

[ResourceManager]: Found 'csjon.cre' in 'Override'.
[ResourceManager]: Found 'NIREg11.bam' in 'chitin.key'.
[GameScript/ERROR]: ActionOverride failed for object and action: 
[GameScript/DEBUG]: IDS Targeting: 0 0 0 0 0 0 0 0 0 0 
Filters: 21 0 0 0 0 

[GameScript/DEBUG]: Int0: 165, Int1: 0, Int2: 0
String0: , String1: 
Point: (0, 0)
1. IDS Targeting: 0 0 0 0 0 0 0 0 0 0 
Filters: 21 0 0 0 0 
2. Object - NULL
3. Object - NULL
RefCount: 2     actionID: 40

[ResourceManager]: Found 'NIREg12.bam' in 'chitin.key'.
[ResourceManager]: Searching for 'deathand'...
[ResourceManager]: Found 'deathand.mve' in 'chitin.key'.
[ResourceManager/ERROR]: Couldn't find 'deathand.2da'.
[MUSImporter]: Playing SPC1...
[ResourceManager]: Found 'GUIW08.chu' in 'chitin.key'.
[ResourceManager]: Searching for 'GUDEATH8'...
[ResourceManager]: Found 'GUDEATH8.mos' in 'chitin.key'.
[ResourceManager]: Found 'GUIWSMB.bam' in 'chitin.key'.
```

#### Steps to reproduce
Start new game.
Tried pre-gen cleric, hand-made barbarian.

#### Expected behavior
Not dying.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Thanks, this is probably related to the recent hp changes.

**Comment by lynxlynxlynx** [comment]
That mostly fixes it; I guess it should be done with a delay to account for conbon, but good enough as a stopgap. It also looks like we don't finish the usual fade-in, which is a new problem. And we shouldn't be touching the stats of imported actors anyway.
