### ISSUE TITLE
Autopause: spell cast doesn't work

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1753]
#### Bug description
BG2 classic.
Autopause: spell cast setting has no effect.

#### Steps to reproduce
1. Start a new game.
2. Enable autopause on cast.
3. Cast any spell.

#### Expected behavior
Working autopause.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [x] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
It does work, it's just disable out of combat to be friendlier to users.

**Comment by burner1024** [comment]
Hmm, but the original behaviour is very useful for pre-battle buff routines. On the other hand, out of combat pause never seemed to be a problem for me. Maybe a separate setting for this?

**Comment by lynxlynxlynx** [comment]
Not via the gui, but it could be done by using another bit in "Auto Pause State", which one can change manually in the ini.

**Comment by burner1024** [comment]
Should I open a new issue for that?

**Comment by lynxlynxlynx** [comment]
Sure.
