### ISSUE TITLE
Web: "Held" is not displayed for the caster

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1754]
#### Bug description
"Held" is not displayed in dialog window when caster is held by his own Web.
Also, you can see that Imoen's selection circle is not disabled, and interface is available to give orders, although she doesn't respond to them.

BG2 classic.

#### Steps to reproduce
1. Start new game.
2. Have Imoen cast Web on self and PC.

#### Expected behavior
"Held" displayed for all webbed characters.

#### Screenshots
![Captura desde 2022-12-04 04-45-09](https://user-images.githubusercontent.com/1279852/205463357-b0e6f1fd-1902-46f3-91d5-1a5f1a236c1a.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [x] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Test with someone else or post-Spellhold Imoen — the CI one has a bunch of immunities and defenses in her unremovable belt.

**Comment by burner1024** [comment]
You are right... with PC mage, it's displayed properly. I didn't think.
The interface difference remains, not sure if intended or not, but actually it might be better than the original, being able to change orders for held chars, so that they carry on when released.
