### ISSUE TITLE
Stinking Cloud 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1755]
#### Bug description
See screenshot below.

1. For some reason Stinking Cloud shows Save vs Polymorph, when it should be Poison.
2. How do you even get 27 on a save roll? Isn't it supposed to be 1-20?
   (I don't know is the roll shows bonuses/maluses - it would be great to see the original roll and all the modifers affecting it. But this spell has no roll mods, and the characters have no gear anyway).
4. Look at the portraits. PC has "Unconscious" icon and is actually unconscious. But standing.
5. Imoen has "Poisoned" icon and other than that is not affected.

BG2 classic.

#### Steps to reproduce
1. Start new game.
1. Have Imoen cast Stinking Cloud on self and PC.

#### Expected behavior
1. Correct saving throw type.
2. Correct saving throw range.
3. Portrait icons and stance consistent with character state.

#### Screenshots
![Captura desde 2022-12-04 04-52-00](https://user-images.githubusercontent.com/1279852/205463748-6977c7e5-a2fc-428f-8ef6-cd0ab7864e9d.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
1. I see, the strings for both are swapped, easy to fix.
2. It's the roll plus any bonus from the spell (+2 here) or stats — most notably luck, so if you're on the easiest settings, you get +6 just from that.
3. Probably just a stance thing, the effect should do more.
4. Again, bad test subject.

**Comment by burner1024** [comment]
Why +2? I don't think SC has any bonuses.

Something strange is going on with difficulty slider:
1. Load game.
2. Go to difficulty setting, max it out, click "Done".
3. Go to difficulty setting again, but don't change it, just see that it's maxed out, then "Cancel".
4. Go there for the 3rd time. Now it's set to minimum.

At step 2), rolls seem to be in normal range (it would be nice to have a breakdown for clarity, not sure if there's a setting for that?)

Sances seem to work intermittently. But if a character is laying at the end of the spell, he remains laying there after it ends.
This is a long time after cast, Jaheira not getting up.
![Captura desde 2022-12-04 05-46-55](https://user-images.githubusercontent.com/1279852/205465270-0da821a1-bfc7-4545-9191-9850076dfcad.png)

**Comment by lynxlynxlynx** [comment]
Don't trust the description, look at the data (+2).

**Comment by burner1024** [comment]
Dang, how does this stuff go unnoticed for 20 years.
