### ISSUE TITLE
 Fist fighting is slow

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1756]
#### Bug description
In BG2 (didn't test the other ones), fist fighting is a very tough matter, it looks as if the attacks per round is 1 vs. maybe 3 in the original.

#### Screenshots
Original:
![fists2](https://user-images.githubusercontent.com/238558/205464646-b04198df-4f9a-4a59-84fb-aa14ad0958cf.gif)

gemrb:
![fists](https://user-images.githubusercontent.com/238558/205464658-601c39e4-dee9-43b3-b94e-bef71eede530.gif)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

**Comment by lynxlynxlynx** [comment]
The original draws fake attacks, that's all. There's a tobex component to remove this fluff.
It'll be fixed with #92.

**Comment by MarcelHB** [comment]
Fake attacks? My world just shattered a little ... anyway, makes sense in a lot of ways.
