### ISSUE TITLE
Silence visual played multiple times

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1757]
#### Bug description
- Silence's visual (blue cloud, see screenshot) and sound are played multiple times. 2 times, and a 3rd starts, then disappears.
- Occasionally, Jaheira's cloud would appear split in 2. It's rare and I don't know how to reproduce.
- Multiple saving throw messages are displayed. This is only on master. 0.9.1 doesn't show save rolls for me, not sure how to enable.

BG2 classic.

#### Steps to reproduce
1. Start new game with a cleric.
2. Cast Silence on Jaheira and Minsc.

#### Expected behavior
Visual played 1 time, without glitches, save rolls also shown only 1 time.

#### Screenshots
![Captura desde 2022-12-04 05-56-54](https://user-images.githubusercontent.com/1279852/205466019-aa7100e6-6905-4bd6-bcff-f35dd22f4bb9.png)
![Captura desde 2022-12-04 06-13-21](https://user-images.githubusercontent.com/1279852/205466071-1019919e-e9dc-4d94-9aa6-8915dd30af5a.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [x] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Looking at sppr211:
1. The effects have a duration of 3s, but the bam played has frames for just over a second. So it gets restarted. Looks like the effect should keep vvc state in mid as well.
2. 🤷🏾 
3. A check was too strict before and now it's too lax.
