### ISSUE TITLE
Formation issues

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1759]
#### Bug description
1. Formations are not geometrically perfect in the first place.
2. They get distorted further when rotating.
3. Presumed destination get "pre-bumped" by actors and in particular, the same selected actors.

#### Steps to reproduce
1. Select a few actors, try various formations and rotate.

#### Expected behavior
- Formations actually matching their geometry
- No distortion on rotation.
- Selected characters should try to bump busy spots. Or, at least ignore positions of currently selected characters when calculating destinations.

#### Screenshots
This is not a proper hexagon.
![Captura desde 2022-12-06 02-23-05](https://user-images.githubusercontent.com/1279852/205724943-d5a1fb36-2d40-4326-8272-984ecad06efa.png)

These T's are gravitating towards south (other formations also get distorted similarly).
![Captura desde 2022-12-06 02-24-50](https://user-images.githubusercontent.com/1279852/205725367-e38d50ae-2240-46fa-a094-a4d8fa88f7ef.png) ![Captura desde 2022-12-06 02-24-57](https://user-images.githubusercontent.com/1279852/205725372-38626d65-16d9-4175-8760-7d11805147ec.png)

T turned into mush by currently selected characters
![Captura desde 2022-12-06 02-28-14](https://user-images.githubusercontent.com/1279852/205725758-88e1b3d7-769f-4370-9ab3-e0500919261b.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
1. Likely just erroneously taking the isometric perspective into account.
2. Probably the same thing.
3. What do you mean? We do take the search map into account, yes.

**Comment by burner1024** [comment]
3. I mean I expect to see a T.

**Comment by bradallred** [comment]
re 3 we purposely deviate from the original to show where the actor will be directed to. Maybe this could be enhanced to ignore actors tho.

**Comment by burner1024** [comment]
Yes, ideally this would ignore all bumpable actors. Destinations jump all round when rotating in a crowded area, screenshots don't show that very well, but I'm struggling with recording a video unfortunately.

Or, if that's not possible for some reason, at least ignore+bump player controlled ones.

**Comment by bradallred** [comment]
As for the unexpected curvature, I don't see anything that sticks out mathematically speaking. We certainly aren't performing an isometric transformation. My guess would be unexpectedly hitting the `isWithinRadius` check:

https://github.com/gemrb/gemrb/blob/65803e89b4ce5c2c8773c48f3c94440644ca4287/gemrb/core/GUI/GameControl.cpp#L217-L225

this check is so that actors cannot get assigned to a location already assigned to the formation. This could either be due to different formations using a different radius, or just needing to subtract one from the check.

However, we are supposed to alternate directions of the search for every actor, so I would have expected a jagged line rather than a curve.

https://github.com/gemrb/gemrb/blob/65803e89b4ce5c2c8773c48f3c94440644ca4287/gemrb/core/GUI/GameControl.cpp#L166

you can inspect the script that generates the formations here:
https://github.com/gemrb/gemrb/blob/3f2baf8289021f404b5a8e19c324705fff5318db/admin/make_formation.py

**Comment by burner1024** [comment]
> you can inspect the script that generates the formations here:

So is this script supposed to generate mathematically correct formations?
I tried plotting it. Doesn't look great with 6, and with 20 I don't even know what it's supposed to be.

![6](https://user-images.githubusercontent.com/1279852/205779248-c915aa9d-1955-422d-ab74-dde96445020a.png)
![20](https://user-images.githubusercontent.com/1279852/205779261-d95712b0-534f-4f4d-98aa-c49a0c86cee8.png)

**Comment by bradallred** [comment]
> So is this script supposed to generate mathematically correct formations, or they get smoothed later?

I have no idea what you mean.

> Doesn't look great with 6, and with 20 I don't even know what it tries to be. Not that original does any good with formations over 6.

you'd have to look at the generated 2da files to see how many positions we generated with, but we probably did 6. Anything beyond what is in the data is generated is calculated another way:
https://github.com/gemrb/gemrb/blob/65803e89b4ce5c2c8773c48f3c94440644ca4287/gemrb/core/GUI/GameControl.cpp#L191-L214

**Comment by burner1024** [comment]
> I have no idea what you mean.

I mean, you see that it's asymmetric, right? Is it intended?


I actually thought it's supposed to be equilateral, but double checking the original, it's not. Still pretty symmetric, though.
![Captura desde 2022-12-06 12-33-43](https://user-images.githubusercontent.com/1279852/205826284-9506e384-5760-4157-a195-c466de098257.png)

**Comment by burner1024** [comment]
Wait, I re-plotted hex from actual formatio.2da, and it's better
![6](https://user-images.githubusercontent.com/1279852/205977318-53fee9fc-199f-43ac-a187-ac0f9f1b8f53.png)

Looks like the script is dated.

Penta is the same.

**Comment by bradallred** [comment]
feel free to submit a PR

**Comment by burner1024** [comment]
> We should probably not be using a hardcoded radius at all, and instead keep track of the actors occupying the positions so we can do a personal distance check between the two instead.

I think that's the thing. Technically, formations don't even use a radius.
And if the algo is enhanced to ignore bumpable actors, then there's no need to even check distance?

**Comment by bradallred** [comment]
> And if the algo is enhanced to ignore bumpable actors, then there's no need to even check distance?

No, this has nothing to do with the current location of the actors, it's the location in the formation being produced. The former is just an easy modification to the search map flags we check (`area->GetBlocked(dest) & PathMapFlags::PASSABLE`)

>  Technically, formations don't even use a radius.

No, but we use a radius for:
# the positions of actors beyond the generated formation (eg summons) 
# adjusting positions if they are unreachable (eg into a wall)
# knowing if a calculated position overlaps with another (so we can adjust it)

so we need a radius or the "circle size" of each formation position

**Comment by burner1024** [comment]
Oh you mean position radius. I think the script is not consistent much abouth that.
It's probably gonna bite in the rear with creatures that have large foot circles, too.

So anyway, the rotation distortion bug remains at large.
I tried to replace `return p.isWithinRadius(radius, dest);` with `return false;`, it doesn't change anything.

**Comment by lynxlynxlynx** [comment]
So what's the distortion, the squashed hexagon? Are we sure the data is ok?

**Comment by bradallred** [comment]
> There's a fixme note, something about precision, maybe related.

Yes, but that is in the NextDest calculation, which shouldn't be executed unless we think we are in a condition where the point needs to be adjusted. In a wide open space with no actors (like the T formation in your 2nd and 3rd screenshots) no adjustments should be taking place. Thats why I thought the problem might be the radius check. Since its not, that leaves pretty much just the incoming `angle` parameter and `RotatePoint` as suspects.

**Comment by bradallred** [comment]
I didnt necessarily mean for this to get closed, but neither did I see distortion. part of the problem might be you have a very small angleworm the click point to the cursor?

**Comment by burner1024** [comment]
I tried with latest changes, unfortunately the angle distortion remans.

>  a very small angleworm the click point to the cursor?

If I understood this correctly, here's another screenshot:
![Captura desde 2022-12-09 02-51-18](https://user-images.githubusercontent.com/1279852/206553806-4e2023ee-0586-48c7-b4e3-ca4e2cf23558.png)

**Comment by bradallred** [comment]
yes, thats what I was asking.

**Comment by bradallred** [comment]
<img width="672" alt="image" src="https://user-images.githubusercontent.com/1126744/206556718-4d48f726-90c0-4e71-b588-999218fe26e3.png">

Do I not understand the problem?

**Comment by burner1024** [comment]
Dang, I could swear it was not 90 degrees. It could be a optical illusion thing. I'll double check everything and report.

**Comment by bradallred** [comment]
my guess is your eyes are deceived due to the reticles not being oriented. they are always drawn in the same orientation.

**Comment by lynxlynxlynx** [comment]
I don't think so, it looks like there's a 1px error for the 6th and onward. It's of course clearer if you don't zoom out. In this pic if you align the first two centers of the cross, only one more falls on the same line:
![image](https://user-images.githubusercontent.com/121515/206578257-6016dba4-33fb-4cac-8dc2-30d2662ae0b3.png)

**Comment by burner1024** [comment]
OK, I apologize for the confusion, but it appears that it's the other way around: GemRB draws perfect angles, and original either apply some isometric voodoo, or just have buggy rotation code.
Here's a T from original:
![Captura desde 2022-12-09 05-48-24](https://user-images.githubusercontent.com/1279852/206583615-bc1efa04-6673-498b-9ffc-386f8f56fbbe.png)

**Comment by bradallred** [comment]
> I don't think so, it looks like there's a 1px error for the 6th and onward. It's of course clearer if you don't zoom out. In this pic if you align the first two centers of the cross, only one more falls on the same line:
> ![image](https://user-images.githubusercontent.com/121515/206578257-6016dba4-33fb-4cac-8dc2-30d2662ae0b3.png)

1 px is just a combo of truncating instead of rounding and probably not being at exactly 0 degrees to begin with. we also have no sub pixel rendering.

> original either applies some isometric voodoo

probably. easy to check. take samples at 45 deg increments and see how they change. I'd wager the top of the T when its right side up is longer than when on its side.

**Comment by burner1024** [comment]
I get 190px for top of the T when in vertical orientation and 144px when it's on the side
![Captura desde 2022-12-09 06-54-42](https://user-images.githubusercontent.com/1279852/206592979-5731aeec-9e14-4b68-93c0-64b8bf75f774.png)
![Captura desde 2022-12-09 06-57-18](https://user-images.githubusercontent.com/1279852/206592307-d77a2424-5d5a-432c-b690-4387465ffbbb.png)

More samples below



![Captura desde 2022-12-09 06-56-34](https://user-images.githubusercontent.com/1279852/206592299-2716d31f-b1e9-4e86-a4f7-92de654dd9a4.png)
![Captura desde 2022-12-09 06-56-54](https://user-images.githubusercontent.com/1279852/206592303-37b50b12-4b61-4843-b6c8-70d221f23cd8.png)


![Captura desde 2022-12-09 06-57-34](https://user-images.githubusercontent.com/1279852/206592281-d797c984-acd4-446c-bcf3-8bd90bdaa3c5.png)
![Captura desde 2022-12-09 06-55-21](https://user-images.githubusercontent.com/1279852/206592289-55b043cf-da3f-4f94-aaa3-7663d1bcaac2.png)
![Captura desde 2022-12-09 06-55-45](https://user-images.githubusercontent.com/1279852/206592290-b0a38e06-394a-4fff-a633-34f0e92e28b9.png)
![Captura desde 2022-12-09 06-56-07](https://user-images.githubusercontent.com/1279852/206592294-7fb95c97-ed73-4b57-a9ec-d64eadebe371.png)

**Comment by MarcelHB** [comment]
Yeah, the rotation is in the wrong space: screen space instead of ... projected-camera space, or whatever we'd like to call this static, isometric thing. If you look how an X axis rotation ccw is from (1, 0) to (0, 0.75), an Y axis ccw from (0, 0.75) to (-1, 0), and look at `RotatePoint`, it doesn't take this into account for its canonical form. If instead we do this for this case:

```cpp
int newy = static_cast<int>(p.x * std::sin(angle) * 0.75 + p.y * std::cos(angle) * 0.75);
```
We'd get it fixed (red is >90°, green < 90°C, as on your screens of the original).

![formation](https://user-images.githubusercontent.com/238558/206605361-025e98ef-a7db-4bc7-9cd3-e70a396cc60f.jpg)

**Comment by bradallred** [comment]
no, `RotatePoint` is the wrong place to apply an isometric projection. For one such a coordinate wouldn't work for sampling the search map.

Is `dest.y = ((dest.y - origin.y) * 0.75) + origin.y;` right before `return dest;` not enough?

we should probably have some generic way of doing this transformation too.

**Comment by JohnG1985** [comment]
Yes, using dest.y = ((dest.y - origin.y) * 0.75) + origin.y before returning dest should be sufficient to apply an isometric projection. It's also a good idea to have a generic way of doing this transformation, which can be used in other parts of the code that require isometric projections.

Here is an example of a generic function that can be used to apply an isometric projection to a point:

Point applyIsometricProjection(const Point& point) {
  return Point((point.x - point.y) * 0.5, (point.x + point.y) * 0.25);
}


You can then use this function to apply an isometric projection to the dest point before returning it from the RotatePoint function. This should ensure that the resulting coordinates are properly transformed and can be used for sampling the search map.

Here is an example of how you could use the applyIsometricProjection function in the RotatePoint function:


Point GameControl::RotatePoint(const Point& origin, const Point& dest, int angle) {
  // Rotate the point around the origin by the specified angle
  int x = origin.x + (dest.x - origin.x) * cos(angle) - (dest.y -

**Comment by MarcelHB** [comment]
I was looking for something without translating away from `origin` and without touching `RotatePoint` but it was a little late for math-on-paper. So yes, and something like this inside of `GetFormation`:
```cpp
auto p = RotatePoint(...);
p.y = static_cast<int>(0.75 * p.y);
```
is equivalent.

**Comment by JohnG1985** [comment]
If you want to avoid using RotatePoint and instead modify the y value of
the point directly, you could use something like this inside of GetFormation
:

Copy code
auto p = GetOriginalPoint();p.y = static_cast<int>(0.75 * p.y);

This will adjust the y value of the point by multiplying it by 0.75,
effectively reducing its value by 25%. This will have the effect of moving
the point closer to the origin along the y axis.

Alternatively, if you want to use a more mathematically precise approach,
you could use a matrix to perform the rotation and translation of the
point. This would allow you to avoid using the RotatePoint function
altogether and instead apply the transformations directly to the point
using matrix multiplication.

Here is an example of how you could do this:

Copy code
// Define the rotation matrix
Matrix rotationMatrix = {
    {cos(angle), -sin(angle)},
    {sin(angle), cos(angle)}
};
// Define the translation matrix
Matrix translationMatrix = {
    {1, 0, x},
    {0, 1, y},
    {0, 0, 1}
};
// Define the original point as a column vector
Vector originalPoint = {
    {x},
    {y},
    {1}
};
// Rotate and translate the point using matrix multiplication
Vector rotatedTranslatedPoint = translationMatrix * rotationMatrix *
originalPoint;
// Extract the x and y coordinates of the rotated and translated point
int rotatedTranslatedX = rotatedTranslatedPoint(0, 0);
int rotatedTranslatedY = rotatedTranslatedPoint(1, 0);

Using this approach, you can apply any combination of rotations and
translations to the original point using matrix multiplication, allowing
for more precise control over the final position of the point.

**Comment by MarcelHB** [comment]
Is this how the takeover of ChatGPT collaborators looks like?

**Comment by JohnG1985** [comment]
Yes, it is.  Did it help you ???

**Comment by bradallred** [comment]
the realization that the originals were doing an isometric projection for formations makes me wonder what else should be considering it? The main thing that comes to mind are `PersonalDistance` checks which could affect scripting.

I wonder if you can get closer to another actor in vertical space than horizontal? We would probably have to use IE script to check this in the original.

**Comment by lynxlynxlynx** [comment]
The originals were inconsistent in using isometric calculations. We already use them heavily in scripting as well. Nothing to worry about.

**Comment by burner1024** [comment]
So, uhm, any consensus on how the diff would look, or is it still up for discussion?

**Comment by bradallred** [comment]
you could try something like this:
```diff
diff --git a/gemrb/core/GUI/GameControl.cpp b/gemrb/core/GUI/GameControl.cpp
index 234093d6c..b87f9597b 100644
--- a/gemrb/core/GUI/GameControl.cpp
+++ b/gemrb/core/GUI/GameControl.cpp
@@ -182,6 +182,7 @@ Point GameControl::GetFormationPoint(const Point& origin, size_t pos, double ang
 		stepVec.x = radius * direction;
 	}
 	
+	vec.y *= 0.75f; // isometric projection
 	Point dest = vec + origin;
 	int step = 0;
 	constexpr int maxStep = 4;
@@ -210,7 +211,9 @@ Point GameControl::GetFormationPoint(const Point& origin, size_t pos, double ang
 			}
 		}
 		
-		return origin + start + RotatePoint(stepVec, angle + stepAngle);
+		Point rotated = RotatePoint(stepVec, angle + stepAngle);
+		rotated.y *= 0.75f; // isometric projection
+		return origin + start + rotated;
 	};
 
 	while (step < maxStep) {
```

**Comment by burner1024** [comment]
That looks similar enough:
142px / 106px ~ 1.339, about same as 190/144 ~ 1.319.
The angle at 45 rotation is also about 106 degrees.

![1](https://user-images.githubusercontent.com/1279852/207987189-6cfa1a55-7d89-4400-b9ff-ab5a12f0061d.png)
![2](https://user-images.githubusercontent.com/1279852/207987199-4ac01b3e-df97-402d-ab1c-cc8ff15ef7ec.png)
![3](https://user-images.githubusercontent.com/1279852/207987205-d099edf1-f7fd-4923-8d5b-80d1309a97ad.png)

**Comment by lynxlynxlynx** [comment]
I've committed Brad's patch and with that I think all the issues mentioned here have been dealt with.
