### ISSUE TITLE
 GEMRB and BG1 EE

### ISSUE THREAD

**Issue by rossimariolee** [gemrb/gemrb#1764]
Hi,

**Does GemRB support the EE version of BG1 and BG2 ?**

There are a lot of info but I cannot find a real answer (  :sob:  ), so I'm asking you about...

I need only to play Bg1 **EE** and Bg2 **EE** on Raspberry PI4 and I wander if them are supported.

Thank you really.

**Comment by rsantellan** [comment]
Hi @rossimariolee they are not supported: [Status page](https://gemrb.org/Features.html)

Regards
