### ISSUE TITLE
 C++14 support

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1768]
#### Description

In 2019, we enabled C++11. Now in 2023, we can maybe consider C++14 as base line soon? I recently noticed some QoL features are still not available in C++11 (like binary literals, some constexpr, better lambda captions), and the standard itself is nowhere a huge difference as from old-style to C++11.

The support is there in [all of our](https://en.cppreference.com/w/cpp/compiler_support/14) current compiler versions we have for compatbility testing for a long time already.

**Comment by lynxlynxlynx** [comment]
I don't mind, hit the need a few times myself as well. I suggest we do it after the next release, giving a heads up in the release/packager notes.

**Comment by bradallred** [comment]
we have a few todos in the code tagged with C++14, so lets fix those as well.

we can replace our make_unique with std::make_unique as well.
