### ISSUE TITLE
PST: proper floating text support

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#177]
PST has no message window and everything except dialog is displayed as overhead text. It was animated to move away, slowly fade and maybe do some avoidance with other text. We don't do almost any of that yet.

(wiki) Here is a rough guess at how it works:
  * each actor on the game screen has a message queue
  * when an actor takes damage, casts a spell, etc, a message is added to the queue
  * the queue is printed to the screen at roughly a rate of 3 per second
  * the messages float up and dissolve at +100px in about 3s, leaving space for the next message
  * no special care seems to have been taken to avoid overlapping messages, apart from the fact that actors occupy a different physical location on the screen

Revisit also FloatMessageAtPoint to avoid the need to create placeholder actors (just Map's overhead queue directly if possible).

**Comment by burner1024** [comment]
Some details:
- damage inflicted by party is white
- damage taken by party is red

**Comment by lynxlynxlynx** [comment]
Some small progress on this. The colors mentioned by @burner1024 are now implemented. The overhead text handling has been disentangled from Scriptable to its own struct and files, so future work will be simpler.
