### ISSUE TITLE
BG2: Party formation when moving always point right 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1775]
#### Bug description
I notice that the party formations always is pointing to the right side, and sometimes it seems that is not a straight (This I don't know how to explain it)

I have compared with the v0.9.1.1 tag and are different.

#### Steps to reproduce
1. Go to any place with space
2. Click on select all party
3. Move them around in different directions

#### Expected behavior
The formation should look to the place you are moving.

#### Screenshots
**Master**

https://user-images.githubusercontent.com/1820598/211698738-c7a3ed70-c1c0-442f-a174-288840d41dd0.mp4

**v0.9.1.1**

https://user-images.githubusercontent.com/1820598/211698748-822c438e-49d3-430c-856e-99aa665efa3b.mp4

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [X] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by MarcelHB** [comment]
It's a regression from one part of f86598f8df0895cce1da7a6b53b8672b63c8f020. Obvioulsy this `isFormationRotation` refers to any rotation including the calculated one, not just the manually adjusted ones.

**Comment by rsantellan** [comment]
@MarcelHB that change should be reverted ? Don't know why the change of logic.

**Comment by bradallred** [comment]
No, it shouldn't be reverted, else you reintroduce a different bug. `isFormationRotation` _shouldn't_ be `true` unless you are rotating a formation, so if thats not the case that is a bug.

**Comment by MarcelHB** [comment]
Can you look at this? Because trying something else but the original code made me lose either auto-orientation or manual rotation.

**Comment by lynxlynxlynx** [comment]
@bradallred any progress on this?

**Comment by bradallred** [comment]
I can get it done this week
