### ISSUE TITLE
 Minor visual artifacts on DXT textures on Windows

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1777]
#### Bug description
I just tried running BG2EE + demo on a new Windows/GCC build. I observed something that I cannot reproduce on Linux, and regardless of the renderer backend, but also without any warning in the compiler like type warnings or anything.

Some of the EE game textures have little visual glitches, deterministic ones. Appears to be around alpha regions.

#### Screenshots
![bg2ee_quit](https://user-images.githubusercontent.com/238558/213875852-ea6c1e0b-acd6-464a-9a38-b75be6b27c36.jpg)
![bg2ee_ui](https://user-images.githubusercontent.com/238558/213875854-dcbd90bc-fbe8-4d94-8958-561d1a172cfb.jpg)
![demo_swirl](https://user-images.githubusercontent.com/238558/213875855-c77776fb-9d61-4156-8d42-f85cf83cd077.jpg)
![bg2ee_menu](https://user-images.githubusercontent.com/238558/213875857-34aa9b1c-398c-43ff-8052-50f199f37111.jpg)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by MarcelHB** [comment]
@bradallred I found something I yet need an explanation for. I use GCC v12.2. on both Linux and Windows, and it appears that his line lacks portability, I guess:

https://github.com/gemrb/gemrb/blob/ff591e15c1c7181c71177490754c75ca69ffa34a/gemrb/plugins/PVRZImporter/PVRZImporter.cpp#L367

The idea is simple: get the exact three bits that I need from that bit-string. Works well on Linux. Looking at the assembly there:
```asm
mov     edx, 7
sal     rdx, cl
mov     rax, rdx
and     rax, QWORD PTR [rbp-16]
```
On Windows, in contrast:
```asm
mov	ecx, eax
sal	edx, cl
mov	eax, edx
and	rax, QWORD PTR [rbp-16]
```
Not sure about your x86 ASM familiarity, but `edx` means the value is considered 32bit here whereas `rdx` means 64bit, and obviously the shift (`sal`) puts the bittern into nirvana if the shift value is too high (or maybe it's the following `mov`, but doesn't matter much), so we end up with 0. But since this is 48bit of data, I definitely need a 64bit type.

I can fix this only by changing `0x7UL` into `uint64_T{7}`. I remember some warnings/error that `0x7` alone was rejected by some compiler for data loss, but GCC did not complain about this (don't have UBSan on Windows atm.) and the [docs says](https://en.cppreference.com/w/cpp/language/integer_literal) this should have worked.

Are you aware of anything w. r. t. standard or something that undermines this, silently? I find this even more odd given that it's virtually the same compiler on these platforms.

**Comment by bradallred** [comment]
I can't try this without EE (er maybe I can with the demo now?), but I suspect the UB would come from shifting by a signed type. I don't recall the promotion rules off the top of my head, but I _think_ when you multiply `uint_8` with `int` the result is `int`. You should add unsigned suffixes to the `3` literals to rule that out.

**Comment by MarcelHB** [comment]
This also came to my mind and I tried this, but no. 

But what also fixed this as I've been trying around the last minutes: using `7ULL`

**Comment by bradallred** [comment]
> But what also fixed this as I've been trying around the last minutes: using 7ULL

Right, the warning about data loss was because `0x7` would produce an `int` (32 bits on your platform), but you need 64 bits. `7ULL` forces it to be a `unsigned long long`, which just happens to be 64 bits on your platform so it works.

The size of `int`, `long`, and `long long` are all platform dependent. Thats why we have been using explicit sized types since switching to c++11. I think it is preferable we avoid using suffixes in cases where the number of bits matter to us. Using `uint64_t(7)` would be my preferred insurance of the correct type and is much more portable than a suffix.

**Comment by MarcelHB** [comment]
Yeah, note to self: _Stop using integer suffixes_.
