### ISSUE TITLE
BG2: Quicksave saved even when not possible.

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1779]
#### Bug description
When separating the party and creating a quick save the game will tell you is not possible and next that is saved correctly

```
[KeyMap]: Looking up key: 113(q) 
[KeyMap]: RunFunction(GUISAVE::QuickSavePressed)
[ResourceManager]: Searching for 'ERROR18'...
[ResourceManager/WARNING]: Couldn't find 'ERROR18'... Tried ERROR18.wav ERROR18.acm ERROR18.wav ERROR18.ogg 
[Core/WARNING]: 39 ms (compressing SAV file)
```

#### Steps to reproduce
1. Go to a big map
2. Click on move one member of the party far away
3. Quick save

#### Expected behavior
Not been able to save

#### Screenshots
![image](https://user-images.githubusercontent.com/1820598/214458554-7664eba8-d1a7-4f2e-9854-feca94db16dc.png)

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
I can't reproduce this, please provide some reliable steps. I can easily quicksave with the party at opposite diagonals of ToB start, the Underdark, the Planar Sphere ...

**Comment by rsantellan** [comment]
@lynxlynxlynx if you load this save game.
[000000154-Freeze.zip](https://github.com/gemrb/gemrb/files/10564066/000000154-Freeze.zip)

And press the quick save inside the sphere the error occurs. (Is not only on that save game, but every time I'm on the sphere)

That is the way that happens always for me.
