### ISSUE TITLE
BG2: Sometimes is really hard to set the party to enter a door. 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1785]
#### Bug description

On a party of six sometimes is really hard to make the enter a door. 

On my logs I have.

```
[WalkTo/DEBUG]: Aerie re-pathing ignoring actors
[WalkTo/DEBUG]: Sir Anomen re-pathing ignoring actors
[PathFinderWIP/DEBUG]: Abandoning because I'm close to the goal
[WalkTo/DEBUG]: Yoshimo: Path was just abandoned
[PathFinderWIP/DEBUG]: Abandoning because I'm close to the goal
[WalkTo/DEBUG]: Sir Anomen re-pathing ignoring actors
[WalkTo/DEBUG]: Aerie: Path was just abandoned
[WalkTo/DEBUG]: Sir Anomen re-pathing ignoring actors
[WalkTo/DEBUG]: Yoshimo re-pathing ignoring actors
[WalkTo/DEBUG]: Aerie re-pathing ignoring actors
[PathFinderWIP/DEBUG]: Abandoning because I'm close to the goal
[WalkTo/DEBUG]: Aerie: Path was just abandoned
```

#### Steps to reproduce
1. Go to slums
2. Click on the door to the sphere.
3. See error

#### Expected behavior
It shouldn't be so hard to enter the doors

#### Screenshots
[If applicable, add screenshots to help explain your problem.](https://user-images.githubusercontent.com/1820598/224592729-7154468d-2368-40ea-81f6-1f3ca7a74077.mp4)

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
It's not really a pathfinding issue, even though this is a tricky location. We seem to insist on trying to preserve the formation instead of making everyone approach.

**Comment by MarcelHB** [comment]
Maybe we should just refrain from enforcing a formation when clicking on stairs, portals and entrances.

**Comment by lynxlynxlynx** [comment]
Yep, I said as much in the previous comment. So we have Door, Infopoint (ST_TRAVEL) and map edges (which I could swear is tracked elsewhere, but I don't see it) to handle.
