### ISSUE TITLE
FadeToColor and FadeFromColor actions are not fully understood

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#179]
The fading itself is ok, changing the color and so on. But it seems these actions are sort-of blocking. They currently don't have that turned on (AF_BLOCKING), but even with, the behaviour seems incorrect and breaks bg2 (can't get to chapter2). But the status quo can fatally break some cutscenes too (_Viconia's dream is a candidate — real problem could turn out to be elsewhere_), but we never found a simple reproducer.

Old notes from the wiki:

>   * viconia's post-sleep cutscene never completes (cut34a.bcs), but just ending it manually is good enough (EndCutSceneMode() in our console)
>     * at minimum the usual problem of [FadeToColor not blocking](https://sourceforge.net/p/gemrb/bugs/97/) (though a quick test says that's not enough)
>     * ~~see also [a different angle](http://gibberlings3.net/forums/topic/28629-a)~~

So, the first thing to do is to get a good test case, before we start testing different solutions. The script block in the forum link is a good starting point, it just needs some trimming.

**Comment by caillean7** [comment]
Just for the record: since you just referenced this I tried my last case of getting stuck in cutscene mode, but removing the FadeToColor lines from the script did not solve this.

**Comment by bradallred** [comment]
reading IESDP makes it seem like these _are_ understood. I think our implementation doesn't quite follow the intent there.

>  the x coordinate specifying the number of AI updates (which default to 15 per second) to take to complete the fade action

to me that sounds like AI should block for `x` update cycles. currently we just use that as a duration for the fade. I don't see anything being done to apply a block to AI.

**Comment by lynxlynxlynx** [comment]
I wouldn't read that much into the quote, as IESDP doesn't use the "tick" wording for AI updates.

Marking the action as blocking would block that Scriptable's script, until the action is done or cancelled. Freezing everything (like the hard pause) hasn't been tried, but from the old bug, the most trustworthy research comes from fuzzie and she says no. It's not that hard to test; eg. give one actor a script that counts with displayoverheadmessage and another to do the fade. Is the counting affected and how ...

The Sender in this case is whoever is running the cutscene, unless it's overridden with ActionOverride. Nothing to worry about.

**Comment by lynxlynxlynx** [comment]
Bubb confirmed these are instants, so perhaps we've just been blaming too much on them. The Viconia dream cutscene needs a retest, so we can see if the problem was really caused by the fading actions.

**Comment by lynxlynxlynx** [comment]
Yeah, has nothing to do with it, even though the cutscene is practically empty.
