### ISSUE TITLE
Smoke and blending/transparency

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1792]
#### Bug description
- In Beregost, characters are drawn walking on top of smoke.
- Smoke looks different, although that might be a more general issue with blending/transparency, see screenshots.

#### Steps to reproduce
1. Go to Beregost, walk over smoke.
2. Cast protection from evil, mage version.

#### Expected behavior
Smoke and spells animations more similar to original.

#### Screenshots
Standing on top of smoke in Beregost:
![Captura desde 2023-04-11 11-04-55](https://user-images.githubusercontent.com/1279852/231054956-0e7ae134-690b-48b9-ade4-846bb4f98d19.png)

And compare to original smoke look:
![Captura desde 2023-04-11 11-18-37](https://user-images.githubusercontent.com/1279852/231055097-11c31be0-4ad5-41ca-b2f8-a4f2413043e9.png)

Casting Protection from Evil, GemRB - both animations fired together, non-transparent.
![Captura desde 2023-04-11 11-23-13](https://user-images.githubusercontent.com/1279852/231055847-64233e8b-4fab-4f5a-9087-d495040c53ce.png)

Original: this
![Captura desde 2023-04-11 11-23-41](https://user-images.githubusercontent.com/1279852/231056008-4c669a80-5cb7-427b-9d2d-3baee0536f4b.png)
followed by this
![Captura desde 2023-04-11 11-24-01](https://user-images.githubusercontent.com/1279852/231056085-d1195731-e8cc-4c8b-8ae3-48a0d4859a67.png)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by burner1024** [comment]
Oh, opengl.
But the character is still drawn on top of smoke.
![Captura desde 2023-04-11 14-15-39](https://user-images.githubusercontent.com/1279852/231085192-736cfd31-8832-41a6-b2f6-63644a62390e.png)
vs 
![Captura desde 2023-04-11 14-18-04](https://user-images.githubusercontent.com/1279852/231085303-d9b93025-8da9-4661-8eaf-4b9f20044387.png)

Protection from evil exists in bg1 too. Maybe it's related to fps setting, not sure what's the proper way to compare.

**Comment by lynxlynxlynx** [comment]
The one in bg1 doesn't have so complicated graphics, that's all.

This is ar3300, area animations 13 and 14. It doesn't have the background bit set, the baseline is lower, so yeah, something is wrong.

**Comment by bradallred** [comment]
https://github.com/gemrb/gemrb/blob/dcbdecabc1cb655a90a73016b01a0601291d5350/gemrb/core/Map.cpp#L342-L343

not sure why we stopped taking the pos into account.

**Comment by bradallred** [comment]
BTW, the blending modes should all work for other SDL2 backends other than OpenGL. I think probably not the software renderer tho.

**Comment by lynxlynxlynx** [comment]
That line is commented out since 2011, 2934c80d. Best to check if the mentioned animations are still problematic and how to fix it better.

**Comment by bradallred** [comment]
Not quite. That same commit had `AreaAnimation::GetHeight` defined to return `Pos.y+height`, but now it only returns `height`.

**Comment by lynxlynxlynx** [comment]
Yeah but the same test cases apply, the path is clear.

**Comment by lynxlynxlynx** [comment]
You removed it in 1957b1a. But yeah, even the bg2 starting area is broken:
![image](https://github.com/gemrb/gemrb/assets/121515/2e2c5021-97f7-4226-9004-0748a71351c3)
I'll just reinstate the y adding in the sorting, so GetHeight remains just a height getter.
