### ISSUE TITLE
FPS setting, walking and other animation speed 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1793]
#### Bug description
With `CapFPS` setting added by #1789, walking speed and likely other animations speed is not affected, resulting in a strange experience. You can see the pendulum swinging faster, but walking is the same.

Original `Maximum Frame Rate` setting mentioned in #144 acts as overarching game speed. It affects _everything_, except media playback.

#### Steps to reproduce
1. Set CapFPS to 60 or more.
2. Load a game, see walking speed.

#### Expected behavior
Walking and other animations speed increased to match sped up game clock. 

- I'm not sure if there are other independent speeds/rate in GemRB, if there are, they should be made dependent too.
- Also not sure if the intention is to have separate setting for drawing FPS vs game speed. But either way, #144 is not about drawing FPS, it's about game speed.

#### Screenshots

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Capfps is just about drawing, why are you not setting Maximum Frame Rate?

**Comment by burner1024** [comment]
Seeting where, baldur.ini? It's set.

**Comment by lynxlynxlynx** [comment]
To 30?

**Comment by burner1024** [comment]
To 90.

**Comment by MarcelHB** [comment]
I've been testing this with the default of 30, which means 15 AI updates per second. So maybe reset this first and check if things are good again, and then let's figure out how setting this value higher should impact the game.

**Comment by burner1024** [comment]
Sorry, what things?

**Comment by MarcelHB** [comment]
You set `Maximum Frame Rate` to 30 and report what anomalies remain then, since this is as far as I know the default or baseline that the games run by default, and what I've preserved to make no difference to GemRB  after #1789.

**Comment by burner1024** [comment]
I don't see any difference with 30, 90 or any other value. I don't see any difference at all except the pendulum swinging faster (which it probably shouldn't do at 30 MFR, I'd expect it to reflect game speed, not FPS).
Looking at the commit, since it does something with `Time.ai_update_time`, I guess something must be faster (scripts?), but that's not immediately noticeable.
Point is, #144 asked for game speed control, now it's closed and there's no control, as far as I understand.

**Comment by lynxlynxlynx** [comment]
I feel like you two are running in circles. We just need a list of things that should be affected by higher "ai" speed, besides walking speed.

**Comment by burner1024** [comment]
Uhm, I wouldn't know which things are on separate clock in GemRB. In original, it's one main loop for everything, except media is always played at the same speed.

**Comment by MarcelHB** [comment]
What should stick to real time:

* Media playback
* Delay setting of tooltips (appears to be tied to the FPS r/n)
* Weather drawing

FPS:
* Everything w. r. t. drawing the UI elements

Game speed:
* Movement, animations
* Projectiles, effects
* Scripts, AI
* Seconds per Round
* Boredom

Misc:
* Map navigation via mouse, keyboard

**Comment by lynxlynxlynx** [comment]
Managed to slip in a little test before leaving: adjusting stepTime didn't appear to make any difference.

**Comment by burner1024** [comment]
I'm not so sure about weather, but it's not critical, most important is that gameplay is proper.
One other minor issue, which manifests in the original games too is overlapping compliments/insults on higher speeds. But I've designed a [component](https://github.com/BGforgeNet/bg2-tweaks-and-tricks/blob/master/docs/soundsets.md#compliments-and-insults) to fix that, so also not very important.

**Comment by bradallred** [comment]
for tooltips you need to address this:
https://github.com/gemrb/gemrb/blob/9b4413b5b32f752210d9ff98cf16d54bf2c20091/gemrb/core/Interface.cpp#L1779-L1781

We should probably just nix that altogether and just use a `PointAnimation` to drive it.

**Comment by lynxlynxlynx** [comment]
Weather was indeed sped up, but that would be silly to replicate. PST's setting doesn't seem to do anything visible btw, so not good for testing.

I think we'll need something more like this for proper scaling, so the duration of a second (round, turn ... effects) is affected:
```diff
diff --git a/gemrb/core/Interface.cpp b/gemrb/core/Interface.cpp
index 6d37473bd..0369e7bb7 100644
--- a/gemrb/core/Interface.cpp
+++ b/gemrb/core/Interface.cpp
@@ -1821,7 +1821,7 @@ bool Interface::LoadGemRBINI()
    // We use this for the game's state exclusively
    ieDword maxRefreshRate = 30;
    vars->Lookup("Maximum Frame Rate", maxRefreshRate);
-   Time.ai_update_time = maxRefreshRate / 2;
+   Time.ai_update_time = 15 / (maxRefreshRate / 30);
 
    for (const GFFlags flag : EnumIterator<GFFlags>()) {
        const bool set = ini->GetKeyAsBool("resources", game_flags[flag], false);
```
With that and scaling `stepTime` also the movement speed is affected. I have the first change at home, so can't commit it all — posting more for discussion. It also doesn't appear to actually change effect duration, which I'll look into later.

**Comment by burner1024** [comment]
Still don't see any change in walking speed...

**Comment by lynxlynxlynx** [comment]
Works for me, no uncomitted changes. 🤷🏾

**Comment by burner1024** [comment]
Do I need any special build options or something?

**Comment by lynxlynxlynx** [comment]
No. I was testing with a thief in tob btw and there's a clear difference in walking speed at 30 or 60.

**Comment by burner1024** [comment]
Not sure what else to check.
@cygarniczka you want to try?

**Comment by lynxlynxlynx** [comment]
My guess is you're not setting the higher fps. In the sense that you have a gemrb ini and are editing the original instead.

**Comment by burner1024** [comment]
gemrb ini? Different from gemrb.cfg and baldur.ini?

**Comment by lynxlynxlynx** [comment]
gem-baldur.ini

**Comment by burner1024** [comment]
Right, just found it. Why is there a different file? Apparently is autogenerated or something? I never touched it.
It has `Maximum Frame Rate = 90` line.

**Comment by lynxlynxlynx** [comment]
Then that's fine and you'll have to be more verbose about how you're testing.

**Comment by burner1024** [comment]
OK, I stand corrected, characters do walk faster. But definitely not as fast as in original.

**Comment by MarcelHB** [comment]
Make the party go some straight distance and measure the time in both engines, maybe we get another factor 🙂

**Comment by burner1024** [comment]
Beregost top to bottom, testing original and gemrb with 60 MFR, both 18 seconds, increasing to 90 - gemrb stays at 18, original finishes in 12.
My display is 60Hz, not sure if related.

**Comment by lynxlynxlynx** [comment]
How strong is your machine? This laptop of mine for example can't do 90, the actual rate will be lower.

**Comment by burner1024** [comment]
I set `CapFPS=-1` and was able to get 12 seconds from GemRB too. (FPS as displayed by gemrb fluctuating in 100-200 interval).
Shouldn't game speed and fps be decoupled now?

**Comment by MarcelHB** [comment]
Nah, FPS is more like the upper bound for now.

**Comment by burner1024** [comment]
I see, so in a roundabout way we arrive at approximately the same point where the original was.
Maybe add the info to the docs/comments then?
