### ISSUE TITLE
Crash in  SDLVideoDriver::BlitSpriteClipped

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1796]
Going to the cave entrance in our demo crashes immediately. Probably since it's a BAMv2 and doesn't have a palette. This patch avoids the crash:

```diff
diff --git a/gemrb/plugins/SDLVideo/SDLVideo.cpp b/gemrb/plugins/SDLVideo/SDLVideo.cpp
index 9dce44ff5..ba1b0b71b 100644
--- a/gemrb/plugins/SDLVideo/SDLVideo.cpp
+++ b/gemrb/plugins/SDLVideo/SDLVideo.cpp
@@ -349,7 +349,7 @@ void SDLVideoDriver::BlitSpriteClipped(const Holder<Sprite2D>& spr, Region src,
        Color ck = ColorBlack;
        if (flags & (BlitFlags::ONE_MINUS_DST | BlitFlags::DST | BlitFlags::SRC)) {
                // FIXME: this is a hack. the video driver just needs to be able to ignore the color key during any blending
-               if (pal->col[0] != ColorBlack) {
+               if (pal && pal->col[0] != ColorBlack) {
                        ck = pal->col[0];
                        pal->CopyColorRange(&ColorBlack, &ColorBlack + 1, 0);
                }

```
But the rendering is then bad, there's a white background of sorts and other artifacts (looks pretty cool tbh): 
![image](https://user-images.githubusercontent.com/121515/235953469-9510f2a8-c970-44b5-9ac8-36397ff6f185.png)

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by MarcelHB** [comment]
This is a regression at some point after 7d6f9c43205448cc80e97ad616ec73b48ad70e16

**Comment by MarcelHB** [comment]
Well, the whole code block is fairly new ...

**Comment by lynxlynxlynx** [comment]
The crash is from e77fc8d; the visuals were fine before that as well.

**Comment by bradallred** [comment]
looking at the BAM in NI, it seems like we just ought to remove the `A_ANI_BLEND`. Also, maybe we should rename `A_ANI_BLEND` as all area animations are blended. That just changes the blend mode to `ONE_MINUS_DST`.

**Comment by bradallred** [comment]
I'm wondering if we also need to reexamine `AREImporter::AdjustPSTFlags`. `A_ANI_BLEND` may no longer be relevant to it, and possibly is now causing rendering issues.
