### ISSUE TITLE
Tooltip delay setting doesn't work

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1797]
#### Bug description

Tooltip delay setting doesn't work (doesn't change the delay), console throws errors:
```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/opt/gemrb/share/gemrb/GUIScripts/GUIOPT.py", line 304, in DisplayHelpTooltipDelay
[Python/ERROR]:     GemRB.SetTooltipDelay (GemRB.GetVar ("Tooltips") * TOOLTIP_DELAY_FACTOR/10)
[Python/ERROR]: TypeError: 'float' object cannot be interpreted as an integer
[Python/ERROR]: Traceback (most recent call last):
```

#### Steps to reproduce
1. Go to tooltip delay setting
2. Change it.

#### Expected behavior
Working setting.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by burner1024** [comment]
There's another bug with this: maximum on that setting is supposed to disable tooltips, which it doesn't. Not sure where to fix this.
![Captura desde 2023-05-25 11-21-42](https://github.com/gemrb/gemrb/assets/1279852/100dbd47-d269-4cfc-8f6e-87ed38720218)

**Comment by lynxlynxlynx** [comment]
Oh, there's more. The easiest way would be to just detect the highest value and then set the delay to something enormous.

**Comment by burner1024** [comment]
I don't fully understand how settings work.
If this can be done in the same `DisplayHelpTooltipDelay` function, I can send a PR.

**Comment by lynxlynxlynx** [comment]
Yes, exactly there, it's the same call you already modified.
