### ISSUE TITLE
Selection sounds played during loading game 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1798]
#### Bug description
During loading a savegame, selection sounds for every character in the party are played simultaneously.

#### Steps to reproduce
1. Load a save with NPCs in party.

#### Expected behavior
No selection nor other game world sounds until the save has finished loading.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by burner1024** [comment]
The same still hold for the familiar.

**Comment by lynxlynxlynx** [comment]
Familiars are not part of the party, so I don't know by what mechanism that would happen. Is `Actor::PlaySelectionSound` really being called? If not, can you backtrack from `Actor::VerbalConstant` or `Play` to see what triggers it?
