### ISSUE TITLE
Autopause doesn't show source 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1799]
#### Bug description
Original BG2 shows who triggered autopause, Gemrb doesn't.

#### Steps to reproduce
1. Enable autopause on spell cast.
2. Trigger it.

#### Expected behavior
Autopause should say who or what triggered it.

#### Screenshots
BG2
![Captura desde 2023-05-24 19-31-35](https://github.com/gemrb/gemrb/assets/1279852/9438ab15-b03c-4070-9e2d-62f78eaf7fa0)
GemRB
![Captura desde 2023-05-24 19-35-08](https://github.com/gemrb/gemrb/assets/1279852/8be54312-1ab8-45ba-8c23-2dd2b4bff0f2)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
For "enemy sighted" it prints it with the enemy, which is fine, while the rest use the right actor.
