### ISSUE TITLE
Stoneskin blocks spells

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1801]
#### Bug description
BG2

Stoneskin blocks (and gets spent by) Magic Missile, Wand of Magic Missiles, Chromatic Orb (just the damage component, I think, it still shows a save roll). Not Flame Arrow nor Acid Arrow, though. Don't know about other spells.

#### Steps to reproduce
1. Start a new game with a mage.
2. Cast Stoneskin, and get Imoen to cast some of those spells on PC.
3. See damage being blocked.
 
#### Expected behavior
Stoneskin not blocking spells.

#### Screenshots
\
GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by burner1024** [comment]
Huh, why?
Yes, I'm sure.

https://baldursgate.fandom.com/wiki/Stoneskin
> Stoneskin only protects from the physical damage of an attack. If a wizard protected by Stoneskin is hit with a weapon that inflicts some sort of elemental or magical damage – like e.g. fire – on top or exclusively, this damage component will still hurt the wizard.
Stoneskin can protect against each instance of applied crushing, slashing, piercing, missile or stunning (non lethal subdual) damage. For instance, a creature protected by 10 stoneskins will be able to withstand ten different and individually applied physical damage hits and suffer no physical damage. Each time the Stoneskin absorbs a physical attack, one skin is consumed.
A spell effect or innate power that applies physical damage can also be blocked with Stoneskin, such as Bigby's Crushing Hand, an Alchemical trap, or the Wand of Whips. Other status effects applied by the spell won't be blocked by the Stoneskin, such as Hold/Paralyze or Stun.

Is there anything else... whitelisted like that?

**Comment by lynxlynxlynx** [comment]
Random descriptions shouldn't be trusted, but I did go and check in the original.

**Comment by burner1024** [comment]
I mean, Stoneskin is *the* spell...
Iron Skins works the same, by the way (although it's secondary type is Spell Protections).

Are there any other special exceptions like that?

**Comment by lynxlynxlynx** [comment]
What exceptions?

**Comment by lynxlynxlynx** [comment]
Not really, just some special logic for pst.
