### ISSUE TITLE
 Attacking provokes neutrals too early

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1805]
#### Bug description
In BG2, to provoke a neutral you have to actually ~~land a hit (or spell)~~ perform an attack.
In GemRB, the very attempt provokes.
Especially noticeable when attacking with a bow.

#### Steps to reproduce
1. Enable pause on enemy sighted.
2. Go to a tavern.
3. Start shooting people.

#### Expected behavior
Neutrals turns hostile after being actually hit.

#### Screenshots
(Sorry for the language, but I hope it's clear what's happening)

Gemrb: turned enemy even before an attack roll is made (harder to reproduce, but happens).

![Captura desde 2023-05-25 16-55-16](https://github.com/gemrb/gemrb/assets/1279852/091d5691-2cee-43df-8922-3412a73c0281)

Gemrb: turned enemy after the attack roll is made, but before the arrow is shot. Then I cancel the attack and un-pause. So, never actually shot the target, still enemy.

![Captura desde 2023-05-25 16-58-36](https://github.com/gemrb/gemrb/assets/1279852/c51b7459-3c96-4dae-bb3c-c16fb778312f)

Original behaviour, correct sequence: nothing happens until the target it actually hit.

![Captura desde 2023-05-25 17-01-34](https://github.com/gemrb/gemrb/assets/1279852/ab19bd06-1579-4501-bcb5-c7771fea41a2)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Please look up the script the target uses, that's what's driving everything. Sounds like we match a trigger too often.

**Comment by burner1024** [comment]
```
[Actor/DEBUG]: Debugdump of Actor Plebeyo (Plebeyo, Plebeyo):
Scripts: SHOUT <none> <none> <none> FTOWBEZ <none> <none> <none>
```

<details>
  <summary>SHOUT</summary>
    
```
IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Shout(99)
		Enemy()
END

IF
	HitBy([GOODCUTOFF],CRUSHING)
THEN
	RESPONSE #100
		Shout(99)
		Continue()
END

IF
	Heard([ANYONE],99)
	Allegiance(Myself,NEUTRAL)
	!Class(Myself,INNOCENT)
THEN
	RESPONSE #100
		Shout(57)
		Enemy()
		MoveToObject(LastHeardBy(Myself))
END

IF
	Heard([ANYONE],99)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Heard([ANYONE],57)
	Allegiance(Myself,NEUTRAL)
THEN
	RESPONSE #100
		Enemy()
END

IF
	Heard([ANYONE],99)
	!Class(Myself,INNOCENT)
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
		Continue()
END

IF
	Heard([ANYONE],57)
	!Class(Myself,INNOCENT)
	!See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
		Continue()
END
```
  
</details>


<details>
  <summary>FTOWBEZ</summary>
  
  ```
IF
	Global("Chapter","GLOBAL",3)
	OnCreation()
THEN
	RESPONSE #100
		SetDialog("ftowbez")
END
  ```
  
</details>


This is in Jovial Juggler, BGT.

**Comment by lynxlynxlynx** [comment]
I don't think there's anything to do here then. Apparent timing is just #92 again.

**Comment by burner1024** [comment]
But arrows and attack rolls are not apparent timing, it's actual timing, no?

**Comment by lynxlynxlynx** [comment]
They're both actually, since you also have fake attacks.

**Comment by burner1024** [comment]
But my understanding is that arrows and other ammo are never fake.
Well, I guess you know better. If fixing #92 will fix this, great.
