### ISSUE TITLE
Foot circles for feared enemies should be yellow 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1806]
#### Bug description
Foot circles for feared enemies are red.

#### Steps to reproduce
1. Fear some enemies.

#### Expected behavior
Foot circles for feared enemies should be yellow.

#### Screenshots
BG2
![Captura desde 2023-05-25 17-10-41](https://github.com/gemrb/gemrb/assets/1279852/da8d9f9a-9a6a-439c-8987-3b3ce1459b76)

GemRB
![Captura desde 2023-05-25 17-12-11](https://github.com/gemrb/gemrb/assets/1279852/1133d9f3-41a4-49a5-8857-30bf572f8d18)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
We already set it to yellow in Actor::SetCircleSize, so something else must go wrong.
