### ISSUE TITLE
Using wands, no rotation to the target 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1808]
#### Bug description

Using wands doesn't rotate the user to the target.

#### Steps to reproduce
1. Turn PC back to the target.
2. Use a wand on it.
3. See that PC doesn't turn to the target.

#### Expected behavior
Using wands should turn the user to the target (or target point), same as casting spells.

#### Screenshots
Using the wand on the party.

Gemrb
![Captura desde 2023-05-26 19-29-35](https://github.com/gemrb/gemrb/assets/1279852/0d882498-588b-4fa8-b0b9-7a776b766a5f)

Original
![Captura desde 2023-05-26 19-30-11](https://github.com/gemrb/gemrb/assets/1279852/cf94293a-5a44-4621-80bf-d6237ed3bfa8)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
This is also probably a simple fix (Actor::UseItem* or earlier in GameControl or even GUIScript callers). 
Does it happen immediately on targeting or when the wand is actually used?

**Comment by burner1024** [comment]
Turning should happen immediately on targeting (and I think it follows if target moves).
