### ISSUE TITLE
Wand of Frost issues 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1809]
#### Bug description
1. Animation starts from behind wand user (#1808 maybe related - edit: yes, it is)
2. Animation is different (which is not necessarily worse).

#### Steps to reproduce
1. Use a Wand of Frost.
1. See the animation.

#### Expected behavior
Animation should start in front of the user.

Animation being different is not bad per se. I actually might like Gemrb version better. But I'd not sure why is it different, is it a bug?

#### Screenshots
Animation start, GemRB (yes, the wand is pointed to the _left_).

![Captura desde 2023-05-26 19-29-35](https://github.com/gemrb/gemrb/assets/1279852/315d56f7-1da9-45ec-82f1-e445926a4354)

Original BG2
![Captura desde 2023-05-26 19-30-11](https://github.com/gemrb/gemrb/assets/1279852/e68c8530-65e9-48e9-972c-bac884f40878)

Progressed animation, GemRB
![Captura desde 2023-05-26 21-30-13](https://github.com/gemrb/gemrb/assets/1279852/7946bb0f-8178-472f-a2bb-04553253ed72)

![Captura desde 2023-05-26 19-36-10](https://github.com/gemrb/gemrb/assets/1279852/166af4bc-ee1f-4890-9070-bbf223044696)

Original
![Captura desde 2023-05-26 19-36-43](https://github.com/gemrb/gemrb/assets/1279852/aaadc0a7-5499-4431-861b-b9456f10346c)
![Captura desde 2023-05-26 21-28-51](https://github.com/gemrb/gemrb/assets/1279852/e4bb5942-d1c4-4d1d-8659-84ca6662cfe4)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
I guess we use the bg1 animation in bg2 and coupled with the positional problem, I guess this is an unhardcoded projectile that we need to fix.

**Comment by burner1024** [comment]
Original BG1 wand used ice column projectile.
And I checked original Cone of Cold, it's just ice Burning Hands:
![Captura desde 2023-05-27 03-04-30](https://github.com/gemrb/gemrb/assets/1279852/5d7d6c4c-7e02-427d-93e2-010463587b0a)

Cone of Cold in GemRB
![Captura desde 2023-05-27 03-15-10](https://github.com/gemrb/gemrb/assets/1279852/6ecdc189-89ca-4224-85e2-dac7c87d8a33)

**Comment by lynxlynxlynx** [comment]
Could be a leftover resource (maybe even from iwd), but anyway, we just need to find the resref of the bam that the original used.

**Comment by burner1024** [comment]
Original BG1 spell? `BURNHAND` maybe?

**Comment by lynxlynxlynx** [comment]
`gemrb/unhardcoded/bg2/areapro.2da:15:CONECOLD   SPCCOLDE   SPCCOLDL   *          EFF_M19        *       0`
It's clear from the screenshots we use the right bam already, it's just not rendered the same. Might needs more bits enabled or more code ... this was all hardcoded in the original.

**Comment by burner1024** [comment]
So no further research needed?

**Comment by lynxlynxlynx** [comment]
Not of the easy kind, no.

**Comment by lynxlynxlynx** [comment]
Made it look pretty close to the original, which was clearly a hardcoded mess (plus still had orientation issues). Good enough for now.
