### ISSUE TITLE
Invisibility pulsating too strong 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1810]
#### Bug description
Invisibility transparency goes 0-100%.

#### Steps to reproduce
1. Cast invisibilty on any party member.
2. See how they are pulsating.

#### Expected behavior
Should be something like 0-50%.

#### Screenshots
Original
![0](https://github.com/gemrb/gemrb/assets/1279852/f977d00f-15dd-46ec-8789-977623fa6dab)

Gemrb
![2](https://github.com/gemrb/gemrb/assets/1279852/863366c9-e028-468f-960c-c254b7e7fdd5)

(Avatars and colors are all different too, don't know why).

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
More like 50-90% from that gif. And slower.

**Comment by burner1024** [comment]
Definitely not 50%. Maybe gif doesn't represent it well.
Hard to catch, since pulsating doesn't stop with pause. Here's the lowest I could screen.
![Captura desde 2023-05-27 01-00-24](https://github.com/gemrb/gemrb/assets/1279852/05d3b475-3c7c-4915-91d3-2cf7f72aa2bb)
I think it touches 0.

And here's max I could cap:
![Captura desde 2023-05-27 01-05-28](https://github.com/gemrb/gemrb/assets/1279852/c58ef777-8610-44f7-9304-d1c96f75f73a)

**Comment by lynxlynxlynx** [comment]
If that's 0, then you're talking about opacity, not transparency/invisibility.

**Comment by burner1024** [comment]
Yes.

**Comment by lynxlynxlynx** [comment]
You can play with this by setting the 32 to a higher number at the end of fx_set_invisible_state. 128 might do it.

**Comment by burner1024** [comment]
I put 128, seems closer.
And I think you're right about speed, I changed the interval to 8 and I think it's better.
![0](https://github.com/gemrb/gemrb/assets/1279852/05309e51-cbff-4778-9b6d-d0b94fc3f98b)
![1](https://github.com/gemrb/gemrb/assets/1279852/2ad45d7a-7eca-4da3-a755-b062cfb01ac8)

**Comment by lynxlynxlynx** [comment]
Ok, please submit a PR once you're happy with the results. :)
