### ISSUE TITLE
Casting spells on self breaks invisibility 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1811]
#### Bug description
Casting defensive spells on self breaks invisibility.

#### Steps to reproduce
1. Go invisible in some way (potion, spell).
2. Cast, say, Protection from Evil on self.
3. See that invisibility is broken.

#### Expected behavior
BG2 behaviour:
1. Any spells with `Hostile` flag break invisibility.
2. Any spells cast on point break invisibilty (even if target self).
3. Non-hostile spells with no target or single target, cast on self - do not break invisibility.
4. Non-hostile single target spells cast on party - break invisibility.

BG2 description:
> This spell causes the creature touched to vanish from sight and be undetectable by normal vision or even infravision. 
...
**He can, however, cast defensive spells on himself and fellow party members**. And if he attacks, he immediately becomes visible, although the invisibility enables him to attack first.

One option would be to replicate original behaviour 1-1.
But if an improvement can be considered, I'd suggest to allow all blue spells (on self, party, area), and some white ones, those that do not affect enemies.
Or just go with hard `Hostile/non-Hostile` separation and leave fixing that flag in spells to mods.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
So it's seems it's just like sanctuary in that regard, interesting.

**Comment by burner1024** [comment]
Yes, in original they are pretty much the same. (And both don't match their own descriptions exactly).

**Comment by lynxlynxlynx** [comment]
For sanctuary there's already a bit in the header, IIRC since the ees. So if some modder *really* wanted more granularity, that would be the way to go, just another bit. Or a new bit for splspec.2da if all else fails.
