### ISSUE TITLE
 iwd1 autopause options issue

### ISSUE THREAD

**Issue by gregariousmonk** [gemrb/gemrb#1815]
Version 0.9.0 installed via Lunux Mint software manager.
Icewind Dale Complete (GOG) (how)

Autopause options are visible on the autopause options panel, but the options for "enemy spotted", "trap found", "", and "center" are not selectable (ie no highlight appears when clicking on those options (all others can be selected normally.

I traced the issue to GUIopts.py, there is a check for those options, but it only checks for iwd2.  I added "or IWD1" and the options are now selectable.  I have not yet tested if the selected options work correctly or not.  This code appears to be the same in 0.9.1.

GemRB version (check as many as you know apply)
- [ ] master as of this issue
- [ ] 0.9.1
- [ x] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ x] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Thanks, please submit a pull request, if you can.

**Comment by gregariousmonk** [comment]
I have attempted to do as you have requested, but honestly it's been a while since I worked on anything collaborative and my git skills are rudimentary.  If I find other bugs I can fix I'll figure out how this works properly.
