### ISSUE TITLE
Enemy spotted status lines and pausing in Kuldahar 

### ISSUE THREAD

**Issue by gregariousmonk** [gemrb/gemrb#1820]
#### Bug description
When entering Kuldahar from either the world map or from building maps in Kuldahar I keep get status messages and autopausing from spotting (invisible) neo orogs.  It also happens periodically when traversing the middle region of the map.

#### Steps to reproduce
Configure autopause for "enemy spotted"
Enter Kuldahar exterior map from either the world map or by exiting a building in Kuldahar and observe the message and autopause.

#### Expected behavior
No pausing from invisible neo orogs?

#### Screenshots
Screenshots attached
![Screenshot from 2023-06-26 21-36-38](https://github.com/gemrb/gemrb/assets/137374871/02786e39-429f-4977-88db-1dc4dffdaf7b)
![Screenshot from 2023-06-26 21-49-45](https://github.com/gemrb/gemrb/assets/137374871/e82e2fe3-77ca-44d2-9b24-aedaf5e53aa3)
![Screenshot from 2023-06-26 22-01-35](https://github.com/gemrb/gemrb/assets/137374871/bb4a9aa8-1daf-42d3-a34b-9435bf5ae0ea)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [x] SDL2 without `USE_OPENGL_BACKEND`

**Comment by gregariousmonk** [comment]
I restarted with a new game and new characters and got a similar occurence in Easthaven.

Upon exiting buildings in Easthaven I get the message:
Goblin - Auto-paused: Enemy sighted

No goblin can be seen from the tavern entrance area. I have not yet gone to the goblin encounter.

![Screenshot from 2023-06-27 17-58-16](https://github.com/gemrb/gemrb/assets/137374871/9f0e0183-3cf9-46da-829f-c7f29eb0118a)

**Comment by gregariousmonk** [comment]
I stopped getting these in the Prologue, but they are happening in Kuldahar (with less frequency).  I'll see how it goes in the Vale of Shadows.

**Comment by lynxlynxlynx** [comment]
If you can easily reproduce, look at my previous commit. Perhaps the first call to HandleAutopauseForVisible is being hit, not the second, and it needs extra checks (priority == PR_SCRIPT).

**Comment by gregariousmonk** [comment]
I checked through the actors in the map: 
- townsfolk are always visible and are not hostile --> no trigger enemy sighted
- bears are spawned in by the area ini file when needed --> no trigger enemy sighted
- neo orogs are present on the map but have their "default visibility" set to Hidden (1) --> triggers enemy sighted
The code checks to see if the point on the map is visible, but does it check to see if an actor is marked as hidden?

**Comment by lynxlynxlynx** [comment]
Did you try what I suggested?

**Comment by gregariousmonk** [comment]
I looked at your previous commit and then I went on a whirlwind tour of the code while looking up functions to see how they work.

I haven't touched C++ in in a while and when I did it was mostly code updates to system stuff, you'll have to give me a minute. ;)

**Comment by gregariousmonk** [comment]
Should  `bool scheduled = actor->Schedule(gametime, false);` 
be changed to  `bool scheduled = actor->Schedule(gametime, true);` 
to check if the actor is hidden?

**Comment by lynxlynxlynx** [comment]
No?

**Comment by gregariousmonk** [comment]
I was looking at checking to see if an actor's avatar has been removed. I have a lot of things to figure out before I can make meaningful contributions to the game core.

**Comment by gregariousmonk** [comment]
Can iactor->GetStat(IE_AVATARREMOVAL) be used to distinguish between actors that are visible and hidden/invisible?

if (IsVisible(actor->Pos) && (actor->GetStat(IE_AVATARREMOVAL))

**Comment by lynxlynxlynx** [comment]
I went to check what you/NI means by "default visibility" and yes, that's the IE_AVATARREMOVAL stat (invisibility is something else). This also means checking the priority wouldn't help, since scripts do run for them. But the check needs to be negated here.

**Comment by gregariousmonk** [comment]
When I was doing up some pseudocode for it I used a test for && !(avatar_removal) but when I typed it here I forgot the !, of course.

I'm sorting out my workflow and tools to manage the C++ code. I've built it a couple of times, but I still have some things to sort out wrt git (I hate all the git gui clients I've looked at so far.)

**Comment by gregariousmonk** [comment]
I've got a workflow set up to handle git and C++ development that doesn't bug me too much. 

Spent a half-day chasing my tail trying to get an appimage target to work, lol.

Tried a couple of things for the enemy detection issue but with little joy. I'll keep at it until I figure out how to fix this, or someone else fixes it while I faff about.
