### ISSUE TITLE
 IWD1 Bard Song not working correctly.

### ISSUE THREAD

**Issue by gregariousmonk** [gemrb/gemrb#1827]
#### Bug description
When playing bard song, the effects and icons appear on the bard, but not on any of the other party members.  The effects do not appear in the character record, nor do they appear to change the THAC0, etc.

These related messages appear in the console window when bard song is activated:

> [Actor/WARNING]: Unhandled SPL type 5, using average casting level!

#### Steps to reproduce
Create a bard character, start playing bard music and observe the effect.

#### Expected behavior
Bard song icons (plus any related effect icons) appear on the character portraits.

#### Screenshots
![Screenshot from 2023-06-29 12-06-18](https://github.com/gemrb/gemrb/assets/137374871/37f6d6c3-f4a2-4e05-83a7-8bbac4916560)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Works for me in various saves.

**Comment by gregariousmonk** [comment]
Thanks Jaka, I'm going to close this and reinstall everything.   

I'm getting odd lookup errors for some things that should be working.

**Comment by gregariousmonk** [comment]
Bard song works correctly after redoing my install.

**Comment by lynxlynxlynx** [comment]
Odd, but good to hear. :)

**Comment by gregariousmonk** [comment]
Ooh, puns! :D
