### ISSUE TITLE
IWD1 scripting error in prologue goblin quest

### ISSUE THREAD

**Issue by gregariousmonk** [gemrb/gemrb#1828]
#### Bug description
During the Goblin quest in Easthaven a script error occurs:

> [Actor/ERROR]: Scriptname goblinbowelite(quest) (name: Goblin Elite) is too long for generating death globals!

#### Steps to reproduce
Kill the goblin chief, check the console/log.

#### Expected behavior
Not sure what impact this has on the game, it doesn't cause any issues that are apparent.

#### Screenshots
n/a

GemRB version (check as many as you know apply)
- [ ] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
This is an inconsequential data bug in the original.

**Comment by bradallred** [comment]
Is it? seems like that variable would only be 25 characters (goblinbowelite(quest)_DEAD), and we should be able to fit up to 32.

**Comment by lynxlynxlynx** [comment]
But not SPRITE_IS_DEAD ...
