### ISSUE TITLE
Check map types after switching to C++14

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1829]
now that we are using `std::unordered_map` over custom hash maps, there is one downside to that: searching the map requires constructing a new key type. Not usually a big deal, but not ideal for a game engine.

for `std::map` c++14 has [overloads](https://en.cppreference.com/w/cpp/container/map/find) that avoid this, but for whatever reason `std::unordered_map` did not gain them until c++20.

I wonder if many of our `std::unordered_map`s would be better as `std::map`, since we probably are mostly just building them all at once and then just doing find operations. This is probably extra true if the key is a string, since you can compare many strings in the time it takes to hash just one.

we already have an issue (#1768) for moving to C++14

**Comment by MarcelHB** [comment]
Isn't using hashes exactly the advantage when the use case is building them once and reading them many times? In contrast to a tree-based structure (like `std::map`) that is much more stable (no need for re-bucketing, copying) when frequently inserting and removing keys?

**Comment by bradallred** [comment]
there are a lot of factors that map/hashmap performance depends on.

if your keys are numerical, then the hash is instant and so is the copy of the key. When your keys are strings, then the hash operation and the copy can really hurt when compared to a copy less comparison (string comparisons short circuit at the first difference). It is also non trivial to know that you have a good hash for your string set, and this is something done in various different ways because of how widely it can differ (this isn't something we are going to worry about tho).

Everything get further muddied depending on the size and stability of the data set or what operations you want to optimize for. Tiny datasets with string keys usually perform better with `std::map`, especially if you use a custom allocator that is cache friendly. I don't know how big any of these maps are, but I suspect at least a few are extremely small.

For our purposes, it's not something we need to stress about too much, but it's worth looking into what we are doing in case there are some hot paths. The solution would depend on what we find by taking actual measurements. We're not going to complicate things for non noticeable differences.

If nobody notices a difference between 0.9.1 and upcomming 0.9.2 where we changed the data structures, then thats a good sign there isn't much to worry about.

**Comment by bradallred** [comment]
At least for `ResRefMap`, I don't expect the key copy to hurt us, since `ResRef` is short enough to copy "for free". Likewise, you wont save much via short circuiting.

One thing that would probably benefit us with low effort is determining what a good hash algorithm is for `ResRef` and `ieVariable`.

**Comment by MarcelHB** [comment]
So we have:

* `Cache`: no idea but I guess reaching RC=0 happens once in a while, but much less than read accesses (spells, items, effects) since they live for a couple of frames
* `LRUCache`: currently a size of 100 and only in use for sound, so probably not a topic at all
* `Variables`: some of them are built once (config) or are very small (plugin flags), some game script variable maps appear to be of static-size (new variables forbidden), others allow insertion but nothing is ever removed so probably many more reads over insertions, if any after setup.

w. r. t. inserting/erasing, I claim that there is no hot path to consider for these maps.

My concern with bigger trees for random lookups is the elevated probability of hitting plenty of cache-unfriendly dereferencing during node iteration that will cost time than hashing itself, leaving the hash implementation aside.

**Comment by bradallred** [comment]
we also have a lot of previously existing uses of both `std::map` and `std::unordered_map`. One likely hot path there is `std::unordered_map<const void*, std::pair<VideoBufferPtr, Region>> objectStencils;`.

> My concern with bigger trees for random lookups is the elevated probability of hitting plenty of cache-unfriendly dereferencing during node iteration that will cost more time than hashing itself, leaving the hash map implementation aside, of course.

sure, we shouldn't make performance related changes without measuring. You can also use a custom allocator (I use a circular allocator for a similar use elsewhere) to maintain cache friendliness of nodes.

**Comment by bradallred** [comment]
related sonar report: https://sonarcloud.io/organizations/gemrb/rules?open=cpp%3AS6045&rule_key=cpp%3AS6045

this is the least we need to do here.
