### ISSUE TITLE
[bug] BG2/BGT Location without music/interior houses keep playing dream music.

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#183]
Location without any music like most of the interior house locations in BG1 play dream music. Probably something sneak in when #180 got the fix.

**Comment by MarcelHB** [comment]
I had another anomaly in PST yesterday when I moved from AR0500 to AR0405 the first time after loading, both map themes were playing concurrently.

**Comment by lynxlynxlynx** [comment]
Thanks, it was 60e911e903 then. I'll limit it to combat music.

**Comment by lynxlynxlynx** [comment]
Ok, should be gone. Could also take care of the PST issue, since ChangeSong gets called each tick, though it's not really related..

**Comment by MarcelHB** [comment]
Nevermind, it was not related and my memory got tricked by the fact that in the original game, the map music of AR0500 fades in two seconds later in AR0405, and immediately in GemRB.
