### ISSUE TITLE
[IWD1+HOW GOG] no actor audio 

### ISSUE THREAD

**Issue by gregariousmonk** [gemrb/gemrb#1834]
#### Bug description
The radio button issue for character sounds is resolved, the radio buttons retain their state, but the characters and creatures make no selection/bored/battlecry sounds.

I've also noticed that if I set the Selection/Command sounds radio buttons, they only retain their settings until I exit to the loadscreen.  Upon reloading the game, those character sound settings reset to 'Never'.

The other in-game audio seems to be mostly working as expected (I still get the theme music dropping out on return to loadscreen sometimes).

#### Steps to reproduce
1. Load a game
2. Go to Options-->Sound-->Character Sounds-->set the sounds to "Always"
3. Click on a character or leave them waiting idle or enter battle.
4. No character audio is heard
5. Exit to the Loadscreen and select Load Game
6. Check the Character Sounds settings, they have returned to the "Never' position,

#### Expected behavior
Enabling Selection and Command sounds should create character sounds dependent on the current actions.  The sound settings should be retained from session to session.

#### Screenshots

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Hmm, that's odd. I can reproduce, but when I was testing the fix for the radios, the values did get saved to the ini properly.

**Comment by gregariousmonk** [comment]
I forgot to mention that I don't get any creature battlecries either, combat has only hit and missile sounds and there is no battle music.

**Comment by gregariousmonk** [comment]
The soundsets for the game are present and work when played via the character customization or during chargen.  

They just aren't being played, or are not playing correctly, when characters are selected, given a command, nor battlecries and the banter-ish comments.

**Comment by lynxlynxlynx** [comment]
This will be the same regression as noticed with scripting from the cache refactor. No need to test further.

**Comment by lynxlynxlynx** [comment]
Yep, a different thing, but I found it already.
