### ISSUE TITLE
[ IWD1 HOW] Beetles moving backward in ar1015

### ISSUE THREAD

**Issue by gregariousmonk** [gemrb/gemrb#1835]
#### Bug description
Not a gamebreaking bug, but it is odd and may be related to other issues with facing.
Beetles in the cellar of the starting tavern cellar (ar1015) move backwards or their facing is set to opposite the direction of travel.

#### Steps to reproduce
1. Start a new game of HOW and create a character or two
2. Once the initial dialogue is done, start a conversation with the barmaid to get the beetle quest
3. Enter the cellar and observe the moonwalking beetles.

#### Expected behavior
In the original game the beetles move with their pincers ahead of them

#### Screenshots
[cinnamon-2023-06-30T231808-0230.webm](https://github.com/gemrb/gemrb/assets/137374871/b2b07dbd-b9ee-4d67-be23-4e530842bcd7)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Nice, this shows we don't know something about a family of actions for running away — when they should back up and when not.
