### ISSUE TITLE
[IWD1+HOW] Random Encounters missing

### ISSUE THREAD

**Issue by gregariousmonk** [gemrb/gemrb#1836]
#### Bug description
Not sure if this was a design choice, oversight, or bug, but random encounters do not spawn anywhere in the Prologue or Chapter 1 of IWD.

#### Steps to reproduce
1. Play until you can rest in a dangerous location, eg. the orc cave from the prologue caravan quest or the vale of shadows.
2. Rest repeatedly, there are no random encounters.

#### Expected behavior
Random encounters were part of the original play experience and add to the challenge of the game.

#### Screenshots
n/a

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
In the orc cave the data gives only a 15% chance, but you're right, I made a mistake in 2020.

**Comment by gregariousmonk** [comment]
I'm willing to pitch in and help where I can (scripting, with some pointers, lol) but this one is out of my depth just now.
