### ISSUE TITLE
 Cleanup of all trailing whitespaces in code

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1838]
My editor cleans up all trailing white spaces when saving. Unfortunately, there are still tons of them so I need to do a special treatment or `git add -p` a lot to filter out all the whitespace stuff.

We should clean this up once and for all.

**Comment by MarcelHB** [comment]
Otherwise, we can also try setting `trim_trailing_whitespace` to `false` in `.editorconfig`.

**Comment by lynxlynxlynx** [comment]
Yeah, let's preserve it. The big wipe will happen with the rest of the format changes.
