### ISSUE TITLE
[iwd1+how (gog)] Thief stealth value not shown in character record

### ISSUE THREAD

**Issue by gregariousmonk** [gemrb/gemrb#1842]
#### Bug description
The stealth/move silently score is not shown for thief characters, but it is shown for rangers.

I found the section in GUIREC.GetSkills:503 where it sets up the skills but I can't figure out why the stealth score gets skipped for the thief but not the ranger.

The stealth skill seems to work fine and the stealth button is shown correctly, etc., but the score is not shown for thieves.

#### Steps to reproduce
1. Go to Character Record
2. Scroll down the information box for a thief character and a ranger character.
3. The "Move Silently" score is present for rangers, but not for thieves.

#### Expected behavior
The Move Silently/Stealth score should be present for any class that has the skill.

#### Screenshots
[cinnamon-2023-07-01T190355-0230.webm](https://github.com/gemrb/gemrb/assets/137374871/0c4c9f7c-db65-4e11-b892-856f336135f5)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
It's because the code was written with bg2 in mind and it's the only one with split skills for stealthing. Ok, iwd2 also, but it doesn't use that code.
