### ISSUE TITLE
[iwd+how gog] Large shield not displaying on HF fighter paperdoll

### ISSUE THREAD

**Issue by gregariousmonk** [gemrb/gemrb#1848]
#### Bug description
The paperdoll for female human fighter has some kind of issue with the large shield.  Other race class combinations seem to display the shield in the paperdoll.  The shield appears correctly displayed in the game view. The medium and small shields are displayed in the pdoll.

There are frequent warnings and for missing plt/bam files, but I guess those are not critical.

#### Steps to reproduce
1. Open the inventory dialogue
2. Equip a large shield on a human female fighter|paladin|ranger
3. Observe the paperdoll and the missing shield

#### Expected behavior
The paperdoll should reflect the equiped shield

#### Screenshots
[cinnamon-2023-07-03T224434-0230.webm](https://github.com/gemrb/gemrb/assets/137374871/e2f05c8c-ddd2-4d4c-a5d3-d2cced92b7f0)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
> frequent warnings and for missing plt/bam
No, in this case this is very important.

Eg. when equipping on a paladin:
> [ResourceManager]: Searching for 'CHFF4INV'...
> [ResourceManager/WARNING]: Couldn't find 'CHFF4INV'... Tried CHFF4INV.plt  <-- then the bam is taken, as expected
> [ResourceManager]: Searching for 'WPNS1INV'...
> [ResourceManager/WARNING]: Couldn't find 'WPNS1INV'... Tried WPNS1INV.plt   <-- then the bam is taken, as expected
> [ResourceManager]: Searching for 'WPND4INV'...
> [ResourceManager/WARNING]: Couldn't find 'WPND4INV'... Tried WPND4INV.plt  (i only have wpnd1inv)
> [ResourceManager/ERROR]: Couldn't find 'WPND4INV.bam'.
> [GUISCript/WARNING]: BAM/PLT not found for ref: WPND4INV

Should be WPSD4INV. So I guess we misconstruct the filename. All three plain large shields have a correct item and animation type set (D4). I'd start looking if we miscategorize them in Inventory::UpdateShieldAnimation.

**Comment by gregariousmonk** [comment]
Sorry, I meant to attach the game log. :/

**Comment by gregariousmonk** [comment]
The correct animation for this is WPLD4INV, I'm looking through the code to find where the name is built.

**Comment by lynxlynxlynx** [comment]
Depends on the stance, but yeah. Actor::SetUsedShield is a good place to start looking from.

**Comment by gregariousmonk** [comment]
I have no idea what I'm doing, but I am learning a fair bit about the code, so I'll call it a win. ;)  Here's what chasing my own tail all day has shown me.

In GUIINV.RefreshInventoryWindow the size is read from pdolls.2da:
The row is determined by: row = "0x%04X" %anim_id

				#shield
				Button.SetPLT("WP" + size + item['AnimationType'] + "INV", Color1, Color2, Color3, Color4, Color5, Color6, Color7, 0, 2)

For female fighter animations in pdolls.2da for 'how' the size is 'N', as it is for many of the pdoll animations:
CHFCxINV (0x5010), CHFFxINV (0x5110), CHFWxINV (0x5210), CHFTxINV (0x5310), CEFCxINV (0x6010), COFCxINV (0x6015), CHFFxINV (0x6110), COFFxINV (0x6115), CHFWxINV (0x6210), COFWxINV (0x6215), CHFTxINV (0x6310), CHFMxINV (0x6510)

There are no 'N' size *INV animations for the shields except the buckler, WPND1INV.BAM

If the values are read from avatars.2da for the same hex row, there is no size 'N'.  

The pdolls.2da for bg1 has no size 'N' listed.

So, I think for shields to show up in IWD/HOW for some avatars either the size listing in the 2da must change or the method of reading the size has to change.  I'll keep at it until I figure it out, eventually.

**Comment by gregariousmonk** [comment]
I'm going to try something simple along the lines of "if (size == 'N') then size = 'M'" but I need to check the BAMs for other 'N' size items, it was a very short list of WPNxxxx.BAM files.

**Comment by lynxlynxlynx** [comment]
Sounds good.

**Comment by gregariousmonk** [comment]
Tentative success.  I'll do some more testing with the other avatars with size set to N in pdolls.2da before I submit a pull.

[cinnamon-2023-07-05T132450-0230.webm](https://github.com/gemrb/gemrb/assets/137374871/b642d4ec-363d-498c-81d6-1d1a8967e537)
