### ISSUE TITLE
Only reading the first key

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1852]
Must be a recent regression, but eg. when parsing our cfg, only the first occurrence of a key will be taken into account, while subsequent ones should override previous ones.

Eg. I expect 1024, not 640:
```
Width=640
Width=800
Width=1024
#Width=1200
#Width=1920
```

**Comment by MarcelHB** [comment]
https://github.com/gemrb/gemrb/blob/24d035100f97f4fed29ea6148a514c331108cffc/gemrb/core/InterfaceConfig.cpp#L33

must be `configVars[key] = value;` then, I guess
