### ISSUE TITLE
 [iwd+how] No battle music

### ISSUE THREAD

**Issue by gregariousmonk** [gemrb/gemrb#1854]
#### Bug description
Battle music is broken or disabled, no music plays during battle scenes.  

There are a number of other audio issues with iwd, but I'll do a separate report for each of them individually after I've trolled though more of the code. 

#### Steps to reproduce
1. Start a game of iwd+how
2. Get in a battle
3. Only weapon sounds and ambient sounds are heard, battle music is absent.

#### Expected behavior
Battle music from the music cue files should play during combat.

#### Screenshots
n/a I'm using gnome desktop video capture which has no sound recording :/

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
I noticed the same now when testing bg1. It happened before, ChangeSong or wherever we end up has some poorly understood logic.

**Comment by gregariousmonk** [comment]
I see periodic warnings about not finding 'cdplayer.bcs', I assume that those are for playing tracks from the CD(?)

**Comment by lynxlynxlynx** [comment]
Might be worth looking at [CGameArea::PlaySong](https://github.com/search?q=repo%3Aalexbatalov%2Fiwd2-re%20PlaySong&type=code) and where it's used. Especially once Alex has them fleshed out more.

**Comment by lynxlynxlynx** [comment]
For iwd2 looking at the code shows no fallbacks (SetSong is only called by a scripting action, which I verified with a disassembler). Looking at the data, no battle music is set in areas (typically 0 in master,  -1 in subareas). Even Targos is without and just continues playing the day/night theme.

Exceptions:
- ar5005: proper playlist
- ar5303, ar6201: battle6 / b6
- ar6305: battle5 / b5
Those 4 areas are the only ones with any battle music in iwd2.
