### ISSUE TITLE
 Multiclass with more than 3 classes

### ISSUE THREAD

**Issue by i30817** [gemrb/gemrb#1855]
#### Description
I would like the possibility of a f/t/c/m or similar. It always seemed like this was impossible in IE, not in the least because of the menus not having space/all class abilities in a single menu.

Another mode I'd find cool is a general TNO mode where your character is just a single class at the time but can change at will, with for instance a mod dialog, item mod dialog or similar.

The idea is simply to make these possible not necessarily implement them as default options.

**Comment by lynxlynxlynx** [comment]
The multiclass thing would be very annoying to implement and with dubious benefit. If you want to try how something like that would play, just install an xp reducer mod and give f/m/t a cleric spell table in our classes.2da. And I guess ignore weaponry the cleric can't use, unless you want to develop a mod on top that patches all weapons (affecting all f/m/ts).

TNO mode would be perhaps easier, but there are also challenges. The XP holding stats are in the same place as other stats used in non-pst, the level-up code would need hacks and an accompanying mod would have to be developed to enable switching in practice.

So overall I'd say this is out of scope and would just needlessly increase the maintenance burden.

**Comment by lynxlynxlynx** [comment]
Spells: yes
Turning: there's a problem with space in the action bar that we haven't solved yet #96, but after that or if you're willing to sacrifice some other slot, it's the same approach as with cleric spells, just enable the feature for the class

Class checks: this would have never worked with any checks just for clerics anyway (only things like CLERIC_ALL would catch them). 
Usability: true, but would you even use the symbols? You have so many classes competing for the few equipment slots and besides the symbols there's hardly any cleric-only items.

To make the last two work in game, you would need to write a mod as well anyway, so you can just lift class restrictions instead.

**Comment by lynxlynxlynx** [comment]
A kit is not a class. I already outlined how you can do it already too, without resorting to kits. Spell checks only check for memorization, they don't care about class or other details.
