### ISSUE TITLE
 [iwd+how] ar3001 (yeti cave) traps detected but no traps present

### ISSUE THREAD

**Issue by gregariousmonk** [gemrb/gemrb#1856]
#### Bug description
After disposing of the yetis in the cave the thief detects 4 traps in the area, but none are highlighted and the ARE doesn't show any.
 
#### Steps to reproduce
1. Go to ar3001 with a theif character
2. Get rid of the yetis
3. Detect traps
4. The feedback window indicates 4 traps found

#### Expected behavior
There are no traps I could find in the ARE file, so trap found shouldn't trigger

#### Screenshots
[cinnamon-2023-07-06T171430-0230.webm](https://github.com/gemrb/gemrb/assets/137374871/afa895ac-d67b-4114-8db0-627adcf0976c)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.1
- [ ] 0.9.0
- [ ] 0.8.8

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
It's the containers, simple bug, I'll fix it.
