### ISSUE TITLE
[bug] 1pp  gui modification component font crash

### ISSUE THREAD

**Issue by bholland** [gemrb/gemrb#186]
**Describe the bug**
Opening the inventory and the character screen crashes on both 0.8.5 release and master. it happens every time on a heavily modded game. 

GemRB version: 0.8.5 and master

**To Reproduce**
1. start up the game
2. open character or inventory
3. see the crash 100% of the time. 

**Expected behavior**
It should open the inventory. 

**Screenshots**
I will attach a gdb output and if I can find a fix, I will. I am also going to test this out to see if it happens with the 1pp GUI enhancements. I just removed that option. 
[weidu.log](https://github.com/gemrb/gemrb/files/3548783/weidu.log)

**Comment by lynxlynxlynx** [comment]
Thanks for the report. Does it actually crash or does it just freeze (python exception)? The end of the log output might be handy, but yeah, if it is a crash, a gdb trace is much better.

**Comment by bholland** [comment]
It segfaults and on RetroPie, that requires a hard reboot. Little did I
know that you can run gemrb in LXDE. With LXDE, it crashes to desktop. In
another thread about this, I believe the dev reported the issue was one
with fonts, either a corrupted font, or simply one that wasnt embedded
properly. The culprit appears to be the 1pp gui modification and that is a
crying shame. Removing the modification. Allowed me to open up the game.

Both GemRB and 1pp are under active development and i have been itching to
get back to c. This seems like a good opportunity. Given that this isnt an
intermittent crash, we know the mod, we know the mod component, this
shouldnt be hard to fix. It just turns out that 1pp is very popular and
will make these changes by default.

BTW, I am overjoyed by GemRB. It runs on 1 core on my pie 4 at 50%. I never
had bg2 play so well.

Thanks,
~Ben

**Comment by lynxlynxlynx** [comment]
1pp changes data files and whatever it does, we should handle it gracefully, even if we can't do what it wants. Crashes are never good. 

Glad to know you like it and are willing to drill down. :) Check out CONTRIBUTING.md for some pointers.

**Comment by bholland** [comment]
Will do. Expect a pull request shortly both for this and the pi comment.

Thanks,
~Ben

**Comment by lynxlynxlynx** [comment]
I've had that component installed for a long time and didn't get any crashes, especially not reproducable. Closing  as worksforme.
