### ISSUE TITLE
Minor GUI issues around IWD2 stores 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#1873]
#### Bug description

1. When entering a store, the bag isn't shown to the right. If you return from another service, then it appears.
2. There is a button missing or wrong when requesting identification.

#### Steps to reproduce
1. Start an IWD2 game
2. Enter a store with identification
3. Switch services

#### Expected behavior
Add a clear and concise description of what you expected to happen.

#### Screenshots

![2023-07-29_17-31](https://github.com/gemrb/gemrb/assets/238558/b0b6bf28-29ff-42b0-b147-48526adf5dbd)
![2023-07-29_17-31_1](https://github.com/gemrb/gemrb/assets/238558/1f4aab80-0e9f-499a-9811-3a25915fcb52)
![2023-07-29_17-32](https://github.com/gemrb/gemrb/assets/238558/2d76e8f4-5fd2-4a10-9609-2e0d3a444ebe)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by bradallred** [comment]
the bag thing is seen in BG2 as well.

It looks like we create the labels, so the first thing to verify would be that the hierarchy is what is expected:
`window.subviews` contains Button, and `Button.subviews` contains the labels. If the window is the superview to both, then that would be a cause of issues like this.

**Comment by bradallred** [comment]
ok, the hierarchy is correct, so then the problem is most likely that the window background is getting drawn without the button getting redrawn. The labels are the same size as the button so it wasn't obvious.

**Comment by lynxlynxlynx** [comment]
Did it fix the button as well?

**Comment by bradallred** [comment]
I didn't check it

**Comment by MarcelHB** [comment]
Identify button remains as seen above.
