### ISSUE TITLE
BG2: Quests are reinitialized. 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1879]
#### Bug description
I have a save game pretty advanced on the second chapter, going back to the wizard sphere on the slums after updating to master I'm receive by Gaelan Bayle like the first time, but the quest is already on my journal for a long time.

#### Steps to reproduce
1. Go to Slums after getting the introduction of Gaelan Bayle
2. Be receive by Gaelan Bayle
3. See error

#### Expected behavior
Only be greeted once by him.

#### Screenshots
Quest on journal
![image](https://github.com/gemrb/gemrb/assets/1820598/ed93f8ca-6016-45e6-9c1c-e35fa8d1b663)
Again him
![image](https://github.com/gemrb/gemrb/assets/1820598/0efa9675-8da3-4930-a49d-1fe44c90f793)

This is my save game.

[000000157-Traveling error.tar.gz](https://github.com/gemrb/gemrb/files/12286335/000000157-Traveling.error.tar.gz)

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
This is critical and likely caused by the dictionary refactor, since it's probably a problam with some variable or variable timer. If you can find a simpler reproducer in some other circumstance, that would be even better.

**Comment by MarcelHB** [comment]
The problem appears to be something else: `SaveGameAREExtractor` isn't extracting the saved `AR0400` here or any more so you end up with a fresh instance.

**Comment by MarcelHB** [comment]
Probably; from the corner of my eye, `areLocations` wasn't filled as it is supposed to be.

**Comment by MarcelHB** [comment]
The problem is a little different than expected: When I look at the save games generated from GemRB, all area files but the currently loaded one lack the file extension in the sav file.

**Comment by lynxlynxlynx** [comment]
All good now?

**Comment by MarcelHB** [comment]
No, something is even more broken by now. If I save something now, I see one only file with a broken name saved in the SAV file:

![iwd2_sav_file](https://github.com/gemrb/gemrb/assets/238558/a7459e1f-e6a1-4a26-a8f2-ab3855a976fe)

While the file size appears reasonable, I guess the index is misaligned.

**Comment by lynxlynxlynx** [comment]
One of the writing chunks removed a +1 to the name length field, might be that.
