### ISSUE TITLE
libfmt is sometimes included without disabling exceptions

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1894]
in `Strings/Format.h` we set some defines prior to including `fmt/format.h`:
```
#define FMT_HEADER_ONLY
#define FMT_EXCEPTIONS 0
#include <fmt/format.h>
```

However, there are now some other places we include libfmt headers, so those TUs are not being compiled the way we intend. Sonar has picked up on this and is reporting a bunch of exceptions from destructors as a result.

we should probably address this by adding these to the build so it doesn't matter how `fmt` headers are included.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
I did it, I'm just not sure the xcode part is ok / enough.

**Comment by lynxlynxlynx** [comment]
Sonar is none the wiser though.

**Comment by bradallred** [comment]
hmmm, if it doesnt build it seems like there should be a way to at least tell it some macro values so it can make an informed analysis.

**Comment by lynxlynxlynx** [comment]
As per their suggestion, I've marked the issues as won't fix. In the future we will get more control:
 
> - To improve the situation, we are working on a way to let the user force a config from the UI to cover such edge conditions(for example, by forcing some macros). It should be available in Q4.
> - In the long run, we will consider parsing CMake files to get closer to the user-preferred configuration.
