### ISSUE TITLE
BG2: Spell casting of healing spell aborted by pathfinder

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#1897]
#### Bug description

Trying to cast a healing spell on a character is never happening. Looking at the logs I see this.

```
[ResourceManager]: Found 'ARM_02d.wav' in 'chitin.key'.
[GUIScript]: Cast spell: sppr401
[GUIScript]: Slot: 0
[GUIScript]: Type: 0 (1 vs 1)
[GUIScript]: Spellname: Cure Serious Wounds
[GUIScript]: Target: 1
[GUIScript]: Range: 1
[PathFinderWIP/DEBUG]: Abandoning because I'm close to the goal
[WalkTo/DEBUG]: Jaheira: Path was just abandoned
[KeyMap]: Looking up key: 224
```

#### Steps to reproduce
1. With a cleric select a healing spell
2. Select another companion of the party
3. See error

#### Expected behavior
Healing spell is casted

#### Screenshots

https://github.com/gemrb/gemrb/assets/1820598/16b48e0f-1c7e-4e72-a4f4-82afcd2b977b

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [X] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Hmm, interesting. I can only reproduce with others around, if there's enough space it always works.
