### ISSUE TITLE
 Problems with recent versions of BGT

### ISSUE THREAD

**Issue by Fernside2** [gemrb/gemrb#1904]
Running Arkos on RG353P, GemRB 9.1 installed with portmaster. Fresh installs of BG1,BG2, BGT-Weidu.

The issue is the number of monsters spawning is not scaled for Lv1 party, eg AR2700 is spawning large groups of bears and wolves immediately after Candlekeep.

Current version of GemRB available on ArkOS is 9.1, so this issue may have been solved with the 9.2 update, but 9.2 is not available for Arkos via Portmaster or otherwise.

BGT changed:
https://www.gibberlings3.net/forums/topic/37131-gemrb-and-bgt-issue/?do=findComment&comment=326806

#### Steps to reproduce
1. Install BG1, BG2 (GOG Galaxy, Windows 7)
2. Install BGT Weidu
3. Transfer build to relevant directory on SD card.
4. Run GemRB, choose BG2 in GemRB menu, Start new Game
5. Complete Candlekeep, watch cutscene of Gorion dying.
6. Game loads in AR2700, but encounters with monsters are incorrectly scaled, eg 6 or more Bears or Wolves where 1 would be expected.

#### Expected Behaviour
Expected BGT to operate in the same way via GemRB as it performs on Windows machine.

#### Screenshots

GemRB version (check as many as you know apply)
- [ ] master as of this issue
- [ ] 0.9.2
- [ x] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by Fernside2** [comment]
> Like I said on the forum, first try with the latest release or code. Even then it's borderline a mod issue.
> 
> I have an old megamod install from Zelazko and there ar2700 is a different area, so can't really test (also the worldmap is broken).
> 
> You can also upload a fresh ar2700.are file here.

No problem, will try again when 9.2 is available for Arkos.

**Comment by Fernside2** [comment]
> Like I said on the forum, first try with the latest release or code. Even then it's borderline a mod issue.
> 
> I have an old megamod install from Zelazko and there ar2700 is a different area, so can't really test (also the worldmap is broken).
> 
> You can also upload a fresh ar2700.are file here.

Have tested with 9.2, still encountering same issue.

**Comment by lynxlynxlynx** [comment]
Did you try from Candlekeep onwards or from an old save in the same area?

**Comment by Fernside2** [comment]
> Did you try from Candlekeep onwards or from an old save in the same area?

New game each time.

**Comment by lynxlynxlynx** [comment]
Ok then upload the file.

**Comment by Fernside2** [comment]
> Ok then upload the file.

The area file?

**Comment by lynxlynxlynx** [comment]
Either, the save also has the are.

**Comment by Fernside2** [comment]
[000000007-Fernside.zip](https://github.com/gemrb/gemrb/files/12565366/000000007-Fernside.zip)
 
This is a save game in AR2700, it seems as though BGT has modified area codes for BG1, so not sure which is the relevant .are file but I hope this is useful.

**Comment by lynxlynxlynx** [comment]
Thanks, the only difference I see is what @skellytz mentioned changing in 1.21 — the difficulty level. I don't see the mod touching spawngrp.2da * — does yours look the same as https://gibberlings3.github.io/iesdp/files/2da/2da_bgee/spawngrp.htm ? Specifically check if there are any new columns, eg. bgwolf that bgt adds.

\* it says it does, but there's only one mention in a comment: https://github.com/SpellholdStudios/BGT-WeiDU/blob/dab56555e1eec6aebd3f0dfc42b38bc79ba91ef6/bgt/include/biff_move.tpa#L7

**Comment by Fernside2** [comment]
Have just checked, spawngrp.2DA is exactly the same as the copy you linked. BGT hasnt touched it as far as I can see.

**Comment by lynxlynxlynx** [comment]
Ok, then I definitely consider this a bgt issue. We use that bg2-only file to not have to hardcode the different logic. You can add a column for bgwolf like the others (not sure what weight would be best) and that should fix it for you.

**Comment by skellytz** [comment]
spawngroup.2da was used by BGT up till v1.21 which restored the original [spawn point](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm#formAREAV1_0_Spawn) system in BG1 area files. 0x76 "base creature number to spawn" is used for calculations and 0x24-0x6c resrefs are filled with creature files just like in BG1 rather than spawngroup.2da references like in BG2.

**Comment by lynxlynxlynx** [comment]
It's what allows GemRB to be data-driven in this case; we don't need to hardcode the 1:100 distinction. But it's also true there are other mechanical differences: bg2 doesn't care for CR, the whole spawn group is dumped, always. Just increasing the CR (44 / XP) to match the difficulty increase would fix it.

**Comment by lynxlynxlynx** [comment]
Ok, I suggest a simpler fix without potential side effects: set the unused bit 4 of spawn method (0x007a) in all the spawn points bgt adjusts. Then we can detect that and compensate without much hassle.

**Comment by Fernside2** [comment]
I’m assuming there’s not much more I can do to help? Just wait and hope the BGT guys take a look some time? Let me know if I can test anything or be of assistance.

**Comment by lynxlynxlynx** [comment]
Yeah, thanks. I'm ready to apply a fix, but it will need a counterpart in the mod. Unless you can rebuild gemrb on your own, with a small patch applied (for yourself), there's not much you can do yet.

**Comment by skellytz** [comment]
No problem. BGT will set that bit.

**Comment by Fernside2** [comment]
Would it be worth opening an issue on their GitHub?

**Comment by skellytz** [comment]
Is this OK? https://github.com/SpellholdStudios/BGT-WeiDU/commit/f2257d5b2224d49bf86a70058d8a89ef4b1c104f

**Comment by lynxlynxlynx** [comment]
Yes, thank you!
