### ISSUE TITLE
Crash due to invalid read in scripting

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#1913]
I can reproducibly crash by clicking on a free boulder in the iwd2 ar5004 puzzle. 
I'm surprised nobody hit this sooner, since it seems any cutscene that doesn't have just blocking actions should trigger it. It looks like it started being a problem from the cache rewrite, maybe 28564536. ~Definitely after the last release.~

<details><summary>Valgrind output</summary>
<p>

```c++
Invalid read of size 4
   GemRB::Action::GetRef() const (GameScript.h:281)
   GemRB::Response::~Response() (GameScript.h:316)
   GemRB::Response::~Response() (GameScript.h:323)
   GemRB::Response::Release() (GameScript.h:326)
   GemRB::ResponseSet::~ResponseSet() (GameScript.h:339)
   GemRB::ResponseSet::~ResponseSet() (GameScript.h:342)
   GemRB::ResponseSet::Release() (GameScript.h:345)
   GemRB::ResponseBlock::~ResponseBlock() (GameScript.h:362)
   GemRB::ResponseBlock::~ResponseBlock() (GameScript.h:365)
   GemRB::ResponseBlock::Release() (GameScript.h:368)
   GemRB::Script::~Script() (GameScript.h:381)
   GemRB::RCCache<GemRB::FixedSizeString<8ul, &strncasecmp>, GemRB::Script, GemRB::CstrHash< GemRB::FixedSizeString<8ul, &strncasecmp>, &tolower> >::Value::~Value() (Cache.h:41)

Address 0x1cb3ecec is 204 bytes inside a block of size 208 free'd
   operator delete(void*, unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
   GemRB::Action::~Action() (GameScript.h:255)
   GemRB::Action::Release() (GameScript.h:295)
   GemRB::Scriptable::ReleaseCurrentAction() (Scriptable.cpp:481)
   GemRB::GameScript::ExecuteAction(GemRB::Scriptable*, GemRB::Action*) (GameScript.cpp:2593)
   GemRB::Scriptable::AddAction(GemRB::Action*) (Scriptable.cpp:395)
   GemRB::Response::Execute(GemRB::Scriptable*) (GameScript.cpp:2441)
   GemRB::GameScript::EvaluateAllBlocks(bool) (GameScript.cpp:2192)
   GemRB::GameScript::StartCutScene(GemRB::Scriptable*, GemRB::Action*) (Actions.cpp:833)
   GemRB::GameScript::ExecuteAction(GemRB::Scriptable*, GemRB::Action*) (GameScript.cpp:2569)
   GemRB::Scriptable::AddAction(GemRB::Action*) (Scriptable.cpp:395)
   GemRB::Response::Execute(GemRB::Scriptable*) (GameScript.cpp:2441)

Block was alloc'd at
   operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
   GemRB::GenerateActionCore(char const*, char const*, unsigned short) (GSUtils.cpp:1719)
   GemRB::GenerateAction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (GameScript.cpp:2656)
   GemRB::GameScript::EvaluateAllBlocks(bool) (GameScript.cpp:2189)
   GemRB::GameScript::StartCutScene(GemRB::Scriptable*, GemRB::Action*) (Actions.cpp:833)
   GemRB::GameScript::ExecuteAction(GemRB::Scriptable*, GemRB::Action*) (GameScript.cpp:2569)
   GemRB::Scriptable::AddAction(GemRB::Action*) (Scriptable.cpp:395)
   GemRB::Response::Execute(GemRB::Scriptable*) (GameScript.cpp:2441)
   GemRB::ResponseSet::Execute(GemRB::Scriptable*) (GameScript.cpp:2393)
   GemRB::GameScript::Update(bool*, bool*) (GameScript.cpp:2125)
   GemRB::Scriptable::ExecuteScript(int) (Scriptable.cpp:342)
   GemRB::Scriptable::TickScripting() (Scriptable.cpp:264)
```

</p>
</details> 

It all comes down to this:
```c++
void GameScript::StartCutScene(Scriptable* Sender, Action* parameters)
{
	GameScript* gs = new GameScript(parameters->resref0Parameter, Sender);
	gs->EvaluateAllBlocks();
	delete gs;
}
```

We run the cutscene, reading the actions from the file and executing them (`EvaluateAllBlocks`). If they are instant (non-blocking), the actions are also freed after they're done (the `ReleaseCurrentAction` call in the trace). The dtor for GameScript then runs and tries to clean up all the hierarchy, including the already freed actions in whatever `Response` they may be. It's not a double free just because we call `GetRef` first and crash there.

I'm not sure what the best fix is. The obvious thing to try, switching to refcounting (turning `autoFree` off) in `GameScript::ReadResponse` double frees on load. I guess some `IncRef` is missing somewhere. Similarly for using shared pointers in `Response::actions`.

**Comment by bradallred** [comment]
wanna try this?

[diff.txt](https://github.com/gemrb/gemrb/files/12677927/diff.txt)

**Comment by bradallred** [comment]
you could try this patch:
[shared_ptr.patch](https://github.com/gemrb/gemrb/files/12680605/shared_ptr.patch)

**Comment by lynxlynxlynx** [comment]
Uff, that's a big diff. :) 
When does the release happen now, when the variable gets out of scope or later? I don't see any uses of `DecRef` any more, but I'm mostly worried if caching still works. Before, most of the Free* calls didn't actually release the resource, which was great, since for many of the uses, the same resources will come up again and again.

**Comment by bradallred** [comment]
Yeah, the `DecRef` is now integrated into the scope. The patch is two commits if you just want to try the cache changes without the `Action` changes.

**Comment by bradallred** [comment]
ok, it looks like `GameScript::Unusable` and `Inventory::BreakItemSlot` were the only "free" callers passing `true` for `DecRef`. I don't understand why, however. Is there a reason we have to purge the items from the cache in those cases? If so then it seems odd that the purge could only happen if there were no other references.

Seems to me that we don't need `DecRef` at all with that patch, unless I'm not understanding a reason to purge. If we do need a reason, then now we can just erase from the cache without invalidating users holding onto an existing reference. If we need the references to all be the same then we just overwrite the cached object via copy construction to achieve that.

**Comment by lynxlynxlynx** [comment]
Some of this might be a relic from msvc6 times, where we had to jump through hoops and only free memory from outside of plugins (or something like that).

I don't know if there are many uses where it makes sense to immediately purge, where we know further use is unlikely. Certain rare actions or effects might fit, but if they're rare, they shouldn't have much of an impact on the cache even if we only free on exit.

But then, why is refcounting even useful here? Without a permanent cache, wouldn't we keep loading and unloading resources, since the pointers are function local? Wouldn't an appropriately sized `LRUCache` be a better fit?

**Comment by bradallred** [comment]
Yeah, LRU would make sense IMO. As for refcounting, It's most only useful in this case because we have no idea who has a reference and when it will get released. It looks like most users only use it temporarily or make a copy (`Effect`) so maybe we should just be handing out `const&` instead which would prevent one user from modifying the cached object and force such users to copy.

**Comment by lynxlynxlynx** [comment]
Const references should work splendidly since we never modify the original resource (eg. `Item` vs the inventory's `CREItem`). I guess it's just not explicit yet and if there are any exceptions, they are bugged already.

**Comment by bradallred** [comment]
currently, we have `Scriptable::SpellCast` and `Scriptable::CreateProjectile` modifying the `Spell` returned from the cache.

**Comment by lynxlynxlynx** [comment]
Cool, so it will fix more bugs. :) Maybe it's minor, but it should still be avoided.

**Comment by bradallred** [comment]
right, its unraveling into quite a bit of cleanup, but it should make things much more clear.

**Comment by lynxlynxlynx** [comment]
I didn't mean to distract you from finishing the window work, but I guess it's too late.

**Comment by bradallred** [comment]
that just requires re-testing for regressions. I haven't had much time for either thing.
