### ISSUE TITLE
'16 Party Size' feasibility feedback for 10PP GemRB mod

### ISSUE THREAD

**Issue by WithinAmnesia** [gemrb/gemrb#1914]
https://github.com/lynxlynxlynx/gemrb-mods/issues/13

Any insights into 16 Party Size of GemRB? I have some comments on the 10PP mod for GemRB and I wish to get more feedback from the community.

Please give feedback. Thank you for the work on old BG / IWD and making these old 90's / 2000's RPGs hopefully have a optimistic future.

**Comment by lynxlynxlynx** [comment]
Let's keep the discussion in one place. GemRB doesn't care about the resolution, overall or of the assets. Party size was unhardcoded already when 10pp was developed. As for the object.ids entries, that's a simple copy paste job.
