### ISSUE TITLE
What is needed for GemRB multiplayer / LAN support? 

### ISSUE THREAD

**Issue by WithinAmnesia** [gemrb/gemrb#1915]
What is the scope for GemRB to support multiplayer or even LAN? I don't expect server hosting but the ability to plug GemRB into a server makes sense hopefully. "Multiplayer is not supported." - https://gemrb.org/Features.html Why though and what is needed in order to support multiplayer?

What are the challenges and easier things to do to support multiplayer / LAN? I remember Flare was built without multiplayer support and its a hassle now to backport it. I learned that multiplayer support should be started day 1 to avoid retroporting hell mhmm. What is the status under the hood for multiplayer / LAN support or the state of the engine / how close is GemRB to multiplayer / LAN support?

I hope there is a way to support multiplayer / LAN for that's the only like really big thing left different from the EE versions and GemRB. Furthermore GemRB is open source so it has a future whereas Beamdog is almost shutting down again so its probably up to the community now for ant old BG / IWD future works? Remastering Old BG+IWD / BGEET+ would probably need GemRB and I would imagine people would expect Multiplayer carrying forward to from BGEE and IWDEE etc. So where is GemRB with multiplayer / LAN support? I enjoy multiplayer support for RPGs so I hope the Old BG+IWD series can be remastered in 4K 60fps and probably with big multiplayer support too or at least a realistic server side plug in / LAN option to live up to expectations for a 'BG2.5'? Any feedback is welcome, thank you.

**Comment by WithinAmnesia** [comment]
https://github.com/gemrb/gemrb/issues/164 Is the EE stuff related too I would imagine or?

**Comment by WithinAmnesia** [comment]
> Nobody has ever cared about multiplayer, so it is hard to discuss and assess. It definitely wouldn't require a ground up rewrite, but it is tricky to get right (even EEs struggle with that even though they inherited multiplayer).

Okay so it is feasible to patch in Multiplayer like how Diablo1 got late dev cycle multiplayer support in 1996?

**Comment by MarcelHB** [comment]
> Okay so it is feasible to patch in Multiplayer like how Diablo1 got late dev cycle multiplayer support in 1996?

Feasible: yes. Having six people with network code experience with six months of time (according to [Wikipedia](https://en.wikipedia.org/wiki/Diablo_(video_game)#cite_ref-30)): I don't think we have them right now.

**Comment by WithinAmnesia** [comment]
> > Okay so it is feasible to patch in Multiplayer like how Diablo1 got late dev cycle multiplayer support in 1996?
> 
> Feasible: yes. Having six people with network code experience with six months of time (according to [Wikipedia](https://en.wikipedia.org/wiki/Diablo_(video_game)#cite_ref-30)): I don't think we have them right now.

We have 2020's tech hopefully? So this could be 1 person over less than a season like ~3 months?

**Comment by WithinAmnesia** [comment]
Its been like ~3 decades since Diablo 1. I hope the coding would have gotten more efficient one would imagine? 3 decades before Diablo 1 people were using magnetic physical iron rings that were literal bits and weaving copper wires by hand to make cpu and printing out debug code on paper down a hallway? https://www.youtube.com/watch?v=6mMK6iSZsAs

**Comment by MarcelHB** [comment]
This isn't your highly (and commercially) supported Unreal Engine with a PnP MP framework. It's a code base not much younger than D1 and we are trying not to break the menu music every time we touch something.

**Comment by bradallred** [comment]
I don't believe anybody working on GemRB currently has any experience with LAN gaming. My own networking experience is limited to very basic communication over unix sockets which wouldn't be what we would want to use here anyway. The networking isn't event the difficult part these days. There are cross platform libraries for that part. The difficulty is in architecting the the game loop for the clients and synchronizing relevant state with the server.

AFIK, we all have other areas of focus and I haven't sensed much interest in this. But as you said its open source, so if you know people...

**Comment by bradallred** [comment]
> > > Okay so it is feasible to patch in Multiplayer like how Diablo1 got late dev cycle multiplayer support in 1996?
> > 
> > 
> > Feasible: yes. Having six people with network code experience with six months of time (according to [Wikipedia](https://en.wikipedia.org/wiki/Diablo_(video_game)#cite_ref-30)): I don't think we have them right now.
> 
> We have 2020's tech hopefully? So this could be 1 talented person over less than a season like ~3 months?

A team of people with the right tools and knowledge and _full time employment_. They also likely weren't starting from scratch.

**Comment by WithinAmnesia** [comment]
https://www.youtube.com/watch?v=WZyRbnpGyzQ We should do multiplayer because it is hard and would do well to serve to measure our best and brightest. How are we to succeed old BG+IWD in open source if we cannot match what people did 4 decades ago in the 1990's? We are at risk of losing this forever because we are are losing momentum but the world marches on with or without us regardless of how we feel yet the world does care about what we do. Glory to the person in the arena and all that too. Rome wasn't built in a day nor with one set of hands, wherever a person can live a person can live well, the kingdom of humanity is within all people etc, this republic shall not perish from the earth etc, fight them on the beaches and hills we shall never surrender, I need ammunition not a ride etc etc. What is worth doing though? So old BG+IWD needs multiplayer help with GemRB I suppose? Its open source which is good. Where are these talented people one would wonder?

**Comment by MarcelHB** [comment]
> https://www.youtube.com/watch?v=WZyRbnpGyzQ We should do multiplayer ...

Feel free to dig into this, we'll gladly looking forward for this contribution. In the meantime, we'll keep ourself and the other players happy with getting the SP work done. 🙂

**Comment by WithinAmnesia** [comment]
Its been 20 years it says on the GemRB website: https://github.com/gemrb/gemrb/graphs/contributors . The future is with multiplayer whether or not I am able to deliver such. Flare may just be stuck with singleplayer yet will GemRB be stuck without multiplayer? BG3 and the legal owners of the Faerun and D&D content abandoned the Infinity Engine because in their eyes it has no future and if things remain the same they are correct. The old BG+IWD will shrink the patches will die out because new players will not revitalize the community because we failed them and their expectations of quality. When BG was younger it had a growing population and was on the cutting edge of technology. Yet here I am a child who learned to read playing old BG when I was barely 9 years old and I am standing here asking the best and brightest of the community of a game I dearly love what are we going to do to make sure we have a future?

I don't want these games to die a long slow painful death as they are now if nothing changes. I am not comfortable nor happy for I know what the EEs are is not enough to prevent old BG and IWD from becoming an irrelevant relic of the past come the 2030's. I can say this for I may be one of the youngest devs here and I know the world is changing and I feel it change and its not as nice as it used to be when I was growing up. The giants of the industry are dying and the creators of these games have abandoned them to the digital wilds of the community.

I know a reckoning is coming to this community for the future offered here is nothing but the past and the world needs new horizons new thrills new wonders to hold up the world and their good will to be worth to be played. Old BG and IWD are old clunky horribly pixelated and they need not just multiplayer but a multiplayer overhaul so its up to speed with todays and the *futures'* expectations. We need to plan ahead stay fit or die to obscurity a long slow painful death as the like of every old dead franchise.

BG3 is not the same as BG1&BG2 its a different kind of game. Its fully 3D its smaller in scope yet it has a bright future and new people will want to play BG3 regardless of if we like it or not. This not about what I want in features or addons to feel happy its about is this community fit enough to earn a future? Diablo II Resurrected will find new fans new people new blood into the 2020's and 2030's and probably spawn a sequel but what will we do stuck at 480p singleplayer and code older than most people playing games today? Don't we want a bright future?

We can have 4K 60fps 16:9 but we need to be fit and healthy and able to lead well enough to draw in new players not just old and we need multiplayer damned if I can do it or not if there is a will and opportunity there is a way. I fear losing Old BG+IWD, I don't want my dreams to be dreams I want to just do it. https://www.youtube.com/watch?v=5-sfG8BV8wU . Nothing is impossible. I want to realize my and the communities' dreams but it requires fitness and power to be worth in the furnaces of adversity and the glory of life. Everyone else way wish to fade away yet I won't go gently into that good night. We can be great, we can rise to be amongst the mighty of old; we are humanity. https://www.youtube.com/watch?v=a3lcGnMhvsA + https://www.youtube.com/watch?v=A311CnTjfos&pp=ygUVVGhlIE1hbiBpbiB0aGUgQXJlbmEg + https://www.youtube.com/watch?v=w1JJ5actiUM + https://www.youtube.com/watch?v=RlKJDwViNKs + https://www.youtube.com/watch?v=KlUMrzwmbyo It is possible and it is necessary to be great; even if you start from less than nothing like myself you can rise to do anything but you have to be willing to pay the sacrifice.

We need to turn dreams into reality, even if we fail we can still plant the seed that will grow into the fruit tree that will bear into fruition our dreams. We can fail until we fail so much there is nothing left but success. Even if everyone thinks you are being a failure you can still win; for as long as you can keep fighting for what you love for you just need life and reality and as cruel as they are they can be engaged with and will give infinite chances if you are worthy; so long as one just keeps fighting, always be unyielding.

**Comment by WithinAmnesia** [comment]
> Yeah, but you could spend less time writing speeches and spend more time familiarizing yourself with Wireshark or the code base, that will get _us_ closer to what you ask for.

I wish to communicate how I feel. Some dreams are not about one person or or one vision but are are for everyone and there to empower everyone they find and inspire to be greater than what they once were. True strength is empowering those around you. I am finite yet I am glad you hope that I could be more than what I currently am. No king or queen or leader rules forever. Happy is the city that in peace thinks of war. Civilizations thrive when old people plant trees in which they know their shade they'll never sit under. https://www.youtube.com/watch?v=w8HdOHrc3OQ + https://www.youtube.com/watch?v=BCr7y4SLhck + https://www.youtube.com/watch?v=0rW7U6_AM4w Its about making sure every is okay and things will get better no matter who is leading its about values and hope and succession. These games hold values that's why they have wonder and challenge and mystery. Values are within everything in life. I am not special but with healthy succession it doesn't matter if one person is special to save the day it can be everyone together that is special and that needs hope and inspiration and good values to believe in. I am one person but maybe I can help many people if I am worthy of these hopes and dreams.

**Comment by MarcelHB** [comment]
A'ight, please pull a number and wait for your call. ETA: twelve years.

**Comment by lynxlynxlynx** [comment]
Closing as out of scope.
