### ISSUE TITLE
Save game files randomly/suddenly bloat 

### ISSUE THREAD

**Issue by tomasz89** [gemrb/gemrb#1919]
Sorry to say this appears randomly/spuriously. I can't exactly find a method to reproduce. If I do I'll update here.

Playing Baldur's Gate 1, from GOG + the fix pack.

I notice sometimes when I save it suddenly grows - a LOT! See output from a du -sm of my save game directory:
1	000000000-Auto-Save
1	000000013-tg2
1	000000015-tg4
1	000000017-tg5
1	000000018-tg6
8045	000000019-new large 

I'm playing the game, doing my thing, running, killing etc, around map AR2800. Actually this map may be the common thread; I didn't notice this in Candlekeep and had previously cleared AR2700 without issue.

I'm running bb3eb9212d51a44669c18fcdc60a00eb9f3413a2 on Linux/Ubuntu 23.04 x64, compiled from source against SDL2/OpenGL. I previously experienced this using 0.9.0+dfsg-1build2 (straight from the repos) so thought I'd move to sources and had the same effect.

This problem gets worse and worse if I keep playing. Moreso, if I save **over** a corrupted/bloated save, it just grows even more. I've found to quit/delete the save, then restore from other saves (which are ~1MB) to be the only fix.

Hard to provide the corrupted saves but they're VERY large, happy to provide other saves but I can seem to play on for a while before suddenly and randomly finding saves bloat and save times increase drastically as expected for a file 5G in size.

**Comment by lynxlynxlynx** [comment]
Thanks for the report! Can you look at one of the corrupted saves in NearInfinity? It will show you all the files inside — I wonder if there are any misnamed duplicates. And `hexdump -C blabla.sav | head -n10` (it is the .sav that's the largest file in the save folder, right?).

**Comment by tomasz89** [comment]
Hmm... I can't be sure I've done what you're asking.
I've downloaded/compiled NearInfinity from sources, opened the game from the same directory GemRB is using, that seems to read OK.
I've done an "open file" and opened the baldur.gam from the bloated save. I see no specific evidence of duplication.

Yes it's the .sav file which becomes large.

Hexdemp embedded below:

00000000  53 41 56 20 56 31 2e 30  0b 00 00 00 61 72 32 36  |SAV V1.0....ar26|
00000010  31 37 2e 61 72 65 00 db  6f d6 53 48 fd f7 a5 00  |17.are..o.SH....|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
a5f7fd60  00 00 00 00 00 00 00 0b  00 00 00 61 72 32 36 30  |...........ar260|
a5f7fd70  36 2e 61 72 65 00 ca 35  02 5a 82 d6 dd d2 00 00  |6.are..5.Z......|
a5f7fd80  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
178d5cd70  00 00 00 00 00 00 00 00  00 00 00 00 00 00 ff be  |................|
178d5cd80  d0 91 b9 0b 00 00 00 61  72 32 36 30 36 2e 61 72  |.......ar2606.ar|

**Comment by lynxlynxlynx** [comment]
You open the sav to see its listing, it's just a glorified archive. Already from the hexdump I see something interesting — an entry for ar2606 is repeated (reminds me of problems @cyrus-and is having). If you dump a bit more than the first 10 lines, do you see more repeats?

**Comment by tomasz89** [comment]
Yes, there are multiple references to ar2606. I see it interspersed with other references, but this seems to be the main culprit. Below is a grep of the pattern:

00000000  53 41 56 20 56 31 2e 30  0b 00 00 00 61 72 32 36  |SAV V1.0....ar26|
00000010  31 37 2e 61 72 65 00 db  6f d6 53 48 fd f7 a5 00  |17.are..o.SH....|
a5f7fd60  00 00 00 00 00 00 00 0b  00 00 00 61 72 32 36 30  |...........ar260|
a5f7fd70  36 2e 61 72 65 00 ca 35  02 5a 82 d6 dd d2 00 00  |6.are..5.Z......|
178d5cd80  d0 91 b9 0b 00 00 00 61  72 32 36 30 36 2e 61 72  |.......ar2606.ar|
178d5d1a0  00 00 61 72 32 36 31 37  2e 61 72 65 00 bc 1d 00  |..ar2617.are....|
178d5d400  0b 00 00 00 61 72 32 36  31 36 2e 61 72 65 00 65  |....ar2616.are.e|
178d5d420  61 72 32 36 30 36 2e 61  72 65 00 4c 2c 00 00 04  |ar2606.are.L,...|
178d5d830  8a f9 14 1d 99 27 ed 0b  00 00 00 61 72 32 36 31  |.....'.....ar261|
178d5d840  37 2e 61 72 65 00 bc 1d  00 00 06 04 00 00 78 da  |7.are.........x.|
178d5e420  61 72 32 36 30 36 2e 61  72 65 00 4c 2c 00 00 04  |ar2606.are.L,...|
178d5e830  8a f9 14 1d 99 27 ed 0b  00 00 00 61 72 32 36 31  |.....'.....ar261|
178d5e840  37 2e 61 72 65 00 bc 1d  00 00 06 04 00 00 78 da  |7.are.........x.|
178d5f420  61 72 32 36 30 36 2e 61  72 65 00 4c 2c 00 00 04  |ar2606.are.L,...|
178d5f830  8a f9 14 1d 99 27 ed 0b  00 00 00 61 72 32 36 31  |.....'.....ar261|
178d5f840  37 2e 61 72 65 00 bc 1d  00 00 06 04 00 00 78 da  |7.are.........x.|
178d60420  61 72 32 36 30 36 2e 61  72 65 00 4c 2c 00 00 04  |ar2606.are.L,...|
178d60830  8a f9 14 1d 99 27 ed 0b  00 00 00 61 72 32 36 31  |.....'.....ar261|
178d60840  37 2e 61 72 65 00 bc 1d  00 00 06 04 00 00 78 da  |7.are.........x.|
178d61420  61 72 32 36 30 36 2e 61  72 65 00 4c 2c 00 00 04  |ar2606.are.L,...|
178d61830  8a f9 14 1d 99 27 ed 0b  00 00 00 61 72 32 36 31  |.....'.....ar261|
178d61840  37 2e 61 72 65 00 bc 1d  00 00 06 04 00 00 78 da  |7.are.........x.|
178d62420  61 72 32 36 30 36 2e 61  72 65 00 4c 2c 00 00 04  |ar2606.are.L,...|
178d62830  8a f9 14 1d 99 27 ed 0b  00 00 00 61 72 32 36 31  |.....'.....ar261|
178d62840  37 2e 61 72 65 00 bc 1d  00 00 06 04 00 00 78 da  |7.are.........x.|
178d63420  61 72 32 36 30 36 2e 61  72 65 00 4c 2c 00 00 04  |ar2606.are.L,...|
178d63830  8a f9 14 1d 99 27 ed 0b  00 00 00 61 72 32 36 31  |.....'.....ar261|
178d63840  37 2e 61 72 65 00 bc 1d  00 00 06 04 00 00 78 da  |7.are.........x.|
178d64420  61 72 32 36 30 36 2e 61  72 65 00 4c 2c 00 00 04  |ar2606.are.L,...|
178d64830  8a f9 14 1d 99 27 ed 0b  00 00 00 61 72 32 36 31  |.....'.....ar261|
178d64840  37 2e 61 72 65 00 bc 1d  00 00 06 04 00 00 78 da  |7.are.........x.|
178d65420  61 72 32 36 30 36 2e 61  72 65 00 4c 2c 00 00 04  |ar2606.are.L,...|
178d65830  8a f9 14 1d 99 27 ed 0b  00 00 00 61 72 32 36 31  |.....'.....ar261|
178d65840  37 2e 61 72 65 00 bc 1d  00 00 06 04 00 00 78 da  |7.are.........x.|
178d66420  61 72 32 36 30 36 2e 61  72 65 00 4c 2c 00 00 04  |ar2606.are.L,...|
178d66830  8a f9 14 1d 99 27 ed 0b  00 00 00 61 72 32 36 31  |.....'.....ar261|
178d66840  37 2e 61 72 65 00 bc 1d  00 00 06 04 00 00 78 da  |7.are.........x.|
178d67420  61 72 32 36 30 36 2e 61  72 65 00 4c 2c 00 00 04  |ar2606.are.L,...|
178d67830  8a f9 14 1d 99 27 ed 0b  00 00 00 61 72 32 36 31  |.....'.....ar261|
178d67840  37 2e 61 72 65 00 bc 1d  00 00 06 04 00 00 78 da  |7.are.........x.|
178d68420  61 72 32 36 30 36 2e 61  72 65 00 4c 2c 00 00 04  |ar2606.are.L,...|
178d68830  8a f9 14 1d 99 27 ed 0b  00 00 00 61 72 32 36 31  |.....'.....ar261|
178d68840  37 2e 61 72 65 00 bc 1d  00 00 06 04 00 00 78 da  |7.are.........x.|
178d69420  61 72 32 36 30 36 2e 61  72 65 00 4c 2c 00 00 04  |ar2606.are.L,...|

**Comment by lynxlynxlynx** [comment]
Crap, this is much worse than I expected. I can reproduce blocking problems quite easily. I load a game, pause, quick save (same size), then quick save again. I have to kill gemrb then, since it starts creating a huge ares.blb in the cache, taking all my space.

**Comment by tomasz89** [comment]
Yep. Pretty much has stopped my ambitions to play BG at this point in time. Glad you found a path to reproduce.

**Comment by lynxlynxlynx** [comment]
Just use the released version (you can build the tag v0.9.2 yourself), this is a regression from later.

**Comment by tomasz89** [comment]
Agree this seems not an issue with v0.9.2.

**Comment by lynxlynxlynx** [comment]
Actually I can't reproduce in bg1 or bg2. Tried with fresh state, old saves, same thing. But I can immediately with my quicksave in iwd2, interesting. It does have multiple quicksaves, but I doubt this is related.

**Comment by lynxlynxlynx** [comment]
Interesting, I didn't know we create bif files — I have some fresh ones in cache named after areas. They're not from original data (one are.bif), unless they nested bifs. Nor do I see the code, hah.

**Comment by MarcelHB** [comment]
Is this really a bif file, not just by its name?

**Comment by lynxlynxlynx** [comment]
The header starts with the right signature, but I didn't investigate compliance much farther.

**Comment by lynxlynxlynx** [comment]
Ah, those bifs are in the cd2 path. Still no point in caching them, but I doubt it's related to this bug.

**Comment by lynxlynxlynx** [comment]
@tomasz89 this fixes it for me, can you check if it does for you as well please?
```diff
diff --git a/gemrb/core/SaveGameAREExtractor.cpp b/gemrb/core/SaveGameAREExtractor.cpp
index a06d07502..beaa77fd5 100644
--- a/gemrb/core/SaveGameAREExtractor.cpp
+++ b/gemrb/core/SaveGameAREExtractor.cpp
@@ -47,14 +47,14 @@ int32_t SaveGameAREExtractor::copyRetainedAREs(DataStream *destStream, bool trac
 
        size_t relativeLocation = 0;
        for (auto it = areLocations.cbegin(); it != areLocations.cend(); ++it, ++i) {
-               relativeLocation += 4 + it->first.length() + 1;
+               relativeLocation += 4*2 + it->first.length() + 1;
 
                ieDword complen, declen;
                saveGameStream->Seek(it->second, GEM_STREAM_START);
                saveGameStream->ReadDword(declen);
                saveGameStream->ReadDword(complen);
 
-               destStream->WriteDword(it->first.length() + 1 + 4);
+               destStream->WriteDword(it->first.length() + 1 + 4); // +1 for ending null as per SAV spec
                destStream->WriteString(it->first);
                destStream->WriteString(".are");
                destStream->WriteDword(declen);
```

I don't understand the target layout fully, but since the change to ResRef in adb9ce108 the offset hasn't been updated (the string used to contain the extension, so was longer). 
@MarcelHB does it look ok to you? 4 for the first dword, 4 + len + 1 for the filename and then later 8 and complen to skip the last two dwords and compressed data.

**Comment by MarcelHB** [comment]
The target layout is simply a [SAV file entry](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/sav_v1.htm) per ARE.

But yeah, this should do it.

**Comment by MarcelHB** [comment]
There is no signature here, that does the SAV writer. Those entries are simply blobbed together into that `*.blb` just gets binary-append and nobody notices.
