### ISSUE TITLE
compiling with USE_LIBVLC set to OFF doesn't work.

### ISSUE THREAD

**Issue by fogobogo** [gemrb/gemrb#192]
Trying to build gemrb from git and disabling the USE_LIBVLC option ends in a failed compilation. 

Turns out, the `bink_tree[i].init_vlc(...)` function in BIKPlayer.cpp has no `#ifdef` as well as the `VLC` class in GetBitContext.cpp.

Both files are found under `/gemrb/plugins/BIKPlayer/`

No issues without that.

**Comment by lynxlynxlynx** [comment]
Hmm, that's odd. I don't have all the required VLC stuff installed (cmake isn't happy), but BIKPlayer still builds fine. There are several things that could be wrong, so please include cmake output.

**Comment by fogobogo** [comment]
here goes...
[log.txt](https://github.com/gemrb/gemrb/files/3562598/log.txt)

**Comment by lynxlynxlynx** [comment]
Ok, while I don't see any detection output, it's pretty clear it has nothing to do with the VLC plugin at all. If you don't pass USE_LIBVLC you should get the same error. I think you have an older gcc version, before the fallthrough warnings were relaxed. Pass -DDISABLE_WERROR=1 and it should finish.

**Comment by fogobogo** [comment]
gcc version is 8.3.0 but I just tried and indeed that did the trick.
Sorry for the ruckus and thank you very much.

**Comment by lynxlynxlynx** [comment]
For non-release sources we have almost all warnings turned on and made fatal, so we can improve as they get added. But when they added this particular one, it was too greedy, so meh, ignoring is better. Later versions amended this.

Btw, where/how did you find gemrb?
