### ISSUE TITLE
GemRB with Godot?

### ISSUE THREAD

**Issue by WithinAmnesia** [gemrb/gemrb#1920]
How could one effectively port GemRB to Godot 4+?

Old BG+IWD maps are made from tiles and could in theory be ported to GemRB like one big tileset. The combat can be ported I think too. I have seen tutorials on Diablo 2 and old Zelda style combat and there are some plugins that help with items and general rpg stats and systems.

The multiplayer might be better off with the multiplayer options in Godot 4+

The D&D spells I am not sure how to port, I can see most of them working but the wizard chess may have to be delayed like BG1998 or BG3 for the Level 7+ spells get really tricky. As in there is a simple pen and paper description but kinda clunky list of if then cases going on behind the screens for many spells but I guess with a robust spell system it could be done? Even if the Spells got up to level 6 like in BG3 that would cover a lot of gameplay scenarios are get the bulk of the experience together. Spells like Wish or Miracle and Time Stop are kinda hard to pull off, literally 'a wizard did it' but they are cool just hard to replicate lol.

I've seen mouse movement control tutorials for Godot but how does one do Real Time Strategy controls in Godot mixed with say Baldur's Gate? I'd prefer not to do turn based combat but real time with kinda maybe optional pause combat but it might be hard to implement for multiplayer. I guess if 16 party sizes were allowed but pausing was gone it would sorta balance out and play like Warcraft 2 and or 3 and or Like multiplayer Diablo 2 with a bunch of summons or something like multiplayer Mount and Blade or Age of Empires on smaller scenarios kinda?

I can port the art, the maps, the player animastions, and general stats rpg systems. Yet it's the party system and rts elements I have a tricky time trying to figure out. Any help or suggestions? [So far I have the tilesets WASD movement procedural generation for building up a free open source 2D / 2.5D ARPG for Godot 4+](https://github.com/WithinAmnesia/ARPG). Yet it's like how do I do crpg / old bg+iwd / classic rts games in Godot and maybe make a version of my open source ARPG that can handle these kinds of game implementations hopefully?

**Comment by MarcelHB** [comment]
> How could one effectively port GemRB to Godot 4+?

Maybe ask someone familiar with and at Godot? Show them the SP game spec: https://gibberlings3.github.io/iesdp/

**Comment by WithinAmnesia** [comment]
Oh thank you for that helping insight. Its like a big engine manual for the Infinity Engine. That's very useful.

**Comment by lynxlynxlynx** [comment]
It's a bit of a pointless questions, since it should be possible to use any engine as a base. It just means various levels of extra work and inefficiencies. But it's _just_ code, real limits are rare if you're determined.
You can look at the Game and Map classes if you don't want to start from the main game loop.
