### ISSUE TITLE
Character movement invisible when interacting with environment

### ISSUE THREAD

**Issue by tomasz89** [gemrb/gemrb#1921]
I'm playing baldur's gate 1 through gemrb, vanilla GOG install + fixpack (plainab).
Version is ec6f1282354625d5146e73fb77210d676342d6c8 compiled from source on Ubuntu 23.04, SDL2/OpenGL.

I'm noticing whenever I click on objects - eg containers, or actors, that my movement is not shown; my character disappears. Clicking on the ground to walk is fine, just when there's an active "target".

Some oddness also for monsters making their way towards me, they seem to "slide".

To reproduce:
- Start a new game
- Create the character
- Once in the game, move away from the inn doors a little.
- Click on the doors of the inn; observe that the movement between initial location and final location you are not visible.
- The doors still open though.

I've tried to enable the video workarounds (using software for any/all) to no avail.

**Comment by lynxlynxlynx** [comment]
Huh, that sounds more like missing animations. Do you get any error spam in the log?

**Comment by tomasz89** [comment]
The following repeated from the consoled over and over from my compiled version:

[ResourceManager/ERROR]: Couldn't find 'CEFT2e.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: CEFT2e (0x6311)

I took this installation from the GOG Windows install within a VM.

The Ubuntu version, using the resources from the GOG installer, similar story:
[ResourceManager/ERROR]: Couldn't find 'cifc1.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: cifc1 (6014)

**Comment by lynxlynxlynx** [comment]
I've just tried creating a new bg1 char on my gog install and it still works. And then a female elven thief, which I believe is your first log entry. And it's not something to blame the fixpack for either.

Do you have the same problem with appimage for the last release? We have renovated much of our path handling and perhaps there was an uncaught regression.

**Comment by tomasz89** [comment]
Thanks for investigating. I'm now running ceb77ab2cca90eef2c0a97dcdef78a19c30ceaaa but have the same result. Sorry am not sure what you mean by appimage.

**Comment by lynxlynxlynx** [comment]
The officially released binaries.

**Comment by tomasz89** [comment]
I've tried using the game assets three ways all with the same result.
From GOG I downloaded the installer for Linux and used game-data-packager to package and then install.
I point the cfg file at the directory above and get the invisible effect. Or using v0.9.0 of gemrb from the Ubuntu repos pointed at the same assets, same effect.

Using the installer above, I ran the shell script which deploys a wine instance, pointed the cfg file at that deployment's assets. Ran the game using a compiled 0.9.2 tag with the config adjusted to this directory, and get this effect.

Finally, I obtained the Windows version, I install in a Windows XP VM, applied the fixpack, and copy the assets over to Linux. I run gemrb against these assets, same effect.

**Comment by tomasz89** [comment]
I did try to find the "ceft2.bam" file in the directories, and sure enough it does not exist. Is it part of some compressed asset or something? The only *.bam files I have are in the "Override" directory.

**Comment by lynxlynxlynx** [comment]
Yeah, they're in the bif files. Are you using the Polish version?

**Comment by tomasz89** [comment]
I can see what the game is looking for, however there are no unpacked files by that name. No, the English version is what I'm on.

**Comment by lynxlynxlynx** [comment]
We read from these custom format archives directly since that's more efficient than fully unpacking.
Are you running on some special partition type? Is it case sensitive? Can you post the log somewhere (it's enough just for startup, no need to load a game)?

**Comment by tomasz89** [comment]
It's an ext4 partition, case sensitive (as Linux is).
[GemRB.log](https://github.com/gemrb/gemrb/files/12817337/GemRB.log)

**Comment by tomasz89** [comment]
Using NearInfinity I can't see that CEFT2e asset that gemrb is looking for anywhere at all.

**Comment by lynxlynxlynx** [comment]
Besides the curious dir name, I don't see anything wrong in the log.

There's no reason for it to exist, the name is bad — something is missing (two chars for the stance). Eg. it should be CEFT2A1e.bam for one of the attacks. But at least we're making progress. :)
In this case this is done in `CharAnimations::AddMHRSuffix`, but I think you'd go mad if you tried breaking on that, since it's hit every tick and for most bg1 animations. Hmm

**Comment by tomasz89** [comment]
I have several installs and this was where I unpacked the transferred-from-Windows BG data with fixpack applied, was meant to be temporary but it seems like it's sticking!

Right I see; some of the assets are not being suffixed, hence the hopeless search ..

**Comment by lynxlynxlynx** [comment]
Did I understand correctly that you also tried the gog installer itself? That's what I used.
But it shouldn't really matter, since things are missing from the middle of the filenames for you. :s

**Comment by tomasz89** [comment]
Hi, yes; have installed:
baldur_s_gate_the_original_saga_gog_3_23532.sh (using game-data-packager, and just by running the sh)
setup_baldurs_gate_2.0.0.20.exe (in Windows XP VM, then copied over).

The truncation is interesting..

**Comment by bradallred** [comment]
is there any chance this regression is already fixed? Seems like it could be if you have the same install on a CI-FS. Otherwise maybe a sanitizer would say something useful.

**Comment by lynxlynxlynx** [comment]
No, that's a dud. We put a final null byte in in the very next line this complains about (so far we just disable it breaking the build, not displaying the whole warning class). I'm also building with gcc 12.

**Comment by tomasz89** [comment]
Hi, got it, please find attached.
[valgrind.log](https://github.com/gemrb/gemrb/files/12856200/valgrind.log)

**Comment by tomasz89** [comment]
Indeed; I've got two versions installed, one from the Ubuntu repos, and the other built from sources. I ldd'd the sources and it doesn't point to /usr/lib. My valgrind command line was using gemrb from $PATH (by accident). Just to be sure, I got rid of the Ubuntu-supplied gemrb instance and changed the valgrind command to be more explicit, new log attached.
I see the same effect after this run with regards to the no animations.
[valgrind.log](https://github.com/gemrb/gemrb/files/12859028/valgrind.log)

**Comment by lynxlynxlynx** [comment]
Thanks, but alas, nothing really interesting in that log either.
It's really odd, congratulations! ;) We're even on the same distro, not just using the same data and software.

**Comment by bradallred** [comment]
A UBSan build might reveal something. @tomasz89 are you playing in English?

**Comment by tomasz89** [comment]
Yes, English version of the game. By UBSan I assume you mean a sanitised build? I will try that.

**Comment by lynxlynxlynx** [comment]
Pass `-DSANITIZE=undefined` when calling cmake then.

**Comment by tomasz89** [comment]
I've tried address sanitisation as previously mentioned, still see the same in the log over and over:
[CharAnimations/ERROR]: Couldn't create animationfactory: CEFT2e (0x6311)
[ResourceManager/ERROR]: Couldn't find 'CEFT2e.bam'.

[output.log](https://github.com/gemrb/gemrb/files/12872666/output.log)

Otherwise memory leak output in the log attached. Recompiling now with the argument you've given.

**Comment by tomasz89** [comment]
OK; it was asked for prior hence I provide. Here is log output from the undefined santiser run:
[output.log](https://github.com/gemrb/gemrb/files/12872797/output.log)

**Comment by bradallred** [comment]
ok, thanks; nothing there either. I'm not sure what other straws to grasp at other than gemrb.cnf/gemrb.ini settings. Maybe your config is pointing to an older build resources directory or something.

**Comment by tomasz89** [comment]
When I get a chance I'll try foscking through the code, now that I know the truncation of the filename is a culprit that's a good starting point.

**Comment by tomasz89** [comment]
OK; some progress. Yes you're right insofar as it is likely a configuration difference. 
In my gem-baldur.ini, I have
"Always Run = 1".
This causes a stance ID of 15 in CharAnimations::AddMHRSuffix.

Changing "Always Run = 0" changes the stance ID to 10, and my characters don't disappear.

**Comment by tomasz89** [comment]
I changed the define of RUN to 55, and sure enough when Always Run is 1, the game aborts out with:
[CharAnimation/FATAL]: Illegal stance ID

So that seems to be the gotcha. I must have figured at some point when I was setting up the game "Why NOT always run? It's faster, right?".

Suggest the treatment is to deconflict the defines in CharAnimations.h.

**Comment by lynxlynxlynx** [comment]
We can't do that, that's from the data. Only pst supports running and you explicitly sidestepped our checks by enabling that option. This should fix it even if you do shoot yourself in the foot that way:

```diff
diff --git a/gemrb/core/GUI/GameControl.cpp b/gemrb/core/GUI/GameControl.cpp
index 5240b438a..6ee371fd0 100644
--- a/gemrb/core/GUI/GameControl.cpp
+++ b/gemrb/core/GUI/GameControl.cpp
@@ -273,9 +273,10 @@ void GameControl::ClearMouseState()
 // only PST supports RunToPoint
 void GameControl::CreateMovement(Actor *actor, const Point &p, bool append, bool tryToRun) const
 {
-       Action *action = NULL;
-       tryToRun |= AlwaysRun;
-       
+       static bool hasRun = GenerateActionDirect("RunToPoint([0.0])", actor) != nullptr;
+       Action* action = nullptr;
+       tryToRun = hasRun && (tryToRun || AlwaysRun);
+
        if (append) {
                action = GenerateAction(fmt::format("AddWayPoint([{}.{}])", p.x, p.y));
                assert(action);
```
