### ISSUE TITLE
BG1 Save prevented en route to destination

### ISSUE THREAD

**Issue by tomasz89** [gemrb/gemrb#1927]
Running 9d76fac83c03547bb301e1f99beafee0799b2518 on Ubuntu 23.04. Compiled with OpenGL/SDL2. BG1 GOG version with Fixpack.

I left west of Nashkel town, got waylaid by enemies on the way to AR4700. Encountered a bear along the way, took care of it. Now, even after writing this report (several minutes) save is still prohibited -
"You cannot save at this time".
Where more than sufficient time has passed since combat and no other enemies are on this small screen.

On pressing quick save, the following appears in the log:
[KeyMap]: Looking up key: 113 (q) 
[KeyMap]: RunFunction(GUISAVE::QuickSavePressed)
[ResourceManager/WARN]: 'worldm25.wmp' not found...

On leaving the combat zone, once I arrive at AR4700, I can save again (although the entering autosave is prohibited, a subsequent manual save works).

**Comment by bradallred** [comment]
is this actually a bug? I didn't think the originals let you save in those areas either.

**Comment by tomasz89** [comment]
Good question, never played the original :)

**Comment by bradallred** [comment]
yeah, there are [bits on the ARE](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/are_v1.htm) that determine if you can save or not. If NI says that bit isn't set then I guess its maybe a bug.

**Comment by lynxlynxlynx** [comment]
Yes, you are not supposed to be able to save in ambush areas. This way they can get recycled.
