### ISSUE TITLE
 Scripts deal damage only to the last triggerer

### ISSUE THREAD

**Issue by Dreamkins** [gemrb/gemrb#1934]
#### Bug description
Scripts from the "slimedamage" group deal damage only to the last triggerer (maybe others scripts too). You can check it at the last level of the Durlag tower from BG1. 

#### Steps to reproduce
1. Go to slime first character.
2. Go to slime second character.
3. Only the second character will receive damage

#### Expected behavior
Both characters must take damage.

GemRB version (check as many as you know apply)
- [x] 0.9.2

**Comment by lynxlynxlynx** [comment]
ctrl-m on the trap (which I guess is what you mean by script) to get its name and actual AI script that it runs. Which you can then inspect to see how it was coded. Could easily be an original design decision or data bug.

**Comment by Dreamkins** [comment]
![slimedamage](https://github.com/gemrb/gemrb/assets/119408536/3413355d-721e-43f5-a45d-48ccaea9e127)
This is not a trap, this is slime) Omg In the original BG1 it does not damage))

**Comment by Dreamkins** [comment]
There, Targets *GameScript::LastTrigger is called, which returns only the last triggerer.

**Comment by lynxlynxlynx** [comment]
Of course, that's what it's supposed to do. And it's technically still a trap, even though you may not be able to detect or disarm it. You can look it up in the area via NearInfinity.

**Comment by Dreamkins** [comment]
[000000001-Quick-Save.zip](https://github.com/gemrb/gemrb/files/13457853/000000001-Quick-Save.zip)
My save

**Comment by lynxlynxlynx** [comment]
Rather post the technical details, nothing interesting will be in the save, since this is base game data.

**Comment by Dreamkins** [comment]
I posted the save only for a quick reproduct if someone wants to look. Apparently there are no errors in the code, the problem is in the logic, the second one to come will always be the last triggerer. It's very strange that the original BG1 has no damage.

**Comment by Dreamkins** [comment]
If you need script names, they are called "slimedamage" with a number at the end.

**Comment by lynxlynxlynx** [comment]
It's faster if you report the area code and the scripts used (not the (script)names of the regions).

**Comment by Dreamkins** [comment]
AR0514.ARE 
Point of interest "Slime damage" 01-10
Script used PDT1.BCS

**Comment by lynxlynxlynx** [comment]
Thanks. Interestingly NI doesn't even parse the file properly; I suspect IsOverMe was added only with totsc. If not, then that would explain why it does nothing in the original. My copy doesn't have it registered in trigger.ids, which then explains everything.

Scripts don't evaluate every tick and the way the trap is set up makes it inevitable only one actor will get targeted. It would be up to a mod to change the behaviour to something nastier.
