### ISSUE TITLE
Attack animation problems

### ISSUE THREAD

**Issue by Dreamkins** [gemrb/gemrb#1935]
#### Bug description
Some monsters (such as Ettercap) have a weapon action equip best weapon when attacking, which resets its attack animation. Resetting an attack before the attack projectile is fired will result in the attack being lost.
There is the opposite situation, when the attack animation switches to walking, and then back. Then the attack animation will resume its frame.

- [x] 0.9.2

The screenshot shows that Ettercap is in an attack state and its attack animation will be reset by equip.
![dropanimationbyequip](https://github.com/gemrb/gemrb/assets/119408536/0e7a42c2-38f8-4867-af5a-0423de273628)

**Comment by lynxlynxlynx** [comment]
It's correct that we do that, but we shouldn't do it if it doesn't cause an actual weapon change. Probably best prevented in `GameScript::SelectWeaponAbility`.

**Comment by lynxlynxlynx** [comment]
Judging from the lack of animation jerks, I closed this. Technically it could still happen once when they actually switch between different weapons, but that's to be expected.
