### ISSUE TITLE
[bug]  Graphical glitch in Spellbook / Priestscroll in BG2

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#194]
**Description**
Removing memorized spells in the spellbook and priestscrolls in BG2 has a "flashing" animation. If removing multiple memorized spells, and then skimming to another spell level, I noticed remnants of these flashings flickering. It's a little hard to describe... Most noticeable if you recruit a new party member and edit their spells.

**GemRB version:**
0.8.5-git. I'm pretty sure I didn't have this issue prior to 0.8.5

**To Reproduce**
- load a BG2 savegame with a spellcaster in the party
- or start a new game, you'll have Imoen to test with
- open the spellcasters spellbook or priestscroll, and start removing their memorized spells at level 1, then proceed to the spell level 2, remove these spells as well, if necessary skim to higher spell levels. At some point you should notice the flickering if you turn a page

**Screenshot**
Tried uploading png and jpeg less than 1 MB in size, it won't work, sorry
EDIT: NoScript issue, works now
![screen_priestscroll](https://user-images.githubusercontent.com/54738589/64074906-bc2f3980-ccb1-11e9-8e76-061a6c666981.jpg)

**Comment by lynxlynxlynx** [comment]
Can confirm. The game has to be unpaused and it's visible at higher spell levels when the slot count is lower. So remove let's say the fifth level 1 memorization and move to level 5 if you have less available there and the looping flash will persist. Page turning or control disabling should kill any such animations.
