### ISSUE TITLE
 Turn undead has no effect on enemy undeads, but trying turn the caster.

### ISSUE THREAD

**Issue by Dreamkins** [gemrb/gemrb#1940]
#### Bug description
Turn undead has no effect on enemy undeads (no saving throws, no calls Actor::Turn), but the caster rolls saving throws and calls Actor::Turn on himself.

#### Screenshots
![Screenshot 2023-11-27 162041](https://github.com/gemrb/gemrb/assets/119408536/046e06bc-a3fc-4e45-adc0-6f06769939cd)
![Screenshot 2023-11-27 162019](https://github.com/gemrb/gemrb/assets/119408536/cf4d6d15-0210-49ff-8416-5606692a2679)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [x] 0.9.2

**Comment by lynxlynxlynx** [comment]
Like I said, it works fine for me, what's an exact way to reproduce?

**Comment by Dreamkins** [comment]
> Like I said, it works fine for me, what's an exact way to reproduce?

I take my paladin, turn on Turn Anded. I see that the paladin makes saving throws as in the screenshot. I put a breakpoint in Actor::Turn and see that the target is the paladin himself. I run into the crowd of skeletons and see that skeletons don’t throw save throws and there are none at Actor::Turn.

**Comment by lynxlynxlynx** [comment]
You know that turn undaed, like any other modal, runs once every round, not every tick or every second?

**Comment by Dreamkins** [comment]
I don’t understand at all how it can work for you if the only projectile it throws has the opcode 0x6e fx_turn_undead and the target is assigned with the line t
`arget = area->GetActorByGlobalID(Caster); `
which directly calls Astor::Turn on the paladin

**Comment by Dreamkins** [comment]
I recorded a video on the buildbot version https://streamable.com/71f4mb

**Comment by lynxlynxlynx** [comment]
I can reproduce now in bg1, which I guess is shipping different data for this than bg2. Not sure where it goes wrong — we provide the spell payload ourselves. I suspect inareans.pro is missing ...

**Comment by Dreamkins** [comment]
I'm very glad that I was able to prove this)

**Comment by Dreamkins** [comment]
Maybe this is the problem?
https://baldursgate.fandom.com/wiki/Turn_Undead
`Turn Undead is hard coded in the game engine. This makes it is difficult to see or analyze the inner workings of the code. Making modifications to hard coded parameters is also difficult and would require developer level access and source code.`

**Comment by lynxlynxlynx** [comment]
Not really, it's only an obstacle to better understanding; as far as the code and data goes, we've unhardcoded it. Turning works fine in bg2 since it has everything, in iwd since it uses inarea.pro instead (which we manually ship — but also means the useless extra feedback is printed) and similarly for iwd2.

What's curious is that just providing the projectile doesn't solve it for bg1, even though we have it registered from before.

**Comment by lynxlynxlynx** [comment]
There, the weaker version of turn undead is much better now, everywhere.
