### ISSUE TITLE
Agannazar's scorcher is drawn higher and does no damage

### ISSUE THREAD

**Issue by Dreamkins** [gemrb/gemrb#1943]
#### Bug description
Agannazar's scorcher is drawn higher (PSF_FLYING again) and does no damage (IWD at least)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [x] 0.9.2

**Comment by lynxlynxlynx** [comment]
Unlike in bg1 and bg2, the spell doesn't have a damage payload for some stupid reason, just the caster stun.

**Comment by lynxlynxlynx** [comment]
Finally this deep rabbit hole has been filled and all scorchers work as expected. We can do further tweaks to improve the drawing, which was suboptimal in the originals already (partly by design), but the rest is pretty sound.
