### ISSUE TITLE
 Find traps spell does not write anything and does not find anything.

### ISSUE THREAD

**Issue by Dreamkins** [gemrb/gemrb#1946]
#### Bug description
Find traps spell does not write anything and does not find anything (BG1).

GemRB version
- [x] master

**Comment by lynxlynxlynx** [comment]
works for me, tested in the final fight area. How many times do I have to ask you to provide exact reproduction steps?

**Comment by Dreamkins** [comment]
I recorded a video.
The spell has 31 effects with a frequency of 6 ticks (SPPR205.SPL). Apparently only the first effect works. In the first video, I cast the spell far from the traps and then approach them (what's with the strange message from the bats?)
https://streamable.com/4xiaxr

In the second video, I cast a spell next to the traps and then they are already there, which confirms that only 1 effect out of 30 works. (But the message from the bats is confusing)
https://streamable.com/var4p4

**Comment by lynxlynxlynx** [comment]
It's 6 seconds, not 6 ticks. But yes, I can see the followup applications don't succeed.
