### ISSUE TITLE
Dream cutscene freezes in BG2 at the moment with Sarevok.

### ISSUE THREAD

**Issue by Dreamkins** [gemrb/gemrb#1948]
#### Bug description
Dream cutscene freezes in BG2 at the moment with Sarevok.

#### Screenshots
![Screenshot 2023-11-28 134929](https://github.com/gemrb/gemrb/assets/119408536/114149d2-7e74-4e4b-b0e0-f0e208dc93f9)

GemRB version
- [x] master

**Comment by lynxlynxlynx** [comment]
Check the log and you should see useful errors and the name of the cutscene. Could again be a fixpack thing, but I don't see any obvious reference in the docs.

**Comment by Dreamkins** [comment]
Fixpack didn't help, the only interesting message in the logs is:
[GameScript/DEBUG]: CutSceneID was called by none!

**Comment by lynxlynxlynx** [comment]
That's not useful though. There are no broken dialogs? No errors, warnings? Which cutscene script is this ...

**Comment by Dreamkins** [comment]
I looked at the log from the start of loading the zone. This is AR0011.ARE, it has the script AR0011.BCS, which is not located and I don’t see it in near infinity either. But at the same time, characters move, dialogues are written, some script is launched.

**Comment by lynxlynxlynx** [comment]
Ok, thanks, I can reproduce that by manually invoking cut28a. As a workaround, you can just EndCutSceneMode() in the console manually and talk to him, finishing the dream. Unclear yet when things go wrong.
