### ISSUE TITLE
 IWD2 Actor::IsDead() return true on live PC

### ISSUE THREAD

**Issue by Dreamkins** [gemrb/gemrb#1949]
#### Bug description
IWD2 Actor::IsDead() return true on live PC, flag IF_IDLE is set.

- [x] master

**Comment by lynxlynxlynx** [comment]
So what? Besides clearly having a suboptimal name, you haven't presented an actual issue.

**Comment by Dreamkins** [comment]
Perhaps this is not a problem within the framework of pure gemrb. But I'm writing a mod with a turn based combat and I need to check whether the character is alive or not. This function is supposed to return this status, but in IWD2 it returns true for living characters. Perhaps I should have asked you directly about this rather than creating an issue, but where should I do this?

**Comment by lynxlynxlynx** [comment]
`GetStat(IE_STATE_ID) & STATE_DEAD` is the traditional approach and also what the Dead trigger checks.

**Comment by Dreamkins** [comment]
Thanks

**Comment by lynxlynxlynx** [comment]
Btw, I'm not sure what exactly you want to do, but each actor has their own combat round. Besides that, some stats and weapons affect the speed of attacking, so that's a sort of initiative delay. You can get very close to turn based combat by enabling the autopause option for end of round.

**Comment by Dreamkins** [comment]
Turn-based combat is always a convention. For now I'm just ignoring weapon speed. I recorded a video, you can see what it looks like now. https://streamable.com/nr7voq
