### ISSUE TITLE
[bug]  looping foe attack sound in bg1 + toswc

### ISSUE THREAD

**Issue by fogobogo** [gemrb/gemrb#195]
The first enemy encountered during the tutorial stage repeats "crush your face i will" endlessly until the battle ended. He's located in a housing north (top edge of the starting map) to the players starting location right after an NPC hint about opening and entering doors.

**Comment by lynxlynxlynx** [comment]
It should be a simple scripting bug. Shank from ar2602 only has wtasight.bcs and it appears we keep hitting the third block instead of the second one already (or AttackReevaluate has a problem):
```
IF
  AttackedBy([GOODCUTOFF],DEFAULT)
  Allegiance(Myself,NEUTRAL)
THEN
  RESPONSE #100
    Enemy()
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
  AttackedBy([ANYONE],DEFAULT)
THEN
  RESPONSE #100
    Attack(LastAttackerOf(Myself))
END
```

**Comment by caillean7** [comment]
Don't know if this is important, but I noticed these repeating battle cries also for in-party characters in BG2, not only enemies

**Comment by lynxlynxlynx** [comment]
It's the same verbal constant (well usually, they really complicated this with half-implemented animation hacks), entries of the character sounds list.
