### ISSUE TITLE
Crash in WorldMap: worldmap->GetMapMOS() returns null

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#1952]
At some point, the world map in IWD began to crash. I can’t figure it out, there’s a problem somewhere in Python. Look at the save if possible. Just open the world map and it will crash.
[000000001-Quick-Save.zip](https://github.com/gemrb/gemrb/files/13522507/000000001-Quick-Save.zip)

_Originally posted by @Dreamkins in https://github.com/gemrb/gemrb/issues/1938#issuecomment-1835578038_

**Comment by bradallred** [comment]
I can replicate the issue with the attached save. However, there are no Python errors. It is a matter of the `WorldMap::MapMOS` member being `nullptr`. Not sure why that might be.

**Comment by bradallred** [comment]
ah, from the log:

```
[ResourceManager] Couldn't find 'WMAP1'... Tried WMAP1.png WMAP1.mos WMAP1.pvrz WMAP1.bmp
[WMPImporter] Worldmap image not found.
```

**Comment by lynxlynxlynx** [comment]
Err, why is it looking up that file in particular? In all three subgames I see GUIMAPWB.mos, no mention of WMAP1. Maybe I'm looking at the wrong line in the log, but there's definitely no WMAP1 anywhere.

**Comment by Dreamkins** [comment]
I get WORLDMAP.wmp and EXPMAP.wmp from another save and it worked again. Someone change it.

**Comment by lynxlynxlynx** [comment]
Nothing changed related to worldmaps recently and the background used is baked in the game data. So I guess one of your memory problems managed to corrupt the worldmap in the save game.

**Comment by lynxlynxlynx** [comment]
Yeah, the worldmaps in the save are all sorts of busted, now that inspected them. I've made our reliance on the bg image forceful, since it doesn't make sense to check for it everywhere else.
