### ISSUE TITLE
Fear action RunAwayFromNoInterruptNoLeaveArea block actors personal script.

### ISSUE THREAD

**Issue by Dreamkins** [gemrb/gemrb#1954]
#### Bug description
Fear action RunAwayFromNoInterruptNoLeaveArea block actors personal script. (IWD)

#### Steps to reproduce
1. Cast fear on troll.
2. Try kill troll
3. Troll don't fall on ground.

#### Expected behavior
Troll must execute script with PlayDead(600) and enable variable to kill him with acid or fire.

GemRB version
- [x] master as of this issue

**Comment by Dreamkins** [comment]
In general, everything is complicated with trolls. They regenerate while dead. If you kill the trolls, then save and load, they will get up. The death animation immediately continues with another animation because that's how it's written (the character is expected to die, but trolls don't die). If you remove the continuation of the death animation, then the death animation will be looped, since A_ANI_PLAYONCE is not checked at EndReached. This is all in IWD, but most likely it is the same in other games.

**Comment by lynxlynxlynx** [comment]
Trolls are different in pretty much every game, with a different mechanic to have the special vulnerability.
