### ISSUE TITLE
 Portrait panel start minimized and toggle on quick load

### ISSUE THREAD

**Issue by Dreamkins** [gemrb/gemrb#1957]
#### Bug description
Portrait panel start minimized and toggle on quick load (IWD/BG2 least). 

#### Expected behavior
Portrait panel start maximized and do not toggle on quick load.

GemRB version
- [x] master as of this issue

**Comment by lynxlynxlynx** [comment]
Quick load is a thing, ok, wow. Apparenly L as the hotkey. `QuickLoadPressed` maybe needs a bit more setup done that's otherwise in Game.py.

**Comment by Dreamkins** [comment]
Is the window in Minimize by default ok? I actually thought it was a bug at first. How can it be maximized on a tablet?

**Comment by lynxlynxlynx** [comment]
It's not fully hidden, you still have a bit of it left to click on and expand. We need to check if the original behaved any differently for quick loading, but the sane thing is of course to maintain the same GUI state.

**Comment by bradallred** [comment]
the GUI state is supposed to be saved in the save, but we probably only initialize it on the first save load or something. There is a hot key to minimize/maximize them.

```
Hide_Interface        CommonWindow     ToggleGUIHidden                   0
Right_Interface       GUICommonWindows PortraitWinToggle                 0
Left_Interface        GUICommonWindows OptionsWinToggle                  0
```

you'd have to match those up with the keycap.ini from the game directory to see the keys.

**Comment by lynxlynxlynx** [comment]
I don't see any toggling when trying quick loading. In iwd1 there's no buttons, neither the hotkeys (Y/U) seem to be wired. In bg2 the fully sized state is restored on quick load (but it didn't work in tob). Is this reproducible for you?
