### ISSUE TITLE
Spells from scrolls not worked 

### ISSUE THREAD

**Issue by Dreamkins** [gemrb/gemrb#1958]
#### Bug description
Spells from scrolls not worked (IWD least)

Acton is null. Point spell similar.
![Screenshot 2023-12-07 114811](https://github.com/gemrb/gemrb/assets/119408536/c94a99fa-dbe1-457e-8596-b7d42eb4a693)

If action not null then action will be removed. May be It's better to swap these lines.
![Screenshot 2023-12-07 114843](https://github.com/gemrb/gemrb/assets/119408536/5e30ab77-3dfe-4381-8f86-a158d752bee3)

GemRB version (check as many as you know apply)
- [x] master as of this issue

**Comment by lynxlynxlynx** [comment]
We need to add ForceSpellRes to our gemaction.ids for pst and iwd1, I didn't notice they don't have it. Or use it stealthily, by using ForceSpell directly.

And good catch with UseItem as well, thanks!

**Comment by Dreamkins** [comment]
> We need to add ForceSpellRes to our gemaction.ids for pst and iwd1, I didn't notice they don't have it.

I added them, but the parser misses the first letter here
```
			case 's': //String
			{
				SKIP_ARGUMENT();
				src++;
```
You can comment out src++; and then it works, but won't it affect something else?
