### ISSUE TITLE
 Allow modifying the SDL_HINT_RENDER_SCALE_QUALITY

### ISSUE THREAD

**Issue by zebez** [gemrb/gemrb#1973]
Allow modifying the [SDL_HINT_RENDER_SCALE_QUALITY](https://wiki.libsdl.org/SDL2/SDL_HINT_RENDER_SCALE_QUALITY) setting to nearest/linear via config file.

I run a desktop resolution of 3440x1440, and 480x3 should look pixelperfect at fullscreen but it looks kinda blurry for BG1.

**Comment by bradallred** [comment]
does it actually improve for you when you change it from "best" to one of the other modes?

**Comment by bsdcode** [comment]
I also have a 3440x1440 monitor and I tested the resolutions
```
640x480 (x3)
800x600
1024x720 (x2)
1024x768
1280x960 (x1.5)
3440x1440 (x1)
```
with the three quality values. In my perception the values `linear` and `best` don't make a difference from each other. But `nearest` definitely provides a less blurry picture, at the cost of more pixelation. At the lower resolutions I can totally understand if someone prefers the non-filtered, not blurry picture. Now that I have seen the difference I cannot __unsee__ it anymore and would much prefer the `nearest` setting for anything below 960. For the higher resolutions 960 and 1440 it's not as noticeable (of course with 1440 you don't see anything anyway ;) ).

Would such an option be located in GemRB.cfg?
