### ISSUE TITLE
[bug] BG2 better Horror Spell - terrified face  graphic effect covers NPCs and their circles

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#198]
When fear spell is cast the terrified face graphic spell effect covers the NPC and the circle underneath him/her. It makes difficult for go about and click on your or hostile npcs because you don't see on which one you click. In below picture there at least 4 hostile doppelgangers but only one red circle is even barely visible. Thanks for fixing combat the voices for creatures. :=D

![fear](https://user-images.githubusercontent.com/17316115/64144318-fe579880-cde1-11e9-8da2-703dec8ea80b.jpg)
![fear2](https://user-images.githubusercontent.com/17316115/64144321-01528900-cde2-11e9-8ed5-fe5cfc7053e3.jpg)

**Comment by lynxlynxlynx** [comment]
How did it look in the original? Was it drawn behind actors?

**Comment by caillean7** [comment]
I just checked  with EE (don't have any wine installation of the classic BG2 right now), and it looks like it depends how close the enemy is standing to that face thingy. They're covered up when the spell is cast directly at them. Most important
![screen1](https://user-images.githubusercontent.com/54738589/64172796-123ce200-ce56-11e9-86a3-2d24d6057a38.jpeg)
![screen2](https://user-images.githubusercontent.com/54738589/64172800-149f3c00-ce56-11e9-8140-da9b975b42f1.jpeg)

 however, I tried several times casting Horror at some crowd, and it only ever drew one face where the spell was pointed, while GemRB seems to draw one for every affected critter.

**Comment by lynxlynxlynx** [comment]
Thanks. The occlusion seems a bit random, on the top pic even the background is occluding it. But we can at least fix the multiface problem. The projectile Horror is using was hardcoded in other games, except for bg2, so it's not a problem of our data, at least not in bg2. But it's clear what's wrong, we are drawing the face for each child projectile, not just at the target.

@cygarniczka are you also talking about Horror or does Fear have the same problem?

**Comment by cygarniczka** [comment]
I view multiface as a new feature. Maybe make it more transparent? 
@lynxlynxlynx - Yes the horror lvl 2 spell. I used incorrect name I thought that spell was called Fear. I don't think fear effect which is used in horror spell has this problem. It only happened to be when horror spell was used.

**Comment by lynxlynxlynx** [comment]
Ok.
Actually the other games should have the same problem, as our fx_play_visual_effect doesn't differentiate between two of the possible values of a parameter.
