### ISSUE TITLE
JDungeon GemRB Support (Godot 4.NET MMORPG) 

### ISSUE THREAD

**Issue by WithinAmnesia** [gemrb/gemrb#1981]
https://github.com/jonathaneeckhout/jdungeon
Please give JDungeon a review. JDungeon is a Godot 4.NET MMORPG that has an excellent core. It is BSD 2-Clause License open source. Imagine how good of games could be made with GemRB features with Godot 4.NET networking MMORPG features of JDungeon. It is an excellent developing opportunity.

**Comment by MarcelHB** [comment]
> Imagine how good of games could be made with GemRB features with Godot 4.NET networking MMORPG features of JDungeon. It is an excellent developing opportunity.

Then just maybe play JDungeon? It's apparently there, it has contributors, it's working. Don't see what's the point of integrating a non-IE game here.

We had the MP discussion, if that's what you trying to sneak into again. And we told you: feel free, we have other focuses and time budgets. And you cloaked saying: no, no, I don't want to do the work.

**Comment by WithinAmnesia** [comment]
It's good to have multiple field or types of experiences too. There are many similar ways to do the same thing and also working on multiple games of various engines and types and coding languages and tool sets has taught me its good to try different things especially if there is new feature knowledge or something to be learned or special about a project.

What is special about JDungeon is the networking and the MMORPG core that works with open source online Godot 4.NET which can used to play together with both single player and multiplayer like with many popular classic RPGs. I'd like to add that Baldur's Gate 1 and Baldur's Gate 2 on other Infinite Engine games supported online play and BG1 was first hoped to be an MMORPG. Diablo 1&2 have online play, all of the Warcraft games have online multiplayer and most classic older games that lasted a long time had online multiplayer support. So in order to do networking effectively as a community it seems Godot 4.NET is a very good option for its open source and widely used and documented and improving as well.

If anyone wants to learn multiplayer work or is curious its really good to try new things and tinker around. World of Warcraft for example is great to learn online features adding content to private servers but its closed source and not great legally but with Godot 4.NET with JDungeon there are very similar opportunities to learn and grow as a developer but its going to need some extra work at the start. Any game made with JDungeon can be made commercially too. So it can support game developer work too and also its online which everything is better with friends.
