### ISSUE TITLE
Stoneskin changes dialog name color

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1982]
#### Bug description
Iron skin and probably others too.

(Also dialog lines colors are different, grey vs blue. Not sure if it's intentional?)

#### Steps to reproduce
1. Cast stoneskin
2. Select/command the character.

#### Expected behavior
Character name using main character color.

#### Screenshots
BG2 (switched Imoen's color to red for more contrast)
![Captura desde 2024-02-07 04-11-11](https://github.com/gemrb/gemrb/assets/1279852/059eee80-7b44-43bd-972e-2864d0fa47c4)

Gemrb, after casting stoneskin color changed.
![Captura desde 2024-02-07 04-11-37](https://github.com/gemrb/gemrb/assets/1279852/9a93fadd-1740-498f-9f0d-db3bbe2a0299)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Yes, we compute the name color instead of hardcoding it (IIRC the original had a fixed-sized list to pick from). It takes the color stats into account, so when effects change them, it shows.

How did you switch the color in the original?

**Comment by burner1024** [comment]
The normal UI 
![1](https://github.com/gemrb/gemrb/assets/1279852/4c0a9975-8d46-4dd9-a257-72baa9a19bd1)

I probably wouldn't mind dynamic name color, but the issue is that later in game many of the characters are stoneskinned, and the dialog window starts to look really bland and hard to distinguish who says what.
![Captura desde 2024-02-07 03-58-01](https://github.com/gemrb/gemrb/assets/1279852/685feb58-2e8d-4328-b323-50bdd39f0f2e)

Also the light grey text color doesn't help when names are grey too. Is that intentional, after all?

**Comment by lynxlynxlynx** [comment]
Ok, so it's the major color. As for the grey, I don't know, but that's configurable already (probably DIALOG in colors.2da).

**Comment by burner1024** [comment]
I tried changing DIALOG and DIALOG_PARTY, that works when in dialog mode, but has no effect in "world" mode, basically selection sounds are always white/light grey. Should I file a separate issue about that?

**Comment by lynxlynxlynx** [comment]
I guess it's using WHITE then. That's another todo for colors.2da — get rid of the color entries, since they don't tell you where they are used, and replace them with "functional" ones.

This way is more dynamic. 1PP has to patch the exe to work around it. It's a simple matter of looking up the base stat instead of the one modified by effects.
