### ISSUE TITLE
 USE_OPENGL_BACKEND vs OPENGL_BACKEND

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1985]
#### Bug description
```
cmake .. -DCMAKE_INSTALL_PREFIX=/opt/gemrb -DUSE_OPENGL_BACKEND=true
-- The C compiler identification is GNU 11.4.0
...
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    USE_OPENGL_BACKEND
```

`USE_OPENGL_BACKEND` flag seems to be replaced by `OPENGL_BACKEND=OpenGL`? But the former is still referenced here and there.
Or am I reading it wrong? Then why cmake throws a warning?

#### Steps to reproduce
1. Launch cmake as above.

#### Expected behavior
No warning.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
It's defined in `gemrb/plugins/SDLVideo/CMakeLists.txt:13`. What does need changing is the bug reporting template, since it should mention OPENGL_BACKEND instead.

**Comment by burner1024** [comment]
Still, why the warning?

**Comment by lynxlynxlynx** [comment]
It's a cmake thing. I guess because you're defining a cmake var that way, not a c++ macro. IOW it's not something that gets forwarded to the c++ preprocessor.

**Comment by burner1024** [comment]
Is `OPENGL_BACKEND` supposed to imply `USE_OPENGL_BACKEND`? Then what use is `USE_OPENGL_BACKEND`, shouldn't it be removed?

**Comment by lynxlynxlynx** [comment]
Yes, it shouldn't be defined manually.
