### ISSUE TITLE
Can't launch in full screen 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1989]
#### Bug description
This is probably something stupid on my part, but... can't get the game to start in full screen.
```bash
$ grep -i "full screen" *baldur.ini
baldur.ini:Full Screen=1
gem-baldur.ini:Full Screen = 1

$ grep -i "fullscreen" ~/games/GemRB-bg2-test.cfg 
#Fullscreen [Boolean]
Fullscreen=1

$ /opt/gemrb/bin/gemrb -c ~/games/GemRB-bg2-test.cfg
# launches windowed
```

Then Ctrl-F switches to full screen just fine.

#### Steps to reproduce
1. Set full screen = 1 in all inis and cfgs.
2. Launch the game.

#### Expected behavior
Launched in full screen.

#### Screenshots

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Wrong key in `gemrb/core/Interface.cpp:370`. I think we should just retire the cfg key instead, as everything else relies on the ini version (name) and that's also what toggling it ingame changes.

If not, we need another lookup, so both options would work.

**Comment by burner1024** [comment]
It is kinda confusing to have two.

Maybe also save the last value in gem-baldur.ini?
Clicking 
![Captura desde 2024-02-10 00-10-13](https://github.com/gemrb/gemrb/assets/1279852/8a6c238a-9d93-4def-934d-6cd94c7af596)
immediately switches between full screen and windowed.

But switching with CTRL-F on the same page does not toggle the option.

**Comment by burner1024** [comment]
#1990 actually will fix this as well. At least the proper startup mode.

I don't think the value from GemRB.cfg is used anywhere. It can probably be retired, and I think it would be consistent if CTRL-F also set and saved the option in gem-baldur.ini.

**Comment by burner1024** [comment]
OK, actually `Fullscreen` appears to be used in some other places:
```bash
$ grep -R Fullscreen *
...
platforms/vita/README.Vita.md:Use "Fullscreen=1" to scale game area to native Vita resolution or "Fullscreen=0" to keep game area at the center of the screen.
platforms/vita/GemRB.cpp:		if (VideoDriver->GetFullscreenMode()) {
platforms/apple/ios/GemRB.cfg.newinstall:#Fullscreen [Boolean]
platforms/apple/ios/GemRB.cfg.newinstall:Fullscreen=1
platforms/apple/defaults.plist:	<key>Fullscreen</key>
platforms/apple/CocoaWrapper/mac/nibs/GemRB.xib:                                        <binding destination="882" name="value" keyPath="values.Fullscreen" id="993"/>
```

I think with #1990 merged Vita will use value from ini, so readme will need to be update to reflect that.

And as for apple I'm not even sure what are these plist and xib files.

**Comment by lynxlynxlynx** [comment]
Their version of the cfg.

**Comment by burner1024** [comment]
So what do you want to do? Retire it after all?

**Comment by lynxlynxlynx** [comment]
Yes, the launcher can set the same game var we use from the ini. If we want to keep it there at all — I think it's better to  retire that part of the GUI as well. It's just a checkbox: https://user-images.githubusercontent.com/1126744/67640031-ffc2b000-f8bc-11e9-81c1-e6a37571b634.png
