### ISSUE TITLE
[bug] GameControl doesn't clear when leaving the game

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#199]
**Describe the bug**
I almost don't want to report this because its kind of neat:

If you load a game then quit back to the main menu the `GameControl` isn't cleared. If you are playing at a resolution that lacks window border assets (in this case BG2 @ 1400x768) you can easily see this.

Probably the best way to fix this would be to destroy `GameControl` when you leave the game. That way there are no possible lingering states that could bork loading a new game.

It looks like currently we disable `GameControl` in `Interface::HandleFlags`, but we should probably destroy it instead.

GemRB version: subviews

**To Reproduce**
1. start a game at a resolution that has no window border assets.
2. load a game
3. exit back to main menu

**Expected behavior**
The `GameControl` should be cleared.

**Screenshots**
![image](https://user-images.githubusercontent.com/1126744/64222441-513a5a00-ce8d-11e9-8baf-386f3c50fb62.png)

**Comment by bradallred** [comment]
My suggested fix isn't quite good enough. I can clear it when leaving the game well enough, but when you load a new game (use a different save to see this) the old area is drawn briefly. Since I am deleting and recreating the `GameControl` there is no way this is a drawing issue. I don't think we are clearing the area (and probably other data) like we should.

I think that might need to be a separate issue... I'm not exactly sure what we need to clear. I'm also not sure if master has this issue too.

**Comment by MarcelHB** [comment]
I'm not really sure if this is related, but I had tested this branch a few days ago on a FullHD setup for PST. What I observed: You load a game, and then you load the game again. The controls look fully enabled, and you can somewhat interact with the screen, but the visually drawn area remains covered under FoW without any PC actors being drawn.

**Comment by bradallred** [comment]
@MarcelHB it sounds like yes, you are seeing this artifact, but also probably encountering some other error (GUIScript error?).

I was mistaken about it not being a drawing issue. For performance reasons the game window doesn't get blanked out, so the window buffer itself had the last thing painted on it and we show the window before the game/area is loaded so you see that.

I'm pushing up a fix shortly, so maybe see what the new behavior is after and we can open a new issue for whatever you are seeing.
