### ISSUE TITLE
Reverbation should not apply to all sounds 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1993]
#### Bug description
It seems that reverbation applies to all sounds.
It shouldn't apply at least to:
- inventory sounds (moving stuff around)
- interface sounds (clicking buttons and stuff)

#### Steps to reproduce
1. Start a new BG2 game.
2. Click on any interface button: options, record, etc. Move some stuff in inventory.

#### Expected behavior
No reverbation for inventory sounds, interface sounds.
Not sure what kinds/channels are else there. It definitely should apply to ambients, voices.

#### Screenshots

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by burner1024** [comment]
Reverbation remains even after you exit from game to main menu.

**Comment by lynxlynxlynx** [comment]
We can probably get away with limiting it to certain sound channels, ie. not using it for SFX_CHAN_GUI and SFX_CHAN_NARRATOR.
