### ISSUE TITLE
IWD: missing fire elemental animation sometimes

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#1999]
#### Bug description
In IWD1, polymorph to fire elemental in initial area and spot (no moving after game start) just disappears the PC.

If you walk around first, it works. Something about angle or space, probably.

[1.zip](https://github.com/gemrb/gemrb/files/14335902/1.zip)

```
[GUIScript]: Cast spell: SPIN141
[GUIScript]: Slot: 3
[GUIScript]: Type: 2 (4 vs 4)
[GUIScript]: Spellname: Shapeshifts Fire Elemental
[GUIScript]: Target: 5
[GUIScript]: Range: 1
[ResourceManager]: Found 'DruidFE.cre' in 'chitin.key'.
[ResourceManager]: Found 'GNSUMMM.bcs' in 'chitin.key'.
[Actor]: No moverate.2da found, using animation (0xe228) for speed fallback!
[Actor]: No moverate.2da found, using animation (0xe228) for speed fallback!
[ResourceManager/ERROR]: Couldn't find 'MELFcae.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: MELFcae (0xe220)
[ResourceManager/ERROR]: Couldn't find 'MELFcae.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: MELFcae (0xe220)
[ResourceManager/ERROR]: Couldn't find 'MELFcae.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: MELFcae (0xe220)
[ResourceManager/ERROR]: Couldn't find 'MELFcae.bam'.
```

#### Steps to reproduce
1. Load game (or just start a new druid importing DRUID+).
2. Polymorph to fire elemental.
3. See no avatar.

#### Expected behavior
Working spell.

#### Screenshots
![Captura desde 2024-02-20 01-30-28](https://github.com/gemrb/gemrb/assets/1279852/43e3495e-2afa-422b-b942-500d7a7fae23)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
You have HoW, right? Who gets that innate?

**Comment by burner1024** [comment]
Yes, it's GoG version.
Initial druid (+DRUID in import list).

**Comment by lynxlynxlynx** [comment]
Ah, you're overleveled, now I see. Looks like it's another simplified animation, though I thought the CA suffix is for casting.
