### ISSUE TITLE
IWD: pathfinding fails to find path 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#2000]
#### Bug description
In initial area, fire elemental doesn't fit in a lot of corners.

```
[FindPath/DEBUG]: Ilauna can't fit in destination
[WalkTo/DEBUG]: Ilauna re-pathing ignoring actors
[FindPath/DEBUG]: Ilauna can't fit in destination
```

#### Steps to reproduce
1. Start a new druid.
2. Shift to fire elemental.
3. Try to walk to the top left corner.

#### Expected behavior
Being able to walk around kill everyone in the initial area.

#### Screenshots
Original
![Captura desde 2024-02-20 01-44-02](https://github.com/gemrb/gemrb/assets/1279852/03399b50-af63-4c67-b0b2-fcdfac55d3ad)

GemRB
![Captura desde 2024-02-20 01-31-13](https://github.com/gemrb/gemrb/assets/1279852/7827c8e3-d043-4bd1-8891-cfad5281a538)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Not fixing this, it doesn't make sense comparing the searchmap and the animation size.
