### ISSUE TITLE
Options menu in SoA flips to ToB 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#2003]
#### Bug description
Options menu in SoA shows ToB art.

#### Steps to reproduce
1. Launch game.
2. Select SoA
3. Click on "Options"

#### Expected behavior
Center art should keep SoA logo in SoA campaign.

Additionally, it's missing GemRB version at the bottom, which I think is not intended, given that it's present on all other menu screens?

#### Screenshots
Original

![Captura desde 2024-02-20 16-16-40](https://github.com/gemrb/gemrb/assets/1279852/f2305d30-ebeb-4f7f-a917-e4b31fba79a7)

GemRB

![Captura desde 2024-02-20 16-20-24](https://github.com/gemrb/gemrb/assets/1279852/988d8bf8-0666-4417-b696-28e7cb43f1ff)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `USE_OPENGL_BACKEND`
- [ ] SDL2 without `USE_OPENGL_BACKEND`

**Comment by lynxlynxlynx** [comment]
Should be a simple fix in GUIOPT.py and SetBAM or one of the other button methods.

**Comment by bradallred** [comment]
I think the LoadScreen has a similar issue

**Comment by burner1024** [comment]
I have checked LoadScreen and actually original ToB uses ToB art when loading SoA games.
I guess restoring SoA logo would be a nice addition, if you want to do that.
I vaguely recall that there might've been a mod that did that... or not?
