### ISSUE TITLE
 BG1: Big delay by loading single player main menu when using Game Text Update by Baldurdash

### ISSUE THREAD

**Issue by bsdcode** [gemrb/gemrb#2005]
#### Bug description
I use the original german 5-disc-set version of Baldur's Gate 1 with the `dialog.tlk` replaced by Baldurdash's Game Text Update `dialog.tlk`. When I start gemrb and click "single player" in the main menu then there's a delay of ~24s before the program continues to show the next main menu screen. The log shows
```
[Streams/ERROR]: Invalid seek position 1093201284 in file dialog.tlk (limit: 3100217)
```
The program probably tries to scan through this or more files before it continues.
It doesn't happen with the original `dialog.tlk`. It also doesn't happen with the 0.9.2 release version.

#### Steps to reproduce
1. Replace `dialog.tlk` with Baldurdash's Game Text Update
2. Start gemrb
3. Click "Single Player"
4. Experience long delay before it continues

#### Expected behavior
No delay.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
Sounds like a mod data problem, but we should be more resilient.

**Comment by lynxlynxlynx** [comment]
BTW, the G3 Fixpack has the latest GTU.
Does Baldurdash have a German GTU? If not, that could explain wrong strings, but I don't see how it could cause any issues that aren't just display related — unless the file is malformed.

**Comment by bsdcode** [comment]
No it doesn't have a German GTU.

The cause of the big delay is a huge returned string length `l`, about ~1.5GB. And this big `mbstr` then wants to be converted to StringView in `StringFromTLK`'s constructor.

**Comment by bsdcode** [comment]
Is the G3 Fixpack also applicable to BG1? If so I would be happy to try it.

**Comment by bsdcode** [comment]
It's the StringRef `24110`. NI shows "No such index".

**Comment by lynxlynxlynx** [comment]
In the official bg1 that's "mission pack" for its menu button (the shipped save at the start of TotSC). But that suggests indeed that the file is corrupted.

**Comment by bsdcode** [comment]
It should actually be the version without TotSc, because, unfortunatly, I do not have the TotSc (should finally buy the complete package from GOG).

Hmm, guess I doublecheck the file again and try to redownload it.

**Comment by lynxlynxlynx** [comment]
Oh, that would explain it then, since we manually add the text to the button. I'll fix it.

**Comment by bsdcode** [comment]
I can confirm this prevents the invalid seek.

But now we have a greyed out MOVIES text in the single player menu which shouldn't be there:

![menu](https://github.com/gemrb/gemrb/assets/155195419/0454e95d-fca8-43b3-9d13-00f57caf95fd)
