### ISSUE TITLE
 BG1: Placement of "Back"-button in "Single Player" main menu is wrong

### ISSUE THREAD

**Issue by bsdcode** [gemrb/gemrb#2006]
#### Bug description
The "Back"-button in the main menu is aligned at the bottom. It should be placed directly under the "Load Game"-button.

#### Expected behavior
"Back"-button correctly placed.

#### Screenshots
![bg1_wine](https://github.com/gemrb/gemrb/assets/155195419/0d9edf9a-d3c8-4b17-b697-a405497ff790)
![bg1_gemrb](https://github.com/gemrb/gemrb/assets/155195419/cc5f8e86-12a3-48e4-b744-69ce0cd802bb)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
What do others think? I'd close it as wontfix, since it's a better user experience this way.

**Comment by lynxlynxlynx** [comment]
Ok. :)
