### ISSUE TITLE
 BG1: Voice selection shows only the default voice in the character creation

### ISSUE THREAD

**Issue by bsdcode** [gemrb/gemrb#2007]
#### Bug description
Window to choose the character's voice only shows the default entry.
(And the inactive window in the back should actually be darker than the active foreground voice selection window).

#### Expected behavior
Window shows all available voices.

#### Screenshots
![bg1_wine](https://github.com/gemrb/gemrb/assets/155195419/baa18eca-2f60-4e0e-8c28-aa67eb23ab1c)

![bg1_gemrb](https://github.com/gemrb/gemrb/assets/155195419/8f467a4f-ba4b-4c9a-9898-ff7b2d360699)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
Thanks, can reproduce — it's not a German-related problem.

**Comment by burner1024** [comment]
And the "play" volume is soooo low. At first I thought it didn't play at all.

**Comment by burner1024** [comment]
Try loading a save first, the exiting to main menu and starting new one.

**Comment by bsdcode** [comment]
Yes. Can reproduce this way.

**Comment by bsdcode** [comment]
I haven't looked deeper, but maybe something is wrong here regarding the volume problem:

https://github.com/gemrb/gemrb/blob/253e06cac9eb8247e101235198442278bfda422d/gemrb/GUIScripts/bg1/GUICG19.py#L80-L81

**Comment by burner1024** [comment]
Might be same as this https://github.com/gemrb/gemrb/issues/1993#issuecomment-1962349636... sound system appears to have some sort of lingering.

**Comment by bsdcode** [comment]
Missing voices in list:

https://github.com/gemrb/gemrb/blob/253e06cac9eb8247e101235198442278bfda422d/gemrb/plugins/GUIScript/GUIScript.cpp#L4686

borks `dirit` somehow. I'm investigating.

**Comment by lynxlynxlynx** [comment]
I don't see anything in valgrind, so it's less ominous than you make it sound. You could just bisect it, without giving it much thought, since it did work at the time of the last release.

**Comment by bsdcode** [comment]
The predicate `EndsWithFilter` does have problems in finding files, because the `stricmp` compares the filterstring `A` with the complete `fname.length - fpos` last part of the tested filename:

https://github.com/gemrb/gemrb/blob/311f1ff08f3ecf8163f4f5a6af94580e83977509/gemrb/core/System/FileFilters.h#L66

We need to replace with `strnicmp(endMatch.data(), &fname[fpos], endMatch.length())`. I'll do the PR.

**Comment by bsdcode** [comment]
And yes, it broke with the last change ~7 month ago ;)

**Comment by MarcelHB** [comment]
> Might be same as this [#1993 (comment)](https://github.com/gemrb/gemrb/issues/1993#issuecomment-1962349636)... sound system appears to have some sort of lingering. Maybe #2008 too.

Went through some sound bugs today, and no, they are not related. Will open a new issue for this.
