### ISSUE TITLE
BG1: New game is missing intro text

### ISSUE THREAD

**Issue by bsdcode** [gemrb/gemrb#2009]
#### Bug description
When starting a new game you start outside Candlekeep Inn and you should see an intro text in the text panel. With GemRB it isn't there.

#### Expected behavior
Intro text is there.

#### Screenshots
![bg1_wine](https://github.com/gemrb/gemrb/assets/155195419/45e3e3f6-7fb2-4e13-8727-121aeef3629d)

![bg1_gemrb](https://github.com/gemrb/gemrb/assets/155195419/8c6abe58-be72-4113-a89d-bb48df1de8b7)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
That's trivial to add in bg1's Game.py or somesuch. We can also fix the color of GOT_GOLD .

**Comment by bsdcode** [comment]
Ok, with the help from NearInfinity I found the StrRef number for the text: `16214`. Now I need to find the right place to do a `DisplayString` with it. Looking through share/GUIScripts/bg1...

**Comment by lynxlynxlynx** [comment]
Actually gemrb/GUIScripts/bg1/Start.py might be a better place than Game.py; if it works there after the LoadGame (in NewSingle), that's a one-liner. Otherwise we'd need extra logic to display it only once.

**Comment by bsdcode** [comment]
Yeah, doesn't work in NewSingle form Start.py. At this point we haven't even loaded the character creation screen.

It works when putting `GemRB.DisplayString(16214, ColorWhite)` after `MessageWindow.OnLoad()` in Game.py. Of course it also displays when loading a saved game, so we must restrict it to a new game. According to Near Infinity the original script checks the chapter number and displays this message only when it's still chapter 0. Maybe we can do a similar check?

**Comment by lynxlynxlynx** [comment]
Ah, it was scripted in the area script. Then we run that script already and shouldn't duplicate it. I guess the intro story screen resets Chapter to a higher number already, so when the area script runs again, the block doesn't execute:
```
IF
  Global("Chapter","GLOBAL",-1)
THEN
  RESPONSE #100
    IncrementChapter("Chptxt0")
    DisplayString(Myself,16214)
    Continue()
END
```

Maybe not pausing during that screen would avoid it.

**Comment by bsdcode** [comment]
Setting `GemRB.GamePause (0, 3)` in gemrb/GUIScripts/TextScreen.py doesn't help.

According to the log, `AR2600.bcs` is definitly loaded after `EnterGame()` in gemrb/GUIScripts/bg1/Game.py. I put a `print(GemRB.GetGameVar("CHAPTER"))` in `EnterGame()` in order to see how this value is initialized. It's `4294967295`, either UINT32_MAX or (int32_t)-1.

So one question is, if the script handles the signedness correctly?

Second question is, if that's actually the real initialized value or does GemRB initialize it to 0 before executing scripts? Because at least in the beginning of `StartTextScreen` in TextScreen.py the chapter value is 0.

**Comment by bsdcode** [comment]
Wait, I played around with AR2600.bcs, deleted the `IncrementChapter("Chptxt0")` and logged in gemrb/core/Game.cpp's `Game::IncrementChapter`. It doesn't fire. So the script IS executed. The chapter value is correct.

So it seems the `DisplayString(Myself, 16214)` in the script is not working correctly.

**Comment by lynxlynxlynx** [comment]
Why not just break on DisplayString directly?

**Comment by bsdcode** [comment]
Yes it's the next step. I try differnt things to get to know the codebase better.

We are entering `DisplayStringCore` in gemrb/core/GameScript/GSUtils.cpp:460 without DS_CONSOLE in the flags. When I add it manually then the text shows up in the console.

**Comment by bsdcode** [comment]
The calling context is `GameScript::DisplayString` in gemrb/core/GameScript/Actions.cpp:1722. It adds `DS_CONSOLE` if `Sender->Type==ST_ACTOR`
```c++
void GameScript::DisplayString(Scriptable* Sender, Action* parameters)
{
    Scriptable* target = GetScriptableFromObject(Sender, parameters->objects[1]);
    if (!target) {
        target=Sender;
    }
    if (Sender->Type==ST_ACTOR) {
        DisplayStringCore(target, ieStrRef(parameters->int0Parameter), DS_CONSOLE);
    } else {
        DisplayStringCore(target, ieStrRef(parameters->int0Parameter), DS_AREA);
    }
}
```

**Comment by lynxlynxlynx** [comment]
Yes, we can just add it there, along DS_AREA. It was removed ages ago without justification and other similar actions have it in this case as well (if fixing the current issue is not enough :)).

**Comment by lynxlynxlynx** [comment]
No, it's just unconditional in pst due to the mentioned garbage. Introduced by #1420, so need to take that complication into account. I guess you can try with: 
```c++
if (core->HasFeature(GFFlags::ONSCREEN_TEXT) || (!charactersubtitles && Sender->Type == ST_ACTOR)) {
```

**Comment by bsdcode** [comment]
Yes it works.

**Comment by lynxlynxlynx** [comment]
Do you want to PR them or should I just commit both changes?

**Comment by bsdcode** [comment]
I already writing the commit message for the PR ;)
