### ISSUE TITLE
[subviews] 42 new issues found by coverity

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#201]
The setup: SDL1, no SDL_MIXER and VLC. Ran the analysis and it found 42 issues. Some are for sure useless, but it did find a clear operator bug and a bunch of potential crashers. No corruption though.

**Comment by bradallred** [comment]
I can't seem to figure out how to start a new scan on this brach...

**Comment by bradallred** [comment]
we should for sure run this against SDL2 as well

**Comment by lynxlynxlynx** [comment]
I've reran it. It doesn't support separate branches and they have low rate limits (used to be 1 per day), so they suggest a separate branch you merge whatever you want into when needed and then travis runs the check on its own.

**Comment by lynxlynxlynx** [comment]
Ok, this will now get regularly checked. Currently there are 26 defects reported and all look branch specific.

**Comment by lynxlynxlynx** [comment]
I was hoping to get this done quickly, but coverity itself has been having issues this month — even our run from last week hasn't been analysed yet and still no word about what's going on.

**Comment by lynxlynxlynx** [comment]
Sigh, it won't get fixed in a while:
https://community.synopsys.com/s/question/0D52H00004v4aM2SAI/when-coverity-scan-will-be-working-again

**Comment by lynxlynxlynx** [comment]
Ok, coverity is operational again and our workflow as well. Only three reports remain that I've now fixed in master and will get inherited with the next branch sync.

The checks will be running roughly once per week ("Actions" tab here on github), so there's nothing left to do ... but to switch the checked branch back to master, once the Big merge is over.
