### ISSUE TITLE
BG1: Doors and shelves are highlighted on complete surface not just the outline

### ISSUE THREAD

**Issue by bsdcode** [gemrb/gemrb#2011]
#### Bug description
Pointing on a door or a shelf highlights the whole object surface. It should only highlight the outline.

#### Expected behavior
Only highlight outline of doors etc.

#### Screenshots
![bg1_wine0](https://github.com/gemrb/gemrb/assets/155195419/d4b1d9e8-de6e-4656-8ff8-9da68101e18a)
![bg1_wine1](https://github.com/gemrb/gemrb/assets/155195419/79de8d64-e8df-4779-92da-b697538cfb70)

![bg1_gemrb0](https://github.com/gemrb/gemrb/assets/155195419/4b1ade9c-282e-4bdc-a131-01bb8b8f45b0)
![bg1_gemrb1](https://github.com/gemrb/gemrb/assets/155195419/a9f3c807-02c9-40a9-8150-b2fe4f0c6a27)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
It's easy to change (GameControl::Draw or thereabout), since we have to draw them separately anyway. But it would make it different from everyone else, so a new game flag would be needed.

**Comment by bsdcode** [comment]
I only know Baldur's Gate 1. Does this mean that the other Infinity Engine games are highlighting the complete surface instead of just the outline?

**Comment by lynxlynxlynx** [comment]
Yes, like we do now.

**Comment by bsdcode** [comment]
Ok. I actually like the aesthetics of just the outline more. Personally I would rather see it in the other games too.

Can I add a new option in gem-baldur.ini for controlling the highlight behaviour, defaulting to the current way, i.e. highlight the whole surface by default. This way everyone can decide how they want it to be highlighted for all games.

**Comment by lynxlynxlynx** [comment]
That's what I meant with game flag. You can grep for `GFFlags` to get started

**Comment by bsdcode** [comment]
Alright.
