### ISSUE TITLE
BG1: Characters leaving the map disappear immediatly

### ISSUE THREAD

**Issue by bsdcode** [gemrb/gemrb#2015]
#### Bug description
Probably related to #2014, i.e. is the same root cause. Characters who want to leave the map disappear immediatly instead of going to their exit point. An example is Padra, the yellow monk at the beginning of the game, when you go to house in the north of Candlekeep where Skank attacks you. After the battle you leave the house and a monk asks you what happend. After the dialog the monk goes into the house. In the original Baldur's Gate 1 he would go to door of the house and disappear. In GemRB the monk disappears immediatly without going up to the door. Probably because the character is already on the same level as the "exit marker" for the door (#2014).

#### Expected behavior
Characters go the whole way.

#### Screenshots
![bg1_gemrb](https://github.com/gemrb/gemrb/assets/155195419/e637f9b0-1539-4609-9d09-30072e070433)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
Time to figure out what she's using. One of the EscapeArea calls?

**Comment by lynxlynxlynx** [comment]
It's the plain EscapeArea and it works as expected as in the actor vanishes if he can't find a path closer.  But he should, so it's a different problem.

**Comment by lynxlynxlynx** [comment]
One obvious problem is that we position the actor differently on area exit. Bottom two screenshots are from the original and tutu, then us with the searchmap, then NI:
![image](https://github.com/gemrb/gemrb/assets/121515/2e73ee00-6c82-4fe5-875a-3f3838e76baa)
I suspect we ignore that impeded door tile and the original didn't, shifting the position.

https://youtu.be/4-1YPfhSU3Y?si=Xp-KkAJDtC4WBC5K&t=343

**Comment by bsdcode** [comment]
Thanks for looking into it.

Unfortunately this is just one example of the problem. Another two are
![dis](https://github.com/gemrb/gemrb/assets/155195419/b12213cb-c508-4f03-b470-4b1cc9bf52a7)
![dis1](https://github.com/gemrb/gemrb/assets/155195419/8fc80ca1-a498-404a-9550-ecdf9f024fe5)

right at the beginnig of chapter 1. They can't find a way to the exit and then disappear instantly. Maybe these NPC have to try a little bit harder before they give up ;)

**Comment by lynxlynxlynx** [comment]
Ok, that's different and a missing feature. I'm on it.

**Comment by bsdcode** [comment]
Awesome! Thanks for your work on it. Now the mentioned NPCs all go properly to an exit point much like in the original. Thanks!
