### ISSUE TITLE
[subviews] Container view not showing up in IWD2

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#202]
**Describe the bug**
You cannot inspect containers or items on the ground. There is no inventory view showing up. Screen res is 1024x768.

**To Reproduce**
1. Start some game
2. Click on something you want to pick up from the ground.
3. Click on some container you want to exchange items from.

**Expected behavior**
Container inventory to show up, but nothing is happening

**Comment by bradallred** [comment]
it would be helpful when opening bugs for this branch to report if you have any GUIScript errors too. Mostly thats the only thing that differs from game to game, so it's the most likely cause of issues even if the GUIScript error sounds unrelated.

**Comment by MarcelHB** [comment]
No GUIScript errors to spot unfortunately.

**Comment by lynxlynxlynx** [comment]
I remember the same problem with bg2, so I guess it's just a matter of porting the same fix, since iwd2 has some uncommon guiscripts. There's many commits referencing ContainerWin to look through.

**Comment by bradallred** [comment]
well that was easy
