### ISSUE TITLE
BG & OpenAL: Speech handling broken in CharGen in some circumstances

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2030]
#### Bug description
In BG or BG 2, when going through CharGen and the PC's sound table, the playback is almost mute. What we know:

* It's only observable BG/2, IWD games look good (Python script is using another method there)
* When going directly into GC without loading a game first, it's Ok.
* It does not appear to be related to any volume or position corruption, debugging says it's 100% at (0, 0), as expected.
* It is independent of having EFX enabled.
* It is located around `GEM_SND_SPEECH` since if you set non-replacing playback, i. e. the speech flag, in the Python script, everything is Ok.
* When you return to an actual game, all PC voices are good again.
* There is no error returned by the AL implementation around the sound settings before queuing the buffers.

I've spent some time debugging this without any findings so far, yet is remarkable in some way as it is fully reproducible and the code in question appears to work for every other case but _returning_ to the GC from a game – which itself is somewhat an edge case, so maybe only for reference to report here.

#### Steps to reproduce
0. Use OpenAL as sound driver.
1. Start a BG2 game by loading a save game.
2. Exit the game.
3. Start a new game via CG.
4. When choosing any of the sound sets, click the playback button.

#### Expected behavior
Full volume for the voice.

#### Screenshots
You can only hear somthing on the lowest possible volume in the far left channel. Virtually nothing on bad speakers.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

**Comment by lynxlynxlynx** [comment]
Is it just about the actor soundset? It looks obvious to me that the two PlaySound calls should use 5 instead of 4, so there's no spatial positioning done.

**Comment by MarcelHB** [comment]
That makes sense, the position of the listener is probably just left somewhere by the game ... that's why we don't notice in the first run.
