### ISSUE TITLE
PST: text floats away too fast 

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#2032]
#### Bug description
Text floats up much faster than original, like 0.5 seconds to window edge.

#### Steps to reproduce
1. Attack anyone.
2. See damage text.

#### Expected behavior
Slower text float speed.

#### Screenshots

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
I'm going to need some data, because I timed it when developing. See `OverHeadMsg::Draw`.

**Comment by burner1024** [comment]
Ah, it's tied to FPS, I have it unlimited.

**Comment by lynxlynxlynx** [comment]
Indirectly to AI speed, since it's based on game time. Easy to fix by factoring the speed ratio into the delay there.
