### ISSUE TITLE
Projectiles/Spell effects burning down too fast on higher FPS 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2037]
#### Bug description
I don't know whether it's recent regression or an obvious oversight for some time already, but I think there's something wrong with at least some area spell projectiles and effects on FPS > 30: They manifest shorter by some factor while being accelerated to the inverse apperently, and by listening to the annoying sounds they make.

#### Steps to reproduce
1. `CapFPS=0`
2. Cast something like Web or Entangle
3. Watch the time until it's over

#### Expected behavior
Manifestation duration should adhere to the description regardless of the FPS.

#### Screenshots

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
That's odd, didn't you successfully decouple the drawing from the game speed? What's your "Maximum Frame Rate" in your gem-*.ini?

**Comment by MarcelHB** [comment]
I looked at effects but probably not suitable ones for this. `Projectile.cpp` (for the whole Web thing) has some code parts that looked suspicious at first glance.

`Maximum Frame Rate` is 30, and capping the FPS to 30 prolonges the whole thing. Although that setting still looked to short for the description (30s vs. 60s), but I will test that again as well.

**Comment by MarcelHB** [comment]
Yep, the draw code of projectiles also manages the state transitions.

**Comment by MarcelHB** [comment]
Trying to rewrite this a little, the otherwise simple state machine make its transitions a little hard to figure out from the outside.

**Comment by MarcelHB** [comment]
Yes, like it's supposed to be. It's just that after the first rewrite I still had little idea what I refactored and why it worked that way to the degree of _almost_.

**Comment by MarcelHB** [comment]
I fixed the projectiles, but I'd also fix sparkles/particles. But that currently suffers from things that look otherwise broken to me (see skull trap in IWD2), so let's check them in a different issue.
