### ISSUE TITLE
Specialist mages saving throw modifiers don't work

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#2038]
#### Bug description

Mage specialization saving throws mods don't work in BG1 nor BG2, probably others too.

#### Steps to reproduce
1. Put `Log(ERROR, "EffectQueue", "specialist {}; PrimaryType {}", specialist, fx->PrimaryType);` somethere here
  https://github.com/gemrb/gemrb/blob/f580e496a4b0c072667029264c732b452e682181/gemrb/core/EffectQueue.cpp#L1061-L1063
1. Start a new game, pick an Invoker, and Illusionist, cast Web, Stinking Cloud, Blind on self.
1. Check logs.

In BG1, `PrimaryType` is not populated at all, so it never matches.
![Captura desde 2024-02-27 22-32-51](https://github.com/gemrb/gemrb/assets/1279852/1dd7d786-a279-4512-8b7f-142bd5e778c5)

In BG2, `PrimaryType` is mostly set, although there are appear to be some intermittent cases when it's not. But it doesn't matter, here specialist var is set to kit id from kitlist.2da, and the condition, probably designed on BG1 data, checks for kit usability flag instead, so it also never matches.
![Captura desde 2024-02-28 10-23-00](https://github.com/gemrb/gemrb/assets/1279852/523c01ea-8dbb-4064-a4bf-6f849a951e13)

#### Expected behavior
Specialist saving throw bonunes and maluses should work.
Spell school should be chain propagated. Probably the only place where effect's own school should matter is when it's attached directly to an item.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
Like you note, bg1 doesn't have spell school data, so this can't work there without a mod. You're also right about the fact that we should be checking the kit usability. We have it stored in Actor's class2kits.
For spell effects we already replace their school with the spell's one.

**Comment by burner1024** [comment]
Yes, I missed that bg1 spells don't have school specified.
