### ISSUE TITLE
[subviews] IWD2 message log has some display issues

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#204]
**Describe the bug**
There are some things related to the message log in the main controls.

1. There is always a caret in the bottom left corner (screenshot).
2. You can click the text area, press SPACE, and the whole text loses its format and collapses towards the top of its containment (not on screenshot).
3. After that, newly inserted text is not positioned correctly either (screenshot).

**Screenshots**
![Screenshot_2019-09-06_00-03-09](https://user-images.githubusercontent.com/238558/64387516-876a0c00-d03c-11e9-918b-ab7074c7b39e.jpg)

**Comment by lynxlynxlynx** [comment]
The entry thing sounds familiar. This may be one of the unremembered TODOs after the textarea editing support was readded.

**Comment by bradallred** [comment]
yeah, looks like that TA has the `Editable` flag set. How it got set I haven't the foggiest. Maybe IWD2 is doing something like `SetFlags` with some integer value somewhere so it was never found and fixed up with the rest. Should be an easy fix, but it's something that could be done from any script so the offender could be anywhere.

**Comment by MarcelHB** [comment]
What I just observed by looking at the screenshot: Is it correct to have two scrollbars here?

**Comment by bradallred** [comment]
the scrollbar things is also probably an artifact of IWD2 GUIScripts not being up-to-date.

**Comment by bradallred** [comment]
The input cursor is actually coming from a `TextEdit` specified in the CHU... No idea what that is for. I'm going to delete it for now.

**Comment by bradallred** [comment]
The "scrollbar" is actually not a scrollbar. You can see this if you set `DEBUG_VIEWS` to `1`. I have confirmed by looking at all the subviews of the window. This is apparently part of the CHU background.

![image](https://user-images.githubusercontent.com/1126744/64454914-6d1a4780-d0a9-11e9-8252-4187c54ad0b7.png)

**Comment by bradallred** [comment]
@MarcelHB I cant reproduce any of you other issues here

**Comment by MarcelHB** [comment]
I just checked out your commits, and now I just did the following: On the message window, clicking the left mouse button and the space bar repeatedly and in no particular order, and I get this:

![console](https://user-images.githubusercontent.com/238558/64455489-15ea9600-d0ee-11e9-9d80-ee8edb25e3fd.jpg)

**Comment by MarcelHB** [comment]
Maybe it's localization, I'm testing this on master again.

**Comment by MarcelHB** [comment]
Looks good there, no corruption, no scroll cursor, working scrollbar.

**Comment by bradallred** [comment]
ok, I can reproduce with those steps. This does appear to not affect BG2, and I get an edit cursor again. The view debugger doesn't indicate any other funky controls like that extraneous TextEdit, however.

**Comment by bradallred** [comment]
@MarcelHB what is wrong with the scrollbar now?

**Comment by MarcelHB** [comment]
The drag item gets los, as you can see on the screenshot.

**Comment by MarcelHB** [comment]
Well, consider that aethetics:

![scrollbars](https://user-images.githubusercontent.com/238558/64456815-644d6400-d0f1-11e9-802c-41485f492e4c.jpg)

**Comment by bradallred** [comment]
if there is nothing to scroll then that is why there is no bar. I have no desire to replicate the original behavior here. There are minor adjustments that I have made for the positioning.

![image](https://user-images.githubusercontent.com/1126744/64463361-fa1ccb00-d0c0-11e9-8c2a-b75b812eb356.png)

**Comment by bradallred** [comment]
seems like the formatting bug has to do with some double click behavior somewhere.

double click the _TextContainer_ (not just the TA) and press space everything already in the TA loses its formatting and the new string is added with formatting and all subsequent presses of space behave the same way.

if you then click the TA only (not possible if the TextContainer has grown to the bottom) then everything starts getting appended properly again.

seems like a bug with double click and control focus. we shouldn't be able to send key events to the TextContainer inside the TA if the edit flag isn't on, but they double click seems to bypass that somehow.

**Comment by bradallred** [comment]
clicking outside the TA also restores the intended behavior.

I've put breakpoints in `TextContainer::OnMouseDown`, `TextContainer::OnMouseDrag`, and `TextContainer::OnKeyPress1, but none are hit. very interesting. I see the edit cursor at the top advance when I hit space so... o_O

**Comment by bradallred** [comment]
ok, I had forgotten the SDL2 text input events. I see `TextContainer::OnTextInput` does get hit and indeed it is hit because it is the window `focusView`... so the root seems to be that somehow we are able to focus this with a click. It doesn't actually have to be a double click.

**Comment by bradallred** [comment]
The issue was happenstance. It just so happens that in IWD2 the TextContainer is the last thing added to the window so it has the windows focus I've fixed it so that disabled or ignoring views cant get the window's focus.

**Comment by bradallred** [comment]
It's now clear that the IWD2 MessageWindow.py is in need of more updates. Reopening.

Things nearly work correctly, however, my fixes were applied in `UpdateControlStatus()` which gets called repeatedly... so things start drifting into chaos in dialog now. The large window also doesn't get cleaned up after dialog it seems.

Unfortunately, I don't think we can get away with just a single MessageWindow like we do with the other games. I'll just have to split them in two. The easy thing would be to load both and toggle their visibility and scripting keys...

**Comment by lynxlynxlynx** [comment]
What is different about iwd2 compared to, let's say, pst? I don't understand why we'd need a separate window for dialog and regular log, especially since the two can mix — not all dialog is pausing and even if when it is, actions can still print stuff after text (journal updates, gold, xp, items ...).

**Comment by bradallred** [comment]
Functionally you wouldn't be able to tell the difference between one window and 2 as long as we swap the `TextArea` so why does it matter? I'm not suggesting 2 TextAreas that get different content.

But you are right, we can probably just swap the backgrounds and change size/position. Its a little more hairy than the other games because the size and position of both the window and TextArea change between the 2 modes... then again there aren't any resize buttons to deal with :)

**Comment by lynxlynxlynx** [comment]
Oh, I see now, IWD2 has a bigger window for dialog only. The first proposal sounds cleaner to me.

**Comment by bradallred** [comment]
yes, I think it might be too. I see also that the large window has a portrait control and the smaller of the 2 is also the options window so there really isn't a good way to get by with a single window in this case.

I will just load both windows and swap the TextAreas between the 2. I shouldn't have to do any other juggling with that approach and it should appear seamless to the user.

**Comment by bradallred** [comment]
This should be playable now. Eventually I'll have to circle back and figure out how best to restore the TextAreas scroll position when we swap to the large since the resizing makes the position inaccurate.

**Comment by bradallred** [comment]
Ok, had an epiphany. I think everything is working as expected now.

The only thing remaining that I am aware of is the need to expose `SetMargins` to GUIScript so that we can counteract the overflow caused by the frame hacking required by the  scrollbars.

**Comment by MarcelHB** [comment]
Don't want to complain any more. :wink:

**Comment by bradallred** [comment]
@MarcelHB nonsense, complaining is how things get fixed 😉

Thanks for helping out.
