### ISSUE TITLE
LISTENER_HEIGHT increase results in too low volume for soundeffects

### ISSUE THREAD

**Issue by bsdcode** [gemrb/gemrb#2040]
#### Bug description
Since the increase of the listener height
https://github.com/gemrb/gemrb/blob/db426f2b0ed08514b221db58ba9151fb55fbb328/gemrb/plugins/OpenALAudio/OpenALAudio.h#L55
in one of the recent commits, the volume of soundeffects is way too low in contrast to the other sounds. The increased gain
https://github.com/gemrb/gemrb/blob/db426f2b0ed08514b221db58ba9151fb55fbb328/gemrb/plugins/OpenALAudio/OpenALAudio.cpp#L247-L249
doesn't mitigate the lost volume. The volumes of ambient sounds, voices and music have to be decreased considerably in the options menu in order for other soundeffects to be decently hearable and not "swallowed" by them.

#### Steps to reproduce
1. Start new game in original BG1 and start in front of Candlekeep Inn
2. Open/Close the front door of Candlekeep Inn
3. Hear the opening/closing sound in good volume
5. Start new game of BG1 in GemRB and start in front of Candlekeep Inn
6. Open/Close the front door of Candlekeep Inn
7. Almost no hearable opening/closing sound

#### Expected behavior
Soundeffects keep good volume and don't get swallowed by other sounds.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
Just a note to anyone testing. Make sure the volume levels are set to the same values in both {gem-,}baldur.ini, just in case you modified either via the GUI.

**Comment by bsdcode** [comment]
I played the beginning of BG1 from Candlekeep to Friendly Arm with different `LISTENER_HEIGHT` values (0, 50, 100, 200) and different `AL_GAIN`s. A change in `AL_GAIN` doesn't do much in my perception. The bumped volume is definitly noticable from 1.00 to 1.25, but afterwards not so much.

A higher `LISTENER_HEIGHT` does indeed smooth out the L/R-transitions, but the price to pay are swallowed soundeffects. In this regard a value of 0 seems to represent the volume of the original game the best. In addition, at least in original BG1, speech/dialog is always centered and volume isn't depending on listener position. This adds the question if GemRB actually should depend the dialog volume on the listener position at all, which then questions the gains in smoother L/R-transitions in its foundations. That's probably another topic entirely.

All in all I think there's no absolut best value for `LISTENER_HEIGHT` which fits all users and preferences. This should probably be an user configurable option.

What do others think?

**Comment by MarcelHB** [comment]
Just as an idea: If the channel is any of the sound effects you find too low, does raising the Z position of that source a little (0 < z < LISTENER_HEIGHT) help/sound good? Not sure how cleanly the channels are distinct in detail here, but two things:

1. if it's your banging door, I don't see any reason against helping like this, these are short bursts, not ambients
2. some things like spell sound effects, that may last a little longer, appear to be little broken, like having a lighting or web explosion off-screen still makes your hear a full blast, this is what I'd adress in the future maybe

**Comment by lynxlynxlynx** [comment]
I don't think this should be user configurable, since they already have both the volume controls and can edit the relative volumes per channel. What we need is a sane default for whatever values are required, whether we need to take a different approach or not.

**Comment by lynxlynxlynx** [comment]
So how about just having a container indexed by `SFX_CHAN_*` and we define per-channel heights? We already do it for volume (but can't override the 2da) and could just set the source height in `OpenALAudioDriver::Play` instead like Marcel mentioned.

**Comment by lynxlynxlynx** [comment]
The mechanism is now in and we can play with the values to get better outcomes.

**Comment by lynxlynxlynx** [comment]
Not sure if some other fixes affected this, but for the test case in the OP, I could only hear a minor volume difference. With a position of 100 it seems fine, so that's what's going in. 

It is true that we play these sounds as spatial. BG1 we can't test with, but in BGEE/BG2, I can hear that it is spatial in the sense that L/R matters, but the volume change is quite minor until it just cuts off relatively close to the edge of the viewport (might be a fixed range, didn't check with several resolutions).
