### ISSUE TITLE
Should dialog volume actually be depending on listener position 

### ISSUE THREAD

**Issue by bsdcode** [gemrb/gemrb#2043]
#### Bug description
Currently the volume of dialogs is depending on the listener position. This gives L/R-transitions, but has the detrimental effect of hardly hearable dialogs at higher resolutions. As an example look at the dialog with Montaron near the beginnig of BG1:

![bg1_480](https://github.com/gemrb/gemrb/assets/155195419/11ae25a1-9447-4e5b-aec2-18dabddf0fe8)

With the standard resolution of 640x480 the game can center on Montaron (original BG1 and GemRB) and play the dialog with 100% volume.

![bg1_960](https://github.com/gemrb/gemrb/assets/155195419/f68b9cf0-cc84-480f-87f6-b92ca92fb9dc)

With a higher resolution of 2280x960 the game isn't able to center on Montaron because it's near the edge of the map. As a result the dialog's volume is very low.

In the original games, at least in BG1, dialogs/speech isn't depending on the listener position and always plays with 100% volume.

What should GemRB do?

Also see #2040

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by MarcelHB** [comment]
I agree, dialogs are not configured to be interpreted spatially, so the screen res. and focus of the other actor in the dialogue shouldn't have any of the observed effects.

The source pos should be something like (0, 0, 0) and then feel like completely centered. Looks like it is not but something VP-relative ...

**Comment by lynxlynxlynx** [comment]
In `GameControl::MoveViewportUnlockedTo` if we're not centering, aren't we misplacing the listener?

**Comment by MarcelHB** [comment]
> In `GameControl::MoveViewportUnlockedTo` if we're not centering, aren't we misplacing the listener?

Even if so, it should not matter for a dialog: https://github.com/gemrb/gemrb/blob/ef3cab5d5835138d37f996b674bfcab7aa103d58/gemrb/core/GameScript/GSUtils.cpp#L525-L528

**Comment by MarcelHB** [comment]
Maybe I've missed something down the line but looking at the GSUtils code above, if it's a dialog, then don't match this condition, i. e. relative mode + source `pos` remains 0, good.

Then with https://github.com/gemrb/gemrb/blob/31837d90f6a0f7c0ead466fc730e9a0eef077396/gemrb/plugins/OpenALAudio/OpenALAudio.cpp#L515-L516 relative mode is true unless the spatial flag is set. EFX is pre-set but that's supposed to be irrelevant w. r. t. any positioning.

**Comment by lynxlynxlynx** [comment]
Ah, I'm mixing up names again, these two do look fine. 
But this isn't what dialog is using to play the sounds, the code is there to prevent any dialog triggered DisplayString* family of actions to play incorrectly. It's `gemrb/core/DialogHandler.cpp:327` (eventually ending in `Interface::GetString`) where the spoken stuff is printed and voiced.

**Comment by MarcelHB** [comment]
Going down, we end up here ... lgtm https://github.com/gemrb/gemrb/blob/0d5af59d600dd2b73d675add6571641449530249/gemrb/plugins/TLKImporter/TLKImporter.cpp#L375-L381

**Comment by lynxlynxlynx** [comment]
STRING_FLAGS::ALLOW_ZERO turns into GEM_SND_QUEUE, which is a problem, but can't affect the volume.
So yeah, still sounds like a wrong listener position.

**Comment by lynxlynxlynx** [comment]
Ok, that centering is unused. Changing the listener position lowers the volume, hence this issue. Making sure it's set to the specified position (before it gets boxed in) doesn't change anything (or I did it poorly). 

But I later realized we're testing with Montaron, who doesn't really speak during dialog, it's just his greeting verbal constant and that has GEM_SND_SPATIAL on since dialog hasn't started at that point yet (in BeginDialog). If he had any voiced dialog lines, those would be played properly. I'll make it consistent with those.
