### ISSUE TITLE
`CreateItem`/`ci` console cheat command needs better item placement

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2046]
#### Bug description
If you execute `ci("...", 1)`, it replaces the _head_ item of the selected PC, regardless of the type. And whatever was there is gone then.

#### Steps to reproduce
1. Open cheat console
2. `ci` something
3. Look at the head item in the inventory to pick up the item

#### Expected behavior
Place it in the regular inventory, or drop it if full.

#### Screenshots

![2024-03-03_01-03](https://github.com/gemrb/gemrb/assets/238558/ca5e492d-344f-4762-9e33-de05be6c7f7b)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

**Comment by MarcelHB** [comment]
Well ok, I had the original game param order in mind, i. e. `("ITEM12", 3)` with the 2nd argument being the number of items.

Here, it's `slot`, so my 1 placed that on the head apparently. Does anybody of you use slot values? I don't even know how they map to the inventory. Otherwise, can we move that the back of the arguments?

**Comment by lynxlynxlynx** [comment]
It's simply this way to match the `GemRB.CreateItem` that it calls. We can drop the parameter, I've never needed it.
