### ISSUE TITLE
[bug] Graphical glitch in Spellbook / Priestscroll in IWD1

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#205]
**Description**
Issue #194 (flickering in spellbooks and priestscrolls) also affects IWD1. Perhaps the games utilize the same GUI scripts (?), but just for the record, here it is.

**GemRB version**
0.85-git Linux

**Comment by lynxlynxlynx** [comment]
They do, yes (except pst). Closing in favour of the other. Thanks for thinking about it any way.
