### ISSUE TITLE
Wrong blending for some damage types

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2050]
#### Bug description
When struck by a lightning/lightning mephit, there is (in BG2) SPSPARKS.bam and SPSHKIMP.bam on the actor. They aren't blended properly so you see the black surroundings.

Also applies to some flame, acid and ice damage effects across different games.

#### Steps to reproduce
1. Cast a lightning towards an actor.

#### Expected behavior
No black background.

#### Screenshots
![lightning](https://github.com/gemrb/gemrb/assets/238558/f5093877-e9e3-49da-a279-44b9233cff74)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by bradallred** [comment]
the fix is easy enough, just use `ONE_MINUS_DST` as the blend mode. That's (almost) always the answer when a BAM uses a black BG. Is this a PRO that we created? If so just open it in NI and tick whatever bit relates to `PTF_TRANS` (and possibly clear the one for `PTF_BLEND`)

**Comment by bradallred** [comment]
It might be worthwhile for somebody to comb though our PROs and check the rest of them so we can fix them all in one go instead of as we encounter them.

**Comment by MarcelHB** [comment]
The projectile's BAM is good, that's the damage-associated animations (electricity). If one assigns the `AA_BLEND` flag, then it looks good. But since it's not (only for PST?), it maybe needs to be checked for every game/damage type first.

**Comment by lynxlynxlynx** [comment]
In our case the code is in `Actor::PlayDamageAnimation`, but yeah, it's simple to test this in other games.

**Comment by MarcelHB** [comment]
I went through the lists and checked all games' BAM files. My suggestion is to put a new flag column into the `damage.2da` files that can be applied to both `MAIN` and `SPARKS` BAMS since this is always pairwise connected.

**Comment by lynxlynxlynx** [comment]
So you're saying we can't just turn blending on for all the games?

**Comment by MarcelHB** [comment]
I've tested all BAMs for black surroundings of effect visuals. Some of them (some flames but also almost all blood effects) have very dark shades though (dark red). Without doing the blending math, I'm not sure if this is a good idea for every case.
