### ISSUE TITLE
BG1/BG2: some class restrictions don't apply for some races

### ISSUE THREAD

**Issue by bsdcode** [gemrb/gemrb#2059]
#### Bug description

I realized and checked for BG1 and BG2 that some races are allowed to become some classes which they are not allowed to in the original games. The classes are:

**Elf:** Druid, Bard, Fighter/Cleric, Fighter/Druid, Cleric/Mage, Cleric/Thief, Cleric/Ranger, Fighter/Mage/Cleric
**Half-Elf:** Paladin, Cleric/Thief
**Gnome:** Bard
**Halfling:** Bard, Fighter/Cleric, Cleric/Thief
**Dwarf:** Druid, Bard, Cleric/Thief

This is easily fixed by changing `gemrb/unhardcoded/{bg1,bg2}/classes.2da`. The question is if it should be fixed or is there a reasoning behind it in GemRB?

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

**Comment by lynxlynxlynx** [comment]
This was changed before my time, but the rationale is simple: the restrictions are ridiculous.

**Comment by bsdcode** [comment]
I checked IWD + HOW: they adhere to the original restrictions.

**Comment by lynxlynxlynx** [comment]
Sure, the most proper way is to follow the originals and move changes to a mod like gemrb-tweaks.
