### ISSUE TITLE
Pointing on PCs as action target should also highlight their portrait

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2064]
#### Bug description

In the original, when choosing an attack or a spell on a PC, _both_ the ground circle _and_ the portrait border should have an oscillating white-green effect. For GemRB, it's only the ground circle right now.

This is helpful if the tooltip is delayed and you have no clue who's under cursor exactly, but a look at the avatar reveals that.

#### Steps to reproduce
1. Pick a spell with an actor target.
2. Point to one of the party members

#### Expected behavior
Green-white avatar frame pulses, as for the ground circles.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

**Comment by lynxlynxlynx** [comment]
Basically whenever the cursor is over a pc, also their portrait's border should oscillate. And vice versa for the selection one. Currently we only oscillate the border when hovering over the selected pc's portrait. So we should have all the tools already, it's just that some are maybe done on the python side.

**Comment by bradallred** [comment]
This also happens when speaking. At least in BG2.
