### ISSUE TITLE
[bug] BG2: GUI freezes when dialogues trigger while in spellbook / level-up screens

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#207]
**Description**
If a dialogue triggers while managing spells / inventory or leveling up, the game freezes up completely. Could only kill GemRB. The screenshot shows it happening during a level up, watch the dark space at the bottom where the dialogue window would be. Doesn't happen in IE.

**GemRB version:**
0.8.5-git Linux

**To Reproduce**
A little difficult - if you have the Kivan NPC installed, it could likely happen after the Promenade Cutscene when he approaches the PC. Usually at least Minsc levels at this point. That's what happened when I made the screenshot. It also happened while memorizing a bunch of spells once.

**Expected behavior**
Dialogue should only trigger in main game screen. The game should probably be paused when accessing whatever screens other than the main playing screen?

**Screenshots**
![screen](https://user-images.githubusercontent.com/54738589/64429912-5aa70a80-d0b7-11e9-9ed6-390e0ff71453.jpg)

**Comment by lynxlynxlynx** [comment]
Thanks, this is important and known (though we didn't think of this particular combination) it can happen. More cases to plug, though I believe #95 will fix it generically.

**Comment by caillean7** [comment]
Heh, it's  bound to happen sometimes with NPC mods and different banter packs installed. Need to remember to pause the game before accessing those screens for the time being.

**Comment by lynxlynxlynx** [comment]
I think the records window alone or with the other subwindows does close fine, just like the inventory, but yeah, best workaround is to pause.

**Comment by lynxlynxlynx** [comment]
Yeah, rechecked, all the main windows are fine at level 1 deep, but not more. Current status:
- GUIREC, GUINV, GUIMG and GUIPR (and GUISPL)
- GUIJRN, GUIOPT and GUIMA are fine

At least that was the case on Sunday, now all are fixed. Level up and dual classing can still break this though, since it would be much too tedious to make them cancellable at any arbitrary point of the process.

**Comment by lynxlynxlynx** [comment]
That's incorrect (bg1 vs bg2 inventory), but a great idea for GUIREC, taking care of the other two corner cases. GUIOPT does the same already.

**Comment by caillean7** [comment]
And does GUINV also take care of item description windows? (Happened to me just yesterday)

**Comment by lynxlynxlynx** [comment]
Yes.
