### ISSUE TITLE
 Bug with special characters wrongly dipslayed

### ISSUE THREAD

**Issue by PowaBanga** [gemrb/gemrb#2078]
#### Bug description
Some characters with accent "àéè" are displayed wrong in narative text, and diary.

#### Steps to reproduce
1. Go to the diary and see or wait for a narrative windows

the seem

#### Expected behavior
Add a clear and concise description of what you expected to happen.

#### Screenshots

GemRB version (check as many as you know apply)
- [ ] master as of this issue
- 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

(we spoke about this issue on [baldursgateworld.fr](https://www.baldursgateworld.fr/viewtopic.php?t=34433) )

![https://i.imgur.com/1n2z0CM.png](https://i.imgur.com/1n2z0CM.png)
[![https://www.baldursgateworld.fr/download/file.php?id=14530](https://www.baldursgateworld.fr/download/file.php?id=14530)](https://www.baldursgateworld.fr/download/file.php?id=14530)
[![https://www.baldursgateworld.fr/download/file.php?id=14529](https://www.baldursgateworld.fr/download/file.php?id=14529)](https://www.baldursgateworld.fr/download/file.php?id=14529)

**Comment by lynxlynxlynx** [comment]
What font is that? What are the two download links for?

Anyway, please try a recent development build, since this should be fixed there already.

**Comment by PowaBanga** [comment]
I use [baldur](https://www.dafont.com/fr/baldur.font) from dafont in this case, but i have the same with original fonts, and comic from windows (imported into my linux)

So i tried to compil the game from AUR on my archlinux, and i finaly recieved this error message:
`[ 49%] Linking CXX shared library libgemrb_core.so
In function 'strncpy',
    inlined from '__ct ' at /usr/src/debug/gemrb-git/gemrb/gemrb/core/Strings/CString.h:114:0,
    inlined from '__ct ' at /usr/src/debug/gemrb-git/gemrb/gemrb/core/Strings/CString.h:111:11,
    inlined from 'PrepareSpawnPoints' at /usr/src/debug/gemrb-git/gemrb/gemrb/core/IniSpawn.cpp:259:28:
/usr/include/bits/string_fortified.h:95: warning: '__builtin_strncpy' writing 32 bytes into a region of size 9 overflows the destination [-Wstringop-overflow=]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      | 
/usr/src/debug/gemrb-git/gemrb/gemrb/core/Strings/CString.h: In member function 'PrepareSpawnPoints':
/usr/src/debug/gemrb-git/gemrb/gemrb/core/Strings/CString.h:96:7: note: destination object 'str' of size 9
In function 'strncpy',
    inlined from '__ct ' at /usr/src/debug/gemrb-git/gemrb/gemrb/core/Strings/CString.h:114:0,
    inlined from '__ct ' at /usr/src/debug/gemrb-git/gemrb/gemrb/core/Strings/CString.h:111:11,
    inlined from 'PrepareSpawnPoints' at /usr/src/debug/gemrb-git/gemrb/gemrb/core/IniSpawn.cpp:282:48:
/usr/include/bits/string_fortified.h:95: warning: '__builtin_strncpy' writing 32 bytes into a region of size 9 overflows the destination [-Wstringop-overflow=]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      | 
/usr/src/debug/gemrb-git/gemrb/gemrb/core/Strings/CString.h: In member function 'PrepareSpawnPoints':
/usr/src/debug/gemrb-git/gemrb/gemrb/core/Strings/CString.h:96:7: note: destination object 'str' of size 9
In function 'strncpy',
    inlined from '__ct ' at /usr/src/debug/gemrb-git/gemrb/gemrb/core/Strings/CString.h:114:0,
    inlined from '__ct ' at /usr/src/debug/gemrb-git/gemrb/gemrb/core/Strings/CString.h:111:11,
    inlined from 'PrepareSpawnPoints' at /usr/src/debug/gemrb-git/gemrb/gemrb/core/IniSpawn.cpp:292:61:
/usr/include/bits/string_fortified.h:95: warning: '__builtin_strncpy' writing 32 bytes into a region of size 9 overflows the destination [-Wstringop-overflow=]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      | 
/usr/src/debug/gemrb-git/gemrb/gemrb/core/Strings/CString.h: In member function 'PrepareSpawnPoints':
/usr/src/debug/gemrb-git/gemrb/gemrb/core/Strings/CString.h:96:7: note: destination object 'str' of size 9
/usr/src/debug/gemrb-git/gemrb/gemrb/core/Spellbook.cpp: In member function '__ct_base ':
/usr/src/debug/gemrb-git/gemrb/gemrb/core/Spellbook.cpp:51:65: error: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Werror=alloc-size-larger-than=]
/usr/include/c++/13.2.1/new:128:26: note: in a call to allocation function 'operator new []' declared here
  128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
      |                          ^
lto1: all warnings being treated as errors
make[3]: *** [/tmp/ccyLwqhQ.mk:122: /tmp/ccAZfjx4.ltrans40.ltrans.o] Error 1
make[3]: *** Waiting for unfinished jobs....
lto-wrapper: fatal error: make returned 2 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[2]: *** [gemrb/core/CMakeFiles/gemrb_core.dir/build.make:1969: gemrb/core/libgemrb_core.so.0.9.2-git] Error 1
make[1]: *** [CMakeFiles/Makefile2:1143: gemrb/core/CMakeFiles/gemrb_core.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`

can you help me ?

**Comment by 11jo** [comment]
Did you try the last [developement build](https://sourceforge.net/projects/gemrb/files/Buildbot%20Binaries/Linux/) ?

On [the french forum](https://www.baldursgateworld.fr/memberlist.php?mode=viewprofile&u=8832) it seem to resolve the issue.

**Comment by lynxlynxlynx** [comment]
Those errors look bogus to me. Anyway, you can always disable -Werror, we even provide a convenience switch to cmake for it.

**Comment by lynxlynxlynx** [comment]
It also compiles fine with gcc13 here. Please open a new bug if your unrelated problems persist.

**Comment by PowaBanga** [comment]
I am on gcc14, so, i tryed with the app-image, and it finaly the bug disapear.

**Comment by lynxlynxlynx** [comment]
Hmm, will definitely check that before the release. Nothing major screamed at me when I was looking at the changelog.
