### ISSUE TITLE
[bug] BG2: DisplayStringWait script action working differently than in the IE

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#208]
**Description**
Modded cutscenes might not have sound files associated with displayed strings. In both the classic IE and EE the displayed strings have a delay, they are displayed long enough to comfortably read them while GemRB just shows them so fast that you can't make them out. This is in accordance with what the IESDP describes, I think:

`This works likes DisplayStringHead. The Wait part either refers to waiting for a sound to finish playing before it fades away or for waiting for another DisplayStringHead() before disappearing... or something.`

However the original Engines handle this differently, and modders write their scripts accordingly.

**GemRB version**
0.85-git Linux

**To Reproduce**
An example to watch this behavior is the recent Imoen4ever mod. It modifies the cutscene in the beginning of chapter 2 in the council building ("These are prisoners from the disturbance at Waukeen's Promenade..."). The first part is voiced / vanilla, the rest not.

**Comment by lynxlynxlynx** [comment]
Are you using any audio (gemrb config)? Things are fast if you use none (NullSound plugin), since there's no way to check the length.

**Comment by caillean7** [comment]
You mean if I disabled audio completely - play without sound? No...

**Comment by lynxlynxlynx** [comment]
Ok. Everything looks fine at first glance. So it must be what we said — there's no audio to judge the length from, so we fall back to not waiting.We could fall back to a round. Sounds about right for reading and just on the cusp of being too long. What do you think?

**Comment by caillean7** [comment]
6 seconds - sounds good to me!

**Comment by lynxlynxlynx** [comment]
Should be fine now, please retest.

**Comment by caillean7** [comment]
Nope, sorry, not only does the problem persist, it's gotten kinda worse... The displays of the strings and the sounds are out of sync, most of the sounds are cut off. The first cutscene when you start a new game works, but the one at Waukeen's Promenade after you leave Chateau Irenicus is really messy. Got to mention that I have the restored version of this cutscene from Almateria's Restoration Project installed, but that shouldn't be a problem since it worked fine before that latest commit. The beginning of chapter 2 cutscene in the council is also affected, both the original and the modded content.

**Comment by lynxlynxlynx** [comment]
Ahh, I forgot one pair of braces.

**Comment by lynxlynxlynx** [comment]
Should really be fine now, please retest. :)

**Comment by caillean7** [comment]
Ah, can't compile:

```
/home/nadia/Software/Games/gemrb2019_09_08/gemrb/core/GameScript/GSUtils.cpp: In function ‘int GemRB::GetHappiness(GemRB::Scriptable*, int)’:
/home/nadia/Software/Games/gemrb2019_09_08/gemrb/core/GameScript/GSUtils.cpp:161:40: error: ‘Clamp’ was not declared in this scope
  reputation = Clamp(reputation, 10, 200);
                                        ^
gemrb/core/CMakeFiles/gemrb_core.dir/build.make:2198: recipe for target 'gemrb/core/CMakeFiles/gemrb_core.dir/GameScript/GSUtils.cpp.o' failed
make[2]: *** [gemrb/core/CMakeFiles/gemrb_core.dir/GameScript/GSUtils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:215: recipe for target 'gemrb/core/CMakeFiles/gemrb_core.dir/all' failed
make[1]: *** [gemrb/core/CMakeFiles/gemrb_core.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2


```

**Comment by lynxlynxlynx** [comment]
Yeah yeah, too hasty with the cherry-pick. All the buildbots screamed at me. :)

**Comment by lynxlynxlynx** [comment]
Fixed. Too many projects with the same function, it would be a good candidate for a standard library.

**Comment by caillean7** [comment]
:D While having only the slightest idea what you're tallking about, I can happily report that cutscenes flow fine now, sounds play as expected and readability is good! Tested with both above mentioned cutscenes. A pair of braces with a big effect.
