### ISSUE TITLE
IWD2: crash when misclicking colors in CG 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2083]
#### Bug description
Clicking somewhere behind the color overlay in the colors step of CG (of IWD2), but definitely when hitting the color button again, will hit an assertion violation.

#### Steps to reproduce
Like this:

![iwd2_cg_colors](https://github.com/gemrb/gemrb/assets/238558/923f5a84-a72c-4c40-8ac4-e749d131978b)

#### Expected behavior
No crash.

#### Screenshots
```
Assertion failed: win->GetScriptingRef(), file D:/Sources/gemrb/gemrb/core/GUI/WindowManager.cpp, line 110

Thread 1 hit Breakpoint 1.2, 0x00007ffda861f1e7 in msvcrt!abort () from C:\Windows\System32\msvcrt.dll
(gdb) bt
#0  0x00007ffda861f1e7 in msvcrt!abort () from C:\Windows\System32\msvcrt.dll
#1  0x00007ffda861da39 in msvcrt!_wassert () from C:\Windows\System32\msvcrt.dll
#2  0x00007ffd2d33ff60 in GemRB::WindowManager::LoadWindow (this=0x4524fb0, WindowID=14, ref=..., pos=GemRB::Window::PosCentered) at D:/Sources/gemrb/gemrb/core/GUI/WindowManager.cpp:110
#3  0x00007ffd4577234b in GemRB_LoadWindow (args=0x34bd870) at D:/Sources/gemrb/gemrb/plugins/GUIScript/GUIScript.cpp:552
#4  0x00007ffd7ab8693b in ?? () from C:\MSYS2\mingw64\bin\libpython3.11.dll
```

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
It would be a workaround, but we need to do it either way — the popup should be modal.
