### ISSUE TITLE
IWD2: Mysterious ranger CRE byte makes original crash

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2091]
#### Bug description
I've found a funny bug: If you create a new game in GemRB for IWD2, and your party contains a ranger, than the original executable is unable to load the game. It's faulty error handling can even make Windows unresponsive.

But I've found something going through a little binary diff'ing:

In CRE v2.2, there is a reputation byte, that shouldn't have any meaning in this game in terms of reputation mechanics.

For GemRB, if there is the initial value is 0xB for whatever reason _and_ it's a ranger, then the original crashes. And only then, other classes I've tested don't suffer from this problem of 0xB. In IWD2, the ranger has an initial value of 0x78 at the reputation position. Now if we manually edit that byte from 0xB to 0x78 in the GemRB savegame, everything is good again.

I've replayed this a couple of times since it sounds so odd.

#### Expected behavior

Maybe solve mystery about this value, esp. for rangers, or find a neutral value.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.2
- [ ] 0.9.1
- [ ] 0.9.0

**Comment by lynxlynxlynx** [comment]
gemrb/GUIScripts/iwd2/CharGen9.py:190
we can just delete that if it works with 0, it's a leftover table.

**Comment by MarcelHB** [comment]
0 also looks bad, then let's try 120 for now.

**Comment by lynxlynxlynx** [comment]
Looks like the original started with 100:
https://github.com/alexbatalov/iwd2-re/blob/4fa36bcd6c33e0d35c9e273561aa683aece88490/src/CScreenCreateChar.cpp#L3715
-10 on Game itself (huh, maybe to zero it?):
https://github.com/alexbatalov/iwd2-re/blob/4fa36bcd6c33e0d35c9e273561aa683aece88490/src/CInfGame.cpp#L2935
Could be more code has yet to be revealed, but 120 is surprising.

**Comment by MarcelHB** [comment]
It's actual purpose hasn't been revealed yet, as far as I can see. Let's do it like this until somebody ever finds out more? Enables side-by-side playing for now to maybe spot something else.

**Comment by lynxlynxlynx** [comment]
It has the code to work with the table and a bunch of helpers, but yeah, it's only about save compatibility, since it has no ingame use.

Judging from the starting characters and that new char/import code, unlike other games (as far as we know), iwd2 stored reputation already multiplied by 10, like our Game. That explain the value ranges (80-120). But it would still leave an off-by-1 error (0x78 / 10 = 0xb + 1 ). Is that ranger lawful good?

**Comment by MarcelHB** [comment]
Yes.

**Comment by lynxlynxlynx** [comment]
Then the correct thing should be:
`t = TmpTable.GetValue (GemRB.GetVar ("Alignment") - 1, 0) * 10`
Reviewing other uses of the var confirms we should reduce it by 1 when using it as an index.
