### ISSUE TITLE
 Disabled window rendering is broken

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#2099]
The recent optimizations in `View::DirtySuperViewRegions` caused a regression: drawing a disabled window now just draws a black rect instead of the grey-modal-like overlay.

Easiest to see by selecting a non-caster and opening one of the spellbooks.

Both #2087 #2096 have to be mostly reverted to get it back:
```diff
diff --git a/gemrb/core/GUI/View.cpp b/gemrb/core/GUI/View.cpp
index 9a896d973..5dddd609f 100644
--- a/gemrb/core/GUI/View.cpp
+++ b/gemrb/core/GUI/View.cpp
@@ -181,11 +181,11 @@ Regions View::DirtySuperViewRegions() const
        // if we are opaque we cover everything and dont care about the superview
        // if we arent but we need to redraw then we simply report our entire area
 
-       if (IsOpaque() || frame.size.IsInvalid()) {
+       if (IsOpaque() /*|| frame.size.IsInvalid()*/) {
                return {};
        }
 
-       if (NeedsDraw()) {
+       if (NeedsDraw() || !IsVisible()) {
                return { frame };
        }

``` 

... but that's not desirable. What's the best way forward to fix this while keeping the scrollbars speedy?

**Comment by MarcelHB** [comment]
We can again consider this type-based approach, i. e. overriding this check for the respective SB type only. Although there were concerns, I guess this is safer for limiting the impact of this fix in the meantime.

**Comment by lynxlynxlynx** [comment]
I started with the last commit, since it has a clear data nature.

Looking at the scrollbar data, these are the ones hitting that SetVisible in CHUImporter:
```css
pst
GUIWORLD
  GUIWORLD window: 8, SB: 52 has no matching TA (0 vs candidates: []) container window button lists
  GUIWORLD window: 8, SB: 53 has no matching TA (0 vs candidates: []) container window button lists
GUIREC
  GUIREC window: 7, SB: 8 has no matching TA (0 vs candidates: [7]) mockup
GUISTORE
  GUISTORE window: 9, SB: 16 has no matching TA (0 vs candidates: [13, 15]) 15 would make sense

bg2
GUICG
  GUICG window: 23, SB: 5 has no matching TA (3 vs candidates: []) tf
GUIJRNL
  GUIJRNL window: 9, SB: 5 has no matching TA (0 vs candidates: []) tf
GUIREC
  GUIREC window: 23, SB: 6 has no matching TA (4 vs candidates: []) tf
GUISTORE
  GUISTORE window: 8, SB: 5 has no matching TA (0 vs candidates: [13, 11]) drink button list
(crash after GUIW)

iwd2
GUICG
  GUICG window: 51, SB: 3 has no matching TA (4 vs candidates: []) tf
GUIREC
  GUIREC window: 51, SB: 3 has no matching TA (4 vs candidates: []) tf
GUISP
  GUISP window: 10, SB: 8 has no matching TA (0 vs candidates: [6]) party button list

iwd1
GUICG
  GUICG window: 51, SB: 3 has no matching TA (4 vs candidates: []) tf
GUIREC
  GUIREC window: 51, SB: 3 has no matching TA (4 vs candidates: []) tf
GUISTORE
  GUISTORE window: 8, SB: 5 has no matching TA (0 vs candidates: [13, 11]) drink button list

bg1 maybe none, crash after WORLD, suspicious count
```

Legend:
1. tf: there's a textedit at that ID. Either they're normal textedits (single line) or it's the biography, which we replace
2. all the button lists are fine, ideally they'd have an ID of -1, so we'd skip them — we should not hide them
3. that leaves just that one pst GUISTORE scrollbar with a wrong ID; the TA does have the correct one, but since it is loaded first, there's no linking

So we can remove that SetVisible call while deleting 1. and 3. on the python side.

**Comment by lynxlynxlynx** [comment]
Ok, done, but the second part is a hack, which we'll want to revisit — postponing, so this release can fly out.
