### ISSUE TITLE
Crashes on launch with this error [Interface/FATAL]: Mapping of codepage 65001 unknown to iconv. 

### ISSUE THREAD

**Issue by duy64** [gemrb/gemrb#2106]
#### Bug description
I'm on windows 11 with all the latest patches and all the MS Visual C++ installed
The engine crashes right after launched with this error [Interface/FATAL]: Mapping of codepage 65001 unknown to iconv.
I have checked the FAQs but I still can't seem to fix the issue.

#### Steps to reproduce
1. Go to '...'gemrb folder
2. Click on '....'gemrb.exe
3. Scroll down to '....'got a cmd popup with the error, but closed instantly
4. See error [Interface/FATAL]: Mapping of codepage 65001 unknown to iconv.

#### Expected behavior

It should launch the gemrb engine in either demo mode or the bg2 non ee demo that was installed

#### Screenshots
added screenshot of the error
and a dxdiag report

GemRB version (check as many as you know apply)
version 0.9.3
I haven't tried the other versions

Video Driver (check as many as you know apply)
what ever is the default I didn't mess around with any settings

------------------
System Information
------------------
      Time of this report: 7/27/2024, 19:33:34
             Machine name: RX7900XTX
               Machine Id: {B5C85D44-7335-4237-8C83-9FBAE6D622E4}
         Operating System: Windows 11 Pro 64-bit (10.0, Build 22631) (22621.ni_release.220506-1250)
                 Language: English (Regional Setting: English)
      System Manufacturer: ASUS
             System Model: System Product Name
                     BIOS: 3002 (type: UEFI)
                Processor: AMD Ryzen 7 5800X3D 8-Core Processor            (16 CPUs), ~3.4GHz
                   Memory: 131072MB RAM
      Available OS Memory: 130986MB RAM
                Page File: 27703MB used, 122738MB available
              Windows Dir: C:\Windows
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 144 DPI (150 percent)
       System DPI Setting: 144 DPI (150 percent)
          DWM DPI Scaling: UnKnown
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
 DirectX Database Version: 1.5.8
           DxDiag Version: 10.00.22621.3527 64bit Unicode

[DxDiag.txt](https://github.com/user-attachments/files/16401837/DxDiag.txt)

![Screenshot 2024-07-27 190318](https://github.com/user-attachments/assets/7a57714b-d809-4729-97bb-ddd761bfd436)

**Comment by lynxlynxlynx** [comment]
Hmm, that's UTF-8. Did you manually switch to that encoding? Windows should be using UTF-16 by default AFAIK.

**Comment by MarcelHB** [comment]
I guess https://github.com/gemrb/gemrb/blob/master/platforms/windows/CodepageToIconvMap.cpp needs an update.

**Comment by duy64** [comment]
I had to changed it to utf-8 for an unrelated issue, but thank you for fixing this issue.
