### ISSUE TITLE
[subviews] Skipping the (intro) videos makes a sound

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#211]
**Describe the bug**
I hear things I'm not supposed to hear when skipping the videos, making me a bit paranoid that there is already GUI action going on in the background or something alike.

**To Reproduce**
1. Start any of the games.
2. Skip each video by pressing a key, e.g. ESC.

**Expected behavior**
Probably silence?

**Screenshots**
You hear this snoring (IWD/BG) or wooshing (PST) sound that also plays when closing dialogs, possibly crossfading into the next playing video.

**Comment by lynxlynxlynx** [comment]
From memory, the player now implements a few non-chu and invisible playback controls. The sound could be triggered by the default enter/cancel action if they're considered as other buttons. So by you inputting. But just a fuzzy guess.

**Comment by bradallred** [comment]
yes, this is known and I thought we decided we don't care. It is the window close sound (not attached to a button) and the movie player is displayed in a window now so that is why.

I would vote to close this

**Comment by bradallred** [comment]
If we decide it's annoying or whatever, then we could easily add a new window flag for closing sounds. Could even be like modal windows and there is actually already a bit in the CHU for this.

It's just tedious to go hunt down all the GUIScript places to set/unset the flag. If there is a CHU field for it then lets just pay attention to that and make the default silence and problem solved.

**Comment by MarcelHB** [comment]
Did you do something that you now cannot skip videos at all? I have tried various res/windowed-mode settings for PST and IWD2 on Linux.

**Comment by bradallred** [comment]
any click or key (except 's') should stop the videos. I'm not having problems skipping videos, so I'm not sure why Linux would. Resolution or window mode shouldn't matter either.

**Comment by MarcelHB** [comment]
I'll try again on Windows then.

**Comment by MarcelHB** [comment]
Can you maybe test the following scenarios? I get it like that on both Windows an Linux:

1. Start a game.
2. Only click the left mouse cursors to skip through to the main main.

Works for me.

1. Start a game.
2. Hit escape, notice the sound.
3. Try any other key or mouse click.

I'm stuck and need for all videos to finish. On Linux, I even need `SIGKILL` if I want to exit the process at all.

**Comment by bradallred** [comment]
Start a new game of which game? I can't start a new IWD2 game because I hit an assert in `Actor::ApplyKit`... maybe another bad merge bug? we aren't passing all parameters and one of the params we don't pass is defaulted to 0 which triggers the assert.

**Comment by MarcelHB** [comment]
I can reproduce this for every game.

**Comment by lynxlynxlynx** [comment]
No, the applykit thing is different. I have it fixed locally, but want to fix another bug before I push.

**Comment by bradallred** [comment]
@MarcelHB should work again.

**Comment by MarcelHB** [comment]
Yep, thanks. No longer locked in here.

**Comment by lynxlynxlynx** [comment]
There wouldn't be much more to do with an extra flag, as we currently have only one candidate as a user.

**Comment by bradallred** [comment]
An extra flag is fine (and easy), but I was hoping we could answer the following questions:
1. does every window in the originals make the sound when closing?
2. if not, can we identify which it applies to (eg modal windows only? is there a CHU flag? IESDP lists some unknowns and at least one of them identifies windows as modal)
3. if we have answered the above we probably do not need another flag

**Comment by lynxlynxlynx** [comment]
We know which field indicates modals, we just learned about it too late. Other unknowns may well just be padding and unused.
I don't know of any window that would stand out. But I can't imagine there's a mapping to modals, since then you wouldn't get the sound for the main ingame windows or the menu window wouldn't work.
