### ISSUE TITLE
 BG2: unable to pick portal key in first level

### ISSUE THREAD

**Issue by jpalus** [gemrb/gemrb#2123]
#### Bug description
It was reported in number of places and supposedly fixed already but I've just tried BG2 and am unable to take portal key off the chest. Looking at code I don't really understand why `CanMoveItem` involving `IE_INV_ITEM_UNDROPPABLE` check is used in container -> inventory direction:

https://github.com/gemrb/gemrb/blob/a52d96b56cc47b8de527e50e84f23e2966b47bc5/gemrb/plugins/GUIScript/GUIScript.cpp#L6946-L6956
https://github.com/gemrb/gemrb/blob/a52d96b56cc47b8de527e50e84f23e2966b47bc5/gemrb/core/Interface.cpp#L3485-L3490

I believe in this direction  `IE_INV_ITEM_UNDROPPABLE` check should be skipped.

#### Steps to reproduce
1. Navigate through first level all the way to "Mistress' Room"
2. Try to pick portal key from chest

#### Expected behavior
Portal key is picked but cannot be removed later on.

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [X] 0.9.3

Video Driver (check as many as you know apply)
- [X] SDL2 built with `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
Did you install the fixpack?

**Comment by jpalus** [comment]
> Did you install the fixpack?

Yes, v13. All ended up successfully and I have a 16k line long `setup-bg2fixpack.debug` log file mostly filled with `Copying and patching file` entries. Although I don't see any visual confirmation of this fact in game UI. Was it supposed to make portal key droppable like in EE?

**Comment by lynxlynxlynx** [comment]
Works fine for me on v13 in the sense that I can pick it up from the chest. It's actually buggy, since I can now move it within the inventory, while the original didn't allow that. A regression, but I bet some would argue it's a usability improvement.

Btw, for testing, you can use ctrl-j to jump to the chamber immediately. Is this the English bg2 or some other distribution? Mine is from GOG.

**Comment by jpalus** [comment]
Thanks for the tip. After starting new game with fixpack installed I can indeed pick portal key. I suppose it doesn't work for save games created prior to installing fixpack. Will start again then.

**Comment by lynxlynxlynx** [comment]
Yep, since the area file is part of the savegame.

**Comment by qboriskr** [comment]
This issue has been occured again on latest gemrb version and unmodded BG2. Is installing fixpack will always be necessary for playing gemrb?

**Comment by MarcelHB** [comment]
Yes.
