### ISSUE TITLE
 BG2: Temple ruins entrance is missing

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#2125]
#### Bug description
After completing the area of temple ruins and trying to go back to fight Thaxll'ssillyia I can't go into the ruined temple.

Save game
[000000176-Entrance is missing.zip](https://github.com/user-attachments/files/16901885/000000176-Entrance.is.missing.zip)

Weird thing is that if I reform the party and send someone away he or she will go to the entrance.

#### Steps to reproduce
1. Go to temple ruins
2. Go to any of the entrances
3. Try to enter

#### Expected behavior
I should be able to enter the bellow ruins

#### Screenshots
Video of what is going on
https://github.com/user-attachments/assets/bf02ed18-ccc4-43be-ad84-cd80d3e315ce
With the Ctrl + 4 debug mode

![temple-ruins](https://github.com/user-attachments/assets/06c35111-104d-4377-8bae-a6c31f36a590)

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `OPENGL_BACKEND` enabled
- [X] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
I'm pretty sure this is the default behaviour, i.e. that it works this way in the original.
When you send someone away they'll go to the nearest entrance, regardless if it's disabled or not.

**Comment by rsantellan** [comment]
Something is wrong with the save because I can't load it on the original. I will start trying early saves games to figure out what when wrong, and if this continue to happen

**Comment by rsantellan** [comment]
@lynxlynxlynx going back to the last good save game I have this:
![image](https://github.com/user-attachments/assets/92ab1a7d-57eb-4005-ad00-5ec1725912ca)
That is the same as the original:
![image](https://github.com/user-attachments/assets/6c68a385-4dd6-40dd-a09e-47cc7273d3df)

The differences of this area are that the last save game I can't load on the original and that:
I finish the **Harper plot reveal** on this area and I don't know why the quest **Investigate the deaths of umar hill** has been reseted, so they tell me to go to speak to the mayor.

Is there anything that I can look upon ? Or should I go back to the last good save game and start from there ?

**Comment by lynxlynxlynx** [comment]
In this previous save, have you gone through the dungeon yet?
I doubt the Harper encounter changes anything here.

**Comment by rsantellan** [comment]
Yes I already have gone through the dungeon and finish all the quests, but couldn't kill the dragon. So I wait to level up a little bit and try again, but can't go in.
I will try to trigger the Harper plot in another area to see if is that, because is the first time I came back.

**Comment by lynxlynxlynx** [comment]
Like I said, I doubt that matters. If you ctrl-m in the area in the save before going through the temple, you should get ar1404, while after it's probably ar1400.

**Comment by rsantellan** [comment]
Doing ctrl+m give me this:

```
[Map/DEBUG]: Debugdump of Area ar1400:
Scripts: <none> <none> <none> <none> <none> <none> <none> ar1400
Area Global ID:  10025
OutDoor: Yes
Day/Night: Yes
Extended night: Yes
Weather: Yes
Area Type: 16
Can rest: Yes
```

**Comment by rsantellan** [comment]
@lynxlynxlynx  open the save game with Near Infinity I see it like this:
![image](https://github.com/user-attachments/assets/34bc8575-d47b-423e-85bf-0a86df782cda)

And the last good save game is like this:

![image](https://github.com/user-attachments/assets/d3e26550-24e3-4ef4-9d3f-f6706d8f222b)

As you can see one is AR1400 and the other is ar1400 can that be the problem ?

**Comment by lynxlynxlynx** [comment]
No. I don't have access to the data files here (traveling), but ar1400 is the area after the quest completion. And I still claim there is no bug, that you have just one chance to fight the dragon, unless maybe for ranger strongholds. One would have to check that through NI or in the original.

**Comment by lynxlynxlynx** [comment]
That's always possible, but I find it unlikely.

**Comment by MarcelHB** [comment]
The AR1400 in the savegame looks severly broken. NI lists a lot of heaps (stuff dropped by emenies), and then the rest is missing/broken: ambients, animations, incl. traces of memory corruption. Your issue is likely to be a symptom of this, haven't looked at the code yet. But it's definitely wrong and also breaking BG2. Not sure about the cause of this so far.
![bg2_ar1400](https://github.com/user-attachments/assets/711aa3e9-81b0-4bcc-b868-751f61e78880)

**Comment by MarcelHB** [comment]
Did you manage to retrigger this behavior again? Like retrying the last working save game, progress, and end up in the same situation as with this broken save game? Otherwise it's hard to figure out how any moving parts could have impacted this particularly and we should be keep an eye on this for any future occurrence.

**Comment by rsantellan** [comment]
@MarcelHB that is the hardest part the last good save game is number 138 and the one that I figure out it was trouble is 176....
A lot of thing happen on the middle, I believe the problem started on save game 139 because I couldn't load it on the original.
What I'll will do is start from that save game and try to repeat all the quests that I did one by one, and try all new save games on the original and see if brakes or when.

**Comment by MarcelHB** [comment]
That's quite a mission I guess ;)

I can load 139 from above in the original, maybe it's quicker to check it first when it broke?

**Comment by lynxlynxlynx** [comment]
Hmm, I see some save breaking in iwd2 as well; some polygons get mangled. Haven't managed to put a finger on it yet.

Now that I can load the data, I see nothing disables the entrance, so I was wrong, it should always be an option. Doing a speedrun shows it works as expected, so it's all about the corruption.

**Comment by rsantellan** [comment]
@MarcelHB that is the hardest part the last good save game is number 138 and the one that I figure out it was trouble is 176....
A lot of thing happen on the middle, I believe the problem started on save game 139 because I couldn't load it on the original.
What I'll will do is start from that save game and try to repeat all the quests that I did one by one, and try all new save games on the original and see if brakes or when.

> That's quite a mission I guess ;)
> 
> I can load 139 from above in the original, maybe it's quicker to check first when it broke?

The 138 is the number of the last good save:
![image](https://github.com/user-attachments/assets/ac2ebd63-2968-4b9b-8cd4-534c5f87b77e)
All of the above are broken, I will be a week without been able to access the files. But when I can I will try to see why the first one is broken.

**Comment by lynxlynxlynx** [comment]
Ok, my specific problem is from using ctrl-w. Valgrind doesn't complain when saving, just later before the crash, not very useful. Rechecking if something is  subtly wrong with 9a2866d4...

**Comment by lynxlynxlynx** [comment]
Yeah, there were three problematic places (2 unused, 1 important) from three weeks ago. Unless you got this problem with older gemrb (in that case we'll reopen), it's very likely this was also the culprit for your bug. You can just replay freely, no need for trying to match old order.

I've now also made it so that empty piles are removed immediately, not only when saving.

**Comment by rsantellan** [comment]
They are from last year those save games. I will start from there and see
if it happens again.

**Comment by MarcelHB** [comment]
There is still something wrong. IWD2 does load the entrances we are writing, and NearInfinity fails to display the map in the SAV file, with something like:
```
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: class org.infinity.resource.cre.Iwd2Struct cannot be cast to class org.infinity.resource.are.Song (org.infinity.resource.cre.Iwd2Struct and org.infinity.resource.are.Song are in unnamed module of loader 'app')
```

**Comment by lynxlynxlynx** [comment]
Is this with the latest release? It added the ability to add song headers, so maybe something is wrong there. IWD2 uses the 9.1 format, so I've hit problems due to that in NI before.

**Comment by MarcelHB** [comment]
An original save game does load in NI, of the ones created by newest master, none does.

**Comment by lynxlynxlynx** [comment]
It works here, except for the visual area display, which doesn't finish loading even with ancient gemrb saves. So nothing new, but definitely something to address at some point. iediffing AREs or diving into NI code would be a good start — why is NI stricter than the original?

**Comment by MarcelHB** [comment]
Ok, then that's a different problem we can address elsewhere, or maybe even ask the NI author directly.

What I was up to: IWD2 currently has the doors and displays travel cursors, but clicking them doesn't do anything with our saves, PCs don't move there. I have a déjà-vu about this, but I haven't found it in the issue history yet.

**Comment by lynxlynxlynx** [comment]
Which area are you looking at? I've now played up to the outside of the horde fortress and had issues only with two entrances in Targos. Judging from the searchmap it looks like the lack of diagonal pathfinding is to blame.

**Comment by MarcelHB** [comment]
So this is what the save  game looks like in GemRB:
![iwd2_savegame_gemrb](https://github.com/user-attachments/assets/5231fff3-6a1e-4dde-9924-d7109edd6f1f)

And this is what happens when loaded in the original game:
![iwd2_savegame](https://github.com/user-attachments/assets/5f421db5-d688-49ca-b287-f37e134f36c3)

**Comment by lynxlynxlynx** [comment]
Oh, you mean gemrb saves don't have working travel regions when opened in the original.
