### ISSUE TITLE
Highlight empty containers in gray instead of cyan

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#2126]
It's a component in eeex. Since we externalized the colors to colors.2da, it's easy to see where we set  the container colors. Checking if it's empty or not can be done through its Inventory instance and the whole thing should be contingent on a new GUIEnhancement bit being set (32 at this point).

**Comment by ca1eigh** [comment]
Hi! Is this issue still open? I would like to work on it if possible. Thanks!

**Comment by lynxlynxlynx** [comment]
Hah, what a question, you can see it was just opened. :)
Let me know what sort of guidance you need; a good first step is to set up a build environment, make a successful build.
