### ISSUE TITLE
[bug] BG2: Shadow Jailor doesn't drop anything

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#213]
**Description**
A minor issue I have encountered during several playthroughs with different installations of BG2 and BGT-weidu is this: The Shadow Jailor (RNGSHA04.cre) in the Temple north of Umar Hills is supposed to drop a leather armor and the key to the cell Mazzy Fentan is held in (KEY22.itm - Shadow Prison Key). It has these items in its inventory alright, but they're not dropped if it is killed.

**GemRB version**
Noticed with GemRB 0.84 and 0.85

**Expected behavior**
Drop items so that they can be picked up from the floor

**Comment by lynxlynxlynx** [comment]
Works for me, do you have some mod mucking with him?

Btw, ctrl-m gives you a debug dump of things pointed at with the mouse. For actors that includes scripts, inventory and much more.

**Comment by caillean7** [comment]
Perhaps it is a mod... checked him with weidu:

Mods affecting RNGSHA04.CRE:
00000: /* created or unbiffed */ BG2FIXPACK/SETUP-BG2FIXPACK.TP2 0 0 // BG2 Fixpack - Core Fixesv13
00001:  SETUP-D0QUESTPACK.TP2 0 1 // Creature & Area ImprovementsAll Creature & Area Improvementsv3.3
00002:  SETUP-NSCPORTRAITS.TP2 0 1 // Portraits for BG2 and ToBv3.0
00003: /* acted upon in an undefined manner */ GENERALIZED_BIFFING/GENERALIZED_BIFFING.TP2 0 0 // Generalized Biffingv2.2

**Comment by caillean7** [comment]
I think I found it. It's  the Creature Improvements component from the Questpack. It adds a script to that creature:
`IF`
`	Die()`
`THEN`
`	RESPONSE #100`
`		CreateVisualEffectObject("D0QPSHAD",Myself)`
`		SmallWait(3)`
`		DestroySelf()`
`END`

Debug Output for the Shadow Jailor just in case:

[Actor/DEBUG]: Debugdump of Actor Shadow Jailor (Shadow Jailor, Shadow Jailor):
Scripts: d0qpshad <none> <none> <none> shoutdlg <none> <none> wtasight
Area:       ar1401 ([1160.560])   Dialog:     rngsha04
Global ID:  10107   PartySlot: 0
Script name:rngsha04    Current action: -1    Total: 0
Int. Flags: 0xc50a00    MC Flags: 0x0    TalkCount:  1   
Allegiance: 255   current allegiance:255
Class:      170   current class:170    Kit: 16384 (base: 16384)
Race:       132   current race:132
Gender:     4   current gender:4
Specifics:  0   current specifics:0
Alignment:  33   current alignment:33
Morale:     10   current morale:10
Moralebreak:0   Morale recovery:1
Visualrange:30 (Explorer: 0)
Fatigue: 0 (current: 0)   Luck: 0

Levels (average: 5):

current HP:60
Mod[IE_ANIMATION_ID]: 0x7703 ResRef:mshd Stance: 1
TURNUNDEADLEVEL: 0 current: 0
Colors:       1263225675   1263225675   1263225675   1263225675   1263225675   1263225675   1263225675
WaitCounter: 0
LastTarget: 0 <NULL>    LastSpellTarget: 0 <NULL>
LastTalked: 10003 jaheira
INVENTORY:
 7:  immune1 - (0 0 0) Fl:0x2029 Wt: 0 x 0Lb
 8:   ring95 - (0 0 0) Fl:0x2029 Wt: 0 x 0Lb
10:     FIST - (1 0 0) Fl:0x2029 Wt: 0 x 0Lb
19:   leat01 - (0 0 0) Fl:0x2c21 Wt: 0 x 15Lb
21:    key22 - (0 0 0) Fl:0x2d01 Wt: 0 x 0Lb
35: shadowwp - (1 0 0) Fl:0x2069 Wt: 0 x 0Lb
Equipped: 0       EquippedHeader: 0
Total weight: 15
SPELLBOOK:
 Known spells:
  0:  spwi112 L: 0 T: 1
 Memorized spells:
  0:  spwi112 1
  1:  spwi112 1
  2:  spwi112 1
  3:  spwi112 1
  4:  spwi112 1
 Known spells:
  0:  spwi212 L: 1 T: 1
 Memorized spells:
  0:  spwi212 1
  1:  spwi212 1
  2:  spwi212 1
  3:  spwi212 1
  4:  spwi212 1
 Known spells:
  0:  spwi308 L: 2 T: 1
  1:  spwi306 L: 2 T: 1
  2:  spwi304 L: 2 T: 1
 Memorized spells:
  0:  spwi304 1
  1:  spwi304 1
  2:  spwi306 1
  3:  spwi308 1
  4:  spwi308 1
 Known spells:
  0:  spwi415 L: 3 T: 1
  1:  spwi402 L: 3 T: 1
 Memorized spells:
  0:  spwi402 1
  1:  spwi402 1
  2:  spwi415 1
  3:  spwi415 1
 Known spells:
  0:  spwi508 L: 4 T: 1
  1:  spwi504 L: 4 T: 1
  2:  spwi501 L: 4 T: 1
  3:  spwi502 L: 4 T: 1
  4:  spwi505 L: 4 T: 1
 Memorized spells:
  0:  spwi501 1
  1:  spwi502 1
  2:  spwi505 1
  3:  spwi504 1
  4:  spwi508 1
 Known spells:
  0:  spwi604 L: 5 T: 1
  1:  spwi602 L: 5 T: 1
  2:  spwi601 L: 5 T: 1
 Memorized spells:
  0:  spwi601 1
  1:  spwi602 1
  2:  spwi604 1
EFFECT QUEUE:
  0: 0x127: DisableChunk (0, 1) S:
  1: 0x78: Protection:Weapons (-1, 2) S:immune1
  2: 0x65: Protection:Opcode (0, 24) S:ring95
  3: 0xce: Protection:Spell (-1, 25) S:ring95
  4: 0xce: Protection:Spell (-1, 25) S:ring95
  5: 0xce: Protection:Spell (-1, 25) S:ring95
  6: 0x10b: Protection:String (14017, 25) S:ring95
  7: 0x10b: Protection:String (14662, 25) S:ring95
  8: 0x65: Protection:Opcode (0, 25) S:ring95
  9: 0x10b: Protection:String (14001, 39) S:ring95
 10: 0x65: Protection:Opcode (0, 217) S:ring95
 11: 0x65: Protection:Opcode (0, 39) S:ring95
 12: 0x65: Protection:Opcode (0, 93) S:ring95
 13: 0x65: Protection:Opcode (0, 134) S:ring95
 14: 0x10b: Protection:String (14791, 128) S:ring95
 15: 0x10b: Protection:String (14782, 128) S:ring95
 16: 0x128: Protection:Animation (0, 128) S:ring95
 17: 0x65: Protection:Opcode (0, 128) S:ring95
 18: 0x65: Protection:Opcode (0, 3) S:ring95
 19: 0x128: Protection:Animation (0, 5) S:ring95
 20: 0x10b: Protection:String (14780, 5) S:ring95
 21: 0x10b: Protection:String (14672, 5) S:ring95
 22: 0x10b: Protection:String (8364, 5) S:ring95
 23: 0x65: Protection:Opcode (0, 5) S:ring95
 24: 0x65: Protection:Opcode (0, 175) S:ring95
 25: 0x65: Protection:Opcode (0, 109) S:ring95
 26: 0xad: PoisonResistanceModifier (100, 0) S:ring95
 27: 0x65: Protection:Opcode (0, 55) S:ring95
 28: 0xce: Protection:Spell (0, 0) S:ring95
 29: 0x10b: Protection:String (41616, 216) S:ring95
 30: 0x10b: Protection:String (40979, 216) S:ring95
 31: 0x10b: Protection:String (40969, 216) S:ring95
 32: 0x10b: Protection:String (40968, 216) S:ring95
 33: 0x10b: Protection:String (41495, 216) S:ring95
 34: 0x65: Protection:Opcode (0, 216) S:ring95
 35: 0x10b: Protection:String (14043, 45) S:ring95
 36: 0x65: Protection:Opcode (0, 210) S:ring95
 37: 0x65: Protection:Opcode (0, 45) S:ring95
 38: 0xce: Protection:Spell (0, 0) S:ring95
 39: 0xce: Protection:Spell (0, 0) S:ring95
 40: 0xce: Protection:Spell (0, 0) S:ring95
 41: 0xce: Protection:Spell (0, 0) S:ring95
 42: 0xce: Protection:Spell (0, 0) S:ring95
 43: 0xce: Protection:Spell (0, 0) S:ring95
 44: 0x128: Protection:Animation (0, 106) S:ring95
 45: 0x10b: Protection:String (17427, 106) S:ring95
 46: 0x10b: Protection:String (14007, 106) S:ring95
 47: 0x10b: Protection:String (14665, 0) S:ring95
 48: 0x65: Protection:Opcode (0, 106) S:ring95
 49: 0x10b: Protection:String (14665, 0) S:ring95
 50: 0x10b: Protection:String (340, 0) S:ring95
 51: 0x10b: Protection:String (384, 0) S:ring95
 52: 0x10b: Protection:String (915, 0) S:ring95
 53: 0x10b: Protection:String (1473, 0) S:ring95
 54: 0x10b: Protection:String (8823, 0) S:ring95
 55: 0x10b: Protection:String (17404, 0) S:ring95
 56: 0x10b: Protection:String (1280, 0) S:ring95
 57: 0x10b: Protection:String (14102, 0) S:ring95
 58: 0x128: Protection:Animation (0, 0) S:ring95
 59: 0x128: Protection:Animation (0, 0) S:ring95
 60: 0x65: Protection:Opcode (0, 23) S:ring95

**Comment by lynxlynxlynx** [comment]
If you select multiple lines and use the toolbar to do the quote, it will be more readable. I've removed the debug dump, since it's not useful.

So it appears in your case DestroySelf() is somehow ran before he dies completely.

**Comment by caillean7** [comment]
Yes, he gets destroyed before finished dying. Not that sounds weird. If I remove the override script with NI, he drops his stuff alright.

Question is now, do you need / want to address this issue (or, for that matter, every little issue that might pop up due to mod x meddling with game file y)? I feel I might just be wasting your time here. So do you have a rule of thumb what kind of issues you want reported at this stage of GemRB's development?

**Comment by lynxlynxlynx** [comment]
All issues. Mods should work; sure, some are broken and maybe we wouldn't want to accommodate them, but in general we go to great lengths to do so, since mods are life. A good example would be the oozemaster kit from divine remix, which we do support, regardless of the hoops it required due to the way the original mod was coded.

But also, mods exercise behaviour that's not seen in the original, so in essence they provide more tests for correctness, which is always good.

**Comment by caillean7** [comment]
>  mods are life

Nicely put, my feelings exactly. As a non-programmer and someone with no real insight into your project, it is a little hard to judge what issues are valid. Plus, since you moved to GitHub, I imagine a lot of 'non-geeky' folks find this site and the procedures here a little intimidating, registering on a forum like G3 and post there might be less 'daunting' - if players are willing to spent time on reporting and testing at all. But if you want that feedback from players with modded games, that's good to know. Now, just because I want to tell you guys this once how awesome GemRB is and how much I admire your skill and dedication. Has to be said beside all the complaints and bug reports.

**Comment by lynxlynxlynx** [comment]
Thanks and don't worry, bug reports are not taken personally. :) It's the only way we can improve consistently, since even when the developers play the game, we won't see all the facets.

The forums are still ok for reporting, but bug trackers are better. With how the community finally embraced version tracking and github, it's the right time to move here (the old on SF: nobody has an account for that, wiki: not fit for discussions). This way we avoid forum posts with 10 reports in one, curation is much easier, we can categorize, flag things that are easy to fix for newcomers and directly reference changes, code and other reports. It's better for everyone involved.

**Comment by caillean7** [comment]
Affects also Shadow Patrick (RNGSHA02.cre/RNGSHA2D.cre). Possibly more. Scripts added / appended by the questpack also have this effect on death which prevents drops.

**Comment by lynxlynxlynx** [comment]
I've changed it so we dump the safe stuff immediately. Please retest.

**Comment by caillean7** [comment]
Works, now I get my loot, thanks!
