### ISSUE TITLE
IWD2: Standing above a pile should list items in inventory's dropped column

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2135]
#### Bug description
If some PC is supposed to pick items from the ground, and when the pick up window has openend, the same items should be shown in the dropped column of the inventory when directly switching to it.

Works in BG, BG2, PST (if we notice the scrollbar being at the end), but apparently not in IWD2.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
This is indeed a regression, but it's not limited to iwd2 for me. I just retried bg2 and 3 dropped piles didn't work nor the aggregated one from ctrl-w.

I think we match by position (piles have generated names) and it's broken probably since the first major pathfinder update.

**Comment by MarcelHB** [comment]
It work, sometimes. Turns out that the searchmap translation is just off-by-one here and there.

**Comment by MarcelHB** [comment]
This should be reverted: 7260ed326ae5aac1d217bdfdb1a5f2e4c4a71eee

It was previously aligned to the current SM cell, then its center + some bbox. Now it's the exact point + (8, 6). Alternatively, the PC must be placed (-8, -6) for picking up something so that this one matches.

**Comment by lynxlynxlynx** [comment]
Looks like I was too sloppy indeed.
