### ISSUE TITLE
IWD2 travel region incompatibility

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#2137]
So this is what the save  game looks like in GemRB:
![iwd2_savegame_gemrb](https://github.com/user-attachments/assets/5231fff3-6a1e-4dde-9924-d7109edd6f1f)

And this is what happens when loaded in the original game:
![iwd2_savegame](https://github.com/user-attachments/assets/5f421db5-d688-49ca-b287-f37e134f36c3)

It's the same for every local travel point I've tested,

_Originally posted by @MarcelHB in https://github.com/gemrb/gemrb/issues/2125#issuecomment-2358060737_

**Comment by MarcelHB** [comment]
Broke somewhere between v0.9.1 and v0.9.2 ... will dive deeper.

**Comment by MarcelHB** [comment]
It's 11f146274742bc65596f9ab62d97b50259befbeb or later since this particular one makes the original crash.

**Comment by MarcelHB** [comment]
Looks like override and alternate point don't get their Y values set.
