### ISSUE TITLE
 IWD2: CharGen sometimes hangs around portraits

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2139]
#### Bug description
That's somewhat ugly since it may completely vaporize your efforts to create a party in the last minute. I've had it twice by now, and so far it happened after PC 3 or 4, when choosing for male or female character. Clicking the choice then freezes the game before getting to the portraits.

Unfortunately, I haven't found a way to reproduce it reliably expect it always happend for female PCs. Given the stacktrace below, I'm suspecting that this loop never finishes:

https://github.com/gemrb/gemrb/blob/9e59cbda257f55c086ed6a7930aeb6fb04964938/gemrb/GUIScripts/iwd2/CGPortrait.py#L79-L83

Maybe `LastPortrait` is rolled into something bad that makes it loop into eternity.

#### Screenshots
```
(gdb) bt
#0  0x00007ff9807c43c0 in msvcrt!memmove () from C:\Windows\System32\msvcrt.dll
#1  0x00007ff9554d05a7 in ?? () from C:\MSYS2\mingw64\bin\libstdc++-6.dll
#2  0x00007ff90ff92a1c in GemRB_Table_GetValue (self=0x1b25ae60, args=0x11336f40)
    at D:/Sources/gemrb/gemrb/plugins/GUIScript/GUIScript.cpp:675
#3  0x00007ff946ddd2eb in ?? () from C:\MSYS2\mingw64\bin\libpython3.11.dll
#4  0x00007ff946da0c75 in ?? () from C:\MSYS2\mingw64\bin\libpython3.11.dll
#5  0x00007ff946e5d375 in ?? () from C:\MSYS2\mingw64\bin\libpython3.11.dll
#6  0x00007ff946e55f34 in ?? () from C:\MSYS2\mingw64\bin\libpython3.11.dll
#7  0x00007ff946da04a1 in ?? () from C:\MSYS2\mingw64\bin\libpython3.11.dll
#8  0x00007ff90ffc3442 in GemRB::GUIScript::RunFunction (this=0xbbb6ad0,
    moduleName=0x20a2e790 "CGPortrait",
    functionName=0x7ff911c8d604 <GemRB::IDT_SKILLPENALTY+3036> "OnLoad", pArgs=0x7ff946f0a4d8,
    report_error=true) at D:/Sources/gemrb/gemrb/plugins/GUIScript/GUIScript.cpp:13519
#9  0x00007ff90ffc3314 in GemRB::GUIScript::RunFunction (this=0xbbb6ad0,
    Modulename=0x20a2e790 "CGPortrait",
    FunctionName=0x7ff911c8d604 <GemRB::IDT_SKILLPENALTY+3036> "OnLoad",
    params=std::vector of length 0, capacity 0, report_error=true)
    at D:/Sources/gemrb/gemrb/plugins/GUIScript/GUIScript.cpp:13484
#10 0x00007ff9119dba7b in GemRB::ScriptEngine::RunFunction (this=0xbbb6ad0,
    Modulename=0x20a2e790 "CGPortrait",
    FunctionName=0x7ff911c8d604 <GemRB::IDT_SKILLPENALTY+3036> "OnLoad", report_error=true)
    at D:/Sources/gemrb/gemrb/core/ScriptEngine.cpp:55
#11 0x00007ff911991a8c in GemRB::Interface::HandleFlags (this=0x5ff2b0)
    at D:/Sources/gemrb/gemrb/core/Interface.cpp:835
#12 0x00007ff9119926d0 in GemRB::Interface::Main (this=0x5ff2b0)
    at D:/Sources/gemrb/gemrb/core/Interface.cpp:983
#13 0x00007ff6c9c11657 in main (argc=1, argv=0xdf63e0)
    at D:/Sources/gemrb/platforms/windows/GemRB.cpp:63
```

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
I think in at least one of the other copies we have some manual protection against infinite loops. We can reuse that; it maybe becomes redundant with the unmerged refactors, but why wait.

**Comment by MarcelHB** [comment]
I don't see a reason to loop at all, there is a roll into either half of the list ... given that this list remains sorted this way, but it's ours anyway. I look at it.

**Comment by lynxlynxlynx** [comment]
This whole thing might be from the changes to table reading, where now GetValue can return None. But yeah, we have better ways to find the first entry with a matching gender.
