### ISSUE TITLE
 IWD2: CharGen does not assign voice set prefix

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2141]
#### Bug description
The CRE files that I found in the game created by GemRB lack what NI calls _Voice Set prefix_, like the set `male_fighter_1` has the prefix `DMC_` for all files of the set.

So all PCs remain mute.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
Trivial: NextPress in CSound.py does not set the value in the actor, it currently only happens if you press play.

**Comment by lynxlynxlynx** [comment]
Actually it was already being set through preselection and something wipes PCStats->SoundSet.
