### ISSUE TITLE
 PCs run around to the north-west of an enemy for close combat

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2142]
#### Bug description
It's an interesting problem I have observed multiple times by now across games, you can even see it here: https://github.com/gemrb/gemrb/issues/2130 -- TNO has been sent from the south/south-east to attack Ignus but took position at that particular location to the north-west first. That should not have been necessary, of course.

It's easily reproducible under many close combat situations. It's not helpful for combat since it makes you lose time.

#### Screenshots

So place a PC somewhere SE and choose an enemy (green) to engage. I'd expect to rush to purple and attack, but no, sight-seeing first:

![attack_path2](https://github.com/user-attachments/assets/b683962f-03cd-41a8-bc40-d10ba24c8e60)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
Can confirm, but the only thing that comes to mind is that it's maybe related to weapon range. Daggers and the like with minimal range. However, we do take personal distance into account, so that's unlikely.

**Comment by lynxlynxlynx** [comment]
A quick test gives me the impression this wasn't a problem in 0.9.2, but already in 0.9.3. So another thing to bisect.

**Comment by lynxlynxlynx** [comment]
Actually it must be older, so looking at history is probably useless.

**Comment by lynxlynxlynx** [comment]
It's the `AdjustPositionNavmap` call in `FindPath` and just a general bias. We need to take the orientation into account and try that direction first.
