### ISSUE TITLE
 IWD2: Morale recovery zero

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2143]
#### Bug description
If one of the PCs has broken morale, I can't get them recovered. Ctrl+M says the following:

```
[Actor/DEBUG]: Debugdump of Actor Nummer Vier (Nummer Vier, Nummer Vier):
Scripts: <none> <none> <none> <none> <none> <none> <none> <none>
...
Morale:     1   current morale:1
Moralebreak:5   Morale recovery:0
```

Looks like recovery will never happen then: https://github.com/gemrb/gemrb/blob/b52ca94e41f2f251209b1900900b4473c1e11ffc/gemrb/core/Scriptable/Actor.cpp#L2947-L2950

In contrast, this is a healthy one, but also no positive recovery:
```
Debugdump of Actor Nummer Drei (Nummer Drei, Nummer Drei):
...
Morale:     96   current morale:96
Moralebreak:5   Morale recovery:0
```

I'd say that this values lacks an assignment somewhere. BG1 in contrast looks good on a new game.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
charbase has it at 60, so something went wrong.

**Comment by MarcelHB** [comment]
Yep, reading is skipped since refactoring there.

**Comment by MarcelHB** [comment]
Hm, original sets 1 in the file whereas other games such as BG set 60 there. I'd consider multiplying this value by sixty to be consistent with the rest for now.

**Comment by lynxlynxlynx** [comment]
Sounds fine, less complexity elsewhere.

**Comment by MarcelHB** [comment]
Uncovers another bug that _sometimes_ doesn't put the PC out of the yellow circle, and prevents saving. Trying to dig through.

**Comment by lynxlynxlynx** [comment]
There are codepaths where we set STATE_PANIC potentially permanently, if that's the thing that caused your yellow.
