### ISSUE TITLE
Problems around leaving morale panic

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2145]
#### Bug description
As discussed in #2144 and #2143, fixing the reading shows some more problems that potentially keep you from saving the game (that's what I observed, but not sure if fully related).

1. If morale panic rolls into bezerking, relief from panic won't fix the yellow circle, since it also looks at `IE_CHECKFORBERSERK` that isn't reset when morale has recovered.
2. If during bezerking-panic the PC attacks an enemy successfully, the morale value rises beyond the threshold, but the recovery is defined over a step-wise increase from below, leaving a now high morale PC panicking, also after cooldown.

#### Steps to reproduce
Easy way to check is this IWD2 savegame, when #2144 has merged: There is one PC that currently panics and may attack the barrels, so we can see both cases after some loading runs.
[000000001-Quick-Save.zip](https://github.com/user-attachments/files/17075151/000000001-Quick-Save.zip)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
Nr. 6 is at -7 morale in the save and the recovery is busted, but nr. 4 is a good test at 1/5/60.
