### ISSUE TITLE
 IWD2: destroying barrels gives XP rewards

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2147]
#### Bug description
Destroying barrels (like on AR2000) gives a bunch of XP (37), and that isn't the case for the original. The associated CRE file `20KEG2` has the ~~XP~~ XP power level value set to 0.

#### Screenshots

![iwd2_barrels](https://github.com/user-attachments/assets/13cdb479-8063-4f9e-a79f-78c4652ad926)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
That value is not used like in other games, iwd2 has a table that uses the next xp stat (CR; Power level in NI). 0 is perhaps not a valid value, though I see other creatures with it, like 00szmbl2.

**Comment by MarcelHB** [comment]
Keg is not the only case. I guess I got 375 or something for every drum in AR3000 https://youtu.be/zebx5cBXuzo?feature=shared&t=21992

**Comment by lynxlynxlynx** [comment]
Hmm. IE_GENERAL == 0 would catch all, but it looks a bit too much as well. I'll figure something out.
