### ISSUE TITLE
 BG2: Hand does not appear in inventory in sewer riddle

### ISSUE THREAD

**Issue by jpalus** [gemrb/gemrb#2149]
#### Bug description
In the sewer riddle quest when I reach out for a hand in the middle of sewer room I see in the dialog box that hand was found but it is not actually placed in inventory. All 3 other items are fine though.

#### Steps to reproduce
1. Go to sewers under  Copper Coronet
2. In the first room (first turn right after entering sewers) interact in the middle to get a hand

#### Expected behavior
Hand is placed in inventory

GemRB version (check as many as you know apply)
- [ ] master as of this issue
- [X] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `OPENGL_BACKEND` enabled
- [X] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
Did you have a full inventory already?

**Comment by lynxlynxlynx** [comment]
Nevermind, can reproduce. LastTrigger is not being set properly any more.
In the interim, you can pop open the console and run `ci("MISC5S")`.
