### ISSUE TITLE
 BG1: Missing gold message at start

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#2154]
#### Bug description
Starting a new game on BG1 after the prologue you have a nice message that now you have 120 gold on the original. 
It is missing on Gemrb.

#### Steps to reproduce
1. Go to Start a new game
2. Create character
3. Skip prologue

#### Expected behavior
It show the message that the party has now 120 gold

#### Screenshots
Original
![image](https://github.com/user-attachments/assets/d4794109-2f8a-477e-ab61-06756fec3c94)
Gemrb
![image](https://github.com/user-attachments/assets/20846b90-914b-4882-883a-ca4fa7d1e1bc)

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `OPENGL_BACKEND` enabled
- [X] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
I'm not sure this is worthy of fixing.
We give the gold directly in `gemrb/GUIScripts/bg1/CharGenGui.py:339`
`GemRB.GameSetPartyGold(x, 1)` could be used instead, but I'm not sure the message window is available at that point, so perhaps there'd be no difference.
