### ISSUE TITLE
 BG1: Opening the inventory gives an empty state

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#2155]
#### Bug description
Opening the inventory gives an empty data

Saving and reloading fix the error.

#### Steps to reproduce
1. Go to learn to fight with a party
2. Click on Hull and take the quest
3. Talk to Hull again because you already has the sword.

#### Expected behavior
The stuff is still shown.

#### Screenshots

![image](https://github.com/user-attachments/assets/46b2e3a0-f029-4265-a4ab-a552f484615d)

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `OPENGL_BACKEND` enabled
- [X] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
Closing. If you hit it again, do save the log.
