### ISSUE TITLE
 IWD2: Orc animation MOR1cae can't be created

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2156]
#### Bug description
On IWD2 AR2000, one orc animation reliably fails, making the orc disappear for a few seconds. Log says:
```
[CharAnimations/ERROR]: Couldn't create animationfactory: MOR1cae (0xe818)
```
I can't find such a BAM either.

#### Steps to reproduce
1. AR2000, trigger the orc wave behind the barrels.

#### Screenshots
![iwd2_orc_anim](https://github.com/user-attachments/assets/d186ce0b-2664-47b1-ad06-d85292230f5f)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
That's a casting animation, not something I'd expect from a grunt. Maybe they rage or something similar, is there anything in the message window?
We have stance.2da to easily override such problems; it could also be that just the animation type needs to be changed (iirc one of 9 and 16).

**Comment by MarcelHB** [comment]
Well, the orc actually casts something, Silence? That's what I see in the original:
![iwd2_orc_spell](https://github.com/user-attachments/assets/0f39ecda-a3ea-45c8-82a7-c5a0e152cfa0)

**Comment by lynxlynxlynx** [comment]
Still sounds like using some innate ability. And I was spot on with the types - in bg2 we have them marked as 16, 9 in the rest. One of the two marks iwd animations with fewer stances.
