### ISSUE TITLE
[subviews] expose `SetMargins` to GUIScript 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#216]
Ok, had an epiphany. I think everything is working as expected now.

The only thing remaining that I am aware of is the need to expose `SetMargins` to GUIScript so that we can counteract the overflow caused by the frame hacking required by the  scrollbars.

_Originally posted by @bradallred in https://github.com/gemrb/gemrb/issues/204#issuecomment-529132304_

**Comment by bradallred** [comment]
closing this. The margin issues have been solved a better way. This could still be an enhancement if we wanted a reason to override the CHU tho.
