### ISSUE TITLE
 Heal Party on Rest not working as expected

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2162]
#### Bug description
In IWD2, I have set _Heal Party on Rest_. 

All injured PC health stats before resting:
19/36
6/42
26/36
7/32
23/27

One is 18/18. Then I rent a room (Standard level) and 8h have passed according to message window.

Updated health is now:
21/36
11/42
28/36
9/32
35/27

#### Expected behavior
In the original, all PCs should have been cured in one sleep turn at the price of 1d + 8h when I chose this option.

If I take the equivalent turns (4) in terms of hours in GemRB, I have not only lost more money for renting, the PCs are still not guaranteed to be at full health: e. g. 19/36 only made it to 27/36.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
I guess you mean this:
`gemrb/core/Game.cpp:1827:       // TODO: implement "Rest until healed", it's an option in some games`

**Comment by MarcelHB** [comment]
Hm, maybe. I looked for the variable and found this https://github.com/gemrb/gemrb/blob/a6931a46cdedeef171888c733f5844e7dffc4c64/gemrb/core/Game.cpp#L1945-L1951

I guess that's the variable in question?

**Comment by MarcelHB** [comment]
The native config sets this variable, and according to the description, it's just a matter of time then. Don't know about the other games right now, but according to your implementation many years ago, it's interepreted as consumption of healing spells during rest.

**Comment by lynxlynxlynx** [comment]
If so, then we're not using it right. Easy to test what it toggles though.

**Comment by MarcelHB** [comment]
I see that BG2 really has a different description that makes this kind of implemenation reasonable.

We should check what BG2 really did for this case.

**Comment by MarcelHB** [comment]
It's both things combined, here are some tests:

Test 1, fighter with 1/200 HP: 4d
Test 2, cleric with 1/200 HP, 5x cure light wounds, 3x cure medium wounds, 2x cure serious wounds: 16h
Test 3, both from test 1 and test 2: 1d 8h
Test 4, two fighters 1/200 HP: 7d 16h
Test 5, fighther 1/200 HP + cleric 1/200 HP with 2x serious wounds: 3d 16h

* So unassisted resting gives at least 16HP/8h. 
* Test 4 makes little sense to me as that would mean that two PCs can't heal in parallel.
* Test 3 and 5 point to the direction of base healing rate + healing spells, but also more in serial than in parallel for both PCs.

Healing can be divided into 8h + multiple of 4h, depending on the amount to heal.

**Comment by lynxlynxlynx** [comment]
This was all with the option on, right? With it off, do you get just the base 2/h and 8 hours?

I see in guiopt of bgee that "Rest until healed" is just about repeatedly casting healing spells, so it must be doing full rests, which gives the spells back, until healed. Testing there I get 1hp/h. I think we currently do 1 hp/rest?

In bg1 I get the 1-4hp in taverns per rest, as we have it now, and 1 hp per rest outside.

So it looks like this is different at least between bg1, iwd2 and ees. :/

**Comment by MarcelHB** [comment]
Yes, that was BG2 with this option on.

With the option off: fighter gets 1HP/8h, cleric with spells will apply as much as available on self in one rest-turn, giving me 133HP in this case.

**Comment by lynxlynxlynx** [comment]
> iwd2: Heal Party on Rest - Enables/disables healing the party to full hit points when the Rest button on the main screen is pressed.  Default: On
> bg2: Enable this option to cast healing spells on resting repeatedly until fully healed.  Otherwise currently memorized healing spells are cast once on resting.

iwd2 matches descriptions in iwd1, where one can see players complaining that autocasts were always happening in inns. So it seems to me everything matches and we should make it the same everywhere:
- if the option is off, do the casts once
- if it is on, repeat until the party is healed
