### ISSUE TITLE
 IWD2: slings cause unknown type of damage

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2163]
#### Bug description
When you equip someone with a plain-simple sling and regular bullets, the damage that is being caused is _unknown_ and enemies get struck by some red lightning. Damage degree looks normal though.

#### Screenshots

![iwd2_sling_damage](https://github.com/user-attachments/assets/3724a111-3f17-4421-8c5b-63f97653b898)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
If it's not a damage type string bug, the other thing that comes to mind is that some games also have composite damage types like missile-blunt IIRC. Breaking on `Actor::DisplayCombatFeedback` should make it easy to find at least the surface cause.

**Comment by MarcelHB** [comment]
Not sure about the proper translation but the original displays the same damage type as done by maces.

damagetype is 8308, and from what I see in the bit pattern that's many different types of damage. That comes from the projectile.

**Comment by lynxlynxlynx** [comment]
0x8308 or 8308? Either way an odd value.

**Comment by MarcelHB** [comment]
8308, decimal.

**Comment by lynxlynxlynx** [comment]
It's supposed to be a bitfield and that's divisible only by 4, hah. Something interesting must be going on.
Looking at a regular bullet, it has blunt-missile (9) damage type set, unlike iwd1 where it's just missile (4). So I was spot on, but there's likely something more going on besides the unhandled type.
