### ISSUE TITLE
 IWD2: Are we doing difficulty/attack/armor correctly?

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2164]
#### Bug description
It's somewhat hard to exactly pinpoint this problem, and it's more like a skewed observation when comparing IWD2 original vs. our implementation: The game is much harder as PCs tend to be injured faster. On the other hand, attacking enemies doesn't feel easier in the same way, so the whole system isn't balanced symetrically.

Let's look at the following situation:

![iwd2_orkinator](https://github.com/user-attachments/assets/8d91467d-b380-4711-97de-c00340d6abbd)

This guy is a level 3 fighter, dex 12, plate mail -> armor value 17. Regular two-handed sword with 2 points on this weapon class. The character sheets look identical in both games, so we can likely rule out any reading issues of values.

In the original, lowest difficulty, this guy can single-handedly take out the whole orc crowd, and _maybe_ requires a health support while doing so.

In GemRB, four to all five orcs will probably live after they have killed him quickly, and even though the archers don't keep their distance and should suffer from a penalty.

Btw. GemRB sets the left-most diff. value to `Difficulty Level = 0` whereas the original uses `Difficulty Level = 1` but aligning this did not do any difference.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
I also noticed archers seem more likely to hit than I'd expect. But there's definitely a damage calculation problem somewhere (noted concrete example in the meta issue).

**Comment by lynxlynxlynx** [comment]
One thing I suspect is happening is that some actors get treated like they're in HoF and get upgraded to match.

**Comment by lynxlynxlynx** [comment]
feat41 gives a DamageBonusModifier with +20. :O It's a mistake from the get go, it looks like this is Scion of flame feat.

**Comment by lynxlynxlynx** [comment]
Can you try this again? I've fixed all the mentioned damage issues. If it's still a problem, please show me the script names of the orcs.

**Comment by MarcelHB** [comment]
I've played the savegame 10 times in both IWD2 and GemRB:

IWD2: 10 wins, 8 easily
GemRB: 1 win, 9 losses

Looking closer at this: Nobody is doing fake attacks here, right? Yet if we count the number of attacks in a duel by an orc to my fighter, I'd say it's about 1:2.5 for the ork. Sometimes I'd even looks as if the fighter is somehow stunned, but maybe this is pathfinding related.

Given the frequency of hits, maybe its still some armor calculation?

That's one of the orc's script set here:

![iwd2_orc_scripts](https://github.com/user-attachments/assets/6cbbbf26-6c88-4816-b127-a1b5bb83f38a)

**Comment by lynxlynxlynx** [comment]
Yeah but which orc? Areas are full of them and some get deleted based on difficulty.

**Comment by MarcelHB** [comment]
T8_Orc_1 for example.

**Comment by burner1024** [comment]
This is where #1800 would be helpful.

**Comment by MarcelHB** [comment]
I noticed in videos the EE mod for IWD2 has something like this, but it looks more primitive than in your screenshots. Maybe one can tweak this further to do a side-by-side comparison.

**Comment by lynxlynxlynx** [comment]
We have the details in AC and ToHit, but like I said, they are fine. A better thread to investigate would be your comment that the orc appears to attack more often, which suggests we might have an APR calculation problem.

**Comment by MarcelHB** [comment]
That later the game, the more I think the issue isn't applicable at this point any more, i. e. it has turned easier. Figher APR also looks good at level 14, although I can't directly compare it to the original due to breaking savegames.

**Comment by lynxlynxlynx** [comment]
In the end it was limited to slow weapons like the greatsword. Why it wasn't visible later in the game is because you got enchanted weapons and they have lower speeds, so they didn't overflow the length of the combat round.

**Comment by MarcelHB** [comment]
Test was now 5:5, so definetely an improvement.
