### ISSUE TITLE
 IWD2: non-stop goblin patrol spawning in AR3000

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2167]
#### Bug description

In AR3000 and some attached maps, the area of the Goblin fort, there are drums and shamans. When they are not taken down, they summon worg riders.

This should be two of them every once in a while. In GemRB, once started, this looks like a never-ending summoning of worg riders giving us one in 4s, making it virtually impossible to continue here.

#### Steps to reproduce
This save game and walk to the east a little: [000000001-Quick-Save.zip](https://github.com/user-attachments/files/17176816/000000001-Quick-Save.zip)

#### Screenshots

![iwd2_spawn_bug](https://github.com/user-attachments/assets/05078c70-9d37-4cfe-9f23-700a894ca0e4)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
I looked at this when I played through the area, the drums are on a simple timer loop. Needs a deeper dive.

**Comment by lynxlynxlynx** [comment]
I can't even find where the spawning happens now. 😖 
There's drum doors, drum actors, drum hitters, at least one useless variable and no CreateCreature in sight.

**Comment by MarcelHB** [comment]
I also noticed some INI-spawn points.

**Comment by lynxlynxlynx** [comment]
Ah, right. I think I see the problem now.

**Comment by lynxlynxlynx** [comment]
Some fixes went in, but the core issue remains — the ini specifies a 1s spawn timer. The question is why the needed vars get set appropriately so fast as well. The one external timer (between 3-4s) is only used in a special case, so the observed short delay appear to be from accumulated quick Waits and the like.

**Comment by lynxlynxlynx** [comment]
Ah, there's a bug in our TotalQuantity handling, somehow the stat mapping is wrong and we check gender instead of specifics. I think it's just a pst data mismatch, on it.
