### ISSUE TITLE
 Critical Hit feedback too early

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2170]
#### Bug description
Let's say we have a distance attack by an archer. It rolls a critical hit, and then the screen shakes and we may see a message.

But it may take another half of a second, maybe more, until the enemy has been hit, and then maybe even splatters. Not sure about the message but I think shaking should be post-poned to the damage, not during attack, so that it goes in-hand with splatter.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
This could be complicated, but at least for the shake, it should be easy — we can set the Projectile::Shake member on the attack projectile instead of triggering it in `Actor::ModifyWeaponDamage`.

**Comment by lynxlynxlynx** [comment]
As for the text, it would be too complicated, since there's so many things going on — could easily give it in wrong order.
