### ISSUE TITLE
 IWD2: two PCs teleported in AR4100

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2175]
#### Bug description

See this, the party sticks together at the beginnging of AR4100: https://youtu.be/gZyMUExgL4M?feature=shared&t=15038

In GemRB, during the cutscenes, two PCs of the party get teleported to the two spot locations, putting them at high risk since at least at one of the locations there are heavy enemies.

#### Screenshots
![iwd2_ar4100](https://github.com/user-attachments/assets/0eb0b746-08a6-421e-b1d4-84d5d60c2ae1)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
I didn't hit that, but I was playing solo every time I was there. Can you grab their exact coordinates, so we can work backwards to the scripting that caused it?

**Comment by MarcelHB** [comment]
One is (1400, 1566), the other one (1950, 2530).

**Comment by lynxlynxlynx** [comment]
Huh, 41CMOLB2.DLG literally does:
```
SAY #41000 /* ~This glacier's the last thing blocking the Western Pass.  We mustn't fail.~ */
  IF ~~ THEN DO ~JumpToPointInstant(Protagonist,[1950.2530])
StartCutSceneMode()
StartCutScene("41cMOLoc")~ EXIT
```
That and the cutscene that follows seems to use the protagonist as a spy. I don't see where he's taken back, which is odd, since solo I didn't have any issues. Can reproduce this with a party, though.

Worth a bisect, I hope it wasn't the dialog change I just made.
