### ISSUE TITLE
 Some bad pixels in TIS graphics

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2176]
#### Bug description
I only started to notice it in AR4100 of IWD2 that there are some black pixels around. Maybe something key color related.

#### Screenshots

![bad_tis_pixels](https://github.com/user-attachments/assets/3e505074-b16d-41b3-a9c1-a9af69055b80)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
Looks fine here, also SDL2 GL:
![image](https://github.com/user-attachments/assets/c0f58726-9da7-44fe-9bb5-1b8fbf31a406)

**Comment by lynxlynxlynx** [comment]
But it is visible during dusk and night:
![image](https://github.com/user-attachments/assets/6bc2c862-f683-4ab5-89d3-e32b34233d01)

**Comment by lynxlynxlynx** [comment]
ar4000 also has some suspect bits, though nothing so bad:
![image](https://github.com/user-attachments/assets/0ac74440-297d-4187-860b-c6290fd9865a)

visible already in Targos docks:
![image](https://github.com/user-attachments/assets/62bd4700-3339-4a63-9809-61a10579f100)

So probably something on our end.
Btw, you can `ex('AdvanceTime(1800)')` to advance for 6h.

**Comment by MarcelHB** [comment]
Looks like tinting then.

**Comment by lynxlynxlynx** [comment]
Yeah, these areas don't have night weds.
