### ISSUE TITLE
Incorrect Usage of GoogleTest Macros

### ISSUE THREAD

**Issue by bhbuehler** [gemrb/gemrb#2177]
#### Bug description
GoogleTest requires test suite names and test names used in the TEST macro not contain underscores (see https://google.github.io/googletest/faq.html). 
Every file containing tests in `gemrb/test` has tests violating this rule.
#### Steps to reproduce
N/A 

#### Expected behavior
N/A

#### Screenshots
N/A

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [x] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1.1
- [ ] 0.9.1

Video Driver (check as many as you know apply)
N/A

Other
I found this when I started looking into writing a unit test for a change I wanted to make. I will be submitting a pull request fixing the naming issue unless it is not seen as something the project wishes to change.
Admittedly, this bug doesn't appear to cause any bad behavior currently. But it is technically incorrect usage of GoogleTest and it does mean that extra care must be taken with similarly named test cases or tests. For example, there is a `Feed` test in the test case `MurmurHash_Test` in the file `gemrb/test/core/Test_MurmurHash.cpp`. If a test called `Test_Feed` were ever created in a test case called `MurmurHash`, the two `TESTS` would generate the same test case called `MurmurHash_Test_Feed_Test`, which would be undefined if the two were created at the same time.

**Comment by lynxlynxlynx** [comment]
Sure, please fix it. And thanks. 👍🏾

**Comment by lynxlynxlynx** [comment]
@bhbuehler do you have any mergeable work? Soon we'll put #1875 in that will very likely cause conflicts if you already made any commits (otherwise you can just let it be auto-reformatted).

**Comment by lynxlynxlynx** [comment]
Any plans to finish this or should we take over?

**Comment by bhbuehler** [comment]
@lynxlynxlynx Thank you for reaching out.
I should have done so myself.
My git skills are not complete and I needed to look up how to fix a botched merge and got sidetracked.
Since you believe #1875 will conflict regardless, it sounds like it would be easier to get rid of my old work and make the changes on a new branch off HEAD?
Regardless, I plan to have this done by 2024-12-14 and if it is not finished, you should take over.
Alternatively, I would not be offended if you or someone else preferred to takr over now because it has been so long.

**Comment by lynxlynxlynx** [comment]
If you're fighting git it might indeed be easier to start over, yes. Especially now that I checked that #1875 will indeed conflict, since the lines with the names of the tests were modified.
So I suggest you make it easier on yourself and start from a clean slate. Isn't this something that can be done with a regex search and replace? Definitely not worth wading through merge conflicts for that.
