### ISSUE TITLE
 IWD2: Stuck in wrong store mode after completing Conlan quest

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2181]
#### Bug description
After completing Conlan's quest (finding the son), I cannot save any more or enter any store window around.

#### Steps to reproduce
1. Find Sheemish in Kuldahar
2. Return to Conlan.
3. Choose response 26 (found your son...)
4. Choose response 43 (glad to help...)

Now try to save or buy something from Conlan. Won't work.

I suspsect there is something wrong with the implementation of this script that sits on response 43.
```
ChangeStoreMarkup("60Sheemi", 110, 60, 20)
```

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
Another one from my list. If you look at the log it will have a smoking gun. It should open with the dialog and then close properly, so the printed error is probably spot on. Same for you suspicion, since that code wasn't touched in ages, eg. last time Tomsod added nested bag support.

**Comment by lynxlynxlynx** [comment]
I'll take a look, could be just a missing SaveStore call.
