### ISSUE TITLE
 IWD2: Can't initiate dialog to rejoin group

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2185]
#### Bug description
The join dialog doesn't work. The PC will stay out of the party. Not sure what was happening originally here.

#### Steps to reproduce
1. Have a PC that gets petrified.
2. Apply Stone to Flesh.
3. Try to talk to the PC.

#### Screenshots
Shortly there is some window flashing up but the log says:

```
[ResourceManager/ERROR]: Couldn't find 'MULTIJ.dlg'.
[DialogHandler/ERROR]: Cannot start dialog (MULTIJ): X with Y
```

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by MarcelHB** [comment]
Instant rejoin in the original, no dialog.

**Comment by lynxlynxlynx** [comment]
That should simplify things. :) IWD2 ships a leftover pdialog.2da or this bug wouldn't happen (GameScript::JoinParty). So we just need to add an empty file into override/iwd2.
