### ISSUE TITLE
 IWD2: Can't talk to amabassador Jasper in AR6104

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2192]
#### Bug description
In AR6104, this time loop map, the first time I'm encountering ambassador Jasper and attempt to talk to him, nothing happens. I see that for maybe one frame the dialog window opens, so it looks like, but then it's gone again. No Python error or anything else, so we are stuck here.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
It sounds like he can't find a valid dialog state. I've never had this problem and about a month ago had maybe a hundred conversations with him (nor anything during the full run). :s

So you talk to the boat guy for the first time and get ferried for the first time and talk to the guy directly?

**Comment by MarcelHB** [comment]
There was a frost giant to kill after the ferry, but yes, that's where I am.

**Comment by lynxlynxlynx** [comment]
Ok, can reproduce, must be a very recent regression.

**Comment by MarcelHB** [comment]
Still doesn't work, do I have to fix something in the save?

**Comment by lynxlynxlynx** [comment]
Sorry, yes, actor dialog resrefs. Would be easier to start the area anew.
