### ISSUE TITLE
 BG2: Garren Windspear cut scene never completes

### ISSUE THREAD

**Issue by jpalus** [gemrb/gemrb#2194]
#### Bug description
After following Garren Windspear on first encounter, we had a chat in his cabin, which should end up in him leaving to talk my case with his friends. The cut scene starts, he makes a move towards door but does not actually leave and cut scene never ends.

The only suspicious thing that I see in console is:
```
[GameScript/DEBUG]: CutSceneID was called by garren!
```

#### Steps to reproduce
1. Talk to  Lord Jierdan and start Journey to the Windspear Hills quest
2. Go to Windspear Hills
3. Kill "monsters"
4. Talk to Garren
5. Follow him into cabin
6. Talk to Garren more
7. Observe cut scene

#### Expected behavior
Cut scene ends and game continues.

GemRB version (check as many as you know apply)
- [ ] master as of this issue
- [X] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [X] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
Do you have a save from the cabin, before you speak to him?

**Comment by jpalus** [comment]
That's another story that seems to be bugged somehow or perhaps it's not possible to save this intermediary state.

If I make a save before entering cabin and load it again Garren is not there inside anymore. What seems to happen instead is likely what should have happened if Garren left -- only Iltha is there, she talks to me, then Taar enters with info about bandits. When they're dead cut scene starts again and also never completes, this time with following error logged:
```
[GameScript/ERROR]: ActionOverride failed for object and action: 
[GameScript/DEBUG]: Int0: 0, Int1: 0, Int2: 0
String0: , String1: 
Point: (0, 0)
1. Object: garjum
2. Object - NULL
3. Object - NULL
RefCount: 2	actionID: 111
```

In any case attaching saves before going to Windspear Hills and after going there but before entering cabin.
[saves.zip](https://github.com/user-attachments/files/17366176/saves.zip)

**Comment by lynxlynxlynx** [comment]
Oh, I forgot, Garren comes to you after the illusion fight. Perhaps saving before he returns breaks something, but that would be a separate problem.
Will need to check which cutscene script hangs. Perhaps it's not important and you can just `EndCutSceneMode() `in the console without missing out, but we still need to fix it — it used to work.

**Comment by jpalus** [comment]
Thanks for the tip. Following did work;
1. After first fight make save
2. Load save instead of entering cabin and talking to Garren
3. Enter cabin jumping directly to Iltha dialog
4. Fight bandits
5. End hung cut scene with `EndCutSceneMode()`
6. Leave cabin
7. Enter cabin
8. Garren is there again and quest progresses

**Comment by lynxlynxlynx** [comment]
Ok, so the fact that he gets stuck is now fixed, after a delay, with a recent general pathfinding workaround. But the fact that saves from outside don't work the same as playing straight through still holds.

**Comment by lynxlynxlynx** [comment]
Ah, the cabin area isn't even in the save, since the party hasn't entered it yet. So when it does, the area is loaded as if brand new — without him.

**Comment by lynxlynxlynx** [comment]
Nah, that's not it, since he get added to the area on entry, being a global actor in the interim. It appears to be that we don't run effects on global actors without an area, so his final part of the teleport never runs. At least not from a fresh load and the difference still needs more investigating. For this to work, they'd need to get at least one attempt in.
