### ISSUE TITLE
 XP reward messages on kill occasionally missing

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2199]
#### Bug description
As title says, sometimes XP rewards in IWD2 appear to missing in the message log, not sure if limited to IWD2. Usually it's sufficient to have some enemies around and check each death message for the lack of a following XP message to find such a case. Also nothing a few seconds later.

I'm sure that the XPs are rewarded, since otherwise I'd expected to have signficantly less XPs in total at the end of the game, compared to the original.

#### Screenshots

![iwd2_xp_death](https://github.com/user-attachments/assets/9ba63933-b620-4d1b-9589-74a041a8f42d)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
Are you sure you just weren't too high leveled, so the poor goblin isn't worth any xp any more? That's an iwd2 specialty, you can look at the level mapping in crtable.2da. Also some creatures have it disabled or might nor have the stat set, but I that's the case for a mere goblin.

**Comment by MarcelHB** [comment]
Hm, need to check this in detail I guess. I think I even had this at advanced enemies (Xvim slaughters) missing but I'll do some look up.

**Comment by MarcelHB** [comment]
Not sure if I'm something missing here which is related but not the original topic. I have a level 15 party and tested the following enemies (as seen on AR6703), XP levels & values taken from NI/CRE files (I've added a log line for `XP for ...`):

* neo orog priest, XP power level: 18, XP value: 75000 -> 2250XP
```
[Actor]: XP for neoorogshaman
[Game]: Challenge Rating: 17, party level: 15
```
* red mage, XP power level: 16, XP value: 6000: nothing
```
[Actor]: XP for redwizard1
[Game]: Challenge Rating: 9, party level: 15
```
* half-dragon, XP power level: 16, XP value: 5000 -> nothing
```
[Actor]: XP for halfdragon2
[Game]: Challenge Rating: 9, party level: 15
```
* half-orc, XP power level: 10, XP value: 900 -> nothing
```
[Actor]: XP for halforc2
[Game]: Challenge Rating: 6, party level: 15
```
* Xvim slayer, XP power level: **10000**, XP value: 18 -> 281XP
```
[Actor]: XP for slayerknightofxvi1
[Game]: Challenge Rating: 11, party level: 15
```

This looks weird to many extents: Xvim slayer is probably mistakenly exchanged in the CRE file already? Whis is the logged CR different to the CRE files?

**Comment by lynxlynxlynx** [comment]
The slayer is clearly buggy data, 3 instances, while most of them are fine. But it's handled, we just take the max level. 

The odd things are indeed the mismatches in your print — I don't see any of the slayer CRE's with a CR of 11. Even accounting for the fact that we read it as a byte, 10k doesn't wrap to 11. I don't see any effects or actions touching either name of the stat. But also, I see in `CREImporter::GetActor` we always read the old style xp before calling the IWD2 getter and it's not immediately obvious why. It could be some other offset problem as well.

**Comment by lynxlynxlynx** [comment]
Yes, we rewrite the stat as we read the CRE. NI just doesn't display the second value, which indeed is 14 for 65kntxvm, 18 in the header. Time to dig deeper.

**Comment by lynxlynxlynx** [comment]
I couldn't find out all I wanted, but it's clear in effect it's not using IE_XPVALUE, but the later field.

This video is not so useful, says 750xp and one char is at level 17, which doesn't match the table and could thus be modded (or just level squatted). But it does match a CR of 14:
https://www.youtube.com/watch?v=h21s1sNpfeE

So I'm not sure anything is wrong.
