### ISSUE TITLE
[bug] Whistling sound not played when using ranger's charm animal ability

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#221]
**Description**
When using a ranger's charm animal ability, the original IE and EE play a whistle sound, while it doesn't happen with GemRB. Checked also on an unmodded installation.

**GemRB version**
0.85-git

**To Reproduce**
- go to e.g. Umar Hills (AR1100) with a ranger in your party
- find yourself an animal and charm it:
![screen](https://user-images.githubusercontent.com/54738589/64489723-b22fac80-d256-11e9-8a0b-366f08e92ee1.jpg)

**Comment by lynxlynxlynx** [comment]
This is an innate, innit? So unless we provide the spell, which I doubt, it doesn't make much sense. Or does charming non-animals do the same and the sound was hardcoded into the opcode?

**Comment by caillean7** [comment]
It is an innate - SPCL311. The sound played is assigned as casting sound: CORAN03.wav. It's also played when attempting to charm a non-animal, it's unaffected by the spell's target.

**Comment by lynxlynxlynx** [comment]
Check the log then, does it mention the file at all?
Could be it's from  the fact that it's an innate and has a casting time of 0 though.

**Comment by caillean7** [comment]
It doesn't mention the sound file, but there's something about that spell.
```
[Control/WARNING]: Nested event handlers are not supported!
[Unknown]: Cast spell: spcl311
[Unknown]: Slot: 1
[Unknown]: Type: 2 (4 vs 4)
[Unknown]: Spellname: Charm Animal
[Unknown]: Target: 1
[Unknown]: Range: 1
[Control/WARNING]: Nested event handlers are not supported!

```

Don't know if this has something to do with this or the casting time, but at least the visual animation (waving hands around) works.

**Comment by caillean7** [comment]
Near Infinity shows a casting speed for this spell of 1. The Bhaalspawn power version of Cure Light Wounds for example has the same casting speed and the sound is played - shortened, but that's also how it works on IE.

**Comment by lynxlynxlynx** [comment]
It works for me, eff_p73.wav is played. Please check if any mod modified the spell and how.

**Comment by caillean7** [comment]
I tried this also an unmodded installation, just BG2 + ToB + the latest official patch. It didn't work. That's strange. In my current modded BG2 only the BG2 Fixpack by G3 and the Generalized Biffing affect the spell.

**Comment by caillean7** [comment]
Eff_p73 is not the whistle sound. I listened to it in NI, then re-checked on EE. Eff_p73 is definitely not played in EE, only the above mentioned CORAN03.

**Comment by lynxlynxlynx** [comment]
It's odd indeed, I see the coran completion sound in dltcep too, while not the other one. And it's not an internal sound either.

**Comment by caillean7** [comment]
An uneducated guess before I shut up about this: Some 2da or ids file in the unhardcoded folder that identifies sound files for GemRB that points to a wrong file?

**Comment by lynxlynxlynx** [comment]
We actually don't identify a casting sound, what we construct is not existent. So yeah, this looks like some extra functionality not tied to specific spell schools or projectiles (our cgtable.2da).

**Comment by caillean7** [comment]
Heh, I just got this open in the editor, trying to figure out what is means :)

**Comment by lynxlynxlynx** [comment]
We don't even use that field yet, hah. Only in stores as a backup when buying cures.

Do I understand correctly that this is played once casting finishes? Eg. timestop, which takes ages, first plays whatever school's sound it is from and once you're finally done waving around, also this _casting_ completion sound? You can play with the current spell by increasing its duration.

**Comment by caillean7** [comment]
The EE doesn't seem to like me playing with casting times, but it worked with 2. So watching closely, I think you are right. First the hand waving, then the whistling.

**Comment by caillean7** [comment]
About all those unhardcoded files - I remember checking GemRB wiki for documentation on them, but didn't find a lot. Is there any somewhere? Some things are reasonably self-explanatory, but some of these files are less obvious.

**Comment by lynxlynxlynx** [comment]
Can you try a spell that's long to cast by default?

Tables (I suspect several are outdated though):
https://github.com/gemrb/gemrb/tree/master/gemrb/docs/en/Tables

**Comment by caillean7** [comment]
I tried with the simple Cure Light Wounds Spell, which has a casting time of 5. Assigned as casting sound here is EFF_P07 (this 'whoosh' sound), and this is also played once the animation / hand waving animation is done.  There's also this intonation 'Vita, Mortis, Careo' which is played simultaneously with the casting animation. But what DLTCEP and NearInfinity list as 'Casting Sound' seem actually to be a casting completion sound.

Thanks for this link, I'll be sure to dig into it.

**Comment by lynxlynxlynx** [comment]
Ok, all clear.

**Comment by caillean7** [comment]
Sounds good to me. We have whistling on any attempt to charm, and if cast on an animal and it actually succeeds it also plays another sound upon completion - sounds about right?

**Comment by lynxlynxlynx** [comment]
Yep!
