### ISSUE TITLE
 Transparency issues on some mirrored sprites

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2210]
#### Bug description
Looks as if there is some coloring/transparency problem when sprites are mirrored to the right half of the clock. Will have a look at it.

#### Screenshots

![sprites_green](https://github.com/user-attachments/assets/9b72e4e1-2dcc-4c51-a331-b9529703f2e1)

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [x] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
I noticed this once or twice, but couldn't pin it down. Eg. only once with the wand of lightning, which I've used maybe 20 times overall.

**Comment by MarcelHB** [comment]
Probably one of the more annoying bugs. So far I was 1. not able to fix the bug through things I had in mind or 2. fix the bug at the expense of other bugs/performance issues I did not understand so far. Will continue to look for solutions.
