### ISSUE TITLE
No way to set base animation FPS

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#2212]
As was [pointed out in the forum by Shekn](https://www.gibberlings3.net/forums/topic/38815-proper-way-to-define-character-move-speed/), animation drawing speed is defaulted to 15 (ANI_DEFAULT_FRAMERATE).
Looking at the code, that can be adjusted for `ScriptedAnimation` and `GUIAnimation`, but nothing else. So character anims, area anims and anything else just using `Animation`, is stuck at 15. Which sucks for new content creators.

The BAM formats don't have any fields for this, so either we'll have to extend them and fix the tooling, so artists can set them at all, or provide a workaround like an extra column in avatars.2da (only for actors) or a separate table (where we could have a default per type). I doubt such low granularity would be satisfactory though.

Another hacky approach would be to encode the FPS in the filename, sacrifice 3 chars at, let's say, the start. Many ways that can fail.

Any other ideas? So far, the best I came up with is a table for BAM files with non-default FPS. No need to change the tooling, just an extra step for creators.

**Comment by MarcelHB** [comment]
Extra table sounds best to me.
