### ISSUE TITLE
BG1:  Exception on Scriptable.cpp

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#2213]
#### Bug description
Going to the second floor of the Friendly Arm Inn give me this:

```
gemrb: /home/rodrigo/games/BaldurGate2/gemrb-myfork-git/gemrb/core/Scriptable/Scriptable.cpp:2163: virtual void GemRB::Movable::DoStep(unsigned int, GemRB::ieDword): Assertion `!step.point.IsZero()' failed.
```
This is my save game:
[888888898-Full party.zip](https://github.com/user-attachments/files/17595220/888888898-Full.party.zip)

#### Steps to reproduce
1. Go to the second floor with half the party
2. Click on ahead
3. See error

#### Expected behavior
It will not crash

#### Screenshots
---

GemRB version (check as many as you know apply)
- [X] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `OPENGL_BACKEND` enabled
- [X] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
Thanks, I just hit it with the assassin mage in front. Will investigate.
