### ISSUE TITLE
[subviews] Misplaced bar when in IWD2 inventory

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#222]
**Describe the bug**
There is a GUI element that I cannot identify when opening the inventory.

**To Reproduce**
1. Have 1024x768 screen res.
2. Load an IWD2 game.
3. Open the inventory.

**Expected behavior**
No whatever-bar-this-is.

**Screenshots**
![iwd2_inventory](https://user-images.githubusercontent.com/238558/64491057-fb3a2d80-d263-11e9-840e-bb89b1e853bd.jpg)

**Comment by bradallred** [comment]
that is actually part of the inventory window. you can see this if you build with `DEBUG_VIEWS` or hold the ctrl key and click drag the anomaly.

There is a control there, but the background actually appears to be part of the window. To fix it we have to do more frame hacking on the inventory window to shrink it down. We also have to delete the control else you will get a scrollbar on the window.

As for what it is, I imagine its some sort of text area so you can see messages while in the inventory?

**Comment by bradallred** [comment]
an alternative would be to remove the `Borderless` flag from the inventory window on IWD2, but then it would look wrong at non standard resolutions.

**Comment by bradallred** [comment]
do you know if it is only the inventory window?

**Comment by MarcelHB** [comment]
I was also thinking that it's for these "you had an item picked when you left the inventory" messages but in the original the overall arrangement is different and this kind of message shows up in the message text area.

![iwd2_inventory_ok](https://user-images.githubusercontent.com/238558/64491460-08a5e680-d269-11e9-9707-00b2e1aa6ca2.jpg)

**Comment by MarcelHB** [comment]
So far, I haven't spot it anywhere else.

**Comment by lynxlynxlynx** [comment]
the way it looks it could be the cheat textedit from messagewindow, but misplaced. Are we always removing it? Or if it was under the frame in the original, it likely wouldn't have any effect.

**Comment by bradallred** [comment]
oh, thats what that weird TextEdit is for? We don't need/want that then I assume.
