### ISSUE TITLE
Sourceforge 0.9.3 Intel MacOS binary is ARM

### ISSUE THREAD

**Issue by tlancina** [gemrb/gemrb#2221]
Hey there, just a heads up that the file `gemrb-macos-v0.9.3.tar.bz2` from https://gemrb.org/Install.html does not appear to be `x86_64`. 0.9.2 is fine though

```
./gemrb
-bash: ./gemrb: Bad CPU type in executable
```
```
file gemrb
gemrb: Mach-O 64-bit executable arm64
```

**Comment by lynxlynxlynx** [comment]
Looks like Github Actions upgraded the runners to arm, since the newest build is for the same arch. Grab it of Mac source ports instead.

I wonder if there's some place where we could still build for x86. Now we apparently have two builds for the same arch.

**Comment by lynxlynxlynx** [comment]
The cause was fixed, but the file is bad still. Can't really build it again, but the download page now links to the MSP versions as well anyway.
