### ISSUE TITLE
 BG2: Horn of Blasting does not work as expected

### ISSUE THREAD

**Issue by jpalus** [gemrb/gemrb#2225]
#### Bug description
Upon using Horn of Blasting animation appears but other than that nothing happens. No damage is done to anyone and the animation does not disappear.

#### Steps to reproduce
1. Use Horn of Blasting

#### Expected behavior
Damage is done to everyone in area.

#### Screenshots
![screenshotwl-20241121122928](https://github.com/user-attachments/assets/2aea867f-eda0-4fe7-8c2d-a5ee2825f248)

GemRB version (check as many as you know apply)
- [ ] master as of this issue
- [X] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [X] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
Indeed and this one is actually using a projectile that was already not hardcoded in bg2 (safefire.pro "anti fireball"). Somehow it never finishes its travel phase, will take a closer look.

**Comment by lynxlynxlynx** [comment]
Ok, that was easy. The projectile has such a high speed set that we rounded something important into 0.
