### ISSUE TITLE
 Grey box around some spells

### ISSUE THREAD

**Issue by DarthRevan501st** [gemrb/gemrb#2229]
#### Bug description

So when I cast some spells they have grey boxes around them.

#### Steps to reproduce
1. Use a fresh copy of GemRB with BG1 from GOG( Obviously OG and not EE.) on Linux or Windows( Not sure about other platforms.)
2. The only change I made to the config file was my game path.
3. Start a new game, click the mission pack, and load the default mission pack save.
4. When you get sent to the island just start attacking enemies with your full party.

#### Expected behavior
When certian members of the party attack you will see the grey box in the picture below around some spells.

#### Screenshots
![Capture](https://github.com/user-attachments/assets/64b1294a-2134-4a97-a70c-0e5eaad2f520)

GemRB version (check as many as you know apply)
- [ ] master as of this issue
- [x] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1
Not sure about older versions as I haven't used them.

Video Driver (check as many as you know apply)
- [ ] SDL1.2
- [ ] SDL2 built with `OPENGL_BACKEND` enabled
- [ ] SDL2 without `OPENGL_BACKEND` enabled

**Comment by lynxlynxlynx** [comment]
Thanks, this might be the same thing as #2210. Can reproduce on master, but not with wolves in ar1009 (what would cause the dispel?), I get it when getting spit on by the ankhegs in the center and left of the area.

**Comment by lynxlynxlynx** [comment]
Yeah, it's fixed now.

**Comment by DarthRevan501st** [comment]
> Yeah, it's fixed now.

Hey thanks! I look forward to the next release.
