### ISSUE TITLE
[subviews] Cannot immediately pause on entering new area

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#223]
**Describe the bug**
This one's funny: When you enter a new area and e.g. spot enemies, you usually hit the space bar to pause the game and prepare the fight. This doesn't work completely like that for now.

**To Reproduce**
1. Start a new game in let's say IWD2.
2. Enter the first building (AR1005) with the goblins.
3. Do NOT do anything but
4. Press space to pause.

**Expected behavior**
The game to pause. Instead, nothing happens. If you do something first, e.g. select an actor, it's working again. This could make you panic a bit.

**Comment by lynxlynxlynx** [comment]
Sounds like the game window doesn't have focus yet.

**Comment by bradallred** [comment]
agree with @lynxlynxlynx, probably this is due to the fact that we disable the GameControl when changing areas, which causes it to loose focus. We probably just need to add a focus call when we reenable it to solve this.
