### ISSUE TITLE
[DOC] Fix malapropism "XDG_CONFIG_PATH"

### ISSUE THREAD

**Issue by elde-n** [gemrb/gemrb#2237]
Manual specifies "XDG_CONFIG_PATH" while the code uses the "XDG_CONFIG_HOME" environment variable
https://github.com/gemrb/gemrb/blob/1190f1d37c3bb2b415c48fe5a6d6b867fb17bf1e/gemrb.6.in#L524
https://github.com/gemrb/gemrb/blob/1190f1d37c3bb2b415c48fe5a6d6b867fb17bf1e/gemrb/core/InterfaceConfig.cpp#L94

**Comment by lynxlynxlynx** [comment]
Correct, we should fix it. Feel free to submit a PR.
