### ISSUE TITLE
[subviews] Circles lost behind animations

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#224]
**Describe the bug**
In AR1005 of IWD2, you notice that you lose the circles of the actors when close to the fireplace. This is _not_ happening in master, so this is probably a regression.

**To Reproduce**
1. Enter AR1005.
2. Move an actor over the background animation of the chimney.

**Expected behavior**
See circles

**Screenshots**
![ar1005_broken](https://user-images.githubusercontent.com/238558/64493783-cab6bb80-d284-11e9-801b-62a838cc30ec.jpg)

vs. master:
![ar1005_ok](https://user-images.githubusercontent.com/238558/64493785-d73b1400-d284-11e9-8817-49aff533ce60.jpg)

**Comment by MarcelHB** [comment]
There is an animation right there, so maybe draw order?

**Comment by lynxlynxlynx** [comment]
I doubt it changed, but in master the actor is drawn in the same routing as his circle, so there would be more missing if it was an ordering thing. Plus, you should be able to get partial circles by standing at the edges of the animation.

**Comment by bradallred** [comment]
for performance reasons (and other technical reasons) the new SDL2 driver splits masking (SpriteCovers) into its own layer. I'm guessing actors have a SpriteCover, but the circles do not. We will need to probably add a new method to be able to draw to the masking layer so we can draw the circles there too.

**Comment by bradallred** [comment]
I woudl suspect this works fine still if you use the SDL1.2 backend?

**Comment by MarcelHB** [comment]
Can't tell you quickly, that SDL backend code throws a bunch of compilation errors on MingW/GCC 9.2.

**Comment by MarcelHB** [comment]
Ok, wasn't hard. Yes, 1.2 still looks good.

**Comment by MarcelHB** [comment]
By the way, could you maybe check this?

```diff
diff --git a/gemrb/plugins/SDLVideo/Pixels.h b/gemrb/plugins/SDLVideo/Pixels.h
index fb0640e58..7329ff729 100644
--- a/gemrb/plugins/SDLVideo/Pixels.h
+++ b/gemrb/plugins/SDLVideo/Pixels.h
@@ -361,7 +361,7 @@ public:
 	}
 
 	SDLPixelIterator(Direction x, Direction y, const SDL_Rect& clip, SDL_Surface* surf)
-	: IPixelIterator(NULL, surf->pitch, x, y), format(surf->format), clip(clip)
+	: IPixelIterator(NULL, surf->pitch, x, y), imp(NULL), format(surf->format), clip(clip)
 	{
 		Uint8* pixels = static_cast<Uint8*>(surf->pixels);
 		pixels = FindStart(pixels, surf->pitch, format->BytesPerPixel, clip, xdir, ydir);
diff --git a/gemrb/plugins/SDLVideo/SDL12Video.h b/gemrb/plugins/SDLVideo/SDL12Video.h
index 90fbb96eb..3f82a2c47 100644
--- a/gemrb/plugins/SDLVideo/SDL12Video.h
+++ b/gemrb/plugins/SDLVideo/SDL12Video.h
@@ -186,7 +186,7 @@ public:
 		va_list args;
 		va_start(args, pitch);
 
-		enum PLANES {Y, U, V};
+		enum {Y, U, V};
 		const ieByte* planes[3];
 		unsigned int strides[3];
 
```

**Comment by bradallred** [comment]
looks good to me! send a pull?

**Comment by bradallred** [comment]
I seem to have something to fix this, but it needs to be cleaned up.
I'm not sure what the performance impact will be either.

**Comment by bradallred** [comment]
To clarify, I specifically mean cases where we need a sprite with a cover drawn _over_ lines/rects/etc.

**Comment by MarcelHB** [comment]
Ok, I'll look at it later today.

**Comment by MarcelHB** [comment]
Thinking of #198 , I can only think of this spell as another example.

**Comment by bradallred** [comment]
yeah, I can't think of anything beyond foot circles. I guess I'll fixup what I've got and wait till we encounter something else. Unless @lynxlynxlynx has ideas about candidates.

**Comment by bradallred** [comment]
This should be fixed with the exception of PST, which uses sprites for the foot circles.
We will need to generate our own SpriteCover for those and I'm not sure how to best do that.

**Comment by bradallred** [comment]
does somebody have a save/area where this can be tested?

**Comment by MarcelHB** [comment]
I have save games from #163, you should be able to mta everywhere from that state: 
[pst_saves.zip](https://github.com/gemrb/gemrb/files/3597196/pst_saves.zip)

**Comment by bradallred** [comment]
PST seems to be ok to me actually. Closing.
