### ISSUE TITLE
 BG2: Tutorial stuck at learning spells

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#2246]
#### Bug description
In the BG2 tutorial, Xan will appear and teach how to learn new spells, an arrow of flame (but `TTSCRL01.itm`). 

He tells you what to do, and then you do. The spell appears in the spellbook, and you can assign it to a slot. But this is when something gets stuck, or is not recognized correctly: Xan will repeatingly remind you how to do this since it hasn't happend yet (`TTXANJ.DLG`).

Apparently, we do not reach `TutorialLession == 20`, and in some mild research and I did not spot anything in the scripts helping us.

But there is something called `TUTOR1.EFF` that sets some variable to 20 and two strings `Tutorial` and `Lession`, which can be found referenced in the item's ~~effects~~ abilities' effects.

GemRB version (check as many as you know apply)
- [x] master as of this issue
- [ ] 0.9.3
- [ ] 0.9.2
- [ ] 0.9.1

**Comment by lynxlynxlynx** [comment]
Sounds more like a timing issue on the effect. If it's an equipping one, of course it will be gone when the item is consumed.

**Comment by MarcelHB** [comment]
Hm, I put a breakpoint on specified effect 177 (use EFF file) in `FXOpcodes.cpp` and it did not hit.

**Comment by lynxlynxlynx** [comment]
Ahh, I think I know what's going on. When learning from scrolls, we don't actually fire their abilities (probably it was unreliable at some point or in some game data or problems with pause etc.), but do it directly. So indeed this whole effect queue never gets a chance to run.

So I think we should just hardcode this little exception in Spellbook.LearnFromScroll and update the global manually.

**Comment by lynxlynxlynx** [comment]
The rest of the tutorial works fine too.
