### ISSUE TITLE
[subviews] Spell targeting is broken

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#225]
**Describe the bug**
In IWD2, I tried to cast a spell, good ol' Magice Missile. Here is my story. Not on master, so a regression.

**To Reproduce**
1. Pick a spell caster.
2. Pick a spell that requires an actor as target.
3. Try cast the spell on some actor.
4. Try to cast the spell on anything but an actor, the ground, a wall (possibly even crashes at some point).

**Expected behavior**
You should be able to cast on the target for such spells, nothing else.

**Comment by lynxlynxlynx** [comment]
Reminds me of https://github.com/bradallred/gemrb/issues/38, but beside it being about targetting, it's likely unrelated.

**Comment by bradallred** [comment]
might be something I broke while fixing #217

**Comment by MarcelHB** [comment]
Please reopen as part 2 of this issue is still unfixed: Try casting such a spell (at least in IWD2, this works) onto an arbitrary pixel on the map, despite the grey cursor.

**Comment by lynxlynxlynx** [comment]
Done. I've invited you as a triage collaborator, so you'll be able to at least edit issues and so on.
