### ISSUE TITLE
Error when ambient sound is switched from a 2-channel source to a 1-channel source

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#2251]
Ambients support several resources and play them in a queue. If you use two different files as sources for the ambient, one with 2 channels and one with a single channel, then when one is finished and the next one is started, the console displays:

> Unable to queue buffer: 0xa004 - Invalid Operation

Only going from 2 to 1 causes problems, the other way is fine.

Test case here:
https://www.gibberlings3.net/forums/topic/38983-setup-ambient-sounds/#findComment-344859

**Comment by MarcelHB** [comment]
Reproducing this only works with OGG files, not WAVEs. Will have a look.
