### ISSUE TITLE
[subviews] No night

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#228]
**Describe the bug**
This is a regression, I am missing the darkness of the night. You can see actors having a night shading though.

**To Reproduce**
1. Load an IWD2 game.
2. Wait until night conditions apply, 11pm.

**Expected behavior**
![master_night](https://user-images.githubusercontent.com/238558/64565015-1df73f80-d353-11e9-9ee0-e24336b160da.jpg)

**Screenshots**
![subviews_night](https://user-images.githubusercontent.com/238558/64564999-159f0480-d353-11e9-828c-c13d993f1e88.jpg)

**Comment by lynxlynxlynx** [comment]
Did something change with the area loading in subviews? There is a night version of wed files for such occasions (same filename+N iirc).

**Comment by bradallred** [comment]
I can't recall. I don't even know where this is handled. Where should we start?

**Comment by lynxlynxlynx** [comment]
What I was thinking of is in AREImporter::ChangeMap. AT_EXTENDED_NIGHT is the data point and Map::DayNight can be used to check if think it's the correct time of day.

**Comment by lynxlynxlynx** [comment]
Just breaking on Map::ChangeMap will get you in the gist of things immediately on load. These areas don't have AT_EXTENDED_NIGHT set (maybe bg2-only), so it's not about the tilesets. In the original it looks just like a soft tint (red in my master, but it could be a timing thing).

**Comment by bradallred** [comment]
I'm sure its unrelated, but it seems odd to me that `Tile` has an `NLightMap` member that is unused. I'm assuming thats a light map for night time...

**Comment by bradallred** [comment]
Does this work in SDL1.2? I still can't check for myself.

**Comment by MarcelHB** [comment]
Thanks, I will test that later.
