### ISSUE TITLE
[enhancement] More Efficient Text Rendering

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#233]
Palette swapping is hugely expensive (relatively speaking) in SDL2. This is especially noticeable with text due to the palette being swapped many many times per frame.

Specifically, I'm talking about the Palettes from GemMarkupParser::GetSharedPalette. We could ditch this entire cache and just use a single palette + color. Just would need to add a new method to Font to take a color and add the BLIT_TINTED flag.

If you uncap the FPS then open the large message text window and fill it up with text you will notice a substantial difference vs if the window is closed. I know some of that is due to the printing rather than the rendering, but since changing colors requires a cache flush (destroying and recreating the texture) and we change colors back and forth multiple times it makes sense that this has a big impact on performance.

This request only applies upon #95 being completed.

**Comment by bradallred** [comment]
It became clear from my testing yesterday that our colors here don't look right compared to the original anyway. I don't know if doing this will make it any closer, but at least it won't be any worse.

**Comment by lynxlynxlynx** [comment]
Which colors? The actor name we randomize better, while we have the message colors hardcoded to best guesses #137 .

**Comment by bradallred** [comment]
None of the colored text looked exactly right be it names or the selection options. Not a big deal, they are close enough and look fine.

**Comment by FrElvire** [comment]
I did a rapid check and the difference can be huge between master and subviews : 

Always with SDL2 (without OGL), on master you have ~20% CPU used, with subviews it's ~80% (unable to maintain 30fps, stay between 20 and 25)

Save used : 
[000000011-conv spam.zip](https://github.com/gemrb/gemrb/files/4738517/000000011-conv.spam.zip)

Difference in video : 
[master_spam_sdl2.zip](https://github.com/gemrb/gemrb/files/4738518/master_spam_sdl2.zip)
[subviews_spam_sdl2.zip](https://github.com/gemrb/gemrb/files/4738520/subviews_spam_sdl2.zip)

To put things into perspective, the cpu is a core i5 6200U

**Comment by bradallred** [comment]
I managed to rewrite Font/GemMarkup to support font tinting instead of palette swapping which was a wonderful improvement to performance. Sadly, as discussed in #1149, I've discovered the method that the originals used to render text which uses 2 colors and a palette inversion. This means that we are once again back to excessive palette swapping.

The options at this point are:
1. Have BAM fonts duplicate their atlas pages as an inverted copy. This will fix there SDL 2 performance implications at the cost of such fonts being 2x the memory requirements. TTF fonts could use a palette that supports alpha instead.

2. Use a shader to invert the colors, but then we effectively require OpenGL for the SDL 2 backend.

**Comment by lynxlynxlynx** [comment]
1. Considering the size and small count of fonts it doesn't sound like the footprint would increase by much.
2. I think it would be fine while we still have sdl1 as a software-only fallback.

So overall I have only a slight preference for 1.

**Comment by bradallred** [comment]
yes, some information gathering on what is broken would be nice.

For the IWD2 buttons, it looks like IWD2 button fonts are inverted. Switching the fg and bg color fixes them. Seems like we may need another game flag and to find out which games need it. An alternative solution may be to add just another `font::print` override that only does tinting since the main issue is that the button fonts don't actually have a "background".

We need to check the games for tooltip colors. I have BG2 and IWD sorted out. I imagine games that don't have fancy TT backgrounds (so all bug BG2?) are the same as IWD.

if you run across labels that are broken, check the GUIScripts to see if we are manually setting a color. Might be we just need to remove that. In fact, I wonder if any GUIScripts actually need to manually set colors anymore. I imagine we did this because we didn't actually understand font coloring before.

**Comment by bradallred** [comment]
its probably the best thing to do in the short term. We can mitigate it by identifying which fonts use a background in fonts.2da so only some will require the inverted shadow surface.

**Comment by MarcelHB** [comment]
Isn't there something we can optimize structurally, and agnostic towards the SDL backend? When scrolling through a large journal with a hundred of entries, FPS go down to single digits here. My CPU spends a lot of time in `SDLTextureSprite2d::GetTexture`, and the SDL stuff below.

At the moment, it's one large textbox with a lot of text inside, right? Do we currently render all the glyphs individually? Because in `Font::Print`, I noticed it's not using `canvas` to set up one larger buffer, but there is a `Font::RenderTextAsSprite` which does that but looks unused to me.

Maybe by reducing the number to texture/draw calls towards SDL, and the driver, we can achieve a bit without OpenGL-exclusive shader hacks. Just sketching: Having render groups, e. g. individual journal entries (or messages), grouping glyphs that are subject to the same palette before blitting them with ones of different palettes, keeping the resulting textures for the lifetime of the view, or using some LRU cache.

**Comment by bradallred** [comment]
> At the moment, it's one large textbox with a lot of text inside, right? Do we currently render all the glyphs individually? Because in Font::Print, I noticed it's not using canvas to set up one larger buffer, but there is a Font::RenderTextAsSprite which does that but looks unused to me.

The glyphs are all rendered on 1024 wide atlas pages, not individual textures. we could probably increase that to 2048, but I doubt it would make a noticeable impact (feel free to try it!). The original reason for using 1024 is because there are hardware specific limitations to how big a texture can be and we tried to fly under that. However, even phones these days can do 4096x4096 so i'm not sure what our minimal target ought to be, whatever PSP is 🤷. I assume we landed on 1024 because we also need screen sized textures and 1024 is more or less the upper limit for that (I know we can go higher, but as an expectation for small devices it holds)

Even though the text is one giant box, we already don't render clipped lines. See `Font.cpp:314`. We only draw what is visible.

SDL is supposed to use sprite batching on the backend so rendering the same texture repeatedly with the same color as would be the case with plain text shouldn't be a bottle neck. Regardless, creating one gigantic texture and rendering to that then rendering to screen would be slower in most cases. 

I don't believe there is anything more we need to do to achieve satisfactory efficiency. I believe there is a bug causing `staleTexture` to get set when it shoudn't be. You shouldn't be getting stale font textures anymore because now we render them with a tint operation instead of a palette swap. that is the entire point of this issue. figure out why that is getting set and the problem will vanish.

**Comment by MarcelHB** [comment]
I noticed the `SpriteSheet` and thought it was good then. Yet I sampled tens of thousands of steps through https://github.com/gemrb/gemrb/blob/f8f7863f1e75fcc86ee2a333a3a107a205301b0f/gemrb/core/SpriteSheet.h#L73

_per second_ when scrolling up and down in the journal. Which made me wonder if there is something to tune left.

**Comment by lynxlynxlynx** [comment]
I noticed today that the iwd2 journal chapter switching is slower than in bg2. Sure, the saves don't have the same amount of journal text (both had plenty), but it _feels_ like the difference is not due to content size. iwd2 does display more of it, so perhaps it _is_ a drawing issue.

**Comment by MarcelHB** [comment]
You are right: In IWD2, when using the scroll wheel to move up and down without even fully losing a single line of text, it becomes painfully slow.

**Comment by bradallred** [comment]
as I pointed out, if you are spending noticeable time in `SDLTextureSprite2d::GetTexture` that is because the texture is considered stale. It shouldn't be considered stale when drawing text since we no longer use any non hardware supported gfx for drawing it (`BLIT_BLENDED`, `BLIT_ADD`, and ` BLIT_COLOR_MOD` are all supported directly by `SDL_Renderer`). That is the bug.

**Comment by bradallred** [comment]
can somebody upload a good IWD2 save for reproducing this? I don't have a problem in BG2 nor do I see font textures becoming stale.

**Comment by bradallred** [comment]
> Yet I sampled tens of thousands of steps through per second when scrolling up and down in the journal.

30 fps * number of characters visible. sounds normal to me 1000 characters drawn 30x a second is 30,000. I don't understand why you think this is a problem or how it can be made faster. at the end of the day each character has to get drawn to screen each frame during a scroll event. It would be a problem if each glyph were a separate texture, but thats not the case.

**Comment by lynxlynxlynx** [comment]
More pronounced when switching between the Prologue and Chapter 1 sections.
[000000046-buggy snow trolls.zip](https://github.com/gemrb/gemrb/files/6177049/000000046-buggy.snow.trolls.zip)
Can't say anything about mouse scrolling, since here it does scroll per-line as expected.

**Comment by lynxlynxlynx** [comment]
I checked the journal sizes vs a bg2 final save (done quests section) and now it looks like it is about text layouting. The smaller bg2 textarea gives an illusion of a similar amount of text, but it's not even close:

iwd2:
- ch0: 22528
- ch1: 10012
- ch2: 7771

bg2:
- 2009
- 4373
- 1829
- 2110
- 3381
- 1419
- 1621

Reminds me of the hang on the pst journal #1056. Will try the same approach.

**Comment by MarcelHB** [comment]
> 
> 30 fps * number of characters visible. sounds normal to me 1000 characters drawn 30x a second is 30,000. I don't understand why you think this is a problem or how it can be made faster. at the end of the day each character has to get drawn to screen each frame during a scroll event. It would be a problem if each glyph were a separate texture, but thats not the case.

The numbers make sense, but since the counter accelerated while even slightly moving over the same text, I had suspected quite a amount of blit calls that doesn't scale well. But if it's first a matter of better dealing with stale textures, we can ignore this in the meantime.

**Comment by lynxlynxlynx** [comment]
iwd2 journal chapter switching lag is pretty much negligible after the last few fixes — for me.

**Comment by MarcelHB** [comment]
Here are some numbers that made me curious, it's the frequency of walks through `SpriteSheet.h:73` per second. I'm in some later IWD2 journal with some text, and I either hold still or scroll up and down by a very few px, like this:
![jrnl_scroll](https://user-images.githubusercontent.com/238558/111906030-f48e9800-8a4e-11eb-902e-f051676fd304.gif)

FPS go down to 6 while recording, and freq is like this:
```
// Holding still:
7055
7048
6544
7500
7166
...
// Scrolling up and down
16608
23703
23043
29119
30000
30000
28168
26599
21840
19701
25767
25111
...
// Holding still again
9966
6643
6643
7159
7055
6947
6643
7500
...
```
Which made me wonder if there is a way to keep it a.) stable even while virtually not scrolling into different texts or b.) reduce the numbers to reduce any implications in the tail.

**Comment by bradallred** [comment]
"holding still" doesn't redraw the window at all; those calls are coming from elsewhere. you are comparing apples to oranges. put a return at the top of `GameControl::DrawSelf` and pause the game if you want to filter out most of the noise from other sources.

**Comment by MarcelHB** [comment]
Ok, the noise is coming from the (otherwise still) message window.

**Comment by bradallred** [comment]
so now that you can filter out the noise, where do you see the program spending time. Note I actually mean _time_ and not # of calls. You said you were spending a lot of time in `SDLTextureSprite2d::GetTexture`, but I have not observed that to be the case myself. If it is the case, I don't see Journal text causing font textures to be marked as stale. Can you break it down more by actual _time_? Please only ever profile things with an `-O3` build, anything else is useless with all the abstractions we have.

**Comment by MarcelHB** [comment]
I prepared a run like this. I can only help with AMD µProf right now, so that gives me this flame graph as consuming 1/3 while doing journal scroll action:

![flame](https://user-images.githubusercontent.com/238558/111916691-72b56380-8a7c-11eb-89ec-2d33b486cbab.png)

Some more about numbers according to the profiler:
![callgraph](https://user-images.githubusercontent.com/238558/111916783-f1120580-8a7c-11eb-9f80-d8f528cab2a1.png)

**Comment by bradallred** [comment]
I dont know if im interpreting these right because nothing says anything at all about time, but `SDL_UpdateTexture_REAL` does imply you are running into stale textures. Can you find out why?

Im assuming this data is from a sample taken as I prescribed in my edit? the stale textures are in fact font related and not from some noise elsewhere?

**Comment by bradallred** [comment]
after putting my breakpoints in `GetTexture` instead of on `staleTexture` the problem is obvious and simple to fix.

**Comment by MarcelHB** [comment]
I attach to the process right before doing the journal test (for 15-20s), and detach immediately after to keep the influence as low as possible.

As far as I understand, µProf samples the stack every 1ms, so I don't get anything too reliable unless I find better settings. The Intel was better.

**Comment by bradallred** [comment]
try that now please

**Comment by MarcelHB** [comment]
That's it :)

**Comment by bradallred** [comment]
I'm going to go ahead and resolve this issue. We can open new issues if bugs appear.
