### ISSUE TITLE
[bug] BG2: Dialogue issue with Alternatives mod

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#236]
**Description**
In chapter 2, after you've collected 15,000 gp and are approached by Valen and Brus, if you enter the Government district, the Alternatives mod adds a cutscene letting you overhear Prelate Wessalen and Chiefinspector Brega talking. The party gets transported to another area of the map, then the dialogue is supposed to initiate:

`      ActionOverride("b!brega",StartDialogNoSet("b!prelat"))`

Instead, you only get a message like "Prelate Wessalen has nothing to say to you". You can see the dialogue and thus advance the quest if you walk up to Brega and start a dialogue with him.

(I also noticed another problem in a situation when two actors are supposed to start a dialogue with the PC present but not directly involved (Valygar and Leonora in a quest that's part of Corthala Romantique), but unfortunately I didn't keep a save game for testing purposes)

Seems to me as if GemRB always tries to start a dialogue with Player 1, even if they're not supposed to be involved?

**GemRB version**
0.85-git

**Expected behavior**
Start the dialogue between Brega and Wessalen automatically

**Comment by lynxlynxlynx** [comment]
This is handled by BeginDialog, a common function for all these dialog starters. We take speakers and targets into account (especially whacky in pst, where it could be a trap or an item), but for your example the swapping in "case BD_TARGET" looks suspicious.

What's the fastest way to reproduce, just install the mod+dbg, start a new game, get to gaelan, get out, cheat in the money, move around?

**Comment by caillean7** [comment]
If I'm interpreting the scripts right, you should set the "chapter" Global to 2, "SpawnBrus" to 2 and "BodiAppear" to 1. Then proceed to AR1000 (Government district). (Otherwise I could set up a password protected download of my installation with save game for you).

**Comment by lynxlynxlynx** [comment]
Please retry this one with the latest code, just so we know it's not the same underlying problem as with Mazzy.

**Comment by caillean7** [comment]
Unfortunately, the issue persists, so, different problem.

**Comment by lynxlynxlynx** [comment]
As the log says, it can't find a proper dialog state to start. In this case it's a similar problem as seen before — it's looking into the target's dialog file, not the speaker's one, while apparently a swap should have happened.

**Comment by lynxlynxlynx** [comment]
This now works and I tried a lot to find dialogs that would break, since this is really central code. Please check if it also helped with Valygar

**Comment by caillean7** [comment]
Nope, sorry, both Valygar problems persist :( But the Alternatives cutscene is perfect now, thanks!
