### ISSUE TITLE
[bug] BG2: NPCs dying when entering an area

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#238]
**Description**
I read the thread [here](https://www.gibberlings3.net/forums/topic/29884-gemrb-bugs-issues-and-problems-with-mods-and-mega-mod-setups/) and also had an issue with characters dying without apparent reason. It affects a NPC from the Victor's Improvements mod (Djin Merchant component): ERWAN.CRE, has non-zero strength, 50 current HP but 0 max HP. The guy is an advertiser standing just outside of Adventurer's Mart. According to the post at G3 it can also affect Wellyn, the ghost child in the Graveyard district, and one "Alexandria in the Umar Hills" - not sure who this is, and there's no cre with that name apparently. I checked Wellyn at least, but he has a max HP value of 3, so that's not the reason.

**GemRB version**
0.85-git

**To Reproduce**
- install Victor's Improvement Pack from [here](http://balduran.blackwyrmlair.net/) (gotta do a right-click + save as...)
- go to the Adventurer's Mart at Waukeen's Promenade (AR0700)
- you should see the advertiser (yellow clothing) lying near the entrance

**Comment by lynxlynxlynx** [comment]
Does he at least have any minhp items or effects?

**Comment by caillean7** [comment]
The only thing he has on his person is the Djin Merchant Call token he's supposed to hand out. He has no active effects, creature or state flags set. Btw., this one is just a minor issue, since you can pick up the token from his corpse.

**Comment by lynxlynxlynx** [comment]
It's still a ridiculous idea. Just out of curiosity: what's his CON?

**Comment by caillean7** [comment]
It's 9. All his stats are 9. Weird. Wellyn's stats are also all 9. Still haven't found out who "Alexandria"'s supposed to be.

**Comment by lynxlynxlynx** [comment]
Wellyn is an old thing, he should be fine. This sort of problem happens every time or never, so it's easy to check.

I'm thinking of closing this as WONTFIX, as it's clearly a data bug. I could limit the hp<=maxhp enforcement to creatures with player classes, but it's bordering on the absurd.

**Comment by caillean7** [comment]
Heh, if you hadn't said you wanted all issues reported, I probably wouldn't have bothered you with this one. The only thing you miss out is the few lines of dialogue the guy has; like mentioned above, you can still grab the token and it'll work fine.

**Comment by lynxlynxlynx** [comment]
what's his class id?

**Comment by caillean7** [comment]
155 - Innocent.

**Comment by lynxlynxlynx** [comment]
Try with the latest code, it's probably fixed.

**Comment by caillean7** [comment]
Yay, Erwan's alive!!! Sorry for being such a bean counting, bug report spamming nitpicker, so more complaints from me for a week I promise!
