### ISSUE TITLE
[0.8.5-git] Fail to compile without -DDISABLE_WERROR=1

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#244]
Hi,

I made a slight modification on gemrb ebuild (package on gentoo linux) to fetch code from git instead of 0.8.5 source package.

But without '-DDISABLE_WERROR=1' it fail to compile :
![image](https://user-images.githubusercontent.com/55502325/65165915-00effa00-da40-11e9-9d9c-fe7f5a444c55.png)

cmake output : 
![image](https://user-images.githubusercontent.com/55502325/65166271-aefba400-da40-11e9-9e5b-ccd56ff2c0bb.png)

GemRB version: 0.8.5-git

**To Reproduce**
1. modify gemrb ebuild : 
replace : 

![image](https://user-images.githubusercontent.com/55502325/65166006-28df5d80-da40-11e9-8e78-6bc87caa519e.png)

with : 
![image](https://user-images.githubusercontent.com/55502325/65166069-48768600-da40-11e9-8f8b-b3045b4f8a7c.png)

2. name the ebuild : gemrb-9999.ebuild
3. emerge it

it's not very precise on how to reproduce, if wanted I can provide more precision.

**Expected behavior**
finish building gemrb

**It is OK 0.8.5 source package.**

**Comment by FrElvire** [comment]
I use GCC 8.3.0 with these flags : 

![image](https://user-images.githubusercontent.com/55502325/65170732-8f1cae00-da49-11e9-9a7e-f01865d8a442.png)

**Comment by lynxlynxlynx** [comment]
Well don't remove the flag then? It's only detected as unused, since it is a release build and the asserts are removed.

**Comment by FrElvire** [comment]
Oh my bad, if removed in release package that's perfect :). I close

**Comment by lynxlynxlynx** [comment]
Since this is a git clone, it defaults to a debug build. RelWithDebugInfo is good enough for most users, so set that.
