### ISSUE TITLE
[bug] Time does not advance when travelling

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#252]
**Description**
I think this might be new, anyway, I never noticed it before that the time not advances if you travel around the world map. The message window says "The journey took x hours", but game time remains the same. I tested it on an unmodded BG2 installation.

EDIT: Also affects IWD1.

**GemRB version**
0.85-git

**To Reproduce**
Load any save game, check the time and travel using the world map

**Expected behavior**
Advance game time accordingly

**Comment by caillean7** [comment]
Did the bisecting: problem was introduced with https://github.com/gemrb/gemrb/commit/ff3d3c243c4ddd76c6a5b452272f0e6e09db26af.

**Comment by lynxlynxlynx** [comment]
Hmm, thanks, this will be another case of just unearthing an older bug.
