### ISSUE TITLE
[bug] BG2: Problems with EscapeArea / EscapeAreaMove

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#253]
**Description**
There are some cases where EscapeArea() and EscapeAreaMove() actions won't work - in other words, NPCs stick around where they shouldn't be. I've seen it at least with
- Delon (little boy in the Government District sent to get help for Imnesvale)
- Valen (after she approached the party about meeting Bodhi in the Graveyard she stays at Waukeen's Promenade and follows the party around)
- Nalia in the Copper Coronet (After the initial dialogue with her is over and you don't recruit her she won't leave for her keep but instead immediately start with "There you are! I've waited positively ages for you...")
- Kivan (Mod) (If you don't recruit him he should leave for good, instead he stays at Waukeen's Promenade indefinitely)

At least the Nalia thing is also the case on an unmodded installation, just checked.
```
 IF ~~ THEN BEGIN 53 // from: 14.0
  SAY #25445 /* ~I will meet you at my land.  I will mark it on your map.  We had best gather south of the keep, so we are not spotted. Please be quick.~ */
  IF ~~ THEN DO ~RevealAreaOnMap("AR1300")
SetGlobal("NaliaMove","GLOBAL",1)
EscapeAreaMove("AR1300",748,3227,SE)
~ UNSOLVED_JOURNAL #42371 /* ~The de'Arnise Keep has been invaded.

I have met a young woman by the name of Nalia, who is desperate to find help for her family's keep, which is under siege by a force that she has not yet explained.  She has agreed to tell us all if we meet her by the keep, which she has marked on our map... but we must travel there quickly if we are to be any help at all.~ */ EXIT
END
```
The other cases all use EscapeArea().

**GemRB version**
0.85-git

**To Reproduce**
Try the Nalia issue:
- If you have a save prior to meeting Nalia use this and go to the Copper Coronet
- If not, start a new game and MoveToArea("AR0406")
- Talk to Nalia, but don't let her join the party

**Expected behavior**
Make the NPCs in question leave the area

**Comment by lynxlynxlynx** [comment]
I'm looking at Nalia, since this was seen often, but I can't pinpoint what starts the second dialog. She only has nalia.bcs as far as relevant scripts go. Please add some debugging messages or something to the blocks to see which triggers the second dialog.

**Comment by caillean7** [comment]
The culprit block is lines 34 to 46:
```
IF
	See([PC])
	!InParty(Myself)
	Global("NaliaMove","GLOBAL",1)
	CombatCounter(0)
	Global("NaliaInitKeepOnce","GLOBAL",0)
	Global("NaliaKeepPlot","GLOBAL",0)
THEN
	RESPONSE #100
		StartDialogueNoSet([PC])
		SetGlobal("NaliaInitKeepOnce","GLOBAL",1)
END
```

**Comment by lynxlynxlynx** [comment]
That's for the first dialog for sure, but you're saying it also triggers the second one?

**Comment by caillean7** [comment]
No, I'd say the first one is triggered by lines 48 to 56:

```
IF
	See([PC])
	NumberOfTimesTalkedTo(0)
	Global("NaliaTalkedTo","LOCALS",0)
	CombatCounter(0)
THEN
	RESPONSE #100
		Dialogue([PC])
END
```
At the end NaliaMove is set to 1, which is necessary  to trigger the 2nd talk.

**Comment by lynxlynxlynx** [comment]
Oh, right, I shouldn't be multitasking. At least it confirms nothing funny is going on. I think it breaks because internally MoveBetweenAreas is called, which isn't blocking like the parent actions.

**Comment by lynxlynxlynx** [comment]
9 ticks go by fine and then it breaks, never entering EscapeAreaCore any more (MoveBetweenAreas is never even reached). I've added a fix, but I'm not sure why it is needed in the first place — the action is blocking, so her script should never get reevaluated. Nothing fishy in the area script, but also backtracking in such a full area is highly annoying. So it will remain as is.
