### ISSUE TITLE
[bug] BG2: MoveViewPoint in some mod cutscenes not working

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#254]
**Description**
In some modded cutscenes GemRB seems to ignore MoveViewPoint - the focus stays on the party in some corner of the map, and you can't see what's going on. I've seen it with one cutscene from Imoen4ever mod, and one from I shall never forget mod.

Example ISNF, the final cutscene (from isnfxc2.baf):
```
IF
True()
THEN RESPONSE #100
CutSceneId(Player1)
StartCutSceneMode()
FadeToColor([40.0],0)
Wait(4)
LeaveAreaLUA("ISNF08","",[400.1800],4)
MoveViewPoint([920.2240],INSTANT)
Explore()
CreateCreature("CUTSPY",[777.2170],12)
CreateCreature("CUTSPY",[1080.2222],12)
FadeFromColor([40.0],0)
Wait(4)
...
```
You can see your PC standing there, and depending on your resolution probably, just see the cutscenes actors on the bottom of the screen. I tried this on the classic IE, it works there, the focus is on the actors, Charname is not visible.

EDIT: Save this view point issue the cutscenes work, and GemRB log shows no errors.

**GemRB version**
0.85-git

**To Reproduce**
* install the 'I shall never forget' mod from [here](http://www.shsforums.net/files/file/1004-i-shall-never-forget/)
* load any save game, access the console, type:
`ExecuteString('StartCutscene("ISNFxc2")')`

**Expected behavior**
Move the focus / view point to the actors of the cutscene

**Screenshots**
Cutscene in GemRB
![gemrb_cutsc](https://user-images.githubusercontent.com/54738589/65761171-99603b80-e11e-11e9-97b3-dbc5a2ba9720.jpg)
... and in the classic IE
![IE_cutsc](https://user-images.githubusercontent.com/54738589/65761225-ae3ccf00-e11e-11e9-9459-cbc2f623ae2a.jpg)

**Comment by lynxlynxlynx** [comment]
Nice, are those converted iwd2 areas? Anyway, this might be related to #179, but I doubt it. Do you get the same results if you comment the fades out?

**Comment by caillean7** [comment]
I think they might originally be from IWD2, but it's been ages since I played it. All the Colours of Infinity mods by Lava have beautiful artwork, areas included. He's really good with areas, the Southern Edge district for Athkatla and the Ooze's Lounge look amazing, too.

I commented all FadeToColor stuff out and ran the cutscene again, no change.

**Comment by caillean7** [comment]
Just been looking into the other case with the Imoen4ever mod, which makes changes to the cutscene at the beginning of chapter 3 (after you paid off Gaelen, "The girl they just brought in, she' a cute one, isn't she..."). Re-checked the vanilla cutscene, and had the problem there, too, so this is not purely a mod issue:
![cutscene_chptr3](https://user-images.githubusercontent.com/54738589/65792351-d864b000-e163-11e9-9485-b96af7645451.jpg)

**Comment by caillean7** [comment]
Perfect, thank you.
