### ISSUE TITLE
Mazzy's eulogy doesn't end properly

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#256]
Split from #246, but basically after defeating the shadow altar and co, Mazzy goes to write on the old altar ... but at the very end we don't continue the dialog with a "has nothing to say" error.

cut30b runs DayNight after teleporting peeps away, so there's a lot of time passing. But it's still in a cutscene, so it should be fine. ~I think more gritty details need to be investigated — do we get one tick in already at creation, somehow bypassing the update check?~ I doubt it, but it could easily be an off-by-one error somewhere. One tick too many is enough.

The new area script needs to run in between the cutscenes for the chain to work:

1. old area (ar1404) runs cut30a on enemy death
2. cut30a teleports everyone to the new area (ar1400) and ends
3. ar1400 runs cut30b (so it has to be running)
4. cut30b starts a dialog
5. dialog sets MazzyAltar to 1 and starts cut30c
6. cut30c starts a dialog
7. dialog sets MazzyAltar to 2 and starts the same dialog ("It is done")
8. dialog doesn't find the correct state due to MazzyAltar=3 by the area script interference. Otherwise the dialog would set it to 3 and continue the scene.

Individual cutscenes end when the dialog finishes. So the problem starts somewhere from 5 onwards. Time to do some timing and the annoying tracking of MazzyAltar changes.

**Comment by lynxlynxlynx** [comment]
it's set to 3 before starting cut30c (after "Aye it would") and back to 1 practically immediately. Then more action, "Know noble" with 2 right after, 3 practically immediately and bam.

**Comment by lynxlynxlynx** [comment]
So on transition between 6 and 7 the dialog shows "Know..." and you have control (good place to activate noisy breakpoints). When you end the dialog by clicking, it runs the action payload in the same tick. However, second of the four actions is Wait (blocking = the only non-instant), so just the first one is ran immediately, the rest queued on Mazzy [_or all, since currently master inserts a BreakInstants at the start_]. Since EndDialog got called, we're officially out of dialog too, so script execution resumes normal course. We begin a new tick and scripts run again in order (global, area, actors), so the area script always gets a chance before actors.

There is some staggering involved based on globalID for everyone, so in rare cases one might get lucky and the actor's would fire first. But in this case it wouldn't do any good, since any chance Mazzy gets to run her script, she just counts off that wait (and it's too long even for extreme luck).

It seems what we want is that other or just area scripts are blocked until dialog end blocks are done. Just like it was a cutscene or while still in dialog. We specifically disable the first, since things would otherwise break (added for Hjollder of HoW, who starts it manually), while the second is there for a similar use case — dialogs starting dialogs.  Some of this might need changing or maybe other methods are in order.

Treating the action block as a cutscene does fix this bug, but it's likely not correct.

**Comment by lynxlynxlynx** [comment]
Good news, it didn't break Hjollder, so it's going in.

**Comment by lynxlynxlynx** [comment]
Unfortunately it breaks cases where the speaker selfdestructs as the dialog ends. Then the fake cutscene never ends and you're stuck. This is visible with Melissan the first time you enter Saradush. :(

**Comment by bradallred** [comment]
Can't we just terminate cutscenes as soon as either the target or source are destroyed?

**Comment by lynxlynxlynx** [comment]
Sure, but it'd be layering a new bunch of hacks over the existing one. I'd rather find a solid solution.
