### ISSUE TITLE
[bug] Some creatures should not have circles

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#258]
**Describe the bug**
When I entered the final battle area of Baldur's Gate, I found something odd and distracting: all those light blue circles - of bats. They did not have them, or at least not here. Also: In the original, you cannot attack them, and also area spells leave them unaffected.

GemRB version: Current Head

**To Reproduce**
1. Start BG
2. Go to AR0125
3. Notice the bat creatures and their circles.

**Expected behavior**
![bug_bats_circles_good](https://user-images.githubusercontent.com/238558/65838755-c4a57f00-e306-11e9-82c7-e2093c18e74f.jpg)

You can find three bats without circles here.

**Screenshots**
![bug_bats_circles_bad](https://user-images.githubusercontent.com/238558/65838763-cec77d80-e306-11e9-8ab6-68a2902ed1dc.jpg)

**Comment by lynxlynxlynx** [comment]
Do you have the same marker feedback settings on in both games? Remember that if you changed any options, there's two files in play, baldur.ini and gem-baldur.ini.

**Comment by MarcelHB** [comment]
What's the setting you refer to named? I don't even know what to look for exactly. Maybe `Locator Feedback Level`? It is 3 in both settings.

**Comment by MarcelHB** [comment]
Ok, there is also `Circle Feedback` in the code but no explicit setting in any of the INI files.

**Comment by caillean7** [comment]
It's called 'Marker Feedback'.

**Comment by MarcelHB** [comment]
Well, if it's that what I find in the code, it refers to `GUI Feedback Level` which is 5.

**Comment by caillean7** [comment]
Huh, not sure how it's called in the ini, I set it ingame, Options->Gameplay->Feedback->Marker Feedback.

**Comment by lynxlynxlynx** [comment]
Yes. When it's at max (5), I can see the circles on bats. One less, only during pause. As designed.

Easiest to check by just loading the mission pack save. IOW can't reproduce.

**Comment by caillean7** [comment]
Works for me, too.

**Comment by lynxlynxlynx** [comment]
And two are visible in your screenshot at #257.

**Comment by MarcelHB** [comment]
Yes, #257 is taken from GemRB in the same context. But in the original, I set that mentioned slider set to max, and they aren't there. I just played around: Yes, it affects the other (humanoid) creatures, but not the bats?

**Comment by MarcelHB** [comment]
Maybe it's that I don't have the mission pack installed (it is vanilla v1.1.4135). In that case, and if you cannot reproduce, there is probably no need to address this.

**Comment by lynxlynxlynx** [comment]
Ah, the reverse. It is so minor and goes against the description, that I'm not sure we should care.

We could patch it if we find out what's so special about these buggers. No effects (eg. there's a dedicated one to suppress the circle), nothing interesting in the dump.

**Comment by MarcelHB** [comment]
Not sure, reasons against the feedback theory: You cannot attack them by cursor, and not even a spell such as fireball touches them.

**Comment by lynxlynxlynx** [comment]
Do they don't have any effects in your install either? They could have the "do not jump" stat set for example (the same way you can't touch seagulls).

**Comment by caillean7** [comment]
BG2 has those bats, too, (e. g. at Underdark Exit AR2500) and the IE doesn't show circles for them even at maximum marker feedback. They don't have any active effects, however.

**Comment by lynxlynxlynx** [comment]
How about the other animals? None of interesting stats seem to be set.

**Comment by MarcelHB** [comment]
What's the easiest way to get the list effects on an actor?

**Comment by izhuravlev** [comment]
Hey everyone, 
I will be happy to help with this one and find out what's wrong.

**Comment by lynxlynxlynx** [comment]
@MarcelHB ctrl-m while pointing to them.

@caillean7 are bats the only ones without the circles in ar2500? I'm sure the moose has it, since you should be able to charm it, but not sure about the pheasants.

@izhuravlev Cool, thanks! We're still researching how the bats are special and if they're alone in that regard. Not all animals are affected, so there has to be some other discriminator.

**Comment by caillean7** [comment]
The pheasants do have their circles, as do the rats and all other small animals. I looked at the creatures in NI, and I can't see anything that sets bats apart from the others, but then, not sure what to look for.

**Comment by lynxlynxlynx** [comment]
I wonder if it was a size thing and they're just too small. Try with a 0 circle size in avatars.2da.

**Comment by caillean7** [comment]
Setting size to zero for a creature makes the circle go away, but the cursor still changes when hovering over it. Marcel's bats in IE however don't affect the cursor at all. So that's only part of the solution.

**Comment by lynxlynxlynx** [comment]
Seagulls have the "do not jump" stat set, so they can fly over anything and be completely removed from things. Such creatures are already excluded from "circling", but I now see we don't just rely on the effect or the cre having a base set. Bats could be added here:
https://github.com/gemrb/gemrb/blob/c7e0932ffe2346fdef724a88129e2cd652b61aa9/gemrb/core/Scriptable/Actor.cpp#L686-L694

Does 7 as the animation type in avatars.2da work for bats per chance too? That would be the cleanest solution, though it's probably a long shot.

**Comment by caillean7** [comment]
Yeah, won't work, they don't get drawn:
```
[ResourceManager/ERROR]: Couldn't find 'abat.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: abat (c500)
```
So no declaring them birds.

**Comment by lynxlynxlynx** [comment]
Ok, thanks. 

@izhuravlev  So the best way forward is to use CharAnimations::GetCircleSize instead of the above IE_ANI_BIRD check. And set it to 0 for bats in all the avatars.2da files.

**Comment by caillean7** [comment]
It doesn't work - we still have a talk cursor for bats and birds. So I reverted that to the old code and checked the birds again. They actually do have a talk cursor. So they had one all the time?!

**Comment by lynxlynxlynx** [comment]
Just another thing to fix, but that's a separate bug ... you know what to do. At minimum Actor::ValidTarget(GA_TALK) needs to return false for them.

**Comment by MarcelHB** [comment]
Do we know for sure that these mysterious "unused" bytes in the actor entries of the map are truly unused? I mean, did somebody ever check the executable? Otherwise, if it's not in the creatures files, and I did not spot any hardcoding in the executable without going too deep, would it make sense to investigate around there?

**Comment by lynxlynxlynx** [comment]
Why do you think it has something to do with the area? It's likely this was hardcoded in the animation code like everything else.

**Comment by MarcelHB** [comment]
Principle of exclusion, seperation of concerns ... just developer things.

**Comment by lynxlynxlynx** [comment]
Sounds like a waste of time to me, but you can search the iesdp forums to see if anyone reversed them. Or if the full header for EE ARE was posted (I forgot which formats were).

**Comment by caillean7** [comment]
>  ... you know what to do.

Who, me or @izhuravlev ? And sorry for just meddling with this, I'm just trying this here locally, might learn something in the process.

**Comment by lynxlynxlynx** [comment]
I meant: open a separate report. ;)

**Comment by caillean7** [comment]
Will do. Well, you're not here to tutor people in programming, but I've got the Actor::ValidTarget working and the no circle thing. If you give me some pointers for the cursor and tooltips, perhaps I could finish this.

**Comment by lynxlynxlynx** [comment]
Onboarding new contributors is definitely one of my "job" descriptions. Pastebin the code and I can take a look; it's a bit easier than rewriting git history of an already opened pull request, unless you're handy with git already.

Btw, I have this in my .bashrc:
`gdup() { git diff "$@" | curl -s -F 'sprunge=<-' http://sprunge.us | sed 's,$,?diff,';  }`
just wraps git diff and pastes it directly, returning a handy url.

**Comment by caillean7** [comment]
Yeah, but I'm no programmer, just have a very basic understanding of this and a strange interest / fascination. Anyway, this is what I did to Actor.cpp: https://pastebin.com/VCzzi28h

C&Ped to mine :D

**Comment by lynxlynxlynx** [comment]
That's how you start. :) The diff looks fine if I disregard formatting.

**Comment by caillean7** [comment]
Are you referring to the spaces between the text and the brackets? Should there be spaces?

**Comment by lynxlynxlynx** [comment]
https://pastebin.com/WnnzByKy

**Comment by caillean7** [comment]
'kay, so no spaces there but spaces for the operators. Want me to try with a pull request?

**Comment by lynxlynxlynx** [comment]
Yes, but don't forget to also modify the avatars.2da files.

**Comment by caillean7** [comment]
Are there bats in PST? I don't have this one, I'm afraid, and it's avatars.2da differs from the others. Would be cool if someone with a PST installation could check that. The others are done.

**Comment by lynxlynxlynx** [comment]
There aren't, go ahead.
