### ISSUE TITLE
[subviews] loading game fade

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#260]
When you load a game from within the game, we jump to black and do a slow fade out first (unloading the game win?). It's annoying, let's not do that.

**Comment by bradallred** [comment]
Hmmmm, I don't know what you are talking about. I either don't see anything like a fade or it happens too fast to notice... possibly the fade is altogether broken on SDL 2? or maybe a specific game?

The only fade I remember adding was for the beginning of BG2 specifically to fix the annoying issue where you see the interface and everything else briefly before the scripted fade is executed. That fade was added in CharGenEnd.py for BG2 only.

We do delete and recreate `GameControl`, but thats a pretty necessary thing to do for hopefully obvious reasons and shouldn't cause any fade anyway.

**Comment by lynxlynxlynx** [comment]
I have it in bg1, pst, iwd2 but not bg2 and iwd1.

**Comment by bradallred** [comment]
I haven't been able to replicate this with either BG1 or PST either.

**Comment by MarcelHB** [comment]
I had it lots of times today, I'll try to describe steps for reproduction later.

**Comment by bradallred** [comment]
it sounds like something with the fade isn't being explicitly initialized to 0 then.

**Comment by MarcelHB** [comment]
Ok, in BG1 the following steps:

1. Start BG, and from the main menu, load a game.
2. After loading, go back to options.
3. Leave the game back to the main menu.
4. Now, to the load screen again.

In the last step, the save game list fades in very slowly.

**Comment by bradallred** [comment]
Nope, still can't reproduce this. I think one of you is going to have to debug it.

**Comment by MarcelHB** [comment]
Cannot reproduce any more.
