### ISSUE TITLE
[subviews] modal actions lack feedback

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#261]
Searching for traps or turning undead doesn't display the modal starting text like "Turning undead". Playing around by switching among them I could get the end/failure ones for stealth displayed, but that's it.

**Comment by bradallred** [comment]
You are talking about the string in the message window? If so I cannot reproduce this. More details required.

I _did_ see a different bug: if you have somebody doing an action such as turn undead and then you have another actor start another action that also starts the same round the text area will scroll from the very top to the bottom. It doesn't seem to like 2 messages being appended in the same frame. You can confirm this by altering the code to just double print messages.

**Comment by lynxlynxlynx** [comment]
Maybe it happens only on sdl1 then.

**Comment by lynxlynxlynx** [comment]
Ah, bg2 is fine, while bg1 isn't.

**Comment by bradallred** [comment]
This doesn't work on master either and the reason is there is no modal.2da for BG1. the shared 2da only has a valid entry for stealth.

**Comment by caillean7** [comment]
At least BG1 and IWD1 don't seem to have strings like "Turning Undead" / "Detecting Traps".

**Comment by lynxlynxlynx** [comment]
Ah, nice, so we can't do much about it, stuff for the tweaks.
