### ISSUE TITLE
iwd1 worldmap icons and icon title miscolored

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#262]
Start a bg1 char and go to the world map. We have three different color schemes now:
- master: unreachable icons are red, titles violet or white; everything is filled in
- subviews: all icons are light grey, titles violet or white; everything is filled in
- original: unreachable icons are of the same color as the roads on the map, all text likewise; visited areas are filled in

So it's clear we are applying the unreachable red blending too often (did bg1 use it at all - it definitely did the blue one for reachable neighbours?). These areas are technically not discovered yet. IIRC bg1 has an override palette for the icons and maybe that's where our pink is from.

![](http://www.oocities.org/timessquare/arena/8461/baldurs-gate-worldmap.jpg)
bigger: http://www.thecomputershow.com/computershow/graphics/bgworldmap.jpg

**Comment by MarcelHB** [comment]
Not sure if related to this one, but hovering destinations in IWD also look odd, like inverted.
![iwd_map](https://user-images.githubusercontent.com/238558/67982282-ac38c500-fc22-11e9-9c6f-f11e139a6d24.jpg)

**Comment by lynxlynxlynx** [comment]
Got partly resolved through the work in #1244. Changing to iwd-specific.

**Comment by lynxlynxlynx** [comment]
... which already works fine too.
