### ISSUE TITLE
[bug] viconia's post-sleep cutscene never completes (cut34a.bcs)

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#268]
Her dialog triggers when you try to rest. It fires, we chat and it fires cut34a:
```
IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  //
    FadeToColor([30.0],0)
    Wait(3)
    FadeFromColor([30.0],0)
    RestParty()
    EndCutSceneMode()
END
```
Wait gets a tick in and something then wipes it, so the restparty never executes and one is stuck in cutscene mode while the world continues (so resting happens from our button). Sounds awfully similar to #253, but what's the breaker here is our interruption from RealRestPress (2 tick delay). If the rest there is commented out, RestParty does get called. But not EndCutSceneMode. RunRestScripts runs vicond.bcs which starts the initial dialog that then starts the problematic cutscene, but we don't detect the rest there, so we try it twice.

So it seems at minimum GemRB.RunRestScripts needs to be checked/improved, as it shouldn't be returning false in this case. db58cd7fdc5 could be improved to just never run our rest if any script ran. Due to potentially blocking actions, we can never set a reliable delay.

That leaves the question of why EndCutSceneMode isn't being run ... which is due to resting clearing all actions.

**Comment by caillean7** [comment]
For your "Better compatibility with mods" feature list (should you keep one): It also solved a problem with the Check the bodies chores component rest cutscenes, where you would get stuck in cutscene mode and couldn't complete the chores part.
