### ISSUE TITLE
[bug] BG2 GUI: Chargen Multiclass scrollbar not functional

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#269]
**Description**
When you have multiple custom multi-class mods installed, only the first is selectable from the list on character creation, because the scrollbar doesn't seem to work.

**GemRB version**
0.85-git

**To Reproduce**
- install at least two different multi-class mods for GemRB
- start character generation and pick Multi-Class in the Class selection part
- try using the scrollbar

**Screenshots**
![chargen](https://user-images.githubusercontent.com/54738589/66040040-c47bce00-e516-11e9-996c-26ae9b66df12.jpg)

**Comment by lynxlynxlynx** [comment]
This is handled in gemrb/GUIScripts/bg2/GUICG10.py ... which already has a TODO mentioning the scrollbar, so it seems the work is cut out for someone. It looks like it doesn't take TopIndex into account. The kit selection window (GUICG22.py) has this working, so can be a cheat sheet.

**Comment by caillean7** [comment]
If you think it's idiot-proof enough, I'll take a look.

**Comment by lynxlynxlynx** [comment]
You can try if you want. All the ggod-first-issue reports are good starting points for new contributors, so the rest of us must resist the urge and ensure there's always some available.

**Comment by caillean7** [comment]
Since I kinda stole @izhuravlev's job with the bird circles, wouldn't it be fair if he could do this one? :D
 (In other words, this stuff is crazy, noooo way I get this done)

**Comment by lynxlynxlynx** [comment]
Heh, that's up to him. But, of course, it's open for everyone.

**Comment by bernds** [comment]
Which mods exactly would help reproducing this?

**Comment by lynxlynxlynx** [comment]
The two class one here:
https://github.com/lynxlynxlynx/gemrb-mods

Recent changes might have broken something though, I remember someone changing a table. Let me know if they don't install etc.
