### ISSUE TITLE
[bug] Item usability issue with custom multi-class

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#270]
**Description**
Like explained [here](https://www.gibberlings3.net/forums/topic/30661-new-multi-class-combination-some-questions) there is an issue with Gnome PCs unable to use items they're supposed to be able to use. E.g. an half-elven PC with the Ranger-Thief multi-class can use Ranger specific items like the Moon Dog Figurine (MISC7T.itm) while a Gnome with the same class can't. The figurine has no race-specific unusable flags.

**GemRB version**
0.85-git

**To Reproduce**
- install the mod from [here](https://github.com/caillean7/ranger_thief)
- start a new game & create a new human / half-elven / elven character and choose the Ranger / Thief multi-class
- Give yourself the Moon Dog Figurine
`CreateItem(1,"MISC7T")`
- you should be able to use it
- do the same with a Gnome, and they shouldn't be able to use the figurine

**Expected behavior**
No Gnome discrimination

**Comment by lynxlynxlynx** [comment]
Does it start working if you add the illusionist bit to the item's usability? I suspect this has the same underlying problem as #272.

**Comment by caillean7** [comment]
Indeed, if I remove the unusable flag for Illusionist, I can use it.

**Comment by lynxlynxlynx** [comment]
So yeah, you have a ranger/thief with an illusionist kit on top. Closing as a dupe.
