### ISSUE TITLE
Gnomes are limited to the Illusionist kit

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#272]
**Description**
Another Gnomish specialty related to #270 from the thread [here](https://www.gibberlings3.net/forums/topic/30661-new-multi-class-combination-some-questions/). Internally their kit can only be "Illusionist", it seems, so with custom multi-class combinations the alignment choices are not restricted on character creation as they possibly should be (depending on the mod).

EDIT: Should probably have opened this as a feature request, not a bug.

**GemRB version**
0.85-git

**To Reproduce**
- install the mod from [here](https://github.com/caillean7/ranger_thief)
- this mod restricts alignments to NG and CG
- create a Gnome Ranger / Thief and proceed to the alignment choice
- all alignments are selectable

**Expected behavior**
Enforce alignment restrictions for Gnomes, too. Don't limit them to the Illusionist kit.

**Comment by lynxlynxlynx** [comment]
Like I said, it goes wrong before you get to see the alignment buttons, so it's not about that at all.

**Comment by caillean7** [comment]
So is it the mod or something GemRB does? I see things in GUICG2.py about that Gnomes being Illusionists, but I can't say I really understand how it works.

**Comment by lynxlynxlynx** [comment]
The mod is just exposing a problem.

**Comment by caillean7** [comment]
https://github.com/caillean7/gemrb/commit/85544a073013d6542b10f54dc5875716da5eddbb

Works - is this acceptable?

**Comment by lynxlynxlynx** [comment]
Not really, your mod inserts 1s and the only single class with 2 is mage, so how can you get other values there? What are they?

**Comment by caillean7** [comment]
Can't answer that, but it fixed both my gnome problems and I couldn't find anything with chargen either.

**Comment by lynxlynxlynx** [comment]
You can add a print statement in front. Your change should have no effect is what I'm saying.

**Comment by caillean7** [comment]
What can I say? Just that I can create gnome Ranger / Thieves that can use Ranger items and the Alignment selection is right with that change.

**Comment by caillean7** [comment]
Okay, that was stupid. One more try, then I stop, I swear. So in GUICG2.py we're always getting a value of 5 (Illusionist) for GemRB.MAGESCHOOL if we're gnomes. The only way to get rid of that is to choose another kit via the Kit Window. So I included another check for Class IDs to get rid of the 5 if not any mage class.
https://github.com/caillean7/gemrb/commit/9f8660ba6301d820f91cefd77aa5bbb9e4f2a055

**Comment by lynxlynxlynx** [comment]
No, this is a worse hack than the one before it (just now realized why it works — it's just never true). The school thing should not have an effect on non-mages at all. Eg. Are cleric/thieves broken too? Then the fix likely requires a bit of restructuring.

**Comment by caillean7** [comment]
I think I feel a slight migraine coming... ahem - no, they're not broken. I made one and gave her a Potion of Masterthievery, she was able to use it. Anyway, I've been adding debug messages all over the place, and as soon as GUICG2 runs, it assigns this value of 5 to MAGESCHOOL. This check for Allowed == 2 doesn't seem to work.

**Comment by caillean7** [comment]
Btw, I had it print values for Allowed, they seem okay in GUICG2 and 10.

**Comment by lynxlynxlynx** [comment]
It does work, but it's looping over all classes, so one match is enough — and that's the mage.

**Comment by caillean7** [comment]
Okay, I'll go away now :D Call me if you need some bisecting / dissecting / testing done.

**Comment by lynxlynxlynx** [comment]
Please check if this does the trick:
```
diff --git a/gemrb/GUIScripts/bg2/GUICG2.py b/gemrb/GUIScripts/bg2/GUICG2.py
index 608c835b4..239db3691 100644
--- a/gemrb/GUIScripts/bg2/GUICG2.py
+++ b/gemrb/GUIScripts/bg2/GUICG2.py
@@ -126,7 +126,7 @@ def SetClass():
        KitIndex = GemRB.GetVar ("Class Kit")
        MageSchool = GemRB.GetVar ("MAGESCHOOL")
        #multiclassed gnomes 
-       if MageSchool and not KitIndex:
+       if MageSchool and not KitIndex and "MAGE" in ClassName:
                SchoolTable = GemRB.LoadTable ("magesch")
                KitIndex = CommonTables.KitList.FindValue (6, SchoolTable.GetValue (MageSchool, 3) )
                KitValue = (0x4000 + KitIndex)
```

**Comment by caillean7** [comment]
It does, alignment choice and item usability are fine with this.
