### ISSUE TITLE
[subviews] Assertion crash after closing the area map view in PST

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#275]
**Describe the bug**
Assertion failure in PST when clicking around the area map view.

**To Reproduce**
1. Open the area map in game.
1. Close the area map.
1. Click right somewhere on the game map, other clicks may or may not trigger the crash, too.

**Logs**
```
Assertion failed: unregistered, file ./gemrb/core/GUI/View.cpp, line 711
```

**Comment by bradallred** [comment]
this is going to be the same issue as 5815ef4

**Comment by MarcelHB** [comment]
Ok, I'll pick them up later today.

**Comment by MarcelHB** [comment]
Ok, I'll pick them up later today.

**Comment by bradallred** [comment]
no worries, I got this one, but it probably wont be the last. I think replacing controls is something we do fairly often and if we don't delete the old one first this will happen now... on master this is a silent problem.
