### ISSUE TITLE
[subviews] Sprite cover issues with items on the ground

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#277]
**Describe the bug**
In IWD2, there are some items on the ground. You see two anomalies in the screenshot:

1. The one that is positioned on the map isn't covered by the polygon.
2. The one I placed next to it to test positioning issues disappears mostly below the snow, mostly.

**Screenshots**
![iwd2_items_spritecover](https://user-images.githubusercontent.com/238558/66241930-92c65b00-e700-11e9-89f9-6fe32e0b2dc1.jpg)

**Comment by bradallred** [comment]
It would be handy to know how it is in SDL 1 (that goes for any rendering issue really).

**Comment by bradallred** [comment]
doesn't look like actors are afflicted. Have to look at how the covers are generated for piles vs actors.

**Comment by bradallred** [comment]
![image](https://user-images.githubusercontent.com/1126744/66249306-6a356580-e6ee-11e9-951b-c58950835e48.png)

seems much better when dithering is forced.

**Comment by bradallred** [comment]
to compare master:

![image](https://user-images.githubusercontent.com/1126744/66249454-03657b80-e6f1-11e9-8d12-7dc6217f1428.png)

with subviews:

![image](https://user-images.githubusercontent.com/1126744/66249481-9dc5bf00-e6f1-11e9-9e08-759e6b0673f0.png)

its clear that the covers (for at least items) are misaligned

**Comment by MarcelHB** [comment]
SDL1.2 is still looking good here.

**Comment by bradallred** [comment]
closing as resolved by #441
