### ISSUE TITLE
[subviews] Color of the cursor when above disabled UI elements

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#281]
Whenever you move the cursor over something that is disabled (buttons, I guess), it turns gray. I'm not sure if you intend this as second indicator for the disabled state, but I noticed it looks hard to notice in Baldur's Gate for some occasions, like the main PC generation.

![gray_cursor](https://user-images.githubusercontent.com/238558/66259357-55b9a180-e7b0-11e9-874a-97e203bde9da.jpg)

**Comment by bradallred** [comment]
This is indeed intentional

**Comment by MarcelHB** [comment]
Ok, close these things if you think so.

**Comment by lynxlynxlynx** [comment]
What did the original do? This is a change from what we have in master.

**Comment by MarcelHB** [comment]
Without having checked everything in detail here: what master does.

**Comment by lynxlynxlynx** [comment]
So, any opposition to rolling this back? We'll just get user complaints otherwise, that's why I'm pushing for it.

**Comment by bradallred** [comment]
Let me handle it.
