### ISSUE TITLE
[subviews] Color picker controls are broken

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#282]
In every game (except PST), the color picker controls are still broken:  There's only just one color, ~or sometimes none at all, such as in BG~:

![bg_colors](https://user-images.githubusercontent.com/238558/66259401-ef814e80-e7b0-11e9-99f5-0bf39ccd0b59.jpg)

**Comment by MarcelHB** [comment]
These button all end up having the same palette values, not sure yet where this happens.

**Comment by lynxlynxlynx** [comment]
In master the inventory part of this window is here: https://github.com/gemrb/gemrb/blob/master/gemrb/GUIScripts/InventoryCommon.py#L638
It's just reading from a table, so I suspect it goes wrong later ... if this code is the same in subviews.

**Comment by MarcelHB** [comment]
Yep, it's down in the SDL2 code somewhere - all good for 1.2 here.

**Comment by MarcelHB** [comment]
@bradallred I think the problem and solution is buried in this code block: https://github.com/gemrb/gemrb/blob/9cfacb2942b025bdc32f1b3dcaefff717a77a1f0/gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp#L67-L86

If the sprites share the surface via copy constructor (they obviously do here), palette switching and drawing is probably not correlated anymore. If I uncomment that code and fix it for some syntax, the problem is gone. Not sure about the rationale here (performance?) or do you have a better idea how to fix this now?

**Comment by bradallred** [comment]
it's mostly a memory use conservation. The surface itself is only source material for the textures, each separate `SDLTextureSprite2D` is supposed to have its own texture so it shouldn't need its own copy of the pixels as we never edit pixels.

i'm not even sure off the top of my head what these are supposed to look like, but I doubt using a palette is the optimal thing to do for SDL2. If we could just do a color multiply (`BLIT_TINTED`) that would be nice and simple.

Are these palettes from a BAM or are they ones we generate ourselves?

**Comment by MarcelHB** [comment]
Can't get the details right now, but it was from a call to `core->GetPalette(...)`.

**Comment by lynxlynxlynx** [comment]
They're from a COLGRAD.BAM.

**Comment by bradallred** [comment]
Ok, I'm gonna do some research on this.

**Comment by bradallred** [comment]
@MarcelHB what you suggested is close. I did verify that these palettes aren't just a poor mans color mod (though EE certainly gives the appearance its doing something like that).

We still have no need to copy the pixels, so ditch the malloc and set `freePixels = false` and that should be fine.
