### ISSUE TITLE
[subviews] Main action controls look and behave weird when disabled

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#283]
Also in many games (BG, BG2, IWD), some PCs don't have the features enabled yet that render some action bar items disabled. This has some issues:

1. The color of disabled items is not as in the original - Ok, it's also like that in master, you can ignore that.
2. You can click anyway, sometimes you end up in an empty bar (item features), or the items turn active for no good reason.

BG par exemple:

![bg_action_controls](https://user-images.githubusercontent.com/238558/66259523-3cb1f000-e7b2-11e9-8c7f-b53aac238187.jpg)

**Comment by lynxlynxlynx** [comment]
What did you click in the screenshot (or what does before-after show)?

**Comment by MarcelHB** [comment]
The spell icon.

The undead-thing plays a sound, the item button brings me to an empty bar.

**Comment by bradallred** [comment]
was there a Python error associated with this? Seems like the most likely reason for it since I don't recall a need to do anything with the action buttons. Its clearly not a rendering issue since you say you can also toggle them.

**Comment by lynxlynxlynx** [comment]
This is all done in the binding - GemRB_Window_SetupControls, so that's where I'd start to look.

**Comment by MarcelHB** [comment]
There is a Python error when clicking on the spell book icon but NOT for the other ones.

```python
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File ".\GUIScripts\GUICommonWindows.py", line 993, in ActionCastPressed
[Python/ERROR]:     UpdateActionsWindow ()
[Python/ERROR]:   File ".\GUIScripts\GUICommonWindows.py", line 705, in UpdateActionsWindow
[Python/ERROR]:     Spellbook.SetupSpellIcons(CurrentWindow, type, TopIndex, ActionBarControlOffset)
[Python/ERROR]:   File ".\GUIScripts\Spellbook.py", line 200, in SetupSpellIcons
[Python/ERROR]:     raise AttributeError ("Error, unknown BookType passed to SetupSpellIcons: %d! Bailing out!" %(BookType))
[Python/ERROR]: AttributeError: Error, unknown BookType passed to SetupSpellIcons: 3! Bailing out!
```

**Comment by bradallred** [comment]
The error I was theorizing would have happened when the window was created, not when clicking the button, but I'll copy that error as a new issue.
