### ISSUE TITLE
[subviews] Place death message dialogs at the bottom.

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#285]
In all of the games, when the main/last PC died, the message asking for reloading is always centered, not at the bottom.

More like an aesthetic bug:

![death_screen](https://user-images.githubusercontent.com/238558/66259596-07f26880-e7b3-11e9-88cc-c2e0341a2b39.jpg)

**Comment by bradallred** [comment]
this is just a matter of adding the correct flag on those windows. There are also probably a bunch of windows that need the `borderless` flag set too.
