### ISSUE TITLE
[subviews] Exit windows

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#287]
In nearly all of the games, when clicking _Exit_ (or _Quit/Leave_, not sure what the English versions say) in the main menu, the dialogs are not what I expected:

* Baldur's Gate: It's a black background.
* Baldur's Gate: The overlay (?) has some pixles offset over the background, showing a bit of the underlay.
* Icewind Dale 2: No gray layer, this allows you to click everything in the background.
* Planescape Torment (on Full HD): It's centered, unlinke the original, thus not covering the other controls, also allows clicking around.

IWD is fine.

**Comment by bradallred** [comment]
sounds like window flags are not set appropriately. They should all have the `NeedsAlpha` and `Borderless` flags and be presented modally. Black background indicates no alpha and being able to click other windows indicates the window wasn't shown with `DisplayModal()`

PST probably should be centered now for resolution independence purposes (tho I have no image in my mind about it). Again it should be presented modally.

**Comment by lynxlynxlynx** [comment]
Either this is too old or something else is at play — all four games here have no transparency issues. SDL1 as usual and standard resolutions.

**Comment by MarcelHB** [comment]
I still see all those misbehaviours on SDL2, or you refer _transparency issues_ to something particular here?

For SDL1, IWD shows no gray layer behind the modal exit dialog, and BG1 is otherwise buggy (not clearing the menu background).

**Comment by lynxlynxlynx** [comment]
All modals appear modal to me (tried clicking on actors or the action bar for example), but it's true that they don't have that dithered surrounding.
... but I see it's not exactly the same for the menu, I was testing from ingame. BG1 indeed stops drawing and you either have garbage (cursor trails) or it turns black at some point.

**Comment by bradallred** [comment]
> Baldur's Gate: The overlay (?) has some pixles offset over the background, showing a bit of the underlay.

I have no idea what you mean. screenshot?

> Planescape Torment (on Full HD): It's centered, unlinke the original, thus not covering the other controls, also allows clicking around.

if the window is modal who cares?

**Comment by MarcelHB** [comment]
PST is not modal from what I see. I'll post a screenshot for BG2 later.

**Comment by MarcelHB** [comment]
You don't have this on master.

![bg2_exit](https://user-images.githubusercontent.com/238558/69532491-40721f80-0f76-11ea-8d3f-4e4b655101a5.jpg)

**Comment by bradallred** [comment]
> PST is not modal from what I see. I'll post a screenshot for BG2 later.

sure it is. I just made them all modal.

**Comment by MarcelHB** [comment]
You're right, I did not notice your change in the meantime.

**Comment by MarcelHB** [comment]
I'm closing this because that BG2 thing is probably part of something more general when having a window modally another window.
