### ISSUE TITLE
[subviews] Scrollbar body missing in BG item pickup view

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#289]
Minor visual glitch when there is nothing to scroll:

![bg_pickup_scrollbars](https://user-images.githubusercontent.com/238558/66259745-35d8ac80-e7b5-11e9-99c9-527e9a87f1ef.jpg)

**Comment by lynxlynxlynx** [comment]
True story, working on gemrb scrollbars taught me a new English word: trough. Here both the trough and the knob are missing, though the latter may be a recent intentional change.

**Comment by bradallred** [comment]
it's probably that the buttons are annoyingly part of the background and scrollbars are only visible if there is something to scroll (issue #204)
