### ISSUE TITLE
[subviews] Issues with scroll items in the inventory of BG2

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#291]
There is something weird going on in Baldur's Gate 2:

One of my PCs has a wizard scroll in his inventory. Now, I try to pick it up, and some things are happening:

1. ~~It terribly lags over the flood of messages of (dozens, maybe hundred):~~ (seems fixed now)
```
[Actor/ERROR]: GetIWD2KitIndex: didn't find kit 16384 for any class, ignoring!
[Actor/DEBUG]: GetIWD2KitIndex: didn't find kit 16384 at expected class 1, recalculating!
```
@lynxlynxlynx Looks like you could maybe check that as well?

2. The cursor does NOT get the scroll attached. It works with other items, but not (that) scroll, the cursor remains the default one, so it looks as if it is gone.

**Comment by lynxlynxlynx** [comment]
Yeah 1. is my fault, though it'd be interesting to know what calls it that often. I guess item usability for highlighting acceptable slots? We don't really need to do that every tick. I'll check it out.

**Comment by MarcelHB** [comment]
No, I also had it in BG2, only.

**Comment by bradallred** [comment]
Is this related to #240? missing the cursor in the BAM, but also now missing whatever fallback (probably the item icon itself) master is using?

**Comment by lynxlynxlynx** [comment]
Do you see this with all scrolls? Either way one guaranteed problematic one would be handy.

**Comment by MarcelHB** [comment]
"All" scrolls is a bit much to test. I am going to sample some more.

**Comment by MarcelHB** [comment]
All scrolls: no. But I also do not spot any specific pattern at a first glance.

Good examples: SCRL91 (Knock), SCRL95 (Melf's Acid Arrow), SCRL1F (Flame arrow).
Bad examples: SCRL9Z (Freedom), SCRL9R (Time stop), SCRL6R (Spider Spawn), and many more.

**Comment by caillean7** [comment]
> Is this related to #240?

At least all Marcel's Bad examples do in fact miss the folded frame cycle, just checked.

**Comment by lynxlynxlynx** [comment]
But this is a wider issue, since you can also see it with many other items. Eg. a large shield is ok, but the blue quadratic potion of healing isn't.

**Comment by MarcelHB** [comment]
In IWD2, this seems to affect any item without exception.

**Comment by bradallred** [comment]
is this what everybody expects now?

**Comment by MarcelHB** [comment]
That looks good. :+1:
