### ISSUE TITLE
[subviews] Item pickup view of BG2 needs to be positioned

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#292]
I have 1024x786, and this is not the bottom, obviously.

![bg2_inventory](https://user-images.githubusercontent.com/238558/66259821-a59b6700-e7b6-11e9-9482-ac85845ba529.jpg)

**Comment by bradallred** [comment]
yeah, thats just its default position which is because normally the Message window is there.... Why isn't the message window there?

**Comment by MarcelHB** [comment]
:man_shrugging: Good question.

**Comment by lynxlynxlynx** [comment]
Normally neither the message nor the acttion window is displayed when the container one is open.

**Comment by lynxlynxlynx** [comment]
It works fine in 800x600. OpenContainerWindow has code to hide msgwin, but it apparently silently fails.
