### ISSUE TITLE
[subviews] PST "Back to game" button not disabled by default

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#294]
There is too much purple/blue in here, Ok on master:

![pst_back_button_tint](https://user-images.githubusercontent.com/238558/66259869-5bff4c00-e7b7-11e9-8d12-f9c9b25f025b.jpg)

**Comment by MarcelHB** [comment]
I was wrong, it's not a color thing but the button is supposed to be disabled by default - the purple tint means it's enabled. Unless you enter the inventory, spellbooks etc from which you can return to the game.

Even the manual is wrong here as it says "Click to Un-Pause" as it's function.

**Comment by lynxlynxlynx** [comment]
I did some work on this in master, but the enable/disable stuff will be easier done on subviews. The original regression is in 40c81c1203 and trivial to fix.

**Comment by bradallred** [comment]
this is pretty much identical to #267

**Comment by lynxlynxlynx** [comment]
Not really, pst needs this part of the action window enabled for the button to work.

Looking at it, I can't see a way to detect if a top window is open, since the objects persist. I can add a GetFlags function and wrappers that would suffice, but just wondering if you have any better ideas.

**Comment by bradallred** [comment]
a lazy way that would probably work great is to do something like this in the `UpdateActionsWindow` function:
 `Button.SetDisabled(not GemRB.GetView("GC").IsDisabled())`. I don't think there is a `IsDisabled()` but we should be able to get the flags and check it.

**Comment by bradallred** [comment]
i did realize we _do_ have a way to know if a relevant window is open

**Comment by lynxlynxlynx** [comment]
Had something similar in the works, but will just keep the stash in case it comes handy later.
