### ISSUE TITLE
[subviews] Hovering attitude/group icons in PC view not showing details

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#297]
When you hover some of the icons in the information window of a PC in PST, then, in the upper right area, details are shown - and disappear on leaving the item. At the moment, nothing is happening then, leaving you asking what these thingys actually are:

![pc_info](https://user-images.githubusercontent.com/238558/66260002-f01de300-e7b8-11e9-9247-5eae2a8d9dbf.jpg)

**Comment by bradallred** [comment]
I would expect you to get a python error for this. Sounds like a bad event binding.

**Comment by MarcelHB** [comment]
I will later look for them.

**Comment by MarcelHB** [comment]
Here it is:
```python
[Python/ERROR]: AttributeError: 'NoneType' object has no attribute 'GetControl'
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "E:\Devel\Sources\Cpp\gemrb_subviews\gemrb\GUIScripts\pst\GUIREC.py", line 280, in OnRecordsButtonLeave
[Python/ERROR]:     OnRecordsHelpStat (-1, 0, stats_overview)
[Python/ERROR]:   File "E:\Devel\Sources\Cpp\gemrb_subviews\gemrb\GUIScripts\pst\GUIREC.py", line 312, in OnRecordsHelpStat
[Python/ERROR]:     TextArea = RecordsWindow.GetControl (0)
```
With different values for `OnRecordsHelpStat` per control.

**Comment by lynxlynxlynx** [comment]
RecordsWindow is obviously not set there. If the file isn't using it as a global any more, its users need to look it up again.
