### ISSUE TITLE
[subviews] PC save portraits taken at wrong scale/position in IWD

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#298]
Here, you see what master/original do, and what subviews does.

![iwd_save_portraits](https://user-images.githubusercontent.com/238558/66260021-3ecb7d00-e7b9-11e9-9d52-700044d9a161.jpg)

**Comment by lynxlynxlynx** [comment]
Do you mean the other way around? Bottom looks correct.

**Comment by MarcelHB** [comment]
Yes, bottom is correct.

**Comment by MarcelHB** [comment]
Also noticed in BG2 right now.

**Comment by lynxlynxlynx** [comment]
Didn't see it in bg2, but I did have it in how.
