### ISSUE TITLE
[subviews] Right clicking inventory items in IWD2 sometimes fails

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#299]
Sometimes, I cannot right click on items in the inventory, getting a Python error:

```Python
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File ".\gemrb\GUIScripts\InventoryCommon.py", line 392, in OpenItemInfoWindow
[Python/ERROR]:     UpdateInventoryWindow ()
[Python/ERROR]: TypeError: UpdateInventoryWindow() takes exactly 1 argument (0 given)
```

**Comment by MarcelHB** [comment]
Looks related to #305

**Comment by lynxlynxlynx** [comment]
no parameters in master, but I think it takes a window here, so users "just" weren't all updated when the change in subviews was made.

**Comment by MarcelHB** [comment]
Yes, I just copied what the other games already do here.
