### ISSUE TITLE
[bug] Map note input of IWD2 is read only

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#300]
Can't get this "Note" text away, cannot enter anything.

![iwd2_notes](https://user-images.githubusercontent.com/238558/66260136-bc43bd00-e7ba-11e9-98a0-27b80c2ce39d.jpg)

**Comment by lynxlynxlynx** [comment]
It doesn't work in master here either. I don't have any original saves with custom map notes, but it also seems like we should add some padding to the input box. "Note" should be from that workaround for unmanageable characters.

**Comment by bradallred** [comment]
if we do want to fix it, subviews branch  is probably the best place since it has actual editable `TextAreas`.

**Comment by bradallred** [comment]
I can't reproduce this. fixed?

**Comment by bradallred** [comment]
@MarcelHB are you still having issues with this?

**Comment by MarcelHB** [comment]
It works - and probably did longer than I think, but here is probably the reason why I had the impression it doesn't:

![iwd_notes](https://user-images.githubusercontent.com/238558/69315588-2adbbd80-0c37-11ea-9c43-dc966ed56820.jpg)

If you click somewhere in this text box below this "Note"-line, nothing actually happens. If you click onto it, I can edit.
