### ISSUE TITLE
[subviews] Using some scrollbars in IWD2 hits FPS

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#301]
When using some scrollbars in IWD2, the game really slows down. I ends in a flood of messages like these:

```
[ResourceManager]: Searching for 'hmf6_l'...
[ResourceManager]: Found 'hmf6_l.bmp' in 'chitin.key'.
```
For example, the scrollbar in the inventory for items on the ground but also the one of the list of available spells in the spell books are affected, other ones look smooth.

**Comment by lynxlynxlynx** [comment]
I noticed a similar slowdown in master, but with bg2 and savegame scrolling. On a heavily modded install with many saves it can lag. Just noting so the two don't get conflated.

**Comment by MarcelHB** [comment]
I doubt there is a link, I tested your scenario and such type of message does not show up anywhere. So it's probably I/O vs. scrollbar implementation.

**Comment by bradallred** [comment]
is there text involved? if so its gonna have to wait for #233. How does it feel in SDL 1.2?

If its not text and is not slow in SDL1.2 then Its probably an issue with lots of little textures which we need to fix by atlasing BAMs. If it is slow in SDL 1.2 then we should look at if we are crossing between C++ and Python a bunch.

**Comment by MarcelHB** [comment]
I can't think of anything involving text here. From the log messages, it looks like the same texture is loaded over and over again.

Will test SDL 1.2 later today.

**Comment by bradallred** [comment]
probably just hammering something needlessly from the sound of it. SDL version shouldn't matter then.

**Comment by bradallred** [comment]
do you have a save to demonstrate this? I tried from a new game and I don't see a problem.

**Comment by MarcelHB** [comment]
I just started a new IWD2 game, and that's what my performance says:

![bad](https://user-images.githubusercontent.com/238558/66770397-d6b32000-eeb7-11e9-9efd-843bac005676.gif)

Together with a load of the messages above.

**Comment by MarcelHB** [comment]
@bradallred Can you confirm this?

**Comment by bradallred** [comment]
I haven't had a chance to look. All my recent activity here has been during breaks at work, no computer to actually test anything on.

Do you get the flood of messages on master too? Regardless of weather or not you do that still sounds like the best thing to address to improve performance. spamming stdout is _always_ going to be a huge performance sink. Even just making those messages silent (I think we have a parameter to silence resource lookups) would help a ton.

**Comment by lynxlynxlynx** [comment]
That would just hide the problem though; resources that need to be looked up that often anew (why?) should be cached instead.

**Comment by bradallred** [comment]
yes, I'm suggesting we find out why that resource is being spammed. I'm just speculating that the slowdown is due to flooding stdout even though it wasn't something I saw when I tried to look into this.

what is `hmf6_l.bmp` anyway?

**Comment by bradallred** [comment]
looking at the code the `ScrollBar.SetVarAssoc ("TopIndex", Count)` compared to BG2 `ScrollBar.SetVarAssoc ("TopIndex", Count, 0, Count)` looks suspicious

**Comment by lynxlynxlynx** [comment]
It's a pc portrait, nothing intrinsically related to scrollbars.

**Comment by MarcelHB** [comment]
Suppressing the stdout output makes the slowdown about half as bad.

Changing the mentioned `TopIndex` changes the behaviour that circumvents the issue a bit since there is only two valid scrollbar handle positions left then on the empty container - and thus I get the `hmf6_l.bmp` message only once per movement.

**Comment by MarcelHB** [comment]
Ok, and the mentioned bitmap is actually the PC portrait of the one that I have the inventory opened for.

**Comment by bradallred** [comment]
We should change the `TopIndex` initialization for all the games to be like BG2... master doesn't have "infinite" scrolling either I assume? even if it did I don't see why it would be preferable to continuously expanding scrolling achieved by adding that value clamp.

**Comment by lynxlynxlynx** [comment]
master clamps it too, so reinstating that is fine. It does not keep looking up the portrait though, unless you changed the verbosity parameter in subviews. It's clear where RefreshInventoryWindow uses the bmp.

**Comment by bradallred** [comment]
I wouldn't have changed it on purpose, but merge errors happen. I'll have to compare the 2.
