### ISSUE TITLE
[subviews] Some scrollbars need their positions fixed

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#302]
Never talked about scrollbars so much in one day, I guess.

The journal and the PC information view have scrollbars that are a few pixels off.

![iwd2_journal_scrollbar](https://user-images.githubusercontent.com/238558/66260194-a4b90400-e7bb-11e9-82e3-529089a7084a.jpg)

**Comment by bradallred** [comment]
issue #204  again

**Comment by lynxlynxlynx** [comment]
Why is this happening though? The scrollbar in 204 is actually there, is it just our insistence on constructing our own now?

It's also visible in main guirec and script selection.

**Comment by bradallred** [comment]
IWD2 embeds the scrollbar graphics in the window background image and the scrollbars are not the same height as the TextAreas they represent.

IWD2 also uses different margins than BG2 and currently the margins are currently hardcoded. Unhardcoding the margins and defining them somewhere on a per-game basis would get us most of the way there, but it also appears the Scrollbars and TextAreas are not always the same height. I can't tell from this sliver of screen why the TextArea is not the full height tho.

**Comment by lynxlynxlynx** [comment]
In NI/CHU all three (journal and the two in the guirec info window) scrollbars are full height (a few px taller than the TA). So huh.

I'll take that as a yes — that it work in master, because we don't touch the data.
