### ISSUE TITLE
[subviews] Placing items in the inventory makes them appear on cursor leave only

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#303]
Something I only noticed in IWD2.

1. Pick an item in the inventory.
2. Drop it into another slot - but don't move the mouse yet.
3. When you see it, start moving the cursor out of the slot.

The item only appears when the cursor has left the target slot, not in an instant.

**Comment by bradallred** [comment]
I either don't understand what you are saying or I cannot reproduce this.

**Comment by MarcelHB** [comment]
You're right, it's no longer there. I guess it got fixed by #310 .
