### ISSUE TITLE
[subviews] Voice selection menu in char gen misplaced

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#304]
In the PC generation of IWD2, I only noticed one obvious glitch: When you can pick from the list of voices, the whole list needs to be moved to the right and bottom a bit (tested on 1024x768).

![iwd2_new_game_voice](https://user-images.githubusercontent.com/238558/66260286-f1e9a580-e7bc-11e9-99d9-0b8ec0d8e7cf.jpg)

**Comment by bradallred** [comment]
this is the same issue as #204
