### ISSUE TITLE
[subviews] Some text inputs cut text off in last line a bit

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#306]
I only spotted this in IWD2, and only in subviews: For text inputs the last line loses the last one or two rows of pixels. See the save game name input, for example:

![iwd2_text_input](https://user-images.githubusercontent.com/238558/66260394-61ac6000-e7be-11e9-9086-81bfaa3e43c0.jpg)

Not sure if just some padding  settings here or an IWD2 wide thing.

**Comment by bradallred** [comment]
it's going to be the margins. I just guessed values using BG2. I don't know if we need different values for different games, but I've seen this there too, so likely its just me guessing poorly. 

the exception of course would be TextAreas from #204

**Comment by bradallred** [comment]
it looks like I just copied the same margins as the TextAreas, so maybe setting that to 0 in the TextEdit constructor would look right.

**Comment by bradallred** [comment]
this should be fixed now

**Comment by MarcelHB** [comment]
Looks good, thanks.
