### ISSUE TITLE
[bug] Portrait placeholder image in PST group organization

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#307]
**Describe the bug**
I see a placeholder image where there are supposed to be actual PC portraits.

GemRB version: HEAD.

**To Reproduce**
1. Start PST with a save game
2. Have or obtain another PC next to TNO
3. Go to "Reorganize group" (or whatever it is labelled in English) in a PC information sheet view
4. Inspect the group portraits of that view

**Expected behavior**
The actual PC portraits to be shown.

**Screenshots**
Ehm ... all PC slots look like that.

![pst_reorder_groups](https://user-images.githubusercontent.com/238558/66260433-dd0e1180-e7be-11e9-820f-9bfe015208ff.jpg)

**Comment by lynxlynxlynx** [comment]
OpenReformPartyWindow from pst/GUIWORLD.py is only partially implemented. The shared GUIWORLD.py has all the code and ideally we'd be able to merge the two, ifdefing as needed (GameCheck.IsPST()). 

Most of the current differences stem from the difference in windowing set up, which subviews work will remove, so it'll probably be easier (cleaner) then.

**Comment by chilvence** [comment]
I can handle the merging if you like, I've already got this functionally working on my test branch

**Comment by lynxlynxlynx** [comment]
Someone is already working on it, so better choose something else.

**Comment by chilvence** [comment]
No worries, didn't realise that
