### ISSUE TITLE
[bug] Headlines of journal items look bad in BG2

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#308]
**Describe the bug**
I don't like so much what I see there, I'm not even font-guy enough to state the typographic attribute that is wrong here.

**To Reproduce**
1. Start BG2.
2. Obtain an item for he journal
3. Open the journal

**Screenshots**
![bg2_journal_font](https://user-images.githubusercontent.com/238558/66260502-c4522b80-e7bf-11e9-992e-6020a5d4d7c7.jpg)
vs. original
![bg2_journal_font_original](https://user-images.githubusercontent.com/238558/66260530-1f841e00-e7c0-11e9-9634-1f8b17fb24c4.jpg)

You presumably notice ~a one-off error in the days~ calendaric interpreation issues here, too.

**Comment by lynxlynxlynx** [comment]
I always thought it's a blending issue. Most text colouring is done via tags, but here that doesn't cut it.

**Comment by bradallred** [comment]
does that look good to you guys? i don't know that the color is the closest match still, but the rough blending is fixed:

![image](https://user-images.githubusercontent.com/1126744/77451761-ba96a180-6dba-11ea-8f20-ab0591bbf30d.png)

unfortunately, the fix seems to only work on SDL2 on the subviews branch for whatever reason. I'm also unsure about the color, but somebody else can play with that.

**Comment by lynxlynxlynx** [comment]
Yep, we just need a darker or more saturated base color, which is set in the scripts.

**Comment by bradallred** [comment]
apparently our SDL 1 driver completely ignores the alpha setting on the palettes

**Comment by MarcelHB** [comment]
Looks way better already!

**Comment by lynxlynxlynx** [comment]
It's too light though and I have no clue how to make it darker. 000000 kinda works for black, but as soon as you add some color, it gets washed away and you can only make it lighter.

**Comment by bradallred** [comment]
probably need to do #233 first then coloring text is done with a simple tint rather than trying to build a complicated palette with an alpha channel.
