### ISSUE TITLE
[subviews] Issues with centering mode in PST

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#311]
I checked master - and it's not there. I observe two things in PST (fullscreen mod):

1. All my save games start in the centering mode, i.e. where you cannot move the viewport around. Pressing C fixes that, but that's probably not supposed to be the default - or is this again a setting I'm not aware of?
2. When I'm in centering mode, the cursor switches sprites twice per second or so: Between the one that is supposed to be there, and one of the cursors that appears when you move the mouse towards the window border, in order to move the viewport towards that direction.

**Comment by bradallred** [comment]
nothing changed intentionally so not a setting I'm aware of.

The cursor thing sounds like I expected `moveX` and `moveY` to only be set by being at the edge. See `GameControl::WillDraw()`.

**Comment by bradallred** [comment]
@MarcelHB should be fixed now. BTW there _is_ a setting for always center, it just wasn't properly initialized to 0.

**Comment by MarcelHB** [comment]
Thanks, I'll test it.
