### ISSUE TITLE
[bug] Map not switching if TNO resurrection at different place

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#315]
**Describe the bug**
I found a place where PST gets stuck on the death of TNO.

GemRB version: `HEAD`

**To Reproduce**
1. Go to AR1201 (Fortress)
2. Get killed there.

**Expected behavior**
The resurrection of TNO at AR1200, that's outside. Right now, there is no switch to the other map, you just can't do much any more and are stuck on AR1201. In the console, you can see some of loading actions for AR1200, though, so it's probably not much left to do here.

**Comment by lynxlynxlynx** [comment]
This has a very simple workaround — just reselect TNO. Looks like it was a problem since you're stripped of the party.

**Comment by MarcelHB** [comment]
Nice. :)
