### ISSUE TITLE
[bug] BG2: Circles drawn for Spirit Heads

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#319]
**Description**
In the initial ToB area, where the Spirit Heads recite the prophecy before the Illasera attack, on GemRB there are circles drawn for the invisible creatures (HEAD1 to HEAD5.cre, equipped with Rings of Invisibility) present during this dialogue.

![heads_gemrb](https://user-images.githubusercontent.com/54738589/66459186-d4466580-ea74-11e9-8751-b03123435311.jpg)

That's not the case on IE. Those creatures are using the DOOM_GUARD_LARGE animation, so it comes to mind to set the space to 0 in avatars.2da, however the same animation is used by the Amaunator statue (SHAAVA01.cre) in the Shadow Temple (AR1401), and that change would render the statue not valid for dialogue. Still, the original seems to do something different with that statue, as it looks on these screenshots:

Statue in IE:
![statue_ie](https://user-images.githubusercontent.com/54738589/66459565-94cc4900-ea75-11e9-8aa8-014bd52a339a.jpg)

Statue in GemRB:
![statue_gemrb](https://user-images.githubusercontent.com/54738589/66459625-b62d3500-ea75-11e9-9a6f-2ba6b00e1c33.jpg)

**GemRB version**
0.85-git

**Comment by lynxlynxlynx** [comment]
At minimum the circle size needs to be increased, but please check if they have any interesting effects on.

**Comment by caillean7** [comment]
None has any effects beside what their items give them. They have jewelery giving them immunity to all sorts of effects (to make them invincible basically, I assume). The HEAD creatures have Rings of Invisibility, like mentioned above, but curiously no Invisibility items on the statue's cre. Not sure why you can't see that one. Perhaps something hardcoded Bioware did.

**Comment by caillean7** [comment]
I checked what other creatures use this animation, so beside vanilla ones like the shadow altar there are also modded ones. So any changes will affect all of those, something to consider perhaps.

![screen](https://user-images.githubusercontent.com/54738589/66461910-48cfd300-ea7a-11e9-9186-8dd5059ea262.jpg)

**Comment by lynxlynxlynx** [comment]
if you remove the invisibility from the heads, does the circle appear?

**Comment by caillean7** [comment]
Removing the jewelery makes no difference, the circle's still there. But now I think they aren't completely invisible - didn't even notice before, but on the first screenshot, when you zoom in, you see that creature, transparent, but visible despite the rings. Or should I really have my eyes checked out?

**Comment by lynxlynxlynx** [comment]
But what about the original? See my previous question.

**Comment by caillean7** [comment]
Ah, good thinking. The original has indeed a circle too, if the rings are removed.

Size of 4 is perfect, exactly as the original. It's also conveniently moved somewhat, though not exactly to the orignial's position:
![statue_gemrb_s4](https://user-images.githubusercontent.com/54738589/66473999-b5ee6300-ea90-11e9-9a60-358960b4a2fa.jpg)
Still, looks good enough, imho.

**Comment by caillean7** [comment]
Could the invisibility effect be modified to show no circles for neutral creatures? It shouldn't do that enemies, anyway, so only for friendly invisibles?

**Comment by lynxlynxlynx** [comment]
First please try removing just invisibility, so we're sure it's to blame. This technically isn't about the effect code. We already don't draw the circle for invisible enemies and neutrals; what is the EA (enemy-ally) value of these things?

**Comment by caillean7** [comment]
Nah, that was to simple anyway. I checked the shadow altar on the original, which is hostile, and it has a circle. So this animation is somewhat special, it seems.

And yes, if I only remove the rings and leave them their 'cheater's dream' amulet, the circle is there. So it's the invisibility.

All the heads and also the Amaunator statue creature are neutral. In case this is relevant: The heads also have General: humanoid, race: human and class: innocent. The statue is general: monster, no_race, and class: cleric.

**Comment by caillean7** [comment]
No, it's the effect on the ring: 

>  Type: Remove feet circle (287)
Target: Self (1)
Power: 0
Unknown: 00 00 00 00 h
Unknown: 00 00 00 00 h
Timing mode: Instant/While equipped - 2

**Comment by lynxlynxlynx** [comment]
Ok, so it was just displayed due to the dialog then.

**Comment by caillean7** [comment]
Yes, they only get created by a cutscene script, and are present only during this dialogue.
