### ISSUE TITLE
[bug] BG2: AC bonus from single weapon style isn't displayed

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#325]
Split from #171 

**Description**
AC bonus from single weapon style isn't displayed in the record and inventory windows as it should be (number in 'shield' frame).

**Comment by lynxlynxlynx** [comment]
This is handled by a small function GetWeaponStyleBonuses in the main GUIREC.py. And works for me. @Tomsod  did you mean it's not accounted for in the main AC number?

**Comment by Tomsod** [comment]
Oh, yes, I did mean the main number.  The one that's displayed inside the shield thingy in both the stats and inventory windows.  In the original game it was appropriately decremented when the PC held a one-handed weapon.

**Comment by caillean7** [comment]
He's right, it works on IE, but not on GemRB.

**Comment by lynxlynxlynx** [comment]
It's just a display incoherence, the bonus is taken into account — just later, when needed.

It looks annoying though, so instead of ripping it out of Actor::GetDefense, I suggest we just add the -1/-2 when displaying, since it's just one stat check away.
