### ISSUE TITLE
[bug]  BG2: No XP bonus for PCs

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#329]
Split from #171

**Description**
Protagonist in BG is apparently supposed to get bonus +10% XP.

**Comment by caillean7** [comment]
Couldn't reproduce that. Killing some monster gave each character in the party the exact same amount of XP when I tried. There are some scripted XP gains where the PC gets more than the others during the main quest, but that's fixed.

**Comment by lynxlynxlynx** [comment]
I'm pretty sure it's true, but it may be limited to bg1. There was for sure discussion about it on the forum. I think the displayed xp amount didn't change, you just got more (look at the record screen).

**Comment by caillean7** [comment]
I noted the xp values for each party member before and after killing a monster, from the record page. There was no difference. At least in classic BG2 - don't have a BG1 install to test though.

**Comment by lynxlynxlynx** [comment]
Was it a bad enough monster for 10% of 1/6th not to be rounded away?

**Comment by caillean7** [comment]
Nah, just a goblin, but only the PC and Imoen were in the party (used the auto-save at game start, since I don't have any other saves, because not actually playing the game with wine). So if the goblin's worth 20 xp, the PC should get 11 points while Imoen gets only 10?

**Comment by lynxlynxlynx** [comment]
That's what I'd expect, yes. However the calculation could be nastier, so it'd really be better to try with something beefier (you can use cc(""crefile) in the console to summon).

**Comment by caillean7** [comment]
After killing a lich with 22,000 xp value both the PC (from 90,870 to 102,970 xp) and Imoen (from 96,870 to 108,970 xp) gained 12,100 xp. That means an xp bonus of 10 % for both...

**Comment by lynxlynxlynx** [comment]
TobEx:
> Gaining Experience
> 
> Option: Normally, Throne of Bhaal gives the party 110% of the experience actually coded into creatures and given by the AddExperienceParty() action opcode. However, the amount coded into creatures (100%) is reported in the dialogue bar. TobEx gives the option of fixing this issue and giving the party the coded amount of experience (100%) in these situations.

bg1 even wierder, investigation incomplete:
https://www.gibberlings3.net/forums/topic/25443-awarding-experience/

**Comment by caillean7** [comment]
Ah, BG1 is crazy - I wonder why they did come up with such a weird system (whatever the system may actually be) in the first place.

As for BG2, at least those lich killing test show no bonus for the PC, otherwise it makes sense. And the 110 % - if people care enough about that so that TobEx includes a tweak, perhaps GemRB could have one, too.

**Comment by lynxlynxlynx** [comment]
gemrb already does the sane thing, which is what tobex restored. This was likely a hidden player satisfaction feature, bolted on later. Like with platformers allowing you to still jump, even though you're already a step too far off the cliff.

But bg1 needs more research, since that potentially is also what iwd does.

**Comment by caillean7** [comment]
Well, from a player's perspective I'd say just take the xp value of the monster and divide through the number of party members - be it BG1 or 2 or even IWD1. That's not what the game's about. Heh, but perhaps one day someone will figure out the weird system, and you can implement it. But, thinking about what you said earlier about something else: "We don't have to imitate this madness" - or something like that.

**Comment by lynxlynxlynx** [comment]
In our case it's trivial to emulate this as a user — you just install the tweakpack and use a custom table for the wisdom xp mod (all values the same). So yeah, I agree about the silliness of the bg2 part and just closing ... but it'd be still cool to know how bg1 worked, since it appears wild.

**Comment by lynxlynxlynx** [comment]
I've added a subcomponent to gemrb-tweaks to deal with this, so anyone that insists, can replicate the behaviour without us having to pollute the engine.
