### ISSUE TITLE
[bug] BG2: Crash related to multiple random encounters

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#330]
Split from #171

**Description**
Two random encounters in a row (on the same map?) can mess up your location on the world map, leading to a crash [should be impossible to get there twice].

**Comment by lynxlynxlynx** [comment]
Like I said, we should never enter the same one twice, so when it happens, a save file is needed (before the ambush).

**Comment by lynxlynxlynx** [comment]
I got three ambushes in a row in bg1, all different areas, so I'm closing this. We can reopen if someone manages to reproduce.
