### ISSUE TITLE
[bug] BG2: Glitch with tooltips due to right click

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#334]
Split from #171 

**Description**

>     cursor can get stuck, disabling tooltips

I think this is about the little hovertext scrolls ceasing to work after pressing the right mouse button. The currently displayed scroll, if any, will be stuck, and others won't be displayed, until you press the left button.

**Comment by lynxlynxlynx** [comment]
This can be reproduced by right-clicking and holding on the Journal button. Once the tooltip appears, you can release and move around. It will not expire.

It does not happen on subviews any more though, so closing.
