### ISSUE TITLE
[bug] AOE spells can affect disabled enemies on random encounter maps

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#335]
Split from #171

**Description**
Some encounter maps have different enemies set to show up at different times of day, so most of the map's creatures will be toggled off and invisible at any given time. But using an AOE spell (like a fireball) will still affect them.

**Comment by lynxlynxlynx** [comment]
Unscheduled actors are immortal, so I don't believe this is possible. @Tomsod do you have an area reference handy? Otherwise I'll just close it and we can deal with it if it resurfaces.

**Comment by Tomsod** [comment]
I just traveled a bit and got some encounter with inactive bears and gnolls.  A wand of fireball managed to kill all the gnolls and wound the bears; the gnolls dropped the random treasure, but no halberds and no corpses.  The bears also remained inactive.  I did get the XP.
Unfortunately, it's a bit difficult for me to give the area name, as I only have the Trilogy mod for BG2 and have only played through the BG1 part.  The mod shuffles the names for some BG1 area files, you see.  For me the area is AR4801, FWIW.  It can be encountered by going west from Nashkel, you can look it up on the world map file, there's only one west link from Nashkel and only one encounter on it.

**Comment by caillean7** [comment]
Can confirm - tried on my BGT installation in AR4801, all sorts of inactive monsters can be killed with AoE spells.

**Comment by lynxlynxlynx** [comment]
Ok, so by what mechanism are they inactive? Are they unscheduled, only appearing at a certain time or is there some broken scripted difficulty scaling involved?

**Comment by Tomsod** [comment]
Yes, they only appear at a certain time.  The game basically packs several encounters in the same map this way.

**Comment by caillean7** [comment]
It's set in the area file, has nothing to do with scripting.

**Comment by lynxlynxlynx** [comment]
Should be done now, please recheck and reopen if not.

**Comment by caillean7** [comment]
Partly fixed, it seems - I can hear them still, though - some grunting when I shoot a fireball at their approximated position. Can you mute them, too?

**Comment by lynxlynxlynx** [comment]
I wonder which sound that is. Does this mute it?
```diff
--- a/gemrb/core/Scriptable/Actor.cpp
+++ b/gemrb/core/Scriptable/Actor.cpp
@@ -4558,7 +4558,7 @@ void Actor::CheckCleave()
 int Actor::Damage(int damage, int damagetype, Scriptable *hitter, int modtype, int critical, int saveflags)
 {
        //won't get any more hurt
-       if (InternalFlags & IF_REALLYDIED) {
+       if (InternalFlags & IF_REALLYDIED || !ValidTarget(GA_NO_UNSCHEDULED)) {
                return 0;
        }
        // hidden creatures are immune too, iwd2 Targos palisade attack relies on it (12cspn1a.bcs)
```

**Comment by caillean7** [comment]
Argh, it's the wand making that sound, I'm so sorry - did Wands of Fire always make gruntlike sounds?!
