### ISSUE TITLE
[bug] BG2: Hour-based NPC presence and spawn points trigger one hour early 

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#336]
Split from #171 

**Description**
Looking at the code, it's a simple error within the SCHEDULE_MASK macro:

 https://github.com/gemrb/gemrb/blob/9466e449e9e2e80ace0c8891d3d481dddfc71891/gemrb/includes/globals.h#L206

It should be - hour_size/2, not +. As it is, e.g. 0:30-1:29 gets converted to 1:00-1:59 and thus bit 1, not bit 0 as it should be.

**Comment by caillean7** [comment]
lynxlynxlynx commented:
> Are you sure about SCHEDULE_MASK? IESDP:
> 
>     
> 
> > 0x401E Time(I:Time*Time)
> >     Returns true only if the period of day matches the period in the 2nd parameter (taken from Time.ids). Hours are offset by 30 minutes, e.g. Time(1) is true between 00:30 and 01:29.
> >

**Comment by caillean7** [comment]
Tomsod commented:

> Yes, as it currently implemented, the Time() trigger actually relies on the wrong behavior. But both it and Actor::Schedule() call GemRB::Schedule(), which explicitly notes:
> https://github.com/gemrb/gemrb/blob/8110286ee262b94171e7e3f507cb8b9b74aa7eb1/gemrb/core/Core.cpp#L224-L226
> Also, from the ARE file format description on IESDP, which is directly relevant to this bug:
> 
> > Actor appearence schedule. Bits 0-23 each represent an hour of game time. Setting a bit means the actor will appear in the area for the corresponding hour.
> > Hours are offset by 30 minutes as follows:
> > bit 23 = 23:30 to 00:29
> > bit 22 = 22:30 to 23:29
> > (...)
> > bit 0 = 00:30 to 01:29
> 
> So I suppose Time() will need to be tweaked as well. Good find!
>

**Comment by lynxlynxlynx** [comment]
Yeah, found the original research:
https://www.gibberlings3.net/forums/topic/6674-time-triggers/?do=findComment&comment=60616

So after that commit scheduling in general should be fine, iesdp is still correct in both places, but our Time trigger is off by 1. and TimeLT looks wrong as well. Does this look correct to you:

```diff
--- a/gemrb/core/GameScript/Triggers.cpp
+++ b/gemrb/core/GameScript/Triggers.cpp
@@ -3219,7 +3219,8 @@ int GameScript::AnimState(Scriptable* Sender, Trigger* parameters)
 //this trigger uses hours
 int GameScript::Time(Scriptable* /*Sender*/, Trigger* parameters)
 {
-       return Schedule(1 << parameters->int0Parameter, core->GetGame()->GameTime);
+       if (!parameters->int0Parameter) parameters->int0Parameter = 24;
+       return Schedule(1 << (parameters->int0Parameter - 1), core->GetGame()->GameTime);
 }
 
 //this trigger uses hours
@@ -3231,7 +3232,11 @@ int GameScript::TimeGT(Scriptable* /*Sender*/, Trigger* parameters)
 //this trigger uses hours
 int GameScript::TimeLT(Scriptable* /*Sender*/, Trigger* parameters)
 {
-       return Schedule(0xFFFFFFu >> (24 - parameters->int0Parameter - 1), core->GetGame()->GameTime);
+       if (parameters->int0Parameter == 1) {
+               return Schedule(1<<23, core->GetGame()->GameTime);
+       } else {
+               return Schedule(0xFFFFFFu >> (25 - parameters->int0Parameter), core->GetGame()->GameTime);
+       }
 }
 
 int GameScript::HotKey(Scriptable* Sender, Trigger* parameters)
```

**Comment by Tomsod** [comment]
`Time()` looks right, but `TimeLT()` should also check against bit 23 for any `int0Parameter >= 1`.  Like this:
```
if (parameters->int0Parameter <= 0) {
    return 0;
} else {
    return Schedule((0xFFFFFFu >> (25 - parameters->int0Parameter)) | 1 << 23, core->GetGame()->GameTime);
}
```
Or even:
```
if (SCHEDULE_MASK(core->GetGame()->GameTime) == 1 << 23)
    return parameters->int0Parameter >= 1;
} else {
    return Schedule(0xFFFFFFu >> (25 - parameters->int0Parameter), core->GetGame()->GameTime);
}
```
`TimeGT()` also needs fixing: currently `TimeGT(0)` will check against mask `0xFFFFFE`, so bit 23 will pass but not bit 0, while according to your link it should be the other way around.  So, something like:
```
return Schedule((0x7FFFFFu << parameters->int0Parameter) & 0x7FFFFFu, core->GetGame()->GameTime);
```
Also, checking `int0Parameter` for being inside [0;23] would be nice for all three.  Putting unsanitized numbers on the right side of a shift operator may lead to nasal demons, after all!

**Comment by caillean7** [comment]
> So after that commit scheduling in general should be fine

Yes, I could see that while testing for #335 - there was a bear present 1 hour early yesterday, with today's version it shows up as scheduled.

**Comment by lynxlynxlynx** [comment]
Thanks for the review! I tested it and you're correct, TimeLT(1) is true for 23:30+. Committed the fixes.

Looking at vanilla scripts and dialogs, there are a few interesting cases (and no uses of MIDNIGHT == 0):

```
scripts/bg2/vampsttp.baf:14:    TimeGT(24)
scripts/bg2/vampsttp.baf:39:    TimeGT(24)
scripts/bg2/vampsttp.baf:66:    TimeGT(24)
scripts/bg2/vampsttp.baf:88:    TimeGT(24)
scripts/bg2/vampsttp.baf:113:    TimeGT(24)
dlg/bg2/haerdax.d:152:          TimeGT(23)
```
Luckily all those gt24s are in an OR block with TimeLT(DAWN_START), so it worked in the original regardless if that's a valid call or not. The dialog one is also never true due to surrounding triggers, so it also doesn't matter if it's valid or not.
