### ISSUE TITLE
[bug] BG2: Sound and animation for effects wearing off from corpses

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#337]
Split from #171 

**Description**
For instance, Slow plays a sound effect when it runs out. If you slow some monsters and them kill them, the sound will still play when the spell wears off from the monsters' corpses. Not sure if that's not present in original, but it's certainly weird.

**Comment by lynxlynxlynx** [comment]
So yeah, what happened in the original?

**Comment by caillean7** [comment]
Some experiments with goblins showed that Tomsod's right. First, the corpses do play the sound. Second, I tried a couple of times on the original, couldn't hear it there.

**Comment by lynxlynxlynx** [comment]
Which effects are involved?

**Comment by caillean7** [comment]
That's likely the responsible one:

![screen](https://user-images.githubusercontent.com/54738589/66678748-e12da980-ec6c-11e9-9035-991c2c25dde0.jpg)

**Comment by Tomsod** [comment]
`Play visual effect (215)` also may be relevant -- I must have meant it as well when first writing this bug down, although I can't find which spell has delayed visual effects now.

**Comment by caillean7** [comment]
I can't find that one on Slow - only Lighting effects (141), but this one has a timing mode Instant/Permanent until death. Also, looking out for any visual effects, I couldn't find any, just the sound was played.

**Comment by lynxlynxlynx** [comment]
Play visual effect is already handled, but I added it to Play sound. @caillean7 are you saying 141 should be killed too?

**Comment by caillean7** [comment]
No, that one's fine.

**Comment by lynxlynxlynx** [comment]
Should be fixed.

**Comment by caillean7** [comment]
Yes, it's fine now.

**Comment by lynxlynxlynx** [comment]
oops, that should've been a reference to #377, for anyone looking in the long future.
