### ISSUE TITLE
[bug] BG2: Records page cannot handle missile/melee weapon dual-wield

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#339]
Split from #171 

**Description**
Specifically, game hangs after putting a sling in the left hand and going to the stats page. I don't think you're supposed to be able to do that at all? I also once managed to trigger the same error with a sling in the right hand and a mace in the left, but I wasn't able to reproduce it later.

**Comment by lynxlynxlynx** [comment]
Easy to reproduce and the python traceback leads you to the code (eventually likely Actor::GetCombatDetails). Did the original even allow slings in the left hand though? I'm pretty sure it did darts, but those don't have ammo.

**Comment by caillean7** [comment]
> Did the original even allow slings in the left hand though?

Nope, no ranged weapon in the left hand allowed.

**Comment by lynxlynxlynx** [comment]
How about one of those hammers or daggers with an optional ranged mode?

**Comment by caillean7** [comment]
It always results in a message: Can not equip a ranged weapon in your off hand.

**Comment by lynxlynxlynx** [comment]
Even if they have the melee ability selected?

**Comment by caillean7** [comment]
Yes. They seem to reset to ranged if you take them out of the weapons slot.

**Comment by lynxlynxlynx** [comment]
Ok, so we should just prohibit it when testing for slot usability. Might even just be a data bug in gemrb/unhardcoded/bg2/slottype.2da (the 260 in BITS), but it takes some effort to come up with the number.
