### ISSUE TITLE
[bug] Bad non-ASCII character handling in creature names

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#340]
Split from #171 

**Description**
I play BG in Russian, so there's a lot of weiяd characters. I think they weren't displayed correctly in the console debug messages, so instead of PC names there were empty strings and I had to guess which is which when reading dumps.

**Comment by caillean7** [comment]
Something I noticed recently was that I couldn't use umlauts in the name for my PC when creating the character. When typing a name containing umlauts, I can't confirm the name. Not sure if this is due to the English version of the game, but it would be nice if you could use umlauts, anyway.

**Comment by lynxlynxlynx** [comment]
This is a wider issue. #47 tackled part of it, but both our current and subviews code has plenty of todos for full i18n support.

I doubt the English versions allowed umlauts though.

**Comment by caillean7** [comment]
Probably not. They have the US keyboard layout on the original though, so I couldn't test that.

**Comment by MarcelHB** [comment]
In PST, I frequently hear beeps on Windows, mostly after loading. Why that: Some bytes of the names are apparently in an encoding that mismatches what the Windows command line expects, thus printing BEL (0x7) to the console and making a sound.

**Comment by caillean7** [comment]
@MarcelHB : Out of interest - I gather from your screenshots you're playing in German - could you use umlauts in character names, if you wanted?

**Comment by MarcelHB** [comment]
It mostly works, yet there are incompatibilities between savegames when it comes to umlauts, and the inputs always appends garbage when typing such glyphs, i.e. I press `ü` and get `ü\xC3\xBC` - but I can delete the garbage and everything is good again.

**Comment by caillean7** [comment]
Ah, so you can use them at least, if you don't care about save game compatibility. Again, would be cool if you could regardless of the language you play in. There are languages containing umlauts, like Finnish, and there's no game version available, so folks play in English, and it's nice if you can at least name your character however you want.

**Comment by MarcelHB** [comment]
It's a not so trivial thing here, as in theory, these things must be considered:

1. The game has assets packed in some encoding, i.e. ISO-8859-1 afaik for German.
2. The operating system has some quirks to respect - and we're multiplatform here - for example file names. Windows has UTF-16 over WinAPI, Linux uses byte streams.
3. The user provides input in whatever encoding, like PC names, save game names, map notes.
4. The save games contain data of 1. and 3.  and let's say, you now open them on another native game or GemRB platform.

**Comment by caillean7** [comment]
Doesn't sound as if Paivi can be Päivi anytime soon - ah well, can't have everything.

**Comment by lynxlynxlynx** [comment]
iwd2 definitely had some support for non-ascii, as there are handy ini settings available:
```
Font Name=
Double Byte Character Support=0
```

**Comment by lynxlynxlynx** [comment]
So, where are we at now? I see the namesake bug is still present:
- char name text input doesn't handle non-ascii (can crash, usually just doesn't print anything)

I think map notes were fixed already. Anything else? If so, it deserves it's own report.

**Comment by Tomsod** [comment]
Personally I'm playing in English this time, so can't really help anymore.
