### ISSUE TITLE
[bug] AoE projectiles targeted at actors through sequencers should ignore magic resistance

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#343]
Split from #171

**Description**

> (worksforme) mag res can block minor sequencer itself from executing (not its stored spells) [tried with a 100% resistant caster]

Just tried casting a sequencer with Horror and Web on Viconia. Normally casting those AOE spells on her would mostly succeed, Viconia's MR only preventing them from acting on herself, but in the case of sequencer she's able to nullify them completely, so there's no web animation, for instance.

>  A location/point-targeted spell (ability target 4) cannot be cast on a creature through the UI* - even if you click on the sprite, it's still targeting their location, not the creature.
> 
> \* *They can target a creature while in a contingency or sequencer, though the sequencer must also contain a creature-targeted spell.*

**Comment by lynxlynxlynx** [comment]
This needs testing in the original, because I'm pretty sure targetting a person, not the ground can eat up aoe spells too. So just cheat someone to 100% magic resistance and try.

**Comment by caillean7** [comment]
I tested it, both on the original and GemRB. As Tomsod described, no web animation on GemRB, while on IE it is visible. Also, the other party members had to make a save on the original, while on GemRB not. At least that's what I gathered from the message window.

**Comment by lynxlynxlynx** [comment]
Was that web alone or through a sequencer/trigger?

**Comment by caillean7** [comment]
Like Tomsod described, a Minor Sequencer with Web and Horror. If I cast Web directly, the party members get webbed except for the one with 100 % MR.
