### ISSUE TITLE
[bug] iwd2 regression: goblins flee

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#344]
Goblins in Targos attack you, but the next round they try to escape the area and only then return back to harass you properly.

This didn't use to happen, so something got broken and it might be easiest to just bisect it.

**Comment by MarcelHB** [comment]
The ones you encounter in one of the houses nearby don't show that behaviour, right?

**Comment by lynxlynxlynx** [comment]
if you mean ar1005, then yes, I don't see that problem there. They have partly different scripts assigned.
Good don't have: 10gobf0 (shouting), 00t03m (team 3 version of below), 00amvw05 (suspicious block)
Bad don't have: 00t01m (movetoobject if they can't see a pc)

```
IF
  !Global("RW_00AMVW050","LOCALS",0)
  Range([PC],40,LESS_THAN)
THEN
  RESPONSE #100
    MoveToPoint([-2.-2])
END
```
In Targos the one exit just happens to be in that corner, so I'm betting these coordinates are special and now mishandled.

**Comment by lynxlynxlynx** [comment]
It might be the iwd2 version of MoveToSavedLocation, though this having worked before also means it was never executed before. And it does have ReturnToSavedLocation. The only susceptible trigger is NearSavedLocation, but that didn't change either. 

So two things remain to do:
- figure out when it broke (= what was hiding this missing feature)
- figure out what to do with -2,-2, which should just match our guess in NearLocation (added for the same reason)

**Comment by caillean7** [comment]
So boys, is any of you already busy bisecting this? Else, I'd volunteer to dig after the old IWD2 CDs and give it a go.

**Comment by MarcelHB** [comment]
When working, I'm currently at the subviews stuff. I'd say feel free.

**Comment by caillean7** [comment]
Any hints or suspicions where to start? And, if you guys have a savegame handy or some easy way to reproduce (not so familiar with IWD2 here)?

**Comment by MarcelHB** [comment]
You don't need a savegame, it's starting a fresh game in IWD2 and going straight from the peer towards the western map border, the goblin close to the stairs is already a valid subject.

Not sure where to start bisecting in the commit history, though.

**Comment by caillean7** [comment]
Ah, okay, thanks. I'll work my way backwards month-wise, then.

**Comment by lynxlynxlynx** [comment]
Yes, feel free. I'm pretty sure it worked in 0.8.5, so you can try that binary first (if it works, releases are [tagged](https://github.com/gemrb/gemrb/releases)). In the meanwhile I'm  reverse engineering what -2,-2 should do as coordinates.

**Comment by caillean7** [comment]
0.8.4 is the last release where it's working, at this point - https://github.com/gemrb/gemrb/commit/eefb3c44423c8a967cef153124f8a164cc000aed - the problem is already present. I'm using GCC 6.3.0, and can't compile the code between 0.8.4 and that commit. It gives me an error while compiling the ACMReader plugin. I'm afraid my geek-level is not sufficient to work around that. Any advice?

**Comment by lynxlynxlynx** [comment]
even if you rerun cmake with -DDISABLE_WERROR=1?

**Comment by caillean7** [comment]
Ahem - I kinda passed that to make... yeah yeah, just laugh... But it works now :laughing:

**Comment by caillean7** [comment]
Found it - goblin weirdo behavior started with https://github.com/gemrb/gemrb/commit/ffeca9ed660bb84473c63f3e842b5e95367fea38 almost immediately after the release of 0.8.4.

**Comment by lynxlynxlynx** [comment]
Most of this bug is fixed, but I'm weary of blindly reinstating that game flag and behaviour without better understanding first.

devSin had this to say in 2010:
> _So IWD2 really is the only one with the stupid Or() logic._ They also have the instants hack so that Continue() is actually useful (HoW uses BG2 Continue(), and all the scripts where they tried to use it are junk; some of them were ass-hard to fix because of the way they're written).

And more concretely:
https://www.gibberlings3.net/forums/topic/20012-short-circuiting-or-trigger/?do=findComment&comment=168225
