### ISSUE TITLE
set up weekly coverity runs

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#345]
I've reran it. It doesn't support separate branches and they have low rate limits (used to be 1 per day), so they suggest a separate branch you merge whatever you want into when needed and then travis runs the check on its own.

_Originally posted by @lynxlynxlynx in https://github.com/gemrb/gemrb/issues/201#issuecomment-530372539_

We can copy what we did in ja2s, since we also have access to github actions:
https://github.com/ja2-stracciatella/ja2-stracciatella/pull/877/files

**Comment by lynxlynxlynx** [comment]
The docs say we need to end up here, but it's not exposed in the menu:
https://scan.coverity.com/projects/gemrb/builds/new?tab=travis_ci

No idea why it thinks we're not using travis yet, since when I compare with ja2s, all looks the same.

We can just use github actions instead:
https://github.com/ruby/actions-coverity-scan/blob/master/.github/workflows/coverity-scan.yml

**Comment by lynxlynxlynx** [comment]
It's done, we'll get weekly checks of subviews and any reports will be sent to gemrb-commits.

**Comment by burner1024** [comment]
This tries to run and fails in forks, see [here](https://github.com/BGforgeNet/gemrb/actions/runs/3817451010/jobs/6493719128).
Maybe make runs conditional on `COVERITY_SCAN_TOKEN` being  non-empty?

**Comment by lynxlynxlynx** [comment]
The first should definitely work, while for the second I'm not sure, since there's not mention on how to check for empty strings:
```
if: github.repository == 'gemrb/gemrb'
if: $env.COVERITY_SCAN_TOKEN
```
You can add it to the job ("latest") and report back in a week.

**Comment by burner1024** [comment]
`if: github.repository` thing works.
