### ISSUE TITLE
[bug] HoW can get stuck if you have low charisma

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#346]
This is an old breaking bug that was not there on a retest, but now it's clear why.
Once you're expelled from the barbarian camp (ar9200), your test of Tempos will begin. If you can talk yourself out of it, all is fine. The gates remain closed and Angaar stays in front. So once you return, you can talk to him and proceed as planned.

If you however don't have enough charisma (14), a fight test is in order. Angaar summons the partygoers and then also does this (bcclgate.bcs):
```
		MoveToPoint([789.584])
		Face(NW)
		MoveViewPoint([568.358],VERY_FAST)
		Wait(2)
		PlaySound("am9200e")
		CloseDoor("AR9200_GATE1")
		Wait(1)
		SetStartPos([0.0])
		SetSavedLocation()
```
So he moves behind the gates, closes them and sets his new location to that spot. When you come back later, he'll be there and you can't talk through the gates, getting stuck. It only has the non-interactive flag set, so you can't open/close it yourself / it doesn't toggle as time passes. ~I'm pretty sure iwd2 relies on talking through doors in the goblin dens, so maybe there's some shared functionality, but also, I believe that one door has extra flag bits set, so the comparison may be a red herring.~

We already allow seeing through them, but something blocks the dialog. Likely it's just a matter of dialog range, but let's see what the original does first.

To reproduce, you can just go there and ExecuteString('StartCutScene("bcclgate")').

Here's a video:
https://youtu.be/Eb7_yrWYDUI?t=4465
(starts in battle in https://www.youtube.com/watch?v=JB32jgRUMvI)

So clearly he is later repositioned and we *just* need to find where and why we don't do it.

**Comment by lynxlynxlynx** [comment]
Phew, Angaar shows up in many scripts and it's just one area! DID_GATE_CUTSCENE controls whether you're talking to him for the first time or on the return.

He should be around [650.407], so it must be one of these scripts:
> scripts/how/bcgotowy.baf:    JumpToPoint([649.410])
> scripts/how/bcogatec.baf:    MoveToPoint([649.410])
> scripts/how/bcogatej.baf:    JumpToPoint([649.410])
> scripts/how/bcptyent.baf:    MoveToPoint([649.410])
> scripts/how/bcptyent.baf:    MoveToPoint([649.410])

**Comment by lynxlynxlynx** [comment]
RECHECK: older testing showed it worked if fog of war is disabled, so it might be more of a metascripting bug.

**Comment by caillean7** [comment]
After brooding over this mess of scripts a bit, I guess what happens is this:

- in BCENTBTL.bcs the fight / Tempos test is set up, and the global BC_CUTSCENE is set to 14.
- if you killed the warriors, in BCGUARD.bcs BC_CUTSCENE is set to 10
- after that, you return to Lonelywood, whose area script AR9100.bcs sets BC_CUTSCENE to 15
- when returning to the barbarian camp and BC_CUTSCENE is 15, its' area script AR9200.bcs calls
BCOGATEJ.bcs, which moves Angaar back to his post at those coordinates. I added a debug message (actually a PlaySound) to this script to test that, and I'm pretty sure this is our problem script.

**Comment by caillean7** [comment]
Huh, I just tried that on GemRB, and it worked? Angaar was where he's supposed to be after returning to the camp.

**Comment by lynxlynxlynx** [comment]
Did we accidentally fix this in the meanwhile? :) In your GemRB test, did you go from the start, eg. the first barbie camp entrance? Otherwise some things may have been saved already.

**Comment by caillean7** [comment]
Yes, I had a save made at the entry point of that area, before talking to any of the barbarians. And as far as I could see there's no talking through doors involved - though I can't remember exactly from my last playthrough of HoW.

**Comment by caillean7** [comment]
I checked in those videos you linked, so even if you return after this glacier / seer thing, Angaar is supposed to be in front of the gate, so it seems to me like this works as it's supposed to, no talking through the gate involved at any point.

As a side note, I noticed some other things, like the walking speed of the actors in cutscenes (too fast), also Angaar should not be visible behind the gate after you defeated the warriors (could be HideCreature). Are you aware of these things or do you want me to go over it and open up new issues?

**Comment by lynxlynxlynx** [comment]
Speed is already reported and there's nothing related to cutscenes about it. The other one sounds interesting, so yeah, go ahead. Is it just him or is the whole palisade supposed to be in fog? Etc.

**Comment by lynxlynxlynx** [comment]
I jumped through a clean game now and yes, apparently something in between fixed this. Perfect. :)
