### ISSUE TITLE
20 year anniversary

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#352]
The project registered on SourceForge on 2000-08-21 (before bg2 was even released), to get file hosting and CVS version control. The internal mailing list shows some of the earliest discussions on the best way to start etc., but we don't really know when the first code was written or what could be considered the real project start. So the SF date is our best bet and isn't off by much.

What should we do to commemorate? Another release or a new website (#116) are quite easy, but this is a good opportunity for some intro- and retrospection, plus wider news coverage. We could interview some of the pioneers, compare some code (earliest changes tracked in the repo are from the 2003 SVN migration), maybe have less of a skeleton demo, ???, maybe show some broken [screenshots](https://lynxlynx.info/bugs/mushroom.madness.jpg) ...

Thoughts, ideas? Curated list:
- [x] anniversary release
- [x] new website [SHINY](https://gemrb.github.io)
- [x] interviews
- [x] simplify install experience (mostly done, but will be even simpler with the next release)
- ~create universal launcher~ #231 
- ~get a famours LP-er to do a Let's Play on GemRB~
- ~edheldil: enhance the game demo to release quality and have it reenact eventual interviews with us devs :)~ #313

Annoucement and release annoucement are being written here: https://github.com/gemrb/gemrb.github.io/blob/master/_drafts/20_announcement.md
_PR: a one pager combining screenshots, anniversary announcement, some citations from the interviews, and perhaps the changelog, (new website since the last release), (suggest subscribing to gemrb-release?), CTA (looking for contributors, especially gfx/sdl wizards)_
My comms colleague suggested we only tease the interviews and then publish them after the release. So let's do a whole celebratory week, in a similar way G3 did on their anniversary:
- day 1: release
- day 2: balrog interview
- day 3: edheldil interview
- day 4: what's next — brad & subviews
- day 5: avenger interview
- day 6: lynx interview
- day 7: -
- [x] Announce on
  - [x] homepage: news, index
  - Gibberlings3 forums
    - [x] GemRB forum
    - [x] modding news (a template is available in `admin/announcement.template`)
  - [x] #GemRB in channel and title; Discord channel will get it automatically
- [x] send announcement around; list of publishers from our previous mentions:
  - [x] email:
    - gemrb-release@lists.sourceforge.net 
    - contact@gamingonlinux.com
    - https://gameranx.com/ atul@gameranx.com
  - [x] web:
    - ~https://www.rpgwatch.com/submitnews.html~ broken captcha
    - https://sorcerers.net/community/index.php?misc/contact for the "Infinity Engine Modding News" section
    - https://rpgcodex.net/contact.php
    - https://phoronix.com - https://www.phoronix-media.com/?k=contact top right link
  - r/gamedev, r/baldursgate/ https://www.reddit.com/r/baldursgate/submit link; https://www.reddit.com/r/gamedev/submit gfx CTA
  - https://www.gamebanshee.com - tweet it at them \@gamebanshee
  - slogamedev FB
  - ~https://core-rpg.net/~ no obvious way to contact
  - ~https://polter.pl/~ no obvious way to contact, Polish submission form
  - ~start updating moddb as well? Do we have access?~ Nope and not really worth it
  - ~https://www.pcworld.com~ not so relevant for their audience, now that ees are around
  - ~http://www.tuxmachines.org~ broken login
- later:
  - [x] SourceForge project page news section
  - [ ] http://lxer.com/story_howto.php - relink
  - [x] https://news.ycombinator.com - relink?
  - [x] LWN, worth a shot - send after the interviews are live
  - [x] notify SF HQ, Balrog's interview is full of praise
  - [x] add interview links to the History.md page
  - [x] reinstate en.wikipedia page after gathering the noise: https://github.com/gemrb/gemrb/wiki/Media-clipping

**Comment by bradallred** [comment]
Things like this make me wonder about @fuzzie and the others. Do you talk to any of them still?

I think most commemorative things would be greatly facilitated by having a newer website. You would need somewhere to host interviews/retrospectives/whatever.

**Comment by lynxlynxlynx** [comment]
Rarely, but nobody I know was around when the project started. Avenger, wjp and edheldil all started just a bit later, while everyone else you can think of did much later.

The content could be on the forum, but that's a missed opportunity. If we don't find a webdev volunteer, I'll just build the site myself, tweaking some existing jekyll template. It's not a lot of work, but it seems silly atm.

**Comment by bradallred** [comment]
I may regret mentioning this but I was once a webdev (mind you not a designer). It's been some years, but I can probably be helpful still.

But yeah if G3 still gets enough traffic to make it worthwhile go ahead and use that.

**Comment by MarcelHB** [comment]
I am curious about the history, like initial motivation, milestones, reverse engineering efforts, help from IE devs (if any?), organization. So I think a one pager combining screenshots, some citations or two and a story would be a nice thing without trying to squeeze out a whole new project (unless really votes for doing that).

**Comment by caillean7** [comment]
> Another release

Not sure about your roadmap concerning EE compatibility, but folks love their EEs nowadays, so wouldn't a new release supporting EE installations be sweet for the 20th anniversary?

**Comment by lynxlynxlynx** [comment]
Nah, EEs still function, so there is little benefit in working on something so ambitious in such a short time. I don't know how long we'll need to finish subviews off, but either way, I expect the anniversary release to be of the organic sort, an accruement of random bugfixes and improvements. Things like #231 are much more realistic.

Bundling 10pp doesn't make any sense though, since it's a weidu mod like any other and what's worse, can't be preinstalled. We already list many innovations, but on the new site this could be more prominently displayed indeed.

@bradallred I do it too, but our time is better spent elsewhere. There are hordes of competent and aspiring webdevs, we just need to attract them. :) I can ask the FCC community — it worked before — but that's for later.

**Comment by caillean7** [comment]
Yeah - the most ingenious thing about 10pp is that it patches also the scripts from mods, a pity that it can't be pre-installed, I thought more of sparing people the effort to download. 

Ah well, a Let's Play on GemRB started on occasion of the anniversary would be cool! You don't happen to know anyone with a hot wire to a popular LPer? :laughing:  Imagine Sorcerer Dave or Veriax LPing on GemRB. Or Pem! That would be an awesome thing for sure.

**Comment by bradallred** [comment]
#231 would be nice. It (theoretically) shouldn't be difficult. However, it would require #158 or some cmake voodoo to use C++11 if you want the GUI.

**Comment by caillean7** [comment]
Ooh, looks neat!! Definitely a good thing to have for the other OSs too! Is it an extra executable like the originals also have their own launchers?

**Comment by lynxlynxlynx** [comment]
Yes.
#158 will be history by then, so it's not much of a blocker.

**Comment by bradallred** [comment]
> Ooh, looks neat!! Definitely a good thing to have for the other OSs too! Is it an extra executable like the originals also have their own launchers?

No, it is just a wrapper around the code in `main()` not a separate binary. A separate binary is not a good approach if you want something that works across all platforms especially mobile.

**Comment by lynxlynxlynx** [comment]
Ah, right, no forking.

**Comment by lynxlynxlynx** [comment]
A while back I hunted down Daniele (Balrog) on LinkedIn, but he didn't respond. Today I realized he used a yahoo address in his commits, so just sent a mail to see if it's still used. No immediate mailer complaint, so fingers crossed.

edheldil is about as responsive as a cup of coffee, but I also have his phone #, while Avenger should be better. The lesson is just to start the process much sooner. :)

Time to slowly start drafting the questions, so all help is welcome.

**Comment by MarcelHB** [comment]
Since I don't know the old boards and people and history, some of the questions may suffer from not knowing the obvious, anyway, some suggestions:

* (If not an original author) How did you find your way into GemRB? Given that it was early 2000s.
* Regarding your contribution, what are you especially proud of, what did you find amusing along the way, something that drove you mad ...?
* How did you perform reverse engineering in the very early stages? (Not sure what tools like NI and IESDP were available back then) Was there any help from official developers at some point?
* Still playing IE games, contributing to mods or tools like GemRB? Other games, maybe?
* Thoughts about IE games and GemRB 20 years later?

When I come up with other questions I'd like to hear the answers, I will post them here.

**Comment by lynxlynxlynx** [comment]
That was a great starting point, thanks. Managed to hunt down Balrog too. :) Listed a few media in OP to push to once we're there (suggestions welcome).

Questions sent to Balrog, Edheldil and Avenger.

**Comment by chilvence** [comment]
It's tough to think what to ask about, I could maybe add a few to ask the guys though - 

When you started out, did you forsee the longevity of GemRB? In both senses, eg the length of development time and the long term resilience of the project

Was there anything you wish you knew when you started out (about the game mechanics, or just programming in general?

Is there anything in particular you wish you could see in GemRB? Or conversely, anything that has pleasantly surprised you?

**Comment by lynxlynxlynx** [comment]
One down: https://github.com/gemrb/gemrb.github.io/blob/master/_drafts/20_avenger.md :)

**Comment by lynxlynxlynx** [comment]
Two:
https://github.com/gemrb/gemrb.github.io/blob/master/_drafts/20_edheldil.md

**Comment by kmfrick** [comment]
Other possible community to announce on: https://www.reddit.com/r/baldursgate/
Also should this link to #704 or 704 to this?

**Comment by lynxlynxlynx** [comment]
And the crown jewel: https://github.com/gemrb/gemrb.github.io/blob/master/_drafts/20_balrog.md

I consulted "my" PR expert and she suggested we just tease the interviews, publishing them after the release. Plus the existing plan of including some quotes in the announcement.

**Comment by lynxlynxlynx** [comment]
The 21st is a Friday, so not ideal for press. Ergo I think it's better to do the first batch on Monday and then have the celebratory week. 

So far we have 5 pieces of content (3.5 already written). Any ideas for more? I'm toying with the idea of interviewing myself, to complete the maintainer series. :smiley: Would that be too weird? 

For the 7th piece, probably as the last thing to post, we could do a thank you (& recruiting) post, reflecting on the wider community / ecosystem ("A pearl to you" as the bg2 merchants would say). Just needs something corny, quirky or otherwise appropriate alongside. Like a specially crafted screenshot.

**Comment by chilvence** [comment]
I see what you mean, I personally think you're well deserving of an interview spot, but it does seem a bit bizarre to interview oneself, maybe something like an 'ask me anything' event as a compromise?

**Comment by MarcelHB** [comment]
Feel free to put my name as the interviewer. :wink:

**Comment by lynxlynxlynx** [comment]
An AMA could work, but I don't need that much attention — it's the project that should get it. So yeah, good idea Marcel, the questions were a joint effort anyway. Do you guys have any additional questions for me besides what we asked Avenger? https://github.com/gemrb/gemrb.github.io/blob/master/_drafts/20_avenger.md

Another idea for content 7 would be a gource development visualization like we had in 2013:
https://www.youtube.com/watch?v=2ZL99pXosfI
It's kinda boring when there's low activity, but it's also not something I'd expect anyone to watch in full, for the whole 20-3 years we have revision history.

**Comment by MarcelHB** [comment]
Pick or alter whatever you like:
1. Is there any organizational or financial support on your wishlist? Something else you consider still missing or worth improving?
2. What's on the GemRB feature/tech plan for the future? Like merging subviews, goging Python 3 ... but maybe platform polishing, other technical stuff, EEs? Like a short roadmap of ideas you have in mind.
3. How much time do you currently spend on GemRB for contributing? Per week or month, or generally.
4. How has playing the original games changed for you, given that you do the implementation things all the time?

Gource is probably not so interesting unless it's accompanied by (legal) music, screenshots of milestones and so on. Not sure what the effort is, but I'd estimate it to be non-trivial.

**Comment by chilvence** [comment]
I can't think of any extra questions, but I noticed there is no draft interview from Brad yet either, maybe Marcel can be ghostwriter on that as well :) ?

**Comment by lynxlynxlynx** [comment]
To be honest, I consider Brad a great developer, not a maintainer (same with a bunch of other historically prominent contributors). However that's not really important and the slot for the future of the project is right up his alley and we can just convert it to a sort of interview. If I'm about incremental updates, he's all about leap-frogging. :)

**Comment by chilvence** [comment]
If it is the same article I am thinking of, I found that to be a really nice read, it would definitely be worth mentioning at it so that people who might have missed it will get to see what has been going on, I mean I'm pretty hyped when things get shaken up, I imagine most other readers are the same :)

Speaking of shaking things up, @kmfrick, I won't assume you have time to spare, but I think an article about your experience developing the pathfinder algorithm would be a real crowd pleaser. Even if it were incredibly technical and made me feel dumb, I would enjoy reading it.... Prego :)

**Comment by lynxlynxlynx** [comment]
Something like this? :) https://gemrb.org/2020/07/16/new-pathfinder-smarter-movement.html

There's a lot to say about subviews, so we could have a dedicated article about what's around the corner (so mostly subviews, can be in interview form) and  one looking into the longer future, where we can list the big todos, but also any personal ones, if any.

Marcel: for the news, do you have a favourite quote and an image you'd like to use? Otherwise the fallback is a logo.

**Comment by MarcelHB** [comment]
I don't have screenshots at hand, but maybe some quotes:
* _I don't know what you have expected, but as a sword I'm pretty one-dimensional in what I want!_ -- Lilarcor
* _Whoa, Lord. It's hard to be humble when you're perfect in every way._ -- Elminster
* _Chief, we're being followed! Just look natural, uh, casual._ -- Morte
* _Well, it's been so much easier when I discovered all the Slayer really wants is a sandwich..._ -- Protagonist (BG2)

Pick what you think fits space and context best. :slightly_smiling_face:

**Comment by lynxlynxlynx** [comment]
Thanks and phew, that took some time:
https://github.com/gemrb/gemrb.github.io/blob/master/_drafts/20_lynx.md
I think it's obvious I became an IRL campaigner in the meanwhile. :laughing: 

@bradallred, how do you want to be handled? :) I see at least these options:
- interview form
- writing or helping write the subviews article
- both
- not at all

**Comment by bradallred** [comment]
I'm not much at writing, but I'd be happy to answer some questions about whatever people want to know about.

**Comment by lynxlynxlynx** [comment]
Ok, here are your questions (feel free to improve the intro or add questions you'd like to answer too):
https://github.com/gemrb/gemrb.github.io/blob/master/_drafts/20_brad.md

The wiki writeup we can use sometime later, closer to the next release. It will need an update first anyway.

In other news, the release announcement is written and the main announcement is almost there too — it could stand as is, but there's room for more content and to fine-tune. Code-wise I just have to commit something wrt walking speeds and then it's just about playthrough testing. :) It looks like we've ironed out all the pathfinder corner cases too. @chilvence if you want anything from your WIP pst stuff to be included, time is running out, but also, it can wait — up to you.

**Comment by chilvence** [comment]
Sorry, it has really been getting hard to steal time away to finish stuff! Frustrating, but I think I will be less in demand this week. I only have a couple of "boring" things to fix up, which should be simple to test, I just need a day without any distractions...

**Comment by lynxlynxlynx** [comment]
Ok, the cat is out of the bag and almost everyone already notified. @bradallred please answer the questions — it's scheduled to go out on Thursday.

**Comment by bradallred** [comment]
sorry for the delay, I have been on holiday. All answered now.

**Comment by lynxlynxlynx** [comment]
Phew, got me worried for a second. :) I'll edit it clean, it looks like you wrote it in a rush.

**Comment by bradallred** [comment]
Indeed, thank you.

**Comment by lynxlynxlynx** [comment]
Drafted a Wikipedia page, since the old one got deleted ages ago (4 old ones exist in other languages though) due to notability concerns. There's a very long review queue, but hopefully the FLOSS team will cut the time: https://en.wikipedia.org/wiki/Draft:GemRB

Found out we're mentioned in at least three academic articles. 😃 

Sent mail to LWN, let's see.

Closing.
