### ISSUE TITLE
[bug] BG2: Stuck in cutscene mode after Imoen escaping in Chapter 1

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#354]
**Description**
I just noticed while testing with the fireballs that if Imoen escapes the Irenicus' Dungion due to low health I get stuck in cutscene mode. Pretty sure that's a fairly new problem (?), if you like I can do some bisecting tomorrow.

**GemRB version**
0.85-git

**To Reproduce**
- load a save in Chapter 1 (Irenicus' Dungeon) or start a new game
- get Imoen close to death by e. g. letting her fry herself with Fireballs or Lightning Bolts

**Comment by lynxlynxlynx** [comment]
This from the Mazzy thing, which I haven't reverted yet. Thanks anyway.
