### ISSUE TITLE
[bug] Can't create a Paladin in IWD

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#356]
**Describe the bug**
When creating a PC as a paladin in IWD, you cannot finish the wizard.

GemRB version: HEAD.

**To Reproduce**
1. Create a human paladin.
2. Go through all the steps
3. Try to finish after giving a name

**Expected behavior**
PC to be accepted

**Logs**
```python
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "./GUIScripts/iwd\CharGen.py", line 364, in AcceptPress
[Python/ERROR]:     GUICommon.ResolveClassAbilities (MyChar, ClassName)
[Python/ERROR]:   File "./GUIScripts\GUICommon.py", line 189, in ResolveClassAbilities
[Python/ERROR]:     AddClassAbilities (pc, ABTable, Levels[0], Levels[0])
[Python/ERROR]:   File "./GUIScripts\GUICommon.py", line 228, in AddClassAbilities
[Python/ERROR]:     Spellbook.LearnSpell (pc, ab[3:], IE_SPELL_TYPE_INNATE, 0, 1, LS_MEMO)
[Python/ERROR]:   File "./GUIScripts\Spellbook.py", line 683, in LearnSpell
[Python/ERROR]:     raise RuntimeError, "Failed learning spell: %s !" %(spellref)
[Python/ERROR]: RuntimeError: Failed learning spell: SPIN152 !
```

**Comment by MarcelHB** [comment]
It's probably a typo in one of the 2DA files (clabpala). I cannot find SPIN152 but SPIN125.

**Comment by lynxlynxlynx** [comment]
Yeah, though I'm surprise they get that.

**Comment by lynxlynxlynx** [comment]
Ah, 125 is only named Neutralize poison, while it is in fact their disease resolver. And 152 again only doesn't exist in non-how iwd (smite evil). What does your description say they should get besides remove disease, lay on hands, detect evil and protection from evil?

**Comment by MarcelHB** [comment]
When I'm back at the computer with an optical drive, I can start the original with a Paladin a look for the proper spells.

Other than that I'd say, for non-HoW it should be the same as BG1, and that's less than what the 2DA currently says.

**Comment by caillean7** [comment]
Starting spells for the paladin should be Lay On Hands (SPIN109), Protection from Evil (SPIN121), Cure Disease (SPIN125), Smite Evil (SPIN152) 5x Detect Evil (SPIN120).

**Comment by lynxlynxlynx** [comment]
That's with HoW installed, which he doesn't have.

**Comment by caillean7** [comment]
Ah, sorry, didn't get that.

**Comment by MarcelHB** [comment]
My new Paladin, without knowing if the abilities are supposed to do further things here, has the following spellbook:

SPIN109, SPIN120 (5x), SPIN121, SPIN125

**Comment by MarcelHB** [comment]
I do not remember how many levels there are to reach in IWD but `clubdrui.2da` also mentions non-existing spells (SPIN14x) - but on level 11+.

**Comment by MarcelHB** [comment]
Ok, `XPLEVEL` (Lvl 14) and `XPCAP` (1.8M) make these bugs as well, so let's combine the fix.

**Comment by lynxlynxlynx** [comment]
What do you mean with the last two? They're provided by the game.

**Comment by MarcelHB** [comment]
I wanted to check if there are more unknown spells in other ones of our `clabxxxx` filesfor IWD. So they are for the druids, but only at these high levels (11+) so I had to check how far you actually get and if this might cause the same error later in the game. 

In BG, there was a cap at level 7 or 8 which would not ever cause a problem then.

**Comment by lynxlynxlynx** [comment]
Ah, so it was just a reference to the previous comment. Are you making a PR?

**Comment by MarcelHB** [comment]
Yes, will do.
