### ISSUE TITLE
[bug] [iwd] Can not level up necromancer

### ISSUE THREAD

**Issue by ifyGecko** [gemrb/gemrb#361]
**Describe the bug**
Necromancer PC will not level up, clicking the level up button does nothing. Have been able to level up other PC's under the same save file.

GemRB version: 
0.8.5-git

**To Reproduce**
1. load provided game save
2. kill a couple enemies
3. thief and necromancer will be ready to level up
4. level up necromancer

**Expected behavior**
Necromancer should be able to level up.

**Provided**
1. console log
[log.txt](https://github.com/gemrb/gemrb/files/3789430/log.txt)

**Comment by lynxlynxlynx** [comment]
Here's the cleaned up error, please rather copy it from the console next time:
```
  Traceback (most recent call last):
    File "/usr/local/share/gemrb/GUIScripts/LevelUp.py", line 376, in OpenLevelUpWindow
      TextAreaControl.SetText(GUIREC.GetStatOverview(pc, LevelDiff))
    File "/usr/local/share/gemrb/GUIScripts/GUIREC.py", line 343, in GetStatOverview
      cdet = GemRB.GetCombatDetails (pc, 0)
  RuntimeError: Serious problem in GetCombatDetails: could not find the hitting header!
```

**Comment by lynxlynxlynx** [comment]
How about just reequipping in the same slot?

**Comment by lynxlynxlynx** [comment]
You're describing the same thing twice. The level thing must be a misinterpretation, since there is no way for a pc to level up automatically. Maybe you're just having icon problems.

Anyway, you can ctrl-m on the necromancer to get a debug dump, including his inventory and equipped slot.

**Comment by ifyGecko** [comment]
Maybe "thinks you completed the level up" was poor choice of words on my end. All I can say is I no longer had the ability to click the level up button, it became grayed out.

I attempted the re-equip to same slot situation again, no crash or freezes it just does not let me click the level up button and go through the process. However, the button is still available to click, not grayed out.

I will get the dump as soon as I can, thanks!

**Comment by ifyGecko** [comment]
[Python]: Title: Necromancer    Actor Title: Necromancer
[Python]: Class: 1      Actor Class: 1
[Python]: Kit: 7        Actor Kit: 7
[Python]: ClassName: MAGE       Actor ClassNames: ['MAGE']
[Python]: NumClasses: 1         Actor NumClasses: 1
[Python]: Classes: [1]  Actor Classes: [1]
[Python]: IsDual: False         Actor IsDual 0
[Python]: Actor CurrentLevels: [1, 1, 1]
[Python]: Levels: [2, 0, 0] Actor NextLevels: [2]
[Python]: LevelDiffs: [1, 0, 0] Actor LevelDiffs: [1

**Comment by ifyGecko** [comment]
Noticed that after leveling the thief his info is mirrored on the necromancer's.

![necro](https://user-images.githubusercontent.com/26214995/67891338-64317980-fb20-11e9-9ed6-9282b36cf501.png)
![thief](https://user-images.githubusercontent.com/26214995/67891345-67c50080-fb20-11e9-950d-905180dcab60.png)

**Comment by lynxlynxlynx** [comment]
They have the same name, but I don't think that matters, since pcs don't have script names. Debug dumps would still be handy.

**Comment by ifyGecko** [comment]
necromancer ctl-m:
[GUIScript/ERROR]: Runtime Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/GUICommonWindows.py", line 1767, in PortraitButtonOnPress
[Python/ERROR]:     RunSelectionChangeHandler ()
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/GUICommonWindows.py", line 1378, in RunSelectionChangeHandler
[Python/ERROR]:     SelectionChangeHandler ()
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/GUIREC.py", line 307, in UpdateRecordsWindow
[Python/ERROR]:     Text.SetText (GetStatOverview (pc))
[Python/ERROR]:   File "/usr/local/share/gemrb/GUIScripts/GUIREC.py", line 343, in GetStatOverview
[Python/ERROR]:     cdet = GemRB.GetCombatDetails (pc, 0)
[Python/ERROR]: RuntimeError: Serious problem in GetCombatDetails: could not find the hitting header

thief ctl-m:
[ToHit/DEBUG]: Debugdump of ToHit of asdf:
TOTAL: 18
Base: 19        Generic: 0      Effect: 0
Armor: 0        Shield: 0
Weapon: 0       Proficiency: 0  Ability: -1


[Python]:       Single classed
[Python]:               Class (Level): THIEF ( 3 )

Upon trying to ctl-m on selected weapons to see if that also gave a way to level up presented itself. I have a sling in the 3rd slot, when I click on it the slot grays out forcing me to place it in the first slot since 2nd slot holds a dagger. By doing this I can click level up and successfully level the PC.

**Comment by lynxlynxlynx** [comment]
that's not ctrl-m, just regular logged output. You have to be in the main game view and point on the actors with the mouse.

Trying any gui thing after that python error is pointless.

**Comment by ifyGecko** [comment]
I am using stumpwm instead of a full desktop environment allowing me to control everything with ctl/alt key combination so stumpwm probably recieved the key strokes instead. I split the screen into two windows and got this with ctl-m. Let me know if this is correct output for ctl-m.

Necromancer:
Scripts: <none> <none> <none> <none> <none> <none> <none> <none>
Area:       ar2000 ([1560.1206])   Dialog:     
Global ID:  10003   PartySlot: 2
Script name:none    Current action: -1    Total: 0
Int. Flags: 0x50a04    MC Flags: 0x800    TalkCount:  0   
Allegiance: 2   current allegiance:2
Class:      1   current class:1    Kit: 4096 (base: 4096)
Race:       3   current race:3
Gender:     2   current gender:2
Specifics:  0   current specifics:0
Alignment:  32   current alignment:32
Morale:     10   current morale:10
Moralebreak:5   Morale recovery:60
Visualrange:28 (Explorer: 1)
Fatigue: 1 (current: 1)   Luck: 0

Levels (average: 1):
MAGE: 1    
current HP:11
Mod[IE_ANIMATION_ID]: 0x6111 ResRef:ceff1 Stance: 1
TURNUNDEADLEVEL: 0 current: 0
Colors:       454761243   1010580540   791621423   218959117   370546198   387389207   33686018
WaitCounter: 0
LastTarget: 0 <NULL>    LastSpellTarget: 0 <NULL>
LastTalked: 0 <NULL>
INVENTORY:
10:     FIST - (1 0 0) Fl:0x2029 Wt: 0 x 0Lb
11:   bull01 - (40 0 0) Fl:0x2ca1 Wt: 40 x 0Lb
12:   bull01 - (40 0 0) Fl:0x2ca1 Wt: 40 x 0Lb
13:   bull01 - (32 0 0) Fl:0x2ce1 Wt: 40 x 0Lb
18:   staf01 - (1 0 0) Fl:0x2e21 Wt: 0 x 4Lb
36:   dagg01 - (1 0 0) Fl:0x2c21 Wt: 0 x 1Lb
37:   slng01 - (1 0 0) Fl:0x2c21 Wt: 0 x 0Lb
Equipped: -22       EquippedHeader: 0
Total weight: 5
SPELLBOOK:
 Known spells:
  0:  spwi110 L: 0 T: 1
  1:  spwi112 L: 0 T: 1
  2:  spwi116 L: 0 T: 1
 Memorized spells:
  0:  spwi112 1
EFFECT QUEUE:
  0: 0x07: Color:SetPalette (22, 20) S:slng01
  1: 0x07: Color:SetPalette (27, 16) S:slng01
  2: 0x01: AttacksPerRoundModifier (1, 1) S:slng0

Thief:
Scripts: <none> <none> <none> <none> <none> <none> <none> <none>
Area:       ar2000 ([1592.1146])   Dialog:
Global ID:  10004   PartySlot: 3
Script name:none    Current action: -1    Total: 0
Int. Flags: 0x50a04    MC Flags: 0x800    TalkCount:  0
Allegiance: 2   current allegiance:2
Class:      4   current class:4    Kit: 16384 (base: 16384)
Race:       3   current race:3
Gender:     1   current gender:1
Specifics:  0   current specifics:0
Alignment:  33   current alignment:33
Morale:     10   current morale:10
Moralebreak:5   Morale recovery:60
Visualrange:28 (Explorer: 1)
Fatigue: 1 (current: 1)   Luck: 0

Levels (average: 2):
THIEF: 2    
current HP:5
Mod[IE_ANIMATION_ID]: 0x6001 ResRef:cemc2 Stance: 1
TURNUNDEADLEVEL: 0 current: 0
Colors:       454762014   909522486   690563369   1431655765   370564375   387390230   33686018
WaitCounter: 0
LastTarget: 0 <NULL>    LastSpellTarget: 0 <NULL>
LastTalked: 0 <NULL>
INVENTORY:
 1:   leat01 - (0 0 0) Fl:0x2c21 Wt: 0 x 15Lb
10:     FIST - (1 0 0) Fl:0x2029 Wt: 0 x 0Lb
18:   staf01 - (1 0 0) Fl:0x2e21 Wt: 0 x 4Lb
35:   dagg01 - (1 0 0) Fl:0x2c61 Wt: 0 x 1Lb
Equipped: 0       EquippedHeader: 0
Total weight: 20
SPELLBOOK:
EFFECT QUEUE:
  0: 0x00: ACVsDamageTypeModifier (8, 16) S:leat01
  1: 0x07: Color:SetPalette (22, 5) S:leat01
  2: 0x00: ACVsDamageTypeModifier (-2, 4) S:leat01
  3: 0x00: ACVsDamageTypeModifier (-2, 2) S:leat01
  4: 0x07: Color:SetPalette (23, 4) S:leat01
  5: 0x07: Color:SetPalette (30, 0) S:leat01
  6: 0x91: DisableCasting (0, 0) S:leat01
  7: 0x07: Color:SetPalette (27, 21) S:dagg01
  8: 0x07: Color:SetPalette (93, 20) S:dagg01
  9: 0x07: Color:SetPalette (30, 16) S:dagg01

**Comment by lynxlynxlynx** [comment]
Yeahm that's mostly it (did you edit the name and script lines?). The mage clearly has an odd equipped slot saved. Did you create her yourself or imported from somewhere? The thief doesn't matter.

**Comment by ifyGecko** [comment]
yes to the name and script lines because i was getting this in the log file (gemrb -c iwd.cfg > log.txt). "Script:" was out of screen scope to grab all text in one copy/paste and just over looked typing the repeated <none>'s.

^[[1m^[[37;40m[Actor/^[[0m^[[34;40mDEBUG^[[1m^[[37;40m]: ^[[0m^[[37;40mDebugdump of Actor asdf (asdf, asdf):
Scripts: <none> <none> <none> <none> <none> <none> <none> <none>

I created her and the whole party in game only a day or two ago and no editing of saves has gone on.

**Comment by ifyGecko** [comment]
Script: has \<none\> in them, they needed to be escaped to be printed in a comment.

**Comment by ifyGecko** [comment]
Is there an ExecuteString() command I can use to give xp to a PC so I can try to efficiently reproduce this issue with a different character/save? Also, where would I look to find all console commands?

**Comment by MarcelHB** [comment]
Go to `gemrb/GUIScripts/include.py` to find a list of predefined console commands, and how Python is used.

**Comment by lynxlynxlynx** [comment]
It has nothing to do with XP, but the inventory. You can either look at the guiscript docs at the wiki or the code. The shorthand for SetPlayerStat is sps ... sps(IE_XP,40000).

**Comment by lynxlynxlynx** [comment]
Anyway, I'd start by looking at iwd GUIINV and the UpdateSlot chain in InventoryCommon. Even in HoW, loading an original save, my paladin has 4 weapon slots enabled instead of 3. It is possible to override this with a table, but the defaults match the originals (eg. mages: 2).

**Comment by MarcelHB** [comment]
@ifyGecko Your zipped save game file looks empty, and from what I've read here I couldn't reproduce it. (Necromancer, sling + dagger, level up 1 -> 2)

**Comment by ifyGecko** [comment]
@MarcelHB Hmm, I am just going to delete my custom key macro's for stumpwm and just zip the save like normal, trying to be fancy with stuff is showing itself as more of a hassle than an aid. I will be away from my computer with the saves for most of the day, I will load a proper zip when I can.

@lynxlynxlynx Thanks, I just need a quick way to gain xp so I can try to reproduce this with other characters and saves. I will start looking where you mentioned.

**Comment by ifyGecko** [comment]
[000000008-asdf.zip](https://github.com/gemrb/gemrb/files/3796342/000000008-asdf.zip)

Here is the suspect game save.

**Comment by ifyGecko** [comment]
The bug only arises once you have saved the game. When you start a fresh game the PC has the proper 2 slot restriction. When you save the game and load it the PC now has 4 slots available.
