### ISSUE TITLE
[bug] IWD does not split up quest XPs

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#364]
**Describe the bug**
For the very first quest in AR1006 (tavern), you kill the bugs and return to Grisella to get rewarded 1200XP. In a party of 6, you expect everyone to gain 200XP then, not 1200XP _each_.

GemRB version: Current HEAD

**To Reproduce**
1. Start a new game
2. Get Grisellas quest to kill the bugs in the basement
3. Kill the bugs
4. Talk to Grisella again

**Expected behavior**
200XP per PC.

**Comment by lynxlynxlynx** [comment]
> AddXPVar("Level_1_Easy", 14978)
Unless you have proof the action does split xp, this is invalid.

**Comment by MarcelHB** [comment]
Something doesn't match: When I finish that quest (on diff. level 3) in the non-HoW original, the gain splits up into 200 each.

When I look at the code of that script action, GemRB tests if the the XP value of `EXPTABLE` begins with `P_`, and only then sets `SX_DIVIDE`. My file simply says:

```
Level_1_Easy	1200
```
