### ISSUE TITLE
[bug] [iwd1] saving changes quick weapon slot count

### ISSUE THREAD

**Issue by ifyGecko** [gemrb/gemrb#366]
**Describe the bug**
After loading a game save the quick weapon slot count becomes 4.

GemRB version: 0.8.5-git

**To Reproduce**
1. create game
2. open inventory, note quick weapon slot count
3. save game
4. load game
5. open inventory, the slot count is 4

**Expected behavior**
Saving should not give extra quick weapon slots.

**Comment by lynxlynxlynx** [comment]
Nice find! At first I had a hunch that there might be a wrong reused game flag check somewhere, but it turns out bg1 has the same problem (but not bg2).

**Comment by lynxlynxlynx** [comment]
(these are called quick weapon slots) It looks like weapSlotCount gets updated back from the default of 4 too late/improperly when loading.
