### ISSUE TITLE
[bug] Antimagic shield not shown in IWD

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#368]
**Describe the bug**
In AR8012 (temple in chapter 6), the priests are initially under some kind of influence, shown by their antimagic shield. In GemRB, it is not drawn.

The priests wear some item ANTIMAG that has effect 0xF2 with overlay 0x2 (anti magic shell).

GemRB version: HEAD of right now.

**To Reproduce**
1. Go to AR8012 without fighting the idol

**Expected behavior**
![iwd_antimagic_ok](https://user-images.githubusercontent.com/238558/68092558-b0681b00-fe8c-11e9-8773-9e00060741a9.jpg)

**Actual behaviour**
![iwd_antimagic_bad](https://user-images.githubusercontent.com/238558/68092618-69c6f080-fe8d-11e9-96fa-92051dd329b9.jpg)

**Comment by MarcelHB** [comment]
Code says it reuses the code from PST for this effect but the comments next to the case handling show that it does largely different things than what IWD assigns here (see NI).

**Comment by lynxlynxlynx** [comment]
Yeah, maybe it was true when the opcode was young, but either way, it looks more like a different one from the bg branch.

**Comment by lynxlynxlynx** [comment]
This now works. I'm pretty sure the permanency problem existed before and the 7-eyes don't decrement the visual as you use it, so looking at that now ...

**Comment by MarcelHB** [comment]
Opacity is quite strong here but thanks. :)

**Comment by lynxlynxlynx** [comment]
I doubt we touch the alpha, so that would be a separate issue.
