### ISSUE TITLE
[bug] Wrong avatar for paladin in IWD

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#369]
**Describe the bug**
When I have a paladin PC, it gets assigned animation ID 0x6200, and according to `avatars.2da` that maps to `CHMW`, a _wizard_. When in the PC setup, I still see the correct paperdoll (fighter). I could not spot any other mismatches, though I tested only some H and E models.

I assume that the acquired ID is wrong rather than the 2DA, BG1 does not suffer from that bug but has the same avatar row value.

GemRB version: Current HEAD.

**To Reproduce**
1. Create a paladin PC.

**Expected behavior**
Expect a fighter paperdoll and avatar. Wizard with plate armor looks cool, though. 

**Screenshots**
![palwiz](https://user-images.githubusercontent.com/238558/68092896-33d73b80-fe90-11e9-91b6-9dbe76869996.jpg)

**Comment by MarcelHB** [comment]
I guess 0x6100 would be correct.

**Comment by caillean7** [comment]
I recently had this when I installed the latest version of the IWD 1 NPC project. I thought it was the mod :/

**Comment by MarcelHB** [comment]
What I found out: In `UpdateAnimationID`, for `avprefc` it jumps to row 6 - which says `MAGE` and `0x200` as modifier. 6 results from `GetBase(IE_CLASS)`.

If we look at original 2DA/IDS files, such as `CLASSES`, `CLASWEAP` or `XPCAP`, `PALADIN` is really to be found at row 6.

For them GemRB `unhardcoded` stuff, it's mostly located in row 3. For compatibility reasons, 6 is the must have value. So we could either rearrange all our 2DA files that somehow relate to classes, or rewrite the lookup by to row name.

**Comment by lynxlynxlynx** [comment]
Isn't this just a problem of avprefc.2da? Similarly to how I apparently fixed bg1 in 2010: 3d48d2bb4c7

**Comment by lynxlynxlynx** [comment]
Ah, still need to fix something, sorry.
