### ISSUE TITLE
Remove VOODOO_SHOUT_RANGE

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#373]
Similarly to #145 , we understand the proper calculation now, so we can remove the constant and change its two users.

**Comment by ifyGecko** [comment]
Is this referring to the range out the spell "shout"?

**Comment by lynxlynxlynx** [comment]
No, the actions Shout and Help.

**Comment by ifyGecko** [comment]
@lynxlynxlynx That's what I was afraid of. I have never seen a help or shout action in my limited time in iwd/how. Could you elaborate on what they are or how to trigger them so I can figure things out on my own?

**Comment by lynxlynxlynx** [comment]
First you can dump all scripts (or dialogs) with weidu and decompile them to text, so they're easy to search:
```
weidu --biff-get "*.bcs"
weidu *.bcs # will create .baf files with the plain text
```

Shout and Help are used by the AI for exactly what it sounds like. But you don't really need to test the actions, they just share the constant which we know we can remove. It's just about using Feet2Pixels instead, to account for the isometric view. The comments for the constant explain everything.

**Comment by lynxlynxlynx** [comment]
Are you working on this @ifyGecko?

**Comment by ifyGecko** [comment]
I will be next week. The tail end of this semester has kicked me in the teeth real hard the past couple weeks so my apologies just bear with for the moment.

**Comment by lynxlynxlynx** [comment]
Thanks, was just trying to get some clarity — no rush.

**Comment by ifyGecko** [comment]
Why is it that for Feet2Pixels the angle is from the y-axis to the radial line we are trying to find the length of? I initially thought Feet2Pixels(30, 0) made sense for replacing VOODOO_SHOUT_RANGE but after hand computing this I realized the radius found is 12px instead of 16px like I had assumed. It may be just be the lack of sleep while starting to look at this but that strikes me as odd.

**Comment by lynxlynxlynx** [comment]
It is not really a constant, that is the whole point.

**Comment by ifyGecko** [comment]
How come it's not? 

Also, any specific reason 0 degrees starts on the y-axis for the Feet2Pixels calculation?

**Comment by lynxlynxlynx** [comment]
Because of the isometric view. 
And 0° doesn't start at the top — not sure why you think that.

**Comment by ifyGecko** [comment]
![Screenshot_20191215-141150_Firefox](https://user-images.githubusercontent.com/26214995/70868346-93bc0a00-1f45-11ea-96ea-dfb1663603f9.jpg)

Plug in 0 and you get 12 not 16.

**Comment by lynxlynxlynx** [comment]
You're right, I didn't transplant my test correctly (7ae5fc5) and today only checked the angles check out. Thanks!

**Comment by ifyGecko** [comment]
No problem!

Can you give two distinct examples of when Shout and Help will need differing range values? I must be missing something cause I thought all that was needed was a constexpr with Feet2Pixels just beyond visual range.

**Comment by lynxlynxlynx** [comment]
Shouting for help is omnidirectional, but because the view is tilted, that means fewer pixels of vocal range vertically than horizontally. So someone has to be closer on the y axis to hear you than on the x axis. Maybe reread the comments for VOODOO_SHOUT_RANGE?

**Comment by ifyGecko** [comment]
I feel dumb for asking that, thanks for suggesting to reread the comments. I have no idea where my mind was going this morning but alas that's what sleep deprivation gets ya.
