### ISSUE TITLE
[bug] pause target / casterhold should block scripts?

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#375]
This is the opcode that the summon elemental spells use on the caster (during the "negotiation"). IESDP still says it doesn't block scripts, but igi didn't include the tobex findings where it said explicitly that that is incorrect.

Another simple test case and an obvious show case that there's a problem are the air mephits in the air plane of Chateau Irenicus. They do their little cone of cold grit all the time, since they have this in their script:
```
IF
	See(NearestEnemyOf(Myself))
	Global("airmephitcombat","LOCALS",1)
	Range(NearestEnemyOf(Myself),4)
THEN
	RESPONSE #100
		ForceSpell(NearestEnemyOf(Myself),MEPHIT_GRIT)  // SPIN942.SPL (Breathes Grit)
		AttackOneRound(NearestEnemyOf(Myself))
		AttackOneRound(NearestEnemyOf(Myself))
END
```
Making the effect skip script updates helps, since the frequency decreases, but doesn't fix it fully, since the two other actions abort — the caster is immobile after all and so you don't see normal attacks after the freeze. Maybe it needs to trigger an internal wait and soft block that way.

The IESDP just says it's like stun, but the actor is still selectable and scripts continue to run (which we know is incorrect, but also imprecise). Some easy tests to be done:
- add some DisplayStringHead+SmallWait counter to dplayer scripts that pcs have and have the pc cast one of those mage elemental summoning spells. Do the messages continue to pop up while he's paused?
- `ForceSpell(NearestOf(Myself),MEPHIT_GRIT)` would work to trigger it too (3 second pause)
  - after the pause is done, does the action block continue or do scripts start from the beginning? Eg. if you had `DisplayStringHead(1), Wait(1),DisplayStringHead(2), Wait(1), ForceSpell(NearestOf(Myself),MEPHIT_GRIT), DisplayStringHead(3), Wait(1),DisplayStringHead(4), Wait(1),DisplayStringHead(5)` does it display 4 & 5? Is it after the pause wears out or before?

**Comment by caillean7** [comment]
> add some DisplayStringHead+SmallWait counter to dplayer scripts that pcs have and have the pc cast one of those mage elemental summoning spells. Do the messages continue to pop up while he's paused?

No, they stop during this "mental combat".

**Comment by caillean7** [comment]
> ForceSpell(NearestOf(Myself),MEPHIT_GRIT) would work to trigger it too (3 second pause)
> 
>     after the pause is done, does the action block continue or do scripts start from the beginning? 

Continues.

>   does it display 4 & 5? Is it after the pause wears out or before?

Yes - I guess after the pause... I captured it on Video, see attachment. Here's the block from MEPAIR.BCS: display 2 messages, then cast the spell, after that 2 more messages:

```
IF
	See(NearestEnemyOf(Myself))
	Global("airmephitcombat","LOCALS",1)
	Range(NearestEnemyOf(Myself),4)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,56150)  // Then I see no further need to speak. It shall only make the battle all the harder. 
		SmallWait(30)
		DisplayStringHead(Myself,56151)  // They cannot make us do this, can they? To house us together that we might speak... then force us to fight... it is monstous. Or do you taunt us?
		SmallWait(30)
		ForceSpell(NearestEnemyOf(Myself),MEPHIT_GRIT)  // SPIN942.SPL (Breathes Grit)
		DisplayStringHead(Myself,56152)  // And then Minsc will disrupt them with his bootheel! Yes, speak more of this evil-smashing partnership!
		SmallWait(30)
		DisplayStringHead(Myself,56153)  // And then Minsc will disrupt them with his bootheel! Yes, speak more of this evil-smashing partnership!
		SmallWait(30)
		AttackOneRound(NearestEnemyOf(Myself))
		AttackOneRound(NearestEnemyOf(Myself))
END

```
[mephit.zip](https://github.com/gemrb/gemrb/files/3846687/mephit.zip)

**Comment by lynxlynxlynx** [comment]
Perfect, thanks! You can even see the animation stop. Now just to figure out how to code this in properly ...
