### ISSUE TITLE
[bug] something is wrong with attacking vs range

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#377]
Sometimes actors don't move close enough to really start a ranged attack. Not sure if a regression or not, but it shouldn't be happening. Sometimes I see the actor move closer to get in range, but then not attack, seemingly like she was still too far. I bet something aborts the attack, but haven't investigated any of these hunches yet.

**Comment by caillean7** [comment]
I've noticed something with Melf's Minute Meteors a couple of times. On the original they move into range when out of, but at least sometimes on GemRB they just keep standing there, doing nothing at all. Might that be related or a separate issue?

**Comment by lynxlynxlynx** [comment]
Same thing, the spell creates weapons.
