### ISSUE TITLE
[bug] HoW GUI bug

### ISSUE THREAD

**Issue by ifyGecko** [gemrb/gemrb#378]
**Describe the bug**
When going through dual class selection the class button can overlay the menu.

GemRB version: gemrb-win32-8a4eb6e.zip

**To Reproduce**
1. Go to PC Record
2. Click Dual Class
3. Click Class
4. Click Back

**Expected behavior**
Class button should not overlay the selection menu

![Capture](https://user-images.githubusercontent.com/26214995/68552776-7f35a080-03e0-11ea-8a01-9f767b5f7be0.PNG)

**Comment by lynxlynxlynx** [comment]
The whole window should redraw if you click back and this looks like a partial update.

**Comment by bradallred** [comment]
also, glitches like this wont be possible after the subviews branch is merged so don't pull any hair trying to fix this.
