### ISSUE TITLE
[bug] HoW specialist mage character creation bug

### ISSUE THREAD

**Issue by ifyGecko** [gemrb/gemrb#379]
**Describe the bug**
Known and memorized spells chosen when creating a specialist mage do not match when you start the game. Such as choosing shield, armor, and magic missile for known spells results in armor, identify, and magic missile being known. It can also give you a known spell that was not in the selection list. The chosen memorized spell ends up not being what you picked either.

GemRB version: 0.8.5-git

**Comment by lynxlynxlynx** [comment]
Are you saying it works fine for other specialists and the generalist mage?

**Comment by ifyGecko** [comment]
It is all specialist mages, general mage works as expected as far as I can tell. I updated the title and added another bit of detail I found while testing all specialists.

If I can later tonight I'll further test the generalist mage to make sure this does not affect it too, been extremely busy recently.

**Comment by lynxlynxlynx** [comment]
No need, I have it fixed. :)

**Comment by ifyGecko** [comment]
My man! Getting work done lol
