### ISSUE TITLE
[bug] Can't create new game into BG2 ToB

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#381]
**Describe the bug**
When I try to create a new game for ToB, after the setup, the game finishes into a blue screen - not a BSoD but my area view is fully blue, I cannot access the automap as it then crashes.

GemRB version: current HEAD

**To Reproduce**
1. Create a new game in BG2 ToB
2. Finish the PC setup

**Expected behavior**
Starting in AR4000 AFAIR.

I could not spot any Python errors.

**Comment by bradallred** [comment]
blue area means `core->GetGame()->GetCurrentArea()` is returning null. You probably have something in your log about it.

**Comment by MarcelHB** [comment]
Hmm:
```
[ResourceManager]: Found 'ar4000.are' in 'chitin.key'.
[ResourceManager]: Found 'pathfind.2da' in 'GemRB Unhardcoded data'.
[Unknown]: Cannot find data\AREA4000.bif... Resource unavailable.
[ResourceManager/ERROR]: Couldn't find 'ar4000.wed'.
[AREImporter/ERROR]: No tile map available.
```

**Comment by MarcelHB** [comment]
Ok, my CD5 path was not configured properly ... Not sure if we could prevent this limbus situation then?

**Comment by lynxlynxlynx** [comment]
Uff, don't scare me! :)
At one point we may add a GUI popup window for the fatalities that are not too early (we can reuse the exit window), but someone needs to care enough.
