### ISSUE TITLE
[bug] does circle size affect the hit box for projectiles?

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#384]
We have an old TODO in the projectile code:

> fixme: a dragon will definitely be easier to hit than a mouse

All the calculations are currently using the position only, not accounting for personal space / circle size. Did the original (one should be enough) behave the same? Cone of cold is probably the easiest way to test, since it has a 90° target area. Get two other targets to be the anchors for the angle and then put something outside it, with or without its circle in the expected path.

**Comment by caillean7** [comment]
Doesn't seem as circle size had any effect here. I fiddled a lot with dragons and wyverns. Imoen serves as a marker, she's in a position where she just starts taking damage from Cone of Cold. I targeted some specific speck on the floor every time.
![hitbox1](https://user-images.githubusercontent.com/54738589/69913634-89c0e400-143a-11ea-88b0-bd51146c6493.jpg)
Here the wyverns' foot circle just so protrudes into the rage of the spell.

![hitbox2](https://user-images.githubusercontent.com/54738589/69913655-e7553080-143a-11ea-86f1-f587a34e4408.jpg)

Same positions for Imoen and the caster on the 2nd screenshot, although the dragon covers up Imoen. You can see, though, that she takes damage, while the dragon does not. I'd say from the 2nd one, if personal size would have any impact, the dragon should definitely haven taken damage.

**Comment by lynxlynxlynx** [comment]
Perfect, thanks!

**Comment by caillean7** [comment]
This note in your source code does make a lot of sense, actually. Maybe it could be added as an improvement over IE sometime in the future?

**Comment by lynxlynxlynx** [comment]
So many things could ... it's saner to do it when needed.

**Comment by caillean7** [comment]
Heh, sounds like a prudent approach. Moving on to something else, then.
