### ISSUE TITLE
[subviews] msgwin started too early, breaking the game

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#386]
If you start iwd2 either with cg or a pregen party, the result is the same. As soon as you hit the first dialog that needs continuation, you won't be able to finish it.

This is the error from before you even reach the game view:
```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "../gemrb/GUIScripts/iwd2/MessageWindow.py", line 101, in UpdateControlStatus
[Python/ERROR]:     largeMW.SetVisible(False)
[Python/ERROR]: AttributeError: 'NoneType' object has no attribute 'SetVisible'
```

Similar thing if you start by loading a game:
```
[GUIScript/ERROR]: Runtime Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "../gemrb/GUIScripts/iwd2/GUIWORLD.py", line 54, in DialogStarted
[Python/ERROR]:     MessageWindow.UpdateControlStatus()
[Python/ERROR]:   File "../gemrb/GUIScripts/iwd2/MessageWindow.py", line 118, in UpdateControlStatus
[Python/ERROR]:     smallMTA.AddAlias("MTA_LG", 0)
[Python/ERROR]:   File "../gemrb/GUIScripts/MetaClasses.py", line 44, in handler
[Python/ERROR]:     raise type(e)(str(e) + "\nMethod Docs:\n" + str(f.__doc__))
[Python/ERROR]: RuntimeError: ref cannot be null.
Method Docs:
AddAlias(GView, AliasGroup, AliasID])
```

I thought the reason for making MessageWindow not be what we run first ... is to not run it first, so this is unexpected.

**Comment by bradallred** [comment]
> I thought the reason for making MessageWindow not be what we run first ... is to not run it first, so this is unexpected.

The main motivator was to separate out game specific behavior from MessageWindow so that BG1,BG2, and IWD could all share a MessageWindow.py. Also MessageWindow.py was just not an obvious name for the entry point script :)

The problem here seems to be that `UpdateControlStatus()` is getting called before `OnLoad()` where `MSGWINLG` gets set. I suspect something in chargen (or whatever IWD2 calls it) is doing something unnecessary that attempts to update the message window.

**Comment by lynxlynxlynx** [comment]
Since it's reproducible by plain loading, it can't be a cg thing. Both share code around EnterGame, so yeah, it's more likely core is triggering a callback too soon.

**Comment by bradallred** [comment]
Right, whatever script calls `EnterGame`. Its either doing something it doesn't need to, or the thing its doing just needs to be moved to after the `EnterGame` call. Its possible that moving the offending code to `EnterGame` after the message window stuff is even better.
