### ISSUE TITLE
[subviews] chapter text scrolling too fast

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#387]
It scrolls too fast to even read if you don't start asap and should match master / the voiceover more closely.

Saw it in iwd2, but we likely use the same speed everywhere,

**Comment by bradallred** [comment]
No, it is (or was) fine in BG1 and BG2 (I compared with the originals). The speed is calculated in `GemRB_TextArea_SetChapterText`. How many lines is this text in question?

**Comment by lynxlynxlynx** [comment]
Several, but of course it depends on where it's cut:
```
@14454 = ~Uncle Oswald said that Maer Dualdon was full of sunsets that day.  So many ships coming up the Shaengarne had been set aflame by the goblin hordes that they burned to the waterline in a row like a flock of fiery geese.   Some leapt overboard and tried to swim to shore only to be cut down by orcs when they arrived.  Others clung to the hulking infernos and were inevitably consumed in the flames.  The rest dropped into the icy deep, snowflakes off death's shoulders as he shrugged over the dale.  So many had died already in the attacks that the failure of the Luskan forces to arrive was but a sigh, a comma in what was to be a rather long story.

Only a few small ships made it through to Targos, where my Uncle was watching from the upper reaches of the town.  Many villagers were too busy repelling enemies at the palisade wall to notice a few sad, sorry stragglers make it into the port.  The sun burned behind the horde and cast a cloak of shadows over the heart of Targos and all within.  It was into this shadow that uncommon mercenaries were thrust from Captain Hedron's ship, the Wicked Wench.  Like many other mercenaries in the town, these few had come from Luskan.  Unlike the others, their journeys would take them far beyond the rude palisades and bloody fields that lay ahead of them...
~ [NARR00P]
```

**Comment by bradallred** [comment]
right, but what is the result of `ieDword lines = (h / rowHeight) + 1;`? does that match what is represented visually?

**Comment by bradallred** [comment]
well the speed seems to scale with both the font size and height of the TextArea. Does IWD2 use a much larger or smaller TextArea or font than BGs?

It feels like I meant for `lines` in `ta->ScrollToY(-ta->ContentHeight(), lines * 2500);` to mean lines of total text, but it actually represents the number of lines that are visible in the TA.

**Comment by lynxlynxlynx** [comment]
![image](https://user-images.githubusercontent.com/121515/68883410-46b00280-0711-11ea-93e6-707f9d7afc3d.png)
It depends on what you ran it against. BG1 starting textscreen is this size (bigger):
![image](https://user-images.githubusercontent.com/121515/68883498-79f29180-0711-11ea-8541-1310a4594d9f.png)
the expansion one is basically the message window, so even bigger.

**Comment by bradallred** [comment]
the main issue is resolved, but now somebody needs to go make comparisons with originals. The speed is currently just what felt right to me.

**Comment by caillean7** [comment]
Can I help?

**Comment by MarcelHB** [comment]
You could measure some timings in the original, i.e. how much time does it take until the last line has appeared, and compare them to the latest state of this branch.

Give it a try, some games may have a load problem right now.

**Comment by caillean7** [comment]
Will do. Could also record it for you guys?

**Comment by caillean7** [comment]
Measured from the very beginning to the point where the last line has fully appeared.

| Game / Chapter Text  | IE duration min. | GemRB subviews duration min. |
|-----------------------------|----------------|-----------------------------------|
| BG1 Engl. Prologue "Nestled atop..." | ~ 1:30.5 | ~ 0:45.9 |
| BG2 Engl. End of Irenicus Dungeon "The tunnel slopes..." | ~ 0:22.5 | ~ 0:12.3 |

**Comment by Mingun** [comment]
> Does PST also have chapter texts?

No, PST haven't chapters

**Comment by caillean7** [comment]
Thanks, that's great :smile:

**Comment by bradallred** [comment]
@caillean7 thanks for the assistance :)

Interesting results. We are indeed about 2x faster, but its inconsistent. For example IWD2 is 8.5 sec longer than BG1 on originals but we are 4.9 seconds _shorter_. I'll have to look at the font sizes on those 2. I added a scaling factor because we allow modifications to the fonts and without it things feel wrong if your font is much different in size to the original. As long as we are close that's good enough for me.

@MarcelHB If you are still having issues loading anything you should open a new issue with details. I fixed everything that I knew about.

**Comment by MarcelHB** [comment]
Ok, I had not enough time this morning to check latest changes.

I found the scrolling speed in BG1 terribly slow, but then I'm not sure if it was balanced to respect the mose dense written language that was published (chinese, japanese?).

**Comment by caillean7** [comment]
> I found the scrolling speed in BG1 terribly slow

You're talking about the original, right? Then: agreed. I found it a bit slow to comfortably read along with the spoken text, especially in the beginning.

**Comment by bradallred** [comment]
> I found the scrolling speed in BG1 terribly slow, but then I'm not sure if it was balanced to respect the mose dense written language that was published (chinese, japanese?).

Same, that is why I attempt to scale speed so that larger text moves faster (and why being ~2x faster here is what felt right to me).

That said, I don't care if we are faster or slower as long as there is consensus about how fast it ought to be :)

@lynxlynxlynx thoughts?

**Comment by lynxlynxlynx** [comment]
Being too fast is more of an issue than being too slow, since it has greater impact — one can't read. Let's make it match better; maybe the line width also needs to be taken into account if we want a single formula. Or use the audio length to scale.

**Comment by bradallred** [comment]
yeah, we should take the TextArea width into consideration too. I don't know if we can always assume audio is available. I would think mods with no audio exist. Its also not _that_ big of a deal.

**Comment by bradallred** [comment]
that should be pretty close to the originals. It would be nice to add an INI config for another scaling factor, but apparently our INI class doesn't handle floating point

**Comment by lynxlynxlynx** [comment]
Judging from the high values you used, integers should be just fine.

**Comment by bradallred** [comment]
how would you do it then?

**Comment by lynxlynxlynx** [comment]
I thought you wanted to externalize the 1100, but we actually have GetKeyAsFloat as well.

**Comment by bradallred** [comment]
dang it i forgot to switch my search back to case insensitive!

**Comment by bradallred** [comment]
what INI section do we want this under?

**Comment by lynxlynxlynx** [comment]
We only have one, but it kinda fits too — resources.

**Comment by lynxlynxlynx** [comment]
So it looks like just the externalisation is missing. Is 1100 an empirical value or does it have some significance?

**Comment by bradallred** [comment]
IIRC its just the value that best fit the timing for all the games

**Comment by lynxlynxlynx** [comment]
Ok, so we don't need to have it stored as a float after all. I can take care of this data stuff.

**Comment by bradallred** [comment]
well the float idea was because it seems much more intuitive/friendly to adjust by a multiplier because to a user that is just an arbitrary value instead of a factor they wish to adjust by 🤷

**Comment by lynxlynxlynx** [comment]
But shifting that constant from 1100 to 11 leaves you with a default of 100 to externalize, which is as intuitive, since it appears like a percentage. I'm just averse towards floats, since it's one more thing anyone editing the number can screw up (different decimal symbol in different locales). Not that I expect anyone to edit it after we set it.
