### ISSUE TITLE
[subviews] iwd2 intro movie doesn't play

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#388]
I'm pretty sure we discussed this somewhere before, but for me, the intro video in iwd2 still doesn't play. The logo ones do, but the story mve just leaves a black screen (music plays). @MarcelHB does it work for you?

**Comment by bradallred** [comment]
IIRC its an issue with having subtitles enabled on SDL 1.2. I think the behavior varies between platforms too. there is no longer a working version of SDL 1.2 for me to play with tho.

See the implementation of `SDLOverlayVideoBuffer` which is what is used for BIK videos. I dont know that there is a good way to mix YUV and RGB rendering in SDL1.2. We should probably disable subtitles in this condition (they don't work in master either).

**Comment by bradallred** [comment]
You can also look at the history of that class to play around with/revert some of my experiments trying to get it to work. You can probably pretty easily get it back to a state where the video works but subtitles don't and that is probably as good as it can get. Again, YMMV depending on platform; last time I checked this worked fine on Mac, but obviously that is moot.

**Comment by MarcelHB** [comment]
On Windows, I can have all videos on both SDL1.2 and 2. Linux definitely works with SDL2, too.

**Comment by bradallred** [comment]
@MarcelHB what happens if you enable subtitles?

**Comment by MarcelHB** [comment]
Everything works for both backends. SDL1.2 does not clear the area before showing new subtitles, but that's it.

**Comment by bradallred** [comment]
even using x11 I can't reproduce this except what Marcel mentioned which seems like a limitation/bug from drawing a surface over a YUV overlay 🤷‍♂

**Comment by lynxlynxlynx** [comment]
I retried. It works for me on SDL2, while on SDL1 I still only get the subtitles. :man_shrugging:

**Comment by bradallred** [comment]
what happens if you turn off subtitles?

**Comment by lynxlynxlynx** [comment]
This is per-video, but it does help. With my latest rebuild I get some imagery even with subtitles on, flickery and with rectangles of black now and then, but at least something. Let's just close it.
