### ISSUE TITLE
[subviews] scrollbars don't respect their limits

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#389]
Many scrollbars allow infinite scrolling and at some point that means either no or garbage content. One example would be the iwd2 guirec information window class list, but it's visible in bg2 stores too.

On masters they have a maximum defined and at most a few extra steps available, depending on the design.

**Comment by bradallred** [comment]
see #301. It is an easy fix.

**Comment by bradallred** [comment]
lets start a list of offenders.

all cases should be a simple matter of updating code like `ScrollBar.SetVarAssoc ("TopIndex", Count)` with something that passes the range as 2 additional optional parameters like `ScrollBar.SetVarAssoc ("TopIndex", Count, 0, Count)`.

**Comment by bradallred** [comment]
I'm feeling like GScrollBar needs an override of `SetVarAssoc` that defaults the parameters to 0 and the value. I'll try that and then we can revert the ones that got changed.

**Comment by bradallred** [comment]
I believe that got everything. I don't know of any scrollbars that would have required different clamping values
