### ISSUE TITLE
[subviews] ctrl-shift-y not working anymore

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#391]
ctrl-y works, but the almighty shift variant doesn't.

**Comment by bradallred** [comment]
does shift+y do anything anywhere normally? wondering if this is getting mistakenly eaten by that combo. or is it that the crtl-y code runs for both?

**Comment by lynxlynxlynx** [comment]
I can't think of anything that uses shift besides running in pst. The handling is in the same place for both, in that long ass a-z cheat dispatch.
