### ISSUE TITLE
[subviews] inventory -> records -> inventory craps out

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#392]
I load a game, open the inventory, then the records window and then the inventory again, the gui breaks. Same by just pressing i to open and reopen the inventory:
```
[CHUImporter/ERROR]: Cannot Load Button Images, skipping control
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "../gemrb/GUIScripts/GUICommonWindows.py", line 1377, in ret
[Python/ERROR]:     initer(window)
[Python/ERROR]:   File "../gemrb/GUIScripts/iwd2/GUIINV.py", line 109, in InitInventoryWindow
[Python/ERROR]:     Window.RemoveSubview(Label)
[Python/ERROR]:   File "../gemrb/GUIScripts/GUIClasses.py", line 163, in RemoveSubview
[Python/ERROR]:     return RemoveView(view, False)
[Python/ERROR]: SystemError: error return without exception set
```

The inventory works fine and the error suggests it doesn't find a paperdoll it wants. Considering on the first open all are loaded properly, something goes wrong later and we look up the wrong file (bg2-style) and fail.

**Comment by bradallred** [comment]
```
# info label, game paused, etc
# this is useless to us, message window is still visible
Label = Window.GetControl (0x1000003f)
Window.RemoveSubview(Label) # <- this is line 109
```

This comes after the paperdoll stuff. It appears to be a reference again to the label from #222 
I wonder if that label only exists on 1024x768?

**Comment by lynxlynxlynx** [comment]
No and then it would be a problem on first open too. Does window reopening restore the controls/views? If not, it would explain this bug.

RemoveView should also fail more gracefully and usefully.

**Comment by bradallred** [comment]
probably if you reopen the window before another is opened it is pulled out of limbo. I wonder if the order of things is:

1. inventory opened
2. record win opened
3. inventory closed
4. inventory reopened

if inventory were closed before the records window opened it should be completely destroyed.

then yes that explains what is happening. we should probably check for `None` here and probably any other window initializers that delete controls.

**Comment by bradallred** [comment]
might need to run in a debugger to verify what path `GemRB_RemoveView` is taking in this case, because it looks like it should be hitting  `return AttributeError("Invalid view");` which should set the exception.

**Comment by bradallred** [comment]
I also don't know why were are passing `False` there. I would think we would want to delete that control permanently since we aren't moving it somewhere else.

**Comment by bradallred** [comment]
It doesn't look like `WindowManager` ever attempts to pull windows out of limbo. I wonder if something is calling `InitInventoryWindow` directly after its already been ran once tho.

**Comment by bradallred** [comment]
I added runtime errors for `GUIScript::ConstructObjectForScriptable` so now the error trace is much more useful:

>  Runtime Error:
>  Traceback (most recent call last):
>  File "GUICommonWindows.py", line 1377, in ret
>      initer(window)
>    File "iwd2/GUIINV.py", line 109, in InitInventoryWindow
>      Window.RemoveSubview(Label)
>    File "GUIClasses.py", line 163, in RemoveSubview
>      return RemoveView(view, False)
>  RuntimeError: Cannot construct object with null ref.
