### ISSUE TITLE
[subviews] CharAnimation rendering with CLOAKSC

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#397]
**Describe the bug**
I have an IWD wizard that wears a CLOAKSC (Cloak of Scintillating Colors). On master, it's good. On subviews, half of the animation is lost in alpha, I assume. 

Screenshot to the left is taken from the original.

![iwd_cloaksc](https://user-images.githubusercontent.com/238558/69013197-c5a97300-097d-11ea-8bf5-d620ee766712.jpg)

**Comment by bradallred** [comment]
@MarcelHB is this still an issue?

**Comment by MarcelHB** [comment]
Yes, no improvement here so far.

**Comment by bradallred** [comment]
Sounds like something needs `BLIT_BLENDED` added then.

**Comment by lynxlynxlynx** [comment]
This is not related to BLIT_BLENDED — if you manually add it to all Blit(Game)Sprite*, nothing changes. I get the same result with several spells, like draw upon holy might.

**Comment by bradallred** [comment]
I'll have to actually debug this to know what is happening, but if `BLIT_BLENDED` has no effect then the only sensible explanation is that the palette alpha on the "missing" colors is 0 (or close to it) and the software "shader" in use simply ignores the alpha.

I know long ago (d1c04fa) I had to hack around 0 alpha palettes too.

**Comment by lynxlynxlynx** [comment]
It looks a bit funky — it gets better with time or if you move. I guess from the other frames, so it could be palette related. However it doesn't revert to the bad state by itself either.

**Comment by bradallred** [comment]
oh, then it might be the same general palette issue as all the others. Since SDL_Renderer doesn't support palettes we rely on "versioning" the sprites so that rendering paletted sprites isn't horrifically slow. The (main) problem is that the palette color table is public and a bunch of stuff touches it directly resulting in the "version" getting out of sync. I know at some point in the last year the Palette code was changed quite a bit and I never went though those changes to make sure the versioning was being properly applied after merging it so it could be just a few missing increments too.

**Comment by bradallred** [comment]
after #441 is closed I will open another design meta issue for how `Palettes` need to change. The current versioning solution is inadequate for a variety of reasons, it was just something quick and dirty I threw together to get things mostly working. Things could be much simpler if Palettes could be immutable, but I don't know if that is feasible right now.

At the very least we need a "versioning" system that wont allow 2 distinct palettes to have the same "version", that is another way palettes fall out of sync.

**Comment by bradallred** [comment]
@MarcelHB can you check this for me too?

**Comment by MarcelHB** [comment]
Still the same.

**Comment by bradallred** [comment]
the quest continues; thanks.

**Comment by bradallred** [comment]
for me this looks identical as on master. are you sure this is still broken? can you try with SDL 2.0.12?

**Comment by MarcelHB** [comment]
I can say that it worked with SDL1 backend, also on subviews. I haven't checked since the latest SDL2; I'll do that later today.

**Comment by MarcelHB** [comment]
It's really like that for me:

master/SDL2: good
subviews/SDL2: see screenshot, both for D3D & OGL
subviews/SDL1: good

So you see everything in order across the branches?

**Comment by bradallred** [comment]
yes, everything looks fine for me. does this only happen in certain scenarios? like combined with another effect? or when the sprite is being blended with something else?

**Comment by lynxlynxlynx** [comment]
He was just pointing out master works. Marcel, it'll be easiest if you just share a savegame that has the problem already visible on load.

**Comment by bradallred** [comment]
sure. I was just pointing that out so nobody wastes their time checking SDL1+2 on master. I didn't think it was common knowledge.

**Comment by MarcelHB** [comment]
[000000011-HoW_1.zip](https://github.com/gemrb/gemrb/files/4411786/000000011-HoW_1.zip)

It's IWD HoW + TotLM (German).

**Comment by bradallred** [comment]
ok, i can definitely see it there. weird.

**Comment by bradallred** [comment]
this should also fix the previously unnoticed issue of the actor in the top right being too transparent. probably those blurs too.

**Comment by MarcelHB** [comment]
Cool, looks better :slightly_smiling_face:

**Comment by bradallred** [comment]
this has reappeared and is probably related to #1114
