### ISSUE TITLE
[bug] Effect 0x11A (Suppress HP) not fully applied

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#398]
**Describe the bug**
For IWD (HoW), there is this MOURNER.ITM (Mourner's Armor) that contains opcode 0x11A. It is supposed to hide any information about the current HP. It leaks through, though.

GemRB version: Current HEAD.

**To Reproduce**
1. Start IWD
2. Get and wear MOURNER.ITM or anything with that opcode.

**Expected behavior**

1. Portrait is fully red.
2. Tooltip shows `?` for current HP
3. Inventory and PC sheet as well.

Currently, it's implemented for one case but for most of the things, the current HP is shown.

**Comment by lynxlynxlynx** [comment]
What do you mean by 1?

**Comment by MarcelHB** [comment]
Expected:

![portrait](https://user-images.githubusercontent.com/238558/69013836-efb26380-0984-11ea-906a-10e8b86051c7.jpg)

**Comment by lynxlynxlynx** [comment]
Hah, that's perfect!

**Comment by MarcelHB** [comment]
dadadada, nice.
