### ISSUE TITLE
[subviews] Final HoW cutscene with visual glitches

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#399]
**Describe the bug**
There is another thing I observed that works on master, but is a bit broken in subviews. When entering the area with the final dragon (AR9604), there are two obvious glitches.

1. The dragon does is not seen to fully move to the right to the party but steps out of some kind of alpha curtain that makes him visible slowly. This screenshot shows the scene half way.

![how_scene1](https://user-images.githubusercontent.com/238558/69013695-5b93cc80-0983-11ea-85aa-f683971825eb.jpg)

2. When starting the dialog, the colors/palette is broken.

![how_scene2](https://user-images.githubusercontent.com/238558/69013705-70706000-0983-11ea-94a7-aff80fa6c4cc.jpg)

**Comment by lynxlynxlynx** [comment]
The viewport moves during the cutscene, right? It would be odd, but the first pic looks like the clipping rect was in game coordinates and then not updated for a while.

**Comment by MarcelHB** [comment]
Yes, it moves. Sounds like a solid theory, I guess.

**Comment by bradallred** [comment]
can anybody confirm what it is like on SDL 1.2 for me?

**Comment by MarcelHB** [comment]
No issues there.

**Comment by bradallred** [comment]
@MarcelHB even the clipping is only SDL2? I expected that issue to apply to both... interesting.

**Comment by MarcelHB** [comment]
Yeah, I checked that twice.

**Comment by bradallred** [comment]
@MarcelHB is this still an issue?

**Comment by bradallred** [comment]
specifically the clipping issue. I don't expect any palette issues to have been resolved.

**Comment by MarcelHB** [comment]
No, the clipping is still grabbing into the sprite.

**Comment by bradallred** [comment]
most vexing since the clipping code is common to both backends. Do we know of other cases that behave like this?

**Comment by MarcelHB** [comment]
I don't remember anything like this atm. Just some candidates I can test later/tomorrow.

**Comment by bradallred** [comment]
thanks. If you can think of anything special about this dragon or any polygons/animations that might be in the affected area that would be great info too.

**Comment by bradallred** [comment]
the clipping can be reproduced by an actor being partially offscreen to the left in certain circumstances

**Comment by bradallred** [comment]
those circumstances being if we have a "flip" flag set apparently

**Comment by bradallred** [comment]
The clipping issue should be resolved. We should probably consolidate all the actor palette issues for SDL2 into a new issue since they are distinctly separate issues.

**Comment by MarcelHB** [comment]
Works :+1: Closing this, palettes issues tbd in another issue.

**Comment by bradallred** [comment]
can you see if that dragon palette issue is resolved now?

**Comment by MarcelHB** [comment]
Looks gone!
