### ISSUE TITLE
[bug] IWD1: Noticable gray shadow for elven thief paperdoll in inventory window

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#402]
**Description**
In the inventory screen and the character creation screen the character paperdolls have odd gray shadows in GemRB, see screenshots for a comparison to the original. Looks to me as if those shadows are supposed to be transparent.

**GemRB version**
0.85-git

**Screenshots**
Original:
![IWD_inv_IE](https://user-images.githubusercontent.com/54738589/69067464-656d0c80-0a23-11ea-9cc0-ac439f7062cf.jpg)

GemRB:
![IWD_inv_gemrb](https://user-images.githubusercontent.com/54738589/69067481-6b62ed80-0a23-11ea-99c8-5e47f713379f.jpg)

**Comment by lynxlynxlynx** [comment]
Is this subviews or master?

**Comment by caillean7** [comment]
Both, actually.

**Comment by lynxlynxlynx** [comment]
SDL2? It works fine here.

**Comment by caillean7** [comment]
Nope, SDL 1.2. Could it be a gfx driver thing? I'm using the proprietary nvidia driver on this pc.

**Comment by caillean7** [comment]
This observation was made with an unmodded installation - my modded installation I use for playing hasn't this gray shadows. So the IWD1 fixpack or another mod could have fixed it for you, perhaps? On this modded installation, the shadows are solid black, no transparency here either:
![IWDmodded_inv_gemrb](https://user-images.githubusercontent.com/54738589/69075290-62791880-0a31-11ea-9ffa-a3b245d14a55.jpg)

**Comment by lynxlynxlynx** [comment]
No mods installed, it's a plain HoW.

**Comment by bradallred** [comment]
Does it have anything to do with the color palettes you have selected?

**Comment by caillean7** [comment]
Indeed, it seems so. When I timed those chapter texts, I simply imported the first character in the list, which is +Bard. She has the gray shadows, other characters don't...

**Comment by lynxlynxlynx** [comment]
CEFT1INV.bam needs to be checked if it has a different shadow color.

**Comment by caillean7** [comment]
It has, it's gray, while other *inv.bam files have black shadows.

**Comment by lynxlynxlynx** [comment]
My guess would be we don't even look at the data and just assume a black shadow ... but speculation is cheap.

**Comment by bradallred** [comment]
so I was running UBsan and it complained about `Palette::SetupPaperdollColours`. I fixed that issue in 0b797ba and thought it might possibly be the cause of this.

**Comment by caillean7** [comment]
I tried with the latest subviews code, it's still there, sorry.

**Comment by caillean7** [comment]
Okay, re-checked with master, it persists.

**Comment by fizzet** [comment]
I looked at this for a bit, and the problem afaics is twofold.

1. `Button` uses `BlitSprite()` to render the image, and that completely ignores the shadow colour (uses `SRShadow_Regular`)
2. I believe we're not correctly treating the shadow colour even where we do not ignore it. `SRShadow_HalfTrans` makes the shadow colour itself semi-transparent. It seems to me like the correct treatment would be ignore the colour itself for index 1 just like with the colour key at index 0 and always simply render a semi-transparent black pixel instead. That would also nicely get rid of the BAMWorkshop "fix" in `BAMImporter`.

A naive stab at fixing this made the inventory render fine but broke other stuff like fog of war, so maybe someone more versed in the intricacies of the rendering architecture may want to take another look with this in mind.

**Comment by bradallred** [comment]
we could just tweak the color on the palette in Button.cpp prior to calling `BlitSprite`, or where we assign the picture to the button we can copy the palette and tweak the copy to whatever we want.

I would assume `Palette::SetupPaperdollColours` would be a good place

**Comment by fizzet** [comment]
I don't think the problem is limited to paperdolls, though. It's a general BAM thing.

**Comment by bradallred** [comment]
how so? I don't understand how in general you can always treat index 1 as black. AFIK index 1 is only special in certain contexts (currently where we do `BLIT_NOSHADOW` and `BLIT_TRANSSHADOW` although neither of those exist on the subviews branch anymore)

**Comment by lynxlynxlynx** [comment]
I don't know where all the shadow color comes into play, but the transparent one was actually configurable. The community standardized on pure green and pure black, since even the originals had some problems with other colors.

Doing a random sampling in bg1, most bams do use these colors. I found two exceptions for the shadow color:
- tree03.bam and co, could be deliberate
- the scroll inventory icons for spell scrolls with some orange (unlikely to end up as a shadow, but I forgot to check if the color is even used)

**Comment by fizzet** [comment]
> how so? I don't understand how in general you can always treat index 1 as black. AFIK index 1 is only special in certain contexts (currently where we do `BLIT_NOSHADOW` and `BLIT_TRANSSHADOW` although neither of those exist on the subviews branch anymore)

It may be contextual, yes, but since the gfx pipeline needs to support it anyway, why build a completely separate solution just for paperdolls?

**Comment by bradallred** [comment]
> It may be contextual, yes, but since the gfx pipeline needs to support it anyway, why build a completely separate solution just for paperdolls?

the new gfx pipeline _dosen't_ support it. Having `BLIT_NOSHADOW` and `BLIT_TRANSSHADOW` only made sense because palettes were shared. Shared palettes no longer make sense (see #899 and others), particularly since our SDL 1 backend is soon to be deprecated (#821). Treating a palette index as special on the backend is silly and oddly limiting when nothing shares a palette anymore. Now contexts where we needed `BLIT_NOSHADOW ` or `BLIT_TRANSSHADOW` just change the color at index 1 to what is required for their particular context at assignment time without affecting anything else. It's a matter of a couple lines of code so I don't understand the objection.

**Comment by fizzet** [comment]
The objection was against building an entirely different code path for a specific instance of a common task. If palette munging is the way *all* users handle this issue going forward, then there is no objection. I suppose that means we'll leave master as-is, though.

**Comment by lynxlynxlynx** [comment]
Came across an explanation for the shadow index — it should always be treated as black:

> 2) In which scenarios does the second entry in the BAM's Palette take on the special properties of being the "shadow" color, or does it always?
>
>When the bam is rendering, it asks the palette system how many entries are reserved. If the 2nd entry matches the shadow color of 0x00000000, then it returns 2 Otherwise it returns 1. So basically if the 2nd entry is the shadow color, then it will treat it as such. Otherwise it just uses the 1 reserved entry of the color key green.

https://forums.beamdog.com/discussion/42195/spell-animation-bam-and-translucent-7-flag

**Comment by bradallred** [comment]
there is an even more exciting bit there at the top explaining the blend modes they use and confirming my suspicions about us hacking around things with our palettes. This should enable a lot of cleanup and fix a bunch of bad projectiles.

**Comment by lynxlynxlynx** [comment]
That's just for GL-mode though, which only bg2, how and iwd2 had. It does suggest what algos were used.
