### ISSUE TITLE
[subviews] Escaping the movie list turns screen black

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#403]
**Describe the bug**
A minor bug that I discovered clicking impatiently: I return into a black screen from the videos menu. Works on master.

**To Reproduce**
1. Start BG1/BG2/IWD/HoW into the main menu.
2. Click "Videos"
3. Press the Escape key (not the back/return button)

**Expected behavior**
Return to the main menu. Screen turns black, nothing to do anymore.

**Comment by bradallred** [comment]
esc will close a window unless it is bound as a hot key. Sounds like the movie window just needs to call `MakeEscape()` on the back button. Alternatively we could leave the main window open when opening such windows so then closing the video window would be fine.
