### ISSUE TITLE
[bug] IWD1 HoW: Angaar visible behind gate after barbarian fight

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#404]
**Description**
After Wylfdene ordered the party dead, and your charisma is below 14, you have to fight a group of barbarian warriors in front of their camp. Before this fight, Angaar retreats to the inside of the camp and closes the gate. He stays in this position until after you have left for Lonelywood and re-entered the Camp area. On IE he is not visible in this position, while he is on GemRB. The script that moves him there is [BCCLGATE](https://pastebin.com/0EFzaUzb), which doesn't contain anything like HideCreature (what I suspected at first).

**GemRB version**
0.85-git

**Expected behavior**
Make Angaar invisible through the gate like original does

**Screenshots**
IE:
![Angaar_IE](https://user-images.githubusercontent.com/54738589/69150961-074f3080-0ada-11ea-8915-47103dcc9d14.jpg)
GemRB:
![Angaar_GemRB](https://user-images.githubusercontent.com/54738589/69150985-10d89880-0ada-11ea-9b9e-322e18e88afd.jpg)

**Comment by lynxlynxlynx** [comment]
The question is when does he become "invisible" and what triggers it. That cutscene is surely not enough, since you see it play out.

**Comment by caillean7** [comment]
Yes, you can see him become invisible. When the gate is closed, he first gets transparent and then vanishes completely. There's nothing in the area script or the one that calls BCCLGATE. Could it be just the way the IE treats visibility behind solid objects in general?

**Comment by lynxlynxlynx** [comment]
I still bet it's a script, but yeah, the video shows the same thing:
https://youtu.be/JB32jgRUMvI?t=4416

**Comment by caillean7** [comment]
I'll look into the scripts some more, perhaps searching for HideCreature turns up something, since - according to NI - good ol' Angaar hasn't got his own scripts, he just gets pushed around by all those cutscene script.

Another observation I made while clicking through the dialogue with Wylfdene a million times: The IE displays messages about XP gain and 'You discovered...' beneath the dialogue text in the message window, while GemRB doesn't show those. (Maybe subviews does?) Issue or do you know this one too?

**Comment by lynxlynxlynx** [comment]
All the issues that are not opened (or closed) here should be.

**Comment by caillean7** [comment]
Huh, I searched for it, couldn't find anything (kinda lost overview over all those issues). I'll post it as a feature request then.

**Comment by caillean7** [comment]
If there's yet another script involved, I can't find it.

**Comment by lynxlynxlynx** [comment]
Could be through effects as well. A useful test that you can do is to mod the area and add another neutral actor nearby and see how he is affected. Or just using a hotkey script to toggle the door opened/closed and seeing how visibility of the barbies behind it is affected.

**Comment by caillean7** [comment]
I commented out the closing the gate part of the script, and Angaar remained visible. Then it came to me that I could have just done Ctrl.+J behind the gate to see if he's visible or not :roll_eyes: So no, he's not invisible or disabled, but really seems to be obstructed by that gate.

**Comment by lynxlynxlynx** [comment]
Ok, I wonder if the door has any special bits set. Definitely not something I'm changing just before release (just won in hell btw).

**Comment by caillean7** [comment]
It has a "Cannot close" flag set... there are other things I have no idea what they mean, to be honest (like vertex index or impeded cell index stuff). I also looked at all triggers in this areas to see if there's something unusual, but only travel and info triggers there.

Finished Jon then? Or had you already hacked and slashed your way to Mellisan?

**Comment by lynxlynxlynx** [comment]
Ok, thanks.

... Did that before, but I'm not going to play through whole tob.

**Comment by caillean7** [comment]
Huh, I hope you can still enjoy actually playing the games - would be a shame if gaming would become a mere chore.

Anyway, if I can take some tedious task off your hands for the upcoming release (one that's doable with a mediocre geek-level, that is), do let me know.

**Comment by lynxlynxlynx** [comment]
A runthrough and a playthrough are two different things. :)

**Comment by MarcelHB** [comment]
@caillean7 Is there a mismatch w.r.t. infravision in the screenshot or just a missing selection?

**Comment by caillean7** [comment]
I assumed the original has group infravision activated and GemRB not, but no... That char is a dwarf, and according to the IWD Wiki she should have infravision - except she doesn't. On GemRB it makes no difference if I activate group infravision or not, btw.

**Comment by caillean7** [comment]
Oh boy, just noticed something else - my supposed to be female dwarf has a male avatar :P That's kind of discriminating, you know.

**Comment by MarcelHB** [comment]
Ok, then feel free to open issues.

**Comment by lynxlynxlynx** [comment]
I'll open a separate issue, since infravision is only one of the hardcoded things missing.

**Comment by caillean7** [comment]
Okay, missing feature then.


> A runthrough and a playthrough are two different things. :)

That's your way to say "Go and play the game again", right? Which one - BG2 (I kinda recently did, what resulted in my registering here and spamming you with issues ever since), or another? With mods or unmodded?

**Comment by lynxlynxlynx** [comment]
There's no need now (#189), we're done with the cycle. As soon as I get word back from Wisp, I can commit the addition for the final remaining thing in the milestone and then it's just an hour or two to do the release.

**Comment by caillean7** [comment]
Ah, sounds great. Then I'll save my urges to play any IE game for a time you actually need a test run :smile:

**Comment by lynxlynxlynx** [comment]
Looking at the original, even the first approach proves the gate shouldn't be see-through:
https://youtu.be/8-KFH_jimQw?t=36

Easier to test with that and just further proves it's a door thing, not a scripting thing. :)

**Comment by lynxlynxlynx** [comment]
All that goose chase about the myriad of scripts, while it's clear we added this behaviour as part of a fix for the same area:
https://www.gibberlings3.net/forums/topic/27444-seethrough-doors-discrepancy/

So it should uncover fog of war, but not the shroud.
