### ISSUE TITLE
[enhancement] Not all menu actions should close the main menu

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#406]
after fixing #403 I noticed that leaving the movie window played the short movie that plays when you select Shadows of Amn. I checked the original behavior and its clear that opening the movie window (and probably some others) doesn't close the SoA window. You hear no window close sound and returning from the movies screen doesn't play the video.

I don't _think_ this is feasible to do in master (without hacks), but It would be trivial to do is the subviews branch.

We need to do some research to see which main menu options in which games should actually be leaving the main window open. Maybe we don't care about anything other than BG2 (the replay of that video sure is annoying). The only other way to tell I suppose is if _entering_ the sub GUI produces the window close sound.

**Comment by lynxlynxlynx** [comment]
It just requires a tweak, we already have some conditionality involved for playing the soa/tob video.

**Comment by bradallred** [comment]
care to elaborate on how you would accomplish this?

The idea in my head would remove a bunch of code rather than add any.

**Comment by lynxlynxlynx** [comment]
First I'll check why the "play once" parameter to GemRB_PlayMovie is not enough, but otherwise it'd be just about changing a global variable.

**Comment by bradallred** [comment]
I'll have to check it out and compare the 2 approaches. I don't even know if my plan was feasible because I don't know what side effects we might have been relying on by rerunning the start script.

It sounds perfectly safe on the surface, but I've been surprised many times now :)

**Comment by lynxlynxlynx** [comment]
Probably, yes, though I don't remember how the original behaved either. SoA and ToB surely have different, so only half of the cases could have a continuation on re-start.

**Comment by caillean7** [comment]
> The only other way to tell I suppose is if entering the sub GUI produces the window close sound.

Entering the following sub menus **does** produce the closing sound (GAM_03.wav in BG2):

**BG1**: Main menu: Quit. Single Player: Mission Pack. Multi Player: Connect.
**BG2**: SoA main: Options, Back, Quit. ToB main: Options, Back, Quit
**IWD1** with and w/o HoW: none at all
**IWD2**: New Game, Options
**PST**: (need to install first)

@bradallred Are you also interested in the sub menus?

**Comment by bradallred** [comment]
@caillean7 No, I think its only going back to the main menu that restarts the music/video, so that is the only back that causers annoyance. Thank you, most helpful as always.
