### ISSUE TITLE
[enhancement] IWDs & BGs: Halfling graphics for female gnomes instead of male avatars

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#407]
**Description**
On GemRB female dwarves have male avatars. The paperdoll in the inventory screen is fine.

**GemRB version**
0.85-git

**Expected behavior**
Don't make females have beards, dwarf or not.

**Comment by lynxlynxlynx** [comment]
Are you sure there are animations for them? This is all avatars.2da again, so you can easily compare with bg2 and others.

**Comment by caillean7** [comment]
I compared to IE, and there's definitely a female version. Perhaps she uses some other avatar, like Halfling... Avatars.2da doesn't differentiate between male and female, does it?

I checked BG2 - here, on IE, the avatar is male, while the inventory paperdoll is female. On GemRB both are male. Tomorrow I'll check all small races (best look at Gnomes and Halflings, too, while I'm at it?) in all the games.

**Comment by lynxlynxlynx** [comment]
It does, they're on different lines. And some animations are definitely missing, eg. some female gnome ones and maybe all the halfling ones?

Inventory paperdolls are handled elsewhere though.

**Comment by caillean7** [comment]
Classes also affect this - one thing I noticed a while back with those Ranger-Thief gnomes is that even though I wanted it to use the thief avatar it used the fighter - so maybe defaulted to that because there's no female thief gnome avatar. So there are quite some possibilities to check out. Do you think we can be sure that the original engines use all available animations - so e. g. if BG2 doesn't seem to have a female dwarf avatar, there's not one still hidden somewhere in the game data?

**Comment by lynxlynxlynx** [comment]
1) For new combos it's your choice, plainly through the animations you specify.

2) That would be dumb and while that's not any guarantee, people would have found out ages ago and tobex or other exe hacks would have addressed it.

**Comment by caillean7** [comment]
> For new combos it's your choice, plainly through the animations you specify.

Works for e. g. Half-elves - I guess there just are not many people who play female gnomes and dwarves.

**Comment by caillean7** [comment]
While I'm checking this out, I noticed that GemRB already uses halfling graphics for female gnomes in BG1, unlike on the original, where gnome females look like men. I appreciate this, and while I think there have been discussions about the question if female dwarves are supposed have beards or not in DnD lore, in the case of the games it seems female dwarves appearing mostly male is due to laziness / oversights / time pressure on the part of the developers. This is a dwarf female inventory paperdoll from BG2, while the avatar is male:
![dwarf_inv](https://user-images.githubusercontent.com/54738589/69236783-9a4ca100-0b94-11ea-9d2a-cff460dc6e77.jpg)
So what I'm asking is basically what your approach would  be to make it consistent - stay with the originals or use available female halfling grapics for all games? Or else: Can we have female graphics for female small folk, please?

**Comment by caillean7** [comment]
**BG1** female graphics for the "small races"

| Race / class | Avatar IE / GemRB | Inventory paperdoll IE / GemRB |
|-----------------|--------------------------|-----------------------------------------|
| **Gnome** Fighter | - / :heavy_check_mark: |  - / :heavy_check_mark: |
| " Cleric | - / :heavy_check_mark: | - / :heavy_check_mark: |
| " Thief | - / :heavy_check_mark: | - / :heavy_check_mark: |
| " Mage | - / - | - /- |
| **Halfl.** Fighter | :heavy_check_mark: / :heavy_check_mark: | :heavy_check_mark: / :heavy_check_mark: |
| " Cleric |  :heavy_check_mark: / :heavy_check_mark: | :heavy_check_mark: / :heavy_check_mark: |
| " Thief |  :heavy_check_mark: / :heavy_check_mark: | :heavy_check_mark: / :heavy_check_mark: |
| **Dwarf** Fighter | -/- | -/- |
| " Cleric | -/- | -/- |
| " Thief | -/- | -/- |

**Comment by caillean7** [comment]
**BG2** female graphics for the "small races"

| Race / class | Avatar IE / GemRB | Inventory paperdoll IE / GemRB |
|-----------------|--------------------------|-----------------------------------------|
| **Gnome** Fighter | :heavy_check_mark: / :heavy_check_mark: |  :heavy_check_mark: / :heavy_check_mark: |
| " Cleric | :heavy_check_mark: / :heavy_check_mark: | :heavy_check_mark: / :heavy_check_mark: |
| " Thief | :heavy_check_mark: / :heavy_check_mark: | :heavy_check_mark: / :heavy_check_mark: |
| " Mage | - / - | :heavy_check_mark: / :heavy_check_mark: |
| **Halfl.** Fighter | :heavy_check_mark: / :heavy_check_mark: | :heavy_check_mark: / :heavy_check_mark: |
| " Cleric |  :heavy_check_mark: / :heavy_check_mark: | :heavy_check_mark: / :heavy_check_mark: |
| " Thief |  :heavy_check_mark: / :heavy_check_mark: | :heavy_check_mark: / :heavy_check_mark: |
| **Dwarf** Fighter | - / - | :heavy_check_mark: / - |
| " Cleric | - / - | :heavy_check_mark: / - |
| " Thief | - / - | :heavy_check_mark: / - |

**Comment by caillean7** [comment]
**IWD1** female graphics for the "small races"

| Race / class | Avatar IE / GemRB | Inventory paperdoll IE / GemRB |
|-----------------|--------------------------|-----------------------------------------|
| **Gnome** Fighter | :heavy_check_mark: / :heavy_check_mark: |  :heavy_check_mark: / :heavy_check_mark: |
| " Cleric | :heavy_check_mark: / :heavy_check_mark: | :heavy_check_mark: / :heavy_check_mark: |
| " Thief | :heavy_check_mark: / :heavy_check_mark: * | :heavy_check_mark: / :heavy_check_mark: |
| " Mage | - / - | :heavy_check_mark: / - |
| **Halfl.** Fighter | :heavy_check_mark: / :heavy_check_mark: | :heavy_check_mark: / :heavy_check_mark: |
| " Cleric |  :heavy_check_mark: / :heavy_check_mark: | :heavy_check_mark: / :heavy_check_mark: |
| " Thief |  :heavy_check_mark: / :heavy_check_mark: * | :heavy_check_mark: / :heavy_check_mark: |
| **Dwarf** Fighter | :heavy_check_mark: / - | :heavy_check_mark: / :heavy_check_mark: |
| " Cleric | :heavy_check_mark: / - | :heavy_check_mark: / :heavy_check_mark: |
| " Thief | :heavy_check_mark: / - | :heavy_check_mark: / :heavy_check_mark: |


* GemRB uses fighter avatar instead of available hooded thief ones

**Comment by caillean7** [comment]
**IWD2** female graphics for the "small races"

| Race / class | Avatar IE / GemRB |
|-----------------|--------------------------|
| **Gnome** Fighter | :heavy_check_mark: / :heavy_check_mark: |
| " Cleric | :heavy_check_mark: / :heavy_check_mark: |
| " Rogue | :heavy_check_mark: / :heavy_check_mark:  |
| " Mage | - / - |
| **Halfl.** Fighter | :heavy_check_mark: / :heavy_check_mark: |
| " Cleric |  :heavy_check_mark: / :heavy_check_mark: |
| " Rogue |  :heavy_check_mark: / :heavy_check_mark:  |
| " Mage | - / - |
| **Dwarf** Fighter | :heavy_check_mark: / - |
| " Cleric | :heavy_check_mark: / - |
| " Rogue | :heavy_check_mark: / - |
| " Mage | - / - |

**Comment by lynxlynxlynx** [comment]
Whew, that's comprehensive, great job! Let's go with "halfling graphics for female gnomes" elsewhere too. Dwarves are stockier, so I'd leave those as is. Of course any wrong inventory paperdolls need to be fixed.

The inventory pics are specified in pdolls.2da. If it's not in there we extrapolate.

The star comment needs fixing as well.

**Comment by caillean7** [comment]
So I'll update the respective 2da's locally, re-test and return with a diff for you to review?

**Comment by lynxlynxlynx** [comment]
That would be perfect.

**Comment by caillean7** [comment]
Okay, on the job - just one more question about the IWD dwarves - do you still want them to use male graphics when there are female ones on the original? (Another complaint might be just around the corner - see my inital one).

**Comment by lynxlynxlynx** [comment]
No, we should be using all the available animations, including the thief ones you mentioned.

**Comment by caillean7** [comment]
Uhm, sorry to bother you wit this, but having a few problems here.

IWD1 has a gnome wizard inventory paperdoll, and I'm trying to get GemRB to use it. IWDs Animate.ids lists only
`0x6212 MAGE_FEMALE_DWARF`
 
No *_GNOME, so maybe the IE uses those for the gnome wizards - the file names would suggest: CDFC (D -> dwarf, f -> female). However, updating pdolls.2da accordingly has no effect. So I wonder if GemRB would even attempt to use this animation for the gnomes. Also, pdolls.2da has entries for 0x6213 and 0x6214, not sure what these are for, since IE doesn't seem to have them. However, changing them to use the CDFC graphics doesn't do the trick either. So I'm at a loss as to how to proceed. Do I need to add a new entry, or did I miss something here?

(Furthermore the BG2 dwarven inventory paperdolls don't follow the usual naming scheme, and I haven't found them after spending 2 hours searching already :P I was hoping to get this done quicker, but it's trickier than I anticipated.)

**Comment by MarcelHB** [comment]
Some of these 2DA files partially look a bit copied & pasted from other games, like HoW -> IWD. If there is no corresponding IE content, do not assume they have a particular use in GemRB.

**Comment by caillean7** [comment]
Hey Marcel :smile: Okay. so 0x6213 and 0x6214 don't do anything at all then. I just hope this doesn't involve any messing with the GUI script.

**Comment by caillean7** [comment]
[Here](https://github.com/gemrb/gemrb/compare/master...caillean7:master) is everything related to the respective avatars.2da files. Female dwarves for IWD1 & 2, like the originals, plus the hooded armor level 1 avatars for HoW, all thieves.

The inventory thing is still in the making - perhaps I could do them separately.

**Comment by lynxlynxlynx** [comment]
0x6214 is our female gnome avatar for eg. fighter/mages (I even fixed it in bg2 a week ago — this was my protagonist in the test run). 0x6213 would be the halfling one (gemrb/unhardcoded/bg2/avprefr.2da).

Not sure what problem you have with pdolls.2da. The filenames only matter for the eventual lookup, the key is to have a matching animation id.

**Comment by caillean7** [comment]
I'll try that with the female gnomes in HoW again, then...

The problem with BG2 is that I can't find those bam files, because I don't know the filenames. They do exist, but I've been through all bam files, they are not in there. Not sure how this could be - if I look at another something.bam anytime soon I'll scream.

Also, you have been spotted among Today's birthdays on G3, so: Happy Birthday, lynx!

**Comment by lynxlynxlynx** [comment]
I used weidu to list all *inv.bam files and some awk magic to compare to our pdolls. There are no files *inv.bam that we don't reference yet (ignoring the weapon ones).

Which one are you looking for? And that isn't CDFC*INV, CDFF*1INV, CDFT*INV? Which class?

And yep, it's true, thanks.

**Comment by caillean7** [comment]
> And that isn't CDFC.INV, CDFF.1INV, CDFT.INV?

Don't tell me you have such files? That would be what I'm looking for, just NI doesn't list them!

**Comment by lynxlynxlynx** [comment]
![image](https://user-images.githubusercontent.com/121515/69373899-2e0d9280-0ca5-11ea-9912-fe5216674ef4.png)

**Comment by caillean7** [comment]
There's something with my BG2 installation then - I checked my BGT one, is has those files, too! I made a fresh BG2 installation just a few weeks ago (after the debacle with the invisible shadows), the old CD version of ToB plus the latest patch, no mods. How weird. I'm sorry for the fuss. BG2 pdolls.2da is fine. The other thing I have fixed. So here you go: https://github.com/gemrb/gemrb/compare/master...caillean7:master

**Comment by lynxlynxlynx** [comment]
There's no way I'm going to recheck that, so just submit the PR. :)

**Comment by caillean7** [comment]
Heh, I double-checked and tested everything (twice actually, to account for airheadedness I'm prone to) but of course nothing comes with a error-free guarantee. A pity that there are no animations for female gnome wizards, they still look male - it could be a possibility for the tweak pack to make them use either the fighter or thief halfling avatar, but then, there's 1PP already. Just never tried it, so not sure if it works with GemRB out of the box / without 2da editing.
