### ISSUE TITLE
add the hardcoded racial goodies: THAC0 bonuses

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#408]
Things like infravision, elven sword bonus (a TODO is already in the combat code), ~elven sleep resistance, (only in iwd) dwarves actually get the "vs giants" bonuses and probably more. There's surely a full list somewhere and we know the ingame descriptions can't be trusted.~

We can just add another clab-like 2da to list spells that should be applied in chargen or on import. At least for the features where this is possible, the rest will have to be hardcoded.

I also had a confusing note on the wiki:
> racial boni / generic stat vs. effect application mechanism (check what we do with iwd2:races.2da; bgee also has new tables for this)

**Comment by caillean7** [comment]
I thought I could start with this by going over the game wikis, compile a list for each game and probably verify it on the original engines? I think dwarves' and gnomes' racial con bonuses on saving throws are already handled by 2da files of the originals (according to IESDP), so that would leave then status effects (infravision) plus modifiers for thieving skills and to-hit chance against certain enemies or with certain weapons. Anything else I'm not aware of?

**Comment by lynxlynxlynx** [comment]
Thieving is also handled by 2das. I don't remember the descriptions mentioning anything else.

**Comment by caillean7** [comment]
> Thieving is also handled by 2das.

I see, they seem to get applied later, though, on GemRB. I didn't notice, because IE shows them during chargen already - and I never noticed GemRB has different skill selection screens.

**Comment by caillean7** [comment]
**BG1 & 2** - Special racial bonuses for non-humans not yet implemented

| Race | Infravision | Thac0 | Special Resistances |Comment |
|--------|---------------|----------|---------------------------|-------------|
| Dwarves | :heavy_check_mark: | | | |
|Elves | :heavy_check_mark: | -1 w. Bows / Swords | 90 % to Sleep & Charm * | * originally broken; restored by G3 Fixpack |
| Half-Elves | :heavy_check_mark: | | 30 % to Sleep & Charm * | * originally broken; restored by G3 Fixpack |
| Gnomes | :heavy_check_mark: | | | |
| Halflings | | -1 w. Slings | | |
| Half-Orcs | :heavy_check_mark: * | | | * originally broken; restored by aTweaks |

**Comment by caillean7** [comment]
IWD 1 - Special racial bonuses for non-humans not yet implemented

| Race | Infravision | Thac0 | Special Resistances |Comment |
|--------|---------------|----------|---------------------------|-------------|
| Dwarves | :heavy_check_mark: | | | |
|Elves | :heavy_check_mark: | -1 w. Bows / Swords | 90 % to Sleep & Charm | can't be raised by 'Raised Dead'; Resurrection should work, however |
| Half-Elves | :heavy_check_mark: | | 30 % to Sleep & Charm  |can't be raised by 'Raised Dead'; Resurrection should work, however  |
| Gnomes | :heavy_check_mark: | | | |
| Halflings | | -1 w. Slings | | |
| Half-Orcs | :heavy_check_mark: * | | | |

**Comment by caillean7** [comment]
One more question: 

> > Thieving is also handled by 2das.
> 
> I see, they seem to get applied later, though, on GemRB. I didn't notice, because IE shows them during chargen already


Are you aware of this, is is intentionally / for technical reasons, or might it be good for a feature request -> 'Show racial thief skill bonuses during chargen already'?

**Comment by lynxlynxlynx** [comment]
They already should be, I think both dex and race factor in the initial numbers shown. But I didn't look at the code.

The tables: so only the weapon thac0 bonus is missing? Where did you get the info from? Eg. do iwd dwarves really don't get bonuses vs giants?

**Comment by caillean7** [comment]
> They already should be

Then I might need to open a new issue after all, since they're not - sorry- didn't want to clutter the tracker unnecessarily.

> so only the weapon thac0 bonus is missing? Where did you get the info from?

I found it in the Wikis, then used the original to check it (created 2 fighters with different race but same strength and weapon profs, then compared the thac0 with weapons in question) It checked out.

About the bonuses vs. giants: I couldn't find any reference to that, not in-game descriptions, wikis or general web search. Are you maybe thinking of the fixpack component that gives penalties to giants when fighting 'small folk', or 3rd ed. rules? I remember from NWN that the small races are supposed to have had special combat training vs. giants / orgres, and thus get bonuses, but again - couldn't place that in IWD1.

**Comment by lynxlynxlynx** [comment]
The only clutter on the tracker is when we have several issues reported as one, so don't think that way and open away.

I don't remember where my memory for iwd is from and forum search is partly broken atm. So let's just ignore it.

**Comment by caillean7** [comment]
Organization-wise it might be better to create those To-Do-List for every game? I could prepare them, you can then edit and cut&paste to your original post, so you guys have an easier time to keep track of what has already been taken care of?

**Comment by lynxlynxlynx** [comment]
Combat code is shared, so this bonus will be fixed at once for everyone. Even when the same bug has different manifestations in the games (eg. from different code), one bug is still enough. A Markdown todo-list can be added as needed, but in this case, there's no point.

**Comment by caillean7** [comment]
Alright, if you're all good with this, I'll turn to something else.

**Comment by caillean7** [comment]
Just noticed that there's no Infravision again on GemRB - should I split this into a new issue?

**Comment by lynxlynxlynx** [comment]
Are you sure you have it enabled? And also not disabled darkvision, since it's a synonym? But yeah, if you can prove that it stopped working, open a separate issue.

**Comment by caillean7** [comment]
They are both enabled in gem-baldur.ini. I thought it was never implemented in the first place, see #404. You said there

> I'll open a separate issue, since infravision is only one of the hardcoded things missing.

So I'll open a new one for Infravision. Also for the spell resistance stuff - not sure if that's missing or not?

**Comment by lynxlynxlynx** [comment]
Aha, so this is not about infravision not working, just new chars not getting it.

**Comment by caillean7** [comment]
It doesn't work at all - e. g. Jaheira as a half-elf should have it, but no. I double-checked it says Infravision and Darkvision = 1 in my ini.

Well, the tick was supposed to mean that the races thus marked have Infravision.

**Comment by lynxlynxlynx** [comment]
Yeah and the spell works and it works in iwd2, since it wasn't hardcoded there.

**Comment by caillean7** [comment]
> it works in iwd2

Well, if you're sure it's fine - the only game it works for me is BG1, both IWDs don't.

**Comment by lynxlynxlynx** [comment]
It's not red in iwd2, but that's how it was in the original.
