### ISSUE TITLE
[subviews] Cursor sprite collecting garbage

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#410]
This is a problem I just discovered on Linux - I'm pretty sure it wasn't there some time ago. Anyway, it's specific to subviews, my Linux computer and SDL2.

After moving the cursor around a bit, it starts to look like this.

![cursor](https://user-images.githubusercontent.com/238558/69189514-c7f70300-0b1e-11ea-8755-5e2dbf68bb76.jpg)

I try to bisect it later.

**Comment by MarcelHB** [comment]
@caillean7 Have you noticed this on your Linux computer and this branch?

**Comment by caillean7** [comment]
No, though I hardly ever touch subviews - which game does it affect?

**Comment by MarcelHB** [comment]
This is IWD2. I remember you mentioned you switched to subviews shortly for some recent issue, but I guess you would have noticed it.

**Comment by caillean7** [comment]
I didn't notice anything. Though, according to GemRB.log, it uses SDL 1.2. Stand by - I'll rebuild it with SDL 2 support.

**Comment by MarcelHB** [comment]
Thanks, that will be helpful to exclude driver issues or something (did upgrade to Ubuntu 19.10. recently).

**Comment by caillean7** [comment]
Oi, I'm getting this error, even with -DDISABLE_WERROR=1 (all the SDL2 dev packages are installed):

```
home/nadia/Software/Games/gemrb-subviews2019_11_19/gemrb/plugins/SDLVideo/SDL20Video.cpp:33:13: error: ‘SDL_BLENDOPERATION_ADD’ was not declared in this scope
             SDL_BLENDOPERATION_ADD, SDL_BLENDFACTOR_ZERO,
             ^~~~~~~~~~~~~~~~~~~~~~
/home/nadia/Software/Games/gemrb-subviews2019_11_19/gemrb/plugins/SDLVideo/SDL20Video.cpp:34:13: error: ‘SDL_BLENDFACTOR_ONE_MINUS_SRC_ALPHA’ was not declared in this scope
             SDL_BLENDFACTOR_ONE_MINUS_SRC_ALPHA, SDL_BLENDOPERATION_ADD);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nadia/Software/Games/gemrb-subviews2019_11_19/gemrb/plugins/SDLVideo/SDL20Video.cpp:34:72: error: ‘SDL_ComposeCustomBlendMode’ was not declared in this scope
             SDL_BLENDFACTOR_ONE_MINUS_SRC_ALPHA, SDL_BLENDOPERATION_ADD
```

**Comment by MarcelHB** [comment]
But you did `-DSDL_BACKEND="SDL2"`?

**Comment by caillean7** [comment]
Yes, if I don't, it compiles fine.

**Comment by MarcelHB** [comment]
Hm, is it SDL v2.0.6 or new? Just asking for that specific error.

**Comment by caillean7** [comment]
Nope, 2.0.5. - I'm on Devuan, that's even more "gestrig" than Debian :D

**Comment by MarcelHB** [comment]
I don't want to bother you if this is more than a simple package update command (which I strongly recommend to figure out though). Bisecting already gets me closer.

**Comment by caillean7** [comment]
Nah, there's no newer version in my repositories, likewise this is the latest stable release for this distro. If this was just a single package, I'd try to install it manually alongside the older version, but as things are with this, it will most likely seriously mess up the package database. Sorry :frowning_woman:

**Comment by MarcelHB** [comment]
Yeah, ruins the system at one point or another. Thanks for trying.

**Comment by caillean7** [comment]
Anytime :)

**Comment by MarcelHB** [comment]
@bradallred git bisect tells me the culprit is 3ac85da6ea462266341e6367e848b6ceb5dc6666 - can you relate this to something around the mouse cursor?

**Comment by lynxlynxlynx** [comment]
Did you try reverting it? IOW was the bisect result a true positive?

**Comment by MarcelHB** [comment]
Yes, reverting fixes that thing here.

**Comment by bradallred** [comment]
wow really? interesting. all that should do is add clipping so that we cant draw outside what we have set for the screen clip. What version of SDL 2 do you have?

I wonder if sometimes that is set to a 0 rect or even negative; thats the only way I can imagine a problem just looking at it.

**Comment by bradallred** [comment]
@MarcelHB can you see if that fixed it?

**Comment by MarcelHB** [comment]
Unfortunately not. SDL is v2.0.10.

**Comment by MarcelHB** [comment]
What problem was the commit addressing initially? So that I try to preserve that fix when playing around here later.

**Comment by bradallred** [comment]
it is what prevents drawing outside a view's (not window) bounds

**Comment by bradallred** [comment]
@MarcelHB it has occurred to me `screenClip` is of course screen coordinates, but we are setting a clip for render textures so we actually need to do something like:

- take the intersection of the `screenClip` with the region of the texture buffer
- change the origin of this intersection to 0,0
- apply the new rect as the SDL clip rect

Note that this clipping only is helpful for "primitive" drawing operations. sprites are clipped by passing the rectangle directly to the render texture function.

In fact I'm puzzled at how this works currently, but I have verified that it does:

edit `MapControl` so that it draws its rect outside the control bounds but still within window bounds (eg change the y coordinate to be negative) I can see that the rectangle is properly clipped for me, but if I comment out the `SDL_RenderSetClipRect` call it will happily draw itself over the other things at the top of the window.

![image](https://user-images.githubusercontent.com/1126744/69266885-42f50380-0b89-11ea-9ee3-eb3b326c1237.png)

**Comment by MarcelHB** [comment]
I've replayed your example:

![clipping](https://user-images.githubusercontent.com/238558/69285846-2345f580-0bf2-11ea-9499-02f80d985188.jpg)

From the clipping perspective, the purple region should be your clipping region, right? Not sure how drawing is stacked here exactly, but shouldn't this be a matter of `MapControl` then, like doing `video->SetScreenClip(rgn)` right before drawing that green rect? Then your `SDL_RenderSetClipRect` looks like it does its job while I also cannot explain without some research why this currently works anyway here.

**Comment by bradallred** [comment]
Yes, the purple area would be the clipping region for when `MapControl` is drawn and the green rect should be clipped if `SDL_RenderSetClipRect` is _not_ commented out.

The clipping rect is both set and restored automatically in `View::Draw`. Subclasses don't need to worry about setting their own clip unless they want one for their own purposes.

**Comment by MarcelHB** [comment]
I haven't found enough time but I noticed if I comment out the 2nd case of 3bc7da9bce3b5bc7a0dd3787faa700b72a88ac24 the problem is gone again - so is the cursor sprite supposed to hit the first case by that change?

**Comment by bradallred** [comment]
The cursor shouldn't be clipped at all, so yes it should be going though the first case.

maybe the `video->SetScreenClip(NULL);` in `WindowManager::DrawMouse()` needs to happen sooner?

**Comment by bradallred** [comment]
yes, that is the question;  something must change it later.

That is a good theory about why `SDL_RenderClear` is not working too.

**Comment by MarcelHB** [comment]
On Windows SDL2 uses D3D by default, and metal on Mac? As I'm browsing through the code for OpenGL which is used for Linux, there is one thing in the SDL2 code that I remember being problematic in the OpenGL porting attempt of mine is using `glClear` with an alpha-only value (as the code sets for the cursor) on an on-screen framebuffer, since it does not clear in a way we expect.

I expect to have FBO here that can be cleared to transparency, but I try to find out more and why this conflicts with that change. SDL2 says that `SDL_SetRenderDrawBlendMode` applies to clear operations, precisely to the alpha component of the clear color. Maybe this would to the trick, but that's guessing for now.

**Comment by bradallred** [comment]
we do have `SDL_SetRenderDrawBlendMode` calls for when we pass in a color. do we need an `else` condition to set it no none/blend for other uses?

FYI you can force opengl on Mac and Windows by setting the hint for which renderer to use. Presumably I could reproduce this if I did that.

**Comment by MarcelHB** [comment]
You got my plan ;)

**Comment by MarcelHB** [comment]
Setting the hint works on Windows and produces this bug, so I can happily debug that on my desktop computer.

**Comment by MarcelHB** [comment]
I did a quick experiment, I use `SDL_SetRenderDrawColor(255, 0, 0, SDL_ALPHA_OPAQUE)` to make sure everything is red before drawn over, i.e. in `SDLTextureVideoBuffer::Clear`. Now, you see OpenGL (top) and D3D:

![cursors](https://user-images.githubusercontent.com/238558/69460698-0c7bdc00-0d75-11ea-9a77-75986d4eac2f.jpg)

**Comment by bradallred** [comment]
If this is true universally, then you would see the same artifacts on window buffers that have alpha channels. The round "do you really want to quit" window in BG2 for example.

**Comment by bradallred** [comment]
Sure, it does appear to be so, but you also have shown that not setting the clipping rect fixes it. We also know that the cursor shouldn't have the clipping rect set, but yet it is getting set somehow. That is still the mystery to solve is it not?

**Comment by MarcelHB** [comment]
On both backends, I get a clipping for what looks like cursor sprite dimensions despite assuming we set it to NULL before, so expecting `screenSize`. This is why we never hit the first case at the moment.

But then, why is there virtually no trouble for the other backends anyway - or why does SDL not abstract that the same way for OpenGL? That's what bites me too.

**Comment by bradallred** [comment]
You shouldn't expect different behavior for different backends regarding the setting of `screenClip` that is purely a GemRB thing. We would have to break on `DrawCursor()` and then set a watchpoint on `screenClip` to see what is changing it.

I don't know why OpenGL behaves differently, it _could_ be considered a bug in SDL perhaps, but that isn't relevant really here. We shouldn't have a clip rect to contend with so we shouldn't be triggering this behavior, bug or not.

**Comment by MarcelHB** [comment]
I was wrong, when I go into detailed tracing, we _do_ hit the first case for the cursor, yet disabling the second case keeps us away from that bug. Out of ideas for today, I will try to look tomorrow.

**Comment by MarcelHB** [comment]
Ok, this interesting to a degree that needs explanation by the SDL guys. Consider some experiments:

### Experiment 1
```diff
@@ -412,6 +412,10 @@ void WindowManager::DrawMouse() const
 	pos.y = std::max<int>(0, pos.y - bufSize.h / 2);
 	pos.y = std::min<int>((screen.h - bufSize.h), pos.y);
 
+	Region screenClip = video->GetScreenClip();
+	Region smallerRect(screenClip.x + 1, screenClip.y + 1, screenClip.w - 2, screenClip.h - 2);
+	video->DrawRect(smallerRect, ColorBlue, false, false);
+
 	cursorBuf->Clear();
 	video->PushDrawingBuffer(cursorBuf);
```
The bug: **gone**. What the hell? I just decided to draw the rect dimensions for the clear thing, which is most of the screen at that moment in IWD2 but suddenly the cursor sprite is good again?

### Experiment 2
```diff
@@ -162,6 +162,7 @@ public:
 
 	void Clear() {
 		SDL_SetRenderTarget(renderer, texture);
+		SDL_RenderSetClipRect(renderer, NULL);
 		SDL_SetRenderDrawColor(renderer, 0, 0, 0, SDL_ALPHA_TRANSPARENT);
 		SDL_RenderClear(renderer);
```
The bug: **not gone**. Again, what? If I disable scissoring/clipping before clearing, my clear should apply the whole screen.

### Experiment 3
```diff
@@ -163,6 +163,12 @@ public:
 	void Clear() {
 		SDL_SetRenderTarget(renderer, texture);
+		SDL_Rect r;
+		r.x = 0;
+		r.y = 0;
+		r.w = 1;
+		r.h = 1;
+		SDL_RenderSetClipRect(renderer, &r);
 		SDL_SetRenderDrawColor(renderer, 0, 0, 0, SDL_ALPHA_TRANSPARENT);
 		SDL_RenderClear(renderer);
 
 		ClearMaskLayer();
```
The bug: **gone**. Loosing faith in SDL a bit ...

### Solution
Working with SDL2 on OpenGL requires two things to know (and we probably didn't yet): You cannot effectively call a scissor/clipping update right before a clear command. See implementations of
https://github.com/spurious/SDL-mirror/blob/e4d2f905ebf2e3fa9984980b62210977999c8510/src/render/opengl/SDL_render_gl.c#L1141
https://github.com/spurious/SDL-mirror/blob/e4d2f905ebf2e3fa9984980b62210977999c8510/src/render/opengl/SDL_render_gl.c#L1154

Why:
* SDL2 won't let you enable scissoring if it previously was disabled here.
* SDL2 won't let you update scissor dimensions here.

Solution: You need to draw something in between, because this is where you find `glEnable(GL_SCISSOR_TEST)` and `glScissor(...)` in use. This is probably why experiment 1 works for no obvious reason, but I had a sufficiently large clipping (game area), the cursor there is cleared as the region coincidentally fits here.

Then there is a subtle thing I don't get r/n:
https://github.com/spurious/SDL-mirror/blob/e4d2f905ebf2e3fa9984980b62210977999c8510/src/render/opengl/SDL_render_gl.c#L1169

Clipping is disabled if it's currently enabled _or_ about to be changed, no matter the next state (see some lines above). So if we are about to enable it, we may disable scissoring here - this is why experiement 3 may work even if the rect specification (0,0,1,1) is effecively garbage, but if was previously disabled for the other case you implemented in 3bc7da9bce3b5bc7a0dd3787faa700b72a88ac24 then here you go? So if we didn't change the state (experiement 2), there it may be disabled and unchanged and at some whatever-state `glScissor` was fed last.

The only thing to further address this is probably creating a minimal test case to confirm my digging through the code, and if so, maybe ask at SDL.

**Comment by MarcelHB** [comment]
In the meantime, I can propose this as a one way of workaround. :man_facepalming: 

```diff
diff --git a/gemrb/plugins/SDLVideo/SDL20Video.h b/gemrb/plugins/SDLVideo/SDL20Video.h
index 6b1caee31..43ca4afc5 100644
--- a/gemrb/plugins/SDLVideo/SDL20Video.h
+++ b/gemrb/plugins/SDLVideo/SDL20Video.h
@@ -163,6 +163,11 @@ public:
 	void Clear() {
 		SDL_SetRenderTarget(renderer, texture);
 		SDL_SetRenderDrawColor(renderer, 0, 0, 0, SDL_ALPHA_TRANSPARENT);
+
+		SDL_Point dummyPoint;
+		dummyPoint.x = dummyPoint.y = 0;
+		SDL_RenderDrawPoints(renderer, &dummyPoint, 1);
+
 		SDL_RenderClear(renderer);
 
 		ClearMaskLayer();
```

**Comment by MarcelHB** [comment]
Ok, I could write a minimal test case and then looked in the SDL bug tracker for things that sound related. Turns out we've actually hit a bug for that I roughly see the solution in comment 10 of here: https://bugzilla.libsdl.org/show_bug.cgi?id=4766

So - implement that workaround for 2.0.10. Leave it open until 2.0.12? Closing?

**Comment by bradallred** [comment]
wow, thats quite the diagnosis to digest. Excellent work; thank you.

it looks like then the SDL folks have[ fixed this in their trunk](https://hg.libsdl.org/SDL/rev/d465f3a64af6) so next release shouldn't be afflicted.

You should submit a patch with that patch properly ifdefed to SDL 2.0.10 (sounds like 2.0.9 and earlier work fine): `SDL_VERSIONNUM(2,0,10)` along with a comment (just reference this issue)

Also, why not just use `SDL_RenderDrawPoint` instead?

**Comment by MarcelHB** [comment]
Ok.

No particular reason, was just the first and simple thing I spotted in the SDL source around there. Will use the shorter one.
