### ISSUE TITLE
[subviews] Can move the main menu buttons

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#411]
Try the following (in IWD, maybe it's portable):

1. Click away all the intro movies but the last one.
2. For the last movie, click down the mouse and hold the button pressed.
3. Now, in the main menu, holding the button still down, move the cursor to the left/right.

The buttons turn out to be mobile to some extent. :)
![menu_iwd](https://user-images.githubusercontent.com/238558/69191005-deeb2480-0b21-11ea-99f8-d91f17a922bb.jpg)

**Comment by MarcelHB** [comment]
It's not related to clicking while the last movie plays - you simply don't click any button and this is possible by clicking and dragging the cursor somewhere else.

**Comment by bradallred** [comment]
I cant figure out how you did this but I don't have IWD1 ATM. If it is one of those funky situations where there are 2 windows then my guess would be that you actually had the ctrl key held down and just moved one.

**Comment by MarcelHB** [comment]
No CTRL key, just clicking down over e.g. the background image and moving the cursor then.

![menu_iwd_debug_view](https://user-images.githubusercontent.com/238558/69313406-b8b4aa00-0c31-11ea-80b3-5a553982cec2.jpg)

**Comment by MarcelHB** [comment]
Well, I cannot reproduce this for anything but IWD (+ HoW).

**Comment by bradallred** [comment]
I don't see a second window so thats not it.

**Comment by MarcelHB** [comment]
The content is wider (800px) than the window (640px), so there is 160px to move to the left.

**Comment by lynxlynxlynx** [comment]
On master we passed the true size when declaring the window pack, since yes, the reported size can't be trusted. It's even clearer in iwd2, which also started at 640x, but then that was removed —  the main 800x window still reports the old size.

**Comment by MarcelHB** [comment]
The reported value looks good, it's the label that contains the GemRB version that is ... 800px wide.

**Comment by lynxlynxlynx** [comment]
We create that in Start.py ...
