### ISSUE TITLE
[subviews] Selecting items in bags/stores is delayed

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#412]
I am a bit too lazy to describe it, I had a BAGH01 in IWD/HoW opened, and so I took a record:
![store](https://user-images.githubusercontent.com/238558/69194400-596b7280-0b29-11ea-844b-1548885d78a7.gif)

**Comment by bradallred** [comment]
a lack of visual update I'm assuming

**Comment by MarcelHB** [comment]
Look at the button, it's probably more than visual.

**Comment by bradallred** [comment]
yeah, its like some update function isn't getting called
