### ISSUE TITLE
[subviews] Some buttons get redrawn too frequently

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#414]
You can see what I am talking about by compiling with `DEBUG_VIEWS`

![image](https://user-images.githubusercontent.com/1126744/69299016-ba985200-0bcc-11ea-965c-4a87460fa1b7.png)

The red borders indicate `View`s that need to be redrawn. We don't do a good job of detecting which buttons are truly animated tho so the buttons in the options window and action window are getting redrawn each and every frame, which is not great for performance.

**Comment by bradallred** [comment]
Oddly, IWD2 is much better behaved. I'm not sure what the difference is between the 2.

**Comment by MarcelHB** [comment]
By that, do you mean that `View::NeedsDraw()` is not complete/optimal yet?

**Comment by lynxlynxlynx** [comment]
This is related to a cleanup note I left on the wiki:
> implement or remove IE_GUI_BUTTON_ANIMATED (already defined and used for paperdolls, just no logic in core; at the same time we have a working SetAnimation)

Animated buttons are few and far between (pause, pst portraits, ???), so a manually set flag bit sounds fine if we can't check for the animation directly.

**Comment by bradallred** [comment]
> By that, do you mean that `View::NeedsDraw()` is not complete/optimal yet?

Essentially, yes. Specifically, `Button`s implementation of `IsAnimated()` (which `View::NeedsDraw()` relies on)  is incomplete as lynx alludes to.

**Comment by lynxlynxlynx** [comment]
bg2 action bar buttons are already green. Investigating what's with the options ones, since only rest is truly animated.

**Comment by lynxlynxlynx** [comment]
Odd, neither IsAnimated nor MarkDirty is hit for them. But they do turn green when the game is paused. So I guess it's the window as their superview triggering the redrawing.

**Comment by bradallred** [comment]
I never tried debugging it, but IWD2 buttons behave as I expect and I'm not sure what the difference is.

**Comment by lynxlynxlynx** [comment]
How are you testing it? For me the menu window buttons are red in all the games. PST is the only one that stands out, but it has the animated time control in a different window and the buttons there are red as well. So it looks like I might have been onto something. Do we always redraw windows with animated controls, so they don't smudge (if the animation was bigger than its control — currently the case in bg2*)?

\* an anomaly though, not sure why we do it — it should look like:
![image](https://user-images.githubusercontent.com/121515/94295864-350ace80-ff62-11ea-8f48-90f42fa6fec4.png)

**Comment by bradallred** [comment]
You're right, it is certainly the clock. Proved by the fat that the action window no longer suffers from this since edae5d8

The exact cause is the `TODO` in `View::MarkDirty`. What is happening is the animated control is not opaque so it needs to invalidate a region of the superview and this progresses up the hierarchy until reaching the window (because the window is what has the background) and then the window needs to inform all intersecting subviews that they need to then redraw a portion of themselves. We never calculate this dirty region and instead just call `MarkDirty` which uses the entire `View` region as the dirty region so _every_ subview of the `Window` (actually the `ContentView`) ends up getting dirtied because they all necessarily intersect the `ContentView`. This would also cascade down the entire hierarchy.

I think calculating the dirty region and passing that to the subview `MarkDirty` call would be enough to limit the redraws to just the animated control and it's subviews. We still wouldn't support partial redraws, but thats not really necessary.
