### ISSUE TITLE
[bug] IWD1 w/o HoW: Some inventory graphics not displayed

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#418]
**Description**
In IWD1 without HoW installed there seem to be quite a few problems with inventory graphics: I've seen missing paperdolls (gnomes, I know, that sounds suspiciously like I might messed this up myself, but I don't think I've touched those lines), ~~and also weapons. The quarterstaff you start out with is not displayed on some characters.~~ When this happens, the console spouts errors about missing graphics.

So, I think this needs some more testing (which characters are affected) and checking the pdolls.2da entries. Not sure what's the deal with those quarterstaves, though.

Again, a fresh IWD1 installation patched to 1.06.

EDIT: Striking the problem with the weapons - Marcel couldn't reproduce, and me neither after reinstallation

**Comment by caillean7** [comment]
@MarcelHB Do you have a IWD1 installation without HoW handy? Would you mind checking something for me? Will take only a minute, I promise!

**Comment by MarcelHB** [comment]
I'll try out the gnomes.

**Comment by caillean7** [comment]
Heh, I just wanna know if you have a file "CDFT1INV.bam". I had this weird problem with missing inventory graphics in BG2 recently, and though I just re-installed IWD I'd like to be sure I'm not working with a messed installation again.

**Comment by MarcelHB** [comment]
I don't see any CDFxxxxx files here. Paperdolls seem to be taken from CIxxxINV, avatars from CDMxxxx.

I'm really not sure how gnomes, dwarves and halfling split up their paperdolls  - My non-HoW installation no longer starts correctly after having HoW installed in parallel, so I currently cannot double check that. Anyway, in GemRB, the gnome wizards and the rest don't seem to follow the same line, so you could maybe check the original first?

Looking at the BAM files myself, I also fear that there is some mess in the naming convention (Why are there human-like as well as short creatues in CDxxxxxx? Also for CIxxxxxx?).

I could _not_ reproduce any obvious issues related to quarterstaff displaying.

**Comment by MarcelHB** [comment]
Ok, `ANIMATE.IDS` tells us there is only design for halflings and dwarves - so the task is probably to check where gnomes actually go to here. My memory tells me that gnomes are visually dwarves, but that's the question.

**Comment by caillean7** [comment]
From what I've seen in all the games, CI*** seems to be for Halflings - CH*** is for humans, so maybe they chose i - the next letter - because of this. Anyway, thanks for looking into this, and sorry if it turned out to be more than a minute. If you don't have any CDF***, that's good news. Well, actually, maybe not, because SOMEBODY has to check those pdolls.2da entries now. But just for the record - I didn't put those CDF*** entries in there.

**Comment by caillean7** [comment]
> ANIMATE.IDS tells us there is only design for halflings and dwarves

Lynx commented on #407 

> 0x6214 is our female gnome avatar for eg. fighter/mages (I even fixed it in bg2 a week ago — this was my protagonist in the test run). 0x6213 would be the halfling one (gemrb/unhardcoded/bg2/avprefr.2da).

So he has added those entries for gnomes the IE has not.

**Comment by caillean7** [comment]
>  My memory tells me that gnomes are visually dwarves, but that's the question.

Lynx said:

> Let's go with "halfling graphics for female gnomes" elsewhere too.

So here I just need to make sure they're using the halfling graphics. And I couldn't find any female small folk mage avatars in any of the games, so unfortunately gnome mages will always look male.

**Comment by MarcelHB** [comment]
If you'd ask me out of the blue, I'd say CIFC then. In a second turn, I'd say _Look what the originals do_, even if it looks flawed. So, I'm somewhat too indifferent to decide that.

**Comment by caillean7** [comment]
Yeah, I need to test and compare to IE again. I keep forgetting IWD is considered a different game than HOW, so I also forgot it when doing those tests for #407. Again, thanks a lot for your help :)

**Comment by caillean7** [comment]
**IWD1 w/o HoW** female graphics for the "small races"

| Race / class | Avatar IE / GemRB | Inventory paperdoll IE / GemRB |
|-----------------|--------------------------|-----------------------------------------|
| **Gnome** Fighter | - / :heavy_check_mark: |  - / - * |
| " Cleric | - / :heavy_check_mark: | - / - * |
| " Thief | - / :heavy_check_mark: | - / - * |
| " Mage | - / - | - / - |
| **Halfl.** Fighter | :heavy_check_mark: / :heavy_check_mark: | :heavy_check_mark: / :heavy_check_mark: |
| " Cleric |  :heavy_check_mark: / :heavy_check_mark: | :heavy_check_mark: / :heavy_check_mark: |
| " Thief |  :heavy_check_mark: / :heavy_check_mark:  | :heavy_check_mark: / :heavy_check_mark: |
| **Dwarf** Fighter | - / :heavy_check_mark: | - / - * |
| " Cleric | - / :heavy_check_mark: | - / - * |
| " Thief | - / :heavy_check_mark: | - / - * |


* pdolls.2da lists non-existent bam resulting in GemRB not displaying any paperdoll at all

The question about dwarves is, should they continue using halfling graphics (like in HoW), or changed to dwarf like on the original? Lynx said:

> Dwarves are stockier, so I'd leave those as is

So we're using also dwarven graphics for the BGs. So - to change or not to change?

**Comment by lynxlynxlynx** [comment]
Every playable character variant should have a paperdoll, so make it so. Since they apparently added some only with HoW, chose the next best thing.

**Comment by caillean7** [comment]
Done. I also fixed female halfling fighters, that used the cleric paperdoll previously. The male smallfolks I have tested, they are okay.

**Comment by lynxlynxlynx** [comment]
Thanks!

**Comment by caillean7** [comment]
Gladly! I'm taking the rest of the day off, so have a great WE, guys :smile:
