### ISSUE TITLE
[subviews] BG/IWD/IWD2 loading screen has a scrollbar

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#422]
Looks familiar to #411 but this time we see a scrollbar to the right, and as soon as the cursor appears, you seem to have both axes (but only little time) to move the content around a bit.

![bg_loading](https://user-images.githubusercontent.com/238558/69501013-00248a00-0f01-11ea-91a2-7a46a8673c20.jpg)

**Comment by MarcelHB** [comment]
In BG, that self-made GUILS has an section for the prograss bar that requires definitely too much height (230px vs. 100px available, scrollbar is gone when set to 99px).

Since the explicit size override is no longer in the GUI script, we probably need to patch these files for BG/IWD/IWD2.

**Comment by lynxlynxlynx** [comment]
Controls/vuews have a SetSize defined in python, so it's easy to reinstate such tweaks, if they were removed.

**Comment by MarcelHB** [comment]
Not sure if this is intended w.r.t. subviews. As far as I see, those params in `LoadWindowPack` will did a hard cut, and scrollbars were nowhere in sight. Now, if the content is actually larger than the window frame (which is Ok since it's 640x480), (vertical) scrollbars appear. Since there is, I assume, no further discrimination then between this oversized GUILS child element or let's say valid content as in #296, one of these cases will make the other suffer then

**Comment by lynxlynxlynx** [comment]
I don't get — we glue everything together manually, so we can as easily set the height to 99px for that element alone at runtime, without affecting any other window.

**Comment by MarcelHB** [comment]
Ok, that's an option as well.

**Comment by bradallred** [comment]
you can also use `SetResizeFlags` (see `AutoresizeFlags` definition) to change the behavior.

**Comment by lynxlynxlynx** [comment]
Sorry, I didn't realize this is data provided by us. I've fixed it for all games. IWD2 needed more tweaks, while I couldn't see anything in how (no fat saves on this machine), so that's amended, but unchecked.
