### ISSUE TITLE
[bug] iwd fighter/clerics also erroneusly get druid spells

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#425]
Reported here:
http://gibberlings3.net/forums/topic/28112-a

Potentially there's also something about racial kit restrictions to extract into a separate report.

**Comment by caillean7** [comment]
> 1. The dwarf gets characteristics (-1 wisdom and +1 intellect) 

No. This affects the possible maximum values for the respective attribute, right? There are issues here, this stuff seems to be only partly implemented, e. g. dwarves can have a con of 19 on GemRB while dex is not capped at 17, but aren't those racial bonuses covered by #408? Then it'll be checked out anyway.

> 2. Multiclass character warrior/cleric knows spells the cleric and druid.

No, a newly created fighter / cleric combination has the exact same spells on GemRB as on IE

> appearance ( no beard) like gnome.

No, the avatars and paperdolls are dwarven alright. However, the IE uses cleric graphics for fighter / clerics, GemRB applies fighter graphics.

**Comment by lynxlynxlynx** [comment]
Thanks, so only one thing to do — I'll ignore the avatars.

1. No, these are not hardcoded bonuses, this is all in:
https://gibberlings3.github.io/iesdp/files/2da/2da_tob/abracerq.htm
https://gibberlings3.github.io/iesdp/files/2da/2da_tob/abracead.htm

Which we already read and use, so if a dwarf can get 18 dex, it's a bug in gemrb/GUIScripts/bg2/GUICG4.py .

.. but I see now this was reported against iwd, not bg2, grrr. Where were you testing?

**Comment by caillean7** [comment]
*cough* I tested BG2.

> if a dwarf can get 18 dex, it's a bug in gemrb/GUIScripts/bg2/GUICG4.py 

But then it wasn't for naught, because dwarves can get 18 dex with GemRB. I'll open a separate issue.

Retested on IWD1, and here single and multiclass clerics indeed have druid spells (both with and without HoW installed). The avatars and max stats are fine.

**Comment by lynxlynxlynx** [comment]
Ok. This bug will then remain about the spell issue. I have a slight memory that iwd doesn't have a separate mxspl* table for druids? Might be that, but the memo thing is a very good starting point, thanks.

**Comment by lynxlynxlynx** [comment]
Looks like this has been fixed already. I've created a half-elf f/c and in both cases got the same spells.
