### ISSUE TITLE
[bug] BG2 GUICG4.py: Faulty max stats for dwarves and halflings

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#431]
**Description**
Dwarves can have a maximum dex of 18 on GemRB while it should be capped at 17. Also, according to the [BG2 Wiki](https://baldursgate.fandom.com/wiki/Halfling) Halflings should get -1 to wis besides +1 dex and -1 str (which works). All other races are fine, I compared them to the stat modifiers listed on the Wiki.

**GemRB version**
0.86-git

**Expected behavior**
- max dex for dwarves: 17
- max wis for halflings: 17

**Comment by lynxlynxlynx** [comment]
This is all in:
    https://gibberlings3.github.io/iesdp/files/2da/2da_tob/abracerq.htm
    https://gibberlings3.github.io/iesdp/files/2da/2da_tob/abracead.htm

Which we already read and use, so it's a bug in gemrb/GUIScripts/bg2/GUICG4.py .
