### ISSUE TITLE
[subviews] Modal windows have a slightly wrong position.

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#433]
This is one example of BG2 discovered for #287 with notable shining through.

![69532491-40721f80-0f76-11ea-8d3f-4e4b655101a5](https://user-images.githubusercontent.com/238558/69812448-6e629880-11f0-11ea-9bcf-f2eedfaf5a22.jpg)

In this example of IWD, you probably don't notice that, and it's only three pixels too high, but maybe there is some common cause?

![modal_window_offset](https://user-images.githubusercontent.com/238558/69812539-9c47dd00-11f0-11ea-975a-d0ad97c82c62.jpg)

**Comment by bradallred** [comment]
It is a side effect of being resolution independent. What exactly do you want us to do about it?

For the main menu relative positioning could be done (tho I would argue in the IWD case you are just being pedantic), but in general other modal windows in the game don't have anything to anchor their position to.

**Comment by MarcelHB** [comment]
Yeah, the second example is not relevant.

In PST, the res. independence is good (speaking of my HD mod there). But for BG2 here, there is something odd: If you take the two MOS files and put the one for win ID 3 (the dialog) over the background, it should be seamless as it is on master. Though, even for none of the native resolutions, this dialog MOS up in the correct place.

**Comment by MarcelHB** [comment]
A bit of rephrasing, this is 640x480 in BG2. There should not be any room for effects depending of screen resolution effects, right? Yet the overlay window did end up elsewhere.

![bg2_smallest](https://user-images.githubusercontent.com/238558/69829111-0f684800-121f-11ea-8155-30e3c9429c50.jpg)

**Comment by bradallred** [comment]
The resolution independence ignores window coordinates completely. There is no way to know any better, especially when you factor in the widescreen mod.

 There are positioning flags to achieve positioning:

```
enum WindowPosition {
		PosTop = 1,		// top
		PosBottom = 2,	// bottom
		PosVmid = 3,	// top + bottom = vmid
		PosLeft = 4,	// left
		PosRight = 8,	// right
		PosHmid = 12,	// left + right = hmid
		PosCentered = 15// top + bottom + left + right = center
	};
```
We also have a Python function to position a window relative to another which is used currently only for chargen. It is also what would need to be employed here or other cases where you are trying to align 2 windows.

**Comment by MarcelHB** [comment]
Ok, I get it.

**Comment by lynxlynxlynx** [comment]
So, did we notice any other cases? Can't say I have. But it's easy to fix.

This one in start.chu should work fine with WINDOW_TOP (same offset from the top as the bg), but we crop its empty padding somewhere, so that doesn't do it. I'll just reposition it, since it's two lines of code. The cg function is not generic and relating to the frame would likely hit the same problem.

**Comment by MarcelHB** [comment]
Looks good, I'll reopen if I find any other significant example.
