### ISSUE TITLE
[bug] Save-before-exit dialog appearing when in CharGen

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#434]
**Describe the bug**
When you try to hard-exit the game while in CharGen, the dialog pops up that asks you if you want to save before exit. You can actually click Save, and Python errors appear, putting some of the games into a buggy state.

GemRB version: HEAD of r/n.

**To Reproduce**
1. Go into CharGen of whatever game, in IWD2 you need to go into the custom group setup.
2. Click "X" or whatever button on your window title bar to close the game.
3. Click "Save" in the dialog.

**Expected behavior**
_Save_ should be disabled, makes no sense anyway.

**Screenshots**
IWD (and some other):
```py
[GUIScript/ERROR]: Runtime Error:
[Python/ERROR]: .gemrb/GUIScripts\GUISAVE.py:97: RuntimeWarning: tp_compare didn't return -1 or -2 for exception  for j in range(min(6, MAX_PARTY_SIZE)):
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "./gemrb/GUIScripts\GUIOPT.py",line 619, in SaveGamePress
[Python/ERROR]:     GUISAVE.OpenSaveWindow ()
[Python/ERROR]:   File "./gemrb/GUIScripts\GUISAVE.py", line 97, in OpenSaveWindow
[Python/ERROR]:     for j in range(min(6, MAX_PARTY_SIZE)):
[Python/ERROR]: RuntimeError: Cannot find window index #0 (unloaded?)
```

PST:
```py
[GUIScript/ERROR]: Runtime Error:
[GUIScript/ERROR]: Syntax Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "./gemrb/GUIScripts/pst\GUIOPT.py", line 441, in SaveGame
[Python/ERROR]:     GUISAVE.OpenSaveWindow ()
[Python/ERROR]:   File "./gemrb/GUIScripts\GUISAVE.py", line 49, in OpenSaveWindow
[Python/ERROR]:     if GUICommon.CloseOtherWindow (OpenSaveWindow):
[Python/ERROR]:   File "./gemrb/GUIScripts\GUICommon.py", line 44, in CloseOtherWindow
[Python/ERROR]:     OtherWindowFn ()
[Python/ERROR]:   File "./gemrb/GUIScripts/pst\GUIOPT.py", line 59, in OpenOptionsWindow
[Python/ERROR]:     GemRB.SetVar ("OtherWindow", -1)
[Python/ERROR]: AttributeError: ===== SetVar =====
```

**Comment by MarcelHB** [comment]
I did not find a stable cross-game state that can be used here yet. Best thing looks like `QuitFlags` since `QF_ENTERGAME` looks unset at this point but that querying that will require a new GUIScript method.

**Comment by lynxlynxlynx** [comment]
We already have one for a pretty haphazard set of core variables, but perhaps it's not needed. We could check against one of the stats charbase doesn't have set up until the end of chargen as a proxy.

**Comment by MarcelHB** [comment]
Besides sounding hackish, I guess will fail for IWD(2) since you may already have a fully setup PC while still in CG.

**Comment by lynxlynxlynx** [comment]
It would just require a loop, since CreatePlayer adds them to the party already at the start of CG. But it might be simpler to just check for the existence of the game window; at least on master it's a global.

**Comment by MarcelHB** [comment]
Sounds better to me, but `GameWindow` is never `None` and looks to be toggled over visibility only.

https://github.com/gemrb/gemrb/blob/a859eee0439b5e3d349bbcfd6ab748559dd32a1e/gemrb/GUIScripts/GUICommon.py#L837

**Comment by lynxlynxlynx** [comment]
It will be pointing to a different window when early, but yeah, it's easier to have EnterGame just set a global var to check or even easier, expose it via GetSystemVariable.

**Comment by bradallred** [comment]
on the subviews branch you can just check `GemRB.GetView("GC") is not None` maybe its better to just fix it there instead of adding more infrastructure.

**Comment by MarcelHB** [comment]
@bradallred There is no alias `GC` for all these CharGen windows yet, right? Because that did not work and I was wondering how to get them.

**Comment by MarcelHB** [comment]
Argh, spent some time looking for `CG` (as in CharGen) while you probably meant `GC` for GameControl to check, right?

**Comment by lynxlynxlynx** [comment]
Yes.

**Comment by MarcelHB** [comment]
This approach fails because of:

```py
[GUIScript/ERROR]: Runtime Error:
[GUIScript/ERROR]: Runtime Error:
[Python/ERROR]: RuntimeError: Failed to lookup name 'Ggc'
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File ".\gemrb\GUIScripts\GUIOPT.py", line 567, in OpenQuitMsgWindow
[Python/ERROR]:     if GemRB.GetView("GC") is not None:
[Python/ERROR]: RuntimeError: Failed to construct object
```

I did not find my way through the script and view code here yet. Not sure how busy the week will be, so I leave it there for now.

**Comment by lynxlynxlynx** [comment]
Did you manually retype that or does it really look for 'Ggc'?

**Comment by MarcelHB** [comment]
It really does, it prepends a 'G' for the lookup.

**Comment by lynxlynxlynx** [comment]
Ah, it's the class then, like GControl. I guess it will never work with nonexisting aliases without a try-catch statement. Perhaps we should be logging and returning None instead, so it's easier to work with.

**Comment by MarcelHB** [comment]
Apart from that, `GC` is registered as a script group. So, not sure if this is the way to go anyway?

**Comment by bradallred** [comment]
you probably need to also pass the second parameter of `GetView` as 0. I have done this before, so I know it works :)

Its possible it was recently broken I suppose.

**Comment by bradallred** [comment]
Nevermind, that param defaults to 0 so that's not it. You can see that in `Interface::StartGameControl` we do `gamectrl->AssignScriptingRef(0, "GC");` so that ref should be valid. This is the same thing we do for other things like the window groups for dialog/cutscenes too.

Probably, we have a switch somewhere switching on type and `GameControl` is missing from that.

**Comment by lynxlynxlynx** [comment]
StartGameControl hasn't run yet at this point, that's why.

**Comment by bradallred** [comment]
No, if that were true it wouldn't have been able to lookup anything and you would get `None`. The lookup is successful, but decoding it into a Python object fails.

It broke because `GameControl` no longer is a subclass of `Control` and the Python object constructor assumes that everything is a control.

**Comment by lynxlynxlynx** [comment]
Well, it's only called by GemRB_EnterGame, which cg doesn't do until the very end.

**Comment by bradallred** [comment]
Well we don't know where @MarcelHB was encountering that error. But looking at the error he gets it is clear that lookup is successful since it tries to construct an object and in fact tries to construct a `Ggc` from it. We just need a check in `GemRB_GetView` to construct non-controls differently by passing "View" as the class instead of attempting to decode it from the group, which will only work for controls and windows.

Alternatively, `ViewScriptingRef::ScriptingClass()` could just return "View", but I don't know if there are other consequences with that; I'm not sure if something depends on the current behavior.

**Comment by MarcelHB** [comment]
Codewise, I hit that line in `OpenQuitMsgWindow`, when deciding for the save button state. I encountered in the game, can't remember right now if I the error was the same while in CharGen.

**Comment by bradallred** [comment]
It shouldn't have been in chargen. We don't create GC till we enter the game and we destroy it when we leave. If that isn't the case that means we are leaking refs.

Want to try changing the return value of `ViewScriptingRef::ScriptingClass()` and seeing if that breaks anything? I can't think of anything that would be using it so I assume it is currently a vestige of past development.

**Comment by MarcelHB** [comment]
Yep, works while in CG but no later.

You mean to return whatever hardcoded value? It's not breaking anything obvious then. *

(*) PST looks broken but for other reasons, will investigate.

**Comment by bradallred** [comment]
yes, I mean change this:

```
virtual const ScriptingClassId ScriptingClass() const {
	return ScriptingGroup().CString();
};
```
to this:

```
virtual const ScriptingClassId ScriptingClass() const {
	return "View";
};
```

**Comment by MarcelHB** [comment]
Looks good then.

**Comment by bradallred** [comment]
@MarcelHB were you putting together a pull request for this?

**Comment by MarcelHB** [comment]
If you want me to include your workaround like this, I can try this again tomorrow.

**Comment by bradallred** [comment]
I don't see any reason why that wouldn't be the correct thing to do. The current version is just a historical artifact from when there was only `ViewScriptingRef`.

**Comment by MarcelHB** [comment]
Urgh, I probably don't find enough time before christmas week.

**Comment by bradallred** [comment]
we are in no hurry; enjoy the holidays :)
