### ISSUE TITLE
[bug] IWD1 CharGen: Thieving skills not shown in overview window

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#436]
**Description**
Found this one by checking out #435, though it only affects IWD1, both with and without HoW installed. After distributing the thieving & weapon skill points, the overview in the chargen menu shows only 0% for thieving skills there:

![chargen_IWD1](https://user-images.githubusercontent.com/54738589/69867375-d70c4c80-12a6-11ea-9e2e-57a56853a58d.jpg)

**GemRB version**
0.86-git

**Comment by lynxlynxlynx** [comment]
Ah, this should be very easy to fix. I bet it's still using variables instead of stats, so it remains at 0.
