### ISSUE TITLE
[bug] PST: you still respawn if you die in the final fight

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#438]
From the wiki:

> nothing (dlg, script) seems to call SetNamelessDeath (which can disable that), so check if there's anything interesting in the area ini

only:
```
[nameless]
destare		= ar1200
point		= [4457.1256]
state		= 35
```

**Comment by lynxlynxlynx** [comment]
What happened in the original? @chilvence

**Comment by chilvence** [comment]
Nothing particularly exiting, first the UI is locked long enough for you to hear your own last words, eg "Don't let it end like this"

![dont let it end like this](https://user-images.githubusercontent.com/1923867/97575833-3e65db80-19e5-11eb-87bd-929b80ee8760.png)

Then this message: (48155)

![you died](https://user-images.githubusercontent.com/1923867/97575852-4756ad00-19e5-11eb-846a-714f6a6c8cfd.png)

Clicking "Done" starts the end credits

Offhand, I can't remember if GemRB implements all or indeed any of the game endings though - but if you are looking into the endgame, I could document and test them all.

**Comment by lynxlynxlynx** [comment]
Thanks! The others are scripted, so at least murder and self-destruct work already.

**Comment by lynxlynxlynx** [comment]
Didn't bother with waiting for the audio, but the rest works fine.
