### ISSUE TITLE
[bug] Djinni companion mod's djinni does not display its weapon slots

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#440]
We have an old report that [it](https://github.com/Argent77/DjinniCompanion/releases) doesn't display the 2nd quickweapon in the action bar properly ("no 2nd weapon displayed due to an unset value for qwslot2"). It has been confirmed in #428 this is still the case:

> the quickslots in fact don't work. On IE, if you summon the djinni, he has two weapon quickslots, in one he has a special enchanted scimitar, a basic unenchanted one in the other. On GemRB, both weapons do not show up in the quickslots. His avatar wields a weapon, just you can't switch them.

Since he's not a member of one of the playable races, perhaps he just needs a line in qslot2.2da (what's his class?). Or it may be a deeper problem.

**Comment by caillean7** [comment]
His class is the normal Fighter / Mage, so that's most likely isn't the problem.

**Comment by lynxlynxlynx** [comment]
What "MC Flags" do they have in the ctrl-m output?

**Comment by caillean7** [comment]
MC Flags: 0x400000 the djinni, 0x0 the animal companion.

**Comment by lynxlynxlynx** [comment]
Ok, so it's not 15, but:
> bit 22: Don't apply nightmare mode modifiers (BGEE)
aka irrelevant.

**Comment by lynxlynxlynx** [comment]
This fixed two issues: the two weapons not being displayed and only one being displayed. Loading a game restores a problem though, but that's part of #428 .
