### ISSUE TITLE
[feature] soa->tob not gifting all possible bags

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#442]
If you start tob, you get a bunch of gear, as per 25stweap.2da. But if you get there through soa, that is skipped and you get something else. Similarly for importing characters in character generation.

If it's a multiplayer game it's bag19, otherwise usually bag19a. But they go on to bag19e. It was supposed to be based on experience, so different xp/level chars need to be imported to see what sort of bag they get. In EE transitioning characters only get the amulet from Ellesime, so it's not the best testing bed.

Are bag19b-e unused or what?

**Comment by caillean7** [comment]
I tried importing parties and doing the transition to ToB the usual, in-game way, but both times my party didn't get a bag of holding at all, only the Amulet of the Seldarine.

So only starting a new game and importing your PC gives you the bag and some small amount of gold, both a previously exported SoA char and an imported from a saved game one.

Also, not only bag19* seem to be used for this ToB starting gear, e. g. on of my test cases started out with bag26. Not all of the equipment is in the Bag of Holding, some is loose in the inventory, even though the bag is not full. At first glance it looks rather complicated, however that list in the wiki looks right so far. That stuff would be hardcoded somewhere, right, perhaps MoveToExpansion takes care of this? I checked the involved scripts of this transition, also the area script of the spirit heads area, which takes care of any remaining drow equipment, so I guess there's no other way than really doing LOTS of tests?

**Comment by lynxlynxlynx** [comment]
bag26 and unbagged is from 25stweap.2da aka a fresh start, which we already handle. The rest is hardcoded.

So importing a game or transitioning is the same and you only get the amulet. Meaning the only thing to test more are character imports. You can try first with different classes, to see if that affects the bag. Then level/xp.

**Comment by caillean7** [comment]
Argh, it seems the game distinguishes between new chars and chars which have been already been played. So doing an ToB Import Game on a PC at the beginning stills gives you a bag. Maybe the game assesses party gold or the value of the equipment that char or the party is equipped with. And I got bag19, not bag19a, so bag 19 seems to be not only for multiplayer games. But the gold you get really seems to be for not imported games. Oh bloody hell, I want a cookie if I get this figured out. Or a whole BAG.

**Comment by lynxlynxlynx** [comment]
Like I stated two times already, it's supposed to be tied to xp. That could also unify the difference between importing a game and a character.

As for cookies, that could be arranged. :D

**Comment by caillean7** [comment]
> Like I stated two times already, it's supposed to be tied to xp

IknowIknow, still some of those test chars didn't get a bag, while the newly created and then imported ones do. Just want to make sure there's not something else affecting this.

> I tried importing parties and doing the transition to ToB the usual, in-game way, but both times my party didn't get a bag of holding at all, only the Amulet of the Seldarine.

So disregard this for now, it affected only one save game. I want to look into it some more. However, what I found for others is:

- More xp doesn't mean different bags. I tried raising xp level-wise, makes no difference. You'll always get bag19. However, the threshold is 2,499,999 xp. As soon as you hit ToB minimum starting xp (2,500,000), no more bag, only amulet.

- All classes get bag19. I didn't get bags19a to e at all.

**Comment by lynxlynxlynx** [comment]
CrevsDak tested this yesterday and said:
> ToB imported characters get bag19a in vanilla

It looks like b-e might truly be unused. But 19a is actually even hardcoded in the exe, so it must be for something. It's much poorer in content, but I doubt this is gold related.

**Comment by caillean7** [comment]
> Have you tried importing a tob-level char or one of the tob pregenerated ones?

I hadn't, but just did, and yes, that's seems to be what bag19a is for. The pre-generated tob chars get it, and also one I made with the 'Pre-generate character' function from the multi-player menu.

I just can't figure out how the game decides which SoA imported games get a bag and which don't.

**Comment by lynxlynxlynx** [comment]
Is there more variability than the 2.5M xp threshold you already found?

**Comment by caillean7** [comment]
Hm, yes, sorry if I'm a bit incoherent. It looks like this: a save game with a party that has already been played a bit imported in ToB means no bag. However, when I create a new SoA game and just import that, the PC gets a bag. I looked into party gold, equipment, game time, real time, and so far had no luck in figuring it out.

**Comment by lynxlynxlynx** [comment]
On a whim I installed a disassembler and checked the mentions of bag19. There doesn't seem to be any code for b-e, as '' and 'a' have pretty much the same follow-up.

![image](https://user-images.githubusercontent.com/121515/70078035-49ac5d80-1602-11ea-92f8-3b3234118538.png)
Not pictured, a comparison against 2.5M - x > 161000 (bg1 max?) and skipping the bags. There's a similar step there that's probably the amulet granting, but less obvious.

The core stuff is:
First it compares something against 1,750,000 and if it's not smaller, subtracts something (accounting for dualclass xp?) from 2.5M and rechecks. If that's still not small enough, it does another computation checking a flag and if the result is 1, that's the only way to get bag19a.

At least we got some confirmation about the other bags and two other constants that play a role and are likely also xp thresholds.

**Comment by caillean7** [comment]
Oh god, my brain is not wired to deal with this. Anything else that can be figured out with plain and simple testing, then?

**Comment by lynxlynxlynx** [comment]
Sure. You can try with a char with less than 1.75M xp. 
Also, it's not related to this bug, but you also get some xp right after (same limits apply) and it's not clear if dualclassed characters get the same or is their first class accounted for.

**Comment by lynxlynxlynx** [comment]
Oh, I forgot. Whatever you're testing, you can just check the global var XPGiven, which should contain the bonus xp.

**Comment by caillean7** [comment]
> You can try with a char with less than 1.75M xp.

That I already did earlier, starting with level 7 at the start of SoA and then adding more xp for another level, import into ToB again, did this for all levels up to the threshold, and they all got bag19. So not sure what 1.75M. is all about.

I'll took into dual classed chars then tomorrow, maybe also multi-class? Just keep the instructions nice and simple and don't forget the cookies :D

**Comment by lynxlynxlynx** [comment]
You know, it's an odd coincidence — I had thought about visiting Finland, since I have to go to Tallinn anyway, but it's again in January, so I doubt it is any less miserable. Sorry. :P

**Comment by MarcelHB** [comment]
Looking at the STO files, b to e are identical anyway.

**Comment by lynxlynxlynx** [comment]
I thought they might be for other party members, since they're almost void of unique items.

**Comment by caillean7** [comment]
> I thought they might be for other party members

Perhaps it was intended at one point, and they hadn't the time to implement it. You promise-breaker. I'm not in Finland anyway.

**Comment by lynxlynxlynx** [comment]
There's always mail, that perkeleen was all I was going from. :)

**Comment by caillean7** [comment]
Hm, I hope your baking matches those programming skills :smirk: About the XP Given at the start of ToB, I'd say for dualclassed chars the first class is decisive for the amount of XP. The second one doesn't seem to matter, not which class nor the time when the char was dualclassed. Or, if dualclassed at all. I got the same results every time. Just the base class seems to influence the amount of xp here - so you already have those numbers?

**Comment by lynxlynxlynx** [comment]
Yeah, we give the starting xp. Good to know they didn't bother with the mess that's dualclassed chars. The biggest unfairness is with disabled dualclasses (not reactivated yet). Let's say you dualclass just before beating Hell, then the transition would almost double your xp.

I asked Avenger for his ida data, so perhaps we'll get a more readable dump soon.

**Comment by bradallred** [comment]
> I asked Avenger for his ida data, so perhaps we'll get a more readable dump soon.

If you are looking for a free capable dissembler/reverse engineering tool have a look at [ghidra](https://github.com/NationalSecurityAgency/ghidra). Its Java so you can run it on Linux no prob. Of course I'll understand if you don't want to touch NSA software with a 10 meter pole.

**Comment by lynxlynxlynx** [comment]
There are several others and at least they have docs. None can decompile, but I won't bother checking it just for that. Without the annotations, it wouldn't be that big of an upgrade even if it worked well.

**Comment by bradallred** [comment]
You can import IDA annotations. I've never done it, but the tool itself is pretty stellar for reverse engineering and the disassembler is much better than any other I've ever used (never used IDA tho). I don't know what you mean about the lack of documentation.

**Comment by lynxlynxlynx** [comment]
Anyway, no response yet, but I tested a bit around the 4,5M border with disabled duals and fairness is ensured. Even ees are buggy here. Made me wonder if one could import bg1 games again.

Doesn't matter much, since we did resolve the most important questions.

**Comment by caillean7** [comment]
Okay, all baggy questions more or less answered then.
