### ISSUE TITLE
[bug] Nitpick: PST Dialogue: Click to close is only meant to appear when reviewing the history

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#445]
**Describe the bug**
Currently in regular dialogue, the click to close text appears, while the button cannot actually be used because there must be a dialogue response chosen instead.

GemRB version: 
any
**To Reproduce**
Talk to a party member or npc
**Expected behavior**
The button should appear blank until needed, either when reviewing the history or when the dialogue window is overflowing with text (click to continue/click for more in EE)

**Comment by chilvence** [comment]
This commit seems to be enough to blank out the button when not required

https://github.com/chilvence/gemrb/commit/d5d4174285c8907d55a7db354b806854aa89944d

I'm a bit confused about the workings of NextDialogState though. In common and IWD2, the intent seems to be to disable the button

``` 
def NextDialogState ():
	if not ContinueWindow:
		return

	ContinueWindow.GetControl(0).SetVisible(False)
	ContinueWindow.GetControl(0).SetDisabled(True)
```

in PST it's like this:

```
def NextDialogState ():
	if not MessageWindow.MWindow:
		return

	Button = MessageWindow.MWindow.GetControl (0)
	Button.SetEvent (IE_GUI_BUTTON_ON_PRESS, lambda: MessageWindow.MWindow.Close())
```

I can't think of a way to find a dialog to test this with, would it just be when a character goes off on an endless monologue with no actual dialog options?

**Comment by lynxlynxlynx** [comment]
The commit looks fine and the event is clearly not implemented yet (should be the overflow handler, but I don't think we need it).
