### ISSUE TITLE
[bug] Nitpick: PST Dialog-Usable items have incorrect 'use item' strings

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#446]
**Describe the bug**
Items that are attached to DLG files in order to use them wrongly display "talk to item" when it is actually only one or two that are labelled this way

GemRB version: any

**To Reproduce**
The easiest item to find is note from corpse #1201 on the zombie walking around in Dhall's chamber, you need the scalpel to retrieve it. 

**Expected behavior**
The original game shows the 'use' option in the inventory screen, GemRB shows 'Talk to item', like the Lim Lim. I think the 'conversible' bit is somehow used to choose which string to show.

**Comment by lynxlynxlynx** [comment]
Do you have the item resref?

**Comment by chilvence** [comment]
Some to compare: 

Items you 'talk' to: cube.itm  limlim.itm doll.itm

Items you use: porlens.itm n1201.itm bsphere.itm

I think it's all functionally identical, they are all dialogue starting items, it's just setup different because you can't 'talk' to a note and you don't just 'use' a pet lim lim . None of the items caused any particular gameplay issue last time I checked

**Comment by lynxlynxlynx** [comment]
Thanks. I've checked and you're correct — these examples differ by the conversable bit - IE_INV_ITEM_CONVERSIBLE. This is all handled in InventoryCommon.DisplayItem (python) and trivial to fix, since the data is already there. You can look at how IE_INV_ITEM_IDENTIFIED is looked up for an analogous example.

**Comment by chilvence** [comment]
I did have a fix before I think, but it is probably past being usable anymore. I wouldn't lose sleep over this anyway, I have a few more issues like this to add which are all really for version '1.0', but I have to post them before the old wiki page can be torched

**Comment by lynxlynxlynx** [comment]
An issue is an issue is an issue. Small and easy things like this are perfect for newcomers, so they have some extra added value.
