### ISSUE TITLE
[bug] PST: Running animation direction does not update with changes of movement direction

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#447]
The animation of Running characters is fixed to whatever direction they originally set off in, regardless of if they have to turn to run around obstacles

GemRB version: any

**To Reproduce**
Make a PC Run to anywhere where they have to avoid an obstacle like a table or NPC to watch them magically sidestep like a Doom 2 Sprite

**Expected behavior**
Characters in the game should not all be masters of the Moonwalk

**Comment by lynxlynxlynx** [comment]
To recheck after #106.

**Comment by kindaro** [comment]
Note that this problem is absent in _subviews_.

**Comment by lynxlynxlynx** [comment]
Not for me, I see the same issue there.

**Comment by kindaro** [comment]
[See screencast.](https://github.com/gemrb/gemrb/files/4463143/recording.mp4.gz) This is built from commit 268725892, current _subviews_.

**Comment by MarcelHB** [comment]
I have seen both cases, like _Oh, it's fixed?_ ... _Ah no, there it is again_. So there is probably some unseen factor in play.

**Comment by chilvence** [comment]
Sorry, I am a little bit slow on the response time for bugs I filed a while ago.

I reported this issue on my last full test playthrough of Torment, because it's something I only noticed when the characters were running. I see now I could have been a bit more explicit about that point.

I thought it might have just been a minor oversight, because PST is the wildcard of the whole bunch of infinity games, I have not observed this issue on any other game supported I assume that is because running doesn't even exist on them. 

Also in general since the primary focus is on BG/IWD 1 and 2 by nature, If ever I do find a bug that I think only applies to PST I usually try to shove a note of it somewhere hastily in case it gets overlooked.

It is also rather inconsequential as far as gameplay is concerned, and to be honest I have committed myself to use kmfrick's new pathfinder branch the next time I do a full playthrough, which may even be able to completely sidestep this particular issue. No pun intended. I would much rather that fork be absorbed first before fixing this minor annoyance :)

**Comment by lynxlynxlynx** [comment]
The PR is ready for testing, yes. Now with npc bumping, so it's feature complete. <3

**Comment by chilvence** [comment]
Wait... are you sure it isn't Christmas ?

I had plans tomorrow, but they are no longer important anymore :)

**Comment by chilvence** [comment]
Apparently I made a 2 month detour to get here, but, can confirm that this can be closed with #126, no more moonwalking with the new pathfinder
