### ISSUE TITLE
[bug] nitpick: PST Blood displayed at actors feet instead of mid body

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#448]
**Describe the bug**
Gemrb doesn't offset the blood sprite, so all the combat hits make blood appear on the floor, making combat look a bit awkward. I also noticed there is some blending in the original, not in gemrb

GemRB version: any

**To Reproduce**
Attack anyone

**Expected behavior**

**Screenshots**

![grb_blood](https://user-images.githubusercontent.com/1923867/70060293-279ee500-15da-11ea-8c44-59b162606391.png)
![pst_blood](https://user-images.githubusercontent.com/1923867/70060295-279ee500-15da-11ea-8272-fd9c1583254f.png)

**Comment by lynxlynxlynx** [comment]
Black should be transparent; maybe these require similar flag bit changes as the area animations did.

**Comment by lynxlynxlynx** [comment]
This was actually a problem everywhere, just the blending one was pst specific.
