### ISSUE TITLE
[bug] nitpick: PC race is misreported on the record sheet

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#449]
**Describe the bug**
Instead of the character race being printed above the class on the record sheet, all characters just display an asterisk. I believe this is unresolved because Morte throws a spanner in it because he is human according to the data files, but 'Morte' is what is actually reported to the player, so that field was probably a special case in the original interface code , if anything maybe the EE menu interface might have a clue about how this was originally decided?

GemRB version: any

**Comment by lynxlynxlynx** [comment]
So PC and Morte currently display an asterisk instead of their race. Morte is indeed a troublemaker, but we should just match the display of the original. As stupid as the implementation has to be.

This is all done in gemrb/GUIScripts/pst/GUIREC.py.

**Comment by chilvence** [comment]
This issue has apparently been already fixed. I must have loaded up an older version of Gemrb when I checked this one, sorry about that.

**Comment by lynxlynxlynx** [comment]
Hmm, indeed, new game is fine.
