### ISSUE TITLE
[feature] for 1:1 feature parity: implement shift+click to run to target in PST

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#450]
**Description**
If in the original version you had 'always run' off, but wanted to run away from a single situation, you could shift+click on an area of the map to give the character a run order

**Additional context**
I think the feature is also reversed, so if you have always run on, shift+click sends a walk order

I am in no way suggesting this is important, it is just one of the little noticeable differences between GRB and the original game

**Comment by lynxlynxlynx** [comment]
We also expose it as a double click, but yeah, the original also had this input combo.

**Comment by bradallred** [comment]
the problem is we use shift + click as a waypoint system. we cant do both things.

we can fix not walking when double clicking when always run is on tho

**Comment by chilvence** [comment]
I'd prefer sticking with the waypoint shortcut if it comes down to choice. I only really noted this because I was side by side testing at the time and the difference was obvious. Maybe it could alt+click, or something else?

**Comment by lynxlynxlynx** [comment]
PST didn't have waypoints? BG1 did, so that'd be quite interesting.

**Comment by chilvence** [comment]
Looks like the shortcut is CTRL instead, but it does have them

**Comment by lynxlynxlynx** [comment]
This is something keymap.ini doesn't handle (no mod keys), so we have to do it on our own. Should be an easy translation before the handler jumps in its switch table.
