### ISSUE TITLE
[feature] for 1:1 feature parity, PST interface stays visible during cutscenes

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#451]
**Description**
This is another minor difference between the original game and gemrb, cutscene mode does not actually hide the interface in the original game, it only disables it. This is visible at the very start of the game.

![cutscene](https://user-images.githubusercontent.com/1923867/70065652-5e2d2d80-15e3-11ea-8486-e800b41d5816.png)

However it is arguably better the way it is in Gemrb. None of the scripted cutscenes were worse for not having the interface in the way, I am only reporting it for OCD level exactness

**Comment by lynxlynxlynx** [comment]
I don't have my laptop handy, but this may have been changed already in the subviews branch.

**Comment by bradallred** [comment]
I'm not sure. that branch hides any window in the group 'HIDE_CUT'. Looking at pst/MessageWindow.py those windows don't seem to appear in that group, so yes they should be visible still.

However, I'm guessing they would not be disabled unless cut scenes also enable dialog mode. We would likely need to have cutscenes also toggle dialog mode or add `ToggleViewsEnabled(!(game->ControlStatus & CS_HIDEGUI), "NOT_DLG");`  at the same place we do `ToggleViewsVisible(!(game->ControlStatus & CS_HIDEGUI), "HIDE_CUT");`

**Comment by lynxlynxlynx** [comment]
Cutscenes should definitely not enable dialog mode, but good to know.

**Comment by chilvence** [comment]
Closing this because Subviews branch copies original behaviour
