### ISSUE TITLE
[bug] PST: d300mer8.dlg can break the game

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#456]
**Describe the bug**
If the player talks to Meiram at length about her seeing him before in a previous life, and if the player gives her some copper for her time, she changes to offer different dialogues to reflect the 'good' reaction. 

One of those dialogue actions tied to Mebbeth's quest to make you a mage has a stray semicolon which causes GemRB not to execute it, 

```
[GameScript/ERROR]: Invalid scripting action: ;SetGlobal("Mebbeth_Quest","GLOBAL",10)
[DLGImporter/WARNING]: Can't compile action: ;SetGlobal("Mebbeth_Quest","GLOBAL",10)
```

GemRB version: any

**To Reproduce**
Follow the mage quest from Mebbeth up the point of finding the ink. BEFORE doing this part, make sure to talk to Meiram, try to see what she is looking at, ask her if she has seen you before etc, then give her 10cp. Now you will be unable to complete the mage quest because you will only be given the un-parseble dialogue option.

This save is made at the appropriate moment: https://filebin.net/by05fxp183lvihgi 
(Khossa jai is directly in front of TNO and tells you where to get the ink, Meiram is on the southeast street, and the lady to get the tanker from hangs around the middle of the market

**Expected behavior**
Black Isle should watch out for typos.

**Comment by lynxlynxlynx** [comment]
The save expired. Does this solve it?
http://sprunge.us/mwwWvm?diff

**Comment by chilvence** [comment]
Sorry about that, somehow I never realised github lets you post all sorts of files in the comments.

Unfortunately, that just crashes the game for me, 

`[GameScript/ERROR]: Invalid scripting action: ;SetGlobal("Mebbeth_Quest","GLOBAL",10)
free(): invalid pointer
Aborted (core dumped)
`
This save is right up to the last moment before the errant dialog state is chosen

[000000189-PST - Got tankard done good.zip](https://github.com/gemrb/gemrb/files/3973194/000000189-PST.-.Got.tankard.done.good.zip)
