### ISSUE TITLE
[bug] PST: Unknown problem with resource loader 

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#457]
[000000165-I am a Mage.zip](https://github.com/gemrb/gemrb/files/3928107/000000165-I.am.a.Mage.zip)

After loading this save, as soon as you exit the house, the resource loader goes crazy. I am so far not able to diagnose what went wrong, and I am not sure when either.

[GemRB.log](https://github.com/gemrb/gemrb/files/3928164/GemRB.log)

**Comment by bradallred** [comment]
Uh, log?

Without anything to go on i'm going to guess that it cant find some animation. I think we have a setting for case sensitive filesystem... or something.

**Comment by chilvence** [comment]
I have attached the log, sorry that would have been informative ....

**Comment by bradallred** [comment]
yikes... that is scary. It looks like possible memory corruption.

**Comment by lynxlynxlynx** [comment]
I'll look into it, we were just discussing it on discord.

**Comment by lynxlynxlynx** [comment]
Yep, same bcs spillage, quite bizarre. Valgrind reports a font problem several times, but it's all earlier and all look like red herrings for this.

**Comment by chilvence** [comment]
Just because there was probably too much hair left on my head or something, this other save where I restarted causes me no issue on my linux build, but gives errors on my windows gemrb setup (appveyor version, latest commit) 

[000000168-i really am  a mage.zip](https://github.com/gemrb/gemrb/files/3928193/000000168-i.really.am.a.mage.zip)

**Comment by lynxlynxlynx** [comment]
ar0101.are in the save is corrupted, there's nothing we can do.

**Comment by chilvence** [comment]
I just wonder, how did it get corrupted. I tried dozens of different windows builds, I seem to be able to load that other save if I use one before f7ff2d2 , but I can't be sure which commit because I can't actually build on windows

**Comment by lynxlynxlynx** [comment]
Unless you can reproduce the broken file (you said it worked in a new game), there's nothing to be done. It's not related to loading, the save is just broken, so the saving is where the bork got finalized.
