### ISSUE TITLE
[bug] PST: Globe of Invulnerability has a duration of just 3 / different timing mode meaning

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#458]
That's barely half a round. It seems instant/limited timing mode needs to be interpreted differently in pst? Should the duration be in rounds, not seconds?

The description: "Duration: 5 seconds per level", but then the effects have 3 or 4 set and there's only one extended header in spwi602. Traditionally descriptions can't be trusted anyway, but it would be a good test to try mages of different level in the original and see if this one holds any merit.

Timing modes "delayed" and "delayed duration" also show problems ...

**Comment by chilvence** [comment]
I have noticed when I was digging through the spell data that a lot of spells that I believe are intended to be 'instant' in game are reported by ni as 'delay/limited' , so I believe that those values must have been interpreted completely differently by Torment.exe

I also find that in contrast to bg1/2 where you expect to find a ton of seperate spell abilities per level, that most of them only have 1 ability.  I can only imagine that there must have been something at code level that read these spl files, checked the caster level and then overrode their duration values or something, because otherwise pretty much every spell description would be all lies...

I will try to do stopwatch tests in the retail game as I level up

**Comment by lynxlynxlynx** [comment]
I almost accidentally found that this spell of ours actually uses iwd2-style simplified duration, which is per level. Something just goes wrong, so this will again likely fix more spells.

**Comment by lynxlynxlynx** [comment]
Ok, so the spell contains the immunity opcodes + glow, our projectile then applies also some other stuff. This second half now works (after I push), but the crucial immunity stuff doesn't — still uses the untouched timing.

Some ideas:
- copy the payload into our projectile spell (in this case the effects are not additive, so no problem); gemrb/unhardcoded/pst/goinvul.spl
- look harder if there's anything in the spell, extended/ability header or effects that could mark the need for special treatment; if this would be true, it'd be ideal, since it can then help with other spells. I think it's unlikely though

**Comment by chilvence** [comment]
Is there any way of dumping all the spells and their headers out to a text file? Could iesh possibly do that? I've been thinking that if there are any as yet unknown patterns in the data, the only way to spot them would be to line up everything in a big overview table of some sort.

I'm still mostly convinced the 'missing' spell durations were calculated on the fly, eg in the internal projectile code. If it is the case, then your first option there seems to make the most sense. Then the spells would work just like the other games in practice, wouldn't they?

**Comment by chilvence** [comment]
I'd be totally happy to do that by the way, now that you've solved the deep seated timing issue, I'll actually be able to see which spells need fixing while I'm playing the game now, it will just be any that still don't have the desired result.

**Comment by lynxlynxlynx** [comment]
Yeah, it was all hardcoded. The first option is the simplest and while not that friendly for modding, it's not *that* bad either, since they can just rerun the same weidu code on our spell. And not like anyone is touching pst any way.

Looking for markers is hard, because they might be in untagged areas, so dumps can be misleading. Or there might be weird reuse. ... Yeah, let's KISS and solve it the straightforward way. NI actually supports copying of effects, so you can try fixing GOI yourself.

Then it would be good to get a new list of spells with the same problem (best to check ctrl-m after casting and later vs what's in the data). Maybe it's worth adding another bit to the projectile code, since I think it might not be too late on first load to autocopy the other effects or change their duration.

**Comment by lynxlynxlynx** [comment]
Coming back to this, blur is the simplest test case, since it has no custom projectile. PST:EE just used the usual spell ability spam to scale its duration. So it must have been something nasty before. We already have some of this in fx_overlay, but GoI and blur don't use it. Currently I'm mapping the spells and you even have one gem (Adder's kiss) that claims to scale duration per 3 levels.

I was thinking of another table for these overrides, but it could get tricky, since iwd2 simplified duration assumes only one extended header and some of these spells use several to scale their range (if that even works considering sight limits — check if we can ignore this). And the onset delays probably shouldn't be touched, so the current filtering for SF_SIMPLIFIED_DURATION wouldn't cut it alone.
