### ISSUE TITLE
Are all actor overlays displayed properly for invisible enemies?

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#461]
> Which overlays are hidden for invisible enemies? Current lore says bg1-style hardcoded ones (globe of invulnerability, protection from missiles, sanctuary), while bg2 ones aren't (turning). GemRB holds a list of all the hardcoded overlays in gemrb/unhardcoded/*/overlay.2da and the last column tells the engine whether the overlay should be hidden (1) or not if the enemy is invisible. Most of the values default to 0, but the correct values need to be found.

**Comment by caillean7** [comment]
Is it a viable test to open up some weak enemy in NI, add a permanent invisibility effect to it, plus some other effect, start up IE, console in a copy of the creature and see if the spell effects are visible? I tried that with a handful of effects, and in BG2 none of them showed so far. Also, concerning overlay.2da, we're talking about the FLAGS column, which is currently empty, or the UNDER column?

**Comment by lynxlynxlynx** [comment]
It's the last column, yes (but it's not empty).

the testing plan sounds fine — the question is whether gemrb behaves the same as the original.

**Comment by caillean7** [comment]
Uh, then the column heads are misaligned maybe.

Cool, then I'd make this my next job, unless you'd prefer me doing something else? If I gotta check all the games, then it might take a bit - don't have so much free time like last year anymore, but a week or two should be okay?

**Comment by lynxlynxlynx** [comment]
Looking at bg2 is enough and there's no rush at all. :)

**Comment by lynxlynxlynx** [comment]
Other entries can stay.

How are you adding the effect? Not by an item, equipping effect, right?

**Comment by caillean7** [comment]
No, not by item.

**Comment by lynxlynxlynx** [comment]
Which timing mode did you use?

**Comment by caillean7** [comment]
Instant / Permanent.

**Comment by lynxlynxlynx** [comment]
Hmpf, everything looks fine with fx_cure_invisible_state and what it calls. And it has to work or they wouldn't appear, so it's like the actual effect removal line doesn't do it, but I can't see how that'd be possible (`fxqueue.RemoveAllEffects`). Can you try breaking on it and stepping through? The loop in the next function should set the effect to expired.

**Comment by caillean7** [comment]
In which file is this?

**Comment by lynxlynxlynx** [comment]
FXOpcodes.cpp, but it doesn't matter, just: `b fx_cure_invisible_state`

**Comment by caillean7** [comment]
Uh, bear with me... in the console?

**Comment by caillean7** [comment]
Ah, okay, sorry for being daft.

So what's supposed to happen when it hits that breaking point? Right now, nothing happens, the game just keeps running.

**Comment by lynxlynxlynx** [comment]
you're supposed to next until the RemoveAllEffects line then step there, which will take you to a different file. Just next there until exit and note if any effect got their timing changed — since it appears that it's somehow getting skipped.

**Comment by caillean7** [comment]
I'm not familiar with gdb, but I think my problem is that the breaking point doesn't work.

**Comment by lynxlynxlynx** [comment]
Hmm, tell me everything you type after gdb starts.

**Comment by caillean7** [comment]
```
break fx_cure_invisible_state
r
```

That should stop execution when this function is called and give me the gdb prompt, right?

**Comment by lynxlynxlynx** [comment]
Actually no, since the plugin is loaded later — you probably get a warning about that breakpoint.
Try r for gemrb to start up, then ctrl-c in the console to get back to gdb, and then the break and then c to continue.

**Comment by caillean7** [comment]
No change, still doesn't 'break'.

**Comment by lynxlynxlynx** [comment]
It doesn't break when the skelly goes visible again?

**Comment by caillean7** [comment]
Nope.

**Comment by lynxlynxlynx** [comment]
how about "b Actor::ResetState"?

**Comment by caillean7** [comment]
Sorry, had to go...

No breaking with this, either. Did the running, Ctrl.+C, then b, then c. Said:

```
Function "Actor::ResetState" not defined.                                                   
Make breakpoint pending on future shared library load? (y or [n])
```

Tried with yes and no.

**Comment by lynxlynxlynx** [comment]
how about "b GemRB::Actor::ResetState"?

**Comment by caillean7** [comment]
Some progress:

```
(gdb) next                                                                                  
Single stepping until exit from function _ZN5GemRB5Actor10ResetStateEv@plt,                 
which has no line number information.                                                       
0x00007ffff7a93470 in ?? ()                                                                 
   from /home/nadia/Software/Games/gemrb2020_1_20/build/gemrb/core/libgemrb_core.so.0.8.6-git                                                                                           
(gdb) n                                                                                     
Cannot find bounds of current function  
```

**Comment by lynxlynxlynx** [comment]
Ah, it looks like you don't have a debug build — you'd have to rerun cmake with -DCMAKE_BUILD_TYPE=Debug for all the symbols to get included and being able to use gdb for anything helpful.

**Comment by caillean7** [comment]
KK, I'll do that tomorrow afternoon, repeat above steps and post any progress (hopefully!) then.

**Comment by bradallred** [comment]
FYI, you can do `b File:Line` so you don't have to remember all the namespacing.

Actor.cpp is part of the core, so breakpoints inside it shouldn't generate warnings anyway 🤷‍♂

**Comment by lynxlynxlynx** [comment]
Actually for me the namespacing isn't needed any more. Either gdb improved or the dwarf info from the compiler is better.

**Comment by caillean7** [comment]
Tried with the debug build, but I'm still getting this "Cannot find bounds of current function" with it.

**Comment by lynxlynxlynx** [comment]
Eh, please just upload the modified CRE then.

**Comment by caillean7** [comment]
Ah, sorry about that.

SKELET01.cre has currently Minor Globe Overlay and Invisibility active:

[skelet01.zip](https://github.com/gemrb/gemrb/files/4091873/skelet01.zip)

**Comment by lynxlynxlynx** [comment]
When I try it, once they attack they only have the overlay effect in their queue.

**Comment by caillean7** [comment]
Here, too, same on the original. I thought that was due to the attack dispelling invisibility.

I checked all BG2 overlays now, and everyone I was able to test didn't show while invisibility was active, so I'd assume the same value for the others (additional ones mentioned above) and just set all the flags to 1. Also sampled some on IWD1 to see how it looks there: the same. So can we just assume 'Invisibility = no overlays drawn' for all games? Then I could go over the 2da's tomorrow.

**Comment by lynxlynxlynx** [comment]
Haha, what a misunderstanding! I thought you were saying the invisibility effect is still in the queue, but you meant the overlay one.

re flags: it's also true for spell turning? Interesting. Which weren't you able to test?
Maybe I played it too many times in gemrb, but I thought some of the protections from the lich contingency remained visible, while they go invisible through mislead or projected image.

Since it appears then they're always hidden, it's better to rework 942c1a16 than to set the flags in the table. It could likely be just partially reverted, but let's first see if we need the flags col for anything else — like the sound issue still open.

**Comment by caillean7** [comment]
Some that BG2 doesn't have at all, like e. g. Death Armor, Flame Shroud, Seven Eyes, and a few I couldn't find in NIs drop-down list, where you select the effects. E. g. Insect Plague or Globe of Invulnerability (might use the Minor Globe overlay instead?).

I'll start up the IE and pay a visit to some liches then.

**Comment by caillean7** [comment]
Side note, before I forget: On IWD1 it looks as if the overlays are drawn just slightly too low compared to the original:

GemRB:
![overlay_gemrb](https://user-images.githubusercontent.com/54738589/72890169-9f071000-3d11-11ea-94fd-e687e31c5764.jpg)

IE:
![overlay_ie](https://user-images.githubusercontent.com/54738589/72890189-a9c1a500-3d11-11ea-95ee-200a41fcee1c.jpg)

Probably not so noticeable for human or elves, but this armored skeleton is somewhat bigger. Just caught my eye with this one yesterday, so we might take a look at some other of the overlays too.

**Comment by caillean7** [comment]
> I thought some of the protections from the lich contingency remained visible, while they go invisible through mislead or projected image

Sorry about the delay, you're right here. Spell turning and spell deflection overlays are indeed drawn for the lich's mislead:

![lich](https://user-images.githubusercontent.com/54738589/73120674-74b38d80-3f71-11ea-9a37-838d1cc47a3a.jpg)

I wanted to test them with my skeleton, too, but strangely they aren't drawn if I just add the effect with NI. Even when I removed the invisibility, it drew no overlay for both 200 and 201 opcodes.

**Comment by lynxlynxlynx** [comment]
So, they're drawn on the actual actor, not the mislead illusion, which is good. 

Too bad our testing approach isn't bulletproof. Maybe just illusions are special, but can you try testing turning and deflection via a script? ForceSpell them and invisibility ...

**Comment by caillean7** [comment]
Yep, I'll get to it on Monday.

**Comment by caillean7** [comment]
Testing with a combat script showed that Spell Turning and Spell Deflection do show while Invisibility is active. I then tried with some other spells previously tested with the other method, and results were consistent with the previous ones. So looks like Spell Turning and Deflection are somewhat special, since they're drawn for invisible actors; so far everything else I tested was not.

Are there any other spells I could test while I'm at it, something not in overlay.2da maybe? Right now nothing comes to my mind...

**Comment by lynxlynxlynx** [comment]
Thanks, so then is this it? http://sprunge.us/c9o2Cu?diff

**Comment by caillean7** [comment]
Yep, looks good.

**Comment by lynxlynxlynx** [comment]
Since most other games don't have anything like that, I'll just suppose they don't display anything and transpose the changes.

**Comment by caillean7** [comment]
I could take a look at IWD1 - gotta test the overlays for #623 anyway, and I'll do it with a script, it's much quicker than adding effects to the creature. Could use the same like for this test, some spell plus invisibility.

**Comment by lynxlynxlynx** [comment]
Sure, better coverage is always good, but iwd doesn't have turning or deflection, so I don't expect deviations.

**Comment by caillean7** [comment]
Checked out Invisibility along with the overlays for IWD1 now, and everything except for Insect Plague was invisible on the original. However, testing them on GemRB showed the opposite behavior - looks like HOWs overlay.2da is missing from https://github.com/gemrb/gemrb/commit/f9de9f23203c78838a675825f63afdeb68847a2c

**Comment by lynxlynxlynx** [comment]
Nice catch! Are you sure you didn't misplace a file into our override or something like that? Check the log to see where it found overlay.2da, just to rule that out.

**Comment by caillean7** [comment]
According to GemRB.log, it's using the correctly modified file from the override folder, as intended. But yeah, since I made a mess a few times, I made fresh testing installations for all the games and archived override folders, so I can restore them before starting with testing new issues.

**Comment by lynxlynxlynx** [comment]
Hmm ... Please just make that pull request and I'll look at what's so special. That script snippet would also help.

**Comment by caillean7** [comment]
[test_overlay.zip](https://github.com/gemrb/gemrb/files/4204745/test_overlay.zip)

That zip has all the files I'm using. Since IWDs have no CreateCreature command, there's a save in Winter's Cradle tavern, and Easthaven's  area script will create a test skeleton with permanent invisibility directly in front of the building. Test.bcs is the script for that skelly where you can change the spell effects is has on.

Another weird thing I noticed: When loading this save on the original, the char (one of the pre-grenerated character file the game comes with) looks like this:
![cleric_IE](https://user-images.githubusercontent.com/54738589/74538430-7fdc5680-4f3c-11ea-9e95-fd0b142bdb71.jpg)

See the glowy effect on the flail and the horned helmet. Same installation and save on GemRB:
![cleric_GemRB](https://user-images.githubusercontent.com/54738589/74538474-9bdff800-4f3c-11ea-8025-2df24f11ddaa.jpg)

Armor and shield look slightly different, too.
