### ISSUE TITLE
Check if anything used the AlchemyModifier effect

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#462]
Another brief wiki research note:

> IE_ALCHEMY is unused. Check iwds if anything used 0x3D AlchemyModifier (it crashed in bgs).

Search for it with your favourite game file editor; both NearInfinity and DLTCEP would do.

**Comment by caillean7** [comment]
I did extended searches in NI for this opcode, turned up no uses for IWD1 HoW / TotLM, but it is used in IWD2.

Items:
![screen1](https://user-images.githubusercontent.com/54738589/71523981-bd711b80-28cb-11ea-97aa-2b658c6118d7.jpg)

Spells:
![screen2](https://user-images.githubusercontent.com/54738589/71523998-cd88fb00-28cb-11ea-80b4-e869d9ed22c0.jpg)

**Comment by lynxlynxlynx** [comment]
Thanks. It will be used practically once #478 is done. The opcode already works.
