### ISSUE TITLE
[bug] Cloak of mirroring vfx not applied

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#464]
**Describe the bug**
Cloak of mirroring is supposed to encompass the wearer in a spherical field as seen [here](http://www.shsforums.net/files/file/1130-improved-cloak-visual-sound-effects/).

GemRB version: any

**Comment by lynxlynxlynx** [comment]
This is removed by the fixpack or maybe tweakpack, since it's so annoying. Do you have any of that installed?

**Comment by bradallred** [comment]
nope.

**Comment by caillean7** [comment]
This affects also the 6th level wizard spell Spell Deflection (SPWI618), it seems to use the same hideous animation:
![spll_dflct](https://user-images.githubusercontent.com/54738589/70551588-16c11700-1b78-11ea-8e65-b97239e6cc11.jpg)
That's on the original, no animation at all on GemRB.

**Comment by lynxlynxlynx** [comment]
The spell uses opcode 201 (fx_protection_spelllevel_dec), while the cloak (clck26) 205 and 206. I suspect it's that single 205 (fx_protection_secondary_type) that's the second cause for the sphere.

**Comment by caillean7** [comment]
Separate issue?

**Comment by lynxlynxlynx** [comment]
Nah, it's practically the same code.

**Comment by lynxlynxlynx** [comment]
This works already, checked with the aforementioned Spell Deflection (SPWI618).
