### ISSUE TITLE
[bug] buggy character animations

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#466]
You should see a flood in the console when it happens. Maybe a stance is missing, there's some improper orientation handling, some files don't have all the data or it's a different layout that needs a new animation type.

bg1:
- [x]  can't reproduce: ~Viconia(?) animation problem [CharAnimations/ERROR]: Couldn't create animationfactory: cefc4 (6011) [ResourceManager/ERROR]: Couldn't find 'cefc4.bam'.~
- [x] Couldn't create animationfactory: chft1 (6310) <-- imoen, can be hit in Candlekeep if you approach the inner courtyard from the SE

bg2:
- [x] Couldn't create animationfactory: chfw1 (6210) <-- hit with Nalia if entering the CC from the top entrance
- [x] Couldn't create animationfactory: cemt2 (6301) <-- bridge district mugger
- [x] Couldn't create animationfactory: chfb1 (6010) and chmb1 (6000) <-- bard troupe in five flagoons after finishing their play
- [x] #1682
- [x] [CharAnimations]: Couldn't create animationfactory: udrz1a2e
- [x] [CharAnimations]: Couldn't load animation: meaeg26, cycle 56 (eg. from druid or mage polymorph #867)
- [x] Couldn't load animation: usar1g1e, cycle 69 (in Saradush, bg1 Sarevok)

iwd1:
- [x] Couldn't create animationfactory: mor1 (e810) <-- orcs in ar1201
- [x]  Couldn't create animationfactory: myu2ca . This one has more files than usual and ca1-ca4 instead of just ca (similar with some other types).
- [x]  Couldn't create animationfactory: mbaitw (e7a0) <- should use sl instead of tw
- [x]  Couldn't create animationfactory: mbaica (e7a0) <- sd(?) instead of ca
- [x]  Couldn't create animationfactory: myetca (e760) <- uses winter wolf script with ForceSpell, but lacks CA
- [x] Couldn't create animationfactory: man2a4 (eb20)
- [x] Couldn't create animationfactory: mcrda2 (ea20) <-- only a1 available
- [x] Couldn't create animationfactory: myu3a2e (e8a0) <-- only a1 available

iwd2:
- [x] Couldn't create animationfactory: msh1e (e908) (shadows in ar4102)
- [x] Couldn't create animationfactory: mba1ca (f77a) (barbie warrior: 01_postulant_16)
- [x] Couldn't create animationfactory: mrem (e050) (remorrhaz, ar4100)
- [x] Couldn't create animationfactory: mtsne (e738) (snow troll, ar4100)
- [x] 0x6405 (doom guards, ar4100) go invisible once they start attacking
- [x] Couldn't create animationfactory: mgo2a2e (e412)

pst:
- [x] 0xE041: Couldn't create animationfactory: cstctrzb (0041) [Couldn't find 'cstctrzb.bam'.] this is the end boss

There was also a report for both bg1/bg2 original (animation ID 0x6404) Sarevok, but I couldn't reproduce. Just noting if anyone hits it again.

Latest NearInfinity has a great animation viewer, so figuring out what does what and which stances are available should now be much easier:
http://www.shsforums.net/topic/45358-nearinfinity/page-52#entry610929

**Comment by lynxlynxlynx** [comment]
!!! Just found out we have stances.2da / gemrb/docs/en/Tables/stances.txt, which can probably be used to plug many of these baddies without introducing new animation types.

**Comment by FrElvire** [comment]
In iwd1, it seems creeping doom miss some animation too.

ResourceManager/ERROR]: Couldn't find 'mcrda2.bam'.
[CharAnimations/ERROR]: Couldn't create animationfactory: mcrda2 (ea20)

![CreepingDoom_anim](https://user-images.githubusercontent.com/55502325/98462069-9228af80-21b1-11eb-83cc-dca84989ff86.png)

**Comment by FrElvire** [comment]
In IWD1 too, same thing with yuan-ti priest : 
![yuan-ti priest_ouput](https://user-images.githubusercontent.com/55502325/98468470-e005dd80-21da-11eb-873c-ff7e738ac3e8.png)
![yuan-ti priest](https://user-images.githubusercontent.com/55502325/98468473-e3996480-21da-11eb-8db2-1a5768a4b407.png)

**Comment by lynxlynxlynx** [comment]
Besides the latest NearInfinity having a great animation viewer, IESDP is now gettiing a detailed account of the pst-like animation ini files used in the EEs. Plus the games basically ship this unhardcoded info for all animations (for all games, even iwd2 IIRC), so finding proper cycles and frame offsets is much easier now, especially for bg2.

https://github.com/Gibberlings3/iesdp/pull/119
