### ISSUE TITLE
[bug] iwd: are we handling actor names properly?

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#467]
Actors have two names, a short (generic) and a long one. In BG we use TalkCount, so the first time the short name is used and later the long name. However this is supposedly not true in iwd.

Needs testing and a comparison. ar9708 of totl also shows a problem with this. Elisia in SW corner of Easthaven or Jhonen over the lake near Hrothgar's house were old test subjects too. And Hobart in the Whistling Gallows Inn.

See [this thread](https://www.gibberlings3.net/forums/topic/17580-creature-flags/) for the actual logic — seemingly only depends on the first bit (MC_SHOWLONGNAME), but maybe not in other games. Aaaargh

**Comment by lynxlynxlynx** [comment]
@caillean7 and another one:
0. Check if the above test cases already match.
1. Find or make an actor with a different short and long name.
2. See if before talking to him for the first and second time displays a different name in the tooltip.
3. Check if that bit 1 can be used to force one or the other behaviour.

**Comment by caillean7** [comment]
On the original talking to an actor with different long and short name doesn't change the tooltip. Setting the 'identified' bit doesn't change that. Tested with Jhonen and Hildreth Highhammer. The only creatures in my TotLM installation that have that bit set are all sorts of spiders, ghasts and carrion crawlers, not a single NPC. So if that bit actually does anything, it has nothing to do with the tooltip. Perhaps it was planned to implement it and then was abandoned.

**Comment by lynxlynxlynx** [comment]
Are you saying the long name is always used?

**Comment by caillean7** [comment]
No, according to IESDP shortname is the tooltip. On IE the tooltip always shows the short name - e. g. Hildreth's shortname is 'Dwarf' and that's what the tooltip always shows, no matter if you talked to him or not or even if he has that bit set. It works different on GemRB, though. I hope you won't change it? It's feels like an improvement that if you talked to somebody and know who they are, it would be reflected in the tooltip.

**Comment by lynxlynxlynx** [comment]
So I guess the long one was just for dialogs. You're right, this is silly to replicate.
