### ISSUE TITLE
[bug] ar0512 watery woes

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#470]
ar0512 Temple of Helm has two big semitransparent blue rects over the holy water
  *  in the original, only the water transparency was off: https://www.gibberlings3.net/gallery/image/464-helm-temple-graphics-fix/
  *  the fixpack fixes it (above), but makes us render some overlays too

Recheck if this is still relevant and if anything needs to be fixed. Assume the fixpack is installed.

**Comment by caillean7** [comment]
Looks good:
![holy_water](https://user-images.githubusercontent.com/54738589/70457448-76ec8600-1ab0-11ea-8119-02506731cbad.jpg)

**Comment by lynxlynxlynx** [comment]
:+1:
