### ISSUE TITLE
[feature] iwd2: Tyrant's dictum

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#475]
How was “Tyrant's dictum” done? 

It's a cleric of Bane superpower: all saves versus their Will spells are at +1DC. Did it really work? `EnableRollFeedback = 1` under program options in (gem-)icewind.ini would perhaps help if the default saving throw feedback is not detailed enough.

If it did work, that probably means it was for all spells needing will saves, so we could probably reuse (with another case/mode) the opcode for aura of courage #474 .

**Comment by Bubb13** [comment]
After some digging through the IWD2 engine, I can confirm that Tyrant's dictum works. It retroactively increments the effect's save penalty when it is being applied in the event that:

1) The effect uses a will save.
2) The effect source was a Cleric with the CLERIC_BANE kit.
3) **The spell was cast from the Domain pool.** Regular cleric casts do not receive the bonus.

**Comment by lynxlynxlynx** [comment]
Thanks, so it sucked even more.
