### ISSUE TITLE
[bug] BG2 'Badspells' - Issue with Spook / Horror

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#480]
See #465

**Description**

> spooking a friendly summon has no panic effect (only the string is displayed)

This seems to affect not only summons, but also enemies. If Spook or Horror is successfully cast, the string is displayed and the Ctrl.+M dump shows the correct effect. However, the circle is not changed to yellow, and the target doesn't show panic behaviour / running. It will either just stand there passively or attack the caster. I also tried casting Symbol of Fear on a bunch of goblins, with no success. It looks as if fear / panic in general is somehow broken...

**Comment by lynxlynxlynx** [comment]
Two more things to keep in mind. This old note, perhaps fixed by #110 :

> buggy State:Panic (still had orientation control (movement blocked though), no wandering[this bit was not tested, due to the panic being morale induced]).

And in iwd there are several panic modes, but we have a separate issue for that. #459
