### ISSUE TITLE
[bug] BG2 'Badspells' - Domination / Hold animation issues

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#481]
See #465 

**Description**
Domination (SPLWI506) has two animation / gfx problems

- On hit animation is ~~not displayed~~ (EDIT: sorry, missed this at first: they are displayed, but a good bit below the target's feet) on GemRB.

![Hit_Domin_GemRB](https://user-images.githubusercontent.com/54738589/70546507-b928cc80-1b6f-11ea-80c5-3e31bb54c4c5.jpg)

 If cast successful it looks like this on the original:

![Hit_Domin_IE](https://user-images.githubusercontent.com/54738589/70545262-93022d00-1b6d-11ea-9a0e-ccb2aef100a3.jpg)
![Hit_Domin_Mndfl_IE](https://user-images.githubusercontent.com/54738589/70545265-9695b400-1b6d-11ea-8641-40be43ff2b1d.jpg)

- The projectile animations 'in flight' are not lined up correctly:

![Domin_GemRB](https://user-images.githubusercontent.com/54738589/70545595-1faceb00-1b6e-11ea-9479-cf2e5cd71037.jpg)

It should look like:
![Domin_IE](https://user-images.githubusercontent.com/54738589/70545620-276c8f80-1b6e-11ea-8f00-91fe9b2481be.jpg)

**Comment by caillean7** [comment]
The second point affects also Hold Person (SPWI306). On hit animation is fine for this one, though.

**Comment by lynxlynxlynx** [comment]
1) I found the problem and it fixes Domination nicely, however it breaks the drawing order, which is visible with fireshield. Still investigating why changing SelectObject is not enough.
2) Map::Sparkle has a fallback of 30 if the effect didn't specify a third param (not common).

**Comment by lynxlynxlynx** [comment]
I've fixed the first problem and opened a separate report for the second. Don't have the mind for geometry right now.
