### ISSUE TITLE
[bug] BG2 'Badspells' - Time Stop lacks projectile suspension

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#482]
See #465 

**Description**
On the original engine projectiles are suspended by time stop in mid-flight. They continue on their course when the spell wears out. On GemRB this is still missing - here any projectiles are completely unaffected.

**Expected behavior**
Halt any **ranged** projectiles (magical / spells & ranged weapons) when Time Stop is cast.

**Comment by MarcelHB** [comment]
Do the ones fly that are cast _during_ time stop?

**Comment by lynxlynxlynx** [comment]
At minimum the ones without "range", otherwise buffing wouldn't work. Even attacking wouldn't. So I think only aoe projectiles are stopped?

It will be fixed by the same thing. Projectile.cpp code (DoStep or Update probably) needs similar checks like Actor, via Game::TimeStoppedFor and Game::IsTimestopActive.

**Comment by caillean7** [comment]
> Do the ones fly that are cast during time stop?

Yes, spells and ranged weapons.

> So I think only aoe projectiles are stopped?

No, I can cast e. g. Fireball or Ice Storm during Time Stop normally.

**Comment by lynxlynxlynx** [comment]
Great, so it's even easier. Everything from the caster is exempt, while everything else is stopped. :)

**Comment by caillean7** [comment]
> Everything from the caster is exempt

Not on the original engine - it treats the caster like everyone else.

**Comment by lynxlynxlynx** [comment]
I don't get it then:
> > Do the ones fly that are cast during time stop?
> 
> Yes, spells and ranged weapons.
> 
> > So I think only aoe projectiles are stopped?
> 
> No, I can cast e. g. Fireball or Ice Storm during Time Stop normally.

**Comment by caillean7** [comment]
What you said sounded to me like "Projectiles from everyone except the caster should be suspended, but NOT the caster's own". Misunderstanding then?

**Comment by caillean7** [comment]
> Even attacking wouldn't. So I think only aoe projectiles are stopped?

If that's a bit unclear: On IE they are stopped, on GemRB not. Not sure which engine you meant there. So basically the original seems to stop everything, while GemRB currently stops nothing.

**Comment by lynxlynxlynx** [comment]
Ok, so then only the attack projectiles are immune. Or just melee?

**Comment by caillean7** [comment]
Just melee, I tried with darts during time stop, they just floated in front of the mage and then hit their target all at the same time when the spell ran out.

**Comment by lynxlynxlynx** [comment]
Just for completeness, so we can rule out range, how about "touch" spells like shocking grasp?

**Comment by caillean7** [comment]
Shocking Grasp and Ghoul Touch work during Time Stop - they are type melee however, and list for all effects 'Projectile: none'.

**Comment by lynxlynxlynx** [comment]
Hmm, that's in the extended header of the spell though, not the projectile. But good to know, of course they're linked.
