### ISSUE TITLE
[bug] IWD1 & BG2: nothing grants racial infravision

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#483]
**Description**
I can't seem to get Infravision working on those two games, double-checked my ini settings, even tried deleting them. Could someone check if it's working for you, please?

**GemRB version**
0.8.6-git master

**Comment by lynxlynxlynx** [comment]
Did you try the spell or are you just checking the racials?

**Comment by caillean7** [comment]
The spell works, it's just the racial ability.

**Comment by lynxlynxlynx** [comment]
Ok. The same problem should be in bg1, did it not have infravision at all or something?

**Comment by caillean7** [comment]
BG1 works for me - the Mission Pack Save is great for easy testing.

**Comment by lynxlynxlynx** [comment]
Not well though. It's Minsc that has it, but the only one and he's human. Apparently it just set the base state to include the infravision one.

**Comment by caillean7** [comment]
> It's Minsc that has it, but the only one 

Same here when I disable Group Infravision.

**Comment by lynxlynxlynx** [comment]
EE stores this info in racefeat.2da, so let's add the same layout and not stick it into races.2da.
