### ISSUE TITLE
[bug] BG2 'Badspells' - Cone of Cold applies damage instantly

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#484]
See #465 

**Description**

> cone of cold applies the damage immediately, not when the drawn projectiles hit

When Cone of Cold is cast, the damage gets applied immediately, while the animation 'travels' rather slowly. On the original they are in sync. Tested with a longer spell range, that makes it more obvious:

![cone](https://user-images.githubusercontent.com/54738589/70563821-36176e80-1b8f-11ea-8768-fafb4178daee.jpg)

Imoen has long been hit here, while the 'ice wave' has way to go.

**Comment by lynxlynxlynx** [comment]
This could be hard. Is at least the drawn speed matching?

**Comment by caillean7** [comment]
Looks like, I'll time like the Magic Missiles to be sure.

**Comment by caillean7** [comment]
Nah, I'm sorry, on IE it's much faster than GemRB, almost doubly so :( Didn't notice until I used a stopwatch.

**Comment by lynxlynxlynx** [comment]
Hmpf, the projectile has a speed of 10.

**Comment by bradallred** [comment]
I don't remember if it is possible with this spell, but is the result different if you cast on the ground vs on an actor? I noticed some oddities with that when working on #146

**Comment by caillean7** [comment]
You can target on the ground, so I compared 'ice wave traveling times', it's the same. Allowing some minor margin of error (few ms) because of the human / me factor.

**Comment by bradallred** [comment]
I was talking about the instantaneous damage application, not the animation.

**Comment by caillean7** [comment]
That one is not visible - I'll try adding some visual to it.

**Comment by caillean7** [comment]
Well, targeting on the ground near some character will still apply the damage instantly.

**Comment by lynxlynxlynx** [comment]
So the speed field is used, most projectiles seem fine, while this one is too slow and mm too fast. Something is fishy.
