### ISSUE TITLE
[bug] BG2: IE ToB saves issue

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#487]
**Description**
Just noticed that GemRB won't show any ToB saves made by the original engine, and vice versa. For ToB, they ignore each others saves, except for the ToB quicksave, which shows up with the SoA saves on GemRB. Not sure if this could have any connection to #318, maybe something not yet implemented.

**GemRB version**
0.8.6-git

**Comment by caillean7** [comment]
I see that GemRB is using the 'mpsave' folder instead of 'save' like the original.

**Comment by lynxlynxlynx** [comment]
Yes, that's the only thing. Saves are otherwise ignored only if the version mismatches.

**Comment by FrElvire** [comment]
Save from TOB are not automatically migrated from 'mpsave' to 'save' so no more TOB save available before moving them manually

**Comment by lynxlynxlynx** [comment]
They are migrated, I tested it. If it doesn't work for you, I'll need more details. Eg. are save and mpsave using different case on windows?

**Comment by FrElvire** [comment]
The saves were not made on Windows (never used gemrb on it), so all is case sensitive, here is some info : 
![image](https://user-images.githubusercontent.com/55502325/87870613-0db7e400-c9aa-11ea-9689-80d65abe2c1e.png)
![image](https://user-images.githubusercontent.com/55502325/87870624-27f1c200-c9aa-11ea-8142-d6db395607c9.png)
in save directory you can see some TOB saves, bu it's me who moved them manually after not having them available
![image](https://user-images.githubusercontent.com/55502325/87870633-3dff8280-c9aa-11ea-9209-02fc931c8e54.png)

In my cfg file : 

CaseSensitive=1
SavePath=/home/dupontr/.gemrb/games/BGII - SoA/

I just correct it (and others occurrences) with : 
SavePath=/home/dupontr/.gemrb/Games/BGII - SoA/

and restart gemrb but no change : no migration

**Comment by lynxlynxlynx** [comment]
Ah, you have your saves at a different location, not something I considered.

**Comment by lynxlynxlynx** [comment]
You can retry with the latest build. :)

**Comment by FrElvire** [comment]
Migrating saves from old location ... done.   👍 

They are now all  in save directory
