### ISSUE TITLE
[bug] iwd2: wrong text colors in the movie list

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#491]
There's an old report that the movie list in the options window of iwd2 used a different color for the movie names. Check and fix if true. Start in `gemrb/GUIScripts/iwd2/Options.py`.

**Comment by caillean7** [comment]
GemRB shows the active name in orange, the IE doesn't. If you mouse over a name, GemRBs yellow / gold color seems slightly darker as on the original. GemRB looks better imho.

![movies](https://user-images.githubusercontent.com/54738589/70624520-bfc34c80-1c20-11ea-8b52-873cae466666.jpg)
![movies_IE](https://user-images.githubusercontent.com/54738589/70624525-c2be3d00-1c20-11ea-9264-ec28dbefa2e4.jpg)

**Comment by lynxlynxlynx** [comment]
I agree, let's ignore.
