### ISSUE TITLE
[bug] BG2 'Badspells': Web child projectiles

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#506]
See #465 

**Description**

> web has too fast child area “projectiles”

No, in fact they're quite slower than on the original. They also spread out much more random and less uniform on GemRB. On IE there's a quite 'orderly' ring of children spreading out from where the spell hit, they cover a circular area. On GemRB the target area is often more like an ellipse and far less homogenious. I'm not sure if this needs addressing - recorded two casting attempts for you to take a look at.

[web.zip](https://github.com/gemrb/gemrb/files/3951320/web.zip)

**Comment by lynxlynxlynx** [comment]
Thanks, this is fine. I did some work in May to make it better and the todos are still there: a799a97220

It really looks like web ignores the isometric view. Whatever.
