### ISSUE TITLE
[bug] BG2 'Badspells' - Wish

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#507]
See #465 

**Description**

> miscast magic, restoration (wishpower14) have a bad projectile (not affecting everyone they should)

Restoration seems to work okay. MM has some problems, plus I found some more while testing.

~~**WishPower04** - Temporarily set Strength to 18 for everyone in the area, including enemies
Doesn't work on enemies, effects only party members and the djinn himself. I'm unsure how to test if it's working on the original, since it hasn't something like Ctrl.+M to check actors(?)~~
Targets must be inside 20 ft range

**WishPower05** - Miscast Magic,  spwish30
Affects everyone, but it looks like the game tries to apply the effect to creatures with magic resistance over and over again, e. g. golems and cambion in the starter dungeon (AR0602). You can see that in the Message Window, it goes on like this as far as you can scroll up:
![misc_magic](https://user-images.githubusercontent.com/54738589/70652949-d8992580-1c53-11ea-8caf-c0fa692a2323.jpg)

And in the terminal output / GemRB.log (see attached txt file for an excerpt of my GemRB.log)
[Wish_log.txt](https://github.com/gemrb/gemrb/files/3952165/Wish_log.txt)

**WishPower07** - Abi-Dalzim's Horrid Wilting' on everyone in the area, including the party, spwish32
Shows the spell's visuals always, but the damage is only applied if an enemy is in range. Neutral actors make no difference.

~~**WishPower21** - Make it as if the entire party has just rested a full night and re-memorized all their spells
Doesn't work at all - is supposed to affect spells and non-magical innates like e. g. Set Snare~~
fixed

~~**WishPower26** - Level Drain two levels from each party member
Doesn't always work on all party members~~
Was caused by Imoen's girdle in Chapter 1

**WishPower27** - Temporarily remove half of the caster's HP, spwish20
It's supposed to halve the caster's max HP. On GemRB it doesn't remove enough HP, but instead wounds the character as well. Example: A char with 57 max HP gets reduced to 28 max HP on IE. On GemRB she's left with 38 max HP and 28 actual HP.

**WishPower28** - Temporarily remove 15% of all party members' HPs, spwish21
This one removes too many max HP on GemRB, 44% instead of 15%. Also, it applies damage to the characters, possibly even killing them. On the original, nothing like this happens, max HP get reduced, leaving the character wounded if the spell wears out. Example: A char with 57 max HP gets reduced to 48 on IE. On GemRB she gets reduced to 32 max HP and she loses 13 more, so her actual health is 19 HP after the spell is applied

~~**WishPower30** - Party loses 10,000 gp
On GemRB this gives 10,000 rather than removing it - works on the original.~~
fixed

**Comment by lynxlynxlynx** [comment]
Of course the variables don't match the spell names, that would make too much sense.
> WishPower04 spwish29
> WishPower05 spwish30
> WishPower26 spwish19
> WishPower30 spwish23

Easiest way to test is to cast those spells. In the original that probably means modifying a script. The dialog just does `ActionOverride(LastTalkedToBy,ForceSpellRES("spwish41",Myself))`, so perhaps something like `ActionOverride(Mysel,ForceSpellRES("spwish41",Myself))` attached to a hotkey.

04:
The secondary projectile was hardcoded, in gemrb currently SHAREA or SHAREA1. But neither that nor the main one do any target filtering. Are you sure the enemies were within range? Before I spend too much time on this it'd be good to know if it worked in the original.

05:
Looks like we don't abort the effect correctly and it tries to get reapplied. This spell is using a particular targetting mode, so maybe the bug is there.

26:
That's too vague. Is it always the same people that are immune? Magic resistance, negative plane protection etc can all be the culprit. The spell itself doesn't appear to have saving throws.

30:
Yeah, bg2 broke the effect.

**Comment by caillean7** [comment]
Heh, I just removed the conditions from the djinn's dlg, so I get all the options every time, seemed easier than setting up hotkeys (for me anyway). Can go over all the wish options methodically now.

> 04:
> The secondary projectile was hardcoded, in gemrb currently SHAREA or SHAREA1. But neither that nor the main one do any target filtering. Are you sure the enemies were within range? Before I spend too much time on this it'd be good to know if it worked in the original.

Those spells have ranges set, but the others seem to work for all creatures in a given area. Take the Miscast Magic, it has a range of 50 ft, while this Strength modification has 20 ft. I just assumed they ought to work the same way, i. e. on all actors in the area. But retested with an enemy right next to the party, it was affected.

> 26:
> That's too vague. Is it always the same people that are immune? Magic resistance, negative plane protection etc can all be the culprit. The spell itself doesn't appear to have saving throws.

It's always Imoen, now that you mention it. I tried adjusting her position in the party, so it's not that. If I remove her from the party, the others work. Haven't tried all NPCs, though. I did try force joining some enemy into the party, they got affected by the level drain alright.

**Comment by lynxlynxlynx** [comment]
04: so is there a problem or not?

Is it Chateau Imoen or later? That first one is godlike wrt immunities.

**Comment by caillean7** [comment]
> 04: so is there a problem or not?

No, like I said, I just assumed it should work like the others. Sorry.

> Is it Chateau Imoen or later? That first one is godlike wrt immunities.

Yeah, it was that bloody girdle of hers, it works on Imoen213. Sorry gain, didn't think of it.

**Comment by caillean7** [comment]
@lynxlynxlynx I have tested all wish options and found some more problems, they're added to the list in the initial post.

**Comment by lynxlynxlynx** [comment]
What do the two hp ones look like on characters without a constitution bonus?

**Comment by caillean7** [comment]
Half caster HP: Takes a char with 37 max HP down to 18 max HP; char is not wounded.

Lower HP 15%: The same char does down to 12  max HP, likewise she is not wounded. Only the party members that have a con bonus end up hurt.

**Comment by caillean7** [comment]
Please don't kill the messenger, but I still have the negative gold problem.

**Comment by lynxlynxlynx** [comment]
How are you testing? I just emulate the dialog to get the spell cast.

**Comment by caillean7** [comment]
Just talking to the Djinn and select the option. When I do with 1 gp party gold, I end up with -9999.

**Comment by caillean7** [comment]
:+1:  It's fine now

**Comment by lynxlynxlynx** [comment]
> WishPower05 - Miscast Magic, spwish30
This appears to be just spam, from each effect being resisted. Did the original behave differently? Might be just the fact that this area is not nice for testing due to all these special actors.

> WishPower07 - Abi-Dalzim's Horrid Wilting' on everyone in the area, including the party, spwish32
> Shows the spell's visuals always, but the damage is only applied if an enemy is in range. Neutral actors make no difference.
I think this is fixed now — for neutral casters everyone is considered an enemy.

> WishPower27 - Temporarily remove half of the caster's HP, spwish20
> It's supposed to halve the caster's max HP. On GemRB it doesn't remove enough HP, but instead wounds the character as well. Example: A char with 57 max HP gets reduced to 28 max HP on IE. On GemRB she's left with 38 max HP and 28 actual HP.
> 
> WishPower28 - Temporarily remove 15% of all party members' HPs, spwish21
> This one removes too many max HP on GemRB, 44% instead of 15%. Also, it applies damage to the characters, possibly even killing them. On the original, nothing like this happens, max HP get reduced, leaving the character wounded if the spell wears out. Example: A char with 57 max HP gets reduced to 48 on IE. On GemRB she gets reduced to 32 max HP and she loses 13 more, so her actual health is 19 HP after the spell is applied
This two use the same opcode, setting to a % value. Sounds like conflicts with constitution hp bonuses and maybe other items.

**Comment by lynxlynxlynx** [comment]
With that and Tomsod's hp handling fixes all the remaining powers are fixed.
