### ISSUE TITLE
[bug] IWD1 'Badspells' - Cone of Cold damages caster only

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#515]
See #465 

**Description**

If cast on the ground and not at an actor, Cone of Cold doesn't 'fly off' at all, the damage gets applied only to the caster, even if someone else is standing directly next to them.

The animation as shown in this screenshot from the original is not drawn:
![Cone_IE](https://user-images.githubusercontent.com/54738589/70831104-f2706f00-1df1-11ea-8bb6-ccffb013f02b.jpg)

**Comment by bradallred** [comment]
This probably only applies if you target the ground I think. If you were to target an actor you should get a different issue where the damage is only applied to the target.

We definitely have a bad implementation of payload application for any spells that hit multiple targets with only a few special exceptions (scorcher and lightning come to mind). It seems to me that this spell and any others that travel and hit anything in their path need to use the same payload delivery mechanism the lightning bolt that I added in #146

**Comment by caillean7** [comment]
You're right, Mr. A. It also doesn't draw the 'flying animations' for the spell, nor does it play the casting sound. AND it also doesn't make bystanders hostile if I attack people in town with spells - attack with weapons does. I tried some other spells, too, this seems to a common issue and not only Soul Eater. Will update those issues then.

**Comment by bradallred** [comment]
we are going to have to get fancier with target scanning too. Scorcher and lightning are thin projectiles so we get by with a point radius scan along the projectile path. Things like cone of cold need to do something like a line scan perpendicular to the projectile path to search for targets.

**Comment by caillean7** [comment]
Those games are all related, the rules are the same, a lot of spells are, it's kinda curious that they can't share such mechanics - BG2 works so well already. Ah well, noobish question being nonconstructive, just a thought.

**Comment by lynxlynxlynx** [comment]
Targeting is not as bad as you two make it sound. But it sure does show this was all hardcoded until late versions, meaning also that our replacements may lack certain flags or other settings.

**Comment by bradallred** [comment]
Unless I missed something in my assessment, there is no code to even handle this sort of targeting and we end up targeting the caster, so isn't that exactly as bad (non-existent) as I make it sound? I'm not being derogatory there simply isn't code written for this type of spell and so we do the wrong thing is all :man_shrugging:

**Comment by lynxlynxlynx** [comment]
You made a general statement, ignoring most multiple-hit spells that work fine. While I agree we probably do need a cone payload application mode as the other bug suggests, the fact that it now falls back to the caster is independent. BG2 cone of cold, for example, does hit everyone, while the iwd one isn't even set up as an aoe.

**Comment by lynxlynxlynx** [comment]
It was using the completely wrong projectile. The "caster only" and missing animation are fixed, but there are other problems, so perhaps let's just keep this bug here open to polish the spell further.

One is that the animation is always drawn at the same angle, the second that it's most likely too fast (handled elsewhere).
