### ISSUE TITLE
[bug] IWD1 - No casting sounds played

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#518]
**Description**
IWD1 seems not to play any casting sounds / incantations at all, affects arcane and divine spells.

**GemRB version**
0.8.6-git

**Comment by lynxlynxlynx** [comment]
It's looking for files of the same pattern as in other games, but they don't exist.

spiritual hammer: 
> [ResourceManager/WARNING]: Couldn't find 'CHA_mp00'... Tried CHA_mp00.wav CHA_mp00.ogg CHA_mp00.acm CHA_mp00.wav 

blur:
> [ResourceManager/WARNING]: Couldn't find 'CHA_fm00'... Tried CHA_fm00.wav CHA_fm00.ogg CHA_fm00.acm CHA_fm00.wav 

It's the 00s that should be something else, but the data/logic is lacking. My how install comes with both some bg1-style sounds (CAS_P*) and these CHA_* ones from bg2. What did the original use?
This is all decided in Spell::AddCastingGlow.

**Comment by caillean7** [comment]
I sampled quite a few spells on the original, and they all use the CHA_* sounds. There are 2 versions for each sex / school / mage/priest.

About those CAS_P ones - I can't remember where they were used. BG2 has them, too... I keep thinking that I would recognize them if they were used in BG2, though. Right now I'm out of ideas how to find out how and where they are used.

**Comment by lynxlynxlynx** [comment]
They're from bg1. Thanks for checking what's actually used. It turns out it was just missing the sound mappings.

**Comment by caillean7** [comment]
I just noticed with Mordenkainen's Force Missiles that the game uses different casting sounds than on the original, some others, too. Seems like the magic schools got mixed up somehow.

**Comment by lynxlynxlynx** [comment]
Can you play with the numbers of each school to get the right result?
https://github.com/gemrb/gemrb/commit/83a6483a258d96a7af2bdf2ac02f895e6b02aee2
Modify the HoW one.

**Comment by caillean7** [comment]
I modified it according to the file names, added Evocation, it wasn't there before, but it doesn't pick up on any changes I make to cgtable?

**Comment by lynxlynxlynx** [comment]
Show me your work.

**Comment by caillean7** [comment]
https://github.com/gemrb/gemrb/compare/master...caillean7:master

**Comment by caillean7** [comment]
Wait a minute - Invocation? Is that supposed to be Evocation?

**Comment by lynxlynxlynx** [comment]
The row names don't really matter, it's the order that does, corresponding to the spell school id. But yeah, even dltcep says invocation for fireball. Same 15 for Mordekainen's, so it's the one line you didn't edit, that's why you can't hear a difference.

**Comment by caillean7** [comment]
Sorry, I'm at a loss - I thought it should correspond to the numbers in the names of the wav files?

**Comment by lynxlynxlynx** [comment]
Yes, but MFF is using the invocation line and the number didn't change before or I didn't see it correctly. What's the current result?

When I was testing beforehand, a lot of the _invocations_ sounded very similar.

**Comment by caillean7** [comment]
It seems to use the illusion line, which is exactly the one I didn't change, because the numbers were the same. And other spells still sound wrong, too. I tried with a 2da file in the override and even reinstalled the whole GemRB with a modified file.

**Comment by caillean7** [comment]
Nah, sorry, it's Armor using Illusion, which is actually Conjuration. MFM is using Abjuration.

**Comment by lynxlynxlynx** [comment]
Armor has conjuration 14 in my install and line 14 in the table is conjuration. I'm opening a new report, so it'll be cleaner.
