### ISSUE TITLE
[bug] IWD1 - Attacks on townsfolk with spells don't aggro neutral actors

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#519]
**Description**
If casting hostile spells - directly on a target or AoE spells - in towns on neutral persons it should make the others hostile - this doesn't work. Wounding a neutral NPC with a spell likewise provokes no reaction. I tried with a few spells, seems to be something general. Attacking with weapons does the trick.

**GemRB version**
0.86-git

**To Reproduce**
Start a new game with a mage character and cast e. g. Magic Missile on someone in the tavern.

**Comment by bradallred** [comment]
are you saying even when the spells do damage they don't turn hostile? Hostility should be triggered by damage, not the casting of a spell per se. As you know our spell damage application is largely broken.

**Comment by caillean7** [comment]
I mean bystanders as well as the actors you actually damage. So even if you wound someone with a spell, they won't react.

**Comment by bradallred** [comment]
how interesting; thanks.

**Comment by lynxlynxlynx** [comment]
So what scripts do they have? Iow which trigger is failing us?

**Comment by caillean7** [comment]
Checked a number of townie scripts, these are ones supposed to trigger hostility:

`AttackedBy([GOODCUTOFF],DEFAULT)`
`HitBy(NearestEnemyOf(Myself),CRUSHING)`

**Comment by lynxlynxlynx** [comment]
Please isolate and test them individually. AttackedBy makes sense, but HitBy being sent by spells sounds suspicious.

**Comment by caillean7** [comment]
There must be something hardcoded, too? Because, even if I disable all scripts from all actors in the area, they're still turning hostile if attacked. But strangely enough all townies have those two trigger blocks in not only one, but two of their scripts.

**Comment by caillean7** [comment]
> AttackedBy makes sense, but HitBy being sent by spells sounds suspicious.

Yep, exactly right, it's the AttackedBy part. The HitBy doesn't do anything for attacks with spells.

**Comment by lynxlynxlynx** [comment]
Phew, don't scare me like that. We already make hostile effects send this trigger, so maybe spells in iwd don't have the hostile bit set? ... Indeed. :( Barely any even use the flags field.

We'll just check if they have a damage opcode, since we already have code for that. This heuristic should be good enough.

**Comment by caillean7** [comment]
Ah, sorry, didn't mean to give you a turn, just used NI's 'Recently opened games', which is probably fine if you have but one installation of the given game. Will make some properly named bookmarks!

There's even a 'hostile' flag, but it's not set for offensive spells.
