### ISSUE TITLE
[bug] PST: Death should not leave you with only 1 HP on resurrection 

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#521]
In the original game, dying is not meant to be much of a setback, just a regular Monday morning. You have to die at least 3 times in one particular map just to escape it. The fastest way to get out of the dungeon and get back to town is to get your party members to carry out your lifeless corpse and wake up feeling refreshed :)

GemRB version: any

Order TNO to run into suicidal danger

**Expected behavior**
You should wake back up at wherever recovery place the game already sets with full health instead of 1HP

**Comment by MarcelHB** [comment]
It's not (always) 100%. If my TNO dies at 116 max HP, he resurrects with 89.

**Comment by chilvence** [comment]
I didn't know that one, that makes it tricky.  I don't tend to die if I can avoid it, do you think it is a cap , or a random dice roll, or something else? I will keep notes when I get to that stage of the game but I am not there yet

**Comment by MarcelHB** [comment]
Yes, investigation would be helpful. In a few samples, it's been always the same reset HP - and there was no difference between medium and lowest difficulty.

**Comment by lynxlynxlynx** [comment]
Also think about TNO's constitution, since he does have extra regeneration from that.

**Comment by chilvence** [comment]
You thinking it may simply be the passing of time curing TNO? I can check for that...

**Comment by chilvence** [comment]
No actual time seems to pass, it's just an insta teleport to the mortuary by the look of it.

I'm having a really hard time reproducing the 'not fully healed' status though. If I edit my CON to 10 and set my MaxHP to 200, I still get 200 HP back.

Do you happen to have a save game I can try out?

**Comment by MarcelHB** [comment]
Try out this one. I noticed something interesting: When TNO dies, his TP displays shows 89 instead of 110 at times being alive. When resurrecting, I always seem to get 89.

[pst_save.zip](https://github.com/gemrb/gemrb/files/4788347/pst_save.zip)

**Comment by MarcelHB** [comment]
Just an idea: Do you have this Max HP per level attribute? You can obtain this at some early stage in the game. Just if that's what make the calculation mismatch.

**Comment by chilvence** [comment]
It appears that you have the Aegis Torment increasing your CON, and Tatoos increasing your MaxHP, so I think the game might be reseting to the maximum number of hit points for your character, but ignoring the CON modifier and maxhp bonuses from the items

**Comment by lynxlynxlynx** [comment]
Added the heal, not addressing any effect problems. Are you saying they are not being applied on the respawned TNO (iow same max hp)?

**Comment by chilvence** [comment]
It's tricky and convoluted, the original game is applying the amount of hitpoints provided by the knock on effect of having +3 Con, but not the extra hitpoints provided by the +15 max HP effect

However, just having the heal should be enough to match the same player experience, I probably wouldn't have known any better if Marcel didn't point out the different behaviour.

**Comment by lynxlynxlynx** [comment]
we should make the effects work if they don't. There's no need to copy the original lameness if the fix can be done nicely.

**Comment by chilvence** [comment]
Ah, I see what you mean, I hadn't rebuilt yet, I just assumed the Resurrect() call would take care of reapplying the applying item effects . With this, the HP value is set to the base 76, before any mods.

**Comment by lynxlynxlynx** [comment]
But is the max hp set or not?

**Comment by chilvence** [comment]
Yes, the map hp is set 

Although one thing I did notice, is that it is 112 when I load the game in GemRB instead of 116, so that might be another thing to investigate

**Comment by lynxlynxlynx** [comment]
Does this help?
http://sprunge.us/M2RDQ9?diff

**Comment by chilvence** [comment]
Indeed it does :)
