### ISSUE TITLE
[bug] PST:  TNO must change avatar depending on equipped weapon type

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#522]
PST has a complete set of character animations for each weapon type he can use instead of being a multi part sprite like in BG/IWD . Currently Gemrb seems to only use the fists anim set no matter which weapon equipped

These are the animation sets I could find, with the first four letters being the name of the action in the pst convention:

****NOAB - resdata: 47 - Axe
****NOCB - resdata: 48 - Club
****NODB - resdata: 49 - Dagger
****NOFB - resdata: 50 - Fists
****NOHB - resdata:51 - Hammer 

Also there are two disguises in the game that should probably override that:

****NOMB - resdata:93 - Dustman disguise, which is given by equippable robes
****NOZB - resdata:82 -  Zombie disguise, which is placed on you by an npc.

I can't see anything notable in the itm files that relates to these avatars so I guess they were just hardcoded changes. Even the DUSTROBE.itm file has no specific avatar change action that I can find.

None of the other characters can actually use any other weapons unless they are the same type they started with. Vhailor might be different, but I can't remember offhand. I actually remember on my old Pentium 233 it taking a good second or two to change weapons in the inventory screen, so it must have been preloading the animations to stop the main game window from imploding.

Of course this is probably better dealt with after subviews, just reporting it.

**Comment by chilvence** [comment]
This is actually probably related to #175 , it slipped my mind that this has already been noted down, and the link in that issue has lots of really good general information

**Comment by lynxlynxlynx** [comment]
Disguises should work already, we have code for at least the dustman one.

**Comment by chilvence** [comment]
IIRC they do, but I thought I would mention them here because I am not sure how that would interact with weapon avatar switching as well. Should disguises have priority, or should equipping weapons break them? Not sure what the original game does.
