### ISSUE TITLE
[bug] PST: Morte loses his taunt special ability after only 1 use

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#524]
In GemRB, Morte is only able to use his gobby mouth once, then the ability is discharged and disappears never to come back

GemRB version: any

**Expected behavior**
In the original game, this ability can be used once per round, at will, as many times as you like.
Just for fun, I tried to insult everyone in the southeast quarter:

![Trmnt000](https://user-images.githubusercontent.com/1923867/70852716-b6deaf00-1e9c-11ea-873b-fae192d5cd60.png)

**Comment by chilvence** [comment]
Of course helpfully, in SPIN101.SPL, the spell is set to vanish when drained, so the game is only apparently doing what the data tells it to do. Several other innate abilities have exactly the same set. The game must do something special here, Is there a 2da file that has the npc abilities maybe?

**Comment by lynxlynxlynx** [comment]
SPIN101 is hardcoded 3 times and "Special Ability: Litany of Curses" once. Suspicious. I suggest we just override it with our own version that adds a self-refreshing effect.

**Comment by chilvence** [comment]
That sounds good to me, it doesn't really seem necessary to overthink this one as long as the end result is the same

**Comment by lynxlynxlynx** [comment]
Oh, I remembered that you could upgrade this ability throughout the game. Annah can do it and at least one other person. So there's either more files involved or they changed some aspect of the spell on the fly via some game variable. I guess it's easiest to check by inspecting Annah's dialog, see what it's doing and if that's enough.

**Comment by chilvence** [comment]
I couldn't find anything in Annah's dialogue file

I do remember several points in the game where characters start streaming obscenities and Morte reacts to it,  in the lower ward pawn shop the couple is arguing, in the clerks ward there is a statue that you can un-petrify, also when you are trying to find Jhelai for Craddock they both task you with sending insults to each other on their behalf. I think you can also ask Kimaxi to coach Morte's insults.

All of these occurences seem to have the action 'IncrementGlobal("Morte_Taunt","GLOBAL",1)' in the dialogue file.

It's possible that the conversation is initiated by Annah's dialogue, but the action to increase it is in DMORTE.DLG

Here's some Chris Avellone talk about it :

> Peacedog1 wrote:

> I've beaten the game. I got 2 curses for morte, the litany (which he comes with), and the one where the enemy gets assaulted by a hoard of skulls (and its damage might be level based, because towards the end I got high 30s to 40 with it). Is there another ability? I had three different instances where Morte said he learned a new curse, but I only got these two abilities (though the other might have been the ability to cast the skull one more than once between resting). The statue in the museum, The Sensate, and I think Annah were the three I found. Did anyone find any other instances where Morte learned new curses?

> That's the only 2 special abilities he gets. When Morte says he learns "new taunts," he's actually getting a +1 bonus (lowering his enemy's chance to save by-1) to his Litany of Curses.

> The bonus for the statue in the musuem is higher than normal, however, +2.

> I think someone posted a list of all the curses, which is probably more complete than the list here at Interplay. Three other places for curses I know of are:

> Kimasxi Adder Tounge in the Brothel

> Craddock in the Hive marketplace (when you tell him Jhelai won't be showing up for work)

> Any Harlot in the Hive (when you defend Morte by insulting her)

> Chris

Source: http://www.shsforums.net/topic/38511-chris-avellone-said-about/

**Comment by lynxlynxlynx** [comment]
Nice, also a detailed description in the same thread:
> Type: Special Ability
> Name: Litany of Curses
> Description: Morte can draw upon his repertoire of insults to taunt an opponent into lowering his guard and attacking. The target suffers penalties to hit and damage when enraged.
> Ability: Instant
> Range: The effect can target any single living target on screen. I do not know what this range translates into.
> Speed Factor: 1
> 
> Effect: When Morte's special ability is selected, the targeting cursor appears and the player may click on one living opponent on screen. This spell cannot target undead creatures. Magic resistance does not affect this spell. The target does get a saving throw vs. Spells to resist the effect, however.
> 
> When a target is selected, a brief insult from Morte plays (taken randomly from a list of voice files). If the Litany of Curses is unsuccessful, then nothing happens. If it is successful, the target freezes for two seconds, turns a pulsing red (pulsing like a heartbeat, the effect similar to the Strength spell) and then moves to attack Morte as quickly as possible. **The number of taunts that Morte has accumulated will penalize this saving throw.**
> 
> While the target is 'taunted', the following effects occur:
> 
> 1. The target suffers a +2 to hit and a +2 to AC and a -2 to damage as long as the Litany of Curses is in effect.
> 
> 2. The target's AI is overridden so the target will always attack Morte with a physical hand to hand attack, no matter what. This lasts only for the duration of the taunt effect.

**Comment by lynxlynxlynx** [comment]
The spell is supposed to set spin101.bcs as the override script on the enemy to do part 2, but the opcode has an empty resource (so doesn't work at all in testing, right?). Looks like we'll have to hardcode it somewhere along with that Morte_Taunt malus do the saving throw. It does use an unhardcoded yet bland litany.pro, but I doubt that's helpful here.

**Comment by lynxlynxlynx** [comment]
Perhaps these two are of use too, even though I don't see any matches in the exe:
```
SPIN001 Add Litany of Curses
SPIN002 Removed Litany of Curses
```
There's analog spells for most of the npc abilities.

**Comment by chilvence** [comment]
I think it might be possible to ignore those as cruft, I can't point to any particular point in the game where any NPC loses their special abilities. 

The only scenarios I can think of is that Nameless gains special abilities by dialogue options, eg by talking to Stale Mary. I think there is also a scenario that the can learn Grace's sensory touch. There is however no scenario in the game where any character learns Fall-from-grace's kiss ability (spin009), that is something innate she possesses from being a succubus.

 If there are extra spell files that add or remove abilities I would guess it is more likely that some fastidious developer created them just in case they would come in handy.

**Comment by lynxlynxlynx** [comment]
Taunt upgrading is now implemented. Another research todo: did the original really exclude undead? We have a useless litany.spl as well, which could probably host the rememorization part.

**Comment by lynxlynxlynx** [comment]
SPIN001 can indeed be reused for rememorization, since it triggers no message.

**Comment by i30817** [comment]
Can't you be expelled from some guilds/be recruited by another and lose special abilities that way? Haven't played this game in years though, so it may be that you can't be expelled.

**Comment by lynxlynxlynx** [comment]
No, that just removes faction-specific benefits.
