### ISSUE TITLE
[bug] PST : Areas that separate you from your party cause various problems

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#525]
I am reporting this error as a general problem because there seem to be various factors going wrong

One is a simple GUI problem, when party members are removed the scripts do not handle it and your empty slots become glitchy, they just need to be emptied

The other, it seems like the game does actually try to remove all other party members, but does not succeed. For example moving from AR1700 to AR1800, Morte is removed from the party but not Dakkon, I haven't been able to deduct what part of the travel trigger is supposed to be telling the game this is a special exit, the only thing different about it seems to be the 'trigger silent' flag is set, which is interesting because that seems to be an exceptionally rare occurrence among all the travel triggers in the game, I suspect it may only be set for this particular exit but I haven't had time to scour the data. 

After looking at at least 50 different exit points, this was the only one I could find that has this particular bit set, and the only other one that has a weird bit set is the one in the mortuary that travels to AR1200 (endgame), which according to nearinfinity, has 'trap set off by NPC' set.

What I surmise from this is that the travel trigger bits should be treated differently from the trap bits, and that NI doesn't know that. These are two of the areas that cause you to become separated from your party, the only other one is the Lady of Pain maze, and I think that is handled by a script instead but I am not sure. In any case, I think it is no coincidence that both exits have these unexplained bits set which don't occur on any other travel trigger, and the original game was set up to use them accordingly. I will experiment with them to see if I can break the original game in interesting ways and get back to this.

edit: contrary to what I expected, changing a random entrance to that bit seemed to have no effect, however changing it to warp to AR1800 put the game in a feedback loop where it was just failing to warp to the area and retrying constantly. Are these special areas handled by the game by name?

edit2: foolishly, I forgot to set the entrance name. Setting the entrance name correctly, I was able to warp to AR1800 from a random door in the lower ward, and arrived there alone as expected. No other data was changed, so while the door to1800 in ar1700 is the only one I can find with the 'trigger silent' bit ,I am not sure what it is supposed to achieve, I only had to change a door to warp to the correct entrance in ar1800 in order to be separated from my party. No other parameters for the travel trigger were changed, so the game clearly handles these special areas by area resource name.

**Comment by chilvence** [comment]
I seem to recall something about the BG games, where if you move a character to another area seperate from the rest of the party, the portait list lets you click on party members in the other area to return to it. 

What I think is happening is this: the other NPC's are not actually being removed from the party, they are just not following TNO into the new area, because on return to AR1700 you don't have to go through all that 'would you like to join me on my travels again' spiel, the NPC's just act like nothing has happened.

So what is actually happening by my guess, is that the character selection UI box just doesn't let you select characters that are not in your current area. 

I could be wrong of course, but it sounds dumb enough to be true.

**Comment by chilvence** [comment]
I am really dumb, I could have saved myself 3 hours of mucking about by using the github search box, turns out Gemrb does know about these special exits after all, which means Lynx must have fixed them  and something else is going wrong:  49e8d31

**Comment by chilvence** [comment]
I think I can see the problem:

The loop tries to iterate through the list of PC characters:

```
for (int i=1; i < game->GetPartySize(false); i++) {
 Actor *pc = game->GetPC(i, false);
```

However in the same loop, it removes the PC from the list

 game->LeaveParty(pc);

So 'i' has now skipped over what was expected to be the next party member, because they have all shifted up the list, which explains why my middle party member was always the one to remain with me.

Changing to 

`Actor *pc = game->GetPC(1, false);` 

makes the loop continuously remove the first party member after the protagonist until it ends

However, even though that stops the loop from skipping over party member entries, it doesn't get to the end of the list, I had to change it to

 `for (int i=1; i <= game->GetPartySize(false)+1; i++) {` 

to make that happen. Which I thought was a bit odd. I don't get why I need to add 1 to the party size, I thought just adding 'i<=' would loop the correct number of times.

**Comment by Mingun** [comment]
> I don't get why I need to add 1 to the party size

Maybe because loop starts with 1 instead of 0 (which can be correct, of course)?

**Comment by lynxlynxlynx** [comment]
Nice find! When you say you have to +1, is that for all npcs to get removed or why?

**Comment by chilvence** [comment]
So eg i starts at 1 and the party size is 4, should it not be able to loop 3 times before it is greater than 4? ie   <= 4

I know this is basic stuff, but it always confuses me

**Comment by lynxlynxlynx** [comment]
In that case four times. Anyway what is the visible problem?

**Comment by chilvence** [comment]
If I don't change it, then I am always left with the last party member (as opposed to before, I was always left with the 3rd party member I think)

**Comment by chilvence** [comment]
[000000185-abandonment issues.zip](https://github.com/gemrb/gemrb/files/3965142/000000185-abandonment.issues.zip)

If anyone needs a savegame ^

**Comment by chilvence** [comment]
Can confirm this also fixes the identical problem at the endgame portal , oo-rah

**Comment by lynxlynxlynx** [comment]
I still have the save I used to test this back then and it's clear why the fix wasn't complete — I just had Morte tagging along, nobody else.

**Comment by chilvence** [comment]
It's possible I didn't notice this for the exact same reason, doh!

From memory, I think there are only two more issues with that endgame area remaining,
