### ISSUE TITLE
[bug] PST: Alleyway dialogue does not resume after playing flashback video

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#526]
Last of my three game breaking nuisances, and sort of easy to work around

When you enter the alleyway, a cutscene starts which force walks you to a trigger point. This starts the dialogue with the alleyway, which ends by playing a flashback movie. Then, apparently, the dialogue trap is supposed to instantly trigger again, whereas in GemRB, you have to walk away and then back on to it in order to continue. 

So it doesn't technically completely break your game, but it does give that impression because you end up staring gormlessly at a silent wall, desperately hoping that it will talk to you again. This game is weird,

**Comment by lynxlynxlynx** [comment]
Do you have the area file name and dialog handy?

**Comment by chilvence** [comment]
I think it is AR0405, trigger 2 (Face) , it has 0405FACE.BCS attached to it which starts the dialogue DPREGAL.DLG . State 7 in that dialogue starts the cutscene 0405cut8.

**Comment by chilvence** [comment]
Then that cutscene starts 0405cut9 , which has this:

`SetNoOneOnTrigger("Face")`

**Comment by chilvence** [comment]
https://github.com/gemrb/gemrb/blob/dc48e42dea5dc20e3f077fec9725073ece92b510/gemrb/core/GameScript/Actions.cpp#L6227

I don't notice anything wrong here, it did not reach the error log condition, so does the 'InitTriggers()' function have to do something that it isn't?

Either that, or is '`if (!parameters->objects[1]) {` supposed to be checking objects[0] instead? There is only one parameter in the BCS file so I would have guessed it would be that, but I don't really know the workings of the scripting language at all.

'

**Comment by lynxlynxlynx** [comment]
Nah, that's for ActionOverride. But this rare function is a very good lead, perhaps it should also just execute immediately. Try adding `ip->ImmediateEvent();` at the end.

**Comment by chilvence** [comment]
I tried that ip->ImmediateEvent(), it didn't seem to have an effect . 

Wouldn't the actor on the trigger have to cross over its boundary again in order to register as being on it again ? Or is that checked every frame?

**Comment by lynxlynxlynx** [comment]
The only other use of this action is in ar0702 to reset an acid trap. You did find the right function to inspect after all. Now just to figure out the best way to fix it and ensure the Entered triggers fire on their own.

**Comment by lynxlynxlynx** [comment]
Please provide a save, there's something fishy going on.

**Comment by chilvence** [comment]
[000000182-GRB - Expectant Esplanade.zip](https://github.com/gemrb/gemrb/files/3970602/000000182-GRB.-.Expectant.Esplanade.zip)

This save was made before entering the area at all
