### ISSUE TITLE
[bug] is the dying animation is naked?

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#530]
We have this old note on the wiki:
> RESEARCH the dying animation is naked - any armor is stripped beforehand (is it different in originals?)

Is it still relevant? The only way for this to happen is if we dropped the loot too soon.

**Comment by caillean7** [comment]
All games? For BG2, on the original the armor is dropped immediately, too, before the whole falling down is done. Looks almost the same on GemRB, maybe GemRB even drops the equipment a wee bit later.

**Comment by lynxlynxlynx** [comment]
Thanks, so there's nothing to do.
