### ISSUE TITLE
[bug] PST: Healing items etc need to be usable from the inventory

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#531]
This one should be pretty easy to fix, it just hasn't bothered me enough so far to report it. Healing items like bandages and clot charms in the original game were usable instantly from the inventory, even when paused, so if you were down to 1 HP in a battle and had 33 rolls of bandages stacked up, you could still save the day. Just another way that PST is completely different to all the other games.

Just noting it here on the bug tracker while it is on my mind, I am currently getting beaten half to death by lowly thugs :)

**Comment by lynxlynxlynx** [comment]
So is the problem that we force a pause (one potion per round) or that you can't do it without first putting them in a quickslot?

**Comment by chilvence** [comment]
At the moment, there is no option to use these items at all in the inventory GUI, you must put them in a quickslot and use them on the game window.

**Comment by lynxlynxlynx** [comment]
How did it work in the original, the same way you initiate a dialog with an item?

**Comment by chilvence** [comment]
The functionality is similar to the 'drink potion' button in the item description in bg1/2 , except in this case, it happens immediately regardless of game pause state, and there is no limit to how many items can be used

Healing items that can be used this way are Bandages (BANDAGE.itm ), blood charms (BLOOCHRM) clot charms (CLOTCHRM), Embalming fluid (EMBALM)

Certain other items can also be instantly used this way, like charcoal charms (CHARCHRM) , bone charms (BONECHRM), blood flies(BLOODFLY), cockroach charms (ROCHCHRM).

I haven't found any clear pattern in the data yet though, so I don't know how the game decides what should be usable from the inventory or not. For example, KNOTCHRM can only be used from the game window in the original, as well as EMBCHRM , EMBCHRM2,  BBCHRM. 

The differences between them might be more obvious to someone else.  Unless it is another one of those silly things where they hardcoded my name somewhere in the game?

**Comment by chilvence** [comment]
I just looked again and it seems like all the items in the first group have the 'conversable' bit set in NI, which is a misnomer that continuously misleads me . I am sure it is probably correct as far as BG2 and the talking sword is concerned. For PST, it seems like this is the flag used to denote inventory screen usability, although please double check me if i am wrong about that.

**Comment by chilvence** [comment]
Yup, I removed that bit from the roach charm, and sure enough, I can no longer use it while in the inventory, only from the floating menu.

**Comment by lynxlynxlynx** [comment]
Ok, it's easy to enable the usage button now that #446 is done. However, two other subissues remain:
- we only allow one consumption per round
- some of these charms have external targetting; eg. the clot charm is not like a potion, but if you exit the inventory, you'll be invited to cast it as a spell by the cursor (doesn't work though) — were these all forced to apply to the drinker in the original?

**Comment by chilvence** [comment]
That is a good point, it looks like they behave differently depending on when you use them from the float menu or the inventory. The float menu gives you a targeting cursor to use it on whoever you please, whereas the inventory use method applies it directly to the user. Would the LUA stuff in the original be able to force this to happen?

**Comment by lynxlynxlynx** [comment]
Surely it was done in core. Either way, all but one thing is now fixed — during pause, you're still allowed to use only one item.

There also appears to be an unrelated off-by-1 bug in the inventory. You use one item, but the one in the slot before it gets consumed. Something must be wrong when constructing the ItemHash in GUIINV.py.

**Comment by chilvence** [comment]
I've not encountered this off by one bug before, but it is definitely happening now, with everything except my Modron Cube (which is a talk item)

**Comment by lynxlynxlynx** [comment]
Maybe it's a problem only with items that weren't usable before, though I can't imagine why. Please investigate and open a new report.

**Comment by chilvence** [comment]
No problem, I will see if I can spot it
