### ISSUE TITLE
[bug] PST: Cutscene Scripting error in AR1601 leaves you in game breaking state

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#532]
[000000187-GRB - Rapscallious Rodents.zip](https://github.com/gemrb/gemrb/files/3970804/000000187-GRB.-.Rapscallious.Rodents.zip)

Enter the Wererat dungeon , Mantuok will start to grill you. Pick the dialogue options "i came to see you", "....soego....", "....many as one...."

You should end up in AR1601 and a cutscene will start to play. Mantuok will disappear and then you will be stuck in limbo forever.

That seems to be because in 1601CUT3,BCS :
```
IF
	True()
THEN
	RESPONSE #100
		CutSceneId("Mantuok")  // Mantuok - Wererat
		FaceObject(Protagonist)
		FloatMessage(Myself,34700)  // "You and I shall meet again."
		Wait(3)
		FloatMessage(Protagonist,34919)  // "I'm looking forward to it."
		Wait(3)
		MoveToPoint([859.1174])
		GlobalSet("1601_Mantuok_Respawn","GLOBAL",0)
		DestroySelf()
		EndCutSceneMode()
END
```

Mantuok destroys himself before ending the cutscene mode. 

Swapping the order of the statements around fixes the problem. Here is my override bcs file:

[1601CUT3.zip](https://github.com/gemrb/gemrb/files/3970831/1601CUT3.zip)

The implications of this seem to me a bit larger than this simple script...

**Comment by chilvence** [comment]
FWIW, if it was possible roleplay your own response lines in the game, I would have replied "No, you and _I_ shall meet again"

**Comment by lynxlynxlynx** [comment]
Let's just try with manually ending the mode if the runner selfdestructs.

**Comment by chilvence** [comment]
I tried various different things in the original, adding some more script functions after DestroySelf() (didn't work)

I removed the EndCutsceneMode() entirely. The game still went back to normal, so your suggested fix sounds like how was originally working in the first place.
