### ISSUE TITLE
Cache and Variables class design

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#534]
A perhaps irrelevant TODO that survived since 2006:
> The Cache and Variables classes could be rewritten to incorporate the release function more smoothly (use templates?)

**Comment by bradallred** [comment]
c++11 brings a lot of new tools to the table. It even provides a hash map now if we were so inclined to use it.

**Comment by lynxlynxlynx** [comment]
Closing stale report from the old TODO file.
