### ISSUE TITLE
[feature] pst: was APP_BUDDY used?

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#536]
> we're not using APP_BUDDY anywhere (another pst specialty), just setting it. Check how other AppearanceFlags are used and try pissing others (of the same group) off on death.

The old speculation was that this was used in a similar way as teams/shout/help, so if you attack one member of a gang, everyone gets hostile. If the note placement is correct, actors in the areas of Buried Village have this set.

**Comment by caillean7** [comment]
> Bit 15: Turn all nearby creatures party-hostile when calling Help()

Do you mean this flag? If so, then no - did a extended search in NI, no creatures having this set.

**Comment by lynxlynxlynx** [comment]
Yes:
`#define APP_BUDDY        0x8000      //npcs will turn hostile if this one dies`
It can be set by the auto_buddy ini key, but that's not used either.

**Comment by caillean7** [comment]
> Bit 8: Increment team death counter (KILL_team)

That sounds more like this one, NI calls it "Track team death", but this one is used by many actors.

**Comment by lynxlynxlynx** [comment]
Here's how you can convert the values or get one from the bit number (assuming they are numbered from 0):
```
$ python
Python 2.7.16 (default, Apr  9 2019, 04:50:39) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 1<<1
2
>>> 1<<12
4096
>>> hex(1<<12)
'0x1000'
>>> hex(1<<13)
'0x2000'
>>> hex(1<<15)
'0x8000'
```

**Comment by caillean7** [comment]
Huh, usually I use the calculator when I have to convert some numbers - and that's a BIG when, of course :D But that's probably quicker. I'll write into my 'special notebook', thanks!

**Comment by lynxlynxlynx** [comment]
So, what's left to do is to see if the auto_buddy ini key worked in the original. It's present in the exe, but perhaps the scripting obviated the need to use it. Only testing can show. If it didn't work, we can remove some code and document it, otherwise we might as well implement it.

**Comment by caillean7** [comment]
After refreshing long repressed memories about that bit shifting, I added that attribute to the zombie workers in the starter area of PST. Attacked them. The others did not go hostile. So looks like this is doing nothing.

**Comment by lynxlynxlynx** [comment]
Thanks, closing.
