### ISSUE TITLE
Does the Mordenkainen's Force Missiles spell work properly?

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#538]
There was a note on the forums from Bubb, about how it deals damage:

> I can confirm that it is hardcoded. The Mordenkainen's Force Missiles projectile will inflict a 5-foot damage effect equal to the casters level, applied directly by the engine.

**Comment by caillean7** [comment]
The 5 ft. damage is secondary to the actual missile damage, and really is equal to the caster level on the original. It's missing on GemRB currently. The missiles themselves (amount / damage) look good, so it just needs implementing the area damage with reflex save for the targets in range.

**Comment by lynxlynxlynx** [comment]
Did you try in both games?

**Comment by caillean7** [comment]
Ah, sorry, just IWD2, didn't see IWD1, will do that now.

**Comment by lynxlynxlynx** [comment]
No need then, since the report was from iwdee.

**Comment by caillean7** [comment]
Ah, no big deal, the same as for IWD2, it misses the area damage on GemRB.

**Comment by lynxlynxlynx** [comment]
Ok, this is relatively simple thing to fix then:
- reuse or create a projectile that affects everyone in 5" radius
- create a spell with the appropriate damage and above projectile
- modify gemrb/unhardcoded/how/mfmiss.pro with DLTCEP and add the spell as the "success spell"
