### ISSUE TITLE
[bug] PST Level up : TNO Ability point upgrade window appears in unexpected conditions

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#540]
If TNO is the selected character, but another character is selected while in the inventory window etc, the level up script doesn't seem to care and jumps to the screen that gives TNO ability points.

**To Reproduce**
1:Wait for any NPC to have enough XP to level up
2: Select TNO in the main game window (or select all characters?)
3: Open the record window
4: Select the character that is to be leveled up
5: Level up. Now the UI will presume that it is TNO who is being leveled up, instead of the character selected while in the record window, and you will be able to give him ability points

It appears from what I can tell that the correct character is actually leveled up properly all the same, but the TNO does get ability points that haven't been earned.

**Comment by lynxlynxlynx** [comment]
How about if you change gemrb/GUIScripts/pst/NewLife.py around line 70, GemRB.GameGetFirstSelectedPC to GemRB.GameGetFirstSelectedPCSingle ?

**Comment by chilvence** [comment]
Changing it to `` pc = GemRB.GameGetSelectedPCSingle () `` appears to fix this one, there was no GameGetFirstSelectedPCSingle but I assume that is what you meant :) 

Tried all sorts of paging back and forth to try and upset it, but it seems it was as simple as that one line.
