### ISSUE TITLE
[bug] PST Worldmap travel, only a very limited number of exits should be allowed

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#541]
The original game limits travel by worldmap specifically to the hive overland areas, unlocked after you reach the lowerward (which happens correctly) , and once you move on to the outlands it is unused again until you return to sigil. There are only two overland areas at most in all the later chapters so it would have been redundant.

These are the areas and exits that are supposed to allow it:

AR0100 (flophouse) : to0300 , to0200 , to0101 
AR0101(ragpicker sq: to0100
AR0200 (mortuary) : to0100 , to0301, to0400
AR0300 (market): to0100, to0301, to0400
AR0301(alley of angles): to0200 to0300
AR0400(smouldering corpse bar) : to0200 to0300
AR0500(lower ward) : to0405 to0600
AR0600(clerk's ward): to0500

I would guess this was probably just a list of exits in the original game that would be checked whenever a travel trigger is activated.  A text search using IDA finds this exact list near a lot of references to F:\Torment\Source\baldur\CGameArea.cpp'

**Comment by lynxlynxlynx** [comment]
How does the modron cube play into this? Weren't you able to travel everywhere with it?

**Comment by chilvence** [comment]
That was done by dialogue choices from the portal gem item, I think it handles its own deactivation once you leave Sigil if I remember correctly

**Comment by lynxlynxlynx** [comment]
So it didn't bring up the world map?

**Comment by chilvence** [comment]
No, its all in the DLG, pretty basic

[000000200-Pst Modron Maze.zip](https://github.com/gemrb/gemrb/files/3984800/000000200-Pst.Modron.Maze.zip)

It's the first item in TNO's inventory here if you want to try it out. It is actually much more useful than the worldmap since it lets you escape from any area and reach more areas directly
