### ISSUE TITLE
[bug] iwd uses wrong casting sounds

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#543]
Continuing the investigation post #518.

Better mapping:
https://github.com/gemrb/gemrb/compare/master...caillean7:master

What are the open issues after that?

I noticed that the numbers are just odd in there. Are the even one of the other gender, something else?

**Comment by caillean7** [comment]
The even ones are alternative sounds of the same school and gender, a different recording. I think they are unused on the original, though.

**Comment by lynxlynxlynx** [comment]
Ok. Does your pull fix everything or is there some other problem too? For a second I got the impression that maybe the school ids are different in iwd.

**Comment by caillean7** [comment]
No, problem is that no matter what I do with that table, it has no effect in game. As if it would look up another table, not this one.

**Comment by lynxlynxlynx** [comment]
You do have HoW installed, right?

**Comment by caillean7** [comment]
Yes.

**Comment by lynxlynxlynx** [comment]
Works for me. MFF without: veritas ..., with: credo ...

Look at the gemrb log to see where cgtable is being plucked from, you have a stale file somewhere.

**Comment by caillean7** [comment]
On IE MFM has "Incertus, Pulcher, Imperio".

In my GemRB.log it says "Found 'cgtable.2da' in 'GemRB Unhardcoded data'" - so that would mean /usr/local/share/gemrb/unhardcoded?

**Comment by lynxlynxlynx** [comment]
If you installed gemrb without specifying a destination, then yes. If you're running from the build dir (not the installed binary), then no, it would be the one in the sources.

**Comment by caillean7** [comment]
No, I installed it, more convenient this way. I also tried with the tables in the override, plus I checked on all 3 installations of IWD1 I have. Am I crazy?

**Comment by lynxlynxlynx** [comment]
You can see what file it's using through strace:
`strace gemrb -c ... |& grep /unhardcoded`

**Comment by caillean7** [comment]
Doesn't return anything. Am I making you crazy? If you're sure it's fine, then please close, no need to put you on a wild goose chase because there's some zombie file around here.

**Comment by lynxlynxlynx** [comment]
How do you run it? I get matches already in the main menu:
```
$ strace gemrb/gemrb -c how.cfg |& grep /unhardcoded/.*cgtable
stat("../gemrb/unhardcoded/how/cgtable.2da", {st_mode=S_IFREG|0644, st_size=455, ...}) = 0
stat("../gemrb/unhardcoded/how/cgtable.2da", {st_mode=S_IFREG|0644, st_size=455, ...}) = 0
```

**Comment by caillean7** [comment]
OMG, the package wasn't installed - say nothing, please.

It shows 
`/usr/local/share/gemrb/unhardcoded/how/cgtable.2da`

This is my edited file:

```
cat /usr/local/share/gemrb/unhardcoded/how/cgtable.2da
2DA V1.0
*
            RESREF    SOUND
UNUSED0     *         *
UNUSED1     *         *
UNUSED2     *         *
UNUSED3     *         *
UNUSED4     *         *
UNUSED5     *         *
UNUSED6     *         *
UNUSED7     *         *
UNUSED8     *         *
NECROMANCY  NecroCG   13
ALTERATION  AlterCG   15
ENCHANTMENT EnchaCG   09
ABJURATION  AbjurCG   03
ILLUSION    IllusCG   01
CONJURATION ConjuCG   05
INVOCATION  InvocCG   11
DIVINATION  DivinCG   07

```

**Comment by lynxlynxlynx** [comment]
For me changes work ... but only for two versions. Time to slow time down.

**Comment by caillean7** [comment]
Are we going to manipulate the laws of physics or is this your way of saying "I've got enough, I'm going to bed"?

**Comment by lynxlynxlynx** [comment]
I ran the debugger. :P It's fixed now, you can sync and see if you're happy with your table. If you are, please open a pull request.

**Comment by caillean7** [comment]
Poke out your tongue at me all you want, I'm just happy I'm not crazy or it's nothing like this thing with the shadows again :smiley:
