### ISSUE TITLE
[feature] was objectRect/ADDITIONAL_RECT actually implemented?

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#548]
It's usedin iwd/iwd2/pst. Here is a brief discussion:
https://www.gibberlings3.net/forums/topic/29506-solved-iwd2-object-types-edit-nearlocation/

We already parse it and store it in Object's objectRect. We need to test if this limiting works or not. Easiest to just construct a contrived example.

to find uses: `grep -Erin '[^(]\[[^.]+\.[^.]+\.[^.]+\.[^.]+\]'`

**Comment by caillean7** [comment]
According to the discussion on G3 you linked this should return true only if Player 1 is within the given coordinates:

`Exists(Player1[110.520.190.600])`

I added a block to Targos Docks' area script to print some string with coordinates of a small area on one of the piers, but on IE moving Player1 there won't trigger the message (on GemRB it currently spams the string no matter where player 1 is located in the area). If this wouldn't work, it'd probably explain the above example from AR6400.bcs:

```
IF
	Exists(Player1)
	Or(3)
		Exists(Player1[110.520.190.600])
		Exists(Player1[720.450.830.530])
		Exists(Player1[350.380.440.440])
THEN
```

**Comment by lynxlynxlynx** [comment]
Hmm, it's odd that they need to check without the rect too if that was supposed to work. Since the action that follows is insta-death, it should be easy to recheck (maybe it's even in a walkthrough doc somewhere).

But you're saying your test didn't work on IE, which would just skip these blocks then. Can you share the snippet you used?

**Comment by caillean7** [comment]
That's what I added to AR1000.bcs:

```
IF
	Exists(Player1[2052.977.2165.1049])
THEN
	RESPONSE #100
		ActionOverride(Player1,FloatMessage(Player1,511))  
END
```

I figured that the numbers have to be the coordinates of 2 diagonal points? That would be an area directly off Herons' ship.

**Comment by lynxlynxlynx** [comment]
Yeah, most likely top left and bottom right. If you change it to [0.0.3000.2000], does it trigger?

**Comment by caillean7** [comment]
It does. Did I use wrong coordinates?!

**Comment by lynxlynxlynx** [comment]
I don't have any clever ideas, so the fastest way that comes to mind is bisection. Since [0.0.3000.2000] works, how about [0.0.1500.1000] or [0.0.750.500] ... or [1500.1000.3000.2000] or [2000.1500.3000.2000] ... you get the idea, just shrinking the rect in various directions as far as you can, to get the smallest possible working one.

**Comment by caillean7** [comment]
Alright, I'll have a go at it tomorrow afternoon then.

**Comment by caillean7** [comment]
So it seems the first two coordinates have to be 0 for this to work. E. g. [0.0.150.50] works, [1.0.150.50] or [0.1.150.50] won't. If the first values are zero, it works as intended. I tested this in two different areas with different rectangle sizes.

**Comment by lynxlynxlynx** [comment]
Huh, interesting. I wonder if they're coordinates at all. Did you at least manage to confirm the other two are a coordinate pair?

**Comment by caillean7** [comment]
What I saw was consistent with the theory that the second two numbers are the bottom right point of that rectangle. So the string display triggered as expected when I moved Player 1 in the area in question. Making the rectangle smaller worked. I'd say it really looks like coordinates, the whole thing is just only semi-useful because of the limitations of the first values... I wonder if something in game actually relies on this to work. Oh, and I noticed the string display didn't go away if I left the target area again, so once it's triggered, it stays on.

**Comment by caillean7** [comment]
> I wonder if something in game actually relies on this to work

Searched in the game scripts, there's stuff like 

```
See(Player1[0.0.10000.10000],0)
See(Player2[0.0.10000.10000],0)
See(Player3[0.0.10000.10000],0)
See(Player4[0.0.10000.10000],0)
See(Player5[0.0.10000.10000],0)
See(Player6[0.0.10000.10000],0)
```
or
`MoveViewObject([PC][0.0.10000.10000],20)`

**Comment by lynxlynxlynx** [comment]
But whyyyy? :) 0-10k is bigger than most, if not all, areas, so how is `See(Player1[0.0.10000.10000],0)` different from `See(Player1,0)`?

It would be helpful to try that AR6400 area, since it's double interesting and the coords don't start with 0.

**Comment by caillean7** [comment]
Heh, who knows, it seems like a waste of space, really. I've been to AR6400 - not sure what's supposed to happen - you mentioned ChunkCreature means instant death? Didn't happen...

**Comment by lynxlynxlynx** [comment]
Were you within the rect though?

**Comment by caillean7** [comment]
AR6400: It's the one with the floating islands, where you have to activate these thingies in the shape on a pentagram. The coordinates the area script checks for fit to the 3 floating spaces. I moved there. But even if the script also checks for Exists(Player1) without any coordinates it fails to trigger on the original. I changed the ChunkCreature to FloatMessage to see what happens, doesn't work. Not sure why - on GemRB it works... :woman_shrugging:

**Comment by lynxlynxlynx** [comment]
GemRB ignores this rectangle, so we see Exists or Exists or Exists or Exists with the same parameters. So this is actually a blocker for #505 too.

So to sum it up, it is a rect as always thought, but if the first corner coordinates are not 0.0, it matches nothing and fails the whole trigger. :-1:

**Comment by caillean7** [comment]
Will you implement it like this, too, then?

**Comment by lynxlynxlynx** [comment]
We have no choice ... besides a research breakthrough showing it's more complicated and the first values have some magic meaning; though by now it would likely need looking at the disassembly and finding the relevant code.

Looks a bit like hastily disabled code with some fallout.

**Comment by lynxlynxlynx** [comment]
Interestingly, there are some uses with -1 as the final coordinate:
```
pst/0512kela.baf:31:    FloatMessage([0.0.0.0.0.0.FWORKER_2][10000.10000.0.-1],17014)
pst/104cblac.baf:47:  NearLocation([PC][658.215.400.-1],[658.215],15)
iwd2/50spiri1.baf:5:  !Exists([ENEMY][70.1590.5.-1])
```

I hope it has no special significance. Same for the inverted order of the coordinate pairs!?

Roughly a hundred start with non-zero out of roughly 700. An uncomfortably big ratio. 

PST ar0512 seems to work fine, so in pst, we shouldn't fail non-zero starting coords. pst/ar1400.baf looks like it should also work, though most (all) spawns are defined in ar1400.ini. @chilvence can you try removing all the blocks with CreateCreature from ar1400.bcs and retrying the area in the original (the amount of spawns shouldn't change)?

In HoW, all uses are "[0.0.10000.10000]", so basically it doesn't matter.

Current plan:
- if x1 > x2 || y1 > y2 -> ignore rect
- if iwd2 and x1 or y1 are non-zero, match nothing
- else filter within rect

**Comment by chilvence** [comment]
I also emptied the spawns from the ini file to be sure, if I remove the varg blocks then I don't get the big ambush outside the crypt of dismemberment door

**Comment by lynxlynxlynx** [comment]
Thanks, so the feature appears to work as expected in pst.

**Comment by chilvence** [comment]
Just to be clear, you did mean test the original game and not gemrb?

**Comment by lynxlynxlynx** [comment]
of course. :)
