### ISSUE TITLE
[bug] subviews build problems

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#550]
After the changes in #441 subviews doesn't build for me any more. As expected it doesn't with sdl1, but neither does sdl2. 

Is opengl now required? GLFloat and similar is what's undefined when it tries to build GLSLProgram, since the driver includes it unconditionally. Removing the include fails too, since the stencilShader requires it.

Isn't the 'raw' version supposed to be sdl-only?

**Comment by bradallred** [comment]
yes, we need to #ifdef that include. `stencilSuhader` is just a pointer so you can get by with just declaring the class without its definition `class GLSLProgram;`

**Comment by bradallred** [comment]
see what you can do with that. we will have to conditionally include the .cpp in cmake or something for the `OPENGL_BACKEND` build.

**Comment by lynxlynxlynx** [comment]
Thanks, it builds now. The cmake change is trivial, in gemrb/plugins/SDLVideo/CMakeLists.txt, but I don't have gl set up on that machine to test.
