### ISSUE TITLE
[bug] PST AR0500: Cutscene attached to Yi'min leaves you hanging

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#553]
[000000214-GRB Malignant Mendacity.zip](https://github.com/gemrb/gemrb/files/3991999/000000214-GRB.Malignant.Mendacity.zip)

Yimin should be nearby to you if you load this save (he seems to move about a bit but he is usually always near the slave market). If you talk to him and accept his offer to help you recover memories, he will lead TNO to a dark alley, and the two of them will start an eternal staring contest. I believe TNO would certainly win because he will eventually outlive the Githyanki, but I haven't put that to the test in game.

What is actually meant to happen is 5-6 Githyanki soldiers suddenly appear, and promptly try to murder you.

It might not necessarily be a problem with the actual cutscene that is last played, in the script it seems to refer to actors that never appear, 

```
IF
	True()
THEN
	RESPONSE #100
		CutSceneId("GithSol1")
		TimedMoveToPoint([3247.778],150)
		FaceObject(Protagonist)
		StartCutScene("0500cut3")
END
```

This 'GithSol1' is not spawned along with the rest of the ambush, which is probably why 0500cut3 is never started

It is not *known* to me what is supposed to cause these actors to spawn, only that they appear only in the area's INI file, starting line 161

**Comment by lynxlynxlynx** [comment]
it looks like yimin's script is supposed to set Githzerai_Ambush_Spawn to 1 before 0500cut2 is started.
IniSpawn::CheckSpawn is what is called each tick to see if something should be spawned.

```
[ambush]
critters    = gith1,gith2,gith3,gith4,gith5,hamrys
interval    = 15

/.../

[gith1]
spec        = githsol1
spec_var    = GLOBAL::Githzerai_Ambush_Spawn
cre_file    = GithSol
script_name = githsol1
script_general  = 0500gith
dialog      = dalmidil
spawn_point = [2986.739]
;facing     =
ignore_can_see  = 1
```

Perhaps we're updating last_spawndate too soon — it looks odd that it is unconditional. Does this help: http://sprunge.us/bk7fOB?diff

**Comment by chilvence** [comment]
It might be a few days before I can test this, I am traveling to visit family.

**Comment by lynxlynxlynx** [comment]
It's not enough, so a deeper look is needed.
