### ISSUE TITLE
messagewindow usability issues

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#560]
> - The text info in the inventory doesn't disappear when you click/do something else, making it difficult to work out exactly which items are causing the text. It also isn't filtered, so any message can be displayed. How did the originals behave?
> - messages while the inventory or the messagewindow are hidden should still be sent to the text area for later viewing

**Comment by bradallred** [comment]
are you sure about that second point? `DisplayMessage::DisplayString` looks like it just sends the message to both. I guess the problem is that sometimes `GetMessageTextArea` returns NULL? I think this part at least works on the subviews branch if not on master.

**Comment by lynxlynxlynx** [comment]
It requires some testing if we want to match the original, hence the research tag, but it also makes sense by itself.
