### ISSUE TITLE
how: Couldn't find 'walksnd.2da'

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#565]
Icewind dale is missing footstep sounds, since nobody mapped them yet, which sounds play on what terrain. 

The walksnd table needs to be created in `gemrb/unhardcoded` (in iwd/ and how/ dirs) — you can check `gemrb/unhardcoded/iwd2/walksnd.2da` and `gemrb/unhardcoded/bg2/walksnd.2da` for inspiration. Maybe either of those is fine already.

**Comment by caillean7** [comment]
I created the two files using the BG2s and IWD2s as a template, including all WAL_*.wav's the game has. Two from the HoW 2da are ToTLM-only, since my installation without ToTLM installed hasn't got them.

https://github.com/gemrb/gemrb/compare/master...caillean7:master

I also noticed that IWD2 has some wav files that its 2da doesn't include yet, I could update that, too?

**Comment by lynxlynxlynx** [comment]
You mean other animation slots/ranges that aren't in walksnd yet? Sure.

**Comment by caillean7** [comment]
Not animations, just the existing wav files are not assigned. E. g. IWD2 has a sound for bears, which is WAL_12.wav, but currently the  2da lists SOUND (some sort of placeholder, I think). The sound files are all the same in the games, so this would be simply c&ping entries from the BG2 file.

**Comment by lynxlynxlynx** [comment]
Whatever works ingame. :man_shrugging:

**Comment by caillean7** [comment]
Were only 3 sounds missing, I tested them ingame. PR?

**Comment by MarcelHB** [comment]
Probably works ingame (if you refer to IWD2) because I wired some of this into the code some years ago. :grin:

**Comment by caillean7** [comment]
Yep, IWD2. Well, the sounds for bears, spiders and carrion crawlers appeared unused. E. g. spiders were using usual footstep sounds. After changing their entry in the 2da they sound like on the original.

**Comment by lynxlynxlynx** [comment]
Ship it. :)

The SOUND entries are there, since we do some randomization — there are apparently several available sounds, just like with eg. armor twangs. If that's wrong, it's something for the dedicated bug #130 .

**Comment by caillean7** [comment]
Done. Sounds a bit off still, especially the carrion crawler, even though it uses the correct wav file.
