### ISSUE TITLE
[subviews] Wrong tinting for some char animations/stances

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#571]
I noticed how my PC (IWD2; dark elf) changed his brightness by some pattern:

![anim_colors](https://user-images.githubusercontent.com/238558/71633303-ae63d380-2c13-11ea-9a3d-ed63fe18d31c.jpg)

1. If he looks southwards, he looks as dark as the light map requests. (left)
2. If he looks northwards/sidewards, he appears much brighter/golden. (center)
3. But if I take away his staff, he is dark again. (right)

Case 2 does not occur on master; this pattern looks a bit odd anyway.

**Comment by MarcelHB** [comment]
Ok, that's the currently malfunctioning tinting in OGL (#441). Whatever strange effect it fails to cover then. :)

**Comment by MarcelHB** [comment]
So, in IWD2, there is currently the following twist:

1. If you start the game at night, there is currently no global blue tint. Little suprise.
2. If I take `v_color` (that's your `SDL_SetTextureColorMod` value) into the fragment shader and multiply it by with `color`, blue tint is back but infravision does not work: The actors should be red/white (IWD2) through the darkness. So something about tinting is not adding up correctly so far.

If you have an idea @bradallred, feel free. I must defer further investigation for a day.

**Comment by MarcelHB** [comment]
Ok, the infravision is actually a different story, tbd in another issue.

**Comment by MarcelHB** [comment]
Ah, infravision not working looks like a merge issue (global tint still applied twice - once too late, was changed at some point years ago in master).

**Comment by bradallred** [comment]
I've noticed some other anomalies after adding the SpriteShader. Maybe this fixes those as well, but I kinda doubt it. I'm to laymen in my OpenGL knowledge to say exactly what is happening, but the end solution might be to just combine both shaders.
