### ISSUE TITLE
[subviews] Actor circles are sometimes dark

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#575]
On the generic video path of SDL2 (in OpenGL, it worked good), sometimes the circles of the (N)PCs shift to dark, flicker back to their brighter color, and back.

Here is what it looks like on IWD2, the non-selected party members are almost gray.

![group_circles](https://user-images.githubusercontent.com/238558/71752781-a9578c00-2e80-11ea-8e1e-fc39a19def3e.jpg)

**Comment by bradallred** [comment]
this is one of the anomalies I was referring to. It will go away when I switch back to software rendering.

**Comment by bradallred** [comment]
are you sure your report isn't backwards? my experience was it was OpenGL with the wrong color circles.

**Comment by MarcelHB** [comment]
I will double check.

**Comment by MarcelHB** [comment]
No, for me it's still like initially reported.

**Comment by bradallred** [comment]
interesting, I'm unsure of why that might be. I cannot see anything wrong, tho maybe it is specific to area lighting. Any way you can bisect to see when it broke? or has this been a problem for a long while?

**Comment by MarcelHB** [comment]
Seemed to be good in #397, it try a revision around that time as a lower end.

**Comment by MarcelHB** [comment]
Uhh, have fun: 93c8791b49f559cdbe07deb28d104b15ee9d484c

**Comment by bradallred** [comment]
well, at least it has nothing to do with (our) OpenGL code. I'm mostly nervous that I haven't seen this _except_ when the OpenGL driver was using the SpriteShader. 

Does it depend on the light map or time of day maybe?

**Comment by bradallred** [comment]
I'll force the SDL2 OpenGL backed later when I'm home to see if maybe its the use of Metal on Mac why I haven't seen it except with OpenGL. That actually seems somewhat likely now. maybe you can check d3d on Windows?

**Comment by bradallred** [comment]
yeah, man I can't repro this even with the opengl hint which I have verified is forcing SDL2 to use it. Are you sure you have a clean build of the video driver?

**Comment by bradallred** [comment]
I mean, if it is a problem on that commit before we added our own GL code, and it works fine on mac OpenGL/Metal then it starts to feel like a bug in SDL.

**Comment by MarcelHB** [comment]
Yes, it looks good on Linux OpenGL. So I guess when I start that on Windows with the non-GL path, this ends up in ... D3D. I can verify this later, but I guess that's why only I observe this right now.

**Comment by bradallred** [comment]
hmmm what version of SDL on Windows?

might be worth trying both the d11 and d3d hints (I don't remember their exact values)
it might also be worth building SDL from source and seeing if the problem is corrected.

**Comment by MarcelHB** [comment]
It's v2.0.10. Explicit `direct3d` produces the error, `direct3d11` falls back to `direct3d` on my machine.

But, when I build v2.0.11-dev from scratch: poof, error's gone.

**Comment by bradallred** [comment]
Ok, then lets call this an SDL bug. unless it is manifesting is worse ways I don't think we need to trouble ourselves. By the time we merge with master I'll wager 2.0.12 will be out anyway.

If somebody stubles upon what sorcery happened we can of course take a look about making it work for 2.0.10

We might also want to consider adding a config setting for forcing which SDL backend gets used so people can work around issues like this if they come up in the future.
