### ISSUE TITLE
[subviews] Long tooltips have hard clipping

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#576]
May I introduce the most clichéd sample of German in the game: _Barbarischer Kampfrausch_ (rage). Problem: The toolbox has a hard clipping on this string.

![tooltip](https://user-images.githubusercontent.com/238558/71757464-7cae6f00-2e96-11ea-8f0c-cc85ba46147e.jpg)

If you measure the actual pixels it's a width of 138px. But looking at `Tooltip::Draw`, I get the following values:

- `textWidth`: 151px
- `rgn.w`: 155px
- `bgclip.w`: 156px
- `MaxTextSize().w`: 252px

So, on paper this looks sufficient for both the missing chars to the left and right, as well as the borders. I spent some time to figure out what's going on but failed for today.

**Comment by bradallred** [comment]
this is likely the buffer not being large enough. Same issue as some of the item icon cursors. Increasing the size should fix both.

**Comment by bradallred** [comment]
relevant code:

```
// NOTE: TT width is 138 = 128px (bg) + 10px (right curl) for BG2
// FIXME?: update this to the widest width needed for all games (if different)
cursorBuf = vid->CreateBuffer(Region(0,0,138,64), Video::RGBA8888);
```

**Comment by MarcelHB** [comment]
We can increase the value, we can try to make the string fit into two lines, or somehow try to get the upper bound from some smart calculation?

**Comment by bradallred** [comment]
I don't know that there is such a method. As I said, the inventory icons (things like halberds are apparent) have the same issue and require much more height.

Just increasing the height should allow the text to wrap. We could easily ensure that the height is enough for 2 lines of text in all games by checking the font line height, but that wouldn't solve the inventory icon issue.

**Comment by MarcelHB** [comment]
To address both of them, what's the cost of taking the whole screen width as memory dimension? Pro: will always have enough to physically fit on the screen, con: probably unused for 80% in 99% of cases, more to allocate, more to clear, yet I don't know what languages and strings are out there to handle potentially. Other idea: what about calculating string width + borders, lines, and then request/resize a fitting video buffer?

On the other hand, are there cases where to constraint the width in the hard way, i.e. forcing linebreaks or wrapping because otherwise things start to overlap, look bad, ...?

**Comment by bradallred** [comment]
cost is relative to the resolution, but software rendering would probably suffer a lot from drastically oversized buffers. The text tooltips shouldn't be a problem; it would be silly to have tons of text. even your example above would easily fit by just bumping the height up a tiny bit and letting the text wrap. It looks like the BG can accommodate 2 lines anyway, which I think is the reasonable maximum for tooltips.

**Comment by bradallred** [comment]
hmmm, maybe that text doesn't technically fit in 2 lines. The buffer should already be large enough for that.

1. How does the original look (one or 2 lines)?
2. are we using the correct font?

if it is the right font and it should wrap, then the problem is somewhere else like in Font.cpp. You should measure the background image and get the metrics for the font to see why it isn't wrapping.

**Comment by MarcelHB** [comment]
Screenshots first.

IE:
![tt_original](https://user-images.githubusercontent.com/238558/71771570-90f97700-2f3d-11ea-8ece-09295a255894.jpg)

master:
![tt_master](https://user-images.githubusercontent.com/238558/71771571-99ea4880-2f3d-11ea-8546-5f64561bd1ce.jpg)

**Comment by MarcelHB** [comment]
TOOLTIP.BAM of IWD2 is 256px wide.

**Comment by bradallred** [comment]
we should try 256x256 and see how that works

**Comment by MarcelHB** [comment]
256 (bg) + 6(borders)x64 for the video buffer looks good. But if you speak on a quadratic dimension, do you think of some more lines?

**Comment by bradallred** [comment]
no, the added height is to fix inventory icons like halberds in BG2. We may not need 256, but we need something larger for those.

**Comment by MarcelHB** [comment]
Do you have an item code? I just wonder what these halberds are, so I'd test that. :wink:

**Comment by MarcelHB** [comment]
Ok, I didn't get you refer to the pickup cursors of halberts in the inventory... 57px in height is what I get for the simple one. Anything bigger in mind?

**Comment by bradallred** [comment]
I don't recall exactly which item I saw this issue on (it would have been BG2 tho), we can just leave the height alone for now if we don't know what we are changing it for. we can always open a new issue when it is encountered.
