### ISSUE TITLE
[subviews] SDL1.2 won't compile on GCC

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#577]
Eh, I tried to make SDL1.2 with your latest changes running, and failed:
```cpp
./gemrb/plugins/SDLVideo/SDLSurfaceDrawing.h: In function 'void GemRB::DrawHLineSurface(SDL_Surface*, GemRB::Point, short int, const GemRB::Region&, const GemRB::Color&) [with bool BLENDED = true]':
./mingw64/include/SDL/SDL_stdinc.h:282:25: error: this statement may fall through [-Werror=implicit-fallthrough=]
  282 |         case 0: do {    *_p++ = _val;  \
      |                         ^
./gemrb/plugins/SDLVideo/SDLSurfaceDrawing.h:185:3: note: in expansion of macro 'SDL_memset4'
  185 |   SDL_memset4(px, c, numPx);
```

Turns out that `SDL_memset4` consists of a macro that is incompatible to the current fallthrough settings in GCC v9.2.

Is that SDL-memset crucial to use here? If so, we probably need to scale down the fallthrough strictness for that plugin.

**Comment by bradallred** [comment]
its not crucial per se, but memset4 is 4x faster than memset :)

this is a function that runs a lot now with how the filled polygons work, which are also what make the sprite masks so its definitely one that you should feel a difference if your system actually provides a _real_ memset4. some just hit a fallback which is what you appear to be seeing, if gcc/linux doesn't have a memset 4 we can ifdef it for them.

**Comment by bradallred** [comment]
I just realized SDL 1.2 has a different implementation of `SDL_memset4` than SDL 2 so no platform benefits from a real memset4. We should probably copy the SDL2 implementation into our code.

**Comment by MarcelHB** [comment]
Well, for my Linux computer, `SDL_memset4` is about five times slower for large memory than whatever `memset` I get linked without specifying any optimizations. Same goes for the SDL2 version.

**Comment by MarcelHB** [comment]
If you really want to write 4 bytes, the SDL version is 15% better than the most naive way of writing this in a loop. If you unroll your loop for grouping 4 values/16 bytes per iteration, we already twice as good as SDL again.

And what looks even more promising since we're C++11 now: `std::fill`

**Comment by MarcelHB** [comment]
So, we should either switch between that Maccish `memset_pattern4` and a loop like this (instead of copying that SDL stuff), or test if we can use STL containers and algorithms instead.

**Comment by bradallred** [comment]
we don't need or want a container, but `std::fill` is probably a good replacement because it is a template and that will allow for a lot of compiler optimizations. it would probably be able to vectorize at least as well as `memset_pattern4`.

feel free to send a pull request for that.
