### ISSUE TITLE
[bug] BG1 - Potion of Heroism animation misaligned

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#582]
**Description**

See #563 :

The animation for the Potion of Heroism is drawn below the character, it should overlay them:

![PoH](https://user-images.githubusercontent.com/54738589/71831346-fe75e680-30a8-11ea-8d71-fc25f320b4f8.jpg)

POTN09 and fx_visual_spell_hit

**Comment by lynxlynxlynx** [comment]
This is likely the same bug as #481. Adding 40 to the height  ixes it for this potion and some others (healing), but it looks wrong for invisibility (unsure) and maybe hold?

They're using BAMs, so there's no VVC to hold extra info. Ergo it must be all in the effect (0x8d VisualSpellHit / Lightning effects). Can you check various potions and spells using this effect, so we get a good list of all that are wrong and not wrong? 

Increasing the height helps, but I don't want to break anything that works already:
http://sprunge.us/4HR2Cz?diff

**Comment by caillean7** [comment]
Check only BG1 or any of the others, too?

**Comment by lynxlynxlynx** [comment]
1 is fine, they use the same stuff.

**Comment by caillean7** [comment]
There's so many items and spells using that opcode - I started testing them one by one, and after every one had that misalignment I continued with making spot checks. It sure looks like they're all affected. I compared the ones you mentioned (Invisibility and Hold Person) to the original, and they are off - the IE draws those effects more at the head of the characters. So, what'cha say - shall I continue, or are we convinced they all need adjusting the height?

**Comment by lynxlynxlynx** [comment]
Hold person doesn't use that effect in my copy, did you mean something else? If invisibility starts higher, then it's not conflicting with the fix (I was testing with the potion, btw).
If you apply the patch, how many problems remain and are any new?

**Comment by caillean7** [comment]
> Hold person doesn't use that effect in my copy, did you mean something else?

No, I have it listed with that effect - both the priest and wizard version of the spell.

As for Invisibilty, I tried the potion, too. I'll recheck my samples with patch now, and see how it looks.

**Comment by caillean7** [comment]
Tested a bunch of spells, potions, ammo, and it looks real good, couldn't find any new problems. Adjusting height by 40 is still a bit too low, using 45 looks like the original.

**Comment by lynxlynxlynx** [comment]
My spwi306 has Play visual effect (215), not Lightning effects (141). Good to know the rest are fine then.
