### ISSUE TITLE
[bug] BG1 - Magical Sleep animation issues

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#584]
**Description**

Split from #563 

> Being magically asleep not using proper stance (lying, at least male human fighter) for the selected actor - eg. stinking cloud induced. Switches properly if you try to do anything, but should happen before.

The lying animation works sometimes, sometimes it doesn't, even for the same characters. Some characters also don't get up if you want them to move after the sleep wears off, the only way getting them back to their feet is teleporting them with Ctrl.+J (Viconia and Imoen in the Mission Pack save every time).

**Comment by lynxlynxlynx** [comment]
This was fixed in #1755, closing.
