### ISSUE TITLE
[bug] BG1 - Black scroll counter in some shops

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#585]
**Description**

Split from #563 

>  //This is especially strange, it happens only in Taerom's shop (blackened scroll counter) [[http://img197.imageshack.us/img197/5888/201212311520071440x900s.png|009]]// RECHECK / STILL Similar thing in Kelddath shop at temple.

![scrl_counter](https://user-images.githubusercontent.com/54738589/71835269-67615c80-30b1-11ea-8d5b-d536b4db529b.jpg)

It's still present for both Taerom and Kelddath (only the party side of the merchant window is affected by this, not the shopkeeper's). I tried Sorcerous Sundries for comparison, there the color was normal.

**Comment by lynxlynxlynx** [comment]
Is it always on the same slot or item? Any pattern at all?

**Comment by caillean7** [comment]
Seems to affect any scroll on any inventory slot.
