### ISSUE TITLE
[bug] BG1 - Werewolf worries

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#588]
**Description**

See #563 

> - ...lycanthropy infection works correctly (however I can replicate it only with one save, strange), turning other party members to greater wolfweres (greaterwolf), however they probably shouldn't drop Peladan as loot ;)

The infection and changing to Greater Wolfweres of the party (not Player 1) works the way it does on the original - it takes a couple of days / multiple rests, but not 25 days as the wiki claims. 
But 

~~- each party member indeed drops a copy of Peladan (the baby, MISC96.ITM)~~ Not a GemRB problem

- their bodies stay visible lying on the ground (they disappear when changing into werewolf form on the original) - this is perhaps related to #583

**Comment by lynxlynxlynx** [comment]
What dialog/script/spell is responsible for this stuff?

**Comment by caillean7** [comment]
DPLAYER2.BCS and DPLAYER3.BCS both have a block that triggers the change:

```
IF
	Global("Infected","GLOBAL",1)
	GlobalTimerExpired("PlayerInfected","GLOBAL")
	!Dead("Mendas3")  // Mendas
	Exists(Player2)
THEN
	RESPONSE #100
		ActionOverride(Player2,ForceSpell(Myself,PLAYER_WEREWOLF_CHANGE))  // SPWI946.SPL (No such index)
		ActionOverride(Player3,ForceSpell(Myself,PLAYER_WEREWOLF_CHANGE))  // SPWI946.SPL (No such index)
		ActionOverride(Player4,ForceSpell(Myself,PLAYER_WEREWOLF_CHANGE))  // SPWI946.SPL (No such index)
		ActionOverride(Player5,ForceSpell(Myself,PLAYER_WEREWOLF_CHANGE))  // SPWI946.SPL (No such index)
		ActionOverride(Player6,ForceSpell(Myself,PLAYER_WEREWOLF_CHANGE))  // SPWI946.SPL (No such index)
END
```

**Comment by lynxlynxlynx** [comment]
SPWI946 has a "Summon: Replace Creature [151]" effect with chunking mode on (param2/type 1). So it's the missing chunking that is the reason for maintained corpses.

As for Peladan, does everyone have that item before or what? I guess the transformation doesn't destroy their inventory in general?

**Comment by caillean7** [comment]
Nobody has Peladan before, he seems to be created during this werewolf change. Every party member gets one, but he's not always created in the stack of their other equipment, sometimes he's ending up separately (see screenshot). The transformation doesn't destroy anything, on the original the party members simply drop everything, too.

![peladan](https://user-images.githubusercontent.com/54738589/71915607-6812f500-317c-11ea-8697-cc5140d5bd0f.jpg)

**Comment by lynxlynxlynx** [comment]
I don't get a match for MISC96 in any bg1 script or dialog, so the only remaining thing are spells — where does it come from?

**Comment by caillean7** [comment]
I'll be damned, the IE creates babies, too. It's in the Greater Wolfwere creature file, you're supposed to rescue the baby from Karoug, who is a Greater Wolfwere, too. This is not a GemRB bug, then.

**Comment by lynxlynxlynx** [comment]
Does this fix the bodies?
http://sprunge.us/W3gvVj?diff

**Comment by caillean7** [comment]
No, they are still present.

**Comment by lynxlynxlynx** [comment]
Hmm, ok. I'll need a save game then.

**Comment by caillean7** [comment]
Just rest once, that should trigger the change.
[888888892-werewolf change.zip](https://github.com/gemrb/gemrb/files/4034996/888888892-werewolf.change.zip)

**Comment by lynxlynxlynx** [comment]
Is one supposed to be able to win this fight (I guess, especially if there's just one other pc), but more importantly, is the transformation supposed to permanently kill the pcs, removing them from the window and making resurrection impossible?

**Comment by caillean7** [comment]
Just tried on the original: seems it really kills the party permanently, the portraits are removed, so you can't resurrect them.
