### ISSUE TITLE
[feature] BG1 - No rest movies played

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#589]
**Description**

- ~BG1 doesn't play rest movies like on the original.~

- The IE also has a window popping up when clicking the rest button: "Are you sure you wish to rest?"

**Comment by lynxlynxlynx** [comment]
gemrb/unhardcoded/bg1/restmov.2da needs editing to have the movies you miss (compare to the bg2 table). See gemrb/docs/en/Tables/restmov.txt for some docs.
We have a comment saying only bg2 does them, but prove us wrong. :)

The rest button is visible in several windows; do all of them have the pop up?

**Comment by caillean7** [comment]
Could it be that they added the movies to the GOG version? That's what I have installed, and it definitely has the movies.

Yes, all windows show the pop up.

**Comment by lynxlynxlynx** [comment]
It'd be odd, maybe TotSC added it and people still play without it:
https://youtu.be/vdvz8Pnuvsw?t=518

**Comment by caillean7** [comment]
It has no tavern rest movie, only the camping one! I'll take a look at that 2da.

**Comment by caillean7** [comment]
The column for the rest movies already has an entry 'REST' and that's also the name of the movie: https://github.com/gemrb/gemrb/blob/master/gemrb/unhardcoded/bg1/restmov.2da
So according to this, it should play the camping movie for every type, except that it doesn't. Could there something be missing in the code?

**Comment by lynxlynxlynx** [comment]
Game::GetDream and Game::RestParty have it. Perhaps the areas like the type info? If you add REST to the first row, does it magically fix it?

**Comment by caillean7** [comment]
Yep, it does.

**Comment by lynxlynxlynx** [comment]
s/like/lack/, but cool. You know what to do. :)

**Comment by caillean7** [comment]
Okay, will do. Then we'll have camping movie everywhere.

**Comment by lynxlynxlynx** [comment]
You mean this one triggers also in inns? Then forget about it.

**Comment by caillean7** [comment]
Yes, it triggers in inns, just tried. Then we'll have to live without rest movie in BG1.

**Comment by lynxlynxlynx** [comment]
It did in inns already before. Now only the are-you-sure popup remains.

**Comment by lynxlynxlynx** [comment]
Eh, bg2 doesn't have this pop-up, so I decided to just skip the whole thing. IWDs suggest the same, though I wasn't in a proper area when testing.
