### ISSUE TITLE
[subviews] Compiler issue in BIKPlayer

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#592]
When trying to compile BIKPlayer with GCC v9.2 on Windows r/n, I get this error:
```cpp
In file included from ./gemrb_subviews/gemrb/plugins/BIKPlayer/rational.cpp:31:
./gemrb_subviews/gemrb/plugins/BIKPlayer/rational.cpp: In function 'int av_reduce(int&, int&, int64_t, int64_t, int64_t)':
./gemrb_subviews/gemrb/plugins/BIKPlayer/common.h:47:25: error: comparison of integer expressions of different signedness: 'uint64_t' {aka 'long long unsigned int'} and 'int64_t' {aka 'long long int'} [-Werror=sign-compare]
   47 | #define FFMIN(a,b) ((a) > (b) ? (b) : (a))
      |                     ~~~~^~~~~
./gemrb_subviews/gemrb/plugins/BIKPlayer/rational.cpp:62:27: note: in expansion of macro 'FFMIN'
   62 |             if(a1.den) x= FFMIN(x, (max - a0.den) / a1.den);
      |                           ^~~~~
./gemrb_subviews/gemrb/plugins/BIKPlayer/rational.cpp:64:43: error: comparison of integer expressions of different signedness: 'long long unsigned int' and 'int64_t' {aka 'long long int'} [-Werror=sign-compare]
   64 |             if (den*(2*x*a1.den + a0.den) > num*a1.den) {
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
```

It looks as if you can trivially fix this by changing the type of `x` from `uint64_t` to `int64_t`, but I'm not sure if there is some numerical reason for this in the first place - or how and why that worked before.

**Comment by bradallred** [comment]
we should use `std::min<type>` (and delete `FFMIN`) for whatever type is on the left (type of x?).

**Comment by lynxlynxlynx** [comment]
I changed x to signed — video playback hasn't suffered. Didn't look into its use though, just a quick break from work.

**Comment by bradallred** [comment]
of course that works too. I still like to lean toward API consistency and using <algorithms> when we can :shrug:

**Comment by lynxlynxlynx** [comment]
Doesn't std::min also require the arguments to be of the same type? If the <type> version works, doesn't it just hide the underlying problem by casting implicitly?

**Comment by bradallred** [comment]
no, `std::min` is just a function and obeys the same rules for parameter type conversion/promotion as any other function. you simply have to explicitly select the parameter type (e.g. `std::min<int>`) because type deduction cannot take place in a template when the types differ.

I'm not saying we _shoudn't_ change the types I'm saying I don't like that we have _multiple_ `min` "functions".

**Comment by MarcelHB** [comment]
Looks as if the FFmpeg guys never faced that problem so far, code seems unchanged since forever here.

**Comment by bradallred** [comment]
well they are the ones that created the problem ha ha. They are the ones that defined `uint64_t` as a _signed_ type; that is the problem. You shouldn't do that.

**Comment by MarcelHB** [comment]
As much as I think video codec guys are up to every numeric hack, maybe we change it to signed _and_ use `std::min`?

**Comment by bradallred** [comment]
I don't see any reason that won't work. from the little bit of context in the issue I can't imagine the value is ever negative or in any other way in a conflict that would result in the signedness making a difference for this particular variable.

**Comment by MarcelHB** [comment]
I don't see that either - or plenty of question marks, considering the signedness rules. Will send you a PR shortly.
