### ISSUE TITLE
[subviews] the inventory item count label placement is inconsistent 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#595]
Only the first arrow and potion stack look fine:
![image](https://user-images.githubusercontent.com/121515/71984761-c9dd6880-3229-11ea-8e00-61727d9b584d.png)
Should be fixed to the lower right border.

**Comment by bradallred** [comment]
to me this looks like what to expect when `IE_GUI_BUTTON_PORTRAIT` flag is set. something must be screwing up the flags.
