### ISSUE TITLE
[bug] nitpick: EscapeArea() behaviour is different from original game

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#598]
In all infinity engine games, there are lots of actors that once they have outlived their purpose are scripted to dissapear. In BG2, this action is used 1886 times in DLG files and 592 times in BCS files.

In the original games, the actors make an effort to move to the edge of the screen before they self destruct, you can test by loading this save using torment.exe: [000000242-PST EscapeArea.zip](https://github.com/gemrb/gemrb/files/4043042/000000242-PST.EscapeArea.zip)

In gemrb, the actors simply self destruct immediately in front of the player. 

This has absolutely zero impact on the actual gameplay as far as I can tell, from memory I think in the original BG even if you try to interact with an actor that is trying to escape, it says something like 'cannot initiate dialogue, x appears busy'. However it just looks neater when the actor tries to reach the edge of the screen before vanishing. It isn't anything to lose sleep over, but it is one of the little things that reminds you that you are playing the game with gemrb.

**Comment by lynxlynxlynx** [comment]
Must be some pst problem, since we already have code for this. They escape to the nearest exit (could be a door).

**Comment by chilvence** [comment]
I didn't know that. In this case there are no nearby doors though, if you load the save in the original game, they just walk to the edge of the screen and vanish. It might cause a problem for 4k resolutions, but they probably never thought of that.

**Comment by lynxlynxlynx** [comment]
It's usually the map edge, but you're saying that even just the viewport edge is sometimes used?

**Comment by chilvence** [comment]
That's what it seems to be, yes, they blip out of existence just when they hit the edge of the viewable area.

**Comment by chilvence** [comment]
I just retested this randomly because I was searching for savegames, it seems like these actors behave as intended now. I haven't been keeping track of commits lately, but something that changed must have fixed it. Neat :)

Closing.
