### ISSUE TITLE
[bug] Release builds fail on newer GCC

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#602]
When trying to create a Release build of master with GCC v9.2, I get the following failure:
```cpp
In function 'char* GemRB::PathAppend(char*, const char*)',
    inlined from 'bool GemRB::FindInDir(const char*, char*)' at ./gemrb/gemrb/core/System/VFS.cpp:219:12,
    inlined from 'bool GemRB::PathJoin(char*, const char*, ...)' at ./gemrb/gemrb/core/System/VFS.cpp:272:18:
./gemrb/gemrb/core/System/VFS.cpp:206:9: error: 'char* strncat(char*, const char*, size_t)' output may be truncated copying between 0 and 259 bytes from a string of length 259 [-Werror=stringop-truncation]
  206 |  strncat( target+len, name, _MAX_PATH - len - 1 );
      |  ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function 'char* GemRB::PathAppend(char*, const char*)',
    inlined from 'bool GemRB::PathJoin(char*, const char*, ...)' at ./gemrb/gemrb/core/System/VFS.cpp:276:14:
./gemrb/gemrb/core/System/VFS.cpp:206:9: error: 'char* strncat(char*, const char*, size_t)' output may be truncated copying between 0 and 259 bytes from a string of length 259 [-Werror=stringop-truncation]
  206 |  strncat( target+len, name, _MAX_PATH - len - 1 );
      |  ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus.exe: all warnings being treated as errors
```
Trying to look up what this is supposed to tell us, you find lots of people asking the same since GCC 8+. As far as I get, it warns that the target of `strncpy` may fail to set its terminating `\0` because of end of space.

Writing a guard seems not to convince the static analysis. The options that I see:

- Fixing around CMake for GCC
- Thinking of using C++ string operations here.
- [This glorious workaround](https://github.com/grpc/grpc/pull/19198/files) (works for me).

**Comment by lynxlynxlynx** [comment]
Or we can just remove that warning, since it's not the first time it's caused problems.

**Comment by bradallred** [comment]
can't we just use `strlcat` instead?

**Comment by MarcelHB** [comment]
From what I see, this comes preshipped on Apple/BSD platforms only.

**Comment by MarcelHB** [comment]
@lynxlynxlynx Can you maybe cherry-pick baf3acabb14f1e662eec853bf83822eac3f566aa ? It's only available in subviews.

**Comment by lynxlynxlynx** [comment]
That was basically my proposal, yes.
