### ISSUE TITLE
[subviews] can't attack — wrong cursor

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#604]
In the first tob fight, with a skald bard character, right after the dialog with Illasera finishes and she turns hostile, I can't attack her:
![image](https://user-images.githubusercontent.com/121515/72216604-656d2280-3523-11ea-98d2-32c9e7b7aa49.png)

Some other actions reset it back to normal behaviour, but that excludes reequipping weapons, the most obvious thing that comes to mind.

**Comment by bradallred** [comment]
how reproducible is this? I tried twice as described and had no problem.

**Comment by lynxlynxlynx** [comment]
Always with the same save. Rename to .7z if needed, it's not a normal zip archive.
[tob-start.zip](https://github.com/gemrb/gemrb/files/4063932/tob-start.zip).

I load, click on the sword to make sure something is equipped and wait for the dialog to start. 1 enter 1 etc and the fight eventually starts.

**Comment by bradallred** [comment]
that last bit must be key. I'll try it when I get home.

**Comment by bradallred** [comment]
the problem seems to be that `GA_SELECT` is getting added to `GameControl::target_types` by `GUIScript::GemRB_GameControlSetTargetMode` which causes `lastActor->ValidTarget(target_types)` to fail. Specifically it fails on the very last check: `if (Modified[IE_EA] > EA_CONTROLLABLE) return false;`

no idea why `GA_SELECT` is being added; it is part of the default values there, but it is certainly wrong in this case.

**Comment by bradallred** [comment]
the check above `ValidTarget` is `if (lastActor && lastActor->Modified[IE_EA]>=EA_CONTROLLED) {` so we only run `ValidTarget` in a case that will always fail if `GA_SELECT` is set, so maybe we should NAND that off of the ValidTarget check, but I don't know what other consequences there are for setting it in the first place.

**Comment by lynxlynxlynx** [comment]
This looks fine and is the same in master. The difference is further down in the function, since it's not calling GameControl::UpdateCursor() any more.

**Comment by bradallred** [comment]
Meh, I think NANDing `GA_SELECT` for that one check is a fine fix

**Comment by lynxlynxlynx** [comment]
The cursor is correct now, but clicking doesn't do anything.

**Comment by bradallred** [comment]
right, thats why it's still open; I just haven't had any time to finish.
