### ISSUE TITLE
[bug] PST: FFG is not allowed to cast spells by the floating menu guiscript.

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#610]
A line in the floatmenu GUI script intentionally disables access to the spell list for non mage characters. This is clearly to stop TNO from cheating and casting his mage spells if he becomes a fighter or thief. However an unintended consequence is that it stops FFG from being able to cast any cleric spells as well.

https://github.com/gemrb/gemrb/blob/a64c37bab70a00a23eca5b9c7dfda09bc991a794/gemrb/GUIScripts/pst/FloatMenuWindow.py#L557

I am a little bit embarrassed I have never noticed this before, but I tend to just load FFG up with healing spells and turn the AI scripts on to make her do the medic thing, because she is the only character in the game with any AI worth using...

**Comment by lynxlynxlynx** [comment]
This is trivial, something like this should work:
`if GUICommon.GetClassRowName (pc)[-4:] in ["MAGE", "CLERIC"]: `

**Comment by chilvence** [comment]
This is where my understanding of python lacks a bit. It looks like the [-4:] part of this is supposed to get the last four characters of the class name found, which is why this code works for TNO and Dak'kon, the names of their classes would both end in 'MAGE' , but for FFG this returns a class name of 'ERIC', which is why this shamefully and hastily written fix works perfectly:

```
	if GUICommon.GetClassRowName (pc)[-4:] != "MAGE":
		if GUICommon.GetClassRowName (pc)[-4:] != "ERIC":
			return
```

It's better than my first response to this problem. which was to add a bunch of ###'s and worry about it later :)

**Comment by MarcelHB** [comment]
If you like it cleaner:
```py
className = GUICommon.GetClassRowName (pc)
if not className.endswith("MAGE") and not className.endswith("CLERIC"):
    return
```

**Comment by chilvence** [comment]
That is actually much more sensible, and probably the only fix needed for all intents and purposes realistically, but then of course I also couldn't help ponder about the hypothetical situation of a mod to the game adding a character that is a fighter/mage/thief , and then the floating menu would completely ignore the first two classes, because thief is always the last class name listed in a multi class character. Never mind that this is not BG and you can't actually create any characters from scratch. Having this kind of O.C.D. is a curse however.

**Comment by MarcelHB** [comment]
Over some years of development, you learn to arrange with this kind of ache . Yes, it's more solid to do something like `pc.canCastSpell()` or `pc.hasClass(Class.MAGE)` (not sure if they exist in a way or another) than scanning the string for some other string at some position -- but then, you name it, it's niche code. 

If you think of things you don't even know if they ever appear on the horizon, feel fine to ignore them for the time.

**Comment by chilvence** [comment]
Genau :) It's pretty hard for me sometimes, I really wish for a version of Baldur's Gate that can chop firewood for me and file my taxes but I might be expecting a little bit too much. Those might be considered 'requests for enhancement'

**Comment by lynxlynxlynx** [comment]
I looked it up and this was added based on your code, heh. Here's the clean version to test:
http://sprunge.us/E9dxGt?diff

**Comment by chilvence** [comment]
Hmm, I knew there had to be a reason I was correct to hate myself all this time. Why would I have ever thought that was ok?

**Comment by lynxlynxlynx** [comment]
Eh, don't worry about it, we all make mistakes.
