### ISSUE TITLE
ctrl-c not working on windows?

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#613]
A user reported ctr-c not working, in that case if you sabotage gemrb/GUIScripts/bg2/Start.py:78 to some invalid ID (3254). It works on linux and for simpler programs like ping. 

@MarcelHB @caillean7 If you run gemrb from cmd.exe, does pressing ctrl-c in it kill gemrb? (If in game, it requires two presses)

**Comment by caillean7** [comment]
I'm trying to get a windows build running with wine, but got stuck with the following error:

```
[Core]: Initializing GUI Script Engine...
ImportError: No module named site

```

**Comment by lynxlynxlynx** [comment]
Oh, sorry, I mixed you up, you're on linux too. Nevermind.

**Comment by caillean7** [comment]
Yeah, I'm useless with Windows. Tried on a VM, too btw. wouldn't want to run GemRB, so best to wait for Mr. HB to check it out.

**Comment by MarcelHB** [comment]
Well ...

- If you click the executable, or go there by `cmd`, and press Ctrl+C, Python will at _some next chance_ throw a `KeyboardInterrupt` and hang for one invocation of whatever it is. But at no point this terminates the process.
- If you use MSYS bash, Ctrl+C will immediately terminate the process, without asking first.

So I guess the answer to your question is: no.

Windows does not know so much the concept of signals as Linux does. You generally have window events, and you can use `SetConsoleCtrlHandler` to capature a tiny set of console specific events. Not sure what needs to be considered w.r.t. SDL - or Python, obviously.

And I'm not sure what I'm supposed to manipulate in that Python script you mention, that line is `GemRB.SetNextScript("Start2")` -- unless this brings Python into some illegal state that maybe prevent it from keeping its own signal handler.

**Comment by lynxlynxlynx** [comment]
I guess you're looking at subviews, on master it's simply this: `TextArea = StartWindow.GetControl(0)`.

We could catch and handle KeyboardInterrupt, but I don't know if we should bother at all. The user had the problem that he had to explicitly kill the window to be able to close it, which sounds absurd. But then again it's windows, so ???

**Comment by MarcelHB** [comment]
You're right ... I `cd` in vim and my file indexer stays in subviews. :thinking: But good you mention it, it's line 87, not 78 - which probably ends up in the same result.

I also have no clue what the user wants to achieve, and if the ordinary GemRB player on Windows has a similar motivation (I don't, I really click the X).

**Comment by lynxlynxlynx** [comment]
From what I understood the X didn't work. Since you say it does for you, that's good enough for me, the final nail. I've added some other precautions, so the original mistake that led to this is less likely to happen and the new site content is more explicitly discouraging as well.
