### ISSUE TITLE
[subviews] character list is mangled

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#614]
Trying to quickly start a new game, just to test and show that the class doesn't actually matter for #604 ... but unfortunately:
![image](https://user-images.githubusercontent.com/121515/72418926-1241dc80-377c-11ea-97d2-5e5f48665b4b.png)

**Comment by bradallred** [comment]
I'm not somewhere I can test but maybe the "redundant" code removed in 8022558 is only redundant if there is also text.
