### ISSUE TITLE
[bug] drowned dead door unlocked too much

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#615]
Old note:
> The door at the south east (to the drowned dead, with Barr) should be locked after you get through
> 
>    - RESEARCH, does returning from the next area immediately show them closed already? If not, what do you have to do in the original ... how to reproduce

chiv's addendum:

> As for number 3 on that list.. HMPH. For such a simple issue that should be straightforward, Every time I try to figure it out, I am no wiser. It maybe does deserve its own bug report, but it is infuriating because it actually has no negative effects on the game itself, and I can't find where exactly in the chain of scripts actions and global variables it breaks down. It's a complicated bug that has no consequence whatsoever, besides making the game a bit more lenient. It will need fixing eventually, but to be honest I have been willfully ignoring it because there doesn't seem to be any particular reward for chasing it down.

**Comment by chilvence** [comment]
This might be a duplicate, this is actually what I meant when adding #599 . I am not sure why I wrote 'drowned dead' Perhaps I thought the whole catacombs area was called the drowned dead before?

**Comment by lynxlynxlynx** [comment]
Ah, sorry, even better. :)
