### ISSUE TITLE
[bug] PST No resting movies played

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#617]
Probably directly related to the problem and solution found in  #589 , currently when you rest anywhere in PST there is no movie played.  There is actually no 'restmov.2da' for this game at all, and not knowing what all the meaning of the fields are I haven't tried to create one.

The only single rest movie in PST is called 'TIME' and as far as I recall is played in any rest situation, whether triggered by dialog, gui rest button or by finding a rare 'tavern'

**Comment by lynxlynxlynx** [comment]
Try copying the bg1 one and just set the first column 1-7 to TIME.

**Comment by chilvence** [comment]
That gets it working for the few places you can actually rest via the GUI button, and also partially working in the tavern dialog, but once the video has finished playing the window does not get prompted to redraw and the whole dialog is black.

However I can't see what is meant to happen when you 'rest' using dialogue, which is where the majority of rest opportunities occur. All the characters that trigger is have the action

 ``` 
FadeToBlack()
Wait(1)
RestParty(-1,10,0)
FadeFromBlack()
 ```

 but nothing specifically mentioning the movies. So I tried lengthening the table to see if the second parameter was simply an index to which ever movie is supposed to play but that seems not to be it. 

There is some movie related stuff in Game::Restparty but I think that it is bg dream related going by the parameter list on this line https://github.com/gemrb/gemrb/blob/c4bdcca67ca42734adcf6804195ec04b5489825f/gemrb/core/Game.cpp#L1718

However there is very little else in the Gamescript action :

https://github.com/gemrb/gemrb/blob/4054ec3a3905bceb6f45ea25849bedeb38f5bd35/gemrb/core/GameScript/Actions.cpp#L5290 

it just passes the parameters direct to the game code.

So, is the 'dream' parameter from bg1 supposed to be something else in pst?

**Comment by lynxlynxlynx** [comment]
Where can you rest through dialog reliably?

**Comment by chilvence** [comment]
Quite a few places, AR0102, AR0107, AR0302 all have characters that trigger resting , not sure if they require any conditions first, plenty other random characters you wouldn't expect also have it, but AR1101 Fhjull is bound by geas to help you any way he can so that's probably the most easy place to test.

**Comment by lynxlynxlynx** [comment]
I get the problem even without the table, so that's a separate issue — is it not the same for you?

**Comment by chilvence** [comment]
Yes , I just assumed at first there must be something in the core that decides whether to play a rest movie or not, but if it is only PST that has this kind of behaviour then it would explain why it doesn't work.

 I checked with ida, there is one text entry in the exe in all caps which looks like a resref -- 'TIME' -- in an area with references to InfGame.cpp, so maybe the original game code directly references this video any time any kind of rest is triggered. The code shortly after leads into a subroutine in ChDimm.cpp which I think is something to do with loading resources.

**Comment by lynxlynxlynx** [comment]
Dude, you're wasting time looking at the exe for this. Resting movies work everywhere else, so there's simply something wrong with our GUIScripts for pst — GUISTORE.py and maybe one more. We don't care how hardcoded the original loigic was, since we have a table now.
