### ISSUE TITLE
[bug] PST nitpick : containers have a different color blend from all other games

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#618]
This is a really pedantic issue, and even the EE version missed it, but in the original game the containers have a darker hue than in BG/IWD games, perhaps because one of the artists didn't much like that lovely cyan colour that seems to be a 90's staple

**Screenshots**
![container colour](https://user-images.githubusercontent.com/1923867/72482458-aa2fdc80-37f5-11ea-97ae-a6446f0adab4.jpg)
![container colour gemrb](https://user-images.githubusercontent.com/1923867/72482563-0c88dd00-37f6-11ea-97fc-879ba4b27c40.jpg)

Mucking about using GIMP, I think the actual colour hue is exactly the same, but the blending mode is different, multiply blending seems to work 

![container colour gimp](https://user-images.githubusercontent.com/1923867/72482851-f4658d80-37f6-11ea-8e13-c08b83693569.jpg)

That might not be to correct answer either, I didn't go to the trouble to find the exact RGB colour the original game is using, but it is my best guess. I only thought it worth mentioning because it is one of the constant little reminders that tells you you are playing with GemRB.

Oh yeah, and traps also have this peculiar darkening blending mode as well, before I forget.

**Comment by bradallred** [comment]
@chilvence if you invert the commenting from that commit in Scriptable.cpp you will see that is correct

![image](https://user-images.githubusercontent.com/1126744/72495121-12c18e00-37e3-11ea-8aae-cdaaf91dc4c0.png)

**Comment by chilvence** [comment]
I like that screenshot in many ways

**Comment by bradallred** [comment]
just to be clear, all highlighables (containers, traps, doors) have this blending?

**Comment by chilvence** [comment]
Yup, some other examples:
![catacombs trap screenshot](https://user-images.githubusercontent.com/1923867/72574583-74f0c080-38c1-11ea-8b32-25aa0e209564.jpg)
![vermin control screenshot](https://user-images.githubusercontent.com/1923867/72574587-7b7f3800-38c1-11ea-84a8-69163c848bc1.jpg)

**Comment by lynxlynxlynx** [comment]
We don't do that yet. A door is in ar0400, while I gave up on finding a trap, since the levelup gui is broken.

**Comment by bradallred** [comment]
deferring this for after merging subviews since there is little sense in making changes to the rendering backend till that is merged. plus this already works in that branch for SDL 2 so all we need is to add `BLIT_MULTIPLY` support in the SDL 1 backend.

**Comment by chilvence** [comment]
That makes sense, I only thought I would shove this one in while I know you're working on the rendering area :) At least the solution was more straightforward than I expected
