### ISSUE TITLE
[bug] resting in an inn causes drawing issues

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#621]
Splitting of #617.
When you rest, much of the GUISTORE interface goes black. No manner of Invalidate or reopening helped when I tried. I forgot we already merged the guiscripts, so this is not some pst-specific bitrot either.

Attaching save to retest on subviews:
[resting.zip](https://github.com/gemrb/gemrb/files/4081998/resting.zip)

**Comment by bradallred** [comment]
in subviews movies are drawn in their own windows instead of directly to the screen so I can already assure you this works there.

**Comment by lynxlynxlynx** [comment]
This has nothing to do with movies though.

**Comment by bradallred** [comment]
I don't know what else would draw black over the screen 🤷‍♂ 

regardless I can't imagine this affecting subviews. each view sets the video clip to its bounds so nothing can draw outside its own frame anymore. at worst whatever rouge element is drawing the black will be filled with black and that will at least show us what is responsible.

**Comment by bradallred** [comment]
I guess a fade to/from black would do it, but then that means this problem happens anytime we do a fade when the GUI isn't hidden. Subviews should be immune to this as well tho.

**Comment by lynxlynxlynx** [comment]
It doesn't happen on subviews. :) There's another issue though, now that movies are played — almost impossible to skip, the movie gets restarted several times. I'm traveling now and can't recheck master though. Just my luck.

**Comment by bradallred** [comment]
still sounds like the entire screen had black rendered to it and only things that were redrawn aren't persistently black. Clicking on any of the black controls should refresh them. Doesn't really matter tho; not really a point in trying to fix it in master.

**Comment by lynxlynxlynx** [comment]
No, just catching up on email and saw that I didn't _draw the whole picture_. I'll check out what's wrong with skipping later.
