### ISSUE TITLE
[subviews] hovering over pc shows direction arrow

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#622]
These arrows are used when you're off-screen and hover over their portrait, however on subviews pointing at them in the area displays them instead:
![image](https://user-images.githubusercontent.com/121515/72681568-24e24b80-3ac5-11ea-9107-bf568784abdc.png)

**Comment by bradallred** [comment]
IIRC they also draw at the edge, but that is now below the windows so that is something to work out too.

**Comment by lynxlynxlynx** [comment]
I like the simplicity of the new layer. I don't think anyone will mind that the arrows are now drawn over the side windows, but do they actually draw for you in pst? I do get them in bg2, but not in pst.

**Comment by bradallred** [comment]
hmmm I don't think I checked PST. You're right it doesn't work there for some reason.
