### ISSUE TITLE
[bug] IWD1: Actor overlay sound effects not played correctly

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#623]
**Description**
Checked some overlays in IWD1 for #461 , too, and noticed that on the original they have sound effects playing in a loop, which doesn't work too well on GemRB. So Minor Globe sound isn't played at all, for Sanctuary is played for a few seconds, then stops when it's supposed to loop. Also, combined with invisibility, it's still supposed to play, which doesn't work right now.

**GemRB version**
0.86-git

**To Reproduce**
Use
`CreateCreature(1,"SKELETON")`
to summon a skeleton with a permanent Minor Globe effect active.

[skeleton.zip](https://github.com/gemrb/gemrb/files/4092367/skeleton.zip)

**Comment by caillean7** [comment]
Same for BG2.

**Comment by bradallred** [comment]
these are VVCs right? there is a "looping" sequence flag as well as some sound duration fields we are probably supposed to pay attention to.

**Comment by lynxlynxlynx** [comment]
No time to check, but they could easily be just BAMs or perhaps we set AA_ANI_PLAYONCE somewhere.

**Comment by caillean7** [comment]
Minor Globe is MINORGLB.vvc, has the looping sequence flag set, and Duration (frames) set to -1. As mentioned in #624 I can't find any SANCTRY.vvc that's used for the Sanctuary spell in my installs.

**Comment by lynxlynxlynx** [comment]
Yeah, it's a BAM, so no flags or anything.

**Comment by lynxlynxlynx** [comment]
For the bams we have our own vvcs, but perhaps the sound mapping hasn't been found or done yet, besides any flags being wrong.

Are there more cases than sanctuary and minor globe? The list of hardcoded overlays is what overlay.2da is about.

**Comment by lynxlynxlynx** [comment]
Yeah, our bg2 sanctry.vvc doesn't have any sound resources defined, while the shared one has aft_p01.wav. Is that the correct one? Our minor globe has aft_m03.wav (and a different onset one), but I can't hear it loop indeed.

**Comment by caillean7** [comment]
Not yet complete, I'm roughly half-way through, will update shortly.

> Are there more cases than sanctuary and minor globe?

No sounds played:

- Sanctuary
- Minor Globe of Invulnerability
- Shroud of Flame
- Antimagic Shell
- Otiluke's Resilient Sphere
- Protection from Normal Missiles
- Cloak of Fear
- probably Entropy Shield; see #625 
- Storm Shell

Okay because there's no sound mapped / sound is played already:

- Entangle
- Grease
- Web
- Insect Plague

**Comment by lynxlynxlynx** [comment]
These are all vvcs we provide (skipping pst):
```
gemrb/override/bg1/minorglb.vvc    gemrb/unhardcoded/bg2/spentaci.vvc  gemrb/unhardcoded/iwd2/coldh.vvc
gemrb/override/bg2/minorglb.vvc    gemrb/unhardcoded/bg2/spshield.vvc  gemrb/unhardcoded/iwd2/electrh.vvc
gemrb/unhardcoded/bg2/sanctry.vvc  gemrb/unhardcoded/iwd2/acidh.vvc
gemrb/unhardcoded/iwd2/fireh.vvc gemrb/unhardcoded/shared/sanctuc.vvc
```
Looks like only the first two are on the list. Much more work. :( 

But we need to find the sounds themselves too.

**Comment by caillean7** [comment]
> But we need to find the sounds themselves too.

I'll figure out the wav's and provide you with a list.

**Comment by lynxlynxlynx** [comment]
Awesome, thanks! 

The offer of cookies still stands, but you'd have to accept the cookie policy: a shipping address is needed. :smiley:

**Comment by caillean7** [comment]
> offer of cookies

Давай!!!!!!!!!!! I had given up hope already!

Here's the list

| Spell | WAV file |
|--------|------------|
| Sanctuary - SPPR109 | AFT_P01 |
| Minor Globe of Invulnerability - SPWI406 | AFT_M02 |
| Shroud of Flame - SPWI511 | MISC_01C |
| Antimagic Shell - SPWI601 | AFT_M04 |
| Otiluke's Resilient Sphere - SPWI413 | AFT_M03 |
| Protection from Normal Missiles - SPWI311 | AFT_M01 |
| Cloak of Fear - SPPR409 | AFT_P02 |
| Entropy Shield - SPPR609 | AFT_P03 | 
| Storm Shell - SPPR323 | AFT_P25 |
| Shield of Lathander - SPPR514 | AFT_P26 |
| Greater Shield of Lathander - SPPR718 | AFT_P26 |

**Comment by caillean7** [comment]
Added Seven Eyes, which I previously had forgotten. I'll check out the other VVCs from the list you posted above (other games and shared ones) next.

**Comment by lynxlynxlynx** [comment]
Thanks, huh and interesting — a different resource for the minor globe.

**Comment by fizzet** [comment]
I could use some experimental help from someone with access to the original engine.

Take a VVC that has only one anim sequence but the first two sound slots set (e.g. Minor Globe, minorglb.vvc, in BG2). Is the first sound played at all? Is it cut short when the second sound starts? Does it finish before the second one starts? Do they play simultaneously?

Then, take a VVC that has several anim sequences and several sound slots set (e.g. Fireshield Red, can't look up the vvc file name atm, in BG2). Modify to set a first sound much longer than the first anim sequence. Then, same questions as above.

**Comment by lynxlynxlynx** [comment]
minorglb.vvc is our own, so we can just fix it if it misbehaves. My guess would be that the (onset) sounds are cut off if the bam duration isn't long enough before the phase changes.

**Comment by fizzet** [comment]
If you try with the original it shouldn't matter whether we override that. 😃 
That's part of what I'm trying to find out. It would mean, however, that the onset sound is completely irrelevant if there's only one anim. Not that it's impossible, but odd, and it's set everywhere.

**Comment by lynxlynxlynx** [comment]
I tried GoI in bg2ee and it doesn't use the shipped vvc. Changed the bam and sounds, but it still did its own thing. Looking at the extended headers for both spells (and scrolls), none have the projectile set. The original vvc has 0s in all the phase slots too.

**Comment by fizzet** [comment]
Hm, my BG2 minorglb.vvc looks different, then, but I didn't verify whether it's used. Maybe it's not the best example, then.

**Comment by lynxlynxlynx** [comment]
Cloak of fear (bg2) already sounds the same, so perhaps it's the iwd one in the table. It's not one of the hardcoded overlay anyway.

Protection from missiles uses our sparklgr.pro, so another hardcoded case. Same for sanctuary. The resilient sphere and spell turning use none, so they're likely ours as well.

So overall, I don't know how to test this for you.

**Comment by fizzet** [comment]
The second part with Fireshield should be possible, though?

**Comment by lynxlynxlynx** [comment]
It looks like it plays out completely: the starting sound is much longer than the phase duration, so a good spell to check with. So it behaves like the running phase sound is queued.

**Comment by fizzet** [comment]
Thanks! So I guess I'm going to assume the same behaviour for the other case for now.

**Comment by lynxlynxlynx** [comment]
Sounds good, thanks for taking over. :)

**Comment by fizzet** [comment]
I've added a couple of VVCs for the above-mentioned spells. Things should be better now, though they certainly won't be perfect. I'd like to hear about any specific discrepancies.

**Comment by lynxlynxlynx** [comment]
I tried it and it seems to work fine. I don't know the originals well enough to be able to tell these things apart by memory though. So unless you already know of something needing more work, I propose we close this and leave it to nitpickers to find specific problems later.

**Comment by fizzet** [comment]
Fine with me.
