### ISSUE TITLE
[bug] BG2 - Sanctuary Actor Overlay doesn't work

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#624]
**Description**
The overlay for Sanctuary (SPPR109) is currently not drawn on GemRB. Overlay.2da has as VVC "SANCTRY",  which is also listed in IESDP, however, I couldn't find this file with NI for any of my BG2 installations.

**GemRB version**
0.86-git

**To Reproduce**
A save with the spell added to Jaheira:
[000000045-sanctuary test.zip](https://github.com/gemrb/gemrb/files/4092746/000000045-sanctuary.test.zip)

**Comment by lynxlynxlynx** [comment]
Hmm, I remember seeing it, but maybe that was iwd. That big fat cylinder.

**Comment by caillean7** [comment]
> That big fat cylinder.

You forgot 'wobbling' :smile: 
![sanct](https://user-images.githubusercontent.com/54738589/72852658-8a922b80-3caf-11ea-863c-081764d11b14.jpg)
