### ISSUE TITLE
[bug] IWD1 - Entropy Shield actor overlay doesn't work

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#625]
**Description**
Testing actor overlays and noticed that Entropy Shield's overlay is not drawn. Ctrl.+M shows the effect is active, just the graphics are missing, like with #624 

**GemRB version**
0.86-git

**Comment by ifyGecko** [comment]
When casting Entropy Shield this error appears twice--  [ResourceManager/ERROR]: Couldn't find 'wpMQScae.bam'.
Searching in the bam tab in near infinity I do not see this bam file. However, I am also getting errors in near infinity I haven't seen before so this could just be a fluke on my end. Has or can anyone confirm this error when casting too?

**Comment by lynxlynxlynx** [comment]
The spell uses ESHIELC. It's one of those hardcoded overlays that we externalized (projectile entropy.pro).
wp* are weapon animations, wpmqs* for staves. A separate problem that we're looking it up for the wrong stance.

**Comment by fizzet** [comment]
The overlay actually works fine, but the spell is broken because of opcode 206 (`fx_resist_spell`). I haven't found a good description and don't know how it's supposed to work, but it's pretty obviously broken right now...

**Comment by lynxlynxlynx** [comment]
I suggest you look at other spells that use it then and try changing that last return.

**Comment by fizzet** [comment]
The last return isn't the (first, or only) problem. Do you know of a useful description of what the effect is supposed to do? What's the `Resource` parameter for? Is it conceivable that IWD targeting for "anyone" is broken?

**Comment by lynxlynxlynx** [comment]
I haven't looked at the data, but the obvious choice would be the spell to resist.

**Comment by fizzet** [comment]
That would have been my guess as well, but the effect implementation doesn't actually do anything with it. I also tried looking at some spells for how they use the effect, but I cannot bring that together with the effect implementation, like, at all. It looks like the spells want protection from some other effect, but the implementation can actually only protect from other effects of the very same spell no matter what... Colour me baffled.

And in addition, what I said above: Targeting for "anyone" looks to be the wrong way around currently and ends up aborting the spell for everyone.

**Comment by lynxlynxlynx** [comment]
Looking at entropy shield, it's clear this should be a resistance effect like the protection/immunity ones. So not something that goes away immediately, but something that sticks and blocks in check_resistance.

**Comment by fizzet** [comment]
Yeah, it seems like IWD 206 and IWD2 290 are two entirely different beasts. Does the BG2 variant of 206 work? I can't find any code checking for IE_IMMUNITY...

**Comment by lynxlynxlynx** [comment]
I thought this was used more widely*, but in this bg2 install, only sppr710 uses it (by applying immsp710.eff), to grant immunity to itself near the end of its payload.

* might be spell revisions

```
#define IMM_PROJECTILE  1 <-- NOT implemented, we only support the bounce variants
#define IMM_OPCODE      2 <-- implemented indirectly
#define IMM_LEVEL       4  <-- implemented indirectly (a bit less obvious if you search by name, due to a typo)
#define IMM_SCHOOL      8 <-- implemented indirectly
#define IMM_SECTYPE     16 <-- implemented indirectly
#define IMM_RESOURCE    32  <-- is the bg fx_resist_spell, implemented indirectly + same for the iwd2 varian
#define IMM_PROJECTILE_DEC 0x100 <-- not even set, this was supposed to be an extension, I guess
#define IMM_OPCODE_DEC  0x200 <-- not even set, this was supposed to be an extension, I guess
#define IMM_LEVEL_DEC   0x400 <-- implemented indirectly
#define IMM_SCHOOL_DEC  0x800 <-- implemented indirectly
#define IMM_SECTYPE_DEC 0x1000 <-- implemented indirectly
#define IMM_RESOURCE_DEC 0x2000 <-- implemented indirectly
#define IMM_GUARDIAN  0x80000000  <-- implemented directly
```

Indirectly means in matching by opcode in EffectQueue. So IMM_PROJECTILE is being ignored (which spells use 0x53 Protection:Projectile?) and needs to be implemented, but the spell protection stuff looks fine. See where fx_spell_immunity2_ref is used.

**Comment by fizzet** [comment]
My best guess at the moment would be to toss the IWD variant of `fx_resist_spell` entirely and just use the BG2 one for all games instead. How's that sound?

**Comment by lynxlynxlynx** [comment]
Not good, I'm almost certain the ids targetting is there. But it does look inverted, so perhaps a different fix is needed for iwd2 cure light wounds and bard songs to work still.

**Comment by lynxlynxlynx** [comment]
I guess it needs to be moved to EffectQueue — the check there doesn't care what the opcode is doing.
