### ISSUE TITLE
[bug] IWD1 - Shield of Lathander animation glitch

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#626]
**Description**
SPPR514 (Shield of Lathander) animation is not drawn correctly:

![shield_lath](https://user-images.githubusercontent.com/54738589/74175810-d264fc80-4c36-11ea-96cd-3ac46452c176.jpg)

Supposed to look like:
![shield_lath_IE](https://user-images.githubusercontent.com/54738589/74524383-37627000-4f1f-11ea-9efc-5612cf2283a0.jpg)

**GemRB version**
0.86-git

**Comment by bradallred** [comment]
screenshots of what it is _supposed_ to look like would be helpful too.

**Comment by lynxlynxlynx** [comment]
I think the bottom part is fine and it will just end up being a duplicate of #628

**Comment by caillean7** [comment]
> screenshots of what it is supposed to look like would be helpful too.

Added.

**Comment by lynxlynxlynx** [comment]
Closing as a duplicate, thanks.
