### ISSUE TITLE
[bug] IWD1 - Greater Shield of Lathander animation glitch

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#627]
**Description**
SPPR718 (Greater Shield of Lathander) is not drawn correctly, it looks pretty much like Shield of Lathander, see #626 
![shield_lath_greater](https://user-images.githubusercontent.com/54738589/74525285-0125f000-4f21-11ea-9b27-8bbc1a5486ff.jpg)

Supposed to look like:
![shield_lath_greater_IE](https://user-images.githubusercontent.com/54738589/74525296-097e2b00-4f21-11ea-8021-40c73b6e2d0a.jpg)

**GemRB version**
0.86-git

**Comment by lynxlynxlynx** [comment]
Closing as a duplicate, thanks.
