### ISSUE TITLE
[bug] IWD1 - Seven Eyes animation glitch

### ISSUE THREAD

**Issue by caillean7** [gemrb/gemrb#628]
**Description**
SPWI710 (Seven Eyes) animation is not drawn correctly:

![7_eyes](https://user-images.githubusercontent.com/54738589/74176260-9aaa8480-4c37-11ea-870e-4b4cd8973280.jpg)

Supposed to look like:
![seven_eyes](https://user-images.githubusercontent.com/54738589/74524942-48f84780-4f20-11ea-8911-f8dd1e965724.jpg)

**GemRB version**
0.86-git

**Comment by lynxlynxlynx** [comment]
Interesting, this is a regression. When I noted #372 after fixing the defensive functions of the eyes, it didn't have this problem. Care to bisect?

**Comment by caillean7** [comment]
Sorry for the delayed answer - yes, but might be next week, or are you in a hurry? Week's a little crazy for me.

**Comment by lynxlynxlynx** [comment]
No hurry, I'm almost underwater with work work. :(

**Comment by caillean7** [comment]
You were right, it worked before https://github.com/gemrb/gemrb/commit/48e20b51cc2425e58d03f18055f0eb23eb4fb8f1. This also caused the problems with the Lathander Shield spells (#626 and #627), but does not affect #625 (Entropy Shield) or #514 (Circle of Bones).

**Comment by lynxlynxlynx** [comment]
Uff, what a goose chase! But in the end it was just about fixing the data and removing a confusing initial value. Four birds with one stone sort of thing. :)
