### ISSUE TITLE
[bug] Mouse right click won't move a single character

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#629]
**Describe the bug**
In classic BG2, right click works for directing path for a group as well as a single character. In GemRB, it works only for a group. For a character, right click doesn't register.

GemRB version: 0.8.6-git

**To Reproduce**
1. Select a single character.
2. Right click to walk somewhere.

**Expected behavior**
The character should move to the designated spot.

**Comment by bradallred** [comment]
heh, I would be of the opinion that the group behavior is the unwanted bug :)

Why do we need right click to do what left click already does? Sounds like unnecessary code complexity for no gain to me. This is especially true if this behavior really does only apply to BG2 as per the tag.

**Comment by burner1024** [comment]
I think you got it all backwards. If anything, why do we need left click to do what _right_ click already does? :)

![war4](https://user-images.githubusercontent.com/1279852/75087950-277b0980-5579-11ea-8686-e2809637f3a5.jpg)


Anyway,
1. Sorry, I don't understand what do you mean by "group behaviour", why it's unwanted and a bug on top. I was talking about single character behaviour.
2. Somewhere in the code, it reads:
   ```
   if mouse.right_click()
     n = count_selected_characters()
     if n > 1:
       work()
      else:
       dont_work()
   ```
    That's what seems like unnecessary code complication to me. (Maybe digging git history would shed some light on why it's done that way.)
3. On the broader scope of right vs left, the difference is semantical. Right click only moves. You can't accidentally talk to someone, or attack someone, or pass through a door, or open a guarded container with it. It's _safe_.
   Left click is what you use when you want to _interact_: attack, travel, etc. If you miss, you may be screwed.
  I think many games implement this general distinction, not just IE. In fact, I suspect that the only reason that left click takes on some move functions is because some people have mouses with a single button.
  In addition:
   - A minor thing, but in particular, if you want to walk really close to a travel region, only right click will allow to do that. Left click with take you _through_ it instead.
   - Also, of course, only right click allows and can allow rotating party formations.
4. I mentioned BG2 because that's the only engine I care about, but now I fired up BG1, IWD, BGEE - it's all the same. I'm reasonably sure that's true for all IE games.

**Comment by bradallred** [comment]
re code complexity: I mean my preference is to make things simple and not rely on the number of PCs that are selected. I think we are in agreement there. I didn't realize that there was a subtle difference (interaction vs only movement) between movements directed by left vs right click; that is good to know and is useful behavior.

I'm not saying that the current code is the pinnacle of simplicity, but I can assure you that it reads nothing like you suggest (it may be far worse actually) 😄
