### ISSUE TITLE
[bug] Autopause on enemy sighted triggers on every new enemy

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#630]
**Describe the bug**
"Enemy sighted" autopause triggers every time a new enemy appears in sight. In original, it doesn't trigger if you already see another enemy.
Basically, with this option enabled it's a non-stop autopause fest.

GemRB version: 0.8.6-git

**To Reproduce**
1. Go to Government discrict.
2. Attack an Amn soldier in the top of the area.
3. See the game being paused again and again as backup arrives.

**Expected behavior**
The game gets paused once, when the party goes from "we see no enemies" to "we see some enemies".

**Screenshots**
![Captura de pantalla de 2020-02-13 03-40-21](https://user-images.githubusercontent.com/1279852/74376049-034e5880-4e14-11ea-8aaf-45c12defac42.png)

**Comment by lynxlynxlynx** [comment]
I'm not sure I'd consider this a bug — in many other cases the pause would be welcome. Don't have any spectacular ideas on how to avoid your case though. A timer would work (minimum time has to pass before we consider retriggering), but maybe we can do better.

**Comment by burner1024** [comment]
How do you mean? Why it would be welcome?

**Comment by lynxlynxlynx** [comment]
New enemies later join an ongoing battle; reinforcements, domination, friendly fire, something else ...

**Comment by burner1024** [comment]
I don't see the appeal, but I guess it wouldn't hurt as an additional option/setting.
However, surely it makes sense to implement the option the way it works in the original first, no?

**Comment by lynxlynxlynx** [comment]
Not really, if we blindly copied every stupid thing the original did, we'd go crazy. If you're familiar with vanilla as a version concept, most engine reimplementation projects are actually stracciatellas.

**Comment by burner1024** [comment]
I see, that makes sense.
I disagree that this one in particular is a stupid thing, though. Is it your final decision that there will no possibility to have it work vanilla-like?

**Comment by lynxlynxlynx** [comment]
You shouldn't even notice the difference.

**Comment by burner1024** [comment]
But that's definition of difference - if you can tell it, there is one, and if you can't, there isn't, for practical purposes. I mean, what does that mean making it different, if users can't notice it? (Meaning UX, different "under the hood" doesn't count - the whole GemRB is "different" in that case).

Anyway, off the top of my head I think timer wouldn't work very in encounters with invis-heavy enemies, such as SCS rune assassins, or ashirukuru, who go backstab-invis-backstab-..., and they attack in groups. The delay would have to be practically non-existent to allow to pause on each stab.

**Comment by bernds** [comment]
This is very visible and annoying - in Irenicus' dungeon I can't even attack the first group of goblins because every time I unpause it immediately autopauses again. I'm guessing some if them are straddling the boundary of the fog of war.
Guess I'll see what I can do about it.

**Comment by lynxlynxlynx** [comment]
I don't think we can improve on all the cases, so a short timer/delay (max once per round?) might be the best of both worlds. We already limit each actor to trigger it only once, so the invisibility potion gulping wouldn't have triggered it.

You can start by looking at AP_ENEMY. At a quick glance, I don't know why we're triggering it in two places.

**Comment by bernds** [comment]
My current thinking is a count of enemy Actors on each Map. If it ever goes from 0 to nonzero, warn. If there's a global tick variable somewhere we could also rate-limit the warning per actor (so that a kobold that goes out of view on one frame and back into view the next doesn't trigger it). How does this sound?

**Comment by burner1024** [comment]
This is great!
I would skip rate-limiting per actor, though. It can be a little bit annoying when enemies run in and out of fog, sure, but the alternative seems worse (if you ever fought an Ashirukuru with SCS, you should know).

**Comment by lynxlynxlynx** [comment]
I don't know what you mean, the per-actor check avoids excessive pausing for creatures like Ashirukuru, not the other way around.

**Comment by burner1024** [comment]
I mean that there no such thing as excessive pausing with them. They literally only get out from invis for a split second.

**Comment by lynxlynxlynx** [comment]
Sounds like the buggy pp ogre mages, but we have to rate limit either way. Without that, each team member would trigger the autopause as the same enemy got closer.

**Comment by burner1024** [comment]
Huh, what's this got to do with team members? Autopause is a player mechanic, not a character one. It's global.

**Comment by lynxlynxlynx** [comment]
Perhaps it is global, but that'd be quite odd. When would you consider an enemy "in sight" in such a case?

**Comment by burner1024** [comment]
Hmm, when any of player-controlled units have any enemy in direct LoS. I'm pretty sure that's how it works in original. (So Farsight doesn't trigger it, but blindness is taken into account).

Not entirely sure how it behaves with green uncontrolled units (ALLY or whatever it's called).

I mean, the only point for me is to put me on alert and let me give initial orders, after that there's plenty of other autopause triggers to use.

For completeness, in the original this trigger is not entirely instant, sometimes it misses an enemy that only appears briefly, which is what makes invis-heavy enemies annoying. I have a suspicion that it's checked every 100 ticks, like contingency opcode, which TobEx [allows to modify](https://htmlpreview.github.io/?https://github.com/BGforgeNet/TobEx/blob/master/WeiDU/TobEx/TobEx_redist/readme/TobExReference.htm#effects-232). This could probably use improvement.

**Comment by lynxlynxlynx** [comment]
But do you see how that requires tagging the enemy somehow? Otherwise each party member would trigger it on sight, as the enemy moved closer.

100 ticks would be the adjusted combat round, but we don't need to mimic that.

**Comment by burner1024** [comment]
Um, I don't... Once global state is warm, it's suppressed until state goes cold.

**Comment by lynxlynxlynx** [comment]
That would mean a max of one on sight autopause per encounter, regardless of enemy count and arrival times. Basically back to the simplistic behaviour of the original.

**Comment by burner1024** [comment]
Me personally, I'm quite happy with it.
