### ISSUE TITLE
[enhancement] Support for HQ music

### ISSUE THREAD

**Issue by burner1024** [gemrb/gemrb#633]
**Description**
There's a 1pp HQ music mod for BG2 (BGT, PST, etc). Hosted on SHS, so unfortunately down at the moment. Here's a link to [G3 announcement](https://www.gibberlings3.net/forums/topic/24661-shs-1pp-high-quality-music-for-pst-released/). It provides 44.1 kHz ACMs and applies a binary patch to `bgmain.exe` (without it the music is played twice as slow).
It's a minor QoL feature, of course. But if I understand correctly, it's should not be very difficult either: just reading bitrate from the [header](https://falloutmods.fandom.com/wiki/ACM_File_Format) and adjusting playback speed accordingly should be enough?

**Additional context**
If if it's all the same, probably no reason to limit to just 44.1 kHz, and maybe include wav/wavc too?

**Comment by lynxlynxlynx** [comment]
Yeah, it may be just about detecting the different format and modifying the bitrate on load:
https://github.com/gemrb/gemrb/blob/6f1b497a5a0bda41319a7baaa88a92d881393742/gemrb/plugins/ACMReader/ACMReader.cpp#L61

No idea why the format doesn't have this inbuilt — I remember the same problem when a Fallout reimplementation used our code as a base; by default it was twice too fast, since that's how IE played them.

**Comment by MarcelHB** [comment]
I looked at the upsampled ACMs. The examples I inspected state no different sample rate in the header than the original one: `0x5622` (22 050 Hz). When I manually change that into twice the value `0xAC44`, playback is correct again.

We do the right thing, the one who converted the files just ignored changing the value to what is appropriate (if patching the binary is sufficient, then this probably does not matter). Is there something I'm missing, heuristics?

**Comment by burner1024** [comment]
I see. It could be the tool that just hardcodes the rate. Probably `wavc.exe`, but I can't find a copy of its source.
I'll investigate and get back with more info.

**Comment by MarcelHB** [comment]
I'm convinced it's hardcoded, this is what looks like writing the header. Magic number, channel number and rate is hardcoded:
![wav2acm](https://user-images.githubusercontent.com/238558/82147027-39eda200-984d-11ea-91d5-db401c669bfe.png)

Option 1: While looking easily binary-patchable to the desired constant, it should better adapt to the input sound files.
Option 2: Some post-patches the header in whatever the tool chain is (read the WAV header, overwrite the resulting ACM header).

**Comment by burner1024** [comment]
It seems that [wav2wavc or PS Gui](http://www.shsforums.net/topic/50032-1pp-high-quality-music-for-soatob-tututosc-iwd-pst/page-6) was used for conversion, however I can't find the source code for either yet.

If GemRB already reads the rate, probably the proper way of fixing would be to do it in the mod itself, by either updating the tool and re-coding or patching the files afterwards with weidu to set correct header. In that case, no action on on GemRB side will be required.
In fact, I have an off-chance suspicion that maybe even original engine would be able to play the sounds at normal speed without exe patching if both wavc and acm headers are corrected.

I'll perform tests and update.

**Comment by MarcelHB** [comment]
There is "convert\acmtools\snd2acm.exe" in one of the mods, it says `v1.0 beta  (c) 2000-2001 ABel [TeamX]`. That's what I suspect.

**Comment by lynxlynxlynx** [comment]
Sounds like it would be easiest to patch with weidu if the mod is still maintained. Btw, with the next release,  `ENGINE_IS gemrb ` will become available to modders, but until then, it's easy to check for GemRB in the mod manually.

**Comment by burner1024** [comment]
It's indeed `snd2acm`, and `wav2wavc` only adds the wavc header on top.
I've noted this on the mod's forum. The author is not active unfortunately, but I hope it gets updated at some point.

**Comment by lynxlynxlynx** [comment]
Digging into it, it appears perhaps @GwendolyneFreddy is now maintaining 1PP alongside Infinity Animations. Though the music mods are not on github yet, so I don't know if there are any plans, what the original author thinks about moving etc. @GwendolyneFreddy: any insights into the situation with the 1PP HQ music mods?
