### ISSUE TITLE
[bug] ICW: Cannot import saved character with filename containing non-ASCII characters

### ISSUE THREAD

**Issue by fenuks** [gemrb/gemrb#646]
**Describe the bug**
I have Polish edition of Icewind Dale with Hearth of Winter extension, and in `Characters` folder I have number of predefined, well, characters, some with Polish letters in names.

```sh
❯ ls *.chr
+Bard.chr*  +Druid.chr*  Kapłan.chr*    +KapłanZ.chr*  Łowca.chr*  Mag.chr*       Paladyn.chr*   +Wojowni.chr*  +WojZłod.chr*  Złodziej.chr*
Bard.chr*   Druid.chr*   +KapłanD.chr*  +Łowca.chr*    +Mag.chr*   +Paladyn.chr*  +WojKapł.chr*  Wojownik.chr*  +Złodzie.chr*
```
Attempt to import these characters during party creation results with error (Polish diacritic characters are deformed, and cannot be imported). Restricting names to ASCII-only letters makes character importable.

GemRB version: 0.8.6 on Linux (also tried latest version from sources)

**To Reproduce**
1. Rename one of character and resource file to `Kapłan.{chr,res}
2. Go to 'Import character screen'
3. Select entry with deformed name
4. Click 'Import'
5. See error

```
[GUIScript/ERROR]: Syntax Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/usr/share/gemrb/GUIScripts/iwd/CharGen.py", line 2717, in ImportDonePress
[Python/ERROR]:     GemRB.CreatePlayer (CharImportList.QueryText(), MyChar|0x8000, 1)
[Python/ERROR]: AttributeError: ===== CreatePlayer =====

**Prototype:** CreatePlayer (CREResRef, Slot [,Import, VersionOverride])

**Description:** Adds an actor (PC) to the current game. It works only 
after a LoadGame() was executed, and should be used before an EnterGame(). 
It is also used to import a .chr file as a PC. A new character will need 
additional SetPlayerStat() and FillPlayerInfo() calls to be a working 
character. 
Note: if the slot is already filled, it will delete that pc instead!

**Parameters:**
  * CREResRef - name of the creature to use, usually 'charbase'
  * Slot      - The player character's position in the party
  * Import    - Set it to 1 if you want to import a .chr instead of creating a new character
  * VersionOverride - Force CRE version of new actor.

**Return value:** the new player's index in the game structure

**Examples:**
  MyChar = GemRB.GetVar ('Slot')
  GemRB.CreatePlayer ('charbase', MyChar)
The above example will create a new player character in the slot selected
by the Slot variable.

  MyChar = GemRB.GetVar ('Slot')
  ImportName = 'avenger'
  GemRB.CreatePlayer (ImportName, MyChar, 1)
The above example would import avenger.chr into the slot selected by the 
Slot Variable. (If it exists in the Characters directory of the game).

**See also:** [[guiscript:LoadGame]], [[guiscript:EnterGame]], [[guiscript:QuitGame]], [[guiscript:FillPlayerInfo]], [[guiscript:SetPlayerStat]]
**Expected behavior**
A clear and concise description of what you expected to happen.
```

I dug a little, and in GemRB_TextArea_ListResources names are correctly encoded, but in [CharGen.py#L2722](https://github.com/gemrb/gemrb/blob/a92321eeb797f2a3aa5888ed942303cf975beb2e/gemrb/GUIScripts/iwd/CharGen.py#L2722) QueryText() returns None. I didn't figure out where string is incorrenctly handled, though.

**Screenshots**
![import](https://user-images.githubusercontent.com/1249829/77706197-01a2b380-6fc2-11ea-95e1-325a31d1da44.png)

**Comment by bradallred** [comment]
the `FIXME` in `GemRB_Control_QueryText` says it all: "FIXME: handle non-ascii chars or prevent their input".

The key is going to be found in `MBCStringFromString` where there are 3 additional `FIXME`s about local and ascii. Unfortunately C++ stdlib doesn't provide much here so we would certainly have to roll our own or rope in a 3rd party library to actually cope with unicode.

**Comment by bradallred** [comment]
Also, we would have to make the move to Python 3 first.

**Comment by fenuks** [comment]
I tried yesterday to narrow it down, and indeed I found it to be issue. I might not understand something, but it seems that no locale is set during engine initialization.

I've extracted said function in my test function, and if you comment out `setlocale` call, it fails to convert string.

```cpp
#include <string>
#include <iostream>

typedef std::wstring String;

char* MBCStringFromString(const String& string)
{
	size_t allocatedBytes = string.length() * sizeof(String::value_type);
	char *cStr = (char*)malloc(allocatedBytes);

	// FIXME: depends on locale setting
	// FIXME: currently assumes a character-character mapping (Unicode -> ASCII)
	size_t newlen = wcstombs(cStr, string.c_str(), allocatedBytes);
	if (newlen == static_cast<size_t>(-1)) {
		// invalid multibyte sequence
		free(cStr);
		return NULL;
	}
	// FIXME: assuming compatibility with NTMBS
	cStr = (char*)realloc(cStr, newlen+1);
	cStr[newlen] = '\0';
	return cStr;
}

int main() {
    setlocale(LC_ALL, "");
    String a = L"ŁOWCA";
    std::cout << "converted: " << MBCStringFromString(a) << std::endl;
    return 0;
}
```

Man page for `setlocale` reads:

       If locale is an empty string, "", each part of the locale that should be modified is set according to the environment variables.  The details are implementation-dependent.  For glibc, first (regardless of category), the environment variable LC_ALL is inspected, next the environment variable with the same name as the category (see the table above), and finally the environment variable LANG.  The first existing environment variable is used.  If its value is not a valid locale specification, the locale is unchanged, and setlocale() returns NULL.

       The locale "C" or "POSIX" is a portable locale; it exists on all conforming systems.

After adding `setlocale(LC_ALL, "");` to Gemrb main function, converting works, but as I understand, text is mangled somewhere before that step, so returned string has incorrect diacritic characters as seen on screenshot, which results in file not found error.

Is there any reason locale is not set in program, and default `C` locale is used?

**Comment by bradallred** [comment]
I assume we would want to inherit the locale from the environment.

What is the value of the `string` parameter passed in? why do you think it is mangled  before this step? appearance in the GUI has very little to do with the actual underlying string data unless you are using a TTF font (which is not default).

**Comment by bradallred** [comment]
you might have more luck using TTF and changing your encoding settings: http://www.gemrb.org/wiki/doku.php?id=plugins:ttf

**Comment by bradallred** [comment]
another helpful resourse: https://github.com/gemrb/gemrb/blob/master/gemrb/docs/en/default_ini.txt

apparently somebody made a polish.ini for BG1, but not IWD. might just be able to copy that.

**Comment by lynxlynxlynx** [comment]
Yeah, try copying that file to ../how/ and setting Encoding=polish in your gemrb.cfg.

**Comment by fenuks** [comment]
Thank you for your suggestions. I think in this case problem is of bit different nature (so far I didn't notice any wrongly presented text from game resources).

In this case, game loads list of filenames from `Characters` directory, encodes them with encoding used by game [here](https://github.com/gemrb/gemrb/blob/a92321eeb797f2a3aa5888ed942303cf975beb2e/gemrb/plugins/GUIScript/GUIScript.cpp#L6692) (by default it is `ISO-8859-1`), and sets value in import table. Upon selection, this value is fetched, and converted to narrow multibyte representation [here](https://github.com/gemrb/gemrb/blob/a92321eeb797f2a3aa5888ed942303cf975beb2e/gemrb/plugins/GUIScript/GUIScript.cpp#L2010) with `wcstombs`, which uses program locale to perform convention (source wchar_t string is encoded in `ISO-8859-1`, while `wcstombs` assumes it is in `pl_PL.UTF8` locale [or `C` locale without adding `setlocale` call], hence mangled non-ASCII characters like ‘Ł’). In fact, I replaced call from `StringFromCString(name)` in character list loading method to `StringFromMBCString(name)` I've implemented using `mbstowcs` which is locale-aware, and name is correctly handled in respect of diacritic characters.

I am not familiar with engine, therefore please accept my apologies if I am mistaken.

**Comment by bradallred** [comment]
> so far I didn't notice any wrongly presented text from game resources

Again, the GUI appearance is not a good way to determine anything about the underlying string encoding which is actually going to be what matters for opening files. If you want it to be an indicator then you _must_ use a TTF font that supports whatever your encoding is and make appropriate changes to the GemRB encoding settings.

> source wchar_t string is encoded in ISO-8859-1

this is not always true; the TLK can be in various encodings. Likewise, that list you are talking about is read from the filesystem which is going to be platform dependent encoding. On my Mac this is utf8 for example.

> In fact, I replaced call from StringFromCString(name) in character list loading method to 
> StringFromMBCString(name) I've implemented using mbstowcs which is locale-aware, and 
> name is correctly handled in respect of diacritic characters.

feel free to send a pull request and we can talk about it there. However, we don't _always_ want to use the locale as we actually pull in data from various places with possibly different encodings.

We already have `StringFromEncodedData` which can take encoding options, so we should possibly make changes to that function to handle additional encoding conversions instead and call it instead of `StringFromCString` anytime we are querying the filesystem. It might be nice to break up our conversions into separate functions too.

**Comment by fenuks** [comment]
> Again, the GUI appearance is not a good way to determine anything about the underlying string encoding which is actually going to be what matters for opening files. If you want it to be an indicator then you must use a TTF font that supports UTF-16LE encoding is and make appropriate changes to the GemRB encoding settings to match your TLK encoding.

I'll keep that in mind. So far, my main focus was on getting chr file with non-ASCII characters importable. As matter of fact, I didn't yet go beyond party creation screen.

> this is not always true; the TLK can be in various encodings. Likewise, that list you are talking about is read from the filesystem which is going to be platform dependent encoding. On my Mac this is utf8 for example.

I noticed that it is TLK encoding is configurable, I didn't alter encoding in my config, and by default it is` ISO-8859-1`.

> feel free to send a pull request and we can talk about it there. However, we don't *always* want to use the locale as we actually pull in data from various places with possibly different encodings.

I will, as soon I have import machinery 100% working.

> We already have `StringFromEncodedData` which can take encoding options, so we should possibly make changes to that function to handle additional encoding conversions instead and call it instead of `StringFromCString` anytime we are querying the filesystem. It might be nice to break up our conversions into separate functions too.

I will try to use it. I went with new function that uses `mbstowcs` because I wanted to be certain that convention is correct. I wonder, though, if I know that string is encoded in local user locale isn't it more straightforward to use `StringFromEncodedData` which requires user to pass encoding? GemRB already has `MBCStringFromString`, so by analogy I wrote `StringFromMBCString` that reverses this operation.

Thank you for your patient help, and guidance! :-)

**Comment by bradallred** [comment]
`StringFromMBCString` sounds like a reasonable tool to have.

I'm still not quite sure how the Python/GUIScript stuff is going to cope with non these ascii strings.

**Comment by fenuks** [comment]
> I'm still not quite sure how the Python/GUIScript stuff is going to cope with non these ascii strings.

So far, it doesn't, text ends before first non-ASCII character. I didn't verify why is that yet.

Issue that cannot be easily solved without dedicated library is finding matching name in case-sensitive filesystems. Gemrb uppercases filenames, and later it iterates over `characters` directory, comparing case-insensitively via `strcasecmp`, which is ASCII-only.

**Comment by bradallred** [comment]
there isn't a practical reason (afik) that we need to uppercase those. We probably just do it because the original did. Go ahead and change that.

**Comment by fenuks** [comment]
> there isn't a practical reason (afik) that we need to uppercase those.

Alright, certain recreation projects strive to be as close to originals as possible, including reproduction of bugs. Therefore, I assume it's one of the main project goals, but rather to improve upon original.

There are few ways to deal with it:
* uppercasing with locale library (it is faithful to original)
* uppercasing in GUI, with storing non-modified string (faithful to original, doesn't require locale library)
* no uppercasing (in case of case-sensitive filesystems, one can have two files that when uppercased resolve to same entry, and in such situation GemRB won't be able to load second one)

> We probably just do it because the original did. Go ahead and change that.

Yes, original game does that. Okay, I will go with that.

**Comment by lynxlynxlynx** [comment]
Most of our users have a case insensitive FS, so for them it'll be only a visual change. Mixing and matching FSs could lead to the problem you describe (for them, not for case-sensitive users), but that's such a tiny corner case that it doesn't warrant special attention. Displaying the unmodified name is the way to go.

**Comment by bradallred** [comment]
yeah, displaying something as what it isn't is just confusing (especially when you have case insensitive FS). Keep the string consistent with what is on disk for everybody's sanity.
