### ISSUE TITLE
The counter on a stack of expendable items can go down to 0 and then wraps through to 65535.

### ISSUE THREAD

**Issue by kindaro** [gemrb/gemrb#651]
**Describe the bug**

Suppose I have a stack of 3 bandages in a quick item slot. I can use them 3 times and have a stack of 0 bandages. The same works with charcoal charms. If I use the stack again, I shall have what looks like a stack of 6553 items, but I suspect the last digit simply did not fit. Essentially this means infinite stacks.

GemRB version: 0.8.6

**To Reproduce**
1. Get a stack of usable items.
2. Use them up via the circular menu, one by one.
3. Observe a stack of 0 items.
4. Use the stack once again.
5. Observe a very large stack.

**Expected behavior**
Stack disappears when the counter reaches 0.

**Screenshots**
![stack](https://user-images.githubusercontent.com/2599460/78548473-8767ff80-7809-11ea-8995-f7f30c305b3c.png)

**Comment by lukas-valenta** [comment]
This looks like a good starting issue. Can I give it a shot?

**Comment by lynxlynxlynx** [comment]
Thanks for the report and thanks for volunteering! What a furtuitiuous coincidence, two new users and bam. :)

Kindaro, does it matter if the game is paused or not?

Lukas: I'd start by looking at gemrb/GUIScripts/pst/FloatMenuWindow.py, which handles this window's logic. Check where it calls Gemrb.UseItem or maybe links into InventoryCommon.py or GUICommon.py.

**Comment by kindaro** [comment]
@lynxlynxlynx  No, it does not matter whether the game is paused.

**Comment by lynxlynxlynx** [comment]
Hmm, this will likely then be a problem in core, not in the script.

I specifically disabled aura pollution (how other games limit you to one use per round) in 78593b74. Perhaps the hack is not good enough. Lukas, I suggest you look at other uses of spellCount in GameControl and where we actually consume the item on use.

**Comment by lukas-valenta** [comment]
@lynxlynxlynx yes, i think it's in the core. i did some preliminary exploration yesterday, but i was blocked by #652 before trying an older tag. i will look more closely today

**Comment by lukas-valenta** [comment]
I found out that replacement item Z_GEN2B.itm is not found and therefore the original item is not deleted. As this is my first foray into this code, I'd appreciate some testing as I don't know what else I broke. Expending items normally seems to be working now.

**Comment by lynxlynxlynx** [comment]
Where is this Z_GEN2B coming from? Items generally aren't replaced on consumption.

**Comment by lukas-valenta** [comment]
It's in Item->ReplacementItem
![image](https://user-images.githubusercontent.com/13323507/78707213-9ab1c280-7910-11ea-89df-5814bb105b57.png)

**Comment by lynxlynxlynx** [comment]
Ah yes, different game versions ... this is actually a sound in pst (.wav), while in bg1 it was a replacement item (eg. when swords broke due to the iron crisis).

Check out GF_HAS_PICK_SOUND. It looks like Inventory::BreakItemSlot shouldn't be doing what it does when this feature is enabled (it's only in pst).

It also looks like some DescriptionIcon uses could be wrong (even our docs say it overlaps with this exclusively), but that's unrelated to this particular bug.

**Comment by lukas-valenta** [comment]
i've tried again. feels a bit hacky though

**Comment by kindaro** [comment]
Fantastic!
