### ISSUE TITLE
Loading a save or starting a new game crashes.

### ISSUE THREAD

**Issue by kindaro** [gemrb/gemrb#652]
**Describe the bug**
If I either load a life or start a new one, there will be a crash.

GemRB version: e79d2b934 _(current master)_.

**To Reproduce**
Either start a new life or resume a life.

See a log with a crash report: [gemrb.out.log](https://github.com/gemrb/gemrb/files/4440397/gemrb.out.log). _(Best viewed with `less -r`.)_

**Comment by kindaro** [comment]
Please attach the label _«Planescape: Torment»_ for me. It seems that only maintainers can attach labels.

**Comment by lynxlynxlynx** [comment]
Hmm, indeed, can reproduce, checking out ...

**Comment by lynxlynxlynx** [comment]
I don't see anything obviously suspicious, but try with a reverted 9c46f7929.

**Comment by lynxlynxlynx** [comment]
Yeah, that's it, resetting normal_palette afterwards fixes it. It crashed when reseting the color on a button it was already invoked on.

**Comment by lynxlynxlynx** [comment]
Thanks everyone!

**Comment by kindaro** [comment]
Fantastic!
