### ISSUE TITLE
[bug] windows build can't handle iconv

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#654]
I give up. For the longest of times we ignored whether iconv is found or not and just never built that (the xcode project manually forces it, for example). With that fixed, it turns out Appveyor can't handle it and I don't know why. Here's all the info for anyone more lucid.

We check with our own module cmake/modules/FindICONV.cmake that specifically compiles a test to see if the setup works:
https://github.com/gemrb/gemrb/blob/0de7d8d37a829979c5cfdd922eca5b19c2bddbe7/cmake/modules/FindICONV.cmake#L50-L58

AppVeyor's log is here and it succeeds in finding a good iconv (which we install and prepare beforehand):
https://ci.appveyor.com/project/lynxlynxlynx/gemrb/builds/32022252#L2269
```
-- Looking for iconv_open
-- Looking for iconv_open - not found
-- Performing Test ICONV_COMPILES
-- Performing Test ICONV_COMPILES - Success
-- One (and only one) of the ICONV_ACCEPTS_... tests must pass
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT
-- Performing Test ICONV_ACCEPTS_NONCONST_INPUT - Failed
-- Performing Test ICONV_ACCEPTS_CONST_INPUT
-- Performing Test ICONV_ACCEPTS_CONST_INPUT - Success
```

Cool, so the test compiles and everything fine? Nope, the whole build breaks later with this decoy error:
```
c:\include\sdl\SDL_stdinc.h(581): error C2065: 'iconv_t': undeclared identifier [C:\projects\gemrb\gemrb\plugins\SDLVideo\SDLVideo.vcxproj]
c:\include\sdl\SDL_stdinc.h(581): error C2146: syntax error: missing ')' before identifier 'cd' [C:\projects\gemrb\gemrb\plugins\SDLVideo\SDLVideo.vcxproj]
```

The file is completely wrong, but that "cd" and the fact that it's complaining about iconv_t, which we're only using in one place, makes it clear where it actually chokes:
https://github.com/gemrb/gemrb/blob/0de7d8d37a829979c5cfdd922eca5b19c2bddbe7/gemrb/plugins/TTFImporter/TTFFont.cpp#L43-L52
... which looks identical to the cmake test code to me. We include the same header, call the same function, yet wahwahwah. If something was wrong with our cmake file for the plugin, I'd expect the error to be of the file (header) not being found type. But this one is like it's a missing include.

**Comment by MarcelHB** [comment]
I don't think the file is wrong, if you look at SDL v1.2.15 that AppVeyor loads, you see some suspicious parts around that region in `SDL_stdinc.h` that could also fit into the error description:
https://github.com/spurious/SDL-mirror/blob/bd1a2ca5ca3d0a1e981e1e0318b796e393c2d0ae/include/SDL_stdinc.h#L596-L605

**Comment by lynxlynxlynx** [comment]
Hmm, but the defines are resolved or it would complain about SDL_iconv_t instead. Line number info is usually quite reliable and here it doesn't match.

I could just switch the build over to sdl2, but I think we still have the inverse scrolling problem in this branch.

**Comment by MarcelHB** [comment]
Unfortunately, I cannot reproduce this on Windows, so I assume it is somewhat related to the Nuget package or MSVC.

**Comment by lynxlynxlynx** [comment]
For kicks, I printed the header and it is the same, at least the relevant parts:
https://ci.appveyor.com/project/lynxlynxlynx/gemrb#L2924

I'll just disable it for now, since it couldn't have worked before either.

**Comment by lynxlynxlynx** [comment]
Ok, appveyor is deferred. Time to recheck once we merge subviews.
