### ISSUE TITLE
Wrong portrait displayed in the center of the Level Up screen.

### ISSUE THREAD

**Issue by kindaro** [gemrb/gemrb#657]
## Description of the bug:

The Level Up screen should display the face of the relevant character in the center. Instead, the face of the Nameless One is displayed for all characters.

## Expected behavior:

The face of the relevant character is displayed. Say, if the character leveling up is Morte, Morte's face should be seen.

## Steps to reproduce the behavior:

1. Get a character to gain enough experience to level up.
1. Go to Statistics → Level Up.
1. Observe the face of the Nameless One in the center.

## GemRB version:

Current master, commit `4b2632ab6`.

**Comment by lynxlynxlynx** [comment]
@lukas-valenta if you want to take a look, this is another easy one. In fact, it should be even easier, since this will all be in python under gemrb/GUIScripts/pst (probably GUIREC.py).

**Comment by lukas-valenta** [comment]
@lynxlynxlynx i'll look into it :wink:

**Comment by lynxlynxlynx** [comment]
Oh, you can get free xp, with this shortcut:
- ctrl-space to open our console
- sps(IE_XP,somenumber)
- ctrl-space

That will set the xp for the one currently selected character.

**Comment by lukas-valenta** [comment]
i can't seem to replicate it. when i level up Morte, i don't see the screen with face at all
![image](https://user-images.githubusercontent.com/13323507/78969761-07db7880-7b08-11ea-9cf5-33ee942d67e0.png)

**Comment by kindaro** [comment]
@lukas-valenta  Not all level-ups bring that screen up. Only those where an ability point is given. The screen looks the same as when you assign points to abilities when you start a new life.

**Comment by lukas-valenta** [comment]
@kindaro I know, but i tried leveling up to max level and at no time Morte gets a point

**Comment by lukas-valenta** [comment]
@kindaro I don't remember, but i think only NO gains attribute points on level up. Did you check it in original game?

**Comment by lynxlynxlynx** [comment]
Yes, only TNO gains attribute points. If you manage to get to that screen with someone else, the problem is right there.

**Comment by kindaro** [comment]
[Check out this save game I am attaching.][save] Morte has enough experience for a level up and there will be ability point assignment.

[save]: https://github.com/gemrb/gemrb/files/4460648/morte_level_up.tar.gz

**Comment by lynxlynxlynx** [comment]
Which levels are involved? There are some special rules at 7 and 12 iirc, though I don't remember having choice (it's based on class).

**Comment by lukas-valenta** [comment]
Indeed. I think it's because your Morte is on first position, that's the bug

**Comment by kindaro** [comment]
> Indeed. I think it's because your Morte is on first position, that's the bug

Seems to be the case. I tried on another save and Dak'kon also gets an ability point on level up exactly when I put him in the first position.

**Comment by lynxlynxlynx** [comment]
Yeah, looks like I was sloppy 61070cea6. Change it to an IE_SPECIFIC check or something similar.

**Comment by lukas-valenta** [comment]
@lynxlynxlynx looks like i'm getting 2 for TNO's Specific, but elsewhere in the code it seems like TNO should be 1. is there documentation about what the stat means somewhere?

**Comment by lukas-valenta** [comment]
found it https://gibberlings3.github.io/iesdp/files/ids/pst/specific.htm
that means it should be 2 and there might be some bugs waiting :smile:

**Comment by lukas-valenta** [comment]
#664
