### ISSUE TITLE
The Rest button does nothing.

### ISSUE THREAD

**Issue by kindaro** [gemrb/gemrb#658]
## Description of the bug:

The _«Rest»_ button does nothing.

## Expected behavior:

Clicking the _«Rest»_ button should display the message _«You cannot rest in this area»_. It does so in the original game. But in GemRB, clicking the button does not display any messages.

## Steps to reproduce the behavior:

1. Start a new life or load a life.
1. Click _«Rest»_
1. Observe no visible events.

## GemRB version:

Current master, commit `4b2632ab6`.

**Comment by kindaro** [comment]
This relates to Planescape: Torment. Please attach the label for me.

**Comment by lynxlynxlynx** [comment]
Please just mention the game in the title or the main text next time. 
I think this actually works, but #177 means we don't display it.

**Comment by kindaro** [comment]
@lynxlynxlynx  Note that this message is displayed in the _«status bar»_, with a button that allows to close it and return to the default display with character faces and stuff. So it seems to be distinct from the issue you are referring to.

**Comment by kindaro** [comment]
See picture taken from the original game.
![rest_001](https://user-images.githubusercontent.com/2599460/78888491-63efbf80-7a6a-11ea-89f6-c8d45fa90c06.png)

**Comment by lynxlynxlynx** [comment]
You mean trying to rest pops open this window?

**Comment by MarcelHB** [comment]
Yes, original pops up this message if you click the rest button to the right. GemRB does nothing.

**Comment by lynxlynxlynx** [comment]
Fascinating, especially that @chilvence hasn't brought it up before or not so clearly. :)

Ok, so it looks more like a docked error window than a true message window — that's good.

**Comment by bradallred** [comment]
I wonder if we are actually appending the string and just need to have the function that MTA...

**Comment by bradallred** [comment]
yup, that is all that was needed! Unfortunately, I no longer have knowledge of how to fix it on master...

**Comment by chilvence** [comment]
Also related to this, in areas you can rest, the button is at least functional, it just doesn't ask first if you are sure you want to rest.

I think the reason I haven't brought it up or tried to fix it is I already know all the areas you can rest in, which is almost none of the areas. 

In general, you either ask certain characters if you can rest via dialogue, or you use the one tavern in the game that uses the tavern gui.

Thus I have been conditioned not to ever press the rest button and this problem dropped off my radar...  I remember when playing this game in 1999, I developed a strong dislike for that button :)
