### ISSUE TITLE
Games saved in GemRB cannot be loaded in the original game.

### ISSUE THREAD

**Issue by kindaro** [gemrb/gemrb#659]
## Description of the bug:

Games saved in GemRB cannot be loaded in the original game. Instead, the game hangs on the loading screen.

## Expected behavior:

Save files are interchangeable between the original game and GemRB.

## Steps to reproduce the behavior:

1. Start GemRB.
   1. Start a new life.
   1. Save.
1. Start the original game.
   1. Load the previously saved life.
   1. Observe the loading screen being displayed indefinitely.

## GemRB version:

Current master, commit `4b2632ab6`.

## Other notes:

I am running the original under Wine. I can load the saves made in the original game in the same location, so it is likely that the issue is with GemRB. I run the original 4 disk version of Planescape: Torment.

**Comment by MarcelHB** [comment]
It is known to occur for savegames in later states, and I guess this requires some deeper diff-ing to identify the culprit data.

**Comment by kindaro** [comment]
@MarcelHB  Note that for me it happens even when I save immediately after talking to Morte. [See example save game.](https://github.com/gemrb/gemrb/files/4455858/save-beginning.tar.gz)

**Comment by MarcelHB** [comment]
Good to know, likely to cut down the search space a lot already.

**Comment by lynxlynxlynx** [comment]
The way we usually approach this is to take the original save, resave it in gemrb and then use iediff to check for the changes in SAV and GAM files.

**Comment by MarcelHB** [comment]
There is more than one issue involved here, but the first one is already nice:

We write a variable called `dictionary_githzerai_hjacknir`. The original has `DICTIONARY_GITHZERAI_ HJACKNIR` -- notice the space that is removed in the GemRB savegame. When I manually change this, I can already debug the next one.

**Comment by MarcelHB** [comment]
Next thing, we store the `APPEARANCE` global variable. Although my disassembler shows traces of designated hardcoding/handling of that in PST, removing the variable (as in the native save game) brings us further down the road.

**Comment by kindaro** [comment]
@MarcelHB  What kind of wizardry is that? What do I need to read to be able to do this kind of stuff?

**Comment by MarcelHB** [comment]
It's some superificial combining of tools:

1. You save the game in GemRB, and load it again in PST -> Crash. So it's a good idea to load it into a debugger like [x64dbg](https://x64dbg.com/). [Crash course tutorial](https://www.youtube.com/watch?v=75gBFiFtAb8) what this is about.
2. You hit the crash point and start to look around what looks familiar: `dictionary_githzerai_hjacknir` is displayed _somewhere_ around there, sounds like PST stuff (_Githzerai_).
3. Load the GAM file into a raw editor like [HxD](https://mh-nexus.de/de/hxd/). Cool, the string appears -> looks like it's about variables, [IESDP](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/gam_v1.1.htm) tells you more. Look at the other one, no match. No wait, `hjacknir` _is_ there but the whole thing has a gap in it's name.
4. You fix the GemRB version either manually or by a tool like [NearInfinity](https://github.com/NearInfinityBrowser/NearInfinity/wiki).
5. You start the modified GAM file with PST: Cool, loading is proceeding way more than before, so that's it for sure. Still crashing, but that's next.
6. You browse the source code of `GAMImporter` for gut feelings, look for the section of variable writing, find a suspicious function called `strnspccpy`, look it up and see in the code: It [really cuts away](https://github.com/gemrb/gemrb/blob/4c619fedcb27f5928eccc4e60b0ea5c33d47306c/gemrb/core/System/String.cpp#L197-L199) what the Black Isle guys deliberately left in the code, by accident I assume.
7. Since there are still crashes, go to 1.

This was quite easy, second issue as well. Third one not so much, but I have some days of time to look at it. :wink:

**Comment by bradallred** [comment]
is the `APPEARANCE` one only a problem because of the case?

quality debugging BTW!

**Comment by lynxlynxlynx** [comment]
pst doesn't like any extra vars (GF_NO_NEW_VARIABLES). I don't know if appearance is on the list though (I can see it in the GAMs of saves that should be from the original) and it doesn't appear to be set on start by GameScript::SetNamelessDisguise and there's no way for it to be done by the equipping code. So where does it come from in our case if it's not already there? Or perhaps it is a case thing and there are a few hardcoded occurrences of Appearance.

HJACKNIR: grrr

**Comment by MarcelHB** [comment]
I'll double check the `APPEARANCE`, and I was also wondering how this would make it into the game. 

Third item on the list is related to `playerScriptsActive` but I could not resolve it yesterday since I can see it in both files with the same value, so there is something else, I guess.

**Comment by MarcelHB** [comment]
You were right, `APPEARANCE` is also located there so I was probably tired not to respect the different letter casing all the time while searchig. Which is also good, because that way it's probably the same kind of problem as the said `playerScriptsActive`.

**Comment by lynxlynxlynx** [comment]
What _is_ playerScriptsActive? I don't see it on the list of globals and we don't reference it anywhere.

**Comment by MarcelHB** [comment]
I was badly reciting memory: `partyScriptsActive`. I found it in some scripts.

**Comment by lynxlynxlynx** [comment]
Interesting, it's only checked against, never set. I guess it's tied to the party AI button, since that's how it's behaving in those scripts. The problem was that it is missing in our case or something else? I've added it now.

**Comment by MarcelHB** [comment]
Not sure yet, I see a late loading failure due to null ptr exceptions around handling these two variables in PST -- if taken from the GemRB savegame.

Anyway, I'll try case sensitivity for these guys in a minute.

**Comment by MarcelHB** [comment]
I suspect that `APPEARANCE` and `PLAYERSCRIPTSACTIVE` must not be lowercased; but there is more to come, now in the CHU part.

**Comment by lynxlynxlynx** [comment]
APPEARANCE is mentioned in title case in the exe.

**Comment by MarcelHB** [comment]
Ok, I got the main parts, we must not alter these variable names with our default filter function when writing the GAME file:

* `APPEARANCE`
* `PLAYERSCRIPTSACTIVE`
* `DICTIONARY_GITHZERAI_ HJACKNIR`
* `GAME_OVER`

This makes the earliest possible save game no longer crashing, although it looks there is some palette setup corruption still ongoing:

![gemrb_in_pst](https://user-images.githubusercontent.com/238558/78988684-f1e2ad80-7b31-11ea-80e4-a39bc80da8fa.jpg)

Anyway, enough for a first idea how to handle this (2DA file?). I'll try some later test games now.

**Comment by lynxlynxlynx** [comment]
You still mean partyScriptsActive, right? :)

I couldn't find any uses of HJACKNIR, so I'd rather treat it specially than allow spaces for everyone. It's clearly a mistake ... Or is it? Look at this  [mess](https://gist.github.com/lynxlynxlynx/d224e4570b5696975a9e4bce1a08d709). Morte_Vaxis* is in there in two formats even (makes a nice test case, I doubt both worked)! Grrrr.

Didn't look yet if our dictionary stuff could easily cope without the stripping or if affects anything else.

What do we change for the other vars?

**Comment by MarcelHB** [comment]
Aside from that space thing, I have uppercased everything completely, so not sure if that camel case may work as well. But this is how it is persisted in the native files.

**Comment by MarcelHB** [comment]
Or you mean your findings? Since we have little indication of too many hardcodings in there, I guess they may end up as bugs, so maybe we can test related scripts or quests again.

**Comment by lynxlynxlynx** [comment]
So we can try just upcasing everything when saving back to the GAM.

The originals coped fine with spaces in names, at least iwd2. Eg. the Recruit_Inspired case:
https://youtu.be/bEU3W0U14IU?t=185
And it goes to show how stupid the idea was to have scripts compiled, but the same code in dialogs as plaintext — there are no such bugs in scripts.

pst vars:
- "Absorb_Paranoid _Incarnation", no space in GAM
- "Baen _Quest", no space in GAM
- "Crystal_Escape _Answer", no space in GAM
- "CW_Statue_Cursed ", no space (raw view)
- "Jumble ", no space (raw view)
- "Morte_Vaxis _Quip_1", no space in GAM
- "Morte_Vaxis_Quip _1", no space in GAM
- "PC_Annah_Stealth ", no space  (raw view)
- "Pillar ", no space  (raw view)
- "Porphiron ", no space  (raw view)
- "Speak_With_ Dead", no space in GAM

So I conclude our behaviour is correct and we only need to fix the outlier of this hjacknir dude. Seaching the GAM for 0x20 shows he's the odd one out.

**Comment by MarcelHB** [comment]
I didn't hit anything else related to variables so far, so concerning this, if I understand you correctly:

- We write all the variables upcased, regardless of the game?
- Regarding somebody filtered out spaces in the names for some reason once upon a time -- maybe just skip trailing and leading ones in `strnspccpy`? That will eliminate this outlier while probably not breaking anything else.

**Comment by lynxlynxlynx** [comment]
No, I'd start with limiting it to those with GF_NO_NEW_VARIABLES (pst) and we can relax it as needed.

And we need to strip all, eg. Apsel_Quest from how is used both with and without internal spaces.

**Comment by MarcelHB** [comment]
Ok, I use something like https://github.com/MarcelHB/gemrb/commit/8d6ebe02b3b2d56498ebc43501c09bf02bfede5b to help myself for now.

Other than that, this works, but there are other things left to address, e. g. a crashing journal. :tada:

**Comment by lynxlynxlynx** [comment]
Looks good. :+1: 

Journal: interesting, I hope they didn't change the format. So far we believe it's the same as in other games: https://gibberlings3.github.io/iesdp/file_formats/ie_formats/gam_v1.1.htm#GAMEV1_1_Journal

BTW, NearInfinity got a new release a week or two ago and it now sports a good browser for pst quests and similar formats, besides fixing the chu viewer for iwd2.

**Comment by MarcelHB** [comment]
Good hint, I will try that out.

**Comment by lynxlynxlynx** [comment]
Heh, porting docs and I come across this gold nugget:

> 2. Journal entries:
> Journal entries will have an additional Group ID. This group ID will make it possible to remove a group of journal entries along with adding a new one of the same group using solely the dialog structure. This eliminates the problem of residue entries. Also, you don't have to remember the journal entry strref, just assign a unique group (quest ID).
> The quest ID byte will be stored on offset 0x0002 in the transition table entry.
> The former flags field (it was a dword) will be a word. Its highest bit will be the group flag. Unless this flag is set, the behaviour will be the same as before. If you set this flag, then all journal entries set with the same id will be removed before adding the new one. The scripting actions will also accept an additional quest ID parameter.

So if it's still true, it's likely we save too much for pst.

**Comment by MarcelHB** [comment]
It's not journal entries right now but quests, the check of quests.ini against the variables ends up crashing.

Aside: yes, there is code for these groups in GAMImporter but it adheres to the struct size. So if bad byte pattern are causing trouble, we'll see in a save game with more than 0 journal entries. :wink:

**Comment by MarcelHB** [comment]
Just killvars for now.

**Comment by lynxlynxlynx** [comment]
I don't know if it ever worked, but the only recent related change that comes to mind is ff254df29.

**Comment by MarcelHB** [comment]
Killvars are fixed as far as I can see. There is something left w.r.t. actor rendering, we seem to produce some incorrect CRE v1.2 files.

For TNO, bytes 0x2F2 to 0x2F5:  `20 00 20 80` make him look right. 0x2F5 works for some values/ranges (not 0) but then 0x2F2 and 0x2F4 must be set to 20 (other samples crash, can be debugged). When 0x2F5 acts as disabled, TNO looks like in the screenshot above.

Three of these bytes are marked unknown by both IESDP and NI, so we probably need to sample some more CRE bytes here to see what this is about. Since we have no known actor rendering issues in GemRB right now, I can also think of carrying these unknown bytes through from reading to writing, so we don't care but for compatibility.

**Comment by lynxlynxlynx** [comment]
"Related to colours". I can't find any related discussions, but I see we also skip a bunch more fields. We should be definitely preserving them, at least these that have effect (the others may be truly unused).

**Comment by MarcelHB** [comment]
Hm, where would you put that? I'm scanning the header files of `Actor` to find some suitable field, is it a stat? Is there bilge space or something like that for other stuff already?

**Comment by lynxlynxlynx** [comment]
Just add another member field, we do this a lot.

**Comment by MarcelHB** [comment]
Better, and I start to understand the _clown colors_, I guess. Probably just some more bytes that need treatment.

![pst_zombies](https://user-images.githubusercontent.com/238558/79042779-d42d4b00-7bfa-11ea-8688-a2bddcd4a584.jpg)

**Comment by MarcelHB** [comment]
@kindaro When this fix gets through, you can re-save in GemRB and PST should no longer crash. We cannot repair the colors, so this you must start a new game or load from a PST-native game file.

Feel free to test things and open new issues if you observe anomalies in PST after loading a GemRB game.

**Comment by lynxlynxlynx** [comment]
Interesting, is that screenshot with just the three truly unknown bytes conserved?

**Comment by MarcelHB** [comment]
3+1, yes. I added the remaing 6 after that and got it fixed.

**Comment by lynxlynxlynx** [comment]
Ok, found the research about this, it starts with this post:
https://www.gibberlings3.net/forums/topic/17733-pst-cre-file-offsets-2e1-and-2b8-2bb/?do=findComment&comment=153824 (but most of it is on the next page)

NI allows editing of this, but has no further info on the interim flag bytes. However it looks like the placement fields also have lower bit values as flags ... bleargh.

All this talk of holograms makes me think Deionarra. @chilvence besides the problems with her pop in/pop out animations, does she look properly drawn?

**Comment by chilvence** [comment]
![deionnerra](https://user-images.githubusercontent.com/1923867/79050546-9e9c5800-7c22-11ea-88ef-81ae0e6394ae.png)

I never actually noticed this, but it appears there is no transparency, the cutout box of Deionarra here is from my most recent windows gemrb build. I am having teething issues though so you may want to double check.

**Comment by lynxlynxlynx** [comment]
deion[fc] has 0c 00 0c as the 3 unknown bytes, but none of the colors set. She does have the translucent appearance flags bit on (APP_HALFTRANS). Which we don't use anywhere. So we found a missing feature, just not the one I was thinking of. :)
