### ISSUE TITLE
[There are tags for tagging issues, titles should be tag free.] Bug reporting experience is not great.

### ISSUE THREAD

**Issue by kindaro** [gemrb/gemrb#660]
**Describe the bug**

There are several problems with bug reporting experience. This may be seen as the least important grade of a bug, but it incurs a cost every time an issue is read, and issues are read many times, by many people. The fix is mostly trivial.

* One should use the _«header»_ style for a header, not the _«bold text»_ style. The latter is for inline emphasis.
* Headers should explain what the section is, not what the reporter should do. If the latter is not clear from the former, a comment can be added as, for example, currently done in the _«Screenshots»_ section.
* There should be a way to attach _«game»_ tags. Maybe this can be allowed for everyone in the repository settings. At worst, there should be a field with a header for this information, such as _«Applicable to games: …»_, say at the bottom of the issue.
* The title field should contain the title. Tags should be attached as tags.

See #658 for example.

GemRB version: It may be better to put version of GemRB to the bottom, and of course with an actual header.

**To Reproduce**

Steps to reproduce the behavior: ← There is no need for an additional explanation when the header says it all.

1. Go to repository issues.
2. Click _«New issue»_.
3. Select _«Bug report»_.
4. Observe poorly designed template.
5. Observe that tags cannot be attached.

**Expected behavior**

Well formatted with grammatically correct headers. There is a way to attach the _«game»_ tag.

**Comment by lynxlynxlynx** [comment]
Trying to structure a bit, enumerating your first list:
1. This is trivial to fix.
2. I guess the first two bother you? Also trivial to change.
3. This is a github limitation, don't worry about it. I'm sure you know it's often disabled on bugzilla as well.
4. Not sure what you mean here, is just the preset text bothering you?

Reproduction steps: yes there is a need, people botch this all the time.

**Comment by kindaro** [comment]
@lynxlynxlynx 

#### To point 3:

There should be a place for the reporter to fill in the games the issue applies to. If not by setting tags, then in a section of its own, under a header.

#### To point 4:

There is certainly no need to have the prefix `[bug]` be filled in the title of the issue when the label `bug` is already being added. The practice of putting the names of games the issue applies to in the issue title should also be discouraged, as this information is better transferred by the attached tags.

#### To reproduction section:

There may be example steps. What I am referring to as unnecessary is the line the arrow points to. Currently there are 2 lines that say essentially the same:

> **To Reproduce**

— And:

> Steps to reproduce the behavior:

Surely one would be enough. The longer line is better, as, unlike the shorter one, it is a grammatically correct noun phrase that clearly states that _steps_ should be there. Refer to #658 for example.

**Comment by lynxlynxlynx** [comment]
3. I'm not sure about the value of that. If it's important, it should be in the description. At the same time it's hard to know which games it applies to unless you test all of them. In a different project we use a table for some of this, but the formatting is not friendly at all and omissions are hard to interpret. I'm a proponent of the KISS approach, which in this case means a bit more work for us developers and less for the reporter, at least when we care about categorization, which is not always.

4. Titles should be as descriptive as conciseness allows and adding rules just complicates matters. No strong feelings about the prefixes though; might have positive anchoring effects, but who knows, we don't have any data.

5. Ah, got it.

**Comment by kindaro** [comment]
#### To point 3:

My impression is that most issues are discovered when playing. So the reporter would usually have immediate knowledge of the game the issue applies to. It needs not be exhaustive or final. Rather, the point is to remind the reporter to put this knowledge in a comfortable place where it is easy to look up.

#### To point 4:

This is exactly what I mean. Adding awkward prefixes such as `[bug] BG2` adds nothing to descriptivity in the presence of tags, so it would be more concise to avoid such notations.
