### ISSUE TITLE
Truncated text in ‘repeat throw‘ button

### ISSUE THREAD

**Issue by fenuks** [gemrb/gemrb#662]
#### Bug description
In character creation window where one can draw skill points, repeat button has truncated text, second row of text is missing.

GemRB version: **0.8.6**

#### Steps to reproduce
1. Go to character skill points drawing screen
2. See truncated text in button (probably not applicable to all versions, because it might depend on button label text, see screenshots below).

#### Expected behavior
Button height should be taller with second row of text visible.

#### Screenshots
Gemrb screenshot (draw button has only „POWTÓRZ” text)
![gemrb](https://user-images.githubusercontent.com/1249829/78938904-9c12f480-7aa2-11ea-9f99-a4b57c9765b1.png)

Original version running via wine (button is taller, with full text „POWTÓRZ RZUTY” being presented in two rows).
![original](https://user-images.githubusercontent.com/1249829/78939207-396e2880-7aa3-11ea-98c5-28f84f3d4ec2.png)

**Comment by lynxlynxlynx** [comment]
Polish, right. This is string number 11982. Please check if it has an integrated newline or not. You can break on GemRB_Control_SetText when it is passed that value to see what happens.

**Comment by bradallred** [comment]
I don't see how the button size could be different. that comes directly from the CHU. are you using the same resolution on both? That is the only way to get a different CHU (unless you have mods). Is the actual issue that they appear to be different sizes because the font is actually a different size? if so the problem is likely we are using the wrong font.

**Comment by bradallred** [comment]
this seems to work (at least on the subviews branch) as long as the `IE_GUI_BUTTON_MULTILINE` flag is set.

**Comment by fenuks** [comment]
> Polish, right.

Correct.

>  Please check if it has an integrated newline or not. You can break on GemRB_Control_SetText when it is passed that value to see what happens.

It doesn't have newline, checked both with Gemrb and Near Infinity.

> I don't see how the button size could be different. that comes directly from the CHU. are you using the same resolution on both? That is the only way to get a different CHU (unless you have mods).

I don't have mods, wanted to install widescreen one, but it doesn't support Polish version of IWD.

As for resolution, it is different, because Gemrb doesn't scale GUI to full screen when I set it to the max resolution original engine allows (1280x960 in original engine, and 800x600 in case of Gemrb, but I run both in 800x600 to verify it's not the cause).

> this seems to work (at least on the subviews branch) as long as the IE_GUI_BUTTON_MULTILINE flag is set.

Thank you, I check it.

**Comment by bradallred** [comment]
it looks like this flag is not set in the CHU so it is apparently our own invention. Probably then the right thing to do is just add it (for all those buttons) in the python script corresponding to this window

> I don't have mods, wanted to install widescreen one, but it doesn't support Polish version of IWD.

it might interest you to know the "subviews" branch will work on any resolution (640x480 and up) you choose. it may not look as nice as WSM, but it definitely is functional.

**Comment by lynxlynxlynx** [comment]
Interesting, it's indeed 1280 x 960 in the config exes and it makes more sense than our suggestion of x 1024, maintaining the aspect ratio. For me only 1024x768 can be unlocked from the unsupported modes though.

**Comment by lynxlynxlynx** [comment]
@fenuks does this fix it for you? 
http://sprunge.us/tYwcYh?diff

**Comment by bradallred** [comment]
we would probably want that set on all those buttons

**Comment by lynxlynxlynx** [comment]
Shouldn't it just be the default everywhere? We can't know which translations are too long and where.

**Comment by bradallred** [comment]
I've been wondering that myself. It feels like `IE_GUI_BUTTON_MULTILINE` was a hack and we can probably get rid of it. A lot has changed with the font/text system so it is probably not useful to have anymore. Of course I'm also open to the possibility there are CHU bits we don't use correctly too (IESDP only lists 6).

I don't think it would "break" anything if all buttons were allowed to be multiline, but it may not look as in the originals always.

**Comment by lynxlynxlynx** [comment]
IE_FONT_SINGLE_LINE has been there since 2003 and later IE_GUI_BUTTON_MULTILINE just disabled it.

Do we automatically use different padding when multiline? Or why would it be different?

**Comment by bradallred** [comment]
`IE_FONT_SINGLE_LINE` doesn't change the margins at all, it only prevents line wrapping. None of the font flags affect the printable area directly. 

However, it looks like `Button` itself applies a 5px margin if _any_ of its alignment flags are set, but not if none of them are set so that is weird I think. Doesn't matter in this case tho since the text is centered. 

That is the one case where things might look different that I can see tho. Since removing `IE_GUI_BUTTON_MULTILINE` would imply always having it set whatever buttons that have none of the alignment flags set would have their text printed 5 px more to the left than they do now.

**Comment by lynxlynxlynx** [comment]
Can't we detect this early enough though? Eg. if no alignment and lines < 2, revert the margin back to 0 (and maybe log, so we know when it happens).

**Comment by bradallred** [comment]
sure, but the text doesn't actually contain newlines so we would have to alter `Font::StringSize` to count the number of lines (if it doesn't already) and add that field to the `StringSizeMetrics` struct.

**Comment by bradallred** [comment]
try that out i guess 🤷‍♂️

**Comment by fenuks** [comment]
> @fenuks does this fix it for you?
> http://sprunge.us/tYwcYh?diff

Sorry for late reply. Yes, it does. Well, almost, bottom line is truncated, it seems to me that in original version (see screen above) top padding is a bit smaller for button with wrapped text.

![reroll](https://user-images.githubusercontent.com/1249829/79076237-14b6c280-7ce8-11ea-8dd5-6d6341a778a7.png)

**Comment by lynxlynxlynx** [comment]
I think it's just a mistake in the recent change, < vs >.

**Comment by fenuks** [comment]
My apologies, which recent change you have in mind?

**Comment by lynxlynxlynx** [comment]
Ah, try the current HEAD.

**Comment by fenuks** [comment]
Same with latest master version.

**Comment by lynxlynxlynx** [comment]
Try changing this line is what I meant:
https://github.com/gemrb/gemrb/commit/65e1b92346a06859ba79888bf357cb312bfa855c#diff-a2b770a0c12c6b5b091666a774ce156aR314

**Comment by fenuks** [comment]
Yes, that helps. With

```diff
diff --git a/gemrb/core/GUI/Button.cpp b/gemrb/core/GUI/Button.cpp
index e36a2d61f5..8dc1969cd3 100644
--- a/gemrb/core/GUI/Button.cpp
+++ b/gemrb/core/GUI/Button.cpp
@@ -312,7 +312,7 @@ void Button::DrawInternal(Region& rgn)
 
 			if (metrics.numLines > 1) {
 				// FIXME: I'm unsure when exactly this adjustment applies...
-				r = Region( r.x + 5, r.y + 5, r.w - 10, r.h - 10);
+				r = Region( r.x + 5, r.y + 5, r.w - 10, r.h - 15);
 			}
 		}
```

text looks good. I'll try more variants to find which is in line with original. `-15` looks quite okay, though:

![button](https://user-images.githubusercontent.com/1249829/79077349-81ce5600-7cf0-11ea-84aa-c18b5f06840f.png)

**Comment by bradallred** [comment]
`-15` isn't correct tho. it seems that if we have multiple lines we should dispense with the margins altogether.

**Comment by fenuks** [comment]
Comparing visually, in Infinity Engine margin is indeed reduced.

I'm not familiar with this part of code, but if you explain to me where should I start, I could try to find correct values.

With anything larger than `-15` second line of text is not displayed at all.

**Comment by bradallred** [comment]
I'm saying that multiline buttons don't seem to have any margin at all. In fact I now suspect we shouldn't be applying that margin at all anywhere; I believe it is a hack hold over from back when the font printing was broken (didn't take baseline into account).

**Comment by fenuks** [comment]
Unfortunately, that doesn't help. Version with the latest change you introduced has text has second line truncated, just as previously seen.

**Comment by bradallred** [comment]
it works now. helps if we don't invoke undefined behavior :)

**Comment by fenuks** [comment]
Ha, indeed. :) Yes, now it works perfectly, like in original.
