### ISSUE TITLE
[iwd] Biography cannot be edited or scrolled 

### ISSUE THREAD

**Issue by fenuks** [gemrb/gemrb#663]
#### Bug description
In character creation screen, biography tab displays correctly default text, but it cannot be edited nor scrolled (in my case, text is too long to fit in one screen).

Apparently there is also encoding error while accepting biography by clicking `Next` button.

```
[GUIScript/ERROR]: Syntax Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/usr/share/gemrb/GUIScripts/iwd/CharGen.py", line 2603, in BiographyDonePress
[Python/ERROR]:     GemRB.SetToken ("Biography", BIO) # just for any window reopens
[Python/ERROR]: AttributeError: ===== SetToken =====

**Prototype:** GemRB.SetToken(VariableName, Value)

**Description:** Set/Create a token to be replaced in StrRefs. QueryText() 
will use the actual value of the token when it encounters '<token>' 
substrings in a retrieved dialog.tlk entry. Some tokens are hardcoded and 
you can't affect QueryText() by setting them. Usage of those tokens should 
be avoided. The hardcoded token list:
  * FIGHTERTYPE  - always resolves to strref #10174
  * RACE         - always resolves to the race of the last speaker
  * GABBER       - always resolves to the longname of the last speaker
  * SIRMAAM      - strref #27473/#27475 depending on last speaker's gender
  * GIRLBOY      - strref #27477/#27476 depending on last speaker's gender
  * BROTHERSISTER- strref #27478/#27479 ...
  * LADYLORD     - strref #27481/#27480 ...
  * MALEFEMALE   - strref #27483/#27482 ...
  * HESHE        - strref #27485/#27484 ...
  * HISHER       - strref #27487/#27486 ...
  * HIMHER       - strref #27487/#27488 ...
  * MANWOMAN     - strref #27490/#27489 ...
  * PRO_*        - same as above with protagonist

**Parameters:**
  *  VariableName - the name of the variable (shorter than 32!)
  *  Value        - string, the value of the token

**Example:**
  ClassTitle = CommonTables.Classes.GetValue (Class, 'CAP_REF', GTV_REF)
  GemRB.SetToken ('CLASS', ClassTitle)
  # force an update of the string by refetching it
  TA.SetText (GemRB.GetString (16480))

**Return value:** N/A

**See also:** [[guiscript:GetToken]], [[guiscript:Control_QueryText]], [[guiscript:Control_SetText]]
```

Version with #650 applied does allow saving biography, but re-opened biography shows mangled non-ASCII characters, I will look into that when these changes land into master.

GemRB version: 0.8.6

#### Steps to reproduce
1. Start new game.
2. Begin creating new character, go through all tabs until `BIOGRAPHY`.
3. Try to edit biography text, or scroll it (if it cannot fit the screen).
4. If text has non-ASCII characters, clicking `Next` will result in error pasted above.

#### Expected behavior
Biography text area should be scrollable and editable.

**Comment by lynxlynxlynx** [comment]
Text editing has been completely redone for the next release (different branch), so looking at this in master is not very productive right now.

Also noting it could get much trickier, since these custom strings get stored in a TLK override file (CTLK stuff), which has to use the same encoding.

**Comment by bradallred** [comment]
if you are interested in testing it checkout the subviews branch :)

**Comment by fenuks** [comment]
Of course, I'm sure approaching weekend will have enough hours in it to play with this exciting new implementation. ;)

**Comment by fenuks** [comment]
I'm happy to inform  that subviews version works ideally, in par with original engine. Non-ASCII letters cannot be inserted (Right ALT + l, for example in Polish keyboard layout), but original didn't allow to do that as well. Only difference is that in case of IE ‘plain’ ASCII letter is inserted, whereas in case of GemRB no letter is inserted at all.

**Comment by bradallred** [comment]
That is going to be an issue with our SDL driver most likely, not an issue with the text editing. I'll open an issue with your comment.
