### ISSUE TITLE
[subviews] searchmap debugging is mostly broken

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#665]
ctrl+8 toggles it. In subviews only any path indicators are drawn and the fog-of-war is gone (similarly to the dedicated ctrl-7, but not allowing actors to draw).

Blue and red overlays from master:
![image](https://user-images.githubusercontent.com/121515/79018365-f334ca00-7b73-11ea-9a53-a9ff8f211239.png)

Didn't try if it's different on sdl2.

**Comment by bradallred** [comment]
huh, probably just a drawing origin needs to be updated to be relative to the viewport. the searchmap itself clearly still works.
