### ISSUE TITLE
Horizontal scrolling via touch pad does not work. 

### ISSUE THREAD

**Issue by kindaro** [gemrb/gemrb#666]
#### Bug description

In Planescape: Torment, vertical scrolling via touch pad pans the view as expected, but horizontal scrolling does not.

#### GemRB version

Recent _master_ `1c00d8fd6` and _subviews_ `268725892` branches, although there is a difference: in _subviews_, a large number of clicks is emitted instead, while in _master_ there is no observable effect.

#### Steps to reproduce
1. Start or resume a life.
1. Scroll with touch pad in vertical direction.
   1. Observe view panning vertically.
1. Scroll with touch pad in horizontal direction.
   1. On _master_, nothing happens.
   1. On _subviews_, a large number of clicks is emitted.

#### Expected behavior

Horizontal scrolling pans the view.

**Comment by bradallred** [comment]
what hardware exactly?

**Comment by bradallred** [comment]
this works on my Macbook. I'm not sure why the behavior would be different other than a bug/change in SDL. What version of SDL do you have? I'd try the latest (2.0.12).

**Comment by kindaro** [comment]
I have both SDL 1.2 and 2.0 installed, on Linux. Removing SDL 1.2 makes the game exit with error _«No Video Driver Available»_ on startup, so it must build against SDL 1.2 by default. Moreover, without SDL it errors out when building. How can I make it build against SDL 2?

**Comment by lynxlynxlynx** [comment]
We autodetect the sdl version if you don't force it. So if it wasn't picked up, you're probably missing the headers (often a separate package).

**Comment by bradallred** [comment]
Horizontal scrolling will never work in SDL 1; it is not possible. The issue then is that you get a bunch of clicks instead.

**Comment by kindaro** [comment]
I see. I built against SDL 2 and horizontal scrolling works alright.
