### ISSUE TITLE
IWD2: Mage spell books are read/saved incorrectly 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#667]
#### Bug description
Speaking of savegames, there is some open issue in IWD2. The way we write down spellbooks into savegames makes the original confuse.

GemRB version: master

#### Steps to reproduce
1. Take a mage in IWD2, observe mage spells/spell tabs.
2. Save the game.
3. Open in GemRB, have a look, and save again.
4. Open in native IWD2, look at the mage's spellbook again.

It's _not_ completely wrong, IWD2 shows the correct spells in the action bar!

#### Expected behavior
What IWD2 has set up and persists into the save files.
![iwd2_spellbook_mage](https://user-images.githubusercontent.com/238558/79041578-33865d80-7bf1-11ea-9bc6-2f2adb00ba80.jpg)

#### Screenshots
What GemRB reads (mages afaik don't have domain spells, so the tab should be hidden):
![iwd2_spellbook_mage_gemrb](https://user-images.githubusercontent.com/238558/79041601-57e23a00-7bf1-11ea-9aee-052580640894.jpg)

What GemRB writes and what IWD2 then sees:

![iwd2_mage_spellbook_post_gemrb](https://user-images.githubusercontent.com/238558/79041613-6a5c7380-7bf1-11ea-9a30-46bbec280e22.jpg)

**Comment by lynxlynxlynx** [comment]
Saw the domain problem before, but never got annoyed enough to check why we're granting these slots (which is likely the reason it ends up in the save). Or maybe they're misdetected at someplace, since they do contain all sorts of spells, not just divine.

**Comment by MarcelHB** [comment]
Looks as if we screw up CRE bytes 0x3B4 to 0x3B9.

**Comment by lynxlynxlynx** [comment]
```
0x03b4 | 2 (word) | AVClass value (duplicate of class, used for object matching)
0x03b6 | 2 (word) | ClassMsk bitfield value (duplicate of class, used for object matching)
0x03b8 | 2 (word) | Unknown
```
Are you talking just about gemrb saves in the original or also gem in gem?

**Comment by MarcelHB** [comment]
I only checked IWD2 -> GemRB for now:

was (by IWD2): `0B 00 00 04 00 00`
turns into (by GemRB): `0C 00 0C 00 0C 00`

Replacing these makes the save game look better.

**Comment by lynxlynxlynx** [comment]
Ah, ok. The first two are a bit confusing, since there are conflicting ids available (also with 20 suffix iirc).
