### ISSUE TITLE
[BG2] A Mind Flayer does not reappear in Mind Flayer Dungeon

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#673]
Hello,

I posted this in forum and it seems to be a bug (specific to gemrb ?) .

#### Steps to reproduce
In BG2 in the Mind Flayer Dungeon, a mind flayer is supposed to appear each time you enter in this room as I understand from this walk-through (https://sorcerers.net/Games/BG2/Walkthrough2/SoA/chapter-5/areas/mindflayer-dungeon.php)

![image](https://user-images.githubusercontent.com/55502325/79069246-08713c00-7ccd-11ea-99ce-527329e926fd.png)

![image](https://user-images.githubusercontent.com/55502325/79069253-0f984a00-7ccd-11ea-817d-cb8ba58ceb33.png)

GemRB version: master (28/03/2020) 

#### Expected behavior
A mind flayer should reappear every 60s after killing it

**Comment by lynxlynxlynx** [comment]
This works for me. You can't test by cheating carelessly though, since the script checks if you escaped from the arena first.

I didn't check its changelog, but are you perhaps playing without the fixpack?

**Comment by FrElvire** [comment]
I'm playing with fixpack (v6), I will try to find a save an try again

**Comment by lynxlynxlynx** [comment]
So what do you do, how do you get into the same situation again?

**Comment by FrElvire** [comment]
By taking a earlier save and redoing the dungeon. But as you confirm it's OK, and with my corrupted save, I think I should just close it.

**Comment by lynxlynxlynx** [comment]
Agreed, that will save us some time too.
