### ISSUE TITLE
 [BG2] Change zone with summoned creature

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#674]
#### Bug description

Normally you cannot change zone (entering house, take a stair, ....) without gathering all characters. But if you summon a creature many things are weird. I don't know if there are several issues or one ?

#### Steps to reproduce
* Select summoned creature and make it change zone : 
         - game become choppy (~4fps instead of ~30)
         - select one or more characters and they change zone directly

* When changing zone with a creature, it doesn't go in new zone (I don't see why he shouldn't). If you return to the original area, the creature is here and runs away.

GemRB version: master 28/3

#### Expected behaviour
- Summoned creature or not, you must gather your party before changing zone
- Summoned creature must follow if you change zone (don't know behaviour in original game) ?

**Comment by lynxlynxlynx** [comment]
In the original, the summons didn't follow you. A few mods add specially scripted creatures that can, but that's an exception.

Also, moving to new areas required the whole party only for big (so called master) areas. For things like houses, that's usually not the case, so you can split your party. People for example use this to cheese some lich fights.

I'm closing this, but if you can produce detailed instructions on how to get that terrible performance drop, please open a new issue.

**Comment by FrElvire** [comment]
I made a little video, where you can better see the issues : 

- at first I can't change zone with only one character
- frame rate drop when summoned creature want to change zone alone
- one character and summoned creature (not sure summoned creature reliability follow) change zone just by selecting character

https://sendeyo.com/show/a41e802ea0

hope it make things more clear
