### ISSUE TITLE
Spell trap overlay should be removed on death

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#675]
#### Bug description
Visually, magical shield doesn't follow the wearer in some circumstances : 
- ~If caster fly like beholder~ (same in the original)
![image](https://user-images.githubusercontent.com/55502325/79070030-14f89300-7cd3-11ea-8084-ff72dc37e793.png)
- if caster dies (ar2101)
![image](https://user-images.githubusercontent.com/55502325/79070037-28a3f980-7cd3-11ea-961f-24724efa3692.png)

It's here in BG2 but is it specific ?

GemRB version: master 28/3

#### Expected behavior
- caster should visually be "in" the magical shield
- shield should disappear when caster die

For these two issues, I don't know what is the behaviour in original game

**Comment by lynxlynxlynx** [comment]
I'm pretty sure the second thing is like in the original, since we tested it. Please check how beholders behaved in the original — might be fastest to just look up videos from people playing.

**Comment by FrElvire** [comment]
In original, it seems there is no difference : (5:25) https://www.youtube.com/watch?v=dDichn0kBgs

**Comment by lynxlynxlynx** [comment]
Ok, so they're using the spell trap effect. I'll edit your first post, so we don't get sidelined. I guess they gave no thought to flying enemies.
