### ISSUE TITLE
non-pcs shouldn't be able to trigger travel regions

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#676]
I made a little video, where you can better see the issues : 

- at first I can't change zone with only one character
- frame rate drop when summoned creature want to change zone alone
- one character and summoned creature (not sure summoned creature reliability follow) change zone just by selecting character

https://sendeyo.com/show/a41e802ea0

hope it make things more clear

_Originally posted by @FrElvire in https://github.com/gemrb/gemrb/issues/674#issuecomment-612621953_

The rest appears to be just a bizarre consequence.

Probably GameControl::HandleActiveRegion can take care of it.

**Comment by FrElvire** [comment]
Unfortunately the bug does not seem to be resolved.

Select only one character and try to change zone, it want you to gather your party, that's ok. Do the same with an additional summoned creature and it works.

**Comment by lynxlynxlynx** [comment]
For me there was no slowing down if at least one pc was selected.

**Comment by FrElvire** [comment]
Don't find the slowdown too (but haven't got the original video to test he same at the moment, sendeyo down...), but the third point is always here, will make another video if you want

**Comment by lynxlynxlynx** [comment]
What is the third point?

**Comment by FrElvire** [comment]
third point : one character and summoned creature (not sure summoned creature reliability follow) change zone just by selecting character.

I make a new vid where you can see at the end what is the problem. 

But I don't know if it has to do with your fix (but I had never noticed it and not seen it last weekend, so it's likely ?) : as you can see at the start of video, when releasing mouse button after selecting characters, it doesn't work evrey time (tried with most recent save in TOB, same result).
-> I can open a bug for it ?

[676.zip](https://github.com/gemrb/gemrb/files/4775155/676.zip)

**Comment by lynxlynxlynx** [comment]
This has to do with making party travel easier. Once you order it, they don't have to get completely close. With the new summon, it's position is used in the action and then everyone is closer, closer enough. I bet if the party was farther away it wouldn't work.

I don't think it's worth addressing though.

**Comment by FrElvire** [comment]
Yes I (think) understand, but in this case all members of the party must travel ?

**Comment by lynxlynxlynx** [comment]
good point, I'll open a separate issue.

**Comment by FrElvire** [comment]
> This has to do with making party travel easier. Once you order it, they don't have to get completely close. With the new summon, it's position is used in the action and then everyone is closer, closer enough. I bet if the party was farther away it wouldn't work.
> 
> I don't think it's worth addressing though.

I fear it's worth to address it as with the rest of party at the other side of the map, you can travel just with one character and a summon :(
