### ISSUE TITLE
IWD2: Toughness application is wrong 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#677]
#### Bug description

I have a human mage, CON 13, level 1. I've assigned him one point of toughness (i. e. +3 max HP) in the char. gen. Now, the original game and GemRB interpret that differently.

GemRB version: master

#### Steps to reproduce
1. In IWD2, assign toughness to a guy as described above.

#### Expected behavior
HP: 8, Max HP: 8 (displayed values!) -- NI tells me: 7/7 in the native IWD2 game, so it looks applied to the base, +1 bonus by CON 13.

#### Current behaviour
HP: 8, Max HP: 11

I guess it's not a bonus but a higher base value.

EDIT: the hardcoded toughness handling should be replaced by a normal feat spell that changes both hp and max hp. Make sure it works if you spend more than one point in chargen on it.

**Comment by lynxlynxlynx** [comment]
Interesting, so it looks like we're applying it twice. I can only see the one time, so perhaps it's one of the feat* spells in our unhardcoded/. Either way, moving it out of core and applying it like all the rest will just simplify things.

**Comment by lynxlynxlynx** [comment]
When I create pcs with toughness all seems well — was this another case of creating it in the original and then loading that?

**Comment by MarcelHB** [comment]
I remember so, yes.
