### ISSUE TITLE
[iwd] Failed to play character sound

### ISSUE THREAD

**Issue by fenuks** [gemrb/gemrb#678]
#### Bug description
In character generation section, character appearance window, voice selection, trying to play character sound fails if none is chosen. In case of original engine, by default first one is selected when window is opened.

I'd provide a fix, it's an easy one, but I can't find function to select given row/item. :/

GemRB version: Gemrb master (same applies to 0.8.6)

#### Steps to reproduce
1. Go to 'New game -> ... -> Appearance'
2. Play
3. See error

```
[GUIScript/ERROR]: Syntax Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/rkozicki/Projects/thirdparty/gemrb/gemrb/GUIScripts/iwd/CharGen.py", line 2521, in CharSoundPlayPress
[Python/ERROR]:     GemRB.SetPlayerSound (MyChar, row)
[Python/ERROR]: AttributeError: ===== SetPlayerSound =====

**Prototype:** GemRB.SetPlayerSound (Slot, SoundFolder)

**Description:** Sets the player character's soundset.

**Parameters:**
  * Slot        - numeric, the character's slot
  * SoundFolder - string, a folder in Sounds (iwd2 style), or a filename (bg2 style)

**Return value:** N/A

**See also:** [[guiscript:GetPlayerSound]], [[guiscript:FillPlayerInfo]], [[guiscript:SetPlayerString]]
```

**Comment by lynxlynxlynx** [comment]
I don't get a python error, but for both iwds the files themselves aren't found. Works fine in bgs, but they have a different soundset format.

Perhaps you have more encoding issues, what's in the log before this?

**Comment by lynxlynxlynx** [comment]
I'll fix the lookup, we can be smarter about the default anyway.

**Comment by fenuks** [comment]
I checked GUI behaviour with encoding fix, and you are correct, error above is caused by encoding. With encoding fix, sound is just not found, until user specifically selects one entry from table. I will try to correct that error.

```
[ResourceManager]: Searching for 'kobieta_mag_1
kobieta_mag_2
kobi/dfc_26'...
[ResourceManager/WARNING]: Couldn't find 'kobieta_mag_1
kobieta_mag_2
kobi/dfc_26'... Tried kobieta_mag_1
kobieta_mag_2
kobi/dfc_26.ogg kobieta_mag_1
kobieta_mag_2
kobi/dfc_26.wav kobieta_mag_1
kobieta_mag_2
kobi/dfc_26.acm kobieta_mag_1
kobieta_mag_2
kobi/dfc_26.wav 
```

**Comment by lynxlynxlynx** [comment]
It works fine for me now, please check with the latest commit.

**Comment by fenuks** [comment]
Thank you, yes, that fixes the problem. Last minor issue is that selected by default value text colour is not red, as when used selects row with mouse.

**Comment by lynxlynxlynx** [comment]
It is, there are just too many female entries for you to notice that the selected option requires scrolling to get to. Unless you create a female.

**Comment by fenuks** [comment]
Oh, my mistake. I've created male character, and in my case first male mage voices are visible, and by default 4th mage voice is selected that is off-screen.

**Comment by lynxlynxlynx** [comment]
I hardcoded the choices, but there's not much that can be done about it — your filenames are different, so if I used that to decide, we wouldn't be able to figure out where to start.

However, you can open an enhancement request: ideally we should be able to prescroll to the selected item.

**Comment by fenuks** [comment]
> However, you can open an enhancement request: ideally we should be able to prescroll to the selected item.

I can to do that. 

Another option is not to be smart about character's sex. Original engine always picks first available voice, regardless whether it's male or female. Given that list is shown in alphabetical order, it's highly dependent of game language, and might be wrong for other languages.

**Comment by lynxlynxlynx** [comment]
It is a feature in other games and most users have English, so it's better to fix the gui issue and sometimes have a bad default than to have it wrong 50% of the time.
