### ISSUE TITLE
Non ASCII keystrokes have no effect

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#679]
I'm happy to inform  that subviews version works ideally, in par with original engine. Non-ASCII letters cannot be inserted (Right ALT + l, for example in Polish keyboard layout), but original didn't allow to do that as well. Only difference is that in case of IE ‘plain’ ASCII letter is inserted, whereas in case of GemRB no letter is inserted at all.

_Originally posted by @fenuks in https://github.com/gemrb/gemrb/issues/663#issuecomment-612668426_

**Comment by bradallred** [comment]
the main issue is actually `EventMgr::CreateKeyEvent`

**Comment by bradallred** [comment]
I lied. `SDL_TEXTINPUT` events pass though `EventMgr::CreateTextEvent`. which means this is probably another encoding issue. We assume the encoding for the TLK file is what we are converting from rather than the actual keyboard locale. This can probably be addressed by the new functionality introduced by #650

**Comment by lynxlynxlynx** [comment]
So does at least ascii work for you with English data? For him, even that doesn't.

**Comment by fenuks** [comment]
Yes, entering Latin characters works. Upon trying to insert diacritic character no error is shown in console, though. In last released version, behaviour is a different, <kbd>ALT</kbd>+<kbd>l</kbd>, inserts `B`.

**Comment by lynxlynxlynx** [comment]
Ah, I misunderstood then.
