### ISSUE TITLE
[BG2] attack dice roll flawed for all but one character

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#686]
#### Bug description
For all my character but one (Imoen here, last character here) all my dice roll on attack are equal to 0 or sometime 20 (1/20 maybe), so critical miss nearly always.

console log :  
[critical.txt](https://github.com/gemrb/gemrb/files/4474284/critical.txt)

save : 
[000000056-check bug mind flayer.zip](https://github.com/gemrb/gemrb/files/4474290/000000056-check.bug.mind.flayer.zip)

I tested with 0.8.5 -> same 

And with earlier savegame, nearly the same : only one character (not the same but last too) have normal dice roll.

I try to purge cache, but no change.

Only thing I see is corrupted save ? (this game was started years ago with older version of gemrb)

GemRB version: master 28/3 (tested on 0.8.5 with same save)

#### Steps to reproduce
- in option display to hit roll
- load included savegame
- find a opponent or summon a creature and attack it with one of the character
- roll is a nearly always 0 (or 20) with all character but Imoen

#### Expected behavior
Attack roll must be between 1 and 20 and not 1or 20 for all characters

**Comment by lynxlynxlynx** [comment]
Yes, probably a corrupted save. We had some problems historically with applying the luck penalty from fatigue to rolls. If you ctrl-m on a character, the output will include something like:

> Fatigue: 0 (current: 0)   Luck: 0 

What numbers do you get?

**Comment by FrElvire** [comment]
Yes you are right is seem to be luck, here is some output :

Debugdump of Actor Anomen (Anomen, Anomen):
Fatigue: 0 (current: 0)   Luck: -38

Debugdump of Actor Elvire (Elvire, Elvire):
Fatigue: 0 (current: 0)   Luck: -56

Debugdump of Actor Jaheira (Jaheira, Jaheira): 
Fatigue: 0 (current: 0)   Luck: -56

Debugdump of Actor Imoen (Imoen, Imoen)
Fatigue: 0 (current: 0)   Luck: 0

How can this be corrected ?

**Comment by lynxlynxlynx** [comment]
select one character
ctrl-space to open the console
sps(IE_LUCK,0)
ctrl-space

repeat for everyone affected.

**Comment by FrElvire** [comment]
Thank you for saving this game and so quick :)
