### ISSUE TITLE
[BG2] Scroll map with mouse doesn't work 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#689]
#### Bug description
You can't scroll map with mouse as seen in this video

GemRB version: master (backend SDL2)

#### Expected behavior
click on map and scroll it

#### Video
https://sendeyo.com/show/deac273c82

**Comment by lynxlynxlynx** [comment]
It works fine for me, but on a lower resolution and sdl1. What resolution is this at? You should have gotten a frame border.

**Comment by FrElvire** [comment]
Here the resolution is 1280x720 (widescreen mod), I just tested on another install without widescreen mod on 800x600, always with SDL2 and the result is similar

**Comment by lynxlynxlynx** [comment]
Ok, so this is most probably fixed in the subviews branch, so won't look at it yet. You can work around it by scrolling using the buttons.

**Comment by FrElvire** [comment]
I just test, in windowed mode all is right, just KO in fullscreen. I will recheck with subviews branch when I will success to launch it.....

**Comment by lynxlynxlynx** [comment]
No need to test there, we'll merge it to the main branch in the following months.

**Comment by FrElvire** [comment]
sound good to my as of today, it doesn't work, error and segfault... I will dig a little more when merged in main branch, thanks

**Comment by bradallred** [comment]
I would definitely be interested in hearing more about that segfault

**Comment by FrElvire** [comment]
Ok, it seems it's another effect of my corrupted save. Scrolling is OK with a new game or with a earlier save at the beginning of the game, sorry....

@bradallred : I will try to give you informations about this segfault when launching gemrb from subviews branch. I will open a new bug for this, OK ?
