### ISSUE TITLE
Bad highlighting for resurrection(s) spell

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#708]
#### Bug description
When selecting target of 'resurrection spell' (other neighbour spell impacted ?), only alive characters where highlighted and not dead one, it doesn't seem logical.

here it's BG2, but is it limited to it ?

PS : always with corrupted save, so take it with caution...

GemRB version: master

#### Steps to reproduce
1. kill a character
2. select 'resurrection' spell
3. move the cursor on dead character and no highlight
4. if you click, it resurrect

#### Expected behavior
Cursor highlight only on resurrectable characters and not alive one.

#### Screenshots
![resurect_1](https://user-images.githubusercontent.com/55502325/80458660-6a6aac00-8931-11ea-8b9a-9b2d87c37f0c.jpeg)
![resurect_2](https://user-images.githubusercontent.com/55502325/80458671-6d659c80-8931-11ea-8d59-e340ce4802a1.jpeg)
![resurect_3](https://user-images.githubusercontent.com/55502325/80458683-70608d00-8931-11ea-8bbe-e41e57ac7e5a.jpeg)

**Comment by lynxlynxlynx** [comment]
Did it work in the original? I had the impression you had to cast via the portrait.

**Comment by FrElvire** [comment]
For the original I don't know, I don't have it installed and last time I tried, my saves cannot load in it. I will take a video for you to see better the problem.

**Comment by lynxlynxlynx** [comment]
I don't need a video, your description is clear enough. But we need to find how the original behaved, so we can match it (or improve upon it).

**Comment by FrElvire** [comment]
In original (tob as suggested) : when a character is killed (finger of death spell in both case), his corpse disappear so can't resurrect him by clicking on it (but by selecting it in character list on the right). 
But the cursor is highlighted on any element : stuff on floor, alive character,.... 

In gemrb : corpse is here so can be resurrected by clicking on it, cursor is highlighted only on alive character not stuff.
You can also resurrect character by selecting it in character list on the right.

Side note : in gemrb when selecting the character list on the right, the cursor don't stay a "spell" cursor like in original but a "select" cursor. (see screenshot).

spell" cursor : 
![resurect_4](https://user-images.githubusercontent.com/55502325/80475788-b3c6f580-8949-11ea-9adf-b353e342040c.jpeg)

select" cursor : 
![resurect_5](https://user-images.githubusercontent.com/55502325/80475826-c4776b80-8949-11ea-9d97-2c293b86792e.jpeg)

It seems to be the case for all spell not just this one.

I begin in gemrb a tob game to "remove" any effect of corrupted save, and same cursor change when entering on character list on the right

**Comment by FrElvire** [comment]
Note : For the cursor in subviews it's conform to original : "spell cursor" when selecting a portrait on right bar

**Comment by lynxlynxlynx** [comment]
The main "problem" will be fixed with #583, since the corpse should vanish promptly.
