### ISSUE TITLE
Cannot Initialize Video Driver 

### ISSUE THREAD

**Issue by schyzophrene-asynchrone** [gemrb/gemrb#709]
#### Bug description
I installed bg2 using unshield, and linked GamePath to the directory I installed it in using full path.
I installed gemrb using the aur package available, which is for 0.8.6.
Afterwards, typing `gemrb` in a terminal fails, with the only error displayed being `[Core/FATAL]: Cannot Initialize Video Driver.`.
The log file found in the game directory is not of much help either, it only reads:
```
[Core]: GemRB Core Initialization...
[Core]: Initializing Video Driver...
[Core/FATAL]: Cannot Initialize Video Driver.
[Main]: Aborting due to fatal error...
```
I thought that may be because I run a wayland session (with xwayland enabled), but switching to a X11 session did not resolve the bug. I couldn’t find anything that seemed relevant on the internet, neither as to how to solve it or even get an inch concerning its origin.

#### Expected behavior
I expected the game to launch. :)

**Comment by lynxlynxlynx** [comment]
This call failed for you: `SDL_InitSubSystem( SDL_INIT_VIDEO )`

So I'm afraid we can't do much about it. You can try editing the package and give it a go with SDL1. I have no other ideas yet, besides you compiling sdl2 and debugging the internals.

**Comment by bradallred** [comment]
I've added a log message that might be helpful in figuring out what failed.

**Comment by lynxlynxlynx** [comment]
@schyzophrene-asynchrone have you managed to retry? You can just grab the latest binary from the website if you don't want to bother building your own.

**Comment by schyzophrene-asynchrone** [comment]
Actually I managed to get it working by setting `SDL_VIDEODRIVER=x11`. I used to set it to `wayland-egl`, but it doesn’t seem to work at all (I keep getting errors due to this). I guess that’s just sdl support for wayland that’s still buggy or incomplete.
(Also I had a `SDL_VIDEODRIVER=wayland-egl` in my .zshrc, which explains why it didn’t solve it to switch to an X11 session.)

**Comment by lynxlynxlynx** [comment]
Ok, thanks!

**Comment by bradallred** [comment]
SDL 2 (at least recent versions) works fine under Wayland. You shouldn't _need_ to set `SDL_VIDEODRIVER` to anything to use it either. _If_ you must force it use `SDL_VIDEODRIVER=wayland` _not `SDL_VIDEODRIVER=wayland-egl`.

**Comment by schyzophrene-asynchrone** [comment]
Well, I did remove all `SDL_VIDEODRIVER` setting in my `.zshrc`, but it still defaults to `x11`. Maybe I need to restart for changes to take effect ?

Anyway, forcing it to `wayland` caused gemrb to be unable to load, as described before. I’m using SDL 2.0.12, don’t know if that’s recent enough.

**Comment by bradallred** [comment]
@schyzophrene-asynchrone can you post the error from the log? It should tell you something useful about the failure. 2.0.12 should be plenty recent, but it wouldn't hurt to download the trunk and build it yourself.
