### ISSUE TITLE
[subviews] pst: pausing the game opens msgwin 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#712]

**Comment by bradallred** [comment]
caused by the fix for #658

**Comment by lynxlynxlynx** [comment]
If #658 is fixed, then this is a different bug, since the full msgwin gets opened, not the one from the bug.

**Comment by bradallred** [comment]
huh? I'm talking about 2687258

**Comment by lynxlynxlynx** [comment]
Yeah, I'm saying that then #658 isn't fixed. And that change will probably cause other pop up problems, since pst didn't use the msgwin for anything but dialog. 

The pause string is displayed in the middle of the screen, not in a textarea or overhead, so the msgwin feedback is indeed pointless.

**Comment by bradallred** [comment]
regardless, not printing the pause text to the message window will prevent this.

**Comment by lynxlynxlynx** [comment]
As I feared, it's a wider problem. Eg. anything that will print to the inventory message label (like trying to equip something impossible) will now also pop open msgwin, even when it's hidden. Not a pst-specific issue, so I'm not sure it's worth adding further exceptions, more so since it's the wrong fix for the original bug any way.

**Comment by bradallred** [comment]
it's not the wrong fix, there is only one message window now. It is just incomplete because it also needs to be resized. Unless I'm misunderstanding what you mean.

**Comment by lynxlynxlynx** [comment]
It's not about the duplicate msgwins between various window packs, but the inventory msg label and in that pst case, about a clearly different (error) window.
![Screenshot_20200505_133049](https://user-images.githubusercontent.com/121515/81061652-0453cb00-8ed5-11ea-8fa3-671a6461c696.png)

Same thing happens if you press the pause button while having the container window open. Btw, that did print the feedback to the msgwin in the original (tried bg1).

**Comment by bradallred** [comment]
I'm developing the opinion most of this should be moved to GUIScripts...

**Comment by lynxlynxlynx** [comment]
There's a bit missing for bg2 too (scattered party displays an error window in guistore), so I started a refactoring. I think it will be nicely possible to avoid the need for another EF_ callback, but first the return values need to be untangled.

**Comment by lynxlynxlynx** [comment]
Ok, resting is done on master, so just need to merge again. Instead of reverting the original commit, we can try with just returning immediately if something got printed to the message label:
https://github.com/gemrb/gemrb/blob/ffdd233c61d90457c4740a2b02f79a0e91731f96/gemrb/core/DisplayMessage.cpp#L183-L188

That would take care of the inventory, but it won't suffice in general. Maybe after we add pst-style floating text and review all users of displaymsg and their context; hard to say. So I still suggest we revert it.
