### ISSUE TITLE
[BG2/master] No cursor after death to load or exit game in final seal (Watcher's Keep)

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#715]
#### Bug description
In the final seal in Watcher's Keep after getting and using the Warrior's Skull (see point 10 in https://sorcerers.net/Games/BG2/Walkthrough2/watchers-keep/5-final-seal.php) you have no cursor when not having "dialog box", so if you are killed it show you a box asking to load or exit game but there is no cursor, you have to kill the game.

GemRB version: master (some days ago)

BUT the problem is NOT present with subviews branch, you keep a cursor all the time.

If I understand well, this bug can be closed directly as subviews is OK.

#### Expected behavior
Having a cursor to select load or exit

**Comment by FrElvire** [comment]
I will make you a video of master and subviews as after thinking, master render feel better to me. (if there is a (relative quick) way to reproduce on original, it would be interesting)

**Comment by FrElvire** [comment]
here are the video, same save :

master : https://sendeyo.com/show/39b85e69d4

subviews : https://sendeyo.com/show/0209f1b1cb


here there are some differences (which is better or like original ?) : 
- in subviews, the cursor is always here, so no problem with dying, but there is no point of displaying it during these *nearly cinematic* scene like in master.
- in subviews, during dialog, the left and right bars are like grayed
- in subviews, at 2:50, when staying on "continue" button, a "popup" is displayed "ret : continue" (only with subviews), is it really wanted ?

If any of these comments are considered bugs, I can open them.

**Comment by lynxlynxlynx** [comment]
Nice catch, does this fix it for you on master?
http://sprunge.us/6rsMii?diff

The grayed-out thing is technically fine if ugly, since you shouldn't be able to click on any of that with any effect (in master you can click, easily getting in trouble). How did the original draw it?

The other two things do look like bugs (tooltip and the fact the cursor remains visible in cutscenes).

**Comment by FrElvire** [comment]
Even with this commit, there's no cursor on main character death (visually no change)

**Comment by FrElvire** [comment]
Is there any console command in original to play directly this game part ?

**Comment by lynxlynxlynx** [comment]
No, it's just a series of cutscenes.

**Comment by FrElvire** [comment]
I don't know how this is handled in original but there are some small things in this area :

- during theses cut scenes you can un/pause with space but there is no visual indicator, it feels like frozen/crashed 
- When you take damage, there is no sign of health level on portrait (due to being a spirit ?)
- When you complete the area by killing the mummy, nothing happen and no indication, you have to click on a portrait to exit the zone,

**Comment by FrElvire** [comment]
If this can help, the save.
[000000073-before bug no cursor on die.zip](https://github.com/gemrb/gemrb/files/4569804/000000073-before.bug.no.cursor.on.die.zip)

**Comment by lynxlynxlynx** [comment]
That fix was ok, but these scenes don't actually run in a cutscene, it's faked. Still investigating.

The new stuff you mention:
1. Not much we can do about it — just don't do it. At least I've added a fix for normal cases.
2. It's not your pcs who are taking damage.
3. Yes, this is a bug, please open a new report. The last script to run is: scut14.baf
