### ISSUE TITLE
[subviews/BG2] tooltip appear while staying on dialog button

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#717]
As seen in https://github.com/gemrb/gemrb/issues/715#issuecomment-622973110, tooltip appear while staying on dialog button (here in wk spirit warrior dream).

See video at 2:50 : https://sendeyo.com/show/0209f1b1cb

same video in zip :
[subviews.zip](https://github.com/gemrb/gemrb/files/4575513/subviews.zip)

#### Expected behavior
No tooltip displayed.

**Comment by bradallred** [comment]
how is that a bug? It's a tooltip for the button 🤷

**Comment by FrElvire** [comment]
There is not tooltip in master in this situation (continue, end dialog, ...), it's all I can say..., lynxlynxlynx said it can be a bug so I filled one.

**Comment by lynxlynxlynx** [comment]
Either way, "ret : continue" is a shitty tooltip and we should improve it or prevent it. It looks autogenerated like for the menu window. I guess the buffer is limited to three chars, since those use F-keys. In this instance, since "return" is not a synonym of "enter" most people know about and suggest the opposite of "continue", let's just kill it.

**Comment by bradallred** [comment]
I'm not inclined to complicate things with special cases. Just change "ret" to "return" or "enter" or whatever makes sense to you. There is no buffer limit.

**Comment by lynxlynxlynx** [comment]
Added a flag, so it's nice and clean.

**Comment by bradallred** [comment]
Don't the fonts have the escape and return symbols in them? I vaguely recall that they do.

**Comment by lynxlynxlynx** [comment]
Not tooltip or normal.bam, but it would also cause problems for people that substitute their fonts.

**Comment by bradallred** [comment]
It's moot since they don't exist, but it is trivial to remap those symbols from other fonts to the same character as the BAMs. No problem.

**Comment by FrElvire** [comment]
there are more location where tooltip are probably not needed : 

![sub_abilities](https://user-images.githubusercontent.com/55502325/81420905-f1e5c580-9150-11ea-838d-b4715f38c0d3.png)
![sub_accept](https://user-images.githubusercontent.com/55502325/81420919-f611e300-9150-11ea-85c7-0fa3bdfacdae.png)
![sub_alignment](https://user-images.githubusercontent.com/55502325/81420926-f9a56a00-9150-11ea-9909-931c1d6eec43.png)
![sub_appearence](https://user-images.githubusercontent.com/55502325/81420935-fd38f100-9150-11ea-9905-2bcfb2c0f8af.png)
![sub_back](https://user-images.githubusercontent.com/55502325/81420949-00cc7800-9151-11ea-9f8c-2b9702eec119.png)
![sub_class](https://user-images.githubusercontent.com/55502325/81420957-045fff00-9151-11ea-8e2c-7458109d41d6.png)
![sub_done](https://user-images.githubusercontent.com/55502325/81420975-09bd4980-9151-11ea-9105-60f1d92dfd39.png)
![sub_gender](https://user-images.githubusercontent.com/55502325/81420981-0cb83a00-9151-11ea-8569-82b5ecb3aa87.png)
![sub_name](https://user-images.githubusercontent.com/55502325/81420993-104bc100-9151-11ea-8998-e40ab1f28734.png)
![sub_race](https://user-images.githubusercontent.com/55502325/81421001-13df4800-9151-11ea-8253-0acb33d3c4ca.png)
![sub_return](https://user-images.githubusercontent.com/55502325/81421017-18a3fc00-9151-11ea-8c09-2358448882ad.png)
![sub_skills](https://user-images.githubusercontent.com/55502325/81421038-1e99dd00-9151-11ea-8933-1eae5798fb50.png)

**Comment by lynxlynxlynx** [comment]
The cancel one(s) are fine, but indeed it's a good question if buttons set default gain anything by having a tooltip that's not manually set to something different from their label.

**Comment by bradallred** [comment]
I can tell you I gained the knowledge that the return key is bound to those buttons. I think its really helpful to be able to see from the tool tip what hotkey is set for buttons.

**Comment by bradallred** [comment]
apparently there is already an ini option we support called "Hotkeys On Tooltips" and if you disable that then you won't get these.

**Comment by lynxlynxlynx** [comment]
Let's just change that "Ret" to "Return/Enter" and be done with it. Neither are available as strrefs, so other language users will just have to make do.

**Comment by FrElvire** [comment]
Yes "Return/Enter" will be more helpful, earlier I didn't realize immediately what "Ret" was
