### ISSUE TITLE
[subviews/BG2] cursor remains visible in fake cutscenes 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#718]
As seen in https://github.com/gemrb/gemrb/issues/715#issuecomment-622973110, cursor remain visible in wk spirit warrior dream during cutscenes.

See video : https://sendeyo.com/show/0209f1b1cb

#### Expected behavior
No visible cursor in cutscenes.

**Comment by lynxlynxlynx** [comment]
It's not actually a cutscene, but GameScript::SetCursorState is ran, disabling the mouse ... which apparently doesn't work or something undoes it.

**Comment by bradallred** [comment]
would you mind using a different method of uploading videos? that site has never worked for me. Does GitHub to allow video uploads?

**Comment by lynxlynxlynx** [comment]
Cutscenes are indeed fine (tob starts with one), while the other isn't. Easiest to test by just loading a game and running `ExecuteString("SetCutSceneMode()")` in the console.

**Comment by lynxlynxlynx** [comment]
Ah, no need to test even, since this was temporarily disabled with a FIXME in subviews.

**Comment by bradallred** [comment]
ah, the `WindowManager` does indeed have that functionality now so it is possible to do that at this time.

**Comment by FrElvire** [comment]
> would you mind using a different method of uploading videos? that site has never worked for me. Does GitHub to allow video uploads?

Not directly but in zip file, uploaded in #717 :)
