### ISSUE TITLE
[BG2]  Nothing happen at the end of the area in final seal (Watcher's Keep)

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#720]
When you complete the area by killing the mummy, nothing happen and no indication, you have to click on a portrait to exit the zone. (see #715 for related video or save)

GemRB version: master

#### Steps to reproduce
1. finish the area and kill the mummy
2. dialog box opend, XP gained
3. no button or dialog to respond to exit the zone
4. click on portrait to exit the zone

#### Expected behavior
something intuitive... , I don't know how is it handled in original but it seems to be a bug (as said in #715)

**Comment by lynxlynxlynx** [comment]
This is already fixed; does it not work for you with the latest build?

**Comment by FrElvire** [comment]
It works perfectly 👍
