### ISSUE TITLE
MSVC & VCPKG build: dependency dlls end up in plugins folder

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#721]
I have to open an issue for this because I haven't been able to figure it out, it's stopping me from being able to finalise my build guide

VCPKG comes with a cmake toolchain file, which runs a powershell script for each lib that is supposed to place the dependencies in the same folder as anything that links to them: 

[option(VCPKG_APPLOCAL_DEPS "Automatically copy dependencies into the output directory for executables." ON)
](https://github.com/microsoft/vcpkg/blob/c5f01e1dee0d41b8014ac6f1eeafda974917ba17/scripts/buildsystems/vcpkg.cmake#L219
)

[The actual script that does the dirty work](
https://github.com/microsoft/vcpkg/blob/c5f01e1dee0d41b8014ac6f1eeafda974917ba17/scripts/buildsystems/msbuild/applocal.ps1)

It works surprisingly well, I quickly modified the ADD_GEMRB_PLUGIN macro so that all plugins end up in their subfolders again, and the openal driver gets copies of sdl2.dll, ogg plugin gets copies of vorbis / ogg dlls etc.

That's all well and good but the problem is that this isn't what we need, gemrb knows where to find its plugin dlls, but it expects to find all the external libraries wherever gemrb.exe is (or failing that, the system dir)

Looking at the script I can't find any obvious way to change the destination target, it copies them exactly where cmake builds the related dll file and that is that. 

I really wanted to find a way to use this behaviour, because it would have been really helpful, but I don't think the VCPKG script will fit how Gemrb is set up as it is. Moving the core dll was easy because we only needed to change gemrb's cmakelists a tiny bit, but in this case, the scripts that need to change are all external.

Short of asking the vcpkg team if they could make this feature a bit more flexible, I feel like the only solution is to disable the option it and pretend it doesn't exist.

I'm torn between 4 different ways to deal with this dependency dll chore:

1: Stick with manual copying dll dependencies / adding to system path. You only have to do it once, but it isn't great from a usability p.o.v.

2: Rely on the fact that since they magically end up in the /plugin directory anyway, to just move the dependency dll's one level up with a post build command, exactly how MarcelHB suggested with the core.dll 

3: Alternatively add the /plugin folder to gemrb's dll search path, if it finds them elsewhere first then great, if not it's one option, if not the tidiest

4: Roll my own solution which doesn't have to be anywhere near as complicated as the VCPKG script, something along the lines of a post build command that runs a powershell script loosely based on the VCPKG one but simplified and modified for gemrb.

**Comment by lynxlynxlynx** [comment]
Are you saying that having the dlls near gemrb.exe is not enough for working plugins?
If not, then I think you're plugging that in at the wrong place — don't do it in ADD_GEMRB_PLUGIN, but on the gemrb binary target.

Please share your cmake diff, so it's easier to reason about it.

**Comment by chilvence** [comment]
No it's fine to have the dll files next to gemrb.exe.

It's just me trying to figure out what to do about the default automatic behaviour of VCPKG. I didn't actually add anything to the plugin macro, I was just trying to figure out where it gets the path to copy the dlls to, and it looks to me like it is directly lifted from the library output path, which is currently reset [by this line](https://github.com/gemrb/gemrb/blob/8d7e141aa0dedffd361ce4ead6fe5a5775d2fa4d/CMakeLists.txt#L508) so that the plugins don't end up in 20 different folders

That was one of the things that was confusing me all along, I couldn't work out which part of my MSVC setup was being almost smart enough but not quite. I only managed to work it out after digging through the VCPKG source a bit.

It's possible to change that to something else and have the external dlls follow that, but it seems like isn't possible to have vcpkg copy the dll's to a different directory than whichever plugin includes them. 

It's just this way since gemrb.exe doesn't actually directly reference any external libraries, the plugins do that, and vcpkg isn't smart enough to work out what is actually going on, it just does a bit extra that would work for any project that has everything lumped in the same directory.

So I couldn't decide whether to just roll with this and add a post build command to fix it, or disable the feature entirely and figure it out myself.

**Comment by lynxlynxlynx** [comment]
Ok. Option 3 sounds the cleanest to me, just another search path, but is this actually up to us at all? On linux and mac we can set [rpath](https://cmake.org/cmake/help/latest/prop_tgt/BUILD_RPATH.html), but that's not available on windows:
https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order?redirectedfrom=MSDN#standard-search-order-for-desktop-applications

So to keep it simple for the user, I'd go with option 2. Even if they don't use vcpkg, it can't hurt.

**Comment by chilvence** [comment]
Yeah, option 3 was only a vague idea I had from scanning some MS docs that suggested you could change it.

I'll go with option 2, should just be another small tweak to one of the cmakelists

**Comment by lynxlynxlynx** [comment]
Just make it not fail if the file to move isn't there and we're all set.

**Comment by chilvence** [comment]
So far that is how I am relying on detecting whether or not vcpkg dlls are in use, so it shouldn't fail on other platforms. 

I am so close to getting this done, but I am attempting to come up with something a bit more elegant, what I have so far works but it isn't as tidy as I think I can get it. 

I only keep stumbling because I keep finding out the hard way what cmake is and isn't capable of... i.e, if I knew what I was doing, I would have figured it out weeks ago :)

**Comment by lynxlynxlynx** [comment]
I have two things you maybe already looked at. CMake in command mode (cmake -E) supports "rename", which probably is equal to moving (this is how it works when scripted with file()). But since there's several files, a separate script is needed for add_custom_command anyway, so it's a moot point.

Another option is something like this, but it looks like overkill:
https://discourse.cmake.org/t/linux-copying-dependencies-using-file-get-runtime-dependencies/946/4

**Comment by chilvence** [comment]
Hopefully I shouldn't have to do anything that complex, I was mainly relying on the fact that Gemrb relies on a very short list of libraries that haven't changed for years. All I am really trying to do now is make the changes to the cmake files tidy. 

The add_gemrb_plugin macro is a really useful example, right now I have lots of stuff peppered everywhere which I probably don't actually need, I'm trying to follow that example. 

Basically right now for every plugin that has a dependency I thought I should add a custom command to its cmakelists so it is theoretically only processed if that plugin is built, but that might be way more than necessary. It's actually only just occurred to me that the cmake scripts already have variables to decide what is being built and I can use them.

If I can make it generic enough, it might also make it easy to use msys/mingw builds as well without doing anything special, which would be cool. I'd rather contribute 5 lines that do the job than 50 lines of spaghetti...

**Comment by chilvence** [comment]
I'm not particularly proud of this creation, but it does seem to work, it creates a post build and install rule to copy dependency dll's if they have been provided by vcpkg or msys pacman, either in debug or release modes (although I am not actually sure what msys does with debug libraries, so I haven't got that far yet)

https://pastebin.com/raw/QhXweSpm

patch version : https://pastebin.com/a0y2Kxtm

At the moment the names of the dll files are in pre defined lists. I see no reason why I couldn't make it a bit more flexible/intelligent though, I just wanted to keep it simple while I figured out the cmake syntax.

**Comment by lynxlynxlynx** [comment]
Nice, here are a few comments:

Please move the OPTION up next to the others. Put that in a `IF(WIN32)` instead of the main if.

Simplification: `LIST (APPEND VCPKG_DEBUG_NAMES ${VCPKG_RELEASE_DLLS})`

What dll is that -1 calculation skipping?

It will be cleaner if you create just one post build command — move it out of the foreach loop and construct the appropriate list of full filepaths sooner. Both the copy and install commands can take more than one source file, so that part doesn't need to change.

Please also put the main thing into a separate file under cmake/ and then just `include()` it in the main one. It has a very specific optional function, so can be split out nicely to improve readability.

**Comment by chilvence** [comment]
1: No problem, sounds good

2: I only need the two lists because for some weird reason the game wont find sdl2d.dll if I do a Debug build, even though it figures out the other libraries are named differently. I don't even know where to begin to look for the root cause of this. I'm not sure how important really it is to have debug info for SDL, I can't just ignore it though, because the game crashes if the wrong one is used.

3: It seems like the length of the list is 1 larger than the range needed to loop over it with foreach this way. If I don't reduce it by one, it goes out of range.

There is actually a normal way of looping over a list, foreach ( x IN LISTS Y ), but it doesn't work for me here because I needed a simple number index because of point 2 forcing me to need 2 different lists.

Actually the very newest cmake has a feature to process two lists simultaneously, but it doesn't get installed on either of my systems, so it will ruin it for anyone who doesn't have that. 

But if I could figure out the sdl2 naming issue, I could throw all of that out anyway. Either that, or I could try a more intelligent file specific approach, if there is enough information in the cmake variables to do that.

4: I didn't actually know that, so that should be a simple change

5: I was also thinking the same, would make it a lot more tidy as well if the feature  is expanded on

At least I feel like I am getting somewhere now though, I can cut down swearing at the computer by 75%

**Comment by chilvence** [comment]
That might be a false alarm, I can't actually reproduce it today. It's quite possible I had some path environment variable that needed a reboot to flush it after removing it.

**Comment by lynxlynxlynx** [comment]
So, is there any other blocker or can we expect a PR soon?

**Comment by chilvence** [comment]
Hopefully soon, I incorporated 4/5 of your suggestions, but then I ended up trying a slightly different approach.

I threw out the pre-configured name lists which I really didn't like to begin with and made a couple of extra macros to build them out of variables that are already generated by cmake. It's all split out into a win32deps.cmake file which has roughly two sections, one that tries to locate the files and one that sets up the build rules (it's a lot shorter than it probably sounds though).

I decided to rely on the fact that even if the location of .lib files is not predictable on windows, cmake already does the work of finding them anyway, and since all of the external libs follow linux path layout conventions it is actually quite easy to find the dll's by making an educated guess about the relative path from the lib directory. If that isn't enough, I use find_file in a limited scope to check for dll's that have version numbers in the name. If for any reason it fails to find anything, it prints a message detailing the manual steps that need to be taken.

I am just working on finishing the section that actually does the build rules. Since the extra functionality solved most of the original problems, I decided to write that bit again from scratch to avoid keeping unnecessary complications, I also found I don't need the strange naming hack I came up with for SDL2d.dll anymore. (that's a separate issue, but hopefully a simple one)

Anyway, although it isn't an ultimate solution, I am much more satisfied than I am with my first rough attempt. It should be flexible enough to cope with anyone's windows build setup, and if not, easily adaptable to it.

**Comment by lynxlynxlynx** [comment]
Ok, let me know once you need concrete feedback.

**Comment by chilvence** [comment]
[This is a second working prototype](https://github.com/chilvence/gemrb/blob/MSVC-tweaks/gemrb/win32deps.cmake)

It started off as just an attempt to fix the simple flaw in VCPKG, but as I was trying to adapt it to something generic that works for MinGW as well it's become a bit more complicated, and still not enough for all the optional plugins. The more I add to it the more I wonder if I am barking up the wrong tree. 

MinGW already works fine if it is set up right, and anyone using it probably knows how it works and doesn't need a 'helper' script

It's only actually VCPKG environment that fails, so it kind of needs a fallback so that it can 'work as expected'. So maybe I should have this default to 'off' under Mingw environments, and only 'on' when VCPKG is detected.

My only other personal reason for doing this is I like game directories that can survive a total system reformat and still work fine, but I might just be weird. (Hey, it's still the most reliable way to solve windows bugs)

**Comment by lynxlynxlynx** [comment]
Uff, this got complicated. Considering how many exceptions and hardcoding it includes, the original option 2 (previous approach) sounds much cleaner and robust. Hardcode all possible names of libs and copy or move up any that are present.

Still, some comments, since I already read it whole:
FIND_DLL_FROM_LIB continues its search when there are more paths, even if one was successful. 
The final FOREACH can still be removed if you clean up the previous one.
Maybe vorbisfile is enough and there's no need for the main vorbis lib.

**Comment by chilvence** [comment]
I was even thinking simpler maybe, to cut it back to just a specific fix for VCPKG and leave it at that. I can do that today just by deleting most of it. 

I can come back to this another time if I find some magic ingredient that makes it easy to do. I'm sure I could find a good way to simplify this approach if I spent enough time on it, but I realised I am trying to solve a problem that doesn't really exist. I got the benefit that I can finally read cmake scripts without getting a headache, in any case.

I only included the extra vorbis dll's because I found them in the windows packages on sourceforge, but I can check if they are actually needed

**Comment by chilvence** [comment]
I see what you mean about the FIND_DLL_FROM_LIB macro, it does keep cycling unconditionally, but it is mainly only there to skip over entries in the lists that aren't paths. In all the variables I looked at on my system, there was either a variable with one path, or a list with a debug path and a release (optimized) path packed into one and marked by list entries, which are already split into DLL / DLL_DEBUG variables. So it's just poorly named I think. It should have been something like "INTERPRET_LIB_VARIABLE", maybe. But this file grew a bit organically, somewhat like a mold...

**Comment by chilvence** [comment]
This would be an example of the whole thing stripped down to just the basic fix

https://github.com/gemrb/gemrb/compare/master...chilvence:vcpkg-fix

**Comment by lynxlynxlynx** [comment]
Thanks, left a bunch of comments on how to polish it.

**Comment by chilvence** [comment]
Revised, based on comments.

https://github.com/gemrb/gemrb/compare/master...chilvence:vcpkg-fix

I had to force push because github desktop unstashed some rubbish behind my back, so I might have obliterated the discussion, sorry for that. I don't know if that piece of software has actually been helpful, I might have had a much happier time if I never installed it...

The last thing I need to do is test the ogg plugin, because it isn't behaving for me. I am not sure how to actually do that however. I tried just replacing some audio in the game override folder but it didn't have any effect. I couldn't find any info about how to use it on the old wiki though?

**Comment by lynxlynxlynx** [comment]
Besides the two comments, there are just some style inconsistencies (comments not always starting with spaces, double spaces, spaces before parens) left. Great job!

Ogg: 
put the file somewhere the game can find it and then you can run this in the console:
GemRB.PlaySound ("resref of the file without extension")

**Comment by chilvence** [comment]
I did a quick comb over to remove extra spaces, and moved the win32 check to the beginning.

Also confirmed the ogg plugin works, so I definitely have the right dll, I am just confused about what vcpkg is doing with the filename... I tried changing the find_library function to vorbisfile-1 to test it, but then it doesn't find it, because the library is not under that name, only the dll. [Insert Jackie Chan WTF Meme Here]

**Comment by lynxlynxlynx** [comment]
Ehh, oh well. Open the PR then and maybe ask vcpkg upstream what's with the vorbis names.
