### ISSUE TITLE
 [BG2&other ?] Object on floor invisible when hidden by decor

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#729]
When dropping an object on floor behind decor (dither always activated), it's not always visible nor highlighted by 'ALT' key.

little summarize :

![image](https://user-images.githubusercontent.com/55502325/82191549-f8afcd80-98f2-11ea-9410-7a9e8df3871d.png)

![image](https://user-images.githubusercontent.com/55502325/82191652-1a10b980-98f3-11ea-8872-209f34c00a2d.png)

GemRB version: master

#### Expected behavior
State '3'

#### Screenshots
original (state 3) :

![bg2_original](https://user-images.githubusercontent.com/55502325/81413370-98c46480-9145-11ea-8e88-522d0767205a.jpg)

master (state 1) : 

![bg2_master](https://user-images.githubusercontent.com/55502325/81413389-a37ef980-9145-11ea-8639-07d75ab7422f.jpg)

**Comment by bradallred** [comment]
> on subviews option 'dither always' is always active, selected or not (bug to open or not implemented a this time

If you are _only_ using SDL2 then not a bug. This is just a limitation of SDLs hardware accelerated blending. If you are using SDL 2 + OpenGL (or SDL 1) then it should work as expected.

**Comment by FrElvire** [comment]
> > on subviews option 'dither always' is always active, selected or not (bug to open or not implemented a this time
> 
> If you are _only_ using SDL2 then not a bug. This is just a limitation of SDLs hardware accelerated blending. If you are using SDL 2 + OpenGL (or SDL 1) then it should work as expected.

here is what is being said at start : 

[Core]: Initializing GUI Script Engine...
[ResourceManager]: Found 'GUISCRCW.bam' in 'chitin.key'.
[SDL 2 Driver]: Creating display
[SDL20Video/DEBUG]: Renderer: opengl

**Comment by bradallred** [comment]
that "Renderer: OpenGL" just means that the SDL Renderer is backed by OpenGL, not that you built with OpenGL enhancements. You need to build with `OPENGL_BACKEND` to have the OpenGL support I was referring to.

**Comment by FrElvire** [comment]
> that "Renderer: OpenGL" just means that the SDL Renderer is backed by OpenGL, not that you built with OpenGL enhancements. You need to build with `OPENGL_BACKEND` to have the OpenGL support I was referring to.

OK, I have problem to execute with opengl (shaders path problem), I will make a post on forum to not pollute this bug report

**Comment by bradallred** [comment]
I believe this is resolved now, no?

**Comment by FrElvire** [comment]
On subviews, yes all is OK (SDL1, SDL2 and SDL2+OGL), for master no change at least for SDL2

**Comment by bradallred** [comment]
we're not going to bother with master

**Comment by FrElvire** [comment]
I just recheck with original and there is still one difference (I don't see it as a problem but different) .

With "always dithering" off (SDL2 apart) , you can't highlight object with 'ALT'. With original you can always highlight with 'TAB'.

**Comment by bradallred** [comment]
that's just not worth the headache to implement. we already use tab for tooltips.
