### ISSUE TITLE
[IWD] Couldn't find sound effects

### ISSUE THREAD

**Issue by fenuks** [gemrb/gemrb#731]
#### Bug description
There are numerous errors such as 
```
[ResourceManager]: Searching for 'FS_WOODa'...
[ResourceManager/WARNING]: Couldn't find 'FS_WOODa'... Tried FS_WOODa.ogg FS_WOODa.wav FS_WOODa.acm FS_WOODa.wav 
[ResourceManager]: Searching for 'FS_WOOD'...
[ResourceManager/WARNING]: Couldn't find 'FS_WOOD'... Tried FS_WOOD.ogg FS_WOOD.wav FS_WOOD.acm FS_WOOD.wav 
[ResourceManager]: Searching for 'FS_WOODa'...
[ResourceManager/WARNING]: Couldn't find 'FS_WOODa'... Tried FS_WOODa.ogg FS_WOODa.wav FS_WOODa.acm FS_WOODa.wav 
[ResourceManager]: Searching for 'FS_WOODc'...
[ResourceManager/WARNING]: Couldn't find 'FS_WOODc'... Tried FS_WOODc.ogg FS_WOODc.wav FS_WOODc.acm FS_WOODc.wav 
[ResourceManager]: Searching for 'FS_WOODb'...
[ResourceManager/WARNING]: Couldn't find 'FS_WOODb'... Tried FS_WOODb.ogg FS_WOODb.wav FS_WOODb.acm FS_WOODb.wav 
[ResourceManager]: Searching for 'FS_WOODa'...
[ResourceManager/WARNING]: Couldn't find 'FS_WOODa'... Tried FS_WOODa.ogg FS_WOODa.wav FS_WOODa.acm FS_WOODa.wav 
[ResourceManager]: Searching for 'FS_WOODb'...
[ResourceManager/WARNING]: Couldn't find 'FS_WOODb'... Tried FS_WOODb.ogg FS_WOODb.wav FS_WOODb.acm FS_WOODb.wav 
[ResourceManager]: Searching for 'FS_WOODc'...
[ResourceManager/WARNING]: Couldn't find 'FS_WOODc'... Tried FS_WOODc.ogg FS_WOODc.wav FS_WOODc.acm FS_WOODc.wav 
[ResourceManager]: Searching for 'FS_WOODa'...
[ResourceManager/WARNING]: Couldn't find 'FS_WOODa'... Tried FS_WOODa.ogg FS_WOODa.wav FS_WOODa.acm FS_WOODa.wav 
[ResourceManager]: Searching for 'FS_WOOD'...
[ResourceManager/WARNING]: Couldn't find 'FS_WOOD'... Tried FS_WOOD.ogg FS_WOOD.wav FS_WOOD.acm FS_WOOD.wav 
[ResourceManager]: Searching for 'FS_WOOD'...
[ResourceManager/WARNING]: Couldn't find 'FS_WOOD'... Tried FS_WOOD.ogg FS_WOOD.wav FS_WOOD.acm FS_WOOD.wav 
[ResourceManager]: Searching for 'FS_WOODa'...
[ResourceManager/WARNING]: Couldn't find 'FS_WOODa'... Tried FS_WOODa.ogg FS_WOODa.wav FS_WOODa.acm FS_WOODa.wav 
```
after going in-game. I checked in NearInfinity and sounds do exist, but filenames are in different format (FS_WOOD[1-6] in this example). Certain files are postfixed with letters, like FIRE01[A-B]), but they are in minority.

GemRB version: latest git

#### Steps to reproduce
1. Go to beginning of the game.
2. Move character somewhere
4. GemRB cannot find walking on the wood sounds

#### Expected behavior
Sound should be found and played.

**Comment by fenuks** [comment]
I found that in case for IWD2 numbers in sound filenames are already properly handled [here](https://github.com/gemrb/gemrb/blob/4831717a78b1e97cf1823138824b7494619143ed/gemrb/core/Scriptable/Actor.cpp#L4866). Changing flag to one that is common for Icewind Dale saga (like `GF_IWD2_SCRIPTNAME`) fixes the issue. Is such solution satisfying? I don't have plain IWD to test, but I assume sound names weren't changed in expansion.

**Comment by lynxlynxlynx** [comment]
Yeah, but we first need to check if they actually use both systems (limited to walk sounds like in iwd2?) and then GF_SOUNDFOLDERS would fit better.

**Comment by fenuks** [comment]
As far I can see and hear, it is. All other sounds are played correctly, only resource-related error printed on terminal is as follows:
```
[ResourceManager/WARNING]: Couldn't find 'amb_e45c'... Tried amb_e45c.ogg amb_e45c.wav amb_e45c.acm amb_e45c.wav 
```
(my copy of IWD has only AMB_E02B.WAV, AMB_E11.WAV, AMB_E13A.WAV, AMB_E13B.WAV  AMB_E13F.WAV, so it's some other problem, I suppose).

**Comment by lynxlynxlynx** [comment]
Ah, we handle them separately, so it's definitely safe to change it there without much fuss. :)
