### ISSUE TITLE
[BG2&other?] Level up sign (+) can temporarily disappear on portrait

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#734]
#### Bug description
On some screen (records or maps by example) level up sign can temporarily disappear on portrait when clicking on it. Sign is restored by changing screen.

GemRB version: master

#### Expected behavior
- Level up sign always remains on portrait until the character has leveled up.

#### Video
[levelUP.zip](https://github.com/gemrb/gemrb/files/4643096/levelUP.zip)

#### Save
[000000074-fin watcher keep - no dead.zip](https://github.com/gemrb/gemrb/files/4643139/000000074-fin.watcher.keep.-.no.dead.zip)

**Comment by FrElvire** [comment]
It's perfect on subviews and even better there is no flickering on level up sign when changing selected portrait

**Comment by lynxlynxlynx** [comment]
Maybe in a saved game where you're already over. I tried with cheating and had to toggle around a bit for the + to appear. But that's sort of a different problem.
