### ISSUE TITLE
[BG2 at least] Validating level up without affecting remaining points or abilities 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#735]
#### Bug description
After clicking on level up, you can't ACCEPT without affecting remaining abilities, proficiency slot or skill points.
But if you stay clicked on ACCEPT button, about 2s after ACCEPT is not greyed any more and is validated 

GemRB version: master

#### Expected behavior
Nothing happen if you stay clicked on greyed button

#### Video
[valid_levelUP.zip](https://github.com/gemrb/gemrb/files/4643219/valid_levelUP.zip)

#### Save
[000000074-fin watcher keep - no dead.zip](https://github.com/gemrb/gemrb/files/4643214/000000074-fin.watcher.keep.-.no.dead.zip)

**Comment by lynxlynxlynx** [comment]
Wow, indeed! You just press long enough and it gets enabled and clicks.

**Comment by FrElvire** [comment]
For information, ok in subviews
