### ISSUE TITLE
[subviews] Level up remaining issues

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#739]
#### Bug description
Now you can level up but there are some remaining issues :

- Cursor background on greyed button (appears elsewhere and certainly already known, so surely has nothing to do here) #281
- Level up button stay usable after levelling up

Note : flickering are just visible in video not in game
Note : renderer : SDL2 W/O OGL

#### Expected behavior
- Level up button greyed after levelling up

#### Video
[sub_levelUP2.zip](https://github.com/gemrb/gemrb/files/4648499/sub_levelUP2.zip)

#### Console output

[sub_levelUP2.txt](https://github.com/gemrb/gemrb/files/4648512/sub_levelUP2.txt)

**Comment by bradallred** [comment]
> Level up button greyed after levelling up

It's more complicated than that. The entire window needs to be refreshed. I had plans to add proper event callbacks for when a window receives/looses focus as well as a real handler for when it is closed or opened.
