### ISSUE TITLE
 [HOW] Failed to open biography edit window

### ISSUE THREAD

**Issue by fenuks** [gemrb/gemrb#742]
#### Bug description
Attempt to edit biography from character screen ends with error on console:

```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/home/fenuks/Data/Projects/gemrb/gemrb/GUIScripts/GUIRECCommon.py", line 509, in OpenBiographyEditWindow
[Python/ERROR]:     TextArea = TextArea.ConvertEdit (ScrollbarID)
[Python/ERROR]: AttributeError: 'GTextEdit' object has no attribute 'ConvertEdit'
```

GemRB version: latest git

#### Steps to reproduce
1. Go to character screen -> modify
2. Click on biography
3. See the above error on console

#### Expected behavior
Biography editing window should be opened.

**Comment by lynxlynxlynx** [comment]
Known problem since the previous text rewrite. Should be gone in the other branch.

**Comment by fenuks** [comment]
OK, I will recheck if that is indeed solved in subviews, and close issue.

**Comment by lynxlynxlynx** [comment]
No need to close, we have a special tag for that — to try to keep people from opening dupes.

**Comment by fenuks** [comment]
Alright, good to know.

Yes, windows does open.

There are some issue, though (possibly described in other place, these are notes to future self that will want to test that screen again).

Cursor movement is wacky, using left arrow it is possible to scroll beyond text until end of window frame (just like virtual edit in vim), up/down arrows don't work, it is not possible to move cursor with mouse to last line of text (nor to scroll to it by pressing left arrow key).

Pressing next doesn't save text modifications (clear button is working, and game remembers that change). Restore button works a bit differently (in original upon pressing restore editing window is closed, with GemRB button is set to inactive and text is not restored until user presses cancel, and then opens window again to see restored text).

**Comment by lynxlynxlynx** [comment]
Those should happen in all editable textareas, so worth a separate report.

**Comment by bradallred** [comment]
It's worth at least 2 separate reports IMO. The buttons and restoration stuff are clearly separate from anything to do with text editing and require different knowledge/skillsets entirely.

**Comment by fenuks** [comment]
Sorry for late reply, I've described cursor problems in #752, since I couldn't find prior report.
