### ISSUE TITLE
windows build can't handle iconv 2

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#750]
Opening as a continuation of #654. After the appveyor cleanup with vcpkg, it fails even sooner, so it's unclear if sdl1 is still a problem.

It doesn't find it, so naturally it fails:
```
-- Looking for iconv_open
-- Looking for iconv_open - not found
-- Performing Test ICONV_COMPILES
-- Performing Test ICONV_COMPILES - Failed
-- Could NOT find ICONV (missing: ICONV_TEST ICONV_COMPILES) 
CMake Warning at cmake/modules/FindICONV.cmake:100 (MESSAGE):
  Unable to determine iconv() signature
```

**Comment by lynxlynxlynx** [comment]
@chilvence please paste me a list of files installed by `vcpkg install libiconv`, these weird names are being difficult.

**Comment by chilvence** [comment]
https://pastebin.com/raw/Q7wjES7M

**Comment by lynxlynxlynx** [comment]
Thanks and success, iconv is now found ... let's see if it sdl can handle it as well.

**Comment by lynxlynxlynx** [comment]
Phew, done, the windows builds now include iconv support.
