### ISSUE TITLE
[BG2 at least] Wrong character orientation when going to open lock

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#751]
#### Bug description
When going to open a lock, I've got the impression the character is always oriented at lock location and not in the direction he is going (just a impression, it can be totally something else...)

Not found existing bug for this case precisely...

GemRB version: master/SDL2

#### Expected behavior
character not doing moonwalk :)

#### Video
[orientation.zip](https://github.com/gemrb/gemrb/files/4677846/orientation.zip)

#### Save
[000000010-orientation bug.zip](https://github.com/gemrb/gemrb/files/4677847/000000010-orientation.bug.zip)

**Comment by lynxlynxlynx** [comment]
This is would have likely been triggered by simple movement. Not sure why the orientation is being changed so rapidly, but I'm pretty sure this won't be a problem once #126 is merged, since it doesn't do so many steps.

**Comment by FrElvire** [comment]
Ok thanks, I will try when new pathfinder is merged.

**Comment by FrElvire** [comment]
It's now perfect :)
