### ISSUE TITLE
[subviews] Text Cursor movement issues

### ISSUE THREAD

**Issue by fenuks** [gemrb/gemrb#752]
#### Bug description
There are few issues with cursor movement in text edit areas. Tested with HOW, mentioned earlier in #742.

1. Cursor can be moved beyond text boundary on the right, and doesn't move to next line until edge of window is reached.
2. Up and down arrows doesn't work (original has support for them)
3. Sometimes it is impossible to go the last line of text. I didn't figure out yet what is exactly the case, but I have one game save that I can provide, which has character which causes this bug (is save from Polish version of game compatible with others?)

#### Steps to reproduce
1. Open any text edit window (e.g. biography window in char gen)
2. Try to use up/down arrows, to no action
3. Use left/right arrows, cursor will move beyond text, sometimes until window border, sometimes only few spaces beyond text
4. No instructions to reproduce third error, except for using saved state

#### Screenshots
* Invalid caret position
![invalid caret position](https://user-images.githubusercontent.com/1249829/82840895-baeb1000-9ec3-11ea-96a7-524d8fb83b76.png)

**Comment by bradallred** [comment]
probably the main issue is not handling `\r` characters

**Comment by lynxlynxlynx** [comment]
I can reproduce odd cursor placement in the English version of bg2 by just spamming dfg and space in a cleared biography. The cursor lag becomes visible sooner or later.

**Comment by bradallred** [comment]
I'm pretty sure this is resolved, no?

**Comment by lynxlynxlynx** [comment]
I think so, but not near a comp to check. Let's close and if fenuks still has problems, we can reopen.

September 4, 2020 5:03 PM, "Brad Allred" <notifications@github.com (mailto:notifications@github.com?to=%22Brad%20Allred%22%20<notifications@github.com>)> wrote:
	I'm pretty sure this is resolved, no?
