### ISSUE TITLE
mouse scrolling steps with per-pixel scrolling 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#755]
I don't remember if this is a sdl2 or a subviews change, but while it's handy for the message window when it comes to dialogs and the textscreen, the current behaviour is rendering the mouse wheel useless in text areas where the user is expected to scroll on his own. Things like the journal and item descriptions, but also the message window itself (out of dialog).

We should be scrolling by line or three in this case. Perhaps checking for IE_GUI_TEXTAREA_AUTOSCROLL and being in a dialog as a marker for when to turn on per-pixel scrolling?

**Comment by bradallred** [comment]
another case of a setting that is annoying with a mouse wheel but highly preferable with a touchscreen or a trackpad. I don't see a way around not having a setting for it. I don't know if SDL can report the type of device or not.

**Comment by lynxlynxlynx** [comment]
But don't touches generate other events? We also have EventMgr::TouchInputEnabled as a best guess. It checks for registered devices, so it won't be good enough if you have both a mouse and a touchscreen. On master we're still checking MouseFlags for this too.

**Comment by bradallred** [comment]
I believe touches should generate other events, but it would seem my trackpad does not.

**Comment by bradallred** [comment]
I'm actually surprised to hear a mouse that has distinctive steps is using mouse wheel events instead of button events. What is the delta in that case? Just a single pixel? I wonder if your mouse generates _both_ a button and a wheel event; might be useful to know.

**Comment by lynxlynxlynx** [comment]
I haven't actually checked yet, it just seemed natural ... xev says it does produce only press/release though. Pressing the scrollbar buttons does scroll by line, interesting.

**Comment by bradallred** [comment]
oh, you are probably talking about SDL 1.

In that case we have 2 options:
1. come up with a reasonable delta (12px?) and apply it where we do the `CreateMouseWheelEvent`
2. drops the `CreateMouseWheelEvent` and add logic to handle those buttons... everywhere (`TextArea`, `Scrollbar`, etc)

obviously choice 1 is the easy way out, but choice 2 allows better scrolling for the different scenarios. like being able to scroll by exactly a line.

**Comment by lynxlynxlynx** [comment]
No, this was on sdl2. Checked the dispatch now and while xev reports the presses, SDL reports mousewheel. And yes, the y delta is 1.

**Comment by bradallred** [comment]
I don't know how the SDL folks expect us to deal with this. I don't see any relevant hints.

**Comment by lynxlynxlynx** [comment]
But if only mouse wheels (emulated or not) produce mousescroll events, where's the problem? We never want per-pixel scrolling in this case.

**Comment by bradallred** [comment]
Sure we do, you are only thinking of yourself. If we scaled the delta enough to scroll a line (lets say 12px) then _my_ mouse wheel events are going to be astronomical and a slight breeze will send me up/down several lines.

**Comment by lynxlynxlynx** [comment]
So it works fine for you? Good to know. We don't need to scale the delta though, just override it.

**Comment by bradallred** [comment]
> So it works fine for you? Good to know. We don't need to scale the delta though, just override it.

I have no idea what you mean I guess. Per pixel scrolling works for me and its a Good Thing; anything else would be a sub par and frustrating user experience.

The problem, as I understand it, is your mouse generates (straight from SDL) mouse wheel events with a scroll delta of 1. I have a device where the delta is the number of _pixels_ that should be scrolled. I do not see a way to identify this case to fix it for you without breaking it horribly for me. The only option I am aware of is a setting.

**Comment by lynxlynxlynx** [comment]
So your touchpad scrolling can be done without gestures and doesn't send touch events or is this something else?

Do you ever manage or want to scroll by 1px? Special casing a delta of 1 sounds like a simple way to fix it for everyone.

**Comment by bradallred** [comment]
Right, the trackpad doesn't send touch events as far as I've been able to tell. It's not a matter of _wanting_ to scroll by a particular amount. If is barely touch the trackpad SDL reports an event with something between 6-12 in the `delta` field. That means if we used the delta as a "line" as in your case then I would scroll 6-12 lines just from touching my pad.

So on its face your suggestion for handling a `1` differently sounded plausible, but what happens is if I flick the pad (as one might normally do while scrolling to go far) you get _multiple_ events the first being the largest but then there are several that have a delta of `1`. Part of the reason I assume is that such input devices have inertia.

The problem is the mouse wheel event has no "unit" field that we can use to determine what to do intelligently. If it had such a field this would be trivial to handle.

**Comment by lynxlynxlynx** [comment]
I tried my touchpad's scrolling and it's also just sending 1s. Might be from the default setting of 1mm for vertical scrolling. It does send several events, also keydown/up, though not in any obvious order. In both cases just the event base members are set, nothing else. event.wheel.which is also 0 in both cases, so no SDL_TOUCH_MOUSEID hacks are available.

So the only other thing that comes to mind is to:
- if wheeling with a delta > 1 is detected, start ignoring delta == 1 events
- set delta == 1 events to per-line sizes

**Comment by bradallred** [comment]
that might work. I'll try it.

**Comment by bradallred** [comment]
Are you sure that if you spin the wheel really fast the events won't get rolled together?

**Comment by lynxlynxlynx** [comment]
Just tried with both devices: yes, they don't get aggregated.

**Comment by lynxlynxlynx** [comment]
Works fine here, thanks.
