### ISSUE TITLE
[subviews] wheel scrolling the worldmap scrolls in the reverse direction

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#756]
Don't have a mouse with a horizontal wheel, but it's true for the vertical.

**Comment by bradallred** [comment]
I believe there is a preference for inverting it. I also think there is a way for SDL to detect your computer's settings for it. I like inverted for my trackpad, but I can see why its annoying for a mouse wheel.

**Comment by lynxlynxlynx** [comment]
This hasn't changed for me, any ideas?

**Comment by bradallred** [comment]
when you say "world map" I thought you meant the `GameControl`. did you mean the `WorldMapControl`?

**Comment by lynxlynxlynx** [comment]
yes. I don't remember what was the case for GC, but it's now inverted.

**Comment by bradallred** [comment]
FWIW you can scroll horizontally by scrolling while holding the shift key

**Comment by lynxlynxlynx** [comment]
Doesn't work for me, but I could swear it did at some point. Tried both shifts in case L/R mattered.
The OP bug is fixed though, thanks.

**Comment by bradallred** [comment]
No idea why that would be. the code that checks for it is just `SDL_GetModState() & KMOD_SHIFT`. It's not even driveling down though the event manager to do that.

**Comment by lynxlynxlynx** [comment]
Ah, it's only done for sdl1, that's why.

**Comment by bradallred** [comment]
Thats silly. I'll fix that.
