### ISSUE TITLE
bg2: journal text has the wrong color 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#757]
For the journal journal section, titles should be green:
https://i2.wp.com/lparchive.org/Baldurs-Gate-2-and-Throne-of-Bhaal/Update%2060/26-BG2ToBch8023.jpg

Something like #003d00. Blocked by #308

**Comment by bradallred** [comment]
I checked the original and they are the red color we use now. I don't know where this green comes from. I wonder if it is dependent on the entry somehow..

**Comment by lynxlynxlynx** [comment]
No, that's the quest log.
