### ISSUE TITLE
BG: Ghost list of save games accessible from main menu 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#758]
#### Bug description
I think I just clicked in too much haste and landed in some ghost area. For my BG, below the "Load Game" button, there is blank space. But actually you end up in an empty list of save games.

GemRB version: master

#### Steps to reproduce
1. Go to BG1 main menu.
2. Click the solo play button.
3. Click below the load button.

#### Expected behavior
Nothing should happen.

#### Screenshots
Demo:
<details>
  <summary></summary>

![store](https://user-images.githubusercontent.com/238558/82845664-b3d4f980-9ee5-11ea-85f2-b40362c60a75.gif)

</details>

**Comment by lynxlynxlynx** [comment]
You don't have TotSC installed, do you?
![image](https://user-images.githubusercontent.com/121515/82845888-98b6b980-9ee6-11ea-988f-a751f9776b1a.png)

**Comment by MarcelHB** [comment]
No, I don't.

**Comment by lynxlynxlynx** [comment]
We do have HasTOTSC, but it needs to be moved to GameCheck first if you want to disable the button properly. Perfect time to remove the hack currently in gemrb/GUIScripts/bg1/Start.py
