### ISSUE TITLE
Behavior of escape key 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#762]
#### Description
I don't know how you see this, but usually 'Esc' key close the current window and if there is no open window, open 'option/parameter' window.

Actually :

master : 
'Esc' close open windows except 'journal' one (does nothing)
'Esc' does nothing when there is no open window

Subviews : 
'Esc' close open windows except disabled one (mage spell or priest spell when no applicable)
'Esc' does nothing when there is no open window

Note : on subviews, game is paused when opening 'records' window (this one only)

Pausing game when opening 'option' can make sense too, and remove pause when closing window ?

**Comment by lynxlynxlynx** [comment]
options pause too, so let's not have two separate discussions in the same thread.

I don't like the idea of esc opening the options window. Besides it already having a hotkey, it would break reseting of the action window. Eg. if you are  selecting spells or item abilities, you can esc out of it.

**Comment by FrElvire** [comment]
So that leave these 2 "anormal" behavior : 

in master, 'Esc' doesn't close 'journal' windows
in subviews, 'Esc' doesn't close greyed window (mage spell and/or priest spell)

side note : in subviews, options doesn't pause game

**Comment by bradallred** [comment]
yeah, we have no ability to assign 2 hot keys to a button.

I've fixed the `esc` key not closing disabled windows and I'll push it up later after I'm done working on things.

**Comment by bradallred** [comment]
You _could_ change your options hot key to `esc`... if the keymap parsing code supports it. Might only work on subviews, I don't know.

**Comment by bradallred** [comment]
I don't think there is a reason to keep this open. If you want to use `esc` as a hot key for options that needs to be an enhancement request. We won't ever support 2 hotkeys, but you could assign esc in the keymap or add an `esc` key handler in `GameControl` to run the `OpenOptionsWindow` function.
