### ISSUE TITLE
Encoding problems in AI script window

### ISSUE THREAD

**Issue by fenuks** [gemrb/gemrb#764]
#### Bug description
Current script text area in character AI screen is mangling non-ASCII characters. Problem is related to my work on encoding. Prior to that change, no description was shown due to silent encoding error.

Issue is that QueryText returns now string that is encoded with user system encoding (which is needed if string is filename, like in importable characters list), and here it causes problem (text is [queried here](https://github.com/gemrb/gemrb/blob/22802a62f6465316f5fcb7afa62949305dec3eec/gemrb/GUIScripts/GUIRECCommon.py#L447) (it is in `UTF-8` in my case), and is immediately set in description text area (it expects string encoded in game encoding, `WINDOWS-1250` in my case).

I think situations where text from control is later used to reach some resource on user system that is sensitive to encoding (like filenames) is way rarer, so I think that it will be best to return string in game encoding from QueryText [here](https://github.com/gemrb/gemrb/blob/22802a62f6465316f5fcb7afa62949305dec3eec/gemrb/plugins/GUIScript/GUIScript.cpp#L1999), and explicitly convert between encodings where character is imported [here](https://github.com/gemrb/gemrb/blob/22802a62f6465316f5fcb7afa62949305dec3eec/gemrb/GUIScripts/iwd/CharGen.py#L2708) (and possibly in few other places yet to be discovered).

I've already checked this solution, and it works fine.

GemRB version: 

#### Steps to reproduce
1. Open character screen
2. Click modification -> script
3. See encoding errors

#### Screenshots
![encoding problems](https://user-images.githubusercontent.com/1249829/83075753-e3117500-a063-11ea-9b38-1cf94bde0d30.png)

**Comment by lynxlynxlynx** [comment]
Yeah, adding an optional parameter to QueryText  to enable fs-mode sounds fine. The default then remains the same and only a handful of calls in python need to be updated.

**Comment by fenuks** [comment]
Alright, I will address that in future MR.
