### ISSUE TITLE
[subviews] Mouse wheel stops working in lists

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#770]
#### Bug description
I took IWD2, opened the list of savegames and used the mouse wheel for scrolling. Then you observe two things:

1. You can only scroll down -- not up.
2. Once at the bottom, you can no longer use the wheel even after manually dragging the bar upwards again. Not even after exiting the load menu and re-entering.

In BG2, this interestingly works a couple of times up and down, but eventually arrests as well.

#### Steps to reproduce
1. Go to the list of save games in IWD2
2. In IWD2, scroll down by mouse wheel
3. Try to scroll up, or try to scroll down again after reset

#### Expected behavior
Should allow both mouse wheel directions, and never stop to do so.

**Comment by bradallred** [comment]
I can't reproduce this

**Comment by bradallred** [comment]
I have to assume this is again due to the mouse wheel delta-of-one issue. Unlike `TextArea`s per pixel scrolling doesn't make sense for these sorts of lists. We will need a new flag to change the clamping behavior when you can't scroll by some number of pixels.

**Comment by bradallred** [comment]
Will you see if that works for you?

**Comment by MarcelHB** [comment]
Much better :+1:
