### ISSUE TITLE
[subviews] IWD2 Pick-up inventory cut off a bit

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#772]
#### Bug description
When trying to pick something up at 1024x768, the inventory misses a bunch of pixel rows at the bottom.

#### Steps to reproduce
1. In IWD2, pick up something from the ground.

#### Screenshots

![iwd2_inventory](https://user-images.githubusercontent.com/238558/83698324-749f5a80-a601-11ea-8da6-28c6bb541da5.jpg)

**Comment by lynxlynxlynx** [comment]
Both chus look fine and now I see the same problem is there with 800x600. Looks like it gets relayouted incorrectly, since it's already set to bottom.
