### ISSUE TITLE
[subviews] World map problems

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#773]
#### Bug description
In the games I have tested, the world map shows two problems:

1. It does not update the PCs position while walking
2. When opened again, it turns black.

#### Steps to reproduce
1. In BG/IWD/IWD2, load a game and move a PC
2. Open the world map, not the stuck positions
3. Close the world map, open again.

#### Expected behavior
As in master: live updates of the PCs' positions, no black map.

**Comment by FrElvire** [comment]
1 is OK, but for 2, it's not corrected : map is black at second opening.

**Comment by bradallred** [comment]
I don't understand how to reproduce it then

**Comment by bradallred** [comment]
> To reproduce hit 'M' to open map, 'M' to close map and 'M' to reopen map (and this time, map is black)

Not for me

**Comment by FrElvire** [comment]
I don't know if this can help but to see it (map stay black after that..). 

[black_map.zip](https://github.com/gemrb/gemrb/files/4738729/black_map.zip)

Note : border of electricity shield seems black (not in master), and vertical line in right border or the screen (related to SDL2 ?), I can open bug(s) if they are and not already known

**Comment by bradallred** [comment]
videos don't help, its not like I don't believe you :)

**Comment by MarcelHB** [comment]
I can still reproduce this.

**Comment by bradallred** [comment]
again, its not that I don't believe you

**Comment by lynxlynxlynx** [comment]
which backends are you guys on?

**Comment by MarcelHB** [comment]
Still SDL2 without OpenGL.

**Comment by bradallred** [comment]
I've tried all 3 variants and all work. What backend is SDL using? there is a "Renderer:" log message.

**Comment by MarcelHB** [comment]
Direct3D, I'll try OpenGL again then.

**Comment by bradallred** [comment]
I suspect then perhaps the TODOs regarding `SDL_RENDER_DEVICE_RESET` and `SDL_RENDER_TARGETS_RESET` need to be addressed. I don't have any Windows systems to do that tho. Somebody else will have to write it.

**Comment by MarcelHB** [comment]
It's the same for OpenGL here. I will then try Linux.

**Comment by bradallred** [comment]
assuming this used to work for you, you could do me a solid and bisect it :)

**Comment by MarcelHB** [comment]
My Linux shows the same phenomenon. I have no idea if and when this worked on subviews, so I'd pick something in the last year or so.

**Comment by FrElvire** [comment]
yes here Linux with sdl2 without openGL

**Comment by bradallred** [comment]
> My Linux shows the same phenomenon. I have no idea if and when this worked on subviews, so I'd pick something in the last year or so.

well it had some changes recently, so I'd start there. but also no need to bisect if you just want to debug it. It's pretty simple to determine if its even attempting to draw at least.

**Comment by lynxlynxlynx** [comment]
I can also reproduce (sdl2+ogl), but I could swear this was fine recently. Just from #754 #753 .

**Comment by MarcelHB** [comment]
Bisect tells me 02db8454cea55b1235583d442ecd906e34e60293 to have introduced that.

**Comment by bradallred** [comment]
since I can't reproduce can one of you fiddle with it? It is behaving like the map is null.

**Comment by MarcelHB** [comment]
I'll try.

**Comment by bradallred** [comment]
`MapMOS->acquire();` maybe this was needed after all?

**Comment by MarcelHB** [comment]
Unfortunately not, I will dig through later.

**Comment by MarcelHB** [comment]
When I remove that check:
```cpp
if (newMap != MyMap) {
```
then it works.

**Comment by lynxlynxlynx** [comment]
Isn't MyMap random the first time around, since it's not initialized?

**Comment by MarcelHB** [comment]
Looks good now.

**Comment by bradallred** [comment]
thanks everyone
