### ISSUE TITLE
[subviews] Transparency under cursor in BG2 char customization

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#777]
#### Bug description
SDL2 in use. See screenshot.

#### Steps to reproduce
1. In BG2, try to customize a secondary PC over the char stats panel.
2. Hover over the buttons that are disabled.

#### Screenshots
![bg2_customize_char](https://user-images.githubusercontent.com/238558/83781482-e671b580-a68e-11ea-87e1-04ed142f7444.jpg)

**Comment by bradallred** [comment]
this will be fixed with #281
