### ISSUE TITLE
[subviews] Visual artifact on exhausted spells in book of BG2

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#778]
#### Bug description
When the spell is used, or when you insert a new spell, its slot in the spellbook is not dithered or shaded. See screenshot instead. SDL2.

#### Screenshots
![bg2_spellbook](https://user-images.githubusercontent.com/238558/83782388-09e93000-a690-11ea-99c4-8f119da62138.jpg)

**Comment by bradallred** [comment]
missing a `BLIT_BLENDED` somewhere for sure

**Comment by bradallred** [comment]
I'm not able to reproduce this one either...

**Comment by MarcelHB** [comment]
I was about to say that you're right, looks gone. But I got it once again. Not sure what the conditions are then.

**Comment by bradallred** [comment]
it could be some Python script is setting the "border" on those to the wrong color

**Comment by bradallred** [comment]
alternatively, did you run into a python error when this occurred?

**Comment by MarcelHB** [comment]
Not that I noticed, but I'll look for one.

**Comment by MarcelHB** [comment]
No Python error, but also kind of too infrequent and non-disruptive to really dig deeper in my opinion.
