### ISSUE TITLE
[subviews] adding a WF_BORDERLESS heuristic?

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#781]
Many more windows need this bit, so after adding a few more I wondered if we can do better and be smart about it. Does anything else but the start and chargen need the frames? If not, we could condition the default bit value on core->GetGame() being (not) null.

**Comment by bradallred** [comment]
nothing I know of. That seems like a sensible thing to do actually. We should try it.

**Comment by lynxlynxlynx** [comment]
Will tackle this next and then continue the testing — almost through the backlog now.

**Comment by lynxlynxlynx** [comment]
Ok, checking Game isn't good enough, since we now started immediately with cg. But checking for an area works.
