### ISSUE TITLE
[subviews] custom biography isn't saved

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#782]
Continuing from #742, but it's also visible in bg2 (tested in guirec, not cg). We have all the needed ctlk code, but since the window is broken on master, I can't say if it got rebroken after it worked a couple releases ago.

**Comment by bradallred** [comment]
this actually seems to be working for me. By that I mean I can edit it, click "done" and edit again and my changes are there. I don't know if it is persistent if I save and load.

**Comment by lynxlynxlynx** [comment]
It works now, yes.
