### ISSUE TITLE
[subviews] can't write a biography

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#783]
Maybe will be resolved together with #752, but to see the problem:
- open guirec, customize, biography
- clear biography
- try to input text — doesn't work (besides hitting #780 )

**Comment by bradallred** [comment]
actually #780 isn't a problem (at least not with SDL 2, not sure about 1) since text edit events are separate from key events.

**Comment by lynxlynxlynx** [comment]
Seems to be fixed, thought I'd also expect the cursor to be visible immediately, not just after a character is input.

**Comment by bradallred** [comment]
I think all the remaining problems are captured by other issues
