### ISSUE TITLE
[subviews] ground pile border isn't transparent

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#787]
notice the black outline:
![image](https://user-images.githubusercontent.com/121515/83895182-a411ac80-a752-11ea-97e8-9c4153bd5c4a.png)

**Comment by bradallred** [comment]
that fixes it for SDL 1. Not sure why 2 doesn't just work tho; kinda seems like an SDL bug.

**Comment by bradallred** [comment]
possibly [this change](http://hg.libsdl.org/SDL/rev/5c4ad9fc7b21) fixed it? What ever the fix was it seems that conversions involving both a color key and palette alpha didn't work as expected. Since SDL 2 textures don't support palettes there is an internal conversion that happens when we create a texture for these types of surfaces.

**Comment by lynxlynxlynx** [comment]
Hmm, that's unfortunate — we'll have to note in our docs that 2.0.12 and older has some drawing problems.

**Comment by bradallred** [comment]
I don't know if it is all older versions, but yeah let's make a note of it.

as for web, looks like SDL 1 also has the blackness so probably not the same issue. Blackness like that seems like the effect isn't being blended so hopefully just a missing `BLIT_BLENDED`

**Comment by bradallred** [comment]
hmmmm web thing is due to the `palette->alpha = true;` I just added in `ScriptedAnimation`. not really sure what to do here, but maybe sleep will help. 

Seems like removing that would break something in SDL 1 tho and there is some funny palette business happening in that code I don't understand.

**Comment by bradallred** [comment]
web et al should be fixed now too

**Comment by lynxlynxlynx** [comment]
Web still works fine in sdl1 too.

**Comment by lynxlynxlynx** [comment]
I added a note to INSTALL; did you want to leave this open?
I do get some intermittent transparency issues on sdl1 with helmets, but don't know if that's related.

**Comment by bradallred** [comment]
did the helmets use the old "shadow" flags? If not then it is certainly a different issue.

**Comment by bradallred** [comment]
lets open a new issue for the helmets
