### ISSUE TITLE
[subviews] mouse wheel load game crash

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#788]
Something new, just try wheeling:

```
Thread 1 "gemrb" received signal SIGFPE, Arithmetic exception.                                          
0x00007ffff7f36079 in GemRB::ScrollBar::OnMouseWheelScroll (delta=..., this=0x10366f0)
    at gemrb/gemrb/core/GUI/Control.h:161
161             ValueRange GetValueRange() const { return range; }
(gdb) p range
$1 = {first = 0, second = 0}
```

**Comment by bradallred** [comment]
so division by 0. the question is how did you manage to get a scrollbar with a range of 0... I guess an empty list would do it?

**Comment by lynxlynxlynx** [comment]
no, I have a few saves.

**Comment by bradallred** [comment]
right, by "empty" I meant something that doesn't require scrolling.

**Comment by lynxlynxlynx** [comment]
yes, that's the end result. 6 saves, of which two are not fitting, so 4, which is the slot count. It works fine in my tob list, where there are more.

**Comment by bradallred** [comment]
fixed yeah?
