### ISSUE TITLE
Can't scroll description in options (at least)

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#789]
By example in options/gameplay, description of option is at bottom of window but as description change when fly over options you can't scroll description.

In original to have description you have to click on specific option so you can scroll description

GemRB version: master or subviews

#### Expected behavior
Same as original ??? or scroll description with mouse wheel, up/down key, something else while on selected option ??? or something else ???

#### Screenshots
![option_desc_scroll](https://user-images.githubusercontent.com/55502325/83924632-5c584880-a785-11ea-89c6-30f0b5cfe959.jpg)

**Comment by bradallred** [comment]
so the original doesn't use mouse enter/exit at all?

**Comment by lynxlynxlynx** [comment]
Might be only pst or some other game.

**Comment by bradallred** [comment]
lets find out how all the games work so we can make a plan that doesn't break something else

**Comment by burner1024** [comment]
In BG2, as long as scroll bar is displayed, you can scroll (it's not displayed when the text fits fully).
In BG1, you additionally need to mouse over the description field.
In PST, description text fits fully into the field (at least in English), so there's no scroll bar ever, just mouseover.
In IWD, same as BG2.

Doesn't really matter much how to do this, as long as descriptions can actually be read. Simplest way, leave current situation (scroll always displayed), and allow to scroll it always, like BG2/IWD.

**Comment by lynxlynxlynx** [comment]
And iwd2 has enough space everywhere. It didn't do on-hover.
