### ISSUE TITLE
[BG2(TOB)] The screen goes black for a short time when entering the pocket plane in some circumstance 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#790]
When entering pocket plane in BG2 with this save screen goes black for a short time. It's a save taken after finishing Saradush area and returning in pocket plane. 

Hard to explain, so take a look at video or just load the save.

Not able to reproduce it by just going to pocket plane at random time.

Subviews with SDL2 (ok in master)

#### Expected behavior
No black screen

#### Video
[subviews_SDL2_black_screen.zip](https://github.com/gemrb/gemrb/files/4738652/subviews_SDL2_black_screen.zip)

#### Save
[000000012-fin saradush.zip](https://github.com/gemrb/gemrb/files/4738656/000000012-fin.saradush.zip)

**Comment by bradallred** [comment]
I don't understand the problem; that looks like a scripted fade. that's the only time we do a fade AFIK.

**Comment by FrElvire** [comment]
to me it's weird : you see your character, then black screen, then you character with spell effect. 

Master behaviour  (to me seems more natural) : 
[master_SDL2_black_screen.zip](https://github.com/gemrb/gemrb/files/4738693/master_SDL2_black_screen.zip)

If for you it's normal/wanted, don't hesitate to close :)

**Comment by bradallred** [comment]
there are likely 2 bugs:
1. the fade is apparently broken on master (or it gets canceled by something?)
2. we have a bad order of operations which causes the fade to be delayed

IIRC the fade happens on load in the originals too, but I can't check

the bad fade has been a problem for as long as I can remember. You can easily see it by starting a new game in BG2 on master. On subviews we hack around it by inserting an additional fade in the CharGen script.

**Comment by lynxlynxlynx** [comment]
master works like your video for subviews here (and always has — but I've been using sdl1). Same for subviews on sdl2. bg2ee has the same problem, while the original doesn't appear to; but it could be loadscreen related, since the loading is that slower.

So not sure we should be doing anything extra. You mentioned you can't reproduce it reliably, but haven't explained how it's different from any other time you enter the PP or load a save for it. This whole fade and pomp is in the area script.

**Comment by FrElvire** [comment]
In fact in game it's perfect. But if you save in pocket plane, at reloading it displays :

- character for a short time
- fade 
- animated graphical effect as if you just entered in.

Its just the short characters display which fell not natural (In original, screen begin black)

**Comment by bradallred** [comment]
like lynx said, the loading screen time in the original might just disguise the issue. If you hear the sound effects at any point then that's a clear indication that the original behaves this way too and you just can't see it; if BG:EE has the same issue that's likely.

I'm not sure there is anything we can do about the point scripts begin to execute safely. Changing things around might easily break something else.

**Comment by FrElvire** [comment]
Ok, so can it can be closed :)
