### ISSUE TITLE
[subviews] Shield not dithered

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#791]
The magic shield is hidden instead of being dithered.

Subviews (SDL2+OGL), Ok in master 

#### Expected behavior
shield dithered when hidden

#### Screenshots
![shield_dithering](https://user-images.githubusercontent.com/55502325/83928227-42236800-a78f-11ea-8332-69755030fc79.png)

**Comment by bradallred** [comment]
this isn't how the original works tho

**Comment by FrElvire** [comment]
Here it's with opengl (if I'm not mistaken)

**Comment by bradallred** [comment]
> Here it's with opengl (if I'm not mistaken)

I'm not sure what that has to do with what I said

**Comment by lynxlynxlynx** [comment]
What area is this?

**Comment by MarcelHB** [comment]
That's Saradush castle. AR5001 or AR5002, don't have NI here right now.

**Comment by lynxlynxlynx** [comment]
Thanks, it is AR5001. Just wanted to double check it was really that ugly (the black around the rug).
