### ISSUE TITLE
[subviews] Unexpected map closure

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#793]
Open map, click on 'N' button on upper right, you obtain the world map.
Now click on the 'N' button at the top left and the map window closes.

Note : The tooltip on the "N" button on the world map displays "M", so it makes sense that the map closes
Note 2 : It's a way to display again area map instead of black map (#773)

#### Expected behavior
Return to area map instead of map close

**Comment by lynxlynxlynx** [comment]
This is from #754, arguably an improvement over the original.

**Comment by FrElvire** [comment]
there is something weird at least : 

open area map -> 'N' button at the top right -> world map
          -> M -> switch to area map
          -> 'N' button at the top right with 'M' in tooltip -> close map

**Comment by bradallred** [comment]
we can just remove the `Button.SetHotKey('m')` if we prefer `m` to drop back to the map window instead. doesn't matter to me.

**Comment by bradallred** [comment]
or if we still want the 'm' key for that button then change the handler to `OpenMapWindow` instead

**Comment by FrElvire** [comment]
What I find weird is that on world map 'N' button close map instead of returning to area map.
'M' key for only open/close map window (and not returning to area from world map) seems logical to me too.

But after all, it's more a matter of taste than anything else

**Comment by bradallred** [comment]
I've said how that can be changed. feel free to submit a PR

**Comment by FrElvire** [comment]
OK, I will see what I can do.
