### ISSUE TITLE
[subviews] Unexpected character change when changing window

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#794]
Select one of character, open by example inventory, then select another character.
Now if you select another window, by example priest scroll, the character selected is reverted to first selected.

[char_change.zip](https://github.com/gemrb/gemrb/files/4740053/char_change.zip)

And another very similar (same cause ?) but selected character and window can differ. A little harder to trigger (related to disabled windows I thing), video will explain....

[char_change_2.zip](https://github.com/gemrb/gemrb/files/4740056/char_change_2.zip)

Here are some console error, logically related
[error.log](https://github.com/gemrb/gemrb/files/4740055/error.log)

Subviews/SDL2/OGL

**Comment by bradallred** [comment]
open a new issue with step to reproduce for that python error please
