### ISSUE TITLE
[subviews] Breakages in PST/GUIINV.py

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#804]
There's lots of broken functionality in the PST inventory window in the subviews branch which works fine in the other games. Currently it is impossible to drag and drop anything, there may be other glitches too.

I did a bisect and traced the point where it broke to [this commit](https://github.com/gemrb/gemrb/commit/1b324807e4edb538a09eecb81453dcac137addaa) but it didn't really make sense why that would cause a problem so instead I started updating the python scripts based on the already working examples.

https://github.com/gemrb/gemrb/compare/subviews...chilvence:subviews-pst-GUIINV

These changes restore basic function, but it's not enough because for some bizarre reason if you try and drag the top left eyeball/earring slot it picks up your default weapon instead. Everything else seems fine though.

So, I'll open this bug report for now until I can figure that part out, at least then its a known issue.

**Comment by chilvence** [comment]
Ach, never mind, in the initialiser I should have used >= instead of >, because the control ID's start at 0 instead of 1 like in BG.... I thought it was something completely unrelated.

I'll do some more in game testing and submit a PR

**Comment by lynxlynxlynx** [comment]
You can also just use `if Button:`, since on subviews a missing control for GetControl does not raise an exception any more.

**Comment by chilvence** [comment]
That works as well.

I also need to fix the mouse highlight handlers, do we want to use the cool fancy item highlighting behavior from the other games or just keep it as is?

**Comment by lynxlynxlynx** [comment]
What  do you mean? Just maintain parity with master for now.

**Comment by chilvence** [comment]
^ There's some new color pulse on mouse hover that looks pretty cool, but my priority is just straightening it out, so I'll do that.

I wouldn't expect any of the bugs I've found to actually affect many people, since its subviews branch, but I hope fixing pre-emptively will help

I do feel like I have pulled on the proverbial loose thread of the sweater though. I've got dragging, mouse highlighting, item splitting, item using and talking back to working properly, but I will give it another few days to see if anything else springs up.

**Comment by bradallred** [comment]
the hover effect wasn't intentional in the inventory, it was a change so that hovering an actor on `GameControl` would pulse the portrait button for the actor (like the original does).

It just didn't bother me for it to be on the inventory buttons (in fact I found it useful) so I never bothered creating a way to disable it. If we are going to keep it I would like to set the borders for the non-magic items as well so that it is a consistent behavior for all items.

**Comment by chilvence** [comment]
Ah right, so serendipitous :)

What about merge strategy for this? I wasn't intentionally trying to do too much to an active dev branch, I just wanted to test it out to be honest and I got a bit sidetracked

Is it better if I rebase this on master? Or just keep it around for when it is needed?

**Comment by bradallred** [comment]
A merge strategy for what? If you have fixes for this branch just submit a PR on this branch. If you have fixes that you can apply on master then send a PR to that branch instead.

**Comment by lynxlynxlynx** [comment]
If that portrait pulsing was implemented already, it's now broken again.

chiv: yeah, and just exclude things you think don't fit.

**Comment by bradallred** [comment]
> If that portrait pulsing was implemented already, it's now broken again.

I don't remember if I finished it or not... so long ago. its not important to fix that before merging tho so it'll wait for now :)

**Comment by chilvence** [comment]
I just meant I have no experience knowing how robust git is at merging, so for example, if I do some fixes to this file in subviews, and later someone else does other fixes to the file in master, does it cause a headache? (I know it's probably a dumb question, but, this isn't my trade...)

**Comment by MarcelHB** [comment]
If there is a three-way diff, then yes. Original line is A, on master it turns A -> B, on subviews it turns A -> C, then there is a conflict. If you serialize it, e. g. merge one into the other and then do the locale change, it's fine.

**Comment by chilvence** [comment]
@MarcelHB Thanks for the Nutshell clarification ^ :) , sorry for not answering immediately, but I got lost in a sort of personal learning experience so to speak.

I've tried to rebase these fixes on master a couple of times, but I quickly realized that there wasn't actually much broken in master, the new bugs I found in subviews were just a result of refactoring of various things.

PST has always suffered a little bit because it is a black box compared to the other games, but these problems I reported here are just a couple of things that have been broken the refactoring that has been done so in subviews. That in itself is a consequence of the fact that the branches of the game have never been fully harmonised, mainly because there is so much left to figure out.

My gut tells me that it would be more productive to close this issue and worry about it when the dust settles a bit. I would much rather keep my hands off all of this until subviews becomes mainline.

**Comment by bradallred** [comment]
I would think fixing this is a requirement for that to happen. Why can't you just submit your PR against that branch?

**Comment by chilvence** [comment]
My gut tells me that I will be changing these PST GUI files a lot and I really don't want to concern you with all that noiseI think it will save some headaches if I put this on a shelf, focus on the absolute basics, and then let them filter into subviews by the regular merge. There wasn't anything here that was really hard to fix, it was all just a knock on effect of the refactoring going on.
