### ISSUE TITLE
Do we need a comms plan?

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#805]
Since the rest of you probably don't visit the site, just noting the fresh news \m/
https://gemrb.github.io/2020/06/11/unexpected-new-use-case-of-gemrb.html

As a teaser for the upcoming release, I think it would be also good to convert Brad's wiki article to a news one in a month or two:
https://github.com/gemrb/gemrb/wiki/Subviews---Origins-and-Summary-of-Changes

Then comes the anniversary stuff, tracked in #352 . Need to prepare a list of current (FLOSS) (gaming) sites to notify. Our news post will be like a press release in a sense.

kmfrick will write something about the pathfinder.

After that, nothing special comes to mind. We fixed the site, improved both the user experience and developer startup & onboarding, and the next release will just simplify the instructions further. So I think we're well set to grow and I can slowly stop focusing on all this "soft" stuff. 

Therefore I currently don't see a need for a proper communications plan, but of course it's good to have some news a few times per year.

**Comment by chilvence** [comment]
*stunned silence*

"Yes, that's just how I remember the game, yes :)"

**Comment by bradallred** [comment]
That was truly epic! Don't think I didn't notice the subtle cursor change either 🤘

**Comment by lynxlynxlynx** [comment]
The author promises more. :metal:

**Comment by lynxlynxlynx** [comment]
For the anniversary, a whole week of goodies is planned and going forward, we'll just continue as before — post news as anything newsworthy happens.
