### ISSUE TITLE
[subviews] UpdatePortraitWindow() called excessively with specific items equipped

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#807]
I was testing some of my original save games from my test play through and noticed the game was really struggling in some of them
(https://github.com/gemrb/gemrb/files/4771699/000000241-PST.Carceri.Dialog.Bug.zip)

(ignore the save name, it is for another already logged issue)

I tracked it down to a point in the python scripts where the animated portrait is updated, it seems like the core tries to look for bmp and mos files, but in Torment they are bam files so the resource manager spams the log with warnings.

![file system thrashing](https://user-images.githubusercontent.com/1923867/84519542-2ad20680-acca-11ea-9d3a-0bbe195c8bc9.jpg)

The hidden problem is that something is causing 'UpdatePortraitWindow()' to be run every single frame, which is a real drag. So I decided to ctrl-y my party members one by one to see if any of them had a script or item that was causing this, turned out Dak'kon's lower left tattoo was the culprit, and taking it off stops the endless refreshing. (inventory is currently broken, but ground dumping still works for testing).

Actually removing either constitution related tattoo stops the endless refreshing, so there is some kind of clash happening when both tattoos are equipped.

This is not a problem in master, so if I can't follow the breadcrumb trail here further, I will try to do a bisect when I have a good opportunity

**Comment by bradallred** [comment]
I don't actually know for sure, but I thought we just called that every frame so that the portrait hit points and effect icons are kept up-to-date. I'm actually surprised to hear that we don't call it indiscriminately.

So I think this is expected for certain equipment.

**Comment by lynxlynxlynx** [comment]
Hmm, I don't think a bisect will be particularly useful, we just need to follow the code to see why it's triggering the callback that often. Sure, con effects affect hp, but that should be transparent to the guiscripts.

**Comment by bradallred** [comment]
just put a conditional breakpoint in `Interface::SetEventFlag` for when the flags contain `EF_PORTRAIT`

**Comment by chilvence** [comment]
Hmm, if the Portrait window is supposed to be refreshed every frame intentionally, maybe the drag is only being caused by the file searching. That should only really need to be done if the portraits are rearranged or the game is re loaded, so I'll work at it from that angle.

**Comment by bradallred** [comment]
well, if it doesn't happen in master than its not supposed to happen here. I was saying I was surprised (but pleased to hear) that we are actually selective about it.

**Comment by chilvence** [comment]
This might just be a collision of three different issues then

1: The GUI script does excessive redundant portrait searching when it could just remember the portrait file names (I can fix that)
2: The core is looking for the wrong file type of portrait for PST, the only game that is different here I think
3: The combination of CON adjustment items triggering some weird refresh loop

**Comment by bradallred** [comment]
the solution looks like we should wait to clear the `EF_PORTRAIT` flag until after that function runs. so just move that to below I would think.

**Comment by chilvence** [comment]
Sorry, just tried that but looks like it is not so easy. I'll keep digging though, I just had to make a note of it somewhere so I don't forget the details.

**Comment by bradallred** [comment]
just use the breakpoint then, it will tell you exactly where that flag is getting set from. no digging required.

**Comment by chilvence** [comment]
I should have taken that advice first, but Visual Studio is still a total mystery to me.

I managed to narrow it further to a logjam between these two lines:

https://github.com/gemrb/gemrb/blob/5ad9b7d4f53127911ff6ca8a04a8f8575efd153f/gemrb/core/Scriptable/Actor.cpp#L1296

https://github.com/gemrb/gemrb/blob/5ad9b7d4f53127911ff6ca8a04a8f8575efd153f/gemrb/core/Scriptable/Actor.cpp#L3299

**Comment by lynxlynxlynx** [comment]
In pcf_hitpoint, try adding `&& oldValue != hp` to the check at 1296. I doubt it will help, but worth a shot.

**Comment by bradallred** [comment]
all the `pcf_` stuff looks the same. does `Actor::UpdateActorState` show up in the backtrace? does it behave differently prior to 246b08e?

**Comment by chilvence** [comment]
No it doesn't seem to be that at fault, I checked out 7bf19c9 and it's the same there. Also tried that extra check, but it wasn't successful. 

My gut tells me it will be something really simple though. I will do a bisect anyway because it is easy enough to do while doing other stuff, if I can pinpoint the exact moment where it stops working the same as it does in the master, it might save a headache, there are just so many systems interacting that the actual culprit always turns out to be a surprise...

**Comment by lynxlynxlynx** [comment]
It should be getting called as often on master, but perhaps PrevStats can be used to limit it. If the end result of effect application/refresh is the same as the tick before (and the hps stayed the same), there's no reason to force a refresh.

**Comment by lynxlynxlynx** [comment]
I've made a change to master to limit needless callbacks from pcf_hitpoints, but that won't stop the file search error in GemRB_GetPlayerPortrait. It's from the extension that was done to the function (it doesn't just return the resref any more) and the fact that bams are treated as animations, not images. I'll silence it.

**Comment by lynxlynxlynx** [comment]
Forgot to say that I didn't notice any sluggishness, so I don't know if this is now good enough or if it will be once the branch is synced with master again.

The save does show other dialog problems in pst on subviews though; most noticeably that only the responses get displayed, no intro text. But that's for a separate report once we get into pst thoroughly.

**Comment by lynxlynxlynx** [comment]
@chilvence do you still get noticeable slowdowns now?

**Comment by chilvence** [comment]
No, I think this can be closed now - I think that the slowdown was caused more by the process of printing the console error messages, if I add too many debug prints myself I get a similar speed drain. But both fixes will probably be a great help.
