### ISSUE TITLE
Segfault at start with OGL

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#810]
#### Bug description
When starting gemrb with SDL2/OGL (OK with SDL2 only), game segfault, master or subviews branch

[KEYImporter]: Resources Loaded...
[Core]: Initializing GUI Script Engine...
[SDL 2 GL Driver]: Creating display
[SDL 2 GL Driver]: Creating Main Surface: w=800 h=600 fmt=SDL_PIXELFORMAT_RGBA8888
Segmentation fault

log (subviews)
[strace.txt](https://github.com/gemrb/gemrb/files/4776531/strace.txt)
[gdb.txt](https://github.com/gemrb/gemrb/files/4776539/gdb.txt)

It has perhaps never worked with opengl
[glxinfo.txt](https://github.com/gemrb/gemrb/files/4776549/glxinfo.txt)

GemRB version: git (master & subviews) 

#### Expected behavior
exit gracefully if hardware not supported (atom N570 / OGL 1.4 / Mesa 19.3.5 / i915 driver)

**Comment by MarcelHB** [comment]
OpenGL 1.4 definitely won't work with the OpenGL code in subviews. But yeah, cases like this will need a proper error message.

**Comment by bradallred** [comment]
you are going to get whatever error message SDL feels like giving us. master still needs to be merged to get that message.

**Comment by bradallred** [comment]
I'm closing this. We aren't interested in fixing SDL20GLVideo on master, and from your gdb trace on subviews it segfaults inside libSDL so its either a bug for them to fix or they have and you just need an update.

feel free to reopen if you update your SDL and it now segfaults in our code.
