### ISSUE TITLE
[subviews] custom script listing is unfinished

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#813]
Basically the list resource needs to be upgraded, so we don't skip the description and the right textarea is supposed to show the saved selection (script) instead:
![image](https://user-images.githubusercontent.com/121515/84598272-e1b8b880-ae69-11ea-9945-f4c2c1fe730a.png)
vs
![image](https://user-images.githubusercontent.com/121515/84598411-cef2b380-ae6a-11ea-8431-d483764d93b2.png)

**Comment by lynxlynxlynx** [comment]
Ok, this is 98% fixed. Two remaining issues:
- spacing between the entries is not consistent. I didn't see any newlines in the strings and we trim them to be sure. Yet still some are spaced and some aren't. It's like the TA was adding its own spacing.
- the last entry and part of the penultimate are not visible, you just can't scroll far enough

**Comment by bradallred** [comment]
the scrolling bit was already a known issue that I have now fixed.

I'm much more alarmed at the inconsistent spacing and have no idea why that would be.

**Comment by lynxlynxlynx** [comment]
It's not new, master suffers it as well. So we can close this and deal with it later.
