### ISSUE TITLE
[subviews] infopoint activation is using the bounding box instead of the polygon

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#814]
Obvious in pst ar0704, since it prevents you from talking to the barman:
![image](https://user-images.githubusercontent.com/121515/84602870-919e1e00-ae8a-11ea-844c-99ac9ee8c604.png)

**Comment by chilvence** [comment]
I'm glad you found out what this is, it was going to be my next thing to report but I had no idea what was causing it

**Comment by bradallred** [comment]
do you have more details? it sounds like you already know the code in question since you seem to already know the cause.

**Comment by lynxlynxlynx** [comment]
This was just my speculation, since it seems obvious from both the fish and the shopkeep. The latter shows the correct cursor, so there might be two problems. Will investigate.

**Comment by lynxlynxlynx** [comment]
Caused by 7ae97a6c / #644, since it introduced a fallback on testing the bbox. Before it was checked only as an optimization (as usual in GIS). Should only be done when the outline is not there, so a simple fix.
