### ISSUE TITLE
[subviews] Python error on fiddling with bags

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#816]
#### Bug description
In IWD2, you have plenty of bags to use. But after the first error (see below), the game turns into a bad state, eventually leading to an assertion error. So let's fix this first an then look again.

#### Steps to reproduce
1. Open a bag once
2. Open a bag again

#### Screenshots
Store window fails to be set up.

```python
[GUIScript/ERROR]: Runtime Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File ".\gemrb_subviews\gemrb\GUIScripts/GUISTORE.py", line 179, in OpenStoreWindow
[Python/ERROR]:     Window.AddAlias("WIN_STORE")
[Python/ERROR]:   File ".\gemrb_subviews\gemrb\GUIScripts/MetaClasses.py", line 44, in handler
[Python/ERROR]:     raise type(e)(str(e) + "\nMethod Docs:\n" + str(f.__doc__))
[Python/ERROR]: RuntimeError: ref cannot be null.
```

**Comment by bradallred** [comment]
it appears your GUISTORE has modifications. that is not line 179 for me.

**Comment by bradallred** [comment]
eh, this isn't an actual problem and there is nothing to fix. it fails because the window is already open and "WIN_STORE" is already taken. I don't know how you think you are closing the window, but I couldn't figure out how to close it without it being front and hitting `esc`. If you poke in the `WindowManager` you can see it is still open otherwise; I'm pretty sure something is just hiding it or sending it to the back.

That said its obvious none of this bag business works in IWD2 yet

**Comment by MarcelHB** [comment]
Ok, I better open a issue "make IWD2 bags work"? I mean yes, subviews lacks the close button to the right.

**Comment by lynxlynxlynx** [comment]
Also the left window to switch subwindows is misaligned.

**Comment by bradallred** [comment]
> subviews lacks the close button to the right.

> Also the left window to switch subwindows is misaligned.

actually these are the same issue. I imagine everything else will be solved though #780

**Comment by lynxlynxlynx** [comment]
I'm not so sure, these two things are visible on first entry already.

**Comment by bradallred** [comment]
> I'm not so sure, these two things are visible on first entry already.

I promise its surprisingly the same (now fixed) issue. The "left" window is actually an overlay over the main window and it has the "done" button on it.

**Comment by MarcelHB** [comment]
Let's see it closed since you can now exit the bag window properly.
