### ISSUE TITLE
[subviews] invisible controls affect the cursor

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#818]
Another version of #281: if you move over the hidden disabled iwd2 store buttons, the cursor is grey, but of course in the gaps it's full colored, so it looks odd.
![image](https://user-images.githubusercontent.com/121515/84659618-fb183e00-af17-11ea-8821-0009b269a5c6.png)
![image](https://user-images.githubusercontent.com/121515/84659654-08352d00-af18-11ea-9897-0dd634621869.png)

**Comment by bradallred** [comment]
is it actually invisible (`ViewFlags::Invisible`)? if not I don't see how this is a new issue.

**Comment by lynxlynxlynx** [comment]
If I see correctly, it just doesn't have a disabled frame and we set it up here:
`Button.SetSprites (storebams[Store['StoreType']],0,0,0,0,0)`

So yeah, looks identical.

**Comment by bradallred** [comment]
tho if it is another completely unused button it would be nice to delete it from the window too
