### ISSUE TITLE
[subviews] ctrl-8 crashes the game

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#820]
toggling searchmap debugging explodes:
```
[GameControl]: Show searchmap ON
gemrb: gemrb/plugins/SDLVideo/Pixels.h:217: GemRB::PixelIterator<PIXEL>::PixelIterator(PIXEL*, GemRB::IPixelIterator::Direction, GemRB::IPixelIterator::Direction, int, int) [with PIXEL = unsigned int]: Assertion `w > 0' failed.
Aborted (core dumped)
```
clip.w is indeed 0.

**Comment by bradallred** [comment]
that should fix it, but let me know if you hit something else. mostly im not sure if something else has to be done. I did at least verify I can load a game and hit ctrl+8 without hitting that assert now.

**Comment by lynxlynxlynx** [comment]
yep, thanks.
