### ISSUE TITLE
PST: Critical Hit/Miss lines are mixed up with rare select lines

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#824]
Another character sound bug I neglected to log

When the characters make a critical miss, the 'rare select 4' line is played instead of the critical miss voice line. When they score a critical hit, the 'rare select 3' line is played.

I was attempting to fix this, but I haven't been able to work out where these sounds are actually defined in the original game, they don't appear to be referenced in the CRE files like the selection/bored/insult etc sounds are.

**Comment by lynxlynxlynx** [comment]
We just shouldn't be playing those VBs in pst and criticals have their own entries in strings.2da. But this is also related to #453, since these could fit nicely into VBs (pst has so many unused slots).

**Comment by chilvence** [comment]
Do you mean we could repurpose the unused voice slots in the CRE files?

**Comment by lynxlynxlynx** [comment]
Perhaps yes; there's mayve enough room to dynamically populate them from a table on startup.

**Comment by chilvence** [comment]
I'd be happy to compile the 2da table, I'm guessing something like columns with character names and rows with voice strrefs would do the job, right?

**Comment by lynxlynxlynx** [comment]
A rough count makes it look like there might be enough space, enough unused slots of the 100 in CRE. But this is a discussion for the other bug (or a new one). First step would be to use the lists from there and compile full ones for all the NPCs, then check their CREs if they have enough space and where — hopefully all share enough holes. Only then can we start thinking of a table.

**Comment by chilvence** [comment]
Oops, I didn't realise I already mentioned this over there anyway, must have forgot to take it off my own list.

**Comment by lynxlynxlynx** [comment]
For this bug of using nonexisting VBs, you could indeed remap both slots to one unused one. Then the other bug can work on the full fix.
