### ISSUE TITLE
Recheck if doxygen is working and valuable

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#828]
Ages ago doxygen support was added (just run it with no args in the source dir) and several comments were written with its syntax, specifying params and all. That was even before my time and it hasn't got touched in ages. Is it still useful, do we even have enough coverage? Test it out, play with it and cast a judgement.

Then we'll see if it's worthy of keeping and integrating into our work, ditching or something else.

**Comment by burner1024** [comment]
I tried it, works fine. How useful, not sure. Code editors now are smart, provide intellisense from docstrings.
It does have graphs, though:
![Captura desde 2023-05-28 15-49-57](https://github.com/gemrb/gemrb/assets/1279852/2921df0e-4666-4efe-9d0e-dd8eeecfb12f)

**Comment by lynxlynxlynx** [comment]
Thanks. It doesn't hurt, it's just comments and one extra file
