### ISSUE TITLE
PST travel regression: unable to move around the hive 

### ISSUE THREAD

**Issue by chilvence** [gemrb/gemrb#830]
It took me starting a new game to notice this, but after escaping the mortuary and clearing the first mini dungeon, I was stuck in the northeast quarter.

Worldmap travel works after you reach AR0500, but before that happens those worldmap trigger points have to default to moving to the nearest area. 

This exit should take you to the north entrance of the Smouldering Corpse bar area for example:

 [000000270-GRB Close to the edge.zip](https://github.com/gemrb/gemrb/files/4799557/000000270-GRB.Close.to.the.edge.zip)

I think I have traced it back to https://github.com/gemrb/gemrb/commit/e4e6ce19a37ee544230cf7ac36a88f4ef8d73ce2
The previous https://github.com/gemrb/gemrb/commit/e1c9774b6f76c98f042b0cfa16d293209b0bef37 allows you to exit.

Commenting out [this single line](https://github.com/gemrb/gemrb/blob/f2c6946425574ac8931e275237ea144754f4a76c/gemrb/core/GUI/GameControl.cpp#L2139) is enough to restore the original behaviour, but it also breaks the ability to worldmap travel later on:

[000000271-GRB Don't push me cause I'm.zip](https://github.com/gemrb/gemrb/files/4799798/000000271-GRB.Don.t.push.me.cause.I.m.zip)

I think the issue is trickier than it seemed at first glance, because until you get access to the worldmap in AR0500, all exits should behave like regular travel triggers.

I will continue trying to solve this, just adding a tracker issue for the details

edit: I haven't had a chance to thoroughly test this yet, but I think it might be the simple solution:

https://github.com/chilvence/gemrb/commit/d6148c5363d5a2ec08a0bf967e448cc530c31db4

The issue is, there wasn't anything technically wrong with the original behaviour before the pst world mapping was added, it's just that it needed to change globally when you hit the lower ward (everything was navigable before, it just took longer). So both ways are correct, just at different stages of the game.

I'm not sure yet what happens in Carceri/Baator, which I think are the only other areas with any kind of 'worldmap' ish navigation, although they only have one icon on the map so I suspect they were written as one 'area'

**Comment by chilvence** [comment]
I'm not totally sure about that - for what its worth, the current worldmap checking works fine, except that it doesn't have a fall back behaviour for the large part of the game before you get to use it.

(the world map area entrances are sometimes strange, but that's another issue)

**Comment by lynxlynxlynx** [comment]
btw, if you cancel, it triggers (actually not-cancels) the original behaviour.

**Comment by chilvence** [comment]
I'm not sure what you mean, do you mean if you hit "stop all actions"? Or if you close the map window? 

I can't seem to reproduce that. I might be testing it wrong?

**Comment by lynxlynxlynx** [comment]
if you close the window / not pick a destination.

**Comment by chilvence** [comment]
That's strange. I can't seem to get that to happen, with or without the patch. The "done" button just closes the map and stays in the same area.

**Comment by lynxlynxlynx** [comment]
Looks like I removed it with the last fix, nevermind.

**Comment by chilvence** [comment]
If you know the right way to fix this by the way, don't worry about the PR I made, I am just clearing my working tree because it's got out of hand...

**Comment by lynxlynxlynx** [comment]
interesting, it still works fine with my test saves before the transition, in many areas, but going from ar0400 to NE Hive indeed does not any more.
