### ISSUE TITLE
[subviews] console misplaced?

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#832]
![image](https://user-images.githubusercontent.com/121515/85231136-0aeec100-b3f5-11ea-8d9c-cf4af05ce824.png)

It looks centered — do we intentionally not make it as wide as the window? It's also not clear while button mashing if there is a column (character) limit.

**Comment by bradallred** [comment]
is this really different on the 2 backends? there is not a character cap.

Is it useful to have a larger console? I'd rather have a taller one than a wider one, but I don't know why it would be useful.

**Comment by lynxlynxlynx** [comment]
The problem with the text length is that if you hit the window width, all further input will be invisible, since the whole thing doesn't stop, scroll or soft wrap.
