### ISSUE TITLE
[subviews] Can't properly navigate PCs around right now

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#833]
#### Bug description
There is something wrong r/n: I can't make any PCs move around by clicking. It opens a selection rectangle -- and you don't get rid of it anymore. If you click the right mouse button, it's gone but then you click the num key for some PC and try to move it around, and again: stuck in rectangle mode.

**Comment by lynxlynxlynx** [comment]
With the latest merge from master from today?

**Comment by MarcelHB** [comment]
That's what I've tested. Not sure what it was like right before.

**Comment by lynxlynxlynx** [comment]
Ok, I'll check it out. There weren't any very problematic parts in there, so it appears the automatic merge was bad. Should have tested more. :/
