### ISSUE TITLE
 Wrong screen positioning/resolution on Raspberry Pi 4/Buster

### ISSUE THREAD

**Issue by stuffu** [gemrb/gemrb#836]
I love the idea of playing my old RPG favourites on my RPI 4, so I installed it through RetroPie and it launches the games as expected. But the screen is not behaving as it should. 

First of all, it doesn't scale properly, meaning that the screen is smaller than it should be. I'm running the display in 1080p, also the screen is always in the upper left part of the display, not centered. I have also tried changing the resolution in the gemrb.cfg but that doesn't help anything, as well as enabling fullscreen but it doesn't change anything. Maybe something is overriding the gemrb config?

I have tried the Icewind Dale games as well as Planescape (all from GOG and using the original version).

The log file complains about wrong paths to portraits and data folder. I haven't been able to fix that but the games starts as expected so I am thinking of fixing the resolution issues first.

GemRB version: 0.86

Thanks for a great initiative!

**Comment by lynxlynxlynx** [comment]
Ok, let's take it slow, one thing at a time. Do you have problems already with the default resolutions or not?

**Comment by FrElvire** [comment]
I'm wondering if it's not tied to SDL1 backend ?, if you can recompile it with cmake param : -DSDL_BACKEND=SDL2

**Comment by stuffu** [comment]
The resolution for everything else is correct, it's just gemrb that doesn't scale as intended, attaching screenshot.

![IMG_0377](https://user-images.githubusercontent.com/4310040/85273697-38cc1800-b47e-11ea-9664-954406d0ce50.jpeg)

**Comment by stuffu** [comment]
> Ok, let's take it slow, one thing at a time. Do you have problems already with the default resolutions or not?

Sorry, maybe misunderstood. The issues are there even when using the default resolutions.

**Comment by chilvence** [comment]
I have a pi4 with retropie, so I can try and help, but I can't seem to find any gemrb package in the retropie config

Can you give me a hint how you installed it? I built gemrb from source myself, so I am not sure where to look

**Comment by stuffu** [comment]
Ah how nice! You find it in the experimental packages, it will build the 0.8.4 as default.

**Comment by chilvence** [comment]
Ouch, that is extremely old, you might be better off cloning from the git repository

**Comment by stuffu** [comment]
Yup, I have updated the script to use the 0.8.6 instead but the result is the same.

**Comment by stuffu** [comment]
Located at `/home/pi/RetroPie-Setup/scriptmodule/ports/gemrb.sh`

**Comment by chilvence** [comment]
It looks like it doesn't do too much more than follow the basic build steps and set up the config files/emulation station links

I can't actually remember when the screen scaling was added, but before that was the case, the only choice was to install the widescreen mod to get higher resolutions than the original 640x480 or 800x600

Newer versions of GemRB are working toward making that restriction history, but when I looked in the config files provided it looks like they haven't tried to solve the problem, they are just pegged at 640x480 (I guess that's why they left gemrb in 'experimental')

**Comment by stuffu** [comment]
Thanks for checking it out, I could live with having lower resolution until additional resolutions are implemented in GemRB. Does this also explain why the screen is not centered? That's the most annoying part at the moment...

**Comment by chilvence** [comment]
That's hard to say, from what I remember, EmulationStation doesn't really start the window manager, if you run from the desktop you might find that the 'maximise' button does the trick, it does for me, on Windows and Linux. 

But I also have the latest version built from the master branch, so I couldn't say for sure how long that has been possible.

**Comment by chilvence** [comment]
Actually, it looks like you could just delete the 'v0.8.4' part in the function sources_gemrb and let retropie do the rest.

I still can't wrap my head around how retropie is organised, but I think that will do it, you might have to remove the existing source repo from wherever it puts it first though. I have to admit I can't find it. They really really love directory trees over there.

**Comment by stuffu** [comment]
When removing 0.8.4, it seems it actually builds using the latest commits. I restarted emulationstation after making the change in function sources_gemrb for it to update where to get the repo. But the games won't start now, I think I saw some errors when building but I'm quite novice on linux so I don't know how to pull a log from it...

**Comment by chilvence** [comment]
From what I can tell, the setup script pulls the source into a temporary folder RetroPie-Setup/tmp, installs the game files under /opt/ , then closes the terminal used to build and cleans up the tmp directory, so unfortunately it is not geared in a way that helps us. I'm not able to hazard a guess at what parameters retropie is using to run the script, you would have to ask over there for help getting a build log (or you could just try to take a camera recording of the error)

The only other thing I can suggest at this point is add -DDISABLE_WERROR=ON to the options given to cmake in the gemrb.sh retropie script, in the function build_gemrb() 

It is definitely possible to build and run both development branches of gemrb on the pi4 though, it's just a case of finding what step we are missing.

**Comment by MarcelHB** [comment]
Yes, but have you tried that recently?

**Comment by stuffu** [comment]
I posted on the RetroPie forums to see if someone can help out from there:

https://retropie.org.uk/forum/topic/26864/gemrb-support

**Comment by chilvence** [comment]
Hopefully we will prod them to update, even if only to 0.8.6 , or at least we'll find out the lowdown 👍

**Comment by stuffu** [comment]
Editing `/home/pi/RetroPie-Setup/scriptmodule/ports/gemrb.sh` and changing the 0.8.4 to 0.8.6 actually builds from 0.8.6, but it doesn't change anything when it comes to the resolution and screen position issues.

`function sources_gemrb() {
    gitPullOrClone "$md_build" https://github.com/gemrb/gemrb.git 0.8.6`

**Comment by stuffu** [comment]
It seems to be related to SDL1 as @FrElvire said.

"mitu GLOBAL MODERATOR

Ideally, on a PI4 GemRB should be using SDL2. SDL1 is ancient and using it on Pi4 exhibits the scaling artifacts you've noticed. Maybe adding a GemRB-SDL2 version of the module would be better and/or enhancing the current version to use dispmanx for scaling."

**Comment by chilvence** [comment]
I just tried 0.8.6 again, and it doesn't seem you can resize the window in that version, I thought it might have been a relatively recent addition.

One of the main things to know is, even before GemRB or Enhanced Editions, the general practice for playing with high resolutions was to install the ['Widescreen' mod from Gibberlings 3, ](https://www.gibberlings3.net/mods/tools/widescreen/) , that takes care of the repositioning of the UI elements on a data level, which then any GemRB version can accept. 

I don't know how easy it is to install on your pi though, but even if you have to resort to installing on a desktop and modding that version for 1920x1080, you should be able to transfer that game data across (or rather, just the modded files)

**Comment by chilvence** [comment]
On searching retropie for other gemrb topics, I realise you already tried that route... I'm afraid that's the only tried and tested way at the moment.

Ironically, I did use to have my own patch to Gemrb to fix the UI in higher resolutions, but I scrapped it once I found out it was in the development pipeline! Sorry. (it was based on 0.8.3 anyway, so you definitely wouldn't have wanted to try that...)

**Comment by lynxlynxlynx** [comment]
You can manually resize the window if the backend is sdl2 — this has been in for ages (possibly in .4 already). It will just do some linear scaling, nothing advanced, so best results are at integer multiples.

**Comment by chilvence** [comment]
That's exactly what worked for me, I can resize the window with 0.8.6 now. I just didn't know how or when that ability was included because I'm too used to the old ways :)

I will try to mod their script a bit to build with SDL2 and see if I can get Retropie to start with a maximised window. Since 0.8.6 already builds fine, it looks like they might add it as the default option.

**Comment by chilvence** [comment]
Result :) They have updated to v0.8.6 by default and reportedly fixed the screen scaling

https://github.com/RetroPie/RetroPie-Setup/commit/cdc4aea1cbcf41d98455e995b317d7aa99af3274

Should I tell them that the vlc plugin is not strictly necessary? I hate to admit it, but I can't remember exactly which scenario it's used for - is it only for modding purposes or do some games need it?

**Comment by lynxlynxlynx** [comment]
it's for videos of a certain mac distribution, I don't remember of which game. Not so easy to come by, so yeah, pi doesn't really need it.

Ok, closing the bug. Please open a new one if anything else crops up.

**Comment by bradallred** [comment]
The original Mac versions of at least BG1 and probably others used QuickTime videos. We also need the VLC plugin if we are to support the EE versions which use something else too. The plugin already theoretically works (on subviews branch) for those videos, but I haven't tried.

**Comment by chilvence** [comment]
Ok, I left them a comment to that effect, they can decide (I only thought of it because size is an issue normally on the pi)

**Comment by 2play** [comment]
> ![IMG_0377](https://user-images.githubusercontent.com/4310040/85273697-38cc1800-b47e-11ea-9664-954406d0ce50.jpeg)

Hi @stuffu 
I suggest got to the emulators.cfg of your ports setup and add after the "
XINIT:
the emulator.cfg line that calls the script/emu should look "XINIT: rest of commands"
let me know
