### ISSUE TITLE
Some option buttons in BG2 seem to be lacking a highlight

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#837]
Interestingly some of the buttons in BG2 seem to be lacking a highlight. Am I wrong?

<img width="68" alt="image" src="https://user-images.githubusercontent.com/1126744/85241284-8c941e00-b3f8-11ea-98ef-7e172d943fbf.png">

I've hacked the button to always draw the "selected" frame and indeed they do seem to be missing. Surely these exist somewhere since they don't seem to be missing from the CHU for the secondary options window that we now ignore. Is there a way to manually fix it with `Button.SetSprites`?

_Originally posted by @bradallred in https://github.com/gemrb/gemrb/issues/795#issuecomment-647222814_

> They're there in guiw, but missing in guiw8 and guiw10. Should be easy to fix indeed, since they all use the same bams, it's just that the bigger windows don't have the frame indices set for anything else but pressed and normal (default 0). Should set 2 for selected.
> 
> But odd, bg2 has GF_IGNORE_BUTTON_FRAMES set, so we're trying to fix these already in the importer. Better to dig in there.

**Comment by lynxlynxlynx** [comment]
This is now fixed, but I noticed the mage window in both bgs doesn't highlight on entry, even though it had the correct data before.

**Comment by bradallred** [comment]
I'll bet it has to do with the mage window hack to support sorcerers.
