### ISSUE TITLE
Undefined behavior in GameScript::Matching.cpp

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#838]
After the latest merge from master my UBsan reports errors when loading a game in BG2

```
if (!tgts) {
	tgts = new Targets();
}
tgts = DoObjectFiltering(Sender, tgts, oC, ga_flags); // apparently this can and does return null
tgts->FilterObjectRect(oC); // we are now calling a function with a null `this`
return tgts;
```

the only reason this isn't crashing is because the first check in `Targets::FilterObjectRect` is failing and returning early.

Im opening a bug report instead of simply adding a null check because im really not sure that is the most correct thing. It seems silly that we would create a new `Targets` and then promptly `delete` it in `FilterObjectRect`. Shouldn't `FilterObjectRect` simply return an empty target list?

```
tgts = func(Sender, tgts, ga_flags);
if (!tgts->Count()) {
	delete tgts; // maybe these 2 lines should be a `break` instead?
	return NULL;
}
```

 somebody with more knowledge about `GameScript` should decide what makes sense.

**Comment by lynxlynxlynx** [comment]
We only create new Targets occasionally and delete all of them when filtering even less often (rarely used feature & case). I don't see any benefit in creating another copy just for this.

**Comment by bradallred** [comment]
its not about a benefit or not. I don't know that later code treats `NULL` the same as an empty list so I thought it was worth investigating to make sure things are actually correct.
