### ISSUE TITLE
[subviews] No item lists for bags 

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#839]
#### Bug description
Looks like #816 has offspring, or some kind of regression. When I right-click a bag in IWD2, it immediately attempts to open the bag window, but there is only the left and right side bar shown (as seen in the GIF, the close button to the right), no lists for items.

I do not find any Pyhton errors there.

#### Screenshots
![store](https://user-images.githubusercontent.com/238558/85630843-af326b00-b674-11ea-80c7-37326d8e6341.gif)

The increase from 99 to 100 HP is some regeneration effect, I hope. :)

**Comment by bradallred** [comment]
sounds like another merge regression

**Comment by bradallred** [comment]
I stand corrected
