### ISSUE TITLE
[subviews] Ghost cursors/tooltips in some views.

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#840]
#### Bug description
Try the following:

1. Put the cursor over something, let's say a neutral NPC.
2. Press 'I' for inventory or something different at a higher resolution, i. e. there is enough space between your current view and the sidebars/action bar.
3. Now, move the cursor above the background.

Two things happen:
1. It takes the last cursor before entering the inventory. For the NPC example, it's the dialog cursor.
2. When you leave the cursor there, it displays the tooltip. 

Here, an example for one of my PCs in IWD2;
![ghost_tooltips](https://user-images.githubusercontent.com/238558/85777220-b82d4600-b721-11ea-94e3-e3fb376c63e0.jpg)

**Comment by bradallred** [comment]
the `hoverWin` conditionals at the end of `WindowManager::OrderRelativeTo` might be backwards

**Comment by bradallred** [comment]
I never could reproduce the tooltip part, but that should fix it anyway.

**Comment by MarcelHB** [comment]
I tried that, but unfortunately no change:

![store](https://user-images.githubusercontent.com/238558/85931644-2d398080-b8c6-11ea-96a4-3bf31103281d.gif)

**Comment by bradallred** [comment]
how is that a problem? you are actually hovering over that object.

put an actor under where the window will open and it will update the cursor.

**Comment by MarcelHB** [comment]
Considering where Riki is, and taking my PC actor:

![store](https://user-images.githubusercontent.com/238558/85931772-18112180-b8c7-11ea-8a8d-f0b808c67514.gif)

But I notice a pattern: The update happens only when I really move the cursor down to the action bar, then it turns into the forbidden-cursor. Otherwise, it's like that.

**Comment by bradallred** [comment]
I've opened #848 to handle the actual underlying problem. its non trivial and its definitely not new to this branch.
