### ISSUE TITLE
[subviews] Rendering error of water (seen at start of asylum)

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#844]
#### Bug description
I suspect this is already known but if it's not the case....

A the start of asylum on the bridge, rendering of water is incorrect.

#### Screenshots
![water_rendering](https://user-images.githubusercontent.com/55502325/85918807-28dd7b00-b866-11ea-9773-9da15ad701cc.png)

**Comment by bradallred** [comment]
AR # and coordinates in the description please

**Comment by FrElvire** [comment]
Position: ar1500 [473.2788]

**Comment by FrElvire** [comment]
some additional information : 

Subviews SDL2, SDL2+OGL = bad rendering
Master SDL2 : rendering OK

Tested on linux (intel IGP) with 2 different 3D driver (i965 and iris) -> same result

**Comment by bradallred** [comment]
I don't know if its good news or bad news, but this has nothing at all to do with SDL 2.

**Comment by bradallred** [comment]
I assume this is what it is meant to appear like:
<img width="587" alt="image" src="https://user-images.githubusercontent.com/1126744/86394455-db914d00-bc5b-11ea-80fa-defd6576389f.png">
