### ISSUE TITLE
[subviews] During dialogue Esc key remove vertical bars

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#845]
#### Bug description
During dialogue, pressing Esc key multiple time remove vertical bars.

#### Steps to reproduce
start dialogue with someone
press Esc key, one vertical bar is removed
press Esc key, the other vertical bar is removed

#### Expected behavior
Nothing happen when pressing Esc key during dialogue ?

**Comment by lynxlynxlynx** [comment]
I guess we should just mark it as modal during dialog — if it isn't already.

**Comment by bradallred** [comment]
he is talking about the option and portrait windows. those obviously can't be modal. this is why they have (had?) the `I
ngoreEvents` flags set.

**Comment by lynxlynxlynx** [comment]
I meant the message/dialog window, since nothing else should be able to get focus.

**Comment by bradallred** [comment]
ah, of course. However, that cannot be modal either because the continue/end button is a separate window
