### ISSUE TITLE
[subviews] Scrolling does not follow the characters dialog in the dialog

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#846]
#### Bug description
Scrolling does not follow the characters dialog in the dialog

#### Steps to reproduce
Start dialog with a character
Dialogue is added after the other messages
in dialog box only top messages/dialog is displayed

#### Expected behavior
Dialog box is scrolled to show current dialog

#### Screenshots
![pocketplanedialog](https://user-images.githubusercontent.com/55502325/85920013-7eb72080-b870-11ea-9ae2-48c73b33d6c3.png)

**Comment by bradallred** [comment]
@lynxlynxlynx this appears to be another merge issue if you want to help me take a look

**Comment by bradallred** [comment]
ohh, I spoke too soon. must have been some `TextArea` changes for #842

**Comment by bradallred** [comment]
#$%@, broken by 4e0d6d9 using some dark spell I do not know
