### ISSUE TITLE
[TOB] Solar doesn't look like at all as in original

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#847]
#### Bug description
Solar doesn't look like at all as in original

GemRB version: master (sdl2)/subviews (sdl2/ogl)

#### Expected behavior
look like in original game (even if I find it ugly ;) )

#### Screenshots
Taken from subviews but identically in master.
![pocketplanedialog](https://user-images.githubusercontent.com/55502325/85920138-81fedc00-b871-11ea-9583-5d422440b00a.png)

Picture from original is coming

**Comment by MarcelHB** [comment]
I close this because we have #134 already.
