### ISSUE TITLE
full morale support 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#852]
More great research from Bubb:
> 1) Opcode 130 (Bless): morale += Param1 (we erroneously update IE_MORALEBREAK instead)
> 
> 2) Trigger 0x20 (HitBy) set:
> - "Drop by 2 when first falling below 50% HP, drop by another 2 when first falling below 25% HP. Don't decrease again unless I was healed above the respective tier and hit once before."
> 
```
if (m_hitPoints * 100 / max(1, m_nMaxHitPoints) < 50)
{
    if (m_lastCheckedHitPoints * 100 / max(1, m_nMaxHitPoints) >= 50)
        m_morale = max(0, m_morale - 2)

    if (m_hitPoints * 100 / max(1, m_nMaxHitPoints) < 25)
    {
        if (m_lastCheckedHitPoints * 100 / max(1, m_nMaxHitPoints) >= 25)
            m_morale = max(0, m_morale - 2)
    }

    m_lastCheckedHitPoints = m_hitPoints
}
```
> 
> 3) Trigger 0x25 (Died) set:
> - "Something died, (not necessarily having to do with me)"
> 
```
if (CAIObjectType::OfType() == true)
    // Exact object type match
    morale -= 1
else if (my.EA == PC && died.EA == PC)
    morale -= 1
else if (CAIObjectType::IsEnemyOf() == true)
    morale += 2
```
> 
> 4) Trigger 0x4B (Killed) set: morale += 3
> - "I killed anything"
> 
> 5) INTOXMOD.2DA->MORALE #546 
> 
> 6) Action RunAwayFrom(), when calling CGameSprite::JumpThroughTransition() or CGameSprite::JumpToArea(): morale = 20
> 
> Note that if not explicitly stated, morale is bounded between [0-20]. There are other misc. writes, mostly just resetting morale when the creature is invalid, such as when dying and so on.
>
> PST:EE still modifies the plain morale in basestats, but disables the normalization over time / automatic triggers (like killing something, party member dying, etc.) from modifying the value for EA == PC creatures. Essentially this turns it into a persistent field for PC characters.

`CAIObjectType::OfType()` matches like object matching in gamescript. Eg. the whole `[EA.FACTION.TEAM.GENERAL.RACE.CLASS.SPECIFIC.GENDER.ALIGN]` has to be the same for both creatures.

**Comment by chilvence** [comment]
> > 1. Opcode 130 (Bless): morale += Param1 (we erroneously update IE_MORALEBREAK instead)

This is interesting, it seems to be the case in the MoraleInc/MoraleDec actions as well, which are pretty extensively used by DRAVEL.DLG, and could explain why the party members seem to panic when they should be getting a morale boost

**Comment by lynxlynxlynx** [comment]
We have an interesting pcf, the same for both stats, but yeah, those three actions should also just be updating the main morale stat. Needs a closer look, but feel free to PR it.

**Comment by chilvence** [comment]
I didn't get why the IE_MORALE stat was marked as a GemRB internal, did this never get saved in the original? I've never actually had it happen that a party member ran away in any IE game (other than horror or the like), because I would spam the reload button when someone died

**Comment by lynxlynxlynx** [comment]
Actually, come to think of it, since pst uses MoraleInc/MoraleDec for long term stuff, it can't use the main morale stat. That would quickly decay back to normal and progress would be lost. Still, it surely isn't moralebreak, since evil characters would then just panic very often.

**Comment by lynxlynxlynx** [comment]
Something in the middle:
> PST:EE still modifies the plain morale in basestats, but disables the normalization over time / automatic triggers (like killing something, party member dying, etc.) from modifying the value for EA == PC creatures. Essentially this turns it into a persistent field for PC characters.
> 
> Not sure how close that implementation is to the classic PST, since PST:EE is really just an adapted EE engine.

**Comment by chilvence** [comment]
It isn't easy to say, but if that's the way they did it having the old source available as reference, it can't be a million miles from the truth, can it? It would have been important for them to get right, since you can affect your party morale with so many dialog options.

I'm still really confused why there is only this in stats.ids
```
46 MORALEBREAK
47 MORALERECOVERYTIME
```

And then way down at the end of Gemrb's ie_stats.h:
```
#define IE_MORALE               252 // this has no place
```

Would Bubb be able to tell us which stat is ultimately getting modified by the EE code?

**Comment by lynxlynxlynx** [comment]
It was internal and didn't need to be referenced outside? Don't worry about ids files.

**Comment by chilvence** [comment]
Ach, never mind, I assumed the ids file had some direct relationship to the cre file. I have already set up an experiment with the MoraleInc/MoraleDec actions to try out, it was just confusing me how it was meant to store it when you save the game.

I'm not sure how to deal with the need for it to be persistent in PST only yet, but it would be an improvement if the characters would stop panicking when you get to the major encounters, which is what I'm hoping for.

**Comment by lynxlynxlynx** [comment]
There you go, you made me do it. Haven't tested pst though.
