### ISSUE TITLE
right click on non-pcs and get their selection line

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#855]
In fact, in original BG2 you can simply right click on anyone with blue circle and get their "existence" lines in the dialog window. That doesn't happen in GemRB.
AR0709:
![Captura de pantalla de 2020-02-18 14-45-14](https://user-images.githubusercontent.com/1279852/74714533-4c137080-525d-11ea-9ae4-fa0170b5c30c.png)

_Originally posted by @burner1024 in https://github.com/gemrb/gemrb/issues/634#issuecomment-587324595_

Looking at the data, it's clear the common select sounds are played, not the existence ones. Maybe those in cases where the soundset isn't present, but for this area, definitely not. Basically we need to call Actor::PlaySelectionSound on right-click in GameControl (and enhance the function if needed).

**Comment by burner1024** [comment]
In fact, that's not just neutrals, enemies too.
