### ISSUE TITLE
[subviews] target reticles not drawn over shroud of war

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#856]
Testing the new pathfinder in the first bg2 area it became clear we don't draw the reticles on explored, but shrouded, areas any more. Explore the map, order party some place outside the visual range. Since the markers don't appear, it looks like they abandoned the path, while that's not really the case.

**Comment by bradallred** [comment]
It actually has nothing to do with the fog of war. Its because Actors offscreen aren't drawn anymore and for some reason that's where the reticle drawing was done.
