### ISSUE TITLE
intermittent item transparency issues

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#859]
I do get some intermittent transparency issues on sdl1 with helmets, but don't know if that's related.

_Originally posted by @lynxlynxlynx in https://github.com/gemrb/gemrb/issues/787#issuecomment-644242172_
![Peek 2020-07-08 21-11](https://user-images.githubusercontent.com/121515/86960386-bc188980-c15f-11ea-87e4-42100230a7a7.gif)

Here it's permanent on the shield (shld25, probably from item upgrades). 
The helmet is a regular helm08. It has some color effects attached that target the helmet itself. The flickering doesn't seem to have a pattern to it, like if a certain frame had a corrupted transparency index. The ingame bam is wqlj8g1, maybe some more in the wqlj8 family and all frames display ok in NI. Same for the shield.

So it doesn't look like a data problem.

**Comment by bradallred** [comment]
I can't seem to reproduce this. possibly it depends on unknown factors. If you still see it might be best to attach a save where it is visible.

**Comment by lynxlynxlynx** [comment]
It's hard to test well now that the interface is broken, but it almost looks fixed. Still happens, but harder to trigger — will recheck once #882 is out of the way.

**Comment by lynxlynxlynx** [comment]
Still happens and appears like it was data related, since it's easier to reproduce in some orientations. The simplest I could come up with was when testing with Aerie (probably doesn't matter) wearing nothing but slng06 and walking around. Eventually you can get some green around the sling (no big rects as with helmets in OP).

**Comment by bradallred** [comment]
it almost sounds like we are tinting (due to shadows or something) and mucking up the color key... only I thought with BAM sprites we always treated index 0 as the ck...

**Comment by bradallred** [comment]
maybe that is the problem tho. maybe this BAM shouldn't be using index 0 as the ck for those frames? seems odd tho.

**Comment by bradallred** [comment]
the other possibility that comes to mind is somehow that frame is not being blotted with `BLIT_BLENDED` or that flag is getting dropped somewhere in the pipeline.

**Comment by lynxlynxlynx** [comment]
The last thing sounds more likely, since it's only an intermittent problem not visible in master.

**Comment by bradallred** [comment]
huge portions of `Sprite` and practically the entire rendering pipeline were rewritten so I'm not sure looking to master is useful for identifying what is at fault. I looked at the code and it doesnt appear that BAMSprites care at all about `BLIT_BLENDED` and just always blend.

**Comment by lynxlynxlynx** [comment]
I'm just saying it's not a data issue per se.

By non-compressed you mean normal bams (not bamc)? That as well, there's a per-frame bit (RLECompressed):
https://gibberlings3.github.io/iesdp/file_formats/ie_formats/bam_v1.htm

**Comment by bradallred** [comment]
I'm pretty sure that should have fixed it, tho I was never able to see this myself

**Comment by lynxlynxlynx** [comment]
Better, but it is still possible to get bad results — when behind wall cover. The cover just sort of clips the problem.

**Comment by bradallred** [comment]
do we have a good way to reproduce it? maybe a save or area+coords?

**Comment by lynxlynxlynx** [comment]
This is how it looks, in the pocket plane:
![image](https://user-images.githubusercontent.com/121515/95099209-e8787d80-072f-11eb-8d7c-92c80bd0a9df.png)

I can pretty reliably reproduce it on an install with 1pp, just Jaheira with the helm of Balduran (helm07), when walking northward. When I tried someone else with the helm in a different install, his weapon got the problem instead. So I don't know if a save would do.

**Comment by bradallred** [comment]
that sounds exactly why a save _would_ be useful; it seems to depend on multiple factors. I've tried multiple times now to reproduce and cannot.

**Comment by lynxlynxlynx** [comment]
Good luck. 🤷🏾‍♂️ 
[000000004-Quick-Save-TOB.zip](https://github.com/gemrb/gemrb/files/5330137/000000004-Quick-Save-TOB.zip)

**Comment by bradallred** [comment]
is this any better?

**Comment by lynxlynxlynx** [comment]
Yeah, looks fixed, thanks. :)
