### ISSUE TITLE
Formation rotations are nondeterministic

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#861]
Formation rotation uses `Map::AdjustPosition` when it encounters a point that is not reachable. The problem is this uses `RAND` to randomly pick a nearby point. The problem is compounded when you release the mouse because we again recalculate the points `RAND` will give us, more often than not, a different result.

Expectations:
1. if you rotate a given formation a given direction over a given point the result should always be the same
2. the preview of the rotated formation should exactly match the resulting movement commands

**Comment by lynxlynxlynx** [comment]
We were talking about this with kmfrick just the other day. A nice side effect is that it will also fix flickering.
