### ISSUE TITLE
issues with formations with more than 10 actors (ex summons)

### ISSUE THREAD

**Issue by bradallred** [gemrb/gemrb#862]
Our formations support unto 10 actors so you usually won't see this, but it is possible with a lot of summons or party size mods. If we hit this limit all actors beyond the 10th will all try to go to the same position and they of course get into a horrible tangle.

Expectations:
no 2 actors will ever be directed to the same point by a formation

**Comment by lynxlynxlynx** [comment]
We should also regenerate the formation data for let's say 30 actors. BG1 had no summoning cap and plenty of wands of summoning, so it's easy to reach there.

**Comment by bradallred** [comment]
we can for sure do that too, but the changes I've made will at least stop everything from trying to pile onto a single point. Everything beyond 10 will create an alternating line starting from the last position in the formation and extending with the plane of rotation.
