### ISSUE TITLE
 [TOB] Party displayed at bottom right of the screen when leaving the barracks in the entrance of Sendai's enclave

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#864]
#### Bug description
When leaving the barracks in the entrance of Sendai's enclave just before cutscene, the party is displayed at bottom right of the screen (see screenshot)

GemRB version: master (SDL2 + widescreen mod)

#### Steps to reproduce
1. load save
2. leave the barracks
3. See error before cutscene

#### Expected behavior
just black screen ???? from what I can see (https://youtu.be/z5TTDL3USUE?t=820)

#### Screenshots
![Screenshot_20200714_120329](https://user-images.githubusercontent.com/55502325/87414460-22703280-c5cc-11ea-87bd-fb3b3c66a2af.png)

#### Save
[000000024-sendai enclave bug_1.zip](https://github.com/gemrb/gemrb/files/4918118/000000024-sendai.enclave.bug_1.zip)

**Comment by bradallred** [comment]
no idea what would cause this, but its worth trying on the other branch.

**Comment by lynxlynxlynx** [comment]
Usually it's a viewport positioning problem. The location of the party is fine, but some action from the cutscene list recenters on them erroneously.

**Comment by lynxlynxlynx** [comment]
Your save works fine for me. What mods do you have installed?

**Comment by FrElvire** [comment]
Test with and without widescreen mod, same result.

here is what is installed : 

// Log of Currently Installed WeiDU Mods
// The top of the file is the 'oldest' mod
// ~TP2_File~ #language_number #component_number // [Subcomponent Name -> ] Component Name [ : Version]
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #0 // BG2 Fixpack - Core Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #1000 // BG2 Fixpack - Game Text Update -> GTU Light (by Wisp): v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #100 // Party Gets XP for Sending Keldorn to Reconcile With Maria: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #101 // Improved Spell Animations: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #103 // Mixed-Use Dagger Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #104 // Ghreyfain's Holy Symbol Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #106 // Giants Receive Penalties When Attacking Halflings, Dwarves, and Gnomes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #107 // Remove Dual-Classing Restriction from Archers and Stalkers: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #108 // Remove Second Attribute Bonus for Evil Path in Wrath Hell Trial: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #109 // Corrected Summoned Demon Behavior: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #110 // Additional Script Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #111 // Bard Song Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #112 // Wizard Slayers Cause Miscast Magic on Ranged Attacks: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #113 // Additional Alignment Fixes: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #114 // Change Free Action to Protect Against Stun: v13
~BG2FIXPACK/SETUP-BG2FIXPACK.TP2~ #0 #116 // Remove Thieving Start Bonuses from Bard and Ranger Skills: v13
~UB/SETUP-UB.TP2~ #0 #0 // The Kidnapping of Boo by Cliffette: v26
~UB/SETUP-UB.TP2~ #0 #1 // The Suna Seni/Valygar Relationship: v26
~UB/SETUP-UB.TP2~ #0 #2 // Kalah and What He Was Promised: v26
~UB/SETUP-UB.TP2~ #0 #3 // "Cat and Mouse" (Bodhi hunts you in Spellhold) by Ghreyfain: v26
~UB/SETUP-UB.TP2~ #0 #4 // Gorje Hilldark and the Extended Illithium Quest: v26
~UB/SETUP-UB.TP2~ #0 #5 // The Pai'Na/Spider's Bane Quest: v26
~UB/SETUP-UB.TP2~ #0 #6 // Restored Crooked Crane Inn: v26
~UB/SETUP-UB.TP2~ #0 #7 // Restored Encounters: v26
~UB/SETUP-UB.TP2~ #0 #8 // Artemis Entreri in Bodhi's Lair: v26
~UB/SETUP-UB.TP2~ #0 #9 // Corrected "Xzar's Creations": v26
~UB/SETUP-UB.TP2~ #0 #10 // Restored Hell Minions, by SimDing0: v26
~UB/SETUP-UB.TP2~ #0 #12 // Item Restorations: v26
~UB/SETUP-UB.TP2~ #0 #13 // Yoshimo's Original Portrait: v26
~UB/SETUP-UB.TP2~ #0 #14 // Anomen's Original Portrait: v26
~UB/SETUP-UB.TP2~ #0 #15 // NPC Portrait Restorations: v26
~UB/SETUP-UB.TP2~ #0 #16 // Corrected BAMs and Scripts: v26
~UB/SETUP-UB.TP2~ #0 #17 // Corrected Character Names and Biographies: v26
~UB/SETUP-UB.TP2~ #0 #18 // Restored Minor Dialogs: v26
~UB/SETUP-UB.TP2~ #0 #19 // Restored Bhaalspawn Powers, by David Gaider: v26
~UB/SETUP-UB.TP2~ #0 #20 // Extended ToB Item Descriptions: v26
~UB/SETUP-UB.TP2~ #0 #21 // Throne of Bhaal Minor Restorations: v26
~UB/SETUP-UB.TP2~ #0 #22 // Justifier Kit: v26
~UB/SETUP-UB.TP2~ #0 #23 // Feralan Kit: v26
~UB/SETUP-UB.TP2~ #0 #24 // Sarevok's Remorse: v26
~UB/SETUP-UB.TP2~ #0 #25 // The Murder of Acton Balthis, by Kulyok: v26
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #130 // Force All Dialogue to Pause Game: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #182 // Unique Containers -> Unique icons and names: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #1080 // Add Bags of Holding: v9
~CDTWEAKS/SETUP-CDTWEAKS.TP2~ #0 #3060 // Remove "You Must Gather Your Party..." Sound (Weimer): v9

**Comment by lynxlynxlynx** [comment]
Does this show you any mods?
`weidu --change-log cut236a.bcs`

**Comment by FrElvire** [comment]
It's not mod, it's SDL, with SDL1 it's OK

**Comment by lynxlynxlynx** [comment]
That doesn't make much sense. Does it work on the subviews branch with sdl2?

**Comment by FrElvire** [comment]
It work on the subviews branch with SDL2 / SDL2+OGL. The only faulty combination is master branch with SDL2

**Comment by lynxlynxlynx** [comment]
Ok, thanks, I'll just close it then.
