### ISSUE TITLE
Fliers sometimes get occluded

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#865]
Not sure if this happens in the original or we have a bug (@FrElvire can you check?), but looking at the bg2 Slums (ar0400), the seagulls get occluded by the buildings in some spots. Following them as they fly should eventually make it obvious, since they temporarily disappear or are partially clipped (depending on the flight path).

**Comment by FrElvire** [comment]
I fear this "bug" is only in gemrb, I don't see seagulls occluded in original.

**Comment by bradallred** [comment]
yeah, I've been wrist deep in this code on the other branch and there is nothing distinguishing any type of actor. It's easy to fix if there is a way to differentiate actors that ought to be.

**Comment by lynxlynxlynx** [comment]
That's trivial, since we have to treat fliers specially in several places: `actor->GetStat(IE_DONOTJUMP) & DNJ_BIRD`
