### ISSUE TITLE
Confusion and chaotic command 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#866]
#### Bug description
1. When confused, chaotic commands remove confused status icon, but character stay confused
2. When under the effect of chaotic command spell, the character don't get confused but get confused status (as seen in attachment) 

GemRB version: master

#### Steps to reproduce
1. Get confused and received a chaotic commands spell
2. Be under chaotic commands spell and receive confusion spell

#### Expected behavior (at least feels logical)
1. being confused after receiving chaotic commands spell, character should not be confused any more or stay confused with confused status (I don't know how it's really supposed to work)
2. You should not be able to have the two status

#### Screenshots
![confusion_chaticcommands](https://user-images.githubusercontent.com/55502325/87436035-ca95f380-c5ec-11ea-947f-ee3c496b163f.png)

**Comment by lynxlynxlynx** [comment]
Do you have the fixpack installed? Because point 2 is about the data in the spells.

**Comment by FrElvire** [comment]
Yes I have fixpack installed :

SUCCESSFULLY INSTALLED      BG2 Fixpack - Core Fixes
SUCCESSFULLY INSTALLED      BG2 Fixpack - Game Text Update -> GTU Light (by Wisp)
SUCCESSFULLY INSTALLED      Widescreen Mod -> for GemRB

**Comment by lynxlynxlynx** [comment]
And what is the source of confusion in this case? The wizard, the cleric spell or some monster thing (eg. umber hulk gaze)?

**Comment by FrElvire** [comment]
It's Umber hulk, I can provide a save just before some of them if it can help

**Comment by lynxlynxlynx** [comment]
just need to know the spell they use, so if you can look that up, it'd be perfect.

**Comment by FrElvire** [comment]
The spell is confusion (see attachment), here from Myconid but same problem 
![confusion_cast](https://user-images.githubusercontent.com/55502325/87445461-5f521e80-c5f8-11ea-9da8-0ea2d3c4577e.png)

**Comment by lynxlynxlynx** [comment]
That doesn't help, I need the filename. You can ctrl-m on the affected actor to see the source of the confusion effect.

**Comment by FrElvire** [comment]
Here is what Ctrl-M return for a confused character (here by Myconid) : 206: 0x80: State:Confused (0, 0) S:spin839

[confusion.txt](https://github.com/gemrb/gemrb/files/4920669/confusion.txt)

After Chaotic command spell received, same thing :  206: 0x80: State:Confused (0, 0) S:spin839 

[chaoticcmd.txt](https://github.com/gemrb/gemrb/files/4920703/chaoticcmd.txt)

No more "confused" icon but can't select or do anything with character

**Comment by lynxlynxlynx** [comment]
So spin839, which looks fine and CC works by blocking things manually. So it should be an interesting problem.

**Comment by lynxlynxlynx** [comment]
Ok, I've tested this. 
1. is the same in the original; if you were confused before, you remain confused. It's just a consequence of effect application ordering.
2. Indeed happens sometimes. I have a queued fix for a recent regression, but that was active for just about a week. Still checking why some of the resistances don't prevent the text+icon+sound.
