### ISSUE TITLE
Character disappear after casting earth elemental transformation

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#867]
#### Bug description
When casting earth elemental transformation with Jaheira, she disappear until she moves and in console there are theses repeating errors lines

ResourceManager]: Found 'meaeg26.bam' in 'chitin.key'.                                          
[CharAnimations/ERROR]: Couldn't load animation: meaeg26, cycle 60                               
[CharAnimations/ERROR]: Couldn't load animation: meaeg26, cycle 60                               
[CharAnimations/ERROR]: Couldn't load animation: meaeg26, cycle 60                               
[CharAnimations/ERROR]: Couldn't load animation: meaeg26, cycle 60                               
[CharAnimations/ERROR]: Couldn't load animation: meaeg26, cycle 60                               
[CharAnimations/ERROR]: Couldn't load animation: meaeg26, cycle 60                               
....

GemRB version: master

#### Steps to reproduce
1. cast earth elemental transformation

#### Expected behavior
Earth elemental is displayed

#### Screenshots
![earth_trans](https://user-images.githubusercontent.com/55502325/87446763-07b4b280-c5fa-11ea-80b8-c9cb7a67a986.png)

**Comment by lynxlynxlynx** [comment]
Already mentioned in #466
