### ISSUE TITLE
[BG2] Characters pass through the decor

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#873]
#### Bug description
While playing with new pathfinding (It's way better than older one !! well done 👍 ) on areas where space is a little constrained, I see two of my characters going through the decor (at least it seems).

GemRB version: master

#### Steps to reproduce
1. load included save
2. do the same as in video

#### Expected behavior
All characters take stairs

#### Video
[path_shortcut-2020-07-18_12.13.25.zip](https://github.com/gemrb/gemrb/files/4941477/path_shortcut-2020-07-18_12.13.25.zip)

#### Save
[000000087-through decor bug.zip](https://github.com/gemrb/gemrb/files/4941478/000000087-through.decor.bug.zip)

**Comment by FrElvire** [comment]
I can't reproduce it with old pathfinding code

**Comment by kmfrick** [comment]
It's an oversight in `BlockSearchMap`, made apparent by the presence of bumping with the new pathfinder: blocking the searchmap overrides `PATH_MAP_IMPASSABLE`, if present. I'll address this in #874 .
