### ISSUE TITLE
Party placement outside of target location

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#876]
#### Bug description
In some small rooms when wanting going into them, some characters are placed outside. If you click more times in this room it finally give you a placement with all characters inside, so there's enough room

GemRB version: master

#### Steps to reproduce
1. See video

#### Expected behavior
When clicking in a room place destination of all characters in this room and if there's not enough room, place characters who can't enter  in front of the door (in this example, it's a room but can by be easily reproduced with some narrow stairs) 

#### Video
[placement-2020-07-19_10.20.36.zip](https://github.com/gemrb/gemrb/files/4943458/placement-2020-07-19_10.20.36.zip)

**Comment by lynxlynxlynx** [comment]
There's no concept of rooms on the search map; everything that's walkable is treated the same. Theoretically we could be calculating also paths between the destinations and rerouting if they're too long, but that would be hard to get right, besides potentially slowing everything down, especially for large parties. I'm inclined to close this as wontfix.

**Comment by FrElvire** [comment]
It's not really annoying anyway, so let's close it
