### ISSUE TITLE
Fail to grab item (on ground) 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#877]
#### Bug description
Here there are dozens of things on ground (following some kills and Crtl+W to gather items). In inventory windows you can't grab items at the bottom of the list with error on console.

[GUIScript/ERROR]: Syntax Error:                                                                 
[Python/ERROR]: Traceback (most recent call last):                                               
[Python/ERROR]:   File "/usr/share/gemrb/GUIScripts/InventoryCommon.py", line 49, in OnDragItemGround                                                                                             
[Python/ERROR]:     GemRB.DragItem (pc, slot, item["ItemIcon"], 0, 1) #container                 
[Python/ERROR]: AttributeError: Invalid slot                                                     

GemRB version: master

#### Steps to reproduce
1. load save
2. Click on items in the ground
3. go in inventory
4. select items at the bottom of the list
5.click to grab them

#### Expected behavior
grab item and no error in console

#### Screenshots
![grab_object](https://user-images.githubusercontent.com/55502325/87872639-aeae9b00-c9ba-11ea-9609-eeb39f960e2e.png)

#### Save
[000000026-item grab bug.zip](https://github.com/gemrb/gemrb/files/4943546/000000026-item.grab.bug.zip)

**Comment by lynxlynxlynx** [comment]
Yeah, an old issue, never drilled in to see why it's happening.
