### ISSUE TITLE
Gamplay Options 

### ISSUE THREAD

**Issue by ifyGecko** [gemrb/gemrb#878]
#### Bug description
On IWD with out HoW installed a game play option (max hit points per level) will not highlight when selected.

GemRB version: 0.8.6-git

#### Steps to reproduce
1. Go to Options
2. Click on Game Play
3. Try to set "Max Hit Points Per Level"

#### Expected behavior
Selection box to be highlighted like the others

**Comment by ifyGecko** [comment]
I'm assuming this option isn't actually implemented from looking at GUIScripts/GUIOPT.py and when hovering over the option it does not give an option description like the others. Is this so or am I missing something?

**Comment by lynxlynxlynx** [comment]
Looks like gemrb/GUIScripts/GUIOPT.py:371 should also be checking for iwd1.

**Comment by ifyGecko** [comment]
Agreed, I'll handle this one.
