### ISSUE TITLE
Replace `Map::PathNode` with an `std::list<Point>`

### ISSUE THREAD

**Issue by kmfrick** [gemrb/gemrb#880]
I'm posting this here both to keep track of it myself and, mainly, to ask if I should wait until `subviews` is merged to do this.

`Map::PathNode` implements a doubly-linked list of (navmap) `Point`s and orientations, but: 
- it's 2020 and programmers don't have to write their own linked lists anymore in any sensible programming language; 
- the new pathfinder generates paths that have a much lower node count, so orientations can be just calculated in `Movable::DoStep` instead of `Map::FindPath`, saving a few function calls - not much of an optimization, but it'll contribute to make FindPath less of a behemoth both in terms of code and assembly;
- right now, `PathNode` doesn't store Points but coordinates, which makes it 4.8% more bothersome to pass it around.
- using the STL for this will also make it harder for memory leaks to appear in the future and simplify the code - one less custom data structure to keep track of.

**Comment by lynxlynxlynx** [comment]
Its use is pretty localised, so I don't think we need to wait for subviews. But definitely for the current release, less than a month away, just to minimize potential problems.
