### ISSUE TITLE
[subviews] bg2 start screen miscolorations

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#882]
The cursor is only drawn over the frame and many things lost their color (buttons, tooltips):
![image](https://user-images.githubusercontent.com/121515/88512051-2e092380-cfe6-11ea-9c26-b25ce050e604.png)

**Comment by bradallred** [comment]
obviously this isn't happening for me... I'll comb through the diff and look for suspects.

**Comment by bradallred** [comment]
I _can_ repro on x11
