### ISSUE TITLE
[subviews] area animations get occluded

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#883]
subviews ar0201:
![image](https://user-images.githubusercontent.com/121515/88518070-277fa980-cff0-11ea-8fc6-2588fb74dd04.png)
master:
![image](https://user-images.githubusercontent.com/121515/88518113-38c8b600-cff0-11ea-9c97-1b0ab26388ff.png)
original (matches master):
https://lparchive.org/Baldurs-Gate-2-and-Throne-of-Bhaal/Update%2028/11-BG2SoAch18008.jpg

The top left torch looks fine, but most in the area look like the other one. Ctrl-4 shows the problem — the base polygon is drawn over.

**Comment by bradallred** [comment]
those polygons have their `WF_COVERANIMS` flag set

**Comment by lynxlynxlynx** [comment]
Our use changed its meaning from master then. NI has an area animation bit to invert the behaviour, but it's not set on these flames either. So it looks like we don't understand the flags well yet.

**Comment by bradallred** [comment]
the logic is currently like this:

an `AreaAnimation` is covered if the wall polygon has `WF_COVERANIMS` set _unless_ either the `AreaAnimation` has the `A_ANI_NO_WALL` set _or_ the game flag `GF_IMPLICIT_AREAANIM_BACKGROUND` is set _and_ the animation has a negative `height`.

I presume the `A_ANI_NO_WALL` bit is the one you are talking about. Are you saying these animations have that bit set in the data?

**Comment by bradallred** [comment]
is it possible we are using the wrong bit(s)? for the polygon?

[IESDP](https://gibberlings3.github.io/iesdp/file_formats/ie_formats/wed_v1.3.htm) has 2 bits listed for "cover animations"

**Comment by lynxlynxlynx** [comment]
The IESDP description doesn't match NI or DLTCEP (which are consistent with each other), so I think it's just old.

Don't know about WF_HOVER - it's set on the ropes of the safety fence, but not on the posts. /.../ Digging up brings up some nice old docs (on the bits, interactions with animations):
http://www.simpilot.net/~sc/dltcep/areamaking/wallgroups.htm

**Comment by bradallred** [comment]
we seem to be following that table except for perhaps ignoring the baseline for `AreaAnimations`, but master ignores it too... I'll play around with it and see if that solves tho.

**Comment by bradallred** [comment]
if my theory is correct, this will be fixed by adding code for `AreaAnimation` to respect the wall polygon baseline (when the flag is set, which it is in this case). This follows the table from DLTCEP.

this also means that master doesn't use the `AreaAnimation::height` correctly (which might explain the existance `GF_IMPLICIT_AREAANIM_BACKGROUND`).

I believe that the `AreaAnimation::Pos` is the position where the animation is drawn, but the conceptual position for the animation is `AreaAnimation::Pos` + `AreaAnimation::height`. This conceptual position is what is used for the wall polygon baseline comparison. This fixes the torches because their "position" is now right below the baseline and they are therefore in front of the wall.

**Comment by lynxlynxlynx** [comment]
I remember the iwd negative height case (ar9101), where the ceiling explanation doesn't really work or at least not intuitively. I think Hobart was occluded before and maybe one of the two animations wasn't visible. Easy to check by toggling the setting in gemrb.ini. 

I suspect the special handling isn't really needed if we take the baseline into account like you say. Looking at the area, the two animations are set up at almost the same level, so treating height (probably better called ZPos) as usual, should then ensure proper placement.

footage from the original:
https://youtu.be/EGZihg_vpGg?t=20

**Comment by bradallred** [comment]
so far my theory seems to work fine for everything including IWD AR9101. However, the problem with AR9101 is that the animation itself has a background included.

<img width="192" alt="image" src="https://user-images.githubusercontent.com/1126744/88713522-ab14c580-d0d8-11ea-80d9-0dff7a4eeed5.png">

that is with the tile map and background animations disabled. this is odd and disappointing, but I guess it wasn't until BG:EE that the engine supported alpha values for palettes so I suppose this was the only way to make the shadows look nice if you needed an animation to appear in front of some walls. I have no idea why they didn't just set the background flag tho.

**Comment by bradallred** [comment]
are we sure about `A_ANI_BACKGROUND`? we don't seem to match DLTCEP nor IESDP

**Comment by lynxlynxlynx** [comment]
DLTCEP has it as "Ground (the animation is covered by actors)", NI as "Draw as background", which both match. It's just iesdp that's confusing, since it uses the term cover for a different bit than everyone else.

**Comment by bradallred** [comment]
oh, the DLTCEP screenshot I have shows that bit as "transparent"

**Comment by lynxlynxlynx** [comment]
old stuff:
![image](https://user-images.githubusercontent.com/121515/88720478-37e57080-d125-11ea-95a7-d0ac45b91fc9.png)

**Comment by bradallred** [comment]
cool, thanks.

I've got ahead and removed the checks for `GF_IMPLICIT_AREAANIM_BACKGROUND` since that area seems to work now. Let's play around and see if we can't break something else now. If not we can just remove that flag entirely.

**Comment by lynxlynxlynx** [comment]
ar9109 shows regressions (no dithering):
![image](https://user-images.githubusercontent.com/121515/88726645-69166e80-d12e-11ea-91df-8c6a5a981c5f.png)
![image](https://user-images.githubusercontent.com/121515/88726694-7fbcc580-d12e-11ea-8308-c0fb9a5aee94.png)

ctrl-4 doesn't draw walls any more.
![image](https://user-images.githubusercontent.com/121515/88726822-ada20a00-d12e-11ea-963b-dee2404501ae.png)

**Comment by bradallred** [comment]
if you hit ctrl+5 a few more times you will get better debug info

ctrl+4 is for info points and ctrl+5 is for walls

**Comment by bradallred** [comment]
this is actually due to having an area smaller than the viewport so we run into an underflow situation. nothing to do with these changes.

**Comment by lynxlynxlynx** [comment]
Ah, didn't know you split it off.

Now the apparent positioning is better, but the actors get semi-transparent instead of dithered:
![image](https://user-images.githubusercontent.com/121515/88763864-28d9df00-d174-11ea-8087-1fff574adf9a.png)

Easier to see in this comparison with master (also shows ladder problems): 
![image](https://user-images.githubusercontent.com/121515/88764316-072d2780-d175-11ea-87c2-d23203ff9dcc.png)
![image](https://user-images.githubusercontent.com/121515/88764334-101df900-d175-11ea-8823-d879754bbc5f.png)

**Comment by bradallred** [comment]
right, as discussed in #441 we can't do dithering on SDL2 as it would be astronomically expensive to do without a proper shader. BG:EE doesn't dither either FWIW, just 0-100% opacity. It's been this way for ages now.

We could manually dither the stencils at a performance cost, but then everything would be dithered always. I dont see any benefit tho.

**Comment by lynxlynxlynx** [comment]
Closing in favour of a clean new issue for the eventual shader.
