### ISSUE TITLE
[BG1]  Game freezes when trying to open charachter stats while wielding a broken weapon

### ISSUE THREAD

**Issue by neula** [gemrb/gemrb#885]
#### Bug description
After breaking a weapon the charachter is still wielding the broken weapon remaining in its weapon slot 
( although it's just a regular item and can't be equipped, after moving it out of the weapon slot ).
Opening the charachter stats will now Freeze the game, due to the main weapon not beeing found by the
GetWeapon ( GetWeaponHeader ?) function.

Relevant console output:
```[Python]: CannotDualClass: no good new class choices
[GUIScript/ERROR]: Runtime Error:
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/usr/share/gemrb/GUIScripts/GUIREC.py", line 148, in OpenRecordsWindow
[Python/ERROR]:     UpdateRecordsWindow ()
[Python/ERROR]:   File "/usr/share/gemrb/GUIScripts/GUIREC.py", line 304, in UpdateRecordsWindow
[Python/ERROR]:     Text.SetText (GetStatOverview (pc))
[Python/ERROR]:   File "/usr/share/gemrb/GUIScripts/GUIREC.py", line 340, in GetStatOverview
[Python/ERROR]:     cdet = GemRB.GetCombatDetails (pc, 0)
[Python/ERROR]: RuntimeError: Serious problem in GetCombatDetails: could not find the hitting header!
[ResourceManager]: Found 'GUIOPT.chu' in 'Override'.
[ResourceManager]: Searching for 'guierr3b'...
[ResourceManager]: Found 'guierr3b.mos' in 'chitin.key'.
[ResourceManager]: Searching for 'gam_03'...
[ResourceManager]: Found 'gam_03.wav' in 'chitin.key'.
[Info]: Press ctrl-c (or close the window) again to quit GemRB.
```

GemRB version: master

#### Steps to reproduce
1. Break your main weapon (already done in the provided savegame)
2. Click on the charachter stats menu

#### Expected behavior
Charachter stats menu opens with stats for no weapon (fists).
[savegame_brokensword.tar.gz](https://github.com/gemrb/gemrb/files/4994944/savegame_brokensword.tar.gz)

**Comment by lynxlynxlynx** [comment]
Ah, nice, the iron crisis strikes back. Simple to fix with several options (mark as unequipped, unequip fully, catch the corner case) ...

**Comment by lynxlynxlynx** [comment]
It won't fix it for your save (avoidable through the inventory), but for future occurrences.
