### ISSUE TITLE
 Berzerk and character control

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#887]
#### Bug description
When berzerk is used (here with with Minsc), he is not considered any more as "user controlled" so here are some problems encountered (not limited to ?) : 

- He can't enter or leave a room, zone, ....
- You can't sleep
- You can't save

GemRB version: master

#### Expected behavior
As in original, you can do all theses things above without problem

**Comment by lynxlynxlynx** [comment]
Are you sure this was the behaviour in the original? It's not the same as barbarian rage or berzerker's thingie.

**Comment by chilvence** [comment]
I loaded up BG classic - if you use Minsc's berserk, he is controllable until the point where he spots a target then his circle turns yellow and becomes uncontrollable. So it is more like the 'cursed berserking', unlike the barbarian rage/berserker kit as you say.

**Comment by FrElvire** [comment]
I recheck and yes until fight comes, there seem to be not restriction on what you can do. 2 video just made with original, one without combat and one with :
[berzerk_no_combat.zip](https://github.com/gemrb/gemrb/files/5011957/berzerk_no_combat.zip)
[berzerk_combat.zip](https://github.com/gemrb/gemrb/files/5011958/berzerk_combat.zip)

**Comment by neula** [comment]
Pretty sure this is also the case with the berserk sword you could get in BG1.
Unfortunately I can't test it with the IE version at the moment.
