### ISSUE TITLE
[BG2] Comet spell doesn't seem to work as expected

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#888]
#### Bug description
When comet spell is casted or in Saradush (visually it seems identical), you see the comet fall but looks like disappear without hitting the ground, opponent or party member (in case of Saradush siege) nor doing any damage

GemRB version: master

#### Steps to reproduce
1. In Saradush wait for it or cast it 
2. not visual on impact
3. no damage

#### Expected behavior
Visual effect on impact and damage as expected. 

Verified on original, in Saradush you take damage when it falls on you, not on gemrb

#### Video
[placement-2020-08-01_16.26.46.zip](https://github.com/gemrb/gemrb/files/5010702/placement-2020-08-01_16.26.46.zip)

**Comment by lynxlynxlynx** [comment]
It looks like our projectile is incomplete, without any spell payload.

**Comment by FrElvire** [comment]
In original - Not well framed but give you an idea
[comet.zip](https://github.com/gemrb/gemrb/files/5011955/comet.zip)

**Comment by lynxlynxlynx** [comment]
It had a 1' radius set and no explosion graphics.

**Comment by FrElvire** [comment]
It's now fixed 👍.

But I'm wondering how in original it's done in Saradush as now in gemrb your party can be kill in oneshoot. In original it's vastly less fatal.

**Comment by lynxlynxlynx** [comment]
it's a 10d10, so up to 100 points of damage ...

**Comment by FrElvire** [comment]
I have done more test to confirm or not my impression and yes it seem there is really a problem : 

- In original I never get near 100 and always one line of damage (On 3 comet, 30 is the max damage get by a party member)
- In gemrb, damage can get beyond 100 with multiple lines and multiple time as if there are 2 impacts (or something like that) 

Here is some information for you to see : 

Gemrb : 
[sradush_comet_gemrb-2020-08-04_07.38.40.zip](https://github.com/gemrb/gemrb/files/5020339/sradush_comet_gemrb-2020-08-04_07.38.40.zip)

Original : 
![Saradush_comet_original](https://user-images.githubusercontent.com/55502325/89258619-c3c93200-d628-11ea-95bd-18a8e637d967.png)

**Comment by FrElvire** [comment]
Console log from another comet fall in gemrb : 
[damage saradush comet.txt](https://github.com/gemrb/gemrb/files/5020377/damage.saradush.comet.txt)

**Comment by lynxlynxlynx** [comment]
It's fire damage, so resistances apply. But we definitely shouldn't be applying the damage several times.

**Comment by lynxlynxlynx** [comment]
My first hit looks fine:
![image](https://user-images.githubusercontent.com/121515/89273716-37c30480-d640-11ea-91a1-c5c65c9c7c22.png)

**Comment by lynxlynxlynx** [comment]
Did hit it on the second try. Not sure if there's something wrong with the projectile or just more than one (4 in this case) catapult launches happened.

**Comment by lynxlynxlynx** [comment]
They don't use comet, but jwsiege.spl (5d10). It's fired by some of the fire giants (at guards on wall) and the ptsiege*.baf scripts, targeting the city.

**Comment by lynxlynxlynx** [comment]
So far I can only say that it's not a scripting problem, as a single spell cast can cause several projectile payloads and in the same tick. Might be easier to test with Comet itself and just disable the friendly-fire protection for the duration.

**Comment by FrElvire** [comment]
Everything seems ok 👍
