### ISSUE TITLE
[feature] SNDCHANN.2da handling

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#89]
**Description**
~We currently ignore this table. https://gibberlings3.github.io/iesdp/files/2da/2da_tob/sndchann.htm~

Remaining TODO:
- [ ] ARMOR #124
- [x] SWINGS #100
- [x] MONSTER also for their 2da/ini sounds (some combat sounds are also missing #148 )

RESEARCH all the mappings and implement, will fix too loud magic missile hit sound. Maybe also Saradush soldier NPCs' loud grunts.

**Additional context**
- HIT_*.wav for HITS. It's also what MM uses — also modifies the volume of spell effect sounds with a target (using opcode #174)
- SWI_*.wav for SWINGS #100 and in-CRE ATTACK soundset slot (but not 2DA attack sounds -- these are modified by MONSTER)
- MONSTER: 2DA soundsets and NPC in-CRE soundsets (if they're hostile)
- CHA/CAS_*.wav for CASTING
- ARM_*.wav for ARMOR (tings and twangs as actors in armor move aroun, not inventory don/doff)
- MISSILE ???
- AMB_*.wav: AMBIENTL, AMBIENTN, AREA_AM﻿B are at 100 anyway. Info from skellytz
  - AMBIENTL modifies the volume of ambients in the ARE ambients section with the looping flag.
  - AMBIENTN modifies the volume of all other ambients in the ARE ambients section. 
  - AREA_AMB modifies the volume of main ambients in the ARE songs section (BG1 main ambients), as well as ambients in the ARE ambients section with both looping and ignore radius flags (BG2 main ambients).
- WALKINGC, WALKINGM   footsteps sounds (characters, monsters / pcs, npcs)

**Comment by skellytz** [comment]
Here's the full list based on my research:

**NARRATIO** - textscreen narrator

**AREA_AMB** - main ambients in the songs section; ambients in the ambients section flagged as looping and ignore radius

**ACTIONS** - open/close doors etc. (confusingly not the ACT_XXX sounds)

**SWINGS** - SWI_XX sounds; in-CRE soundset ATTACK slot

**CASTING** - spellcasting voices (BG1: CAS_PXXX, BG2: CHA_XXXX); casting completion sounds in SPL files

**GUI** - buttons around the UI etc.; inventory and container sounds; some special actions (e.g., Turn Undead, Bard's Song)

**DIALOG** - voiceovers in dialog; neutral in-CRE soundset slots (e.g., INITIAL_MEETING, SELECT_COMMON)

**CHARACT0** - party member 1 (leader) soundset

**CHARACT1** - party member 2 soundset

**CHARACT2** - party member 3 soundset

**CHARACT3** - party member 4 soundset

**CHARACT4** - party member 5 soundset

**CHARACT5** - party member 6 soundset

**MONSTER** - 2DA soundsets; hostile in-CRE soundset slots (e.g., BATTLE_CRY)

**HITS** - HIT_XXX sounds; some special actions (e.g., Hide in Shadows, Detect Traps, Disarm, Lockpick); spell effects using play sound opcode (#174); sounds in VVC files

**MISSILE** - sounds in PRO files

**AMBIENTL** - ambients flagged as looping

**AMBIENTN** - ambients not flagged as looping

**WALKINGC** - PC footsteps

**WALKINGM** - NPC/monster footsteps

**ARMOR** - ARM_XX sounds (tings and twangs as actors in armor move around)

**Comment by fizzet** [comment]
I've been working on this for a bit. I've got the basic setup working, but I'm not sure when I'll next find time to add the missing stuff.

What's still missing?
- ambients
- PST has an additional parameter REVERB in sndchann.2da
- verification that we actually play all the sounds we do play on the correct channel.; there are quite a few I am not too sure about
- add missing sounds (e.g., I don't think we play anything that's supposed to use ARMOR right now)

Should I rather push now, or wait until more complete?

**Comment by lynxlynxlynx** [comment]
If it's already an improvement, I say push it. That loud Magic missile sound is annoying!

Ambients entries are all set to 100, so it's not that important to implement that.

PST also had some special handling of reverb, storing an ID in the songlist area (SongHeader.reverbID). Our EAX implementation does take it into account, but you can see in MapReverb::getReverbProperties that the volume column is not used yet anywhere. I guess volume and this sndchann global adjustment just need to scale the three flGain* values? @MarcelHB any thoughts?

And yes, the armor ones are missing.

**Comment by lynxlynxlynx** [comment]
Very nicely done with 72404d85ad3! I've added a todo to the first post, so it will be easier to complete.

**Comment by lynxlynxlynx** [comment]
Swings are now implemented. They sometimes don't match the animation, but that's due to the fact that we don't use the combat bitmaps for round timing yet #92.

**Comment by lynxlynxlynx** [comment]
Closing; the framework is there and the only missing piece has its own report.
