### ISSUE TITLE
Screen freeze the second time I start GemRB using nouveau

### ISSUE THREAD

**Issue by kmfrick** [gemrb/gemrb#892]
#### Bug description
I first noticed this a while ago and just dismissed it as some freak accident, but while testing for #890 this happened again so I'm posting it here. It's definitely low-priority IMO since it's only happening to me and most people with NVIDIA graphics cards install the proprietary drivers anyway. 

The first time I start GemRB after a reboot, everything is fine. The second time, my screen hangs. This only happens when using the Nouveau free drivers and not with the proprietary NVIDIA ones. 

Moreover, if I wait a while before starting GemRB again, this doesn't happen. 

When this had happened before I had music playing and it kept playing, so it's a purely video thing.

The old dmesg log doesn't show anything out of the ordinary, nor does `journalctl -xe`. 

#### Steps to reproduce
Not sure if "steps" fit here, since it just happens when starting GemRB two times. Saw this happen on Fedora 32 and Debian sid. My GPU is a GTX 670.  

#### Expected behavior
The screen shouldn't freeze.

#### Screenshots
N/A.

**Comment by MarcelHB** [comment]
The last time I've tried nouveau on my old Nvidia GTX 460, the whole system was far from optimal, like glxgears was slow, screen resolution was limited. So I guess it's out of our range here.

**Comment by kmfrick** [comment]
I just thought it would be good to have it here since it looks really obscure and some Googler might find this and know they should install the proprietary drivers. Feel free to close this if you so deem appropriate!

**Comment by lynxlynxlynx** [comment]
Do you get this with any other SDL program? Does it happen with both the sdl1 and sdl2 backends?
