### ISSUE TITLE
Some lights are off during the day in the original, not in gemrb

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#895]
#### Bug description
I suppose it's just an example, in Saradush, torch are lit all time in gemrb. In original just at nigth, like in screenshot

GemRB version: master

#### Expected behavior
Torch off like in original

#### Screenshots
<img width="601" alt="torch_saradush" src="https://user-images.githubusercontent.com/55502325/89127648-62ea0e80-d4ef-11ea-8a31-f25875cdeb4b.png">

**Comment by lynxlynxlynx** [comment]
They have a schedule of 21:30 - 6:30. At what times is it wrong? Do we just have a rounding error?

**Comment by FrElvire** [comment]
Ok there's no bug here. I just looked if it was day time or not and not the time .... bug closed....sorry...
