### ISSUE TITLE
[subviews] Performance problems on IWD2

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#899]
I just got the latest version of subviews and noticed one thing with SDL2 on IWD2: whenever I enter the game, no matter where, performance is about 3-6fps.

It's good on Baldur's Gate 2, and for both on SDL1.2, i. e. with frame lock at 30fps. Also good on master.

I can do profiling or test other games tomorrow or at the weekend, maybe. 

Update: When displaying new dialog lines in BG2, or hovering dialog answers, performance also goes down to the same extent.

**Comment by MarcelHB** [comment]
Maybe it's just missing fixes from the path finder changes in this branch?

**Comment by lynxlynxlynx** [comment]
It's not up to speed, but I never had pathfinder problem in the starting area of iwd2.

**Comment by MarcelHB** [comment]
I'm left with more questions than before. The profiler says that both IWD2 and BG2 receive roughly the same amount of CPU time, and that's much less than master - good.

AMD GPU Profiler: only D3D12 and Vulkan, so no use for us. RenderDoc: Not much help for D3D9, and I don't know how to properly initialize SDL2 with the required OpenGL3.2 flags for it to work while not doing some research.

But: If I hint SDL2 into using `direct3d11` as backend, performance is good again for IWD2. Good to know, but does not get us closer to where the atopy against IWD2 is located. Let me think of further ideas.

**Comment by MarcelHB** [comment]
... and if this wasn't enough, my mobile i915 device on Linux runs smoothly. I'll try going back to some older commit, trying to find a good state, and then bisect. No idea if this is some AMD driver issue.

**Comment by MarcelHB** [comment]
amdgpu (Linux) also doing fine.

**Comment by MarcelHB** [comment]
Wasn't much fun to bisect, but here it starts: 799c0ceda67ca8226a541b44e304fdba95538635

**Comment by MarcelHB** [comment]
The whole thing is not easy, but at least I've found something:

From what I've seen looking at the commit above and its later refactoring, this `spr->Restore()` effectively leads to huge amount of `SDL_DestroyTexture` -> `SDL_CreateTextureFromSurface` pairs, much more for IWD2 by default, but also for font rendering in the other games. My not-so-bad AMD GPU is the only one struggling with D3D9 and OpenGL here, no clue yet. 

Anyway, since there is room for improvement by simply doing `SDL_UpdateTexture` since we just change colors, not dimensions. But then it's not so easy, since SDL2 does quite a lot of necessary things in `SDL_CreateTextureFromSurface` like obtaining conversion information for surface -> texture, applying color modification and so on. If we don't do all that, there are some minor glitches mostly related to font rendering. But there is no such onboard function in SDL2, like a `SDL_UpdateTextureFromSurface`. 

So I put this together from the SDL2 source code, taking the `SDL_CreateTextureFromSurface` and throwing out `SDL_CreateTexture` -- _and then it's fast again_, see the patch file below for an idea. Anyway, this looks like a major workaround at the wrong end, yet I have no better suggestion. Maybe I could write a minimal test that runs slow on Windows OpenGL/D3D9 but fast on the i915 Linux OpenGL -- and then ask the guys at SDL2 about an idea? Or maybe break it down into the API calls and try to find somebody with AMD insights. But for now, the games are partially/fully unplayable for me.

@chilvence What's your Windows GPU?

<details>
  <summary>Expand to see patch</summary>
```diff
diff --git a/gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp b/gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp
index 5cc9ac78c..fa9fdf331 100644
--- a/gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp
+++ b/gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.cpp
@@ -327,14 +327,14 @@ void* SDLSurfaceSprite2D::NewVersion(version_t newversion) const
 #if SDL_VERSION_ATLEAST(1,3,0)
 SDLTextureSprite2D::SDLTextureSprite2D(const Region& rgn, int Bpp, void* pixels,
 									   ieDword rmask, ieDword gmask, ieDword bmask, ieDword amask)
-: SDLSurfaceSprite2D(rgn, Bpp, pixels, rmask, gmask, bmask, amask)
+: SDLSurfaceSprite2D(rgn, Bpp, pixels, rmask, gmask, bmask, amask), updateTexture(false)
 {
 	texture = NULL;
 }
 
 SDLTextureSprite2D::SDLTextureSprite2D(const Region& rgn, int Bpp,
 									   ieDword rmask, ieDword gmask, ieDword bmask, ieDword amask)
-: SDLSurfaceSprite2D(rgn, Bpp, rmask, gmask, bmask, amask)
+: SDLSurfaceSprite2D(rgn, Bpp, rmask, gmask, bmask, amask), updateTexture(false)
 {
 	texture = NULL;
 }
@@ -354,27 +354,205 @@ SDL_Texture* SDLTextureSprite2D::GetTexture(SDL_Renderer* renderer) const
 {
 	if (texture == NULL) {
 		texture = new TextureHolder(SDL_CreateTextureFromSurface(renderer, GetSurface()));
+	} else if (updateTexture) {
+		this->updateTexture = false;
+		SDL_UpdateTextureFromSurface(renderer, *texture, GetSurface());
 	}
 	return *texture;
 }
 
 void SDLTextureSprite2D::SetColorKey(ieDword pxvalue)
 {
-	texture = NULL;
+	this->updateTexture = true;
 	SDLSurfaceSprite2D::SetColorKey(pxvalue);
 }
 
 void* SDLTextureSprite2D::NewVersion(version_t version) const
 {
-	texture = NULL;
+	this->updateTexture = true;
 	return SDLSurfaceSprite2D::NewVersion(version);
 }
 
 void SDLTextureSprite2D::Restore() const
 {
-	texture = NULL;
+	this->updateTexture = true;
 	SDLSurfaceSprite2D::Restore();
 }
+
+void SDL_DetectPalette(SDL_Palette *pal, SDL_bool *is_opaque, SDL_bool *has_alpha_channel) {
+	int i;
+
+	{
+		SDL_bool all_opaque = SDL_TRUE;
+		for (i = 0; i < pal->ncolors; i++) {
+			Uint8 alpha_value = pal->colors[i].a;
+			if (alpha_value != SDL_ALPHA_OPAQUE) {
+				all_opaque = SDL_FALSE;
+				break;
+			}
+		}
+
+		if (all_opaque) {
+			/* Palette is opaque, with an alpha channel */
+			*is_opaque = SDL_TRUE;
+			*has_alpha_channel = SDL_TRUE;
+			return;
+		}
+	}
+
+	{
+		SDL_bool all_transparent = SDL_TRUE;
+		for (i = 0; i < pal->ncolors; i++) {
+			Uint8 alpha_value = pal->colors[i].a;
+			if (alpha_value != SDL_ALPHA_TRANSPARENT) {
+				all_transparent = SDL_FALSE;
+				break;
+			}
+		}
+
+		if (all_transparent) {
+			/* Palette is opaque, without an alpha channel */
+			*is_opaque = SDL_TRUE;
+			*has_alpha_channel = SDL_FALSE;
+			return;
+		}
+	}
+
+	/* Palette has alpha values */
+	*is_opaque = SDL_FALSE;
+	*has_alpha_channel = SDL_TRUE;
+}
+
+SDL_Texture* SDL_UpdateTextureFromSurface(SDL_Renderer *renderer, SDL_Texture* texture, SDL_Surface * surface) {
+	const SDL_PixelFormat *fmt;
+	SDL_bool needAlpha;
+	SDL_bool direct_update;
+	int i;
+	Uint32 format = SDL_PIXELFORMAT_UNKNOWN;
+
+	/* See what the best texture format is */
+	fmt = surface->format;
+	if (fmt->Amask || SDL_HasColorKey(surface)) {
+		needAlpha = SDL_TRUE;
+	} else {
+		needAlpha = SDL_FALSE;
+	}
+
+	/* If Palette contains alpha values, promotes to alpha format */
+	if (fmt->palette) {
+		SDL_bool is_opaque, has_alpha_channel;
+		SDL_DetectPalette(fmt->palette, &is_opaque, &has_alpha_channel);
+		if (!is_opaque) {
+			needAlpha = SDL_TRUE;
+		}
+	}
+
+	SDL_RendererInfo rendererInfo = {};
+	SDL_GetRendererInfo(renderer, &rendererInfo);
+
+	/* Try to have the best pixel format for the texture */
+	/* No alpha, but a colorkey => promote to alpha */
+	if (!fmt->Amask && SDL_HasColorKey(surface)) {
+		if (fmt->format == SDL_PIXELFORMAT_RGB888) {
+			for (i = 0; i < (int)rendererInfo.num_texture_formats; ++i) {
+				if (rendererInfo.texture_formats[i] == SDL_PIXELFORMAT_ARGB8888) {
+					format = SDL_PIXELFORMAT_ARGB8888;
+					break;
+				}
+			}
+		} else if (fmt->format == SDL_PIXELFORMAT_BGR888) {
+			for (i = 0; i < (int)rendererInfo.num_texture_formats; ++i) {
+				if (rendererInfo.texture_formats[i] == SDL_PIXELFORMAT_ABGR8888) {
+					format = SDL_PIXELFORMAT_ABGR8888;
+					break;
+				}
+			}
+		}
+	} else {
+		/* Exact match would be fine */
+		for (i = 0; i < (int)rendererInfo.num_texture_formats; ++i) {
+			if (rendererInfo.texture_formats[i] == fmt->format) {
+				format = fmt->format;
+				break;
+			}
+		}
+	}
+
+	/* Fallback, choose a valid pixel format */
+	if (format == SDL_PIXELFORMAT_UNKNOWN) {
+		format = rendererInfo.texture_formats[0];
+		for (i = 0; i < (int)rendererInfo.num_texture_formats; ++i) {
+			if (!SDL_ISPIXELFORMAT_FOURCC(rendererInfo.texture_formats[i]) &&
+					SDL_ISPIXELFORMAT_ALPHA(rendererInfo.texture_formats[i]) == needAlpha) {
+				format = rendererInfo.texture_formats[i];
+				break;
+			}
+		}
+	}
+
+	if (format == surface->format->format) {
+		if (surface->format->Amask && SDL_HasColorKey(surface)) {
+			/* Surface and Renderer formats are identicals.
+			 * Intermediate conversion is needed to convert color key to alpha (SDL_ConvertColorkeyToAlpha()). */
+			direct_update = SDL_FALSE;
+		} else {
+			/* Update Texture directly */
+			direct_update = SDL_TRUE;
+		}
+	} else {
+		/* Surface and Renderer formats are differents, it needs an intermediate conversion. */
+		direct_update = SDL_FALSE;
+	}
+
+	if (direct_update) {
+		if (SDL_MUSTLOCK(surface)) {
+			SDL_LockSurface(surface);
+			SDL_UpdateTexture(texture, NULL, surface->pixels, surface->pitch);
+			SDL_UnlockSurface(surface);
+		} else {
+			SDL_UpdateTexture(texture, NULL, surface->pixels, surface->pitch);
+		}
+	} else {
+		SDL_PixelFormat *dst_fmt;
+		SDL_Surface *temp = NULL;
+
+		/* Set up a destination surface for the texture update */
+		dst_fmt = SDL_AllocFormat(format);
+		if (!dst_fmt) {
+		   SDL_DestroyTexture(texture);
+		   return NULL;
+		}
+		temp = SDL_ConvertSurface(surface, dst_fmt, 0);
+		SDL_FreeFormat(dst_fmt);
+		if (temp) {
+			SDL_UpdateTexture(texture, NULL, temp->pixels, temp->pitch);
+			SDL_FreeSurface(temp);
+		} else {
+			SDL_DestroyTexture(texture);
+			return NULL;
+		}
+	}
+
+	{
+		Uint8 r, g, b, a;
+		SDL_BlendMode blendMode;
+
+		SDL_GetSurfaceColorMod(surface, &r, &g, &b);
+		SDL_SetTextureColorMod(texture, r, g, b);
+
+		SDL_GetSurfaceAlphaMod(surface, &a);
+		SDL_SetTextureAlphaMod(texture, a);
+
+		if (SDL_HasColorKey(surface)) {
+			/* We converted to a texture with alpha format */
+			SDL_SetTextureBlendMode(texture, SDL_BLENDMODE_BLEND);
+		} else {
+			SDL_GetSurfaceBlendMode(surface, &blendMode);
+			SDL_SetTextureBlendMode(texture, blendMode);
+		}
+	}
+	return texture;
+}
 #endif
 
 }
diff --git a/gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.h b/gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.h
index 8e796c027..9a6531324 100644
--- a/gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.h
+++ b/gemrb/plugins/SDLVideo/SDLSurfaceSprite2D.h
@@ -101,6 +101,7 @@ class SDLTextureSprite2D : public SDLSurfaceSprite2D {
 	};
 
 	mutable Holder<TextureHolder> texture;
+	mutable bool updateTexture;
 
 public:
 	SDLTextureSprite2D(const Region&, int Bpp, void* pixels,
@@ -118,6 +119,9 @@ public:
 	void* NewVersion(version_t version) const;
 	void Restore() const;
 };
+
+void SDL_DetectPalette(SDL_Palette*, SDL_bool*, SDL_bool*);
+SDL_Texture* SDL_UpdateTextureFromSurface(SDL_Renderer*, SDL_Texture*, SDL_Surface*);
 #endif
 
 }
```
</details>

**Comment by bradallred** [comment]
the easiest fix (also the most performant fix) is probably to just not share palettes between these sprites (are these ground piles?). this kind of thrashing will happen when we change a palette for one sprite and then a different sprite using the same palette needs another change and they just keep fighting each other.

`SDL_UpdateTexture` won't work. all textures are 32bit and we have no idea what values to change (the conversion process is imperfect and depends on many things) and searching for what to change would be expensive anyway. its completely not needed tho if every sprite uses its own palette.

**Comment by bradallred** [comment]
have you tried with the latest SDL2 trunk out of curiosity?

**Comment by MarcelHB** [comment]
Yes, there was no difference to the release version.

**Comment by bradallred** [comment]
I would look at `SDLVideoDriver::BlitSpriteClipped` and fix the clipping to work on SDL2 so that we aren't calling `SDLVideoDriver::RenderSpriteVersion` for off screen sprites, That would help a ton.

**Comment by bradallred** [comment]
I've enabled offscreen culling for SDL2. No idea how much it will help as I do not experience a problem myself.

We should probably narrow down the specific culprits and assess the situation from there. Still of the opinion shared palettes are most likely at fault and could be easily corrected. We will have to see.

**Comment by MarcelHB** [comment]
I'd say I gained 1fps here, so no salvation.

**Comment by bradallred** [comment]
want to try changing `SDLSurfaceSprite2D::SetPalette` so that it copies the `Palette`?

`palette = pal;` -> `palette = pal->Copy();` should do it (along with deleting the `acquire`).

**Comment by MarcelHB** [comment]
That's much better.

**Comment by bradallred** [comment]
like fixed better? or still kind of laggy?

I'd be curious to know if you can pinpoint what sprites are at fault.

**Comment by MarcelHB** [comment]
I haven't removed the frame lock, but so it was back at 30fps with no notable frame drop or obviously visual bugs.

The sprites around font rendering should be easily narrowed down, right? I refer to hovering the dialog answers, like when they turn from red to white in BG2, that also hit the performance. Not sure what to look for specifically in IWD2, so I guess we had to build some kind of histogram for named sprites and look at what peaks at calling `SetPalette`?

**Comment by bradallred** [comment]
font rendering only uses a few gigantic sprites (something like 1024x1024) so I doubt they are the primary culprit.

we do know that font rendering can be slow (#233) but if that were the main bottleneck it would have been apparent the entire time. Fonts also don't share palettes with anything else so the copy wouldn't have fixed it. As you noted you still lag out when hovering the dialog options and that would be why. We will address #232 and #233 shortly after merging this branch and the font rendering will be super fast then.

I suspect something with actors or area animations myself, but I suppose it's not important since the copy fixes it. It wouldn't be a call to `SetPalette` since that is likely only called once per sprite, but a breakpoint on that `Restore` call and keeping count of which sprites are thrashing on the same palette would be the way to figure it out. Since you say performance is back to expected levels I wouldn't worry about it now.

**Comment by MarcelHB** [comment]
This fixes both observations, i. e. a generally slow IWD2, and framedrops in the dialogs.
