### ISSUE TITLE
Can't make close move 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#900]
#### Bug description
You can't move to a near point even to make action like lock picking, certainly related to path finding ?

GemRB version: los-slim-check

#### Steps to reproduce
Try to move next to actual location

#### Expected behavior
Character move as asked and go enough close to perform asked action.

#### Video
[not_close_enough-2020-08-08_14.58.35.zip](https://github.com/gemrb/gemrb/files/5045268/not_close_enough-2020-08-08_14.58.35.zip)

**Comment by lynxlynxlynx** [comment]
Can you start making screenshots where video doesn't give any extra info (it rarely does)? And please include the area number.

I have changes from #894 applied, but I don't know if it matters — opening containers and ordering to bash them works whether up close or if it requires a move. The only noticeable thing is that we are now sooner happy to stop trying to get closer.

**Comment by FrElvire** [comment]
Position: ar6012 [623.223]

Yes I have these changes applied ( los-slim-check, commit ef8cfac).

I will do a test without.

**Comment by lynxlynxlynx** [comment]
Ok, I can reproduce it, only lockpicking itself makes it obvious.
![image](https://user-images.githubusercontent.com/121515/89712315-61599400-d990-11ea-951a-b432bb7c8c5c.png)
You can't move that one block closer to the cupboard (NE) and I guess we're outside the operating range.

**Comment by FrElvire** [comment]
With last commit from master it's ok.

**Comment by FrElvire** [comment]
you can go where you want even if it's very close from current location.

**Comment by lynxlynxlynx** [comment]
cc @kmfrick

**Comment by kmfrick** [comment]
Prompted a simplification that fixed this, so now the epsilons are only used once. I tested bg1 (thieves' maze), bg2 (starting area), iwd2 (starting area) and pst (mortuary) and found no oscillation near the goalpoint, but maybe I was just too lucky.

**Comment by FrElvire** [comment]
All seems OK for this bug with latest commit from PR #894
