### ISSUE TITLE
[TOB] Draconis AI (dragon form at least)

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#905]
#### Bug description
Like us, Draconis can't control more than 5 creatures, but but he continues to invoke them without stopping

I'm really not sure it has to do with gemrb (to say the least) but if it is...

GemRB version: kmfrick:los-slim-check

#### Steps to reproduce
1. load save
2. look a text windows

#### Expected behavior
Not doing useless thing

#### Screenshots
![draco_summon](https://user-images.githubusercontent.com/55502325/90308669-9d857b00-dee1-11ea-8bc5-3aa1e2a60a57.png)

#### Save
[000000037-draconis battle 1.zip](https://github.com/gemrb/gemrb/files/5078386/000000037-draconis.battle.1.zip)

**Comment by lynxlynxlynx** [comment]
AI is not limited to this; think of the ravager fight. But anyway, there's no way to count this with scripts. He also summons them in a way that doesn't require spell memorization.
