### ISSUE TITLE
[bug] tob hell challenge ogre mages are invisible too much

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#91]
**Describe the bug**
The first challenge in the pocket plane, if you're of good alignment, sees you fighting ogre mages (**chevil03.cre**, spawned simply by the area script of ar4500) in the second half. They turn invisible by script all the time, so they're almost impossible to kill.

They have a ring of permanent invisibility on, but also the **ogmagi01**.bcs has this broken block (nothing sets the timer):

```
IF
	!StateCheck(Myself,STATE_INVISIBLE)
	!GlobalTimerNotExpired("Invis","LOCALS")
THEN
	RESPONSE #100
		ApplySpell(Myself,WIZARD_INVISIBILITY)  // SPWI206.SPL (Invisibility)
END
```
Either thing by itself is problematic and together only worse. Should equipped effect application be delayed? Which of the two is the actual source of invisibility in the original?

https://youtu.be/pJJoDLfZ1gM?t=716 the original does cope with this bs.

**Comment by cygarniczka** [comment]
Removing above mentioned block of the script in OGMAGI01.BCS makes Ogre Mages no longer invisible as soon as they cast a spell. However when Ogre Mages run out of the spells to cast they disappear from the game completely. After Ogre Mages disappear for good Gavid appears and first challenge is completed without having to battle trio - Sarevok, Bohdi, and Irenicus.

**Comment by cygarniczka** [comment]
Behavior is not the same. When nothing is changed Ogre Mages only appear for a second or less when they finish casting the spell regardless how long it takes to cast a spell.

Edit to OGMAGI01.BCS - Ogre Mages are no longer invisible after casting the first spell

Removal of MAGE01.ITM - Ogre Mages become invisible after they cast a spell. During casting the spell they are visible. Some spells require more time to cast.
