### ISSUE TITLE
Evaluate the use of rr 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#913]
Basically it provides proper reversing of execution (unfortunately only on linux):
https://rr-project.org/

So if we used this more commonly, hard to reproduce bugs would suddenly lose their "hard to reproduce" property.

It's not something to put into our build system, it's just an option to shortly document in the [contributor guidelines](CONTRIBUTING.md) and/or dev docs on the website.

**Comment by MarcelHB** [comment]
I gave it a shot. Besides requiring some preparations depending on the machine (like [this](https://github.com/rr-debugger/rr/wiki/Building-And-Installing#os-configuration) and [that](https://github.com/rr-debugger/rr/wiki/Zen)), one major drawback is the lack of OpenGL support. So one must not use `-DUSE_OPENGL=1`, and then SDL falls back to software, and this isn't in a particularly [good state](https://github.com/gemrb/gemrb/pull/1776#issuecomment-1382891168) for us.

**Comment by lynxlynxlynx** [comment]
Added a tiny note to the end of the dev docs.
