### ISSUE TITLE
Error starting latest binary on ubuntu 18.04 

### ISSUE THREAD

**Issue by rsantellan** [gemrb/gemrb#914]
#### Bug description
 Can't start latest binary on ubuntu 18.04

GemRB version: 0.8.7

#### Steps to reproduce
1. Dowload latest binary from webpage
2. Open on ubuntu 18.04

#### Expected behavior
Program starts

#### Screenshots
`
:~/games/gemrb-0.8.7$ ./gemrb 
./gemrb: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
`

Trying to compile it:
`
:~/games/gemrb/build$ cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detected version: 0.8.7-git
-- Git version bool: 1
-- Performing Test NO_STRINGOP_TRUNCATION
-- Performing Test NO_STRINGOP_TRUNCATION - Failed
-- Performing Test VISIBILITY_HIDDEN
-- Performing Test VISIBILITY_HIDDEN - Success
-- Performing Test STACK_PROTECTOR
-- Performing Test STACK_PROTECTOR - Success
-- Performing Test FALLTHROUGH
-- Performing Test FALLTHROUGH - Success
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PythonLibs (missing: PYTHON_LIBRARIES PYTHON_INCLUDE_DIRS)
  (Required is at least version "2.3")
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindPythonLibs.cmake:262 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:234 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "~/games/gemrb/build/CMakeFiles/CMakeOutput.log".
See also "~/games/gemrb/build/CMakeFiles/CMakeError.log".
`

**Comment by lynxlynxlynx** [comment]
You either need libpng12 installed or all the dependencies required for compilation*. But since you're on ubuntu, you can shortcircuit it by grabbing the packages from this list: https://github.com/gemrb/gemrb/blob/master/.travis.yml#L12


*https://github.com/gemrb/gemrb/blob/master/INSTALL

**Comment by lynxlynxlynx** [comment]
The currently building build is using bionic as a base. You can also try that binary once it's done.

**Comment by rsantellan** [comment]
> You either need libpng12 installed or all the dependencies required for compilation*. But since you're on ubuntu, you can shortcircuit it by grabbing the packages from this list: https://github.com/gemrb/gemrb/blob/master/.travis.yml#L12
> 
> *https://github.com/gemrb/gemrb/blob/master/INSTALL

Using the travis file:

```
~/games/gemrb/build$ sudo apt install cmake     libpython2.7     zlib1g     zlib1g-dev     libsdl1.2debian     libsdl1.2-dev     libopenal1     libopenal-dev     libsdl-mixer1.2     libsdl-mixer1.2-dev     libfreetype6     libfreetype6-dev     libvlc-dev     libvlccore-dev     libpng12-0      libpng12-dev     libvorbis0a     libvorbis-dev     openssh-client    python-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libpng12-0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libpng12-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libpng12-0' has no installation candidate
E: Package 'libpng12-dev' has no installation candidate
```
@lynxlynxlynx where is the build link ?

Regards

**Comment by lynxlynxlynx** [comment]
Well obviously if you don't want to grab libpng12, grab the newer version. libpng16-dev will pull in both required packages.

Builds:
https://gemrb.org/Install.html

**Comment by rsantellan** [comment]
> Well obviously if you don't want to grab libpng12, grab the newer version. libpng-dev will pull in both required packages.
> 
> Builds:
> https://gemrb.org/Install.html

Installing that library I was able to run it.
Thanks
