### ISSUE TITLE
Unplayable at low resolutions 

### ISSUE THREAD

**Issue by escalade** [gemrb/gemrb#920]
Not sure if this classifies as a bug, but I'm trying to get Planescape Torment running on an Odroid Go Advance which has a 480x320 screen. It seems the GUI doesn't downscale at all, as I can't get past the menus due to buttons being out of the visible range of the screen. Any workaround for this? Tested on GemRB 0.8.7.

**Comment by lynxlynxlynx** [comment]
Not really, the game files support only 640x480. The dingux port added a downscaler, so things could run at 320x240, but that was never included as a feature and would still leave half your screen empty. And pst is so full of text I can't imagine playing being enjoyable. And we don't support joysticks yet, so you'd have to hardcode some buttons first ... Sorry, even with some coding it's not really viable.

**Comment by escalade** [comment]
I had already mapped mouse and keyboard shortcuts with AntimicroX, so in theory the game would be fully playable. It's amazing what bilinear filters, shaders etc. can do to a downscaled picture, but in any case I understand if it's not a priority for the project. Hopefully someone creates a libretro port in the future :)

**Comment by bradallred** [comment]
after subviews is merged we could probably easily implement downscaling since SDL 2 is hardware accelerated.

**Comment by lynxlynxlynx** [comment]
libretro could help with input stuff, but at the end of the day, that's a painfully small screen that doesn't even match the aspect ratio, so it would look stretched — unless we also added padding support — or have to be even smaller than the screen size.
