### ISSUE TITLE
[subviews] can't make a new save

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#927]
#### Bug description
When opening save window, save button are greyed, you can't write anything and you don't see any of existing saves.

This is the error in console :

[ResourceManager]: Found 'guisrsvb.mos' in 'Cache'.
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "/usr/share/gemrb/GUIScripts/GUIOPT.py", line 479, in OpenSaveMsgWindow
[Python/ERROR]:     GUISAVE.OpenSaveWindow ()
[Python/ERROR]:   File "/usr/share/gemrb/GUIScripts/GUISAVE.py", line 95, in OpenSaveWindow
[Python/ERROR]:     GUICommon.SetSaveDir ()
[Python/ERROR]: NameError: global name 'GUICommon' is not defined
[ResourceManager]: Searching for 'A_LTHR4'...

and there are many of thieses errors too : [ScrollView/ERROR]: Unable to add scrollbars: missing default scrollbar template

Quick save is OK, Concern all games, only in subviews branch

#### Screenshots
![image](https://user-images.githubusercontent.com/55502325/91800036-92905180-ec28-11ea-874c-8e8753f329c2.png)

**Comment by lynxlynxlynx** [comment]
Yeah, it's missing an include. I'm 95 % sure the branch just needs to be synced with master again for this to go away.
