### ISSUE TITLE
[IWD1] Option button greyed at game start

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#928]
#### Bug description
When launching a new game, you can't open option window, it's greyed. 

NB : keyboard shortcut works 

GemRB version: master

#### Steps to reproduce
1. start a new game
2. create or import one or more character
3. option window is greyed

#### Expected behavior
Option window not greyed

#### Screenshots
![image](https://user-images.githubusercontent.com/55502325/91885143-8f787e00-ec87-11ea-9f82-789f37c0c335.png)

**Comment by lynxlynxlynx** [comment]
Quite odd, I could reproduce it with one save from the starting area, but only once. Others were fine. It's as if sometimes the count goes wrong — it's the next icon that should be disabled.

**Comment by FrElvire** [comment]
I fear I can still reproduce the bug, not always but about half of time when starting a new game.

**Comment by FrElvire** [comment]
Sorry I just realize that egit commit number was hardcoded so always compile an old version. Yes it seems ok, sorry for wasting your time :(
