### ISSUE TITLE
Fog of war with snow falling on it

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#929]
#### Bug description
You can see snow falling even if area is not discovered. Doesn't seem normal to see snow falling but just that

GemRB version: master 
OK with subviews or snow is not falling anywhere on the area.

#### Steps to reproduce
1. browse the area with cursor and you can see snow falling (if there's snow...)

#### Expected behavior
You can't see snow if you can't see the field

#### Screenshots
![image](https://user-images.githubusercontent.com/55502325/91886229-4fb29600-ec89-11ea-93ec-1629cae0d61d.png)

**Comment by bradallred** [comment]
Am I to assume this behavior differs from the originals?

**Comment by FrElvire** [comment]
I will certainly try to check tomorrow

**Comment by lynxlynxlynx** [comment]
Related #210.

**Comment by FrElvire** [comment]
So it's a duplicate, can be closed ?

**Comment by lynxlynxlynx** [comment]
No.

**Comment by bradallred** [comment]
Here is the offending code (in subviews at least)

```
bool update_scripts = !(DialogueFlags & DF_FREEZE_SCRIPTS);
area->DrawMap(Viewport(), DebugFlags);
game->DrawWeather(screen, update_scripts);
```

we just need to move the weather drawing into `DrawMap` which is what is drawing the fog. seems like a better place for it anyway.
