### ISSUE TITLE
[IWD1] Some game options are not selectable

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#930]
#### Bug description
Some options in IWD1 are not selectable. 

In the screenshots below here are all the options that can be selected (when there is no screenshot, all options can be selected)

GemRB version: master

#### Expected behavior
You can select all options

#### Screenshots
![image](https://user-images.githubusercontent.com/55502325/91886636-e97a4300-ec89-11ea-99c2-c03dd471191e.png)
![image](https://user-images.githubusercontent.com/55502325/91886682-feef6d00-ec89-11ea-8b6e-44262bcab8ed.png)
![image](https://user-images.githubusercontent.com/55502325/91886744-14fd2d80-ec8a-11ea-958f-563423653049.png)

**Comment by lynxlynxlynx** [comment]
Screenshot:
- 1: the two options are not relevant, so not implemented; still, we can make them togglable to give the users a more sensible illusion
- 2: should be fixed
- 3: should be fixed

These work in bg2, so maybe we are just too strict with game checks. It's all in GUIOPT.py.

**Comment by gregariousmonk** [comment]
iwd1 autopause options issue #1815 is a duplicate issue for a single part of this issue.  May need to do some further review game type checks in GUIOPT.py.
