### ISSUE TITLE
[subviews] MTA missing horizontal padding

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#931]
![image](https://user-images.githubusercontent.com/121515/91894862-9955ad80-ec96-11ea-8f8c-70be95f53715.png)
original looks like 2px: http://speed-new.com/wp-content/uploads/2015/08/24565362546464456.jpg

It looks fine on master, where we likely hardcoded it. Vertically it looks ok, since the control is not full height wrt the MOS bg.

**Comment by bradallred** [comment]
Is this really IWD2 only? we aren't setting margins at all for anything. We can just hard code it in `CHUImporter` if it applied universally.

**Comment by lynxlynxlynx** [comment]
it's definitely not needed in bg2.

**Comment by bradallred** [comment]
I'm not sure what to think since in master we also use the same margins for everything. are they too much in BG2 on master?

**Comment by lynxlynxlynx** [comment]
Master matches the original perfectly, while subviews has a a few pixels less of left padding/margin and looks like a px from the top.
