### ISSUE TITLE
[subviews] sdl1 non-TA scrolling too fast

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#934]
I noticed there is a closely related problem on SDL1 to #755, but not in general. It's only visible in load/save screens and probably other places that aren't text areas. It's fine on SDL2, but here, we scroll 4 items at once in iwd2, 8 in bg2 ... The first is kind of ok, since it basically does a page up/down, but the bg2 case makes you think you have fewer saves. 

On master we scroll per-item, which is more natural. The fix for #755 (9dc7ed6b9) was applied only to SDL2 for obvious reasons. I don't see us doing anything special for those scrollbars and since the speed is 12px, I have trouble explaining even the current behaviour. Ideas?

**Comment by bradallred** [comment]
It's good that we have everything normalized to "pixels" for the lowest common denominator. Its not a problem to require "pixel" devices to have to scroll more to achieve an "event" for the save lists so it seems like we need some sort of scalar variable.

We could do something as simple as add `isPerPixelScrolling` to `View` and default it as `false` and let `TextArea` and `ScrollView` override it. `ScrollBar` is actually never per-pixel, the `TextArea` just sets the value range to the number of pixels. We then just have to divide incoming scroll wheel events by `core->GetMouseScrollSpeed()` when `isPerPixelScrolling` is `false`

**Comment by lynxlynxlynx** [comment]
I retested and partially retract my statement about SDL2 being fine — it works already for scrolling up, but not down!?

**Comment by bradallred** [comment]
this works for me on both SDL 1 and 2 with both a "regular" mouse and my trackpad. let me know if it doesnt work as expected for you.
