### ISSUE TITLE
[iwd1] spell add/remove effect remain 

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#940]
In IWD1 (not bg2) when adding or removing a spell there is an effect which should vanish after the add/remove but stay displayed. You can see it on center of the spell icon in screenshot.

GemRB version: master

#### Steps to reproduce
1. add or remove a spell

#### Expected behavior
spell effect should vanish after being played 

#### Screenshots
![effect_stay_displayed](https://user-images.githubusercontent.com/55502325/93669944-ae547e00-fa97-11ea-83ef-ee8b692bd2e8.png)

**Comment by lynxlynxlynx** [comment]
It depends on the pause setting. If
- unpaused: only remains for one slot when removing
- paused: like in the pic

The underlying problem, if we don't want to refresh too often, is that the flash animation doesn't end with an empty frame. Perhaps it would be enough to add another param to SetAnimation and implement PlayOnce also for ControlAnimations.

**Comment by FrElvire** [comment]
I can still reproduce part of this bug in iwd1 (game is always paused, no choice, when entering spell book) : 
- on adding spell it seems ok
- on removing ok only if another spell is taking the slot ( you don't remove the last spell)
- if you remove the last spell, effect stay

![spell_effect](https://user-images.githubusercontent.com/55502325/94359833-8f627700-00a9-11eb-96e4-0746639b2a6c.png)

**Comment by fizzet** [comment]
Do you see this on master? I cannot reproduce it.

**Comment by FrElvire** [comment]
Sorry I just realize that egit commit number was hardcoded so always compile an old version. Yes it's ok, sorry for wasting your time :(
