### ISSUE TITLE
Dragging out of the main window 

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#944]
Balrog redid the move-viewport-by-drag in #919, but we already had it done properly in the subviews branch. One nice thing that is salvageable is the use of `SDL_CaptureMouse` to enable drags out of the window to continue propagating to us. A usability improvement. Or in the words from the commit: _Captures the mouse so that mouse movement and interaction is tracked even if out of the game window_.

I'm not sure at what level this is best done. For all drag ops? At which level of the stack?

**Comment by bradallred** [comment]
I'm not sure if this is the best approach, or if it would be better to have a new `Window` flag to capture all drags for the `Window`, but for our current purposes either will work.

**Comment by lynxlynxlynx** [comment]
Doesn't work for me, the behaviour didn't change.

**Comment by bradallred** [comment]
yeah, that was silly of me. I changed it to just capture any time we have a mouse button down and release once all buttons are released.

**Comment by lynxlynxlynx** [comment]
That's still not it. It's not about emulating scroll-lock when dragging, but increasing the drag range, so you don't have to reset the mouse that much:

> Captures the mouse so that mouse movement and interaction is tracked even if out of the game window.

**Comment by bradallred** [comment]
thats exactly what it does for me 🤷 you can see in the code for yourself i'm not calling anything related to scroll-lock

check the result of `SDL_CaptureMouse` and `SDL_GetError`?

**Comment by lynxlynxlynx** [comment]
Eh, didn't notice it's not available before 2.0.4.
