### ISSUE TITLE
 Cursor icon not updated when not moved

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#946]
#### Bug description
I don't know if there are other case to trigger it but when you enter or exit a building by example if you don't move the cursor it doesn't get updated.

GemRB version: master

#### Expected behavior
cursor get updated without having to move it

#### Screenshots
![icon_not_updated](https://user-images.githubusercontent.com/55502325/94359385-38f43900-00a7-11eb-9987-0e7c1ef75f68.png)

**Comment by bradallred** [comment]
I can't check now, but I thought this was not an issue on the subviews branch.

**Comment by bradallred** [comment]
yes, this does seem to work as expected on subviews
