### ISSUE TITLE
[bug] BG2 first level of Irenicus' can't pick up the portal key.  

### ISSUE THREAD

**Issue by Poligraf** [gemrb/gemrb#949]
#### Bug description
This bug was fixed in a previous version, but it appears that it has cropped back up again.

I am playing on linux 0.87 with the binary provided from the website. 

Console log states [GUIScript]: Cannot move item, it is undroppable!

No changes made to config or mods installed except point to the game folder

GemRB version: 0.87 linux

#### Steps to reproduce
1. Go to level 1 and try to pick up portal key. You can not seem to do it.

#### Expected behavior
Pick up portal key.

**Comment by lynxlynxlynx** [comment]
Do you have the bg2 fixpack installed? This is what the release was tested with.

**Comment by Poligraf** [comment]
No I am not running the fixpack, so far its giving me an error that it can not find the directory even though the chitin.key is in the same path. 

Unsure why, as of yet. Will report back when I have installed the pack.

**Comment by lynxlynxlynx** [comment]
You will have to restart the game or it won't change anything in the first area in your save. You can just ctrl-j jump imoen to the chest to test though.

**Comment by Poligraf** [comment]
Fixpack  verified and sorts the issue

**Comment by Poligraf** [comment]
Do I have to restart the game for the rest of the changes to take effect? 
I have copied the key using cheats, so I should be good to go

**Comment by lynxlynxlynx** [comment]
No, the other areas should be fine.
