### ISSUE TITLE
IWD: Pathing problems in AR8011 

### ISSUE THREAD

**Issue by fizzet** [gemrb/gemrb#952]
#### Bug description

The new pathfinder apparently has problem with bigger actors. It's pretty obvious generally if you move through this level, as most of the elementals present won't be able to approach the group or attack properly.

The fire giant at 800/1410 shows this problem as well since his script starts a cutscene and then moves him towards the group. If you approach him from the east that works about half the time in my tests. When it doesn't, the cutscene simply hangs.

**Comment by lynxlynxlynx** [comment]
We were testing mostly with dragons, so it's unexpected that something smaller would have problems. 
I have to reinstall my iwd, but a few things come to mind immediately:
- are their circle sizes correct?
  - if so, perhaps we're constructing too big patches to block on the searchmap
- does he get stuck because of a narrow search map or something else? Anything interesting in the log?

**Comment by fizzet** [comment]
Log output differs. Sometimes I get spammed with:

`[FindPath/DEBUG]: s = (1060, 1397), d = (1221, 1404), caller = Feuerriese, dist = 0, size = 4`

but I sometimes also get

`FindPath/DEBUG]: Feuerriese can't fit in destination`

There are somewhat similar problems when moving towards big enemies. If I order the whole party to attack a big foe, at least some party members will stop short of the enemy and not attack. Others might circle around him to the opposite side before attacking.

**Comment by lynxlynxlynx** [comment]
The circling back was noticed before and we decided to treat it as a feature. Dragon bias. :)

Actors should definitely not stop short though. Perhaps its hitting the simplistic weapon range calculation we use. We just multiply by 10, but it's probably a proper range like everything else, taking perspective into account (so the correct factor is between 12-16).

@kmfrick any thoughts? Can you try the area yourself?

**Comment by kmfrick** [comment]
Ground circles look okay, trying to reproduce stopping short right now.

**Comment by fizzet** [comment]
No. Just approaching that giant should do it. I can provide a save if necessary.

**Comment by kmfrick** [comment]
Are you referring to the scripted dialogue with the elf woman? Because if it's that, I can't reproduce it getting stuck - but will try harder - and if it's not, then I can't get the cutscene to trigger. In any case, a save would be really helpful, thank you!!

**Comment by fizzet** [comment]
No, it's not about the elf, it's about the fire giant I mentioned above.

Here's a save (IWD + HoW). Just move the party a bit to the southwest. Chances for a hang-up are higher if you stay south of the rails.
[how-pathfind-save.zip](https://github.com/gemrb/gemrb/files/5321437/how-pathfind-save.zip)

**Comment by lynxlynxlynx** [comment]
Perhaps the same thing: I hit an looping abandonment issue at the start of ar3301 (testing #954):
![image](https://user-images.githubusercontent.com/121515/95008559-3f406300-061b-11eb-9d40-38f50677fc38.png)

Two odd things: debug overlay doesn't show him as blocking and there appears to be enough space for his circle size.

**Comment by lynxlynxlynx** [comment]
The range thing was mostly a dud, since only one trigger had it wrong, the rest was already converted.

**Comment by kmfrick** [comment]
@fizzet #967 seems to fix both cutscenes and actors stopping short of a big enemy, can you confirm?
@lynxlynxlynx how do I go about testing your abandonment? I tried to mta and all skeletons seem to be blocking and able to attack.

**Comment by lynxlynxlynx** [comment]
Works fine now, can't reproduce any more. :)

**Comment by fizzet** [comment]
I can't seem to reproduce the hanging cutscene any more, so I'm closing this issue, thanks. Stopping short seems better, but not completely fixed. I often still have one or two party members abandon their path before reaching their target. That's probably not related to the target size, though, as it also happens with smaller targets.
