### ISSUE TITLE
[iwd1]portrait not always updated after heal or levelup

### ISSUE THREAD

**Issue by FrElvire** [gemrb/gemrb#953]
#### Bug description
When you heal a character, portrait is not updated with regained life, going to inventory by example make the update
When character gain a level it's often the same ('+' not displayed)

A strange thing : after healing going to map window update the character portrait, but when you close map window, portrait return to non updated state

GemRB version: master

#### Steps to reproduce
1. heal a character or gain a level
2. portrait not updated

#### Expected behavior
portrait updated

#### Screenshots
Not updated after heal
![heal_not_displayed](https://user-images.githubusercontent.com/55502325/94992958-dd85e780-058d-11eb-8dcd-5623f1a6914b.png)

temporary updated on map window
![map_heal_displayed_tmp](https://user-images.githubusercontent.com/55502325/94992975-f4c4d500-058d-11eb-94ac-d45697a35495.png)

**Comment by lynxlynxlynx** [comment]
This should be fine on subviews, since it uses only one portrait window.
