### ISSUE TITLE
Figure out a cleaner way to get subclasses from Scriptables

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#965]
It's a long-standing issue, but kmfrick reminded me of it and now I remembered to note it down. :)

Our code has tons of Scriptable Type checks followed by casts and null checks. An example:
https://github.com/gemrb/gemrb/blob/b787a59f6d25951361d5c0ebef09cc1043d842ce/gemrb/core/GameScript/Actions.cpp#L1133-L1137

 At minimum we could have GetAsActor ... GetAsDoor getters to centralize the casting and avoid the need for many of the type checks (just returning nullptr if it doesn't match).

Any other ideas?

**Comment by bradallred** [comment]
the solution I used in the subviews branch for the many subclasses of `View` from a `PyObject` is:

```
template <class RETURN>
static RETURN* GetView(PyObject* obj) {
	return dynamic_cast<RETURN*>(GetView(GetScriptingRef(obj)));
}

TextArea* ta = GetView<TextArea>(obj);
```

you can do something similar:
```
template <class RETURN>
static RETURN* CastScriptable(Scriptable* obj) {
	// dynamic_cast will return nullptr if the cast is invalid
	return dynamic_cast<RETURN*>(obj);
	// alternatively use a switch if dynamic_cast is too slow:
	switch (obj->Type) {
		...
	}
}

Actor* actor = CastScriptable<Actor>(scriptable);
```

**Comment by bradallred** [comment]
It is possible some cases of this would be best served by C++ virtual method dispatch. It looks like `SetBase` is one of biggest culprits, so you could just implement `Scriptable::SetBase(params)`

then code like this:
```
if (!scr || scr->Type != ST_ACTOR) {
	return;
}
Actor* actor = ( Actor* ) scr;
actor->SetBase( IE_EA, parameters->int0Parameter );
```

becomes simply:
```
scr->SetBase( IE_EA, parameters->int0Parameter );
```

**Comment by bradallred** [comment]
yet another possibility since a cursory glance reveals this happens a lot in `GameScript`

there are many, many implementations like this:
```
int GameScript::ClassLevelLT(Scriptable* Sender, Trigger* parameters)
{
	Scriptable* tar = GetActorFromObject( Sender, parameters->objectParameter );
	if (!tar) {
		return 0;
	}
	if (tar->Type != ST_ACTOR) {
		return 0;
	}
	Actor* actor = ( Actor* ) tar;
	return actor->GetLevelInClass(parameters->int0Parameter) < (unsigned) parameters->int1Parameter;
}
```

which can be all done similar to this:
```
int GameScript::ClassLevelLT(Scriptable* Sender, Trigger* parameters)
{
	return InvokeSenderWithParameters<Actor, 0>(Sender, GetLevelInClass, parameters->int0Parameter) < (unsigned) parameters->int1Parameter;
}
```

where `InvokeSenderWithParameters` is something along these lines:
```
// all GameScript functions return an int
template<ScriptableType SCRIPTABLE_TYPE, int DEFAULT, typename ...ARGS>
int InvokeSenderWithParameters(Scriptable* scriptable, int(*method)(Scriptable*, ARGS...), ARGS&&... args)
{
	if (scriptable ->Type == SCRIPTABLE_TYPE) {
		return method(scriptable, std::forward<ARGS>(args)...);
	}
	return DEFAULT;
}
```

**Comment by bradallred** [comment]
Also, why does `GetActorFromObject` _not_ return an `Actor`?

**Comment by lynxlynxlynx** [comment]
We need this everywhere, so let's not start with something GameScript specific. Things like InvokeSenderWithParameters would also make debugging harder.

GetActorFromObject just has a bad name, probably for historic reasons; the object parameter can refer to doors, travel regions, containers and more.

I don't think this is performance critical, so the dynamic_cast version of the template should do. With some shorter name to make the inline uses more pleasant (As?).
