### ISSUE TITLE
[subviews] mouse speed degrades in some windows

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#977]
Start bg2, notice the mouse speed. Click options, still fine. Click gameplay and the pointer speed slows down / starts lagging.

It's the first modal one, so it could be related (also seen ingame), but I couldn't reproduce it with other modals in bg1.

**Comment by lynxlynxlynx** [comment]
With FPS on, it's clear: it drops from the capped 30 to 9.5 in that window, even with the mouse not moving. Is SDL1 that worse at drawing the modal shadow?

**Comment by bradallred** [comment]
try it now. SDL 1 has always yielded terrible performance for me so its really hard to tell

**Comment by lynxlynxlynx** [comment]
Improved by 3 FPS, so it's still not like master. Any other ideas?

**Comment by bradallred** [comment]
assuming you've already determined that the modal shadow is the problem and assuming you have tried a fully optimized build the options quickly devolve into ugly hacks...

**Comment by lynxlynxlynx** [comment]
It's around 22 FPS on a release build. And yeah, commenting out the ShowModal call maxes it out.

**Comment by bradallred** [comment]
is that any better?

**Comment by lynxlynxlynx** [comment]
Yeah, goes to 27. Good enough.

**Comment by bradallred** [comment]
I think I thought of a better fix if you want to try that

**Comment by lynxlynxlynx** [comment]
Maxes out now, nice. :)
