### ISSUE TITLE
[bug] [bg2] [bgt] Ranged Weapons have reduced reach

### ISSUE THREAD

**Issue by cygarniczka** [gemrb/gemrb#98]
**Describe the bug**
All ranged weapons except the long bows and crossbows have reduced range in GemRB i.e. short bows, darts, slings, thrown daggers, axes, hammers (mod), thrown spiritual hammer priest spell lvl 2 (mod), Melf's Minute Meteor ( lvl 3 spell), Melf's Explosive Meteors lvl 5 wizard spell (mod DSotSC me thinks). I prepared spreadsheat with table listing vanilla and gemrb distances for each ranged weapon.

GemRB version: 

**To Reproduce**
You only need to install DSotSC for melf's explosives meteors and Thrown Hammers from Spellhold Studios.  

**Expected behavior**
If you compare e.g. sling bullet thrown distance in GemRB and vanilla engine you will notice that on GemRB engine the distance is significantly reduced. 

Weapon Name | Vanilla Pixels | GemRB Pixels | Feet/Yards Range
------------ | -------------|------------ | -------------
Heavy Crossbow| 430.3| 430.6| 100 ft
Light Crossbow| 430.5| 430.6| 100 ft
Composite Bow| 430.5| 444.5| 100 ft
Long Bow| 430.6| 430.3| 100 ft
Short Composite Bow*| 430.1| 430.8| 100 ft
Short Bow| 430.0| 337.2| 75 ft
Sling| 430.1| 232.5| 40 ft
Dart| 249.3| 92.7| 15 ft
Thrown Axe| 245.5| 93.6| 15 ft
Thrown Hammer*| 245.7| 89.2| 15 ft
Thrown Spiritual Hammer*| 249.2| 84.2| 15 ft
Thrown Dagger| 245.3| 93.6| 15 ft
Melf's Minute Meteors| 238.6| 97.1| 70 yards
Melf's Explosive Meteors*| 233.1| 96.7| Range: Caster Only [that's what spell description says]
Dark Bolt*| 265.0 | 90.8| Range (feet): 1  [that's what NearInfnity effects field show]

Starred* weapons are from the mods.
Thrown Hammers mod here: http://www.shsforums.net/files/file/654-thrown-hammers/
Melf's Explosive Meteors from DSotSC v3.0 beta here: https://github.com/K4thos/DSotSC
Short Composite Bow from Rogue Rebalancing component extra equipment for thieves and bards here: http://www.shsforums.net/files/file/952-rogue-rebalancing-mod-platform-independent/
Dark Bolt - Divine Remix v8 beta https://www.gibberlings3.net/mods/kits/cleric/

**Comment by lynxlynxlynx** [comment]
If you can, please double check normal short bows — that result really stands out.

**Comment by cygarniczka** [comment]
GemRB Short Bow Distance:
![gemrb short bow](https://user-images.githubusercontent.com/17316115/52185344-b8efd000-27ec-11e9-8010-58cd1007461e.jpg)
![gemrb short bow 326 7 pixels](https://user-images.githubusercontent.com/17316115/52185345-b8efd000-27ec-11e9-80e5-a8733b269288.jpg)
Vanilla Short Bow Distance: 
![vanilla short bow reach](https://user-images.githubusercontent.com/17316115/52185354-d02ebd80-27ec-11e9-878d-7b979cd324c0.jpg)
![vanilla short bow 425 7](https://user-images.githubusercontent.com/17316115/52185355-d02ebd80-27ec-11e9-98ea-d95ea1e3b72e.jpg)

**Comment by lynxlynxlynx** [comment]
It's probably item type based, so all bows end up in the same category. Lame. Please also test the difference with the Gesen bow (bow19), since it has a range of 150 set. To drive to point fully, then also try  with any bow where you modify the range to let's say 10. Preferably with the same saves and positions/targets as before.

**Comment by cygarniczka** [comment]
Gesen:
426.0 
425.0 
424.6

Regular:
424.1 
424.1
423.1

Clearly they have same range despite what NI data may show.

**Comment by lynxlynxlynx** [comment]
This is now handled, closing.
