### ISSUE TITLE
[BG1] Dialog options get skipped 

### ISSUE THREAD

**Issue by neula** [gemrb/gemrb#989]
#### Bug description
Found in BG1. 
In some dialogues, dialog options aren't displayed. The first dialog option is chosen automatically,
if the player clicks on the "End Dialog" button.

This was introduced with 67c1d53a29797d0e5a3534ff36d60d1c2ba6d9e0
GemRB version: any greater than 67c1d53a29797d0e5a3534ff36d60d1c2ba6d9e0

#### Steps to reproduce with the provided save game
1. Wait for flaming fist officer to talk to you
2. Get arrested immediately.

#### Expected behaviour
Get multiple dialog options to choose from

#### Screenshots
![bg_no_dialog](https://user-images.githubusercontent.com/11018418/96124361-bfa47500-0ef3-11eb-808e-cecf3087aa7e.png)

#### Savegame
[000000001-no-dialog.tar.gz](https://github.com/gemrb/gemrb/files/5384870/000000001-no-dialog.tar.gz)

**Comment by lynxlynxlynx** [comment]
Hmm, I guess it should return true and it's not that problematic. Thanks for the detailed report!
