### ISSUE TITLE
[bug] Baldur's gate 1 (GOG version) Battle music won't play.

### ISSUE THREAD

**Issue by tomudo** [gemrb/gemrb#99]
**Describe the bug**
Baldur's gate 1 (GOG version) won't play battle music.

GemRB version: 0.85

**To Reproduce**
Start combat with enemies.

**Expected behavior**
Play battle music like original game

**Comment by cygarniczka** [comment]
Can reproduce the bug.

**Comment by lynxlynxlynx** [comment]
Started investigating and opened a separate bug for candlekeep.

**Comment by lynxlynxlynx** [comment]
This should now be fixed, please open a new report if you find any specific battle music problems.
