### ISSUE TITLE
[subviews] drag cursor should only be shown when truly dragging

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#992]
You can get it even in the start menu:
![image](https://user-images.githubusercontent.com/121515/96352574-68a1ca00-10c4-11eb-92b0-0027ca022fb4.png)

**Comment by bradallred** [comment]
yes, this was a very handy debugging feature im still using to finish this work :)

**Comment by lynxlynxlynx** [comment]
So, is anything still missing for dragging?

**Comment by bradallred** [comment]
yeah, I have a stash I need to resolve still
