### ISSUE TITLE
[subviews] replaying chapter text skips part of it

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb#993]
Testing in bg1, but should affect everyone. Good text gets passed to TextArea_SetChapterText both times, but even though it recreates its text container, the behaviour is not identical. Prepending one row more fixes the replay, but the extra row means the text is not synced with the sound, so that's not the way to go. Fishy, I suspect something in TextArea itself.

**Comment by bradallred** [comment]
I believe that addresses what you were seeing

**Comment by lynxlynxlynx** [comment]
Indeed, thanks.
