### ISSUE TITLE
[subviews] Screen not shaking (IWD2)

### ISSUE THREAD

**Issue by MarcelHB** [gemrb/gemrb#999]
#### Bug description
In IWD2, when you start chapter two and the flying vessel crashed, the first thing is a shaking screen because of rocks falling down. In master, this works. In subviews, it looks like 3-5s nothing is happening until the party suddenly gets unconscious.

#### Steps to reproduce
1. In IWD2, start chapter 2.

#### Expected behavior
After leaving the chapter intro, inside of Oswald's ship, the screen is supposed to shake for a few seconds. Instead, it stays still (only a text indicating something is happening).

**Comment by lynxlynxlynx** [comment]
I guess it uses the ScreenShake action and something broke lower down. Perhaps 7b45aee?

**Comment by bradallred** [comment]
that would make sense if the area is too small for the screen. does a critical hit work still?

**Comment by lynxlynxlynx** [comment]
The area is small, yes, since you're inside of a ship. This is AR4001.

**Comment by MarcelHB** [comment]
Critical hit also keeps the screen still, regardless of where the viewport is.

**Comment by bradallred** [comment]
I was asking if it worked when in an area large enough to actually scroll

**Comment by MarcelHB** [comment]
Yes, I had some battle with 100% CH chance modification at the center of some larger (larger than AR4001) IWD2 map. Works in master, but not in subviews.

**Comment by lynxlynxlynx** [comment]
cheat for easy reproduction (ensures criticals): `sps(146,20)`

**Comment by bradallred** [comment]
that fixes critical for me... hopefully it fixes the cutscene. I'm still unsure of shaking working in small areas.

**Comment by MarcelHB** [comment]
1. The small area shows no screen effects at all so far.
2. Critical hits in larger areas make the screen wobble towards the point of action? Try a fight, move the VP aside and observe the next CH make the VP oscillatingly moving towards the origin (?) again.

**Comment by bradallred** [comment]
change the `center` param for the shake to `true`

**Comment by MarcelHB** [comment]
You mean like this?

```diff
diff --git a/gemrb/core/GlobalTimer.cpp b/gemrb/core/GlobalTimer.cpp
index 8d0a07387..d09bc07d6 100644
--- a/gemrb/core/GlobalTimer.cpp
+++ b/gemrb/core/GlobalTimer.cpp
@@ -138,7 +138,7 @@ void GlobalTimer::DoStep(int count)
 		if (shakeCounter) {
 			p += RandomPoint(0, shakeVec.x - 1, 0, shakeVec.y - 1);
 		}
-		gc->MoveViewportTo(p, false);
+		gc->MoveViewportTo(p, true);
 	} else if (gc->MoveViewportTo(p, false) == false) {
 		goal = Point(-1,-1);
 	}
```
Makes it jump away from the scene.

**Comment by MarcelHB** [comment]
Ok, your latest changes make it move, the shaking pattern just makes the viewport wander away, significantly leaving the screen.
